vitessio/vitess

go/internal/flag/flag.go, go/mysql/collations/integration/collations_test.go, go/mysql/collations/integration/main_test.go, go/mysql/collations/local.go, go/mysql/collations/platform32.go, go/mysql/collations/platform64.go, go/mysql/collations/tools/makecolldata/main.go, go/mysql/collations/tools/makecolldata/mysqldata.go, go/mysql/collations/tools/makecolldata/mysqlversions.go
I decided to migrate the tests/tools as well, just for consistency's sake.
@vmg do you mind checking if you have any other scripts that use `makecolldata` (I did a `git grep` and updated everything I found, but I am not sure if you have a local workflow) still work on this branch? If not, I can back out just those changes and revisit that piece.
- Closes #10963 
- Closes #10964 
- Closes #10965 
=> [cli] [go/mysql/collations/...] Migrate all flags to `pflag`

go/vt/vttest/local_cluster.go
Before, these helper functions explicitly returned the `flag.Value` type,
making it impossible to use with `pflag`. Attempting to do so would
produce compiler errors like:
```
cannot use vttest.JSONTopoData(&tpb) (value of type "flag".Value) as pflag.Value value in argument to pflag.Var: "flag".Value does not implement pflag.Value (missing method Type)
```
Changing the return type to the struct, which _implicitly_ implements both
`flag.Value` and `pflag.Value` allows us to use these function in both old
(`flag`) and new (`pflag`) Var functions.
Closes #10988 
=> [cli] [vttest] Extend vttest.TopoData to implement `pflag.Value`, and make function return types implicit

go/test/fuzzing/tablet_manager_fuzzer.go, go/vt/schemamanager/schemamanager_test.go, go/vt/schemamanager/tablet_executor.go, go/vt/vtcombo/tablet_map.go, go/vt/vtctl/grpcvtctldserver/server.go, go/vt/vtctl/grpcvtctldserver/testutil/test_tmclient.go, go/vt/vtctl/schematools/copy.go, go/vt/vttablet/faketmclient/fake_client.go, go/vt/vttablet/grpctmclient/client.go, go/vt/vttablet/grpctmserver/server.go, go/vt/vttablet/tabletmanager/rpc_agent.go, go/vt/vttablet/tabletmanager/rpc_query.go, go/vt/vttablet/tabletmanager/rpc_query_test.go, go/vt/vttablet/tmclient/rpc_client_api.go, go/vt/vttablet/tmrpctest/test_tm_rpc.go, go/vt/wrangler/materializer.go, go/vt/wrangler/materializer_env_test.go, go/vt/wrangler/resharder_env_test.go, go/vt/wrangler/workflow.go, go/vt/wrangler/wrangler_env_test.go
This unexplodes the method signatures on both the client- and server-sides for:
- `ExecuteQuery`
- `ExecuteFetchAsAllPrivs`
- `ExecuteFetchAsApp`
- `ExecuteFetchAsDba`
=> [tmclient] [tmserver] Unexplode fetchers

go/test/endtoend/vtgate/gen4/gen4_test.go, go/vt/vtgate/engine/filter_test.go, go/vt/vtgate/evalengine/comparisons_test.go, go/vt/vtgate/evalengine/eval_result.go, go/vt/vtgate/evalengine/evalengine.go
Found this while working on some internal stuff. The `evalengine` does not properly handle mismatched numeric types because we were not properly normalizing. E.g. an UINT8(0) would fail to compare equally to an UINT64(0), even though an INT8(0) would actually compare equally to a UINT64(0). This PR fixes this issue by upcasting all comparison types before performing a numeric comparison.
It probably requires a backport. 
cc @systay @deepthi 
=> evalengine: support mismatched numerical types

tools/shell_functions.inc
[Go 1.19](https://tip.golang.org/doc/go1.19) was just released and as reported in https://github.com/vitessio/vitess/issues/11000 it caused builds to fail when installed:
```
ERROR: Go version reported: go version go1.19 linux/amd64. Version 1.18.4+ required. See https://vitess.io/contributing/build-from-source for install instructions.
make: *** [Makefile:85: build] Error 1
```
To demonstrate the new handling added in this PR:
```
$ go version
go version go1.19 darwin/arm64
$ bash -c 'source ./tools/shell_functions.inc && goversion_min || fail "No good"'
$ bash -c 'source ./tools/shell_functions.inc && goversion_min 1 || fail "No good"'
$ bash -c 'source ./tools/shell_functions.inc && goversion_min 2 || fail "No good"'
ERROR: No good
$ bash -c 'source ./tools/shell_functions.inc && …
```
=> Add more robust go version handling

go/test/endtoend/vreplication/cluster_test.go, go/test/endtoend/vreplication/config_test.go, go/test/endtoend/vreplication/resharding_workflows_v2_test.go, go/test/endtoend/vreplication/vdiff2_test.go, go/test/endtoend/vreplication/vreplication_test.go
When the host machine had a different major version of MySQL
installed in the standard location than we targeted in the
test, the shards added for the Reshard workflows were using
the default version installed which then differed from the
other shards -- which were using the version downloaded into
/tmp -- and caused schema differences that were surfaced in
CopySchemaShard.
=> Tests: AddShard should use targeted MySQL version

tools/shell_functions.inc
This is a cherry-pick/backport of https://github.com/vitessio/vitess/pull/11001
- Backport of: https://github.com/vitessio/vitess/pull/11001
=> Backport: Add more robust go version handling (#11001)

go/test/endtoend/topoconncache/main_test.go, go/test/endtoend/topoconncache/topo_conn_cache_test.go
This is the same basic fix made to other tests in: https://github.com/vitessio/vitess/pull/10961
When [re-]adding replica and rdonly tablets to a shard with a healthy serving PRIMARY tablet, they quickly become SERVING. This led to a timing issue where we added them and waited for them to become NON_SERVING, but they became SERVING by the time we checked.
- Related to: https://github.com/vitessio/vitess/pull/10961
=> Flakes: Expect SERVING status for tablets added to shard with a PRIMARY

go/vt/schemadiff/diff_test.go, go/vt/schemadiff/errors.go, go/vt/schemadiff/schema.go, go/vt/schemadiff/schema_test.go
This PR turns the flat `ErrViewDependencyUnresolved` error into a richer `ViewDependencyUnresolvedError`, indicating the identity of the view in question.
Existing tests adapted to new error type.
- Tracking: https://github.com/vitessio/vitess/issues/10203
=> schemadiff: rich error for unmet view dependencies

docker/k8s/logrotate/Dockerfile, docker/k8s/logtail/Dockerfile, docker/k8s/vtadmin/Dockerfile
We noticed that logtail, logrotate and vtadmin docker image were not building (in Dockerhub) anymore as it use / build context. 
We took this opportunity to move from `ADD` to `COPY` as from the [documentation](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy) it seems to be the preferred way.
=> fix building logtail, logrotate and vtadmin docker image in Dockerhub

.github/workflows/unit_test_mariadb103.yml, test/templates/unit_test.tpl
DigitalOcean mirror isn't working, so let's use RackSpace mirror to install MariaDB into CI VMs.
=> Fix mariadb103 ci

go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/tabletserver/query_executor.go
#10900 introduced `cancelled_timestamp` column, which is populated when a migration is cancelled. Then, based on the value of this column, and assuming a problem in the migration, a migration transitions to either `failed` (if the column is `NULL`) or to `cancelled` (if the column is `NOT NULL`).
As quick recap, `gh-ost`, `pt-osc` and even `vreplication` itself, to some extent, act as 3rd party tools for Online DDL. To cancel a migration is to fail the migration; #10900 was made so that we can make a distinction between a "legitimately failed" migration to a "user cancelled" migration.
However, we left out a couple use cases, where the Online DDL executor _itself_ may cancel a migration:
- if the migration is stale
- if there's an unrecoverable error in the migration flow
In these …
=> Online DDL, CancelMigration: distinguish user-issued vs. internally-issued cancellation

go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go, go/vt/schemadiff/types.go
MySQL does not support multiple `ADD FULLTEXT KEY` clauses in the same `ALTER TABLE` statement.
`schemadiff` now supports a `FullTextKeyStrategy` with the following options:
- `FullTextKeyDistinctStatements` (default): generate distinct `ALTER` statements when there's more than one `ADD FULLTEXT` clause; these statements will be valid to run on MySQL
- `FullTextKeyUnifyStatements`, generate a single `ALTER` statement with multiple `ADD FULLTEXT` clauses. Reasons to use this strategy:
- We will make this statement valid for Vitess's Online DDL
- MySQL may remove this limitation in the future.
Tests added.
- https://github.com/vitessio/vitess/issues/6926
-   [ ] …
=> schemadiff: FullTextKeyStrategy, handling multiple 'ADD FULLTEXT key' alter options

go/vt/schemadiff/diff_test.go, go/vt/schemadiff/schema.go, go/vt/schemadiff/schema_test.go
This was using accidentally the wrong error type that was for views not found during diff application. Nothing was using this new error type yet, which is incorrect.
Changed in https://github.com/vitessio/vitess/pull/10940 which added the type but didn't use it. 
=> Use the correct error type for dependencies

.github/workflows/upgrade_downgrade_test_backups_e2e.yml, .github/workflows/upgrade_downgrade_test_backups_manual.yml, .github/workflows/upgrade_downgrade_test_query_serving_queries.yml, .github/workflows/upgrade_downgrade_test_query_serving_schema.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml
This PR enables upgrade downgrade tests on the `main` branch of this repository. It was previously disabled to ensure we ran the tests only when the `Skip Upgrade/Downgrade tests` label was not set. But since we have removed this assertion, we can safely re-run the tests on `main`.
=> Run upgrade/downgrade tests on main

go/test/endtoend/vtgate/lookup_test.go, go/test/endtoend/vtgate/sec_vind/main_test.go, go/test/endtoend/vtgate/sec_vind/schema.sql, go/test/endtoend/vtgate/sec_vind/vschema.json, go/vt/sqlparser/ast_funcs.go, go/vt/sqlparser/ast_rewriting.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/planbuilder/gen4_planner.go, go/vt/vtgate/planbuilder/select.go, test/config.json
Cherry Pick of https://github.com/vitessio/vitess/pull/10422
In a recent change (#10152), we introduced a special mode handling when no routes are found for a query. 
This introduced an issue that was later fixed for gen4 (#10346), but here I missed fixing the same issue for v3.
#10152 Bug introduced
#10346 Bug fixed for Gen4
Fixes #10301
=> [13.0] Cherry Pick: only use the special NoRoute handling mode when needed

go/mysql/conn.go, go/mysql/conn_flaky_test.go
Also updates the comment to be more specific that the additional length check is only there if DEPRECATE_EOF is set.
Follow-up to https://github.com/vitessio/vitess/pull/10871 to add some additional coverage. 
=> Add additional tests for EOF packet checks

go/vt/vtgate/planbuilder/physical/route_planning.go, go/vt/vtgate/planbuilder/testdata/select_cases.txt
This pull request imrpoves query route merging for queries that consist of multiple joins (via vindex columns), where some of the joined tables also have additional vindex conditions defined.
An example can be found in https://github.com/vitessio/vitess/issues/10819, and in the test case that was added to `go/vt/vtgate/planbuilder/testdata/select_cases.txt`.
Previously, the Gen4 planner would break the query up into multiple pieces, one for each "direct" vindex condition defined, even though the query could be send to a single shard based on the join conditions between all tables.
For the query from the added test case, the plan generated by Gen4 would look like this:
```json
{
"Original": "SELECT user.id FROM user INNER JOIN music_extra ON user.id = …
```
=> Improve route merging for queries that have conditions on different vindexes, but can be merged via join predicates.

go/vt/vtexplain/testdata/multi-output/selectsharded-output.txt, go/vt/vtexplain/testdata/selectsharded-queries.sql, go/vt/vtexplain/testdata/test-schema.sql, go/vt/vtexplain/testdata/test-vschema.json, go/vt/vtexplain/testdata/twopc-output/selectsharded-output.txt, go/vt/vtexplain/vtexplain_vttablet.go
If a query contains an `IN` condition with multiple equivalent values for `lookup_unique` vindexes, `vtexplain` fails with:
```
Lookup.Map: unexpected multiple results from vindex <vindex>
```
This is due to `vtexplain` "simulating" that each value of the tuple in a lookup vindex query returns a result row, but when values are equivalent (e.g. `1` and `"1"`), only a single row should be returned.
I tried to implement this by determining the type of the column being matched against, converting each value of the tuple to that type, and then making sure `vtexplain` only considers non-duplicate values.
=> `vtexplain` fails for vindex lookup queries with duplicate / equivalent values.

go/flags/endtoend/vtctld.txt, go/flags/endtoend/vtexplain.txt, go/flags/endtoend/vtgate.txt, go/flags/endtoend/vtgr.txt, go/flags/endtoend/vttablet.txt, go/flagutil/optional.go, go/trace/fake.go, go/trace/opentracing.go, go/trace/plugin_datadog.go, go/trace/plugin_jaeger.go, go/trace/trace.go, go/trace/trace_test.go, go/vt/servenv/servenv.go
Had to do things a bit backwards here to avoid an import cycle between `servenv` and `trace`.
Closes #10747.
=> [trace] Migrate `go/trace` to use `pflag` for flag definitions

go/vt/vtgate/executor_select_test.go, go/vt/vtgate/legacy_scatter_conn_test.go, go/vt/vtgate/safe_session.go, go/vt/vtgate/safe_session_test.go
This PR sends the multiple set statements into a single set statement to vttablet.
This will avoid multiple round trips at vttablet-mysql with a single call.
- #9706 
=> refactor: group all system setting query into single set statement

go/vt/schemadiff/schema.go, go/vt/schemadiff/schema_test.go, go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go, go/vt/schemadiff/types.go, go/vt/schemadiff/view.go
This change includes two commits that address two specific issues. First there is the way that we clone a schema for an `Apply` operation. This is switched to using the already available `sqlparser` clone helpers instead of serializing to string and then parsing again.
The second change is to use the `sqlparser` comparison methods instead of serializing to a string and then comparing.
Both these impact performance significantly when dealing with large schemas. The improvements here show a 4x performance improvement on internal PSDB usage of `schemadiff` when dealing with large schemas. 
#10203
=> schemadiff performance improvements

go/cmd/mysqlctl/mysqlctl.go, go/cmd/query_analyzer/query_analyzer.go, go/cmd/rulesctl/main.go, go/cmd/topo2topo/topo2topo.go, go/cmd/vtbench/vtbench.go, go/cmd/vtclient/vtclient.go, go/cmd/vtctlclient/main.go, go/cmd/vtctldclient/main.go, go/cmd/vtorc/main.go, go/cmd/vttestserver/main.go, go/cmd/zk/zkcmd.go, go/cmd/zkctl/zkctl.go, go/vt/log/log.go, go/vt/servenv/servenv.go
This migrates the flags defined in `go/vt/log` to pflag. Similar to #11028, the flag registration has to happen backwards, and then for double-fun, (a) every binary needs logging and (b) not every binary uses `servenv.ParseFlags(WithArgs)?`, so this one needed some additional special handling, on top of the aforementioned special handling.
Closes #10808.
=> [log] Migrate `go/vt/log` flags to `pflag`

doc/releasenotes/15_0_0_summary.md, go/flags/endtoend/vtctld.txt, go/flags/endtoend/vtexplain.txt, go/flags/endtoend/vttablet.txt, go/vt/mysqlctl/compression.go
Signed-off-by: Renan Rangel <rrangel@slack-corp.com>
As part of https://github.com/vitessio/vitess/pull/10558, it seems we have changed the default compression engine from `pargzip` to `pgzip`. We can see [here](https://github.com/vitessio/vitess/pull/10558/files#diff-ac82970a17868e6ae810d9e2ea6908f3bea25da4d013231910a7d6e3acbedc88L501-R514) that this was the compressor used before. Currently we are defaulting to `pgzip` and that is not intended as it was moved from `pgzip` => `pargzip` in https://github.com/vitessio/vitess/pull/7037
This will make sure the default engine is `pargzip` again, as there is a considerable difference on resource usage when using the other engine.
-   [ ] Tests were added or are not …
=> revert default compression engine

go/cmd/mysqlctl/mysqlctl.go, go/cmd/query_analyzer/query_analyzer.go, go/cmd/rulesctl/main.go, go/cmd/topo2topo/topo2topo.go, go/cmd/vtbench/vtbench.go, go/cmd/vtclient/vtclient.go, go/cmd/vtctldclient/main.go, go/cmd/vtorc/main.go, go/cmd/vttestserver/main.go, go/cmd/zk/zkcmd.go, go/cmd/zkctl/zkctl.go, go/flags/endtoend/vtctld.txt, go/flags/endtoend/vtexplain.txt, go/flags/endtoend/vtgate.txt, go/flags/endtoend/vtgr.txt, go/flags/endtoend/vttablet.txt, go/internal/flag/flag.go, go/vt/logutil/level.go, go/vt/logutil/purge.go, go/vt/servenv/servenv.go
Basically the same general shape of #11036, but this time for `go/vt/logutil`. The other notable callouts:
- We have a `_flag.Lookup` helper which tries to find a pflag Flag globally defined; failing that, a go flag Flag (which we convert to a pflag Flag).
- The vttestserver Once wrapper is now generic to flag names, so it'll be less cumbersome to keep up to date in the future.
Closes #10809
=> [cli] [logutil] Migrate flags defined in `go/vt/logutil` to `pflag`

go/tools/asthelpergen/clone_gen.go, go/tools/asthelpergen/integration/ast_clone.go, go/vt/schemadiff/schema_test.go, go/vt/sqlparser/ast_clone.go
The code generated for copying basic types in the AST was broken. It would generate code like the following:
```
res := make([]string, 0, len(n))
copy(res, n)
```
The issue is that `copy` uses the logical size of the slice, not the allocated size. This means that it doesn't copy anything at all and that `res` here stays empty.
The change here fixes this issue. It changes the `make` to allocate the logical size as the same value. It then changes the non basic type code to use indexing instead.
That seemed easier to change than having two separate code boths of how the slice is allocated for basic types vs. non basic types.
Do we have a better place to add a test for this except in `schemadiff`? 
The change https://github.com/vitessio/vitess/pull/11035 more easily exposed this issue because …
=> Fix AST copying of basic types

.github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml, .github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml, .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml, .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml, tools/get_next_release.sh
This PR adds the next-release counterparts of the current upgrade-downgrade tests. Currently, we have tests that test the upgrade process from the previous release to the current one. For example on `main` the tests run against release-14.0. On release-14.0 they run against 13.0.2 and so on.
But it is essential to also run the tests against the next release. For example, if we introduce a change in release-13.0 which would prevent it from upgrading to 14.0.1, we won't catch it at all until a new patch release is done, in which case it would fail in a PR based against release-14.0
To also catch these scenarios, we have chosen to add upgrade-downgrade tests to test against the next release apart from just the previous release. For `main`, the tests will just be skipped. For release-14.0, …
=> Add upgrade-downgrade tests for next releases

go/vt/schemadiff/column.go, go/vt/schemadiff/schema.go, go/vt/schemadiff/schema_test.go, go/vt/schemadiff/table.go, go/vt/schemadiff/types.go, go/vt/schemadiff/view.go
Since each entity `Alter()` operation already returns a copy itself of the entity that is modified, it is enough to only shallow copy the schema.
The shallow copy includes the references to the tables, views etc. and will return an already correct new schema when creating or dropping entities with no further issues.
When executing an `Apply()` on a specific entity, that already returns a clone of that entity itself so it also ensures that the new returned value is only changed and the original is unmodified.
This avoids a huge deal of copying when working with large schemas which greatly improves performance there. We're seeing another 6x improvement here in dealing with some large schemas.
#10203
-   [x] …
=> schemadiff: Shallow copy of the schema

go/flags/endtoend/vtctld.txt, go/flags/endtoend/vtexplain.txt, go/flags/endtoend/vttablet.txt, go/vt/vttablet/tabletmanager/vreplication/controller.go, go/vt/vttablet/tabletmanager/vreplication/last_error.go
Fixes https://github.com/vitessio/vitess/issues/10783, and to be backported to v14.
The undocumented flag `vreplication_max_time_to_retry_on_error` now default to `0`, which means "no limit". this makes the behavior backwards compatible. Users will have to opt-in to the vreplication max-retry time limit.
Documentation PR to follow.
cc @derekperkins
=> VReplication: vreplication_max_time_to_retry_on_error default to zero, no limit

go/vt/schemadiff/schema.go, go/vt/schemadiff/table.go, go/vt/schemadiff/view.go
We already have a method that compares while ignoring the name, so use that here too. This avoids a copy and custom logic here.
Testing on a large schema shows that this reduces allocations from over 2 million to around 200k, removing the largest allocation in diff computations for large schemas.
Moving to embedding the pointer instead of the struct removes another set of cases where we copy the object unnecessary. 
#10203
=> Use available method to compare tables

go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go
This fixes the handling of primary key options. When dropping a primary key, we should use `drop primary key` and not use the name.
#10203
=> schemadiff: Fix handling of primary key

go/test/endtoend/cellalias/cell_alias_test.go, go/test/endtoend/cluster/cluster_process.go, go/test/endtoend/cluster/vtctl_process.go, go/test/endtoend/cluster/vtctld_process.go, go/test/endtoend/reparent/utils/utils.go, go/test/endtoend/sharding/base_sharding.go, go/test/endtoend/sharding/mergesharding/mergesharding_base.go, go/test/endtoend/sharding/resharding/resharding_base.go, go/test/endtoend/tabletmanager/commands_test.go, go/test/endtoend/tabletmanager/custom_rule_topo_test.go, go/test/endtoend/tabletmanager/primary/tablet_test.go, go/test/endtoend/tabletmanager/qps_test.go, go/test/endtoend/tabletmanager/tablet_health_test.go, go/test/endtoend/vtorc/utils/utils.go
This PR removes the usage of a deprecated flag `enable_queries` from our end-to-end tests. Essentially, this PR is a backport of https://github.com/vitessio/vitess/pull/10646, but it only backports the end-to-end test changes and not the code changes. 
There is a two-fold reason for this change. The first one is that https://github.com/vitessio/vitess/pull/11034 is attempting to introduce upgrade tests that are failing because of this flag's usage. The second reason is that we shouldn't be using the deprecated flags ourselves since we expect users to stop using them too.
=> Remove deprecated flag `enable_queries` from end to end tests in v14 

go/test/endtoend/vreplication/vdiff_helper_test.go
I noticed that the VDiff2 e2e test was failing ~ 1% of the time — and the error was always due to the ETA being 1 second in the past.
This is NOT indicative of a program error but instead can result when operating near the second boundary as the ETAs use second precision. This PR adjusts the test to account for this.
=> Flakes: Prevent VDiff2 test failures when operating near the second boundary

go/cmd/vtadmin/main.go
In #11028, we moved the tracing flags off the global flagset, which of
course means doing a global lookup on the flagset now returns `nil`.
Unfortunately, it didn't occur to me at the time that this would break
vtadmin's hacky way of getting global flags into its FlagSet.
This fixes that issue.
**Before**
```
✗ vtadmin --help                                                
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x102b9e7c4]
goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddGoFlag(0x140003e0500, 0x0)
github.com/spf13/pflag@v1.0.5/golangflag.go:86 +0x24
main.main()
vitess.io/vitess/go/cmd/vtadmin/main.go:166 +0x23c
```
**After**
<details><summary><code>vtadmin --help</code></summary>
``` …
```
=> [vtadmin] Update how tracing flags are registered

go/vt/vtctld/vtctld.go
Because `healthCheck` was being explicitly declared as a concrete type,
later, in `newTabletWithStatsAndURL` (in api.go), when we compare the
_interface_ to `nil`, we get `false` (despite the underlying
implementation being itself `nil`), and so we attempt to call
`GetTabletHealth` on `nil`, resulting in a panic.
See one of [my favorite talks](https://youtu.be/ynoY2xz-F8s?t=796) on why
this is.
I was able to produce the panic listing `/api/keyspace/commerce/tablets` prior to this change, but it works with this change. This is happening in 14.0, so we need to back port there (<= v13 is fine, I think)
=> [vtctld] Fix nil-ness in healthcheck

go/vt/srvtopo/watch.go, go/vt/topo/memorytopo/election.go
We should only setup the goroutine after we've grabbed the lock to safely start the watcher.
Additionally, the watcher should only be retried if we're not interrupted and shutting down for example.
Follow up fixes after changes in https://github.com/vitessio/vitess/pull/10954 & https://github.com/vitessio/vitess/pull/10906
=> Fix races in memory topo and watcher

go/vt/vtgate/executor.go, go/vt/vtgate/executor_select_test.go
There are statements that are not planned i.e. being, commit, etc. and savepoints related.
Those planner have plan instructions as nil, which means we can skip the `checkThatPlanIsValid` check even when `-no_scatter` flag is set.
Currently it throws nil pointer panic. This PR fixes that.
=> fix: return when instructions are nil in checkThatPlanIsValid

go/test/endtoend/reparent/utils/utils.go
Some tests of ERS and PRS have been flaky. The following steps are followed leading to failure -  
1. We bring up a new cluster with new tablets
2. We try to run PRS
3. Meanwhile, tablets go to RESTORE mode as part of the startup
4. PRS sees the tablets are of type RESTORE and doesn’t set semi-sync on them
5. Tablet complete RESTORE and go to type REPLICA (but semi-sync is off). Here initializing logic for replication exists, but that doesn't run since we run our tests with `disable_active_reparents` to prevent the replication manager from running.
6. Test fails assuming semi-sync is on (Blocks on a write)7. 
The proposed fix is to remove the flag `restore_from_backup` from the vttablets which are coming up for the first time. This will prevent the vttablets from going into the RESTORE …
=> FlakinessFix: Reparent tests by removing `restore_from_backup`

go/mysql/conn.go
On MySQL 8.0 it's possible we get back a zero length state for session state changed information. In this case, we treat this as no data being present and continue.
This was exposed in https://github.com/vitessio/vitess/pull/11026 but I'm extracted this as a separate fix until that lands since this can trigger spurious errors when it shouldn't.
Found through https://github.com/vitessio/vitess/pull/11026 where we have a test failed fixed by this change:
```
--- FAIL: TestCallProcedureChangedTx (0.00s)
call_test.go:154: 
Error Trace:	call_test.go:154
Error:      	Received unexpected error:
Code: INTERNAL
invalid OK packet session state change type: 0 (CallerID: dev)
Test:       	TestCallProcedureChangedTx
```
- …
=> Fix handling zero byte string for session state changed

go/vt/vtgate/executor.go, go/vt/vtgate/executor_select_test.go
This is a backport of https://github.com/vitessio/vitess/pull/11070.
=> [release-12.0] fix: return when instructions are nil in checkThatPlanIsValid (#11070)

.github/workflows/cluster_initial_sharding_multi.yml, .github/workflows/legacy_local_example.yml
These `cluster_initial_sharding_multi.yml` and `legacy_local_example.yml` workflows did not exist on main — they were removed in https://github.com/vitessio/vitess/pull/10278 — so they were not updated when https://github.com/vitessio/vitess/pull/10768 was backported.
This means that we'll need to backport this PR to `release-13.0` and `release-12.0` as well.
- Follow-up to: https://github.com/vitessio/vitess/pull/10768
- Follow-up to: https://github.com/vitessio/vitess/pull/10278
- Fixes test failures in: https://github.com/vitessio/vitess/pull/11077
=> Add SKIP check to workflows removed in v15

go/vt/topo/topoproto/tablet_test.go
This commit fixes an occurrence of a loop variable being captured in a
parallel test. With very high probability, only the last test case
will actually be exercised. To work around this problem, we create a
local copy of the range variable before the parallel test, as advised
by the Go documentation at:
https://pkg.go.dev/testing#hdr-Subtests_and_Sub_benchmarks
Issue was found automatically using the `loopvarcapture` linter.
=> Fix incorrect use of loop variable in parallel test

docker/k8s/vtadmin/Dockerfile
vtadmin binary was missing from the docker image
fix #10770
Signed-off-by: Leopold Jacquot <leopold.jacquot@infomaniak.com>
=> fix missing vtadmin binary in docker image

.github/workflows/upgrade_downgrade_test_backups_manual.yml, .github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
This Pull Request fixes the installation of dependencies in the manual backup upgrade downgrade test. It uses MySQL8.0.29 instead of 8.0.28. The issue can be observed in the following build:
- https://github.com/vitessio/vitess/runs/7980238746?check_suite_focus=true
This PR unblocks the following PRs:
- https://github.com/vitessio/vitess/pull/11052
- https://github.com/vitessio/vitess/pull/11078
- https://github.com/vitessio/vitess/pull/11077
- https://github.com/vitessio/vitess/pull/11068
- https://github.com/vitessio/vitess/pull/11051
- https://github.com/vitessio/vitess/pull/11040
- https://github.com/vitessio/vitess/pull/10928
-   [x] Documentation was added or …
=> Fix Upgrade Downgrade manual backup dependencies install

go/vt/vtgate/planbuilder/physical/route_planning.go, go/vt/vtgate/planbuilder/testdata/select_cases.txt
In the Gen4 planner, routes with a `None` opcode do not be merged with other routes (e.g. for `JOIN`s). Instead, queries are broken up.
For example, the following query (using the schema defined in `go/vt/vtgate/planbuilder/testdata/schema_test.json`):
```sql
SELECT `music`.id FROM `music` INNER JOIN `user` ON music.user_id = user.id WHERE music.user_id IN (NULL) AND user.id = 5
```
Will result in this Gen4 plan:
```json
{
"Original": "SELECT `music`.id FROM `music` INNER JOIN `user` ON music.user_id = user.id WHERE music.user_id IN (NULL) AND user.id = 5",
"OperatorType": "Join",
"Variant": "Join",
"JoinColumnIndexes": "L:1",
"JoinVars": {
"music_user_id": 0
},
"TableName": "music_`user`",
"Inputs": [
{
"Variant": "None", …
```
=> Improve merging for `None` route opcodes.

go/mysql/flavor_mysql.go
When reloading the database schema, a query to fetch table information and tablespace information is executed. This query can take a long time when run on a mysql instance with many tables across many databases.
We notice the impact of this query during database setup in our CI environments, as this query is executed on each DDL statement (and thus gets incrementally slower the more tables are being created).
Performance of this query was improved before in https://github.com/vitessio/vitess/pull/9632 by pre-filtering the rows of the `information_schema.innodb_sys_tablespaces` before joining them to rows from `information_schema.tables`, but that change was accidentally reverted in https://github.com/vitessio/vitess/pull/10703.
This brings back the pre-filtering.
---
Can this be …
=> Improve schema reload performance by pre-filtering joined rows.

go/flags/endtoend/vtexplain.txt, go/flags/endtoend/vttablet.txt, go/vt/vttablet/onlineddl/executor.go
In https://github.com/vitessio/vitess/pull/10410 we introduced concurrent `vitess` migrations. A constant named `maxConcurrentMigrations` was created with the value `256`. @mattlord commented in /files#diff-059c9f46e8d270d9c5514ef2b08679035eb0daaa8d95074e34ef43a81d50dc37R127 that the value should be configurable, and this is what this PR does.
We introduce a new flag called `--max_concurrent_online_ddl'. It applies to the maximum number of possible concurrent `vitess` strategy `ALTER TABLE` statements. `CREATE TABLE|VIEW`, `DROP TABLE|VIEW` and `ALTER VIEW` are almost instantaneous operations and are not part of the concurrency limitation.
The minimum value for this flag is `1` (even if set below `1`, the value will be `1`). The default is `256`, which is a bit high and optimistic.
#6926 …
=> Online DDL: introduce '--max_concurrent_online_ddl'

go/pools/resource_pool.go, go/pools/resource_pool_test.go, go/pools/rp_bench_test.go, go/pools/rpc_pool.go, go/vt/dbconnpool/connection_pool.go, go/vt/dbconnpool/pooled_connection.go, go/vt/vttablet/endtoend/reserve_test.go, go/vt/vttablet/tabletserver/connpool/dbconn.go, go/vt/vttablet/tabletserver/connpool/pool.go
This PR adds a separate channel to keep the connections which has different settings from the default connection settings and on a get it will return the connection with the correct settings. 
On a put the connection will go to the right channel.
Similarly other methods like closeIdleConnection, refresh pool, etc. are modified to accomodate the settings channel.
This is an initial implementation and there will be further modiffication to make the implementation better
1. Currently the resource is closed if the settings mismatch on the existing connection. This will be changed to reset old settings and apply new settings
2. Add metrics around the new channel usage
This PR will atleast for now enable to intergrate other parts of the query serving flow in vttablet.
- #9706 
-   [X] Tests …
=> System Settings connections pool implementation

go/pools/resource_pool.go, go/pools/resource_pool_test.go
This PR on ApplySettings failure return the resource back to the pool for accounting and avoiding leaking the connection.
- #9706 
=> return resource back to pool on apply settings failure

go/vt/vttablet/tabletserver/query_engine.go
Tiny fix for a logging mistake: the 2 arguments weren't formatted into the message but placed at the end.
Before the fix:
> I0824 09:35:56.867155    2521 query_engine.go:180] Stream consolidator is enabled with query size set to **%d** and total size set to **%d**.**2097152 134217728**
After the fix:
> I0824 09:42:03.335050    1602 query_engine.go:180] Stream consolidator is enabled with query size set to **2097152** and total size set to **134217728**.
-   [x] "Backport me!" label ~has been added if this change should be backported~ not required
-   [x] Tests ~were added or are~ not required
-   [x] Documentation ~was added or is~ not required
=> Fix logging formatting mistake

go/test/endtoend/vtgate/queries/misc/misc_test.go
This PR changes `TestInvalidDateTimeTimestampVals` to check we got an error back from the MySQL client. By doing this, the existing linting issues will be fixed. 
```
Error: endtoend/queries/misc/misc_test.go: Error return value of `mcmp.ExecAllowAndCompareError` is not checked (errcheck)
mcmp.ExecAllowAndCompareError(`select date'2022'`)
```
=> Fix `TestInvalidDateTimeTimestampVals` linter issues

go/test/endtoend/vtgate/queries/normalize/normalize_test.go
Use `vtParams.Host` instead of `clusterInstance.Hostname` in `TestNormalizeAllFields` to keep the same format throughout the Gen4 e2e tests.
=> Use vtparams instead of clusterInstance in TestNormalizeAllFields

go/flags/endtoend/vtgate.txt, go/flags/endtoend/vttablet.txt, go/stats/opentsdb/opentsdb.go, go/stats/statsd/statsd.go
This migrates _just_ the flags for the stats backends to pflag. The top-level `go/stats` flags were a bit more complex to analyze dependencies on, so I want to do that separately.
```
go list -f '{{ .ImportPath }}| {{ join .Deps " " }} ' ./go/cmd/... ./go/vt/servenv | awk -F"|" '$2 ~ " vitess.io/vitess/go/stats/opentsdb " {print $1}'
vitess.io/vitess/go/cmd/vtgate
vitess.io/vitess/go/cmd/vttablet
```
```
go list -f '{{ .ImportPath }}| {{ join .Deps " " }} ' ./go/cmd/... ./go/vt/servenv | awk -F"|" '$2 ~ " vitess.io/vitess/go/stats/statsd " {print $1}'           
vitess.io/vitess/go/cmd/vtgate
vitess.io/vitess/go/cmd/vttablet
```
no flags
- Closes #10745.
- Closes #10744.
-   [x] …
=> [cli] [stats] Migrate stats/opentsdb + stats/statsd flags to pflag

go/vt/vtgate/executor.go, go/vt/vtgate/logstats/logstats.go, go/vt/vtgate/logstats/logstats_test.go, go/vt/vtgate/plan_execute.go
Adds the selected database to `LogStats` logs.
Makes it easier to read the queries if the context for the query is available.
=> add the selected keyspace to LogStats

go/tools/asthelpergen/clone_gen.go, go/tools/asthelpergen/integration/ast_clone.go, go/vt/sqlparser/ast_clone.go
Backport of https://github.com/vitessio/vitess/pull/11046 to release-14.0.
Original fix in https://github.com/vitessio/vitess/pull/11046
=> Fix AST copying of basic types in release-14.0

.github/workflows/endtoend.yml, go/mysql/endtoend/query_test.go, go/vt/vttablet/endtoend/misc_test.go, go/vt/vttablet/endtoend/vstreamer_test.go
This extracts the update to Ubuntu 20.04 (and thus MySQL 8 by default) just for the end to end tests and updates the associated tests.
Extracted from https://github.com/vitessio/vitess/pull/11026
=> Upgrade to Ubuntu 20.04 for endtoend tests

go/vt/topo/memorytopo/election.go, go/vt/topo/memorytopo/lock.go, go/vt/topo/memorytopo/memorytopo.go, go/vt/topo/memorytopo/watch.go, go/vt/topo/test/file.go, go/vt/topo/test/testing.go
The model of where we clear out the factory instance to nil is not really tenable since it always by definition races with `Watch` shutdown and there's no way to resolve that without explicit communication.
This introduces an explicit closed state flag instead and we error out if we're already closed to avoid issues around usage after close. This resolves all the issues.
The tests here are also updated to essentially always trigger the previous problem and it's gone with the changes applied here.
Previous attempts like https://github.com/vitessio/vitess/pull/11065, https://github.com/vitessio/vitess/pull/10954 & https://github.com/vitessio/vitess/pull/10906 tried to improve this but don't solve the more fundamental issue. Tried to avoid this change before but I think we have to make it.
- …
=> Add explicit close state to memory topo connection

go/test/endtoend/vtorc/general/main_test.go, go/test/endtoend/vtorc/general/vtorc_test.go
This PR refactors some VTOrc tests to run as a single test with sub-tests. The time of execution is brought down from 6 minutes 34 seconds to 5 minutes 5 seconds.
=> Refactor vtorc tests to run as a single test with sub-tests

go/vt/vttablet/onlineddl/executor.go
The Online DDL state machine ignores some errors in some operations, which is fine; but we're missing logging for the existence of such errors. This PR adds a bunch of logging for when database write operations might happen (transitioning a migration's state, updating its message, etc.)
#6926
=> Online DDL: more error logging

.github/workflows/cluster_endtoend_tabletmanager_consul.yml, .github/workflows/cluster_endtoend_tabletmanager_tablegc.yml, .github/workflows/cluster_endtoend_tabletmanager_throttler.yml, .github/workflows/cluster_endtoend_tabletmanager_throttler_custom_config.yml, go/test/endtoend/tabletmanager/commands_test.go
Extracted from https://github.com/vitessio/vitess/pull/11026 to move CI to 20.04 for the tabletmanager CI jobs.
https://github.com/vitessio/vitess/pull/11026
=> Move tabletmanager CI jobs to 20.04

go/internal/flag/flag.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go
Previous PR https://github.com/vitessio/vitess/pull/11095 had introduced  a bug which related to running the tests manually on the command line. It would ignore all passed test flags due to two bugs: one a typo in the parsing of test flags and another, a missing call to perform the parsing in `TestMain` in `tabletmanager/vreplication`
#11095 
=> CLI Pflag migration work: Fix regression caused by pflag-vreplication PR

tools/do_release.sh
This pull request modifies the do_release script to modify the compose example files to use the proper docker image tag. Now, when doing a release, the compose example will be changed to use the release' image.
=> Include the compose examples in the `do_release` script

Makefile, tools/do_release.sh
This Pull Request is a backport of #11130, plus the addition of the `do_release` script to `release-12.0` which is our utility script to do the releases.
It includes a fix that was made in #11134.
=> [release-12.0] Add `do_release` and include the compose examples in it (#11130)

go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
Cherry-pick of #9978
* Recompute the plan for a table if a new table is encountered for the same id
* Trigger rebuild
* Trigger rebuild
#9978
=> Cherrypick to 13.0: VStreamer: recompute table plan if a new table is encountered for the same id (#9978)

go/flags/endtoend/vtgr.txt, go/vt/sqlparser/truncate_query.go, go/vt/sqlparser/truncate_query_test.go, go/vt/vttablet/endtoend/misc_test.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tabletserver_test.go
This PR moves the flags in sqlparser to use pflags package. It is part of https://github.com/vitessio/vitess/issues/10697#movers-guide work. The only flags available here are the ones that control query truncation for logging and UI, so they have been deemed to be required by all the binaries that import the package.
- https://github.com/vitessio/vitess/issues/10697#movers-guide
- Fixes https://github.com/vitessio/vitess/issues/10824
=> Move sqlparser flags to use pflags

test/ci_workflow_gen.go
We recently changed the vtgate (https://github.com/vitessio/vitess/pull/11118) and tablet manager (https://github.com/vitessio/vitess/pull/11116) CI jobs to run on Ubuntu20, however, the CI generation script did not change. This Pull Request updates the script to generate the same workflows as the ones currently on `main`.
=> Use Ubuntu 20 for vtgate and tabletmanager workflows

.github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
This PR reverts an unwanted change that was made by this commit (https://github.com/vitessio/vitess/pull/11078/commits/e32e30da634263ad511c3d45102daebec8e4c0f0) in #11078.
=> [release-13.0] Remove an unwanted change made in #11078 to the upgrade downgrade tests

go/vt/orchestrator/app/cli.go, go/vt/orchestrator/inst/analysis_dao.go, go/vt/orchestrator/inst/candidate_database_instance_dao.go, go/vt/orchestrator/inst/cluster_alias_dao.go, go/vt/orchestrator/inst/cluster_domain_dao.go, go/vt/orchestrator/inst/instance_dao.go, go/vt/orchestrator/inst/instance_topology.go, go/vt/orchestrator/inst/instance_topology_dao.go, go/vt/orchestrator/inst/maintenance_dao.go, go/vt/orchestrator/inst/pool_dao.go, go/vt/orchestrator/inst/resolve_dao.go, go/vt/orchestrator/inst/tag_dao.go, go/vt/orchestrator/logic/topology_recovery.go, go/vt/orchestrator/logic/topology_recovery_dao.go, go/vt/orchestrator/process/access_token_dao.go, go/vt/orchestrator/process/election_dao.go, go/vt/orchestrator/process/health_dao.go
After moving away from external logging in https://github.com/vitessio/vitess/pull/11085, we started seeing error messages like 
```
E0901 16:38:28.412132   63266 topology_recovery_dao.go:112] <nil>
E0901 16:38:28.412186   63266 topology_recovery_dao.go:356] <nil>
E0901 16:38:28.412247   63266 topology_recovery_dao.go:260] <nil>
E0901 16:38:28.412352   63266 cluster_alias_dao.go:142] <nil>
```
The problem was traced to not doing a nil-check before printing the error message. The previous implementation of `log.Errore` used to do the nil-check before printing the error, so it wasn't required in the codebase.
=> Nil-check errors before printing them in VTOrc

go/vt/vttablet/tabletserver/repltracker/writer.go
Fixing a race condition scenario where on-demand heartbeats are requested (e.g. by a running VReplication workflow) while the writer is also closing, e.g. being demoted in a PRS.
The fix is to use the writer's mutex before enabling writes; this now takes place in a `goroutine` because the call can be made by `Open()` itself as well as by `EnableWrites()`.
https://github.com/vitessio/vitess/issues/10196
=> On demand heartbeats: fix race condition closing the writer

go/cmd/mysqlctld/mysqlctld.go, go/cmd/vtcombo/main.go, go/cmd/vtctld/main.go, go/cmd/vtgate/vtgate.go, go/cmd/vtgateclienttest/main.go, go/cmd/vttablet/vttablet.go, go/cmd/vttestserver/main.go, go/flags/endtoend/vtexplain.txt, go/flags/endtoend/vtgr.txt, go/vt/servenv/grpc_auth.go, go/vt/servenv/grpc_server.go, go/vt/servenv/grpc_server_auth_mtls.go, go/vt/throttler/demo/throttler_demo.go, go/vt/vttest/vtprocess.go
The only codepath that uses these is via `createGRPCServer`, which is called by `Run` (which no one calls externally??) and `RunDefault` (which calls `Run` under the hood)
Relates to #11144.
=> [cli] [servenv] Migrate grpc auth server flags within `servenv` to `pflag`

go/vt/topo/consultopo/server.go, go/vt/topo/consultopo/server_flaky_test.go, go/vt/topo/consultopo/watch.go
Updates throttler related flag references specified in https://github.com/vitessio/vitess/issues/10858
Here are the commands registered
go list -f '{{ .ImportPath }}| {{ join .Deps " " }} ' ./go/cmd/... | awk -F"|" '$2 ~ "go/vt/topo/consultopo" {print $1}'
vitess.io/vitess/go/cmd/topo2topo
vitess.io/vitess/go/cmd/vtbackup
vitess.io/vitess/go/cmd/vtcombo
vitess.io/vitess/go/cmd/vtctl
vitess.io/vitess/go/cmd/vtgate
vitess.io/vitess/go/cmd/vtgr
vitess.io/vitess/go/cmd/vtorc
vitess.io/vitess/go/cmd/vttablet
vitess.io/vitess/go/cmd/vttestserver
vitess.io/vitess/go/cmd/zk
Fixes #10858  …
=> [cli] [topo/consultopo] Migrate consul flags to pflags

go/vt/srvtopo/query.go, go/vt/srvtopo/query_srvkeyspacenames.go, go/vt/srvtopo/resilient_server_test.go, go/vt/srvtopo/status.go, go/vt/srvtopo/watch.go, go/vt/srvtopo/watch_srvkeyspace.go, go/vt/srvtopo/watch_srvvschema.go, go/vt/topo/etcd2topo/server_test.go, go/vt/topo/etcd2topo/watch.go
Right now we pass in the context when starting a Watch that is also used for the request context. This means that the Watch ends up being cancelled when the original request that started it as a side effects ends up completing and cancels the context to clean up.
This is of course not as intended. Before the refactor in https://github.com/vitessio/vitess/pull/10906 this wasn't causing a
practical issue yet. We'd still have the expired context internally in the watcher and it would be passed through with updating entries, but there were no calls that ended up validating the context expiry, avoiding any immediate issue.
This is bound to fail though at some point if something would be added that does care about the context. What is needed is that the watcher we start sets up it's own context …
=> Fix problematic watch cancellation due to context cancellation

go/mysql/fakesqldb/server.go, go/test/endtoend/vtgate/gen4/system_schema_test.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/query_executor_test.go
Tabletserver `Execute()` replaces `bindVars[BvSchemaName]` with the tablet
database name. In practice this means that queries like:
SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'data';
are rewritten to queries like:
SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'vt_data';
Tabletserver `Stream()` does not replicate this
behavior, breaking queries like the one above when workload is OLAP.
This PR applies the schema-name-replace logic to `Stream()` calls.
Fixes #11081.
=> tabletserver stream replace schema name bindvar

doc/releasenotes/15_0_0_summary.md, go/cmd/mysqlctld/mysqlctld.go, go/cmd/vtcombo/main.go, go/cmd/vtctld/main.go, go/cmd/vtgate/vtgate.go, go/cmd/vtgateclienttest/main.go, go/cmd/vttablet/vttablet.go, go/cmd/vttestserver/main.go, go/flags/endtoend/vtctld.txt, go/flags/endtoend/vtexplain.txt, go/flags/endtoend/vtgate.txt, go/flags/endtoend/vtgr.txt, go/flags/endtoend/vttablet.txt, go/flagutil/optional.go, go/vt/servenv/grpc_server.go, go/vt/servenv/pprof.go, go/vt/servenv/run.go, go/vt/servenv/servenv.go, go/vt/servenv/servenv_test.go, go/vt/throttler/demo/throttler_demo.go, go/vt/vttablet/onlineddl/executor.go, go/vt/vttest/vtprocess.go
This migrates the flags used by the grpc servers calling into `servenv.Init`, `servenv.Run`, and `servenv.RunDefault`.
⚠️ it also removes the deprecated profliing flags, which were deprecated approximately 18 months ago ⚠️ 
- #11146 
- #11144 
=> [cli] [servenv] Migrate flags used by grpc servers to `pflag`

go/cmd/mysqlctld/mysqlctld.go, go/cmd/vtcombo/main.go, go/cmd/vtctld/main.go, go/cmd/vtgate/vtgate.go, go/cmd/vtgateclienttest/main.go, go/cmd/vttablet/vttablet.go, go/cmd/vttestserver/main.go, go/flags/endtoend/vtctld.txt, go/flags/endtoend/vtexplain.txt, go/flags/endtoend/vtgate.txt, go/flags/endtoend/vtgr.txt, go/flags/endtoend/vttablet.txt, go/vt/servenv/grpc_server.go, go/vt/servenv/pprof.go, go/vt/servenv/pprof_test.go, go/vt/servenv/service_map.go
I unexported `CheckServiceMap` because no one called it except `servenv.GRPCCheckServiceMap`. We can re-export it later if anyone ends up needing it, but this is not a breaking change or anything.
Part of this involved auditing all the paths that can call `GRPCCheckServiceMap`, which I detail ...
<details><summary>here!</summary>
```
➜  vitess $ go list -f '{{ .ImportPath }}| {{ join .Deps " " }} ' ./go/cmd/... ./go/vt/servenv | awk -F"|" '$2 ~ " vitess.io/vitess/go/vt/binlog/grpcbinlogstreamer " {print $1}'
vitess.io/vitess/go/cmd/vttablet
➜  vitess $ go list -f '{{ .ImportPath }}| {{ join .Deps " " }} ' ./go/cmd/... ./go/vt/servenv | awk -F"|" '$2 ~ " vitess.io/vitess/go/vt/vttablet/grpctmserver " {print $1}'
vitess.io/vitess/go/cmd/vttablet
➜  vitess $ go list -f '{{ .ImportPath }}| {{ …
```
=> [cli] [servenv] migrate `--service_map` and `pprof` flags to `pflag`

go/vt/vtctl/grpcvtctldserver/server.go, go/vt/vtctl/grpcvtctldserver/server_test.go
What it says in the title.
After:
```
$ grpcurl -plaintext localhost:15999 vtctlservice.Vtctld.ReloadSchema
ERROR:
Code: Unknown
Message: uncaught panic: runtime error: invalid memory address or nil pointer dereference
$ ps aux | grep vtctld
andrew           79727   0.0  0.3 408764896  44272 s000  S     3:19PM   0:00.07 vtctld --topo_implementation etcd2 --topo_global_server_address localhost:2379 --topo_global_root /vitess/global --cell test --workflow_manager_init --workflow_manager_use_election --service_map grpc-vtctl,grpc-vtctld --backup_storage_implementation file --file_backup_storage_root /Users/andrew/dev/vitess/examples/local/vtdataroot/backups --log_dir /Users/andrew/dev/vitess/examples/local/vtdataroot/tmp --port 15000 --grpc_port 15999 --pid_file …
```
=> Install panic handler for all grpcvtctldserver endpoints

go/flags/endtoend/vtexplain.txt, go/flags/endtoend/vtgr.txt, go/internal/flag/flag.go, go/vt/servenv/grpc_server.go, go/vt/servenv/pid_file.go, go/vt/servenv/servenv.go, go/vt/servenv/unix_socket.go
This one covers `--pid_file` and `--socket_file`, leaving only MySQLVersion and `--version`, which I'll tackle separately.
Relates to #11144 
=> [cli] [servenv] Migrate miscellaneous flags to `pflag`

examples/compose/.env, examples/compose/client.go, examples/compose/client.sh, examples/compose/docker-compose.beginners.yml, examples/compose/docker-compose.yml, examples/compose/lvtctl.sh, examples/compose/schemaload.sh, examples/compose/template.env, examples/compose/vtcompose/docker-compose.test.yml, examples/compose/vtcompose/vtcompose.go, examples/compose/vtorc-up.sh, test/client.go, test/client_test.sh
This PR fixes the docker-compose examples and the `vtcompose` binary used to generate docker-compose files. 
The example was noticed to be broken and issue filed at #11187 
On further investigation of the `vtctld` container which fails to start leads to - 
```bash
docker-compose logs vtctld   
Attaching to compose_vtctld_1
vtctld_1                          | ERROR: logging before flag.Parse: E0908 07:54:24.363388       9 syslogger.go:149] can't connect to syslog
vtctld_1                          | unknown shorthand flag: 't' in -topo_implementation
```
The issue is arising from the flag being set in vtctld binary. We aren't using the double-dashed arguments. This PR fixes this issue.
After this PR all the docker-compose examples have been tested manually, `docker-compose.yml`, …
=> Fix vtcompose and docker-compose examples

go/test/endtoend/vreplication/migrate_test.go, go/vt/discovery/tablet_picker.go, go/vt/vttablet/tabletmanager/vdiff/action.go, go/vt/vttablet/tabletmanager/vdiff/controller.go, go/vt/vttablet/tabletmanager/vdiff/table_differ.go
This adds support for doing VDiffs — using [VDiff2](https://vitess.io/docs/15.0/reference/vreplication/vdiff2/) — against intercluster VReplication workflows created using the [Mount](https://vitess.io/docs/15.0/reference/vreplication/mount/) and [Migrate](https://vitess.io/docs/15.0/reference/vreplication/migrate/) commands.
- Fixes: https://github.com/vitessio/vitess/issues/11182
-   [x] Tests were enabled
-   [x] Documentation is not required (it was expected to work)
=> VDiff2: Add support for Mount+Migrate

go/vt/vtgate/planbuilder/physical/route.go, go/vt/vtgate/planbuilder/testdata/select_cases.txt
This improves routing mergeability and vindex selection by treating `IN` operations with single value tuples like `Equal` operations.
A query like this:
```sql
SELECT music.id FROM music WHERE music.user_id IN (5)
```
Will now have a plan like this:
```json
{
"Original": "SELECT music.id FROM music WHERE music.user_id IN (5)",
"Variant": "EqualUnique",
"Keyspace": {
},
"FieldQuery": "select music.id from music where 1 != 1",
"Query": "select music.id from music where music.user_id in (5)",
"Table": "music",
"Values": [
"INT64(5)"
],
"Vindex": "user_index"
},
"TablesUsed": [
"user.music"
]
}
```
---
This is a very simple fix for this issue, and it does not handle the following edge cases:
* …
=> Treat `IN` operations on single value tuples as `Equal` operations.

go/vt/vtgate/planbuilder/physical/route.go, go/vt/vtgate/planbuilder/physical/route_planning.go, go/vt/vtgate/planbuilder/physical/subquery_planning.go, go/vt/vtgate/planbuilder/testdata/select_cases.txt
In the Gen4 planner, `Route` structs hold a list of predicates that can influence the routing decisions (`SeenPredicates`). When merging inner queries into their outer query, vindex predicates are reset and their options are rebuild from this list of seen predicates.
Unfortunately, when a route object was build for an `ApplyJoin` operator, the lists of `SeenPredicates` from the left and right parts of the join were not copied over into the new route object. If a subquery was then merged into this `Route`, the vindex predicate options could not be rebuild and the resulting route would become a `Scatter`.
By merging the `SeenPredicates` lists of both sides of the join, we can ensure that the vindex predicate reset actually works correctly, and the correct vindex is used for routing.
This is …
=> [Gen4] Merge `SeenPredicates` when creating route operator for join

go/flags/endtoend/vttablet.txt, go/test/endtoend/tabletmanager/replication_manager/tablet_test.go, go/vt/vttablet/tabletmanager/replmanager.go, go/vt/vttablet/tabletmanager/rpc_replication.go, go/vt/vttablet/tabletmanager/rpc_replication_test.go, test/config.json
This PR improves the replication manager. The proposed improvements are two-fold - 
1. The first is that the replication manager should be able to catch the case where the replication is broken because the primary's hostname and port changed due to kubernetes pod reschedule or some other reason. 
2. The second improvement is the addition of a flag that allows the replication manager to be turned off, if so desired.
Tests of both these changes have been added. An end to end test for the first one and a unit test for the other.
#9809 
=> Replication Manager Improvements

go/test/endtoend/vreplication/vreplication_test.go
`TestVreplicationCopyThrottling` has been somewhat flaky over the last week. I suspect it was due to the CI slowness experienced during GitHub's recent partial outages (due to a DDOS attack, I believe). Whatever the causes, this PR makes two changes which should eliminate the failures that I could find:
1. Extends the transaction timeout, as we rely on holding open transactions for some time with many changes (I saw failures were the transaction timed out during the final `rollback` statement). 
2. Adds a waitFor function that waits for the expected innodb history list length before moving forward (I didn't see any failures in the CI for this but I did see it locally)
I ran this locally and did not see any more failures:
```
$ for try in {1..100}; do go clean -testcache; go test -timeout …
```
=> Flakes: Eliminate TestVreplicationCopyThrottling Flakes

go/vt/vttablet/tabletserver/connpool/pool.go, go/vt/vttablet/tabletserver/connpool/pool_test.go
This PR added a metric called `GetConnTime` with labels `with` and `without` for `settings`, that publishes the amount of time it took to get a connection with and without having settings respectively.
- #9706 
=> Add Metric For Time Elapsed In Getting Connection In Pools

go/mysql/binlog_event_rbr.go, go/test/endtoend/vreplication/config_test.go, go/test/endtoend/vreplication/vreplication_test.go, go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go
With a 0 scale decimal field, with a value of 0, the parsed RBR event has an empty 0 byte length value. This then resulted in a `DECIMAL()` value getting used as the bind variable that in turn resulted in an invalid SQL query. More details can be found in [the issue](https://github.com/vitessio/vitess/issues/11210).
- Fixes: https://github.com/vitessio/vitess/issues/11210
=> VReplication: Handle DECIMAL 0 Value Edge Case

go/vt/vttablet/onlineddl/executor.go
Today, when the Online DDL executor attempts to run a migration that has a conflict, vitess returns a generic error message: 
> cannot run migration since a migration is already running
As of this PR, the message indicates the UUID and table name that cause the conflict. UUID is enough, but table name is added for more clarity.
#6926
=> Online DDL: more info in a conflicting migration message

go/vt/vtgate/engine/delete.go, go/vt/vtgate/planbuilder/abstract/delete.go, go/vt/vtgate/planbuilder/abstract/operator.go, go/vt/vtgate/planbuilder/builder.go, go/vt/vtgate/planbuilder/delete.go, go/vt/vtgate/planbuilder/gen4_planner.go, go/vt/vtgate/planbuilder/operator_transformers.go, go/vt/vtgate/planbuilder/physical/delete.go, go/vt/vtgate/planbuilder/physical/route_planning.go, go/vt/vtgate/planbuilder/testdata/dml_cases.txt, go/vt/vtgate/planbuilder/testdata/oltp_cases.txt, go/vt/vtgate/planbuilder/testdata/tpcc_cases.txt, go/vt/vtgate/semantics/scoper.go
This PR adds delete planning to Gen4 planner. This was required specifically for the following types of queries leads to incorrect tables used populated by v3 - 
```json
"delete foo from unsharded as foo join (select id from unsharded a join unsharded_b b on a.user_id = b.user_id) as keepers on foo.id = keepers.id where keepers.id is null and foo.col is not null and foo.col \u003c 1000"
{
"QueryType": "DELETE",
"Original": "delete foo from unsharded as foo join (select id from unsharded a join unsharded_b b on a.user_id = b.user_id) as keepers on foo.id = keepers.id where keepers.id is null and foo.col is not null and foo.col \u003c 1000",
"OperatorType": "Delete",
"Variant": "Unsharded",
"Keyspace": {
"Name": "main",
"Sharded": false
},
"TargetTabletType": "PRIMARY", …
```
=> Adds delete planning to Gen4

go/test/endtoend/vreplication/helper_test.go, go/test/endtoend/vreplication/migrate_test.go, go/test/endtoend/vreplication/resharding_workflows_v2_test.go, go/test/endtoend/vreplication/vreplication_test.go
The `TestVReplicationCopyThrottling` test — which is included in the `vreplication_basic` GitHub Actions workflow — continued to be flaky (especially with 8.0) after https://github.com/vitessio/vitess/pull/11208.
The primary issue was that there was a race condition that the test was not accounting for. That is, during the period of time between when the VReplication workflow starts and sets the state to `Running`, and where it finishes the initial setup of the copy phase before finally setting the state to `Copying` here: https://github.com/vitessio/vitess/blob/b277bcb871e847c6fb280431d6cf8e62aa455ff7/go/vt/vttablet/tabletmanager/vreplication/vcopier.go#L81
If we looked at the `vtctlclient Workflow show` output during that time, the state would be `Running` which in the test we …
=> Flakes: Correct TestVReplicationCopyThrottling Logic

tools/do_release.sh
=> [release-14.0] Improve the `do_release` script to have two different Pull Requests instead of one during a release

tools/do_release.sh
=> [release-13.0] Improve the `do_release` script to have two different Pull Requests instead of one during a release

go/test/endtoend/vreplication/vreplication_test.go, go/vt/wrangler/vdiff.go, go/vt/wrangler/vdiff2.go
https://github.com/vitessio/vitess/issues/11233 has details on the issue this PR is trying to fix. 
The root cause is that `SwitchWrites` will `Stop` the workflows on the target since writes have now been switched to them. However `vdiff` restarts workflows once it is done irrespective of the previous status of the workflow. 
As part of `SwitchWrites` all streams in a workflow are marked as `frozen`.  This PR adds a check in `VDiff` (both v1 and v2) and does not start it in case the workflow is found to be frozen.
This is the most common issue that has been reported related to VDiff starting stopped workflows. Another use-case would be if the user had stopped a workflow for some reason.  That requires some more discussion: on the one hand we can look for Stopped workflow and not restart …
=> Don't run VDiff on frozen workflows

go/test/endtoend/vtgate/queries/insert/insert_test.go, go/vt/vtgate/engine/insert.go
This PR fixes the bug in insert using select streaming. The fix is to serialize the processing of streaming select.
The underlying issue was causing re-use of same transaction on vttablet in parallel and causing in an error,
- Fixes https://github.com/vitessio/vitess/issues/11247
-   [ ] "Backport me!" label has been added if this change should be backported - The feature itself exists only on main.
=> Fix: Insert using select streaming bug

go/test/endtoend/vtorc/general/vtorc_test.go, go/test/endtoend/vtorc/utils/utils.go, go/vt/orchestrator/inst/instance_dao.go
This PR is a backport of https://github.com/vitessio/vitess/pull/10662 to releaes-14.0
- #10650 
=> Backport to release-14: Fix VTOrc Discovery to also retry discovering tablets which aren't present in database_instance table

Makefile, go/tools/sizegen/sizegen.go, go/vt/vtctl/grpcvtctldclient/client.go, go/vt/vtctl/localvtctldclient/client.go, go/vt/vtctl/vtctldclient/codegen/main.go
This migrates the following tools to pflag:
- `go/vt/vtctl/vtctldclient/codegen`
- `go/tools/sizegen`
Running both make targets (`make vtctldclient sizegen`) works with no diffs.
- Closes #11300 
- Closes #11305 
=> [cli] Misc pflag binary migrations

go/vt/vtgate/planbuilder/rewrite_test.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/postprocess_cases.txt, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/semantics/analyzer_test.go, go/vt/vtgate/semantics/binder.go, go/vt/vtgate/semantics/early_rewriter.go, go/vt/vtgate/semantics/early_rewriter_test.go
When trying to figure out the offsets for some HAVING and ORDER BY expression, it's much easier for the planner if we have the real aggregation function and not the column alias introduced. This PR rewrites these queries, so later phases of the planner don't have to take this possibility into account.
Example:
```sql
select id, sum(foo) as sumOfFoo from tbl group by id having sumOfFoo > 10
```
will get rewritten to:
```sql
select id, sum(foo) as sumOfFoo from tbl group by id having sum(foo) > 10
```
=> feat: rewrite column names in HAVING

go/vt/vtgate/planbuilder/abstract/filter.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt
This fixes an edge case where a comparison using the `<=>` operator would prevent the use of any following predicates after for routing purposes (only on left joins).
Here's an example query:
```sql
SELECT music.id FROM music LEFT OUTER JOIN user ON music.user_id = user.id WHERE user.id <=> NULL AND music.user_id = 10
```
This would generate the following plan:
```json
{
"Original": "SELECT music.id FROM music LEFT OUTER JOIN user ON music.user_id = user.id WHERE user.id \u003c=\u003e NULL AND music.user_id = 10",
"Variant": "Scatter",
"Keyspace": {
},
"FieldQuery": "select music.id from music left join `user` on music.user_id = `user`.id where 1 != 1",
"Query": "select music.id from music …
```
=> Fix conditions after `<=>` operator on left joined table columns being ignored for routing purposes.

go/test/endtoend/vtgate/queries/orderby/without_schematracker/main_test.go, go/test/endtoend/vtgate/queries/orderby/without_schematracker/orderby_test.go, go/test/endtoend/vtgate/queries/orderby/without_schematracker/schema.sql, go/test/endtoend/vtgate/queries/orderby/without_schematracker/vschema.json, go/vt/vtgate/engine/route.go
When we have to do the sorting on the vtgate level, we were not correctly truncating the columns to match the number of columns the user asked for.
Fixes #11261
=> bugfix: Truncate columns even when sorting on vtgate

go/vt/vtgate/planbuilder/abstract/join.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt
Complex `WHERE` predicates for joined tables (stuff along the lines of `(lhs.a = ... OR rhs.b = ...)` or even just `lhs.a = rhs.b`) are pulled into the join conditions. This makes sense for `INNER JOIN` statements, but for `LEFT JOIN` statements this will cause the result to be totally wrong.
This PR fixes this issue by performing this movement of predicates only for non-`LEFT JOIN`s. On top of that, we now also detect more cases where `LEFT JOIN`s can be transformed to `INNER JOIN`s due to "null intolerant" comparisons (e.g. `lhs.a = rhs.b` in the `WHERE` condition allows rewriting a left join between `lhs` and `rhs` to an inner join).
```sql
SELECT music.id FROM music LEFT OUTER JOIN user ON music.user_id = user.id WHERE (user.name = 'Trent Reznor' OR music.genre = 'pop') AND …
```
=> Fix complex predicates being pulled into `ON` conditions for `LEFT JOIN` statements.

examples/local/101_initial_cluster.sh, examples/local/201_customer_tablets.sh, examples/local/201_newkeyspace_tablets.sh, examples/local/302_new_shards.sh, examples/region_sharding/101_initial_cluster.sh, examples/region_sharding/202_new_tablets.sh
Since we introduced VTOrc to also be part of the local and region sharding examples, the tests have been flaky as pointed out in https://github.com/vitessio/vitess/issues/11295. 
This PR fixes the second problem mentioned in https://github.com/vitessio/vitess/issues/11295#issuecomment-1253910772. The problem was arising from the part where we were calling `InitShardPrimary` after VTOrc already initialized the shard. The fix is really simple, just not calling `InitShardPrimary`.
Instead, the call to `ISP` is replaced by code to wait until VTOrc has elected a primary.
- Fixes #11295 
=> Fix local example scripts

go/cmd/vttestserver/main.go, go/cmd/vttestserver/vttestserver_test.go, go/flags/endtoend/flags_test.go, go/flags/endtoend/vttestserver.txt
This PR ports the flags parsing in the package `go/cmd/vttestserver` to use pflags instead. 
- Fixes #11290 
=> [cli] `vttestserver` flag parsing to use pflags

go/vt/vttablet/customrule/filecustomrule/filecustomrule.go, go/vt/vttablet/customrule/topocustomrule/topocustomrule.go
This migrates the following tools to pflag:
* `go/vt/vttablet/customrule/filecustomrule`
* `go/vt/vttablet/customrule/topocustomrule`
- Closes https://github.com/vitessio/vitess/issues/10971
- Closes https://github.com/vitessio/vitess/issues/10972
=> customrule pflags migration

.gitignore, go/mysql/binlog_event_rbr.go, go/test/endtoend/vreplication/config_test.go, go/test/endtoend/vreplication/helper_test.go, go/test/endtoend/vreplication/materialize_test.go, go/test/endtoend/vreplication/migrate_test.go, go/test/endtoend/vreplication/performance_test.go, go/test/endtoend/vreplication/resharding_workflows_v2_test.go, go/test/endtoend/vreplication/vreplication_test.go, go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go
This is a backport of https://github.com/vitessio/vitess/pull/11212. Please see [the issue](https://github.com/vitessio/vitess/issues/11210) for more details. It also backports a test-only dependency: https://github.com/vitessio/vitess/pull/11048
Lastly, I addressed the `TestVReplicationCopyThrottling` flakiness here as well by backporting https://github.com/vitessio/vitess/pull/11208 and https://github.com/vitessio/vitess/pull/11224.
- Backports: https://github.com/vitessio/vitess/pull/11212
- Backports (dep): https://github.com/vitessio/vitess/pull/11048
- Backports: https://github.com/vitessio/vitess/pull/11208
- Backports: https://github.com/vitessio/vitess/pull/11224
- Fixes: https://github.com/vitessio/vitess/issues/11210
-   [x] "Backport me!" label has been added if this change …
=> Backport-v14: VReplication: Handle DECIMAL 0 Value Edge Case #11212

go/test/endtoend/cluster/cluster_process.go, go/test/endtoend/cluster/vtorc_process.go, go/test/endtoend/vtorc/general/vtorc_test.go, go/test/endtoend/vtorc/primaryfailure/primary_failure_test.go, go/test/endtoend/vtorc/utils/utils.go, go/vt/vtorc/logic/topology_recovery.go
This PR adds metrics to VTOrc to track the different number of recoveries that it runs and the count of them that fail and succeed.
The debug/vars page looks like the following after these changes - 
- #6612 
=> Addition of Metrics to VTOrc to track the number of recoveries ran and their success count.

go/cmd/vtctld/schema.go, go/flags/endtoend/vtctld.txt, go/flagutil/flagutil.go, go/flagutil/flagutil_test.go
As a bonus, introduces a new flag type so I could move the `schemaChangeCheckInterval` flag from "give us an int and we'll force it into seconds" to "we will accept an actual time.Duration argument" without breaking anyone.
- Closes #11282 
=> [cli] Migrate cmd/vtctld to pflag

go/cmd/vtclient/vtclient.go, go/cmd/vtclient/vtclient_test.go, go/cmd/vttablet/vttablet.go, go/flags/endtoend/vttablet.txt
Migrate the vtclient and vttablet cmds to pflag
Fixes #11288
Fixes #11289
=> [cli] Migrate cmd/vtclient and cmd/vttablet from flag to pflag 

go/test/endtoend/vtcombo/vttest_sample_test.go, go/vt/vtcombo/tablet_map.go, go/vt/vttablet/tabletserver/query_executor.go
When using vtcombo to run unit tests, we noticed that for transactional tests, transactions didn't seem to be obeyed. Upon further inspection, statements inside of a transaction would always get autocommitted. We could not reproduce this with actual vtgates/vttablets, so it had to be isolated to vtcombo. Turns out, the `options` [here](https://github.com/vitessio/vitess/blob/b277bcb871e847c6fb280431d6cf8e62aa455ff7/go/vt/vtcombo/tablet_map.go#L441-L454) would get mutated [here](https://github.com/vitessio/vitess/blob/1487772f3d59c5fc6fb221402a5100f90c69857f/go/vt/vttablet/tabletserver/query_executor.go#L199), so any previous query that was indeed autocommit=true and not in a transaction would cause future queries to have `qre.options.TransactionIsolation = …
=> vtcombo mutates options, make a copy to avoid this

go/flags/endtoend/vtctld.txt, go/vt/vtctld/action_repository.go, go/vt/vtctld/api.go, go/vt/vtctld/tablet_data.go, go/vt/vtctld/vtctld.go, go/vt/vtctld/workflow.go
Updates vtctld related flag references specified in https://github.com/vitessio/vitess/issues/10893
Modules for flag registration
go list -f '{{ .ImportPath }}| {{ join .Deps " " }} ' ./go/cmd/... | awk -F"|" '$2 ~ "vitess.io/vitess/go/vt/vtctld" {print $1}'
vitess.io/vitess/go/cmd/vtcombo
fixes #10893
=> [cli] [vtctld] Migrate vtctld flags to pflags

go/test/endtoend/vtorc/gracefultakeover/graceful_takeover_test.go, go/test/endtoend/vtorc/utils/utils.go, go/vt/vtorc/logic/topology_recovery.go
This PR fixes the flakiness in `TestGracefulPrimaryTakeover`. 
The flakiness has been present for a while but was very hard to track down until now. After moving the vtorc tests to self-hosted runners, we were finally able to get hold of a failing run at https://github.com/vitessio/vitess/actions/runs/3125969525/jobs/5070929614 which on investigation uncovered the flakiness.
It was noticed in the failing test that the `GracefulPrimaryTakeover` call failed with a status 500. It was found in the logs that the call to `GracefulPrimaryTakeover` was racing with the completion of the previous `ClusterHasNoPrimary` recovery.
At the end of the `ClusterHasNoPrimaryRecovery`, VTOrc refreshes all the information for all the tablets of the shard. This is done because we have run a PRS and we know the …
=> Flakiness Fix: Tests for GracefulPrimaryTakeover

MAINTAINERS.md
This PR fixes a typo in the MAINTAINERS.md file regarding my work email address and adds me to the `build` section.
=> Fix frouioui in the MAINTAINERS.md file

docker/vttestserver/run.sh
This PR fixes the vttestserver docker image by fixing the flags passed to the vttestserver binary by it. This change is required since we moved to the `pflag` package to parse flags which required double-dashed arguments.
- Fixes #11353 
=> Fix flags in vttestserver run script used in the docker image

go/vt/vtgate/executor_framework_test.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/scatter_conn.go
This PR ensures that connection is only reserved when a get_lock advisory function is present in the query.
- Closes https://github.com/vitessio/vitess/issues/10436
=> advisory lock to acquire reserve connection only for get_lock

go/test/endtoend/backup/transform/backup_transform_utils.go, go/test/endtoend/backup/vtbackup/backup_only_test.go, test/config.json
The `TestBackupTransform` test was not fully adjusted for MySQL Semi-Sync replication when we enabled it for all tests. I say that because the test only initially setup a single PRIMARY and a single REPLICA tablet. With [lossless semi-sync](http://my-replication-life.blogspot.com/2013/09/loss-less-semi-synchronous-replication.html) — which is [the default ](https://dev.mysql.com/doc/refman/en/replication-options-source.html#sysvar_rpl_semi_sync_master_wait_point)— this means that we only have a single ACKer and if that ACKer / REPLICA tablet is shutdown after receiving the GTID but before ACKing it, the GTID will exist on the REPLICA (will be applied from the local relay log by the time it starts up again) but will NOT exist on the PRIMARY. At this point the PRIMARY is also left …
=> Flakes: Fix Backup Transform Test Flakiness

go/flags/endtoend/vttablet.txt, go/test/endtoend/vreplication/vreplication_test.go, go/vt/vttablet/tabletserver/vstreamer/engine.go, go/vt/vttablet/tabletserver/vstreamer/resultstreamer.go, go/vt/vttablet/tabletserver/vstreamer/rowstreamer.go, go/vt/vttablet/tabletserver/vstreamer/snapshot_conn.go, test/config.json
Rotate the binary logs as needed in order to limit the GTID auto positioning overhead when starting a results/row stream from a given GTID set/position in VStreams. This is needed as the currently open binary log (which can be up to 1G in size by default) will need to be scanned and empty GTID events will be streamed for those GTIDs in the log that we are skipping. In total, this can add a lot of overhead on both the mysqld instance and the tablet. It can also cause a significant delay — particularly on connections with higher latency such as when the source and target are communicating over the internet with TLS — for otherwise fast actions such as VDiff on relatively small tables. Rotating the log ensures that we are processing a fresh binary log that will be minimal in size and GTID …
=> VStreams: Rotate Binary Log For Snapshot Connections

go/vt/vtgate/planbuilder/abstract/derived.go, go/vt/vtgate/planbuilder/physical/operator_funcs.go, go/vt/vtgate/planbuilder/physical/route_planning.go, go/vt/vtgate/planbuilder/projection_pushing.go, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/semantics/semantic_state.go
When pushing predicates and projections into derived tables, we were not catching the outer rewrite.
=> fix: store the output of the rewrite

go/flags/endtoend/vtgate.txt, go/test/endtoend/cluster/cluster_process.go, go/test/endtoend/vreplication/resharding_workflows_v2_test.go, go/vt/vtgate/planbuilder/bypass.go, go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/planbuilder/plancontext/vschema.go, go/vt/vtgate/vcursor_impl.go, go/vt/vtgate/vtgate.go
This PR addresses some review comments from https://github.com/vitessio/vitess/pull/9987
=> refactor: minor refactor in partial shard routing  and change in flag to dashes

go/tools/release-notes/release_notes.go
This Pull Request changes the release notes generation script to natively include a link for each Pull Request in the change log. This way, the users reading the change log can quickly click and see the Pull Request associated with a change.
- Fixes https://github.com/vitessio/vitess/issues/11240
=> Add hyperlink in the release changelog

Makefile, go/tools/release-notes/release_notes.go
This PR changes the `release-notes` package to use pflag instead of the old flag system.
- Closes #11299
- Part of https://github.com/vitessio/vitess/issues/10697
=> Migrates `release-notes` to pflag

go/cmd/topo2topo/topo2topo.go
Updates mysqlctl related flag references specified in https://github.com/vitessio/vitess/issues/11106
possible package using this flags.
go list -f '{{ .ImportPath }}| {{ join .Deps " " }} ' ./go/cmd/... | awk -F"|" '$2 ~ "vitess.io/vitess/go/cmd" {print $1}'
vitess.io/vitess/go/cmd/mysqlctl
vitess.io/vitess/go/cmd/rulesctl
vitess.io/vitess/go/cmd/rulesctl/cmd
vitess.io/vitess/go/cmd/vtbackup
vitess.io/vitess/go/cmd/vtcombo
vitess.io/vitess/go/cmd/vtctl
vitess.io/vitess/go/cmd/vtctldclient
vitess.io/vitess/go/cmd/vtctldclient/command
vitess.io/vitess/go/cmd/vtctldclient/docgen
vitess.io/vitess/go/cmd/vtgateclienttest
vitess.io/vitess/go/cmd/zk
#11106
-   [ ] "Backport me!" label has been added if …
=> [cli] [topo] Migrate topo2topo flags to pflags

go/cmd/vtctldclient/main.go, go/flags/endtoend/vtctlclient.txt, go/flags/endtoend/vtctldclient.txt, go/flags/endtoend/vttestserver.txt, go/vt/vtctl/vtctlclient/interface.go, go/vt/wrangler/testlib/vtctl_pipe.go
Title says it all.
- Closes #10892.
=> [vtctlclient] Migrate `vtctl_client_protocol` to pflag

go/internal/flag/flag.go, go/mysql/collations/integration/main_test.go, go/vt/vtgate/evalengine/integration/fuzz_test.go
This PR moves the evalengine integration tests package to use pflags instead of flags.
- Fixes https://github.com/vitessio/vitess/issues/10933
=> Move evalengine integration tests to use pflags

go/vt/schema/ddl_strategy.go, go/vt/vtctl/vtctl.go
Followup to #8450 and #9816, this PR removes a deprecated function from the code.
#6926
=> Remove deprecated IsSkipTopo() function

go/cmd/vtaclcheck/vtaclcheck.go, go/flags/endtoend/flags_test.go, go/flags/endtoend/vtaclcheck.txt
Switches flag definitions to be on pflag instead of flag for `go/cmd/vtaclcheck`.
This is a stand-alone binary that uses a dedicated `vtaclcheck` package:
```
$ go list -f '{{ .ImportPath }}| {{ join .Deps " " }} ' ./go/cmd/... | awk -F"|" '$2 ~ " vitess.io/vitess/go/vt/vtaclcheck " {print $1}'
vitess.io/vitess/go/cmd/vtaclcheck
```
- Fixes: https://github.com/vitessio/vitess/issues/11278
=> Move vtaclcheck command to pflags

go/cmd/vtexplain/vtexplain.go
Switches `vtexplain` to use pflags according to https://github.com/vitessio/vitess/issues/10697
Fixes #11285
=> [vtexplain] Migrate to pflags

go/cmd/mysqlctl/mysqlctl.go, go/flags/endtoend/flags_test.go, go/flags/endtoend/mysqlctl.txt, go/vt/grpcclient/client.go, go/vt/mysqlctl/mycnf_flag.go
This migrates the `mysqlctl` command/binary and the `mysqlctl` package from go flag to pflag.
- Fixes: https://github.com/vitessio/vitess/issues/11266
=> Migrate mysqlctl command and package to pflag

go/cmd/vtctldclient/command/legacy_shim.go
Moving from the standard library to our custom interoperability function.
Closes #11284.
=> [cli] Use pflag/flag interop function in vtctldclient legacy shim

doc/releasenotes/14_0_3_summary.md
This PR adds the release summary for `v14.0.3`.
=> Addition of the release summary for `v14.0.3`

go/test/endtoend/vreplication/vschema_load_test.go, go/vt/vttablet/tabletserver/vstreamer/engine.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go, test/config.json
This fixes the bug reported in  https://github.com/vitessio/vitess/issues/11169
Pre-conditions for bug:
1. There is a vstreamer client that is subscribed to, but not reading events fast enough, from a Replica
2. There are a lot of VSchema changes at this time
3. A PRS happens at this time, switching this Replica to a Primary
Bug cause:
1. In `vstreamer.SetVSchema()`  the new vschema is written to a single message buffered channel for each active vstreamer. This is read by the vstreamer event processor, holding the vstreamer engine mutex.
2. In the vstreamer event processor there are two parallel `case` statements: one reads from the vschema channel and other reads the binlog events. The binlog events are streamed to the receiver. If the receiver is not reading them then the send will …
=> VStreamer: fix deadlock when there are a lot of vschema changes at the same time as binlog events

go/vt/mysqlctl/s3backupstorage/s3.go
```
I0818 19:08:27.040771       1 s3.go:261] ListBackups: [s3] dir: mytestshard/-80, bucket: mytestbucket
I0818 19:08:27.040823       1 shard_sync.go:70] Change to tablet state
I0818 19:08:27.061923       1 s3.go:273] objName: 0xc0012faaa0
```
objName is currently printing the memory address of searchPrefix instead of the string.
=> fix: objname was not logged correctly

go/vt/topo/etcd2topo/lock.go, go/vt/topo/etcd2topo/server.go, go/vt/topo/etcd2topo/server_test.go
Updates topo related flag references specified in #10859 
```
$ go list -f '{{ .ImportPath }}| {{ join .Deps " " }} ' ./go/cmd/... | awk -F"|" '$2 ~ "vitess.io/vitess/go/vt/topo/etcd2topo" {print $1}'
vitess.io/vitess/go/cmd/topo2topo
vitess.io/vitess/go/cmd/vtbackup
vitess.io/vitess/go/cmd/vtcombo
vitess.io/vitess/go/cmd/vtctl
vitess.io/vitess/go/cmd/vtgate
vitess.io/vitess/go/cmd/vtgr
vitess.io/vitess/go/cmd/vtorc
vitess.io/vitess/go/cmd/vttablet
vitess.io/vitess/go/cmd/vttestserver
vitess.io/vitess/go/cmd/zk
```
closes #10859 …
=> [cli] [etcd2] Migrate etcd2topo flags to pflags

tools/rowlog/rowlog.go
Also some tidying, and a new flag to handle that resumability test commented-out code
Closes #11408 
=> [tools/rowlog] Migrate to pflag

doc/releasenotes/15_0_0_summary.md, go/cmd/vtctlclient/main.go, go/test/endtoend/recovery/pitr/shardedpitr_test.go, go/test/endtoend/vreplication/vreplication_test.go, go/vt/topo/stats_conn.go, go/vt/topo/stats_conn_test.go, go/vt/vtctl/vtctl.go
- remove `master` stats
- remove deprecated vtctl command sub flags
- add deprecation notice for `prefill` flags
#5960
=> flags etc: delete old flags and stats, add deprecation notice to release notes

go/flags/endtoend/vtbackup.txt, go/vt/mysqlctl/backup.go, go/vt/mysqlctl/backupengine.go, go/vt/mysqlctl/xtrabackupengine.go
This PR adds the flags that `vtbackup` needs but we missed to add them during the flag work. These were found because of VTop failures while running the backup end to end tests.
- #10697 
=> Fix vtbackup binary by adding the flags it needs that we missed before

go/vt/sqlparser/ast_rewriting.go, go/vt/sqlparser/ast_rewriting_test.go, go/vt/vtgate/planbuilder/physical/filter.go, go/vt/vtgate/planbuilder/testdata/select_cases.txt
The Vitess vtgate planner was doing an bad query rewrite. A query such as this:
```sql
select 1 as x, (select x)
```
would get rewritten to:
```sql
select 1 as x, x as `(select x)`
```
This PR stops these rewrites from being performed.
Fixes #11246
=> fix: do not rewrite single columns in derived tables

go/vt/servenv/servenv.go
With the recent flag changes, we discovered that VTop binary broke. The Vitess-operator requires the backup flags like `bakcup_storage_implementation`, `ceph_backup_storage_config` among others. Previously, when we used the `flag` package these got implicitly imported when we imported the packages that defined these flags. Now that we have moved to the `pflag` package, we register the flags only for the binaries that require it. This leads to the flags not being registered in the vitess-operator binary. 
One possible solution would have been to add the `vitess-operator` binary to the list of the binaries where we register certain flags, but that doesn't seem the best approach because it adds a cross-repository code-base dependency. Instead, an alternate fix is proposed in this PR.
This PR …
=> VTop: Adds a function to get the flag set for a given command

.github/workflows/code_freeze.yml
This PR is to code freeze release 15.0 branch. 
#11425 
=> Code freeze of release-15.0

go/vt/vtgate/evalengine/func.go, go/vt/vtgate/evalengine/translate_test.go
The `NULLIF` and `IFNULL` functions in MySQL are easy to rewrite into `CASE` expressions, so that's what I did.
=> [evalengine] add rewrites for nullif and ifnull

go/mysql/collations/env.go, go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go
With MySQL 8.0.30 and later, utf8mb3 is always reported as the charset in output for `SHOW CREATE TABLE` which is what `schemadiff` uses. We already today normalize all `charset` output to use the `utf8mb3` name to avoid any ambiguity in what is intended.
We didn't do this though for collations. Today if `schemadiff` is fed schemas generated both with MySQL 8.0.30 and older versions to compare, it would indicate there's a difference when there is none.
The change here always normalizes to use the more explicit `utf8mb3_` names for the collation if it can be found, based on the charset aliases configured. This ensures that comparisons between such schemas don't see accidental or stray diffs that are not really changes.
This is part of the #10203 schemadiff work.
-   [x] "Backport me!" …
=> Handle aliasing of collation names

go/test/endtoend/vreplication/helper_test.go, go/test/endtoend/vreplication/partial_movetables_test.go, go/test/endtoend/vreplication/resharding_workflows_v2_test.go, go/vt/vtctl/workflow/state.go, go/vt/wrangler/materializer.go, go/vt/wrangler/switcher.go, go/vt/wrangler/switcher_dry_run.go, go/vt/wrangler/switcher_interface.go, go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/workflow.go
For normal `MoveTables` operations — where you're moving tables from one keyspace to another, i.e. the move is at the keyspace level — global routing rules are put in place when the workflow is created so that any attempted access of those tables on the target keyspace are routed to the source keyspace. (In this scenario shard targeting is how you would explicitly get around this routing.)
For partial `MoveTables` operations, you're moving the tables from one keyspace to another **one shard at a time** — so the move is **per shard** rather than per keyspace. In this scenario you want all traffic to go to one side or the other for a given shard, *including* shard targeted queries. This then offers the same kind of "global" (scoped to a shard) routing at the shard level that you would …
=> Backport: For partial MoveTables, setup reverse shard routing rules on workflow creation

go/test/endtoend/vtgate/queries/aggregation/schema.sql
This PR adds a primary key to the E2E aggregation tests. The PK was missing from one of the tables.
=> Add a PRIMARY KEY to the aggregation E2E tests

examples/local/vtadmin/rbac.yaml, examples/region_sharding/vtadmin/rbac.yaml
Today while running the local example I noticed that we don't give all the permissions to the users when we run the local-examples. This leads to the user not being able to manage the tablets' replication from the vtadmin page. This is a little counter-intuitive and not easy to debug. For first time users of Vitess, all the vtadmin operations should work without any issues. Rbac is a more of advanced thing that is of more importance when going into production.
This PR fixes the examples to give all the users all the accesses available so that everything works without any issues.
=> Give all permissions in rbac in examples

go/mysql/collations/integration/coercion_test.go
The `TestComparisonSemantics` test started failing after a recent release of MySQL. This will unblock the failure on the `Unit Test (mysql80)` workflow. 
> @vmg: Oracle has released a new MySQL minor version that changes some coercion rules. While we figure out what they changed and whether it was intentional, let's skip this test.
=> Skip `TestComparisonSemantics` test

go/cmd/vtadmin/main.go
I accidentally stumbled over the behavior outlined in `flag.PrintDefaults` [1], which `pflag` replicates, specifically:
> The listed type, here int, can be changed by placing a back-quoted
> name in the flag's usage string; the first such item in the message is
> taken to be a parameter name to show in the message and the back quotes
> are stripped from the message when displayed.
[1]: https://pkg.go.dev/flag#PrintDefaults.
https://github.com/rohit-nayak-ps/vreplication-docs/pull/2#pullrequestreview-1137468150
=> [vtadmin] Do not backtick binary name

web/vtadmin/src/components/routes/tablet/FullStatus.tsx
The PR https://github.com/vitessio/vitess/pull/11438 introduced the `Full Status` tab in the vttablets in VTAdmin which shows the full replication status of the tablets. 
In this output it was noticed that the IO state and SQL state are printed as integers (because they are stored as an enum), instead of any meaningful output, so it becomes hard for the users to read this data unless they are familiar with Vitess internals on how the enum works.
This PR attempts to improve this situation by decoding these values before printing them using a replacer function in the `json.Stringify`.
Another thing that was noticed was that the semi-sync properties weren't printed if they are false. This is not desirable. We instead always want to print these settings. This PR addresses this too. It checks …
=> Full Status tab improvements for VTAdmin

go/mysql/collations/integration/coercion_test.go
=> [release-14.0] Skip TestComparisonSemantics

go/mysql/collations/integration/coercion_test.go
=> [release-15.0] Skip TestComparisonSemantics

go/mysql/collations/integration/coercion_test.go
=> [release-13.0] Skip TestComparisonSemantics

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
This is a follow up of https://github.com/vitessio/vitess/pull/11473. The tests became flaky because the index has to be unique.
=> Change the indexes in `TestEmptyTableAggr` to be unique

go/mysql/collations/coercion.go, go/mysql/collations/integration/coercion_test.go
From the MySQL 8.0.31 release notes:
>  When comparing two string values with explicit COLLATE clauses, these should have the same collation, else the comparison should be rejected, but this was not always enforced. 
This was breaking the build.
=> collations: fix coercion semantics according to 8.0.31 changes

go/vt/vtgate/planbuilder/testdata/filter_cases.json, go/vt/vtgate/semantics/early_rewriter.go
Rewrites tuple comparisons early in the planner processing, so that later parts, such as deciding how to route the query, can use the predicates.
```sql
WHERE (a,b,c) = (1,2,3)
WHERE a = 1 AND b = 2 AND c = 3
```
=> feat: deconstruct tuple comparisons so we can use them for routing decisions

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/test/endtoend/vtgate/queries/aggregation/main_test.go, go/test/endtoend/vtgate/queries/aggregation/schema.sql, go/vt/vtgate/planbuilder/abstract/queryprojection.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.json
=> [release-15.0] Plan order by `COUNT(X)` (#11420)

go/vt/vtgate/planbuilder/rewrite.go, go/vt/vtgate/planbuilder/testdata/filter_cases.json
The planner rewrites the HAVING clause in two steps, and in the second part, we were doing the the wrong rewrite, which lead to a cycle in the expression tree. When we then tried to turn the expression back to SQL, we ran into a stack overflow.
Example query that was failing:
```sql
select a+2 as a from user having a = 42
```
=> bug fix: using self-referencing columns in HAVING should not overflow

go/vt/vttablet/endtoend/framework/server.go, go/vt/vttablet/endtoend/reserve_test.go, go/vt/vttablet/tabletserver/tabletserver.go
This PR fixes the bug in reserve connection query execution on `ReserveExecute` and `ReserveStreamExecute` calls to not use transaction timeout for queries outside of transaction.
=> fix: reserve connection to follow query timeout when outside of transaction

doc/releasenotes/15_0_0_release_notes.md
This adds explicit HTML anchors so that section/subject links work in the release notes summary: https://github.com/vitessio/vitess/releases/tag/v15.0.0-rc1
=> Fix release notes summary links

.github/workflows/cluster_endtoend_vttablet_prscomplex.yml, go/test/endtoend/cluster/mysqlctl_process.go, go/test/endtoend/reparent/prscomplex/main_test.go, go/test/endtoend/reparent/prscomplex/schema.sql, go/vt/vttablet/tabletserver/query_list.go, go/vt/vttablet/tabletserver/query_list_test.go, go/vt/vttablet/tabletserver/tabletserver.go, test/ci_workflow_gen.go, test/config.json
=> [15.0] Fix query list override issue on mysql restart (#11309)

go/test/endtoend/vtorc/primaryfailure/main_test.go, go/test/endtoend/vtorc/primaryfailure/primary_failure_test.go, go/test/endtoend/vtorc/utils/utils.go, go/vt/vtctl/reparentutil/replication.go, go/vt/vtorc/inst/instance_dao.go
This is a forward port of https://github.com/vitessio/vitess/pull/11489
- #11488 
=> [ForwardPort] Fix VTOrc to handle multiple failures (#11489)

go/vt/wrangler/workflow.go
This is a minor follow-up to https://github.com/vitessio/vitess/pull/11451. At the very end of that work I changed the optimizing work so that it's done in a background goroutine for each tablet and the logging of any failures went from the wrangler's logger (vtctl client terminal) to vtctld's warning log. As part of that, however, I should have noted which tablet the work failed on. This PR corrects that.
- Follow-up to: https://github.com/vitessio/vitess/pull/11451
=> Log which tablet copy_state optimization failed on

go/vt/vtgate/planbuilder/rewrite.go, go/vt/vtgate/planbuilder/testdata/filter_cases.json, go/vt/vtgate/semantics/early_rewriter.go, go/vt/vtgate/semantics/early_rewriter_test.go
This Pull Request fixes a recent change introduced by https://github.com/vitessio/vitess/pull/11306. An issue appeared several days ago as described in https://github.com/planetscale/discussion/discussions/308. We were rewriting the `having` expression to whatever was underneath the alias in the select list which is incorrect.
We can only safely do this rewrite when the expression we want to filter by is not using any columns from the tables, so we should check that the predicate doesn't reference any columns that are out of scope.
- https://github.com/planetscale/discussion/discussions/308
=> Fix `HAVING` rewriting made in #11306

.github/workflows/cluster_endtoend_vttablet_prscomplex.yml, go/test/endtoend/vtgate/transaction/restart/main_test.go, go/test/endtoend/vtgate/transaction/restart/schema.sql, go/vt/vttablet/tabletserver/connpool/dbconn.go, go/vt/vttablet/tabletserver/query_executor.go, test/config.json
This PR fixes the issue with transactions in OLAP mode, when a connection error occurs, a new connection was getting assigned. This will lead to incorrect transaction behaviour as the old queries inside that transaction were lost.
The correct behaviour is to throw the error back and not start a new connection for that transaction.
=> fix: fail over reconnect in stream execution for connection with transaction

.github/workflows/cluster_endtoend_vttablet_prscomplex.yml, go/test/endtoend/vtgate/transaction/restart/main_test.go, go/test/endtoend/vtgate/transaction/restart/schema.sql, go/vt/vttablet/tabletserver/connpool/dbconn.go, go/vt/vttablet/tabletserver/query_executor.go, test/config.json
Cherry pick from https://github.com/vitessio/vitess/pull/11517
This PR fixes the issue with transactions in OLAP mode, when a connection error occurs, a new connection was getting assigned. This will lead to incorrect transaction behaviour as the old queries inside that transaction were lost.
The correct behaviour is to throw the error back and not start a new connection for that transaction.
=> [15.0] fix: fail over reconnect in stream execution for connection with transaction

go/cmd/vtctldclient/command/root.go, go/cmd/vtctldclient/command/shards.go, go/flags/endtoend/vtctldclient.txt
I also refactored the `ensureServerArg` to actually create the client (for commands that need it, now that we have one that doesn't), and renamed it accordingly:
```
vtctldclient  GenerateShardRanges 2                 
[
"-80",
"80-"
]
```
```
vtctldclient  GetCellInfo foo 2>&1 | tail -n 1      
E1013 15:48:33.918217   20963 main.go:56] please specify --server <vtctld_host:vtctld_port> to specify the vtctld server to connect to
```
=> Add GenerateShardRanges to vtctldclient

go/test/endtoend/vtgate/sequence/seq_test.go, go/vt/vtgate/planbuilder/physical/route_planning.go, go/vt/vtgate/planbuilder/testdata/dml_cases.json, go/vt/vtgate/planbuilder/testdata/vschemas/schema.json
Executing a `DELETE FROM` query against a sequence table would fail with:
```
table '<sequence table>' does not have a primary vindex (errno 1173) (sqlstate 42000) during query: DELETE FROM <sequence table>
```
This PR fixes that error by skipping all vindex routing logic for unsharded queries.
Fixes https://github.com/vitessio/vitess/issues/11455.
=> Fix #11455 - skip vindex operations for `DELETE` statements against unsharded tables

go/test/endtoend/vtgate/sequence/seq_test.go, go/vt/vtgate/planbuilder/physical/route_planning.go, go/vt/vtgate/planbuilder/testdata/dml_cases.json, go/vt/vtgate/planbuilder/testdata/vschemas/schema.json
Cherry Pick of https://github.com/vitessio/vitess/pull/11461
Executing a `DELETE FROM` query against a sequence table would fail with:
```
table '<sequence table>' does not have a primary vindex (errno 1173) (sqlstate 42000) during query: DELETE FROM <sequence table>
```
This PR fixes that error by skipping all vindex routing logic for unsharded queries.
Fixes https://github.com/vitessio/vitess/issues/11455.
=> [15.0] Fix: skip vindex operations for DELETE statements against unsharded tables

go/test/endtoend/vtgate/queries/informationschema/informationschema_test.go, go/test/endtoend/vtgate/queries/informationschema/schema.sql, go/test/endtoend/vtgate/queries/informationschema/vschema.json, go/vt/vtgate/engine/concatenate.go, go/vt/vtgate/engine/fake_vcursor_test.go, go/vt/vtgate/engine/primitive.go, go/vt/vtgate/vcursor_impl.go, go/vt/vttablet/sandboxconn/sandboxconn.go
This PR forces concatenate engine to do sequential execution of queries when the session is in a transaction.
- Fixes https://github.com/vitessio/vitess/issues/11454
=> [15.0] Fix: concatenate engine in transaction

go/test/endtoend/vtgate/queries/informationschema/informationschema_test.go, go/test/endtoend/vtgate/queries/informationschema/schema.sql, go/test/endtoend/vtgate/queries/informationschema/vschema.json, go/vt/vtgate/engine/concatenate.go, go/vt/vtgate/engine/fake_vcursor_test.go, go/vt/vtgate/engine/primitive.go, go/vt/vtgate/vcursor_impl.go, go/vt/vttablet/sandboxconn/sandboxconn.go
Forward port from 15.0 https://github.com/vitessio/vitess/pull/11534
This PR forces concatenate engine to do sequential execution of queries when the session is in a transaction.
- Fixes https://github.com/vitessio/vitess/issues/11454
=> [main] Fix: concatenate engine in transaction (#11534)

go/vt/vtgate/planbuilder/gen4_planner.go, go/vt/vtgate/planbuilder/operators/compact.go, go/vt/vtgate/planbuilder/operators/node.go, go/vt/vtgate/planbuilder/operators/operator.go, go/vt/vtgate/planbuilder/operators/operator_test.go
Changes compact to use the new way of traversing the tree structure.
=> [gen4]: small refactoring around Compact

go/vt/vttablet/tabletserver/state_manager.go, go/vt/vttablet/tabletserver/state_manager_test.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tabletserver_test.go
We have been seeing a failure of `DemotePrimary` wherein it just gets stuck indefinitely. The failure was traced to a call to acquiring a lock which was held by the `CheckMySQL` function which too is stuck indefinitely. This PR aims to add a gauge which tells us if `CheckMySQL` is running or not. If the gauge is constantly 1 for more than 10 minutes, then it is an indication that something is wrong and we can take a look.
=> Add Gauge For CheckMySQL Running

go/test/endtoend/vtgate/queries/dml/insert_test.go, go/test/endtoend/vtgate/queries/dml/main_test.go, go/vt/vtgate/vtgate.go
This PR redacts the bindvars in the errors that are produced by MySQL. For instance, a duplicate key error coming from MySQL will no longer contain the bind variables.
=> Redact bind variables in mysql errors

go/vt/grpcclient/client.go, go/vt/grpccommon/options.go, go/vt/servenv/grpc_server.go, go/vt/vtadmin/api_test.go
This PR removes grpc's `EnableTracingOpt` as it is a racy code path. We set the value of `grpc.EnableTracing` directly with the same flag (`--grpc_enable_tracing`) .
=> Remove `EnableTracingOpt` and `--grpc_enable_tracing`

go/vt/vtgate/engine/vindex_func.go, go/vt/vtgate/engine/vindex_func_test.go
In #9426 we added list support for [Vindex Functions](https://vitess.io/docs/reference/features/vindexes/#query-vindex-functions) using the`IN` operator so that you can get the mappings for N values. When doing so, [we loop over the values in the list and call `Vindex.Map()` for each one](https://github.com/vitessio/vitess/blob/e803ac7255f7a5a6bce74c232a92867e28b4c465/go/vt/vtgate/engine/vindex_func.go#L113-L137). This was fine for the built-in Vindex types like [`hash`](https://github.com/vitessio/vitess/blob/e803ac7255f7a5a6bce74c232a92867e28b4c465/go/vt/vtgate/vindexes/hash.go#L76-L87) as the same amount of work was done either way, but for [Unique (Consistent) Lookup Vindexes](https://vitess.io/docs/user-guides/vschema-guide/unique-lookup/) this is very inefficient because its …
=> Optimize List Support In Vindex Functions

examples/local/vtadmin/discovery.json, examples/region_sharding/vtadmin/discovery.json, web/vtadmin/src/components/routes/Gates.tsx
In the VTAdmin vtctld page, we link to the vtctld dashboard. For this purpose the `fqdn` field in the discovery configuration. We can do the same for the vtgate page which currently doesn't link to anything.
This PR makes this change. Now adding a `fqdn` field to the vtgate configuration will allow VTAdmin to link to the debug/status page of vtgate.
The page looks like the following with the hyperlink - 
=> [15.0] Add VTGate debug/status page link to VTAdmin

examples/operator/operator.yaml
With the previous memory limit of the vitess-operator (`128Mi`) the Operator would often error out with an `OOMKilled` error:
```
vitess-operator-66967b4bc4-r8pk8                             0/1     OOMKilled   3 (37s ago)     5m24s
```
This PR changes the upper limit allocated to the vitess-operator to `512Mi`. 
This change must be ported over to the vitess-operator repository once it is merged.
=> Increase the memory limit of the vitess-operator

go/internal/flag/flag.go, go/vt/vtgate/executor_select_test.go
* Running single unit tests in vtgate was not possible before this PR: all tests would run instead of a single test
* GoLand was erroring out if you tried to run/debug a single unit test. This is because GoLand runs tests using `testjson` like 
`go tool test2json -t /private/var/folders/y4/rmwnvscj62zg5mz1jhz5rlkr0000gn/T/GoLand/___TestWeightStringsComprehensive_in_vitess_io_vitess_go_mysql_collations_integration.test -test.v -test.paniconexit0 -test.run ^\QTestWeightStringsComprehensive\E$`, unlike `go test` which uses `/tmp/go-build898573698/b001/vstreamer.test -test.paniconexit0 -test.timeout=10m0s -test.failfast=true -test.v=true --alsologtostderr -test.run=TestWeightStringsComprehensive`
The PR adds a `TestMain()` to the vtgate unit tests, so that we can parse test flags for all …
=> Test flags: Update logic for parsing test flags to run unit tests within GoLand and to parse test flags in vtgate to allow running unit tests

go/vt/mysqlctl/backup_test.go, go/vt/mysqlctl/backupengine.go, go/vt/mysqlctl/capabilityset.go
Instead of relying on a specific version check, detect if the new redo log location is present or not.
This makes the backup logic independent from the version check against MySQL. With this change, 8.0.30 can be backed up just as well as any other version.
Solves the backup part of
https://github.com/vitessio/vitess/issues/11554 by removing the dependency on the version check. There might be still other places where that issue can crop up, but it solves the immediate breaking issue with backups.
Marked this for back porting to 14 and 15, also since we back ported the other 8.0.30 fixes to 14 so we need this one as well. …
=> Detect redo log location dynamically based on presence

doc/releasenotes/15_0_0_summary.md, go/cmd/vtctldclient/command/reparents.go, go/flags/endtoend/vtctldclient.txt, go/vt/vtctl/reparent.go
Deprecate `InitShardPrimary` command in favour of `PlannedReparentShard`
- #6612 
-   [x] Documentation was added or is not required Webiste PR - https://github.com/vitessio/website/pull/1189
=> [15.0] Deprecate InitShardPrimary command

go/vt/vtgate/planbuilder/physical/route_planning.go, go/vt/vtgate/planbuilder/testdata/select_cases.json
This pull request imrpoves query route merging for queries that consist of multiple joins (via vindex columns), where some of the joined tables also have additional vindex conditions defined.
An example can be found in https://github.com/vitessio/vitess/issues/10819, and in the test case that was added to `go/vt/vtgate/planbuilder/testdata/select_cases.txt`.
Previously, the Gen4 planner would break the query up into multiple pieces, one for each "direct" vindex condition defined, even though the query could be send to a single shard based on the join conditions between all tables.
For the query from the added test case, the plan generated by Gen4 would look like this:
```json
{
"Original": "SELECT user.id FROM user INNER JOIN music_extra ON user.id = …
```
=> [V14] Improve route merging for queries that can be merged via join predicates

.github/workflows/release_notes_label.yml
This PR changes the output of the `release_notes_label` workflow to mention `16.0.0` instead of `15.0.0`.
=> Upgrade the `release_notes_label` workflow for `v16.0.0`

go/vt/mysqlctl/backup_test.go, go/vt/mysqlctl/backupengine.go, go/vt/mysqlctl/capabilityset.go
Instead of relying on a specific version check, detect if the new redo log location is present or not.
This makes the backup logic independent from the version check against MySQL. With this change, 8.0.30 can be backed up just as well as any other version.
Solves the backup part of
https://github.com/vitessio/vitess/issues/11554 by removing the dependency on the version check. There might be still other places where that issue can crop up, but it solves the immediate breaking issue with backups.
Signed-off-by: Dirkjan Bussink <d.bussink@gmail.com>
Backport of #11555
=> Detect redo log location dynamically based on presence (#11555)

go.mod, go.sum, go/mysql/flavor_mysql.go, go/mysql/mysql56_gtid.go, go/mysql/mysql56_gtid_set.go, go/mysql/mysql56_gtid_set_test.go, go/mysql/replication_position.go
This is a small optimization pass for MySQL 5.6 GTID Set parsing performance. This is something that we do very often during VStreaming and which we were performing quite inefficiently.
Before/after:
```
name                   old time/op    new time/op    delta
MySQL56GTIDParsing-16    13.0µs ± 1%     6.8µs ± 2%  -47.60%  (p=0.000 n=9+10)
name                   old alloc/op   new alloc/op   delta
MySQL56GTIDParsing-16    4.38kB ± 0%    3.10kB ± 0%  -29.07%  (p=0.000 n=10+10)
name                   old allocs/op  new allocs/op  delta
MySQL56GTIDParsing-16      68.0 ± 0%      25.0 ± 0%  -63.24%  (p=0.000 n=10+10)
```
cc @dbussink 
-   [x] Documentation was added or …
=> mysql: Improve MySQL 5.6 GTID parsing performance

go/flags/endtoend/mysqlctl.txt, go/flags/endtoend/mysqlctld.txt, go/flags/endtoend/vtctld.txt, go/flags/endtoend/vtgate.txt, go/flags/endtoend/vtorc.txt, go/flags/endtoend/vttablet.txt, go/flags/endtoend/vttestserver.txt, go/vt/servenv/servenv.go
This changes the default maximum stack size we allow to 64MiB. There should not be any algorithms in Vitess or logic that ever needs this kind of stack size and it's a really high safe limit we believe for now.
It also adds a knob to tune in case the limit doesn't suffice, or if someone wants to tighten it further.
Addresses #11568 
=> Add default lower stack limit

doc/releasenotes/15_0_0_release_notes.md, doc/releasenotes/15_0_0_summary.md
running release script during release 15.0 changes the bookmarks for release notes and summary. This results in make them non-functional. This PR fix those bookmarks.
Also backup compression was having wrong value as defaults in release notes and summary. I fixed that as well.
=> fix anchors for release notes and summary

go/vt/dbconfigs/credentials.go
This is a follow-up to https://github.com/vitessio/vitess/pull/11336 where I somehow missed replacing the flag usage with the pflag flag set for the vault related flags.
- Follow-up to: https://github.com/vitessio/vitess/pull/11336
=> Fix missing flag usage for vault credentials flags

go/mysql/flavor.go, go/mysql/flavor_mysql.go, go/mysql/flavor_mysqlgr.go, go/mysql/mysql56_gtid_set.go, go/test/endtoend/onlineddl/revert/onlineddl_revert_test.go, go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go, go/vt/schema/ddl_strategy.go, go/vt/schema/ddl_strategy_test.go, go/vt/vttablet/onlineddl/analysis.go, go/vt/vttablet/onlineddl/analysis_test.go
Followup to https://github.com/vitessio/vitess/pull/10402, in this PR:
- INSTANT DDL is supported by ddl_strategy flag `--prefer-instant-ddl`
- Added support for `ENUM/SET` instant DDLs
- A minor validation for `DROP COLUMN` (INSTANT not supported in `COMPRESSED` tables)
As reminders/context:
- MySQL supports [INSTANT DDL](https://dev.mysql.com/doc/refman/8.0/en/innodb-online-ddl-operations.html) for some limited types of `ALTER TABLE` operations
- When `--prefer-instant-ddl` is specified, we capture and analyze those specific operations
- If applicable to `INSTANT`, we add `ALGORITHM=INSTANT` and run the schema migration directly, and do not pass it through to `gh-ost` nor `vitess/vreplication`.
- Schema changes executed with `INSTANT` algorithm are non-revertible.
Tracking: …
=> Online DDL: more support for INSTANT DDL

go/vt/sqlparser/normalizer.go, go/vt/sqlparser/normalizer_test.go, go/vt/vtgate/executor_dml_test.go
Changes the auto-parameterized update queries to user nicer bindvar names when possible.
```sql
update user set a=2 where id = 1
update user set a=:bv1 where id = :id
update user set a=:a where id = :id
```
Continuation of the work in #11571
=> planner enhancement: nice bindvar names for update

doc/releasenotes/15_0_0_release_notes.md, doc/releasenotes/15_0_0_summary.md
bookmarks (anchor) for release notes and summary doc are broken. This PR will fix them.
Cherry-pick #11578 
=> [cherry-pick]fix anchors for release notes and summary (#11578)

go/cmd/vtbackup/vtbackup.go, go/flags/endtoend/vtbackup.txt, go/test/endtoend/backup/vtbackup/backup_only_test.go
Recently [vtbackup was changed to disable innodb redo log](https://github.com/vitessio/vitess/pull/11330) during the replicate-from-primary stage of vtbackup. The goal was to squeeze out a bit more performance. 
My mental model at the time was that "if mysqld of vtbackup fails, we won't try to restart from where we left off, so if any data gets corrupted the next attempt won't re-use any corrupted data".
It turns out that isn't true. If mysqld OOMs, mysqld_safe will restart it, and the next mysqld process may re-use InnoDB data corrupted in a previous run.
I think it's probably better to put this behind a flag and let users opt in to it, at least until we have a better handle on things like mysqld OOMs.
=> vtbackup: add --disable-redo-log flag (default false)

go/vt/mysqlctl/builtinbackupengine.go, go/vt/mysqlctl/compression.go, go/vt/mysqlctl/xtrabackupengine.go
Forward port of: https://github.com/vitessio/vitess/pull/11479
- Fixes: #11480
=> [cherry-pick] remove excessive backup decompression logging (#11479)

go/vt/vttablet/grpcqueryservice/server.go, go/vt/vttablet/tabletconntest/fakequeryservice.go, go/vt/vttablet/tabletconntest/tabletconntest.go, go/vt/vttablet/tabletserver/tabletserver_test.go
When we already have an error during the stream setup, that errors needs to be returned immediately.
Otherwise the stream will already be started and the error message is never returned to the client and it silently looks like a success even if it's a failure.
This in turn can result in an empty result for example when an error would have been expected.
Fixes #11593
=> Fix ordering when error happens during stream setup

go/sqltypes/proto3.go, go/sqltypes/result.go, go/vt/vtgate/engine/route.go, go/vt/vtgate/engine/vindex_func.go, go/vt/vtgate/executor.go
We don't consistently copy all fields everywhere which is confusing. This adds also a shallow copy helper which can be used in a few places.
Session state change was not copied everywhere and also the streaming API didn't honor having all fields on the first result packet, where it would only show fields but now other metadata like info etc.
This makes it all consistent so we copy all state everywhere where needed.
=> Cleanup copying of proto results to sqltypes.Result

go/vt/vtgate/vtgate.go
These metrics are all statically initialized to a fixed value, so we can immediately initialize these.
Even if the vtgate package is not used, these won't emit anything unless actual metrics are used so it's safe to initialize them here.
=> Move initialization of metrics to be static

go/mysql/endtoend/client_test.go, go/mysql/flavor_mysql.go
The various SQL flavors (56, 57, 80, MariaDB, FilePos) use different queries for schema inspection. The FilePos flavor is using a 56 flavor query which isn't forward compatible with MySQL 80.
This commit updates the 56 flavor to be forward-compatible with 57, 80. s/o @mattlord for the suggested fix.
Fixes #11312.
=> make MySQL56-flavor schema queries forward-compatible

go/vt/vtgate/executor_test.go, go/vt/vtgate/planbuilder/ddl.go
Whereas untargeted `ALTER` statements for tables defined a vschema are routed to the vschema's keyspace, the same is not true for `CREATE TABLE` statements, which fail with a "no database selected" error.
This change makes it so that if a `CREATE TABLE` statement references a table defined in a vschema, the statement is routed to that vschema's keyspace.
This is useful, for example, when using declarative online DDL together with [global table routing](https://vitess.io/docs/15.0/reference/features/global-routing/).
=> vtgate: route create table statements to vschema keyspace

go/vt/sqlparser/normalizer.go, go/vt/sqlparser/normalizer_test.go
We were not auto-parameterizing literal values on the `ORDER BY` and `GROUP BY`.
This is because literals can have special meaning when used in these clauses.
For example:
```sql
select name from user order by 1
```
In the query above, `1` does not mean the integer value 1, instead it refers to the first column returned.
On the other hand, in the following query `1` really means integer 1.
```sql
select name from user order by age + 1
```
This PR changes the normalizer to change literals in ORDER BY/GROUP BY as long as they are not directly following the clause.
=> normalize more expressions

doc/internal/ReleaseInstructions.md, docker/k8s/logrotate/Dockerfile, docker/k8s/logtail/Dockerfile, docker/k8s/vtadmin/Dockerfile, docker/release.sh
During the release of v15, a failure of the docker release script was noticed. The bug outlining the issue is at https://github.com/vitessio/vitess/issues/11627. 
The issue was tracked to the PR https://github.com/vitessio/vitess/pull/10968 which changed the context that the Dockerfiles were expecting to be run from. So when the `release.sh` script is run, it fails because the file `docker/k8s/logrotate/logrotate.conf` doesn't exits. Instead it should be `logrotate.conf`.
This PR fixes this issue. It also adds the `release.sh` as a step to the release process which was previously missing.
- Fixes #11627 
=> Docker Image Context Fix

doc/releasenotes/16_0_0_summary.md, go/vt/vtgate/planbuilder/plancontext/vschema.go
Deprecates the V3 planner so we can remove it in V17.
=> deprecate V3 planner

go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go
We need to initialize the default comment with an actual string literal. The reason for this is that `opt.String` being `""` is treated special when the AST is generated back into a query. It's treated as not having a string option, resulting in an alter like the following:
```
alter table t1 comment ()
```
By initializing this to an explicitly string literal value we can distinguish between an empty string and not having a value at all, which isn't possible with a plain string.
Fixes #11644
=> Fix generating invalid alter table for comments

go/test/endtoend/vtgate/schema/schema_test.go, go/vt/schemamanager/tablet_executor.go, go/vt/vttablet/tabletmanager/rpc_query.go
This is a backport of #9998 to release-13.0.
This PR resolves two issues - 
- Fixes #11646
- Fixes #9996 for release-13.0
=> [13.0] ApplySchema: allow-zero-in-date embedded as query comment in call to ExecuteFetchAsDba (#9998)

go/sqltypes/value.go, go/sqltypes/value_test.go, go/vt/sqlparser/normalizer_test.go
Change the `base` argument to `strconv` methods to enforce base 10, as all signed and unsigned literals in MySQL are in this base. A leading zero in these literals does not trigger octal as a base, and a leading `0x` does not generate a signed/unsigned literal but a `HexValue`.
Fixes https://github.com/vitessio/vitess/issues/11648
=> sqltypes: handle leading zeroes

doc/releasenotes/14_0_0_release_notes.md, doc/releasenotes/14_0_0_summary.md, doc/releasenotes/14_0_1_release_notes.md, doc/releasenotes/14_0_1_summary.md, doc/releasenotes/14_0_2_release_notes.md, doc/releasenotes/14_0_2_summary.md, doc/releasenotes/14_0_3_release_notes.md, doc/releasenotes/14_0_3_summary.md, doc/releasenotes/14_0_4_summary.md, go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/vt/vtgate/planbuilder/aggregation_pushing.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.json
=> [release-14.0] Do not multiply `AggregateRandom` in JOINs

doc/releasenotes/14_0_0_release_notes.md, doc/releasenotes/14_0_0_summary.md, doc/releasenotes/14_0_1_release_notes.md, doc/releasenotes/14_0_1_summary.md, doc/releasenotes/14_0_2_release_notes.md, doc/releasenotes/14_0_2_summary.md, doc/releasenotes/14_0_3_release_notes.md, doc/releasenotes/14_0_3_summary.md, doc/releasenotes/15_0_0_release_notes.md, doc/releasenotes/15_0_0_summary.md, doc/releasenotes/15_0_1_summary.md, go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/vt/vtgate/planbuilder/aggregation_pushing.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.json
=> [release-15.0] Do not multiply `AggregateRandom` in JOINs

go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go, go/vt/sqlparser/ast_format.go, go/vt/sqlparser/tracked_buffer_test.go
With this PR `schemadiff` normalizes (to lower case) the value of an index option. For example: 
`fulltext key name_ft(name) WITH PARSER NGRAM` is normalized into
`fulltext key name_ft(name) WITH PARSER ngram`
Tracking: https://github.com/vitessio/vitess/issues/10203
=> schemadiff: normalize index option value (string)

go/test/endtoend/reparent/prscomplex/main_test.go, go/vt/vttablet/grpcqueryservice/server.go, go/vt/vttablet/grpctabletconn/conn.go, go/vt/vttablet/tabletconntest/fakequeryservice.go, go/vt/vttablet/tabletconntest/tabletconntest.go
The old streaming execution that started a transaction or a reserved connection does not propagate the execution error message back. The change done in https://github.com/vitessio/vitess/pull/11592 was to fix the error propagation. The change resulted in missing propagating the open transaction or reserved connection information back in case of failure.
This PR handles those cases and adds additional tests/asserts to ensure it fixes those issues.
- Fixes https://github.com/vitessio/vitess/issues/11674
-   [X] "Backport me!" label has been added if this change should be backported 15.0, 14.0, 13.0
=> Send errors in stream instead of a grpc error from streaming rpcs when transaction or reserved connection is acquired

go/vt/vtctl/vtctl.go
Now that we've moved to [pFlag](https://github.com/spf13/pflag) we can leverage the [`Changed`](https://pkg.go.dev/github.com/spf13/pflag#FlagSet.Changed) function to see if the user specified the flag on the command-line.
```
tabletTypes := subFlags.String("tablet_types", "in_order:RDONLY,REPLICA,PRIMARY", "Tablet types for source and target")
```
If the user  does not specify the `--tablet_types` flag on the command-line, then [`AddFlag`](https://github.com/spf13/pflag/blob/v1.0.5/flag.go#L841) is not called on the flagSet and thus the `tabletTypes` variable has the address of the string variable created for the string literal "in_order:RDONLY,REPLICA,PRIMARY" there rather than the address of the normalized flag map value. [`Changed`](https://github.com/spf13/pflag/blob/v1.0.5/flag.go#L5 …
=> Leverage pFlag's Changed function to detect user specified flag

go/test/endtoend/reparent/prscomplex/main_test.go, go/vt/vttablet/grpcqueryservice/server.go, go/vt/vttablet/grpctabletconn/conn.go, go/vt/vttablet/tabletconntest/fakequeryservice.go, go/vt/vttablet/tabletconntest/tabletconntest.go, go/vt/vttablet/tabletserver/tabletserver_test.go
Backport PR of https://github.com/vitessio/vitess/pull/11592 and https://github.com/vitessio/vitess/pull/11656
=> [15.0] Send errors in stream instead of a grpc error from streaming rpcs when transaction or reserved connection is acquired

go/vt/sqlparser/normalizer.go, go/vt/sqlparser/normalizer_test.go
When normalizing (automatically parameterising) queries, we try to re-use bindvars for the same literal. So the query:
```sql
select * 
from user, user_extra 
where user.id = 5 and user_extra.id = 5
```
would get normalized to:
```sql
select * 
from user, user_extra 
where user.id = :bv1 and user_extra.id = :bv1
```
This then allows the planner to see that the two literal values are expected to be the same, and it can use this information to make routing decisions.
The rule of re-using literal values doesn't make sense on the `LIMIT` and `OFFSET` clauses. Even if they are using the same literal, we should not expect these two numbers to change hand-in-hand. The best solution is to always use a unique bindvar for these clauses.
-   [x] "Backport me!" label has been added if this change …
=> don't reuse bindvars for LIMIT and OFFSET

go/vt/vtgate/semantics/early_rewriter.go, go/vt/vtgate/semantics/early_rewriter_test.go
MySQLs scoping rules around HAVING and ORDER BY are not easy to mimic.
The issue here was that we rewrite column names used in `ORDER BY`/`HAVING` if they match an alias introduced in `SELECT`.
For the query:
```sql
select min(id) as id from tbl having id > 10
```
the `HAVING` clause is comparing the aggregate value of `min(id)`, not the column id on the table. This can easily be shown by not introducing the alias:
```sql
> select min(id) from apa having id = 10;
Error: (1054, "Unknown column 'id' in 'having clause'")
```
But if you then wrap the `id` column in an aggregation, somehow that changes the scoping, and the following query is valid in MySQL:
```sql
select min(id) as id from tbl having min(id) > 10
```
Why we want to rewrite the use of `id` outside aggregations but not inside …
=> improve handling of ORDER BY/HAVING rewriting

go/vt/vttablet/grpcqueryservice/server.go, go/vt/vttablet/grpctabletconn/conn.go, go/vt/vttablet/tabletconntest/fakequeryservice.go, go/vt/vttablet/tabletconntest/tabletconntest.go, go/vt/vttablet/tabletserver/tabletserver_test.go
Backport PR of https://github.com/vitessio/vitess/pull/11592 and https://github.com/vitessio/vitess/pull/11656
=> [13.0] Send errors in stream instead of a grpc error from streaming rpcs when transaction or reserved connection is acquired

go/mysql/flavor.go, go/mysql/flavor_filepos.go, go/mysql/flavor_mariadb_binlog_playback.go, go/mysql/flavor_mysql.go, go/mysql/flavor_mysqlgr.go, go/vt/vttablet/tabletserver/connpool/dbconn.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/schema/engine.go
Currently, obtaining table sizes from mysql involves joining `information_schema.tables`, which can be very costly on systems with a large number of tables.
My tests on a system with 13k tables took around 20s without this patch, and only 4s with it.
Instead of synchronously recalculating table size stats after every DDL, let them be outdated until the periodic schema reload fixes it.
This is an simpler and less risky alternative to:
* #11386 
cc @arthurschreiber
=> Speedup DDLs by not reloading table size stats

go.mod, go.sum, go/vt/vtgate/planbuilder/plan_test.go
Using a nicer diff when comparing JSONs. Makes the tests so much easier to read.
Here I changed `sharded` from true to false in a test
With the new diff tool:
```json
{
"FieldQuery": "select `user`.col + 2 as a from `user` where 1 != 1",
"Keyspace": {
"Sharded": false => true
},
"Query": "select `user`.col + 2 as a from `user` having a = 42",
"Table": "`user`",
"Variant": "Scatter"
},
"Original": "select user.col + 2 as a from user having a = 42",
"QueryType": "SELECT"
}
```
Using the old tool:
```
Diff:
  any(
- 	json.RawMessage("{\n      \"QueryType\": \"SELECT\",\n      \"Original\": \"select user.col + 2 as a from user having a = 42\",\n      \"Instructions\": {\n        \"OperatorType\": \"Route\",\n        \"Variant\": …
```
=> Readable plan tests

.github/CODEOWNERS
This PR adds multiple maintainers to go.mod and go.sum files to unlock the PR for merge when any library usage is changed.
=> added code owners for go.mod and go.sum files

go.sum, go/test/endtoend/cluster/topo_process.go, go/test/endtoend/cluster/vtbackup_process.go, go/test/endtoend/cluster/vtctld_process.go, go/test/endtoend/cluster/vtgate_process.go, go/test/endtoend/cluster/vtgr_process.go, go/test/endtoend/cluster/vtorc_process.go, go/test/endtoend/cluster/vttablet_process.go
This fixes a race we've found that can sometimes get the endtoend tests stuck permanently during shutdown. cc @dbussink 
=> endtoend: fix race when closing vtgate

go/test/endtoend/vtgate/queries/misc/main_test.go, go/test/endtoend/vtgate/queries/misc/misc_test.go, go/test/endtoend/vtgate/queries/misc/uschema.sql, go/vt/vtgate/planbuilder/gen4_planner.go, go/vt/vtgate/planbuilder/insert.go, go/vt/vtgate/planbuilder/testdata/select_cases.json
This PR is an extension of https://github.com/vitessio/vitess/pull/11429. The unsharded cases in select gen4 planner and insert planner were missing the usage of query_timeout_ms comment directive.
This PR fixes that.
- Fixes https://github.com/vitessio/vitess/issues/11710
=> query timeout hints in unsharded cases

go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/traffic_switcher_test.go
When completing a MoveTables operation with `--rename-tables`, the db and tables are not escaped. This causes the operation to fail in a variety of scenarios, including when the db name has dashes in its name.
I'm not sure if this should be backported. It's not a breaking bug, just an inconvenience. In the end, we just ran the complete command with `--keep-data` and manually renamed the tables. 
Credit goes to @hubb for the fix!
=> VReplication:  escape identifiers when renaming source tables

.github/CODEOWNERS
This Pull Request adds @harshit-gangal, @deepthi, @mattlord as CODEOWNERS of the `/test` directory.
- Fixes https://github.com/vitessio/vitess/issues/11759
=> Add more codeowners to the `/test` directory

go/test/endtoend/vtgate/queries/misc/misc_test.go
This PR deflakes the test added in `Query Timeout` feature.
=> test: deflake TestQueryTimeoutWithTables

go/mysql/fakesqldb/server.go, go/test/endtoend/vtorc/utils/utils.go, go/vt/vttablet/tabletserver/query_executor_test.go
Noticed these when resolving merge conflicts on a separate PR, so just fixing them quickly:
```
go/mysql/fakesqldb/server.go:424:14: var-declaration: should omit type func() from declaration of var afterFn; it will be inferred from the right-hand side (revive)
var afterFn func() = func() {}
^
go/test/endtoend/vtorc/utils/utils.go:39:2: blank-imports: a blank import should be only in a main or test package, or have a comment justifying it (revive)
_ "vitess.io/vitess/go/vt/topo/consultopo"
^
go/test/endtoend/vtorc/utils/utils.go:43:2: blank-imports: a blank import should be only in a main or test package, or have a comment justifying it (revive)
_ "vitess.io/vitess/go/vt/topo/zk2topo"
^
go/vt/vttablet/tabletserver/query_executor_test.go:1266:3: `query` is unused (structcheck)
query  string …
```
=> Fix some linter errors

.github/workflows/codeql_analysis.yml
The CodeQL workflow has been failing due to timeouts. This Pull Request increases the timeout for the `make build`.
There is also a new integration that sends a slack message whenever the workflow fails so we can easily know if the build starts failing. It is usually tough the know if the build fails, we have to manually look at it since the PR is executed in a CRON. The message goes to the `#codeql` channel of our OSS Slack workplace.
Fixes https://github.com/vitessio/vitess/issues/11761
=> Fix `codeql` workflow timeout issue

tools/make-release-packages.sh
When we try to install vitess with local method (https://vitess.io/docs/16.0/get-started/local/#install-vitess) for release 15.0, we are getting following error
```
bash
vtadmin-api is running!
- API: http://localhost:14200/
- Logs: /home/vitess/my-vitess-example/vtdataroot/tmp/vtadmin-api.out
- PID: 43498
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/web/vtadmin/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/web/vtadmin/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vitess/.npm/_logs/2022-11-09T08_25_09_328Z-debug.log
vtadmin-web is running!
- …
```
=> Add VTAdmin folder to release package

go/vt/vttablet/tmrpctest/test_tm_rpc.go, tools/all_test_for_coverage.sh, tools/e2e_test_cluster.sh, tools/e2e_test_race.sh, tools/e2e_test_runner.sh, tools/unit_test_race.sh, tools/unit_test_runner.sh
Sometimes it's necessary to have a separate _test package inside another package. Our current test runner doesn't run such tests though, leading to tests being broken without us knowing.
Worst case it hides real bugs. So we should always ensure to also run these tests as well.
I think we should back port this to avoid future regressions there as well. 
=> Update test runners to run all tests including outside package

go/mysql/conn.go, go/mysql/conn_flaky_test.go
On MariaDB, it's possible that an OK packet has `SERVER_SESSION_STATE_CHANGED` set to true, but it has no additional state change information as the end of the packet is reached.
We should not treat this as an error condition and treat this as a proper OK packet.
Fixes https://github.com/vitessio/vitess/issues/11795
=> Accept no more data in session state change as ok

go/cmd/vtctldclient/command/schema.go, go/test/endtoend/vtctldclient/cli_test.go
See [this comment](https://github.com/vitessio/vitess/issues/11785#issuecomment-1323641942) for an explanation.
Fixes #11785.
=> Switch ApplySchema `--sql` argument to be `StringArray` instead of `StringSlice`

go/test/endtoend/vtgate/reservedconn/sysvar_test.go, go/vt/sqlparser/ast_rewriting.go, go/vt/sqlparser/ast_rewriting_test.go, go/vt/sysvars/sysvars.go, go/vt/vtgate/engine/set.go, go/vt/vtgate/executor.go, go/vt/vtgate/executor_set_test.go, go/vt/vtgate/safe_session.go
This PR fixes the regression caused by https://github.com/vitessio/vitess/pull/11673 where when transaction isolation is not set returns `DEFAULT` which is an unknown value from the transaction isolation system variable.
Now, this PR will return the default value from the connection which will be one of these
`READ-UNCOMMITTED`, `READ-COMMITTED`, `REPEATABLE-READ` and `SERIALIZABLE`
- Fixes https://github.com/vitessio/vitess/issues/11793
=> Fix: return allowed transaction isolation level value on select query

bootstrap.sh
This release also has MacOS M1 arm64 binaries available, so we can use the upstream artifacts directly and also don't need to fall back to a locally installed etcd.
This way we always install etcd and use a consistent version as well independent of what folks already have installed to make it more reliable.
=> Update to latest etcd release

tools/do_release.sh
This PR adds automation to the release script to also update the vitess version in the docker release script. The changes have been tested manually. Calling the function `updateDockerReleaseScript 'v17.0.0'`, changes the release.sh file like 
```
#!/bin/bash
set -ex
vt_base_version='v17.0.0'
debian_versions='buster  bullseye'
default_debian_version='bullseye'
```
- Fixes #11681 
=> Add automation to change vitess version in the docker-release script

.golangci.yml
There's a bunch of deprecated linters that don't work anymore, so let's remove them:
```
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [linters context] structcheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649.
```
Closes https://github.com/vitessio/vitess/issues/11825
-   [x] "Backport to:" labels …
=> Fix the golangci-lint config

go/mysql/collations/coercion.go, go/mysql/collations/integration/coercion_test.go
=> [release-14.0] collations: fix coercion semantics according to 8.0.31 changes (#11487)

go/mysql/collations/coercion.go, go/mysql/collations/integration/coercion_test.go
=> [release-13.0] collations: fix coercion semantics according to 8.0.31 changes (#11487)

GITHUB_SELF_HOSTED_RUNNERS.md
This PR adds the instructions to the self-hosted runner guide on how to fix a self-hosted runner if it runs out of disk space.
- https://github.com/vitessio/vitess/issues/11840
=> Add instructions on how to fix a self-hosted runner running out of disk space

.golangci.yml, go/test/endtoend/clustertest/main_test.go, go/test/endtoend/clustertest/vtctld_test.go, go/test/endtoend/clustertest/vtgate_test.go, go/test/endtoend/clustertest/vttablet_test.go, go/test/endtoend/messaging/message_test.go, go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go, go/test/endtoend/tabletgateway/buffer/buffer_test_helpers.go, go/test/endtoend/tabletgateway/vtgate_test.go, go/test/endtoend/tabletmanager/primary/tablet_test.go, go/test/endtoend/tabletmanager/tablet_health_test.go, go/test/endtoend/tabletmanager/throttler/throttler_test.go, go/test/endtoend/tabletmanager/throttler_custom_config/throttler_test.go, go/test/endtoend/tabletmanager/throttler_topo/throttler_test.go, go/test/endtoend/topoconncache/main_test.go, go/test/endtoend/vreplication/helper_test.go, go/test/endtoend/vreplication/vreplication_test.go, go/test/endtoend/vtcombo/vttest_sample_test.go, go/test/endtoend/vtgate/schematracker/restarttablet/schema_restart_test.go, go/vt/vtctld/api_test.go, go/vt/vttablet/tabletserver/throttle/throttler.go, go/vt/workflow/long_polling_test.go, go/vt/workflow/websocket_test.go, test.go
One of the easy things to miss that can cause resource leaks is not closing a response body for an HTTP request.
There's a linter available to make it easier to catch this, so this enables that linter and fixes all the cases reported.
This is almost all test cases, except for one production code path case in the throttler.
Fixes #11841
=> Fix closing the body for HTTP requests

go/vt/vtgate/executor_framework_test.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/executor_test.go, go/vt/vtgate/vindexes/cached_size.go, go/vt/vtgate/vindexes/cfc.go, go/vt/vtgate/vindexes/cfc_test.go
This PR simplifies the self-reference of the CFC struct by prefix Vindex in the CFC Vindex.
Prefix Vindex is created when it is required rather than upfront. This resolved the cyclic dependency which was causing cache_size to crash with stack full error.
- Fixes CFCInsert Flakyness reported via launchable
- Fixes https://github.com/vitessio/vitess/issues/11858
=> Simplify recursive data structure in CFC Vindex

.github/workflows/cluster_endtoend_tabletmanager_throttler_topo.yml
Followup to https://github.com/vitessio/vitess/pull/11604, I notice `.github/workflows/cluster_endtoend_tabletmanager_throttler_topo.yml` is not up do date with latest `make generate_ci_workflows`. Now updated.
#11316 
=> Update throttler-topo workflow file

.golangci.yml, go/test/endtoend/clustertest/main_test.go, go/test/endtoend/clustertest/vtctld_test.go, go/test/endtoend/clustertest/vtgate_test.go, go/test/endtoend/clustertest/vttablet_test.go, go/test/endtoend/messaging/message_test.go, go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go, go/test/endtoend/tabletgateway/buffer/buffer_test_helpers.go, go/test/endtoend/tabletgateway/vtgate_test.go, go/test/endtoend/tabletmanager/primary/tablet_test.go, go/test/endtoend/tabletmanager/tablet_health_test.go, go/test/endtoend/tabletmanager/throttler/throttler_test.go, go/test/endtoend/tabletmanager/throttler_custom_config/throttler_test.go, go/test/endtoend/topoconncache/main_test.go, go/test/endtoend/vreplication/helper_test.go, go/test/endtoend/vreplication/vreplication_test.go, go/test/endtoend/vtcombo/vttest_sample_test.go, go/test/endtoend/vtgate/schematracker/restarttablet/schema_restart_test.go, go/vt/vtctld/api_test.go, go/vt/vttablet/tabletserver/throttle/throttler.go, go/vt/workflow/long_polling_test.go, go/vt/workflow/websocket_test.go, test.go
One of the easy things to miss that can cause resource leaks is not closing a response body for an HTTP request.
There's a linter available to make it easier to catch this, so this enables that linter and fixes all the cases reported.
This is almost all test cases, except for one production code path case in the throttler.
Backport of #11842
=> Fix closing the body for HTTP requests (#11842)

.github/CODEOWNERS, MAINTAINERS.md
Add @notfelineit to maintainers 🎉 
I also snuck in a change to CODEOWNERS to add myself, @harshit-gangal and @mattlord for the generated proto files for vtadmin.
=> add frances to maintainers

.github/workflows/static_checks_etc.yml, .golangci.yml, misc/git/hooks/golangci-lint
I ran into an issue with the output of git diff not being parseable. That has been fixed in this new version.
=> update golangci-lint to 1.50.1

go/vt/vttablet/tabletserver/state_manager.go, go/vt/vttablet/tabletserver/state_manager_test.go
This is a backport PR for https://github.com/vitessio/vitess/pull/11895
=> [release-15.0] Fix CheckMySQL by setting the correct wanted state #11895

go/vt/vttablet/tabletserver/state_manager.go, go/vt/vttablet/tabletserver/state_manager_test.go
This is a backport PR for https://github.com/vitessio/vitess/pull/11895
=> [release-14.0] Fix CheckMySQL by setting the correct wanted state #11895

go/vt/sqlparser/utils_test.go
This PR just adds more unit test to validate behavior of `QueryMatchesTemplates()`, as quick followup to https://github.com/vitessio/vitess/issues/11893
https://github.com/vitessio/vitess/issues/11893
=> more unit tests for QueryMatchesTemplates()

go/test/endtoend/vtgate/queries/subquery/subquery_test.go, go/vt/sqlparser/normalizer.go, go/vt/sqlparser/normalizer_test.go, go/vt/vtgate/planbuilder/operators/derived.go, go/vt/vtgate/planbuilder/projection_pushing.go, go/vt/vtgate/planbuilder/testdata/dml_cases.json, go/vt/vtgate/planbuilder/testdata/unsupported_cases.json, go/vt/vtgate/semantics/early_rewriter_test.go, go/vt/vtgate/semantics/semantic_state.go, go/vt/vtgate/semantics/table_collector.go
This PR is fixing two separate bugs that affected the same query.
First off: the gen4 planner was having a hard time dealing with predicates on top of derived tables that did not depend on the derived table.
Example:
```sql
SELECT 1 
FROM (SELECT `hello world`) AS tmp 
WHERE EXISTS(SELECT 1 FROM user WHERE id = 123)
```
This type of query failed with `unsupported: unable to split predicates to derived table: not :__sq_has_values1`.
Once that problem was solved, a different problem surfaced.
Vitess has a normalizer that auto-parameterizes queries so the plan cache can be shared between more queries. This means finding literals and replacing them with bindvars. It also does something called "expand star" - basically it finds all instances of `SELECT *` and replaces the star with the actual …
=> bugfix: allow predicates without dependencies with derived tables to be handled correctly

go/vt/vtgate/engine/compare_utils.go, go/vt/vtgate/engine/gen4_compare_v3.go, go/vt/vtgate/executor.go, go/vt/vtgate/planbuilder/gen4_compare_v3_planner.go
This Pull Request simplifies the `getPlan` and `gen4CompareV3` code paths to make it more reusable.
=> Simplify `getPlan` and `gen4CompareV3`

go/test/endtoend/vtgate/queries/subquery/subquery_test.go
In a recent PR, I accidentally did not mark on of the end to end tests to only run on the latest version of Vitess.
This change set fixes that issue.
The problem was introduced in #11875
=> [ci issue] Tests are running on older versions that do not support the query

.github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml, .github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml, .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml, .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml
This Pull Request is a follow-up of https://github.com/vitessio/vitess/pull/11897. We will now run the appropriate golang version in the next-release upgrade downgrade tests.
=> Use `go1.18.9` in the next release upgrade downgrade E2E tests

.github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml, .github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml, .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml, .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml
This Pull Request is a follow-up of https://github.com/vitessio/vitess/pull/11905. We will now run the appropriate golang version in the next-release upgrade downgrade tests.
=> Use `go1.19.4` in the next release upgrade downgrade E2E tests

go/mysql/conn_flaky_test.go, go/mysql/query.go, go/mysql/query_test.go
Once a connection has received a connection error from MySQL, we close the connection in `dbconn` and other callers. In order for this close to work properly we should be sending a MySQL.`CRServerLost` error. 
All the callers of `readEphemeralPacket` wrap the error and send this error so that the connection can be closed. However, there is one code-path that doesn't do this.
We believe that is an issue. Not sending a mysql.`CRServerLost` error causes the connection to remain open and be reused for the rollback call, even though the connection isn't usable any more. This causes a panic in the code, since we didn't cleanup the state when we error out the first time.
This PR fixes the issue after adding a failing test which ensures that we receive a `CRServerLost` error on MySQL crashing …
=> Fix sending a ServerLost error when reading a packet fails

GOVERNANCE.md, GUIDING_PRINCIPLES.md
Minor corrections regarding what maintainers are allowed to do.
=> Correct minor inaccuracies in governing docs

go/vt/vtorc/logic/orchestrator.go
This PR just moves a single log line around to also print the error if a force discovery of a tablet fails.
- Fixes #11935
=> Also log error on a failure in DiscoverInstance

go/test/endtoend/vtgate/queries/subquery/subquery_test.go, go/vt/sqlparser/normalizer.go, go/vt/sqlparser/normalizer_test.go, go/vt/vtgate/planbuilder/abstract/derived.go, go/vt/vtgate/planbuilder/physical/operator_funcs.go, go/vt/vtgate/planbuilder/projection_pushing.go, go/vt/vtgate/planbuilder/testdata/dml_cases.json, go/vt/vtgate/planbuilder/testdata/unsupported_cases.json, go/vt/vtgate/semantics/early_rewriter_test.go, go/vt/vtgate/semantics/semantic_state.go, go/vt/vtgate/semantics/table_collector.go
=> bugfix: allow predicates without dependencies with derived tables to be handled correctly (#11911)

.github/CODEOWNERS, MAINTAINERS.md
Adds Arthur Schreiber @arthurschreiber as the newest maintainer of Vitess. Also adds him as code owner of the plan builder package so he gets pinged for PRs against this package.
=> add Arthur to the maintainers file

go/vt/vttablet/onlineddl/executor.go
Fixes https://github.com/vitessio/vitess/issues/11913
This PR ensures to clean up non-utf8 characters from the error message reported in `_vt.schema_migrations`. If writing the message still fails for whatever reason (the text is too long?), we opt for an alternative, generic error message.
https://github.com/vitessio/vitess/issues/11913
#6926
=> Online DDL: ensure message is valid `utf8` in `updateMigrationMessage()`

go/mysql/constants.go, go/vt/vtctl/vdiff2.go, go/vt/vttablet/tabletmanager/vdiff/controller.go, go/vt/vttablet/tabletmanager/vdiff/engine.go, go/vt/vttablet/tabletmanager/vdiff/engine_test.go, go/vt/vttablet/tabletmanager/vdiff/framework_test.go, go/vt/vttablet/tabletmanager/vdiff/schema.go, go/vt/vttablet/tabletmanager/vdiff/table_differ.go
>**Note** This is a backport of https://github.com/vitessio/vitess/pull/11768. We're doing this because 1) the changes are isolated to vdiff2 2) vdiff2 is currently marked as experimental in v15 and we want more testing of it in v15 (this was the origination of the bug report) in the hopes of marking it production ready in v16.
This addresses two ways a VDiff could become "orphaned" and require a manual `Stop` and `Resume` step:
1. A tablet and/or mysqld are not shutdown normally or otherwise cannot save the final state
- Fix: when opening the engine, restart any vdiffs that are in the started state as this indicates it did not complete and was unable to save the final state and must be restarted.
2. The vdiff run fails with an error and the DB connection is closed/lost
- Fix: when a …
=> [release-15.0] [Backport]: VReplication: Prevent Orphaned VDiff2 Jobs (#11768)

go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/executor_test.go
backport of https://github.com/vitessio/vitess/pull/11889
---
At some point the behavior of `sqlparser.QueryMatchesTemplates(...)` changed such that if the template has multiple recurring `'val'` values, the new behavior expects them to be equal.
This breaks the `vtctlclient OnlineDDL` behavior, because OnlineDDL's query templates used recurring `'val'`. The templates are now updated, and a new unit test validates their behavior.
https://github.com/vitessio/vitess/issues/11893
#6926
=> v15 backport: Online DDL: fix 'vtctlclient OnlineDDL' template queries (#11889)

doc/releasenotes/15_0_2_summary.md
This PR creates and updates the `v15.0.2` release summary document.
- Fix #11947 
=> Update the release `15.0.2` summary doc

go/test/endtoend/vtgate/queries/subquery/subquery_test.go
The changes made in https://github.com/vitessio/vitess/pull/11911 affected how we treat subqueries/derived tables, it got backported in https://github.com/vitessio/vitess/pull/11922. We skipped the upgrade/downgrade tests for `TestSubqueriesExists` on `main` but did not skip them on `release-15.0`. This PR skips it.
- Fixes https://github.com/vitessio/vitess/issues/11952
=> Skip `TestSubqueriesExists` during upgrade-downgrade tests

.github/CODEOWNERS
Both vtgate components/services are related to VReplication:
- [Tablet Picker](https://vitess.io/docs/16.0/reference/vreplication/tablet_selection/)
- VStream
- https://vitess.io/docs/16.0/concepts/vstream/
- https://deploy-preview-1216--vitess.netlify.app/docs/16.0/reference/vreplication/vstream/
=> CODEOWNERS: Add vrepl team members for vtgate vstream and tablet picker

go/flags/endtoend/vtctld.txt, go/vt/vtctl/vtctl.go, go/vt/vtctld/vtctld.go
What it says in the title. These are only used by the vtctld UI (behind the already-deprecated `enable_realtime_stats` flag.
- #11326 
- #11973 (for the follow up)
=> Migrate missed vtctld flags to pflag and immediately deprecate them

go/vt/vttablet/tabletserver/vstreamer/engine.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
This PR adds the ~~`VStreamersActive`~~ `VStreamerCount` stats metric to `vttablet` to make the # of active streams more observable. There may be a way to infer this using rates from a combination of `VStreamersCreated` and other metrics but I was unable to do so myself (in Prometheus/Grafana) after many attempts so this feels like a rough edge
The length of the VStream engine `streamers` map is used as the number of active streams. This is done without a lock but I'm happy to add one
-   [x] Documentation: https://github.com/vitessio/website/pull/1291
=> Add `VStreamerCount` stat to `vttablet`

go/vt/vtgate/semantics/derived_table.go, go/vt/vtgate/semantics/early_rewriter_test.go, go/vt/vtgate/semantics/vtable.go
Before planning a query, vtgate will simplify the query. One of the simplifications is to expand `*` outputs in the query.
This is only done if we have enough schema information about the tables in the query.
The issue reported in #11880 is related to a derived table where we don't have enough information to expand the columns. Before this fix, we would just use whatever column information we had, which is not correct.
This PR changes the semantic analysis so it keeps track in more places if we can successfully expand columns or not, and will just not expand when we are missing necessary information.
Fixes #11880
=> only expand when we have full information

test/config_partial_keyspace.json
There is no need to run the `vexplain` end-to-end tests on the partial_keyspace test configuration, so this PR removes it.
=> remove e2e test from partial_keyspace config

go/vt/vtgate/planbuilder/operators/SQL_builder.go, go/vt/vtgate/semantics/semantic_state.go
The perfectly valid use case of derived tables that have been pushed under a `Route` lead to a warning from the planner that wasn't really helpful or informative. The solution was to simply remove this logging altogether.
Fixes #11869
=> Remove unnecessary logging

docker/vttestserver/run.sh
This PR fixes the default values for a couple of parameters in the run script used by the vttestserver docker image.
This fixes the issue described in https://github.com/vitessio/vitess/issues/12003. Running the docker image without specifying the `TABLET_REFRESH_INTERVAL` environment variable works just fine after these changes.
The default planner has also been changed to gen4.
- Fixes #12003 
=> Fix vttestserver run script defaults

docker/local/run.sh
This PR adds the VTOrc port to be exported from the docker-local example so that VTOrc dashboard can be accessed.
-   [x] Documentation was added or is not required - https://github.com/vitessio/website/pull/1307
=> Add vtorc port to vitess local docker run

go/vt/vtctl/grpcvtctldserver/server.go, go/vt/vtctl/vdiff2_test.go, go/vt/vtctl/vdiff_env_test.go, go/vt/vttablet/tabletmanager/vdiff/controller.go, go/vt/vttablet/tabletmanager/vdiff/engine.go, go/vt/vttablet/tabletmanager/vdiff/engine_test.go, go/vt/vttablet/tabletmanager/vdiff/framework_test.go, go/vt/vttablet/tabletmanager/vdiff/schema.go, go/vt/vttablet/tabletmanager/vdiff/workflow_differ_test.go, go/vt/vttablet/tabletmanager/vreplication/engine.go, go/vt/vttablet/tabletserver/schema/engine.go, go/vt/wrangler/traffic_switcher_env_test.go, go/vt/wrangler/traffic_switcher_test.go, go/vt/wrangler/vexec_test.go, go/vt/wrangler/workflow.go, go/vt/wrangler/wrangler.go
This effectively ports over the [VDiff1 vtctld/wrangler unit tests](https://github.com/vitessio/vitess/blob/main/go/vt/wrangler/vdiff_test.go) to VDiff2 tablet/tabletmanager and vtctl unit tests, building on the unit test framework code added in https://github.com/vitessio/vitess/pull/11768.
- Fixes: https://github.com/vitessio/vitess/issues/11151
=> VDiff2: Migrate VDiff1 Unit Tests

go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go
Fixes https://github.com/vitessio/vitess/issues/12013 by adding `AND reviewed_timestamp IS NOT NULL` 
fixes https://github.com/vitessio/vitess/issues/12013
=> OnlineDDL: scheduleNextMigration() to only read reviewed migrations

go/vt/sqlparser/utils.go, go/vt/sqlparser/utils_test.go
Additional followup to https://github.com/vitessio/vitess/issues/11893. When `QueryMatchesTemplates()` was created, we only had `sqlparser.String(stmt)`. But today, we have `sqlparser.CanonicalString(stmt)` which is the better function to use, because it canonically and reliably normalizes a query (e.g. fully qualifies names, upper-lower casing it, etc.).
This PR now uses the latter function. All existing tests must pass. Added a couple more tests that specifically targets canonical statement properties.
- https://github.com/vitessio/vitess/issues/11893
- https://github.com/vitessio/vitess/pull/11894
- 
=> sqlparser: `QueryMatchesTemplates` uses canonical string

go/mysql/replication_status.go, go/test/endtoend/reparent/newfeaturetest/reparent_test.go, go/vt/vtctl/reparentutil/emergency_reparenter.go, go/vt/vtctl/reparentutil/emergency_reparenter_test.go, go/vt/vtctl/reparentutil/replication_test.go
This PR fixes the issue raised in #12023. The errant GTID detection code has been fixed to not mark a single replica as errant.
- Fixes #12023 
=> BugFix: Errant GTID detection for a single replica

.github/workflows/codeql_analysis.yml
This is a backport of #11760. When I created the original PR I forgot to backport it to `release-15.0` leading to errors on the workflows in the `release-15.0` branch: https://github.com/vitessio/vitess/actions/workflows/codeql_analysis.yml?query=branch%3Arelease-15.0+is%3Afailure.
=> Fix `codeql` workflow timeout issue (#11760)

docker/vttestserver/run.sh
Backslash was missing, which was causing, that --schema_dir was not applied and therefore alters were not applied and tables in databases were not created. This will fix it
Signed-off-by: kbslvsk <76602353+kbslvsk@users.noreply.github.com>
This is a bug fix, that will fix unapplied option --schema_dir, which was causing alters not applying
https://github.com/vitessio/vitess/issues/12032
N/A
=> Add missing backslash to run.sh script

go/flags/endtoend/vtbackup.txt, go/vt/mysqlctl/compression.go
We missed adding compression related flags to vtbackup during the flags refactor. This PR fixes that.
Fixes #12047 
=> mysqlctl: flags should be added to vtbackup

go/internal/flag/flag.go, go/vt/topo/locks_test.go
This PR fixes the race in `IsFlagProvided` as described in issue #12041. 
The way the fix is accomplished is to replace the usage of `flag.Visit` with `flag.Lookup` which just reads from a single map and doesn't write anything, making it thread-safe.
- Fixes #12041 
=> BugFix: Fix race in `IsFlagProvided`

doc/releasenotes/16_0_0_summary.md, go/stats/prometheusbackend/collectors.go, go/stats/prometheusbackend/prometheusbackend_test.go
Here's a bug we've found in production: when exporting Prometheus metrics, the name of the labels is not consistent when using Single-Label metrics vs Multi-Label metrics. More precisely, the Single-Label metrics API does not perform label normalization (i.e. from CamelCase to snake_case), while the Multi-Label API does perform this normalization.
The normalization into snake_case *is* sensible, as metric names in Prometheus are idiomatically written in snake case, so the lack of normalization when using single-label metrics feels like an oversight that caused our Prometheus metrics exports to report the wrong metrics.
After this change, the behavior between using a Single-Label metric and a Multi-Label metric with just one label is consistent. This is, however, a breaking change so it …
=> stats/prometheus: normalize labels for single-label implementations

go/vt/sqlparser/ast_funcs.go, go/vt/sqlparser/predicate_rewriting.go, go/vt/sqlparser/rewriter_api.go, go/vt/vtgate/planbuilder/ddl.go, go/vt/vtgate/planbuilder/delete.go, go/vt/vtgate/planbuilder/gen4_planner.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/operators/SQL_builder.go, go/vt/vtgate/planbuilder/operators/expressions.go, go/vt/vtgate/planbuilder/operators/join.go, go/vt/vtgate/planbuilder/operators/logical.go, go/vt/vtgate/planbuilder/operators/subquery_planning.go, go/vt/vtgate/planbuilder/operators/union.go, go/vt/vtgate/planbuilder/projection_pushing.go, go/vt/vtgate/planbuilder/single_sharded_shortcut.go, go/vt/vtgate/semantics/analyzer.go, go/vt/vtgate/semantics/early_rewriter.go, go/vt/vtgate/semantics/semantic_state.go, go/vt/vtgate/simplifier/expression_simplifier.go, go/vt/vtgate/vindexes/vschema.go, go/vt/vttablet/tabletserver/planbuilder/builder.go
Refactor of sqlparser.Rewrite usages.
Doing cursor.Replace() on the down path is not great.
It makes it difficult to understand what happens after - do we visit the children of the old AST object or the new one?
This change moves most uses of Rewrite so cursor.Replace() happens on the up path.
In a separate PR, I'll change the API so it's not possible to do replace on the down path.
=> Refactor sqlparser.Rewrite uses

go/vt/vtorc/db/db.go, go/vt/vtorc/inst/analysis_dao.go, go/vt/vtorc/inst/analysis_dao_test.go, go/vt/vtorc/test/recovery_analysis.go
This PR fixes issue #12018.
The proposed fix is to convert the `JOIN` back to a `LEFT JOIN` and add code to not run a fix until that information is populated.
This PR adds significant test code to test the situation described in the issue. The problem is very hard to reproduce as an end-to-end test or even as a simple unit test. Therefore I had to rely on a relatively complex test that uses an SQLdump from an actual running VTOrc instance and then gets to the situation as described.
- Fixes #12018 
=> VTOrc running PRS when database_instance empty bug fix.

go/flags/endtoend/vtbackup.txt, go/flags/endtoend/vtctld.txt, go/flags/endtoend/vttablet.txt, go/flags/endtoend/vttestserver.txt, go/vt/mysqlctl/backup.go
Since we have deprecated [backup_storage_hook] (https://github.com/vitessio/vitess/commit/8aebb6fdbd6b07024c3df7c14f2edbdf52c9f5dc), there is no need to specify it in other flag's description.
=> remove backup_hook from flag help

.github/workflows/check_label.yml
This PR adds the required changes to the CI to fail future PRs with the `NeedsWebsiteDocsUpdate` or `NeedsDescriptionUpdate` labels on.
When CI fails, there is a message inviting the contributor to update either the PR's description or the documentation.
=> Fail CI when a PR is labeled with `NeedsWebsiteDocsUpdate` or `NeedsDescriptionUpdate`

doc/releasenotes/16_0_0_summary.md, go/vt/vtctl/vtctl.go
The [`VReplicationExec` client command](https://vitess.io/docs/16.0/reference/vreplication/vreplicationexec/) leverages the `VReplicationExec` tabletmanager RPC: https://github.com/vitessio/vitess/blob/7fc1b48d9ea8f10afa597a1e3885b4fb55f3b6be/go/vt/vttablet/grpctmserver/server.go#L355-L361 ▶️ ▶️ ▶️  https://github.com/vitessio/vitess/blob/7fc1b48d9ea8f10afa597a1e3885b4fb55f3b6be/go/vt/vttablet/tabletmanager/rpc_vreplication.go#L27-L34 
This client-server interface needs to be replaced because it does not do proper encapsulation and instead exposes the raw SQL interface. This causes problems for upgrades/downgrades where the internal schema changes as e.g. shown in https://github.com/vitessio/vitess/issues/11535. As you can see from that bug report this RPC is used internally by, among …
=> Mark VReplicationExec Client Command as Deprecated

doc/releasenotes/16_0_0_release_notes.md, go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go, go/vt/schema/ddl_strategy.go, go/vt/schema/ddl_strategy_test.go, go/vt/vttablet/onlineddl/executor.go
This PR introduces a new [DDL strategy](https://vitess.io/docs/15.0/user-guides/schema-changes/ddl-strategies/): `mysql`. This strategy is a hybrid between `direct` (which is completely non-Online) and the various online strategies.
A migration submitted with `mysql` strategy is _managed_. That is, it gets a migration UUID. The scheduler queues it, reviews it, runs it. The user may cancel or retry it, much like all Online DDL migrations. The difference is that when the scheduler runs the migration via normal MySQL `CREATE/ALTER/DROP TABLE` statements.
The user may add `ALGORITHM=INPLACE` or `ALGORITHM=INSTANT` as they please, and the scheduler will attempt to run those as is. Some migrations will be completely blocking. See the [MySQL …
=> OnlineDDL: 'mysql' strategy, managed by the scheduler, but executed via normal MySQL statements

go/test/endtoend/utils/utils.go, go/test/endtoend/vtgate/reservedconn/main_test.go, go/test/endtoend/vtgate/reservedconn/sysvar_test.go, go/vt/sysvars/sysvars.go, go/vt/vtgate/engine/fake_vcursor_test.go, go/vt/vtgate/engine/primitive.go, go/vt/vtgate/engine/set.go, go/vt/vtgate/executor_dml_test.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/executor_set_test.go, go/vt/vtgate/executor_test.go, go/vt/vtgate/planbuilder/testdata/set_cases.json, go/vt/vtgate/safe_session.go, go/vt/vtgate/safe_session_test.go, go/vt/vtgate/vcursor_impl.go
This PR moves the transaction isolation system variables (transaction_isolation or set transaction isolation level) from vitess aware to reserved connection.
Earlier it used to only work with transactions. With this change, support will be added for read queries.
- Closes https://github.com/vitessio/vitess/issues/11810
- Related to https://github.com/vitessio/vitess/pull/11673 and https://github.com/vitessio/vitess/pull/11804
=> support transaction isolation modification through reserved connection system settings

go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
GitHub did not seem to pick up the merge conflict between these two commits (older to newer):
- https://github.com/vitessio/vitess/commit/673573ab5097eb48289ce32d3093fb3d6d2b027a
- https://github.com/vitessio/vitess/commit/836b3c1e7df43c1474f0686363a824e7aeefdecc
The first (earlier) commit changed the function signature for `testOnlineDDLStatement()`, while the second (later) commit used the old signature. I noticed that GitHub/Azure was having all sorts of strange issues around the time that https://github.com/vitessio/vitess/pull/12027 was merged so I suspect that's why it did not pick up on the merge conflict.
This was then blocking new PRs as it caused all of these workflows to fail:
- `onlineddl_declarative`
- `onlineddl_scheduler`
- `onlineddl_scheduler/mysql57`
- `Static Code …
=> Internal: Fix Bad Merge

doc/releasenotes/16_0_0_summary.md, go/cmd/vtctl/vtctl.go, go/test/endtoend/cluster/cluster_util.go, go/test/endtoend/vreplication/vdiff_helper_test.go, go/test/endtoend/vreplication/vreplication_test.go, go/vt/vtctl/vdiff2.go, go/vt/vtctl/vtctl.go, go/vt/vttablet/tabletmanager/vdiff/README.md
[VDiff v2](https://vitess.io/docs/16.0/reference/vreplication/vdiff2/) is now considered [feature complete](https://github.com/vitessio/vitess/issues/10494) and has been experimental for 1+ releases now so we are marking it as Generally Available or production-ready in v16. For now we will hold off on deprecating v1 — with an eventual removal coming 1+ releases after the deprecation — but the deprecation should probably be done in v17.
- https://github.com/vitessio/vitess/issues/10494
-   [x] Documentation: https://github.com/vitessio/website/pull/1347
=> Mark VDiff V2 as GA in v16

go/vt/binlog/binlog_connection.go, go/vt/binlog/binlog_streamer.go, go/vt/binlog/binlog_streamer_rbr_test.go, go/vt/binlog/binlog_streamer_test.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
This PR adds an errors channel to the binlog streamer so that we can propagate stream errors back to the caller/client. See [the bug report](https://github.com/vitessio/vitess/issues/12093) for additional details.
The key final snippet of the `show` output from the bug report's test case is now:
```
"State": "Error",
"Message": "vttablet: rpc error: code = Unknown desc = stream (at source tablet) error @ a61630ee-9379-11ed-b080-97c823585086:1-71: Cannot replicate because the master purged required binary logs. Replicate the missing transactions from elsewhere, or provision a new slave from backup. Consider increasing the master's binary log expiration period. The GTID set sent by the slave is 'a61630ee-9379-11ed-b080-97c823585086:1-71', and the missing transactions are …
```
=> VReplication: Propagate Binlog Stream Errors

go/vt/vtorc/logic/topology_recovery_dao.go, go/vt/vtorc/logic/topology_recovery_dao_test.go
This PR fixes the insertion query for `blocked_recovery` table for VTOrc which was broken in #12012. 
- Fixes #12090 
=> Fix insert query of blocked_recovery table in VTOrc

go/vt/sqlparser/ast_format.go, go/vt/sqlparser/tracked_buffer_test.go
The canonical string representation needs to keep the correct case for the charset. Those are never upcased in MySQL so we should not enforce that here either.
Fixes #12104
=> Keep the correct case for the charset for canonical string

go/test/endtoend/vtgate/queries/misc/misc_test.go, go/vt/vtgate/evalengine/convert.go, go/vt/vtgate/evalengine/translate.go, go/vt/vtgate/evalengine/translate_test.go
This PR fixes the bug described in #12110. The issue is that the evalengine converts the expression into a eval engine expression whose evaluation isn't supported at runtime. What this means is that planning phase succeeds but the runtime throws an error.
This isn't correct since we have an alternate way of planning of not using the evaluation engine and send the query to a vttablet like we did before evalengine existed. 
This PR fixes this bug by failing the translation itself instead of creating an expression that can't be evaluated.
- Fixes #12110 
=> BugFix: Cast expression translation by evaluation engine

go/test/endtoend/tabletmanager/throttler_topo/throttler_test.go
An attempt to fix `tabletmanager_throttler_topo` flakiness, as seen [here](https://github.com/planetscale/vitess-private/actions/runs/3913922615/jobs/6690389759#logs). In a few places where we expect to find a status "OK", we now poll for the status until "OK" is received, or until some timeout (at which time the test fails).
The flakiness is only found in GitHub CI and never in my local tests, which suggests this is a timing issue. This fix hopefully works around it.
=> CI, tabletmanager throttler topo tests: polling until status received

go/test/endtoend/vtgate/misc_test.go, go/vt/vtgate/evalengine/convert.go, go/vt/vtgate/evalengine/translate.go, go/vt/vtgate/evalengine/translate_test.go
=> [release-14.0] BugFix: Cast expression translation by evaluation engine (#12111)

go/cmd/vtexplain/vtexplain.go, go/flags/endtoend/vtexplain.txt
This PR fixes the issue described in #12020. Gen4 is now the default planner version for VTExplain.
- Fixes #12020.
=> Use Gen4 as the default planner version for VTExplain

go/vt/sqlparser/ast_funcs.go, go/vt/sqlparser/ast_rewriting.go, go/vt/sqlparser/normalizer.go, go/vt/sqlparser/rewriter_api.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/operator_transformers.go, go/vt/vtgate/planbuilder/operators/queryprojection.go, go/vt/vtgate/semantics/early_rewriter.go
More of the same - we want to only change the AST after visiting the children of a struct, and not before.
If we allow changing the struct we are standing on, and then visiting it, we would need to update the generated code to allow for this. The current code allows this to happen but the behaviour is not tested and probably buggy. In all places I could find, we were only doing this replacement on leaf nodes, which probably was our saving grace.
This PR changes more places to use `SafeRewrite`, which through the API only allows for changing the AST after visiting the children.
Part of https://github.com/vitessio/vitess/issues/12123
-   [x] Documentation was added …
=> Move more rewriting to SafeRewrite

go/test/endtoend/cluster/vtctld_process.go, go/test/endtoend/cluster/vttablet_process.go, go/test/endtoend/reparent/emergencyreparent/ers_test.go, go/test/endtoend/reparent/utils/utils.go
This PR removes the flags removed from v16 to be set on binaries from that and later releases. This change is required because we run upgrade-downgrade tests which spawn binaries from the next release too. So the flags removed in #12083 and #12085 have to be put behind a condition check to see if the spawned binary is from a version higher than 15 or not.
This PR makes these changes to fix the upgrade-downgrade tests which are currently broken as seen in https://github.com/vitessio/vitess/actions/runs/3949422838/jobs/6763433594
=> Remove removed flags from being used for v16+ binaries

go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go, go/vt/schemadiff/types.go
`schemadiff`: adding a new hint, named `TableCharsetCollateStrategy`, which controls how `schemadiff` treats diffs in a table's `CHARSET` and `COLLATE` option values:
- `TableCharsetCollateStrict` - default, if charsets or collations are different, that's a diff.
- `TableCharsetCollateIgnoreEmpty` - if one of the tables has no value for `CHARSET` or `COLLATE`, ignore the diff (works whether the source table or target table have empty values)
- `TableCharsetCollateIgnoreAlways` - never generate a table charset/collate diff
=> schemadiff: TableCharsetCollateStrategy hint

go/test/endtoend/vtgate/grpc_server_auth_static/main_test.go, go/vt/servenv/grpc_server_auth_static.go, go/vt/vtgate/grpcvtgateservice/server.go, test/config.json
Signed-off-by: Brendan Dougherty <brendan.dougherty@shopify.com>
Currently, when using gRPC static auth on VTGate, the immediate caller id is always set to `unsecure_grpc_client`, rather than the username provided by the client. This means that table ACLs on VTTablet will reject the client's queries.
The problem appears to have been discussed when static auth was originally added [here](https://github.com/vitessio/vitess/pull/3418#discussion_r154534073), but was not changed in a followup.
This PR takes a similar approach to what was suggested and sets the authenticated username in the Context. This allows the VTGate server to retrieve the username in a similar manner to how it retrieves the certificate common name as the immediate caller id when using mTLS …
=> VTGate: Set immediate caller id from gRPC static auth username

go/vt/vttablet/tabletserver/planbuilder/plan_test.go, go/vt/vttablet/tabletserver/planbuilder/testdata/ddl_cases.txt, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/query_executor_test.go, go/vt/vttablet/tabletserver/schema/engine.go
In `query_executor.go`, in `execDDL()`, we differentiate two cases:
1. The query is an Online DDL
2. The query is not Online DDL
In the latter case, we always invoke `Reload()` (specifically `ReloadAtEx()`) to reload table schema. 
However, for `CREATE TEMPORARY TABLE` and `DROP TEMPORARY TABLE` this is wasteful:
- Only the connections which created or dropped the table is at all aware of the existence of the table
- `Reload()` adds an overhead which becomes significant if temporary tables are created and dropped intensively.
With this PR we skip `Reload()` for temporary tables.
=> DDL: do not Reload() for 'CREATE TEMPORARY' and 'DROP TEMPORARY' statements

go/vt/vitessdriver/rows.go, go/vt/vitessdriver/rows_test.go
I attempted to use https://github.com/jimsmart/schema to introspect the vitess schema via the vitessdriver. Much to my surprise all of the column types were returned as `interface{}`. I dug deeper and found that the Go sql code attempts to cast the row to `RowsColumnTypeScanType` and if that fails it will not be able to return the types.
`RowsColumnTypeScanType` contains just one function that I've implemented below. Example of how the mysql drivers implemented it: https://github.com/go-sql-driver/mysql/blob/4591e42e65cf483147a7c7a4f4cfeac81b21c917/fields.go#L140
Overall it's fairly straight forward I have tested it against our vitess locally. However a few of the types are unfamiliar to me, such as HEXNUM so any extra eyes would be appreciated.
Adding the vitess dialect to the schema …
=> Implement the RowsColumnTypeScanType interface in the go sql driver

docker/lite/install_dependencies.sh
Related to #7802
I would like to have zstd CLI available in Docker lite images so that when using VTOP-deployed Vitess I can take advantage of the fact that zstd external is apparently much faster (see https://github.com/vitessio/vitess/pull/11994) than the native Go library.
`docker inspect <image> | jq -r .[].Size`
| Target | 7fc1b48d9 | This PR | ∆ |
|-------|--------|------|-------|
| lite_mysql57  | 1230530599 | 1231544936 | +1014337 (+0.082%) |
| lite_mysql80  | 1222034851 | 1223049180 | +1014329 (+0.083%) |
| lite_percona57  | 1151917943 | 1152923524 | +1005581 (+0.087%) |
| lite_percona80  | 1818075338 | 1819080907 | +1005569 (+0.0553%) |
| lite_testing  | 797503720 | 798774969 | +1271249 (+0.159%) |
| lite_ubi7.mysql57  | ⚠️ | ⚠️ | ⚠️ |
| lite_ubi7.mysql80  | ⚠️ | ⚠️ | ⚠️ |
| …
=> docker/lite: +zstd dep

doc/releasenotes/16_0_0_summary.md, go/vt/mysqlctl/compression_benchmark_test.go
Relates to #7802.
These benchmarks are proving useful in internal discussions around improving the performance of backups. Sharing here in case others find them useful. 
This benchmark downloads and compresses [this ~60GB InnoDB file](https://archive.org/details/enwiki-20221220-externallinks.ibd), which was built by loading [this Wikipedia dataset](https://dumps.wikimedia.org/enwiki/20221220/enwiki-20221220-externallinks.sql.gz) into MySQL 8.
```
$ go test -bench=BenchmarkCompress ./go/vt/mysqlctl -run=NONE -timeout=12h -benchtime=1x -v
goos: darwin
goarch: arm64
pkg: vitess.io/vitess/go/vt/mysqlctl
BenchmarkCompressLz4Builtin
compression_benchmark_test.go:310: downloading data from https://www.dropbox.com/s/raw/smmgifsooy5qytd/enwiki-20080103-pages-articles.ibd.tar.zst …
```
=> go/vt/mysqlctl: add compression benchmarks

go/vt/schemadiff/column.go, go/vt/schemadiff/schema.go, go/vt/schemadiff/table.go, go/vt/sqlparser/ast.go, go/vt/sqlparser/ast_clone.go, go/vt/sqlparser/ast_copy_on_rewrite.go, go/vt/sqlparser/ast_equals.go, go/vt/sqlparser/ast_format.go, go/vt/sqlparser/ast_format_fast.go, go/vt/sqlparser/ast_rewrite.go, go/vt/sqlparser/ast_visit.go, go/vt/sqlparser/cached_size.go, go/vt/sqlparser/sql.go, go/vt/sqlparser/sql.y
Small PR that makes an AST type consistently used as reference instead of value.
`ColumnType` was sometimes used as a value type although only the reference type implements the SQLNode interface, which lead to unwanted behaviour such as these fields not being seen by the AST tooling (Equality, Cloning and Rewriting).
=> Clean up ColumnType uses

go/test/endtoend/vtgate/queries/misc/misc_test.go, go/vt/vtgate/evalengine/translate.go, go/vt/vtgate/evalengine/translate_test.go, go/vt/vtgate/planbuilder/testdata/from_cases.json
Adds support for `BETWEEN` in the eval engine, by translating them to `=>` and `=<` comparisons, or the equivalent for `NOT BETWEEN.
Solves part of https://github.com/vitessio/vitess/issues/9647
=> Support BETWEEN in the evalengine

doc/releasenotes/16_0_0_summary.md, go/vt/vtadmin/api.go
Title says it all (mostly). With the introduction of [`vexplain`], we're phasing out use of the simulated vtexplain code, which can sometimes, and I quote, "make stuff up".
[`vexplain`]: https://github.com/vitessio/vitess/pull/11892
Since vtadmin is GA, we're going with the two-step deprecate (this PR) and delete (for which I have filed #12161)
=> [vtadmin] deprecated vtexplain

go/test/endtoend/vtgate/gen4/system_schema_test.go, go/vt/vtgate/planbuilder/testdata/systemtables_cases80.json, go/vt/vtgate/semantics/table_collector.go
In recent changes, we have added schema information about the `information_schema` database to the vschema. This means that we started asking the vschema about schema information even about system tables.
Since `sys`, `performance_schema` and `mysql` were not added to the vschema, vtgate started to fail planning queries against these databases complaining about the database not existing.
```sql
> SELECT variable, value, set_time, set_by FROM sys.sys_config;
ERROR 1105 (HY000): Unknown database 'sys' in vschema
```
The bug was introduced in https://github.com/vitessio/vitess/pull/11941
Fixes: https://github.com/vitessio/vitess/issues/12176 …
=> handle system databases other that information_schema correctly

go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go, test/config.json
Similarly to https://github.com/vitessio/vitess/pull/12055, the `onlineddl_scheduler` tests now include testing for `declarative`, effectively making `onlineddl_declarative` redundant.
In this PR we do not yet remove `onlineddl_declarative`, because we can't atomically merge the PR while removing a `required` test from the very same PR. A followup PR will remove both `onlineddl_singleton` and `onlineddl_declarative` tests and workflows.
The objective of this change is to reduce CI workflow files.
#6926
=> consolidating OnlineDDL 'declarative' tests into 'scheduler' tests: part 1

go/test/endtoend/onlineddl/revert/onlineddl_revert_test.go, go/test/endtoend/onlineddl/revertible/onlineddl_revertible_test.go, test/config.json
Similarly to https://github.com/vitessio/vitess/pull/12061 and https://github.com/vitessio/vitess/pull/12055, we now consolidate `onlineddl_revertible` into `onlineddl_revert`.
After this has been merged, we can remove the `Required` tag from `onlineddl_revertible` and then followup with a romval PR, much like https://github.com/vitessio/vitess/pull/12182
This will free two CI workflows.
#6926
=> Online DDL CI: consolidated revertible and revert CI tests (part 1)

go/sqltypes/value.go, go/sqltypes/value_test.go
We can use big.Int directly to parse this and convert it to bytes. We don't need to parse it into an integer, nor use an intermediate hex encoding either.
Fixes https://github.com/vitessio/vitess/issues/12190
=> Fix parsing of bitnum values larger than 64 bit

go/vt/discovery/healthcheck.go, go/vt/discovery/healthcheck_test.go
The VTGate HealthCheck cache has an [authoritative map of tablets](https://github.com/vitessio/vitess/blob/release-15.0/go/vt/discovery/healthcheck.go#L267-L268) — keyed by tabletAlias — that it uses for query serving. It has a [secondary map](https://github.com/vitessio/vitess/blob/release-15.0/go/vt/discovery/healthcheck.go#L269-L272) — keyed by `<keyspace>.<shard>.<tabletType>` which has a sorted list of tablets that is used when printing the contents of the cache for the vtgate `/debug/status` endpoint and for the `show vitess_tablets` SQL statement without blocking query serving (lock free in the hot path).
The healthcheck cache implementation in the `discovery` package is responsible for keeping those two maps in sync as tablets are added and removed. There was one case, however, …
=> VTGate: Ensure HealthCheck Cache Secondary Maps Stay in Sync With Authoritative Map on Tablet Delete

go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go, go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go, go/test/endtoend/onlineddl/vrepl_stress/onlineddl_vrepl_mini_stress_test.go, go/test/endtoend/onlineddl/vtgate_util.go, go/vt/vttablet/onlineddl/executor.go
Fixes https://github.com/vitessio/vitess/issues/12168
This PR prevents excessive gaps in `_vt.schema_migrations` `id` values with a small refactor:
- Instead of relying on `INSERT IGNORE`, we first `SELECT` for existing migration UUID, and only if it does not exist, we `INSERT`.
- Because this is now a two-step logic, we add a mutex around the function (the mutex is only used by `SubmitMigration` function and does not otherwise conflict with the rest of the scheduler's work)
- The logic that used to _follow_ the `INSERT IGNORE`, which addresses the case where the UUID pre-existed, is now moved to run _before_ `INSERT IGNORE`
Tests are unchanged. We expect no change in behavior.
https://github.com/vitessio/vitess/issues/12168
-   [ ] "Backport to:" labels have been added if this change …
=> OnlineDDL: avoid schema_migrations AUTO_INCREMENT gaps by pre-checking for existing migration

.github/workflows/create_release.yml
This moves the release package build CI workflow to Ubuntu 20.04, which is the [oldest supported Linux distro available on GitHub hosted runners](https://github.com/actions/runner-images/blob/main/README.md) today.
This will get us back to what we were using with v14 and the `vtorc` binary — which links in the native `sqlite` `C` library via `cgo` — will be usable on a larger set of Linux distros. For additional details see: https://github.com/vitessio/vitess/issues/12185
We may want to investigate additional options at some point, even going so far as attempting to statically link `glibc` in `sqlite` and using that resulting archive rather than shared object, but this PR gets us back to where we were and improves the situation significantly.
- Helps with: …
=> Use Ubuntu 20.04 for Release Builds

go/vt/vtgate/vtgateconn/vtgateconn.go, go/vt/vtgate/vtgateconn/vtgateconn_test.go
Allows removing a named dialer to clean up when it is no longer needed. Inspired by similar APIs in go-sql-driver/mysql: https://pkg.go.dev/github.com/go-sql-driver/mysql
Fixes #12212.
=> vtgateconn: add DeregisterDialer hook

.github/workflows/codeql_analysis.yml
This allows for running it on other branches manually to test to see if it helps address issues that it reports.
Wanted to see what it reports for #12199 but we can't run it today without merging things. 
=> Allow manually kicking off CodeQL

.github/workflows/create_release.yml
The underlying issue has now been addressed in: https://github.com/vitessio/vitess/pull/12214
- Related to: https://github.com/vitessio/vitess/issues/12185
- Follow-up to: https://github.com/vitessio/vitess/pull/12214
-   [x] Tests re not required
=> Revert "Use ubuntu 20.04 for release builds (#12202)"

doc/releasenotes/16_0_0_summary.md
This is a follow-up of the PR https://github.com/vitessio/vitess/pull/12054, and the command made in https://github.com/vitessio/vitess/pull/12054#discussion_r1094875495.
The release notes summary that mentions the new default MySQL version in our Docker images is fixed.
=> Update release notes summary for the new default MySQL version

go/vt/discovery/healthcheck_test.go
We added new test code in https://github.com/vitessio/vitess/pull/12178 to ensure that when removing a tablet from the healthcheck cache (by Alias) we are properly/fully deleting the tablet from the secondary healthcheck maps. See that PR for more details.
Subsequently, we've seen the race tests failing regularly like this:
```
--- FAIL: TestRemoveTablet (0.01s)
healthcheck_test.go:727: [unexpected result]: (-want +got)
  []*discovery.TabletHealth{
  	&{
  		... // 1 ignored field
  		Tablet:               s`alias:{cell:"cell"} hostname:"a" port_map:{key:"grpc" value:2} p`...,
  		Target:               s`keyspace:"k" shard:"s" tablet_type:REPLICA`,
- 		Stats:                s"replication_lag_seconds:1 cpu_usage:0.2",
+ 		Stats:                nil,
  		PrimaryTermStartTime: 0,
   …
```
=> Flakes: Properly Test HealthCheck Cache Response Handling

go/vt/schemadiff/schema.go, go/vt/schemadiff/schema_test.go
fixes https://github.com/vitessio/vitess/issues/12188
Ensures an internal counter is at least `1` after iterating list of tables; if the list of tables is empty, the counter was never incremented.
Added tests that fail before the fix and of course pass with the fix. 
https://github.com/vitessio/vitess/issues/12188
=> schemadiff: fix scenario where no tables exist in schema and with just views reading from DUAL

go/test/endtoend/vtgate/lookup_test.go, go/test/endtoend/vtgate/main_test.go, go/test/endtoend/vtgate/schema.sql, go/test/endtoend/vtgate/vschema.json, go/vt/vtgate/engine/fake_vcursor_test.go, go/vt/vtgate/engine/primitive.go, go/vt/vtgate/engine/vindex_lookup.go, go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/vcursor_impl.go, go/vt/vtgate/vindexes/consistent_lookup.go, go/vt/vtgate/vindexes/lookup.go, go/vt/vtgate/vindexes/lookup_hash.go, go/vt/vtgate/vindexes/lookup_unicodeloosemd5_hash.go, go/vt/vtgate/vindexes/vindex.go
The `VindexLookup` primitive re-implemented some parts of the lookup vindex functionality, but missed to honor the `autocommit` flag. This pull request changes `VindexLookup` to re-use existing logic instead of using a separate implementation.
- Fixes https://github.com/vitessio/vitess/issues/12173
=> [Gen4] Fix lookup vindexes with `autocommit` enabled

go/sqltypes/named_result.go, go/sqltypes/value.go, go/vt/binlog/binlogplayer/binlog_player.go, go/vt/vtctl/workflow/server.go, go/vt/vtctl/workflow/stream_migrator.go, go/vt/vtctl/workflow/traffic_switcher.go, go/vt/vttablet/onlineddl/vrepl.go, go/vt/vttablet/tabletmanager/vreplication/engine.go, go/vt/vttablet/tabletmanager/vreplication/insert_generator.go, go/vt/vttablet/tabletmanager/vreplication/insert_generator_test.go, go/vt/vttablet/tabletmanager/vreplication/vreplicator.go, go/vt/wrangler/materializer.go, go/vt/wrangler/resharder.go, go/vt/wrangler/vexec.go
This addresses a number of the issues identified by CodeQL around typecasting. We use 32 bit integers for these, so let's make sure we parse and cast then as those everywhere it matters.
Part of https://github.com/vitessio/vitess/issues/12216
=> Fix typecasting issue for workflow types

go/mysql/binlog_event_filepos.go, go/mysql/filepos_gtid.go, go/mysql/filepos_gtid_test.go, go/mysql/flavor.go, go/mysql/flavor_filepos.go
This is defined as uint32 at the protocol level, so better to use that type consistently and also parse it accordingly with `ParseUint` with the right size.
Part of #12216 as this was flagged there.
=> Use the correct uint32 type for the GTID file position

go/vt/throttler/throttlerlogz.go, go/vt/throttler/throttlerlogz_test.go, go/vt/throttler/throttlerz.go, go/vt/vtctl/vtctldclient/codegen/main.go
This addresses two classes of issues that CodeQL found. One is a not as strict as needed regexp for a domain match, where there's no literal `.` being matched.
The other is a user controlled XSS since we run the template with arbitrary user input. Instead we validate if the throttler with that name actually exists before trying to execute the template.
On error we also don't reflect the input to avoid the same XSS.
Part of #12216
=> Fix CodeQL identified issues

go/test/endtoend/vreplication/cluster_test.go
The current mirror listed seems to be missing this, so let's point it at a working one.
=> Use a working MariaDB mirror for CI

doc/internal/ReleaseInstructions.md
This PR is part of https://github.com/vitessio/vitess/issues/12233. It adds two mentions in the release instructions so we don't forget to update the `main` SNAPSHOT version and we copy branch protections rules for new branches.
- Part of https://github.com/vitessio/vitess/issues/12233
=> Update the release instructions after v16 code freeze

go/test/endtoend/vtgate/grpc_server_auth_static/main_test.go, go/vt/vitessdriver/driver.go, go/vt/vtgate/grpcvtgateconn/conn.go
Resolves a linked issue relating to Go variable scopes.
Fixes #12209.
=> grpcvtgateconn: add Dial and deprecate DialWithOpts

go/cmd/vtbackup/vtbackup.go, go/cmd/vtcombo/main.go, go/mysql/constants.go, go/mysql/flavor.go, go/mysql/flavor_mariadb_test.go, go/mysql/flavor_mysql_test.go, go/mysql/flavor_mysqlgr.go, go/mysql/flavor_mysqlgr_test.go, go/mysql/replication_status.go, go/sqltypes/value.go, go/vt/mysqlctl/fakemysqldaemon/fakemysqldaemon.go, go/vt/mysqlctl/mysql_daemon.go, go/vt/mysqlctl/replication.go, go/vt/vttablet/tabletmanager/rpc_replication.go, go/vt/vttablet/tabletmanager/tm_init.go, go/vt/wrangler/testlib/planned_reparent_shard_test.go, go/vt/wrangler/testlib/reparent_utils_test.go
These are used as int32 in the protobuf (and enum maps to int32 for replication state). This means we should also keep using int32 internally if easily possible.
Part of #12216 
=> Use consistent type port and replication state

doc/releasenotes/16_0_0_summary.md, docker/lite/install_dependencies.sh, go/flags/endtoend/mysqlctl.txt, go/flags/endtoend/mysqlctld.txt, go/flags/endtoend/vtbackup.txt, go/flags/endtoend/vtctldclient.txt, go/flags/endtoend/vtexplain.txt, go/flags/endtoend/vtgate.txt, go/flags/endtoend/vttablet.txt, go/flags/endtoend/vttestserver.txt, go/vt/servenv/buildinfo_test.go, go/vt/servenv/mysql.go
=> [release-16.0] Revert default MySQL 80 version to `8.0.30` (#12252)

go/test/endtoend/vreplication/cluster_test.go, go/test/endtoend/vreplication/vreplication_test.go
We are now downloading MariaDB from [vitess-resources v4](https://github.com/vitessio/vitess-resources/releases/tag/v4.0).
=> Download mariadb from vitess-resources

.github/workflows/code_freeze.yml, doc/releasenotes/16_0_0_changelog.md, doc/releasenotes/16_0_0_release_notes.md, docker/release.sh, examples/compose/docker-compose.beginners.yml, examples/compose/docker-compose.yml, examples/compose/vtcompose/docker-compose.test.yml, examples/compose/vtcompose/vtcompose.go, examples/operator/101_initial_cluster.yaml, examples/operator/201_customer_tablets.yaml, examples/operator/302_new_shards.yaml, examples/operator/306_down_shard_0.yaml, examples/operator/operator.yaml, go/vt/servenv/version.go, java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/jdbc/pom.xml, java/pom.xml
Includes the release notes and release commit for the v16.0.0-rc1 release. Once this PR is merged, we will be able to tag v16.0.0-rc1 on the merge commit.
=> Release of v16.0.0-rc1

go/vt/vtctl/vtctl_test.go, go/vt/wrangler/traffic_switcher_env_test.go, go/vt/wrangler/vexec.go, go/vt/wrangler/vexec_test.go, go/vt/wrangler/wrangler_env_test.go
During the copy phase Vitess periodically updates rows copied for each stream. This value is a _cumulative_ count for all tables that are part of this stream.
This PR displays the rows copied in the `Workflow Show` command (https://vitess.io/docs/reference/vreplication/workflow/).
https://github.com/vitessio/vitess/issues/12203
=> Workflow Show: display rows copied 

docker/release.sh, go/vt/servenv/version.go, java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/jdbc/pom.xml, java/pom.xml
Includes the changes required to go back into dev mode (v16.0.0-SNAPSHOT) after the release of v16.0.0-rc1.
- #11749
=> Back to dev mode after v16.0.0-rc1

go/vt/vtgate/planbuilder/operators/helpers.go, go/vt/vtgate/planbuilder/operators/rewrite/rewriters.go, go/vt/vtgate/planbuilder/operators/route_planning.go, go/vt/vtgate/planbuilder/operators/subquery_planning.go, go/vt/vtgate/planbuilder/operators/union.go, go/vt/vtgate/planbuilder/testdata/filter_cases.json, go/vt/vtgate/planbuilder/testdata/select_cases.json
Fixes how we route dual tables. MySQL has a little weird way of routing the `dual` table.
```sql
mysql> select 1 from dual;
+---+
| 1 |
+---+
| 1 |
+---+
mysql> select 1 from `dual`;
ERROR 1046 (3D000): No database selected
mysql> use test;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A
Database changed
mysql> create table `dual`(id bigint not null);
Query OK, 0 rows affected (0.01 sec)
mysql> select 1 from `dual`;
Empty set (0.00 sec)
mysql> select 1 from dual;
+---+
| 1 |
+---+
| 1 |
+---+
mysql> select 1 from test.dual;
Empty set (0.00 sec)
```
As can be seen in the little session above, ``` `dual` ``` and ```dual``` are handled differently. When qualified …
=> fix dual table handling

go/vt/vttablet/tabletmanager/vreplication/controller.go, go/vt/vttablet/tabletmanager/vreplication/last_error.go, go/vt/vttablet/tabletmanager/vreplication/last_error_test.go
This PR fixes a bug where a VReplication workflow doesn't restart if the same error happened far enough in the past as to be beyond the defined `--vreplication_max_time_to_retry_on_error`.
See related issue for more details.
https://github.com/vitessio/vitess/issues/12101
=> VReplication Last Error: retry error if it happens after timeout

go/vt/sqlparser/precedence.go, go/vt/sqlparser/precedence_test.go
This PR adds the precedence rule for Null Safe Comparator
- Fixes https://github.com/vitessio/vitess/issues/12120
-   [X] "Backport to:" labels have been added if this change should be back-ported 14.0, 15.0, 16.0
=> fix: added null safe operator precendence rule

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.json, go/vt/vtgate/planbuilder/testdata/filter_cases.json, go/vt/vtgate/planbuilder/testdata/tpch_cases.json
This PR fixes an issue with aggregation on the left join by adding coalesce on the result from the right-hand side table.
- Fixes https://github.com/vitessio/vitess/issues/12269
-   [X] "Backport to:" labels have been added if this change should be back-ported 14.0 15.0 16.0
=> Fix aggregation on outer joins

go/mysql/client_test.go, go/mysql/conn.go, go/mysql/constants.go, go/mysql/endtoend/main_test.go, go/mysql/server_flaky_test.go, go/mysql/sql_error.go, go/mysql/sql_error_test.go, go/test/endtoend/mysqlserver/mysql_server_test.go, go/test/endtoend/vtgate/errors_as_warnings/main_test.go, go/test/endtoend/vtgate/lookup_test.go, go/test/endtoend/vtgate/misc_test.go, go/test/endtoend/vtgate/sequence/seq_test.go, go/vt/mysqlctl/backup.go, go/vt/vtgate/endtoend/lookup_test.go, go/vt/vtgate/engine/route_test.go, go/vt/vtgate/executor_set_test.go, go/vt/vtgate/executor_test.go, go/vt/vtgate/vcursor_impl.go, go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/tabletmanager/rpc_replication.go
This ErrorCode type maps to a uint16 to match what MySQL has as the range and parses things accordingly as well. With the explicit type we know better when we use the specific error code.
Fixes some of the issues from #12216 which were identified here because of the pretty loose typing.
=> Change SQL error codes to use explicit type

go/vt/vtgate/engine/insert.go, go/vt/vtgate/engine/limit.go, go/vt/vtgate/engine/memory_sort.go
CodeQL reported a few cases in the vtgate engine where we can simplify and make the typecasting more correct.
We were double casting for the eval as well which isn't useful, so reduce this to it doing one for the hash code.
Part of #12216 
=> Fix typecasting alerts inside vtgate engine

go/flagutil/sets.go, go/sets/set.go, go/vt/topo/cell_info.go, go/vt/topo/topoproto/tablet.go, go/vt/vtadmin/api.go, go/vt/vtadmin/cluster/cluster.go, go/vt/vtadmin/cluster/cluster_internal_test.go, go/vt/vtadmin/cluster/cluster_test.go, go/vt/vtadmin/http/shards.go, go/vt/vtadmin/rbac/config.go, go/vt/vtadmin/rbac/rule.go, go/vt/vtctl/grpcvtctldserver/server.go, go/vt/vtctl/reparentutil/emergency_reparenter.go, go/vt/vtctl/reparentutil/emergency_reparenter_test.go, go/vt/vtctl/reparentutil/replication.go, go/vt/vtctl/reparentutil/replication_test.go, go/vt/vtctl/workflow/server.go, go/vt/vtctl/workflow/traffic_switcher.go, go/vt/vttablet/tabletmanager/tm_init.go, go/vt/wrangler/reparent.go, go/vt/wrangler/testlib/emergency_reparent_shard_test.go, go/vt/wrangler/vexec.go
This moves to a separate sets package inside Vitess so we don't break version pinning for k8s like in the Vitess operator.
It mostly copies the existing implementation, but simplifies and cleans it up to only copy what we actually use.
Fixes #12250 
With these changes, the only thing depending on the `k8s.io` libraries is `k8stopo`. 
=> Move to independent sets package

MAINTAINERS.md
Congratulations to @dbussink on joining the Vitess maintainers team!
I signed him up for some shit on `maintaners.md` and reworked some of the sections.
cc @deepthi 
=> maintainers: add dbussink and rework some sections

go/vt/mysqlctl/tmutils/schema.go, go/vt/mysqlctl/tmutils/schema_test.go
Per https://github.com/vitessio/vitess/issues/12317, this PR fixes the slice concatenation for `excludeTableREs`. While at it, adding more unit tests to validate expected behavior, and while at it, modernize the unit test file to use `testify` rather than "bare meta" golang tests.
Fixes https://github.com/vitessio/vitess/issues/12317
=> TableFilter: fix excluded RE listing

go/vt/vterrors/last_error.go, go/vt/vterrors/last_error_test.go, go/vt/vttablet/tabletmanager/vreplication/controller.go
`lastError` is a mechanism introduced into `VReplication` in https://github.com/vitessio/vitess/pull/10429 ; the idea is that we can have a retry-able operation that waits for some error to clean up, or times out if the error persists.
Up till now this was a local class in `vreplication` package. I have a use case outside VReplication (well, related, it's Online DDL). Anyway, the mechanism is really quite generic and useful, and so I'm externalizing the structure and moving it to `go/vt/vterrors`.
There's no real code changes here other than using the `name` field of `LastError` in place of hard coded `"Vreplication"` text.
This refactor includes the recent changes made in https://github.com/vitessio/vitess/pull/12114
- #10429
- #12114
-   [ ] "Backport to:" labels have been added if this …
=> Internal refactor: LastError as a public struct

go/vt/vtgate/evalengine/arithmetic.go, go/vt/vtgate/evalengine/integration/testdata/mysql_golden_1676045458.json, go/vt/vtgate/evalengine/internal/decimal/decimal.go, go/vt/vtgate/evalengine/internal/decimal/format.go
These bugs have been in the evalengine for a while, but we were not running the fuzzer properly, so they went undetected!
They are as follows:
- The precision after multiplying two decimals is the sum of their two precisions, not their max. This is required by standard SQL and clearly listed in the MySQL docs, so I don't know what I was thinking. Maybe it was a copy-paste mistake.
- The constant for Decimal zero should be `(0, 0)`, not `(0, 1)`. This is not specified in the SQL standard but it appears to be empirically wrong: it results in the wrong number of decimal points after multiplying any number by zero. Note that the parameters to a Decimal `(X, Y)` result in the decimal value `X * 10^Y`, so having `Y` have a 0 exponent is equivalent to having it be 0, as long as the `X` remains …
=> evalengine: fix bugs with decimal rounding

go/vt/mysqlctl/schema.go, go/vt/mysqlctl/tmutils/schema.go, go/vt/mysqlctl/tmutils/schema_test.go, go/vt/schema/name_test.go, go/vt/schema/tablegc.go, go/vt/vttablet/onlineddl/analysis.go, go/vt/vttablet/tabletmanager/vreplication/vreplicator.go, go/vt/vttablet/tabletserver/schema/engine.go
Fixes https://github.com/vitessio/vitess/issues/12319. When VReplication begins working, it first analyzes the schema. Per #12319 it may safely ignore all GC (garbage collection) tables of the form `_vt_(HOLD|PURGE|EVAC|DROP)...`. This PR does so. This in turn fixes race conditions caused while reading GC tables.
The PR extends https://github.com/vitessio/vitess/pull/12318 because the existing logic of regexp-based table exclusion has a [bug](https://github.com/vitessio/vitess/issues/12317).
Please first review #12318 before reviewing this PR.
Fixes https://github.com/vitessio/vitess/issues/12319
Depends on https://github.com/vitessio/vitess/pull/12318
-   [ ] …
=> VReplication: ignore GC tables in schema analysis

go/vt/schemadiff/table_test.go, go/vt/sqlparser/ast_format.go
Fixes https://github.com/vitessio/vitess/issues/12371
Normalizing the `CAST(...AS <type>)` in `CannonicalString()` ; previously uppercased, but that's incompatible with MySQL's behavior. Now keeping the original case.
- fixes https://github.com/vitessio/vitess/issues/12371
- similar to https://github.com/vitessio/vitess/pull/12105
=> sqlparser/schemadiff: normalize CAST type case

go/vt/tlstest/tlstest.go, go/vt/vttls/crl.go
`x509.ParseCRL` is deprecated, we should use `x509.ParseRevocationList` instead which is new in Go 1.19.
Fixes https://github.com/vitessio/vitess/issues/12314
=> Switch to using new Go 1.19 CRL parser

go/vt/sidecardb/schema/onlineddl/schema_migrations.sql, go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go
The "stowaway table" was part of the previous `vitess` cut-over mechanism, described in https://vitess.io/blog/2022-04-06-online-ddl-vitess-cut-over/
However, the logic has changed in https://github.com/vitessio/vitess/pull/11460. We no longer use a stowaway table in the cut-over mechanism. The stowaway table was the place where we would store our original table at cut-over phase. But because the cut-over was not atomic, we had to journal that changed. That was done with the `stowaway_table` column in `_vt.schema_migrations`. We would check this value to be able to rollback a halfway executed migration.
Anyway, now we use atomic cutover. We have a "sentry table" now. But this isn't merely a change of name. The sentry table is ephemeral. That is, it's a real table, but we don't care what …
=> Online DDL: remove legacy "stowaway table" logic

go/vt/vtgate/planbuilder/testdata/info_schema57_cases.json, go/vt/vtgate/planbuilder/testdata/info_schema80_cases.json, go/vt/vtgate/semantics/early_rewriter.go
When rewriting `JOIN ... USING` syntax into a `JOIN ... WHERE` form, we missed columns that in the query were not lower cased 🤦 
I'll manually create the backport to 15 and then let the bot do the backport of that to 14.
Fixes #12332
=> Fix for USING when column names not lower cased

go/vt/discovery/topology_watcher.go, go/vt/discovery/topology_watcher_test.go
=> [release-15.0] Bug fix: Cache filtered out tablets in topology watcher to avoid unnecessary GetTablet calls to topo

go/vt/discovery/topology_watcher.go, go/vt/discovery/topology_watcher_test.go
=> [release-14.0] Bug fix: Cache filtered out tablets in topology watcher to avoid unnecessary GetTablet calls to topo

go/test/endtoend/vtgate/schematracker/sharded/st_sharded_test.go, go/test/endtoend/vtgate/schematracker/unsharded/st_unsharded_test.go, go/test/endtoend/vtgate/vschema/vschema_test.go
This PR is a follow up of the work done in https://github.com/vitessio/vitess/pull/12292. We removed the `dual` table from the output of `SHOW VSCHEMA TABLES`, this PR updates the tests that are used in upgrade/downgrade accordingly.
=> Fix `SHOW VSCHEMA TABLES` tests using v17 vtgate that expected `dual`

go/cmd/vtaclcheck/vtaclcheck.go, go/cmd/vtexplain/vtexplain.go, go/vt/mysqlctl/query.go, go/vt/topo/k8stopo/directory.go, go/vt/topo/k8stopo/file.go, go/vt/topo/k8stopo/server.go, go/vt/topotools/tablet.go, go/vt/vtctl/vtctl.go, go/vt/vtexplain/vtexplain.go, go/vt/vtexplain/vtexplain_vttablet.go, go/vt/zkctl/zkctl.go
This removes a bunch of debug logging that is set for higher log levels. The problem is that many of these are logging user provided values directly which is something CodeQL also alerts on.
If someone needs this kind of additional logging level, I think it suffices to modify the code locally to test something rather than always carrying these high log level entries.
Part of #12216 where CodeQL identified a bunch of user provided log input issues. 
=> Remove a bunch of debug logging

go/vt/sidecardb/sidecardb.go, go/vt/sidecardb/sidecardb_test.go, go/vt/vtexplain/vtexplain_vttablet.go, go/vt/vttablet/tabletserver/schema/engine.go, go/vt/vttest/local_cluster.go
=> Allow zero (in) date when setting up internal _vt schema (#12262)

examples/common/lib/utils.sh, examples/common/scripts/vtadmin-up.sh
VTAdmin failing to discover the Vitess cluster in the local examples was [reported in the Vitess Slack](https://vitess.slack.com/archives/C02JQQ88Z1C/p1676993782703629).
This was caused by the relative path usage missed as part of the refactoring done in: https://github.com/vitessio/vitess/pull/12239
And this was easily missed because there was no check done to confirm proper discovery and thus the local examples CI tests did not fail.
In this PR we correct the static discovery file path AND add a check to ensure that the discovery was successful and if not, we exit with an error (which would cause the tests to fail).
>**Note** While testing/confirming this fix in the CI with manual test re-runs, I saw [another timing issue](https://github.com/vitessio/vitess/actions/runs/4237884075/jobs/7 …
=> Examples: Correct VTAdmin Discovery File Path And Add Check

go/test/endtoend/tabletmanager/replication_manager/tablet_test.go, go/test/endtoend/vreplication/helper_test.go, go/test/endtoend/vreplication/sidecardb_test.go, go/vt/sidecardb/sidecardb.go, go/vt/sidecardb/sidecardb_test.go
The initial implementation of the new mechanism for initializing the sidecar database in https://github.com/vitessio/vitess/pull/11520 causes a failure if there is an error while applying a DDL to create or alter even a single sidecardb table.  Such a failure causes the tablet initialization to fail. Hence if there is an issue with one of the queries to create or upgrade a table, say due to an incompatible MySQL version we would end up with tablets not reaching the serving state. 
Now, if this happens during a Vitess version upgrade, it would not be catastrophic because the upgrade process would be stopped when the first replica being upgraded fails to launch.
However if, for any reason, the entire cluster rolls over to a new Vitess version in the presence of these failures, we would have …
=> SidecarDB Init: don't fail on schema init errors

doc/releasenotes/17_0_0_summary.md, go/vt/vtgr/config/vtgr_config.go, go/vt/vtgr/db/tls.go, go/vt/vtgr/ssl/ssl.go, go/vt/vtgr/ssl/ssl_test.go
We were hardcoding this to TLS 1.0 which is not considered safe anymore these days and was called out by CodeQL as a security issue.
Instead we should default to TLS 1.2 which we do everywhere else, and allow for an option to change it if needed so that we're safe by default here.
I've also reviewed the documentation about `vtgr`, but we don't make any mention there for any of the SSL/TLS related configuration options, so I don't think there's a good place to add that yet? It's also marked still as experimental. 
I did add a release notes entry with the change that the default is now TLS 1.2. 
This is the last remaining issue identified in #12216 
-   [x] …
=> Add configuration option for minimum TLS version

go/mysql/schema.go, go/vt/vtgate/planbuilder/ddl.go, go/vt/vtgate/planbuilder/testdata/unsupported_cases.json, go/vt/vtgate/planbuilder/testdata/view_cases.json, go/vt/vttablet/endtoend/views_test.go, go/vt/vttablet/tabletserver/health_streamer.go, go/vt/vttablet/tabletserver/health_streamer_test.go, go/vt/vttablet/tabletserver/query_executor.go
This PR enables view support on information schema queries by restricting the create views to refer only single keyspace.
The views are now created at the MySQL level so all information schema, show query, describe, and explain query can work.
- https://github.com/vitessio/vitess/issues/11559
=> Create Views allowed for same keyspace

go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go, go/vt/schemadiff/types.go
`schemadiff` now adds an `ALGORITHM` hint. The algorithm has an operational effect on the MySQL engine, but no semantic effect on the table. It only applies for `AlterTable` diffs.
=> schemadiff: AlterTableAlgorithmStrategy

examples/operator/101_initial_cluster.yaml, examples/operator/201_customer_tablets.yaml, examples/operator/302_new_shards.yaml, examples/operator/306_down_shard_0.yaml, test/vtop_example.sh, tools/release_utils.sh
Since the default images are now MySQL 8.0, we need to update the operator example to use the right property for the image.
This PR also fixes the image we use for vtadmin deployment and fixes the release script to also change that automatically.
Further the vtop example script is fixed to use `vtctldclient` inplace of `vtctlclient`.
Fixes #12438 
=> examples: Fix Vtop example and release script

go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go, go/vt/schemadiff/types.go, go/vt/sidecardb/sidecardb.go, go/vt/sidecardb/sidecardb_test.go
Enforce use of `ALGORITHM=COPY` for all `ALTER TABLE`s used during the sidecar schema init process. By default, MYSQL8.0 uses `INSTANT` which causes `Percona XtraBackup` to fail  with the following error message, at least for `8.0.29` (which was deemed unstable and withdrawn):
```
Percona XtraBackup Error Message
If Percona XtraBackup detects that MySQL 8.0.29 server has tables with instant add/drop columns, it aborts with the following error message
2022-07-01T15:18:35.127689+05:30 0 [ERROR] [MY-011825] [Xtrabackup] Found tables with row versions due to INSTANT ADD/DROP columns
2022-07-01T15:18:35.127714+05:30 0 [ERROR] [MY-011825] [Xtrabackup] This feature is not stable and will cause backup corruption.
2022-07-01T15:18:35.127723+05:30 0 [ERROR] [MY-011825] [Xtrabackup] Tables found: …
```
=> Sidecar schema init: use COPY algorithm while altering sidecardb tables

go/vt/vtgate/evalengine/api_arithmetic_test.go, go/vt/vtgate/evalengine/api_hash.go, go/vt/vtgate/evalengine/cached_size.go, go/vt/vtgate/evalengine/eval.go, go/vt/vtgate/evalengine/eval_bytes.go, go/vt/vtgate/evalengine/eval_json.go, go/vt/vtgate/evalengine/eval_numeric.go, go/vt/vtgate/evalengine/eval_tuple.go, go/vt/vtgate/evalengine/expr_compare.go, go/vt/vtgate/evalengine/internal/json/helpers.go, go/vt/vtgate/evalengine/translate_simplify.go
Follow up on https://github.com/vitessio/vitess/pull/12428. Now that we have support for 128-bit hashing, we should also use it internally for all hashing operations.
cc @dbussink 
=> evalengine: use 128 bit hashing internally

examples/operator/101_initial_cluster.yaml, examples/operator/201_customer_tablets.yaml, examples/operator/302_new_shards.yaml, examples/operator/306_down_shard_0.yaml, examples/operator/operator.yaml, examples/operator/pf.sh, test/vtop_example.sh, tools/release_utils.sh
Since the default images are now MySQL 8.0, we need to update the operator example to use the right property for the image.
This PR also fixes the yaml files to not use `enforceSemiSync` anymore and updates the operator.yaml to the latest version, and fixes the release script to also change the vtadmin image version automatically.
Further the vtop example script is fixed to use `vtctldclient` inplace of `vtctlclient`.
Fixes #12456
=> Fix Vtop example and release script

.github/workflows/upgrade_downgrade_test_query_serving_queries.yml, .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml, .github/workflows/upgrade_downgrade_test_query_serving_schema.yml, .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml
Upgrade downgrade tests have been failing with the error `no space left on device`. In order to fix them, it was decided to turn off the `keep-data` flag when running these tests. Since the tests are independent of each other, we don't need to keep the data around for each test run. This fixes the issue on the CI.
=> Don't keep data in upgrade-downgrade tests

doc/releasenotes/16_0_0_summary.md
This PR reorders the summary file of release-16.0 to move some items which are important to the top of the list.
- https://github.com/vitessio/vitess/issues/12293
=> Reorder summary in order of importance

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/vt/vtgate/engine/scalar_aggregation.go, go/vt/vtgate/engine/scalar_aggregation_test.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/planbuilder/testdata/onecase.json
This PR fixes the issue on scalar aggregation primitive where the additional column added by the planner was not removed from the final result sent back to the client.
```
user query: select count(distinct col) from user
planned query: select col, weight_string(col) from user group by col, weight_string(col) order by col asc
```
Scaler Aggregation after aggregating the column count missed truncating the `weight_string(col)` column.
This was only missed for OLTP workload, for OLAP the logic was present.
=> Fix scalar aggregation engine primitive for column truncation

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/vt/vtgate/engine/scalar_aggregation.go, go/vt/vtgate/engine/scalar_aggregation_test.go, go/vt/vtgate/executor_select_test.go
=> [release-14.0] Fix scalar aggregation engine primitive for column truncation (#12468)

examples/backups/create_commerce_schema.sql, examples/backups/create_customer_schema.sql, examples/compose/external_db/mysql/commerce.sql, examples/compose/tables/create_dinosaurs.sql, examples/compose/tables/create_eggs.sql, examples/compose/tables/create_messages.sql, examples/compose/tables/create_messages_message_lookup.sql, examples/compose/tables/create_tokens.sql, examples/compose/tables/create_tokens_token_lookup.sql, examples/compose/tables/lookup_keyspace_schema_file.sql, examples/compose/tables/test_keyspace_schema_file.sql, examples/demo/schema/customer/customer_schema.sql, examples/demo/schema/product/product_schema.sql, examples/local/create_commerce_schema.sql, examples/local/create_commerce_seq.sql, examples/local/create_test_table.sql, examples/operator/create_commerce_schema.sql, examples/operator/create_commerce_seq.sql, examples/region_sharding/create_lookup_schema.sql, examples/region_sharding/create_main_schema.sql, examples/vtexplain/atomicity_schema.sql
This PR changes all `CREATE TABLE` into `CREATE TABLE IF NOT EXISTS` in the various `examples` schemas.
This allows the user to take down a cluster and bring it up again with no error (currently the `create table` statements fail the bootstrap script).
=> examples schema: demi-idempotency via CREATE TABLE IF NOT EXISTS

go/test/endtoend/reparent/plannedreparent/reparent_test.go, go/test/endtoend/utils/utils.go
This PR is a follow up of the recent work done by @rohit-nayak-ps around vttablet sidecar (https://github.com/vitessio/vitess/pull/11520). In the latter work, we removed `Create`/`Alter` `ReparentJournal`, this PR fixes a test that uses this SQL query. The test will not be ran during upgrade tests when vttablet is on version 16.
- Follow up of #11520
=> Skip `TestReparentDoesntHangIfPrimaryFails` in vttablet v16 and above

go/vt/vtgate/evalengine/api_hash.go, go/vt/vtgate/evalengine/api_hash_test.go
We missed this functionality while backporting the new 128 bit hashes from PlanetScale's internal fork. This is the idea:
There are a few directions in which SQL values can be coerced which are not loseless, but could be (e.g. converting from FLOAT to INT64 works, but only if the float has no fractional part). Usually, the coercion rules for MySQL will never perform such coercion, but supporting them is gives us a lot more versatility when dealing with external user queries, whose types can be _weird_ (think: MySQL drivers emitting numbers in the wrong format).
This PR implements this functionality.
cc @dbussink 
-   [ ] Did the new or modified tests pass …
=> evalengine: add more coercion paths to Hash128

go/vt/vtgate/executor_select_test.go, go/vt/vtgate/planbuilder/testdata/select_cases.json, go/vt/vtgate/semantics/semantic_state.go
This PR fixes the query support for the query described in the bug https://github.com/vitessio/vitess/issues/12483
- Fixes https://github.com/vitessio/vitess/issues/12483
=> BugFix: Unsharded query using a derived table and a dual table

go/vt/vtgate/executor_select_test.go, go/vt/vtgate/planbuilder/testdata/select_cases.json, go/vt/vtgate/semantics/semantic_state.go
---------
This PR is a forward port of #12484 
- Fixes https://github.com/vitessio/vitess/issues/12483
=> [main] BugFix: Unsharded query using a derived table and a dual table (#12484)

go/cmd/vtctldclient/command/keyspaces.go
The [`GetKeyspace` vtctldclient command](https://vitess.io/docs/17.0/reference/programs/vtctldclient/vtctldclient_getkeyspace/) returned invalid JSON (using the [vitess local example](https://vitess.io/docs/17.0/get-started/local/)):
```
$ vtctlclient GetKeyspace commerce
{
"served_froms": [],
"keyspace_type": 0,
"base_keyspace": "",
"snapshot_time": null,
"durability_policy": "semi_sync"
}
$ vtctldclient GetKeyspace commerce
name:"commerce" keyspace:{durability_policy:"semi_sync"}
```
With this PR:
```
$ vtctlclient GetKeyspace commerce
{
"served_froms": [],
"keyspace_type": 0,
"base_keyspace": "",
"snapshot_time": null,
"durability_policy": "semi_sync"
}
$ vtctldclient GetKeyspace commerce
{
"name": "commerce",
"keyspace": {
"served_froms": [],
"keyspace_type": 0,
"base_keyspace": "", …
```
=> vtctldclient: Format GetKeyspace output using cli.MarshalJSON

go/streamlog/streamlog.go, go/streamlog/streamlog_flaky_test.go, go/vt/vtexplain/vtexplain_vtgate.go, go/vt/vtgate/executor_framework_test.go, go/vt/vtgate/querylog.go, go/vt/vtgate/querylogz.go, go/vt/vtgate/querylogz_test.go, go/vt/vttablet/endtoend/framework/eventcatcher.go, go/vt/vttablet/filelogger/filelogger.go, go/vt/vttablet/sysloglogger/sysloglogger.go, go/vt/vttablet/sysloglogger/sysloglogger_test.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletmanager/vreplication/vrlog.go, go/vt/vttablet/tabletserver/querylogz.go, go/vt/vttablet/tabletserver/querylogz_test.go, go/vt/vttablet/tabletserver/tabletenv/config.go, go/vt/vttablet/tabletserver/tabletserver_test.go, go/vt/vttablet/tabletserver/txlogz.go, go/vt/vttablet/tabletserver/txlogz_test.go
The `logstats` package is a good example of a primitive that is used throughout the Vitess codebase and that still uses `any` for polymorphism. It's un-ergonomic and it has a lot of type checks that won't be needed if we switch to use Generics.
=> streamlog: make generic

.github/workflows/code_freeze.yml, doc/releasenotes/16_0_0_changelog.md, doc/releasenotes/16_0_0_release_notes.md, doc/releasenotes/16_0_0_summary.md, docker/release.sh, examples/compose/docker-compose.beginners.yml, examples/compose/docker-compose.yml, examples/compose/vtcompose/docker-compose.test.yml, examples/compose/vtcompose/vtcompose.go, examples/operator/101_initial_cluster.yaml, examples/operator/201_customer_tablets.yaml, examples/operator/302_new_shards.yaml, examples/operator/306_down_shard_0.yaml, examples/operator/operator.yaml, go/vt/servenv/version.go, java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/jdbc/pom.xml, java/pom.xml
Includes the release notes and release commit for the v16.0.0 release. Once this PR is merged, we will be able to tag v16.0.0 on the merge commit.
- #12293
=> Release of v16.0.0

.github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml, .github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml, .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml, .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml
This PR is a follow up of the recent PR made against `release-16.0` that bumps the Golang version to `go1.20.1`. The `next release` upgrade downgrade tests will now use `go1.20.1`.
=> [release-15.0] Use `go1.20.1` in upgrade/downgrade tests

go/cmd/vtctldclient/command/root.go, go/cmd/vtctldclient/command/root_test.go, go/flags/endtoend/vtctldclient.txt
Add a Run func to `vtctldclient`'s Root command to return an error on unknown command.
Cobra can't (and shouldn't!) be distinguish between "we didn't find a subcommand because the user made an error" and "we didn't find a subcommand because the user is trying to invoke a parent command with positional arguments", so we specify a run function (what cobra invokes when executing the command) on the root (top-level parent) and check if there are any positional arguments, which in our case we assume means the user was trying to run a subcommand that doesn't exist.
Closes #12480.
-   [x] …
=> Fix `vtctldclient`'s Root command to return an error on unknown command

go/bucketpool/bucketpool_test.go
Fixes https://github.com/vitessio/vitess/issues/12513 on `release-16.0`.
=> Fix `TestFuzz` that hangs on `go1.20.1`

.github/workflows/check_label.yml
This PR will block merges if the `Do Not Merge` label is set.
- Fixes https://github.com/vitessio/vitess/issues/12488
=> Block merge if the `Do Not Merge` label is set

go/vt/sidecardb/sidecardb.go, go/vt/sidecardb/sidecardb_test.go
Enforce use of `ALGORITHM=COPY` for all `ALTER TABLE`s used during the sidecar schema init process. By default, MYSQL8.0 uses `INSTANT` which causes `Percona XtraBackup` to fail  with the following error message, at least for `8.0.29` (which was deemed unstable and withdrawn):
```
Percona XtraBackup Error Message
If Percona XtraBackup detects that MySQL 8.0.29 server has tables with instant add/drop columns, it aborts with the following error message
2022-07-01T15:18:35.127689+05:30 0 [ERROR] [MY-011825] [Xtrabackup] Found tables with row versions due to INSTANT ADD/DROP columns
2022-07-01T15:18:35.127714+05:30 0 [ERROR] [MY-011825] [Xtrabackup] This feature is not stable and will cause backup corruption.
2022-07-01T15:18:35.127723+05:30 0 [ERROR] [MY-011825] [Xtrabackup] Tables found: …
```
=> Forward port of #12436: Sidecar schema init: use COPY algorithm while altering sidecardb tables

doc/releasenotes/17_0_0_summary.md, go/vt/schema/online_ddl_test.go, go/vt/vttablet/onlineddl/executor.go
These checks were done to maintain backwards compatibility with versions 10, 12, and 13, respectively, so I'm removing them now for version 17.
#8499
-   [x] "Backport to:" labels have been added if this change should be back-ported (N/A)
=> [onlineddl] Remove some old backwards-compatibilities in online ddl code

go/cmd/vtctldclient/command/root.go, go/cmd/vtctldclient/command/root_test.go, go/flags/endtoend/vtctldclient.txt
* Add a Run func to `vtctldclient`'s Root command to return an error on unknown command
Closes #12480.
* Add test
* flags test data
#12480 
#12481 
=> [Backport] Fix `vtctldclient`'s Root command to return an error on unknown command (#12481)

ADOPTERS.md
- Added [Twitter] to ADOPTERS. see: https://blog.twitter.com/engineering/en_us/topics/infrastructure/2023/how-we-scaled-reads-on-the-twitter-users-database
- Added [Etsy] to ADOPTERS. see: https://www.etsy.com/codeascraft/scaling-etsy-payments-with-vitess-part-1--the-data-model
Hi, I saw today from the article that Twitter uses vitess, this is a simple PR that add Twitter to the ADOPTERS list.
Cheers!
=> Added [Twitter] & [Etsy] to ADOPTERS.md

doc/releasenotes/16_0_0_release_notes.md, doc/releasenotes/16_0_0_summary.md
This PR adds the known issue of xtrabackup with DDLS.
- #12517 
=> Add a known issue into the release notes for xtrabackup and DDLs

go/vt/discovery/topology_watcher.go, go/vt/discovery/topology_watcher_test.go
=> [release-13.0] Bug fix: Cache filtered out tablets in topology watcher to avoid unnecessary GetTablet calls to topo

go/test/endtoend/reparent/newfeaturetest/reparent_test.go, go/vt/vtctl/grpcvtctldserver/endtoend/init_shard_primary_test.go, go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_init_test.go, go/vt/wrangler/testlib/backup_test.go, go/vt/wrangler/testlib/copy_schema_shard_test.go, go/vt/wrangler/testlib/emergency_reparent_shard_test.go, go/vt/wrangler/testlib/external_reparent_test.go, go/vt/wrangler/testlib/permissions_test.go, go/vt/wrangler/testlib/planned_reparent_shard_test.go, go/vt/wrangler/testlib/reparent_utils_test.go, go/vt/wrangler/testlib/version_test.go
This PR fixes the bug described in #12533 by fixing the initialization code to also stop replication before it tries to `reset slave  all`. The old code assumed that replication is already stopped when a new vttablet was coming up, but that assumption is incorrect. We should stop replication irrespective before we try to change the primary hostname, and port.
This PR is a follow-up to: https://github.com/vitessio/vitess/pull/10881 which was originally created to resolve #10880.
- Fixes #12533 
=> Fix initialization code to also stop replication to prevent crash

examples/local/101_initial_cluster.sh
This is particularly useful when using the local examples for testing and debugging (as I do on a daily basis) — where you are continually creating and destroying clusters — because building and installing VTAdmin takes a significant amount of time and in these scenarios is unused.
=> Examples: Add ENV Var to Local Examples to Skip VTAdmin

go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go
An optimization PR.
Intro: When we submit an Online DDL migration, and with `--singleton-context`, the submission is only accepted if there's no pending migration with a different migration context than the submitted migration. i.e., the migration is only ever accepted if all other pending migrations (queued, ready, running) have the exact same migration-context as the submitted migration.
Sometimes we will submit a large number of migrations, e.g. when importing a schema. Say we have `200` `CREATE TABLE` statements. Whether one by one, or whether by `ApplySchema --sql="many; migrations; here;"`, the Online DDL executor is asked to `SubmitMigration()` for each and every DDL,, one at a time.
For each such migration, the executor scans the existing list of pending migrations to see if …
=> OnlineDDL: optimizing --singleton-context conflict check

go/mysql/collations/internal/uca/iter_fast_900.go, go/mysql/collations/uca_test.go
When using the fast iterator to _compare_ two strings with an UCA collation, we need to keep in mind that the weights in the collation are in BIG ENDIAN (this is the output format for the weight strings, so we store the weights this way), so comparing them directly will not result in the proper collation order. They need to be byte-swapped before they can be compared with an arithmetic operation!
- Fixes https://github.com/vitessio/vitess/issues/12541
=> collations: fix sorting in UCA900 collations

go/vt/log/log.go, go/vt/vtctl/vdiff2_test.go, go/vt/vtctl/vdiff_env_test.go, go/vt/wrangler/vdiff_env_test.go, go/vt/wrangler/vdiff_test.go, go/vt/wrangler/vexec_test.go, go/vt/wrangler/wrangler_env_test.go
The [unit race workflow](https://github.com/vitessio/vitess/blob/main/.github/workflows/unit_race.yml) was [failing pretty regularly in the CI](https://github.com/vitessio/vitess/actions/workflows/unit_race.yml) (~20% of the time), and the two failures that I would regularly see were:
1. `testVDiffEnv` related races — most often in the wrangler unit tests, as they  have the widest use
- These were simply NOT concurrency-safe
2. `glog.MaxSize` related races — most often in the wrangler unit tests as they create a LOT of loggers, primarily ConsoleLoggers and MemoryLoggers
- The way we modified the `glog.MaxSize` global exported variable in our `--log_rotate_max_size` flag handling was not concurrency-safe
I was able to quickly repeat these failures locally as well using the method below. …
=> Flakes: Address Common Unit Test Races

.github/workflows/release_notes_label.yml, doc/internal/ReleaseInstructions.md
This is a backport of https://github.com/vitessio/vitess/pull/12489 and https://github.com/vitessio/vitess/pull/12487
=> [release-14.0] Tooling improvements backports

go/vt/tableacl/tableacl.go, go/vt/topo/cell_info.go, go/vt/topo/cells_aliases.go, go/vt/topo/external_vitess_cluster.go, go/vt/topo/keyspace.go, go/vt/topo/replication.go, go/vt/topo/shard.go, go/vt/topo/srv_keyspace.go, go/vt/topo/srv_vschema.go, go/vt/topo/tablet.go, go/vt/topo/test/watch.go, go/vt/topo/topotests/shard_watch_test.go, go/vt/topo/vschema.go, go/vt/topo/workflow.go, go/vt/vitessdriver/driver.go, go/vt/vtgate/engine/ordered_aggregate.go, go/vt/vttablet/tabletserver/schema/historian.go, go/vt/vttablet/tabletserver/schema/historian_test.go, go/vt/vttablet/tabletserver/schema/tracker.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer_flaky_test.go, go/vt/wrangler/testlib/vtctl_topo_test.go
Use the more efficient `MarshalVT`/`UnmarshalVT` functions instead of `proto.Marshal`/`proto.Unmarshal`.
The only places I didn't switch over are `go/vt/servenv/grpc_codec.go` (because that is used by the grpc communication for `etcd-client`) and `go/vt/topo/decode.go` (which I can switch over if anyone cares about that).
N/A
=> Use `MarshalVT`/`UnmarshalVT` instead of `proto.Marshal`/`proto.Unmarshal`.

bootstrap.sh
Presently [protoc bootstrap](https://github.com/vitessio/vitess/blob/b09ce8baee19144ec28e6753714a6dae74907d1d/bootstrap.sh#L268) gets wiped out by [ZK bootstrap](https://github.com/vitessio/vitess/blob/b09ce8baee19144ec28e6753714a6dae74907d1d/bootstrap.sh#L273) via [this rm](https://github.com/vitessio/vitess/blob/b09ce8baee19144ec28e6753714a6dae74907d1d/bootstrap.sh#L65) in `install_dep`. The fix in this patch is to invoke `install_dep` for ZK with subdir of `dist/` instead of the top-level `dist/`, similar to the other deps.
N/A
N/A
=> Prevent bootstrap of ZK from clearing previous dist binaries

examples/common/lib/utils.sh
The [local examples CI workflow](https://github.com/vitessio/vitess/blob/main/.github/workflows/local_example.yml) is still flaky — [failing ~ 35% of the time](https://github.com/vitessio/vitess/actions/workflows/local_example.yml) — and it always fails here (or in the same way in later VReplication steps):
```
+ for shard in "customer/0"
+ true
+ command mysql --no-defaults -h 127.0.0.1 -P 15306 customer/0 -e 'show tables'
+ break
+ ./202_move_tables.sh
E0306 18:54:21.968491   13432 main.go:96] E0306 18:54:21.967743 traffic_switcher.go:208] buildTrafficSwitcher failed: rpc error: code = Unknown desc = TabletManager.VReplicationExec on zone1-0000000200 error: vreplication engine is closed: vreplication engine is closed
E0306 18:54:21.969504   13432 main.go:105] remote error: rpc error: …
```
=> Examples, Flakes: Wait for Shard's VReplication Engine to Open

go/cmd/vtbackup/vtbackup.go
While auditing the logs I saw the need to add some logging and also corrected a place where we were printing `nil` GTID. 
=> adding log statment to vtbackup

go/vt/vtgate/planbuilder/abstract/concatenate.go, go/vt/vtgate/planbuilder/testdata/systemtables_cases80.json, go/vt/vtgate/planbuilder/testdata/unsupported_cases.json
When planning for filtering on top of a derived table that contains an UNION, the planner was just giving up. This change is not the most optimal fix, since we should be able to push the filtering into the route, but at least this plan works.
We need to forward port this fix to `release-16.0` and `main`.
-  https://github.com/vitessio/vitess/issues/9214
=> handle filter on top of UNION

examples/common/lib/utils.sh
This is a manual backport of https://github.com/vitessio/vitess/pull/12560.
I should have added the `Backport to: release-16.0` label to the PR because it improves the reliability of the tests when run locally by users as well — but I did not do so _before it was merged_. Thus I'm doing the Bot's job here. 🙂
=> [release-16.0] Examples, Flakes: Wait for Shard's VReplication Engine to Open (#12560)

test/config.json
Due to recent GitHub CI runners slowness, we're seeing some tests time out after `20min` of running. These tests normally run for `5-6 min` on a local dev env, and `20min` used to give good margins. Not anymore.
This PR increases all Online DDL related tests timeouts to `30min`.
=> CI: increase overall test timeouts for all OnlineDDL tests

go/vt/topotools/vschema_ddl.go, go/vt/vtgate/executor_vschema_ddl_test.go
We use `ALTER VSCHEMA ... ADD AUTO_INCREMENT ...` statements to provision new sharded tables with their Sequence table references, however we ran into a bug because our sequence tables are stored in keyspaces that contain dashes (e.g. <code>\`app-name-global\`.sequence_table</code>).
The issue is that the `ApplyVSchemaDDL` function does not escape the value of the  `Sequence` field below even though it's capable of parsing user input correctly:
```go
table.AutoIncrement = &vschemapb.AutoIncrement{
Column:   alterVschema.AutoIncSpec.Column.String(),
Sequence: sequenceFqn,
}
```
Not surprising, since we're going through a cycle of parsing user input (from a SQL statment) and then trying to write something out to the VSchema's `Table.AutoIncrement.Sequence` field with the (new-ish?) …
=> `ApplyVSchemaDDL`: escape Sequence names when writing the VSchema

test/config.json
Manual backport of https://github.com/vitessio/vitess/pull/12584
---
Due to recent GitHub CI runners slowness, we're seeing some tests time out after `20min` of running. These tests normally run for `5-6 min` on a local dev env, and `20min` used to give good margins. Not anymore.
This PR increases all Online DDL related tests timeouts to `30min`.
=> v15 backport: CI: increase overall test timeouts for all OnlineDDL tests

test/config.json
Manual backport of https://github.com/vitessio/vitess/pull/12584
---
Due to recent GitHub CI runners slowness, we're seeing some tests time out after `20min` of running. These tests normally run for `5-6 min` on a local dev env, and `20min` used to give good margins. Not anymore.
This PR increases all Online DDL related tests timeouts to `30min`.
=> v14 backport: CI: increase overall test timeouts for all OnlineDDL tests

go/vt/vttablet/tabletserver/query_executor_test.go
Temporarily disable this flaky test until it can be re-worked.
#12602 
=> go/vt/vttablet/tabletserver: temporarily skip flaky consolidation test

go/mysql/sql_error.go
This PR merely adds some code comments for future generations (or future us) about the way `NewSQLErrorFromError()` is implemented.
Related: https://github.com/vitessio/vitess/pull/12574#issuecomment-1465579958
=> SQLError: adding some code comments

go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/txthrottler/tx_throttler.go, go/vt/vttablet/tabletserver/txthrottler/tx_throttler_test.go
This PR adds the metrics below to `vttablet` to make it easier to observe the transaction throttler
1. Gauge: `TxThrottlerRunning`
- `0` (disabled)
- `1` (enabled)
2. Counter: `TxThrottlerRequests` - total # of calls to `.Throttle()`
3. Counter: `TxThrottlerThrottled` - total # of throttled calls to `.Throttle()`
4. ~~Gauge: `TxThrottlerMaxRate` - the max rate reported from the underlying throttler `.MaxRate()`~~
While updating unit tests for the transaction throttler, I moved the testing to use `github.com/stretchr/testify/assert`
Resolves: https://github.com/vitessio/vitess/issues/12417
=> Add basic metrics to `vttablet` transaction throttler

go/flags/endtoend/vtbackup.txt, go/vt/mysqlctl/builtinbackupengine.go
https://github.com/vitessio/vitess/pull/12073 added support for backup read IO buffering but did not make the new flags available to the `vtbackup` binary. This PR enables that part.
https://github.com/vitessio/vitess/issues/12069
-   [x] Documentation: https://github.com/vitessio/website/pull/1403
=> go/{vt,flags}: register builtin backup flags with vtbackup

go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go, go/vt/schema/online_ddl.go, go/vt/sidecardb/schema/onlineddl/schema_migrations.sql, go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go
Fixes https://github.com/vitessio/vitess/issues/12610
Two main change in this PR:
1. `executeAlterDDLActionMigration()` does not create goroutines in order to execute `vitess`, `gh-ost`, and `pt-osc` migrations. The calls to `ExecuteWithVReplication`, `ExecuteWithGhost`, and `ExecuteWithPTOSC` are now inlined, synchronousely.
- This means these functions operate under `migrationMutex` acquired by `runNextMigration()`, which calls `isAnyConflictingMigrationRunning()` to determine which migration can be executed that does not conflict with running migrations.
- As such, the three functions do not need to execute `isAnyConflictingMigrationRunning()` themselves, and that 2nd chcek is removed, trivially solving the race condition reported in #12610.
The reason these migrations were called in a …
=> Online DDL: `ready_to_complete` race fix

go/vt/vttablet/tabletserver/gc/tablegc.go
This PR removes a log entry that logs every `1min` on an interval, with some outliers. It is otherwise not very informative and not needed. It was added in https://github.com/vitessio/vitess/commit/d8f17888aa8561acc0c8b8d88f08b02be5b15446 for better visibility but ended up spamming the logs.
https://github.com/vitessio/vitess/pull/11972
=> Table GC: remove spammy log entry

go/mysql/query.go, go/test/endtoend/vtgate/queries/misc/misc_test.go
There was a panic due to the way we typecasted the size variable used to create our `bitMap` causing https://github.com/vitessio/vitess/issues/12333 to happen.
This PR fixes the issue https://github.com/vitessio/vitess/issues/12333.
- https://github.com/vitessio/vitess/issues/12333
=> Fix `panic` when executing a prepare statement with over `65,528` parameters

go/test/endtoend/backup/vtctlbackup/backup_utils.go, go/vt/mysqlctl/backupengine.go, go/vt/mysqlctl/backupstats/stats.go, go/vt/mysqlctl/backupstats/stats_test.go
Recently merged detailed backup stats has a minor bug in that it is not actually counting # of bytes. I know I had this correct at least locally at some point, but looking through commits in #11979 it seems like it was always wrong 😵‍💫 
#11979 
=> go/vt/mysqlctl/backupstats: increment *_bytes metric by actual number of bytes

go/mysql/query.go, go/test/endtoend/vtgate/queries/misc/misc_test.go
=> [release-15.0] Fix `panic` when executing a prepare statement with over `65,528` parameters

go/vt/vtgate/endtoend/vstream_test.go
I've noticed that the `TestVStreamCopyResume` test has been flaky lately in the endtoend workflow since we merged https://github.com/vitessio/vitess/pull/12623. You can see an example of it failing 4 times in a row here: https://github.com/vitessio/vitess/actions/runs/4432838267
After investigating the failures, the reason for them is that the order of the shards in the VGTID event is non-deterministic and thus so is which one has the `table_p_ks` field: https://github.com/vitessio/vitess/blob/7afc6e1e1816a820baba841fd4dc38901d40e5a3/go/vt/vtgate/endtoend/vstream_test.go#L483-L488
The regexp would fail if the 80- shard was first in the output. This PR alters the regexp so that it matches regardless of the shard order in the output. 
The test was failing in the CI ~ 50% of the time. With …
=> Flakes: Handle Non-Determinstic Shard Ordering in VGTID

go/mysql/fakesqldb/server.go, go/vt/vttablet/tabletserver/bench_test.go
Recent improvements to character collation logic have surfaced some latent data race issues in tests that use fakedb. S/o @mattlord for finding and debugging some of these races. Matt shared this code w/ me.
- Fixes: #12602 
=> Use atomic.Bool for fakesqldb behavior flags

go.mod, go.sum, go/mysql/binlog_event_json.go, go/mysql/binlog_event_json_test.go, go/test/endtoend/vreplication/unsharded_init_data.sql, go/test/endtoend/vreplication/vreplication_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go
The binlog parser in vstreamer currently uses the `github.com/spyzhov/ajson` module to decode the value from the binlog image to its json value. However the library only supports a single type Numeric (float64) as a catchall for all numeric types including signed and unsigned integers. As a consequence, the generated JSON represents integers as floats and the string representation in a VEvent can contain decimals or values in scientific notation. So integers can be stored as floats on the target and larger ints sent with scientific notation in VStream events. 
This results in VDiff failures since the json strings stored are different. Also parsing the VEvents sent using the VStream API can result in errors if, for example, the JSON is being parsed by golang. See …
=> VStreamer: improve representation of integers in json data types

go/vt/vtgate/endtoend/vstream_test.go
Part duex (the [first one](https://github.com/vitessio/vitess/pull/12637) was prematurely merged).
I've noticed that the [`TestVStreamCopyResume` test](https://github.com/vitessio/vitess/blob/7afc6e1e1816a820baba841fd4dc38901d40e5a3/go/vt/vtgate/endtoend/vstream_test.go#L389) has been flaky lately in the [`End-To-End` workflow](https://github.com/vitessio/vitess/blob/7afc6e1e1816a820baba841fd4dc38901d40e5a3/.github/workflows/endtoend.yml) since we merged https://github.com/vitessio/vitess/pull/12623. You can see an example of it failing 4 times in a row here: https://github.com/vitessio/vitess/actions/runs/4432838267
After investigating the failures, the reason for them is that the order of events in the stream are non-deterministic and thus the …
=> Flakes: Handle Non-Deterministic VStream Event Ordering

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/test/endtoend/vtgate/queries/aggregation/schema.sql, go/test/endtoend/vtgate/queries/aggregation/vschema.json, go/vt/vtgate/engine/ordered_aggregate.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/planbuilder/gen4_planner.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/operators/queryprojection.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.json
This PR fixes https://github.com/vitessio/vitess/issues/12540 by making sure to not push down to MySQL complex expressions that involved aggregations.
If we have a derived table and it's aggregating results for us, we can't use these results until the are fully aggregated, which happens on the vtgate level.
```sql
select dt.a,
dt.b,
(dt.a / dt.b)
from (select sum(a) as a,
sum(b) as b
from user) dt
```
In the query above, since we have to spread out the aggregation across all `user` shards, we can't push down the division between the two sums until after summing up the individual shard results.
Fixes https://github.com/vitessio/vitess/issues/12540
-   [x] Did the …
=> [gen4 planner] Make sure to not push down expressions when not possible

go/vt/sidecardb/identifier_cache.go, go/vt/sidecardb/sidecardb.go, go/vt/sidecardb/sidecardb_test.go
This addresses some minor things noticed when doing other work. These things were not caught by the [`golangci-lint` pre-commit hook](https://github.com/vitessio/vitess/blob/main/misc/git/hooks/golangci-lint) as they were caught by `revive` which we disabled in this PR: https://github.com/vitessio/vitess/pull/12286#issuecomment-1423957152
- Follow-up to: https://github.com/vitessio/vitess/pull/12240
=> Minor Cleanup of SidecarDB Package

go/vt/vtadmin/api.go, go/vt/vtadmin/api_authz_test.go, go/vt/vtadmin/api_test.go, go/vt/vtadmin/testutil/authztestgen/config.json
Two problems here, one cause.
Cause: the old vtexplain code (which we have deprecated and are moving away from) spins up tablets, which do a bunch of things to global state (because you would normally only have one `vttablet` per process), and is therefore not thread safe.
Problem(s):
1. the /vtexplain endpoint is not thread safe => add a lock to the api instance
2. some tests spin up their own api, which makes the above fix insufficient. => we _could_ move the lock off the api instance to its own global, but i don't like that, so i serialized the tests
Fixes https://github.com/vitessio/vitess/issues/12636
-   [x] Did the new or modified tests pass consistently …
=> [vtadmin] racy vtexplain

go/vt/mysqlctl/schema.go
Cherry pick of https://github.com/vitessio/vitess/pull/12641 for `release-14.0`
--
Identify the two scenarios where a table may be dropped while we're inspecting the schema. Either we get a `(errno 1146)` error code, or the table does not appear in `information_schema` even after it did, before. 
The fix is to silently ignore tables hitting this scenario.
- Fixes: https://github.com/vitessio/vitess/issues/12640
=> Cherry pick v14: Mysqld.GetSchema: tolerate tables being dropped while inspecting schema

go/vt/vtgate/engine/concatenate.go, go/vt/vtgate/engine/opcode/constants.go, go/vt/vtgate/engine/ordered_aggregate.go, go/vt/vtgate/engine/ordered_aggregate_test.go, go/vt/vtgate/engine/pullout_subquery.go, go/vt/vtgate/engine/pullout_subquery_test.go, go/vt/vtgate/engine/scalar_aggregation.go, go/vt/vtgate/engine/scalar_aggregation_test.go, go/vt/vtgate/planbuilder/aggregation_pushing.go, go/vt/vtgate/planbuilder/expr.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/operators/operator_test.go, go/vt/vtgate/planbuilder/operators/queryprojection.go, go/vt/vtgate/planbuilder/operators/sharded_routing.go, go/vt/vtgate/planbuilder/operators/subquery_planning.go, go/vt/vtgate/planbuilder/ordered_aggregate.go, go/vt/vtgate/planbuilder/project.go, go/vt/vtgate/planbuilder/projection_pushing.go, go/vt/vtgate/planbuilder/pullout_subquery.go, go/vt/vtgate/planbuilder/rewrite.go, go/vt/vtgate/planbuilder/show.go, go/vt/vtgate/planbuilder/subquery_op.go, go/vt/vtgate/semantics/analyzer_test.go, go/vt/vtgate/semantics/binder.go, go/vt/vtgate/semantics/scoper.go, go/vt/vtgate/semantics/typer.go, go/vt/vttablet/tabletmanager/vdiff/table_plan.go, go/vt/vttablet/tabletmanager/vdiff/workflow_differ_test.go, go/vt/wrangler/vdiff.go, go/vt/wrangler/vdiff_test.go
This is an internal refactor PR, that creates a new package: `go/vt/vtgate/engine/opcode`. With this new package, we can remove `go/vt/vtgate/semantics`'s dependency on `go/vt/vtgate/engine`. Now both `semantics` and `engine` use the new `opcode` package.
This decoupling was found necessary in https://github.com/vitessio/vitess/pull/12565#issuecomment-1475805681, and helps to untangle https://github.com/vitessio/vitess/pull/12565
https://github.com/vitessio/vitess/pull/12565
=> Refactor: go/vt/vtgate/engine/opcode to reduce `semantics` package dependencies

go/vt/vtgate/evalengine/arena.go, go/vt/vtgate/evalengine/arithmetic.go, go/vt/vtgate/evalengine/compiler.go, go/vt/vtgate/evalengine/compiler_arithmetic.go, go/vt/vtgate/evalengine/compiler_asm.go, go/vt/vtgate/evalengine/compiler_bit.go, go/vt/vtgate/evalengine/compiler_compare.go, go/vt/vtgate/evalengine/compiler_fn.go, go/vt/vtgate/evalengine/compiler_json.go, go/vt/vtgate/evalengine/compiler_test.go, go/vt/vtgate/evalengine/eval.go, go/vt/vtgate/evalengine/eval_json.go, go/vt/vtgate/evalengine/eval_numeric.go, go/vt/vtgate/evalengine/expr_arithmetic.go, go/vt/vtgate/evalengine/expr_bit.go, go/vt/vtgate/evalengine/expr_logical.go, go/vt/vtgate/evalengine/fn_base64.go, go/vt/vtgate/evalengine/fn_json.go, go/vt/vtgate/evalengine/internal/decimal/decimal.go, go/vt/vtgate/evalengine/internal/decimal/decimal_test.go, go/vt/vtgate/evalengine/testcases/cases.go, go/vt/vtgate/evalengine/testcases/inputs.go, go/vt/vtgate/evalengine/translate.go, go/vt/vtgate/evalengine/translate_card.go
As follow up on #12369, this implements additional missing arithmetic support for `DIV`, `%` (and the `MOD` alias). 
It also adds support to the compiler for `NOT`, `AND`, `OR` and `XOR` which was missing as well. 
Implements part of the items listed in #9647 as well.
=> evalengine: Implement integer division and modulo

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/test/endtoend/vtgate/queries/aggregation/schema.sql, go/test/endtoend/vtgate/queries/aggregation/vschema.json, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/planbuilder/gen4_planner.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/operators/queryprojection.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.json
=> [release-16.0] Make sure to not push down expressions when not possible (#12607)

go/vt/sqlparser/ast_funcs.go, go/vt/sqlparser/ast_test.go, go/vt/vtgate/planbuilder/operators/SQL_builder.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.json
When planning derived tables, we were pushing down predicates into the WHERE clause instead of the HAVING clause, even when the predicate contains aggregation.
Fixes #12550
=> [planner bugfix] add expressions to HAVING

go/vt/vtgate/planbuilder/gen4_planner.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/operator_transformers.go, go/vt/vtgate/planbuilder/operators/horizon_planning.go, go/vt/vtgate/planbuilder/operators/operator.go
This PR moves more of the horizon planning to the operators.
=> Horizon planning on operators

web/vtadmin/package-lock.json, web/vtadmin/package.json, web/vtadmin/src/util/queryString.ts
Updating the `query-string` version to address the vulnerability associated with its `decode-uri-component` dependency: https://security.snyk.io/vuln/SNYK-JS-DECODEURICOMPONENT-3149970
release note: https://github.com/sindresorhus/query-string/releases/tag/v7.1.3
=> update query-string dep due to reported vulnerability

go/test/endtoend/reparent/newfeaturetest/reparent_test.go, go/vt/vtctl/grpcvtctldserver/endtoend/init_shard_primary_test.go, go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_init_test.go, go/vt/wrangler/testlib/backup_test.go, go/vt/wrangler/testlib/copy_schema_shard_test.go, go/vt/wrangler/testlib/emergency_reparent_shard_test.go, go/vt/wrangler/testlib/external_reparent_test.go, go/vt/wrangler/testlib/permissions_test.go, go/vt/wrangler/testlib/planned_reparent_shard_test.go, go/vt/wrangler/testlib/reparent_utils_test.go, go/vt/wrangler/testlib/version_test.go
This is a backport of https://github.com/vitessio/vitess/pull/12534
=> [release-15.0] Fix initialization code to also stop replication to prevent crash #12534

go/vt/vtgate/planbuilder/physical/operator_funcs.go, go/vt/vtgate/planbuilder/testdata/systemtables_cases57.json
=> [release-15.0] Always add columns in the `Derived` operator

go/vt/vterrors/code.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.json, go/vt/vtgate/planbuilder/testdata/filter_cases.json, go/vt/vtgate/planbuilder/testdata/from_cases.json, go/vt/vtgate/planbuilder/testdata/info_schema57_cases.json, go/vt/vtgate/planbuilder/testdata/info_schema80_cases.json, go/vt/vtgate/planbuilder/testdata/postprocess_cases.json, go/vt/vtgate/planbuilder/testdata/select_cases.json, go/vt/vtgate/planbuilder/testdata/symtab_cases.json, go/vt/vtgate/planbuilder/testdata/tpch_cases.json, go/vt/vtgate/planbuilder/testdata/union_cases.json, go/vt/vtgate/planbuilder/testdata/unsupported_cases.json, go/vt/vtgate/planbuilder/testdata/vindex_func_cases.json, go/vt/vtgate/semantics/analyzer_test.go, go/vt/vtgate/semantics/binder.go, go/vt/vtgate/semantics/errors.go
The change in https://github.com/vitessio/vitess/pull/12572 introduced a subtle bug. When we clone a parsed SQL statement, we don't clone the column information since that's used in the semantic analyzer as a by pointer value.
This means that semantic analysis also is not allowed to update / change this column information because it would modify also a previously cloned statement.
So we need to introduce an explicit field reference to the table. This also updates the terminology to use column instead of symbol as that's a more common term and also what MySQL uses in it's error messages.
Issue introduced in https://github.com/vitessio/vitess/pull/12572
-   [x] Did …
=> Fix handling of table information for missing column

go/test/endtoend/backup/vtctlbackup/backup_utils.go
Backup Tests `TestBackupMysqlctld/TestPrimaryBackup` is flaky. Here is one such instance of failure
https://github.com/vitessio/vitess/actions/runs/4477008834/jobs/7868010386
The failure is coming from this piece of test code 
```
// Perform PRS to demote the primary tablet (primary) so that we can do a restore there and verify we don't have the
// data from after the older/first backup
err = localCluster.VtctlclientProcess.ExecuteCommand("PlannedReparentShard", "--",
"--keyspace_shard", shardKsName,
"--new_primary", replica2.Alias)
require.Nil(t, err)
// Delete the current primary tablet (replica2) so that the original primary tablet (primary) can be restored from the
// older/first backup w/o it replicating the subsequent insert done after the first backup was taken
err = …
```
=> Fixing backup tests flakiness

go/test/endtoend/reparent/plannedreparent/reparent_test.go
Downgrad/Upgrade test (Reparent New Vtctl) is failing on v16.0 (https://github.com/vitessio/vitess/actions/runs/4466836285/jobs/7865121597) 
In #12206 we added an additional field "super_read_only" to FullStatus message, with upgrade downgrade test we use N+1 (17) version of Vtctl along with N (v16) version of VTTablet. Since the test code does not have updated proto definition of FullStatus message (replicationdata.proto), it fails to Unmarshal the message object.
1- If I use
```
opt := protojson.UnmarshalOptions{DiscardUnknown: true} 
err = opt.Unmarshal([]byte(primaryStatusString), primaryStatus)
```
then this will disregard the missing fields ...
-   [x] Did …
=> Fix fullstatus test for backward compat

go/vt/vtgate/planbuilder/testdata/from_cases.json, go/vt/vtgate/planbuilder/testdata/union_cases.json, go/vt/vtgate/semantics/analyzer.go, go/vt/vtgate/semantics/analyzer_test.go, go/vt/vtgate/semantics/binder.go
Backport of #12704
In earlier releases, the vtgate planner would be lenient with unknown columns, letting the underlying MySQL if there was a real problem.
This PR re-introduces this behaviour. On queries that only touch a single unsharded keyspace, the gen4 planner will allow missing column information.
Fixes #12548
=> [planner fix 14.0] make unknown column an error only for sharded queries

go/vt/vtgate/planbuilder/testdata/from_cases.json, go/vt/vtgate/planbuilder/testdata/union_cases.json, go/vt/vtgate/semantics/analyzer.go, go/vt/vtgate/semantics/analyzer_test.go, go/vt/vtgate/semantics/binder.go
Backport of #12704
In earlier releases, the vtgate planner would be lenient with unknown columns, letting the underlying MySQL if there was a real problem.
This PR re-introduces this behaviour. On queries that only touch a single unsharded keyspace, the gen4 planner will allow missing column information.
Fixes #12548
=> [planner fix 16.0] make unknown column an error only for sharded queries

go/vt/vttablet/onlineddl/schema.go
Fixes https://github.com/vitessio/vitess/issues/12261
The fix  in https://github.com/vitessio/vitess/pull/12262 cannot be backported because of how internal schema management was redesigned in https://github.com/vitessio/vitess/pull/11520
The solution in this PR is to fix the actual values. They should not be zero. They should have some timestamp value, which we borrow from `added_timestamp` column.
An `UPDATE` query runs on PRIMARY tablet initialization, just after table is created and before the rest of DDLs kick. So it runs once in the lifetime of the tablet. It's a full table scan query, but `_vt.schema_migrations` is never too large.
-   [ ] Documentation …
=> Bugfix/Backport to v15: Fix schema migrations requested_timestamp zero values

go/vt/vtgate/planbuilder/testdata/from_cases.json, go/vt/vtgate/planbuilder/testdata/systemtables_cases80.json, go/vt/vtgate/planbuilder/testdata/union_cases.json, go/vt/vtgate/semantics/analyzer.go, go/vt/vtgate/semantics/analyzer_test.go, go/vt/vtgate/semantics/binder.go
Backport of #12704
In earlier releases, the vtgate planner would be lenient with unknown columns, letting the underlying MySQL if there was a real problem.
This PR re-introduces this behaviour. On queries that only touch a single unsharded keyspace, the gen4 planner will allow missing column information.
Fixes #12548
=> [planner fix 15.0] make unknown column an error only for sharded queries

go/mysql/flavor_mysql.go, go/test/endtoend/vreplication/vstream_test.go
To make sure the behaviour of the schema engine is the same for 5.7 and 8.0 in terms of handling of tables that have innodb tablespace set to innodb_system (those are not included in `information_schema.innodb_tablespaces`). This should make sure that vstreamer works as expected when some of the tables in a keyspace have been created with `tablespace innodb_system` option (because of https://bugs.mysql.com/bug.php?id=110383 or some other reason).
This issue exists in 14.x and the fix needs backporting AFAIU.
Fixes #12669
=> Use a left join to make sure that tables with tablespace=innodb_system are included in the schema

go/vt/vtgate/evalengine/api_literal.go, go/vt/vtgate/evalengine/compare.go, go/vt/vtgate/evalengine/compiler_asm.go, go/vt/vtgate/evalengine/compiler_compare.go, go/vt/vtgate/evalengine/compiler_json.go, go/vt/vtgate/evalengine/eval.go, go/vt/vtgate/evalengine/eval_bytes.go, go/vt/vtgate/evalengine/eval_json.go, go/vt/vtgate/evalengine/eval_numeric.go, go/vt/vtgate/evalengine/expr_compare.go, go/vt/vtgate/evalengine/fn_base64.go, go/vt/vtgate/evalengine/internal/json/helpers.go, go/vt/vtgate/evalengine/internal/json/parser.go, go/vt/vtgate/evalengine/internal/json/parser_test.go, go/vt/vtgate/evalengine/testcases/cases.go, go/vt/vtgate/evalengine/testcases/inputs.go, go/vt/vtgate/evalengine/translate.go
This extends the evalengine support to better convert existing types to JSON as appropriate.
It also implements the comparison according to https://dev.mysql.com/doc/refman/8.0/en/json.html.
Extends the work started in https://github.com/vitessio/vitess/pull/12369.
=> Implement logic to handle more JSON conversion

go/test/endtoend/reparent/plannedreparent/reparent_test.go
=> fix fullstatus test for backward compat (#12685)

go/test/endtoend/backup/vtctlbackup/backup_utils.go
[cherrypick #12655](https://github.com/vitessio/vitess/pull/12655)
- remove unnecessary vtorc process
- Adding vtorc disabling at right place
- Adding comments
=> Fixing backup tests flakiness (#12655)

go/vt/vtgate/executor.go, go/vt/vtgate/executor_test.go, go/vt/vtgate/queryz_test.go, go/vt/vtgate/vcursor_impl.go, go/vt/vtgate/vcursor_impl_test.go
This PR changes the contents of the key used when caching Query Plans in the VTGate to include the VCursor's current collation (which defaults to the user's connection collation).
Right now, there are two places in the `evalengine` where this collation is considered:
1. When first translating a SQL expression (passed as an argument to `Translate`)
2. When executing a SQL expression (passed as a field in `ExpressionEnv`).
This behavior is not consistent and can lead to buggy evaluation when an user with a specific collation first performs a query, the query's plan is cached, and then separate request with a different connection collation re-uses the same cached plan.
The WIP PR https://github.com/vitessio/vitess/pull/12724 removes the usage of (2) so that the only place where connection …
=> vtgate: use collation when hashing query plans

go/vt/vttablet/tabletserver/repltracker/reader.go, go/vt/vttablet/tabletserver/repltracker/reader_test.go, go/vt/vttablet/tabletserver/repltracker/writer_test.go
Reset the current replication lag on the replication lag reader when closing it.
Co-authored with @arthurschreiber.
Fixes https://github.com/vitessio/vitess/issues/12682.
N/A.
=> Reset the current lag when closing the replication lag reader.

go/vt/vtgate/vindexes/cached_size.go, go/vt/vtgate/vindexes/numeric_static_map.go, go/vt/vtgate/vindexes/numeric_static_map_test.go
`numeric_static_map` supports a JSON file. In some environments it may be more convenient to set this in the VSchema directly, rather than make the JSON file available everywhere it needs to be loaded.
In addition, it would be useful to have the ability to fallback to a hash lookup when there are keys missing from the json mapping.
* Fixes https://github.com/vitessio/vitess/issues/12411
* Addresses https://github.com/vitessio/vitess/issues/12412
One thing @aquarapid and I are not happy about is having to embed a JSON document inside a proto string type. If possible, we would like to amend the proto definition for vindexes to support nested, typed options. Have created https://github.com/vitessio/vitess/issues/12413 to have that discussion, and can amend this PR depending on the outcome of …
=> go/vt/vtgate: add json and use_fallback opts to numeric_static_map vdx

examples/common/env.sh, go/test/endtoend/cluster/cluster_util.go, go/test/endtoend/vreplication/materialize_test.go, go/test/endtoend/vreplication/migrate_test.go, go/test/endtoend/vreplication/performance_test.go, go/test/endtoend/vreplication/resharding_workflows_v2_test.go, go/test/endtoend/vreplication/time_zone_test.go, go/test/endtoend/vreplication/vdiff2_test.go, go/test/endtoend/vreplication/vreplication_test.go, go/test/endtoend/vreplication/vschema_load_test.go, go/test/endtoend/vreplication/vstream_test.go, test/local_example.sh
=> [release-16.0] Flakes: Use new healthy shard check in vreplication e2e tests (#12502)

go/mysql/fakesqldb/server.go, go/vt/log/log.go, go/vt/vtctl/vdiff2_test.go, go/vt/vtctl/vdiff_env_test.go, go/vt/vttablet/tabletserver/bench_test.go, go/vt/wrangler/vdiff_env_test.go, go/vt/wrangler/vdiff_test.go, go/vt/wrangler/vexec_test.go, go/vt/wrangler/wrangler_env_test.go
* Use atomic.Bool for fakesqldb behavior flags #12603
* Flakes: Address Common Unit Test Races #12546
#12603
#12546
=> [release-16.0] Port two flaky test fixes #12603 and #12546

go/vt/vttablet/tabletserver/repltracker/reader.go, go/vt/vttablet/tabletserver/repltracker/reader_test.go, go/vt/vttablet/tabletserver/repltracker/writer_test.go
=> [release-15.0] Reset the current lag when closing the replication lag reader. (#12683)

go/vt/throttler/throttler.go, go/vt/vttablet/tabletserver/txthrottler/tx_throttler.go, go/vt/vttablet/tabletserver/txthrottler/tx_throttler_test.go
This PR fixes an issue leading to the transaction throttler ignoring the `initial rate` parameter passed to it.
https://github.com/vitessio/vitess/issues/12549 
N/A
=> Fix transaction throttler ignoring the initial rate

changelog/17.0/17.0.0/summary.md, go/vt/topo/keyspace.go, go/vt/topo/keyspace_test.go, go/vt/topo/topotests/keyspace_test.go, go/vt/vtorc/inst/keyspace_dao.go
What it says on the tin. Note that any method that calls `GetKeyspace` will be affected by this ([almost a good search](https://github.com/search?q=repo%3Avitessio%2Fvitess+language%3AGo+%2F%5C.GetKeyspace%2F+%28path%3Ago%2Fvt%2Ftopo%2F+OR+path%3Ago%2Fvt%2Fvtctl%29&type=code&l=Go))
- Fixes https://github.com/vitessio/vitess/issues/12738
=> Update topo {Get,Create}Keyspace to prevent invalid keyspace names

go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go
This PR does better cleanup of `schema_migrations.artifacts` column. As reminder, this column has a concatenated list of all artifact tables created or needed by a migration. Specifically for `ALTER TABLE`, this can include the `_vrepl` table, sentry table (whose cleanup is handled in #12451), "old" table, etc. Once a migration is complete, or failed, and after a predefined duration (`24h`) we read `artifacts` column, and iterate the list of tables to destroy them ("send" them over to GC by renaming them away).
But we'd leave the `artifacts` column intact. A `cleanup_timestamp` indicates we're done, and we'd never look into it again. The reasoning for leaving the column intact was for better debuggability. We'd be able to look up the artifact names in a long-since-completed migration, and …
=> Online DDL: remove artifact entry upon GC

.github/workflows/create_release.yml, .github/workflows/docker_test_cluster_10.yml, .github/workflows/docker_test_cluster_25.yml, .github/workflows/endtoend.yml, .github/workflows/sonar_analysis.yml, .github/workflows/static_checks_etc.yml, .github/workflows/upgrade_downgrade_test_backups_manual.yml, .github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
As mentioned by @pnacht in #12718 (https://github.com/vitessio/vitess/pull/12718#issuecomment-1485287983) we still have some unnecessary bits of code in our workflow files, this Pull Request removes those bits.
=> Remove unnecessary code bits in workflows

go/slices2/slices.go, go/vt/vtgate/planbuilder/operator_transformers.go, go/vt/vtgate/planbuilder/operators/apply_join.go, go/vt/vtgate/planbuilder/operators/derived.go, go/vt/vtgate/planbuilder/operators/filter.go, go/vt/vtgate/planbuilder/operators/helpers.go, go/vt/vtgate/planbuilder/operators/horizon.go, go/vt/vtgate/planbuilder/operators/horizon_planning.go, go/vt/vtgate/planbuilder/operators/operator.go, go/vt/vtgate/planbuilder/operators/ops/op.go, go/vt/vtgate/planbuilder/operators/rewrite/rewriters.go, go/vt/vtgate/planbuilder/operators/route.go, go/vt/vtgate/planbuilder/operators/route_planning.go, go/vt/vtgate/planbuilder/operators/simpleProjection.go, go/vt/vtgate/planbuilder/operators/simple_projection.go, go/vt/vtgate/planbuilder/operators/subquery_planning.go, go/vt/vtgate/planbuilder/operators/table.go, go/vt/vtgate/planbuilder/operators/vindex.go, go/vt/vtgate/planbuilder/simple_projection.go, go/vt/vtgate/planbuilder/testdata/from_cases.json, go/vt/vtgate/semantics/semantic_state.go
While planning, we use two important types of data structures - logical plans and operators. We are moving more and more logic over to the operators. This PR moves planning of projections over to the operators. 
Still to do is: ordering, limit, distinct and aggregation.
Tracking issue: https://github.com/vitessio/vitess/issues/11626
Other PRs in this series: #11622, #11680, #12506
=> [gen4 planner] Move more horizon planning to operators

changelog/16.0/16.0.1/summary.md, go/vt/topo/keyspace.go, go/vt/topo/topotests/keyspace_test.go, go/vt/vtorc/inst/keyspace_dao.go
Backports #12732, had to do manually to not pick up https://github.com/vitessio/vitess/pull/12525
=> [Backport] Update topo {Get,Create}Keyspace to prevent invalid keyspace names (#12732)

changelog/14.0/14.0.5/changelog.md, changelog/14.0/14.0.5/release_notes.md, changelog/15.0/15.0.3/changelog.md, changelog/15.0/15.0.3/release_notes.md, changelog/16.0/16.0.1/changelog.md, changelog/16.0/16.0.1/release_notes.md, changelog/16.0/16.0.1/summary.md
This PR copies the release notes for v16.0.1, v15.0.3 and v14.0.5.
=> Copy release notes for v16.0.1, v15.0.3, and v14.0.5

changelog/17.0/17.0.0/summary.md, go/stats/export.go, go/stats/export_test.go, go/stats/prometheusbackend/collectors.go, go/stats/prometheusbackend/prometheusbackend.go, go/stats/prometheusbackend/prometheusbackend_test.go, go/vt/vttablet/tabletmanager/vreplication/stats.go
In order to make it easier to monitor VReplication workflow status, expose the existing `VReplicationStreamState` as a 1-valued Prometheus gauge. S/o @mcrauwel for the idea.
- Fixes: #12770
=> go/{stats,vt}: publish VReplicationStreamState to prometheus backend

go/tools/release-notes/release_notes.go
As witnessed in the recent Release Pull Requests (https://github.com/vitessio/vitess/pull/12766/commits/0b41ed2fd2bd41b46f479cf08d192dd76b1c8554 in https://github.com/vitessio/vitess/pull/12766) the generated folder for the release notes was incorrect. There was an extra `v`. This pull request fixes this issue.
=> Fix incorrect path during release notes generation

.github/workflows/create_release.yml, .github/workflows/docker_test_cluster_10.yml, .github/workflows/docker_test_cluster_25.yml, .github/workflows/endtoend.yml, .github/workflows/sonar_analysis.yml, .github/workflows/static_checks_etc.yml, .github/workflows/upgrade_downgrade_test_backups_manual.yml, .github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
=> [release-16.0] Remove unnecessary code bits in workflows (#12756)

go/test/endtoend/cluster/cluster_process.go, go/test/endtoend/reparent/prssettingspool/main_test.go, go/test/endtoend/reparent/prssettingspool/schema.sql, go/test/endtoend/reparent/utils/utils.go, go/vt/vtgate/safe_session.go, test/config.json
This PR fixes a bug exposed on PRS when the settings pool is enabled on vttablet.
A transaction leaves the tablet tagged to the shard session even after a commit or rollback.
On PRS, that session will keep sending the query to the same tablet and would receive the error until that session is closed and new session is created.
`vttablet: rpc error: code = FailedPrecondition desc = wrong tablet type: PRIMARY, want: REPLICA or []", state: "HY000"` 
-   [X] "Backport to:" labels have been added if this change should be back-ported 16.0 and main
=> Fix: reset transaction session when no reserved connection

examples/common/scripts/vtadmin-up.sh
This PR removes the `nvm use` lines in `vtadmin-up.sh` script, since `nvm install` will also execute `nvm use`:
```
➜  vitess git:(main) nvm install 16
v16.20.0 is already installed.
Now using node v16.20.0 (npm v8.19.4)
```
N/A
-   [x] "Backport to:" labels have been added if this change should be back-ported **Not needed**
-   [x] Tests were added or are not required **Not needed**
-   [x] Did the new or modified tests pass consistently locally and on the CI **No new tests**
-   [x] Documentation was added or is not required **Not needed**
N/A
=> Remove `nvm use` from vtadmin-up.sh script

.github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml, .github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml, .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml, .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml
This is a follow up of the recent golang version upgrade that was done on `release-16.0`. We'll now use a compatible golang version in the next-upgrade/downgrade tests.
=> [release-15.0] Use go1.20.2 in next-upgrade/downgrade workflows

examples/common/scripts/vttablet-up.sh, go/flags/endtoend/vttablet.txt, go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go, go/test/endtoend/onlineddl/vtctlutil.go, go/test/endtoend/tabletmanager/throttler_topo/throttler_test.go, go/test/endtoend/throttler/util.go, go/vt/vttablet/tabletserver/throttle/throttler.go
=> [release-16.0] Throttler: Expose Tablet's Config & Leverage to Deflake Tests

.github/workflows/assign_milestone.yml
=> [release-16.0] Automatically add milestone to new Pull Request (#12759)

go/mysql/json/fastparse/fastparse.go, go/mysql/json/fastparse/fastparse_test.go, go/vt/vtgate/evalengine/cached_size.go, go/vt/vtgate/evalengine/compiler.go, go/vt/vtgate/evalengine/compiler_asm.go, go/vt/vtgate/evalengine/compiler_asm_push.go, go/vt/vtgate/evalengine/compiler_fn.go, go/vt/vtgate/evalengine/compiler_test.go, go/vt/vtgate/evalengine/eval_numeric.go, go/vt/vtgate/evalengine/fn_numeric.go, go/vt/vtgate/evalengine/fn_time.go, go/vt/vtgate/evalengine/testcases/cases.go, go/vt/vtgate/evalengine/translate_builtin.go
This implements the `CRC32`, `CONV` & `UTC_DATE` functions in the evalengine.
Part of #9647 
=> evalengine: Implement CRC32 & CONV

build.env
Following the recent Golang upgrade on main (https://github.com/vitessio/vitess/pull/12706) we want to let developers choose whatever Golang version they want, and thus not fail the build if the version is not exactly what we expect.
There are several places where the Golang version has to be exactly how we expect it to be:
- In the Docker images
- In the CI workflows
With the new automated process to upgrade the Golang version in the repository we now have more trusts that the two places listed above will always contain valid values.
If the version is not what we expect, we print a warning.
- Website docs change: https://github.com/vitessio/website/pull/1433
- …
=> Do not fail build on incorrect Go version

go/vt/vttablet/tabletserver/gc/tablegc.go
=> [release-16.0] Table GC: remove spammy log entry (#12625)

.github/workflows/unit_race.yml, go/mysql/fakesqldb/server.go, go/vt/vtctl/grpcvtctldserver/server.go, go/vt/vtctl/grpcvtctldserver/server_test.go
This lock is used around adding to the query log, but it means we also need to use the lock when reading from it or when resetting it.
We've seen this cause race test failures which look like this:
```
$ go test -trimpath -race -v -count=1000 ./go/vt/vttablet/tabletserver -run TestReserveExecute_WithTx
=== RUN   TestReserveExecute_WithTx
E0403 15:54:57.850444    4408 server.go:418] Query not found: set @@session.sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
E0403 15:54:57.854239    4408 server.go:418] Query not found: show full tables like '\_vt\_%'
Write at 0x00c000556460 by goroutine 363:
vitess.io/vitess/go/mysql/fakesqldb.(*DB).ResetQueryLog() …
```
=> fakesqldb: Guard query log usage with lock

go/vt/vtgate/executor.go
The PR added the length of actual rows to the current warning log.
- Closes https://github.com/vitessio/vitess/issues/12753
=> Log the length of the actual rows when the query exceeds the warning threshold

go/vt/vtgate/planbuilder/operators/derived.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.json
We can't push predicates with aggregations into derived tables - we need to evaluate the derived table and only after can we evaluate the predicate.
Fixes #12798 
=> [planbuilder bugfix] do not push aggregations into derived tables

go/sqltypes/value.go, go/vt/vtgate/evalengine/integration/comparison_test.go, go/vt/vtgate/evalengine/integration/fuzz_test.go
Looks like Actions sometimes runs slow enough that 100ms is not enough buffer, so increase it to 1 second and allow the limit value itself as well. This is useful if things are rounded to seconds already.
Also compare `TIME` objects in a similar way to allow for differences.
See failure output like https://github.com/vitessio/vitess/actions/runs/4597420941/jobs/8125168911
=> evalengine: Try to reduce test flakyness around time

go/mysql/datetime/time_zone.go, go/mysql/datetime/time_zone_test.go, go/mysql/sql_error.go, go/vt/vterrors/state.go, go/vt/vtgate/safe_session.go, go/vt/vtgate/safe_session_test.go
While looking at supporting `CONVERT_TZ` in the evalengine, it was clear that our current timezone parsing didn't suffice. MySQL also supports direct UTC offsets to be used as a timezone identifier which `time.LoadLocation` doesn't handle.
This adds support for parsing this style of timezone offsets and a bunch of tests for this as well. It adds a separate parsing function with error so in the future we can use that in `CONVERT_TZ` which returns `NULL` on invalid timezone definitions.
Part of implementing #9647 and something that was missed in #12742
-   [x] Documentation was added or …
=> evalengine: Improve the timezone parsing logic

go/vt/vtadmin/grpcserver/server.go, go/vt/vtadmin/http/response.go
This installs middleware ("ish" in the case of the http side) layers to both the HTTP and gRPC APIs for vtadmin to ensure that any methods that ultimately return an error log that error at the ERROR level to facilitate better debugging
After creating a bogus shard as described in #12842, trying to load the keyspace page now shows in the logs as:
```
E0405 14:32:48.115084   20808 response.go:48] FindAllShardsInKeyspace(cluster = local, keyspace = commerce) failed: rpc error: code = Unknown desc = uncaught panic: runtime error: invalid memory address or nil pointer dereference
E0405 14:32:49.139644   20808 response.go:48] FindAllShardsInKeyspace(cluster = local, keyspace = commerce) failed: rpc error: code = Unknown desc = uncaught panic: runtime error: invalid memory address or nil pointer …
```
=> [vtadmin] log response errors

go/vt/vtadmin/http/api.go, go/vt/vtadmin/http/api_test.go, go/vt/vtadmin/http/backups.go, go/vt/vtadmin/http/cells.go, go/vt/vtadmin/http/experimental/tablets.go, go/vt/vtadmin/http/gates.go, go/vt/vtadmin/http/keyspaces.go, go/vt/vtadmin/http/replication.go, go/vt/vtadmin/http/schemas.go, go/vt/vtadmin/http/shards.go, go/vt/vtadmin/http/srvkeyspaces.go, go/vt/vtadmin/http/srvvschemas.go, go/vt/vtadmin/http/tablets.go, go/vt/vtadmin/http/vschemas.go, go/vt/vtadmin/http/vtctlds.go, go/vt/vtadmin/http/vtexplain.go, go/vt/vtadmin/http/workflows.go
This does the API portion of #12729 by introducing a step in the `http.Adapt` function that turns any request with a `cluster` query param into a `cluster_id` query param, logging a warning if it needed to make that transformation.
<details><summary>test requests</summary>
```
➜  local git:(andrew/vtadmin-standardize-cluster_ids) ✗ curl "localhost:14200/api/keyspaces?cluster=local"
{"result":{"keyspaces":[{"cluster":{"id":"local","name":"local"},"keyspace":{"name":"commerce","keyspace":{"durability_policy":"semi_sync","sidecar_db_name":"_vt"}},"shards":{"0":{"keyspace":"commerce","name":"0","shard":{"primary_alias":{"cell":"zone1","uid":100},"primary_term_start_time":{"seconds":1680373482,"nanoseconds":17317000},"is_primary_serving":true}}}}]},"ok":true}%             
➜  local …
```
=> [vtadmin-api] standardize cluster ids

.github/workflows/update_golang_version.yml, go/tools/go-upgrade/go-upgrade.go
We could see two issues in the previous golang upgrade auto Pull Requests:
- The bootstrap version was `14.2999999..` instead of `14.3`. This is because the summing operations of two float can give different results if there are some gaps in the mantissa. 
- The bot would re-create the Pull Request on top of the already existing one.
These two issues are now fixed in this PR.
=> Small fixes to the auto-upgrade golang tool

go/vt/discovery/keyspace_events.go, go/vt/vtgate/tabletgateway.go, go/vt/vtgate/tabletgateway_flaky_test.go
This Pull Request fixes the test `TestGatewayBufferingWhileReparenting` which was found to be flaky.
To quote @GuptaManan100:
> I found a race that is causing this failure. I believe it's not the test, but a race in the code itself. Consider these operations:
>
> - PRS has started and the primary tablet has published itself as not-serving.
> - This causes the call `tablets := gw.hc.GetHealthyTabletStats(target)` to not return any tablets.
> - We end up going into the if condition block, which is going to check for potential problems with the shard.
> - Before that code runs, let's assume the new primary succeeds and publishes itself as serving.
> - Now the code in the condition check is going to say that there is nothing wrong with the cluster, and we get the error no healthy tablet …
=> Fix `TestGatewayBufferingWhileReparenting` flakiness

go/cache/ristretto/bloom/bbloom_test.go, go/cache/ristretto/cache_test.go, go/cache/ristretto/sketch_test.go, go/vt/wrangler/fake_dbclient_test.go, go/vt/wrangler/resharder_env_test.go, go/vt/wrangler/traffic_switcher_env_test.go, go/vt/wrangler/vdiff_env_test.go
* VDiff unit tests had not setup fakedb to expect some queries and they were being excessively logged in the unit/e2e test workflows
* Removed old debug code in vreplication 
* Other minor fixes
=> VDiff: cleanup test log output

.github/workflows/static_checks_etc.yml, .golangci.yml
This Pull Request bumps the version we use for `golangci-lint` from `1.51.2` to `1.52.2`. We're now using `--timeout 10m` when calling `golangci-lint` in our CI workflow. The default timeout is 1 minute can be easily reached without cache.
=> Add timeout to `golangci-lint` and bump its version

changelog/17.0/17.0.0/summary.md, go/vt/topo/shard.go, go/vt/topo/shard_test.go
Gives echos of https://github.com/vitessio/vitess/pull/12732
"demo" of this erroring out in vtadmin:
Fixes #12842.
=> [topo] Disallow the slash character in shard names

build.env
This Pull Request is a follow-up of https://github.com/vitessio/vitess/pull/12809, it fixes a misleading sentence that @deepthi noticed in https://github.com/vitessio/vitess/pull/12809#discussion_r1158746593.
=> Remove misleading message in `build.env`

examples/common/scripts/vtadmin-up.sh, web/vtadmin/.gitignore, web/vtadmin/README.md, web/vtadmin/src/components/links/ExternalTabletLink.tsx, web/vtadmin/src/components/routes/Tablets.tsx, web/vtadmin/src/components/routes/shard/ShardTablets.tsx
https://github.com/vitessio/vitess/issues/12837
Following our [Slack discussion](https://vitess.slack.com/archives/C01H307F68J/p1680076925636199) we saw that there are four slashes in front of vttablet links (like: `////10.95.196.20:15000/debug/status`) preventing user to specify the protocol (http/https). 
This fix aims to remove those / and allow user to specify the protocol they want to use.
Before the fix: 
After the fix:
=> fix: vtadmin vttablet url protocol

.github/workflows/static_checks_etc.yml
This ensures we run it on Node 16, fixing the current deprecation message it shows.
See for example the output at https://github.com/vitessio/vitess/actions/runs/4664825536
=> Update fossa check for Node deprecation

.github/workflows/assign_milestone.yml, .github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml, .github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml, .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml, .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml
This is in preparation for https://github.com/vitessio/vitess/pull/12832. The upgrade downgrade tests will now use `go1.20.3`.
=> Use go1.20.3 in the upgrade downgrade tests

docker/base/Dockerfile, docker/base/Dockerfile.mysql57, docker/base/Dockerfile.percona57, docker/base/Dockerfile.percona80, tools/build_version_flags.sh
This PR allows us to configure the build time via Docker build-args. By
default nothing changes, but it'll allow us to pass down the
build-time from a CI environment. It's useful for cases when you want to
store the same build time of a binary also in a different environment
for logging purposes.
Signed-off-by: Fatih Arslan <fatih@planetscale.com>
=> tools/build_version_flags: allow configurable `build time`

go/cmd/zk/zkcmd.go
`zk rm` appears to be broken due to a mistake in pflag setup.
The pflag library which we recently migrated to prohibits shorthand flags greater than a single character[1]. As currently written, the `zk` tool panics in `cmdRm` due to the shorthand `rf`. ~The patch fixes by changing this shorthand from `rf` to `F`.~ Fortunately pflag supports combined flags. Since we already have `r` and `f` defined, we don't need a separate `rf` flag, so we can simply remove this line.
[1] https://github.com/spf13/pflag/blob/85dd5c8bc61cfa382fecd072378089d4e856579d/flag.go#L868-L872
N/A
-   [ ] …
=> Fix shorthand flag for recursive delete in zk tool

changelog/16.0/16.0.2/summary.md, go/vt/topo/shard.go, go/vt/topo/shard_test.go
=> Backport: [topo] Disallow the slash character in shard names #12843

go/vt/vtadmin/api.go, go/vt/vtadmin/http/handlers/panic_recovery.go, go/vt/vtadmin/http/handlers/panic_recovery_test.go
What it says on the tin.
Closes #12863 
=> Add panic recovery handler to vtadmin http middleware

go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go
This PR attempts to fix https://github.com/vitessio/vitess/issues/12336. ~~I'll keep it in `Draft` and run `onlineddl_vrepl` test a few times in CI, before asking for review.~~
https://github.com/vitessio/vitess/issues/12336 presents a very weird situation, where the `_vt.vreplication.time_throttled` value, recorded by `vreplication` components, ends up being _earlier_ than a migration's `started_timestamp`, which shouldn't possibly happen, as we only ever start looking at the migration's throttler state _after it starts_.
The one thing that caught my eye is that `vreplication` grabs current time and extracts it to Unix time:
https://github.com/vitessio/vitess/blob/a6529e1df6ea6e4e7b7ecfa65f985f5f1db0803d/go/vt/vttablet/tabletmanager/vreplication/vreplicator.go#L534-L535
But then, as we …
=> Flaky test fix: OnlineDDL: convert time->unix->TIMESTAMP in golang space

go/mysql/datetime/format_test.go, go/mysql/datetime/formats.go, go/mysql/datetime/spec.go, go/mysql/datetime/types.go, go/vt/vtgate/evalengine/mysql_test.go
One of the things we punted on in #12815 was formatting week numbers. This adds support for those formats as well.
Follow-up to #12815
=> datetime: Add week number formatting

go/vt/vtgate/planbuilder/testdata/select_cases.json, go/vt/vtgate/semantics/analyzer_test.go, go/vt/vtgate/semantics/early_rewriter_test.go, go/vt/vtgate/semantics/scoper.go
This PR updates the scoping rules for expressions involved in join table ON clauses, allowing them to use the scope of the SELECT statement's parent scope.
In MySQL 5.7, this scoping rule is not supported. However, MySQL 8.0 and later versions do support this functionality.
For example, consider the following query:
```sql
SELECT 1, (SELECT foo FROM t1 JOIN t2 ON t1.col = t2.col AND t1.id = t3.id) subquery FROM t3;
```
With the updated scoping rules, the join condition between t1 and t2 can now reference columns from t3, essentially allowing access to all columns available from the outer query.
-   [X] Did the new or modified tests pass consistently locally and …
=> planner fix: scoping rules for JOIN ON expression inside a subquery

go/vt/vtgate/evalengine/api_literal.go
This is a small fix that makes the creation of `Column` entities in the evalengine consistent. The `Type` of the column must be initialized to -1 to mark it as "unset", because the zero value for `Type` is actually `sqltypes.Null`, which is a valid type for a column to have.
cc @dbussink 
=> evalengine: unset Type for NewColumnWithCollation

go/vt/vttablet/onlineddl/executor.go
This PR merely changes the text in an error message when the OnlineDDL executor finds and terminates a rogue `gh-ost` migration.
#6926 
=> gh-ost migrations: improved error log message

go/test/endtoend/cluster/cluster_util.go, go/test/endtoend/cluster/mysqlctl_process.go, go/test/endtoend/cluster/mysqlctld_process.go, go/test/endtoend/mysqlctld/mysqlctld_test.go
Backup tests are flaky. One such example is 
Cluster 21 --> https://github.com/vitessio/vitess/actions/runs/4620105525/jobs/8169754027
During mysql Teardown, it is observed that sometimes mysql is not able to stop, clean and restart properly. I saw there was a fix done for similar issue by @rohit-nayak-ps (https://github.com/vitessio/vitess/pull/12799). So I refactored his code and added some additional enhancement.
Ran test in CI few times to make sure, it is no longer flaky
https://github.com/vitessio/vitess/actions/runs/4614501474
=> Fix backup flaky tests

go/vt/sqlparser/ast_funcs.go, go/vt/vtgate/semantics/analyzer.go, go/vt/vtgate/semantics/check_invalid.go, go/vt/vtgate/semantics/early_rewriter.go, go/vt/vtgate/semantics/early_rewriter_test.go, go/vt/vtgate/semantics/scoper.go, go/vt/vtgate/semantics/semantic_state.go
Refactoring of the semantics package. I searched for methods with high cognitive complexity, and worked on them to simplify. In the process, I found dead code that could be removed.
=> refactor: clean up and simplify the semantics package

go/vt/schemadiff/diff.go, go/vt/schemadiff/diff_test.go, go/vt/schemadiff/schema.go, go/vt/schemadiff/schema_diff.go, go/vt/schemadiff/schema_diff_test.go
Followup to https://github.com/vitessio/vitess/pull/12551
This PR hides the original `Schema.Diff()` function as `Schema.diff()`, leaving `SchemaDiff()` as the only mechanism for diffing two schemas.
The resulting `SchemaDiff` object offers these two public functions for getting the diffs:
- `OrderedDiffs()`: typically this is what you want to use; a linearized slice of diffs, which are guaranteed to be conflict free and keep the schema valid at each step (a non-nil error is returned if it is impossible to get a conflict free list)
- `UnorderedDiffs()`: a list of diffs - same diffs as above - but in non guaranteed and non-tested order. The order will work in the vast majority of cases and uses some basic heuristics. The use case for this function is for when the above `OrderedDiffs()` …
=> schemadiff: formalize SchemaDiff as the only schema diffing mechanism

go/mysql/datetime/parse.go, go/mysql/datetime/spec.go, go/vt/vtgate/evalengine/cached_size.go, go/vt/vtgate/evalengine/compiler_asm.go, go/vt/vtgate/evalengine/compiler_fn.go, go/vt/vtgate/evalengine/eval_temporal.go, go/vt/vtgate/evalengine/fn_time.go, go/vt/vtgate/evalengine/integration/comparison_test.go, go/vt/vtgate/evalengine/testcases/cases.go, go/vt/vtgate/evalengine/testcases/inputs.go, go/vt/vtgate/evalengine/translate_builtin.go
This adds the CONVERT_TZ function to convert between different timezones. It assumes that the timezone tables are loaded in MySQL as well and always has these functions working.
It also fixes a number of issues found in the DATE_FORMAT logic where it would for example panic on invalid timestamps. We also need to be able to parse the fractional part of decimals or floats for timestamp conversions.
Follow up https://github.com/vitessio/vitess/pull/12815 and part of #9647 
=> evalengine: Add CONVERT_TZ function

go/vt/vttablet/tabletserver/tabletserver.go
This PR removes the ACL check on the tablet server's HTTP API `/healthz` endpoint. Currently if `security_policy` is set to something like `deny-all` the `/healthz` endpoint is restricted which interferes with the ability to use it as a liveness/readiness probe check in Kubernetes. The `/healthz` endpoint doesn't return any sensitive information as it returns either a 200 OK or 500 error if the tablet is unhealthy (i.e not serving or high replication lag). 
- https://github.com/vitessio/vitess/issues/12896
- https://vitess.slack.com/archives/C0PQY0PTK/p1681400286098069
-   [ ] …
=> remove tablet server's ACL check on the /healthz HTTP api route

.github/workflows/static_checks_etc.yml, .golangci.yml
This reverts the golangci-lint version upgrade that was done in #12853
=> [release-15.0] Remove recent golangci-lint version bump

.github/workflows/static_checks_etc.yml, .golangci.yml
This reverts the golangci-lint version upgrade that was done in #12854
=> [release-16.0] Remove recent golangci-lint version bump

go/vt/schemadiff/errors.go, go/vt/schemadiff/schema_diff.go, go/vt/schemadiff/schema_diff_test.go
Continuing https://github.com/vitessio/vitess/pull/12551 and https://github.com/vitessio/vitess/pull/12885, this PR offers a strongly typed and rich `ImpossibleApplyDiffOrderError`.
This error indicates the total diffs for which no valid ordering is found, as well as a subset of diffs that causes the conflict. From there' we can generate the statements, or extract the effected entities.
- https://github.com/vitessio/vitess/pull/12551
- https://github.com/vitessio/vitess/pull/12885
- #10203 
=> schemadiff: rich `ImpossibleApplyDiffOrderError`

go/mysql/datetime/types.go, go/vt/vtgate/evalengine/compiler_test.go, go/vt/vtgate/evalengine/testcases/cases.go
In #12907 the focus was first on adding a lot of the new functions but we didn't add the additional week formats that `WEEK` supports but `DATE_FORMAT` doesn't.
This adds those week formats as well.
Follow up to #12907 and part of #9647
=> evalengine: Implement additional week modes

go/cmd/vtctldclient/command/tablets.go, go/vt/topo/topoproto/tablet.go
Filtering by tablet type was added to the `ListAllTablets` vtctl command in https://github.com/vitessio/vitess/pull/9560 but did not exist in the new `GetTablets` vtctldclient command (its successor).
- Follow-up to: https://github.com/vitessio/vitess/pull/9560
-   [x] Documentation: https://github.com/vitessio/website/pull/1446
=> Add tablet type filtering to vtctldclient GetTablets

go/vt/vtgate/planbuilder/operator_transformers.go, go/vt/vtgate/planbuilder/operators/SQL_builder.go, go/vt/vtgate/planbuilder/operators/horizon_planning.go, go/vt/vtgate/planbuilder/operators/limit.go, go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/planbuilder/testdata/from_cases.json, go/vt/vtgate/planbuilder/testdata/select_cases.json, go/vt/vtgate/planbuilder/testdata/wireup_cases.json
This PR adds the functionality to do the limit planning on operators and not on the logical plan
- #11626 
=> Add limit planning to operators

go/mysql/datetime/types.go, go/vt/vtgate/evalengine/compiler_test.go
It's not safe to add multiples of 24 hours to `time.Time` instances to try and move things a certain number of days since some days might have DST changes and more or less than 24 hours in one day.
Instead use the proper function to add a specific number of days to a `time.Time`.
Introduced in #12916 
=> datetime: Fix weekday calculation for DST changes

changelog/17.0/17.0.0/summary.md, go/flags/endtoend/vtctld.txt, go/vt/vtctld/vtctld.go
This PR deprecates the `durability_policy` flag in vtctld, the working of which was changed a long time ago. Vtctld now reads the durability policy from the keyspace information for all the keyspaces and doesn't rely on the flag.
- #8975 
=> Deprecate `durability_policy` flag in vtctld

go/vt/vtctl/vtctl.go
This PR brings the `vtctl`/`vtctlclient` `UpdateThrottlerConfig` client command behavior in line with the `vtctldclient` `UpdateThrottlerConfig` client command behavior as they are all now using the same RPC — the [`VtctldServer` `UpdateThrottlerConfig` gRPC call](https://github.com/vitessio/vitess/blob/main/proto/vtctlservice.proto#L133-L134) (implementation can be seen [here](https://github.com/vitessio/vitess/blob/8d99ddcd83ab21209d8ef86a9de666ab8c705b25/go/vt/vtctl/grpcvtctldserver/server.go#L1568-L1631)) — to ensure that the `Keyspace` record is properly updated and the changes get immediately propagated to the `SrvKeyspace` records.
Fixes https://github.com/vitessio/vitess/issues/12935
-   [x] Tests …
=> TabletThrottler: `vtctlclient UpdateThrottlerConfig` use VtctlServer RPC

go/mysql/datetime/parse.go, go/vt/vtgate/evalengine/cached_size.go, go/vt/vtgate/evalengine/compiler_asm.go, go/vt/vtgate/evalengine/compiler_test.go, go/vt/vtgate/evalengine/fn_time.go, go/vt/vtgate/evalengine/testcases/cases.go, go/vt/vtgate/evalengine/translate_builtin.go
This adds the `MAKEDATE` and `MAKETIME` functions. As always, this also uncovers some other small issues in how we parse things. This time it's that we don't allow the full range of valid values for hours when parsing the integer representation for a `time` type.
Follow up to https://github.com/vitessio/vitess/pull/12907 and part of https://github.com/vitessio/vitess/issues/9647
=> evalengine: Implement `MAKEDATE` and `MAKETIME`.

go/vt/topo/topoproto/shard.go, go/vt/topo/topoproto/shard_test.go
This code seems to be entirely unused and only referenced from tests. We can therefore safely clean this up.
=> topo: Remove unused templating code

changelog/16.0/16.0.0/release_notes.md, changelog/16.0/16.0.0/summary.md
This PR provides a better warning regarding the v16 upgrade: `VTGate Advertised MySQL Version is a breaking change for MySQL 5.7 users.`
Discussion on Slack: https://vitess.slack.com/archives/C0PQY0PTK/p1682067776047289
Follow up to https://github.com/vitessio/vitess/pull/11989
=> update v16 release notes about VTGate Advertised MySQL Version

.gitignore, go/vt/vtgate/planbuilder/operator_transformers.go, go/vt/vtgate/planbuilder/testdata/union_cases.json
This PR fixes a panic on pushing weight_string function on a join plan over a union operator for distinct planning.
- Fixes https://github.com/vitessio/vitess/issues/12969
=> fix: union distinct between unsharded route and sharded join

examples/operator/operator.yaml
This is a follow-up of the recent `2.7.5` vitess-operator release. This PR updates the example to use that newer version.
=> Use the newer `v2.7.5` vitess-operator version in the examples

go.mod, go.sum, go/vt/vtgr/ssl/ssl.go, go/vt/vtgr/ssl/ssl_test.go
While digging into something else, I ran into this code which seems entirely unused.
This cleanup also removes a bunch of deprecated APIs for encrypted PEM files which aren't very secure and custom certificate validation logic, so that's a double win.
=> vtgr: Remove unused code

go/vt/vttablet/endtoend/views_test.go
This PR adds cleanup query before start of `TestGetSchemaRPC` test. 
-
=> fix: deflake TestGetSchemaRPC test

go/flags/endtoend/vtgate.txt, go/test/endtoend/vtgate/grpc_server_acls/acls_test.go, go/test/endtoend/vtgate/grpc_server_auth_static/main_test.go, go/vt/vtgate/grpcvtgateservice/server.go, test/config.json
Fixes https://github.com/vitessio/vitess/issues/12970 
This PR adds a new flag grpc-use-static-authentication-callerid to gate the behavior introduced in https://github.com/vitessio/vitess/pull/12050
While I reviewed this PR, I didn't catch the issue where the username from static authentication context **would completely override the immediate callerID** for all `Execute` calls to vtgate. 
PlanetScale's usage of vtgate static auth and ACLs system is a bit unique in that we don't handle authentication for user queries in vtgate. We do that in our own query front-end service.
VTGate static authentication is configured for service-to-service authentication between the query front-end and vtgate, ACL system is configured to pass through user roles from our credential store to vtgate.
We do …
=> vtgate : Disable Automatically setting immediateCallerID to user from static authentication context 

go/vt/sqlparser/ast_funcs.go, go/vt/sqlparser/tracked_buffer.go, go/vt/vtgate/planbuilder/operators/SQL_builder.go, go/vt/vtgate/planbuilder/operators/apply_join.go, go/vt/vtgate/planbuilder/operators/derived.go, go/vt/vtgate/planbuilder/operators/horizon.go, go/vt/vtgate/planbuilder/operators/horizon_planning.go, go/vt/vtgate/planbuilder/operators/logical.go, go/vt/vtgate/planbuilder/operators/operator.go, go/vt/vtgate/planbuilder/operators/projection.go, go/vt/vtgate/planbuilder/testdata/from_cases.json, go/vt/vtgate/planbuilder/testdata/memory_sort_cases.json, go/vt/vtgate/planbuilder/testdata/select_cases.json, go/vt/vtgate/semantics/binder.go, go/vt/vtgate/semantics/derived_table.go, go/vt/vtgate/semantics/early_rewriter.go, go/vt/vtgate/semantics/real_table.go, go/vt/vtgate/semantics/semantic_state.go, go/vt/vtgate/semantics/table_collector.go, go/vt/vtgate/semantics/vindex_table.go, go/vt/vtgate/semantics/vtable.go
As part of the ongoing effort to improve the Vitess query planner and transition more planner logic to the operator model, this PR focuses on enhancing the handling of derived tables.
Previously, derived tables were only managed effectively if they could be pushed down under a Route. With this update, the query planner is now able to handle situations where derived tables need to be split into multiple operators under the Route. This improvement enables the queries sent to MySQL to more closely resemble the user's original query, retaining the derived table in the query being sent down.
By maintaining the derived table in the query, the result is easier for users to understand, as it better reflects their initial input. This enhancement aligns with the overall goal of simplifying the …
=> gen4 planner: Derived table handling on operators

go/vt/schemadiff/diff.go, go/vt/schemadiff/diff_test.go, go/vt/schemadiff/schema.go, go/vt/schemadiff/schema_diff.go, go/vt/schemadiff/schema_diff_test.go
More followup to https://github.com/vitessio/vitess/pull/12551 and https://github.com/vitessio/vitess/pull/12885. This PR further formalizes the use of `SchemaDiff`:
- The functions `DiffSchemas` and `DiffSchemasSQL` now return a `SchemaDiff` object rather than list of diffs
- Renamed various public dependency-related structs, functions, and constants to read `Dependency` rather than `Dep`, for improved clarity
- Added access function to `DiffDependency` (formerly `DiffDep`) so that external uses can investigate the dependency.
#10203 
=> `schemadiff`: better naming; formalizing `SchemaDiff` use.

go/test/endtoend/tabletmanager/throttler_custom_config/throttler_test.go
We have seen that the [`tabletmanager_throttler_custom_config` workflow](https://github.com/vitessio/vitess/blob/main/.github/workflows/cluster_endtoend_tabletmanager_throttler_custom_config.yml) has been somewhat flaky, with the seen failures revolving around what seem to be ephemeral 500 errors ([runs can be seen here](https://github.com/vitessio/vitess/actions/workflows/cluster_endtoend_tabletmanager_throttler_custom_config.yml)). 
All of the failures that I've seen were this ([example](https://github.com/vitessio/vitess/actions/runs/4791103225/jobs/8521102542)):
```
=== RUN   TestThrottlerThresholdOK/immediately
throttler_test.go:165: 
Error Trace:	/home/runner/work/vitess/vitess/go/test/endtoend/tabletmanager/throttler_custom_config/throttler_test.go:165
Error:      	Not equal: …
```
=> Flakes: Wait for throttler to open in throttler custom config test

go/test/endtoend/vreplication/vreplication_test.go, go/test/endtoend/vreplication/vreplication_test_env.go, go/test/endtoend/vreplication/vstream_test.go, go/vt/wrangler/traffic_switcher.go
There's a bug when resharding and switching traffic that makes it so it does not respect the `--dry_run` flag.
> **Note the `no locksInfo` error**
```bash
vtctlclient Reshard -- --tablet_types=rdonly,replica SwitchTraffic --dry_run customer.cust2cust
I0426 14:42:58.221613    9828 main.go:96] I0426 14:42:58.221425 traffic_switcher.go:399] About to switchShardReads: [], [RDONLY REPLICA], 0
E0426 14:42:58.223739    9828 main.go:96] E0426 14:42:58.223117 traffic_switcher.go:401] switchShardReads failed: Code: INVALID_ARGUMENT
keyspace customer is not locked (no locksInfo)
E0426 14:42:58.224562    9828 main.go:96] E0426 14:42:58.223567 vtctl.go:2264] 
keyspace customer is not locked (no locksInfo)
I0426 14:42:58.236510    9828 main.go:96] I0426 14:42:58.236337 vtctl.go:2266] Workflow Status: …
```
=> Fix bug in `SwitchTraffic` that wasn't respecting `--dry_run` for readonly and replica tablets during a resharding event

go/vt/vtgate/evalengine/api_hash_test.go, go/vt/vtgate/evalengine/eval.go
This was a likely copy-paste bug introduced in
https://github.com/vitessio/vitess/pull/12979/files#diff-4e6fe1f65ff81fe967668629b6d6b978309e3ad20ba5f81ae95612c98b7c3cfcR244
Instead of converting properly into a decimal, it was returning a float instance. This adds some additional test to ensure we catch this case and improves the random test generator to cover decimals too.
Broken in https://github.com/vitessio/vitess/pull/12979/files#diff-4e6fe1f65ff81fe967668629b6d6b978309e3ad20ba5f81ae95612c98b7c3cfcR244
=> evalengine: Fix wrong coercion into float

changelog/17.0/17.0.0/summary.md, go/vt/topo/keyspace.go, go/vt/topo/shard.go, go/vt/topo/validator.go, go/vt/topo/validator_test.go, go/vt/wrangler/tablet_test.go
Today we explicit disallow only specific characters like `/`. We should move here to an allow list approach though, explicitly allowing specific characters.
The reason is that a block list approach is bound to end up in a game of whack-a-mole where we keep having to add characters. Instead an allow list approach of safe characters is a fundamentally better method moving forward that provides security.
The biggest potential downside is that there's people we don't know about that are using names we would disallow with the current restrictions.
From a security perspective though, it's better that we start off here and then allow more known safe things if necessary and try to get feedback from the community for when things are too restricted.
Followup to …
=> topo: Move to allow list for invalid names

go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_init_test.go
This PR fixes the issue described in #12985 by keeping on retrying until we see a non-0 port in vttablet.
- Fixes #12985 
=> Keep retrying mysql port if it is 0 in Vttablets

go/vt/vttablet/tabletserver/throttle/throttler.go
This Pr adds much required log entries at key points of the tablet's lag throttler's operation; namely around `Open()`, `Enable()`, `Disable()` and a bit more. All of these entries are quiet, ie only log at startup/promotion/demotion/config update. These will not spam the logs.
-
=> Tablet throttler: adding log entries

go/mysql/sql_error.go, go/mysql/sql_error_test.go
This PR causes transactions throttled by the Transaction Throttler to return MySQL error code 1041 ER_OUT_OF_RESOURCES. This error code seems better suited to represent the fact that transactions
are being throttled by the server due to some form of resource contention than the current code 1203 ER_TOO_MANY_USER_CONNECTIONS.
https://github.com/vitessio/vitess/issues/12958
N/A
=> Throttled transactions return MySQL error code 1041 ER_OUT_OF_RESOURCES

go/timer/rate_limiter_test.go, go/vt/vttablet/tabletmanager/vreplication/vreplicator.go, go/vt/vttablet/tabletserver/vstreamer/rowstreamer.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
Fixes https://github.com/vitessio/vitess/issues/13012 reported by @arthurschreiber
This PR ensures to `defer r.Stop()` for all overlooked cases of  `RateLimiter`. Where possible, the rate limiter's scope was reduced to strictly necessary functions, as opposed to being creates in struct scope.
https://github.com/vitessio/vitess/issues/13012
=> Cleanup rate limiters

go/mysql/collations/charset/helpers.go, go/vt/vtgate/evalengine/cached_size.go, go/vt/vtgate/evalengine/compiler_asm.go, go/vt/vtgate/evalengine/expr_call.go, go/vt/vtgate/evalengine/fn_base64.go, go/vt/vtgate/evalengine/fn_string.go, go/vt/vtgate/evalengine/testcases/cases.go, go/vt/vtgate/evalengine/translate_builtin.go
This implements a bunch of additional string functions, namely `LEFT()`, `RIGHT()`, `LPAD()` and `RPAD()`.
As is a tradition by now, new functions also uncover other issues. This time it turns out it's the charset slice helper which doesn't actually honor the `from` parameter.
Nothing else was using anything but `0` for `from` so there was no externally observable bug anywhere yet, but with these functions we also use it with a non `0` `from`.
Part of #9647
=> evalengine: Implement LEFT, RIGHT, LPAD & RPAD

go/vt/sqlparser/goyacc/goyacc.go, go/vt/sqlparser/sql.go
Avoids importing "unsafe" (and emitting the `*Iaddr` helper function that uses it) if the `--fast-append` flag is not used. When this flag is not used, the `*Iaddr` helper function is never used. To maximize code portability (since there are some niche runtimes that do not support unsafe), we want to avoid the "unsafe" import if we can.
Fixes #13006 
I did some manual testing with a yacc grammar I have. The change excluded the import and the unused helper function as expected. When I added the `-f` flag, they were present (along with a …
=> goyacc: don't import "unsafe" if not used

examples/operator/operator.yaml
This is a follow-up of the recent [vitess-operator v2.8.4](https://github.com/planetscale/vitess-operator/releases/tag/v2.8.4) release. It updates the examples to use the proper version.
=> Use vitess-operator `v2.8.4` in the examples

go/vt/sqlparser/ast_format.go, go/vt/sqlparser/ast_format_fast.go, go/vt/sqlparser/sql.go, go/vt/sqlparser/sql.y, go/vt/vtgate/evalengine/cached_size.go, go/vt/vtgate/evalengine/compiler_asm.go, go/vt/vtgate/evalengine/fn_string.go, go/vt/vtgate/evalengine/testcases/cases.go, go/vt/vtgate/evalengine/testcases/inputs.go, go/vt/vtgate/evalengine/translate_builtin.go
Implements the `TRIM`, `RTRIM` and `LTRIM` functions in the evalengine.
Uncovers a small improvement to the parser where we should set the direction also if we see either `RTRIM` or `LTRIM` so we're consistent later with using it.
Part of #9647 
=> evalengine: Implement TRIM, RTRIM and LTRIM

go/vt/vttablet/tabletmanager/tm_init_test.go
This PR fixes the flakiness in the test `TestStartFindMysqlPort` by increasing the total wait time for reaching the final state to 5 seconds instead of 500 milliseconds.
=> Fix `TestStartFindMysqlPort` test flakiness

go/vt/vtgate/planbuilder/operators/merging.go, go/vt/vtgate/planbuilder/testdata/select_cases.json
In PR #12197, a refactoring error resulted in a bug causing the generation of invalid query plans under specific conditions.
While merging a subquery with the outer query, predicates from the subquery were not copied properly. This led to a partial merge where certain expressions were treated as unmergeable, creating an inconsistency. Consequently, invalid query plans were produced, resulting in the following error:
```query arguments missing for __sq1```
This PR resolves the issue and includes a test to prevent similar problems from occurring in the future.
-   [x] Documentation was …
=> gen4 planner bugfix: issue when merging subqueries

go/vt/vtgate/tabletgateway.go
If a primary is downed, you get the error `primary is not serving, there is a reparent operation in progress`, which in our case led to some debugging in a completely wrong direction because we thought there was a faulty reparent happening. While it's possible the primary isn't serving because of a reparent, it's not guaranteed to be because of a reparent, so this modifies the error wording to be a bit more clear
Fixes https://github.com/vitessio/vitess/issues/12605
=> fix misleading primary not serving message

go/vt/vttablet/tabletmanager/vreplication/controller_plan_test.go, go/vt/vttablet/tabletmanager/vreplication/utils.go
Interfacing with the `vreplication_log` table has not been working via the TabletManager's `VReplicationExec` RPC since the custom sidecar database work was added in: https://github.com/vitessio/vitess/pull/12240
If you tried to use the RPC you would get an error like this:
```
"rpc error: code = Unknown desc = TabletManager.VReplicationExec on zone1-0000000200 error: invalid table name: vreplication_log: invalid table name: vreplication_log"
```
This is because the database identifier is now stripped from the incoming table name and was then being compared to the const defined for the `vreplication_log` table name that still had the default database identifier in it. 
This PR corrects the issue and adds a unit test case for it.
- Fixes: https://github.com/vitessio/vitess/issues/13039
- …
=> Fix vreplication_log usage in VReplicationExec

go/vt/sqlparser/ast_rewriting.go, go/vt/vtgate/planbuilder/testdata/dml_cases.json, go/vt/vtgate/planbuilder/testdata/select_cases.json
We (incorrectly) decided to disallow `last_insert_id` some time ago, although it  was actually working and being used.
Fixed #13020
Backport of #13026
=> gen4 planner: allow last_insert_id with arguments (16.0)

go/vt/sqlparser/ast_rewriting.go, go/vt/vtgate/planbuilder/testdata/dml_cases.json, go/vt/vtgate/planbuilder/testdata/select_cases.json
We (incorrectly) decided to disallow `last_insert_id` some time ago, although it  was actually working and being used.
Fixed #13020
Backport of #13026
=> gen4 planner: allow last_insert_id with arguments (15.0)

go/vt/sqlparser/ast_rewriting.go, go/vt/vtgate/planbuilder/testdata/dml_cases.json, go/vt/vtgate/planbuilder/testdata/select_cases.json
We (incorrectly) decided to disallow `last_insert_id` some time ago, although it  was actually working and being used.
Fixed #13020
Backport of #13026
=> gen4 planner: allow last_insert_id with arguments (14.0)

.github/workflows/check_label.yml
We require a GitHub issue for all bug fixes, new features and enhancements. I have created a new label called `NeedsIssue` that reviewers can use to tag PRs without an issue.
This PR adds a check on that label to the `Check Pull Request labels` workflow to fail it if the `NeedsIssue` label is present.
=> CI: add a check on NeedsIssue label

.github/workflows/code_freeze.yml, changelog/16.0/16.0.2/summary.md, changelog/16.0/README.md
This PR makes summary file changes for release of v16.0.2 and implements code-freeze for the release of v16.0.2.
- #12879 
=> Summary changes and code freeze for release of v16.0.2

go/vt/vtgate/evalengine/arena.go, go/vt/vtgate/evalengine/cached_size.go, go/vt/vtgate/evalengine/compiler_asm.go, go/vt/vtgate/evalengine/compiler_test.go, go/vt/vtgate/evalengine/fn_hex.go, go/vt/vtgate/evalengine/testcases/cases.go, go/vt/vtgate/evalengine/translate_builtin.go
We already had `HEX`, but not `UNHEX`. This fixes the assymmetry.
Part of #9647
=> evalengine: Implement UNHEX

changelog/16.0/16.0.2/release_notes.md, changelog/16.0/16.0.2/summary.md
There was a format issue with the last line of the summary being missing. It was considered as a header in the `release_notes` file due to the `------------` at the end of the summary
=> Fix format error in the `v16.0.2` release notes

go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go, go/vt/schemadiff/diff_test.go
Fixes https://github.com/vitessio/vitess/issues/12336
There's an irregularity in timestamp comparison, and we're seeing what should have been a future timestamp, come before a past timestamp.
https://github.com/vitessio/vitess/pull/12826 was an attempt to fix the irregularity by ensuring all timestamp evaluations are done in `golang` space. But it did not solve the problem.
The irregularity is not very important to the `endtoend` test. It does not affect the throttler, or imply a throttler issue. It's a shame to fail the entire `endtoend` on that timestamp comparison.
In this PR we agree to tolerate a `1sec` deviation. It's not ideal, but we've been chasing this around for months now and it's not worth spending so much efforts, as, again, the particular timestamp comparison is an …
=> OnlineDDL endtoend/CI: timestamp deviation toleration

go/vt/vtgate/evalengine/cached_size.go, go/vt/vtgate/evalengine/compiler_asm.go, go/vt/vtgate/evalengine/compiler_test.go, go/vt/vtgate/evalengine/expr_collate.go, go/vt/vtgate/evalengine/expr_compare.go, go/vt/vtgate/evalengine/fn_string.go, go/vt/vtgate/evalengine/testcases/cases.go, go/vt/vtgate/evalengine/translate_builtin.go
This adds support for the `STRCMP` function to the evalengine. MySQL seems to handle numerics as a somewhat special case for how collation merging works, so this tries to mirror that based on the test results.
Part of #9647 
=> evalengine: Add support for `STRCMP`

go/vt/vtgate/evalengine/testcases/cases.go, go/vt/vtgate/evalengine/translate_builtin.go
Similar to how we handle `IFNULL` and `NULLIF`, we can also handle `IF` using a `CASE` internally in the evalengine.
This implements `IF` accordingly.
Part of #9647
=> evalengine: Add support for handling `IF`

.github/workflows/assign_milestone.yml, .github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml, .github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml, .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml, .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml
This is a follow-up of the golang version upgrade done by https://github.com/vitessio/vitess/pull/13053. The `next` upgrade test will now use the proper golang version.
=> Use `go1.20.4` on `release-15.0` upgrade test

go/vt/vtgate/evalengine/cached_size.go, go/vt/vtgate/evalengine/compiler_asm.go, go/vt/vtgate/evalengine/compiler_test.go, go/vt/vtgate/evalengine/expr_logical.go, go/vt/vtgate/evalengine/testcases/cases.go, go/vt/vtgate/evalengine/translate.go
This adds support for the `INTERVAL` function. Even though the official documentation describes that only a list of incrementing integers is supported, as a binary search is used, you can of course feed it many other values.
The changes here do support passing in unordered lists and behaves the same as MySQL here through reverse engineering with the tests. The implementation here does also use a binary search to match the MySQL behavior as well.
Part of #9647 
=> evalengine: `INTERVAL` support

go/test/endtoend/utils/utils.go, go/vt/srvtopo/query.go, go/vt/srvtopo/query_test.go
This PR fixes the bug described in https://github.com/vitessio/vitess/issues/13079. Earlier, in `resilientQuery`, if we saw that we don't need to refresh the local cache information, we would immediately return the cached value or an error. But, if the cache gets hammered with multiple queries when it starts up, the first query tries to refresh the cache, but the subsequent end up returning the cached result, which doesn't exist! (cache is starting up).
The fix implemented is to first verify that the cache is actually valid or not. If it isn't, then we wait for the previous refresh's output as well.
- Fixes https://github.com/vitessio/vitess/issues/13079
-   [x] …
=> Fix the resilientQuery to give correct results during initialization

go/vt/srvtopo/query.go, go/vt/srvtopo/query_test.go
=> [release-14.0] Fix the resilientQuery to give correct results during initialization (#13080)

go/cmd/vtcombo/main.go, go/test/endtoend/reparent/newfeaturetest/reparent_test.go, go/vt/mysqlctl/fakemysqldaemon.go, go/vt/mysqlctl/mysql_daemon.go, go/vt/mysqlctl/replication.go, go/vt/vterrors/code.go, go/vt/vttablet/tabletmanager/rpc_actions.go, go/vt/vttablet/tabletmanager/rpc_replication.go, go/vt/vttablet/tabletmanager/tm_init.go
Re-opening [my PR](https://github.com/vitessio/vitess/pull/12914) under my own account, as I no longer have access to the Shopify/Vitess repo after being impacted by their layoffs.
This PR also fixes the two failing checks in the original PR.
Fixes a bug where ChangeTabletType would fail on clusters that don't have rpl_semi_sync_master and rpl_semi_sync_slave plugins loaded. Does so by refactoring the convertBoolToSemiSyncAction method to return SemiSyncActionNone if the plugin is not loaded. To do this, we query the underlying mysql to check if the rpl_semi_sync_% variables are present.
This bug is only present from v15 onwards, so a backport might be in order to fix v15.
Fixes https://github.com/vitessio/vitess/issues/12869
-   [ ] "Backport to:" labels have been added if this change …
=> Fix: convertBoolToSemiSyncAction method to account for all semi sync actions

go/vt/vtgate/evalengine/cached_size.go, go/vt/vtgate/evalengine/compiler_asm.go, go/vt/vtgate/evalengine/eval.go, go/vt/vtgate/evalengine/eval_temporal.go, go/vt/vtgate/evalengine/fn_misc.go, go/vt/vtgate/evalengine/testcases/cases.go, go/vt/vtgate/evalengine/testcases/inputs.go, go/vt/vtgate/evalengine/translate_builtin.go
This adds `BIN_TO_UUID`, `IS_UUID`, `UUID` & `UUID_TO_BIN`. This doesn't implement `UUID_SHORT` though since that has specific requirements to use the `server_id` which is not something that conceptually makes sense for `vtgate` since it works across different backend MySQL servers.
So we avoid adding that here since there's no clear path for how to implement that.
Part of #9647
=> evalengine: Add UUID functions

go/vt/vttablet/tabletmanager/vreplication/framework_test.go
The `noblob` PR https://github.com/vitessio/vitess/pull/12905 has introduced a race during the unit race test. This is caused by the re-initialization of `globalDBQueries`, which we do because we run all tests twice: once for the full image and once for noblob. It turns out that the post-copy vcopier task, in `TestCancelledDeferSecondaryKeys` which runs in a goroutine, gets invoked when we cancel the context before the second set of tests. Since we immediately reinit the query queue, there is a race because the post-copy task is writing to the same query queue.
We will need to do a non-trivial refactor of the test framework before re-enabling the `noblob` variant. This PR temporarily disables them since the flakiness is blocking other PRs
https://github.com/vitessio/vitess/issues/13093
- …
=> Flaky vplayer tests: temporarily disable noblob variant

go/vt/sqlparser/truncate_query.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tabletserver_test.go
Vttablet has a flag:
```
--sql-max-length-errors int                                        truncate queries in error logs to the given length (default unlimited)
```
This flag is supposed to truncate queries that are logged, because logging a very long query can fill up disk space if the query is being logged frequently enough. There were a few logging callsites where we were not truncating the query.
- Fixes: https://github.com/vitessio/vitess/issues/13059
=> Optionally truncate queries that are written to logs

go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go, go/vt/vttablet/tabletserver/tabletserver_test.go
The tabletmanager's vreplication unit test framework relies heavily on globals for the test environment. I'm assuming this was done because the test environment is relatively heavy and costly to setup with actual mysqld's etc. The "right" way to do this would be to eliminate the usage of globals so that we could support parallelism and avoid data races — I explored that ([you can see the WiP patch here](https://gist.github.com/mattlord/fdb29007527461a49dcedf3b3051e718)) — but unfortunately it made each unit test take several orders of magnitude longer as now each one had to do a test env setup and teardown. I don't think that's workable given our current CI setup and resources, so I instead opted to a simpler approach that enforces one usage of the framework at a time with a mutex. …
=> Flakes: enforce no concurrency/parallelism in vreplication unit test framework

go/vt/vtgate/tabletgateway.go, go/vt/vtgate/tabletgateway_flaky_test.go
This PR fixes `TestGatewayBufferingWhileReparenting`, after we elect the replica as primary, we were directly checking if the new elected primary is serving. This led to flakiness, we now have a timeout of 1 minute to periodically check the state of the new elected primary.
=> Fix flakiness in `TestGatewayBufferingWhileReparenting`

go/vt/sqlparser/ast_funcs.go, go/vt/sqlparser/parse_test.go, go/vt/sqlparser/sql.go, go/vt/sqlparser/sql.y
We were incorrectly treating view names as case insensitive. Case sensitivity for views is similar as for tables, namely platform dependent by default but we always treat it as case sensitive in Vitess.
Fixes https://github.com/vitessio/vitess/issues/13105
=> sqlparser: Treat view names as case sensitive

go/flags/endtoend/vttablet.txt, go/vt/vttablet/tabletserver/schema/engine.go, go/vt/vttablet/tabletserver/schema/engine_test.go, go/vt/vttablet/tabletserver/schema/historian.go, go/vt/vttablet/tabletserver/schema/historian_test.go, go/vt/vttablet/tabletserver/schema/main_test.go, go/vt/vttablet/tabletserver/schema/tracker_test.go, go/vt/vttablet/tabletserver/tabletenv/config.go
This PR adds the ability for the vttablet to configure purging schema versions _in memory_ used in vreplication schema tracking older than a certain time. The motivation for this change was that for tablets with very large schemas and very frequent DDLs the tablet process would eventually OOM because of storing all of the old schema versions in memory.
> NOTE: This does **_not_** delete the schema version rows from the `_vt.schema_version` table in mysql, but only purges them from the vttablet process memory.
I added a `schema-version-max-age-seconds` vttablet flag that defaults to `0` (no purging) and can be set to purge schema versions older than the set number of seconds. There was an [attempt in the past](https://github.com/vitessio/vitess/pull/8617) to limit the max number of schemas …
=> Purge old schema versions from memory in historian

go/vt/vtgate/vstream_manager.go, go/vt/vtgate/vstream_manager_test.go
Add vstream metrics (number of vstreams, vstream lag) for vtgate.
PR to update docs: https://github.com/vitessio/website/pull/1473
Fixes https://github.com/vitessio/vitess/issues/13099
=> Add vstream metrics to vtgate

go/mysql/flavor.go, go/mysql/flavor_filepos.go, go/mysql/flavor_mariadb_binlog_playback.go, go/mysql/flavor_mysql.go, go/vt/mysqlctl/fakemysqldaemon.go, go/vt/mysqlctl/mysql_daemon.go, go/vt/mysqlctl/replication.go, go/vt/vttablet/tabletmanager/vreplication/controller.go, go/vt/vttablet/tabletmanager/vreplication/engine.go
These haven't been used for a while so afaik we can clean these up now to reduce the size of both the `mysqldaemon` and `flavor` interfaces, reducing coupling.
=> mysqlctl: Remove custom callbacks

go/vt/vtgate/planbuilder/plan_test.go
The `BenchmarkOLTP`, `BenchmarkTPCC`, `BenchmarkTPCH` benchmark tests were failing because the vschema path was incorrect, this PR fixes it.
=> Fix benchmarks in `plan_test.go`

changelog/17.0/17.0.0/summary.md, go/mysql/endtoend/main_test.go, go/test/endtoend/mysqlctl/mysqlctl_test.go, go/test/endtoend/mysqlctld/mysqlctld_test.go, go/test/endtoend/vreplication/cluster_test.go, go/vt/mysqlctl/mysqld.go, go/vt/mysqlctl/mysqld_test.go, go/vt/vttest/environment.go
After the changes in https://github.com/vitessio/vitess/pull/13123, I realized that there's no cases left where we actually use or depend on `MYSQL_FLAVOR`.
This means we can actually remove usages of `MYSQL_FLAVOR`. It doesn't yet remove it from the artifacts we build, because we shouldn't clean that up until v18 then because users might mix versions during the upgrade and we don't want to have old code that still depends on this fail then.
Follow up to https://github.com/vitessio/vitess/pull/13123
=> mysqlctl: Remove usage of MYSQL_FLAVOR

changelog/17.0/17.0.0/summary.md, config/tablet/default.yaml, doc/design-docs/TabletServerParamsAsYAML.md, go/vt/vttablet/tabletserver/tabletenv/config.go, go/vt/vttablet/tabletserver/tabletenv/config_test.go, go/vt/vttest/vtprocess.go
The `enable-query-plan-field-caching` flag was deprecated in v15 in https://github.com/vitessio/vitess/commit/fb9e17864a0fc72976356456057f2a9ae20689e1. This was [noted in the release notes, along with our intention to remove it in v16](https://github.com/vitessio/vitess/blob/main/changelog/15.0/15.0.0/release_notes.md#vttablet-startup-flag-deprecations). We missed deleting it in v16, so doing it for v17.
- Follow-up to: https://github.com/vitessio/vitess/pull/11501
- https://github.com/vitessio/vitess/pull/10489
-   [x] Documentation was added or is not required (I could not find any …
=> Remove enable-query-plan-field-caching flag that was deprecated in v15

go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go, go/vt/vttablet/tabletserver/vstreamer/testenv/testenv.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer_flaky_test.go
This PR only adds unit tests to vstreamer, vcopier and vplayer to illustrate how generated invisible private keys are used in vreplication workflows.
`MoveTables` will retain the GIPK on the table in the target keyspace. However, while that works when the target keyspace is unsharded, for sharded keyspaces we would use [sequences](https://vitess.io/docs/15.0/reference/features/vitess-sequences/) instead. This is similar to how we would deal with regular autoincrement Primary Keys in Vitess. 
When the source table has a GIPK, the schema of the sharded target table will have to define `my_row_id` as the column name for the PK column, in line with MySQL's internal implementation.
Reference: https://dev.mysql.com/doc/refman/8.0/en/create-table-gipks.html
-   [ ] "Backport to:" labels have …
=> Generated Invisible Primary Keys: add vreplication test cases 

go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/workflow_test.go
When the _target keyspace is unsharded_ VReplication creates empty vschema table entries in the target keyspace for tables that it's moving from one keyspace to another (`MoveTables` or `Migrate`). It makes sense to also delete those entries it created if the workflow is subsequently [`Cancel`](https://vitess.io/docs/17.0/reference/vreplication/movetables/#cancel)ed.
However, for _sharded target keyspaces_ the vschema must be created by the user before the workflow is created — as VReplication cannot know the proper vindex definitions to use — so the vschema is managed by the user outside of the workflow. So for sharded target keyspaces we should also _NOT_ be deleting the those vschema table entries when the workflow is [`Cancel`](https://vitess.io/docs/17.0/reference/vreplication/movetab …
=> VReplication: Do not delete sharded target vschema table entries on Cancel

go/vt/vtgate/planbuilder/testdata/reference_cases.json, go/vt/vtgate/planbuilder/testdata/show_cases.json, go/vt/vtgate/planbuilder/testdata/vschemas/schema.json, go/vt/vtgate/vindexes/vschema.go, go/vt/vtgate/vindexes/vschema_test.go
Allow reference tables to specify unqualified (a.k.a. global tables) as their source.
With the changes in this PR, this is now valid:
```json
{
"ks1": {
"tables": {
"t1": {}
}
},
"ks2": {
"tables": {
"t1": {
"type": "reference",
"source": "t1"
}
}
},
}
```
Existing restrictions still apply:
* Referenced table must be resolvable, if the global table is ambiguous, the reference table is invalid.
* Referenced table must actually exist in the VSchema.
* May not be a self-reference.
* #11864
-   [x] Documentation was added: https://github.com/vitessio/website/pull/1457
=> planner: allow reference tables to specify global sources

go/vt/sqlparser/parse_test.go, go/vt/sqlparser/sql.go, go/vt/sqlparser/sql.y, go/vt/sqlparser/token.go
This PR removes the indentation limit of `200` which was introduced 8 years ago in https://github.com/vitessio/vitess/pull/845. The original reason for this limit was to prevent stack overflow, however, there is little chance to reach stack overflow. There are already a lot of possibilities to OOM the VTGate by sending weird queries.
cc @arthurschreiber @GuptaManan100 
Fixes: https://github.com/vitessio/vitess/issues/13159
=> Remove the `200` indentation limit in the SQL parser

go/test/endtoend/vreplication/config_test.go, go/test/endtoend/vreplication/initial_data_test.go, go/test/endtoend/vreplication/vreplication_test.go, go/test/endtoend/vreplication/vreplication_test_env.go, go/vt/mysqlctl/mysqld.go
VReplication  MoveTables workflows which contain a table name or a column which has special characters (like `ö` or `ü`) are currently failing. While tracking down the issue it turned out that the target table/column names are being generated with incorrect character mappings. 
VReplication uses the `tabletmanager`s `ApplySchema` RPC to copy over the schemas from the source to the target. 
It turns out that `ApplySchema` executes the actual ddl  using the mysql CLI in the `mysqlctl` package!!  It is not clear why we are following this approach instead of directly creating it in the tablet like how `OnlineDDL` does it, for example: this code was added way back ~2016. It is possible this is legacy and can be refactored out.
This PR sets the default character set in the extra config that is …
=> ApplySchema vttablet RPC: allow special characters in table and column names

changelog/17.0/17.0.0/summary.md
This PR reorders the deprecated flags from different sections under one header.
This could help readers to know all the deprecated flags under one section.
=> consolidate all deprecated flags under one header in release notes

go/test/endtoend/utils/utils.go, go/test/endtoend/vtgate/queries/orderby/orderby_test.go
New tests have been added in `main` that we try to run against older versions of `vtgate`, and these tests fail.
This change will stop said tests from running on older versions of vtgate.
Faulty tests added in: #12994
=> tests: stop tests not supported by older versions from running

go/viperutil/internal/sync/sync_test.go
`TestPersistConfig` is very flaky at the moment. Skipping temporarily to unblock CI.
=> Flakes: Skip flaky viperutil test TestPersistConfig for now to unblock CI

go/test/endtoend/vreplication/vreplication_test.go, go/vt/vtctl/vtctl.go
VReplication vtctl client workflow commands such as [`MoveTables`](https://vitess.io/docs/reference/vreplication/movetables/) and [`Reshard`](https://vitess.io/docs/reference/vreplication/reshard/) take a [`--keep_routing_rules`](https://vitess.io/docs/reference/vreplication/movetables/#--keep_routing_rules) flag. This flag's value, however, was NOT passed on to the command execution for the [`Cancel`](https://vitess.io/docs/reference/vreplication/movetables/#cancel) action. This PR corrects that and adds endtoend testing for it in the existing `TestVReplicationDDLHandling` test since that does a lot of `Cancel`s.
Manual test:
```sh
git checkout main && make build
cd examples/local
./101_initial_cluster.sh; mysql < ../common/insert_commerce_data.sql; ./201_customer_tablets.sh
vtctlclient …
```
=> VReplication: Pass on --keep_routing_rules flag value for Cancel action

go/test/endtoend/vtgate/partialfailure/main_test.go, go/vt/vttablet/grpcqueryservice/server.go
This PR fixes the issue with `ReserveBeginExecute` to return transaction ID on error. 
Without this fix, the transaction was lost and was only cleared by the transaction killer.
There is a separate PR for main: https://github.com/vitessio/vitess/pull/13127
- Fixes https://github.com/vitessio/vitess/issues/13192
-   [x] "Backport to:" labels have been added if this change should be back-ported 15.0
=> [16.0] Fix: TabletServer ReserveBeginExecute to return transaction ID on error

go/vt/mysqlctl/backupengine.go, go/vt/mysqlctl/builtinbackupengine.go, go/vt/mysqlctl/builtinbackupengine_test.go
Found a silly bug (in code I wrote) where the `Destination:Close` and `Source:Close` stats are being reported multiple times. Removing the duplications and adding a test.
Fixes #12946 
=> go/vt/mysqlctl: fix dup open/close backup stats

examples/operator/101_initial_cluster.yaml, examples/operator/201_customer_tablets.yaml, examples/operator/302_new_shards.yaml, examples/operator/306_down_shard_0.yaml
Current k8s resources for the operator example aren't enough in the current version. See more details here: https://github.com/vitessio/vitess/issues/13118
This PR is related: https://github.com/vitessio/website/pull/1477
N/A
=> Upgrade mysqld memory limits to 1024Mi

go/mysql/fakesqldb/server.go, go/vt/vttablet/tabletserver/health_streamer.go, go/vt/vttablet/tabletserver/health_streamer_test.go, go/vt/vttablet/tabletserver/state_manager.go
This PR fixes the health streamer issue described in https://github.com/vitessio/vitess/issues/13182. This is a partial back port of https://github.com/vitessio/vitess/pull/13121/
- #13182 
=> Fix: errant GTID in health streamer

go/vt/vtgate/planbuilder/testdata/dml_cases.json, go/vt/vtgate/planbuilder/testdata/select_cases.json, go/vt/vtgate/planbuilder/testdata/vschemas/schema.json, go/vt/vtgate/vindexes/lookup_unicodeloosemd5_hash.go
https://github.com/vitessio/vitess/pull/10490 externalized a lot of the logic of lookup vindexes, so that Gen4 planner can ask lookup vindexes "how should I perform the lookup query?", and then runs the query. This works for other lookup vindexes, but doesn't appear to take into account the internal hashing logic of the `lookup_unicodeloosemd5_hash`  vindexes. 
https://github.com/vitessio/vitess/blob/090ca9597e0cf88646af1fc47865120ac1f491e1/go/vt/vtgate/vindexes/lookup_unicodeloosemd5_hash.go#L127-L131
I think what would need to happen for those vindexes to properly implement `LookupPlannable` is to expose a method like `ConvertIDs` which the planner could use to convert IDs before binding them to the result of `Query()`.
That might be more effort than it is worth. Since these vindexes …
=> vindexes: make lookup_unicodeloosemd5_hash non-planable

go/vt/mysqlctl/mysqld.go
The change in #13123 will cause `MoveTables` workflows to panic in certain cases because they use the mysql CLI directly to create the schema of new tables on the target.
The real fix is at https://github.com/vitessio/vitess/pull/13178. However that has exposed a race where vttablets don't always find the newly created tables. To move forward with the v17 RC1 release we comment out the panic until we find a proper solution for this.
Temporary fix for https://github.com/vitessio/vitess/issues/13203
Also:
#13123 
#13178
=> Temporarily disable panic in mysqld when socket files are directly used

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/test/endtoend/vtgate/queries/aggregation/distinct_test.go, go/vt/vtgate/planbuilder/operator_transformers.go, go/vt/vtgate/planbuilder/operators/aggregation_pushing.go, go/vt/vtgate/planbuilder/operators/aggregator.go, go/vt/vtgate/planbuilder/operators/distinct.go, go/vt/vtgate/planbuilder/operators/horizon_planning.go, go/vt/vtgate/planbuilder/operators/projection.go, go/vt/vtgate/planbuilder/operators/queryprojection.go, go/vt/vtgate/planbuilder/operators/route.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.json, go/vt/vtgate/planbuilder/testdata/oltp_cases.json, go/vt/vtgate/planbuilder/testdata/postprocess_cases.json, go/vt/vtgate/planbuilder/testdata/unsupported_cases.json
Plans DISTINCT queries using the new operator model. This enables a couple of queries that before could not be planned by Vitess. 
If we can push down the DISTINCT to a single shard route, we're done. If not, we instead turn the query into a GROUP BY query. Semantically equivalent, but uses the aggregation planning to achieve distinct results.
Tracking issue: https://github.com/vitessio/vitess/issues/11626
=> Handle DISTINCT with the new operators

go/vt/servenv/version.go, java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/jdbc/pom.xml, java/pom.xml
With the creation of the release-17.0 branch main now becomes 18.0.0-SNAPSHOT.
- https://github.com/vitessio/vitess/issues/13138
=> Bump the vitess version on main

go/viperutil/config.go
Makes the error message (for `WARN` _only_ ) indicate optionality and provide additional resources.
#11456 
=> gentler warning message on config-not-found

go/vt/vtgate/evalengine/expr_column_test.go, go/vt/vtgate/evalengine/expressions.go
While working on other parts of Vitess, we noticed this issue. Difficult to show the bug using end to end tests, but the unit test should show the behaviour we want.
Issue: #13149
Backport of: #13148
=> [16.0] evalengine: TypeOf for Columns should only use value type when we have a value

Makefile, go/flags/endtoend/mysqlctl.txt, go/flags/endtoend/mysqlctld.txt, go/flags/endtoend/vtaclcheck.txt, go/flags/endtoend/vtbackup.txt, go/flags/endtoend/vtctlclient.txt, go/flags/endtoend/vtctld.txt, go/flags/endtoend/vtexplain.txt, go/flags/endtoend/vtgate.txt, go/flags/endtoend/vtgr.txt, go/flags/endtoend/vtorc.txt, go/flags/endtoend/vttablet.txt, go/flags/endtoend/vttestserver.txt, go/flags/endtoend/zkctl.txt, go/flags/endtoend/zkctld.txt, tools/generate_flag_testdata.sh
#11456 required us to templatize the flag help text, to handle the `$pwd` default for config-paths, which then requires us to escape the literal template string for `tablet_url_template`
This makes doing a quick one-liner to update the testdata annoying/cumbersome, so I'm including a handy script and corresponding `make` target to do it for us consistently.
#11456 
=> [ci] add generator for templated flag testdata

changelog/17.0/17.0.0/summary.md, go/flags/endtoend/vttablet.txt, go/test/endtoend/onlineddl/ghost/onlineddl_ghost_test.go, go/test/endtoend/onlineddl/revert/onlineddl_revert_test.go, go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go, go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go, go/test/endtoend/onlineddl/vrepl_stress/onlineddl_vrepl_mini_stress_test.go, go/test/endtoend/onlineddl/vrepl_stress_suite/onlineddl_vrepl_stress_suite_test.go, go/test/endtoend/onlineddl/vrepl_suite/onlineddl_vrepl_suite_test.go, go/test/endtoend/schemadiff/vrepl/schemadiff_vrepl_suite_test.go, go/test/endtoend/tabletmanager/tablegc/tablegc_test.go, go/test/endtoend/tabletmanager/throttler/throttler_test.go, go/test/endtoend/tabletmanager/throttler_custom_config/throttler_test.go, go/test/endtoend/tabletmanager/throttler_topo/throttler_test.go, go/test/endtoend/throttler/util.go, go/test/endtoend/vreplication/cluster_test.go, go/test/endtoend/vreplication/resharding_workflows_v2_test.go, go/vt/srvtopo/watch.go, go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/throttle/throttler.go
Backport of https://github.com/vitessio/vitess/pull/13130
---
- `v16` introduced a new `vttablet` flag: `--throttler-config-via-topo`, see the docs: https://vitess.io/docs/16.0/reference/features/tablet-throttler/
- In `v16` this flag defaults `false`, and the old per-tablet `--enable-lag-throttler` configuration is still supported.
- For `v17`, **the target of this PR**, this PR sets the default for `--throttler-config-via-topo` to `true`. The old configuration is still supported but if used there's a deprecation warning.
- In `v18`, the old configuration & logic will be compeletely removed and it will be assumed that `--throttler-config-via-topo` is always `true` whether specified or not. The flag will issue a deprecation message.
- In `v19` we will remove the flag …
=> Backport #13130: Tablet throttler: throttler-config-via-topo defaults 'true', deprecation message for old flags

go/vt/wrangler/materializer.go, go/vt/wrangler/materializer_test.go
When moving or resharding tables to an _unsharded keyspace_, we currently blindly create empty vschema table entires in the target keyspace. For most cases that's fine, but there are certain kinds of tables that contain additional attributes -- e.g. `type` for sequence or reference tables. Currently you lose that important information and have to manually recreate it yourself.
In this PR we change the behavior so that for _unsharded targets_ we copy the source vschema table entry over _if there's not already one defined_ on the target. In the case of Migrate, where we don't have direct access to the source vschema, we continue to create an empty vschema table entry but _only if the target does not already have one defined_.
- Fixes: https://github.com/vitessio/vitess/issues/13217
- Fixes: …
=> VReplication: More intelligently manage vschema table entries on unsharded targets

.github/workflows/cluster_endtoend_backup_pitr.yml, .github/workflows/cluster_endtoend_backup_pitr_mysql57.yml, go/test/endtoend/backup/pitr/backup_mysqlctld_pitr_test.go, go/test/endtoend/backup/vtctlbackup/backup_utils.go, go/vt/mysqlctl/backup.go, go/vt/mysqlctl/backupengine.go, go/vt/mysqlctl/binlogs_gtid.go, go/vt/mysqlctl/binlogs_gtid_test.go, go/vt/mysqlctl/builtinbackupengine.go, go/vt/mysqlctl/fakemysqldaemon.go, go/vt/mysqlctl/mysqld.go, go/vt/mysqlctl/xtrabackupengine.go, go/vt/wrangler/testlib/backup_test.go, test/ci_workflow_gen.go
Followup to https://github.com/vitessio/vitess/pull/11097
This PR supports incremental backup and point in time recoveries for backups using `--backup_engine_implementation=xtrabackup`.
Incremental backup is still done by copying `mysqlbinlog` files (thus we do not use `XtraBackup`'s incremental backup method of copying InnoDB pages). Point in time recovery is likewise done by replaing binary log files.
In fact, incremental backup and PITR are done using the `BuiltIn` backup&restore engine. So, for example, if you're running a point in time recovery using `xtrabackup`, the full backup is restored via `xtrabackup` engine, but then the binlog files are replayed by `builtin` engine.
Best reviewed [with spaces ignored](https://github.com/vitessio/vitess/pull/13156/files?w=1).
To be …
=> Incremental backup and point in time recovery for XtraBackup 

go/test/endtoend/vtgate/transaction/single/main_test.go, go/test/endtoend/vtgate/transaction/single/schema.sql, go/test/endtoend/vtgate/transaction/single/vschema.json, go/vt/vtgate/engine/route.go
This PR fixes an issue with `GetField` primitive function to retrieve the Field Information using the available/existing shard session.
When VTGate has `transaction_mode = single` then if VTGate opens `two or more` shard sessions it believes that the transaction has gone `multi-shard` and VTGate implicitly rolls back the transaction.
- Fixes https://github.com/vitessio/vitess/issues/13214
-   [x] "Backport to:" labels have been added if this change should be back-ported 17.0
=> fix: GetField to use existing session for query

.github/workflows/update_golang_version.yml
This PR removes the file `out.txt` and makes sure it will no longer be created.
This PR also adds the `release-17.0` branch to the golang upgrade automation tool.
=> Remove `out.txt` and add `release-17.0` to go upgrade automation

go/test/endtoend/cluster/cluster_util.go, go/test/endtoend/cluster/vtctlclient_process.go, go/test/endtoend/reparent/utils/utils.go
This PR implements proper filtering of the warning for `vtctlclient`. We will now remove the error produced by a missing or incorrect `vtconfig` on `release-17.0` and above. This is useful to make the upgrade downgrade test pass.
=> Fix new vtctl upgrade downgrade test on `release-16.0`

go/test/endtoend/cluster/cluster_process.go, go/test/endtoend/utils/utils.go, go/test/endtoend/vtgate/gen4/gen4_test.go, go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/test/endtoend/vtgate/queries/aggregation/distinct_test.go, go/test/endtoend/vtgate/queries/foundrows/found_rows_test.go, go/vt/vtgate/endtoend/last_insert_id_test.go, go/vt/vtgate/endtoend/main_test.go, go/vt/vtgate/endtoend/schema.sql, go/vt/vtgate/engine/cached_size.go, go/vt/vtgate/engine/distinct.go, go/vt/vtgate/engine/distinct_test.go, go/vt/vtgate/engine/ordered_aggregate.go, go/vt/vtgate/engine/ordered_aggregate_test.go, go/vt/vtgate/engine/scalar_aggregation.go, go/vt/vtgate/planbuilder/aggregation_pushing.go, go/vt/vtgate/planbuilder/distinct.go, go/vt/vtgate/planbuilder/operator_transformers.go, go/vt/vtgate/planbuilder/operators/aggregation_pushing.go, go/vt/vtgate/planbuilder/operators/aggregator.go, go/vt/vtgate/planbuilder/operators/distinct.go, go/vt/vtgate/planbuilder/operators/horizon_planning.go, go/vt/vtgate/planbuilder/operators/projection.go, go/vt/vtgate/planbuilder/operators/queryprojection.go, go/vt/vtgate/planbuilder/ordered_aggregate.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.json, go/vt/vtgate/planbuilder/testdata/postprocess_cases.json, go/vt/vtgate/planbuilder/testdata/tpch_cases.json, go/vt/vtgate/planbuilder/testdata/unsupported_cases.json, go/vt/vttest/local_cluster.go
This PR makes multiple aggregation planning improvements and fixes some subtle bugs.
1. When we can't push down aggregation, instead we'll now push down the arguments to the aggregation function and then do all of the grouping and aggregating on the vtgate. Before this change, the planner would just fail instead.
2. The DISTINCT operator was only stripping out `weight_string`, and could sometimes return too many columns.
4. Handle SUM with the new operator horizon planning 
5. Refactored how collation information is shared between the planner and runtime 
6. Fix the issue with mixed aggregation and columns in the select expression list.
- https://github.com/vitessio/vitess/issues/11626
-   [X] Tests were …
=> Fix and Make aggregation planner handle aggregation functions better

.github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml, .github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml, .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml, .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml
This PR is a follow up of https://github.com/vitessio/vitess/pull/13257. We are bumping the Golang version to `go1.20.5` on `release-16.0`, we need to make sure the `next`/`new` upgrade downgrade tests are running on the same golang version.
=> [release-15.0] Update Upgrade/Downgrade tests to use `go1.20.5`

Makefile, doc/internal/ReleaseInstructions.md, go/tools/release-notes/release_notes.go
In the previous RC1 release, @mattlord encountered an issue where the release note generation was hitting a request limit error from the GitHub's API. This was due to the high number of concurrency. From now on, we can directly modify the concurrency level using a flag, without having to modify the codebase.
=> Set the number of threads for release notes generation with a flag

go/test/endtoend/vreplication/vdiff2_test.go, go/test/endtoend/vreplication/vdiff_helper_test.go, go/vt/vttablet/tabletmanager/vdiff/action_test.go, go/vt/vttablet/tabletmanager/vdiff/schema.go
The [query used](https://github.com/vitessio/vitess/blob/7aee0635b1c2ba5ff7211e6d36f1ea2c80d99f72/go/vt/vttablet/tabletmanager/vdiff/schema.go#L33-L34) was incorrect and thus deleting every row in the vdiff table. IIRC, this was a mistake on my part as I was first using a WHERE based query and then had to move to LEFT JOIN usage as there may not always be vdiff_table records. When doing so, however, I left the last AND clause in place when it should have become the sole predicate in a new WHERE clause after the LEFT JOIN condition.
>**Note**: I also took the opportunity to move the test file that I modified from using jsonparser to gjson as gjson is generally much nicer and I'd like to move to that everywhere over time.
- Fixes: https://github.com/vitessio/vitess/issues/13253
-   [x] …
=> VReplication: Fix VDiff2 DeleteByUUID Query

go/vt/sidecardb/schema/misc/reparent_journal.sql
`primary_alias` column is now of length 255, increased from previous length of 32.
I also changed `action_name` to 255, just for consistency. 
Fixes #13286
=> increase length of reparent_journal columns

changelog/17.0/17.0.0/release_notes.md, changelog/17.0/17.0.0/summary.md, go/vt/topo/server.go
Include a deprecation warning for Vitess 17.
Part of #13298 
=> k8stopo: Include deprecation warning

go/vt/sidecardb/sidecardb.go
This PR adds a comment and does a minor refactor for code added in https://github.com/vitessio/vitess/pull/13197.
#12967 
=> Refactor and add a comment to schema initialisation code

go/vt/mysqlctl/schema.go, go/vt/mysqlctl/schema_test.go
These need to be escaped as SQL strings for queries against the `information_schema` or otherwise any names that need quotes will break.
Fixes #13311
=> mysqlctl: Correctly encode database and table names

go/vt/vtgate/planbuilder/operators/aggregation_pushing.go, go/vt/vtgate/planbuilder/operators/aggregator.go, go/vt/vtgate/planbuilder/operators/filter.go, go/vt/vtgate/planbuilder/operators/horizon_expanding.go, go/vt/vtgate/planbuilder/operators/horizon_phases.go, go/vt/vtgate/planbuilder/operators/horizon_planning.go, go/vt/vtgate/planbuilder/operators/offset_planning.go, go/vt/vtgate/planbuilder/operators/phases.go, go/vt/vtgate/planbuilder/operators/projection.go, go/vt/vtgate/planbuilder/plancontext/planning_context.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.json, go/vt/vtgate/planbuilder/testdata/filter_cases.json, go/vt/vtgate/planbuilder/testdata/postprocess_cases.json, go/vt/vtgate/planbuilder/testdata/tpch_cases.json, go/vt/vtgate/planbuilder/testdata/unsupported_cases.json
Adds support for HAVING planning
In order to support HAVING in a clean way, I had to introduce more phases in the planner.
The current phases are:
- Join ordering (route_planning)
- PushOrExpand horizons, and push down everything we can, except aggregations
- Add columns missing from Filter
- Add ordering before aggregations running on the vtgate
- Add group by on the RHS of join to get empty results correctly
Depends on https://github.com/vitessio/vitess/pull/13294
Tracking issue https://github.com/vitessio/vitess/issues/11626
=> vtgate planner: HAVING in the new operator horizon planner

go/test/endtoend/vtorc/api/api_test.go, go/vt/vtorc/inst/instance_dao.go
This PR adds a new metric to VTOrc that shows the errant GTIDs detected by VTOrc. The metric looks like the following - 
```
"ErrantGtidMap": {"zone1-0000000100": "b06fd52a-09b4-11ee-8d3b-5677533821fe:1", "zone1-0000000101": "", "zone1-0000000102": ""},
```
- Fixes #13307 
=> Add metric for showing the errant GTIDs in VTOrc

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/operators/horizon_expanding.go, go/vt/vtgate/planbuilder/operators/queryprojection.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.json, go/vt/vtgate/planbuilder/testdata/tpch_cases.json, go/vt/vtgate/planbuilder/testdata/unsupported_cases.json
This PR adds support for complex aggregation in the operators, for instance:
```sql
SELECT MAX(id)+COUNT(*)/1*SUM(t) FROM user;
```
=> Support complex aggregation in Gen4's Operators

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/test/endtoend/vtgate/queries/aggregation/schema.sql, go/test/endtoend/vtgate/queries/aggregation/vschema.json, go/vt/vtgate/engine/scalar_aggregation.go
This PR fixes a bug in certain SQL queries, for example:
`select /*vt+ PLANNER=Gen4 */ tbl0.comm, count(*) from emp as tbl0, emp as tbl1 where tbl0.empno = tbl1.deptno`
With `only_full_group_by` disabled and a non-grouping column selected, Vitess will sometimes error with the message `unknown aggregation random`.
This was found with automated query fuzzing (#13279)
=> Bug fix: SQL queries erroring with message `unknown aggregation random`

go/vt/mysqlctl/schema.go
This was using the command line but we can use a proper mysql connection here. Follow up to #13054 where this was identified.
Identified in #13054
=> mysqlctl: Use DBA connection for schema operations

go/vt/vttablet/tabletmanager/vdiff/action.go, go/vt/vttablet/tabletmanager/vdiff/controller.go, go/vt/vttablet/tabletmanager/vdiff/engine.go, go/vt/vttablet/tabletmanager/vdiff/schema.go, go/vt/vttablet/tabletmanager/vdiff/table_differ.go, go/vt/vttablet/tabletmanager/vdiff/workflow_differ.go
This is some internal cleanup work that I have been wanting to do. I moved all `fmt.Sprintf` usage in building dynamic queries in VDiff2 to using the `sqlparser` instead. This way we are handling inputs and validation in a safer, more robust way.
=> Use sqlparser for all dynamic query building in VDiff2

go/test/endtoend/vreplication/vreplication_test.go, go/vt/vttablet/tabletserver/vstreamer/engine_test.go, test/config.json
The `TestVStreamerWaitForMySQL` e2e test [added in #PR9923](https://github.com/vitessio/vitess/pull/9923) has become flaky again recently. This PR addresses this by removing the endtoend test entirely as:
1. We have unit test coverage for it
2. It's a pretty simple feature and related behavior
I also made some minor improvements to the comments and unit test.
=> Flakes: Remove CI endtoend test for VReplication Copy Phase Throttling

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/test/endtoend/vtgate/queries/misc/misc_test.go, go/vt/vtgate/engine/filter.go, go/vt/vtgate/engine/projection.go, go/vt/vtgate/planbuilder/operators/joins.go, go/vt/vtgate/planbuilder/testdata/from_cases.json
Fixes three one-line issues.
1. Join predicates on outer joins that only depend on the RHS of the join turns join into an inner join
2. Projection not handling types correctly would fail some aggregation queries
3. Filter checking if values are `1` instead of using MySQLs coercion to bool
This was found with automated query fuzzing (https://github.com/vitessio/vitess/issues/13279)
=> bugfixes: collection of fixes to bugs found while fuzzing

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/vt/vtgate/planbuilder/operators/aggregation_pushing.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.json
Some aggregations on the outer side of an outer join would fail, returning the wrong results.
Example query:
```sql
SELECT count(t2.shardkey) 
FROM t1 LEFT JOIN t2 ON t1.t1_id = t2.id
```
When pushing down aggregation to the outer side of a query, we should not always wrap the RHS expression in `COALESCE`.
Found with https://github.com/vitessio/vitess/pull/13260
=> bug: don't always wrap aggregation in coalesce

go/vt/mysqlctl/mysqld.go, go/vt/mysqlctl/schema.go
`executeMysqlScript` was still using a `mysql` client binary for initialization, but there's no reason it needs to do that. We can also move this to our built in MySQL client to be faster and have less dependencies here.
This essentially reverts back `executeSchemaCommands` to what it was before and pushes down the change to use the direction connection into `executeMysqlScript` instead, removing the dependency on the `mysql` CLI client entirely. 
Follow up to #13178 where we already moved things for just the schema commands.
=> mysqlctl: Move more to use built in MySQL client

examples/common/env.sh
Saw in https://github.com/vitessio/vitess/pull/13268 that the `[Upgrade Downgrade Test - Backups - Manual](https://github.com/vitessio/vitess/actions/runs/5204734892/jobs/9402321444?pr=13268#logs)` test was failing due to an invalid flag when running with `vttablet:16.0.2` from the `release-17.0` branch. The incorrect flag is: `--config-file-not-found-handling`.
This PR ensures we do not add the flag if the version of `vttablet` is not greater or equal to 17.
Log fragment from previous CI run:
```
unknown flag: --config-file-not-found-handling
``` …
=> Skip `--config-file-not-found-handling` in upgrade downgrade tests when `vttablet < 17.x.x`

go/vt/vtgate/tabletgateway.go, go/vt/vtgate/tabletgateway_flaky_test.go
This PR fixes an unhandled error when reaching an inconsistent state in query buffering.
- Fixes https://github.com/vitessio/vitess/issues/13329
=> Handle inconsistent state error in query buffering

changelog/16.0/16.0.0/release_notes.md, changelog/17.0/17.0.0/release_notes.md, go/test/endtoend/backup/vtctlbackup/backup_utils.go, go/vt/vttablet/tabletmanager/restore.go
The  `RestoredBackupTime` and `RestorePosition` attributes of backups were stored in `local_metadata` before v16. They were lost in the refactor where we dropped that table. Adding these back as metrics in vttablet.
https://github.com/vitessio/vitess/issues/13336
-   [x] Documentation was added or is not required https://github.com/vitessio/website/pull/1508
=> Add RestorePosition and RestoredBackupTime as metrics to vttablet

go/vt/vtctl/reparentutil/emergency_reparenter.go, go/vt/vtorc/logic/tablet_discovery.go, go/vt/vtorc/logic/tablet_discovery_test.go, go/vt/vtorc/logic/topology_recovery.go
This PR improves the lock action string for VTOrc. Instead of just having `Orc recovery`, it is better to use a more descriptive string including the information of the recovery type and which tablet it is being run on.
=> Improve lock action string

go/test/endtoend/vtorc/api/api_test.go, go/test/endtoend/vtorc/general/vtorc_test.go, go/test/endtoend/vtorc/primaryfailure/main_test.go, go/test/endtoend/vtorc/primaryfailure/primary_failure_test.go, go/test/endtoend/vtorc/utils/utils.go, go/vt/vtorc/inst/analysis.go, go/vt/vtorc/inst/analysis_dao.go, go/vt/vtorc/inst/analysis_dao_test.go, go/vt/vtorc/logic/tablet_discovery.go, go/vt/vtorc/logic/tablet_discovery_test.go, go/vt/vtorc/logic/topology_recovery.go, go/vt/vtorc/logic/topology_recovery_test.go
This PR reworks the VTOrc failure detection logic to include a post-process phase after the initial analysis has run. This is needed because sometimes we need to look at information from analyses of multiple tablets and not just from one. One such case (implemented in this PR), is that of having a primary which is already broken when VTOrc comes up. In this case, VTOrc won't be able to reach the instance and previously it would infer a `ClusterHasNoPrimary` recovery, but that isn't correct. Instead we create a new failure mode called `InvalidPrimary` signifying that VTOrc hasn't been able to reach the given primary tablet.
If VTOrc detects the `InvalidPrimary` failure, it checks whether all the other tablets in the given keyspace shard have their replication broken or not. If the …
=> Improve VTOrc failure detection to be able to better handle dead primary failures

go/sqltypes/testing.go, go/test/endtoend/utils/cmp.go, go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/vt/vtgate/engine/opcode/constants.go, go/vt/vtgate/engine/ordered_aggregate.go, go/vt/vtgate/engine/ordered_aggregate_test.go, go/vt/vtgate/engine/scalar_aggregation.go, go/vt/vtgate/engine/scalar_aggregation_test.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/operator_transformers.go, go/vt/vtgate/planbuilder/operators/aggregation_pushing.go, go/vt/vtgate/planbuilder/operators/aggregator.go, go/vt/vtgate/planbuilder/operators/queryprojection.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.json, go/vt/vtgate/planbuilder/testdata/memory_sort_cases.json, go/vt/vtgate/planbuilder/testdata/tpch_cases.json, go/vt/vtgate/planbuilder/testdata/unsupported_cases.json
This PR adds support for the `group_concat` aggregation function. It also fixes issues with the aggregator operator when complete aggregation/grouping happens at VTGate.
- https://github.com/vitessio/vitess/issues/9928
=> Add group_concat aggregation support

Makefile, changelog/16.0/16.0.0/release_notes.md, changelog/17.0/17.0.0/release_notes.md, doc/internal/ReleaseInstructions.md, go/cmd/vtctldclient/command/reparents.go, go/test/endtoend/backup/vtctlbackup/backup_utils.go, go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/test/endtoend/vtgate/queries/aggregation/schema.sql, go/test/endtoend/vtgate/queries/aggregation/vschema.json, go/test/endtoend/vtgate/queries/misc/misc_test.go, go/tools/release-notes/release_notes.go, go/vt/mysqlctl/schema.go, go/vt/mysqlctl/schema_test.go, go/vt/vtgate/engine/filter.go, go/vt/vtgate/engine/projection.go, go/vt/vtgate/engine/scalar_aggregation.go, go/vt/vtgate/planbuilder/operators/aggregation_pushing.go, go/vt/vtgate/planbuilder/operators/joins.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.json, go/vt/vtgate/planbuilder/testdata/from_cases.json, go/vt/vttablet/tabletmanager/restore.go
This PR aggregates all pending backport PRs and cherry-picks them all. We current cannot merge the vitess-bot PRs due to a GH bug. In order to unblock the release team for `v17.0.0` this PR cherry-picks all that's needed.
- https://github.com/vitessio/vitess/pull/13339
- https://github.com/vitessio/vitess/pull/13273
- https://github.com/vitessio/vitess/pull/13312
- https://github.com/vitessio/vitess/pull/13330
- https://github.com/vitessio/vitess/pull/13332
- https://github.com/vitessio/vitess/pull/13348
- https://github.com/vitessio/vitess/pull/13350
**In order to keep track of the history - Please do not Squash Merge this PR.**
-   [x] Did the new or modified …
=> Cherry-pick all pending PRs into `release-17.0`

examples/common/lib/utils.sh, examples/local/101_initial_cluster.sh, test/local_example.sh
A change in https://github.com/vitessio/vitess/pull/12240 caused `examples/local/101_initial_cluster.sh` to lose idempotency; meaning re-running `examples/local/101_initial_cluster.sh` on a non-empty `VTDATAROOT` failed.
This PR fixes that, and it is now possible to re-run examples `101` on existing cluster data. This is now also tested in `test/local_example` CI.
Lastly, we add a small improvement waiting for the MySQL server to be writeable.
- Fixes https://github.com/vitessio/vitess/issues/13372
=> Local example 101: idempotent on existing clusters

.github/workflows/code_freeze.yml, changelog/17.0/17.0.0/changelog.md, changelog/17.0/17.0.0/release_notes.md, docker/release.sh, examples/compose/docker-compose.beginners.yml, examples/compose/docker-compose.yml, examples/compose/vtcompose/docker-compose.test.yml, examples/compose/vtcompose/vtcompose.go, examples/operator/101_initial_cluster.yaml, examples/operator/201_customer_tablets.yaml, examples/operator/302_new_shards.yaml, examples/operator/306_down_shard_0.yaml, examples/operator/operator.yaml, go/tools/release-notes/release_notes.go, go/vt/servenv/version.go, java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/jdbc/pom.xml, java/pom.xml
Includes the release notes and release commit for the v17.0.0 release. Once this PR is merged, we will be able to tag v17.0.0 on the merge commit.
=> Release of v17.0.0

go/vt/mysqlctl/fakemysqldaemon.go, go/vt/mysqlctl/replication.go, go/vt/vtctl/grpcvtctldserver/endtoend/init_shard_primary_test.go, go/vt/vttablet/tabletmanager/rpc_replication.go, go/vt/vttablet/tabletmanager/tm_init_test.go, go/vt/wrangler/testlib/backup_test.go, go/vt/wrangler/testlib/copy_schema_shard_test.go, go/vt/wrangler/testlib/emergency_reparent_shard_test.go, go/vt/wrangler/testlib/external_reparent_test.go, go/vt/wrangler/testlib/permissions_test.go, go/vt/wrangler/testlib/planned_reparent_shard_test.go, go/vt/wrangler/testlib/reparent_utils_test.go, go/vt/wrangler/testlib/version_test.go
This PR fixes the code to not reset replication every time we set the replication source in vttablet. The code to reset replication parameters was introduced in https://github.com/vitessio/vitess/pull/10943 to resolve the issue https://github.com/vitessio/vitess/issues/10955.
The fix chosen then was to reset replication everytime we called `SetReplicationSource`. This however was incorrect since resetting replication loses track of the relay logs. This is a significant operation that needs to be only done when required and not be run always.
This issue is described in more detail in https://github.com/vitessio/vitess/issues/13276.
This PR fixes this issue, by removing the code to always reset replication. Instead an additional case has been added to the function `handleRelayLogError` for …
=> Prevent resetting replication every time we set replication source

go/vt/vtorc/logic/topology_recovery_status.go
This PR adds timestamp to the VTOrc debug page showing recent recoveries. It also changes the hostname-port to show the vttablet alias instead.
- Fixes #13366 
=> Add timestamp to vtorc debug page

changelog/17.0/17.0.0/changelog.md, changelog/17.0/17.0.0/release_notes.md
This is a forward port of the v17.0.0 GA release notes from: https://github.com/vitessio/vitess/pull/13369
- Part of: https://github.com/vitessio/vitess/issues/13151
=> Forward port of release notes changes from v17.0.0 GA

go/mysql/flavor_mysql.go, go/vt/vttablet/endtoend/misc_test.go
Quick fix to https://github.com/vitessio/vitess/pull/13375
The query in https://github.com/vitessio/vitess/pull/13375 did not output entries for Views. It's unclear how tests passed in https://github.com/vitessio/vitess/pull/13375 and allowed us to merge the PR, as the tests are now consistently failing on `main`. 
This PR should resolve the matter.
- https://github.com/vitessio/vitess/pull/13375
- https://github.com/vitessio/vitess/issues/13374
=> Support views in BaseShowTablesWithSizes for MySQL 8.0

go/vt/vttablet/tabletmanager/rpc_replication.go, go/vt/wrangler/testlib/fake_tablet.go, go/vt/wrangler/testlib/reparent_utils_test.go
=> [release-15.0] Don't run any reparent commands if the host is empty (#13396)

go/vt/vttablet/tabletmanager/rpc_replication.go, go/vt/wrangler/testlib/fake_tablet.go, go/vt/wrangler/testlib/reparent_utils_test.go
=> [release-16.0] Don't run any reparent commands if the host is empty (#13396)
