go/tools/release-notes/release_notes.go
go/tools/release-notes/release_notes_test.go

This PR changes how we generate releases notes' changelog. We used to parse the `git log` output, this led to several errors in the past releases where some PRs made on a totally unrelated branch appeared in the changelog of a release.
With this PR we now use the GitHub Milestones to fetch the full list of merged Pull Request for a given release. This change significantly improves the time taken by the tool to generate the release notes, below is a before / after when generating the `v17.0.0` release notes:
```shell
$> time go run ./go/tools/release-notes/release_notes.go -f v16.0.2 -t v17.0.0 --version v17.0.0
Found 460 merged PRs. Loading PR info................................................................................................................................................ …
```

Optimize release notes generation to use GitHub Milestones

---

go/test/endtoend/vtgate/queries/misc/misc_test.go

This PR deflakes the test `TestQueryTimeoutWithDual`. I think `select /*vt+ PLANNER=gen4 QUERY_TIMEOUT_MS=10 */ sleep(0.001) from dual` isn't a good query to test. The timeout and sleep are equal, so it is a race. Given that sleeps and timeouts are never actually accurate to an infinite precision, we should increase that query timeout somewhat to a higher value.
This PR accomplishes that by increasing the timeout to 15 ms instead.
- Fixes #13404 

Deflake `TestQueryTimeoutWithDual` test

---

examples/common/scripts/vttablet-up.sh

This PR fixes the test `Upgrade Downgrade Testing - Backups - Manual` after it was found to be failing in release-16.0.
The fix entails reverting the changes in `vttablet-up.sh` file in https://github.com/vitessio/vitess/pull/12791
- Fixes #13407 

TestFix: `Upgrade Downgrade Testing - Backups - Manual`

---

go/event/syslogger/fake_logger.go
go/event/syslogger/syslogger_test.go
go/vt/vttablet/tabletserver/schema/engine.go
go/vt/vttablet/tabletserver/schema/engine_test.go

This PR logs any error coming from LoadTable in schema/engine instead of failing the reload method.
- Fixes https://github.com/vitessio/vitess/issues/13422

Ignore error while reading table data in Schema.Engine reload

---

go/test/endtoend/onlineddl/vrepl_stress/onlineddl_vrepl_mini_stress_test.go
go/vt/vttablet/onlineddl/executor.go
go/vt/vttablet/onlineddl/schema.go

This is a (manual) backport of https://github.com/vitessio/vitess/pull/11460, changing the vreplication cut-over algorithm to be atomic.
The change is deemed safe to backport per https://github.com/vitessio/vitess/issues/11226#issuecomment-1401480438 and after additional review of the changes. If the tests pass in CI, this should be good to go.
We were supposed to do this backport months ago, but it was lost.
- https://github.com/vitessio/vitess/issues/11226
- #6926

v15 backport: vitess Online DDL atomic cut-over

---

go/test/endtoend/vtorc/primaryfailure/primary_failure_test.go
go/vt/vtorc/inst/analysis_dao.go
go/vt/vtorc/inst/audit_dao.go
go/vt/vtorc/inst/instance_dao.go
go/vt/vtorc/inst/instance_dao_test.go
go/vt/vtorc/logic/tablet_discovery.go
go/vt/vtorc/logic/topology_recovery.go

This PR fixes the logging in VTOrc to use the tablet aliases wherever possible instead of hostname and port since aliases are easier to read.

Improve VTOrc logging statements, now that we have alias as a field

---

.github/workflows/upgrade_downgrade_test_backups_manual.yml
.github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
examples/backups/restart_tablets.sh
examples/backups/start_cluster.sh
examples/backups/upgrade_cluster.sh
examples/common/scripts/vttablet-up.sh
go/vt/vtctl/reparentutil/planned_reparenter.go
go/vt/vtctl/reparentutil/planned_reparenter_flaky_test.go
go/vt/wrangler/testlib/planned_reparent_shard_test.go

When we introduced the schema-init-db code, we failed to realize that it would start doing writes as part of the code to change the tablet type. As part of the PRS process, we used to call `PromoteReplica` first, followed by calls to `SetReplicationSource`. 
When a user upgrades from v16 (/v15) to v17 (/v16), as part of `PromoteReplica` call, the schema-init realizes that there are schema diffs to apply and ends up writing to the database. The problem is that if semi-sync is enabled, all of these writes get blocked indefinitely. Eventually, `PromoteReplica` fails and this fails the entire `PRS` call.
In this PR we fix this issue, by altering the PRS flow slightly, where we call `SetReplicationSource` on all the replicas and `PromoteReplica` on the new primary in parallel. This allows …

[release-17.0] Upgrade-Downgrade Fix: Schema-initialization stuck on semi-sync ACKs while upgrading

---

.github/workflows/upgrade_downgrade_test_backups_manual.yml
.github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
examples/backups/restart_tablets.sh
examples/backups/start_cluster.sh
examples/backups/upgrade_cluster.sh
examples/common/scripts/vttablet-up.sh
go/vt/vtctl/reparentutil/planned_reparenter.go
go/vt/vtctl/reparentutil/planned_reparenter_flaky_test.go
go/vt/wrangler/testlib/planned_reparent_shard_test.go

This PR is a forward port of https://github.com/vitessio/vitess/pull/13411 to `main`.
When we introduced the schema-init-db code, we failed to realize that it would start doing writes as part of the code to change the tablet type. As part of the PRS process, we used to call `PromoteReplica` first, followed by calls to `SetReplicationSource`. 
When a user upgrades from v16 (/v15) to v17 (/v16), as part of `PromoteReplica` call, the schema-init realizes that there are schema diffs to apply and ends up writing to the database. The problem is that if semi-sync is enabled, all of these writes get blocked indefinitely. Eventually, `PromoteReplica` fails and this fails the entire `PRS` call.
In this PR we fix this issue, by altering the PRS flow slightly, where we call `SetReplicationSource` on …

[main] Upgrade-Downgrade Fix: Schema-initialization stuck on semi-sync ACKs while upgrading (#13411)

---

.github/workflows/upgrade_downgrade_test_backups_manual.yml
.github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
examples/backups/restart_tablets.sh
examples/backups/start_cluster.sh
examples/backups/upgrade_cluster.sh
examples/common/scripts/vttablet-up.sh
go/vt/vtctl/reparentutil/planned_reparenter.go
go/vt/vtctl/reparentutil/planned_reparenter_flaky_test.go
go/vt/wrangler/testlib/planned_reparent_shard_test.go

This PR is a backport of #13411.
When we introduced the schema-init-db code, we failed to realize that it would start doing writes as part of the code to change the tablet type. As part of the PRS process, we used to call `PromoteReplica` first, followed by calls to `SetReplicationSource`. 
When a user upgrades from v16 (/v15) to v17 (/v16), as part of `PromoteReplica` call, the schema-init realizes that there are schema diffs to apply and ends up writing to the database. The problem is that if semi-sync is enabled, all of these writes get blocked indefinitely. Eventually, `PromoteReplica` fails and this fails the entire `PRS` call.
In this PR we fix this issue, by altering the PRS flow slightly, where we call `SetReplicationSource` on all the replicas and `PromoteReplica` on the new …

[release-16.0] Upgrade-Downgrade Fix: Schema-initialization stuck on semi-sync ACKs while upgrading (#13411)

---

examples/common/lib/utils.sh
examples/common/scripts/consul-down.sh
examples/common/scripts/etcd-down.sh
examples/common/scripts/vtadmin-down.sh
examples/common/scripts/vtctld-down.sh
examples/common/scripts/vtgate-down.sh
examples/common/scripts/vtorc-down.sh
examples/common/scripts/vttablet-down.sh

Fix issue 13432 {1}.  At the same time, get rid of duplicate code in vtadmin-down.sh.
{1}: https://github.com/vitessio/vitess/issues/13432
The PR is organized in 2 commits for ease of understanding.  I would suggest a squash-merge.
Fixes: https://github.com/vitessio/vitess/issues/13432
-   [x] Documentation not required
N/A

Examples: only terminate vtadmin if it was started

---

go/mysql/constants.go
go/vt/mysqlctl/schema.go
go/vt/vttablet/tabletserver/schema/engine.go
go/vt/vttablet/tabletserver/schema/engine_test.go
go/vt/vttablet/tabletserver/schema/load_table.go

Followup and refine to https://github.com/vitessio/vitess/pull/13421.
In https://github.com/vitessio/vitess/pull/13421 we ignore (log and continue) errors while reading columns for tables/views. This is too permissive and might cause undesired behavior down the road for code that uses the caches table data. An error reading table columns should remain an error and fail the `Reload()` operation. For views, we can indeed ignore such failure, for two reasons:
1. It is possible to have an invalid view definition in MySQL. So while highly undesired, this is a "valid" situation that we should accommodate.
2. None of our internal processes cares much about view columns (e.g. vreplication doesn't read from views).
So this PR only ignores the errors for views, and does error when failing to read …

schema.Reload(): ignore column reading errors for views only, error for tables

---

go/mysql/constants.go
go/vt/mysqlctl/schema.go
go/vt/vttablet/tabletserver/schema/engine.go
go/vt/vttablet/tabletserver/schema/engine_test.go

Backport v16: schema.Reload(): ignore column reading errors for views only, error for tables #13442

---

go/mysql/constants.go
go/vt/mysqlctl/schema.go
go/vt/vttablet/tabletserver/schema/engine.go
go/vt/vttablet/tabletserver/schema/engine_test.go
go/vt/vttablet/tabletserver/schema/load_table.go

Backport of https://github.com/vitessio/vitess/pull/13442 to `v17`

Backport v17: schema.Reload(): ignore column reading errors for views only, error for tables #13442

---

go/mysql/constants.go
go/vt/mysqlctl/schema.go
go/vt/vttablet/tabletserver/schema/engine.go
go/vt/vttablet/tabletserver/schema/engine_test.go

Backport of https://github.com/vitessio/vitess/pull/13442 to v15

Backport v15: schema.Reload(): ignore column reading errors for views only, error for tables #13442

---

go/vt/vtorc/server/api.go

Currently, whenever a VTOrc API is called, it gets logged with a message like - `HTTP API Request received: /debug/health`. Since the VTOp does a certain amount of API calls constantly, this log line very quickly starts polluting the logs. This PR removes this log line to resolve this problem.

Remove excessive logging in VTOrc APIs

---

examples/compose/.env
examples/compose/docker-compose.beginners.yml
examples/compose/docker-compose.yml

This PR resolves errors pulling `consul:latest` in `examples/compose/docker-compose.yml`:
```bash
tvaillancourt@tvailla-ltmxctu compose % docker-compose up -d       
[+] Running 3/3
✘ consul2 Error                                                                                                                                                                                                2.1s 
✘ consul3 Error                                                                                                                                                                                                2.1s 
✘ consul1 Error …
```

`examples/compose`: fix `consul:latest` error w/`docker-compose up -d`

---

docker/lite/Dockerfile.ubi8.arm64.mysql80

This PR is to fix build error for ubi8.arm64.mysql80.
Installing package from https://download-ib01.fedoraproject.org/ fails and this results to build fail.
I have modified the package mirror server from https://download-ib01.fedoraproject.org/ to https://dl.fedoraproject.org/ and I have checked that there is no issue after modifying the package url.
Installing package was 
Fixes: https://github.com/vitessio/vitess/issues/13420

Fix ubi8.arm64.mysql80 build package mirrorserver error

---

go/test/endtoend/utils/cmp.go
go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
go/vt/sqlparser/ast.go
go/vt/sqlparser/ast_rewriting.go
go/vt/sqlparser/ast_rewriting_test.go
go/vt/vtgate/engine/scalar_aggregation_test.go
go/vt/vtgate/planbuilder/operators/aggregation_pushing.go
go/vt/vtgate/planbuilder/operators/aggregator.go
go/vt/vtgate/planbuilder/testdata/aggr_cases.json

This PR improves the distinct aggregation push-down planner and also fixes a bug introduced in a previous PR.
- https://github.com/vitessio/vitess/pull/13412

Improve and Fix Distinct Aggregation planner

---

go/vt/mysqlctl/replication.go

It was noticed that we are getting logs like `SetReadOnly setting connection setting of :0 to : ReadWrite`. This is happening because vttablet is connected to mysql via a socket file, so the hostname and port are empty. 
This log message is on the vttablets and the knowledge of whether host port is used or whether socket is used to connect to mysql is not interesting.
Now the log looks like - `SetReadOnly setting to : ReadOnly`

Fix logging by omitting the host and port in `SetReadOnly`

---

go/test/endtoend/cluster/mysqlctld_process.go
go/test/endtoend/mysqlctld/mysqlctld_test.go
go/vt/mysqlctl/grpcmysqlctlclient/client.go
go/vt/mysqlctl/grpcmysqlctlserver/server.go

The remote API added in #13449 didn't actually implement the server as this was overlooked with the generated unimplemented server.
This adds the implementation and a test to exercise the remote path. 
This was broken in https://github.com/vitessio/vitess/pull/13449
Fixes #13485

Fix remote VersionString API

---

go/mysql/replication_position.go
go/mysql/replication_position_test.go
go/vt/mysqlctl/builtinbackupengine.go
go/vt/mysqlctl/builtinbackupengine2_test.go

The user may now issue:
```sh
$ vtctlclient -- Backup --incremental_from_pos "16b1039f-22b6-11ed-b765-0a43f95f28a3:1-615" zone1-0000000102
```
And Vitess will infer that they mean `"MySQL56/16b1039f-22b6-11ed-b765-0a43f95f28a3:1-615"`. `MySQL56` is the only flavor supported, anyway. As long as the GTID set is valid and has no parsing errors, the `MySQL56/` can be omitted.
Fixes https://github.com/vitessio/vitess/issues/13415
Documentation: https://github.com/vitessio/website/pull/1533

Incremental backup: accept GTID position without 'MySQL56/' flavor prefix

---

go/vt/vttablet/tabletserver/schema/engine.go
go/vt/vttablet/tabletserver/schema/engine_test.go

This PR fixes the use of `error.As` method to send the correct argument for matching.
- https://github.com/vitessio/vitess/pull/13442
- #13422 

fix: error.as method usage to send pointer to the reference type expected

---

examples/common/scripts/vttablet-up.sh

The upgrade-downgrade tests have become flaky with the changes in https://github.com/vitessio/vitess/pull/13246. In that PR `--disable-active-reparents` has been added to `vttablet-up.sh`. 
I see it has failed on main - https://github.com/vitessio/vitess/actions/runs/5551856255/jobs/10138489035
Adding `--disable_active_reparents` means that if the REPLICA tablet is selected for the backup, then it doesn't fix its own replication back again. So there is a 12.5% chance of success of this test to pass! (We have 3 shards, each having 3 tablets, PRIMARY, REPLICA and RDONLY, 50-50 chance you select REPLICA for running the backup).
This PR removes that flag.
-   [x] Did …

Remove `--disable_active_reparents` flag in vttablet-up.sh

---

go/viperutil/debug/handler.go

It's possible to inject HTML / Javascript in the format parameter which means you can do a self XSS. Not a huge immediately issue as it's only self XSS, but we should fix it nonetheless.
See https://github.com/vitessio/vitess/security/code-scanning/142

viperutil: Remove potential cross site reflecting issue

---

go/flags/endtoend/mysqlctl.txt
go/flags/endtoend/mysqlctld.txt
go/flags/endtoend/vtaclcheck.txt
go/flags/endtoend/vtbackup.txt
go/flags/endtoend/vtctlclient.txt
go/flags/endtoend/vtctld.txt
go/flags/endtoend/vtexplain.txt
go/flags/endtoend/vtgate.txt
go/flags/endtoend/vtorc.txt
go/flags/endtoend/vttablet.txt
go/flags/endtoend/vttestserver.txt
go/flags/endtoend/zkctl.txt
go/flags/endtoend/zkctld.txt

These should not be hardcoded but use the proper variable.
Introduced in #13031

flags: Remove hardcoded runner paths

---

go/vt/vtgate/tabletgateway_flaky_test.go

[release-15.0] Fix `TestGatewayBufferingWhileReparenting` flakiness (#13469)

---

go/vt/vtgate/tabletgateway_flaky_test.go

[release-16.0] Fix `TestGatewayBufferingWhileReparenting` flakiness (#13469)

---

examples/common/scripts/vttablet-up.sh

The flags that are used in `release-17.0` namely `throttler-config-via-topo`  doesn't exist on `main` post the changes in https://github.com/vitessio/vitess/pull/13246. This PR removes these flags in `vttablet-up.sh` so as to fix the failing upgrade-downgrade tests.

[release-17.0] Upgrade-downgrade test fix: Remove throttler flags in `vttablet-up.sh`

---

go/vt/vtgate/tabletgateway_flaky_test.go

[release-17.0] Fix `TestGatewayBufferingWhileReparenting` flakiness (#13469)

---

changelog/18.0/18.0.0/summary.md
docker/release.sh

Pretty straightforward. This should auto-build with releases, but doesn't change the default yet.

docker/k8s: add bookworm builds

---

go/vt/vttablet/tabletmanager/rpc_vreplication_test.go
go/vt/wrangler/materializer_test.go
go/vt/wrangler/traffic_switcher.go
go/vt/wrangler/traffic_switcher_env_test.go
go/vt/wrangler/workflow_test.go

We were NOT ignoring unrelated shards when building the workflow state for a partial MoveTables workflow. See: https://github.com/vitessio/vitess/issues/13508
Without the fix in the PR, the new unit test added here fails:
```
--- FAIL: TestMoveTablesShardByShard (0.04s)
workflow_test.go:330: shardRoutingRules: rules:{from_keyspace:"ks2" to_keyspace:"ks1" shard:"-80"} rules:{from_keyspace:"ks2" to_keyspace:"ks1" shard:"80-"}
workflow_test.go:345:
Error Trace:	/Users/matt/git/vitess/go/vt/wrangler/workflow_test.go:345
Error:      	Not equal:
expected: "Reads Not Switched. Writes Not Switched"
actual  : "Reads partially switched, for shards: 40-80. Writes partially switched, for shards: 40-80"
Diff:
--- Expected
+++ Actual
@@ -1 +1 @@
-Reads Not Switched. Writes Not Switched
+Reads partially …
```

VReplication: Ignore unrelated shards in partial MoveTables traffic state

---

go/cmd/internal/docgen/docgen.go

In #13015, @mattlord found two issues with the docgen tool.
1. The titles were wrong. This was an easy fix to the frontmatter.
2. The links between parent and child command pages were wrong. This was ... a whole thing, mostly due to the problem that the `linkHandler` function has no context (i.e. you know only what page you are generating a link _to_, not what you are linking to that page _from_). So, two changes here:
a. restructure the child command files so they sit below their parent rather than having everything in a single top-level file structure
b. run a `sed` on each child page to rewrite the incorrect link to its parent to simply go to `../`.
I ran this on top of Matt's PR and clicking around worked. I can push those changes directly to his website branch as proof, or he can …

fix docgen for subcommands

---

docker/lite/install_dependencies.sh

The Vitess lite builds were failing within the [`install_dependencies.sh`](https://github.com/vitessio/vitess/blob/main/docker/lite/install_dependencies.sh) script:
```
#11 39.01 The following packages have unmet dependencies:
#11 39.06  libmysqlclient21 : Depends: mysql-common (>= 8.0.30-1debian10) but it is not going to be installed
#11 39.06  mysql-community-client : Depends: mysql-common (>= 8.0.30-1debian10) but it is not going to be installed
#11 39.06  mysql-community-server : Depends: mysql-common (>= 8.0.30-1debian10) but it is not going to be installed
#11 39.06  percona-xtrabackup-80 : Depends: libdbd-mysql-perl but it is not going to be installed
#11 39.07 E: Unable to correct problems, you have held broken packages.
```
You can see recent build failures here: …

Fix dependencies in docker build script

---

go/viperutil/internal/sync/sync_test.go

Turns out this is very tricky to repro locally, so I temporarily rewrote the test to do the following:
```go
func TestWatchConfig(t *testing.T) {
t.Parallel()
type config struct {
A, B int
}
writeConfig := func(tmp *os.File, a, b int) error {
stat, err := os.Stat(tmp.Name())
if err != nil {
return err
}
data, err := json.Marshal(&config{A: a, B: b})
if err != nil {
return err
}
err = os.WriteFile(tmp.Name(), data, stat.Mode())
if err != nil {
return err
}
data, err = os.ReadFile(tmp.Name())
if err != nil {
return err
}
var cfg config
if err := json.Unmarshal(data, &cfg); err != nil {
return err
}
if cfg.A != a || cfg.B != b {
return fmt.Errorf("config did not persist; want %+v got %+v", config{A: a, B: b}, cfg)
}
return nil
}
writeRandomConfig := func(tmp *os.File) error {
a, b := …
```

[vipersync] deflake TestWatchConfig

---

go/test/endtoend/cluster/vtorc_process.go
go/test/endtoend/vtorc/general/vtorc_test.go
go/test/endtoend/vtorc/primaryfailure/primary_failure_test.go
go/test/endtoend/vtorc/readtopologyinstance/main_test.go
go/test/endtoend/vtorc/utils/utils.go

This PR is a backport of #13489.

[release-16.0]: Fix flakiness in VTOrc tests (#13489)

---

go/test/endtoend/cluster/vtorc_process.go
go/test/endtoend/vtorc/general/vtorc_test.go
go/test/endtoend/vtorc/primaryfailure/primary_failure_test.go
go/test/endtoend/vtorc/readtopologyinstance/main_test.go
go/test/endtoend/vtorc/utils/utils.go

[release-15.0]: Fix flakiness in VTOrc tests (#13489)

---

go/vt/wrangler/testlib/planned_reparent_shard_test.go

In the test `TestPlannedReparentShardPromoteReplicaFail` after the first call to PRS fails, it is uncertain whether the `SetReplicationSource` call on the oldPrimary has succeeded or whether it has been cancelled. This indeterminism was causing the test to be flaky. 
In order to remedy the situation, we now explicitly call `SetReplicationSource` on the oldPrimary and wait for it to succeed and for the primary to demote itself to a Replica.

Deflake `TestPlannedReparentShardPromoteReplicaFail`

---

.github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml
config/init_db.sql
go/test/endtoend/backup/vtbackup/main_test.go
go/test/endtoend/cluster/mysqlctl_process.go
go/test/endtoend/utils/utils.go
go/test/endtoend/vreplication/testdata/config/init_testserver_db.sql

This PR fixes the ugprade-downgrade test setup which was installing the incorrect versions of binaries. After fixing this change, the test fails which prompted the change in `init_db.sql` file. 
In release-17.0 the super read only work was done and it was turned on. In order to preserve downgrade path we need to fix `init_db.sql` bundled in release-16.0 to turn off super_read_only when it is executed.

[release-16.0]: Fix `upgrade-downgrade` test setup and fix the `init_db.sql`

---

go/vt/vtorc/inst/instance_dao_test.go

This PR skips the flaky test `TestReadOutdatedInstanceKeys` until the flakiness can be resolved. The PR https://github.com/vitessio/vitess/pull/13489 did not successfully resolve this flakiness.

Skip flaky test `TestReadOutdatedInstanceKeys`

---

go/cmd/vtbackup/vtbackup.go
go/cmd/vtctldclient/command/backups.go
go/flags/endtoend/vtbackup.txt
go/vt/vtctl/backup.go

This was missed in the original PR in #13449 
Missed in #13449 which addressed https://github.com/vitessio/vitess/issues/13448, also see https://github.com/vitessio/website/pull/1540#discussion_r1266929371

vtctldclient: Add missing new backup option

---

Makefile
web/vtadmin/build.sh

This PR unsets the `PREFIX` environment variable when building VTAdmin. It fixes https://github.com/vitessio/vitess/issues/13532
https://github.com/vitessio/vitess/issues/13532

Unset the PREFIX environment variable when building VTAdmin

---

.github/workflows/endtoend.yml
.github/workflows/local_example.yml
.github/workflows/region_example.yml
.github/workflows/upgrade_downgrade_test_backups_e2e.yml
.github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml
.github/workflows/upgrade_downgrade_test_backups_manual.yml
.github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
.github/workflows/upgrade_downgrade_test_query_serving_queries.yml
.github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
.github/workflows/upgrade_downgrade_test_query_serving_schema.yml
.github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml
.github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml
.github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml
.github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml
.github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml
test.go

This Pull Request enhances how we run tests in CI. We now skip VTAdmin build when it is not required to speed up the whole testing process.
Moreover, in the local and region examples we now setup `node` to avoid having to manually download `node`. 

Optimize `make build` in `test.go` and in CI

---

go/vt/wrangler/testlib/copy_schema_shard_test.go
go/vt/wrangler/testlib/external_reparent_test.go
go/vt/wrangler/testlib/planned_reparent_shard_test.go
go/vt/wrangler/testlib/utils.go

This PR fixes the tests in `wrangler/testlib` directory. The tests fixed in this PR are `TestCopySchemaShard_UseTabletAsSource`, `TestCopySchemaShard_UseShardAsSource` and `TestRPCTabletExternallyReparentedDemotesPrimaryToConfiguredTabletType`.
All of these tests were relying on the shard record to be up-to-date and have the `PrimaryAlias` field populated. However, this information is updated by the primary tablet asynchronously and sometimes causes the tests to fail.
This PR adds a waiting logic to these tests to wait upto 15 seconds for the `PrimaryAlias` to be updated before running a operation/test dependent on it.  …

Flaky tests: Fix wrangler tests

---

go/vt/vtgate/tabletgateway_flaky_test.go

Due to valid races the test can get one of two error messages. Only one was expected earlier causing flakiness

Fix flaky vtgate test TestInconsistentStateDetectedBuffering

---

go/vt/topo/memorytopo/election.go
go/vt/topo/memorytopo/memorytopo.go
go/vt/topo/memorytopo/watch.go

Fixing flaky test found in one of the unit test CI workflow runs.
```
2023-07-19T20:55:15.3945216Z W0719 20:53:54.030022   38113 log.go:39] Failed to read in config : Config File "vtconfig" Not Found in "[/home/runner/work/vitess/vitess/go/vt/wrangler]". This is optional, and can be ignored if you are not using config files. For a detailed explanation, see https://github.com/vitessio/vitess/blob/main/doc/viper/viper.md#config-files.
2023-07-19T20:55:15.3948265Z W0719 20:53:54.033199   38113 log.go:39] Failed to read in config : Config File "vtconfig" Not Found in "[/home/runner/work/vitess/vitess/go/vt/wrangler]". This is optional, and can be ignored if you are not using config files. For a detailed explanation, see https://github.com/vitessio/vitess/blob/main/doc/viper/viper.md#config-fil …
```

Flaky tests: Fix race in memory topo

---

docker/mini/Dockerfile

Signed-off-by: Amir Abushareb <yields@icloud.com>
During the cleanup in https://github.com/vitessio/vitess/pull/13327 seems like we removed some files but didn't update `docker/mini/Dockerfile`.

docker/mini: remove refs to orc configs

---

go/test/endtoend/vtgate/queries/misc/main_test.go
go/test/endtoend/vtgate/queries/misc/misc_test.go
go/test/endtoend/vtgate/queries/misc/schema.sql

This PR fixes the `TestQueryTimeoutWithTables` flaky test.

fix TestQueryTimeoutWithTables flaky test

---

Makefile
bootstrap.sh
dev.env
docker/bootstrap/Dockerfile.common

This was from when we had the old legacy vtctld UI, but we no longer have that so we can remove this now.

Remove unused chromedriver

---

go/mysql/flavor_mysql.go
go/vt/dbconfigs/dbconfigs.go
go/vt/sqlparser/constants.go
go/vt/sqlparser/parse_test.go
go/vt/sqlparser/sql.go
go/vt/sqlparser/sql.y
go/vt/sqlparser/testdata/select_cases.txt
go/vt/sqlparser/testdata/union_cases.txt
go/vt/vtgate/evalengine/fn_string.go
go/vt/vtgate/executor_test.go
go/vt/vtgate/planbuilder/set.go
go/vt/vtgate/planbuilder/show.go
go/vt/vtgate/planbuilder/show_test.go
go/vt/vtgate/planbuilder/testdata/show_cases.json

This fixes the implementation for `show character set` by returning all supported collations and fixing like as well. We also move a bunch of things from `utf8` to the explicit `utf8mb3` names so that we're better compatible if MySQL ever decides to change the alias meaning.
Fixes #13564

Fix show character set

---

.github/workflows/e2e_race.yml
.github/workflows/unit_race.yml
.github/workflows/unit_test_mysql57.yml
.github/workflows/unit_test_mysql80.yml
test/templates/unit_test.tpl
test/templates/unit_test_self_hosted.tpl

This PR is a follow up of https://github.com/vitessio/vitess/pull/13567 and https://github.com/vitessio/vitess/pull/13583; we now skip VTAdmin build in even more places in our CI. 

Skip VTAdmin build in more places

---

.github/workflows/cluster_endtoend_vreplication_partial_movetables_basic.yml
test/ci_workflow_gen.go

Minor refactoring of the workflow names changed in #13238.
#13238 

MoveTables sequence e2e tests: change terminology to use basic vs simple everywhere for partial movetables workflows

---

go/vt/vttablet/tabletserver/schema/engine.go
go/vt/vttablet/tabletserver/schema/engine_test.go

This PR ignores all the view related error on vttablet engine reload method. 
The current implementation only ignores a few errors on views during reload, which is insufficient to continue smoothly.
- https://github.com/vitessio/vitess/issues/13422

ignore all error for views in engine reload

---

go/test/endtoend/onlineddl/revert/onlineddl_revert_test.go

The root issue here is that some of the functions we call before the `cancel(); wg.Wait()` section include calls to assertions from the `require` subpackage, which, unlike their `assert` counterparts, end up calling `t.FailNow()` which aborts the test run via `runtime.Goexit()` If this happens while another goroutine is still running, the test "completes", and if that other goroutine has any additional assertions that fail, this panic occurs.
Luckily, `runtime.GoExit` still executes the deferred function calls in the exiting goroutine, so as long as we defer the context cancelation and wait, we will ensure that that other goroutine exits before the main goroutine of the test case.
Since these tests sometimes need to run code both before and after the "cancel and wait for goroutine" …

Fix potential panics due to "Fail in goroutine after test completed"

---

go/vt/vttablet/tabletserver/throttle/throttler.go

Followup and fix to https://github.com/vitessio/vitess/pull/13246
Per https://github.com/vitessio/vitess/pull/13246#issuecomment-1646614732, the deprecation was done incorrectly, and eventually unnecessarily led to https://github.com/vitessio/vitess/pull/13516
This PR re-introduces the flags so that they are deprecated correctly.
https://github.com/vitessio/vitess/pull/13246

Throttler: reintroduce deprecated flags so that deprecation actually works

---

go/vt/vtgate/planbuilder/operators/aggregation_pushing.go
go/vt/vtgate/planbuilder/operators/aggregator.go
go/vt/vtgate/planbuilder/operators/horizon_expanding.go
go/vt/vtgate/planbuilder/operators/horizon_planning.go
go/vt/vtgate/planbuilder/operators/offset_planning.go
go/vt/vtgate/planbuilder/operators/projection.go
go/vt/vtgate/planbuilder/operators/route.go
go/vt/vtgate/planbuilder/operators/table.go
go/vt/vtgate/planbuilder/testdata/aggr_cases.json
go/vt/vtgate/planbuilder/testdata/tpch_cases.json
go/vt/vtgate/planbuilder/testdata/unsupported_cases.json
go/vt/vtgate/semantics/table_collector.go

This PR removed usage of `errHorizonNotPlanned` which makes the fallback to old horizon planning.
- Removes unnecessary `errHorizonNotPlanned` calls
- Add type information to the vindex columns to avoid adding a column with weigh_strings.
- Route operator to honour `reuse existing` boolean flag for adding columns.
- https://github.com/vitessio/vitess/issues/11626

Reduce usages of old horizon planning fallback

---

go/vt/vtorc/inst/instance_dao_test.go

We had recently removed `TestReadOutdatedInstanceKeys` from the CI by skipping the test in #13561. 
We have been unable to indentify the flakiness in the test and have therefore agreed to reintroduce the test albeit adding some debugging information to help us track down the problem.

Reintroduce `TestReadOutdatedInstanceKeys` with debugging information

---

go/mysql/datetime/parse.go
go/mysql/datetime/parse_test.go
go/mysql/datetime/timeparts.go
go/mysql/json/helpers.go
go/mysql/json/parser.go
go/mysql/json/weights.go
go/mysql/json/weights_test.go
go/sqltypes/bind_variables_test.go
go/sqltypes/value.go
go/sqltypes/value_test.go
go/vt/vtgate/engine/hash_join.go
go/vt/vtgate/engine/merge_sort_test.go
go/vt/vtgate/evalengine/api_arithmetic_test.go
go/vt/vtgate/evalengine/api_compare.go
go/vt/vtgate/evalengine/api_compare_test.go
go/vt/vtgate/evalengine/api_hash.go
go/vt/vtgate/evalengine/api_hash_test.go
go/vt/vtgate/evalengine/api_literal.go
go/vt/vtgate/evalengine/api_types.go
go/vt/vtgate/evalengine/collation.go
go/vt/vtgate/evalengine/compare.go
go/vt/vtgate/evalengine/eval.go
go/vt/vtgate/evalengine/expr_bvar.go
go/vt/vtgate/evalengine/expr_compare.go
go/vt/vtgate/evalengine/translate.go
go/vt/vtgate/vindexes/consistent_lookup.go
go/vt/vtgate/vindexes/consistent_lookup_test.go
go/vt/vtgate/vindexes/lookup_test.go
go/vt/vtgate/vindexes/vindex.go

This implements additional type support for the Nullsafe* family of  functions. It implements a fast path for common types with equal coercion and then falls back to the generic evalengine logic for all other cases.
Fixes #13600

Fix type comparisons for Nullsafe* functions

---

changelog/18.0/18.0.0/summary.md
go/flags/endtoend/vtgate.txt
go/viperutil/internal/sync/sync_test.go
go/vt/vtgate/buffer/buffer.go
go/vt/vtgate/buffer/buffer_helper_test.go
go/vt/vtgate/tabletgateway.go
go/vt/vtgate/tabletgateway_flaky_test.go
go/vt/vtgate/tabletgateway_test.go

Vtgate's buffering logic had an option to use the old healthcheck-based implementation (specified via a flag). However that has been deprecated since v12, so we can remove it now.
The related code and tests have been removed and the flag marked as deprecated.
See comments around this deprecation in
https://github.com/vitessio/vitess/issues/8462

vtgate buffering logic: remove the deprecated healthcheck based implementation

---

go/test/endtoend/recovery/recovery_util.go
go/test/endtoend/recovery/unshardedrecovery/recovery.go
go/vt/vttablet/tabletmanager/restore.go

Tablets coming up in SNAPSHOT keyspaces always use the latest backup regardless of the snapshot timestamp specified during keyspace creation. We expect that the latest backup on or before the snapshot time gets used. Reproduced in the issue linked below. 
Discussion here: https://vitess.slack.com/archives/C0PQY0PTK/p1683010265492109
Fixes: https://github.com/vitessio/vitess/issues/13556
**Testing:** 
1. `make build` & `cd examples/local`
2. `./101_initial_cluster`
3. From `GetTablets` pick a replica
4. `vtctldclient --server …

check keyspace snapshot time if none specified for backup restores

---

go/vt/mysqlctl/schema.go

This PR puts a cap (`20`) for goroutine concurrency in `GetSchema`. Meaning `GetSchema` will introspect no more than `20` tables/views at a time.
Not adding tests: this is a refactor of internal behavior. `GetSchema` is tested through and through in many tests, we expect the existing tests to pass.
Fixes https://github.com/vitessio/vitess/issues/13616

GetSchema: limit concurrent operations

---

go/mysql/icuregex/internal/icudata/embed.go
go/mysql/icuregex/internal/ubidi/loader.go
go/mysql/icuregex/internal/ubidi/ubidi.go
go/mysql/icuregex/internal/ucase/fold.go
go/mysql/icuregex/internal/ucase/loader.go
go/mysql/icuregex/internal/ucase/ucase.go
go/mysql/icuregex/internal/uchar/loader.go
go/mysql/icuregex/internal/uchar/uchar.go
go/mysql/icuregex/internal/unames/loader.go
go/mysql/icuregex/internal/unames/unames.go
go/mysql/icuregex/internal/uprops/loader.go
go/mysql/icuregex/internal/uprops/uprops.go

This avoids loading the ICU data into memory for parts of Vitess that never end up using it, like `vtorc` or `vttablet`.
Fixes #13639 

icuregex: Lazy load ICU data into memory

---

changelog/16.0/16.0.0/release_notes.md
changelog/16.0/16.0.0/summary.md
changelog/16.0/16.0.1/release_notes.md
changelog/16.0/16.0.1/summary.md
changelog/16.0/16.0.2/release_notes.md
changelog/16.0/16.0.2/summary.md
changelog/17.0/17.0.0/release_notes.md
changelog/17.0/17.0.0/summary.md

This PR updates the known issues in v16 and v17 releases and adds https://github.com/vitessio/vitess/issues/13426 to the list.

Update known issues in `v16.x` and `v17.0.0`

---

changelog/15.0/README.md

Prepare release note `v15.0.4`

---

go/tools/release-notes/release_notes.go
go/tools/release-notes/release_notes_test.go

[release-15.0] Optimize release notes generation to use GitHub Milestones (#13398)

---

go/viperutil/internal/sync/sync_darwin_test.go
go/viperutil/internal/sync/sync_linux_test.go
go/viperutil/internal/sync/sync_test.go

It turns out that when you call `os.WriteFile`, it does two things:
```go
f, err := OpenFile(name, O_WRONLY|O_CREATE|O_TRUNC, perm)
f.Write(...)
```
On certain platforms (linux), opening with `O_TRUNC` counts as a WRITE event (since the file _is_ being "written" to blank), which causes fsnotify, and therefor viper to detect a config change, and attempt to reload the config, which results in us failing to parse an empty file as JSON. The second WRITE then fires, and the new config is loaded correctly, but if the main test goroutine resumes before this happens, it will make assertions based on the old config, hence the flakiness.
Therefore, we need to make sure we get exactly _one_ WRITE (or CREATE) event to make the test deterministic, without producing any REMOVE events. How we do this …

[viper WatchConfig] platform-specific write to ensure callback fires exactly once

---

.github/workflows/code_freeze.yml
changelog/16.0/16.0.3/changelog.md
changelog/16.0/16.0.3/release_notes.md
changelog/16.0/README.md
docker/release.sh
examples/compose/docker-compose.beginners.yml
examples/compose/docker-compose.yml
examples/compose/vtcompose/docker-compose.test.yml
examples/compose/vtcompose/vtcompose.go
examples/operator/101_initial_cluster.yaml
examples/operator/201_customer_tablets.yaml
examples/operator/302_new_shards.yaml
examples/operator/306_down_shard_0.yaml
examples/operator/operator.yaml
go/vt/servenv/version.go
java/client/pom.xml
java/example/pom.xml
java/grpc-client/pom.xml
java/jdbc/pom.xml
java/pom.xml

Includes the release notes and release commit for the v16.0.3 release. Once this PR is merged, we will be able to tag v16.0.3 on the merge commit.
- #13612

Release of v16.0.3

---

changelog/15.0/15.0.2/summary.md
changelog/15.0/15.0.4/changelog.md
changelog/15.0/15.0.4/release_notes.md
changelog/15.0/README.md
changelog/16.0/16.0.3/changelog.md
changelog/16.0/16.0.3/release_notes.md
changelog/16.0/README.md
changelog/17.0/17.0.0/summary.md
changelog/17.0/17.0.1/changelog.md
changelog/17.0/17.0.1/release_notes.md
changelog/17.0/README.md

This adds the changelogs for the v15.0.4, v16.0.3, and v17.0.1 patch releases to main.
- Part of:
- https://github.com/vitessio/vitess/issues/13613
- https://github.com/vitessio/vitess/issues/13612
- https://github.com/vitessio/vitess/issues/13611

Add v15.0.4, v16.0.3, and v17.0.1 changelogs

---

go/vt/mysqlctl/mysqld.go

We don't need to log for each individual command here. Also in case of an error, we should log it as an error and not as informational.
Fixes #13598

mysqlctl: Reduce logging for running commands

---

docker/release.sh
go/vt/servenv/version.go
java/client/pom.xml
java/example/pom.xml
java/grpc-client/pom.xml
java/jdbc/pom.xml
java/pom.xml

Includes the changes required to go back into dev mode (v16.0.4-SNAPSHOT) after the release of v16.0.3.
- #13612

Back to dev mode after v16.0.3

---

go/mysql/datetime/datetime.go
go/mysql/datetime/parse.go
go/mysql/decimal/weights.go
go/vt/vtgate/evalengine/api_hash_test.go
go/vt/vtgate/evalengine/cached_size.go
go/vt/vtgate/evalengine/compiler_asm.go
go/vt/vtgate/evalengine/compiler_test.go
go/vt/vtgate/evalengine/expr_convert.go
go/vt/vtgate/evalengine/fn_string.go
go/vt/vtgate/evalengine/format.go
go/vt/vtgate/evalengine/testcases/cases.go
go/vt/vtgate/evalengine/translate_builtin.go
go/vt/vtgate/evalengine/translate_simplify.go
go/vt/vtgate/evalengine/weights.go
go/vt/vtgate/evalengine/weights_test.go

This adds additional weight string support for additional types like integers and datetime instances.
Fixes https://github.com/vitessio/vitess/issues/13641

evalengine: Improve weight string support

---

go/test/endtoend/onlineddl/revert/onlineddl_revert_test.go

Followup to https://github.com/vitessio/vitess/pull/13597#issuecomment-1650628533: picked some random test (`onlineddl_revert`) to re-introduce the deprecated throttler flags, just for the sake of verifying they are still accepted, even though their values are ignored in `v18`.
https://github.com/vitessio/vitess/pull/13246

Throttler: verify deprecated flags are still allowed

---

go/mysql/json/helpers.go
go/sqltypes/value.go
go/vt/vtgate/evalengine/compiler_asm.go
go/vt/vtgate/evalengine/expr_compare.go
go/vt/vtgate/evalengine/fn_string.go
go/vt/vtgate/evalengine/testcases/cases.go
go/vt/vtgate/evalengine/weights.go
go/vt/vtgate/evalengine/weights_test.go

The external WEIGHT_STRING function runs weight strings on JSON as if they are on the JSON string representation. This matches that behavior just for the evalengine function specifically.
We also still want to have a correct weight string implementation that does honor the MySQL JSON type ordering rules. So we also test here some more cases and explicit type conversions for those functions. This uncovered a small missing but for temporal types which we didn't convert properly before but these conversion tests now expose.
Fixes #13641 and follow up on #13658 which was missing the correct JSON behavior. 
-   [x] Did the new or modified tests pass consistently …

evalengine: Fix JSON weight string computation

---

go/vt/vtorc/inst/instance_dao.go
go/vt/vtorc/logic/topology_recovery.go

This PR fixes a couple of logs in VTOrc - 
1. When VTOrc is configured to not run ERS, we see the following log come up `executeCheckAndRecoverFunction: ignoring analysisEntry that has no action plan: DeadPrimary`, but this doesn't say exactly why VTOrc is unable to fix `DeadPrimary`. A new log line has been added to this end, so that looking at the logs it is clear that VTOrc is not fixing the cluster because it is configured to not run ERS.
2. `auditType:forget-unseen alias: keyspace: shard: message:Forgotten instances: 0` gets printed on a timer and this provides no information at all. The code has been changed to only print this log line when an instance is actually forgotten. …

Fix a couple of logs in VTOrc

---

examples/backups/restart_tablets.sh
go/test/endtoend/reparent/plannedreparent/reparent_test.go
go/test/endtoend/reparent/utils/utils.go
go/vt/vtctl/grpcvtctldserver/server_slow_test.go
go/vt/vtctl/grpcvtctldserver/server_test.go
go/vt/vtctl/grpcvtctldserver/testutil/test_tmclient.go
go/vt/vtctl/reparentutil/planned_reparenter.go
go/vt/vtctl/reparentutil/planned_reparenter_flaky_test.go
go/vt/vtctl/reparentutil/util.go

This PR makes some improvements to the code of `PlannedReparentShard`. The following improvements have been made - 
1. We are now using `PrimaryTermStartTime` instead of `PrimaryAlias` from the shard record to find if a shard is being initialized or not. This is changed because I recently found out that we actually clear out the `PrimaryAlias` field in the shard record too when a PRIMARY tablet is deleted. However we don't clear out `PrimaryTermStartTime`. So the latter is better used for this check.
2. We shouldn't be ignoring errors in finding tablet positions given that `PlannedReparentShard` is meant to be run only when all the components are running fine.
3. We also now verify the assumption that all the tablets are reachable when we run `PlannedReparentShard`. The way we do this is …

Improvements to PRS

---

go/cmd/vtctldclient/command/schema.go

#10717 and #10716 removed the actual definitions when deprecating the flags, which causes cobra to completely error if they are provided, rather than provide a deprecation warning.
Examples:
```
$ vtctldclient ApplySchema --allow-long-unavailability
E0801 14:22:20.991123   23903 main.go:56] unknown flag: --allow-long-unavailability
$ vtctldclient ApplySchema --skip-preflight
E0801 14:22:48.317692   24011 main.go:56] unknown flag: --skip-preflight
```
https://github.com/vitessio/vitess/issues/6926

[vtctldclient] flags need to be defined to be deprecated

---

go/test/endtoend/onlineddl/vrepl_stress/onlineddl_vrepl_mini_stress_test.go

Previously `break` was operating on the `select`, which means there was no functional difference between the two select cases.
#6926 

[OnlineDDL] add label so break works as intended

---

go/vt/vtgate/tabletgateway.go

In https://github.com/vitessio/vitess/pull/13507 we stopped creating the buffer objects if buffering was disabled. However buffer shutdown was still being called on vtgate shutdown causing this panic
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1011a77a8]
goroutine 1310 [running]:
vitess.io/vitess/go/vt/vtgate/buffer.(*Buffer).shutdown(0x0)
vitess.io/vitess/go/vt/vtgate/buffer/buffer.go:239 +0x28
vitess.io/vitess/go/vt/vtgate/buffer.(*Buffer).Shutdown(0x0?)
vitess.io/vitess/go/vt/vtgate/buffer/buffer.go:234 +0x20
vitess.io/vitess/go/vt/vtgate.(*TabletGateway).Close(0x140000b4ee0, {0x101eba500?, 0x1400069a300?})
vitess.io/vitess/go/vt/vtgate/tabletgateway.go:204 +0x28
main.main.func2() …
```

vtgate tablet gateway buffering: don't shutdown if not initialized

---

go/vt/vttablet/onlineddl/executor.go

Closing a channel should be owned by the writer to the channel. This PR fixes a closed channel panic, described in https://github.com/vitessio/vitess/issues/13728.
Related discussion in `golang` google group: https://groups.google.com/g/golang-nuts/c/_Q6FCjWIr18/m/Wb_NlyusRL8J?pli=1
https://github.com/vitessio/vitess/issues/13728

Fix closed channel `panic` in Online DDL cutover

---

go/vt/schema/online_ddl.go
go/vt/sqlparser/ast_test.go
go/vt/sqlparser/comments.go
go/vt/vttablet/onlineddl/executor.go

In this PR we clone the `RevertMigration.Comments` map before iterating it. Thus, we solve an issue of concurrently reading/writing to same `Comments` map. See https://github.com/vitessio/vitess/issues/13699 for details.
To be backported to all supported versions.
Fixes https://github.com/vitessio/vitess/issues/13699

v16 backport: Solve RevertMigration.Comment read/write concurrency issue

---

go/vt/schema/online_ddl.go
go/vt/sqlparser/ast_test.go
go/vt/sqlparser/comments.go
go/vt/vttablet/onlineddl/executor.go

In this PR we clone the `RevertMigration.Comments` map before iterating it. Thus, we solve an issue of concurrently reading/writing to same `Comments` map. See https://github.com/vitessio/vitess/issues/13699 for details.
To be backported to all supported versions.
Fixes https://github.com/vitessio/vitess/issues/13699

v15 backport: Solve RevertMigration.Comment read/write concurrency issue

---

go/vt/vitessdriver/convert.go
go/vt/vitessdriver/driver.go
go/vt/vitessdriver/driver_test.go
go/vt/vitessdriver/fakeserver_test.go

Implements various new optional interfaces for the vtgate `database/sql` driver so that we can efficiently create connections using a shared config/converter, and can safely pull individual connections from the pool while assuring that there is no shared state pollution for concurrently opened connections.
Fixes #13703
n/a

go/vt/vitessdriver: implement driver.{Connector,DriverContext}

---

go/vt/schema/online_ddl.go
go/vt/servenv/version.go
go/vt/sqlparser/ast_test.go
go/vt/sqlparser/comments.go
go/vt/vttablet/onlineddl/executor.go

In this PR we clone the `RevertMigration.Comments` map before iterating it. Thus, we solve an issue of concurrently reading/writing to same `Comments` map. See https://github.com/vitessio/vitess/issues/13699 for details.
To be backported to all supported versions.
Fixes https://github.com/vitessio/vitess/issues/13699

v17 backport: Solve RevertMigration.Comment read/write concurrency issue

---

docker/release.sh
go/vt/servenv/version.go
java/client/pom.xml
java/example/pom.xml
java/grpc-client/pom.xml
java/jdbc/pom.xml
java/pom.xml

Includes the changes required to go back into dev mode (v17.0.2-SNAPSHOT) after the release of v17.0.1.

Back to dev mode after v17.0.1

---

go/cmd/vtcombo/plugin_dbddl.go

Meant to fix the race condition reported in https://github.com/vitessio/vitess/issues/13116
As mentioned in the bug report above, mitigating the race condition as follows:
> I've tested (and will subsequently propose via PR) a solution which simply modifies vtcombo's DBDDL plugin implementation to use a mutex which locks before executing globalCreateDb and releases the lock after that completes which effectively guarantees that access and incrementing of the uid variable is atomic in turn preventing the issue. This seems to have fixed the issue for me.
Fixes https://github.com/vitessio/vitess/issues/13116
-   [ ] Did the new or modified tests pass consistently …

Fix vtcombo DBDDL plugin race condition

---

go/vt/vttablet/onlineddl/executor.go

For some reason the backport bot did not run.
This backport is not strictly required, since the bug does not happen in `v16` - the channel wasn't being closed in this version. However, we do the backport so as to close the channel appropriately and release resources.
Closing a channel should be owned by the writer to the channel. This PR fixes a closed channel panic, described in https://github.com/vitessio/vitess/issues/13728.
Related discussion in `golang` google group: https://groups.google.com/g/golang-nuts/c/_Q6FCjWIr18/m/Wb_NlyusRL8J?pli=1
https://github.com/vitessio/vitess/issues/13728
-   [ ] Did the new or modified tests pass consistently locally and on …

v16 backport: Fix closed channel panic in Online DDL cutover

---

go/vt/vtgate/executor_test.go
go/vt/vtgate/planbuilder/show.go
go/vt/vtgate/planbuilder/testdata/show_cases.json

This PR follows up on https://github.com/vitessio/vitess/pull/12688. In https://github.com/vitessio/vitess/pull/12688 (release in `v17`) we made `vttablet` support `SHOW VITESS_MIGRATIONS` query in Query Executor. Now, in `v18`, we make `vtgate` direct `SHOW VITESS_MIGRATIONS` queries to the tablet's query service rather than construct a `SELECT` query.
Testing: `endtoend/onlineddl` already relies heavily on `SHOW VITESS_MIGRATIONS` in vtgate. This PR adds no tests -- all the existing `endtoend` tests will use the new logic and are expected to pass seamlessly.
Updated unit test files.
Fixes https://github.com/vitessio/vitess/issues/13706
https://github.com/vitessio/vitess/pull/12688
-   [ ] Tests were added …

Vtgate: pass 'SHOW VITESS_MIGRATIONS' to tablet's query executor

---

go/vt/schemadiff/schema_test.go

This PR adds a test to `schemadiff` that:
- Loads 8192 tables into one schema.
- Loads 8192 tables into another schema. All identical expect `20` that are modified.
- Diffs the two schemas, find those `500` diffs.
There is nothing interesting in particular about the loading and diffing logic itself -- the obejctive of this test is to show that `schemadiff` performs well with `8192` tables. Loading & diffing are all expected to be very quick. There's shouldn't be memory issues.
In local dev env this test runs at under `2sec`. Because this can run longer in GitHub CI, we expect up to `1min` total runtime.
Related: https://github.com/vitessio/vitess/issues/13692 ; the incentive for this PR is to see that `schemadiff` complies with massive schemas.
-   [ ] "Backport to:" labels have been …

schemadiff: add time measure test for massive schema load and diff

---

Makefile

This change allows passing in additional options for Go's `-ldflags`, for example to pass in `-s -w` to reduce binary size.
Fixes #13747 

build: Allow passing in custom -ldflags

---

go/test/endtoend/vtgate/foreignkey/fk_test.go
go/test/endtoend/vtgate/foreignkey/main_test.go
go/test/endtoend/vtgate/foreignkey/sharded_schema.sql
go/test/endtoend/vtgate/foreignkey/sharded_vschema.json
go/vt/vterrors/code.go
go/vt/vtgate/planbuilder/delete.go
go/vt/vtgate/planbuilder/operators/ast2op.go
go/vt/vtgate/planbuilder/plan_test.go
go/vt/vtgate/planbuilder/testdata/foreignkey_cases.json
go/vt/vtgate/planbuilder/testdata/vschemas/schema.json
go/vt/vtgate/vindexes/foreign_keys.go
go/vt/vtgate/vindexes/foreign_keys_test.go

This PR adds detection of child foreign keys that need handling at VTGate for an update or delete query.
This is currently used in delete planning to send delete queries with foreign keys to unsharded or shard scope for restrict cases and fails for all cascade cases.
- https://github.com/vitessio/vitess/issues/12967

Foreign Keys: `DELETE` planning

---

docker/k8s/vtadmin/Dockerfile

This PR uses NodeJS version 18 in the vtadmin Dockerfile.
The build has been validated on DockerHub after creating a test auto-build target against the `enable-vtadmin-docker-build` branch.
- Fixes https://github.com/vitessio/vitess/issues/13752 

Use NodeJS v18 in VTAdmin Dockerfile

---

go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go

This fixes CI flakiness around `--postpone-completion` tests. In various tests in `onlineddl_scheduler` we validate that a migration is `ready_to_complete` (or also validate that it is _not_). In this PR we implement a wait-for logic rather than a single instant check. 
Example failure: https://github.com/vitessio/vitess/actions/runs/5805367546/job/15736748636?pr=13746

CI: fix onlineddl_scheduler flakiness

---

go/vt/vtctl/workflow/traffic_switcher.go
go/vt/wrangler/traffic_switcher.go

This addresses comments from Deepthi after [the original PR](https://github.com/vitessio/vitess/pull/13656) was merged.
- Follow-up to: https://github.com/vitessio/vitess/pull/13656

Minor --initialize-target-sequences followups

---

go/test/endtoend/backup/vtctlbackup/backup_utils.go
go/vt/vttablet/tabletmanager/restore.go

Manually recreated the changes from #13339 to 16.0, rather than doing a complex merge.
FIXME: the changes are currently not tested, because I am not sure where should we invoke `verifyRestorePositionAndTimeStats()`. The test case in `main` where I was doing this is not present in `release-16.0`
#13339 

Manual cherry-pick of 13339

---

go/vt/binlog/binlogplayer/mock_dbclient.go
go/vt/vttablet/tabletmanager/rpc_vreplication_test.go

This fixes a timing issue that could result in the tabletmanager's `TestMoveTables` unit test causing it to fail like this with one or more of the `set foreign_key_checks` or `set @@session.sql_mode` queries coming in an unexpected order:
```
2023-08-10T15:09:33.7869997Z     vdbclient.go:90: DBClient query: set foreign_key_checks=1
2023-08-10T15:09:33.7870724Z     vdbclient.go:90: DBClientMock: query: set foreign_key_checks=1, want select pos, stop_pos, max_tps, max_replication_lag, state, workflow_type, workflow, workflow_sub_type, defer_secondary_keys from _vt.vreplication where id=1
2023-08-10T15:09:33.7871753Z     vdbclient.go:90: DBClient query: SET @@session.sql_mode='ONLY_FULL_GROUP_BY,NO_AUTO_VALUE_ON_ZERO,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO, …
```

Flakes: remove non-determinism from vtctldclient MoveTables unit test

---

.github/workflows/update_golang_version.yml

This PR modifies the auto-golang-upgrade workflow to only run on the `vitessio/vitess` repository.

Run auto golang upgrade only on vitessio/vitess

---

go/flags/endtoend/vtbackup.txt
go/flags/endtoend/vtctld.txt
go/flags/endtoend/vttablet.txt
go/vt/mysqlctl/azblobbackupstorage/azblob.go

We do this by adding a new flag that defaults to the buffer size that was previously used in Vitess prior to 16.0.
In [16.0 we upgraded our internal go dependencies]( https://github.com/vitessio/vitess/commit/c67c79097baf05a5112e2d64c63b4d46cccba3a5) and in doing so we upgraded the version of [azure-storage-blob-go library](https://github.com/Azure/azure-storage-blob-go/tree/0.15) we use from v0.10.0 to v0.15.0.
And [in v0.11.0 the library increased the size of the `BlockBlobMaxStageBlockBytes` const from 100MiB to 4GiB](https://github.com/Azure/azure-storage-blob-go/commit/9e15f04c6946bd987ea313f434a2cdc0b1c0f609). We used that in setting the size of the (static) buffer to use when streaming a file to the Azure Blob service indirectly here: …

Address vttablet memory usage with backups to Azure Blob Service

---

go/vt/mysqlctl/backupengine.go
go/vt/mysqlctl/builtinbackupengine.go
go/vt/mysqlctl/builtinbackupengine_test.go
go/vt/mysqlctl/fakebackupengine.go
go/vt/mysqlctl/xtrabackupengine.go
go/vt/mysqlctl/xtrabackupengine_test.go
go/vt/vttablet/tabletmanager/rpc_backup.go

Fixes https://github.com/vitessio/vitess/issues/13756: during an incremental backup (implemented by `builtinengine` and based on binlog file copy), the backup tablet should not be drained.
To be backported to `release-17.0`.
- Fixes: https://github.com/vitessio/vitess/issues/13756

Do not drain tablet in incremental backup

---

go/test/endtoend/backup/vtctlbackup/backup_utils.go
go/test/endtoend/backup/vtctlbackup/pitr_test_framework.go
go/vt/mysqlctl/backup.go
go/vt/mysqlctl/builtinbackupengine.go
go/vt/mysqlctl/mysqld.go

This PR addresses flakiness in `backup_pitr` family of CI tests. One major cause for flakiness has been identified, and it is an issue of consistent read-after-write. The test framework runs many backups, either full or incremental. Whenever the framework runs a backup, it reads the manifest created by the backup. Since the backup itself does not return the manifest - not does it even return the backup name (about to be changed) - the way to read the backup's manifest is to run `vtctldclient GetBackups`, which lists all known backups, then reading the last one on the list - supposedly the most recent backup, which we've just executed.
As it turns out, that list can be stale. Depending on which topo server serves it, it may actually miss that last backup we've just executed. It's one …

Fixing `backup_pitr` flaky tests via wait-for loop on topo reads

---

go/vt/vtgate/schema/tracker.go

Fixes a race condition between vtgate schema tracker and vschema manager which results in a panic when vschema manager attempts to iterate the map provided by the schema tracker. Updates the schema tracker to return a shallow copy of tables and views.
Fixes https://github.com/vitessio/vitess/issues/13672
n/a

vtgate: fix race condition iterating tables and views from schema tracker

---

go/test/endtoend/reparent/utils/utils.go

The reparent upgrade/downgrade workflows have been repeatedly failing in Actions due to running out of disk space. For example:
```
Error: -15T21:51:23.558594Z 1 [ERROR] [MY-012144] [InnoDB] posix_fallocate(): Failed to preallocate data for file mysql.ibd, desired size 1048576 bytes. Operating system error number 28. Check that the disk is not full or a disk quota exceeded. Make sure the file system supports this function. Refer to your operating system documentation for operating system error code information.
Warning: 5T21:51:23.558689Z 1 [Warning] [MY-012638] [InnoDB] Retry attempts for writing partial data failed.
Error: -15T21:51:23.558704Z 1 [ERROR] [MY-012639] [InnoDB] Write to file mysql.ibd failed at offset 8388608, 1048576 bytes should have been written, only 0 were written. …
```

Flakes: Delete VTDATAROOT files in reparent test teardown within CI

---

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
go/test/endtoend/vtgate/queries/misc/misc_test.go
go/vt/vtgate/engine/filter.go
go/vt/vtgate/evalengine/eval_result.go
go/vt/vtgate/planbuilder/operators/joins.go
go/vt/vtgate/planbuilder/testdata/from_cases.json

Fixes three one-line issues.
1. Join predicates on outer joins that only depend on the RHS of the join turns join into an inner join
2. Projection not handling types correctly would fail some aggregation queries
3. Filter checking if values are `1` instead of using MySQLs coercion to bool
This was found with automated query fuzzing (https://github.com/vitessio/vitess/issues/13279)
Backport of https://github.com/vitessio/vitess/pull/13332

[16.0] bugfixes: collection of fixes to bugs found while fuzzing

---

go/vt/vtgate/engine/cached_size.go
go/vt/vtgate/engine/fk_cascade.go
go/vt/vtgate/engine/fk_cascade_test.go

This PR adds an engine primitive that can execute a foreign key cascade.
The planner support to support this use case is still not done.
- #12967 

Add Foreign key Cascade engine primitive

---

go/test/endtoend/vreplication/vdiff_helper_test.go

During a VDiff2 in vreplication e2e tests there is a check that the ETA for a VDiff2 Progress command is in the future. We have added a jitter of 1 second to account for time precision. However we sometimes get a difference of more than 1s between the ETA and the current time, empirically seen 2s when it has failed, but presumably it can be higher. Commenting that check to reduce the flakes (but keeping the code here for now in case we want to fix and re-enable it).

Flakes: skip flaky check that ETA for a VReplication VDiff2 Progress command is in the future.

---

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
go/test/endtoend/vtgate/queries/misc/misc_test.go
go/vt/vtgate/engine/filter.go
go/vt/vtgate/evalengine/eval_result.go
go/vt/vtgate/planbuilder/testdata/from_cases.json

Fixes three one-line issues.
1. Join predicates on outer joins that only depend on the RHS of the join turns join into an inner join
2. Projection not handling types correctly would fail some aggregation queries
3. Filter checking if values are `1` instead of using MySQLs coercion to bool
This was found with automated query fuzzing (https://github.com/vitessio/vitess/issues/13279)
Backport of https://github.com/vitessio/vitess/pull/13332

[15.0] bugfixes: collection of fixes to bugs found while fuzzing

---

go/cmd/vtctldclient/command/backups.go

Presumably a copy-paste error that got missed, it was previously reading all its options (except `--incremental-from-pos`) from the flags defined on the `Backup` command, which effectively meant it accepted those flags on the
command line but disregarded their actual values.
Yikes!
Fixes #13812 

Fix `BackupShard` to get its options from its own flags

---

go/test/endtoend/vreplication/cluster_test.go

Multiple replication tests have started failing because the disk space if filling up. This PR cleans up the vtdataroot for all vreplication e2e tests while setting up the test cluster.

Flakes: empty vtdataroot before starting a new vreplication e2e test

---

go/vt/vttablet/tabletserver/query_engine.go
go/vt/vttablet/tabletserver/query_engine_test.go
go/vt/vttablet/tabletserver/query_executor.go
go/vt/vttablet/tabletserver/tabletenv/stats.go
go/vt/vttablet/tabletserver/tabletserver.go

Adds two new `vttablet` metrics that mirror existing metrics, except they are labeled with tablet type. We need the tablet type label in these metrics, and it's better to apply the label at the source instead of downstream in our metrics pipeline. Adding the tablet type label downstream causes issues when the tablet type changes (as a result of reparenting) because we end up with a new series but the counters aren't reset, which leads to incorrect values for PromQL functions like `rate` or `increase`.
The new metrics are:
* `QueryEngine#queryCountsWithTabletType` - `stats.CountersWithMultiLabels`
* `tabletenv.Stats#QueryTimingsByTabletType` - `servenv.TimingsWrapper`
Added new metrics instead of adding labels to existing metrics to avoid a breaking change.
`QueryTimingsByTabletType` is …

Add 2 new metrics with tablet type labels

---

changelog/18.0/18.0.0/summary.md
examples/common/scripts/etcd-up.sh
go/test/endtoend/cluster/topo_process.go
go/test/endtoend/clustertest/etcd_test.go

Etcd v3.0 — released _7 years ago_ — had major rewrites of the API and storage layer (data model): https://www.infoworld.com/article/3090223/coreos-ramps-up-container-scaling-with-etcd-30.html 
In order to ease the transition, they supported using 3.x in v2 mode via:
- The etcd `--enable-v2=true` flag
- The `ETCDCTL_API=2` env variable
We've been using these in Vitess to support explicit v2 API usage such as `mkdir` (which is gone, and generally unnecessary because you don't need to create empty prefix keys). This was explicitly needed as starting in 3.4 `--enable-v2` defaulted to false: https://etcd.io/docs/v3.4/upgrades/upgrade_3_4/
The problem with using etcd in v2 mode, however, is that by default reads from replicas/followers are not consistent — i.e. you can get stale reads by …

Remove explicit usage of etcd v2 (api and storage)

---

go/vt/vterrors/errors_test.go
go/vt/vterrors/vterrors.go

Race conditions around access to the `vterrors`.`logErrStacks` variable have been causing different tests to fail with errors like:
While this fix is not addressing the location where the backed flag is actually getting evaluated on load, most likely, there are no competing goroutines. So this should fix a significant number of such flakes.
```
Write at 0x0000042aba01 by goroutine 36851:
github.com/spf13/pflag.newBoolValue()
/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/bool.go:16 +0x70
github.com/spf13/pflag.(*FlagSet).BoolVarP()
/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/bool.go:55 +0x80
github.com/spf13/pflag.(*FlagSet).BoolVar()
/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/bool.go:50 +0x57
vitess.io/vitess/go/vt/vterrors.RegisterFlags() …
```

Flakes: Synchronize access to logErrStacks in vterrors

---

test.go

This PR skips the build of VTAdmin in Docker tests initiated by `test.go`.
- Fixes https://github.com/vitessio/vitess/issues/13837

Skip VTAdmin build in Docker tests

---

.github/workflows/update_golang_version.yml
go/tools/go-upgrade/go-upgrade.go
go/tools/go-upgrade/go-upgrade_test.go

This PR fixes a small issue that was observed during the CRON to upgrade the golang version to 1.21.0. The regular expression was not working properly in `go.mod` leading to `go mod tidy` failures.
- Fixes https://github.com/vitessio/vitess/issues/13847

Fix regular expression issue in Golang Upgrade and remove `release-14.0` from target branch

---

.github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml
.github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
.github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
.github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml
.github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml
.github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml

This PR bumps the golang version used in the `release-17.0` upgrade test to `go1.21.0`. This is done to be compatible with the incoming changes made on main in #13853

[release-17.0] Bump upgrade tests to `go1.21.0`

---

go/test/endtoend/vreplication/vreplication_test.go

The `vreplication_copy_parallel` test had been flaky and has become even more so since moving to larger GitHub Actions runners. It is failing several times in a row now in various PRs, with the failure always seeming to be this:
```
=== NAME  TestVreplicationCopyParallel/shardOrders
vreplication_test.go:1426: 
Error Trace:	/home/runner/work/vitess/vitess/go/test/endtoend/vreplication/vreplication_test.go:1426
/home/runner/work/vitess/vitess/go/test/endtoend/vreplication/vreplication_test.go:1081
Error:      	Received unexpected error:
exit status 1
Test:       	TestVreplicationCopyParallel/shardOrders
Messages:   	SwitchTraffic Error: exit status 1: E0825 16:01:39.730006   46126 main.go:96] E0825 16:01:39.729759 vtctl.go:2205] 
cannot switch traffic for workflow o2c at this time: …
```

Flakes: Improve reliability of vreplication_copy_parallel test

---

go/test/endtoend/onlineddl/revert/onlineddl_revert_test.go
go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
go/vt/vttablet/onlineddl/executor.go
go/vt/vttablet/onlineddl/schema.go

#11910 was merged `Dec 2022`, but still did not make it to `v15`. This bugfix is important and since we still support `v15` it should be backported.
---
This PR formalizes what "immediate operations" are: 
Immediate operations are ones that can be performed within a split second, or rather, do not require long
running processes. Immediate operations are:
- CREATE TABLE
- DROP TABLE (which we convert into RENAME)
- All VIEW operations
- An INSTANT DDL accompanied by relevant ddl strategy flags
Non immediate operations are:
- A gh-ost migration
- A vitess (vreplication) migration
In #11898 we find that `ALTER VIEW` and instant DDLs do not respect `--postpone-completion`. This PR solves that for both, and all other, cases. Any "immediate operation" now respects that flag, including REVERTs …

v15 backport: Onlineddl: formalize "immediate operations", respect --postpone-completion strategy flag

---

docker/bootstrap/build.sh

It seems like this was added back in 2015 when vitess used to use raw
go get commands to build the image, the reasoning behind it was to ensure
that the image has the most recent dependencies. This is no longer needed
because in the dockerfile we correctly add go.* dep manifests and call go mod download.
PR where this was added:
https://github.com/vitessio/vitess/pull/665

docker/bootstrap: remove --no-cache flag

---

go/test/endtoend/preparestmt/stmt_methods_test.go
go/vt/vtgate/semantics/semantic_state.go

The vtgate planner and runtime was tripping up itself, trying to hash a weightstring value but getting the typing wrong, which lead to this error being produced. 
As of the merging of #13450, we started using the hashing distinct a lot more than before, and these errors have started popping up.
I recommend we backport this fix - we used this hashing distinct in earlier releases, just not as much as today, so this bug is probably there in earlier releases as well. That combined with it being a pretty small and safe fix makes me say backport.
Fixes #13764
-   [x] Documentation was added …

Fix for "text type with an unknown/unsupported collation cannot be hashed" error

---

go/ioutil/timeout_closer.go
go/vt/srvtopo/resilient_server_test.go
go/vt/vtctl/grpcvtctldserver/server_test.go

This was merged while we also merged the context leak fixes, so now `main` is broken. This fixes it.
See #13835 where this was refactored and #13860 which was merged concurrently.

Fix merge conflict with new tests

---

go/cmd/vttestserver/vttestserver_test.go
go/test/utils/noleak.go
go/vt/vtgate/executor_framework_test.go
go/vt/vtgate/schema/tracker.go

This ensures that we always set up the sandbox instances first with the correct vschema etc. so that anything that starts goroutines afterwards like `newTestResolver` won't race with reading the vschema while it still might be written.

Fix setup order to avoid races

---

go/vt/wrangler/fake_dbclient_test.go
go/vt/wrangler/keyspace.go
go/vt/wrangler/testlib/version_test.go
go/vt/wrangler/version.go

Miscellaneous code cleanup in `go/vt/wrangler` of completely unused functions. h/t to `staticcheck` which did 99.9999% of the work here
-

[wrangler] cleanup unused functions

---

go/hack/hack.go
go/hack/runtime.go
go/mysql/collations/charset/korean/tables.go
go/mysql/collations/charset/simplifiedchinese/tables.go
go/mysql/collations/colldata/mysqlucadata.go
go/mysql/collations/colldata/uca_tables_test.go
go/mysql/collations/internal/uca/contractions.go
go/mysql/collations/internal/uca/layout.go
go/mysql/collations/tools/makecolldata/codegen/tablegen.go

The collations and hack packages use deprecated reflect usage, this fixes that up. It also removes some unused bits of code as well.

Clean up deprecated slice header usage and unused code

---

go/vt/sqlparser/sql.go
go/vt/sqlparser/sql.y
go/vt/sqlparser/tracked_buffer_test.go

We should not normalize this to uppercase, as this option is case-sensitive.
- Found in #13866 which addresses #13865
- Fixes: https://github.com/vitessio/vitess/issues/13887

sqlparser: Tablespace option is case sensitive

---

go/mysql/collations/tools/colldump/Dockerfile
go/mysql/collations/tools/colldump/colldump.cc
go/mysql/collations/tools/colldump/colldump.sh

The metadata for the collation tables that we use in our `mysql/collations` implementation is extracted with a simple script that links against MySQL's `strings.so` and dumps the data. This same data could be dumped by crafting SQL queries on a live MySQL instance, but we've opted to write a script and link it against MySQL's libraries for performance and ease of development.
The process of linking and running the script, however, has historically been very complex. The script was kept on a fork of `mysql-server` and you had to download and compile the fork to make it run.
This PR remediates this situation by vendoring the script itself in this repository and adding a Dockerfile that reliably builds and links the dumper script.
cc @dbussink @frouioui 
-   [x] "Backport to:" labels have …

collations: implement collation dumping as a docker image

---

go/vt/vttablet/endtoend/healthstream_test.go
go/vt/vttablet/endtoend/main_test.go
go/vt/vttablet/tabletserver/health_streamer.go

Closes https://github.com/vitessio/vitess/issues/13894
`vttablet` will skip internal-table names when reporting RealtimeStats. As result, `vtgate` will never learn about those.
- https://github.com/vitessio/vitess/issues/13894
- https://github.com/vitessio/vitess/issues/12967

vttablet: do not notify `vtgate` about internal tables

---

examples/compose/client.go
go/cmd/vtclient/vtclient.go
go/cmd/vtgate/vtgate.go
go/netutil/netutil.go
go/netutil/netutil_test.go
go/test/endtoend/tabletgateway/buffer/buffer_test_helpers.go
go/test/endtoend/vreplication/cluster_test.go
go/test/endtoend/vtgate/keyspace_watches/keyspace_watch_test.go
go/tools/asthelpergen/asthelpergen.go
go/vt/mysqlctl/grpcmysqlctlclient/client.go
go/vt/tableacl/testlib/testlib.go
go/vt/tlstest/tlstest.go
go/vt/topo/memorytopo/memorytopo.go
go/vt/topotools/shard_test.go
go/vt/vttablet/tabletserver/gc/tablegc.go
go/vt/vttablet/tabletserver/tabletserver_test.go
go/vt/vttablet/tabletserver/throttle/throttler.go
go/vt/vttablet/tabletserver/vstreamer/packet_size_test.go
go/vt/vttest/environment.go
go/vt/vttls/crl.go
test/client/client.go

- update deprecated grpc dial options
- replace deprecated `strings.Title` with recommended replacement
- RevokedCertificates=>RevokedCertificateEntries
- Stop seeding rand with timestamps, it no longer auto-seeds with a constant (See https://github.com/golang/go/issues/56319)
#13877 

[staticcheck] Cleanup deprecations

---

go/vt/vtexplain/vtexplain_vtgate.go
go/vt/vtgate/legacy_scatter_conn_test.go
go/vt/vtgate/tabletgateway.go
go/vt/vtgate/tabletgateway_test.go
go/vt/vtgate/vstream_manager_test.go
go/vt/vtgate/vtgate.go

The fake resolver we use for vtexplain didn't get the correct context passed in, which can result in it leaking resources as the context is never cancelled and thus resources not cleaned up.
This was missed in #13835 

vtexplain: Fix passing through context for cleanup

---

go/test/endtoend/messaging/message_test.go
go/vt/vtgate/vcursor_impl_test.go
go/vt/vtgate/vindexes/consistent_lookup.go
go/vt/vtgate/vstream_manager_test.go
go/vt/vtorc/inst/instance_dao.go
go/vt/vttablet/tabletmanager/rpc_vreplication.go

Removes duplicate imports and tidies imports in any file I touched along the way.
#13877 

[misc] tidy imports

---

go/mysql/flavor_filepos.go
go/test/endtoend/backup/vtctlbackup/backup_utils.go
go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go
go/test/endtoend/onlineddl/vtctlutil.go
go/test/endtoend/onlineddl/vtgate_util.go
go/test/endtoend/vault/vault_test.go
go/test/endtoend/vreplication/helper_test.go
go/test/endtoend/vreplication/partial_movetables_seq_test.go
go/test/endtoend/vreplication/vdiff_helper_test.go
go/test/endtoend/vreplication/vreplication_test.go
go/test/endtoend/vtgate/queries/random/query_gen.go
go/tools/asthelpergen/copy_on_rewrite_gen.go
go/trace/trace_test.go
go/vt/mysqlctl/tmutils/schema_test.go
go/vt/sqlparser/ast_test.go
go/vt/sqlparser/parse_test.go
go/vt/sqlparser/precedence_test.go
go/vt/throttler/max_replication_lag_module.go
go/vt/topo/consultopo/server.go
go/vt/vtadmin/cluster/resolver/resolver_test.go
go/vt/vtorc/discovery/queue.go
go/vt/vttablet/onlineddl/executor.go
go/vt/vttablet/tabletmanager/restore.go
go/vt/vttablet/tabletmanager/rpc_replication.go
go/vt/vttablet/tabletmanager/vdiff/table_differ.go
go/vt/vttablet/tabletserver/gc/tablegc.go
go/vt/vttablet/tabletserver/messager/message_manager.go
go/vt/vttablet/tabletserver/tabletserver_test.go

- unnecessary sprintf/println
- avoiding deep equality on errors
- reversing conditional orders (this one is new to me! see https://staticcheck.dev/docs/checks/#ST1017)
- last of the "unused code" violations (i think)
#13877 

[staticcheck] miscellaneous tidying

---

examples/common/scripts/etcd-up.sh
examples/common/scripts/mysqlctl-up.sh
examples/common/scripts/vtgate-up.sh
examples/common/scripts/vtorc-up.sh
examples/common/scripts/vttablet-up.sh
examples/local/101_initial_cluster.sh
examples/local/401_teardown.sh

Misc improvements, one per commit:
- Make etcd-up.sh output consistent with vtctld-up.sh.
- Remove --server from vtctldclient in 101_initial_cluster.sh.
- Make mysqlctl-up.sh output consistent with vtctld-up.sh.
- Make vttablet-up.sh output consistent with vtctld-up.sh.
- Make vtorc-up.sh output consistent with vtctld-up.sh.
- Make vtgate-up.sh output consistent with vtctld-up.sh.
- Start mysqlctls in parallel in 101_initial_cluster.sh.
- Stop mysqlctls in parallel in 401_teardown.sh.
I have more ideas, but not more time for this PR, so this work will have to be continued by someone else.  Some ideas:
- add Access vtctld at <url>
- add Access vttablet at <url>
- remove --server from vtctldclient in utils.sh
- do not leak global variables PRIMARY_TABLET and _  in utils.sh
- add starting …

Misc Local Install improvements.

---

go/vt/vtgate/executor_test.go

This test was using invalid SQL which is very noisy in the logs. 

Use correct syntax in test

---

go/vt/vtctl/vtctl.go
go/vt/wrangler/materializer.go
go/vt/wrangler/materializer_test.go
go/vt/wrangler/workflow.go

Reverts vitessio/vitess#13858. 
This has been implemented in v18 at https://github.com/vitessio/vitess/pull/13895.

Revert "[release-16.0] MoveTables: add flag to specify that routing rules should not be created when a movetables workflow is created"

---

go/test/endtoend/throttler/util.go
go/vt/vtgate/planbuilder/operators/route_planning.go

The nil one is subtle and due to a quirk in Go, see https://go.dev/play/p/dLYXDE73nQS for an example of what's happening and how this fixes it.
#13877 

[staticcheck] Last few staticchecks!

---

go/vt/vttablet/grpctmserver/server.go
go/vt/vttablet/tmrpctest/test_tm_rpc.go

Silences the noise coming from `CheckThrottler` calls.
Fixes https://github.com/vitessio/vitess/issues/13924

Silence 'CheckThrottler' gRPC calls

---

go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go
go/test/endtoend/onlineddl/vtgate_util.go
go/vt/vttablet/onlineddl/executor.go
go/vt/vttablet/onlineddl/schema.go

This PR ensures to set `completed_timestamp` when transitioning a migration into `cancelled` or `failed` state. This, in turn, ensures a proper cleanup (destorying the migration's artifacts).
It also retroactively fixes `completed_timestamp` in all cases where it's left `nil` on `cancelled`.
- Fixes https://github.com/vitessio/vitess/issues/13927
- Generally similar to https://github.com/vitessio/vitess/pull/8500/files#diff-059c9f46e8d270d9c5514ef2b08679035eb0daaa8d95074e34ef43a81d50dc37

OnlineDDL: fix nil 'completed_timestamp' for cancelled migrations

---

go/vt/sqlparser/ast_funcs.go
go/vt/vtgate/planbuilder/operator_transformers.go
go/vt/vtgate/planbuilder/operators/SQL_builder.go
go/vt/vtgate/planbuilder/operators/delete.go
go/vt/vtgate/planbuilder/operators/insert.go
go/vt/vtgate/planbuilder/operators/update.go

In order to allow DML to be used inside subqueries, we need the DML plan path to use the `sql_builder` path for building the query. It's just cleaner to use mostly the same codepaths and share what we can.
Tracking issue https://github.com/vitessio/vitess/issues/11626
Needed by https://github.com/vitessio/vitess/pull/13750

refactor: move DML logic to sql_builder.go

---

go/test/endtoend/vtgate/queries/misc/misc_test.go
go/vt/schemadiff/schema_test.go
go/vt/vtgate/planbuilder/testdata/from_cases.json
go/vt/vtgate/planbuilder/testdata/unsupported_cases.json
go/vt/vtgate/semantics/analyzer.go
go/vt/vtgate/semantics/binder.go
go/vt/vtgate/semantics/early_rewriter.go
go/vt/vtgate/semantics/early_rewriter_test.go

This PR rewrites `USING` condition to `ON` instead of `WHERE` to avoid the issue mentioned in https://github.com/vitessio/vitess/issues/13929.
- Fixes https://github.com/vitessio/vitess/issues/13929

Rewrite `USING` to `ON` condition for joins

---

go/test/endtoend/vtgate/foreignkey/fk_test.go
go/vt/sqlparser/ast_funcs.go
go/vt/vterrors/code.go
go/vt/vtgate/engine/cached_size.go
go/vt/vtgate/engine/fk_verify.go
go/vt/vtgate/engine/fk_verify_test.go
go/vt/vtgate/engine/primitive.go
go/vt/vtgate/planbuilder/delete.go
go/vt/vtgate/planbuilder/fk_verify.go
go/vt/vtgate/planbuilder/operator_transformers.go
go/vt/vtgate/planbuilder/operators/SQL_builder.go
go/vt/vtgate/planbuilder/operators/ast2op.go
go/vt/vtgate/planbuilder/operators/ast2op_test.go
go/vt/vtgate/planbuilder/operators/ast_to_delete_op.go
go/vt/vtgate/planbuilder/operators/ast_to_update_op.go
go/vt/vtgate/planbuilder/operators/fk_cascade.go
go/vt/vtgate/planbuilder/operators/fk_verify.go
go/vt/vtgate/planbuilder/operators/horizon_planning.go
go/vt/vtgate/planbuilder/plan_test.go
go/vt/vtgate/planbuilder/plancontext/planning_context.go
go/vt/vtgate/planbuilder/testdata/foreignkey_cases.json
go/vt/vtgate/planbuilder/update.go
go/vt/vtgate/vindexes/foreign_keys.go
go/vt/vtgate/vindexes/foreign_keys_test.go
go/vt/vtgate/vindexes/vschema.go

This PR adds two planning support
- FK Cascade that validates that value exists on the parent table.
- FK Restrict that validates that the value does not exist on the child table.
- https://github.com/vitessio/vitess/issues/12967

Update Cascade Planning leading to Foreign key constraint verification

---

go/cmd/vtctld/cli/cli.go
go/cmd/vtctld/cli/plugin_azblobbackupstorage.go
go/cmd/vtctld/cli/plugin_cephbackupstorage.go
go/cmd/vtctld/cli/plugin_consultopo.go
go/cmd/vtctld/cli/plugin_etcd2topo.go
go/cmd/vtctld/cli/plugin_filebackupstorage.go
go/cmd/vtctld/cli/plugin_gcsbackupstorage.go
go/cmd/vtctld/cli/plugin_grpctabletconn.go
go/cmd/vtctld/cli/plugin_grpctmclient.go
go/cmd/vtctld/cli/plugin_grpcvtctldserver.go
go/cmd/vtctld/cli/plugin_grpcvtctlserver.go
go/cmd/vtctld/cli/plugin_grpcvtgateconn.go
go/cmd/vtctld/cli/plugin_opentracing.go
go/cmd/vtctld/cli/plugin_opentsdb.go
go/cmd/vtctld/cli/plugin_prometheusbackend.go
go/cmd/vtctld/cli/plugin_s3backupstorage.go
go/cmd/vtctld/cli/plugin_zk2topo.go
go/cmd/vtctld/cli/schema.go
go/cmd/vtctld/docgen/main.go
go/cmd/vtorc/cli/cli.go
go/flags/endtoend/vtctld.txt
go/flags/endtoend/vtorc.txt
go/vt/servenv/servenv.go

this moves generic stuff into servenv to support cobra commands, fixes some missing glog flags in the previous `vtorc` move, and migrates `vtctld` to cobra
docs: https://github.com/vitessio/website/pull/1578
#13918 

[vtctld] more cobra binaries

---

go/test/endtoend/vtgate/schema/schema_test.go
go/vt/schemamanager/tablet_executor.go
go/vt/schemamanager/tablet_executor_test.go
go/vt/sqlparser/ast_test.go

As described in https://github.com/vitessio/vitess/issues/13950, when DDL strategy is `--allow-zero-in-date`, `TabletExecutor` attempts to edit the SQL; but with `--batch-size` the SQL (`--sql` or `--sql-file`) could be multiple statements. In this PR `TabletExecutor` is able to parse and edit the SQL even if it contains multiple statements.
Added the necessary tests that would have prevented the bug in #13693
- Fixes https://github.com/vitessio/vitess/issues/13950
- Continues https://github.com/vitessio/vitess/pull/13693
- Objective: https://github.com/vitessio/vitess/issues/13692
- …

Fix `ApplySchema --batch-size` with ` --allow-zero-in-date`

---

changelog/18.0/18.0.0/summary.md
go/flags/endtoend/vtorc.txt
go/test/endtoend/vtorc/general/vtorc_test.go
go/test/endtoend/vtorc/utils/utils.go
go/vt/vtorc/config/config.go
go/vt/vtorc/inst/analysis.go
go/vt/vtorc/inst/analysis_dao.go
go/vt/vtorc/inst/analysis_dao_test.go
go/vt/vtorc/logic/tablet_discovery.go
go/vt/vtorc/logic/topology_recovery.go
go/vt/vtorc/logic/topology_recovery_test.go
go/vt/vtorc/test/recovery_analysis.go

This PR introduces a new VTOrc flag `--change-tablets-with-errant-gtid-to-drained` that allows the users to toggle the ability of VTOrc to change the tablet type of tablets with errant GTIDs to `DRAINED`. By default, the flag is false.
This feature allows the users to configure VTOrc such that any tablet that encounters errant GTIDs is automatically taken out of the serving graph. These tablets can then be inspected for what the errant GTIDs are, and once fixed, they can rejoin the cluster.
When VTOrc changes the tablet to a DRAINED type, it also forgets it from its own datastore, and the user has to change the tablet back to its original type for VTOrc to start monitoring it again.
- Fixes https://github.com/vitessio/vitess/issues/13872
-   [x] "Backport to:" labels have been added if …

VTOrc converts a tablet to DRAINED type if it detects errant GTIDs on it

---

go/vt/vtgate/vindexes/vschema.go
go/vt/vtgate/vindexes/vschema_test.go
go/vt/wrangler/materializer_test.go

Changing the recommended [vindex type](https://vitess.io/docs/reference/features/vindexes/#predefined-vindexes) from `hash` to `xxhash` deals with usage of `hash` — which is based on NULL-KEY 3DES (not actually used for cryptography in Vitess but hashing keyspace IDs) — getting flagged because [DES is considered insecure](https://en.wikipedia.org/wiki/Data_Encryption_Standard). And while it's not actually used for cryptography in Vitess it can be difficult to work around appropriate controls that prohibit its use for any reason. `xxhash` should also be significantly faster overall so we should generally recommend that over `hash` (3DES) in Vitess going forward.
The immediate practical impact of this change is that the [`CreateLookupVindex`](https://vitess.io/docs/reference/vreplication/cre …

Change internal vindex type recommendation for integrals to xxhash

---

go/vt/vttablet/tabletmanager/rpc_vreplication_test.go
go/vt/vttablet/tabletmanager/vreplication/external_connector_test.go
go/vt/vttablet/tabletmanager/vreplication/framework_test.go
go/vt/vttablet/tabletmanager/vreplication/journal_test.go
go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go
go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go
go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
go/vt/vttablet/tabletmanager/vreplication/vreplicator_test.go

Upon reparent (planned or not), we were seeing a loss of progress in migrations (eg. progress dropping from 90% to 0%). In diving deeper, I noticed that the underlying vreplication stream would continue along, as advertised, and the migration would actually complete, but at < 100% completion reported (however, the percentages before the reparent and after completion would add up to 100%, which pointed me in the right direction). 
I found that the rows_copied counter was reset in vreplication upon reparent, but the actual position was kept correct, so this is more of a cosmetic issue, but alarming to see your whole migration drop to 0% on a reparent
[Slack conversation](https://vitess.slack.com/archives/C0PQY0PTK/p1694099890304929)
Fixes https://github.com/vitessio/vitess/issues/13948
- …

copy over existing vreplication rows copied to local counter if resuming from another tablet

---

go/vt/vtgate/vtgate.go
go/vt/vttablet/tabletserver/tabletenv/config.go

This Pull Request re-define four flags (two in VTGate and two in VTTablet), https://github.com/vitessio/vitess/pull/13939 recently removed their definition and marked them as deprecated.
- Fixes https://github.com/vitessio/vitess/issues/13974

Fix missing deprecated flags in `vttablet` and `vtgate`

---

go/vt/discovery/tablet_picker_test.go
go/vt/vttablet/tabletmanager/vdiff/action.go
go/vt/vttablet/tabletmanager/vdiff/action_test.go

The documented default value for the `--source_cell` and `--target_cell` flags is 'any available cell': https://vitess.io/docs/reference/vreplication/vdiff/#parameters
And you can see that in the help output as well:
```
❯ vtctlclient vdiff -- --help
W0913 13:58:48.039694   71302 log.go:39] Failed to read in config : Config File "vtconfig" Not Found in "[/Users/matt/git/vitess]". This is optional, and can be ignored if you are not using config files. For a detailed explanation, see https://github.com/vitessio/vitess/blob/main/doc/viper/viper.md#config-files.
Usage: vdiff [--source_cell=<cell>] [--target_cell=<cell>] [--tablet_types=in_order:RDONLY,REPLICA,PRIMARY] [--limit=<max rows to diff>] [--tables=<table list>] [--format=json] [--auto-retry] [--verbose] …
```

VDiff: correct handling of default source and target cells

---

go/vt/vtgate/planbuilder/operators/update.go
go/vt/vtgate/planbuilder/plan_test.go
go/vt/vtgate/planbuilder/testdata/foreignkey_cases.json
go/vt/vtgate/planbuilder/testdata/vschemas/schema.json

This PR fixes the bug reported in https://github.com/vitessio/vitess/issues/13987.
Previously an update on a parent table that has a child with a `SET NULL` constraint created a query like - 
```
update <child> set col = null where (col) in ::fkc_vals1 and (col) not in (2)
```
This used to work fine for a foreign key constraint using a single column, but immediately broke down for a multi-col foreign key constraint, where the query would look like this -
```
update <child> set col = null, col2 = null where (col,col2) in ::fkc_vals1 and (col,col2) not in (2,3)
```
This query fails since it is syntactically wrong and gives the error - `Operand should contain 2 column(s) (errno 1241) (sqlstate 21000)`
The fix in this PR is to encapsulate the tuple in the `NOT IN` clause in another level of …

Fix `NOT IN` expression used in the SET NULL for a child table on an update 

---

go/vt/vtgate/planbuilder/dml_planner.go
go/vt/vtgate/planbuilder/testdata/foreignkey_cases.json

This PR keeps the original lock mode for the select query in the foreign key cascade query which was part of the statement.
- #12967 

Foreign key cascade: retain "for update" lock on select query plans

---

go/vt/vttablet/tabletmanager/vreplication/external_connector_test.go
go/vt/vttablet/tabletmanager/vreplication/framework_test.go
go/vt/vttablet/tabletmanager/vreplication/journal_test.go
go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go
go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go

https://github.com/vitessio/vitess/pull/13949 added an additional query expectation to the vreplication unit tests and it is causing significant flakiness. 
Adding it to the mock db's ignore list for now until we find out the root cause for it. Since it gets called optionally when the metric is not initialized, it is possible some timing issue is causing additional or missing queries.

Flakes: Add recently added 'select rows_copied' query to ignore list 

---

go/vt/vtgate/planbuilder/testdata/foreignkey_cases.json

The foreign key query serving test `TestForeignKeyPlanning` was failing on CI on `main` due to https://github.com/vitessio/vitess/pull/13988 being merged before https://github.com/vitessio/vitess/pull/13985, and https://github.com/vitessio/vitess/pull/13985 not catching the changes made in https://github.com/vitessio/vitess/pull/13988. This PR fixes the expectation to unblock other PRs' CI.

Fix foreign key plan tests expectation

---

doc/internal/README.md
doc/internal/release/README.md
doc/internal/release/how-to-release.md
doc/internal/release/release-cutover.md

This PR changes the internal release documentation to be more intuitive and be up-to-date with some other tools we use.
- Fixes https://github.com/vitessio/vitess/issues/14001

Improve release process documentation

---

go/test/endtoend/vtgate/foreignkey/fk_test.go
go/test/endtoend/vtgate/foreignkey/main_test.go

This PR adds a test using VStream to stream the binlogs to view the effect of executing query with foreign key cascade and expects the relevant row events.
- #12967 

test: added test to check binlogs to contain the cascade events

---

go/vt/vtgate/engine/join.go
go/vt/vtgate/executor_select_test.go

This PR fixes 3 data races in the join engine primitive streaming implementation.
- 1 Concurrent map write - critical as it causes VTGate to crash
- 2 Boolean variables - non-critical but good to fix
- Fixes https://github.com/vitessio/vitess/issues/13908 

fix data race in join engine primitive olap streaming mode execution

---

go/vt/vtgate/planbuilder/operators/update.go
go/vt/vtgate/planbuilder/testdata/foreignkey_cases.json

This PR fixes the bug described in https://github.com/vitessio/vitess/issues/13992.
For a update like `update parent_tbl set col = 2 where id = 1`
Previously an update on a parent table that has a child with a RESTRICT constraint, and the verification is done by Vtgate created a query like -
```
select 1 
from child_tbl 
join parent_tbl on parent_tbl.col = child_tbl.col 
where parent_tbl.id = 1 
limit 1
```
This query would get whether there were any rows in the child table that are related to the parent table rows that are being updated.
This query in general worked fine, but for the very specific case, where the update doesn't actually lead to any row changes on the parent, then we actually shouldn't be failing the update query, but we should be passing it like MySQL does.
In order to …

Fix the `SELECT` query we run on the child table to verify that update is allowed on a RESTRICT constraint

---

changelog/18.0/18.0.0/summary.md
go/cmd/vtbackup/vtbackup.go

Emit `vtbackup_phase_status` to report issues with individual phases of `vtbackup`. Specifically, during the catch-up phase of `vtbackup`, either of these metrics can be set to either `0` or `1`. At the beginning of `vtbackup` execution they are set to 0. If they are set to 1, that indicates a problem that may require manual intervention to resolve.
```
vtbackup_phase_status{phase="CatchUpReplication",status="Stalled"} 0
vtbackup_phase_status{phase="CatchUpReplication",status="Stopped"} 0
```
Fixes #13994
Have a metric test framework for `vtbackup` in https://github.com/vitessio/vitess/pull/12973, when that gets merged I can use that to test these new metrics.
- …

go/cmd/vtbackup: report replication status metrics during catch-up phase

---

go/vt/vttablet/tabletmanager/vreplication/vplayer.go

In #13137, we started setting the `foreign_key_checks` session variable on the target db connection based on the `flags` which is sent in every RowEvent. When this flags value changes we call `select @@session.foreign_key_checks=on/off` depending on the current setting value.
However we were not setting this when vplayer first starts, on the first row event it gets. This was noticed due to flakiness in the end to end `TestForeignKeyWorkflow`. The failure was caused due to this situation:
* when vplayer starts, the cached state of `foreign_key_checks`  (a bool) is not initialized and hence set to false.
* the database connection starts with `foreign_key_checks`  on.
* the first binlog row event after the copy phase happens to have the `/*+ SET_VAR(foreign_key_checks=0) */` hint and …

VReplication VPlayer: set foreign_key_checks on initialization

---

go/vt/vtgate/planbuilder/operators/sharded_routing.go
go/vt/vtgate/planbuilder/testdata/from_cases.json

This PR adds the missing `SubShard` opcode to the cost model.
- Fixes https://github.com/vitessio/vitess/issues/13021

fix: cost to include subshard opcode

---

go/test/endtoend/vtgate/queries/misc/misc_test.go
go/test/endtoend/vtgate/queries/timeout/main_test.go
go/test/endtoend/vtgate/queries/timeout/schema.sql
go/test/endtoend/vtgate/queries/timeout/timeout_test.go
go/test/endtoend/vtgate/queries/timeout/uschema.sql
go/test/endtoend/vtgate/queries/timeout/vschema.json
test/config.json

This PR moves out timeout related test to different packages it the timeout values are very restrictive and causing other test to be flaky.

moved timeout test to different package

---

go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
go/vt/schema/ddl_strategy.go
go/vt/schema/ddl_strategy_test.go
go/vt/vttablet/onlineddl/executor.go
go/vt/vttablet/onlineddl/schema.go

This PR first and foremost fixes https://github.com/vitessio/vitess/issues/14022, by ensuring to collect `cancelled` migrations artifacts for cleanup. The change is in `onlineddl/schema.go`, a mere SQL query modification.
As a bonus, it also fixes https://github.com/vitessio/vitess/issues/14024, introducing `--retain-artifacts=<duration>` DDL strategy flag, which now allows a per-migration setting for artifact retention. This flag came useful when designing the `endtoend` tests for collecting `cancelled` migration artifacts.
Fixes https://github.com/vitessio/vitess/issues/14022
Fixes https://github.com/vitessio/vitess/issues/14024
Docs: https://github.com/vitessio/website/pull/1590
-   [ ] Tests were added …

OnlineDDL: cleanup cancelled migration artifacts; support `--retain-artifacts=<duration>` DDL strategy flag

---

java/jdbc/pom.xml
java/pom.xml

This PR updates the java dependencies to latest grpc and protobuf version

java: update to latest dependencies for grpc and protobuf

---

go/test/endtoend/vreplication/helper_test.go
go/test/endtoend/vreplication/partial_movetables_test.go
go/test/endtoend/vreplication/vreplication_test.go
go/test/endtoend/vreplication/wrappers_test.go
go/vt/topo/shard.go
go/vt/topo/shard_test.go
go/vt/vtctl/grpcvtctldserver/server.go
go/vt/vtctl/workflow/server.go
go/vt/vtctl/workflow/switcher.go
go/vt/vtctl/workflow/switcher_dry_run.go
go/vt/vtctl/workflow/switcher_interface.go
go/vt/vtctl/workflow/traffic_switcher.go
go/vt/wrangler/switcher.go
go/vt/wrangler/switcher_dry_run.go
go/vt/wrangler/switcher_interface.go
go/vt/wrangler/traffic_switcher.go
go/vt/wrangler/traffic_switcher_test.go

When traffic is switched, in a MoveTables workflow, in addition to updating the (Shard) Routing Rules to point to the target, we also add the tables to the Denied Tables list in the source shards' tablet controls. This ensures that, if the user chooses to keep data and not delete the source tables, any vtgate queries that inadvertently get routed to the source will be rejected.
However we do not do this _yet_ on the target shards. If we call a ReverseTraffic then the Denied Tables on the target shards is also updated so that queries are never incorrectly served from these shards.
If we Cancel a migration once we have done a ReverseTraffic then these Denied Tables are orphaned and interfere with any future MoveTables which involve a different set of tables.
This PR drops both source and …

MoveTables Cancel: drop denied tables on target when dropping source/target tables

---

go/test/endtoend/reparent/plannedreparent/reparent_test.go

This PR fixes a bug that causes `fileNameFromPosition` (a test helper-`func` from `go/test/endtoend/reparent/plannedreparent`) to fail to parse a filename when the position text is too long
This is causing `plannedreparent` tests to be flaky on faster, dedicated CI runners we're using because they generate more binlog positions than this test is expecting
Here is a Go Playground reproducing the problem with the old, brittle logic: https://go.dev/play/p/ck5jEMcZu_V
Thanks to @deepthi for helping me find this problem in the Vitess Slack 🙇 
- Fixes: https://github.com/vitessio/vitess/issues/13779
-   [x] Did the new or modified tests pass consistently locally and on …

Fix bug in `fileNameFromPosition` test helper

---

go/vt/vttablet/tabletserver/stateful_connection.go

This PR removes the log statements causing excessive logging as reported in https://github.com/vitessio/vitess/issues/14019
- Fixes https://github.com/vitessio/vitess/issues/14019

Remove excessive logging in transactions

---

go/test/endtoend/tabletmanager/tablegc/tablegc_test.go
go/vt/vttablet/tabletserver/gc/tablegc.go
go/vt/vttablet/tabletserver/gc/tablegc_test.go

Per https://github.com/vitessio/vitess/issues/14018, the [Table GC](https://vitess.io/docs/18.0/user-guides/schema-changes/table-lifecycle/) mechanism was unable to drop views.
In this PR tableGC makes the distinction between tables and views in `DROP` statements. I refactored the code a bit to add unit testing, and also added an `endtoend` test.
Also, using `DB.DbaWithDB()` to drop the view, as dropping a view requires privileges to make changes to the `DEFINER` of the view.
Fixes https://github.com/vitessio/vitess/issues/14018

TableGC: support DROP VIEW

---

go/vt/vttablet/tabletmanager/vreplication/external_connector_test.go
go/vt/vttablet/tabletmanager/vreplication/framework_test.go
go/vt/vttablet/tabletmanager/vreplication/journal_test.go
go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go
go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go

Backport [release-16.0] Flakes: Add recently added 'select rows_copied' query to ignore list #13993

---

go/vt/vttablet/tabletmanager/vreplication/external_connector_test.go
go/vt/vttablet/tabletmanager/vreplication/framework_test.go
go/vt/vttablet/tabletmanager/vreplication/journal_test.go
go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go
go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go

Backport [release-17.0]  Flakes: Add recently added 'select rows_copied' query to ignore list #13993

---

changelog/18.0/18.0.0/summary.md
go/flags/endtoend/vtgate.txt
go/test/endtoend/vtgate/grpc_api/main_test.go
go/vt/vtgate/grpcvtgateservice/server.go
go/vt/vttablet/tabletserver/exclude_race_test.go
go/vt/vttablet/tabletserver/tabletserver_test.go

The PR https://github.com/vitessio/vitess/pull/13131 adds support for sending session on `StreamExecute` grpc API. This causes the client implementation to handle the last packet if it is not handled correctly and may cause failure.
This PR puts this behaviour behind a flag to avoid this disruption. This is a temporary flag.
- Backport to v17 (disabled - default)
- Mark for deprecation in v18 (enabled - default)
- Removed in v19
- https://github.com/vitessio/vitess/pull/13131
-   [X] Documentation was added or is not required (v17: https://github.com/vitessio/website/pull/1592)

Add session flag for stream execute grpc api

---

go/test/vschemawrapper/vschema_wrapper.go
go/vt/vtgate/engine/exec_prepared_statement.go
go/vt/vtgate/engine/fk_cascade_test.go
go/vt/vtgate/planbuilder/plan_test.go
go/vt/vtgate/planbuilder/testdata/foreignkey_cases.json

This PR fixes the bug reported in https://github.com/vitessio/vitess/issues/14047.
While debugging it was noticed that the reason Vitess is ending up cascading the deletes, but fails to rollback the changes when the delete on the parent fails, is because the `ExecStmt` Primitive would always run without a transaction.
This led to Vitess running the cascade operations outside a transaction. So, once the delete on the child table succeeded, we weren't able to roll it back even when the delete on the parent failed. This also explains why the problem was peculiar to prepared statements.
In this PR, I have added testing for the planning of a execute query such that it does cause a delete cascade. I have also fixed the problem described above by making the `ExecStmt` Primitive consult its input …

Fix cascading Delete failure while using Prepared statements

---

go/vt/vtgate/evalengine/compiler_test.go
go/vt/vtgate/evalengine/fn_misc.go

This was missed when this was added in
https://github.com/vitessio/vitess/pull/13097, since the UUID() function needs to be evaluated each time and not cached.
Fixes #14050 

evalengine: Mark UUID() function as non-constant

---

go/mysql/json/marshal.go
go/mysql/json/marshal_test.go

We didn't properly quote JSON keys when marshalling to SQL.
Fixes #14065

json: Fix quoting JSON keys

---

go/cmd/internal/docgen/docgen.go

This won't show _on_ the docs in the rendered website, but it embeds the data (and we can make it visible in the future if we want) so we know when the last time we generated a page was (and from what source it was)
Example (I figure we can go back and bulk-update before cutting RC1, so not doing it here):
```
➜  vtwebsite git:(prod) ✗ COBRADOC_VERSION_PAIRS="HEAD:18.0" VITESS_DIR=~/dev/vitess make vtorc-docs
go run ./tools/cobradocs/ --vitess-dir "/Users/andrew/dev/vitess" --version-pairs "HEAD:18.0" vtorc
➜  vtwebsite git:(prod) ✗ git d
diff --git a/content/en/docs/18.0/reference/programs/vtorc/_index.md b/content/en/docs/18.0/reference/programs/vtorc/_index.md
index ec764f3d..b94a07d5 100644
--- a/content/en/docs/18.0/reference/programs/vtorc/_index.md
+++ …
```

update docgen to embed commit ID in autogenerated doc frontmatter

---

go/test/endtoend/cluster/cluster_process.go
go/test/endtoend/tabletmanager/tablet_health_test.go
go/test/endtoend/vtgate/unsharded/main_test.go
go/vt/vttablet/endtoend/streamtimeout/healthstream_test.go
go/vt/vttest/local_cluster.go

While developing https://github.com/vitessio/vitess/pull/14034 I found several data races and flakyness on tests that have always been there, and that were exposed because of the new LIFO semantics of the new pool.
Let's split these test fixes into their own PR to make the tests less flaky for everybody!
- https://github.com/vitessio/vitess/pull/14034

ci: pool-related test flakyness

---

go/test/endtoend/cluster/mysqlctl_process.go

This backports 514c946457c8c54dbbb1f6d5890c337932811c48 to 17.0, which is needed so upgrade/downgrade tests (upgrading _to_ 18.0 on 17.0) work properly.
#13946 

[release-17.0] backport mysqlctl CLI compatibility fix to 17.0

---

go/flags/endtoend/flags_test.go
go/flags/endtoend/vtcombo.txt

actually test vtcombo

---

go/cmd/vtctldclient/command/onlineddl.go
go/flags/endtoend/vtcombo.txt

This is to standardize around proper sentencing in help texts.
-   [x] Documentation was added or is not required: https://github.com/vitessio/website/pull/1598

switch casing in onlineddl subcommand help text

---

go/cmd/internal/docgen/docgen.go

This replaces the `$(pwd)` default in the `--config-paths` help text with the verbatim `$WORKDIR` when generating docs for the website.
Fixes https://github.com/vitessio/website/issues/1601
```
$ COBRADOC_VERSION_PAIRS="HEAD:18.0" VITESS_DIR=~/dev/vitess make vtorc-docs
$ git diff
diff --git a/content/en/docs/18.0/reference/programs/vtorc/_index.md b/content/en/docs/18.0/reference/programs/vtorc/_index.md
index 596f6ebe..2a7f0f18 100644
--- a/content/en/docs/18.0/reference/programs/vtorc/_index.md
+++ b/content/en/docs/18.0/reference/programs/vtorc/_index.md
@@ -1,7 +1,7 @@
---
title: vtorc
series: vtorc
-commit: b089f78945653f6acd17c66f896820e36df49437
+commit: 9a79ee7a81128f8201af01965cf752d7baebeaae
---
@@ -42,7 +42,7 @@ vtorc \
--config-file string …
```

anonymize homedirs in generated docs

---

go/cmd/vtbackup/cli/vtbackup.go
go/stats/export.go

VTB E2E tests sometimes fail due to:
1. Some VTB plugins (in particular `plugin_opentsdb.go` register with `servenv.OnRun` https://github.com/vitessio/vitess/blob/30385807689b40668d60dbb5059ea0987f19da5c/go/cmd/vtbackup/cli/plugin_opentsdb.go#L24 https://github.com/vitessio/vitess/blob/30385807689b40668d60dbb5059ea0987f19da5c/go/stats/opentsdb/init.go#L36-L38
1.  VTB starts `servenv` in a goroutine https://github.com/vitessio/vitess/blob/30385807689b40668d60dbb5059ea0987f19da5c/go/cmd/vtbackup/cli/vtbackup.go#L232
1. VTB starts writing stats shortly after https://github.com/vitessio/vitess/blob/30385807689b40668d60dbb5059ea0987f19da5c/go/cmd/vtbackup/cli/vtbackup.go#L258
This sequence means that sometimes VTB starts writing stats before `servenv` plugins have finished initializing, which …

go/cmd/vtbackup: wait for plugins to finish initializing

---

.github/workflows/static_checks_etc.yml

The FOSSA API Key is currently inline in our CI workflow file, which is a security issue. For now removing this check until we get a new key and re-implement in a secure way.

Remove FOSSA Test from CI until we can do it in a secure way

---

go/test/endtoend/reparent/utils/utils.go

[release-15.0] Flakes: Delete VTDATAROOT files in reparent test teardown within CI (#13793)

---

changelog/18.0/18.0.0/summary.md

This PR adds the summary notes changes for foreign keys work done as part of #12967 
- #12967 

Summary changes for foreign keys

---

go/vt/vtgate/engine/ddl.go
go/vt/vtgate/engine/ddl_test.go
go/vt/vtgate/engine/fake_vcursor_test.go
go/vt/vtgate/engine/primitive.go
go/vt/vtgate/planbuilder/ddl.go
go/vt/vtgate/planbuilder/show.go
go/vt/vtgate/vcursor_impl.go

This PR commits the existing transaction and clears out the shard session when a DDL statement is executed.
This changes ensures that DDL does not executes on a transactional connection as it is committed before sending DDL statement to vttablet.
There is some additional logic in vttablet which can only be removed in next version.
- https://github.com/vitessio/vitess/issues/14111

DDL execution to commit open transaction

---

go/test/endtoend/vtgate/foreignkey/stress/fk_stress_test.go

Followup to https://github.com/vitessio/vitess/pull/13799
https://github.com/vitessio/vitess/pull/13799 introduced a new `endtoend` stress test suite. This PR improves the design and performance as follows:
- Better logging/auditing of parameters used per test.
- Adapt concurrency/intervals per platform and test (relax on GitHub, relax on potential OnlineDDL).
- Idiomatic use of `context.WithTimeout`, remove excessive timers and flags.
- Evaluate server position by connection/query rather than invoking `vtctl` (reduces load).
- For potential Online DDL, reduce `--migration_check_interval`.
- https://github.com/vitessio/vitess/issues/11975 …

VTGate FK stress tests suite: improvements

---

go/vt/servenv/version.go
java/client/pom.xml
java/example/pom.xml
java/grpc-client/pom.xml
java/jdbc/pom.xml
java/pom.xml

This PR moves `main` branch version to `19.0 SNAPSHOT` version.

moving main to 19.0 snapshot

---

docker/k8s/Dockerfile
docker/k8s/vtorc/Dockerfile
docker/release.sh

We don't currently publish a vtorc image, so this adds it and sets it to build with releases. I've tested it and it runs just fine using the configuration in the docs 
https://vitess.io/docs/17.0/user-guides/configuration-basic/vtorc/#example-invocation-of-vtorc
Fixes https://github.com/vitessio/vitess/issues/14144

docker: add dedicated vtorc container

---

examples/common/scripts/vttablet-up.sh
examples/compose/vttablet-up.sh
go/test/endtoend/cluster/vttablet_process.go
go/test/endtoend/onlineddl/revert/onlineddl_revert_test.go
go/test/endtoend/reparent/utils/utils.go
go/test/endtoend/utils/mysqlvsvitess/main_test.go
go/test/endtoend/vtgate/gen4/main_test.go
go/test/endtoend/vtgate/main_test.go
go/test/endtoend/vtgate/queries/aggregation/main_test.go
go/test/endtoend/vtgate/queries/foundrows/main_test.go
go/test/endtoend/vtgate/queries/informationschema/main_test.go
go/test/endtoend/vtgate/queries/lookup_queries/main_test.go
go/test/endtoend/vtgate/queries/orderby/main_test.go
go/test/endtoend/vtgate/queries/subquery/main_test.go
go/test/endtoend/vtgate/queries/union/main_test.go
go/test/endtoend/vtgate/schematracker/restarttablet/schema_restart_test.go
go/test/endtoend/vtgate/schematracker/sharded/st_sharded_test.go
go/test/endtoend/vtgate/schematracker/sharded_prs/st_sharded_test.go
go/test/endtoend/vtgate/schematracker/unauthorized/unauthorized_test.go
go/test/endtoend/vtgate/schematracker/unsharded/st_unsharded_test.go
vitess-mixin/e2e/vttablet-up.sh

This is a follow-up of https://github.com/vitessio/vitess/pull/14071 on `release-17.0`. In https://github.com/vitessio/vitess/pull/14071 we removed some deprecated flags, this PR remove the usage of `vtctld_addr` as it is deprecated anyway. This will unblock the upgrade tests.

[release-17.0] Fix upgrade tests

---

.github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml
.github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
.github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
.github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml
.github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml
.github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml

This PR is a follow-up of the golang upgrade done in https://github.com/vitessio/vitess/pull/13932. We are bumping the golang version used in the upgrade tests to reflect the new golang version that will be used in `release-16.0`.

[release-15.0] Bump upgrade test to `go1.20.8`

---

go/vt/topo/zk2topo/server_test.go

This PR fixes the flakiness as observed in #14161. 
When we start the zookeeper topo server, sometimes the first call to it fails with a connection error. This should be retried until it succeeds.
With the changes in this PR, the test passes over 100 times locally without failing - 
```
PASS
ok      vitess.io/vitess/go/vt/topo/zk2topo     5.056s
Running test - Number 102
=== RUN   TestZk2Topo
```
- Fixes #14161 

FlakyFix: `TestZk2Topo`

---

go/vt/vttablet/tabletserver/throttle/throttler.go

Fixes https://github.com/vitessio/vitess/issues/14164
Thanks to @vmg , the scenario in https://github.com/vitessio/vitess/issues/14164 has been identified. The specific flow is as follows:
- A primary tablet is elected, notices a replica tablet.
- The replica gets decomissioned.
- A new replica tablet (possibly with same alias) is commissioned.
The particular conditions where the error appears are:
- The new replica tablet is assigned a different IP address than the old one, and
- While the old tablet gets decomissioned, any gRPC calls to that tablet (and specifically `CheckThrottler`) _hang_.
The throttler behaves correctly in identifying the change of replicas, and serves requests correctly. However, because its final `CheckThrottler` gRPC call to the decommissioning replica is being …

Throttler: set timeouts on gRPC communication and on topo communication

---

.github/workflows/update_golang_version.yml

This PR adds release-18.0 in github workflow to be used when new go version is available.

add release-18.0 to golang upgrade

---

doc/internal/release/how-to-release.md

Just a small modification to the release instructions to include steps for handling milestones.

Add release instructions for Milestones

---

go/vt/vtgate/executor_select_test.go
go/vt/vttablet/sandboxconn/sandboxconn.go

This PR fixes the data race as pointed out in #14186.
The data race was happening on the replica tablet. In the test `TestWarmingReads`, warming read queries are run on the replica asynchronously. This lead to the `Queries` field in the sandboxconn being updated in a separate go-routine than the main go routine. This causes the read and writes to this variable in the main go routine to error with a data race.
This has been fixed in this PR by adding synchronization to that variable. This however has been added only when it is required so as to not hamper performance of the other tests.
The test `TestWarmingReads` was introduced in https://github.com/vitessio/vitess/pull/13206
- Fixes #14186 
-   [x] Tests …

Fix data race in `TestWarmingReads`

---

go/vt/vttablet/tabletserver/planbuilder/plan.go
go/vt/vttablet/tabletserver/planbuilder/plan_test.go
go/vt/vttablet/tabletserver/query_engine.go
go/vt/vttablet/tabletserver/query_engine_test.go
go/vt/vttablet/tabletserver/query_executor_test.go
go/vt/vttablet/tabletserver/tabletserver.go

At Etsy, we use OLAP mode for a lot of queries, and we implemented this patch to cache stream query plans. The original motivation was performance-based; feature parity with non-stream queries is a nice bonus.
Fixes #13263

Cache stream query plans in vttablet

---

go/vt/vttablet/tabletserver/throttle/throttler.go

Per https://github.com/vitessio/vitess/issues/14178, the function `throttler.refreshMySQLInventory()` should run on same goroutine as the `select` clause.
A note about testing: this of course would have been caught by race detection. We have a followup PR that make a lot of refactoring to the throttler code, and adds sufficient unit testing to validate the changes and to catch race conditions.
This PR is a one line extract from the followup PR, and without the unit testing. The reasoning is that the refactor is a post-v18 change, while the fix in this PR should be backported to `v18`, `v17` and `v16`, which cannot support the many changes implied by the unit testing. And so this PR does not include those tests.
Said followup PR is https://github.com/vitessio/vitess/pull/14181.
Fixes …

Tablet throttler: fix race condition by removing goroutine call

---

go/cmd/vtctldclient/command/root.go

Was putting together a demo of shell completion for the upcoming release and noticed that `vtctldclient` wasn't working (`zk`, on the other hand, works fine).
Worked it out to the fact that, technically, the secret cobra completion commands still execute the PersistentPreRunE, and since they (obviously) don't specify a server, it was failing.
⚠️ I'd like to get this backported to 18.0 so it's in the final release if at all possible. ⚠️ 
See 

Bypass cobra completion commands so they still function

---

changelog/17.0/17.0.0/release_notes.md
changelog/17.0/17.0.0/summary.md

Added a note to the Breaking Changes for the updated version of `init_db.sql`
https://github.com/vitessio/vitess/pull/12206
None.

Update v17 Release notes with a Breaking Change

---

go/vt/vttablet/onlineddl/executor.go

Following the same lines of how #14165 solves #14164, this PR ensures there's reasonable timeout s for any gRPC call made by the Online DDL service.
- https://github.com/vitessio/vitess/issues/14164
- https://github.com/vitessio/vitess/pull/14165

[Release 17.0]: Online DDL: timeouts for all gRPC calls (#14182)

---

go/vt/vttablet/onlineddl/executor.go

Following the same lines of how #14165 solves #14164, this PR ensures there's reasonable timeout s for any gRPC call made by the Online DDL service.
- https://github.com/vitessio/vitess/issues/14164
- https://github.com/vitessio/vitess/pull/14165

[Release 18.0]: Online DDL: timeouts for all gRPC calls (#14182)

---

.github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml
.github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
.github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
.github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml
.github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml
.github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml

This PR bumps the Golang version used by the upgrade test workflows on `release-15.0` to `go1.20.9` in order to match the go upgrade on `release-16.0`: https://github.com/vitessio/vitess/pull/14194.

[release-15.0] Bump upgrade test workflows to `go1.20.9`

---

.github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml
.github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
.github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
.github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml
.github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml
.github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml

This is a follow-up of https://github.com/vitessio/vitess/pull/14228. We will now use `go1.20.10` in `release-16.0` and thus we want to have a matching Go version in `release-15.0`'s upgrade tests.

Bump upgrade workflows to `go1.20.10`

---

examples/backups/start_cluster.sh
examples/backups/stop_tablets.sh
examples/backups/take_backups.sh
examples/backups/upgrade_cluster.sh
examples/common/env.sh
examples/common/lib/utils.sh
examples/compose/README.md
examples/compose/externaldb_vreplication.sh
examples/compose/lvtctl.sh
examples/compose/schemaload.sh
examples/compose/vtcompose/vtcompose.go
examples/compose/vttablet-up.sh
examples/local/README.md
examples/operator/README.md
examples/operator/pf.sh
examples/region_sharding/201_main_sharded.sh
examples/region_sharding/203_reshard.sh
examples/region_sharding/204_switch_reads.sh
examples/region_sharding/205_switch_writes.sh
examples/region_sharding/301_teardown.sh
go/cmd/vtctldclient/command/vreplication/vdiff/vdiff.go

[`vtctldclient` is replacing the legacy `vtctlclient`](https://github.com/vitessio/vitess/pull/12866). Starting with the v18 GA (after https://github.com/vitessio/vitess/issues/12152 is done) all users should use `vtctldclient` rather than `vtctlclient`. This PR updates the examples accordingly.
- Fixes: https://github.com/vitessio/vitess/issues/14209
- Part of: https://github.com/vitessio/vitess/issues/12152

Move all examples to vtctldclient

---

go/vt/vttablet/onlineddl/executor.go

Following the same lines of how #14165 solves #14164, this PR ensures there's reasonable timeout s for any gRPC call made by the Online DDL service.
- https://github.com/vitessio/vitess/issues/14164
- https://github.com/vitessio/vitess/pull/14165

[Release 16.0]: Online DDL: timeouts for all gRPC calls (#14182)

---

go/flags/endtoend/vtcombo.txt
go/flags/endtoend/vttablet.txt
go/vt/vttablet/flags.go
go/vt/vttablet/tabletmanager/rpc_vreplication_test.go
go/vt/vttablet/tabletmanager/vreplication/controller.go
go/vt/vttablet/tabletserver/vstreamer/rowstreamer.go
go/vt/vttablet/tabletserver/vstreamer/tablestreamer.go

On some particularly busy tables, we cannot run vitess onlineddl schema changes because it fails with `unexpected EOF\nio.ReadFull(packet body of length 287) failed (errno 2013) (sqlstate HY000)`. Note that ghost also fails on these tables, but we have higher hopes for vitess. 
In several slack threads, the recommendation was to increase `net_read_timeout` (default is 30, recommended for vreplication is 300) and `net_write_timeout` (default is 60, recommended for vreplication is 600). However, we don't want to modify these values globally, would be nice if only vreplication's session had these higher values - and this PR does just that
Update: with these changes, we were able to successfully run onlineddl schema changes on an incredibly busy table that was previously unable to run any …

set vreplication net read and net write timeout session vars to high values

---

go/vt/vttablet/tabletserver/throttle/throttler.go

Per https://github.com/vitessio/vitess/issues/14178, the function `throttler.refreshMySQLInventory()` should run on same goroutine as the `select` clause.
A note about testing: this of course would have been caught by race detection. We have a followup PR that make a lot of refactoring to the throttler code, and adds sufficient unit testing to validate the changes and to catch race conditions.
This PR is a one line extract from the followup PR, and without the unit testing. The reasoning is that the refactor is a post-v18 change, while the fix in this PR should be backported to `v18`, `v17` and `v16`, which cannot support the many changes implied by the unit testing. And so this PR does not include those tests.
Said followup PR is https://github.com/vitessio/vitess/pull/14181.
Fixes …

[release-18.0] Tablet throttler: fix race condition by removing goroutine call (#14179)

---

go/vt/vttablet/tabletserver/throttle/throttler.go

Per https://github.com/vitessio/vitess/issues/14178, the function `throttler.refreshMySQLInventory()` should run on same goroutine as the `select` clause.
A note about testing: this of course would have been caught by race detection. We have a followup PR that make a lot of refactoring to the throttler code, and adds sufficient unit testing to validate the changes and to catch race conditions.
This PR is a one line extract from the followup PR, and without the unit testing. The reasoning is that the refactor is a post-v18 change, while the fix in this PR should be backported to `v18`, `v17` and `v16`, which cannot support the many changes implied by the unit testing. And so this PR does not include those tests.
Said followup PR is https://github.com/vitessio/vitess/pull/14181.
Fixes …

[release-16.0] Tablet throttler: fix race condition by removing goroutine call (#14179)

---

go/vt/vttablet/tabletserver/throttle/throttler.go

Per https://github.com/vitessio/vitess/issues/14178, the function `throttler.refreshMySQLInventory()` should run on same goroutine as the `select` clause.
A note about testing: this of course would have been caught by race detection. We have a followup PR that make a lot of refactoring to the throttler code, and adds sufficient unit testing to validate the changes and to catch race conditions.
This PR is a one line extract from the followup PR, and without the unit testing. The reasoning is that the refactor is a post-v18 change, while the fix in this PR should be backported to `v18`, `v17` and `v16`, which cannot support the many changes implied by the unit testing. And so this PR does not include those tests.
Said followup PR is https://github.com/vitessio/vitess/pull/14181.
Fixes …

[release-17.0] Tablet throttler: fix race condition by removing goroutine call (#14179)

---

docker/README.md

This is a fix of a broken link in the [docker readme](https://github.com/vitessio/vitess/blob/main/docker/README.md). In particular, the third bullet under the "Principles" heading links to [lite/build.sh](https://github.com/vitessio/vitess/blob/main/docker/lite/build.sh, which does not exist, and is therefore substituted with another `build.sh` file link that works. 
Fixes #14221 

Fix broken link in docker readme

---

changelog/18.0/18.0.0/summary.md

Now that the [OnlineDDL](https://github.com/vitessio/vitess/issues/13712) and [VReplication](https://github.com/vitessio/vitess/issues/12152) commands have been migrated to `vtctldclient` we have full parity with the legacy clients (`vtctl`/`vtctlclient`). This PR adds related information to the 18.0 summary.
- Fixes: https://github.com/vitessio/vitess/issues/13826

Add vtctldclient info to the 18.0 summary

---

doc/internal/release/how-to-release.md

This is a small modification to the release process documentation to include a post-release step to update the roadmap page in the documentation website.

Mention roadmap planning/modification in the release process

---

go/test/endtoend/utils/utils.go
go/test/endtoend/vtgate/queries/aggregation/distinct_test.go
go/test/endtoend/vtgate/queries/orderby/orderby_test.go
go/test/endtoend/vtgate/queries/union/union_test.go

Quick renaming to address https://github.com/vitessio/vitess/pull/14245#discussion_r1357346163.

Rename `BinaryIsAtVersion` to `BinaryIsAtLeastAtVersion`

---

.github/workflows/docker_build_lite.yml

This PR adds automatic builds for the `vitess/lite` Docker Image on GitHub Actions instead of building them on DockerHub. An example of how the build works can be found below:
- [Build on `v1.1.3` on my own fork](https://github.com/frouioui/vitess/actions/runs/6501861605)
- [Build on `main` on my own fork](https://github.com/frouioui/vitess/actions/runs/6501773987)
- [List of tags on `frouioui/lite`](https://hub.docker.com/repository/docker/frouioui/lite/tags?page=1&ordering=last_updated)
> Note to self: remove DockerHub auto build once this is merged.
> Note to reviewers: the new secrets have already been added to the repository.
- Part of #14149 
-   [x] Did …

Build and push Docker `vitess/lite` to DockerHub from GitHub Actions

---

go/vt/wrangler/vexec_plan.go

Very minor improvement to `vexec_plan.go` log message for when no matching streams are found.
- Fixes: https://github.com/vitessio/vitess/issues/14060

go/vt/wrangler: add len(qr.Rows) check to no streams found log msg

---

go/test/endtoend/vtgate/queries/no_scatter/main_test.go
go/test/endtoend/vtgate/queries/no_scatter/queries_test.go
go/test/endtoend/vtgate/queries/no_scatter/schema.sql
go/test/endtoend/vtgate/queries/no_scatter/vschema.json
go/vt/sqlparser/analyzer.go
go/vt/sqlparser/ast.go
go/vt/sqlparser/comments.go
go/vt/sqlparser/comments_test.go
go/vt/vtgate/executor_ddl_test.go
go/vt/vtgate/executor_test.go
go/vt/vtgate/planbuilder/vexplain.go
go/vt/vttablet/tabletserver/query_engine.go
test/config.json

The bug report #14090 exposed an issue where we where not reading comment directives correctly for most statement types. This PR makes sure we read the directives correctly in a lot more situations.
Fixes #14090

bugfix: use the proper interface for comment directives

---

go/vt/vtgate/planbuilder/operator_transformers.go
go/vt/vtgate/planbuilder/operators/insert.go
go/vt/vtgate/planbuilder/operators/insert_selection.go

In the operator model that we have, a Route represents a part of the operator that should be converted to a query and run as a single unit. It therefore doesn't make sense to have a Route operator nested inside another.
Previously for a query like `insert into music(id, user_id) select * from user`, the operator tree looked like - 
```
Route (Scatter on user Seen:[<nil>])
└── Insert (user.music)
└── Route (Scatter on user Seen:[<nil>])
└── Horizon
└── Table (user.user)
```
This refactor introduces a new operator called InsertionSelection to remedy this situation.
After the refactor the operator tree looks like - 
```
InsertSelection
├── Route (Scatter on user Seen:[<nil>])
│   └── Horizon
│       └── Table (user.user)
└── Route (Scatter on user Seen:[<nil>])
└── Insert (user.music)
``` …

Refactor: New operator InsertionSelection to adhere to the operator model

---

go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
go/vt/vttablet/onlineddl/executor.go
go/vt/vttablet/tabletmanager/vreplication/controller.go
go/vt/vttablet/tabletmanager/vreplication/table_plan_builder.go
go/vt/vttablet/tabletmanager/vreplication/utils.go
go/vt/vttablet/tabletserver/vstreamer/planbuilder.go

This PR fixes a couple scenarios where an Online DDL `ALTER` vitess migration should fail, but instead infinitely keeps retrying behind the scenes. While retrying, it does not provide any meaninful info in `SHOW VITESS_MIGRATIONS`. See #14285 and #14289
With this PR, a few specific scenarios are treated as fatal/unrecoverable, bot in Online DDL's state machine, as well as in `vreplication`.
- With Online DDL: an error in reviewing a migration immediately fails the migration.
- With vreplication: a `Code_INTERNAL` error is treated as unrecoverable. A couple schema-related errors are now set as `Code_INTERNAL`.
I've added an `endtoend` test that covers the OnlineDDL fix. I'm unsure about a `vreplication` test.
- Fixes https://github.com/vitessio/vitess/issues/14285
- Fixes …

OnlineDDL: fix scenarios where migration hangs instead of directly failing

---

.github/CODEOWNERS
go/cmd/vtctldclient/command/vreplication/common/utils.go
go/cmd/vtctldclient/command/vreplication/common/utils_test.go
go/cmd/vtctldclient/command/vreplication/workflow/update.go

For a VReplication workflow to start, it must be able to use at least one valid tablet type.
Today we allow a user to explicitly (I would assume accidentally) specify an empty string which passes our validation.
We instead should return an error in this case as I cannot think of a valid use case for doing so.
```
❯ vtctldclient MoveTables --workflow commerce2customer --target-keyspace customer create --source-keyspace commerce --tables "customer,corder" --tablet-types=""
E1017 00:04:31.361147   46464 main.go:56] invalid tablet-types value, at least one valid tablet type must be specified
```
- Fixes: https://github.com/vitessio/vitess/issues/14293
-   [x] Did the …

VReplication: error on vtctldclient commands w/o tablet types

---

go/vt/schemadiff/diff_test.go
go/vt/schemadiff/errors.go
go/vt/schemadiff/schema_diff.go
go/vt/schemadiff/schema_diff_test.go
go/vt/schemadiff/table.go
go/vt/schemadiff/view.go

See story in https://github.com/vitessio/vitess/issues/14248. In this PR:
- We re-apply an ordering heuristic (where `DROP`s come first, then `ALTER`s, then `CREATE`s) before evaluating dependency permutations. This begins the search with a heuristically probable solution, and followed by "nearby" solutions.
- We copy less objects in the duration of the search. When evaluating a permutation we apply schema changes in-line. It's only at the beginning of a permutation search that we do one copy of the schema.
- We support `context.Context` for premature exit. This changes the function signature for `OrderedDiffs(...)`
Fixes https://github.com/vitessio/vitess/issues/14248
-   [ ] Tests were added or are not …

schemadiff: improved heuristic for dependent migration permutation evaluation time

---

go/vt/vtgate/evalengine/translate.go

We need to start off here with the unknown type, not the null type which is the default for `0`.
Broken in #14292 which is part of #14310

evalengine: Use the right unknown type to initialize

---

.github/workflows/docker_build_vttestserver.yml

This PR adds `vitess/vttestserver` to the list of images that are going to be built by GitHub Actions rather than by DockerHub.
Example runs of this workflow are available on my fork:
- [Run on `main`](https://github.com/frouioui/vitess/actions/runs/6578452550)
- [`mysql80` tag on DockerHub](https://hub.docker.com/layers/frouioui/vttestserver/mysql80/images/sha256-7254937730f28a9ebf0d47048bf5fa99070b0699df33d9284d908c36b1329bab?context=repo)
- [`mysql57` tag on DockerHub](https://hub.docker.com/layers/frouioui/vttestserver/mysql57/images/sha256-178310ca93e3bcb20be204b12451057d4219737187bd995a5be99291e6cf641e?context=repo)
- [Run on a tag](https://github.com/frouioui/vitess/actions/runs/6578645485)
- [`v99.99.9-mysql57` tag on DockerHub](https://hub.docker.com/layers/frouioui/vttestserver/v …

Build and push Docker `vitess/vttestserver` DockerHub from GitHub Actions

---

changelog/18.0/18.0.0/summary.md

Lightly edit the release notes summary for v18 for consistency and readability. For example, I've replaced all instances of v18.0 with v18. And so on.
#13990 
-   [ ] Documentation was added or is not required <- website PR to follow

release notes: edit summary for consistency

---

.github/workflows/docker_build_base.yml

This PR adds the `vtexplain` and `vtbackup` images to the list of images we autobuild on push to `main` and on new tags.
Testing workflow on my own fork: https://github.com/frouioui/vitess/actions/runs/6579148743
- `vtbackup` on my DockerHub: [link](https://hub.docker.com/repository/docker/frouioui/vtbackup/general)
- `vtexplain` on my DockerHub: [link](https://hub.docker.com/repository/docker/frouioui/vtexplain/general)
I opened https://github.com/vitessio/vitess/pull/14316 earlier to remove `vtbackup` entirely, but then ended up thinking keeping it and building as part of the already-existing process would be better.
- Part of #14149 
-   [x] Did the new or …

Add `vtexplain` and `vtbackup` to base docker auto-build

---

go/vt/mysqlctl/builtinbackupengine.go
go/vt/mysqlctl/mysqld.go
go/vt/mysqlctl/mysqld_test.go

See https://github.com/vitessio/vitess/issues/14329 for bug description.
The main change in this PR is to fix the race condition in `scanBinlogTimestamp()`. In essence, the fix is two swap places between `cmd.Wait()` and the wait for output's pipe scan. However, once that's done, it becomes clear that the pipe scan does not need to run in a goroutine, and so the code is further simplified to run sequentially.
As usual, I took the opportunity to do some cleanup in the whereabouts of the affected code. I've added comments in the PR diff, to clarify which are the strict fixes and which are cosmetic or otherwise useful changes.
This fixes `backup_pitr` flaky tests, in this repo (with fast runners) as well as in forks (with slow runners).
This must be backported to `release-18.0` before GA. …

Incremental backup: fix race condition in reading 'mysqlbinlog' output

---

go/vt/vtgate/engine/concatenate.go

There's a race on this recently refactored code: you cannot use an atomic for counting which fields are set because that is inherently racy between setting the field and increasing the atomic. Using a simple Mutex and a counter is not enough either, because the same Result index may receive fields more than once, leaving a `nil` gap in the set of results whose types we must aggregate. One possible correct approach is using a mutex and checking all the parallel results until none of them are `nil`. This is implemented here.
The race was making `TestSQLSelectLimit` flaky.
cc @systay @dbussink 
Broken in #14245
-   [ ] Did the new or modified tests pass consistently …

engine: fix race when reading fields in Concatenate

---

go/cmd/vtctldclient/command/vreplication/common/utils.go
go/cmd/vtctldclient/command/vreplication/common/utils_test.go

This PR adds an `--all-cells` flag to the `vtctldclient` VReplication commands that have a `create` sub-command (e.g. [`MoveTables`](https://vitess.io/docs/reference/programs/vtctldclient/vtctldclient_movetables/vtctldclient_movetables_create/)). When this is specified (cannot be specified when `--cells` is also specified) then all of the current cells will be used for the workflow when looking for source tablets to replicate data from.
>**Note**
>This feature was *not* added to `vtctlclient` as we plan to remove that binary in v19.
- Fixes: https://github.com/vitessio/vitess/issues/13078
-   [x] Did the new or modified tests pass consistently locally and on the …

VReplication: Add --all-cells flag to create sub-commands

---

examples/compose/vtcompose/vtcompose.go

Removes unnecessary use of `fmt.Sprintf` in vtcompose example code.

chore: unnecessary use of fmt.Sprintf

---

web/vtadmin/package-lock.json

No idea how this passed CI before, but it seems stuff is broken atm and showing a diff. This fixes that diff.
Broken in #14336

Fix stray vtadmin package-lock.json content

---

go/mysql/datetime/datetime.go
go/mysql/datetime/time_zone_test.go
go/vt/vtgate/evalengine/compiler_asm.go
go/vt/vtgate/evalengine/fn_numeric.go

These are 3 small bugs in the compiler found with @dbussink:
1. The logic for adding time periods was not DST-aware
2. `BASE64` function calls were not being compiled with the right collation
3. `CONV` function calls were not being evaluated with the right collation

evalengine: Misc bugs

---

.github/workflows/auto_approve_pr.yml

This PR adds a workflow to auto-approve clean backports made by the `vitess-bot`. GitHub Actions will now give one of the two required approvals for backports. Meaning that we will still need at least one manual approval + a manual intervention to hit the merge button of the backport.
Examples:
- Auto approval of a clean backport: https://github.com/frouioui/vitess/pull/107
- No approval on a backport with merge conflicts: https://github.com/frouioui/vitess/pull/109 with its `Auto Approval` workflow being skipped: https://github.com/frouioui/vitess/actions/runs/6631335864?pr=109
-   [x] …

Automatic approval of `vitess-bot` clean backports

---

go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
go/vt/vttablet/onlineddl/executor.go
go/vt/vttablet/onlineddl/executor_test.go

For the ongoing, experimental foreign key support, this PR adds support for `ALTER TABLE ... DROP FOREIGN KEY`. As you might see from the change, there's very little to this PR; all the support has been created long ago, but due to an oversight we did not include `DROP FOREIGN KEY` in the logic.
Just to explain the change: in Online DDL we actually drop the foreign key on the shadow table. Since foreign key constraints, like check constraints, have schema-level naming scope, the shadow table's foreign key constraint is different than the original's.
Without this PR, a `ALTER TABLE t DROP FOREIGN KEY t_id_fk` fails because it attempts to drop the constraint `t_id_fk` from the shadow tables. But on the shadow table the constraint might be named e.g. `fk_aulpn7bjeortljhguy86phdn9`. The fix …

Online DDL: support DROP FOREIGN KEY statement

---

go/mysql/datetime/datetime.go
go/mysql/json/parser.go
go/vt/vtgate/evalengine/compiler_asm.go
go/vt/vtgate/evalengine/compiler_test.go
go/vt/vtgate/evalengine/eval.go
go/vt/vtgate/evalengine/eval_temporal.go
go/vt/vtgate/evalengine/expr_convert.go
go/vt/vtgate/evalengine/expr_env.go
go/vt/vtgate/evalengine/expr_logical.go
go/vt/vtgate/evalengine/fn_time.go
go/vt/vtgate/evalengine/integration/fuzz_test.go
go/vt/vtgate/evalengine/testcases/helpers.go

The evaluation environment in the `evalengine` sets a frozen `time.Time` value upon creation, to ensure that all time-related APIs in the engine are evaluated consistently, following MySQL's behavior.
However, there are APIs in the `datetime` package that call `time.Now()` directly, particularly when converting from a time value to a datetime value. This is not correct! These APIs must use the frozen time set in the `evalengine`. This PR updates the APIs to take a time input when necessary.
cc @dbussink 
Found when working on #14310, follow up to #14351 
-   [ ] Documentation was added …

datetime: obey the evalengine's environment time

---

go/vt/vtgate/planbuilder/operators/queryprojection.go
go/vt/vtgate/planbuilder/testdata/oltp_cases.json
go/vt/vtgate/planbuilder/testdata/postprocess_cases.json

This PR improves the distinct with order by planning by using the aggregation engine over the distinct engine.
It was found as performance regression from `arewefastyet` 

use aggregation engine over distinct engine when overlapping order by

---

go/vt/mysqlctl/s3backupstorage/s3.go

Temporary/Dirty fix for uploading on S3 like storage (Minio, Swift, etc...)
workaround #14188

Fix backup on s3 like storage

---

Makefile
go/tools/sizegen/sizegen.go

This was broken with the new pool.
Broken in #14034

Fix codegen command with the right type

---

misc/git/hooks/shellcheck

This is a minor improvement that will help eliminate unhelpful shellcheck errors — surfaced via the pre-commit hooks: `.git/hooks/pre-commit` -> `misc/git/hooks/shellcheck` — as well as potentially surface new things.
It does this by adding the `-x` shell flag so that shellcheck will follow the files and validate them as well. Here's an example:
```
❯ shellcheck tools/remove_dependencies.sh
In tools/remove_dependencies.sh line 21:
source build.env
^-------^ SC1091 (info): Not following: build.env was not specified as input (see shellcheck -x).
For more information:
https://www.shellcheck.net/wiki/SC1091 -- Not following: build.env was not ...
❯ shellcheck -x tools/remove_dependencies.sh
```
-   [x] Tests …

Tell shellcheck to follow sourced files

---

go/vt/vtctl/workflow/server.go
go/vt/vtctl/workflow/traffic_switcher.go

While porting over the switchReads() code to vtctldclient, the code was incorrectly using the tablet types passed in the command request while updating routing rules. When all trafffic is switched, the list of tablet types includes primary tablets as well. This caused writes to be switched to the target even before the switchWrites() code was called.
This was caught in https://github.com/vitessio/vitess/issues/13954, because vdiff alerted about mismatches in the reverse replication workflow. The reason other e2e tests have not caught it is that, the new one has a load generator script that runs concurrently to the vtctld call which switches writes. 
https://github.com/vitessio/vitess/issues/12152
-   [ ] …

Vtctld SwitchReads: fix bug where writes were also being switched as part of switching reads when all traffic was switched using SwitchTraffic

---

go/vt/sidecardb/schema/vdiff/vdiff.sql
go/vt/vttablet/tabletmanager/vdiff/controller.go
go/vt/vttablet/tabletmanager/vdiff/engine_test.go
go/vt/vttablet/tabletmanager/vdiff/framework_test.go
go/vt/vttablet/tabletmanager/vdiff/schema.go
go/vt/vttablet/tabletmanager/vdiff/table_differ.go
go/vt/vttablet/tabletmanager/vdiff/workflow_differ.go

While working on https://github.com/vitessio/vitess/pull/14327, I experienced repeatable panics while running vdiffs on the workflows which had two tables. The second vdiff would be initialized before the first one ended, resulting in the channel used to synchronize results to be overwritten  by the second vdiff before it was cancelled by the first one. 
This PR adds synchronization so that the context in which the shard streams run to be cancelled when a table's differ is deemed complete, and the vdiff waits for these streams to complete before proceeding.
In addition there was a separate error while saving the error state in the vdiff record. The error contained gtids which can be arbitrarily large. The PR also limits the size of the error being recorded.
- Fixes: …

VDiff: wait for shard streams of one table diff to complete for before starting that of the next table

---

go/vt/schemadiff/names.go
go/vt/schemadiff/names_test.go
go/vt/vttablet/onlineddl/executor_test.go

Similarly to https://github.com/vitessio/vitess/pull/10638, this PR removes the table name from auto-generated foreign key constraint names. The reason is that due to MySQL behavior, when you `RENAME TABLE t TO something_else`, all auto-generated constraints names, including foreign key names, are likewise renamed. In the above example, that means the constraint name length increases by `13` characters. With Vitess internal names that easily risks running out of constraint name allowed length (`64` characters), which in turn fails the `RENAME`.
The existing code was already meant to deal with the situation, but by mistake used `fk`, rather than `ibfk`, as the indicator for auto-generated names.
- #11975 
- …

schemadiff: remove table name from auto-generated FK constraint name

---

go/vt/schemadiff/schema_diff_test.go
go/vt/schemadiff/table.go
go/vt/schemadiff/table_test.go

See https://github.com/vitessio/vitess/issues/14386 for description. In this PR `schemadiff` not only maps the constraints, but also their numbers. This is essential because previously, different identical constraints were only counted _once_ when diffing tables in `ConstraintNamesIgnoreAll|ConstraintNamesIgnoreVitess` hints. This made it impossible to get rid of a duplicate constraint.
- Fixes https://github.com/vitessio/vitess/issues/14386
- #11975 

schemadiff: fix missing `DROP CONSTRAINT` in duplicate/redundant constraints scenario.

---

go/vt/vtgate/endtoend/main_test.go
go/vt/vtgate/endtoend/oltp_test.go
go/vt/vtgate/endtoend/schema.sql
go/vt/vtgate/engine/ordered_aggregate.go
go/vt/vtgate/engine/route.go
go/vt/vtgate/evalengine/api_compare.go
go/vt/vttest/local_cluster.go
go/vt/vttest/vtprocess.go

I'm investigating the performance regressions in the Vitess 18 release compared to Vitess 17.
From reproducing the synthetic benchmarks, there are two issues I've encountered:
1. The aggregation code now allocates rows when no aggregation is performed (i.e. when you run a `DISTINCT` without aggregation). I've fixed that in this PR by optimizing this particular case which I hadn't considered before. This is a very common pattern in the OLTP benchmarks so I think this will revert some of the regression.
2. The `sort` primitive in the engine is extremely hot. This is nothing new -- it has always been hot, but it can now be optimized with the new generics-based implementation, which should be much faster for all cases. I've done this optimization in this PR and the results are very good …

Performance Fixes for Vitess 18

---

go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
go/test/endtoend/vtgate/foreignkey/stress/fk_stress_test.go
go/vt/vttablet/onlineddl/executor.go
go/vt/vttablet/onlineddl/schema.go
test/config.json

As explained in https://vitess.io/blog/2021-06-15-online-ddl-why-no-fk/, Online DDL cannot work with vanilla MySQL.
However, [this patch](https://github.com/planetscale/mysql-server/commit/bb777e3e86387571c044fb4a2beb4f8c60462ced), as part of [this public fork](https://github.com/planetscale/mysql-server/releases/tag/8.0.34-ps1), modifies MySQL as follows:
- Adds a `rename_table_preserve_foreign_key` global/session boolean variable (defaults false/0 for backwards compatibility).
- When enabled, a `RENAME TABLES` statement that replaces two tables Online-DDL-style, pins any children tables' foreign keys to the table name rather than the table pointer. Meaning after the `RENAME`, the children point to the new table that is using the original table name, rather than migrating along with the …

Enable Online DDL foreign key support (also in vtgate stress tests) when backing MySQL includes appropriate patch

---

go/vt/vtctl/workflow/materializer.go
go/vt/vtctl/workflow/materializer_env_test.go
go/vt/vtctl/workflow/materializer_test.go
go/vt/wrangler/materializer.go
go/vt/wrangler/materializer_env_test.go
go/vt/wrangler/materializer_test.go

We were always adding `in_keyrange` filters for a vstream when the target keyspace was sharded. This PR adds a check to see if the shard mappings are 1:1 and the key ranges are equal for both shards — if so then we do not add the `in_keyrange` filter.
When that filter is in place, every row/binlog event on the VReplication stream source must have its KeyspaceID calculated before adding it to the vstream for the target. This same filter from the VReplication record is also used when a `VDiff` is performed for the workflow. In the case of `VDiff`, this means that each source tablet needs to calculate the KeyspaceID for every record read from its mysqld before adding it to the vstream used for the diff.
This additional vindex work can be costly — in particular during the VDiff where you are …

VStream: Skip vindex keyrange filtering when we can

---

go/vt/vtgate/semantics/analyzer_test.go
go/vt/vtgate/semantics/scoper.go

When we see a UNION, we added a new scope but this scope wasn't popped properly, leading to an unbalanced stack.
Broken in #14321

semantics: Fix missing union pop from scoper

---

go/vt/schemadiff/schema.go
go/vt/schemadiff/schema_diff_test.go

In this PR we programmatically identify the following scenario:
- We diff two schemas
- We identify one table (child) adds a new foreign key (pointing to a parent).
- And we identify the parent table adds an appropriate index on the FK referenced columns.
- And we identify there isn't an already existing index on referenced columns.
In this scenario, the two changes are strictly sequential, and the two migrations will never be able to run concurrently.
**UPDATE**: we've identified new scenarios, added in this PR. See followup comments.
- Addendum to https://github.com/vitessio/vitess/pull/12551
- #11975 
-   [ ] Did the new or modified tests pass consistently …

schemadiff: identify a FK sequential execution scenario, and more

---

go/tools/release-notes/release_notes.go

When doing releases, we list all PR authors. This change removes our bots from the list of authors.
Example of what the release with bots look like: https://github.com/vitessio/vitess/blob/main/changelog/16.0/16.0.5/release_notes.md

tooling: don't add bots to authors list

---

go/vt/discovery/tablet_picker.go
go/vt/discovery/tablet_picker_test.go
go/vt/vttablet/tabletmanager/vdiff/controller.go
go/vt/vttablet/tabletmanager/vdiff/table_differ.go
go/vt/vttablet/tabletmanager/vreplication/controller.go
go/vt/wrangler/vdiff.go

This PR adds an option to the tablet picker to allow non-serving tablets to be selected. We use this option while picking tablets to stream data for target shards in VDiff runs.
See https://github.com/vitessio/vitess/issues/14400 for more details.
Fixes #14400
This issue was identified while working on https://github.com/vitessio/vitess/pull/14327 and I confirmed that the changes in this PR fix it.

VDiff tablet selection: pick non-serving tablets in Reshard workflows

---

go/test/endtoend/vtgate/errors_as_warnings/main_test.go

The MySQL shutdown is racy, so we might also see this message that it's still shutting down.
Improves the test flakyness hopefully of these tests.

vtgate: Allow more errors for the warning check

---

go/vt/wrangler/fake_tablet_test.go

The test environment was not being properly initialized resulting in panics related to vdiff goroutines. This was not relevant to the test and not failing the tests, but the panics were being logged.

TestStreamMigrateMainflow: fix panic in test

---

go/vt/vtgate/planbuilder/operators/aggregation_pushing.go
go/vt/vtgate/planbuilder/operators/distinct.go
go/vt/vtgate/planbuilder/operators/queryprojection.go
go/vt/vtgate/planbuilder/testdata/aggr_cases.json
go/vt/vtgate/planbuilder/testdata/select_cases.json

This PR updates our column resolution logic to make it closer to what MySQL does. We want to allow this type of query:
```sql
select u.foo, ue.foo as bar 
from user u, user_extra ue 
order by foo
```
MySQL correctly understands that `foo` here is pointing to `u.foo` and nothing else, but Vitess would not always make this connection. As part of this change, we also check for ambiguous columns and will fail some queries that MySQL also fails, but would be accepted by earlier releases of Vitess.
Backports of this PR should not fail ambiguous columns - we don't want to start failing queries in a patch release.
Fixes #14067 …

Make column resolution closer to MySQL

---

go/vt/vtgate/engine/join.go
go/vt/vtgate/engine/scalar_aggregation.go

This change fixes a race condition in the join logic. This is a classic check-then-act style bug. The problem is that we were using a field to track if we already sent fields. This can lead to a concurrency issue though:
- Thread 1 checks if it needs to send fields and sees that it does.
- Thread 2 checks if it needs to send fields and sees it does not.
- Thread 2 sends the result with no fields.
- Downstream consumers crash because they get a first result set with no fields.
There's no locking around the critical section of checking if we need to send fields and actually calling the callback. We need both those to be covered under the same critical section. This change here introduces a lock around this to make sure this happens.
With the lock, it normally would not be necessary to use …

vtgate/engine: Fix race condition in join logic

---

go/vt/vttablet/tabletserver/txthrottler/tx_throttler.go
go/vt/vttablet/tabletserver/txthrottler/tx_throttler_test.go

A number of txThrottler related metrics were added in v18 in #13153. One of them counts the number of active topology watchers created by the txThrottler. As it happens, these watchers are never actually started or used, so in v19 they have been removed from the txThrottler struct. As part of that, the related metric will need to be deprecated in v19 and deleted in v20.
Since this metric was only introduced in v18 (which is not GA yet), a simpler route is to delete the metric from v18 before anyone uses it instead of trying to release/deprecate/delete over 3 releases.
Q: Why did I choose to do this PR on release-18.0 and not on main? 
A: Removing this metric on `main` will be building on #14412 and cannot be cherry-picked cleanly on to the release branch.
Q: Why not delete topology …

tx_throttler: remove topo watchers metric

---

changelog/19.0/19.0.0/summary.md
go/vt/vttablet/tabletserver/txthrottler/tx_throttler.go

Delete the topo watcher metric instead of deprecating. See #14444 for a detailed explanation.
#14412 #14444 

tx_throttler: delete topo watcher metric instead of deprecating

---

go/viperutil/internal/sync/sync.go
go/viperutil/internal/sync/sync_test.go

The way we have setup viper in vitess, it has two distinct instances of viper - one for disk config and one for live config.
Dynamic config needs to be bound to both instances. We were binding them only to disk, but getting them from live, which meant that neither flag values nor default values were actually respected.
This PR fixes that by duplicating the lines of code that do the binding so that both internal instances know of dynamic configs.
#14452 
We should mark this as fixed only after back ports are merged.

viper: register dynamic config with both disk and live

---

go/test/endtoend/cluster/cluster_process.go
go/test/endtoend/tabletgateway/vtgate_test.go
go/vt/vtgate/executor.go

When determining which tablets to show in `show vitess_replication_status` Vitess is excluding tablets if their states were changed. This now uses the target tablet from the heath check cache which represents the expected state of the tablets. 
- Fixes: https://github.com/vitessio/vitess/issues/14432

Bug fix: Use target tablet from health stats cache when checking replication status

---

go/cmd/mysqlctld/cli/mysqlctld.go
go/cmd/vtaclcheck/cli/vtactlcheck.go
go/cmd/vtbackup/cli/vtbackup.go
go/cmd/vtbench/cli/vtbench.go
go/cmd/vtctld/cli/cli.go
go/cmd/vtgate/cli/cli.go
go/cmd/vttablet/cli/cli.go
go/vt/servenv/run.go

The servenv.Run function already runs the close hooks once it finishes. This means there's no use for deferring a `.Close()` since it double executes all close hooks.
In fact, it leads to panics. For example, vttablet always panics on each shutdown because the connection to the topo is already closed.
Fixes #14458 

servenv: Remove double close() logic

---

go/test/endtoend/vtgate/errors_as_warnings/main_test.go

There's an additional error that we can see in this errors as warnings check.
It refactors it slightly to have one list instead that isn't on a huge single line.
Follow up to #14421

vtgate: Allow additional errors in warnings test

---

go/test/endtoend/vreplication/vdiff_multiple_movetables_test.go
go/vt/vtctl/workflow/server.go
go/vt/vttablet/tabletmanager/vdiff/action.go
go/vt/vttablet/tabletmanager/vdiff/action_test.go
go/vt/vttablet/tabletmanager/vdiff/schema.go
test/config.json

This PR fixes a bug where the specified keyspace and workflow were ignored in the "show all" action.
There was no candidate e2e test that could be extended for this. So a new test has been added which has multiple concurrent workflows.
Fixes https://github.com/vitessio/vitess/issues/14443

VDiff: "show all" should only report vdiffs for the specified keyspace and workflow

---

go/test/endtoend/vreplication/vreplication_test.go
go/textutil/strings.go
go/vt/vttablet/tabletmanager/rpc_vreplication.go
go/vt/vttablet/tabletmanager/rpc_vreplication_test.go

The new [`workflow update`](https://vitess.io/docs/reference/programs/vtctldclient/vtctldclient_workflow/vtctldclient_workflow_update/) and the [`workflow start|stop commands`](https://vitess.io/docs/reference/programs/vtctldclient/vtctldclient_workflow/) did not work when a target shard has multiple source streams. See [the issue](https://github.com/vitessio/vitess/issues/14446) for additional details.
This PR correctly handles this scenario.
- Fixes: https://github.com/vitessio/vitess/issues/14446

VReplication: Handle multiple streams in UpdateVReplicationWorkflow RPC

---

go/vt/vtctl/grpcvtctldserver/server.go
go/vt/vtctl/grpcvtctldserver/server_test.go

You can filter tablets by keyspace, shard, and tablet-type with the [`GetTablets` command](https://vitess.io/docs/reference/programs/vtctldclient/vtctldclient_gettablets/).
There is a different path taken when keyspace _and_ shard are _both_ specified, however, and in that path the tablet type filtering was not done. This PR corrects that and applies the tablet type filtering everywhere if requested.
- Fixes: https://github.com/vitessio/vitess/issues/14462

vtctldclient: Apply tablet type filtering for keyspace+shard in GetTablets

---

go/vt/sqlparser/normalizer.go
go/vt/sqlparser/normalizer_test.go

This PR relates to https://github.com/vitessio/vitess/issues/14450, adding a test and attempting to resolve what appears to be an incorrect sharing of a bind var between a HexVal e.g. `x'31'` and an Int e.g. `31`. This occurs because the type is not considered as part of the key for the BindVar map.
There was some existing code that attempted to disambiguate literal values as map keys by prefixing a single quote. Since this proved to not be correctly handling all situations, I thought it appropriate to key by the `Literal` itself. This ensures that a literal's `Type` is also considered first class in disambiguation.
I chose to use the `Literal` rather than `*Literal` because literals with the same type and value are intended to share a `BindVar`.
There's now slightly more data in the key …

Ensure hexval and int don't share BindVar after Normalization

---

go/sqltypes/type.go
go/test/endtoend/vtgate/queries/random/random_test.go
go/vt/vtgate/engine/opcode/constants.go
go/vt/vtgate/evalengine/api_literal.go
go/vt/vtgate/evalengine/collation.go
go/vt/vtgate/evalengine/compiler_asm.go
go/vt/vtgate/evalengine/compiler_test.go
go/vt/vtgate/evalengine/eval.go
go/vt/vtgate/evalengine/eval_temporal.go
go/vt/vtgate/evalengine/expr_bvar.go
go/vt/vtgate/evalengine/expr_collate.go
go/vt/vtgate/evalengine/expr_column.go
go/vt/vtgate/evalengine/fn_base64.go
go/vt/vtgate/evalengine/fn_crypto.go
go/vt/vtgate/evalengine/fn_hex.go
go/vt/vtgate/evalengine/fn_misc.go
go/vt/vtgate/evalengine/fn_numeric.go
go/vt/vtgate/evalengine/fn_string.go
go/vt/vtgate/evalengine/fn_time.go
go/vt/vtgate/evalengine/translate.go
go/vt/vtgate/planbuilder/operators/dml_planning.go
go/vt/vtgate/planbuilder/operators/insert.go
go/vt/vtgate/planbuilder/operators/projection.go
go/vt/vtgate/planbuilder/operators/route_planning.go
go/vt/vtgate/planbuilder/operators/update.go
go/vt/vtgate/planbuilder/testdata/onecase.json
go/vt/vtgate/planbuilder/testdata/tpch_cases.json
go/vt/vtgate/semantics/dependencies.go
go/vt/vtgate/semantics/typer.go

@systay discovered this issue during fuzzing. We need special handling for the coercibility of numeric types in the `evalengine`, otherwise some `case` expressions will not be collated as text as you'd expect.
We've fixed the issue by replacing the generic `defaultCoercionCollation` helper with an enhanced version that takes into account the type of the value being collated. This also fixes mismatched collations for some datetime and JSON values.
Here's an example of an expression that had the right return type, but the wrong collation before this change:
```
expression: `case column0 when 1 then column1 else column2 end`,
values:     []sqltypes.Value{sqltypes.NewInt64(42), sqltypes.NewVarChar("sole"), sqltypes.NewInt64(0)},
result:     `VARCHAR("0")`,
collation: …
```

evalengine: fix numeric coercibility

---

go/mysql/conn.go

This is an outlier in the profiles for OLTP benchmarks. There's a lot of wasteful allocations and CPU usage in the write path for the MySQL connection for two reasons:
1. We keep creating new `Timer`s for flushing every write call. To fix this, keep a single `Timer` and call `Reset`.
2. We return a closure from `getConn` for every write call. The closure contains the cleanup required after the write (unlocking the buffer and triggering the flush), but it captures the connection pointer itself, so it keeps allocating. Fix this by inlining `getConn` and deferring the cleanup only when required.
Flame graph comparison (the size relative size difference is accurate): 
cc @harshit-gangal @systay 
-   [ ] Tests …

mysql/conn: do not allocate during writes

---

.github/workflows/local_example.yml
examples/common/scripts/zk-down.sh
examples/common/scripts/zk-up.sh

Running the local example with `TOPO=zk2` fails with an error from zkctl startup.
This is because we changed flags to use `--` instead of `-` back in v16.
This was broken at least on main, most likely on 17, and probably on v16 as well.
Fixes #14471 

examples: fix flag syntax for zkctl

---

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
go/vt/vtgate/engine/opcode/constants.go
go/vt/vtgate/planbuilder/operators/aggregation_pushing.go
go/vt/vtgate/planbuilder/operators/phases.go
go/vt/vtgate/planbuilder/operators/queryprojection.go
go/vt/vtgate/planbuilder/testdata/aggr_cases.json
go/vt/vtgate/planbuilder/testdata/tpch_cases.json
go/vt/vtgate/planbuilder/testdata/unsupported_cases.json

Adds support for AVG on queries that need to be sharded. We can't just send down `AVG` to each shard and average these together. We need to turn `AVG` into `SUM/COUNT`, which is easy to shard.
Paired with @arthurschreiber on this
Fixes #9397

Add support for AVG on sharded queries

---

go/cmd/vtctldclient/command/vreplication/materialize/create.go
go/vt/sqlparser/ast_format.go
go/vt/sqlparser/ast_format_fast.go
go/vt/sqlparser/ast_funcs.go
go/vt/sqlparser/ast_rewriting.go
go/vt/sqlparser/utils.go
go/vt/topotools/vschema_ddl.go
go/vt/vtgate/planbuilder/builder.go
go/vt/vtgate/planbuilder/call_proc.go
go/vt/vtgate/planbuilder/delete.go
go/vt/vtgate/planbuilder/operators/projection.go
go/vt/vtgate/planbuilder/operators/queryprojection.go
go/vt/vtgate/planbuilder/operators/table.go
go/vt/vtgate/planbuilder/show.go
go/vt/vtgate/semantics/derived_table.go
go/vt/vtgate/semantics/early_rewriter.go
go/vt/vtgate/semantics/scoper.go
go/vt/vtgate/semantics/table_set.go
go/vt/vtgate/semantics/vtable.go
go/vt/vttablet/tabletmanager/vdiff/table_plan.go
go/vt/vttablet/tabletserver/schema/tracker.go
go/vt/vttablet/tabletserver/vstreamer/planbuilder.go
go/vt/wrangler/vdiff.go

This is not super important, but it does take it's toll. Whenever reading an `if` statement that is using an identifier, and we are checking that it's not empty, we write something like this:
```golang
if !to.QTable.Alias.As.IsEmpty() { ... }
```
The distance between the `!` and the `IsEmpty()` is quite a few characters apart, and that forces me to do an extra mental step when reading code. I much prefer using `NotEmpty` for this:
```golang
if to.QTable.Alias.As.NotEmpty() { ... }
```
This makes the code slightly more readable, and we can use all the readability we can get.

Refactor: use NonEmpty() instead of !IsEmpty()

---

go/test/endtoend/vtgate/queries/informationschema/informationschema_test.go
go/vt/vtgate/planbuilder/operators/aggregator.go
go/vt/vtgate/planbuilder/operators/horizon.go
go/vt/vtgate/planbuilder/operators/route_planning.go
go/vt/vtgate/planbuilder/testdata/aggr_cases.json
go/vt/vtgate/planbuilder/testdata/info_schema57_cases.json
go/vt/vtgate/planbuilder/testdata/info_schema80_cases.json
go/vt/vtgate/planbuilder/testdata/select_cases.json
go/vt/vtgate/planbuilder/testdata/unsupported_cases.json

Somehow we missed adding the relevant tests, and the issue resurfaced. 
For this query:
```sql
SELECT c.column_name FROM user c JOIN (
SELECT table_name FROM unsharded LIMIT 1) AS tables 
ON tables.table_name = c.table_name
```
The planner changes the sides, because we use a nested loop join, and it's much easier to have the limited side on the left - we don't even have the code to support LIMIT on the RHS of our joins.
Somehow, when planning the limited LHS of the join, we did not pull out the `table_name` column from the derived table, and instead returned a literal `1`:
```sql
select 1 from (select table_name from unsharded limit 1) as `tables`
```
This value was then used on the RHS to search for matches, and most often there were none.
Fixes …

planbuilder bugfix: expose columns through derived tables

---

go/test/endtoend/reparent/plannedreparent/reparent_test.go

It looks like the changes made in https://github.com/vitessio/vitess/pull/13623 broke the upgrade downgrade tests in release-17.0.
This PR copies over changes from that PR related to the changes in the test files so that upgrade tests work.

Fix Upgrade downgrade reparent tests in release-17.0

---

changelog/16.0/16.0.6/changelog.md
changelog/16.0/16.0.6/release_notes.md
changelog/16.0/README.md
changelog/17.0/17.0.4/changelog.md
changelog/17.0/17.0.4/release_notes.md
changelog/17.0/README.md

This PR moved release notes from 16.0.6 and 17.0.4 patch releases to `main`

move over 16.0.6 and 17.0.4 release notes to main

---

go/vt/vttablet/onlineddl/schema.go
go/vt/vttablet/onlineddl/vrepl.go

This PR follows up on https://github.com/vitessio/vitess/pull/13352. It utilizes `fast_analyze_table` (global/session variable), introduced in https://github.com/planetscale/mysql-server/commit/c8a9d93686358dabfba8f3dc5cc0621e3149fe78 as part of https://github.com/planetscale/mysql-server/releases/tag/8.0.34-ps1.
In this PR, and when `--analyze-table` DDL strategy flag is provided, the Online DDL executor checks for existence of this variable. If the variable exists, then the executor will set it to `1` prior to running `ANALYZE TABLE ...`.
This introduced code is safe to run on MySQL versions that do not support the variable, as the initial probing query is 
```sql
show global variables like 'fast_analyze_table'
```
which is always safe to run. The query returns 0 rows on unsupporting …

Support `fast_analyze_table` variable, introduced in public MySQL fork

---

go/mysql/flavor.go
go/mysql/flavor_mysql.go
go/mysql/flavor_test.go
go/test/endtoend/onlineddl/revert/onlineddl_revert_test.go
go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
go/vt/vttablet/onlineddl/executor.go

Followup to https://github.com/vitessio/vitess/pull/10638 and https://github.com/vitessio/vitess/pull/14385, this PR edits a `CREATE TABLE` statement, to remove the table-name prefix from existing constraint names. This is so as to make the constraint name a non-generated one. The reasoning is to avoid https://bugs.mysql.com/bug.php?id=107772
e.g. if some issues:
```sh
vtctldclient ApplySchema --ddl_strategy="vitess" --sql "create table mytable (id int primary key, check ((id >= 0)))" commerce
```
Then MySQL auto generates a constraint name, and the `CREATE TABLE` statement becomes:
```sql
CREATE TABLE `mytable` (
`id` int NOT NULL,
PRIMARY KEY (`id`),
CONSTRAINT `mytable_chk_1` CHECK ((`id` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```
However, Online DDL …

Online DDL: edit CONSTRAINT names in CREATE TABLE

---

go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go

This is a quick followup to https://github.com/vitessio/vitess/pull/14517
The `onlineddl_scheduler` test has an "invisible" failure, passing in OSS CI, but failing on a `DROP FOREIGN KEY` test running on publicly forked MySQL. While we are still to deploy the forked MySQL server in `vitessio/vitess` CI, here's a quick fix.
This fix works both as a standalone as well as in combination with #14517.
- https://github.com/vitessio/vitess/pull/14517
- https://bugs.mysql.com/bug.php?id=107772

Online DDL: fix endtoend test dropping foreign key

---

go/test/endtoend/mysqlctld/mysqlctld_test.go
go/vt/mysqlctl/grpcmysqlctlserver/server.go

As per https://github.com/vitessio/vitess/issues/14506, calls to `ReadBinlogFilesTimestamps` failed with `rpc error: code = Unimplemented desc = method ReadBinlogFilesTimestamps not implemented`.
This affects users of `mysqlctld`, but was not detected in `endtoend` tests, which were not using the same.
The function is added and now tested.
A `release-18.0` backport is needed, but also requires a backwards-compatibility fix to `17.0`, because the function `ReadBinlogFilesTimestamps` is new to `v18`. A special PR for 18 release to follow.

MysqlCtl: implement missing `ReadBinlogFilesTimestamps` function

---

go/test/endtoend/mysqlctld/mysqlctld_test.go
go/vt/mysqlctl/backup_test.go
go/vt/mysqlctl/builtinbackupengine.go
go/vt/mysqlctl/grpcmysqlctlserver/server.go

Fixes https://github.com/vitessio/vitess/issues/14506
This PR contains two fixes:
1. Similarly to https://github.com/vitessio/vitess/pull/14525, implements `ReadBinlogFilesTimestamps`.
2. Adds backwards compatibility to `ReadBinlogFilesTimestamps` invocation. `ReadBinlogFilesTimestamps` was introduced in `v18`. If a `v18` `vtctldclient` calls a `v17` `mysqlctld` daemon, then that daemon does not implement said function. The solution here is to check the returned error, and ignore accordingly. It's a bit ugly, and it's a workaround to something we should not have introduced in a single step.
https://github.com/vitessio/vitess/issues/14506 …

[release 18.0]: `ReadBinlogFilesTimestamps` backwards compatibility

---

go/vt/srvtopo/resilient_server.go
go/vt/srvtopo/resilient_server_test.go
go/vt/vttablet/tabletserver/vstreamer/testenv/testenv.go

The logic for the topo resilient server has been apparently broken since it was introduced.  I fixed a single test that was mis-named, that led to a panic with this change.  I would like to test that the name of the metric is now correct, but the stats module does not make that easy, so something like an end-to-end test would be required, and I do not think this fix justifies that level of effort. 
Unnecessary to backport, affects metrics only.
- Fixes: https://github.com/vitessio/vitess/issues/14414

Fix #14414:  resilient_server metrics name/prefix logic is inverted, leading to no metrics being recorded

---

go/vt/vterrors/code.go

This is a short follow up of https://github.com/vitessio/vitess/pull/14339, and the issue mentioned in https://github.com/vitessio/vitess/pull/14339#discussion_r1392980715.

Fix missing query serving error code

---

go/test/endtoend/vtgate/foreignkey/fk_test.go
go/vt/vtgate/engine/cached_size.go
go/vt/vtgate/engine/fk_cascade.go
go/vt/vtgate/planbuilder/operators/update.go
go/vt/vtgate/planbuilder/testdata/foreignkey_cases.json

This PR fixes the issue described in https://github.com/vitessio/vitess/issues/14523.
I looked at the plan and followed along with what Vitess should have done. The first thing we do is run a SELECT query and that works as intended -
```sql
mysql [localhost:8032] {msandbox} (foreign_key_rfc) > select col, col <=> col * (col - col), col * (col - col) from fk_t15 for update;
+------+---------------------------+-------------------+
| col  | col <=> col * (col - col) | col * (col - col) |
+------+---------------------------+-------------------+
| -0   |                         1 |                -0 |
| -5   |                         0 |                -0 |
| 0    |                         1 |                 0 |
| 5    |                         0 |                 0 | …
```

Fix type coercion in cascading non-literal updates

---

go/mysql/sqlerror/constants.go
go/test/endtoend/utils/utils.go
go/test/endtoend/vtgate/foreignkey/fk_fuzz_test.go
go/test/endtoend/vtgate/foreignkey/fk_test.go
go/test/endtoend/vtgate/foreignkey/stress/fk_stress_test.go
go/vt/vterrors/code.go
go/vt/vtgate/engine/sequential.go
go/vt/vtgate/planbuilder/operators/delete.go
go/vt/vtgate/planbuilder/operators/query_planning.go
go/vt/vtgate/planbuilder/operators/update.go
go/vt/vtgate/planbuilder/plan_test.go
go/vt/vtgate/planbuilder/testdata/foreignkey_cases.json
go/vt/vtgate/planbuilder/testdata/foreignkey_checks_off_cases.json
go/vt/vtgate/planbuilder/testdata/foreignkey_checks_on_cases.json
go/vt/vtgate/semantics/analyzer_fk_test.go
go/vt/vtgate/vschema_manager_test.go

While adding replace into support for foreign keys in unsharded tables, we discovered that select queries executed for foreign key cascade were not able to acquire an adequate level of lock on the unique key due to missing gap locks. This led to incorrect results, and further plan execution would result in missing cascading rows, leading to incomplete data in the binary logs.
VReplication workflow relies on these binary logs for tasks like online-ddl or change log streaming.
Example case:
```
drop table if exists some_table;
create table some_table (
id bigint,
col varchar(10),
primary key (id),
unique index(col)
) ;
insert into some_table(id, col) values (3, null), (4, 5);
-- Session 1
begin;
select col from some_table where col in (5) or id in (3)  for update;
-- Session 2
begin;
select …
```

Enable `Replace Into` engine and Fix Foreign key locking issue

---

go/vt/mysqlctl/mysqld.go
go/vt/mysqlctl/mysqld_test.go

When we know the lock file is stale, we can clean it up safely inside `mysqlctl` so that we can safely start MySQL again.
Fixes #14552 

mysqlctl: Cleanup stale socket lockfile

---

go/vt/vtgate/planbuilder/builder.go

This PR remove the excessive logging for `Gen4` as default planner.
- Fixes https://github.com/vitessio/vitess/issues/14551

Remove excessive VTGate logging of default planner selection

---

go/mysql/collations/integration/main_test.go
go/vt/vtgate/evalengine/api_type_aggregation.go
go/vt/vtgate/evalengine/compiler_asm.go
go/vt/vtgate/evalengine/compiler_test.go
go/vt/vtgate/evalengine/expr_arithmetic.go
go/vt/vtgate/evalengine/expr_bit.go
go/vt/vtgate/evalengine/expr_bvar.go
go/vt/vtgate/evalengine/expr_compare.go
go/vt/vtgate/evalengine/expr_logical.go
go/vt/vtgate/evalengine/expr_tuple.go
go/vt/vtgate/evalengine/fn_base64.go
go/vt/vtgate/evalengine/fn_bit.go
go/vt/vtgate/evalengine/fn_compare.go
go/vt/vtgate/evalengine/fn_crypto.go
go/vt/vtgate/evalengine/fn_hex.go
go/vt/vtgate/evalengine/fn_json.go
go/vt/vtgate/evalengine/fn_misc.go
go/vt/vtgate/evalengine/fn_numeric.go
go/vt/vtgate/evalengine/fn_string.go
go/vt/vtgate/evalengine/testcases/inputs.go
go/vt/vtgate/executor_select_test.go

A number of expressions and function implementations in the evalengine were not correctly propagating the nullable checks. For example the multiplication operation didn't do this. This can lead to crashes in the evalengine.
Here the flags have been audited and set properly. New test inputs are also added to ensure we exercise more of these paths.
Fixes #14558 

Fix nullability checks in evalengine

---

go/vt/sqlparser/predicate_rewriting.go
go/vt/sqlparser/predicate_rewriting_test.go
go/vt/vtgate/executor_select_test.go
go/vt/vtgate/planbuilder/testdata/filter_cases.json

When we can't find a good vindex to use, we try rewriting the WHERE clause into CNF (conjuctive normal form), and this transformation can in the worst case become an exponentially large expression. To stop this from happening, we count the number of `OR` expression we are dealing to stop the worst case from happening.

expression rewriting: enable more rewrites and limit CNF rewrites

---

go/vt/vtgate/planbuilder/operators/query_planning.go
go/vt/vtgate/planbuilder/testdata/postprocess_cases.json

When decided what should be pushed under what, we made a mistake. 
The thinking was that if we need to filter and order the results, we should filter first so we have less to order. For that reason we didn't push ordering under filtering.
Unfortunately, this means that we forced the sorting to happen on the vtgate side, which means that we have to have the full result set before we can sort it, and that can easily lead to OOMs.
Here we are allowing the ordering to be pushed down under the route, which means that MySQL is producing ordered results. These can be merged together one chunk at a time, thanks to the pre-sorting. …

planbuilder: push down ordering through filter

---

go/vt/sqlparser/predicate_rewriting.go
go/vt/sqlparser/predicate_rewriting_test.go

In a recent change (#14560) we fixed a bug in the CNF rewriter that stopped it from rewriting a lot of cases.
Unfortunately, we succeeded too well, and the newly rewritten expressions are timing out in expression fuzzing on CI. This is because CNF rewriting in some situations result in huge outputs (see [Wikipedia](https://en.wikipedia.org/wiki/Conjunctive_normal_form#Conversion_into_CNF))
This PR stops the rewriting once the produced expression has grown to 10 times the size of the original expression. 
Fixes #14569

bug fix: stop all kinds of expressions from cnf-exploding

---

go/vt/vtgate/engine/distinct.go
go/vt/vtgate/engine/distinct_test.go
go/vt/vtgate/engine/fake_primitive_test.go
go/vt/vtgate/engine/filter.go
go/vt/vtgate/engine/filter_test.go
go/vt/vtgate/engine/limit.go
go/vt/vtgate/engine/limit_test.go
go/vt/vtgate/engine/memory_sort.go
go/vt/vtgate/engine/memory_sort_test.go
go/vt/vtgate/engine/projection.go
go/vt/vtgate/engine/projection_test.go

This PR adds the required lock on the engine primitive with Streaming support where a local state is maintained and needs to be synchronized between parallel calls from underlying callbacks.
The primitive were either returning the wrong result or were causing VTGate panics.
- https://github.com/vitessio/vitess/issues/14581

fix concurrency on stream execute engine primitives

---

go/vt/sqlparser/predicate_rewriting.go
go/vt/sqlparser/predicate_rewriting_test.go

In a recent change (#14560) we fixed a bug in the CNF rewriter that stopped it from rewriting a lot of cases.
Unfortunately, we succeeded too well, and the newly rewritten expressions are timing out in expression fuzzing on CI. This is because CNF rewriting in some situations result in huge outputs (see [Wikipedia](https://en.wikipedia.org/wiki/Conjunctive_normal_form#Conversion_into_CNF))
This PR stops the rewriting once the produced expression has grown to 10 times the size of the original expression. 
Fixes #14569
Backport of #14585

[18.0] bug fix: stop all kinds of expressions from cnf-exploding

---

go/vt/sqlparser/predicate_rewriting.go
go/vt/sqlparser/predicate_rewriting_test.go

In a recent change (#14560) we fixed a bug in the CNF rewriter that stopped it from rewriting a lot of cases.
Unfortunately, we succeeded too well, and the newly rewritten expressions are timing out in expression fuzzing on CI. This is because CNF rewriting in some situations result in huge outputs (see [Wikipedia](https://en.wikipedia.org/wiki/Conjunctive_normal_form#Conversion_into_CNF))
This PR stops the rewriting once the produced expression has grown to 10 times the size of the original expression. 
Fixes #14569
Backport of #14585

[16.0] bug fix: stop all kinds of expressions from cnf-exploding

---

go/vt/sqlparser/predicate_rewriting.go
go/vt/sqlparser/predicate_rewriting_test.go

In a recent change (#14560) we fixed a bug in the CNF rewriter that stopped it from rewriting a lot of cases.
Unfortunately, we succeeded too well, and the newly rewritten expressions are timing out in expression fuzzing on CI. This is because CNF rewriting in some situations result in huge outputs (see [Wikipedia](https://en.wikipedia.org/wiki/Conjunctive_normal_form#Conversion_into_CNF))
This PR stops the rewriting once the produced expression has grown to 10 times the size of the original expression. 
Fixes #14569
Backport of #14585

[17.0] bug fix: stop all kinds of expressions from cnf-exploding

---

go/vt/mysqlctl/mysqld.go
go/vt/mysqlctl/mysqld_test.go

The lock file can have a newline, so we need to trim any space like characters before we try to parse the PID.
Fixes #14552 

mysqlctl: Fix cleaning up the stale lock file

---

go/test/endtoend/vtgate/foreignkey/fk_test.go
go/vt/vtgate/engine/cached_size.go
go/vt/vtgate/engine/fk_cascade.go
go/vt/vtgate/planbuilder/operators/update.go
go/vt/vtgate/planbuilder/operators/update_test.go
go/vt/vtgate/planbuilder/testdata/foreignkey_cases.json
go/vt/vtgate/planbuilder/testdata/foreignkey_checks_on_cases.json
go/vt/vtgate/planbuilder/testdata/vschemas/schema.json

This PR fixes the bug described in https://github.com/vitessio/vitess/issues/14589. 
Since `fk_t16` has child tables and this is a non-literal update, Vitess has to cascade the changes and then update the `fk_t16` table with foreign key checks turned off. This requires Vitess to verify that the updated values are present in the parent table i.e. `fk_t15`.
Previously Vitess was using a query like `select 1 from fk_t16 left join fk_t15 on fk_t15.col = fk_t16.col * (fk_t16.col - fk_t16.col) where fk_t16.col * (fk_t16.col - fk_t16.col) is not null and not (fk_t16.col) <=> (fk_t16.col * (fk_t16.col - fk_t16.col)) and fk_t16.id = 3 and fk_t15.col is null limit 1 for share nowait`.
The problem is that `fk_t16.col * (fk_t16.col - fk_t16.col)` evaluates to `-0` but of type float. When compared to …

Type Cast all update expressions in verify queries

---

go/test/endtoend/vtgate/queries/subquery/subquery_test.go
go/vt/vtgate/planbuilder/operators/subquery.go
go/vt/vtgate/planbuilder/testdata/filter_cases.json
go/vt/vtgate/planbuilder/testdata/tpch_cases.json

The plans produced for `NOT IN` queries that have to be scattered did not handle the missing values case, which leads to wrong results for these situations.
Fixes #14605

plabuilder: use OR for not in comparisons

---

go/vt/vtgate/evalengine/api_aggregation.go
go/vt/vtgate/evalengine/api_aggregation_test.go

We were not storing the precision for the decimal here, resulting in accidentally rounding it.
Fixes #14608

evalengine: Fix the min / max calculation for decimals

---

changelog/19.0/19.0.0/summary.md

This PR fixes the summary changes for the recent PRs - 
- https://github.com/vitessio/vitess/pull/14484 - Summary changes were missed for this PR.
- https://github.com/vitessio/vitess/pull/14505 - The output was changed slightly when addressing reviews, but the new output wasn't copied into the summary file.

Add summary changes for recent PRs

---

.github/workflows/auto_approve_pr.yml

This is a follow-up to #12718 and #12996. `auto_approve_pr.yml` was publishes a few weeks ago with full permissions (when running on a local branch). This PR ensures it runs with minimal permissions.
#12717

 Set minimal tokens for auto_approve_pr

---

go/vt/vtgate/vindexes/unicode.go

Fixes a memory leak in `unicode_loose_*` vindexes by resetting the buffer before returning the collator to the pool.
This issue impacts v18 and below so I think it should be backported to v17 and v16 as well. As noted in the linked issue, the problem does not exist on `main`.
Fixes https://github.com/vitessio/vitess/issues/14587
n/a

vindexes: fix pooled collator buffer memory leak

---

go/vt/sqlparser/predicate_rewriting.go
go/vt/sqlparser/predicate_rewriting_test.go

This PR enhances the `ExtractINFromOR` to support an unlimited number of `OR` in the statement it needs to rewrite.

Support unlimited number of ORs in `ExtractINFromOR`

---

go/vt/vttablet/tabletserver/state_manager.go

Time taken for tablet init should be logged exactly once, and not every time the tablet goes through a state transition.
The way I have chosen to make this happen is by using `sync.Once`. However it is open to debate whether the log line should actually be moved to some other location in the code to ensure that it is called exactly once.
With this change, even after running a PRS, no new log line appears of the form `Tablet Init took 17899ms`.
Fixes #14596 

logging: log time taken for tablet initialization only once

---

go/mysql/flavor_mysql.go

[release-17.0] Replace use of `WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS` with `WAIT_FOR_EXECUTED_GTID_SET` (#14612)

---

go/mysql/flavor_mysql.go

[release-16.0] Replace use of `WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS` with `WAIT_FOR_EXECUTED_GTID_SET` (#14612)

---

go/test/endtoend/vreplication/fk_test.go
go/vt/vtctl/workflow/materializer.go
go/vt/wrangler/materializer.go

In materializer, and right now scoped to `AtomicCopy` operations only (just to keep the blast radius smaller for the time being), we normalize the source schema via `schemadiff` where possible. This ensures ordering of tables is compliant with any foreign key constraints. See https://github.com/vitessio/vitess/issues/14635 for details.
Fixes https://github.com/vitessio/vitess/issues/14635

Materializer: normalize schema via schemadiff on --atomic-copy

---

go/vt/vtctl/grpcvtctldserver/server.go
go/vt/vtctl/reparentutil/util.go
go/vt/vtctl/reparentutil/util_test.go

In the case of at least one tablet being healthy, this PR would increase the chance of successful backup, by only returning Primary + healthy tablets.
In the case of all Non-Primary tablets having errors, vtctlclient should fail in the same way.
https://github.com/vitessio/vitess/issues/14602

increase vtctlclient backupShard command success rate

---

go/vt/vtgate/planbuilder/operators/aggregator.go
go/vt/vtgate/planbuilder/operators/phases.go
go/vt/vtgate/planbuilder/simplifier_test.go
go/vt/vtgate/simplifier/expression_simplifier.go
go/vt/vtgate/simplifier/simplifier.go
go/vt/vtgate/simplifier/simplifier_test.go

While working on a bugfix, I had to extend the simplifier and improve logging. This shouldn't get backported, so I split it into a separate PR.
https://github.com/vitessio/vitess/pull/14641

refactor: minor cleanups in planner code

---

go/test/endtoend/vreplication/fk_config_test.go
go/vt/vttablet/tabletserver/vstreamer/tablestreamer.go

When we do an atomic copy the `tablestreamer` streams all tables. The corresponding `MoveTables` gets its own list of tables, for which it adds filters for each table as part of the vreplication stream's `binlogsource`. For non-atomic copy workflows, we stream each table in the `binlogsource` list of tables. On the target vreplication creates one table plan for each of these tables.
However we get a full list of tables again after we have taken a snapshot (after locking all tables) for atomic copy and stream those tables.
There was a bug where we were not excluding views from this list. Hence the target was seeing a stream from the view resulting in the target stream erroring out since it doesn't have this view in its list of table plans.
This PR fixes that bug. It also adds a view to the …

VReplication TableStreamer: Only stream tables in tablestreamer (ignore views)

---

go/vt/mysqlctl/mysqld.go
go/vt/mysqlctl/mysqld_test.go

When we see a stale socket file, it's not useful to try and start MySQL since we're going to fail to start it anyway.
In that case it's better to error out immediately and either a human or computer operator can try to fix the situation and retry instead of waiting for `wait_time` which is useless at this point.
This is a follow up to #14553 & #14600 to better handle #14552

mysqlctl: Error out on stale socket

---

go/test/endtoend/backup/vtbackup/backup_only_test.go

In general, it's best to shutdown a tablet before its mysqld instance. This ensures that the tablet can perform any shutdown related steps that may affect its mysqld instance.
The existing backup tests were NOT doing that, and the re-use of the MySQL instances could cause some unpredictable behavior.
This PR simply reverses the order of process termination in these tests.
> Note: this is a "temporary" fix as these tests need to be rewritten soon as they rely on long deprecated things that will be removed such as InitTablet and InitShardPrimary (not to mention the odd sharing of processes and state between tests). …

Flakes: Shutdown vttablet before mysqld in backup tests

---

go/cmd/vtbackup/cli/vtbackup.go
go/flags/endtoend/vtbackup.txt

This is about shutdown (as the argument indicates), and not about startup.
Wrongly copy pasted in #14568

vtbackup: Fix copy pasta typo in option description

---

go/test/endtoend/tabletmanager/tablegc/tablegc_test.go
go/timer/suspendable_ticker.go
go/timer/suspendable_ticker_test.go
go/vt/vttablet/onlineddl/executor.go
go/vt/vttablet/tabletserver/gc/tablegc.go
go/vt/vttablet/tabletserver/gc/tablegc_test.go
go/vt/vttablet/tabletserver/tabletserver.go

Normally, the TableGC mechanism checks for GC table statuses once per hour. It will transition tables to their next state, potentially dealing with that new state yet only one hour _later_. There's incentive to speed up the process. But instead of reducing the interval (causing more load on the `PRIMARY`), we choose to intelligently kick new _check_ routines whenever there's a plausible reason -- or an explicit request.
Any time a table changes state, calls for a new cycle that takes place within seconds. A public function, `RequestChecks()`, makes it possible to "inform" the GC mechanism of recent changes that can benefit from GC.
To combat load, the _check_ function is non-reentrant, and discards recurring or flooding calls made within a period of 10 seconds (ie. the function only …

TableGC: speed up GC process via `RequestChecks()`. Utilized by Online DDL for artifact cleanup

---

changelog/19.0/19.0.0/summary.md

This PR adds the summary changes to indicate MySQL 5.7 is EOL and Vitess is dropping support for it in v19. This is in response to the discussion that was prompted from the review comment https://github.com/vitessio/vitess/pull/14598#discussion_r1406623904

Add summary changes to indicate MySQL 5.7 is EOL and Vitess is dropping support for it in v19

---

go/vt/vtctl/grpcvtctldserver/server.go
go/vt/vtctl/grpcvtctldserver/server_test.go

This PR fixes the bug described in https://github.com/vitessio/vitess/issues/14655. We were just missing a nil check and that has been added. This PR also adds a test to verify we don't see the panic anymore.
- Fixes #14655

Fix Panic in PRS due to a missing nil check

---

go/cmd/vttablet/cli/cli.go
go/vt/vtcombo/tablet_map.go
go/vt/vttablet/tabletmanager/tm_init.go
go/vt/vttablet/tabletmanager/tm_init_test.go
go/vt/vttablet/tabletserver/tabletserver.go
go/vt/vttablet/tabletserver/tabletserver_test.go
go/vt/wrangler/fake_tablet_test.go
go/vt/wrangler/testlib/fake_tablet.go

This PR changes the point of time where we wait for the dba grants to be checked. Earlier we were doing this before the restore workflow had run, but it is better to wait for these grants after the restore has completed and we actually want to create the connections using the dba user.
Restore shuts down and restarts MySQL, so it is preferable to check the grants after all of this has completed.
Extension of the work done in https://github.com/vitessio/vitess/pull/14565
- Fixes #14681

Postpone waiting for dba grants after restore has succeeded

---

go/vt/schemadiff/errors.go
go/vt/schemadiff/schema.go
go/vt/schemadiff/schema_test.go

`schemadiff` now has improved granularity for FK reference errors. It now makes a distinction between:
- A referenced table does not exist.
- The referenced table is in fact a `VIEW`.
- There are cyclic (circle > 1) references.
- #11975 

schemadiff: granular foreign key reference errors

---

go/vt/topo/keyspace.go
go/vt/topo/keyspace_external_test.go
go/vt/topo/shard.go
go/vt/topotools/rebuild_keyspace.go
go/vt/topotools/split.go
go/vt/vtctl/grpcvtctldserver/server.go
go/vt/vtctl/workflow/utils.go
go/vt/vtorc/logic/keyspace_shard_discovery.go
go/vt/wrangler/keyspace.go

Speed up `FindAllShardsInKeyspace` by employing caller-controlled concurrency to avoid 30+ second runtimes for this call.
I've added a new struct for configuration here since certain cases such as `CreateShard` should not make concurrent calls in order to avoid a thundering herd on the topo.
Fixes https://github.com/vitessio/vitess/issues/14669.
Introduces some limited concurrency rather than the unbounded concurrency which was removed in https://github.com/vitessio/vitess/pull/5436.
n/a

go/vt/topo: enable concurrency for FindAllShardsInKeyspace

---

go/vt/vttablet/grpctabletconn/conn.go
go/vt/vttablet/onlineddl/executor.go
go/vt/vttablet/onlineddl/vrepl.go
go/vt/vttablet/tabletmanager/vdiff/action.go
go/vt/vttablet/tabletmanager/vreplication/queryhistory/sequenced_expectation_set.go

Resolve a handful of nilness issues in the vttablet packages.
```
✔ ~/src/github.com/planetscale/vitess/go/vt/vttablet [main|✔] 
12:23 $ nilness ./...
/home/matt/src/github.com/planetscale/vitess/go/vt/vttablet/onlineddl/vrepl.go:665:93: nil dereference in field selection
/home/matt/src/github.com/planetscale/vitess/go/vt/vttablet/grpctabletconn/conn.go:191:11: impossible condition: non-nil == nil
/home/matt/src/github.com/planetscale/vitess/go/vt/vttablet/grpctabletconn/conn.go:540:11: impossible condition: non-nil == nil
/home/matt/src/github.com/planetscale/vitess/go/vt/vttablet/grpctabletconn/conn.go:586:11: impossible condition: non-nil == nil
/home/matt/src/github.com/planetscale/vitess/go/vt/vttablet/grpctabletconn/conn.go:643:11: impossible condition: non-nil == nil …
```

go/vt/vttablet: fix nilness issues

---

go/vt/vtgate/engine/vindex_lookup.go
go/vt/vtgate/evalengine/api_coerce.go
go/vt/vtgate/planbuilder/operator_transformers.go
go/vt/vtgate/planbuilder/operators/query_planning.go
go/vt/vtgate/planbuilder/operators/vindex.go

Resolve a handful of nilness issues in the vtgate packages.
```
✔ ~/src/github.com/planetscale/vitess/go/vt/vtgate [main|✔] 
12:08 $ nilness ./...
/home/matt/src/github.com/planetscale/vitess/go/vt/vtgate/evalengine/api_coerce.go:51:10: impossible condition: nil != nil
/home/matt/src/github.com/planetscale/vitess/go/vt/vtgate/engine/routing.go:276:16: tautological condition: nil == nil
/home/matt/src/github.com/planetscale/vitess/go/vt/vtgate/engine/vindex_lookup.go:234:9: impossible condition: nil != nil
/home/matt/src/github.com/planetscale/vitess/go/vt/vtgate/planbuilder/operators/query_planning.go:79:10: impossible condition: nil != nil
/home/matt/src/github.com/planetscale/vitess/go/vt/vtgate/planbuilder/operators/query_planning.go:225:49: impossible condition: nil != nil …
```

go/vt/vtgate: fix nilness issues

---

go/vt/schemadiff/schema.go
go/vt/schemadiff/schema_test.go

When parsing/reading a `Schema` object, we now pursue reading and mapping all tables, even if we hit foreign key definition errors. We take note and aggregate all errors, and at the end we still list all input tables, whether they do have errors or not.
Normally, when the caller of e.g. `s, err := NewSchemaFromEntities(...)` gets a non nil `err`, they bail out. But it is also possible for them to unwrap the list of errors, or even pry open the schema (if non-nil) and read the list of whatever tables they can find.
- Fixes https://github.com/vitessio/vitess/issues/14703
- #11975 
-   [ ] …

schemadiff: pursue foreign key errors and proceed to build schema

---

go/vt/vtgate/planbuilder/operators/ast_to_op.go
go/vt/vtgate/planbuilder/operators/subquery.go
go/vt/vtgate/planbuilder/operators/subquery_builder.go
go/vt/vtgate/planbuilder/testdata/info_schema57_cases.json
go/vt/vtgate/planbuilder/testdata/info_schema80_cases.json
go/vt/vtgate/planbuilder/testdata/unsupported_cases.json

As described in the bug https://github.com/vitessio/vitess/issues/14700, the query given in it fails on runtime. This PR fixes the planner to find these cases at plan-time itself and fail the planning if we are unable to merge the subquery into a route.
- Fixes https://github.com/vitessio/vitess/issues/14700

Fail correlated subquery in planning phase instead of a runtime error

---

go/vt/vtctl/grpcvtctldserver/server.go
go/vt/vtctl/workflow/server.go
go/vt/vtctl/workflow/traffic_switcher.go

Fixes:
```
✔ ~/src/github.com/vitessio/vitess/go/vt/vtctl [main|✔] 
16:16 $ nilness ./...
/home/matt/src/github.com/vitessio/vitess/go/vt/vtctl/workflow/server.go:1445:14: tautological condition: non-nil != nil
/home/matt/src/github.com/vitessio/vitess/go/vt/vtctl/workflow/traffic_switcher.go:383:10: impossible condition: nil != nil
/home/matt/src/github.com/vitessio/vitess/go/vt/vtctl/grpcvtctldserver/server.go:5011:35: tautological condition: non-nil != nil
```
In particular the vtctld server had some confusing error scopes so I tried to infer the correct errors to display based on the surrounding context. It would appear the error message under `conn.ListDir` should show that error, so the existing err variable in scope there would have been completely unrelated to the error being …

go/vt/vtctl: fix nilness issues and error scopes

---

go/vt/wrangler/materializer.go
go/vt/wrangler/traffic_switcher.go
go/vt/wrangler/vexec.go

Fixes:
```
✔ ~/src/github.com/vitessio/vitess/go/vt/wrangler [main|✔] 
16:02 $ nilness ./...
/home/matt/src/github.com/vitessio/vitess/go/vt/wrangler/materializer.go:321:14: tautological condition: non-nil != nil
/home/matt/src/github.com/vitessio/vitess/go/vt/wrangler/traffic_switcher.go:1923:10: impossible condition: nil != nil
/home/matt/src/github.com/vitessio/vitess/go/vt/wrangler/vexec.go:664:9: impossible condition: nil != nil
```
The results map I've removed was immediately shadowed on old line 725. I marked the query string as const as well just to add a bit more safety.
Updates https://github.com/vitessio/vitess/issues/14684. …

go/vt/wrangler: fix nilness issues and unused variable

---

go/vt/topo/srv_keyspace.go
go/vt/topo/tablet.go
go/vt/topo/test/trylock.go

More nilness cleanup, along with tightening error scopes to fix a scoping issue that presented itself as a nilness violation. Remove unused goroutine variables while here.
```
✔ ~/src/github.com/vitessio/vitess/go/vt/topo [main|✔] 
15:39 $ nilness ./...
/home/matt/src/github.com/vitessio/vitess/go/vt/topo/srv_keyspace.go:616:12: tautological condition: non-nil != nil
/home/matt/src/github.com/vitessio/vitess/go/vt/topo/tablet.go:454:9: tautological condition: nil == nil
/home/matt/src/github.com/vitessio/vitess/go/vt/topo/test/trylock.go:141:45: nil dereference in dynamic method call
```
Updates https://github.com/vitessio/vitess/issues/14684.
-   [ ] Did the new …

go/vt/topo: fix nilness issues and unused variables

---

go/vt/vttablet/tabletserver/schema/engine.go
go/vt/vttablet/tabletserver/schema/engine_test.go

This PR fixes the bug reported in https://github.com/vitessio/vitess/issues/14715
It was noticed that in `RegisterNotifier` we don't make a copy of the `tables` map before sending it to the notifier function. 
This can cause a data race since the same table is copied over into the queryEngine which tries to read it, while the next reload of schema in the schema engine would try to overwrite it.
The fix is straightforward. We already make a copy of the map in `broadcast`. We should do the same in `RegisterNotifier`.
A test to make sure that altering the `table` in schema.Engine doesn't impact the notifiers has also been added.
- Fixes https://github.com/vitessio/vitess/issues/14715 …

Fix RegisterNotifier to use a copy of the tables to prevent data races

---

go/test/endtoend/vreplication/fk_ext_test.go

Add wait for row count check that seems to be flaky in CI. It runs fine every time locally.

Flaky TestFKExtWorkflow: fix Foreign Key stress test flakiness

---

go/cmd/vtctldclient/command/routing_rules.go

While reading through the documentation for `ApplyRoutingRules`, I noticed this typo in the flag. This pull request fixes that.
N/A
N/A

Fix typo for `--cells` flag help description in `ApplyRoutingRules`

---

go/pools/smartconnpool/pool_test.go

```
--- FAIL: TestOpen (0.05s)
pool_test.go:174: 
Error Trace:	/home/runner/work/vitess/vitess/go/pools/smartconnpool/pool_test.go:174
Error:      	Not equal: 
expected: int(5)
actual  : int64(4)
Test:       	TestOpen
pool_test.go:175: 
Error Trace:	/home/runner/work/vitess/vitess/go/pools/smartconnpool/pool_test.go:175
Error:      	Not equal: 
expected: 5
actual  : 4
Test:       	TestOpen
FAIL
FAIL	vitess.io/vitess/go/pools/smartconnpool	15.407s
```
Spotted by @harshit-gangal. A sleep is not always enough to synchronize the wait. We can make the synchronization explicit by waiting until a client is in the wait queue, then offering a connection to them.
-   [ ] …

connpool: fix racy test

---

go/cmd/vtgate/cli/plugin_auth_clientcert.go
go/cmd/vtgate/cli/plugin_auth_ldap.go
go/cmd/vtgate/cli/plugin_auth_static.go
go/cmd/vtgate/cli/plugin_auth_vault.go
go/flags/endtoend/vtcombo.txt
go/mysql/auth_server_clientcert.go
go/mysql/auth_server_clientcert_test.go
go/mysql/auth_server_static.go
go/mysql/client.go
go/mysql/client_test.go
go/mysql/conn.go
go/mysql/conn_fake.go
go/mysql/conn_flaky_test.go
go/mysql/conn_params.go
go/mysql/fakesqldb/server.go
go/mysql/handshake_test.go
go/mysql/ldapauthserver/auth_server_ldap.go
go/mysql/mysql_fuzzer.go
go/mysql/server.go
go/mysql/server_flaky_test.go
go/mysql/vault/auth_server_vault.go
go/vt/vtgate/plugin_mysql_server.go
go/vt/vtgate/plugin_mysql_server_test.go

The servenv package is something that is use for server environments like vtgate, vttablet etc. But the go/mysql package should really be independent code for things like the MySQL protocol bits.
This change refactors things so that go/mysql doesn't depend anymore on servenv. This makes it easier to be used as a library for example.
The remaining bits here are in collations, which is something to tackle separately as it's very invasive.
Part of #14717

mysql: Refactor out usage of servenv

---

go/vt/vttablet/tabletserver/messager/message_manager.go
go/vt/vttablet/tabletserver/state_manager.go
go/vt/vttablet/tabletserver/tabletserver.go
go/vt/vttablet/tabletserver/tabletserver_test.go

When executing queries locally using the local TabletServer, you use a `tabletenv.LocalContext`: https://github.com/vitessio/vitess/blob/main/go/vt/vttablet/tabletserver/tabletenv/local_context.go
And when using this the target tablet is `nil` (or at least it can be) — otherwise an error is returned. For example: https://github.com/vitessio/vitess/blob/08b2c8bcb3f2cb91831ce0927ce9fdf95da7df16/go/vt/vttablet/tabletserver/state_manager.go#L419-L440
You can see all checks for it here: https://github.com/search?q=repo%3Avitessio%2Fvitess%20IsLocalContext&type=code
And you can see the uses of it here (all the locations impacted by the bug): https://github.com/search?q=repo%3Avitessio%2Fvitess%20tabletenv.LocalContext&type=code
This means that in the TabletServer code we can never assume that …

TabletServer: Handle nil targets properly everywhere

---

go/mysql/flavor_mysql.go

Reverts vitessio/vitess#14617
because it causes #14738

Revert "[release-18.0] Replace use of `WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS` with `WAIT_FOR_EXECUTED_GTID_SET` (#14612)"

---

go/mysql/flavor_mysql.go

Reverts vitessio/vitess#14619
because it causes #14738

Revert "[release-17.0] Replace use of `WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS` with `WAIT_FOR_EXECUTED_GTID_SET` (#14612)"

---

go/mysql/flavor.go
go/mysql/flavor_filepos.go
go/mysql/flavor_mariadb.go
go/mysql/flavor_mysql.go
go/vt/mysqlctl/replication.go

The different database flavors use different SQL functions in order to perform the generic "wait for the replica to reach this position" functionality — and each function has different semantics for what it returns and what those return values mean.
We have previously only asked the flavor interface to provide the *command*/*query* (which leveraged the flavor's specific SQL function) to use and then executed the provided query and processed the results at a higher level such as the `mysqlctl` package — where the specifics of the flavor implementation's SQL function were not known. Prior to moving to the newer `WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS()` SQL function for GTID based MySQL replication in https://github.com/vitessio/vitess/issues/14611, the differences were not significant enough …

Replication: Have the DB flavor process waiting for a pos

---

go/mysql/flavor_mysql.go

Reverts vitessio/vitess#14620
because it causes #14738

Revert "[release-16.0] Replace use of `WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS` with `WAIT_FOR_EXECUTED_GTID_SET` (#14612)"

---

go/test/endtoend/vtgate/misc_test.go
go/test/endtoend/vtgate/schema.sql
go/test/endtoend/vtgate/vschema.json
go/vt/vtgate/engine/cached_size.go
go/vt/vtgate/engine/insert.go
go/vt/vtgate/engine/insert_common.go
go/vt/vtgate/engine/insert_select.go
go/vt/vtgate/engine/insert_test.go
go/vt/vtgate/planbuilder/operator_transformers.go
go/vt/vtgate/planbuilder/testdata/dml_cases.json

"In V18, the addition of trimming bound variables during insert needs to be included for each shard in this pull request: https://github.com/vitessio/vitess/pull/14064.  However, the scenario of 'insert on duplicate key' has been overlooked, and the bound variables added are not included for 'on duplicate key' variables."
- Fixes https://github.com/vitessio/vitess/issues/14729

fix: insert on duplicate key update missing BindVars

---

.github/workflows/upgrade_downgrade_test_backups_manual.yml
.github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
examples/backups/stop_tablets.sh

This PR fixes a small issue during the manual upgrade/downgrade backup tests. The issue happens when for some reason the deletion of the VTTablet directory fails due to used files, leading to an error code `39` from `rm -Rf`. This issue can be seen as follows in the logs of the `Stop tablets` step:
```
Shutting down tablet zone1-301
Stopping vttablet...
Shutting down mysql zone1-301
Shutting down MySQL for tablet zone1-0000000301...
Removing tablet directory zone1-301
Successfully deleted 1 tablets
rm: cannot remove '/tmp//vt_0000000301': Directory not empty
```
This silent error leads to the failure of step `Start new tablet and restore`. Since the VTTablet's directory was partially removed, VTTablet thinks it has to start from an existing data dir (which is not what we want). And …

Add a retry to remove the vttablet directory during upgrade/downgrade backup tests

---

go/vt/schemadiff/schema.go
go/vt/schemadiff/schema_test.go

Adding a couple FK rules for column type matching (child table column matching a parent table column), compatible with MySQL. Specific to textual columns:
- A `VARCHAR` parent can work with a `CHAR` child.
- A `CHAR` parent cannot work with a `VARCHAR` child.
- Collation must be identical.
#11975 

schemadiff: additional FK column type matching rules

---

go/stats/counters.go
go/vt/discovery/healthcheck.go
go/vt/discovery/tablet_picker.go
go/vt/discovery/topology_watcher.go
go/vt/discovery/topology_watcher_test.go
go/vt/topo/consultopo/error.go
go/vt/topo/errors.go
go/vt/topo/etcd2topo/error.go
go/vt/topo/memorytopo/file.go
go/vt/topo/memorytopo/memorytopo.go
go/vt/topo/shard.go
go/vt/topo/tablet.go
go/vt/topo/tablet_test.go
go/vt/topo/zk2topo/error.go
go/vt/topotools/tablet.go
go/vt/topotools/utils.go
go/vt/vtctl/grpcvtctldserver/server.go
go/vt/vtctl/grpcvtctldserver/topo.go
go/vt/vtctl/workflow/server.go
go/vt/vttablet/tabletserver/txthrottler/tx_throttler.go
go/vt/wrangler/shard.go
go/vt/wrangler/split.go

VTGate's healthcheck module currently calls GetTablet for each tablet alias that it discovers in a cell. Instead we can use GetTabletsForCell to fetch all tablets for a cell at once.
This PR does a few more things:
- GetTabletsForCell now handles the case where the response size violates gRPC limits by falling back to one tablet at a time in case of error.
- Previously, the one tablet at a time method had unlimited concurrency. In this PR we introduce a configuration option for concurrency.
- We pass `topoReadConcurrency` from healthcheck into GetTabletsForCell.
- The behavior of `--refresh_known_tablets` flag is different now. Previously we would not read those tablets at all, now we do read them, but ignore any changes if they are already known.
The basic fix has already been tried in …

Use GetTabletsByCell in healthcheck

---

go/vt/vtgate/planbuilder/operators/aggregation_pushing.go
go/vt/vtgate/planbuilder/operators/aggregation_pushing_helper.go
go/vt/vtgate/planbuilder/operators/apply_join.go
go/vt/vtgate/planbuilder/operators/ast_to_op.go
go/vt/vtgate/planbuilder/operators/distinct.go
go/vt/vtgate/planbuilder/operators/helpers.go
go/vt/vtgate/planbuilder/operators/horizon.go
go/vt/vtgate/planbuilder/operators/horizon_expanding.go
go/vt/vtgate/planbuilder/operators/insert.go
go/vt/vtgate/planbuilder/operators/offset_planning.go
go/vt/vtgate/planbuilder/operators/plan_query.go
go/vt/vtgate/planbuilder/operators/projection.go
go/vt/vtgate/planbuilder/operators/query_planning.go
go/vt/vtgate/planbuilder/operators/queryprojection.go
go/vt/vtgate/planbuilder/operators/queryprojection_test.go
go/vt/vtgate/planbuilder/operators/route_planning.go
go/vt/vtgate/planbuilder/operators/subquery.go
go/vt/vtgate/planbuilder/operators/subquery_planning.go
go/vt/vtgate/planbuilder/operators/union.go
go/vt/vtgate/planbuilder/operators/vindex.go

Use panics instead of errors in most places in the operators package. Also found a couple of unused methods that were cleaned out.

refactor: remove more errors from operator planning

---

go/vt/sqlparser/normalizer.go
go/vt/sqlparser/normalizer_test.go

This is a very small fix that improves our normalizer. It fixes the issue described in https://github.com/vitessio/vitess/issues/14769
- Fixes https://github.com/vitessio/vitess/issues/14769

Fix order by and group by normalization

---

go/vt/vttablet/grpctmserver/server.go
go/vt/vttablet/tmrpctest/test_tm_rpc.go

Went over all the tablet manager RPCs, and specifically for some of the RPCs that are used in reparenting, it is useful to print their responses in the vttablet logs, to debug failures when they occur. Enabling verbose logging, prints a log when the said function finishes execution which can be very helpful information while debugging.
I have been careful in only enabling verbose logging for RPCs, that aren't called on a regular interval, so as to not pollute the logs.

Enable verbose logging for some more RPCs

---

go/cmd/vtctldclient/command/vreplication/vdiff/vdiff.go
go/test/endtoend/vreplication/vdiff2_test.go
go/vt/vtctl/grpcvtctldclient/client_gen.go
go/vt/vtctl/localvtctldclient/client_gen.go
go/vt/vtctl/workflow/server.go

This fixes the bug described in https://github.com/vitessio/vitess/issues/14777. I also adjusted the other max related flag values as I noticed a difference from the `vtctlclient` implementation in that we were limiting the accepted values to 4,294,967,295 in `vtctldclient` vs 9,223,372,036,854,775,807 in `vtctlclient`.
- Fixes: https://github.com/vitessio/vitess/issues/14777
- Backporting to v18 as this is safe, the bug can cause errant/unexpected results, and the vtctldclient implementation is brand new in v18 
-  The vtctldclient …

VDiff: Fix vtctldclient limit bug

---

.github/pull_request_template.md
.github/workflows/check_label.yml

A new label `NeedsBackportReason` has been added that can be used when a PR is marked for back ports to require a reason/justification.
This label is only checked if at least one `Backport to:` label is set.
For now, this label is expected to be applied manually by reviewers. If necessary we can think about applying it automatically whenever a PR is created.
The PR template has also been enhanced to add an additional check box.
Testing:
Tested that this works as intended by adding and removing labels on this PR after it was created.
#14738  …

Enhance PR template + CI workflow for backport labels.

---

go/vt/vtgate/planbuilder/testdata/from_cases.json
go/vt/vtgate/planbuilder/testdata/unsupported_cases.json
go/vt/vtgate/semantics/derived_table.go

When schema tracking is not enabled, column information can be missing for unexpanded derived tables, which leads to the planner not being able to figure out types and dependencies.
Before this change, the semantic analyser would panic on these queries. This change makes it return an error instead.
Fixes #14788

bugfix: don't panic when missing schema information

---

go/flags/endtoend/mysqlctl.txt
go/flags/endtoend/mysqlctld.txt
go/flags/endtoend/topo2topo.txt
go/flags/endtoend/vtaclcheck.txt
go/flags/endtoend/vtbackup.txt
go/flags/endtoend/vtbench.txt
go/flags/endtoend/vtclient.txt
go/flags/endtoend/vtcombo.txt
go/flags/endtoend/vtctlclient.txt
go/flags/endtoend/vtctld.txt
go/flags/endtoend/vtexplain.txt
go/flags/endtoend/vtgate.txt
go/flags/endtoend/vtgateclienttest.txt
go/flags/endtoend/vtorc.txt
go/flags/endtoend/vttablet.txt
go/flags/endtoend/vttestserver.txt
go/flags/endtoend/zkctl.txt
go/vt/servenv/http.go
go/vt/servenv/pprof.go

this PR adds a flag to allow users to deploy vitess components without including the `/debug/pprof` endpoints. we will begin by defaulting to opted-in to avoid changing behavior when upgrading to v19, but in v20 we will switch to disabled by default.
Demos!
```
➜  local git:(andrew/optional-pprof-endpoints) ✗ grep "false" vtdataroot/tmp/vttablet.WARNING 
W1216 12:57:36.270569   46724 http.go:56] Beginning in vitess version 20, pprof-http will default to `false`; to continue enabling pprof endpoints, please manually set this flag before upgrading.
```
```
local git:(andrew/optional-pprof-endpoints) ✗ curl http://localhost:15000/debug/pprof/
404 page not found
```
-   [x] If this change is …

[servenv] optional pprof endpoints

---

go/cmd/vtctldclient/command/vreplication/mount/mount.go
go/mysql/json/marshal.go
go/test/endtoend/cluster/cluster_process.go
go/vt/binlog/binlogplayer/dbclient.go
go/vt/mysqlctl/mycnf.go
go/vt/mysqlctl/replication.go
go/vt/schemadiff/schema.go
go/vt/sqlparser/parse_test.go
go/vt/zkctl/zkconf.go

Fixes numerous issues. There are a handful left but they're nontrivial:
```
09:39 $ nilness ./...
/home/matt/src/github.com/planetscale/vitess/go/mysql/json/marshal.go:177:9: impossible condition: nil != nil
/home/matt/src/github.com/planetscale/vitess/go/vt/mysqlctl/mycnf.go:181:9: impossible condition: nil != nil
/home/matt/src/github.com/planetscale/vitess/go/vt/mysqlctl/replication.go:240:9: tautological condition: nil == nil
/home/matt/src/github.com/planetscale/vitess/go/vt/schemadiff/schema.go:1077:9: impossible condition: nil != nil
/home/matt/src/github.com/planetscale/vitess/go/vt/binlog/binlogplayer/dbclient.go:186:9: impossible condition: nil != nil
/home/matt/src/github.com/planetscale/vitess/go/vt/vtgate/engine/routing.go:276:16: tautological condition: nil == nil …
```

go: resolve various nilness issues

---

go/vt/tlstest/tlstest_test.go

Resolves:
```
✔ ~/src/github.com/planetscale/vitess/go/vt/tlstest [main|✔] 
15:57 $ nilness .
/home/matt/src/github.com/planetscale/vitess/go/vt/tlstest/tlstest_test.go:124:15: impossible condition: nil != nil
/home/matt/src/github.com/planetscale/vitess/go/vt/tlstest/tlstest_test.go:171:15: impossible condition: nil != nil
```
This test was written in a racy way as well, and that has now been resolved due to explicit use of an errgroup for synchronization.
Updates #14684.
-   [ ] Did the new or modified tests pass consistently …

go/vt/tlstest: fix nilness issues

---

go/vt/wrangler/traffic_switcher.go

During a refactor there was a regression where some errors were just being logged and not returned. This PR correctly returns them to the caller.
Original commit where this was introduced: https://github.com/vitessio/vitess/pull/13656/commits/89295b59d80a6f5ef57b06c5ff19cbf06651699d#diff-a071a972abd45af831ed93cc6447a87b83cee112f1c7d3bb0bdd592979d80c91
https://github.com/vitessio/vitess/pull/13656
Fixes: https://github.com/vitessio/vitess/issues/14801
-   [ …

VReplication SwitchWrites: Properly return errors in SwitchWrites

---

go/vt/wrangler/traffic_switcher.go

Backport of #14800 
During a refactor there was a regression where some errors were just being logged and not returned. This PR correctly returns them to the caller.
Original commit where this was introduced: https://github.com/vitessio/vitess/pull/13656/commits/89295b59d80a6f5ef57b06c5ff19cbf06651699d#diff-a071a972abd45af831ed93cc6447a87b83cee112f1c7d3bb0bdd592979d80c91
https://github.com/vitessio/vitess/pull/13656
https://github.com/vitessio/vitess/issues/14801
-   [ ] Did the new or modified tests pass consistently locally and …

[release-18.0] Backport: VReplication SwitchWrites: Properly return errors in SwitchWrites #14800

---

go/vt/vtctl/workflow/traffic_switcher.go
go/vt/wrangler/traffic_switcher.go
go/vt/wrangler/traffic_switcher_env_test.go
go/vt/wrangler/traffic_switcher_test.go

This is a subset of the changes in https://github.com/vitessio/vitess/pull/14797 — meant to limit changes, making it safer to backport all the way to v16.
- Minimal fix for: https://github.com/vitessio/vitess/issues/14795
- Subset of: https://github.com/vitessio/vitess/pull/14797
-   [x] Tests were updated

VReplication: Update singular workflow in traffic switcher

---

go/test/endtoend/cluster/cluster_util.go
go/test/endtoend/cluster/mysqlctl_process.go
go/test/endtoend/cluster/mysqlctld_process.go
go/test/endtoend/mysqlctld/mysqlctld_test.go

While working on fixing the flaky tests in release-16.0, I stumbled upon a PR that had already fixed the flakiness but wasn't backported properly into release-16.0. This PR is a backport of https://github.com/vitessio/vitess/pull/12834

[release-16.0] Backup flaky test

---

go/vt/vtgate/planbuilder/operators/delete.go
go/vt/vtgate/planbuilder/operators/update.go
go/vt/vtgate/planbuilder/testdata/foreignkey_cases.json
go/vt/vtgate/planbuilder/testdata/foreignkey_checks_off_cases.json
go/vt/vtgate/planbuilder/testdata/foreignkey_checks_on_cases.json

This PR limits the usage of `NOWAIT` to tables having unique key columns.
`NOWAIT` leads to an error when acquiring the required index lock and it cannot be granted immediately. This leads to the failure of DML execution for foreign key cases. 
This is only required when the table has `unique keys`. When a table has `unique keys` MySQL does not take gap locks resulting in the issue described in https://github.com/vitessio/vitess/pull/14532
- #12967 

reduce NOWAIT usage to tables with unique keys for foreign key plans

---

go/vt/vtgate/planbuilder/operators/delete.go

Two PR merges created a build issue due to conflicting changes.
This resolve the build issue.

fix: build on delete operator

---

go/vt/vtgate/engine/set.go
go/vt/vttablet/tabletserver/gc/tablegc.go
go/vt/vttablet/tabletserver/throttle/throttler.go

Removes logs for "Ignored inapplicable SET" system variables and some throttler logs which generate excessive logs for clusters with large number of shards.

Remove some logs that are logging excessively on large clusters

---

changelog/16.0/16.0.7/changelog.md
changelog/16.0/16.0.7/release_notes.md
changelog/16.0/README.md
changelog/17.0/17.0.5/changelog.md
changelog/17.0/17.0.5/release_notes.md
changelog/17.0/README.md
changelog/18.0/18.0.2/changelog.md
changelog/18.0/18.0.2/release_notes.md
changelog/18.0/README.md

This PR moves the release notes of the v18.0.2, v17.0.5 and v16.0.7 patches to main

port release notes of v18.0.2, v17.0.5 and v16.0.7 to main

---

go/cmd/vttestserver/cli/main_test.go
go/test/endtoend/cluster/cluster_util.go

This PR adds logs to tests that have been failing in CI, but we aren't able to reproduce locally. The logging that has been added will help us debug the tests further to see what's going wrong.

Add logging for failing tests in CI

---

go/test/endtoend/onlineddl/revert/onlineddl_revert_test.go
go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
go/test/endtoend/vtgate/foreignkey/stress/fk_stress_test.go
go/vt/vttablet/onlineddl/executor.go
go/vt/vttablet/onlineddl/schema.go

https://github.com/vitessio/vitess/pull/13799 introduced VTGate stress tests for foreign keys, and https://github.com/vitessio/vitess/pull/14098 further improved them. Among the techniques used, we set up a primary with foreign key tables, and a replica where we stripped out the foreign key constraints. This setup validated that VTGate's cascading of foreign key rules works correctly, by comparing data on primary and replica.
This PR adds an additional replica, this time a standard, "faithful" one. The objective with this replica is to validate that the schema on primary and replica are consistent after Online DDL. This is something we can't do with the already existing replica as we intentionally diverged the schema on that replica in the first place.
The test compares the new, …

VTGate/foreign keys stress test: add tests for 'standard' replica

---

go/mysql/binlog/rbr_test.go
go/mysql/collations/colldata/mysqlucadata.go
go/mysql/datetime/interval.go
go/mysql/decimal/scan.go
go/mysql/decimal/scan_32.go
go/mysql/decimal/scan_64.go
go/mysql/icuregex/compiler.go
go/sqltypes/testing.go

To allow using the sqlparser and go/mysql package as a library, we also want to allow it to build on 32 bits with the simplest change possible. The changes here are small and not problematic to carry.
Part of #14717 

Allow for building 32 bit libraries for subparts

---

go/test/endtoend/vtgate/queries/subquery/subquery_test.go
go/vt/vtgate/planbuilder/operators/aggregation_pushing.go
go/vt/vtgate/planbuilder/operators/aggregator.go
go/vt/vtgate/planbuilder/operators/horizon_expanding.go
go/vt/vtgate/planbuilder/operators/queryprojection.go
go/vt/vtgate/planbuilder/operators/subquery_planning.go
go/vt/vtgate/planbuilder/testdata/aggr_cases.json
go/vt/vtgate/planbuilder/testdata/unsupported_cases.json

When the subquery operator was introduced it missed the case for handling the subquery inside an aggregation function.
This PR adds support for it.
As per the issue `group_concat` does not accept more than one argument when evaluated at vtgate. That is still unsupported and is not the cause of regression. The queries reported in the issue would work now.
- Fixes https://github.com/vitessio/vitess/issues/14843
-   [X] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [X] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [X] Did the new or modified tests pass consistently locally and on CI?
-   [X] Documentation was added or is not …

Subquery inside aggregration function

---

go/vt/topo/tablet.go

We're seeing this error message a lot in logs and there is an `err` variable in scope, but it's not actually shown. Display it. Quote the cell name and tablet aliases for clarity as well.
n/a, trivial cleanup.

go/vt/topo: add error value to GetTablet logs

---

go/vt/schemadiff/schema.go
go/vt/schemadiff/schema_test.go

Followup and adjustment to https://github.com/vitessio/vitess/pull/14751. Per https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html:
> The length of string types need not be the same. For nonbinary (character) string columns, the character set and collation must be the same.
This allows parent(char)->child(varchar) types.
- https://github.com/vitessio/vitess/issues/11975
- 

schemadiff: allow char->varchar FK reference type matching

---

go/vt/vttablet/tabletserver/throttle/config/config.go
go/vt/vttablet/tabletserver/throttle/throttler.go
go/vt/vttablet/tabletserver/throttle/throttler_test.go

Following recurring race condition failures, e.g. https://github.com/vitessio/vitess/actions/runs/7299836104/job/19894003119?pr=14851, this PR removes the global throttler configuration Instance, and makes it a member of the throttler struct. Each throttler has its own dedicated config settings now.
This eliminates race conditions in the unit tests, and generally plays nicer with unit testing.
Closes https://github.com/vitessio/vitess/issues/14852
Fixes: https://github.com/vitessio/vitess/issues/14776 …

Throttler: refactor global configuration setting as throttler member

---

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
go/test/endtoend/vtgate/queries/subquery/subquery_test.go
go/vt/vtgate/planbuilder/operators/aggregation_pushing.go
go/vt/vtgate/planbuilder/operators/aggregator.go
go/vt/vtgate/planbuilder/operators/horizon_expanding.go
go/vt/vtgate/planbuilder/testdata/aggr_cases.json
go/vt/vtgate/planbuilder/testdata/unsupported_cases.json

This PR allows aggregation functions with multiple expressions when the aggregation function can be pushed to underlying MySQL for execution.

Added support for group_concat and count distinct with multiple expressions

---

go/mysql/datetime/datetime.go
go/vt/vtgate/evalengine/compiler_test.go

Some of the last days in the year can fall in the first week of the next year. If that happens, there are various modes when we should return 53 as the week number and not week 1 for the next year.
This can always be 53. There are weeks which already contain 53 weeks, but it can never be 54 in those cases as in years with 53 weeks, there's never a last day of the year that falls in the first week of next year. It then always falls in week 53 already.
Fixes #14858 
Backporting as this is a straight bug in the calculation and it's trivially easy to fix. There's no risk to this fix either.  It also can trigger CI instability if we don't fix it which is a useful reason as well. 
-   [x] If …

evalengine: Fix week overflow

---

go/vt/vttablet/tabletserver/vstreamer/snapshot_conn.go

as is, this makes our vttablet logs unreadable when using message tables

vstreamer: rm excessive logging

---

go/test/endtoend/vreplication/vdiff2_test.go

We merged these two PRs concurrently and thus ended up with a test breakage:
- https://github.com/vitessio/vitess/pull/14735
- https://github.com/vitessio/vitess/pull/14786
```
❯ golangci-lint run go/... --timeout 10m
go/test/endtoend/vreplication/vreplication_test_env.go:1: : # vitess.io/vitess/go/test/endtoend/vreplication [vitess.io/vitess/go/test/endtoend/vreplication.test]
go/test/endtoend/vreplication/vdiff2_test.go:239:14: undefined: vtgateConn (typecheck)
/*
```
This PR addresses that issue by using a locally scoped vtgate connection according to the newly established model.
- Internal follow-up to:
- https://github.com/vitessio/vitess/pull/14735
- https://github.com/vitessio/vitess/pull/14786
-   [x] "Backport to:" labels have been added if this change should be back-ported to …

Tests: Fix vdiff test breakage from concurrent merge

---

go/mysql/fakesqldb/server.go
go/vt/vttablet/tabletserver/repltracker/writer.go
go/vt/vttablet/tabletserver/repltracker/writer_test.go

This PR fixes the issue pointed out in #14637. On investigating the issue, it was found that if the heartbeat writer is stuck while writing due to the requirement of semi-sync ACKs, it will also block `Close()` call to itself. This causes a problem since we aren't able to end the primary term, causing the cluster to see 2 primary tablets. VTOrc is unable to repair this failure either, because the problem is in the hearbeat writer of vttablet, and no external RPC can unblock it.
The proposed fix in this PR, is to do what we do for the user queries i.e., when we try to close the heartbeat writer, we try and kill the ongoing write. This ensures that we aren't indefinitely stuck. The code has been written with correctness in mind, and it is still blocking the `Close()` call from finishing, …

Fix hearbeatWriter Close being stuck if waiting for a semi-sync ACK

---

go/test/endtoend/vreplication/vdiff2_test.go

The previously hard coded number of rows to create for each second in the max-diff-duration flag value was too high for some test hosts/runners. This small change takes the host vCPU count into account so that it creates between 100,000 and 1,000,000 rows for each second depending on the vCPUs available to the test.
- Follow-up to: https://github.com/vitessio/vitess/pull/14786

Test: Take test host/runner specs into account for VDiff diff duration test

---

go/test/endtoend/onlineddl/vtgate_util.go
go/vt/vttablet/endtoend/misc_test.go
go/vt/vttablet/onlineddl/executor.go
go/vt/vttablet/onlineddl/vrepl.go
go/vt/vttablet/tabletserver/gc/tablegc.go
go/vt/vttablet/tabletserver/vstreamer/snapshot_conn.go

We use both `-1` and `MaxInt` style constants for unknown / unlimited result sets.
Let's standardize on `-1` which is by far most commonly use at the moment. Also avoids some imports as a nice little bonus.
Realized this after doing some consistency fixes in #14854. 

Use one canonical style for unlimited queries

---

go/mysql/capabilities/capability.go
go/mysql/flavor.go
go/mysql/flavor_filepos.go
go/mysql/flavor_mariadb.go
go/mysql/flavor_mysql.go
go/mysql/flavor_mysqlgr.go
go/mysql/flavor_test.go
go/test/endtoend/onlineddl/revert/onlineddl_revert_test.go
go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
go/test/endtoend/tabletmanager/tablegc/tablegc_test.go
go/vt/mysqlctl/backup_blackbox_test.go
go/vt/schemadiff/capability.go
go/vt/schemadiff/capability_test.go
go/vt/schemadiff/schema_diff.go
go/vt/schemadiff/schema_diff_test.go
go/vt/vttablet/onlineddl/analysis.go
go/vt/vttablet/onlineddl/executor.go
go/vt/vttablet/tabletserver/gc/tablegc.go
go/vt/wrangler/testlib/backup_test.go

See feature description in https://github.com/vitessio/vitess/issues/14877. `schemadiff`, together with `CapableOf` & `FlavorCapability`, is able to answer:
- Whether a particular `ALTER TABLE` on a given table schema is eligible for `ALGORITHM=INSTANT`
- Whether an entire `SchemaDiff` (the diff of two schemas) result is applicable immediately/instantly, meaning all diffs are either trivially immediate (`CREATE TABLE`, `ALTER VIEW`, etc.) or are eligible for `ALGORITHM=INSTANT`.
This is a first, and isolated, step in a longer change, where:
- Based on `AlterTableAlgorithmStrategy` hint, we could auto-apply `ALGORITHM=INSTANT` to alter table statements.
- `onlineddl/analysis.go`, which has overlapping functionality, can then defer to `schemadiff`.
To reduce `schemadiff`'s package …

schemadiff: using MySQL capabilities to analyze a SchemaDiff and whether changes are applicable instantly/immediately.

---

go/vt/vtctl/vtctl.go

A second table was added to the vtctl `TestMoveTables` unit test which surfaced a flakiness in the test caused by the intrinsic lack of ordering of map keys. Fixed by sorting the keys so that we get a stable output.

Flakes: Fix flaky vtctl unit test TestMoveTables

---

go/mysql/sqlerror/sql_error.go
go/mysql/sqlerror/sql_error_test.go

The previous regexp had superfluous wildcard matching at the beginning and end. This results in eagerly matching the whole string and subsequently matches the last occurance of the match.
Instead we don't want to use the wildcard so the default left to right matching is used and we get the first occurence.
Fixes #14866

Improve err extraction logic

---

.github/workflows/update_golang_dependencies.yml
.github/workflows/update_golang_version.yml

This PR adds a new workflow that runs either on manual trigger or on a weekly CRON. The workflow will attempt to upgrade all the Golang dependencies to a newer version using `go get -u ./...` followed by `go mod tidy`. It will run `main`. This avoid having to manually upgrade the dependencies or even to forget about upgrading them.
@dbussink recently did a PR that manually does this (https://github.com/vitessio/vitess/pull/14888), this new workflow will ensure this work is done consistently. 
[I ran some tests](https://github.com/frouioui/vitess/actions/runs/7415911638/job/20179944616?pr=220) on my fork here where automation created the PR:
- https://github.com/frouioui/vitess/pull/221
- Fixes https://github.com/vitessio/vitess/issues/14890
-   [x] "Backport to:" labels have been added if …

Automatically update the Golang dependencies using a CRON

---

.github/workflows/update_golang_dependencies.yml
.github/workflows/update_golang_version.yml

Little fix to the new golang deps upgrade workflow and remove the `release-15.0` branch from the golang version upgrade matrix.

Typo fix and remove unsupported branch for go version upgrade matrix

---

go/cache/lru_cache.go
go/cache/lru_cache_test.go
go/pools/numbered.go
go/sync2/consolidator.go

The two remaining uses of the old cache API use a fixed cost of 1 and can still benefit from adding a type-safe generic interface.
Remove a couple of entirely unused methods. There are several methods at this point regarding hit/miss/eviction that are otherwise unused outside of tests but I've left them at this point for the sake of coverage.
n/a, cleanup.
n/a

go/cache: use generics and remove unused API

---

go/vt/vtgate/vindexes/consistent_lookup.go
go/vt/vtgate/vindexes/consistent_lookup_test.go

Context handling was refactored in  https://github.com/vitessio/vitess/commit/c43a162ea567f47a89b8d4a506d2995740737b79 which included [this TODO](https://github.com/vitessio/vitess/commit/c43a162ea567f47a89b8d4a506d2995740737b79#diff-0e06131de7d1c872b547136ccc5fa2318a7b6b99f5c3ba78c8d0ab2f6757980eR302-R303)
```go
// TODO: context needs to be passed on.
qr, err = vcursor.ExecuteKeyspaceID(context.Background(), lu.keyspace, existingksid, lu.lockOwnerQuery, bindVars, false /* rollbackOnError */, false /* autocommit */)
```
This causes consistent lookup duplicate row handling to fail when tablets are using strict table ACL enforcement because there is no caller id in the context.
It looks like the TODO and `context.Background()` was left behind inadvertently, so this PR simply passes the …

Vindexes: Pass context in consistent lookup handleDup

---

go/vt/vtgate/vindexes/consistent_lookup.go
go/vt/vtgate/vindexes/consistent_lookup_test.go

This is a cherry-pick of https://github.com/vitessio/vitess/pull/14653

[release-18]: Vindexes: Pass context in consistent lookup handleDup (#14653)

---

go/vt/vtgate/vindexes/consistent_lookup.go
go/vt/vtgate/vindexes/consistent_lookup_test.go

This is a cherry-pick of https://github.com/vitessio/vitess/pull/14653

[release-17]: Vindexes: Pass context in consistent lookup handleDup (#14653)

---

.github/workflows/update_golang_dependencies.yml

Small fix, in #14891 we set the cron schedule to automatically upgrade the golang deps to every day instead of every week.

Run Go deps upgrade every week

---

go/vt/vttablet/tabletserver/state_manager.go
go/vt/vttablet/tabletserver/state_manager_test.go

This PR fixes the issue pointed out in https://github.com/vitessio/vitess/issues/14933. 
Reading the docs of `sync.WaitGroup` we see - 
```
// Note that calls with a positive delta that occur when the counter is zero
// must happen before a Wait. Calls with a negative delta, or calls with a
// positive delta that start when the counter is greater than zero, may happen
// at any time.
// Typically this means the calls to Add should execute before the statement
// creating the goroutine or other event to be waited for.
// If a WaitGroup is reused to wait for several independent sets of events,
// new Add calls must happen after all previous Wait calls have returned.
```
So, apparently, this panic happens, when we have started waiting for a `waitGroup` and then a bunch of `Done()` calls …

Vttablet panic in requests Wait

---

.github/workflows/codecov.yml
.github/workflows/static_checks_etc.yml

This is a follow-up to: https://github.com/vitessio/vitess/pull/14333
You can see that the run on the merge to `main` failed: https://github.com/vitessio/vitess/actions/runs/7466472041/job/20317903610
The FOSSA part of the workflow only runs on main so there's no other way to test it than to merge: https://github.com/vitessio/vitess/blob/9df71e0698febc8fae7de03f11eb449fc2e5ee84/.github/workflows/static_checks_etc.yml#L36-L45
We have an open discussion with CNCF to get a push-only API token so that we can enable the scan for pull-requests as well using that: https://github.com/fossa-contrib/fossa-action#push-only-api-token
- Follow-up to: https://github.com/vitessio/vitess/pull/14333
- …

CI: Adjust FOSSA API secret name

---

go/vt/vtgate/engine/route_test.go
go/vt/vtgate/evalengine/cached_size.go
go/vt/vtgate/evalengine/expr_bvar.go
go/vt/vtgate/evalengine/expr_tuple_bvar.go
go/vt/vtgate/evalengine/expr_tuple_bvar_test.go
go/vt/vtgate/evalengine/format.go
go/vt/vtgate/evalengine/translate_simplify.go
go/vt/vtgate/executor_dml_test.go
go/vt/vtgate/executor_select_test.go
go/vt/vtgate/executor_test.go
go/vt/vtgate/planbuilder/operators/route.go
go/vt/vtgate/planbuilder/operators/sharded_routing.go
go/vt/vtgate/planbuilder/testdata/dml_cases.json
go/vt/vtgate/planbuilder/testdata/filter_cases.json
go/vt/vtgate/planbuilder/testdata/foreignkey_cases.json
go/vt/vtgate/planbuilder/testdata/foreignkey_checks_off_cases.json
go/vt/vtgate/planbuilder/testdata/foreignkey_checks_on_cases.json
go/vt/vtgate/testdata/executorVSchema.json

This PR improved the plan when filter condition has `List Argument`.
E.g. `select 1 from user where (id, col) in ::vals`
Earlier this query was send down as `Scatter` to all shards.
With this PR, the query will send down to the shards based on where the sharding key (here `id`) routes this query.
These `List Arguments` is currently used in DML routing for multi-table query and foreign key cascades.
Old Plan:
```json
{
"Original": "select 1 from user where (id, col) in ::vals",
"Variant": "Scatter",
"Keyspace": {
},
"FieldQuery": "select 1 from `user` where 1 != 1",
"Query": "select 1 from `user` where (id, col) in ::vals",
"Table": "`user`"
},
"TablesUsed": [
"user.user"
]
}
```
New Plan: …

Improve sharded query routing for tuple list

---

go/protoutil/duration_test.go

Adds tests for `DurationToProto` and a `nanoseconds` testcase for `DurationFromProto`
#14931

tests: add tests for `go/protoutil/duration`

---

go/json2/marshal_test.go
go/json2/unmarshal_test.go

Add `TestMarshalIndentPB` to cover `marshal.go`
Add `TestUnmarshalProto`, `TestAnnotate` to cover `unmarshal.go`
#14931

tests: add tests for `go/json2`

---

go/flags/endtoend/vtbackup.txt
go/flags/endtoend/vtcombo.txt
go/flags/endtoend/vtctld.txt
go/flags/endtoend/vtorc.txt
go/flags/endtoend/vttablet.txt
go/flags/endtoend/vttestserver.txt
go/vt/vttablet/grpctmclient/client.go

When the [tablet throttler](https://vitess.io/docs/reference/features/tablet-throttler/) is [enabled in a keyspace](https://vitess.io/docs/reference/features/tablet-throttler/#configuration), the tablets within each shard make [very frequent](https://vitess.io/docs/18.0/reference/features/tablet-throttler/#cluster-health) `CheckThrottler` RPC calls between themselves after moving from http to gRPC in https://github.com/vitessio/vitess/pull/13514.
The initial implementation created a new gRPC connection and dialed the other tablet on each `CheckThrottler` RPC call. Because this RPC is made so frequently, however, this was not practical from a performance perspective (CPU and network overhead along with feature/input latency).
In this PR we instead leverage the existing tabletmanagerclient …

Throttler: Use cached client for CheckThrottler tabletmanager RPC

---

go/test/endtoend/backup/vtbackup/backup_only_test.go
go/test/endtoend/clustertest/vtctld_test.go
go/test/endtoend/mysqlserver/main_test.go
go/test/endtoend/reparent/emergencyreparent/ers_test.go
go/test/endtoend/reparent/plannedreparent/reparent_test.go
go/test/endtoend/reparent/utils/utils.go
go/test/endtoend/vtorc/general/vtorc_test.go
go/vt/schemadiff/schema.go
go/vt/sqlparser/ast_test.go
go/vt/sqlparser/parser.go
go/vt/sqlparser/utils.go
go/vt/sqlparser/utils_test.go
go/vt/vttablet/tabletmanager/rpc_query.go
go/vt/vttablet/tabletmanager/rpc_query_test.go

Addresses https://github.com/vitessio/vitess/issues/14952 and to some extent https://github.com/vitessio/vitess/pull/14949.
In this PR:
- `ExecuteFetchAsDBA` generally rejects any multi-statement SQL. For example, the following returns an error:
```sql
vtctldclient ExecuteFetchAsDBA zone1-0000000100 "select 1 from dual; select 2 from dual"
```
- We make an exception when all queries are of the form `CREATE TABLE` or `CREATE VIEW`. This is to accommodate the already existing use case of `ApplySchema --batch-size`.
- While at it, we also fix the `allowZeroInDate` parsing error as per #14952 
Today, it is possible to send multiple queries in `vtctldclient ExecuteFetchAsDBA`. This potentially makes the connection pool dirty, as connections in the pool could have undrained result sets from …

Protect `ExecuteFetchAsDBA` against multi-statements, excluding a sequence of `CREATE TABLE|VIEW`.

---

go/vt/vtgate/querylog.go
go/vt/vtgate/querylogz.go
go/vt/vtgate/querylogz_test.go
go/vt/vttablet/tabletserver/querylogz.go
go/vt/vttablet/tabletserver/querylogz_test.go
go/vt/vttablet/tabletserver/tabletserver.go
go/vt/vttablet/tabletserver/txlogz.go

This was broken in the parser injection refactor and this didn't inject the properly configured object.
Also cleans up some global init() calls as well and moves it to the pattern of how we initialize the rest which we need to pass in the parser correctly anyway.
Should have been done in #14822 as part of work on #14717

Use the correct parser for truncation

---

go/mysql/format/float.go
go/mysql/format/float_test.go

This PR removes `AppendFloat` from `go/mysql/format`.
This PR also adds required unit tests for `go/mysql/format`
Fixes #14972 

Remove `AppendFloat` from `go/mysql/format` and add required tests

---

go/mysql/hex/hex_test.go

This PR adds required tests for `go/mysql/hex`

Add required tests for `go/mysql/hex`

---

go/vt/sqlparser/parser.go
go/vt/sqlparser/version_test.go

Tiny refactor to export `convertMySQLVersionToCommentVersion` so that it can be used in vitess-operator to validate the MySQL version in order to set the `--mysql_server_version` properly to each Vitess component.

Export `convertMySQLVersionToCommentVersion` to use it in vitess-operator

---

go/vt/vtctl/workflow/server.go
go/vt/vtctl/workflow/server_test.go

In v19 we added a new feature to support auto restarting the diff of a table periodically in https://github.com/vitessio/vitess/pull/14786.
The [proto field used for that is a `vttime.Duration` type](https://github.com/vitessio/vitess/blob/9af869232ad252e013a91a6ba2be1f1db079737c/proto/vtctldata.proto#L1745). Because it [ends up being a pointer in the proto message](https://github.com/vitessio/vitess/blob/9af869232ad252e013a91a6ba2be1f1db079737c/go/vt/proto/vtctldata/vtctldata.pb.go#L13330) there is no ZeroValue in the server side (`vtctld`) message when the client (`vtctldclient`) sent an older version of the `VDiffCreateRequest` proto message from a v18 `vtctldclient` binary and thus when we [passed on `req.MaxDiffDuration.Seconds` to the …

VDiff: Make max diff duration upgrade/downgrade safe

---

examples/common/scripts/vttablet-up.sh

I chatted w/ @mattlord about https://github.com/vitessio/vitess/issues/14978, he said:
> We should just remove that flag in the examples. 
>
> I initially added those flags here as I was using the local examples to test it: https://github.com/vitessio/vitess/pull/12737
>
> They shouldn’t be necessary anymore — you can enable the throttler at the keyspace level in the topo using vtctldclient and use defaults for the other things.
>
> We should backport all the way to release-17.0 as well. That’s the oldest version that has those flags in the script.
I tested this by running all the way through the local example, verifying that no lag was reported on `@replica` or `@rdonly`, and did not see any other issues.
Fixes #14978.
-   [x] "Backport to:" labels have been added if this change should …

examples: rm heartbeat flags

---

go.mod
go.sum
go/mysql/collations/colldata/uca_tables_test.go
go/test/endtoend/vtgate/vindex_bindvars/main_test.go
go/vt/vtctl/vdiff2_test.go
go/vt/vtctl/workflow/log_recorder_test.go
go/vt/vttablet/endtoend/acl_test.go
go/vt/wrangler/log_recorder_test.go

We already extensively use testify, so let's make sure we use that everywhere and not add an additional testing dependency.

Remove usage of additional test package

---

.github/workflows/update_golang_dependencies.yml

This PR reduces the frequency of the Golang Dependency Upgrade CRON from every weeks to roughly every two weeks (on the 1st and 15th of every month).

Reduce the frequency of the golang dependency upgrade CRON

---

go/textutil/strings_test.go
go/textutil/template_test.go

tests: Add tests for `go/textutil`

---

changelog/19.0/19.0.0/summary.md

Towards `release-19.0`: Documenting the breaking change in https://github.com/vitessio/vitess/pull/14954
https://github.com/vitessio/vitess/pull/14984

19.0 release notes: ExecuteFetchAsDBA breaking change

---

go/test/endtoend/vtgate/queries/dml/dml_test.go
go/vt/vtgate/engine/cached_size.go
go/vt/vtgate/engine/delete_multi.go
go/vt/vtgate/engine/delete_multi_test.go
go/vt/vtgate/engine/delete_with_input.go
go/vt/vtgate/engine/delete_with_input_test.go
go/vt/vtgate/executor_dml_test.go
go/vt/vtgate/planbuilder/delete_multi.go
go/vt/vtgate/planbuilder/delete_with_input.go
go/vt/vtgate/planbuilder/operator_transformers.go
go/vt/vtgate/planbuilder/operators/SQL_builder.go
go/vt/vtgate/planbuilder/operators/delete.go
go/vt/vtgate/planbuilder/operators/delete_multi.go
go/vt/vtgate/planbuilder/operators/delete_with_input.go
go/vt/vtgate/planbuilder/operators/phases.go
go/vt/vtgate/planbuilder/operators/query_planning.go
go/vt/vtgate/planbuilder/testdata/dml_cases.json
go/vt/vtgate/planbuilder/testdata/unsupported_cases.json
go/vt/vtgate/semantics/analyzer.go
go/vt/vtgate/semantics/semantic_state.go

This PR add support for `Delete` with `Limit` optionally having `Order By` for sharded keyspaces.
- https://github.com/vitessio/vitess/issues/6854

planner: support cross shard DELETE with LIMIT/ORDER BY

---

go/vt/vttablet/tabletserver/txserializer/tx_serializer.go

Change the hot row protection log message to describe whether or not transactions have been queued based on the dry run status.
_`TestTxSerializer_ConcurrentTransactions`_
```
3 simultaneous transactions (3 in total) for the same row range (t1 where1) would have been queued.
```
❌ The transactions are [actually queued](https://github.com/vitessio/vitess/blob/main/go/vt/vttablet/tabletserver/txserializer/tx_serializer_test.go#L223).
_`TestTxSerializerDryRun`_
```
3 simultaneous transactions (3 in total) for the same row range (t1 where1) would have been queued.
```
✅ The transactions are not actually queued.
---
_`TestTxSerializer_ConcurrentTransactions`_
```
3 simultaneous transactions (3 in total) for the same row range (t1 where1) have been queued.
```
✅ The transactions are actually …

txserializer: change log message based on dry run

---

go/vt/vtgate/planbuilder/plan_test_vindex.go
go/vt/vtgate/planbuilder/testdata/select_cases.json
go/vt/vtgate/planbuilder/testdata/vschemas/schema.json
go/vt/vtgate/vindexes/consistent_lookup.go
go/vt/vtgate/vindexes/lookup.go

As a follow-up to https://github.com/vitessio/vitess/pull/13505, this PR enables non-unique lookups to support the `isBackfilling` interface. This will prevent non-unique lookups from vindex selection during a backfill (i.e. when `write_only` is set to `true`).
- https://github.com/vitessio/vitess/issues/13486

Mark non-unique lookup vindex as backfill to ignore vindex selection

---

go/slice/slice_test.go

Adds unit tests for the slice package. The tests cover the cases resulting in 100% code coverage.
Improve Unit Test Coverage #14931

tests: add tests for `go/slice`

---

go/vt/vttls/vttls.go

fix an error in the log printing format.
This line of log was generated when I encountered a TLS error. This made me confused, so I discovered that there were some minor errors in the log printing format.
```shell
Cannot find loaded tls certificate with cert: /tmp/ssl/server-key.pem, key/tmp/ssl/server-cert.pem
```

Fix log format error in vttls.go

---

go/event/syslogger/fake_logger_test.go

This PR adds missing tests for `go/event/syslogger`.

Add missing tests for `go/event/syslogger`

---

go/stats/histogram.go
go/stats/histogram_test.go
go/stats/hooks_test.go
go/stats/ring_test.go
go/stats/snake_case_converter_test.go

Added 100% test coverage for the following files:
- `vitess/go/stats/histogram`	
- `vitess/go/stats/hooks`
- `vitess/go/stats/ring`
- `vitess/go/stats/snake_case_converter`			
Also refactored some of the existing tests to use the `assert` library for cleaner tests, and added a function called `AddHook` on the `Histogram` struct so that the users can register a hook on the histogram which can be called anytime a value is added to the same (this seemed to be the desired functionality according to the existing code, but the registration of the hook seems to be omitted)
-   [ ] If this change is to be back-ported to previous releases, a justification is included in the …

tests: increase coverage for multiple files in `vitess/go/stats` to 100%

---

go/sets/set_test.go

Partial Fix to #14931 
Covers unit test for `go/sets/set.go`
`ok      vitess.io/vitess/go/sets        0.011s  coverage: 73.8% of statements`

unit test for go/sets/set.go

---

go/tools/codegen/common_test.go
go/tools/codegen/goimports_test.go

This commit increases the code coverage of the `tools/codegen` package from 0% to 90%.
Partially Fixes issue https://github.com/vitessio/vitess/issues/14931

Added unit tests for the tools/codegen package

---

go/vt/hook/hook_test.go

Bump coverage from 37.7% to 78.3% 
#14931

tests: add tests for `go/vt/hook`

---

go/vt/external/golib/sqlutils/sqlite_dialect_test.go
go/vt/external/golib/sqlutils/sqlutils_test.go

Bumps coverage from 15.4% to 61.5%
Question: some functions require a `db *sql.DB` as an argument. Not sure how to approach testing these. Do I make a sqlite DB to test them or use [sqlmock](https://github.com/DATA-DOG/go-sqlmock)?
#14931

tests: Add tests for `go/vt/external`

---

go/vt/vtgate/tx_conn.go
go/vt/vtgate/tx_conn_test.go
go/vt/vtgate/vtgate.go

This change was supposed to get merged with  https://github.com/vitessio/vitess/pull/14848 but it looks like I never pushed it up 😮‍💨 
https://github.com/vitessio/vitess/pull/14848
https://github.com/vitessio/vitess/issues/14815

vtgate: increment vtgate_warnings counter for non atomic commits

---

go/vt/vtgate/evalengine/cached_size.go
go/vt/vtgate/evalengine/compiler_asm.go
go/vt/vtgate/evalengine/fn_time.go
go/vt/vtgate/evalengine/testcases/cases.go
go/vt/vtgate/evalengine/translate_builtin.go

This PR adds implementation of [`LAST_DAY`](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_last-day) func in evalengine.
Fixes part of #9647

evalengine: Implement LAST_DAY

---

go/sqlescape/ids.go
go/sqlescape/ids_test.go
go/vt/mysqlctl/schema.go
go/vt/vtctl/workflow/traffic_switcher.go
go/vt/vtexplain/vtexplain_vttablet.go
go/vt/vtgate/vindexes/vschema.go
go/vt/vttablet/tabletserver/vstreamer/rowstreamer.go
go/vt/wrangler/traffic_switcher.go

`UnescapeID(str)` will now also halve any backticks found within a string.
Associated tests will be added via #14987
Fixes #14992

fix: `Unescape(Escape(str))` now returns the original string

---

go/tools/releases/releases_test.go

This commit bumps the code coverage of the `tools/releases` package from 0% to almost 60%.
Partially addresses: https://github.com/vitessio/vitess/issues/14931

Added unit tests for the tools/releases package

---

go/flagutil/enum.go
go/flagutil/enum_test.go
go/flagutil/flagutil_test.go
go/flagutil/optional_test.go
go/flagutil/sets_test.go

Bug: the `caseInsensitive` variables was not being used in
`StringEnum` initialization.
Fix: Added code to initialize the `caseInsensitive` variable when the
`StringEnum` instance is created.
Added unit tests to increase the code coverage of the `flagutil` package.
Partially addresses: https://github.com/vitessio/vitess/issues/14931

Fixed bug in flagutil package and added tests

---

go/vt/vtgate/semantics/bitset/bitset_test.go

tests: add tests to `go/vt/vtgate/semantics/bitset`

---

go/unicode2/unicode.go
go/unicode2/unicode_test.go

This PR adds required tests for `go/unicode2`

Add required tests for `go/unicode2`

---

go/tb/error_test.go

This PR adds required tests for `go/tb`

Add required tests for `go/tb`

---

go/vt/logz/logz_utils_test.go

This commit increases the code coverage of the `go/vt/logz` package to 100%.
Partially Addresses: https://github.com/vitessio/vitess/issues/14931

Added tests for the vt/logz package

---

go/vt/callinfo/callinfo_test.go
go/vt/callinfo/plugin_grpc_test.go
go/vt/callinfo/plugin_mysql_test.go

This commit increases the code coverage of the `go/vt/callinfo` package to >74%
https://github.com/vitessio/vitess/issues/14931

Added tests for the go/vt/callinfo package

---

go/mysql/conn.go
go/mysql/conn_test.go
go/mysql/query.go
go/mysql/streaming_query.go

While working on some enterprise customers, @maxenglander noticed a very significant amount of allocations from `readComQueryResponse`. I don't think this is the cause of the increased p99 latencies that the customer was seeing, but it is indeed wasteful and should be fixed.
The allocations happen in `mysql.(*Conn).parseOKPacket`, and there are two sources:
- `&PacketOK{}` instances are being created every time the function is called, because they're returned as a pointer value. This is the 64 byte allocation group seen in the profile, 2.7GB total.
- The `coder` struct that handles parsing of the packet is being allocated in the heap, because _when the parsing fails_ (i.e. very rarely), the struct is passed as an `%v` argument to `vterrors.Errorf`. Since `Errorf` is a variadric API, its …

mysql: do not allocate in parseOKPacket

---

go/test/endtoend/tabletgateway/buffer/buffer_test_helpers.go
go/vt/vtgate/buffer/buffer_test.go
go/vt/vtgate/buffer/shard_buffer.go

This is based on a PR from @arthurschreiber with some additional changes based on the review feedback from @vmg. https://github.com/vitessio/vitess/pull/14545
From the previous PR:
> As described in https://github.com/vitessio/vitess/issues/11684, the `--buffer_drain_concurrency` CLI argument to vtgate does not actually do anything.
> 
> This pull request implements the logic required to make this flag actually do something. 😬 When the buffer is drained, we now spawn as many goroutines as specified by `--buffer_drain_concurrency` to drain the buffer in parallel.
>
> I don't think introducing a new flag as described in https://github.com/vitessio/vitess/issues/11684 actually makes sense - instead I propose we mention this in the v19 changelog that this flag is now doing something, and …

Fix `buffer_drain_concurrency` not doing anything

---

go/mysql/conn.go
go/mysql/conn_test.go
go/mysql/query.go

ooops! I actually forgot to push the second commit from https://github.com/vitessio/vitess/pull/15067 before that PR was merged. My bad!
This commit removes the second allocation as described in the PR description for the previous PR. With this change, the `parseOKPacket` API is _actually_ zero-allocation.
- https://github.com/vitessio/vitess/pull/15067
- https://github.com/vitessio/vitess/issues/15071

mysql: remove more allocations from parseOKPacket

---

go/test/endtoend/vtgate/queries/misc/misc_test.go
go/vt/vtgate/executor.go
go/vt/vtgate/executor_select_test.go

This PR fixes to return the flag default for `transaction_mode` instead of `UNSPECIFIED` value.
- Fixes https://github.com/vitessio/vitess/issues/8150

`transaction_mode` variable to return flag default if unset

---

go/vt/vttablet/tabletserver/query_executor.go
go/vt/vttablet/tabletserver/query_executor_test.go

Record the `WaitingForConnection` stat whether or not the connection succeeds. This stat is needed in the error path for metrics and logging.
- Fixes https://github.com/vitessio/vitess/issues/15093
N/A

query_executor: Record `WaitingForConnection` stat in all cases

---

go/vt/vtgate/evalengine/api_type_aggregation.go
go/vt/vtgate/evalengine/api_type_aggregation_test.go

As requested by @systay in https://github.com/vitessio/vitess/pull/15069#pullrequestreview-1850341374, this PR implements a helper in the `evalengine` that performs type aggregation on the engine's native `Type` struct, as opposed to `sqltypes.Type` which is what we were previously using.
cc @dbussink 
- https://github.com/vitessio/vitess/pull/15069#pullrequestreview-1850341374
- 

evalengine: implement AggregateEvalTypes

---

go/sqltypes/named_result_test.go
go/sqltypes/parse_rows_test.go
go/sqltypes/query_response_test.go
go/sqltypes/type_test.go

This commit increases the code coverage of the `go/sqltypes` package to 62%.
Partially addresses: https://github.com/vitessio/vitess/issues/14931

Added missing tests for the sqltypes package

---

go/mathstats/beta_test.go
go/mathstats/sample_test.go
go/mathstats/tdist_test.go
go/mathstats/ttest_test.go

Bumps coverage to 98.3%
#14931

tests: add tests for `go/mathstats`

---

go/test/endtoend/vtgate/foreignkey/fk_fuzz_test.go
go/test/endtoend/vtgate/foreignkey/fk_test.go
go/vt/sqlparser/ast.go
go/vt/sqlparser/ast_clone.go
go/vt/sqlparser/ast_copy_on_rewrite.go
go/vt/sqlparser/ast_equals.go
go/vt/sqlparser/ast_format.go
go/vt/sqlparser/ast_format_fast.go
go/vt/sqlparser/ast_funcs.go
go/vt/sqlparser/ast_rewrite.go
go/vt/sqlparser/ast_visit.go
go/vt/sqlparser/cached_size.go
go/vt/vtctl/workflow/vexec/vexec.go
go/vt/vtgate/planbuilder/delete.go
go/vt/vtgate/planbuilder/operators/delete.go
go/vt/vtgate/planbuilder/operators/route_planning.go
go/vt/vtgate/planbuilder/operators/update.go
go/vt/vtgate/planbuilder/plan_test.go
go/vt/vtgate/planbuilder/testdata/foreignkey_cases.json
go/vt/vtgate/planbuilder/testdata/foreignkey_checks_off_cases.json
go/vt/vtgate/planbuilder/testdata/foreignkey_checks_on_cases.json
go/vt/vtgate/planbuilder/testdata/unsupported_cases.json
go/vt/vtgate/planbuilder/testdata/vschemas/schema.json
go/vt/vtgate/semantics/analyzer.go
go/vt/vtgate/semantics/scoper.go
go/vt/vtgate/semantics/semantic_state.go
go/vt/vttablet/tabletserver/planbuilder/permission.go
go/vt/vttablet/tabletserver/planbuilder/permission_test.go
go/vt/wrangler/vexec_plan.go

This PR makes the changes to support multi-table delete queries along with foreign keys. After the changes in this PR, queries like the following now work - 
```SQL
delete u_tbl1 from u_tbl10 join u_tbl1 on u_tbl10.col = u_tbl1.col
```
Fuzzer tests for the same have been added and verified everything is working as intended.
- Part of https://github.com/vitessio/vitess/issues/12967

Add support for multi table deletes with foreign keys

---

go/vt/env/env.go
go/vt/env/env_test.go
go/vt/mysqlctl/mysqld.go

The following vitess binaries call the tabletmanager [`FullStatus`](https://github.com/vitessio/vitess/blob/31472406194450a258faba02f3477c29f2330b40/go/vt/vttablet/tabletmanager/rpc_replication.go#L53) RPC:
- `vtorc`: It runs it via `refreshAllTablets()` every 15 seconds by default
- `vtadmin`: It runs it on the tablet view pages (I believe with a regular auto refresh)
- `vtctldclient`: Any time the [`GetFullStatus`](https://vitess.io/docs/18.0/reference/programs/vtctldclient/vtctldclient_getfullstatus/) command is used  
In the `vtorc` (for sure) and `vtadmin` (I think) cases, it's run automatically and periodically. So over time, this RPC can be called many thousands of times on a tablet. And this RPC is merely one thing that ends up calling the `VtMySQLRoot()` function. This function …

Improve efficiency and accuracy of mysqld.GetVersionString

---

go/mysql/auth_server_clientcert_test.go
go/mysql/client_test.go
go/mysql/conn.go
go/mysql/conn_test.go
go/mysql/fakesqldb/server.go
go/mysql/handshake_test.go
go/mysql/server.go
go/mysql/server_test.go
go/vt/vtenv/vtenv.go
go/vt/vtgate/plugin_mysql_server.go
go/vt/vtgate/plugin_mysql_server_test.go

The collation env refactor missed a bunch of setup for the MySQL listener, which resulted in a missing initial collation on the connection.
This fixes that and adds additional assertions as well.
Fixes #15112

mysql: Ensure we set up the initial collation correctly

---

go/vt/topo/keyspace.go
go/vt/topo/keyspace_external_test.go

When doing key range prefix scans via `TopoServer.List()` the scan is "recursive" — we get all keys with the matching prefix. This means that it's possible you can get keys that aren't for the type you're looking for but share the same prefix. A practical example of this would be Keyspaces or Shards, as you can get a lock on either and those are implemented in some topo servers by creating a key with the same prefix of what you're locking and with `/locks/<uid>` appended to it.
When doing key prefix scans, at least for things that you can get a lock on, we should be sure to ignore keys with a different suffix than we're looking for as it's the suffix which reflects the type of value/protobuf stored in it.
I have seen this type of error occur in two CI tests now ([latest …

Ignore non-Shard keys in FindAllShardsInKeyspace List impl

---

go/test/endtoend/vtgate/queries/union/union_test.go
go/vt/vtgate/planbuilder/operators/union_merging.go
go/vt/vtgate/planbuilder/testdata/union_cases.json

The query 
```sql
select 1 from user 
union 
select 2 from user
``` 
was transformed into 
```sql
select `1`, weight_string(`1`) from (
select 1 from `user` 
union 
select 2 from `user`) as dt
```
for execution, but by copying the types, it can be simplified and avoid the generation of a derived table. We can now just use the original query.
https://github.com/vitessio/vitess/issues/15020

Copy expression types to avoid weight_strings and derived tables

---

README.md

1. I'm not sure what it is
2. I don't think it was working properly as it had been setup with the old `youtube/vitess` repo (vs `vitessio/vitess`).
ℹ️ In working on this I also noticed that our codecov link wasn't great because it doesn't include the default branch. So I updated that here as well.

Remove codebeat badge

---

go/vt/vtctl/reparentutil/planned_reparenter.go
go/vt/vtctl/reparentutil/planned_reparenter_flaky_test.go
go/vt/vtctl/reparentutil/util.go
go/vt/vtctl/reparentutil/util_test.go

This PR fixes the bug described in https://github.com/vitessio/vitess/issues/15089.
Now when running PRS, if both the new primary and the tolerable replication lag has been provided, we will check that the new primary tablet actually has a replication lag lower than what we can tolerate, otherwise we'll fail the PRS quickly.
- Fixes https://github.com/vitessio/vitess/issues/15089

Respect tolerable replication lag even when the new primary has been provided in PRS

---

go/cmd/zk/internal/zkfs/zkfs.go
go/cmd/zk/internal/zkfs/zkfs_test.go

- Added the tests for some utilities for `vitess/go/cmd/zk/internal/zkfs`
- I couldn't add the complete coverage code as I am having trouble mocking the `zk2topo.ZkConn` in a simple manner for testing. If anyone can point me to any files that might have done the same previously, or give me some clue as to how we might go about it (without defining all the required methods explicitly), I would love to update the PR to handle the same as well. 
Fixes part of #14931

tests: add tests for `zkfs` utilities

---

go/vt/schemadiff/errors.go
go/vt/schemadiff/schema.go
go/vt/schemadiff/schema_test.go

See https://github.com/vitessio/vitess/issues/15061 for details.
`schemadiff` does not support foreign key cycles (with the exception of self referencing tables). In this PR, `schemadiff` identifies cycles and reports those cycles as part of the schema validation process. Taking the same example from https://github.com/vitessio/vitess/issues/15061:
```sql
create table t11 (id int primary key, i int, constraint f11 foreign key (i) references t12 (id));
create table t12 (id int primary key, i int, constraint f12 foreign key (i) references t11 (id));
```
As of this PR, `schemadiff` will now report:
```
table `t11` participates in foreign key loop: `t11`, `t12`, `t11`
table `t12` participates in foreign key loop: `t11`, `t12`, `t11`
```
`schemadiff` will further identify tables that reference …

`schemadiff`: analyze and report foreign key loops/cycles

---

go/vt/vtgate/semantics/analyzer_test.go

Increase test coverage in the semantics package.
#14931 
Added test analyzestrict.

Added test for AnalyzeStrict

---

go/sqlescape/ids_test.go
go/test/endtoend/onlineddl/revert/onlineddl_revert_test.go
go/test/endtoend/onlineddl/vrepl_suite/testdata/enum-rename/alter
go/test/endtoend/onlineddl/vrepl_suite/testdata/enum-rename/create.sql
go/test/endtoend/onlineddl/vrepl_suite/testdata/enum-truncate/alter
go/test/endtoend/onlineddl/vrepl_suite/testdata/enum-truncate/create.sql
go/test/endtoend/onlineddl/vrepl_suite/testdata/fail-enum-rename-changelog/alter
go/test/endtoend/onlineddl/vrepl_suite/testdata/fail-enum-rename-changelog/create.sql
go/test/endtoend/onlineddl/vrepl_suite/testdata/fail-enum-rename-changelog/expect_failure
go/test/endtoend/onlineddl/vrepl_suite/testdata/fail-enum-rename-copy/alter
go/test/endtoend/onlineddl/vrepl_suite/testdata/fail-enum-rename-copy/create.sql
go/test/endtoend/onlineddl/vrepl_suite/testdata/fail-enum-rename-copy/expect_failure
go/test/endtoend/onlineddl/vrepl_suite/testdata/fail-enum-truncate-changelog/alter
go/test/endtoend/onlineddl/vrepl_suite/testdata/fail-enum-truncate-changelog/create.sql
go/test/endtoend/onlineddl/vrepl_suite/testdata/fail-enum-truncate-changelog/expect_failure
go/test/endtoend/onlineddl/vrepl_suite/testdata/fail-enum-truncate-copy/alter
go/test/endtoend/onlineddl/vrepl_suite/testdata/fail-enum-truncate-copy/create.sql
go/test/endtoend/onlineddl/vrepl_suite/testdata/fail-enum-truncate-copy/expect_failure
go/vt/schemadiff/column.go
go/vt/schemadiff/diff_test.go
go/vt/schemadiff/errors.go
go/vt/schemadiff/schema.go
go/vt/schemadiff/table.go
go/vt/schemadiff/table_test.go
go/vt/schemadiff/types.go
go/vt/vttablet/onlineddl/executor.go
go/vt/vttablet/onlineddl/vrepl/foreign_key.go

`schemadiff` supports `EnumReorderStrategy` in `DiffHints`, of these two values:
- `EnumReorderStrategyReject` - the default
- `EnumReorderStrategyAllow`
`EnumReorderStrategyReject` causes a diff operation to error when `schemadiff` detects that an `enum` or a `set` column reorders its values. This is an undesired operation that is _likely_ caused by a user error.
This PR also adds OnlineDDL/vreplication suite tests -- remember that these are then later used by the endtoend/schemadiff tests.
While we're here, we also clean up and formalize some charset/collation related error messages.
https://github.com/vitessio/vitess/issues/15105
-   [x] If this change is to be back-ported to previous …

`schemadiff`: `EnumReorderStrategy`, checking if enum or set values change ordinal

---

go/test/endtoend/vtgate/queries/union/union_test.go
go/vt/vtgate/planbuilder/operators/union_merging.go
go/vt/vtgate/planbuilder/testdata/union_cases.json

Backport of https://github.com/vitessio/vitess/pull/15069
https://github.com/vitessio/vitess/issues/15020

[release-18.0] In the same sqltypes.Type, Copy expression types to avoid weight_strings and derived tables (#15069)

---

go/vt/servenv/version.go
java/client/pom.xml
java/example/pom.xml
java/grpc-client/pom.xml
java/jdbc/pom.xml
java/pom.xml

Includes the changes required to update the SNAPSHOT version (v20.0.0-SNAPSHOT) after the release of v19.0.0-RC1.

Bump to `v20.0.0-SNAPSHOT` after the `v19.0.0-RC1` release

---

go/mysql/datetime/datetime.go
go/mysql/datetime/parse.go
go/mysql/datetime/parse_test.go
go/mysql/json/parser.go
go/vt/sqlparser/literal.go
go/vt/sqlparser/normalizer.go
go/vt/vtgate/evalengine/compiler_test.go
go/vt/vtgate/evalengine/eval_temporal.go
go/vt/vtgate/evalengine/testcases/cases.go
go/vt/vtgate/evalengine/testcases/helpers.go

In places inside the `evalengine` we need to know if a `TIME` instance was properly parsed, if a value could be extracted from input (but it wasn't entirely valid) or if there's enirely invalid input.
Before we only had one flag that indicated the strict parsing. So we couldn't really discern partial parsing success from entire failure. We tried that with checking for a zero time, but that's wrong. A zero time is still an entirely valid time and can be the result of successful partial parsing.
This was identified in https://github.com/vitessio/vitess/pull/15124, but the fix there didn't look like it was the right approach with yet another flag for allowing a zero time. This since we shouldn't really treat a zero time as special anyway. 
Part of …

mysql/datetime: Improve TIME parsing logic

---

go/vt/vtgate/vschema_manager.go
go/vt/vtgate/vschema_manager_test.go
go/vt/vttablet/endtoend/rpc_test.go
go/vt/vttablet/tabletserver/query_executor.go

This PR removed internal tables to be removed from schema tracking in the `GetSchema` RPC and from the Foreign Key Schema definition. They are temporary tables should be ignored for foreign key planning.
Backport to v18: An issue exists on v18 which can cause queries on unexpected tables.
- Closes https://github.com/vitessio/vitess/issues/15145

fix: ignore internal tables in schema tracking

---

go/vt/vttest/vtprocess.go

This PR partially reverts [a recent change to logging in vttestserver](https://github.com/vitessio/vitess/pull/14383/files#diff-c7f2eec761b37939523a6f6faa42a32ea01342f3bcce218baed7c43b23b4a929) which was made in https://github.com/vitessio/vitess/pull/14383.
For normal build (`go build`) logging will be enabled by default, however, for tests logging will be enabled only if the `-v` flag is passed to `go test`.
Backporting this to both `release-18.0` and `release-19.0` as the issue is observed on both branches as described in https://github.com/vitessio/vitess/issues/15119.
Fixes https://github.com/vitessio/vitess/issues/15119
-   [x] If this change is to be back-ported to previous …

Revert unwanted logging change to `vttestserver`

---

go/cmd/vtcombo/cli/main.go

I accidentally made it so the old default of `$VTDATAROOT/tmp` was never set for vtcombo.
Now we manually provide this default by first checking that the flag exists, and that the user did not explicitly set a value for it.
```
➜  vitess git:(andrew/vtcombo/log-dir-default) ✗ ./bin/vtcombo --port 33574 --bind-address localhost --log_dir /tmp/vtdataroot/vttest445905202/logs --alsologtostderr --grpc_port 33575 --db_charset utf8mb4 --db_app_user vt_dba 2>/dev/null
log_dir=/tmp/vtdataroot/vttest445905202/logs%  
```
```
➜  vitess git:(andrew/vtcombo/log-dir-default) ✗ ./bin/vtcombo --port 33574 --bind-address localhost --alsologtostderr --grpc_port 33575 --db_charset utf8mb4 --db_app_user vt_dba 2>/dev/null 
log_dir=$VTDATAROOT/tmp% 
``` …

Correctly set log_dir default in vtcombo

---

go/vt/vtgate/planbuilder/operators/union_merging.go
go/vt/vtgate/planbuilder/testdata/postprocess_cases.json

A bug was recently solved (#15069) that fixes the type copying to UNION columns. We want to backport this fix, so it didn't contain support for collations. In earlier releases we don't have this capability. 
In `main` we now have a way to aggregate the types including the collation of the columns (#15085), so here is the update that uses this new way of aggregating types. 
Original issue: #15020

feat: use collation aware typing for UNION

---

.github/workflows/update_golang_version.yml

This will enable the automation to upgrade the go version on `release-19.0`

Add `release-19.0` to the auto go upgrade

---

go/mysql/collations/env.go
go/vt/vtgate/engine/aggregations.go
go/vt/vtgate/executor_select_test.go
go/vt/vtgate/planbuilder/collations_test.go
go/vt/vtgate/planbuilder/plan_test.go
go/vt/vtgate/planbuilder/testdata/aggr_cases.json
go/vt/vtgate/planbuilder/testdata/postprocess_cases.json
go/vt/vtgate/planbuilder/testdata/vschemas/schema.json
go/vt/vtgate/semantics/analyzer.go
go/vt/vtgate/semantics/analyzer_test.go
go/vt/vtgate/semantics/real_table.go
go/vt/vtgate/semantics/semantic_state.go
go/vt/vtgate/semantics/typer_test.go
go/vt/vtgate/vindexes/vschema.go

[release-19.0] make sure to handle unsupported collations well

---

go/vt/servenv/version.go
java/client/pom.xml
java/example/pom.xml
java/grpc-client/pom.xml
java/jdbc/pom.xml
java/pom.xml

Includes the changes required to go back into dev mode (v19.0.0-SNAPSHOT) after the release of v19.0.0-RC1.

[release-19.0] Bump to `v19.0.0-SNAPSHOT` after the `v19.0.0-RC1` release

---

go/test/endtoend/vtgate/foreignkey/fk_test.go
go/vt/vtgate/planbuilder/operators/update.go
go/vt/vtgate/planbuilder/testdata/foreignkey_cases.json

This PR adds the support requested in https://github.com/vitessio/vitess/issues/15162.
With the changes in this PR, we support having a subquery in a SET clause of an UPDATE statement even if the column is related by foreign keys.
The changes proposed in the PR, are to use a modified clone statement of `UPDATE` statement for foreign key planning that has the subquery replaced by an argument, and to do the foreign key planning underneath the subquery containers so that the inner subqueries run first and their results can be used for the remainder of the update planning.
- Fixes #15162  …

Subqueries in SET condition of UPDATE statement in presence of foreign keys

---

go/vt/vttablet/tabletserver/throttle/throttler.go

Fixes https://github.com/vitessio/vitess/issues/15179 by removing excessive and ineffective line of code.
The `nil pointer dereference` error could happen when a `v19` primary runs with a `v18` replica.
https://github.com/vitessio/vitess/issues/15179

Throttler: fix nil pointer dereference error

---

.github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml
.github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
.github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
.github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml
.github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml
.github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml

This is a follow up of https://github.com/vitessio/vitess/pull/15169 to bump the go version used in our upgrade tests to `go1.22.0`.

[release-18.0] Use `go1.22.0` in upgrade tests

---

go/event/syslogger/syslogger.go

Commit https://github.com/vitessio/vitess/commit/35dd1b429e21a1034cbde000b765d00ee9349238 upgraded the `glog` version from `v1.0.0` to `v1.1.2`.  Since then, writing logs to `VTDATAROOT/logs` no longer works for `vtcombo` when running inside Docker.
The cause for this is that in `vtcombo`, one of the first packages to be defined is `"vitess.io/vitess/go/vt/log"` which sets all the logging mechanism with `glog`, followed soon after by the package `"vitess.io/vitess/go/event/syslogger"`. The latter has an `init()` function that will directly fail when running inside Docker if you have not properly setup you syslog daemon. The call to `syslog.New` will fail with `Unix syslog delivery error`.
When the `syslog.New` call fails, we log a message using `log.Errorf` which calls `glog`. However, …

Fix logging issue when running in Docker with the syslog daemon disabled

---

go/protoutil/binlogsource.go
go/protoutil/binlogsource_test.go
go/test/endtoend/vreplication/vdiff_helper_test.go
go/vt/binlog/binlogplayer/binlog_player.go
go/vt/vtctl/workflow/resharder.go
go/vt/vttablet/tabletmanager/rpc_vreplication.go
go/vt/vttablet/tabletmanager/rpc_vreplication_test.go
go/vt/vttablet/tabletmanager/vdiff/engine_test.go
go/vt/vttablet/tabletmanager/vdiff/schema.go
go/vt/vttablet/tabletmanager/vdiff/table_differ.go
go/vt/vttablet/tabletmanager/vreplication/insert_generator.go
go/vt/vttablet/tabletmanager/vreplication/vcopier.go
go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go

There was no consistent order used for tables copied/replicated in VReplication and for table's diffed in VDiff. Here we enforce consistent ordering for these things and thus their related `show` command output so that output/behavior is deterministic and it's easier for users to compare progress on similar workflows (e.g. when doing [shard level migrations](https://vitess.io/docs/reference/vreplication/shardlevelmigrations/) across many shards).
-   [x] …

VReplication: Enforce consistent order for table copies and diffs

---

go/vt/throttler/throttler.go
go/vt/vttablet/tabletserver/txthrottler/mock_throttler_test.go
go/vt/vttablet/tabletserver/txthrottler/tx_throttler.go
go/vt/vttablet/tabletserver/txthrottler/tx_throttler_test.go

This PR addresses issue https://github.com/vitessio/vitess/issues/14768. It does so by ensuring that the transaction throttler checks for current lag in the shard before deciding whether to throttle the request or not.
The issue mentioned above is a bug causing artificially high throttling when the `TxThrottler` is enabled. Backporting of this is desirable as it will correct that undesirable behaviour in previous versions, not only in the next one. However, it seems I cannot add the _backport to_ label to the PR.
https://github.com/vitessio/vitess/issues/14768
-   [x] Tests …

TxThrottler: dont throttle unless lag

---

go/vt/vtgate/tabletgateway.go

This is a backport from an internal PR by @aquarapid. The warning which we emit when there's a mismatch between Vitess' collations and the collations in the MySQL cluster can get real noisy because it's emitted once per query. Throttle it with the log throttler.
- https://github.com/vitessio/vitess/issues/15187
- 

Make tablet collation mismatch warning throttled

---

go/vt/vtgate/evalengine/cached_size.go
go/vt/vtgate/evalengine/compiler_asm.go
go/vt/vtgate/evalengine/fn_string.go
go/vt/vtgate/evalengine/testcases/cases.go
go/vt/vtgate/evalengine/translate_builtin.go

This PR adds implementation of [`SPACE`](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_space) and [`REVERSE`](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_reverse) func in evalengine.
Fixes part of #9647 

evalEngine: Implement SPACE, REVERSE

---

go/flags/endtoend/mysqlctld.txt
go/flags/endtoend/vtcombo.txt
go/flags/endtoend/vtctld.txt
go/flags/endtoend/vtgate.txt
go/flags/endtoend/vtgateclienttest.txt
go/flags/endtoend/vttablet.txt
go/flags/endtoend/vttestserver.txt
go/vt/servenv/grpc_server.go

Keepalive configurations in gRPC are documented here https://grpc.io/docs/guides/keepalive/#keepalive-configuration-specification and they say that they can be specified separately for server and client. The doc itself is not super clear on how to do this, but the go example is pretty good.
Specifically, I and @deepthi  had seen the flags in vttablet and vtgate that set the client side keep-alives. These default to 10 seconds for `grpc_keepalive_time` and `grpc_keepalive_timeout`. What this ensures is that the client asks the server for KeepAlives every 10 seconds, and if it doesn't get a response in 10 seconds, then it closes the connection.
It looks like the problem is that we don't do the same for server connections! This is how we are configuring the keep-alives in the gRPC servers - …

Enable gRPC Server Side Keepalive settings

---

go/vt/grpcclient/client_auth_static.go
go/vt/grpcclient/client_auth_static_test.go
go/vt/vtgate/grpcvtgateconn/conn_rpc_test.go

This PR causes the `--grpc_auth_static_client_creds` file to be loaded once in order to avoid high OS-thread usage when `vtgate` starts up. In the right circumstances, the repeat loading of this file can contribute to `vtgate` crashing on `runtime: program exceeds 10000-thread limit`
This stack is seen using a significant amount of blocking syscalls on every spawned healthcheck stream:
```bash
(dlv) stack
0  0x000000000047f120 in syscall.Syscall6
at syscall/asm_linux_amd64.s:43
1  0x000000000047bb05 in syscall.openat
at syscall/zsyscall_linux_amd64.go:68
2  0x00000000004f7c5b in syscall.Open
at syscall/syscall_linux.go:155
3  0x00000000004f7c5b in os.openFileNolog
at os/file_unix.go:216
4  0x00000000004f6585 in os.OpenFile
at os/file.go:338
5  0x00000000004f694a in os.Open
at …
```

Load `--grpc_auth_static_client_creds` file once

---

go/vt/vtgate/evalengine/cached_size.go
go/vt/vtgate/evalengine/compiler.go
go/vt/vtgate/evalengine/compiler_asm.go
go/vt/vtgate/evalengine/fn_string.go
go/vt/vtgate/evalengine/testcases/cases.go
go/vt/vtgate/evalengine/testcases/inputs.go
go/vt/vtgate/evalengine/translate_builtin.go
go/vt/vtgate/planbuilder/testdata/select_cases.json

This PR adds implementation of [`INSERT`](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_insert) func in evalengine.
Fixes part of #9647 

evalEngine: Implement string `INSERT`

---

.github/workflows/check_label.yml

I _think_ this will fix the issue we have been seeing with the check labels workflow being stuck in "pending". It seems like the repeated addition or deletion of labels cancels the workflow over and over.

Remove concurrency group for check labels workflow

---

go/vt/schemadiff/schema.go
go/vt/schemadiff/schema_diff_test.go
go/vt/schemadiff/types.go

We already now have the MySQL version in the schemadiff environment, so we should use it from there. Having it also in the diff hints is duplicated and confusing this way.
This should have been cleaned up in #14994 but was overlooked. I'd like to also backport this to v19 as well for consistency reasons since we ship that refactor there and this should have been included in that. Otherwise we have v19 with this slight difference again compared to v20. 
- …

schemadiff: Clean up MySQL version from diff hints

---

go/mysql/collations/charset/eightbit/8bit.go
go/mysql/collations/charset/eightbit/binary.go
go/mysql/collations/charset/eightbit/latin1.go
go/mysql/collations/colldata/collation.go
go/vt/vtgate/evalengine/cached_size.go
go/vt/vtgate/evalengine/compiler_asm.go
go/vt/vtgate/evalengine/compiler_test.go
go/vt/vtgate/evalengine/fn_string.go
go/vt/vtgate/evalengine/fn_time.go
go/vt/vtgate/evalengine/testcases/cases.go
go/vt/vtgate/evalengine/testcases/inputs.go
go/vt/vtgate/evalengine/translate_builtin.go

This implements `LOCATE`, `POSITION` and `INSTR` to find substrings inside another string.
It diverges in behavior for multibyte characters because of the bugs in MySQL identified in https://bugs.mysql.com/bug.php?id=113933.
Part of #9647 

evalengine: Implement LOCATE and friends

---

go/trace/fake_test.go
go/trace/logger_test.go
go/trace/opentracing_test.go
go/trace/plugin_datadog_test.go
go/trace/plugin_jaeger_test.go
go/trace/trace_test.go
go/trace/utils_test.go

Increases the code coverage of the trace package to >42%.
https://github.com/vitessio/vitess/issues/14931

Added tests for the go/trace package

---

go/streamlog/streamlog_test.go

This commit increased the code coverage of the `go/streamlog` package to 93%.
Partially addresses: https://github.com/vitessio/vitess/issues/14931

Added missing tests for the go/streamlog package

---

go/vt/vtorc/collection/collection.go
go/vt/vtorc/collection/collection_test.go

This PR adds missing tests for `go/vt/vtorc/collection`

Add missing tests for `go/vt/vtorc/collection`

---

.github/workflows/static_checks_etc.yml

Now that we have the FOSSA license scan working again on merges to main, let's enable the scan on PRs (opened using forks) again by leveraging a push-only token. You can see a successful run here: https://github.com/vitessio/vitess/actions/runs/7893049759/job/21540828304?pr=15222
This gets us back to where we were prior to having to disable it in https://github.com/vitessio/vitess/pull/14119.
- Hopefully the last follow-up to: https://github.com/vitessio/vitess/pull/14119
-   [x] Did the new or modified tests pass consistently …

CI: Use FOSSA push-only token for license scans on PRs

---

README.md

We needed to update the link used as the old one was no longer valid for the repo and our FOSSA account.

Update FOSSA license scan links

---

go/vt/vtctl/grpcvtctldserver/query_test.go
go/vt/vtctl/grpcvtctldserver/server_test.go
go/vt/vttablet/tabletserver/tabletenv/config_test.go

Also parallelizes some tests and tidies up some imports while I'm here.
#15202 

go1.22: remove outdated loopclosure captures in tests

---

go/test/endtoend/tabletmanager/tablegc/tablegc_test.go
go/vt/schema/name.go
go/vt/schema/name_test.go
go/vt/schema/online_ddl_test.go
go/vt/schema/tablegc.go
go/vt/schema/tablegc_test.go
go/vt/vttablet/onlineddl/executor.go
go/vt/vttablet/onlineddl/util.go
go/vt/vttablet/onlineddl/util_test.go
go/vt/vttablet/tabletmanager/vreplication/vreplicator.go

This is the 2nd part of introducing the new vitess internal table names. This PR is post `v19`, and will be merged in `v20`.
In this PR, we still support both old name format and new name format. However, we now generate internal table names in new format only. This means:
- GC table names will look like `_vt_hld_6ace8bcef73211ea87e9f875a4d24e90_20200915120410_`
- OnlineDDL/Vreplication table names will look like `_vt_vrp_6ace8bcef73211ea87e9f875a4d24e90_20200915120410_`
Some implementation notes:
- This PR renames functions in the likeness of "NameNewFormat" to "Name", and "Name" to "NameOldFormat".
- Formalized `InternalTableHint`, which is also used in `TableGCState`
- OnlineDDL/Executor previously generated the `"_vrepl"` table name by itself, directly; now it uses `go/vt/schema` to …

New unified internal table names format: part 2, generating new names

---

go/mysql/fastparse/fastparse.go
go/mysql/fastparse/fastparse_test.go
go/vt/vtgate/evalengine/cached_size.go
go/vt/vtgate/evalengine/compiler_asm.go
go/vt/vtgate/evalengine/fn_numeric.go
go/vt/vtgate/evalengine/fn_string.go
go/vt/vtgate/evalengine/testcases/cases.go
go/vt/vtgate/evalengine/translate_builtin.go

This implements `BIN(<val>)` as `CONV(<val>, 10, 2)`. It also fixes an edge case in uint64 parsing to match MySQL behavior that was exposed with new tests added for `BIN`. 
Also adds `OCT(<val>)` as `CONV(<val>, 10, 8)` and adds `CHAR` too. 
Part of #9647 

evalengine: Implement BIN, OCT & CHAR functions

---

go.mod

In recent Go versions, it can automatically pick up newer toolchain versions, but it means you have to use the right version number.
We had 1.22 here, but with 1.22.0 it can pick up the right one. See also https://github.com/golang/go/issues/62278#issuecomment-1933790368 for example.

Update toolchain version in go.mod

---

go.mod
go.sum
go/stats/statsd/statsd.go
go/stats/statsd/statsd_test.go

This updates to the latest datadog-go API instead of the v4 version. There's some small changes in setup but nothing really fundamentally changing behavior.

statsd: Update to datadog-go v5 API

---

go/vt/vttablet/tabletmanager/rpc_throttler.go
go/vt/vttablet/tabletserver/throttle/throttler.go

Closes https://github.com/vitessio/vitess/issues/15223 by adding these counter metrics:
- `ThrottlerHeartbeatRequests`: incremented each time the throttler requests heartbeat lease (especially useful when `--heartbeat_on_demand_duration` is set).
- `ThrottlerRecentlyChecked`: for when a tablet's throttler is recently checked. This applies to any tablet type. For example, a vreplication `rowstream` could run on a particular replica. That replica would report itself as being "recently checked".
- `ThrottlerProbeRecentlyChecked`: for when a `PRIMARY` tablet throttler probes the shard tablets, and one of the probed tablets reports it has been "recently checked".
- `ThrottlerCheckRequest`: when a tablet receives a gRPC `CheckThrottler` call.
These metrics will help to pinpoint throttler …

Tablet throttler: adding more stats

---

examples/compose/client.go
examples/compose/vtcompose/vtcompose.go
go/bucketpool/bucketpool_test.go
go/cache/theine/bf/bf.go
go/cache/theine/list_test.go
go/cache/theine/singleflight_test.go
go/cache/theine/sketch_test.go
go/cache/theine/store.go
go/cache/theine/store_test.go
go/cache/theine/tlfu_test.go

This updates a small portion of the codebase, primarily to use the new range syntax, but then made some `assert/require` changes in files I happened to already be editing.
#15193 
#15182

New for loops and some assert/require

---

changelog/20.0/20.0.0/summary.md
go/test/endtoend/vtgate/queries/dml/dml_test.go
go/vt/vtgate/planbuilder/delete.go
go/vt/vtgate/planbuilder/operator_transformers.go
go/vt/vtgate/planbuilder/operators/delete.go
go/vt/vtgate/planbuilder/operators/dml_planning.go
go/vt/vtgate/planbuilder/operators/update.go
go/vt/vtgate/planbuilder/plan_test.go
go/vt/vtgate/planbuilder/testdata/dml_cases.json
go/vt/vtgate/planbuilder/testdata/unsupported_cases.json

This PR adds support for a subquery in a Delete.
e.g. `delete from user where id > (select col from music where id = 2)`
- https://github.com/vitessio/vitess/issues/3838

Delete with subquery support

---

go/vt/mysqlctl/schema.go
go/vt/vtexplain/vtexplain_vttablet.go
go/vt/vtexplain/vtexplain_vttablet_test.go

In https://github.com/vitessio/vitess/pull/13312 we fixed how we encode names in `information_schema` queries. The problem there though is that the `GetColumnNamesQuery` string was also used inside `vtexplain`. Its usage there was not updated for the new escaping logic.
This in turn leads to broken queries during `vtexplain` which then leads to a lot of logs. The issue here is not that we log a lot, we log that we actually do have a problem here which is the case.
This fixes the underlying issue of not correctly generating the query as we should.
Part of https://github.com/vitessio/vitess/issues/15242
Marked for backporting all the way to v16, since that's where the original change in https://github.com/vitessio/vitess/pull/13312 was also back ported to. 
-   [x] "Backport to:" labels …

vtexplain: Fix setting up the column information

---

go/vt/vtgate/evalengine/cached_size.go
go/vt/vtgate/evalengine/compiler_asm.go
go/vt/vtgate/evalengine/compiler_test.go
go/vt/vtgate/evalengine/fn_string.go
go/vt/vtgate/evalengine/testcases/cases.go
go/vt/vtgate/evalengine/translate_builtin.go

This implements the REPLACE function. This function is documented as case sensitive, but in practice is also byte sensitive. This means that equal characters under collation rules are not replaced.
Part of #9647 

evalengine: Implement REPLACE

---

go/cmd/vtexplain/cli/vtexplain.go
go/vt/srvtopo/watch.go
go/vt/srvtopo/watch_srvkeyspace.go
go/vt/vtadmin/api.go
go/vt/vtexplain/vtexplain.go
go/vt/vtexplain/vtexplain_test.go
go/vt/vtexplain/vtexplain_vtgate.go
go/vt/vtexplain/vtexplain_vttablet.go
go/vt/vtexplain/vtexplain_vttablet_test.go
go/vt/vttablet/tabletserver/throttle/throttler.go

This logic ensures the memorytopo is set up for the throttler logic so that it doesn't log any errors.
Needs to be backported to all supported versions, since the throttler is part of all of those. 
Part of #15242 

vtexplain: Ensure memory topo is set up for throttler

---

go/vt/vtctl/reparent.go
go/vt/wrangler/reparent.go
go/vt/wrangler/testlib/emergency_reparent_shard_test.go

While updating some internal code I noticed that the PRS "tolerable replication lag" parameter had to be added to all call sites that use the wrangler. The function signature was difficult to parse beforehand due to length, and the complexity will increase as more parameters are added.
Use the reparentutil structs as arguments instead of constructing them inside the wrangler in order to make the options lists more legible and extensible.
n/a, cleanup only.
-   [] Did the new or modified tests pass consistently locally and on CI? …

go/vt/wrangler: pass reparent options structs

---

go/test/endtoend/backup/vtbackup/backup_only_test.go
go/test/endtoend/backup/vtctlbackup/backup_utils.go
go/test/endtoend/cellalias/cell_alias_test.go
go/test/endtoend/cluster/cluster_process.go
go/test/endtoend/cluster/cluster_util.go
go/test/endtoend/cluster/vtctldclient_process.go
go/test/endtoend/clustertest/vttablet_test.go
go/test/endtoend/encryption/encryptedreplication/encrypted_replication_test.go
go/test/endtoend/keyspace/keyspace_test.go
go/test/endtoend/messaging/message_test.go
go/test/endtoend/migration/migration_test.go
go/test/endtoend/mysqlctl/mysqlctl_test.go
go/test/endtoend/mysqlctld/mysqlctld_test.go
go/test/endtoend/onlineddl/ghost/onlineddl_ghost_test.go
go/test/endtoend/onlineddl/revert/onlineddl_revert_test.go
go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go
go/test/endtoend/onlineddl/vrepl_stress/onlineddl_vrepl_mini_stress_test.go
go/test/endtoend/onlineddl/vrepl_stress_suite/onlineddl_vrepl_stress_suite_test.go
go/test/endtoend/onlineddl/vtctlutil.go
go/test/endtoend/recovery/pitr/shardedpitr_test.go
go/test/endtoend/recovery/unshardedrecovery/recovery.go
go/test/endtoend/reparent/emergencyreparent/ers_test.go

I arbitrarily picked this as a stopping point for this batch. I'll do another round after this!
I'm focusing on the non-output-focused stuff for now to put off dealing with minor changes in output that tests may depend on, but those are coming up.
#15273 

Rewrite _many_ tests to use vtctldclient invocations, mostly non-output related stuff

---

examples/common/scripts/vttablet-up.sh

Followup to https://github.com/vitessio/vitess/issues/14978, https://github.com/vitessio/vitess/pull/14980, and https://github.com/vitessio/vitess/pull/15099. This PR re-enables `heartbeat_on_demand_duration` in `vttablet-up.sh` script in `examples/local`.
This comes at no cost when the throttler is disabled, and makes it possible for the throttler to work based on replication lag.
Future work to change the defaults/default behavior of heartbeat mechanism. See discussion in https://github.com/vitessio/vitess/pull/15099.
Without this PR, the throttler won't work properly in `examples`. I therefore want to backport this to all supported versions, just as https://github.com/vitessio/vitess/pull/14980 was backported.
- https://github.com/vitessio/vitess/issues/14978
- …

Enable 'heartbeat_on_demand_duration' in local/examples

---

go/vt/vttablet/grpctabletconn/conn.go
go/vt/vttablet/grpctabletconn/conn_test.go

This PR fixes the issue described in https://github.com/vitessio/vitess/issues/14201.
On following the steps listed in the issue, it was noticed that we indeed had a bunch of go-routines being spawned off, that never really went away - 
```
goroutine profile: total 102
31 @ 0x102aaf7e8 0x102ac2c38 0x103033f0c 0x102ae9dc4
#	0x103033f0b	google.golang.org/grpc.newClientStreamWithParams.func4+0x8b	google.golang.org/grpc@v1.61.1/stream.go:393
```
Notice the count of the go-routines which are all on the same line. Its 31, but running the queries in a loop causes it to increase by 1 for each iteration.
The problem causes go-routines to leak which will eventually lead to an OOM. The fix however was pretty straightforward. 
In the `StreamExecute` RPC code, we have the following comment …

Fix Go routine leaks in streaming calls

---

go/cmd/vtcombo/cli/main.go
go/flags/endtoend/vtcombo.txt

At GitHub, we use `vtcombo` in our CI system and our local development environments.
While investigating slow CI setup times, I noticed that `vtcombo` by default is starting 3 tablets (`PRIMARY`, `RDONLY` and `REPLICA`) per keyspace/cell. For a small topology, that's not really an issue, but we run multiple hundreds of keyspaces in CI, and just starting this setup takes almost a minute.
This is quite wasteful, especially because we don't use `RDONLY` and `REPLICA` tablets at all in CI or local development. To improve this, we can set `replicaCount` to `1` to only start a single `REPLICA` tablet (which will be promoted to primary), and `rdonlyCount` to `-1` to start no `RDONLY` tablets.
Unfortunately, `vtcombo` will start `vtgate` and instruct it to wait for `PRIMARY,REPLICA,RDONLY` …

[vtcombo] Expose `--tablet_types_to_wait` flag

---

go/cmd/mysqlctld/cli/mysqlctld.go
go/cmd/topo2topo/cli/topo2topo.go
go/cmd/vtexplain/cli/vtexplain.go
go/cmd/vttestserver/cli/main.go
go/cmd/zkctld/cli/zkctld.go
go/flags/endtoend/zkctld.txt

This PR fixes the issue pointed out in https://github.com/vitessio/vitess/issues/15305. 
The fix is just to specify the Version field when we initialize the root command for the binaries.
- Fixes https://github.com/vitessio/vitess/issues/15305

Fix some binaries to print the versions

---

go/vt/sqlparser/ast_format.go
go/vt/sqlparser/ast_format_fast.go
go/vt/sqlparser/parse_test.go
go/vt/vtgate/planbuilder/testdata/cte_cases.json

Support `WITH ... SELECT ... UNION ... SELECT` CTE syntax.
https://github.com/vitessio/vitess/issues/15311

planner: support union statements with ctes

---

go/test/endtoend/vtorc/api/api_test.go
go/vt/vtorc/logic/tablet_discovery.go
go/vt/vtorc/logic/tablet_discovery_test.go
go/vt/vtorc/logic/vtorc.go
go/vt/vtorc/process/health.go

This PR makes the changes requested in https://github.com/vitessio/vitess/issues/15314.
This PR removes the wait period from VTOrc. Also, I noticed that the topo tick that we use to load all the information doesn't trigger immediately. So, in this PR, during the starting phase of VTOrc, we make it populate all the information once in the beginning. And then we can start checking and recovering failures without needing the wait period we had before.
An additional benefit of the changes in this PR is that when VTOrc displays itself as healthy in the `/debug/healthy` API, then it is actually ready to run recoveries, which wasn't true before.
- Fixes https://github.com/vitessio/vitess/issues/15314
-   [x] "Backport to:" labels have been added if this change should be back-ported to release …

Improve VTOrc startup flow

---

go/vt/discovery/healthcheck.go

This PR skips an allocation in a `for`-loop from `go/vt/discovery/healthcheck.go`
If I understand correctly this will cause 1 x allocation for `var tabletHealths []*TabletHealth` per execution of `.waitForTablets(...)` vs `<numTargets> x <numRetries>`
N/A

Skip for-loop alloc in `go/vt/discovery/healthcheck.go`

---

go/mysql/sqlerror/sql_error.go
go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
go/test/endtoend/vtgate/queries/dml/insert_test.go
go/test/endtoend/vtgate/queries/lookup_queries/main_test.go
go/test/endtoend/vtgate/queries/misc/misc_test.go
go/test/endtoend/vtgate/queries/orderby/orderby_test.go
go/test/endtoend/vtgate/queries/orderby/schema.sql
go/test/endtoend/vtgate/queries/orderby/vschema.json
go/test/endtoend/vtgate/queries/union/union_test.go
go/vt/schemadiff/schema.go
go/vt/vterrors/state.go
go/vt/vtgate/planbuilder/testdata/postprocess_cases.json
go/vt/vtgate/planbuilder/testdata/unsupported_cases.json
go/vt/vtgate/semantics/analyzer.go
go/vt/vtgate/semantics/binder.go
go/vt/vtgate/semantics/early_rewriter.go
go/vt/vtgate/semantics/early_rewriter_test.go
go/vt/vtgate/semantics/errors.go

In a recent [PR](https://github.com/vitessio/vitess/pull/14935), I did some work on how to rewrite column aliases used in ORDER BY,  GROUP BY and HAVING.
I did not get that right, and introduced issues for a set of queries. This PR tries to correctly rewrite more column using the same rules that MySQL has.
Terminology first: an expression in the `SELECT` clause is a SELECT-expression. These can have aliased.
An ORDER BY expression is an expression listed in the ORDER BY clause, without the ASC/DESC modifier.
Rewrite rule:
An unqualified column name in the ORDER BY that matches an alias among the SELECT expressions will be replaced with the SELECT expression if:
- ORDER BY is on SELECT and not UNION
- It's the full ORDER BY expression, _OR_ no table has a matching column name, _OR_ it's …

Column alias expanding on ORDER BY

---

go/test/endtoend/utils/cmp.go
go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go

When we are inside a `t.Run` or `mcmp.Run`, we need to mark the correct `t` as skipped. Since the `mcmp` struct contains the `*testing.T` we are using, we should not use the outer `t` for skipping.

test: skip should mark the correct *testing.T

---

go/cmd/vtcombo/cli/main.go
go/cmd/vtexplain/cli/vtexplain.go
go/cmd/vtgate/cli/cli.go
go/cmd/vttablet/cli/cli.go
go/vt/srvtopo/discover_test.go
go/vt/srvtopo/resilient_server.go
go/vt/srvtopo/resilient_server_test.go
go/vt/srvtopo/resolver_test.go
go/vt/vtadmin/api.go
go/vt/vtcombo/tablet_map.go
go/vt/vtexplain/vtexplain.go
go/vt/vtexplain/vtexplain_test.go
go/vt/vtexplain/vtexplain_vtgate.go
go/vt/vtexplain/vtexplain_vttablet.go
go/vt/vtexplain/vtexplain_vttablet_test.go
go/vt/vttablet/endtoend/framework/server.go
go/vt/vttablet/tabletserver/query_executor_test.go
go/vt/vttablet/tabletserver/tabletserver.go
go/vt/vttablet/tabletserver/tabletserver_test.go
go/vt/vttablet/tabletserver/vstreamer/testenv/testenv.go

We currently create a single `srvTopoServer` inside `NewTabletServer` to avoid panics on duplicate metrics.
This is wrong though, since the topo server created is tied to the context given, and if that is cancelled, it will be stopped. We will then never start a new one.
The reason this was set up like that is because of metrics. So instead of what we did before, we need to create metrics once. All other metrics are created in `init()` functions and we need to do the same here.
Fixes #15319 …

srvtopo: Setup metrics in init() function

---

go/vt/wrangler/materializer_env_test.go
go/vt/wrangler/materializer_test.go

There was another implementation of the leak checking logic here, but it was not actually used. Instead this now follows the same pattern we use for vtgate tests to ensure there's no leaks, but for the materializer env.

wranger: Clean up leak check and use existing version

---

go/test/endtoend/tabletgateway/vtgate_test.go
go/vt/vtgate/executor.go
go/vt/vtgate/executor_test.go
go/vt/vttablet/tabletserver/repltracker/poller.go
go/vt/vttablet/tabletserver/repltracker/repltracker.go
go/vt/vttablet/tabletserver/throttle/throttlerapp/app.go

We added the `show vitess_replication_status` query in https://github.com/vitessio/vitess/pull/8900. At the time I chose to use the tablet's replication lag stats variable as we could get a more accurate representation of the lag than using mysqld's `seconds_behind_[master|source]` value. The stat relied on polling — in which case we can also estimate the lag when replication is not running – or sub-second heartbeats, and it was more accurate for these reasons.
This query was first introduced in v12 and at that time the [`ReplicationTracker`](https://github.com/vitessio/vitess/blob/main/go/vt/vttablet/tabletserver/repltracker/repltracker.go) was [always enabled in the local examples](https://github.com/vitessio/vitess/blob/release-12.0/examples/local/scripts/vttablet-up.sh#L49) using the …

SHOW VITESS_REPLICATION_STATUS: Only use replication tracker when it's enabled

---

go/flags/endtoend/vtbackup.txt
go/flags/endtoend/vtcombo.txt
go/flags/endtoend/vtctld.txt
go/flags/endtoend/vtorc.txt
go/flags/endtoend/vttablet.txt
go/flags/endtoend/vttestserver.txt
go/vt/vtorc/inst/instance_dao.go
go/vt/vtorc/inst/tablet_dao.go
go/vt/vtorc/logic/tablet_discovery.go
go/vt/vtorc/logic/topology_recovery.go
go/vt/vttablet/grpctmclient/client.go

This PR implements the feature requested in https://github.com/vitessio/vitess/issues/15355.
Similar changes to the `CheckThrottler` RPC had been made in https://github.com/vitessio/vitess/pull/14979. This PR replicates them for `FullStatus` RPC. While working on this, a few more refactoring changes have been made to make the code more uniform.
- Fixes https://github.com/vitessio/vitess/issues/15355

VTOrc optimize TMC usage

---

go/vt/topo/memorytopo/election.go
go/vt/topo/memorytopo/lock.go
go/vt/topo/memorytopo/memorytopo.go
go/vt/topo/memorytopo/watch.go

This resolves the seen data races on the variable: https://github.com/vitessio/vitess/actions/runs/8054421738/job/21999131114?pr=15361
<details>
<summary>Click here to see example data races</summary>
```
2024-02-26T19:44:41.3026420Z ==================
2024-02-26T19:44:41.3026668Z WARNING: DATA RACE
2024-02-26T19:44:41.3026961Z Write at 0x00c001c0ef58 by goroutine 642:
2024-02-26T19:44:41.3027433Z   vitess.io/vitess/go/vt/topo/memorytopo.(*Conn).Close()
2024-02-26T19:44:41.3028200Z       /home/runner/work/vitess/vitess/go/vt/topo/memorytopo/memorytopo.go:144 +0x2f
2024-02-26T19:44:41.3028835Z   vitess.io/vitess/go/vt/topo.(*StatsConn).Close()
2024-02-26T19:44:41.3029477Z       /home/runner/work/vitess/vitess/go/vt/topo/stats_conn.go:212 +0x1fa
2024-02-26T19:44:41.3030043Z …
```

CI: Address data races on memorytopo Conn.closed

---

go/test/endtoend/vtgate/queries/dml/dml_test.go
go/vt/vtgate/engine/cached_size.go
go/vt/vtgate/engine/dml_with_input.go
go/vt/vtgate/engine/dml_with_input_test.go
go/vt/vtgate/evalengine/cached_size.go
go/vt/vtgate/evalengine/expr_tuple_bvar.go
go/vt/vtgate/planbuilder/delete.go
go/vt/vtgate/planbuilder/dml_with_input.go
go/vt/vtgate/planbuilder/operator_transformers.go
go/vt/vtgate/planbuilder/operators/delete.go
go/vt/vtgate/planbuilder/operators/dml_planning.go
go/vt/vtgate/planbuilder/operators/dml_with_input.go
go/vt/vtgate/planbuilder/operators/phases.go
go/vt/vtgate/planbuilder/operators/update.go
go/vt/vtgate/planbuilder/plan_test.go
go/vt/vtgate/planbuilder/testdata/dml_cases.json
go/vt/vtgate/planbuilder/testdata/foreignkey_cases.json
go/vt/vtgate/planbuilder/testdata/foreignkey_checks_on_cases.json
go/vt/vtgate/planbuilder/testdata/show_cases.json
go/vt/vtgate/planbuilder/testdata/unknown_schema_cases.json
go/vt/vtgate/planbuilder/testdata/unsupported_cases.json
go/vt/vtgate/planbuilder/testdata/vschemas/schema.json

This PR is an enhancement on earlier PR to add support for multi-target delete.
Example: `delete u, m from user u, music m on u.col = m.col`
The SQL here deletes rows from two tables using the join condition.
- Closes https://github.com/vitessio/vitess/issues/5392
- #14855 

Multi Target Delete Support

---

go/vt/discovery/healthcheck.go
go/vt/discovery/healthcheck_test.go
go/vt/srvtopo/discover.go
go/vt/srvtopo/discover_test.go
go/vt/vtgate/tabletgateway.go

This PR causes the `tabletgateway` `.WaitForTablets(...)` method to filter targets by keyspace _(set by `--keyspaces_to_watch`)_ earlier in the process
Currently, the logic under `.WaitForTablets(...)`:
1. Uses `srvtopo.FindAllTargets(...)` to fetch the targets by-cell for **_any_** keyspace _(even if `--keyspaces_to_watch` is set)_
- This calls `.GetSrvKeyspace(...)` on the toposerver for every keyspace in goroutines w/wait group
2. Later targets that do not match `--keyspaces_to_watch` are removed from `targets []*querypb.Target`
Instead this PR implements the filtering in `srvtopo.FindAllTargets(...)` by not-fetching keyspaces from the topo that will just get filtered anyways. This can avoid topo calls and unnecessary filtering of results on deployments with many keyspaces and a subset …

Filter by keyspace earlier in `tabletgateway`s `WaitForTablets(...)`

---

go/test/endtoend/vreplication/cluster_test.go
go/test/endtoend/vreplication/fk_ext_test.go
go/test/endtoend/vreplication/performance_test.go

Note that I left `queryLog` as well as the `exec(...)WithRetry` bits untouched since we use those when debugging (maybe we should add a flag to toggle that behavior rather than having to edit tests)

delete unused code in vreplication e2e tests

---

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
go/vt/vtgate/executor_select_test.go
go/vt/vtgate/planbuilder/testdata/aggr_cases.json
go/vt/vtgate/planbuilder/testdata/cte_cases.json
go/vt/vtgate/planbuilder/testdata/filter_cases.json
go/vt/vtgate/planbuilder/testdata/memory_sort_cases.json
go/vt/vtgate/planbuilder/testdata/oltp_cases.json
go/vt/vtgate/planbuilder/testdata/postprocess_cases.json
go/vt/vtgate/planbuilder/testdata/select_cases.json
go/vt/vtgate/planbuilder/testdata/tpcc_cases.json
go/vt/vtgate/planbuilder/testdata/tpch_cases.json
go/vt/vtgate/planbuilder/testdata/union_cases.json
go/vt/vtgate/semantics/analyzer.go
go/vt/vtgate/semantics/analyzer_test.go
go/vt/vtgate/semantics/binder.go
go/vt/vtgate/semantics/dependencies.go
go/vt/vtgate/semantics/early_rewriter.go
go/vt/vtgate/semantics/early_rewriter_test.go
go/vt/vtgate/semantics/errors.go
go/vt/vtgate/semantics/scoper.go
go/vt/vtgate/semantics/vtable.go

Following up on #15302, this PR does the same fix for `GROUP BY` and `HAVING`.
#15302 (fix for `ORDER BY`)
#14935 (pr that introduced some bad rewrites)

Bugfix: GROUP BY/HAVING alias resolution

---

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
go/test/endtoend/vtgate/queries/orderby/orderby_test.go
go/vt/vtgate/executor_select_test.go
go/vt/vtgate/planbuilder/testdata/aggr_cases.json
go/vt/vtgate/planbuilder/testdata/cte_cases.json
go/vt/vtgate/planbuilder/testdata/filter_cases.json
go/vt/vtgate/planbuilder/testdata/memory_sort_cases.json
go/vt/vtgate/planbuilder/testdata/oltp_cases.json
go/vt/vtgate/planbuilder/testdata/postprocess_cases.json
go/vt/vtgate/planbuilder/testdata/select_cases.json
go/vt/vtgate/planbuilder/testdata/tpcc_cases.json
go/vt/vtgate/planbuilder/testdata/tpch_cases.json
go/vt/vtgate/planbuilder/testdata/union_cases.json
go/vt/vtgate/semantics/analyzer.go
go/vt/vtgate/semantics/analyzer_test.go
go/vt/vtgate/semantics/binder.go
go/vt/vtgate/semantics/dependencies.go
go/vt/vtgate/semantics/early_rewriter.go
go/vt/vtgate/semantics/early_rewriter_test.go
go/vt/vtgate/semantics/errors.go
go/vt/vtgate/semantics/scoper.go
go/vt/vtgate/semantics/vtable.go

This is a backport of vitessio#15344

This is a backport of vitessio#15344

---

go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go

We've seen flakiness in `onlineddl_scheduler` test, `TestSchemaChange/scheduler/Cleanup_artifacts/validate_artifact_exists`. The test run an open ended (`--postpone-completion`) migration, sets a very low artifact retention, and looks to see that its artifacts exist while the migration is running. Artifacts should only be deleted when the migration completes, fails, or gets cancelled, so this is intended to validate we do not cleanup prematurely.
However, it's possible that the artifact is _not yet created_, and that's the race condition. The fact the test is in `running` state, does not mean it's reached the part where the shadow table gets created.
The fix to the flakiness is to wait until the migration is `ready_to_complete`. This guarantees that the artifact (shadow table) is already …

`onlineddl_scheduler` test: fix flakiness in artifact cleanup test

---

go/vt/mysqlctl/s3backupstorage/s3.go
go/vt/mysqlctl/s3backupstorage/s3_test.go

This fixes the issue described in #15335. It seems the bug was introduced in #4200.
The default transport was changed in favour of one were we could skip validating S3 certificates, but instead of cloning the default transport and adjusting the settings, we are creating a new transport from scratch but not setting any defaults ([see current Go defaults for](https://cs.opensource.google/go/go/+/refs/tags/go1.22.0:src/net/http/transport.go;l=43-54) `DefaultTransport`). By doing so, we don't set keepalives, timeouts, max idle connections, etc and other values in `Transport` and since some default to zero it basically means "no limit". To make matters worse, since we are creating a new transport for every client (in this case, for each request from what I understand), there is no sharing of …

prevent vtctld from creating tons of S3 connections

---

go/internal/flag/flag_test.go
go/internal/flag/usage_test.go

This PR adds required tests for `go/internal/flag`.

Add required tests for `internal/flag`

---

go/vt/mysqlctl/mysqld.go

Backporting manually and a bit late, following request by the community.
Coordinated with @systay , the release owner for 19.0.

[release-19.0 backport] Mysqld: capture mysqlbinlog std error output (#15278)

---

.github/workflows/static_checks_etc.yml
.golangci.yml
misc/git/hooks/golangci-lint

Install the latest `golangci-lint` and fix up configuration.
Marked for backport as v19 is also on Go 1.22 and needs the latest too and `exportloopref` is not needed there either. 

Ensure to use latest golangci-lint

---

go/mysql/capabilities/capability.go
go/mysql/capabilities/capability_test.go
go/test/endtoend/onlineddl/vrepl_suite/onlineddl_vrepl_suite_test.go
go/test/endtoend/onlineddl/vrepl_suite/testdata/fk-child-modify-not-null/alter
go/test/endtoend/onlineddl/vrepl_suite/testdata/fk-child-modify-not-null/create.sql
go/test/endtoend/onlineddl/vrepl_suite/testdata/fk-child-modify-not-null/ddl_strategy
go/vt/schemadiff/schema_test.go
go/vt/vttablet/onlineddl/executor.go
go/vt/vttablet/onlineddl/executor_test.go

Solves https://github.com/vitessio/vitess/issues/15375
We added `ALGORITHM=COPY` in https://github.com/vitessio/vitess/pull/12436 and in https://github.com/vitessio/vitess/pull/12521 to overcome a MySQL `8.0.29` vs `Xtrabackup` issue. Those we merged in `release-16.0`.
The problem was resolved as of MySQL `8.0.32`.
This PR no longer adds `ALGORITHM=COPY` for Online DDL operations on `8.0.32` and above. This solves #15375.
Initial commit: adding tests that validate https://github.com/vitessio/vitess/issues/15375
The main change in this PR conditionally undoes https://github.com/vitessio/vitess/pull/12521.
Fixes: https://github.com/vitessio/vitess/issues/15375
-   [ ] If this change is to …

Remove `ALGORITHM=COPY` from Online DDL in MySQL `>= 8.0.32`

---

go/test/endtoend/backup/vtbackup/backup_only_test.go
go/test/endtoend/backup/vtctlbackup/backup_utils.go
go/test/endtoend/cluster/cluster_process.go
go/test/endtoend/cluster/cluster_util.go
go/test/endtoend/cluster/topo_process.go
go/test/endtoend/cluster/vtctl_process.go
go/test/endtoend/cluster/vtctldclient_process.go
go/test/endtoend/clustertest/vtctld_test.go
go/test/endtoend/keyspace/keyspace_test.go
go/test/endtoend/recovery/pitr/shardedpitr_test.go
go/test/endtoend/reparent/utils/utils.go
go/test/endtoend/tabletgateway/buffer/reshard/sharded_buffer_test.go
go/test/endtoend/tabletgateway/vtgate_test.go
go/test/endtoend/tabletmanager/commands_test.go
go/test/endtoend/topoconncache/topo_conn_cache_test.go
go/test/endtoend/vreplication/cluster_test.go

This PR began as an attempt to remove the deprecated `InitTablet` with the underlying topo call, and then evolved to also migrate some of the output-based commands from `vtctlclient` to `vtctldclient`
https://github.com/vitessio/vitess/issues/15273

[e2e] vtctld init tablet and some output-based commands

---

go/vt/vtgate/planbuilder/operators/delete.go
go/vt/vtgate/planbuilder/operators/dml_planning.go
go/vt/vtgate/planbuilder/operators/update.go

The `getVindexInformation` call was returning alternative vindexes, but that was never used by callers. `getUpdateVindexInformation` returned it, but it's callers also never used it.
This means we can remove this, as nothing depends on it.

planbuilder: Cleanup unused logic

---

changelog/19.0/19.0.0/changelog.md
changelog/19.0/19.0.0/release_notes.md

This Pull Request copies the release notes found on `release-19.0` to keep release notes up-to-date after the `v19.0.0` release.

Copy `v19.0.0` release notes on `main`

---

go/vt/servenv/version.go
java/client/pom.xml
java/example/pom.xml
java/grpc-client/pom.xml
java/jdbc/pom.xml
java/pom.xml

Includes the changes required to go back into dev mode (v19.0.1-SNAPSHOT) after the release of v19.0.0.

[release-19.0] Bump to `v19.0.1-SNAPSHOT` after the `v19.0.0` release

---

go/vt/mysqlctl/builtinbackupengine.go
misc/git/hooks/golangci-lint

Close the reader and writer in a defer func. This ensures that the progress goroutine receives a message on the done channel and returns.
Note that the golangci-lint hook broke after the go1.22 upgrade, so I've updated it to the latest version.
Fixes #15409 

fix backup goroutine leak

---

go/vt/vtgate/semantics/analyzer.go
go/vt/vtgate/semantics/binder.go
go/vt/vtgate/semantics/dependencies.go
go/vt/vtgate/semantics/early_rewriter.go
go/vt/vtgate/semantics/errors.go
go/vt/vtgate/semantics/foreign_keys.go
go/vt/vtgate/semantics/foreign_keys_test.go

A few pure refactorings of the semantics code.
- Cleaned up how we create AmbiguousColumnErr
- Cleaned binder#up, extracting cases into methods
- Extracted aggregation tracking into it's own little struct
- Extracted the foreign key logic into it's own type and file

refactor: clean up semantics package

---

go/stats/opentsdb/backend_test.go
go/stats/opentsdb/datapoint_reader_test.go
go/stats/opentsdb/datapoint_test.go
go/stats/opentsdb/file_writer_test.go
go/stats/opentsdb/flags_test.go
go/stats/opentsdb/http_writer_test.go
go/stats/opentsdb/opentsdb_test.go

This PR adds required tests for `go/stats/opentsdb`
- Fixes part of #14931 

Add required tests for `go/stats/opentsdb`

---

go/vt/mysqlctl/mysqld.go
go/vt/mysqlctl/mysqld_test.go

This handles the case where mysqlctld might get assigned the same pid and improves the logging for when this case happens.
Part of addressing #14552

mysqlctl: Improve handling of the lock file

---

go/vt/mysqlctl/s3backupstorage/s3.go
go/vt/mysqlctl/s3backupstorage/s3_test.go

Not having a transport means we get crash here which we should avoid.
Fixes #15419

Ensure that WithParams keeps the transport

---

go.mod
go.sum

This PR bumps the `github.com/golang/protobuf` dependency from `v1.5.3` to `v1.5.4` to fix an incompatibility with the `google.golang.org/protobuf@v1.33.0` package.
Backporting this to `release-18.0` and `release-19.0` as we use `google.golang.org/protobuf@v1.33.0` on both branches.
- Fixes https://github.com/vitessio/vitess/issues/15425

bump `github.com/golang/protobuf` to `v1.5.4`

---

go/textutil/strings.go
go/textutil/strings_test.go
go/vt/binlog/binlogplayer/binlog_player.go
go/vt/binlog/binlogplayer/dbclient.go
go/vt/binlog/binlogplayer/mock_dbclient.go
go/vt/vtctl/workflow/server.go
go/vt/vttablet/tabletmanager/vreplication/engine.go
go/vt/vttablet/tabletmanager/vreplication/utils.go
go/vt/vttablet/tabletmanager/vreplication/utils_test.go
go/vt/vttablet/tabletmanager/vreplication/vcopier.go
go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go
go/vt/vttablet/tabletmanager/vreplication/vreplicator.go

In helping someone debug a VReplication failure, we had seen the following:
1. We failed to create a `_vt.vreplication_log` record and the apparent cause was that the message was too long
2. The truncated error message seen in the `_vt.vreplication` record showed the beginning of a `vcopier` bulk `INSERT` query that failed — truncated at 1000 bytes — but not the *reason why / error it generated*
3. This `_vt.vreplication_log` record generation failure may have caused problems in the workflow (e.g. if this happens after the point of no return in a `SwitchTraffic` then we'll be left in an inconsistent state that needs manual cleanup)
We address all of these issues with the following changes in this PR:
1. We truncate the message as needed before inserting it into the `_vt.vreplication_log` …

VReplication: improve reliability of log management

---

go/vt/graph/graph.go
go/vt/graph/graph_test.go
go/vt/schemadiff/diff_test.go
go/vt/schemadiff/errors.go
go/vt/schemadiff/schema.go
go/vt/schemadiff/schema_diff.go
go/vt/schemadiff/schema_diff_test.go
go/vt/schemadiff/schema_test.go
go/vt/schemadiff/types.go
go/vt/schemadiff/view_test.go

Addressing https://github.com/vitessio/vitess/issues/15430, in this PR `schemadiff` uses the same algorithm as Query-Serving to distinguish between valid and invalid foreign key cycles. `schemadiff` now allows table cycles as long as there's no column-reference cycle.
There's a few implications to this solution. Consider this valid foreign key cycle:
```sql
create table t11 (id int primary key, i int, constraint f11 foreign key (i) references t12 (id));
create table t12 (id int primary key, i int, constraint f12 foreign key (i) references t11 (id));
```
- There is technically no valid ordering to creating these two tables. In MySQL, this could only be achieved by setting `FOREIGN_KEY_CHECKS=0`. However, `schemadiff` is declarative. We introduce `DiffHints.ForeignKeyCheckStrategy` which …

`schemadiff`: support valid foreign key cycles

---

go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
go/test/endtoend/vtgate/schema/schema_test.go
go/vt/schemamanager/tablet_executor.go
go/vt/vttablet/onlineddl/executor.go
go/vt/vttablet/onlineddl/executor_test.go

Applying in both `direct` as well as online strategies, adding `--unsafe-allow-foreign-keys` DDL strategy flag implies a `SET FOREIGN_KEY_CHECKS=0` before executing the SQL.
With this, the user is allowed to create cyclic foreign key relationship, as in:
```sql
create table t11 (id int primary key, i int, constraint f11 foreign key (i) references t12 (id));
create table t12 (id int primary key, i int, constraint f12 foreign key (i) references t11 (id));
```
Note: this changes existing behavior. However, since existing behavior is **experimental**, as clearly indicated by `--unsafe-` prefix, we are good to make that change.
Addresses https://github.com/vitessio/vitess/issues/15430
-   [ ] …

DDL strategy flag `--unsafe-allow-foreign-keys` implies setting `FOREIGN_KEY_CHECKS=0`

---

go/hack/runtime.go
go/pools/smartconnpool/pool.go

This Pull Request removes a reference to runtime.fastrand in `go/hack/runtime.go` and replaces a call to `hack.FastRand()` with `math/rand/v2.Uint32N` in `go/pools/smartconnpool/pool.go`. These change aim to enhance code readability, performance, and reduce dependency on specific runtime implementations.
`math/rand/v2` employs [Lemire](https://lemire.me/blog/2016/06/27/a-fast-alternative-to-the-modulo-reduction/)'s algorithm in functions such as N, IntN, UintN, and others. Preliminary benchmark tests show a 40% improvement compared to `Int31n` in `v1` and a 75% improvement compared to `Int63n` in `v1`.
Furthermore, `math/rand/v2` default utilizes ChaCha8 for the global random number generator in each OS thread.
-   [x] "Backport to:" labels have been added if this change should be …

Fix: transition to `math/rand/v2` for Improved Performance and Code Clarity

---

go/test/endtoend/vtgate/queries/union/union_test.go
go/vt/vtgate/engine/concatenate.go

Race in concatenate spotted by @GuptaManan100. 
```
W0308 15:06:30.305024   15472 log.go:39] Failed to read in config : Config File "vtconfig" Not Found in "[/Users/manangupta/vitess/go/test/endtoend/vtgate/queries/union]". This is optional, and can be ignored if you are not using config files. For a detailed explanation, see https://github.com/vitessio/vitess/blob/main/doc/viper/viper.md#config-files.
panic: runtime error: index out of range [0] with length 0
goroutine 396 [running]:
vitess.io/vitess/go/vt/vtgate/engine.(*Concatenate).parallelStreamExec.func1(0x14000f29110, 0x30?)
vitess.io/vitess/go/vt/vtgate/engine/concatenate.go:266 +0x2a8
vitess.io/vitess/go/vt/vtgate/engine.(*Concatenate).parallelStreamExec.func2.1(0x14000f29110) …
```

engine:  fix race in concatenate

---

codecov.yml

The uncovered lines annotations added to the GitHub PR's `Files changed` view has proven to be a distraction which makes reviews more difficult.
This same general information — seeing what lines are NOT covered by unit tests — is available in two alternative locations:
- The GitHub Actions: https://docs.codecov.com/docs/github-checks#annotations-in-the-checks-tab
- The CodeCov UI when viewing the PR details using the link added to the CodeCov comment, e.g. https://app.codecov.io/gh/vitessio/vitess/pull/15440
Given both of these points, let's disable the GitHub annotations for now. We can always add them back in the future if we decide it's worth it. …

CI: Disable CodeCov GitHub Changed Files Annotations

---

go/cmd/vttablet/cli/cli.go
go/flags/endtoend/vttablet.txt

@deepthi noticed and pointed out that the docs for unmanaged tablets still listed `enable_replication_reporter` flag. The docs said that this flag would make vttablets repair its own replication, but this hasn't been true since v16.0.0. 
This PR fixes the docs and should be backported to all the releases that are affected by the same problem.

Fix docs for unmanaged tablets

---

go/cmd/vtctldclient/command/vreplication/reshard/create.go
go/vt/vtctl/workflow/server.go

This is a backport of #15353
I had to redo this because https://github.com/vitessio/vitess/pull/15363 refused to start CI workflows, apparently due to a Skip Label issue.

[release-18.0] VtctldClient Reshard: add e2e tests to confirm CLI options and fix discovered issues. (#15353)

---

go/mysql/icuregex/compiler.go
go/vt/vtctl/vtctl_test.go
go/vt/vttablet/tabletmanager/vreplication/vcopier.go
go/vt/vttablet/tabletserver/vstreamer/vstreamer.go

chore: remove repetitive words

---

go/test/endtoend/utils/utils.go
go/test/endtoend/vtgate/foreignkey/fk_test.go
go/test/endtoend/vtgate/foreignkey/stress/fk_stress_test.go
go/test/endtoend/vtgate/misc_test.go
go/test/endtoend/vtgate/queries/misc/main_test.go
go/test/endtoend/vtgate/queries/misc/misc_test.go
go/vt/vtgate/planbuilder/ddl.go
go/vt/vtgate/planbuilder/testdata/ddl_cases.json
go/vt/vtgate/planbuilder/testdata/ddl_cases_no_default_keyspace.json
go/vt/vtgate/planbuilder/testdata/view_cases.json
go/vt/vttablet/onlineddl/executor.go

When `vtgate` receives `SELECT *` queries and possesses authoritative column information for the tables in the query, it expands `*` into the actual column list, simplifying subsequent planning.
This column information is sourced from the schema tracker, which experiences a slight delay in reflecting schema changes in `vtgate`. Previously, following an `ALTER TABLE` that modified the column list, an immediate `ALTER VIEW` incorporating a `SELECT *` led `vtgate` to expand the columns using outdated information from the schema tracker, causing the resultant view to misrepresent the updated schema.
The remedy involves refraining from expanding columns in `CREATE/ALTER VIEW` statements, allowing MySQL to handle column expansion. The schema tracker then forwards the view definition to …

Fix view tracking on sharded keyspace

---

.github/workflows/code_freeze.yml
changelog/17.0/17.0.6/changelog.md
changelog/17.0/17.0.6/release_notes.md
changelog/17.0/README.md
examples/compose/docker-compose.beginners.yml
examples/compose/docker-compose.yml
examples/compose/vtcompose/docker-compose.test.yml
examples/compose/vtcompose/vtcompose.go
examples/operator/101_initial_cluster.yaml
examples/operator/201_customer_tablets.yaml
examples/operator/302_new_shards.yaml
examples/operator/306_down_shard_0.yaml
go/vt/servenv/version.go
java/client/pom.xml
java/example/pom.xml
java/grpc-client/pom.xml
java/jdbc/pom.xml
java/pom.xml

Includes the release notes and release commit for the `v17.0.6` release. Once this PR is merged, we will be able to tag `v17.0.6` on the merge commit.

[release-17.0] Release of `v17.0.6`

---

go/vt/servenv/version.go
java/client/pom.xml
java/example/pom.xml
java/grpc-client/pom.xml
java/jdbc/pom.xml
java/pom.xml

Includes the changes required to go back into dev mode (v17.0.7-SNAPSHOT) after the release of v17.0.6.

[release-17.0] Bump to `v17.0.7-SNAPSHOT` after the `v17.0.6` release

---

.github/workflows/code_freeze.yml
changelog/18.0/18.0.3/changelog.md
changelog/18.0/18.0.3/release_notes.md
changelog/18.0/README.md
examples/compose/docker-compose.beginners.yml
examples/compose/docker-compose.yml
examples/compose/vtcompose/docker-compose.test.yml
examples/compose/vtcompose/vtcompose.go
examples/operator/101_initial_cluster.yaml
examples/operator/201_customer_tablets.yaml
examples/operator/302_new_shards.yaml
examples/operator/306_down_shard_0.yaml
go/vt/servenv/version.go
java/client/pom.xml
java/example/pom.xml
java/grpc-client/pom.xml
java/jdbc/pom.xml
java/pom.xml

Includes the release notes and release commit for the `v18.0.3` release. Once this PR is merged, we will be able to tag `v18.0.3` on the merge commit.

[release-18.0] Release of `v18.0.3`

---

changelog/19.0/19.0.1/changelog.md
changelog/19.0/19.0.1/release_notes.md
changelog/19.0/README.md

This Pull Request copies the release notes found on `release-19.0` to keep release notes up-to-date after the `v19.0.1` release.

Copy `v19.0.1` release notes on `main`

---

changelog/18.0/18.0.3/changelog.md
changelog/18.0/18.0.3/release_notes.md
changelog/18.0/18.0.3/summary.md
changelog/18.0/README.md

This Pull Request copies the release notes found on `release-18.0` to keep release notes up-to-date after the `v18.0.3` release.

Copy `v18.0.3` release notes on `main`

---

go/vt/servenv/version.go
java/client/pom.xml
java/example/pom.xml
java/grpc-client/pom.xml
java/jdbc/pom.xml
java/pom.xml

Includes the changes required to go back into dev mode (v19.0.2-SNAPSHOT) after the release of v19.0.1.

[release-19.0] Bump to `v19.0.2-SNAPSHOT` after the `v19.0.1` release

---

go/vt/servenv/version.go
java/client/pom.xml
java/example/pom.xml
java/grpc-client/pom.xml
java/jdbc/pom.xml
java/pom.xml

Includes the changes required to go back into dev mode (v18.0.4-SNAPSHOT) after the release of v18.0.3.

[release-18.0] Bump to `v18.0.4-SNAPSHOT` after the `v18.0.3` release

---

go/vt/vttablet/tabletserver/vstreamer/engine.go
go/vt/vttablet/tabletserver/vstreamer/resultstreamer.go
go/vt/vttablet/tabletserver/vstreamer/rowstreamer.go
go/vt/vttablet/tabletserver/vstreamer/vstreamer.go

Currently we don't log when a rowstreamer, resultstreamer or vstreamer gets throttled. There are times when, due to configuration issues or a replication lag, these can get throttled permanently or for long. We do log this in the target's vreplication row and in debug/vars, but there are times when we only have access to the past logs. 
The throttler checks every 250ms, which is obviously too often to log. This PR uses the `ThrottledLogger` to log every five minutes to improve visibility.
-   [ ] Did the new or modified tests …

VStreamer: add throttled logs when row/result/vstreamers get throttled.

---

go/sqltypes/value.go
go/sqltypes/value_test.go
go/test/endtoend/onlineddl/vrepl_suite/testdata/enum-whitespace/alter
go/test/endtoend/onlineddl/vrepl_suite/testdata/enum-whitespace/create.sql
go/vt/schema/parser.go
go/vt/schema/parser_test.go
go/vt/vttablet/onlineddl/vrepl/columns_test.go

Addressing https://github.com/vitessio/vitess/issues/15492, this is an initial simple fix that allows whitespace in `enum` value. A more formal fix to follow, as this fix is incomplete in that it still requires more escaping.
A complete fix is likely to benefit from some `sqlparser` capabilities, though the use case goes beyond parsing `CREATE TABLE` statements and thus we might still take a lesser-than-`yacc` approach.
https://github.com/vitessio/vitess/issues/15492
-   [ ] Did the new or modified tests pass consistently locally …

Enum value parsing: do not parse by whitespace

---

go/vt/schemadiff/errors.go
go/vt/schemadiff/schema.go
go/vt/schemadiff/schema_test.go

Followup to https://github.com/vitessio/vitess/pull/15431 and https://github.com/vitessio/vitess/issues/15430, this PR removes altogether all loop/cycle analysis logic and removes `ForeignKeyLoopError`.
The rationale is that `schemadiff` should support anything `MySQL` supports. Some foreign key loop scenarios are unsupported by Query Serving, but the Query Serving logic is more intricate and should not be applied nor duplicated by `schemadiff`.
https://github.com/vitessio/vitess/issues/15430
-   [ ] Did the new or modified tests …

`schemadiff`: remove `ForeignKeyLoopError` and loop detection logic

---

go/vt/vtgate/planbuilder/operators/SQL_builder.go
go/vt/vtgate/planbuilder/testdata/filter_cases.json

This PR removes the keyspace information from the final query sent down to vttablet for execution as the database name and keyspace name can be different.
This was caused by to recent change in fixing the order by, group by and having clause column resolution logic to match the MySQL rules.
- Fixes https://github.com/vitessio/vitess/issues/15499
-   [X] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [X] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [X] Did the new or modified tests pass consistently locally and on CI?

fix: remove keyspace from column during query builder

---

go/vt/schemadiff/diff.go
go/vt/schemadiff/diff_test.go

This very simple PR adds a new utility function, that wraps a `sqlparser.Statement` with an appropriate `EntityDiff`. It is useful for unit tests that run outside the `schemadiff` package, and specifically for those that import `schemadiff` as a library.
- #10203 

schemadiff: add `EntityDiffByStatement`, a testing friendly utility

---

go/mysql/datetime/datetime_test.go
go/mysql/datetime/interval_test.go
go/mysql/datetime/mydate_test.go
go/mysql/datetime/parse_test.go
go/mysql/datetime/strftime_test.go

This PR adds missing tests for `go/mysql/datetime`
- #14931 

test: Add missing tests for `go/mysql/datetime`

---

go/vt/vterrors/code.go
go/vt/vtgate/engine/insert_common.go
go/vt/vtgate/engine/insert_test.go
go/vt/vtgate/executor_dml_test.go

This PR fails the `insert ignore` or `insert on duplicate key` query when the row cannot be mapped to a shard.
Earlier we used to ignore the row and continue but that confuses the users as not mapping a row to a shard is a non-ignorable error.
- Fixes https://github.com/vitessio/vitess/issues/7627

fail insert when primary vindex cannot be mapped to a shard

---

go/stats/counter_map.go
go/test/endtoend/tabletmanager/throttler_topo/throttler_test.go
go/timer/rate_limiter.go
go/timer/rate_limiter_test.go
go/vt/vttablet/tabletserver/throttle/check.go
go/vt/vttablet/tabletserver/throttle/throttler.go
go/vt/vttablet/tabletserver/throttle/throttler_test.go
go/vt/vttablet/tabletserver/throttle/throttlerapp/app.go

This PR addresses a starvation scenario in the tablet throttler. The scenario actually doesn't take place, due to an unintentional change. We fix the unintentional change & we fix the starvation scenario.
We also consolidate two different measurements of "last check" or "recent check":
1. `recentCheckValue`
2. `lastCheckTimeNano`
They are superfluous, because both serve to answer a similar question: "when was this throttler last checked?"
`lastCheckTimeNano` was updated in `check.go` at every check, and that's also where the aforementioned unintentional behavior takes place: this value should not be updated when the app is `"vitess"`. Right now in `main` this value does get updated when the app is `"vitess"`, which means the throttler's self-checks keep that value always recent. In turn, …

Tablet throttler: starvation fix and consolidation of logic.

---

go/cmd/vtctldclient/command/vreplication/vdiff/vdiff.go

Minor fixes to the `Example` attribute in the VDiff CLI commands which was missing the target keyspace value in some commands.
https://github.com/vitessio/vitess/issues/12152

VDiff CLI: add missing target keyspace in VDiff command examples

---

.github/workflows/codeql_analysis.yml

The v2 actions are deprecated, so this updates them. Marked for backporting do we don't get hit with the deprecation / breaking of this on older releases either.

Update to latest CodeQL

---

go/test/endtoend/vtgate/gen4/gen4_test.go
go/test/endtoend/vtgate/queries/misc/misc_test.go
go/vt/sqlparser/ast_funcs.go
go/vt/vtgate/executor_select_test.go
go/vt/vtgate/planbuilder/operator_transformers.go
go/vt/vtgate/planbuilder/operators/SQL_builder.go
go/vt/vtgate/planbuilder/operators/aggregation_pushing.go
go/vt/vtgate/planbuilder/operators/apply_join.go
go/vt/vtgate/planbuilder/operators/ast_to_op.go
go/vt/vtgate/planbuilder/operators/join.go
go/vt/vtgate/planbuilder/operators/join_merging.go
go/vt/vtgate/planbuilder/operators/projection_pushing.go
go/vt/vtgate/planbuilder/operators/query_planning.go
go/vt/vtgate/planbuilder/operators/route_planning.go
go/vt/vtgate/planbuilder/operators/subquery_planning.go
go/vt/vtgate/planbuilder/testdata/onecase.json
go/vt/vtgate/planbuilder/testdata/select_cases.json
go/vt/vtgate/semantics/early_rewriter.go

This PR adds the feature requested in https://github.com/vitessio/vitess/issues/15527.
After these changes, Vitess respects the order of tables specified in queries using straight joins.
- Fixes https://github.com/vitessio/vitess/issues/15527

Respect Straight Join in Vitess query planning

---

go/vt/vtctl/reparentutil/util.go
go/vt/vtctl/reparentutil/util_test.go

This PR fixes the issue described in https://github.com/vitessio/vitess/issues/15380. 
In `PlannedReparentShard` we now give a more descriptive error message telling exactly why the tablets cannot be promoted. Post these changes, the error message now looks like - 
```
cannot find a tablet to reparent to
zone1-0000000100 does not match the new primary alias provided
zone1-0000000101 does not match the new primary alias provided
zone2-0000000102 is not a replica
zone1-0000000103 is not in the same cell as the previous primary
zone1-0000000104 has 1m40s replication lag which is more than the tolerable amount
```
- Fixes https://github.com/vitessio/vitess/issues/15380
-   [x] If this change …

Fix error message for planned reparent shard

---

go/vt/mysqlctl/backup.go
go/vt/mysqlctl/fakemysqldaemon.go
go/vt/mysqlctl/mysql_daemon.go
go/vt/mysqlctl/mysqld.go
go/vt/vttablet/tabletmanager/tm_init.go
go/vt/vttablet/tabletmanager/tm_init_test.go

This PR fixes the race as described in #15537.
We now wait for the dba grants to have applied before we run any query that creates a connection with the said users.
- Fixes https://github.com/vitessio/vitess/issues/15537

Fix possible race in MySQL startup and vttablet in parallel

---

go/test/endtoend/vtgate/foreignkey/fk_fuzz_test.go
go/test/endtoend/vtgate/foreignkey/fk_test.go
go/vt/vtgate/planbuilder/operators/update.go
go/vt/vtgate/planbuilder/testdata/foreignkey_cases.json
go/vt/vtgate/semantics/semantic_state.go

This PR adds support for tables with foreign key in multi-table and multi-target update statements.
E.g.
`update user join music on user.foo = music.bar set user.id = 4, music.col = 5 where user.baz = 20`
- #12967 

Foreign Key: Add support for Multi Table and Multi Target Update Statement

---

go/test/endtoend/vreplication/vreplication_vtctldclient_cli_test.go
go/vt/vtctl/workflow/server.go

This is a follow-up to the work done in https://github.com/vitessio/vitess/pull/14424 where we moved reads against the vreplication table away from client side generated SQL to typed client-server RPCs (the server then builds the appropriate SELECT against the underlying table).
As part of that work, I errantly always included a workflow include filter in the new RPC request. The result of that is when you want to get/list all workflows, rather than just one, you get no results as the include workflow name filter is `''` — meaning only include workflows where the name is empty.
This PR corrects that and adds tests for `vtctldclient` based "workflow list" related commands.
- Fixes: https://github.com/vitessio/vitess/issues/15498
-   [x] "Backport to:" labels have been added if this change …

VReplication: Fix workflow filtering in GetWorkflows RPC

---

go/test/endtoend/vtgate/queries/reference/reference_test.go
go/vt/vtgate/planbuilder/operators/route.go
go/vt/vtgate/planbuilder/testdata/aggr_cases.json
go/vt/vtgate/planbuilder/testdata/from_cases.json
go/vt/vtgate/planbuilder/testdata/info_schema57_cases.json
go/vt/vtgate/planbuilder/testdata/info_schema80_cases.json
go/vt/vtgate/planbuilder/testdata/reference_cases.json
go/vt/vtgate/planbuilder/testdata/select_cases.json

This PR fixes the aliasing in the final query that we produce for routes that have derived tables. Specifically it fixes the bug specified in https://github.com/vitessio/vitess/issues/15549
- Fixes https://github.com/vitessio/vitess/issues/15549

Fix aliasing in routes that have a derived table

---

go/vt/vtgate/planbuilder/operators/apply_join.go
go/vt/vtgate/planbuilder/operators/expressions.go
go/vt/vtgate/planbuilder/testdata/select_cases.json

We recently did work to handle derived tables better, and in that change set, a bug snuck in when handling complex join predicates with `AND`s in them. When it was possible to merge everything back into a single route, we did not mark the argument form of the join predicates correctly because of the `AND` and it would show up in the final query sent down to the tablets.
Fixes #15547
Bug introduced in #14974 …

bugfix: handling of ANDed join predicates

---

Makefile

This adds an additional dependency to the `proto` Makefile target, `vtctldclient`, as it is dependent on proto changes — in addition to `vtadmin_web_proto_types` which was already there. This way we will regenerate the `vtctldclient` gRPC client code when the `vtctlservice.proto` is changed and the protobufs are subsequently rebuilt. This ensures that our proto dependent code stays in sync.
We will also then be checking for drift in the [`static_checks` workflow](https://github.com/vitessio/vitess/blob/main/.github/workflows/static_checks_etc.yml) as part of the [`check_make_proto` step](https://github.com/vitessio/vitess/blob/4f2456064a9773447c059193e485d2bf02cfab96/.github/workflows/static_checks_etc.yml#L204-L207).
- Prevents future issues like: …

Generate vtctldclient RPC client code from vtctlservice protobufs on make proto

---

go/vt/vitessdriver/rows.go
go/vt/vitessdriver/rows_test.go

This adds two interfaces, one for the type names and one for nullable to the Go SQL driver for Vitess. This is missing and means this type information can't be easily retrieved from result sets.
Fixes #15568 

Add types to Go SQL driver

---

go/vt/vttablet/tabletserver/throttle/check.go
go/vt/vttablet/tabletserver/throttle/throttler.go

A minor change, creating some dedicated `stats` variables instead of creating the stats on the fly (`stats.NewCounter` vs `start.GetOrNewCounter`) where possible. Some metrics still created dynamically as their name is dynamic.
No issue. Just general cleanup/refactor.

Throttler: refactor stats variables

---

go/vt/vtgate/executor.go

This PR fixes the issue described in https://github.com/vitessio/vitess/issues/15423. 
We now create a throttled logger and use that to log the warnings for exceeding memory row count. 
- Fixes https://github.com/vitessio/vitess/issues/15423

Use a throttled logger for exceeded memory warnings

---

go/vt/vterrors/code.go
go/vt/vtgate/engine/insert_common.go
go/vt/vtgate/engine/insert_test.go
go/vt/vtgate/executor_dml_test.go

[release-19.0] Fail insert when primary vindex cannot be mapped to a shard (#15500)

---

changelog/20.0/20.0.0/summary.md
go/cmd/mysqlctld/cli/mysqlctld.go
go/cmd/vtbackup/cli/vtbackup.go
go/cmd/vtcombo/cli/main.go
go/flags/endtoend/mysqlctld.txt
go/vt/mysqlctl/grpcmysqlctlserver/server.go
go/vt/mysqlctl/mycnf.go
go/vt/servenv/run.go
go/vt/servenv/servenv.go
go/vt/vttablet/tabletmanager/tm_init.go

Until now we've had the same timeouts for shutdown etc. across the different binaries. This doesn't provide the necessary flexibility though, since for example `mysqlctld` will need longer timeouts.
This is because it needs to shut down MySQL and we need it to honor the MySQL shutdown timeout as well. This means this can take significantly longer to ensure the shutdown is clean.
It's necessary to do this, to ensure things like being able to upgrade MySQL since that depends on clean shutdowns.
Fixes #15577
-   [x] Did the new or …

mysqlctld: setup a different default for onterm_timeout

---

go/vt/vtgate/scatter_conn.go
go/vt/vtgate/scatter_conn_test.go
go/vt/vttablet/sandboxconn/sandboxconn.go

If something goes horribly wrong during query execution, vtgate will close the connection to the user, but stay up and serving requests. Except if the panic happens during parallel execution - in these cases, vtgate would just crash and the process dies.
This PR changes this so that we catch the panics during the parallel execution, and rethrows them in the main thread, so that we handle all panics the same way.
This is related to #15434, but does not fix it.
-   [x] Did the new or modified tests pass consistently locally and on …

Handle panics during parallel execution

---

go/test/endtoend/utils/cmp.go
go/test/endtoend/utils/mysql.go
go/test/endtoend/utils/utils.go

We don't want to be tied down to using the testing package when using `MySQLCompare`, here we introduce an interface to make it possible to have other implementations.

chore: use interface instead of struct for tests

---

go/cmd/vtctldclient/command/vreplication/common/switchtraffic.go
go/streamlog/streamlog_test.go
go/test/endtoend/cluster/vttablet_process.go
go/test/endtoend/vreplication/fk_test.go
go/test/endtoend/vreplication/helper_test.go
go/test/endtoend/vreplication/movetables_buffering_test.go
go/test/endtoend/vreplication/partial_movetables_seq_test.go
go/test/endtoend/vreplication/resharding_workflows_v2_test.go
go/test/endtoend/vreplication/wrappers_test.go
go/vt/vtctl/workflow/server.go
go/vt/vtctl/workflow/traffic_switcher.go
go/vt/vttablet/tabletmanager/rpc_vreplication.go
test/config.json

This work was originally done via https://github.com/vitessio/vitess/pull/15536 as I only planned to do that work in the `vtctldclient` implementation and thus I needed to use vtctldclient in order to test the fix. In doing so, I saw other test failures when using the `vtctldclient` implementation and I fixed those there as well.
BUT, because I did not plan to backport that PR and it still remains to be seen how involved/intrusive a full fix may be and also when it will be ready, I'm moving the work not specifically related to that issue here so it can be pushed ASAP and backported to v18 (where the vreplication commands were first added to `vtctldclient`). 
I would like to backport this to v18 so that we have the traffic switching fixes and so that we have better test coverage now that …

VReplication: Move the Reshard v2 workflow to vtctldclient

---

go/test/endtoend/vtorc/api/api_test.go
go/vt/external/golib/sqlutils/sqlutils.go
go/vt/vtorc/db/generate_base.go
go/vt/vtorc/inst/instance_dao.go
go/vt/vtorc/inst/instance_dao_test.go
go/vt/vtorc/server/api.go

This PR adds a new API endpoint for VTOrc, that allows the users to see the current database state of the instance. This is useful for debugging.
The new endpoint is `/api/database-state` and it looks like - 
- Fixes https://github.com/vitessio/vitess/issues/15484
-   [x] Documentation was added or is not required - https://github.com/vitessio/website/pull/1705

Add api end point to print the current database state in VTOrc

---

go/test/endtoend/vtgate/foreignkey/fk_fuzz_test.go
go/test/endtoend/vtgate/foreignkey/fk_test.go
go/test/endtoend/vtgate/foreignkey/main_test.go
go/test/endtoend/vtgate/foreignkey/shard_scoped_vschema.json
go/test/endtoend/vtgate/foreignkey/utils_test.go

This PR adds testing for shard-scoped foreign keys. While making these changes we realised that for shard-scoped foreign keys, the foreign key columns have to be part of the sharding key, which automatically fails all the updates on those columns! 😿 
So, we can currently only support `DELETE RESTRICT` and `DELETE CASCADE` style operations. This PR adds the infra for adding the tests for all the scenarios but skips all the ones that don't work for now. For the same reason, I haven't enabled fuzzer tests either for shard-scoped foreign keys because of the very limited number of queries that actually work.
Here are the tests that work as intended - 
- #12967  …

Add testing for shard scoped foreign keys

---

go/test/endtoend/vtgate/queries/benchmark/benchmark_test.go
go/test/endtoend/vtgate/queries/dml/dml_test.go
go/vt/vtgate/autocommit_test.go
go/vt/vtgate/engine/delete.go
go/vt/vtgate/engine/delete_test.go
go/vt/vtgate/engine/dml.go
go/vt/vtgate/engine/dml_with_input_test.go
go/vt/vtgate/engine/update.go
go/vt/vtgate/engine/update_test.go
go/vt/vtgate/executor_dml_test.go
go/vt/vtgate/planbuilder/operator_transformers.go
go/vt/vtgate/planbuilder/testdata/dml_cases.json

When I run a SELECT statement using an IN clause with the Vindexes, the query is correctly split according to the corresponding values in the IN list. This ensures that each shard is queried separately, which is the expected behavior for optimized shard querying.
However, when I perform an UPDATE/DELETE statement with an IN clause on the Vindexes, the SQL is not rewritten in the same manner. Instead, the query is sent directly to the shard without being split based on the IN clause values.
I hope to have consistent behavior with SELECT when processing UPDATE/DELETE statements with an IN clause on the Vindexes.
I would like the following UPDATE statement:
```sql
UPDATE test_vindex_signed_int SET id = id + 100 WHERE v_key IN (1, 100)
```
to be rewritten into separate statements, one for …

Optimize with IN Clause for UPDATE/DELETE Statements on Vindexes

---

go/mysql/datetime/datetime.go
go/mysql/datetime/datetime_test.go
go/vt/vtgate/evalengine/cached_size.go
go/vt/vtgate/evalengine/compiler_asm.go
go/vt/vtgate/evalengine/fn_time.go
go/vt/vtgate/evalengine/testcases/cases.go
go/vt/vtgate/evalengine/translate_builtin.go

This PR adds implementation of [TO_SECONDS](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_to-seconds) func in evalengine.
- #9647

evalengine: Implement `TO_SECONDS`

---

go/vt/vtgate/evalengine/cached_size.go
go/vt/vtgate/evalengine/compiler_asm.go
go/vt/vtgate/evalengine/fn_string.go
go/vt/vtgate/evalengine/testcases/cases.go
go/vt/vtgate/evalengine/testcases/inputs.go
go/vt/vtgate/evalengine/translate_builtin.go

This PR adds implementation of [`ELT`](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_elt) and [`FIELD`](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_field) functions in evalengine.
Fixes part of #9647 

evalEngine: Implement ELT and FIELD

---

go/vt/vtgate/evalengine/compiler_test.go
go/vt/vtgate/evalengine/fn_time.go

We were failing to pass down the precision correctly in the compiler which would lead to a panic because we'd see an unexpected type downstream.
Marked for backporting as this triggers an internal panic inside `vtgate`. 
Fixes #15610 

evalengine: Ensure to pass down the precision

---

go/vt/vtgate/evalengine/compiler_test.go
go/vt/vtgate/evalengine/fn_info.go
go/vt/vtgate/evalengine/fn_time.go

This fixes a number of other cases where we didn't propagate the type sizing properly, mostly for datetime related functions. Also fixes some plain wrong types for other functions.
Also backported for v19 since it suffers from similar potential panics as #15610 
Fixes #15613 

evalengine: Fix additional time type handling

---

go/vt/schemamanager/local_controller_test.go
go/vt/schemamanager/plain_controller_test.go
go/vt/schemamanager/schemamanager_test.go
go/vt/schemamanager/tablet_executor_test.go
go/vt/schemamanager/ui_controller_test.go

This PR replaces some `t.fatalf` instances with testify's `require` in `go/vt/schemamanager`
- #15182
- #14931 

test: Replace `t.fatalf` with testify `require` in `go/vt/schemamanager`

---

examples/common/scripts/vtadmin-up.sh
web/vtadmin/build.sh
web/vtadmin/src/components/routes/Vtctlds.tsx

This PR:
- Removes the link to vtctld web, since we deprecated it in v17
- Improves `vtadmin-up.sh` by 1) outputting the variables that are being set and 2) shortening the wait time for cluster discovery
- Improves `web/vtadmin/build.sh` by 1) outputting the variables set and 2) when no hostname is set, uses the local machine's hostname
The last bullet point made it so that I could run `./101_initial_clusters.sh` without any extra steps, and get vtadmin-web/vtadmin-api working:
- https://github.com/vitessio/vitess/issues/15597
- https://github.com/vitessio/vitess/issues/15587 …

[VTAdmin] Remove vtctld web link, improve local example

---

go/vt/vtgate/vindexes/vschema.go
go/vt/vtgate/vindexes/vschema_test.go

We were not adding a few fields for the column type information in the vschema, which made it hard to use them in other parts of our code base.

Add more fields to the marshal output of column

---

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
go/vt/vtgate/planbuilder/operators/projection.go
go/vt/vtgate/planbuilder/operators/query_planning.go
go/vt/vtgate/planbuilder/testdata/select_cases.json

This PR fixes the average planning bug found in https://github.com/vitessio/vitess/issues/15625. The issue was with the simple projector, wherein we were creating a new incorrect field instead of reusing an already existing one.
- Fixes https://github.com/vitessio/vitess/issues/15625

Fix AVG() sharded planning 

---

.github/workflows/docker_build_images.yml

I broke the action `docker_build_images` in https://github.com/vitessio/vitess/pull/15620 as seen in https://github.com/vitessio/vitess/actions/runs/8546027282. This fixes it.

Fix `docker_build_images` CI workflow

---

.github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml

Makes a similar change done in the multi-tenant PR at https://github.com/vitessio/vitess/pull/15503/files#diff-79c61525895b1e17d0cc49054a0d19f9264073042bbe75a8f5997092f02a3c92R203-R210
We need to use the same version of vtctld as vttablets.
Otherwise this workflow fails since it cannot insert into `_vt.vreplication` which now has a json column for which we cannot specify a default at the table schema level.
This is being done directly on v19 since the versions of vttablet/vtctlds  of upgrade/downgrade are reversed as compared to main (v20) and v19.
-   [ ] Tests were added …

CI: Upgrade/Downgrade use N+1 version of vtctld when testing with N+1 of vttablet

---

.github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml
.github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
.github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
.github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml
.github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml
.github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml

This is a follow up of https://github.com/vitessio/vitess/pull/15639

[release-17.0] Upgrade go version in upgrade tests to `go1.21.9`

---

go.mod

Followup to https://github.com/vitessio/vitess/pull/15639, we were missing the updated go version in `go.mod`.
#15639 

[release-18.0] Update go.mod go version to 1.21.9

---

go.mod
go.sum

Followup to https://github.com/vitessio/vitess/pull/15646 and https://github.com/vitessio/vitess/pull/15639
We update `golang.org/x/net` to fix a known vulnerability issue.

[release-18.0] Updated `golang.org/x/net`

---

go/vt/servenv/version.go
java/client/pom.xml
java/example/pom.xml
java/grpc-client/pom.xml
java/jdbc/pom.xml
java/pom.xml

Includes the changes required to go back into dev mode (v19.0.3-SNAPSHOT) after the release of v19.0.2.

[release-19.0] Bump to `v19.0.3-SNAPSHOT` after the `v19.0.2` release

---

go.mod
go.sum

Updates the dependency for golang.org/x/net to the latest to avoid a security issue in version 0.22.0
https://github.com/vitessio/vitess/pull/15649

Update dependencies for golang.org/x/net to latest

---

changelog/18.0/18.0.4/changelog.md
changelog/18.0/18.0.4/release_notes.md
changelog/18.0/README.md

This Pull Request copies the release notes found on `release-18.0` to keep release notes up-to-date after the `v18.0.4` release.

Copy `v18.0.4` release notes on `main`

---

changelog/19.0/19.0.3/changelog.md
changelog/19.0/19.0.3/release_notes.md
changelog/19.0/README.md

This Pull Request copies the release notes found on `release-19.0` to keep release notes up-to-date after the `v19.0.3` release.

Copy `v19.0.3` release notes on `main`

---

go/vt/servenv/version.go
java/client/pom.xml
java/example/pom.xml
java/grpc-client/pom.xml
java/jdbc/pom.xml
java/pom.xml

Includes the changes required to go back into dev mode (v18.0.5-SNAPSHOT) after the release of v18.0.4.

[release-18.0] Bump to `v18.0.5-SNAPSHOT` after the `v18.0.4` release

---

go/test/endtoend/vreplication/fk_test.go
go/test/endtoend/vreplication/movetables_buffering_test.go
go/test/endtoend/vreplication/partial_movetables_test.go
go/test/endtoend/vreplication/resharding_workflows_v2_test.go
go/test/endtoend/vreplication/wrappers_test.go

After https://github.com/vitessio/vitess/pull/15579 the tests that used functions in the `resharding_workflows_v2_test` file (primarily `tstWorkflowExec()`) and supported two client flavors — `vtctl[client]` and `vtctld[client]`, doing both or choosing one randomly — were really using `vtctldclient` in both cases.
And when the flavor was `vtctl[client]` — both before AND after #15579 — some of the tests failed every time as they did not properly set the `currentWorkflowType` to `MoveTables` so the command did a `Reshard` instead as that's the default. For example, I noticed that the `TestFKWorkflow` test (which is executed in the `vreplication_cellalias` workflow) failed every time that the flavor was `vtctl` (the flavor being chosen randomly in that test).  This was papered over by our …

VReplication: Get workflowFlavorVtctl endtoend testing working properly again

---

config/mycnf/mysql80.cnf

This PR adds a default value of `replica_net_timeout`. This allows failovers to be detected faster.
- Fixes https://github.com/vitessio/vitess/issues/15664

Add a default for `replica_net_timeout`

---

go/vt/vtgate/planbuilder/operators/SQL_builder.go
go/vt/vtgate/planbuilder/testdata/from_cases.json

When the planner is able to push down a derived table and everything that goes with it under a route, we were not copying over whether the SELECT was distinct or not.
Fixes #13578

fix: don't forget DISTINCT for derived tables

---

go/test/endtoend/cluster/vtctldclient_process.go
go/test/endtoend/vreplication/helper_test.go
go/test/endtoend/vreplication/vdiff_helper_test.go
go/test/endtoend/vreplication/vdiff_online_ddl_test.go
go/vt/vtctl/workflow/server.go
go/vt/vttablet/tabletmanager/vdiff/workflow_differ.go
test/config.json

Currently VDiff errors out if they are run for a vreplication workflow initiated by OnlineDDL. This PR adds support for that.
Note that only OnlineDDLs created as `vitess` with the `--postpone-completions` option qualify to be validated by a VDiff. This is because the VReplication workflow needs to be in a Running state. VDiff needs to synchronize source and target streams so that it can expect to find identical snapshots on the source and the target. For this it will Stop/Start workflows.
If a VDiff is already complete then the vreplication workflow is not expected to restart since the cutover has already happened.  
- Fixes: https://github.com/vitessio/vitess/issues/12965
-   [x] If …

VDiff/OnlineDDL: add support for running VDiffs for OnlineDDL migrations

---

go/vt/discovery/topology_watcher.go
go/vt/discovery/topology_watcher_test.go
go/vt/topo/keyspace_external_test.go
go/vt/topo/memorytopo/directory.go
go/vt/topo/memorytopo/election.go
go/vt/topo/memorytopo/file.go
go/vt/topo/memorytopo/lock.go
go/vt/topo/memorytopo/memorytopo.go
go/vt/topo/memorytopo/watch.go
go/vt/topo/tablet.go
go/vt/topo/tablet_test.go

This PR fixes two bugs that can appear when using Zookeeper as the topo server
1. topo.Server GetTabletsIndividuallyByCell will return an empty slice on a partial result error from GetTabletMap, which causes TopologyWatcher to remove all tablets from the healthcheck.
2. After fixing the first bug, TopologyWatcher will still remove any tablets not present in the partial results list.
In order to test these fixes this PR also introduces a more flexible way to return fake errors from memorytopo.
Since the impact of this bug could be pretty disruptive, I think it should be backported to v19.
Fixes https://github.com/vitessio/vitess/issues/15632
-   [x] If this change is to be back-ported to …

discovery: Fix tablets removed from healthcheck when topo server GetTablet call fails

---

config/mycnf/mysql80.cnf

We still want to be able to work with older MySQL 8.0 releases that don't have the new names yet, so keep using the old one for now.
This was added as setting in https://github.com/vitessio/vitess/pull/15663. Part of https://github.com/vitessio/vitess/issues/15664

Use the legacy name for timeouts

---

.github/workflows/unit_race.yml
tools/unit_test_race.sh

It was noticed that unit_race CI action wasn't reporting its results to launchable. This PR aims to fix this oversight.

Run launchable in unit race

---

.github/workflows/upgrade_downgrade_test_query_serving_queries.yml
.github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
.github/workflows/upgrade_downgrade_test_query_serving_schema.yml
.github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml

It was noticed that the upgarde downgrade tests for query serving were running the tests for the case when both vtgate and vttablet were the latest version. This is redundant since this is already tested in other cluster tests. This removes this redundancy and makes the upgrade downgrade tests faster as a consequence.
The runtime changes from `32m53s` to `22m37s`. This corresponds to a 31% faster execution. …

Make upgrade downgrade tests faster by removing redundancy

---

go/cmd/vttestserver/cli/main.go
go/cmd/vttestserver/cli/main_test.go
go/flags/endtoend/vttestserver.txt
go/vt/vttest/local_cluster.go
go/vt/vttest/vtprocess.go

This PR adds the flag `no_scatter` to `vttestserver`, which will cause scatter queries to automatically fail when set. This behavior is useful for detecting / preventing scatter queries early in a test environment.
Note that this flag already exists in [vtcombo](https://github.com/aparajon/vitess/blob/b3d45fdb5be936f3815ff8e3efcb3af4c1afe06d/go/flags/endtoend/vtcombo.txt#L252).
Fixes https://github.com/vitessio/vitess/issues/15683
-   [x] Documentation was …

Add `no_scatter` flag to vttestserver

---

go/vt/vttablet/tabletserver/vstreamer/snapshot_conn.go
go/vt/vttablet/tabletserver/vstreamer/snapshot_conn_test.go

On a high write qps cluster, while copying a huge table, we noticed that the copy phase of a MoveTables workflow was significantly increasing replica lag. The workflow was streaming from replicas. Reducing the copy phase duration to 10 minutes did not help.
While auditing `INNODB_TRX` It was noticed that `trx_is_read_only` is set to `0`. We expected it to be `1` since we do this
```
if _, err := conn.ExecuteFetch("set transaction isolation level repeatable read", 1, false); err != nil {
return "", err
}
if _, err := conn.ExecuteFetch("start transaction with consistent snapshot", 1, false); err != nil {
return "", err
}
```
This PR modifies the second query to explicitly set `read only`: like `start transaction with consistent snapshot, read only`. A unit test confirms that this works. …

VReplication Workflows (RowStreamer): explicitly set read only when creating snapshots in the copy phase

---

go/mysql/replication/mysql56_gtid.go
go/mysql/replication/mysql56_gtid_test.go
go/test/endtoend/backup/vtctlbackup/backup_utils.go
go/test/endtoend/backup/vtctlbackup/pitr_test_framework.go
go/test/endtoend/vtgate/foreignkey/stress/fk_stress_test.go
go/vt/mysqlctl/builtinbackupengine.go
go/vt/vttablet/tabletmanager/restore.go

Incremental backup and point-in-time recoveries assume a MySQL 5.6 flavor GTID. To that effect, both now:
- Do not require the `"MySQL56/"` prefix in position argument
- Validate that with or without said `"MySQL56/"` prefix, the positiion must be in MySQL 5.6 GTID format
This PR consolidated the logic into a new `DecodePositionMySQL56()` function in `go/mysql/replication`. We retire  `DecodePositionDefaultFlavor()` though we still keep the function as it may yet prove useful.
Added unit tests, and updated endtoend tests to use positions with/out  `"MySQL56/"` prefix.
- Fixes https://github.com/vitessio/vitess/issues/15592
- Followup to https://github.com/vitessio/vitess/pull/13474
-   [ …

Point in time recovery and restore: assume (and validate) MySQL56 flavor in position arguments

---

go/vt/schemadiff/errors.go
go/vt/schemadiff/table.go
go/vt/schemadiff/table_test.go
go/vt/schemadiff/types.go

Some diffs between two tables, cannot be applied in MySQL in a single `ALTER TABLE` statement. Examples:
- Adding a column and dropping a partition.
- Adding and dropping a partition.
- Some other partitioning change scenarios.
- Adding two `FULLTEXT` keys.
These are MySQL limitations. Specifically for `FULLTEXT`, `schemadiff` offers a flag to tolerate multiple changes (and `vitess`  Online DDL can then work with that).
This PR adds a more general diff hint: whether to at all allow multiple changes per table (default: allow, for backwards compatibility), or to outright reject such diff.
This can only ever apply to `ALTER TABLE` as no other supported change has this problem (e.g. `ALTER VIEW` is just one sweep atomic change anyway ; `DROP TABLE` obviously has nothing to apply twice, etc.) …

`schemadiff`: `SubsequentDiffStrategy`: allow/reject multiple changes on same entity

---

go/test/endtoend/vtgate/queries/dml/insert_test.go
go/test/endtoend/vtgate/queries/dml/sharded_schema.sql
go/test/endtoend/vtgate/queries/dml/unsharded_schema.sql
go/test/endtoend/vtgate/queries/dml/vschema.json

TODO
Fixes https://github.com/vitessio/vitess/issues/15696

Match MySQL's `LAST_INSERT_ID` behaviour

---

go/test/endtoend/vreplication/helper_test.go
go/test/endtoend/vreplication/vdiff_online_ddl_test.go

We were checking for the Online DDL to reach `OnlineDDLStatusRunning` before checking for the status of the underlying VReplication workflow. However in  `executor.ExecuteWithVReplication()`  `OnlineDDLStatusRunning`  is set before the VReplication records are created, resulting in flakiness in subsequent checks where we wait for the workflow to reach `Running` status.
This PR adds another wait for the VReplication Workflow to be created.
-   [ ] …

Flaky test TestOnlineDDLVDiff: add additional check for vreplication workflow to exist

---

go/test/endtoend/vtgate/transaction/restart/main_test.go
go/vt/vttablet/tabletserver/livequeryz_test.go
go/vt/vttablet/tabletserver/query_executor.go
go/vt/vttablet/tabletserver/query_list.go
go/vt/vttablet/tabletserver/query_list_test.go
go/vt/vttablet/tabletserver/state_manager.go
go/vt/vttablet/tabletserver/state_manager_test.go

This PR fixes the bug found in https://github.com/vitessio/vitess/issues/15685. The problem was that we were adding to the queryDetails even after unserveCommon had been called and after the kill had happened. This is troublesome and has been fixed by preventing addition to the query details right after `unserveCommon` starts.
- Fixes https://github.com/vitessio/vitess/issues/15685

Prevent adding to query details after unserve common has started

---

go/vt/throttler/aggregated_interval_history_test.go
go/vt/throttler/interval_history_test.go
go/vt/throttler/manager_test.go
go/vt/throttler/memory_test.go
go/vt/throttler/replication_lag_cache_test.go
go/vt/throttler/result_test.go
go/vt/throttler/thread_throttler_test.go
go/vt/throttler/throttler_test.go
go/vt/throttler/throttlerlogz_test.go
go/vt/throttler/throttlerz_test.go

This PR replaces some t.fatalf/errorf instances with testify's require in `go/vt/throttler`
- #15182
- #14931 

test: Use testify require/assert instead of t.Fatal/Error in `go/vt/throttler`

---

go/vt/schemadiff/capability.go
go/vt/schemadiff/capability_test.go

Context: https://github.com/vitessio/vitess/issues/14877
In evaluating whether a `DROP COLUMN` is eligible to `ALGORITHM=INSTANT`, we must make sure that the column is not covered by any existing index. If it is, then dropping the column implies modifying the index, which is a non-`INSTANT` operation in MySQL.
- https://github.com/vitessio/vitess/issues/14877
- https://github.com/vitessio/vitess/pull/14878
- https://github.com/vitessio/vitess/pull/14883
- …

`schemadiff`: `DROP COLUMN` not eligible for `INSTANT` algorithm if covered by an index

---

doc/vtadmin/clusters.yaml
go/vt/vtadmin/cache/cache.go
go/vt/vtadmin/cache/cache_test.go
go/vt/vtadmin/cluster/cluster.go

Currently, when a user passes any schema cache flags, but does not pass `backfill-queue-size`, vtadmin-api crashes because `backfill-queue-size` is defaulted to `-1` and crashes with:
```
panic: makechan: size out of range
goroutine 1 [running]:
vitess.io/vitess/go/vt/vtadmin/cache.New[...](0xc000375570, {0xdf8475800, 0xffffffffffffffff, 0x5f5e100, 0xffffffffffffffff, 0xffffffffffffffff, 0x2faf080})
vitess.io/vitess/go/vt/vtadmin/cache/cache.go:131 +0x20d
```
at https://github.com/vitessio/vitess/blob/main/go/vt/vtadmin/cache/cache.go#L131
This PR makes it so that `backfill-queue-size` is defaulted to 0 if the value is negative. It also adds the `schema-cache-*` flags to the example `cluster.yml`, and adds some logs.
A subsequent PR will make it so that the debug endpoint returns the …

[VTAdmin API] Fix schema cache flag, add documentation

---

config/init_db.sql
examples/compose/config/init_db.sql
examples/compose/external_db/mysql/grant.sh
examples/compose/vttablet-up.sh
examples/operator/101_initial_cluster.yaml
go/test/endtoend/cluster/cluster_util.go
go/test/endtoend/vreplication/testdata/config/init_testserver_db.sql
go/vt/vttablet/tabletmanager/tm_init_test.go
vitess-mixin/e2e/config/init_db.sql
vitess-mixin/e2e/external_db/mysql/grant.sh
vitess-mixin/e2e/vttablet-up.sh

We can remove usage of `FLUSH PRIVILEGES` in many places by making sure we only use the correct SQL functionality for managing users. If we don't modify the `mysql.user` table directly, we don't need to use `FLUSH PRIVILEGES`.

Cleanup usage of FLUSH PRIVILEGES

---

go/test/endtoend/utils/mysql_test.go
go/vt/mysqlctl/fakemysqldaemon.go
go/vt/mysqlctl/mysql_daemon.go
go/vt/mysqlctl/mysqld.go
go/vt/mysqlctl/replication.go
go/vt/mysqlctl/replication_test.go
go/vt/vttablet/tabletmanager/tm_init.go

This avoids the problem where the connection pool is poisoned when we check for the MySQL port, by avoiding to use the pool in the first place. We only ever run this once at startup, so we can create a new connection here and then dispose of it once we've retrieved the port.
That way we know the connection pool is still clean and doesn't have any problems.
Fixes #15730

Fix the race condition during vttablet startup

---

go/test/endtoend/utils/utils.go
go/test/endtoend/vtgate/queries/tpch/tpch_test.go
go/vt/vtgate/engine/scalar_aggregation.go

When using the aggregation engine, we need to have full field information from the inputs to calculate things correctly.
This PR makes sure that the aggregator always asks for fields. When it was running inside of some other operators that don't need fields, we failed to ask for the fields, and this could lead to panics.
- Fixes https://github.com/vitessio/vitess/issues/15729

Fix panic in aggregation

---

go/vt/vtgate/vtgate.go

It fixes the flag field for udf tracking in vtgate.

fix: use correct flag field for udf tracking

---

go/vt/vttablet/grpctmclient/client.go
go/vt/vttablet/grpctmclient/client_test.go

This PR fixes a segmentation fault that is caused by calling the invalidator function gotten from the dedicated connection pooling more than once. The second time around, there is no map entry, so we end up dereferencing a nil pointer.
The two Vitess components that were affected by this (as they are the only dedicated connection pool users today)  are:
- [VTOrc](https://vitess.io/docs/reference/vtorc/)
- [Tablet throttler](https://vitess.io/docs/reference/features/tablet-throttler/)
The only Vitess release affected by this was [v19.0.3](https://github.com/vitessio/vitess/releases/tag/v19.0.3).
- Fixes https://github.com/vitessio/vitess/issues/15752 …

GRPC: Address potential segfault in dedicated connection pooling

---

go/flags/endtoend/vtbackup.txt
go/flags/endtoend/vtcombo.txt
go/flags/endtoend/vtctld.txt
go/flags/endtoend/vtorc.txt
go/flags/endtoend/vttablet.txt
go/flags/endtoend/vttestserver.txt
go/vt/vtorc/inst/instance_dao.go
go/vt/vtorc/inst/tablet_dao.go
go/vt/vtorc/logic/tablet_discovery.go
go/vt/vtorc/logic/topology_recovery.go
go/vt/vttablet/grpctmclient/client.go

This is a backport of https://github.com/vitessio/vitess/pull/15356
As described in https://github.com/vitessio/vitess/issues/15726#issuecomment-2065669975, this backport is required to fix the bug https://github.com/vitessio/vitess/issues/15726.
- Fixes https://github.com/vitessio/vitess/issues/15726

[release-19.0]: VTOrc optimize TMC usage (#15356)

---

go/vt/vtgate/schema/tracker.go
go/vt/vtgate/vschema_manager.go
go/vt/vtgate/vschema_manager_test.go

This PR adds UDFs to the VSchema on receiving an update from the vttablet.
- https://github.com/vitessio/vitess/issues/15711

add udfs to vschema on update

---

go/vt/vtgate/vstream_manager.go
go/vt/vtgate/vstream_manager_test.go
go/vt/vttablet/sandboxconn/sandboxconn.go

The `vtgate` `VStreamManager` — which manages [`VStream API`](https://vitess.io/docs/reference/vreplication/vstream/) requests made against a `vtgate` — watches a healthcheck stream from the tablets that it's streaming data from for each high level vstream. When processing the source tablet's healthcheck responses, however, it was not taking replication lag into account as it should. See [the issue](https://github.com/vitessio/vitess/issues/15754) for more details.
This PR corrects that by checking the replication lag reported in the healthcheck response against the vtgate's live value tied to the `--discovery_low_replication_lag` flag (but this is also a dynamic variable).
I think that we should backport this all the way to 17.0 as it's a small and straightforward fix for a somewhat …

VReplication: Take replication lag into account in VStreamManager healthcheck result processing

---

.github/workflows/update_golang_dependencies.yml
.github/workflows/update_golang_version.yml

This PR changes the automatic golang deps update and version upgrade to tag the `@vitessio/release` team in the reviewers list and in the PRs' descriptions.
To do this, I have generated a PAT for the @vitess-bot account and used it in the create-pull-request action. Here is what a PR for the update dependencies looks like now: https://github.com/vitessio/vitess/pull/15743

Assign and tag the release team for go update/upgrade auto PRs

---

changelog/20.0/20.0.0/summary.md
go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
go/vt/vttablet/endtoend/config_test.go
go/vt/vttablet/endtoend/transaction_test.go
go/vt/vttablet/onlineddl/executor.go
go/vt/vttablet/tabletserver/connpool/dbconn.go
go/vt/vttablet/tabletserver/connpool/dbconn_test.go
go/vt/vttablet/tabletserver/query_list.go

This PR changes the error message returned on the context error.
On context timeout: `ERROR 3024 (HY000): Query execution was interrupted, maximum statement execution time exceeded`
On context cancelled: `ERROR 1317 (70100): Query execution was interrupted`
This PR also executed `kill query` instead of `kill connection` on context error to reduce the connection churn. This is only performed on non-transactional queries.
- Closes https://github.com/vitessio/vitess/issues/10059

Use Kill Query for Non-Transaction Query Execution and Update Query Timeout / Cancelled Error Message

---

go/vt/topo/keyspace.go
go/vt/topo/keyspace_external_test.go
go/vt/vtctl/workflow/server_test.go

This is needed because the input to this function comes from e.g. the vschema, where a keyspace name that contains special characters such as a dash needs to be SQL escaped with backticks.
I think that we should backport this to v19 as that's when we started making heavier use of this function via https://github.com/vitessio/vitess/pull/15047 (and https://github.com/vitessio/vitess/pull/15117).
- Fixes: https://github.com/vitessio/vitess/issues/15766
- …

Properly unescape keyspace name in FindAllShardsInKeyspace

---

go/mysql/flavor_mysql.go
go/vt/vttablet/endtoend/misc_test.go

`BaseShowTablesWithSizes` is executed whenever a `vttablet` process starts up.
We use `vtcombo` in our CI environment, with many different keyspaces defined in the topology or created dynamically via `CREATE DATABASE`. We noticed that when upgrading from MySQL 5.7 to MySQL 8.0 in our CI environment, the `vtcombo` startup time and the database setup times in our build jobs started to be almost twice as long as with MySQL 8.0.
I was able to trace this down to the differences in the `BaseShowTablesWithSizes` query.
The MySQL 8.0 version uses two queries combined via `UNION`. The problem here is that each of the two parts of the `UNION` ends up joining `information_schema.innodb_tablespaces`. `information_schema.innodb_tablespaces` is a MySQL system table that I believe MySQL fills on-demand …

Improve performance for `BaseShowTablesWithSizes` query.

---

go/vt/vtgate/engine/projection.go
go/vt/vtgate/engine/projection_test.go

When we have a project, we correctly convert the value to the connection collation using:
```go
c.Value(vcursor.ConnCollation())
```
But we then don't update / change the collation on the fields information. This needs to match the actual data, otherwise the client might corrupt the data.
This ensures we add the same rules for the resulting collation.
Fixes #15800 

projection: Return correct collation information

---

go/test/endtoend/vreplication/helper_test.go
go/test/endtoend/vreplication/multi_tenant_test.go
go/test/endtoend/vreplication/wrappers_test.go
go/vt/vtctl/workflow/server.go
go/vt/vtctl/workflow/switcher.go
go/vt/vtctl/workflow/switcher_dry_run.go
go/vt/vtctl/workflow/switcher_interface.go
go/vt/vtctl/workflow/traffic_switcher.go
go/vt/vtctl/workflow/utils.go
go/vt/vtctl/workflow/workflow_test.go
go/vt/vtgate/vindexes/vschema.go

As part of #15403 we had assumed it was fine to switch all traffic at the same time. However it turns out there are use cases where we may want to allow switching replica/rdonly and primary traffic separately, similar to other workflows.
This PR adds that support.
#15403 

Multi-tenant MoveTables: allow switching replica/rdonly traffic separately before switching primary traffic

---

changelog/20.0/20.0.0/summary.md
go/mysql/sqlerror/constants.go
go/mysql/sqlerror/sql_error.go
go/test/endtoend/vtgate/queries/dml/insert_test.go
go/vt/sqlparser/ast.go
go/vt/sqlparser/ast_clone.go
go/vt/sqlparser/ast_copy_on_rewrite.go
go/vt/sqlparser/ast_equals.go
go/vt/sqlparser/ast_rewrite.go
go/vt/sqlparser/ast_visit.go
go/vt/sqlparser/cached_size.go
go/vt/vterrors/code.go
go/vt/vterrors/state.go
go/vt/vtgate/engine/cached_size.go
go/vt/vtgate/engine/insert.go
go/vt/vtgate/planbuilder/operator_transformers.go
go/vt/vtgate/planbuilder/testdata/dml_cases.json
go/vt/vtgate/semantics/analyzer_dml_test.go
go/vt/vtgate/semantics/analyzer_test.go
go/vt/vtgate/semantics/derived_table.go
go/vt/vtgate/semantics/early_rewriter.go
go/vt/vtgate/semantics/real_table.go
go/vt/vtgate/semantics/semantic_state.go
go/vt/vtgate/semantics/table_collector.go
go/vt/vtgate/semantics/vindex_table.go
go/vt/vtgate/semantics/vtable.go

This adds planner support for new insert syntax
`insert into t(id, col) values(1, 'apa') as dt(x) on duplicate key col = x`
- Closes https://github.com/vitessio/vitess/issues/12122

feat: Add support for Insert with row alias

---

tools/unit_test_runner.sh

This PR fixes a bug introduced in https://github.com/vitessio/vitess/pull/15734 that causes the unit test CI to not run any tests.
- Fixes https://github.com/vitessio/vitess/issues/15814

Fix unit-test-runner bug
