- go/vt/sqlparser/ast_funcs.go
- go/vt/vtgate/planbuilder/testdata/union_cases.json
When using pure literals without column alias, Vitess is getting the column names a little wrong. 
Fixes #15819
> fix: make sure string literals as columns are handled well

- .github/workflows/check_make_vtadmin_web_proto.yml
- .github/workflows/create_release.yml
- .github/workflows/local_example.yml
- .github/workflows/region_example.yml
- .github/workflows/vtadmin_web_build.yml
- .github/workflows/vtadmin_web_lint.yml
- .github/workflows/vtadmin_web_unit_tests.yml
- changelog/20.0/20.0.0/summary.md
- web/vtadmin/README.md
- web/vtadmin/build.sh
- web/vtadmin/package-lock.json
- web/vtadmin/package.json
- web/vtadmin/src/api/http.test.ts
At least on main/v20 we should use the current LTS version: https://nodejs.org/en/about/previous-releases
We also update the dependencies using the latest min node version of 20.12.0 using `cd web/vtadmin && npm update`.
> Update Node version to current LTS release

- go/test/endtoend/utils/mysql.go
- go/test/endtoend/utils/mysql_test.go
This Pull Request enhances how we compare types with `mcmp`. If the type is the same between MySQL and Vitess but the size is bigger on Vitess than on MySQL, we let the test pass.
Related to https://github.com/vitessio/vitess/issues/15818, it won't fix it but it will allow test to pass.
> Improve `mcmp` type comparison

- go/vt/vtgate/tabletgateway.go
Implement a simple single-pass scan through the list of tablets that both randomly shuffles the set and pulls the same-cell hosts to the front of the list.
This is the same functionality as the old code, just with a simpler algorithm that only needs to loop once through the set of tablets so it's a marginally more efficient approach.
> rewrite shuffleTablets to be clearer and more efficient

- examples/common/scripts/vtadmin-up.sh
- web/vtadmin/build.sh
- web/vtadmin/src/components/routes/Vtctlds.tsx
This PR:
- Removes the link to vtctld web, since we deprecated it in v17
- Improves `vtadmin-up.sh` by 1) outputting the variables that are being set and 2) shortening the wait time for cluster discovery
- Improves `web/vtadmin/build.sh` by 1) outputting the variables set and 2) when no hostname is set, uses the local machine's hostname
The last bullet point made it so that I could run `./101_initial_clusters.sh` without any extra steps, and get vtadmin-web/vtadmin-api working:
> [VTAdmin] Remove vtctld web link, improve local example (#15607)

- config/init_db.sql
- examples/compose/config/init_db.sql
- examples/operator/101_initial_cluster.yaml
- go/test/endtoend/vreplication/testdata/config/init_testserver_db.sql
This removes the resets for the startup script that we use. These were long ago added for a MariaDB 10.3 workaround which is not supported as a managed tablet anyway anymore.
It also would only needed for an existing node to join a cluster that is otherwise manually emptied. If that's the case, the reset should also be done manually anyway too.
Removing this also ensures we have no logic here that would start failing in the future on MySQL 8.4.0 which removed these statements.
Part of #9515 …
> mysqlctld: Remove unneeded resets in init_db.sql

- go/test/endtoend/clustertest/vtctld_test.go
- go/vt/topo/etcd2topo/server_test.go
- go/vt/vtctl/grpcvtctldserver/server.go
- go/vt/vtctl/grpcvtctldserver/server_test.go
This adds test to confirm and enforce the correct / expected behavior of the [`vtctldclient GetTablets` client command](https://vitess.io/docs/reference/programs/vtctldclient/vtctldclient_gettablets/) and the [`GetTablets` vtctlserverice.Vtctld RPC](https://github.com/vitessio/vitess/blob/3814b2a602e83641a8f8305ab0ffce9642516e57/proto/vtctlservice.proto#L164-L165) (which the client command uses). Now we can be sure that the behavior matches the documentation and intuitive expectations.
- Fixes: https://github.com/vitessio/vitess/issues/13801
-   [x] Tests were added or are …
> Add tests for GetTablets partial results

- go/test/endtoend/vtgate/queries/tpch/tpch_test.go
- go/vt/vtgate/executor_select_test.go
- go/vt/vtgate/planbuilder/operators/apply_join.go
- go/vt/vtgate/planbuilder/operators/phases.go
- go/vt/vtgate/planbuilder/operators/projection_pushing.go
- go/vt/vtgate/planbuilder/testdata/cte_cases.json
- go/vt/vtgate/planbuilder/testdata/from_cases.json
- go/vt/vtgate/planbuilder/testdata/memory_sort_cases.json
- go/vt/vtgate/planbuilder/testdata/select_cases.json
- go/vt/vtgate/planbuilder/testdata/tpch_cases.json
This PR fixes the issue described in https://github.com/vitessio/vitess/issues/15830.
While working on fixing the derived table query, it was noticed that `select * from (select u.foo * ue.bar from user u join user_extra ue) as dt` wasn't working on main even before https://github.com/vitessio/vitess/pull/15588 was merged but still #15588 made it worse (as in the plan became even more wrong if that makes sense).
This PR fixes this issue and after the changes in this PR, that query works as intended. There are 2 changes in this PR - 
1. We can't override the original expression when we see a derived table, because overriding the original with a column name causes issues with breaking the expression since a column name can't be split. At the same time, we don't want to lose the information …
> Fix derived table bug

- examples/common/scripts/vtadmin-up.sh
- web/vtadmin/build.sh
This PR:
- updates the build.sh script to reference `build.env` in the same directory
- ensures that the vtadmin-up.sh build scripts work with different formats of `hostname`
- https://github.com/vitessio/vitess/issues/15833
N/A
> Update VTAdmin build script

- changelog/20.0/20.0.0/summary.md
- go/vt/vttablet/tabletserver/tabletenv/config.go
This PR deletes the deprecated pool size flags.
> Delete the deprecated pool size flags

- go/test/endtoend/utils/cmp.go
- go/test/endtoend/utils/mysql.go
- go/test/endtoend/utils/utils.go
- go/test/endtoend/vtgate/foreignkey/fk_fuzz_test.go
- go/test/endtoend/vtgate/foreignkey/fk_test.go
- go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
- go/test/endtoend/vtgate/queries/dml/dml_test.go
- go/test/endtoend/vtgate/queries/misc/misc_test.go
- go/test/endtoend/vtgate/queries/orderby/orderby_test.go
- go/test/endtoend/vtgate/queries/random/random_test.go
- go/test/endtoend/vtgate/queries/random/simplifier_test.go
After noticing the problem https://github.com/vitessio/vitess/issues/15826 and running into the issues described in https://github.com/vitessio/vitess/pull/15779#issuecomment-2088092831 and https://github.com/vitessio/vitess/pull/15779#issuecomment-2088093697, the Vitess maintainers have decided not to fix the issue, and instead let the rows affected fields for Vitess and MySQL differ. The reasoning is that all the users of MySQL with foreign keys, should already be accustomed to having the rows affected being different from the total number of row deletions (because MySQL doesn't count the rows deleted via CASCADEs as they happen at the InnoDB level). Moreover, it will take significant code changes and performance penalty to match the MySQL behaviour. We would have to do multiple SELECT …
> Fix Foreign key fuzzer to ignore rows affected

- go/vt/mysqlctl/backup_test.go
- go/vt/mysqlctl/backupengine.go
- go/vt/mysqlctl/backupengine_test.go
- go/vt/mysqlctl/version.go
This check has to be smarter to allow certain backup restore scenarios. Starting from MySQL 8.0.35, it's allowed to restore into older versions within the same LTS stream. This is something we didn't allow so far, but we need to for managing the more recent MySQL releases correctly.
This also implies that we don't need upgrade safe flags for these cases as well and allows it even if that flag is off now.
Fixes #15855  …
> mysqlctl: Improve backup restore compatibility check

- go/vt/sqlparser/parse_test.go
- go/vt/sqlparser/sql.go
- go/vt/sqlparser/sql.y
This PR fixes https://github.com/vitessio/vitess/issues/15861 by not reusing an old value on the `sql_id_opt` field when parsing `window_spec`.
Backporting this to all release branches as the issue exist in all of them.
- Fixes #15861 
> Fix wrong assignment to `sql_id_opt` in the parser

- .github/CODEOWNERS
See title. 🙂 I've been doing more and more `vtctldclient` related work over recent months so I think it makes sense to add me as a CODEOWNER for related things.
> Add @mattlord as CODEOWNER for vtctld[client] related things

- go/vt/schemadiff/schema_diff_test.go
- go/vt/schemadiff/table_test.go
Just adding a couple test cases. No particular issue, though this is inspired by https://github.com/vitessio/vitess/pull/15859
https://github.com/vitessio/vitess/pull/15859
> `schemadiff`: adding charset/collation tests

- go/vt/schemadiff/diff.go
- go/vt/schemadiff/diff_test.go
- go/vt/schemadiff/table.go
- go/vt/schemadiff/table_test.go
- go/vt/schemadiff/types.go
- go/vt/schemadiff/view.go
- go/vt/schemadiff/view_test.go
Introducing a `AtomicDiffs()` function, which, given a single diff, returns a slice of diffs, as atomic as possible, which together comprises the given diff.
Right now the function only breaks down `DROP PARTITION` statements.
An an aside, this PR also adds a convenient `Clone()` function to `EntityDiff` interface, which does a deep copy of the diff and of its entities (but not necessarily other constructs such as annotations). This is useful for programs using `schemadiff` as a library as it allows some safety for data manipulation.
Addresses https://github.com/vitessio/vitess/issues/15842
-   [ ] If this change is to be back-ported to previous releases, a justification is included in …
> `schemadiff`: atomic diffs for range partition `DROP PARTITION` statement

- changelog/19.0/19.0.4/changelog.md
- changelog/19.0/19.0.4/release_notes.md
- changelog/19.0/README.md
This Pull Request copies the release notes found on `release-19.0` to keep release notes up-to-date after the `v19.0.4` release.
> Copy `v19.0.4` release notes on `main`

- changelog/18.0/18.0.5/changelog.md
- changelog/18.0/18.0.5/release_notes.md
- changelog/18.0/README.md
This Pull Request copies the release notes found on `release-18.0` to keep release notes up-to-date after the `v18.0.5` release.
> Copy `v18.0.5` release notes on `main`

- changelog/17.0/17.0.7/changelog.md
- changelog/17.0/17.0.7/release_notes.md
- changelog/17.0/README.md
This Pull Request copies the release notes found on `release-17.0` to keep release notes up-to-date after the `v17.0.7` release.
> Copy `v17.0.7` release notes on `main`

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v18.0.6-SNAPSHOT) after the release of v18.0.5.
> [release-18.0] Bump to `v18.0.6-SNAPSHOT` after the `v18.0.5` release

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v19.0.5-SNAPSHOT) after the release of v19.0.4.
> [release-19.0] Bump to `v19.0.5-SNAPSHOT` after the `v19.0.4` release

- go/mysql/schema.go
- go/vt/sidecardb/schema/schematracker/schemacopy.sql
This fixes a collation error caused by a query run during health check in `vttablet`.
The same issue exists in v17.x, so a backport is required once this has been merged to v18.x.
* https://github.com/vitessio/vitess/issues/11003
* https://github.com/vitessio/vitess/issues/15858
> [18.x] Fix `schemacopy` collation issues

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v17.0.8-SNAPSHOT) after the release of v17.0.7.
> [release-17.0] Bump to `v17.0.8-SNAPSHOT` after the `v17.0.7` release

- go/vt/vtgate/planbuilder/testdata/other_read_cases.json
- go/vt/vtgate/planbuilder/vexplain.go
In order to handle `I_S` tables/views correctly, we have to do thing different than we do for normal tables.
These queries can be sent to any shard on any keyspace.
This is a relatively low-risk change to backport, so I suggest we backport it at least to v18 and v19.
Fixes #15900
> fix: handle info_schema routing

- go/test/endtoend/vtgate/queries/timeout/timeout_test.go
- go/vt/vtgate/engine/cached_size.go
- go/vt/vtgate/engine/send.go
- go/vt/vtgate/planbuilder/bypass.go
- go/vt/vtgate/planbuilder/testdata/bypass_shard_cases.json
This PR adds support for query timeout hint in shard targeting.
- Closes https://github.com/vitessio/vitess/issues/7031
> allow query timeout hints on shard targeting

- go/test/endtoend/vtgate/queries/informationschema/informationschema_test.go
- go/vt/vtgate/engine/route_test.go
- go/vt/vtgate/engine/routing.go
The engine primitive handling info_schema routing was not able to handle queries with the predicate:
`WHERE table_schema = ''`.
This PR fixes that.
Fixes #15902
> fix: handle table_schema = '' without failing

- examples/common/env.sh
This is a minor fix to `examples/common/env.sh` so that it does not error out on mac where `zsh` is the default shell. `shopt` is bash-specific and does not work on `zsh`. This fix was suggested by @mattlord while reviewing and discussing this other PR for the docs on the website: https://github.com/vitessio/website/pull/1736 
This is my first PR to `vitessio/vitess` so not sure about other procedures such as backports, etc.
No issue for this.
-   [x] …
> Update env.sh so that is does not error when running on Mac

- go/vt/vttablet/tabletserver/vstreamer/helper_event_test.go
- go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go
Final PR on porting over the vstreamer unit tests. Only one test `TestJSON` has been ported. Remaining ones are too specific and will require disproportional changes in the test framework for each test and those have been left as-is. 
https://github.com/vitessio/vitess/pull/14903
> VStreamer unit tests: refactor pending test

- go/vt/topo/etcd2topo/watch.go
- go/vt/topo/etcd2topo/watch_test.go
Etcd has several version related fields/values in each key's header: `Revision`, `ModRevision`, and `Version`. These are related but distinct things:
- https://github.com/etcd-io/etcd/issues/6518
- https://etcd.io/docs/v3.5/learning/data_model/
To summarize:
- `Revision`: a logical clock used to track changes to the etcd keyspace (a transaction / snapshot ID)
- `Version`: a logical clock used to track the changes to an individual key _since it was last created_ (it is not monotonic)
- `ModRevision`: the etcd keyspace revision number for the key at that point in time (the logical version of the key)
The `Revision` is what allows for consistent reads and writes of multiple keys (in a transaction). It allows you, for example, to do a consistent read / scan of N keys at that logical …
> Etcd2Topo: Use node's ModRevision consistently for in-memory topo.Version value

- go/vt/vtgate/executor.go
This makes easier it for other components to plug in logic to modify errors before they are returned to the client by vtgate. By default the `nullTransformer` is used, which does nothing.
N/A
None
> Add error transformer to vtgate executor

- .gitignore
- go/vt/vtgate/planbuilder/plan_test.go
Test infrastructure improvement.
This PR changes the plan test output to be easier to work with. It will leave a single directory after running the plan tests, and this directory will only contain the failed files. When running tests, the expectation directory will be emptied.
I suggest we backport this just to make it easier to work with backports. If there are any issues with the backports, they can just be abandoned.
-   [x] Documentation was added or …
> test: Cleaner plan tests output

- examples/compose/fix_replication.sh
- go/mysql/constants.go
- go/mysql/endtoend/replication_test.go
- go/mysql/flavor.go
- go/mysql/flavor_filepos.go
- go/mysql/flavor_mariadb.go
- go/mysql/flavor_mysql.go
- go/mysql/flavor_mysql_legacy.go
- go/mysql/flavor_mysql_test.go
- go/mysql/flavor_mysqlgr.go
- go/mysql/replication.go
- go/mysql/replication/primary_status.go
- go/test/endtoend/backup/vtbackup/backup_only_test.go
- go/test/endtoend/cluster/vttablet_process.go
- go/test/endtoend/reparent/emergencyreparent/ers_test.go
- go/test/endtoend/reparent/plannedreparent/reparent_test.go
- go/test/endtoend/tabletgateway/buffer/reparent/failover_buffer_test.go
- go/test/endtoend/vtorc/utils/utils.go
- go/vt/binlog/binlog_connection.go
- go/vt/mysqlctl/backup.go
- go/vt/mysqlctl/fakemysqldaemon.go
- go/vt/proto/replicationdata/replicationdata.pb.go
- go/vt/proto/tabletmanagerdata/tabletmanagerdata.pb.go
- go/vt/vtctl/grpcvtctldserver/endtoend/init_shard_primary_test.go
- go/vt/vttablet/tabletmanager/rpc_replication.go
- go/vt/wrangler/testlib/backup_test.go
- proto/replicationdata.proto
- proto/tabletmanagerdata.proto
This deals with more deprecated SQL commands that now uses different terminology on newer MySQL versions.
Also refactors things to reduce some duplication and to simplify some logic. We now treat the latest syntax as default and keep older syntax for older versions as needed explicitly.
Part of #9515
> mysql: Handle more deprecated SQL commands

- go/vt/sqlparser/ast_funcs.go
- go/vt/vtgate/semantics/binder.go
Small PR that introduces helper method that helps make the code a little easier to write and read.
> refactor: introduce helper method to extract logic

- config/mycnf/mysql80.cnf
As described in https://github.com/vitessio/vitess/issues/15937#issuecomment-2109779208, this PR needs to revert the changes in https://github.com/vitessio/vitess/pull/15663 and https://github.com/vitessio/vitess/pull/15689. We'll reintroduce the default change in next release.
- Fixes https://github.com/vitessio/vitess/issues/15937
> Remove the default for replica-net-timeout

- go/cmd/mysqlctl/command/init.go
- go/cmd/mysqlctl/command/shutdown.go
- go/cmd/mysqlctl/command/start.go
- go/cmd/mysqlctl/command/teardown.go
- go/cmd/mysqlctld/cli/mysqlctld.go
- go/cmd/topo2topo/cli/topo2topo.go
- go/cmd/vtadmin/main.go
- go/cmd/vtbackup/cli/vtbackup.go
- go/cmd/vtbench/cli/vtbench.go
- go/cmd/vtclient/cli/vtclient.go
- go/cmd/vtclient/cli/vtclient_test.go
- go/cmd/vtcombo/cli/main.go
- go/cmd/vtcombo/cli/vschema_watcher.go
- go/cmd/vtctld/cli/cli.go
- go/cmd/vtctld/cli/schema.go
- go/cmd/vtctldclient/command/legacy_shim.go
- go/cmd/vtctldclient/command/root.go
- go/cmd/vtexplain/cli/vtexplain.go
- go/cmd/vtgate/cli/cli.go
- go/cmd/vttablet/cli/cli.go
This removes a bunch of the context.Background() usage for the command line entrypoints. In general, we should use the command context (which normally is context.Background(), but it's more semantically accurate).
There's a few cases where we need more fixes. Specifically in vtgate where we want to setup a cancellable context and cancel it when we shut down. This is the one that ends up running things like the topo watcher and this ensures things are closed appropriately.
Similarly in vtcombo we apply similar fixes so that we always correctly cancel the context on shutdown and the same for vttablet.
Fixes #15927
-   [x] If this change is to be back-ported to previous releases, a …
> go/cmd: Audit and fix context.Background() usage

- go/hack/hack_test.go
- go/ioutil/meter_test.go
- go/ioutil/reader_test.go
- go/ioutil/writer_test.go
- go/jsonutil/json_test.go
This PR adds tests for `go/ioutil` and refactor existing
- #14931 
> test: Add tests for `go/ioutil` and refactor existing

- go/test/endtoend/vtgate/queries/misc/misc_test.go
- go/vt/vtgate/planbuilder/operator_transformers.go
- go/vt/vtgate/planbuilder/testdata/aggr_cases.json
- go/vt/vtgate/planbuilder/testdata/cte_cases.json
- go/vt/vtgate/planbuilder/testdata/from_cases.json
This PR fixes the issue pointed out in https://github.com/vitessio/vitess/issues/15944.
The problem was that we were removing some Projection operators that were only passing through the columns in the same order that they were receiving in. However, they were changing the column aliases. These projections are still required and should not be removed.
- Fixes https://github.com/vitessio/vitess/issues/15944
> Fix aliasing in queries by keeping required projections 

- go/logstats/logger_test.go
This PR adds required tests for `go/logstats`
- #14931 
> test: Add required tests for `go/logstats`

- go/mathstats/sample_test.go
- go/sqltypes/bind_variables_test.go
- go/sqltypes/named_result_test.go
- go/sqltypes/result_test.go
- go/sqltypes/value_test.go
This PR adds missing/required tests for `sqltypes` and `mathstats`, and also refactors some existing tests in the packages
- #14931 
- #15182
> test: Add missing/required tests for `sqltypes` and `mathstats`

- go/test/endtoend/vtgate/queries/dml/insert_test.go
- go/vt/sqlparser/normalizer_test.go
- go/vt/vtgate/engine/insert.go
- go/vt/vtgate/engine/insert_test.go
This PR fixes the issue with `insert on duplicate key update`. When there is a `list argument` in the on duplicate key update expressions it was missed in sending down to vttablet.
- Fixes https://github.com/vitessio/vitess/issues/15965
-   [X] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [X] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [X] Did the new or modified tests pass consistently locally and on CI?
> fix: insert on duplicate update to add list argument in the bind variables map

- go.mod
- go.sum
- go/vt/vtorc/inst/analysis_dao.go
- go/vt/vtorc/inst/analysis_dao_test.go
- go/vt/vtorc/inst/audit_dao.go
- go/vt/vtorc/inst/instance_dao.go
- go/vt/vtorc/logic/vtorc.go
This moves the stats setup to the internal Vitess stats package instead of another external dependency.
With this change we can remove the external dependency.
> vtorc: Switch to Vitess stats

- go/cache/theine/bf/bf_test.go
- go/timer/timer_test.go
- go/vt/key/destination_test.go
- go/vt/key/key_test.go
This PR adds required/missing tests for `vt/key`, `timer` and `cache/theine/bf`
- #14931 
- #15182 
> test: Add required tests for `vt/key`, `timer` and `cache/theine/bf`

- go/mysql/fakesqldb/server.go
- go/test/endtoend/vreplication/cluster_test.go
- go/test/endtoend/vreplication/resharding_workflows_v2_test.go
- go/vt/vttablet/tabletmanager/vreplication/controller.go
- go/vt/vttablet/tabletmanager/vreplication/framework_test.go
- go/vt/vttablet/tabletmanager/vreplication/journal_test.go
- go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go
- go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go
- go/vt/vttablet/tabletserver/schema/engine.go
- go/vt/vttablet/tabletserver/schema/engine_test.go
- go/vt/vttablet/tabletserver/schema/historian_test.go
- go/vt/vttablet/tabletserver/vstreamer/helper_event_test.go
- go/vt/vttablet/tabletserver/vstreamer/resultstreamer_test.go
- go/vt/vttablet/tabletserver/vstreamer/rowstreamer.go
- go/vt/vttablet/tabletserver/vstreamer/rowstreamer_test.go
- go/vt/vttablet/tabletserver/vstreamer/tablestreamer_test.go
- go/vt/vttablet/tabletserver/vstreamer/uvstreamer_flaky_test.go
- go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
- go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go
In `SchemaEngine`'s `GetTableForPos` function, we would not find a table schema for a given GTID position when the [historian](https://vitess.io/docs/reference/vreplication/internal/tracker/) is disabled and we would then return the "current" table schema *from the cache*. The problem there is that the cache can be quite stale (up to 30 minutes by default, see `--queryserver-config-schema-reload-time` ). Similarly, if you want to get the current schema for a table that was recently created (within up to the last 30 minutes by default) then `GetTableForPos` would return a `table not found` error as it wasn't yet in the cache. So if you're e.g. doing a fair amount of schema changes/migrations then this function's results can be out of date and block subsequent schema changes/migrations. …
> SchemaEngine: Ensure GetTableForPos returns table schema for "current" position by default

- go/vt/vtctl/reparentutil/emergency_reparenter_test.go
This PR fixes a data race introduced in https://github.com/vitessio/vitess/pull/15934. The test in question is changing the `topo.RemoteOperationTimeout`. Since that value is used while running ERS and PRS, we cannot run that test in parallel with anyother test running a reparent operation. This PR fixes this by removign the test from running parallely with other tests.
Fixes a race introduced in https://github.com/vitessio/vitess/pull/15934 which was caught in the tests in https://github.com/vitessio/vitess/pull/15991#issuecomment-2123858289
-   [x] Tests were added or are …
> Fix Data race in tests introduced in #15934

- go/vt/vttablet/tabletserver/messager/message_manager.go
We've been seeing some message related errors, but without the table name, it's hard to figure out what's going on. This also adds a consistent prefix that was already in use for many of the logging calls, but not all of them.
> messager: add consistent log prefix w/ table name

- doc/design-docs/LockShard.md
- doc/design-docs/TopoLocks.md
This PR adds internal docs for LockShard functionality.
-   [x]  If this change is to be back-ported to previous releases, a justification is included in the PR description
> Add lock shard docs

- go/vt/vtctl/grpcvtctldserver/testutil/test_tmclient.go
- go/vt/vtorc/logic/tablet_discovery.go
- go/vt/vtorc/logic/tablet_discovery_test.go
This PR fixes the bug described in https://github.com/vitessio/vitess/issues/15990. It adds the `RemoteOperationTimeout` to all the RPC calls.
- Fixes https://github.com/vitessio/vitess/issues/15990
> Add timeout to all the contexts used for RPC calls in vtorc

- go/vt/vttablet/tabletmanager/vreplication/engine.go
- go/vt/vttablet/tabletmanager/vreplication/engine_test.go
Add more specific errors when `WaitForPos` receives an unexpected number of rows or columns. No longer prints the raw Result object (which isn't a particularly descriptive error for end users). 
Immediate motivation is to make tests less brittle when `Result` object is modified (in downstream forks).
N/A
> Improve WaitForPos errors, don't include Result struct in message

- go/pools/smartconnpool/pool.go
- go/pools/smartconnpool/pool_test.go
- go/vt/vttablet/endtoend/misc_test.go
- go/vt/vttablet/endtoend/stream_test.go
- go/vt/vttablet/tabletserver/connpool/pool.go
- go/vt/vttablet/tabletserver/connpool/pool_test.go
- go/vt/vttablet/tabletserver/debugenv.go
- go/vt/vttablet/tabletserver/query_executor.go
- go/vt/vttablet/tabletserver/tabletserver.go
- go/vt/vttablet/tabletserver/tabletserver_test.go
- go/vt/vttablet/tabletserver/tx_pool_test.go
Since rolling out the new connection pool in Vitess 18, we've seen in production some cases were the connection pool fails to shutdown properly. I've spotted the following issues:
- The new connection pool is very strict when it comes to shutting down: it won't finish the shutdown operation until every single connection has been returned to the pool and cleanly closed. The previous connection pool was not this strict, so this behavior is new and seems to be causing issues.
- The new connection pool returns the wrong Error when trying to fetch a connection from the pool while the pool is already closed or during the process of closing. The old connection pool had a specific `ErrConnPoolClosed`, whilst the new pool returns a generic `ErrTimeout` that was causing very confusing messages to …
> connpool: Allow time out during shutdown

- go/vt/vttablet/endtoend/vstreamer_test.go
This data race resulted from the fact that the same ctx variable/pointer is re-used in the test and because we did not wait for the goroutine to end once the previous context was cancelled before we overwrote the variable/pointer with a new context those two goroutines were racing on reads and writes of the address. So the race looked like this:
```
Goroutine 16633 (running) created at:
vitess.io/vitess/go/vt/vttablet/endtoend.TestSchemaVersioning()
/vitess/go/vt/vttablet/endtoend/vstreamer_test.go:153 +0x1455
...
Write at 0x00c000407020 by goroutine 16620:
vitess.io/vitess/go/vt/vttablet/endtoend.TestSchemaVersioning()
/vitess/go/vt/vttablet/endtoend/vstreamer_test.go:191 +0x18af
...
```
With those two access being: …
> CI: Address data race in TestSchemaVersioning

- go/vt/schemadiff/column.go
- go/vt/schemadiff/table_test.go
Fixes https://github.com/vitessio/vitess/issues/15999. When looking at textual columns, if the character set is defined and the collation is not, `schemadiff` assumes the default collation for that character set.
https://github.com/vitessio/vitess/issues/15999
cc @lizztheblizz 
> `schemadiff`: assume default collation for textual column when collation is undefined

- go/vt/vtgate/vindexes/vschema.go
This removes the coupling between vschema and topotools just for a single helper function.
With this change, we don't end up pulling a large dependency tree for other utilities like schemadiff.
See also https://go-proverbs.github.io, "A little copying is better than a little dependency.".
Also see https://github.com/planetscale/schemadiff/pull/22#issuecomment-2131055714
Part of #14717
> Decouple topotools from vschema

- go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
This PR fixes a flakiness in `onlineddl_scheduler` CI. It seems to have been lurking for quite a while, but I only encountered it severely in https://github.com/vitessio/vitess/pull/15988, though after a long investigation, I found it's unrelated to the throttler.
It's a really simple race condition between VReplication and a `SELECT FOR UPDATE` query the test runs (validating the behavior of `FORCE_CUTOVER`). The race is that the test can issue said select query before VReplication has even had the chance to start running, in which case VReplication never gets to the point of cutting over, in which case the migration cannot cut-over. This is unrealistic (or rather, not _interesting_) in production, and not the purpose of the test.
The fix is to ensure VReplication has had chance to run …
> Online DDL: fix flaky `onlineddl_scheduler` CI test

- examples/common/env.sh
The [Vitess local examples](https://vitess.io/docs/get-started/local/) ([source](https://github.com/vitessio/vitess/tree/main/examples/local)) are a common first touch experience for users. They are regularly confused or curious as to why many of the columns in the examples show up as HEX in the query results. The reason for this is that we use [`VARBINARY`](https://dev.mysql.com/doc/refman/8.0/en/binary-varbinary.html) types throughout — in some rare cases like `keyspace_id` it makes sense, but most like `customer.email` are pure text. This makes understanding what's happening and quickly confirming at-a-glance results as expected more difficult and poses a minor hurdle when it's already quite a lot to get started with Vitess.
In this PR, we add the …
> Local Examples: Add --binary-as-hex=false flag to mysql alias

- go/vt/vtgate/planbuilder/operators/subquery_planning.go
- go/vt/vtgate/planbuilder/testdata/filter_cases.json
When the planner is able to merge subqueries, it's important to remember to remove the keyspace from the query before adding the subquery to the outer query.
Fixes #14864
> fix: remove keyspace when merging subqueries

- changelog/20.0/20.0.0/summary.md
- go/vt/vtctl/reparentutil/emergency_reparenter.go
- go/vt/vtctl/reparentutil/emergency_reparenter_test.go
This PR removes legacy ERS stats that were deprecated [by a PR I wrote in Vitess 18.0](https://github.com/vitessio/vitess/pull/13723). Replacement metrics with labels were added in the same release
https://github.com/vitessio/vitess/pull/13723
> Remove legacy `EmergencyReparentShard` stats

- changelog/20.0/20.0.0/summary.md
- go/flags/endtoend/vtbackup.txt
- go/flags/endtoend/vtcombo.txt
- go/flags/endtoend/vtctld.txt
- go/flags/endtoend/vtgate.txt
- go/flags/endtoend/vtorc.txt
- go/flags/endtoend/vttablet.txt
- go/vt/topo/locks.go
This PR fixes the documentation for `--lock-timeout` flag after we noticed it was incorrect.
> Fix documentation for `--lock-timeout`

- .github/workflows/static_checks_etc.yml
- tools/check_go_versions.sh
This PR validates that the go versions in the project are compatible as discussed in https://github.com/vitessio/vitess/issues/15494
Real CI result for https://github.com/vitessio/vitess/pull/15932/commits/d412182c4ea02c649bd99c601c4c68de0feb9682:
Resolves https://github.com/vitessio/vitess/issues/15494
> Validate go versions in Static Code Checks CI

- go/vt/vttablet/tabletserver/throttle/throttler.go
- go/vt/vttablet/tabletserver/throttle/throttler_test.go
Followup to https://github.com/vitessio/vitess/issues/15397 and https://github.com/vitessio/vitess/pull/15398
When the `Primary` throttler probes a replica throttler, the replica's `CheckResult` includes a `RecentlyChecked` boolean field.
That field was not set correctly, and was `false` in almost all internal vitess probing situations. The stimulation introduced in #15398 thankfully prevents a complete starvation of the throttler. However, with `RecentlyChecked` reported as `false` more than it should, the `Primary` will not renew the heartbeat lease as much as it should, leading to more throttling scenarios.
In this PR we ensure to return a `RecentlyChecked = true` value when the throttler has, in fact, been recently checked in the past second-or-so, by any other check. …
> Tablet throttler: recent check diff fix

- go/vt/schemadiff/capability.go
- go/vt/schemadiff/capability_test.go
Fixes https://github.com/vitessio/vitess/issues/16024
Although not documented in https://dev.mysql.com/doc/refman/8.0/en/innodb-online-ddl-operations.html, adding a column with a default expression (non-literal) value is not eligible for `INSTANT` DDL:
```sql
> alter table tt add column i3 int default (2+5), algorithm=instant;
ERROR 1845 (0A000): ALGORITHM=INSTANT is not supported for this operation. Try ALGORITHM=COPY/INPLACE.
```
vs
```sql
> alter table tt add column i3 int default 2, algorithm=instant;
Query OK, 0 rows affected (0.00 sec)
```
This PR makes `schemadiff` aware of said limitation.
- https://github.com/vitessio/vitess/issues/16024
- https://github.com/vitessio/vitess/issues/14877
-   [ ] "Backport to:" labels have been added if this change should be back-ported to release …
> `schemadiff`: ALTER TABLE is not INSTANT-able if adding column with default expression value

- go/vt/vttablet/tabletmanager/rpc_throttler.go
- go/vt/vttablet/tabletserver/tabletserver.go
- go/vt/vttablet/tabletserver/throttle/check.go
- go/vt/vttablet/tabletserver/throttle/client.go
- go/vt/vttablet/tabletserver/throttle/throttler.go
- go/vt/vttablet/tabletserver/throttle/throttler_test.go
This is a cleanup PR for a functionality we've never used. While these changes are extracted from https://github.com/vitessio/vitess/pull/15988, this PR is against `main` and not as part of the multi-metrics PR series.
The "low priority" mechanism is a relic we inherited from `freno`, where production client apps competed with background apps over the throttler. We have never used this in `vitess`, to date, and I therefore wish to remove it. It only adds more boilerplate, more considerations, and as a matter in fact I spent the better half of a day chasing down a recurring CI failure that was caused due to a (bug? misconfiguration?) related to prioritization.
In vitess, all existing throttler clients have the same priority and nothing externally to vitess gets any precedence.
The priority …
> Tablet throttler: remove `LowPriority` logic

- go/test/endtoend/tabletmanager/throttler_topo/throttler_test.go
- go/vt/schemamanager/tablet_executor.go
Fixes https://github.com/vitessio/vitess/issues/16029, this PR implements `UpdateThrottlerConfig` for `ALTER VITESS_MIGRATION ... THROTTLE|UNTHROTTLE` commands in `ApplySchema`.
- https://github.com/vitessio/vitess/issues/16029
- https://github.com/vitessio/vitess/issues/16010
- https://github.com/vitessio/vitess/issues/13510
> `ApplySchema`: reroute `ALTER VITESS_MIGRATION ... THROTTLE ...` via `UpdateThrottlerConfig`

- go/flags/endtoend/vtcombo.txt
- go/flags/endtoend/vtgate.txt
- go/flags/endtoend/vttablet.txt
- go/streamlog/streamlog.go
- go/streamlog/streamlog_test.go
This PR implements the RFC https://github.com/vitessio/vitess/issues/15909 by adding a flag `--querylog-sample-rate float` to `vtcombo`, `vtgate` and `vttablet` in order for queries to be sampled randomly without the need for the client to trigger query logging via a query directive/comment == `--querylog-filter-tag string`
This flag supports values between `0.0` (no logging) and `1.0` (log all queries) to match other `0.0-1.0` float "sample" flags
`math/rand/v2` was used because it sounds better
Resolves https://github.com/vitessio/vitess/issues/15909
-   [ ] Tests were …
> Add support for sampling rate in `streamlog`

- .github/CODEOWNERS
This adds @shlomi-noach and myself as code owners for the tablet throttler and the schemadiff library/tool. This way we have at least 2 people (in addition to Deepthi) that are automatically added as reviewers on related PRs.
> Add CODEOWNERS for tablet throttler and schemadiff

- examples/operator/401_scheduled_backups.yaml
- examples/operator/operator.yaml
This Pull Request adds one more step to the operator example: schedule backup. It comes at the very end of the guide, after `Resharding`. For this a new `401_` file is added.
The `operator.yaml` file is also modified to reflect the changes brought by https://github.com/planetscale/vitess-operator/pull/553.
- Website PR: https://github.com/vitessio/website/pull/1746
- Vtop PR: https://github.com/planetscale/vitess-operator/pull/553
> Update `operator.yaml` and add schedule backup example

- .github/workflows/docker_build_images.yml
- Dockerfile
- Makefile
- changelog/20.0/20.0.0/summary.md
- docker/lite/Dockerfile
- docker/lite/Dockerfile.percona80
We have been facing multiple issues after we merged https://github.com/vitessio/vitess/pull/15620. Mainly, the `xtrabackup` and `mysqlbinlog` binaries were missing and thus we could not use certain features of vitess. There was several attempts to fix this: https://github.com/vitessio/vitess/pull/15775 and https://github.com/vitessio/vitess/pull/15854, which both failed. We have a plan internally on how to make this work, but as of today (1 day before the code freeze of v20) I have not been able to make that plan work, hence the revert.
> Revert the removal of the MySQL binaries in the `vitess/lite` image

- changelog/20.0/20.0.0/summary.md
- go/vt/vtgate/plugin_mysql_server_test.go
- go/vt/vtgate/vtgate.go
- go/vt/vttablet/tabletserver/query_engine.go
- go/vt/vttablet/tabletserver/query_engine_test.go
- go/vt/vttablet/tabletserver/query_executor.go
This PR adds stats for the size of query text processed by `vtgate` and `vttablet`
This is useful to understand large queries that potentially cause performance, grpc message size, bandwidth problems
Resolves https://github.com/vitessio/vitess/issues/15929
> Add sql text counts stats to `vtcombo`,`vtgate`+`vttablet`

- changelog/20.0/20.0.0/summary.md
Add changelog info for PR #15911 and #15919
cc @shlomi-noach / @deepthi 
#15911 and #15919
> Add changelogs for PR #15911 and #15919

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to update the SNAPSHOT version (v21.0.0-SNAPSHOT) after the release of v20.0.0-RC1.
> Bump to `v21.0.0-SNAPSHOT` after the `v20.0.0-RC1` release

- .github/workflows/update_golang_version.yml
This is probably something we should automate with the vitess-releaser.
Just adding `release-20.0` to the list of branches so we get the go upgrade there too automatically.
> Add `release-20.0` to the list of branches to upgrade the Go version on

- .github/workflows/upgrade_downgrade_test_onlineddl_flow.yml
Both https://github.com/vitessio/vitess/pull/16017 and https://github.com/vitessio/vitess/pull/16062 merged at about the same time, leading to the Online DDL flow CI test to merge with go `1.22.3` while all the rest of workflows are `1.22.4`.
This updates the go version for that CI workflow.
- https://github.com/vitessio/vitess/pull/16017
- https://github.com/vitessio/vitess/pull/16062
> Online DDL flow CI: Update golang version to 1.22.4

- go/vt/schemadiff/schema_diff_test.go
- go/vt/vtgate/semantics/analyzer.go
- go/vt/vtgate/semantics/check_invalid.go
- go/vt/vtgate/semantics/semantic_state.go
This fixes the problem where we would throw an error for a query on a single unsharded keyspace, even though the limitation only exists for sharded queries.
The issue here was that the previous `singleUnshardedKeyspace` field was really the field indicating if we could short circuit analysis. `schemadiff` doesn't want to short cut full analysis though, since it does want to know table & column dependencies etc. which would not be computed if analysis can be shortcutted.
Since the `singleUnshardedKeyspace` field was overloaded and really was "can we shortcut" (either because of being in a single sharded keyspace or because of non-strict analysis being requested), we couldn't use that field as a fix to guard the error thrown.
Instead, we now have a proper explicit field `canShortcut` that …
> Handle single sharded keyspaces for analysis

- go/vt/schemadiff/schema_diff_test.go
- go/vt/schemadiff/schema_test.go
- go/vt/schemadiff/semantics.go
The problem here is that we store entries in `.Tables` with their unescaped names, which is entirely safe to do here.
However, we would use `sqlparser.String` to retrieve them. Now that normally works for table names, unless a table name is a SQL keyword. In that case, it turns into the escaped version with backticks and the whole table can't be found for semantic analysis.
This can happen for example if you name a table `Order`.
Fixes #16072 
-   [x] …
> Fix schemadiff semantics handling

- changelog/20.0/20.0.0/summary.md
Somewhat late seeing that we code-freezed, this PR fixes a couple broken links in the `20.0` changelog.
I've also reviewed the PR for spell checking, it looks good.
**To be backported to `release-20.0` and then to `release-20.0-rc`**
https://github.com/vitessio/vitess/issues/16010
> Changelog 20.0: Fix broken links

- go/vt/schemadiff/schema_diff_test.go
This PR adds a `schemadiff` unit test for a multi-table add/alter/drop scenario, where we expect a specific sequential ordering of statements.
No related issue in particular. This is a test of interest.
> `schemadiff`: adding a FK dependency unit test

- .github/workflows/upgrade_downgrade_test_onlineddl_flow.yml
- go/test/endtoend/cluster/cluster_process.go
- go/test/endtoend/onlineddl/flow/onlineddl_flow_test.go
- test/config.json
Backporting manually as I forgot to add the backport label.
Adding upgrade/downgrade tests as follows:
- The tests will run an `X` version VTTablet primary, with `Y` VTTablet replica. See breakdown below.
- Enable tablet throttler.
- Create and populate some table.
- Create a load. The load takes throttling into account so that it does not overwhelm the cluster.
- Run Online DDL with `vitess` strategy, thereby running VReplication that is also using the throttler.
- Throttle and unthrottle the migration.
- Validate migration behavior while under load. Complete the migration.
- Expect successful completion of the migration, with cut-over as graceful as possible (but will resort to forced cut-over if unable to complete in a timely fashion).
See more details in …
> v20 backport: CI upgrade/downgrade tests for Online DDL / throttler / vreplication flow

- go/vt/vtctl/grpcvtctldserver/testutil/test_tmclient.go
- go/vt/vtorc/logic/tablet_discovery.go
- go/vt/vtorc/logic/tablet_discovery_test.go
This is a backport of https://github.com/vitessio/vitess/pull/15991
- #15990 
> [release-19.0] Add timeout to all the contexts used for RPC calls in vtorc (#15991)

- go/vt/vtorc/logic/tablet_discovery.go
- go/vt/vtorc/logic/tablet_discovery_test.go
This is a backport of https://github.com/vitessio/vitess/pull/15991
- #15990 
> [release-17.0] Add timeout to all the contexts used for RPC calls in vtorc (#15991)

- java/pom.xml
The Google Group email is no longer valid, let's use the maintainers mailing list.
Fixes https://github.com/vitessio/vitess/issues/16077
> Fix the email in `pom.xml`

- go/vt/schemadiff/schema.go
- go/vt/schemadiff/schema_test.go
We also need to take table level and database defaults into consideration here to compute the correct collation for foreign key type comparisons.
Fixes #16108
> Ensure that we check the correct collation for foreign keys

- web/vtadmin/package-lock.json
This PR updates the `braces` package used by VTAdmin web, because of a security vulnerability.
https://github.com/vitessio/vitess/security/dependabot/382
N/A
> Update braces package

- go/cmd/vtctldclient/command/keyspace_routing_rules.go
- go/cmd/vtctldclient/command/routing_rules.go
- go/cmd/vtctldclient/command/shard_routing_rules.go
- go/json2/marshal_test.go
- go/json2/unmarshal.go
- go/json2/unmarshal_test.go
- go/test/endtoend/vreplication/vreplication_vtctldclient_cli_test.go
The Apply cli commands were incorrectly migrated to `vtctldclient`. This PR fixes them and adds and e2e test for validating the Apply commands for table, shard and keyspace routing rule types. 
The root cause has been there since the first port of the `ApplyRoutingRules` command to vtctldclient. So part of this PR will need to be backported to all supported versions depending on which commands were migrated for each. Also the e2e test may not be portable in older versions since it uses some commands migrated much later. 
#16095
- …
> vtctldclient: Apply (Shard | Keyspace| Table) Routing Rules commands don't work

- go/test/endtoend/vtgate/queries/subquery/schema.sql
- go/test/endtoend/vtgate/queries/subquery/subquery_test.go
- go/test/endtoend/vtgate/queries/subquery/vschema.json
- go/vt/sqlparser/ast.go
- go/vt/sqlparser/ast_funcs.go
- go/vt/vtgate/planbuilder/fuzz.go
- go/vt/vtgate/planbuilder/operators/aggregation_pushing.go
- go/vt/vtgate/planbuilder/operators/aggregator.go
- go/vt/vtgate/planbuilder/operators/helpers.go
- go/vt/vtgate/planbuilder/operators/horizon_expanding.go
- go/vt/vtgate/planbuilder/operators/projection.go
- go/vt/vtgate/planbuilder/operators/query_planning.go
- go/vt/vtgate/planbuilder/operators/queryprojection.go
- go/vt/vtgate/planbuilder/operators/subquery.go
- go/vt/vtgate/planbuilder/operators/subquery_builder.go
- go/vt/vtgate/planbuilder/operators/subquery_container.go
- go/vt/vtgate/planbuilder/operators/subquery_planning.go
- go/vt/vtgate/planbuilder/plan_test.go
- go/vt/vtgate/planbuilder/planner_test.go
- go/vt/vtgate/planbuilder/predicate_rewrite_test.go
- go/vt/vtgate/planbuilder/rewrite_test.go
- go/vt/vtgate/planbuilder/set.go
- go/vt/vtgate/planbuilder/show_test.go
- go/vt/vtgate/planbuilder/testdata/select_cases.json
- go/vt/vtgate/planbuilder/vexplain.go
- go/vt/vtgate/planbuilder/vindex_func.go
- go/vt/vtgate/planbuilder/vstream.go
This PR fixes an issue in the vtgate planner where an incorrect column reference is used in ORDER BY subquery plans.
The planner now correctly uses arguments instead of the column names for subquerie placeholders, ensuring the query works as expected on MySQL.
Fixes #16110
The regression was introduced in #15039.
> fix: order by subquery planning

- go/vt/schemadiff/schema.go
- go/vt/schemadiff/schema_test.go
Followup to https://github.com/vitessio/vitess/pull/16109. #16109 introduced a bug where comparing `int` column types in tables that have different collations, inadvertently caused a `ForeignKeyColumnTypeMismatchError`.
This PR fixes that and adds a test to show it.
https://github.com/vitessio/vitess/issues/16108
> `schemadiff`: only compare column collations if of textual type

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v20.0.0-SNAPSHOT) after the release of v20.0.0-RC1.
> [release-20.0-rc] Bump to `v20.0.0-SNAPSHOT` after the `v20.0.0-RC1` release

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Undo snapshot in order to fix docker images, as part of https://github.com/vitessio/vitess/issues/16010
https://github.com/vitessio/vitess/issues/16010
> Revert "[release-20.0-rc] Bump to `v20.0.0-SNAPSHOT` after the `v20.00-RC1` release (#16142)"

- go/vt/vtexplain/testdata/multi-output/selectsharded-output.txt
- go/vt/vtexplain/testdata/multi-output/updatesharded-output.txt
- go/vt/vtexplain/testdata/selectsharded-queries.sql
- go/vt/vtexplain/vtexplain_test.go
- go/vt/vtexplain/vtexplain_vttablet.go
Add special handling for `WEIGHT_STRING` calls in `vtexplain` to ensure the result of the function call has the correct type (`varbinary` instead of `int`).
Note that the added test cases doesn't actually fail on v18 and newer, but does fail on v17 and older. This is due to changes in `evalengine.NullsafeHashcode`. But instead of mucking around in the evalengine code trying to backport whatever fixed this, I think it's cleaner to just fix the `vtexplain` code to return the correct result type for `WEIGHT_STRING` function calls.
This proposed fix applies cleanly to both affected and unaffected versions, so I feel like adding this change and the unit tests in `main` first and then backporting to all supported versions is the cleanest approach.
Fixes: #16128
-   [x] "Backport to:" labels …
> Fix `vtexplain` not handling `UNION` queries with `weight_string` results correctly.

- go/test/endtoend/utils/mysql.go
- go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
- go/test/endtoend/vtgate/queries/reference/reference_test.go
- go/test/endtoend/vtgate/queries/subquery/subquery_test.go
- go/test/endtoend/vtgate/queries/tpch/tpch_test.go
Post backport of PRs it is missed to enable some e2e test that do not run on release-19. They should be enabled now as the PRs are backported to it.
> Run more test on release-19 branch

- docker/binaries/vtadmin/Dockerfile
- docker/local/install_local_dependencies.sh
One of the vtadmin packages requires node 20 (otherwise docker builds fail).
This is a reverse backport from https://github.com/vitessio/vitess/pull/16145
- To be backported to `release-20.0`. 
- No need to backport to `release-20.0-rc` because it already contains this fix.
https://github.com/vitessio/vitess/issues/16010
> Docker: Update node vtadmin version

- go/vt/vtexplain/testdata/multi-output/selectsharded-output.txt
- go/vt/vtexplain/testdata/selectsharded-queries.sql
The test case I added for https://github.com/vitessio/vitess/pull/16129 is flaky, unfortunately. 😞 
The reason for that seems to be that both parts of the `UNION` get sent to the same shard, and the order in which they are sent is not deterministic. This causes the test to fail sometimes, because the order of the results is different.
It's very unfortunate that I noticed that after backporting the change to various release branches, as this flakiness fix now will need to be backported too.
I verified that this test is no longer flaky by running:
```
go test -count 10 -race vitess.io/vitess/go/vt/vtexplain
```
N/A
-   [x] If this change is to be back-ported to previous releases, a …
> Fix flakiness in `vtexplain` unit test case.

- go/vt/vtgate/engine/dml_with_input.go
- go/vt/vtgate/engine/dml_with_input_test.go
- go/vt/vtgate/engine/fake_vcursor_test.go
This PR fixes the calculation for rows affected for a update query with multi table when a column is updated with non-literal value.
- Fixes https://github.com/vitessio/vitess/issues/16171
> fix: rows affected count for multi table update for non-literal column value

- go/test/endtoend/vtgate/transaction/twopc/main_test.go
- go/test/endtoend/vtgate/transaction/twopc/schema.sql
- go/test/endtoend/vtgate/transaction/twopc/twopc_test.go
- go/test/endtoend/vtgate/transaction/twopc/vschema.json
- go/vt/vttablet/tabletserver/twopc.go
- test/config.json
This PR adds some basic tests when transaction_mode is set to `twopc`. 
This PR also fixes an issue on query initialization related to twopc on vttablet startup.
> Adding Distributed Transaction Test

- go/test/endtoend/vtgate/queries/misc/misc_test.go
- go/test/endtoend/vtgate/queries/misc/schema.sql
- go/vt/vtgate/evalengine/compiler.go
- go/vt/vtgate/planbuilder/operator_transformers.go
- go/vt/vtgate/planbuilder/operators/distinct.go
- go/vt/vtgate/planbuilder/operators/filter.go
- go/vt/vtgate/planbuilder/operators/hash_join.go
- go/vt/vtgate/planbuilder/operators/insert.go
- go/vt/vtgate/planbuilder/operators/join.go
- go/vt/vtgate/planbuilder/operators/projection.go
- go/vt/vtgate/planbuilder/operators/queryprojection.go
- go/vt/vtgate/planbuilder/operators/sharded_routing.go
- go/vt/vtgate/planbuilder/operators/union_merging.go
- go/vt/vtgate/planbuilder/operators/update.go
- go/vt/vtgate/planbuilder/plancontext/planning_context.go
- go/vt/vtgate/planbuilder/plancontext/planning_context_test.go
- go/vt/vtgate/semantics/semantic_state.go
During expression execution with the evaluation engine, columns marked as not nullable are not checked for null values. However, an issue arose when columns from an outer table, which can be null, were incorrectly assumed to be non-nullable. This led to a null pointer panic.
To address this, the solution involves remembering the tables on the outer side during planning and marking any columns from these tables as nullable. This ensures proper null handling and prevents runtime panics.
Example query:
```sql
SELECT * 
FROM t1 LEFT JOIN tbl ON t1.id2 = tbl.id 
WHERE t1.id1 = 6 OR tbl.nonunq_col = 6
```
This query would previously cause a null pointer panic due to the incorrect nullability assumption.
* Track outer tables during the planning phase.
* Mark columns from outer tables as nullable …
> Handle Nullability for Columns from Outer Tables

- go/test/endtoend/vreplication/migrate_test.go
- go/test/endtoend/vreplication/vdiff2_test.go
- go/test/endtoend/vreplication/vdiff_helper_test.go
Fixes two flaky tests:
1. Address the`VDiff stop` test which also regularly fails locally. The problem here is that we are trying to stop a vdiff which completes before it can be stopped. `vtctldclient` is generally much faster and we have virtually no data to diff so there's not really any way to avoid this race. So we consider `stopped` and `completed` to be valid/acceptable.
2. Fixes `TestVtctldMigrate` e2e test.
After https://github.com/vitessio/vitess/pull/15977 the target also has denied tables and hence we need to query the tablets directly rather than check via vtgate. …
> CI flaky test: Fix flakiness in vreplication_migrate_vdiff2_convert_tz

- go/vt/vtexplain/testdata/multi-output/selectsharded-output.txt
- go/vt/vtgate/planbuilder/operators/query_planning.go
- go/vt/vtgate/planbuilder/operators/query_planning_test.go
- go/vt/vtgate/planbuilder/operators/subquery.go
- go/vt/vtgate/planbuilder/testdata/aggr_cases.json
- go/vt/vtgate/planbuilder/testdata/filter_cases.json
- go/vt/vtgate/planbuilder/testdata/info_schema57_cases.json
- go/vt/vtgate/planbuilder/testdata/info_schema80_cases.json
- go/vt/vtgate/planbuilder/testdata/select_cases.json
- go/vt/vtgate/planbuilder/testdata/tpch_cases.json
This pull request introduces an optimization to our query planner by adding a `LIMIT 1` clause to `EXISTS` subqueries. This change aims to minimize the amount of data being transferred over the wire, resulting in improved performance and reduced resource consumption.
- **Optimization Addition**: Added a `LIMIT 1` clause to all `EXISTS` subqueries generated by the planner.
- **Impact**: The optimization reduces the amount of data sent over the network and processed by the database, improving overall query performance.
Before Optimization:
```sql
SELECT * FROM orders o WHERE EXISTS (SELECT 1 FROM order_items oi WHERE oi.order_id = o.id);
```
After Optimization:
```sql
SELECT * FROM orders o WHERE EXISTS (SELECT 1 FROM order_items oi WHERE oi.order_id = o.id LIMIT 1);
```
Our planner used to …
> feat: add a LIMIT 1 on EXISTS subqueries to limit network overhead

- go/cmd/vtctldclient/command/vreplication/vdiff/vdiff.go
This PR fixes incorrect display of multiple vdiffs for a keyspace/workflow, caused by incorrect initialization of a loop variable.
This was introduced in https://github.com/vitessio/vitess/pull/13976, part of v18, hence backporting upto v18.
See https://github.com/vitessio/vitess/issues/16176 for repro. 
Before this PR:
```
+-----------------------------------------+----------------------+-------------+----------+--------------+
|                                    UUID |             Workflow |    Keyspace |    Shard |        State |
+=========================================+======================+=============+==========+==============+
|    c8de5570-5cfe-4d3e-91f7-0d01b2030525 |    commerce2customer |    customer |        0 |    completed | …
```
> VDiff CLI: Fix VDiff `show` bug

- go/test/endtoend/vtgate/foreignkey/stress/fk_stress_test.go
This PR increases the migration cut-over lock timeout in foreign key stress tests, to reduce flakiness caused by timeouts.
It also reduces migration check interval giving the Online DDL scheduler more opportunity to force cut-over the migration.
No issue. Reducing CI flakiness.
> CI: increase timeout for  Online DDL foreign key stress tests

- go/test/endtoend/onlineddl/flow/onlineddl_flow_test.go
Quick followup to https://github.com/vitessio/vitess/pull/16017: there was an assumption that by the end of 3sec into the migration, this would hold:
```go
assert.GreaterOrEqual(t, appliedDMLEnd-appliedDMLStart, int64(maxTableRows))
```
Normally that's correct, the number is actually 3 times larger than `int64(maxTableRows)` on GitHub CI. And yet, this is a source for flakiness on smaller testing runners.
This PR opts to actually _wait_ for that value, with a max timeout of `1min`, which is currently 60 times more than needed in GitHub CI, and still with high margins in slower runners.
#16017
-   [ ] If this change is to be back-ported to previous releases, a justification is included in …
> CI: wait-for rather than 'assume' in Online DDL flow

- go/cmd/vttestserver/cli/main_test.go
- go/vt/vttest/environment.go
Some tests like `TestCanGetKeyspaces` have been flaky. They occasionally end up panicking - 
```
2024-06-13T08:34:17.3101964Z --- FAIL: TestCanGetKeyspaces (12.89s)
2024-06-13T08:34:17.3102209Z panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2024-06-13T08:34:17.3102594Z 	panic: runtime error: invalid memory address or nil pointer dereference
2024-06-13T08:34:17.3102810Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16d5060]
2024-06-13T08:34:17.3102825Z 
2024-06-13T08:34:17.3102924Z goroutine 957 [running]:
2024-06-13T08:34:17.3103056Z testing.tRunner.func1.2({0x1859800, 0x2d13550})
2024-06-13T08:34:17.3103371Z 	/opt/actions-runner/_work/_tool/go/1.22.4/x64/src/testing/testing.go:1631 +0x24a
2024-06-13T08:34:17.3103465Z …
```
> Fix flaky tests that use vtcombo

- go/cmd/vttestserver/cli/main_test.go
This PR further fixes more flakiness in `TestCanGetKeyspaces`. It was noticed in the CI - 
```
I0618 04:44:44.442798   13689 main.go:332] Local cluster started.
main_test.go:467:
Error Trace:	/opt/actions-runner/_work/vitess/vitess/go/cmd/vttestserver/cli/main_test.go:467
/opt/actions-runner/_work/vitess/vitess/go/cmd/vttestserver/cli/main_test.go:254
Error:      	Received unexpected error:
rpc error: code = DeadlineExceeded desc = context deadline exceeded
Test:       	TestCanGetKeyspaces
```
The problem was that we created a context with timeout in the start before the cluster was setup. The cluster setup can take more than 10 seconds, especially in the CI. So, we should be creating the context after the cluster setup is complete.
-   [x] "Backport to:" labels have been added if this …
> Flaky test fix `TestCanGetKeyspaces`

- go/test/endtoend/vreplication/config_test.go
- go/test/endtoend/vreplication/fk_ext_test.go
- go/test/endtoend/vreplication/fk_test.go
- go/test/endtoend/vreplication/partial_movetables_test.go
- go/test/endtoend/vreplication/vdiff2_test.go
- go/test/endtoend/vreplication/vreplication_test.go
- go/vt/vtctl/workflow/traffic_switcher.go
- go/vt/vtctl/workflow/traffic_switcher_test.go
- go/vt/vttablet/tabletserver/schema/engine.go
- tools/unit_test_race.sh
This work ensures that VReplication — when initializing sequence tables during a traffic switch — handles any escaped identifiers (by unescaping them) that may be in the vschema while continuing to ensure that they are escaped when using them in SQL queries.
This PR also moves more of the VReplication endtoend tests to `vtctldclient` as we  now escape the backing sequence table `customer_seq` references in the test vschemas and the `vtctlclient` (wrangler) implementation remains unchanged as it's long deprecated and should be removed entirely in v21 or v22.
I think that this is worth back porting to the latest GA release (v20), for RC2 if we can.
- Fixes: https://github.com/vitessio/vitess/issues/16160
-   [x] "Backport to:" labels have been added if this change should be back-ported to …
> VReplication: handle escaped identifiers in vschema when initializing sequence tables

- go/vt/vttablet/tabletmanager/rpc_vreplication.go
- go/vt/vttablet/tabletmanager/rpc_vreplication_test.go
This PR fixes a bug where a workflow which has been stopped during the copy phase has its published state (observable at `debug/vars` set incorrectly to Running when it is restarted.  We now check for tables still pending copy and update the stream state to `Copying` or `Running` based on whether we are still in the copy phase.
This issue has been around for about 15 months, so backporting to all supported versions.
https://github.com/vitessio/vitess/issues/15337
-   [ ] Did the new or modified tests pass consistently locally and …
> VReplication Workflow: set state correctly when restarting workflow streams in the copy phase

- go/test/endtoend/vtgate/foreignkey/stress/fk_stress_test.go
Adding a self referencing table to the foreign key stress tests. The self referencing table goes through mostly the same tests as other tables, but note:
- Not testing `ON DELETE CASCADE` nor `ON UPDATE CASCADE` as these create a multitude of unexpected scenarios where collected metrics cannot be validated.
- We avoid creating loops. We ensure a row can only point to itself or upwards, but never downwards.
- Closes https://github.com/vitessio/vitess/issues/16215
- https://github.com/vitessio/vitess/pull/16205
- https://github.com/vitessio/vitess/issues/11975
-   [ ] Tests …
> CI: testing self referencing tables in foreign key stress tests

- changelog/20.0/20.0.0/changelog.md
- changelog/20.0/20.0.0/release_notes.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/401_scheduled_backups.yaml
- examples/operator/operator.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v20.0.0-RC2` release. Once this PR is merged, we will be able to tag `v20.0.0-RC2` on the merge commit.
> [release-20.0-rc] Release of `v20.0.0-RC2`

- changelog/20.0/20.0.0/changelog.md
- changelog/20.0/20.0.0/release_notes.md
This Pull Request copies the release notes found on `release-20.0-rc` to keep release notes up-to-date after the `v20.0.0-RC2` release.
> [main] Copy `v20.0.0-RC2` release notes

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v20.0.0-SNAPSHOT) after the release of v20.0.0-RC2.
> [release-20.0-rc] Bump to `v20.0.0-SNAPSHOT` after the `v20.0.0-RC2` release

- go/vt/vtgate/planbuilder/operator_transformers.go
- go/vt/vtgate/planbuilder/operators/aggregator.go
- go/vt/vtgate/planbuilder/operators/distinct.go
- go/vt/vtgate/planbuilder/operators/filter.go
- go/vt/vtgate/planbuilder/operators/ordering.go
- go/vt/vtgate/planbuilder/operators/plan_query.go
- go/vt/vtgate/planbuilder/operators/route.go
- go/vt/vtgate/planbuilder/operators/union.go
- go/vt/vtgate/planbuilder/testdata/aggr_cases.json
- go/vt/vtgate/planbuilder/testdata/cte_cases.json
- go/vt/vtgate/planbuilder/testdata/memory_sort_cases.json
- go/vt/vtgate/planbuilder/testdata/postprocess_cases.json
- go/vt/vtgate/planbuilder/testdata/select_cases.json
- go/vt/vtgate/planbuilder/testdata/tpch_cases.json
- go/vt/vtgate/planbuilder/testdata/union_cases.json
The Vitess planner was previously unable to handle UNION queries that included literals, resulting in an error. For example, the following query:
```sql
select 'a' as type, 0 as id from user group by 2 
union all 
select 'c' as type, 0 as id from user_extra as t
```
Results in:
```
VT12001: unsupported: argument offsets did not line up for UNION
```
To address this issue, the solution ensures that all operators that truncate columns actually perform the truncation during the planning phase. This alignment guarantees that the argument offsets match correctly for UNION queries, preventing the aforementioned error.
Fixes #16228
-   [ ] If this change is to be back-ported to previous …
> Correct Handling of UNION Queries with Literals in the Vitess Planner

- changelog/20.0/20.0.0/summary.md
Updating v20-related release notes for clarity.
Adding backport label as well to keep in sync.
> release notes: update dml related release notes

- go/vt/vtctl/workflow/materializer_test.go
- go/vt/vtctl/workflow/server.go
[`LookupVindex create`](https://vitess.io/docs/reference/programs/vtctldclient/vtctldclient_lookupvindex/vtctldclient_lookupvindex_create/) will now re-use existing vschema entries (Vindex, and ColumnVindex) if they are exactly the same as the ones we want to create (it would already re-use the target table). This makes it easier/nicer to use as the artifact creation is idempotent across [`cancel`](https://vitess.io/docs/reference/programs/vtctldclient/vtctldclient_lookupvindex/vtctldclient_lookupvindex_cancel/) and [`create`](https://vitess.io/docs/reference/programs/vtctldclient/vtctldclient_lookupvindex/vtctldclient_lookupvindex_create/) commands.
Since the unit test was refactored a bit here, I also went ahead and fixed https://github.com/vitessio/vitess/issues/8653 here as well since …
> VReplication: LookupVindex create use existing artifacts when possible

- go/cmd/vtctldclient/command/vreplication/lookupvindex/lookupvindex.go
- go/vt/vtctl/workflow/materializer_test.go
- go/vt/vtgate/vindexes/vschema.go
- go/vt/vtgate/vindexes/vschema_test.go
- go/vt/wrangler/materializer_test.go
When creating the `vtctldclient` implementation of the [`LookupVindex` command](https://vitess.io/docs/reference/programs/vtctldclient/vtctldclient_lookupvindex/) in https://github.com/vitessio/vitess/pull/14086, I added the ability to specify which vindex type to use with the `--table-vindex-type` flag. The `vtctlclient` client and its behavior is now frozen as it's deprecated and slated for removal so that will not be modified.
By default, however, we would still use `md5` by default for text based column types (we had changed the default/recommended vindex type for integral column types in #13955 and #13956). This PR moves the md5 based recommendations to `xxhash` based ones as `md5` for passwords is considered insecure ([1](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-ana …
> VIndexes: Stop recommending md5 based vindex types as md5 is considered insecure

- go/vt/vtgate/planbuilder/operators/aggregation_pushing_helper.go
This PR only backports the vtgate crash fix from https://github.com/vitessio/vitess/pull/16237. 
- Fixes https://github.com/vitessio/vitess/issues/16238
> [release-20.0] Fix vtgate crash in group concat

- go/sqltypes/value.go
- go/sqltypes/value_test.go
- go/vt/binlog/binlogplayer/binlog_player_test.go
- go/vt/sqlparser/ast_format.go
- go/vt/sqlparser/parse_test.go
- go/vt/sqlparser/testdata/select_cases.txt
- go/vt/vtgate/planbuilder/testdata/select_cases.json
- go/vt/vttablet/tabletmanager/rpc_vreplication_test.go
- go/vt/vttablet/tabletmanager/vdiff/action_test.go
- go/vt/vttablet/tabletmanager/vdiff/engine_test.go
- go/vt/vttablet/tabletmanager/vreplication/insert_generator_test.go
- go/vt/vttablet/tabletmanager/vreplication/journal_test.go
- go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go
- go/vt/wrangler/materializer_test.go
- go/vt/wrangler/resharder_test.go
- go/vt/wrangler/traffic_switcher_test.go
It's not necessary to escape a double quote since we quote everything with single quotes. This removes a lot of escaping noise, especially around JSON usage.
> sqlparser: Remove unneeded escaping

- .github/workflows/static_checks_etc.yml
- go/vt/sqlparser/ast_format_fast.go
- tools/check_astfmtgen.sh
> Fix codegen

- go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
- go/vt/vtgate/planbuilder/operators/query_planning.go
- go/vt/vtgate/planbuilder/testdata/memory_sort_cases.json
This PR addresses an issue where incorrectly optimized query planning with `LIMIT` led to inaccurate results when `GROUP BY` was used on the vtgate side.
* Issue: When planning a query with `LIMIT`, our initial approach tried to reduce the number of rows sent over the wire. However, this optimization caused incorrect results in situations where GROUP BY was applied on the vtgate side. By pushing the `LIMIT` to the MySQL query, vtgate did not receive all the rows necessary for proper grouping and inspection.
* Fix: Adjust the logic to ensure `LIMIT` is not pushed down to MySQL queries in scenarios where vtgate needs to perform `GROUP BY`. This guarantees that all relevant rows are available for accurate grouping and aggregation.
Fixes #16262
-   [x] "Backport to:" labels have been added if …
> Fix Incorrect Optimization with LIMIT and GROUP BY

- changelog/20.0/20.0.0/summary.md
Adds VReplication section and entries to v20 summary doc.
> Release docs: Add vreplication related entries to the v20 summary

- changelog/20.0/20.0.0/changelog.md
- changelog/20.0/20.0.0/release_notes.md
This Pull Request copies the release notes found on `release-20.0-rc` to keep release notes up-to-date after the `v20.0.0` release.
> [release-20.0] Copy `v20.0.0` release notes

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v20.0.1-SNAPSHOT) after the release of v20.0.0.
> [release-20.0-rc] Bump to `v20.0.1-SNAPSHOT` after the `v20.0.0` release

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v20.0.1-SNAPSHOT) after the release of v20.0.0.
> [release-20.0] Bump to `v20.0.1-SNAPSHOT` after the `v20.0.0` release

- go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
In a recent PR, #16263 I added an end-to-end test that would not fail without the fixes. This PR changes that test to make sure it fails without the needed code changes.
The original issue was that we are limiting too much data, and the vtgate doesn't see all rows it should receive. To trigger this, we need the LIMIT in the query to be smaller than the number of rows returned by the shards.
#16263
> Make sure end to end test actually tests the fix

- changelog/19.0/19.0.0/release_notes.md
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/401_scheduled_backups.yaml
We overlooked the update to the release notes after fixing https://github.com/vitessio/vitess/issues/15452, and the operator examples are misleading by using the official mysql image for the mysql container instead of the `vitess/lite` image`
We must backport this to `release-19.0` and `release-20.0` where the issue was introduced. For each backport we will need to use the proper `vitess/lite` tag (`v19.0.4` and `v20.0.0` instead of `latest`).
The release notes on the GitHub UI will have to be updated once this is merged.
More information about the whole issue and reproduction can be seen on https://github.com/vitessio/vitess/issues/16281.
- Fixes https://github.com/vitessio/vitess/issues/16281
-   [x] "Backport to:" labels have been added if this change should be back-ported to release …
> Fix the `v19.0.0` release notes and use the `vitess/lite` image for the MySQL container

- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/401_scheduled_backups.yaml
- examples/operator/operator.yaml
I did not think about this situation while re-working the vitess-releaser tool: since we now have two branches for `release-20.0` but we do all release work on `release-20.0-rc` some stuff were forgotten on the `release-20.0` branch like updating the version of vitess used in our tests and examples.
It is a cherry-pick of https://github.com/vitessio/vitess/pull/16258.
Ideally we should have cherry-picked every Release PRs (for RC-1, RC-2 and GA) to `release-20.0` when they got merged.
> [release-20.0] Update post release `v20.0.0`

- go/test/endtoend/vtgate/queries/subquery/subquery_test.go
- go/test/endtoend/vtgate/schematracker/sharded/st_sharded_test.go
Vitess 16 is EOL, and as I understand tests are only run one version above and below anyway.
> test: Remove unreachable test skipping

- .golangci.yml
- go/test/endtoend/backup/vtctlbackup/backup_utils.go
- go/test/endtoend/vreplication/helper_test.go
- go/vt/vtctl/workflow/utils_test.go
This fixes some usages of math/rand and replaces it with math/rand/v2. It also adds a linter check to ensure we don't add new cases anymore.
Followup to #15513 but also enforces no regressions here. 
> No usage of math/rand

- go/vt/vtctl/workflow/framework_test.go
- go/vt/vtctl/workflow/resharder.go
- go/vt/vtctl/workflow/resharder_test.go
- go/vt/vtctl/workflow/server.go
In the [`vtctldclient Reshard` command](https://vitess.io/docs/reference/programs/vtctldclient/vtctldclient_reshard/), we were not checking that the target shard had a primary tablet in the shard record before we attempted to access it. This resulted in a client panic when doing a `Reshard` and a target shard did not have a primary tablet. The `Reshard` would have failed anyway, but obviously we should not panic.
The new test case fails on main this way:
```
❯ go test -v -timeout 30s -run ^TestReshardCreate$ vitess.io/vitess/go/vt/vtctl/workflow
=== RUN   TestReshardCreate
=== RUN   TestReshardCreate/basic
W0627 13:20:10.626498   71963 server.go:1753] Streams will not be started since --auto-start is set to false
resharder_test.go:158: ReshardCreate response: …
```
> VReplication: Properly handle target shards w/o a primary in Reshard

- .github/workflows/local_example.yml
- .github/workflows/region_example.yml
The local and region examples already install the node version needed by vtadmin in their scripts. Plus the node install step was not working since the `NVM_DIR` variable was not set, resulting in the script to anyway download node.
> Remove unnecessary node install step in local/region examples workflow

- changelog/20.0/20.0.0/release_notes.md
- changelog/20.0/20.0.0/summary.md
- go/vt/vttablet/tabletserver/query_engine.go
This PR modifies the v20 release notes to mention that `QueryCacheXX` does not refer to an actual query cache but rather to a query plan cache.
The metrics will be renamed in v21 through https://github.com/vitessio/vitess/pull/16289.
Let's backport this to v20 for the release notes.
- Follow up of https://github.com/vitessio/vitess/pull/14947
> Add a note on `QueryCacheHits` and `QueryCacheMisses` in the release notes

- go/vt/vttablet/tabletmanager/vdiff/table_plan.go
- go/vt/vttablet/tabletmanager/vdiff/utils.go
- go/vt/vttablet/tabletmanager/vdiff/workflow_differ_test.go
In https://github.com/vitessio/vitess/issues/15403 we added experimental support for moving tables from a multi-tenant environment (database per tenant, each with the same schema). 
You would do that by specifying a column on the table(s) representing the tenant identifier in the target VSchema and then specifying a tenant identifier value using [`MoveTables create --tenant-id=<val>`](https://vitess.io/docs/reference/programs/vtctldclient/vtctldclient_movetables/vtctldclient_movetables_create/). You can see an example here: https://github.com/vitessio/vitess/issues/16305#issuecomment-2200745054
There is an optional `--shards <shards>` flag for [`MoveTables create`](https://vitess.io/docs/reference/programs/vtctldclient/vtctldclient_movetables/vtctldclient_movetables_create/) that would …
> VDiff: Copy non in_keyrange workflow filters to target tablet query

- go/cmd/vtctldclient/command/vschemas.go
- go/test/endtoend/backup/vtctlbackup/backup_utils.go
- go/test/endtoend/cluster/vtctldclient_process.go
- go/test/endtoend/recovery/pitr/shardedpitr_test.go
- go/test/endtoend/tabletgateway/buffer/reshard/sharded_buffer_test.go
- go/test/endtoend/tabletmanager/commands_test.go
- go/vt/tableacl/tableacl.go
- go/vt/vtctl/endtoend/get_schema_test.go
- go/vt/vtctl/vtctl.go
- go/vt/vtctl/workflow/traffic_switcher.go
- go/vt/vtexplain/vtexplain_vtgate.go
- go/vt/vtgate/planbuilder/fuzz.go
- go/vt/vtgate/sandbox_test.go
- go/vt/vtgate/vindexes/vschema.go
- go/vt/vtgate/vindexes/vschema_test.go
- go/vt/vttablet/tabletserver/vstreamer/planbuilder_test.go
- go/vt/vttablet/tabletserver/vstreamer/testenv/testenv.go
- go/vt/wrangler/materializer.go
- go/vt/wrangler/traffic_switcher.go
In https://github.com/vitessio/vitess/pull/16096 we added `UnmarshalPB` for adding type safety while deserializing proto objects. That PR only updated the routing rules related code.
In this PR we update move uses of `Unmarshal` over, which deserialize protos.
https://github.com/vitessio/vitess/issues/16095
https://github.com/vitessio/vitess/pull/16096
>  [cleanup] Protos: Use UnmarshalPB() when unmarshalling a proto object

- .github/workflows/docker_build_images.yml
- docker/binaries/vtctldclient/Dockerfile
Introduces the `vtctldclient` image.
`vtctldclient` is a typed replacement of `vtctlclient` which has been deprecated since Vitess v18. A `vtctlclient` image has continued to be published however and a `vtctldclient` image is absent from the projects published images. This introduces `vtctldclient` to resolve this and so that `vtctlclient` can be removed at a later point.
Fixes #16288
- Note: this adds a …
> Add `vtctldclient` container image

- go/test/endtoend/onlineddl/flow/onlineddl_flow_test.go
- go/test/endtoend/onlineddl/vrepl_suite/onlineddl_vrepl_suite_test.go
Submitting two changes in Online DDL CI for things I stumbled upon:
1. In "Online DDL flow" CI, used in Upgrade/Downgrade - wasn't waiting properly for migration to complete, escalating the termination logic. The existing logic still works, but ends up force-terminating the migration rather than waiting gracefully.
2. In Online DDL vrepl suite, we now recognize the `$ONLINEDDL_SUITE_TEST_FILTER` environment variable. If set, then we skip any tests not containing the value of `$ONLINEDDL_SUITE_TEST_FILTER`. If unset, then it is the empty string and trivially all test names contain the empty string.
This is just in a way of making debugging/developing easier.
None really.
-   [ ] If this …
> A couple changes in Online DDL CI

- .github/workflows/codeql_analysis.yml
- .github/workflows/upgrade_downgrade_test_backups_e2e.yml
- .github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml
- .github/workflows/upgrade_downgrade_test_backups_manual.yml
- .github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
- .github/workflows/upgrade_downgrade_test_onlineddl_flow.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml
- .github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml
- .github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml
- .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml
- .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml
- docker/bootstrap/Dockerfile.mysql57
- docker/bootstrap/Dockerfile.percona57
- docker/utils/install_dependencies.sh
- test/templates/cluster_endtoend_test_mysql57.tpl
- test/templates/dockerfile.tpl
CI workflows that installed XtraBackup 2.4 no longer worked as there is now a required step for installing XtraBackup that they were not doing: `percona-release enable-only tools` (see [step #3 in the docs](https://docs.percona.com/percona-xtrabackup/2.4/installation/apt_repo.html)).
In this PR we make the following changes:
1. Remove XtraBackup related steps entirely in the workflows that don't and will not actually use XtraBackup.
2. For workflows that may use XtraBackup (e.g. a backup related workflow), we install XtraBackup 8.0 when the workflow is using MySQL 8.0.
3. For workflows that are using XtraBackup, we add this additional command/step.
This should be backported to all release branches because w/o doing it all PRs will be blocked on that branch.
-   [x] "Backport to:" labels …
> CI: Fix for xtrabackup install failures

- go/vt/schemadiff/column.go
- go/vt/schemadiff/table.go
This PR does some internal refactoring/cleanup without changing behavior. We give `ColumnDefinitionEntity` some more brainpower, cleanup column diffing (introducing `SetExplicitCharsetCollate` and simplifying `ColumnDiff()`.
As part of https://github.com/vitessio/vitess/issues/16229
> `schemadiff` small internal refactor: formalizing column charset/collation

- go/vt/vttablet/tabletserver/dt_executor.go
- go/vt/vttablet/tabletserver/dt_executor_test.go
- go/vt/vttablet/tabletserver/tabletserver.go
- go/vt/vttablet/tabletserver/twopcz.go
This PR reject distributed transaction prepare on reserved connection. These are the connection that are using temporary tables or locking feature. They are not safe to allow support for atomic commit.
- #16245 
> Fail on prepare of reserved connection 

- docker/utils/install_dependencies.sh
After merging https://github.com/vitessio/vitess/pull/16329 we realized the docker build were failing due to an unknown command, this fixes it.
> Fix the install dependencies script in Docker

- Makefile
- removed `docker_local` from makefile as instructed from the discussion -
https://github.com/vitessio/website/pull/1777
> Remove docker_local from Makefile

- go/mysql/encoding.go
- go/mysql/encoding_test.go
This employs a couple tricks that combined seemed fruitful:
* Swapping to binary.LittleEndian.Put* on the basic calls gets us a free
boost while removing code. The main win from this swap is the slice
boundary check, resulting in a massive boost. I kept it inlined, but
added my own boundary checking in `writeLenEncInt` since swapping it
out here resulted in a very minor performance regression from the
current results. I assume from the extra coersion needed to the uint*
type, and another reslice.
* Reslicing the byte slice early so all future operations work on
0-index rather than pos+ indexing. This seemed to be a pretty sizeable
win without needing to do more addition on every operation later to
determine the index, they get swapped out for constants.
* Read path employs the same early …
> go/mysql: performance optimizations in protocol encoding

- changelog/21.0/21.0.0/summary.md
- go/flags/endtoend/vtcombo.txt
- go/flags/endtoend/vtgate.txt
- go/test/endtoend/vtgate/connectiondrain/main_test.go
- go/vt/vtgate/plugin_mysql_server.go
This PR adds the release notes for the changes implemented by https://github.com/vitessio/vitess/pull/16298.
It also changes the flag to use dashes instead of underscores.
- Related to https://github.com/vitessio/vitess/issues/15971
> Add release notes for the new connection drain (+ use dashes instead of underscore)

- go/vt/vtctl/reparentutil/emergency_reparenter.go
- go/vt/vtctl/reparentutil/planned_reparenter.go
- go/vt/vtctl/reparentutil/planned_reparenter_flaky_test.go
- go/vt/vtctl/reparentutil/util.go
This PR makes the 2 following changes - 
1. Removes unused parameters from a lot of function calls.
2. Adds `CheckShardLocked` calls to PRS and ERS code after a RPC has run to ensure we don't end up running any RPC without holding the shard lock.
> Remove unused parameters in reparent code and add CheckLockShard calls

- go/vt/vtgate/planbuilder/testdata/from_cases.json
- go/vt/vtgate/semantics/early_rewriter.go
- go/vt/vtgate/semantics/early_rewriter_test.go
Small refactoring - an `ORDER BY` inside a derive table means nothing if it's not also accompanied with a `LIMIT`. The only way to guarantee sort order on the output is to add an `ORDER BY` to the outer `SELECT`.
This PR adds code that removes these clauses early during semantic analysis, so that later planner phases are not confused by them.
> feat: remove ORDER BY from inside derived table

- go/test/endtoend/vtgate/vitess_tester/aggregation/aggregation.test
- go/vt/vtgate/planbuilder/operators/aggregator.go
- go/vt/vtgate/planbuilder/operators/horizon_expanding.go
- go/vt/vtgate/planbuilder/operators/projection.go
- go/vt/vtgate/planbuilder/operators/queryprojection.go
- go/vt/vtgate/planbuilder/operators/route.go
- go/vt/vtgate/planbuilder/testdata/aggr_cases.json
This PR addresses an issue where executing a specific query involving a derived table and an ORDER BY clause results in an `Unknown column 'id' in 'field list'` error. The problem was due to the subquery rewritten by vtgate not returning the required id column.
Fixes #16226
> planner: Handle ORDER BY inside derived tables

- go/mysql/conn.go
- go/mysql/encoding.go
- go/mysql/encoding_test.go
This isn't a super common path, but if we are tracking GTIDs, this will happen for every single query.
This enhancement effectively calculates the full size of the GTID data to be encoded up front to do a single allocation rather than naively appending to a slice.
I also added documentation and extracted the GTID encoding to it's own function with unit tests.
I also cleaned up how it's utilized to avoid some unnecessary byte -> string allocations within the packet writer.
```
$ benchstat {old,new}.txt
goos: darwin
goarch: arm64
pkg: vitess.io/vitess/go/mysql
│   old.txt    │               new.txt               │
│    sec/op    │   sec/op     vs base                │
EncGtidData-10   104.65n ± 1%   15.55n ± 0%  -85.14% (p=0.000 n=10)
│   old.txt   │              new.txt               │
│ …
```
> go/mysql: improve GTID encoding for OK packet

- go/mysql/encoding.go
This is implemented as the same performance optimization, but is a more clear intention.
Iteration from https://github.com/vitessio/vitess/pull/16341
> go/mysql: use clear builtin for zerofill

- web/vtadmin/src/components/pips/Pip.module.scss
- web/vtadmin/src/components/pips/Pip.tsx
- web/vtadmin/src/components/pips/StreamStatePip.tsx
- web/vtadmin/src/components/routes/Workflows.tsx
- web/vtadmin/src/components/routes/workflow/Workflow.module.scss
- web/vtadmin/src/components/routes/workflow/Workflow.tsx
- web/vtadmin/src/components/routes/workflow/WorkflowStreams.tsx
When a VReplication workflow is throttled, the app that caused the throttling and the time of the last throttle are recorded in the `_vt.vreplication` table. Currently those attributes are only shown in the json output tab of the workflow screen and are not easy to find. 
The throttler app and time are not reset once throttling has ended. So we only show a stream as throttled if it is within (currently) a minute. The throttler is updating this row on each check (every 250ms - 1s).
This PR changes the status color for a throttled running workflow to black and adds the throttler details (app name and time since throttled) to the summary workflow tooltip and to the streams details section.
It also adds a new internal link in the header to scroll down to the Streams section for convenience …
> VTAdmin: Show throttled status in workflows

- go/vt/vttablet/tabletserver/throttle/throttler_test.go
A quick followup to https://github.com/vitessio/vitess/pull/15988
Though tested for literally _months_ in CI and locally, we now see a flaky test caused by https://github.com/vitessio/vitess/pull/15988. The reason for the failure is that the test configures the throttler to be enabled, while at the same time attempts to disable it.
The fix is to explicitly configure the throttler to be disabled at the end of the test.
https://github.com/vitessio/vitess/issues/15624
-   [ ] Did the new or modified tests pass consistently locally …
> Throttler flaky test: explicitly disabling throttler so as to ensure it does not re-enable

- go/test/endtoend/vtcombo/vttest_sample_test.go
- go/vt/vtcombo/tablet_map.go
Ensures that a VSchema exists whenever a keyspace is created by VTCombo
Fixes https://github.com/vitessio/vitess/issues/16088
None
> VTCombo: Ensure VSchema exists when creating keyspace

- .github/workflows/upgrade_downgrade_test_semi_sync.yml
- config/mycnf/mysql8026.cnf
- config/mycnf/mysql84.cnf
- go/test/endtoend/reparent/semisync/semi_sync_test.go
As pointed out in https://github.com/vitessio/vitess/issues/16300, specifically https://github.com/vitessio/vitess/issues/16300#issuecomment-2210529168 outlines the steps that can lead to downgrades from v20 to v19 vttablets as broken. 
The problem is that in v20 we started using new semi-sync plugins even though v19 didn't support them. The fix is that we should continue to use the old semi-sync plugins in v20 while still adding the code to handle the new plugins. This way when we start using the new plugins in v21, upgrades and downgrades won't be broken.
This PR also adds a new workflow with a test that reproduces the problem and ensures that it is fixed by the changes in this PR. It also verifies that the new plugins work in v20.
No changes on `main` are required. The fix is v20 …
> Fix Downgrade problem from v20 in semi-sync plugin

- go/cmd/vttestserver/cli/main.go
- go/flags/endtoend/vttestserver.txt
- go/vt/vttest/local_cluster.go
- go/vt/vttest/vtprocess.go
This PR fixes a bug that causes vttestserver to parse the `--queryserver-config-transaction-timeout` incorrectly. This should be backported all the way to v19.
Fixes https://github.com/vitessio/vitess/issues/16337
> parse transaction timeout as duration

- go/vt/schema/online_ddl.go
- go/vt/schema/online_ddl_test.go
- go/vt/schema/parser.go
- go/vt/schema/parser_test.go
- go/vt/vtgate/engine/revert_migration.go
This is a long overdue cleanup PR, removing support for a long since unused `revert` syntax.
To revert a migration, we use this syntax: `revert vitess_migration '<uuid'>`.
When revert was first introduced, we used this syntax: `revert <uuid>`. This syntax is not being used in over 3 years now since the [new syntax was introduced](https://github.com/vitessio/vitess/pull/7656).
This PR cleans up support of the old syntax.
- https://github.com/vitessio/vitess/pull/7656
- https://github.com/vitessio/vitess/pull/7478
- https://github.com/vitessio/vitess/issues/6926
-   [ ] Tests …
> Online DDL: remove legacy (and ancient) 'REVERT <uuid>' syntax

- go/cmd/vtctldclient/command/shards.go
When attempting to use this command to clear up errant topo data, it was realized that the help output for the flag was unclear and misleading. I've tried to make the help text clear based on following the code to see what the flags actually do. 
> SetShardTabletControl: Improve flag help output

- go/test/endtoend/vtgate/vitess_tester/aggregation/aggregation.test
- go/vt/vtgate/planbuilder/operators/SQL_builder.go
- go/vt/vtgate/planbuilder/operators/horizon_expanding.go
- go/vt/vtgate/planbuilder/operators/queryprojection.go
- go/vt/vtgate/planbuilder/testdata/aggr_cases.json
- go/vt/vtgate/planbuilder/testdata/cte_cases.json
For queries doing aggregation inside derived tables, the planner sometimes struggled with which columns are available.
This PR makes sure to handle these queries well.
Fixes #16367
> fix issue with aggregation inside of derived tables

- go/test/endtoend/vtgate/vitess_tester/join/join.test
- go/test/endtoend/vtgate/vitess_tester/join/vschema.json
- go/vt/vtgate/planbuilder/operators/SQL_builder.go
- go/vt/vtgate/planbuilder/testdata/from_cases.json
This PR addresses a bug in Vitess where, upon successfully merging three tables into a single Route, the join predicates were sometimes not cleaned up correctly. This issue affects all supported versions of Vitess. Given the minimal nature of the fix, it is recommended to backport this fix to all affected versions.
Fixes #16387
> Fix Join Predicate Cleanup Bug in Route Merging

- .github/workflows/upgrade_downgrade_test_semi_sync.yml
- go/test/endtoend/reparent/semisync/semi_sync_test.go
This PR adds the test that were added to release-20 in #16357 to main as well. The tests have their expectations changed slightly given that they are running on main where the default semi-sync plugin is going to be of `SOURCE` type instead of `MASTER`
> Add semi-sync plugin test in main

- go/vt/vtgate/vschema_manager.go
- go/vt/vtgate/vschema_manager_test.go
This PR fixes the panic found in https://github.com/vitessio/vitess/issues/16382.
This PR reproduced the panic as a unit test and then it fixes it. The problem is that we are using `FindRoutedTable` function to find the table which can fail to find the table if keyspace routing rules are present.
The fix is to not go through the `FindRoutedTable` function at all. In the `updateTableInfo` function, we already go over all the tables and add them to the keyspace map if the table doesn't exist when we populate the columns in `setColumns`. 
We should use this table map directly.
The use of `FindRoutedTable` would be justified if we were supporting cross-keyspace foreign keys. Since we don't support them, all the foreign key references are guaranteed to be to tables that exist in the tables of …
> Fix panic in schema tracker in presence of keyspace routing rules

- go/vt/vtgate/planbuilder/operators/aggregator.go
- go/vt/vtgate/planbuilder/operators/queryprojection.go
- go/vt/vtgate/planbuilder/testdata/aggr_cases.json
- go/vt/vtgate/planbuilder/testdata/unsupported_cases.json
This PR fixes the panic found in https://github.com/vitessio/vitess/issues/16397.
On investigation it was found that this panic was introduced in the changes in https://github.com/vitessio/vitess/pull/16049. This PR fixes the panic and also adds test cases to verify we are able to plan udf queries properly and fail in case we are unable to push them down to MySQL.
- Fixes #16397 
> Fix panic in user defined aggregation functions planning

- go/vt/vtgate/planbuilder/operators/horizon_expanding.go
- go/vt/vtgate/planbuilder/testdata/select_cases.json
- go/vt/vtgate/planbuilder/testdata/unsupported_cases.json
As pointed out in https://github.com/vitessio/vitess/issues/16401, the query that used to work before stopped working after the changes in https://github.com/vitessio/vitess/pull/16049.
This PR fixes this issue. Instead of failing the planning when we find a subquery with an aggregation that is used in an order by, we mark the error as a `NotSingleRouteErr`. This means that if we are able to merge everything into a single route, then it works as before, but fails if we are unsuccesful.
- Fixes #16401 
-   [x] Did the new or …
> Fix subquery planning having an aggregation that is used in order by as long as we can merge it all into a single route

- go/vt/vttablet/tabletserver/tabletenv/config.go
- go/vt/vttablet/tabletserver/tabletenv/config_test.go
A behavior change for the for `SchemaReloadInterval` and `SchemaChangeReloadTimeout` configuration options was introduced in: https://github.com/vitessio/vitess/pull/14733
Specifically here, as the value for either one is an empty string after reading the empty config file: https://github.com/vitessio/vitess/pull/14733/files#diff-ee5ffc675b719e69de7147068ab4ecf03f6d5db91a000d212a30f8ce61544691R424-R431
You can see it still on main today here: https://github.com/vitessio/vitess/blob/2e009e3e1d7a84b071926c18ad951f305ebf4cf9/go/vt/vttablet/tabletserver/tabletenv/config.go#L404-L420
This changed the effective defaults for these two configuration options when using config files and not specifying a value for them.
The end result is that we ended up incorrectly overriding the current/default …
> Use default schema reload config values when config file is empty

- go/vt/mysqlctl/xtrabackupengine.go
- go/vt/mysqlctl/xtrabackupengine_test.go
Instead of reading the GTIDs from the `xtrabackup` output, this will make use of the `--extra-lsndir` flag to output a copy of the `xtrabackup_info` file which has the full GTID information, instead of reading it from the `STDERR` where it eventually gets truncated after the line size gets close to ~8KB
Fixes #16303
> fixing issue with xtrabackup and long gtids

- go/vt/vtgate/vschema_manager.go
- go/vt/vtgate/vschema_manager_test.go
This is a backport of #16383
- Fixes https://github.com/vitessio/vitess/issues/16382
> [release-19.0] Fix panic in schema tracker in presence of keyspace routing rules (#16383)

- go/vt/vtgate/vschema_manager.go
- go/vt/vtgate/vschema_manager_test.go
This is a backport of #16383
- Fixes https://github.com/vitessio/vitess/issues/16382
> [release-20.0]  Fix panic in schema tracker in presence of keyspace routing rules (#16383)

- go/vt/vttablet/tabletserver/vstreamer/snapshot_conn.go
- go/vt/vttablet/tabletserver/vstreamer/tablestreamer.go
An alternative approach to https://github.com/vitessio/vitess/pull/16421, addressing https://github.com/vitessio/vitess/issues/16420.
It's really a completely different take: this PR disables the use of tracked session GTIDs, essentially undoing some of the work in #11061. VReplication table streamer and row streamer will only ever use the tried-and-true `flush tables with read lock` to capture a transactionally consistent GTID.
There are multiple reasons here. First, the discrepancy of behavior we have right now between different flavors of MySQL, and across different CI jobs. This makes debugging and reproducibility more difficult to handle, and we've struggled with this for a while.
Next, and what actually kicks this work, is we're seeing a bug, and incorrect value for the tracked …
> VReplication: disable use of `session_track_gtids`

- go/vt/vtgate/planbuilder/select.go
- go/vt/vtgate/planbuilder/testdata/select_cases.json
Dual queries can most of the time be handled on the vtgate side, without having to send anything down to MySQL.
This PR extends this functionality to include `dual` queries with `LIMIT` in them.
> Handle dual queries with LIMIT on the vtgate

- go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
- go/test/endtoend/onlineddl/vtgate_util.go
- go/vt/vtgate/executor_test.go
- go/vt/vttablet/tabletserver/query_executor.go
See story in https://github.com/vitessio/vitess/issues/16242
Fixes https://github.com/vitessio/vitess/issues/16242
> Support `SHOW VITESS_MIGRATIONS` from inside a transaction

- config/mycnf/mysql84.cnf
Fixes #16425
`default_authentication_plugin` was removed starting in MySQL 8.4.0:
> The default_authentication_plugin system variable, deprecated in MySQL 8.0.27, is removed as of
> MySQL 8.4.0. Use authentication_policy instead.
>
> -- https://dev.mysql.com/doc/refman/8.4/en/mysql-nutshell.html
I used the same process for testing the new MySQL 8.4 configuration file as described in the issue #16425.
The binary versions were different:
```
[vitess@78ec5221d252 vitess]$ mysqlctld --version;
mysqlctld version Version: 21.0.0-SNAPSHOT (Git revision cb1ea513ebd55ba3b9d409a235ad42190ea98777 branch 'update-mysql-84-default-cnf') built on Thu Jul 18 03:49:22 UTC 2024 by vitess@78ec5221d252 using go1.22.5 linux/amd64
[vitess@78ec5221d252 vitess]$ mysqld --version
/usr/sbin/mysqld  Ver 8.4.1 for …
```
> fix: Use authentication_policy to specify default auth plugin for MySQL 8.4

- go/vt/schemadiff/schema_diff.go
- go/vt/schemadiff/schema_diff_test.go
Implements the optimization proposed in https://github.com/vitessio/vitess/issues/16434
This PR modifies the algorithm by optimizing it. I keeps all existing tests unchanged so as to prove that the modification does not change actual results.
https://github.com/vitessio/vitess/issues/16434
> `schemadiff`: optimize permutation evaluation

- go/vt/vtgate/engine/aggregations.go
- go/vt/vtgate/engine/hash_join.go
- go/vt/vtgate/engine/join.go
- go/vt/vtgate/engine/memory_sort.go
- go/vt/vtgate/engine/ordered_aggregate.go
- go/vt/vtgate/engine/scalar_aggregation.go
- go/vt/vtgate/engine/semi_join.go
Very small PR that just removes unnecessary JSON annotations on a few types.
> Remove JSON annotations

- .github/workflows/code_freeze.yml
- changelog/18.0/18.0.6/changelog.md
- changelog/18.0/18.0.6/release_notes.md
- changelog/18.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v18.0.6` release. Once this PR is merged, we will be able to tag `v18.0.6` on the merge commit.
> [release-18.0] Release of `v18.0.6`

- .github/workflows/code_freeze.yml
- changelog/19.0/19.0.5/changelog.md
- changelog/19.0/19.0.5/release_notes.md
- changelog/19.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v19.0.5` release. Once this PR is merged, we will be able to tag `v19.0.5` on the merge commit.
> [release-19.0] Release of `v19.0.5`

- changelog/19.0/19.0.5/changelog.md
- changelog/19.0/19.0.5/release_notes.md
- changelog/19.0/README.md
This Pull Request copies the release notes found on `release-19.0` to keep release notes up-to-date after the `v19.0.5` release.
> [main] Copy `v19.0.5` release notes

- go/test/endtoend/vtgate/vitess_tester/subquery/subquery.test
- go/vt/vtgate/planbuilder/operators/subquery.go
- go/vt/vtgate/planbuilder/testdata/select_cases.json
As described in https://github.com/vitessio/vitess/issues/16433, Vitess did not support complex expressions even in uncorrelated queries.
This PR adds this support. One change that we had to make was with how we add `:__sq_has_values` expression on IN and NOT IN subqueries. Previously we would add the clause after we replaced the subquery with a list argument. That worked well for cases wherein we didn't have a complex expression but doesn't work well otherwise. 
For example, for a query like `select count(*) from user where user.id = 2 or user.id in (select id from unsharded_a where colb = 2)`, after we pullout the subquery, we want the final query to look like 
```sql
select count(*) from `user` where `user`.id = 2 or (:__sq_has_values and `user`.id in ::__sq1)
```
and not like 
```sql …
```
> Complex Expression handling for uncorrelated IN and NOT IN subqueries

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v18.0.7-SNAPSHOT) after the release of v18.0.6.
> [release-18.0] Bump to `v18.0.7-SNAPSHOT` after the `v18.0.6` release

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v19.0.6-SNAPSHOT) after the release of v19.0.5.
> [release-19.0] Bump to `v19.0.6-SNAPSHOT` after the `v19.0.5` release

- .github/workflows/vitess_tester_vtgate.yml
- test/templates/cluster_vitess_tester.tpl
It was noticed that the vitess tester workflow while running make build was also building the vtadmin binaries. That however is not required since it doesn't actually run the vtadmin. Moreover, because of the lack of correct dependencies being installed the workflow fails sometimes https://github.com/vitessio/vitess/actions/runs/10043908851/job/27757759665. This PR fixes this issue.
> Skip running vtadmin build for vitess tester workflow

- go/mysql/collations/env.go
- go/mysql/collations/integration/main_test.go
- go/vt/vtgate/evalengine/api_coerce.go
This cleans up some logic around the default collation and coercion. We now make the MySQL 8 collations the default if there's no version mismatch instead of what we had with MySQL 5.7.
Additionally we fix a small issue that doesn't really matter in practice with an unknown collation, but we know have a full type so we do know it, so let's use it.
> Small internal cleanups

- go/mysql/binlog_event.go
- go/mysql/capabilities/capability.go
- go/mysql/capabilities/capability_test.go
- go/mysql/flavor_mysqlgr_test.go
- go/mysql/flavor_test.go
Removes some unused MySQL 5.6 code. Usage of `MySQLJSONFlavorCapability` was already removed some time ago, but the capability was left in. I also noticed some stuff for collations and binlog, but I left that alone (at least for this PR).
> Remove some unused MySQL 5.6 code

- go/vt/mysqlctl/builtinbackupengine.go
- go/vt/mysqlctl/builtinbackupengine_linux.go
- go/vt/mysqlctl/builtinbackupengine_stub.go
On Linux, the fadvise(2) syscall can be leveraged to hint to the kernel to readahead disk pages since the file is intended to be read sequentially.
This works well with our use of opening this file, then slamming it into `io.Copy`.
In benchmarking, this alone yields around ~50% improvement on the read side without other tunings.
In a naive test, the setup was simply an io.Copy with an os.File for src, and io.Discard for dest:
no fadvise: 222.41 MB/s
with fadvise: 344.69 MB/s
This is with no other tunings to the kernel.
#16442 
- …
> mysqlctl: open backup files with fadvise(2) and FADV_SEQUENTIAL

- go/test/endtoend/vtgate/queries/misc/misc_test.go
- go/vt/vtgate/planbuilder/operators/apply_join.go
- go/vt/vtgate/planbuilder/operators/route_planning.go
- go/vt/vtgate/planbuilder/testdata/from_cases.json
Fixes an issue where we were treating join predicates as `WHERE` predicates by mistake.
Fixes #16471
> bugfix: don't treat join predicates as filter predicates

- go/test/endtoend/backup/vtctlbackup/backup_utils.go
- go/vt/mysqlctl/builtinbackupengine.go
Parameterize the `ReportProgress` function which is being used by both backup and restore so that we log properly.
Fixes #16482
> builtinbackup: log during restore as restore, not as backup

- go/vt/vttablet/tabletserver/vstreamer/uvstreamer.go
- go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go
The `vstream API` currently doesn't validate that the `Fields` for a specified `TableLastPK` are defined. This results in a panics:
```
2024-07-16 18:28:49.897	runtime/panic.go:113 (0x436d5e)
2024-07-16 18:28:49.897	vitess.io/vitess/go/sqltypes/result.go:288 (0xcc1fda)
2024-07-16 18:28:49.897	vitess.io/vitess/go/sqltypes/proto3.go:92 (0xcc1e96)
2024-07-16 18:28:49.897	vitess.io/vitess/go/sqltypes/proto3.go:123 (0xcc2210)
2024-07-16 18:28:49.897	vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer/copy.go:183 (0x15269b2)
2024-07-16 18:28:49.897	vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer/copy.go:211 (0x1526b97)
2024-07-16 18:28:49.897	vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer/copy.go:60 (0x152558c)
2024-07-16 18:28:49.897 …
```
> VStream API: validate that last PK has fields defined

- go/vt/vttablet/tabletserver/schema/engine.go
- go/vt/vttablet/tabletserver/schema/engine_test.go
This PR is a backport of #14716 
This is done in response to https://github.com/vitessio/vitess/pull/14716#issuecomment-2252917870
> [release-18.0] Fix RegisterNotifier to use a copy of the tables to prevent data races (#14716)

- go/test/endtoend/vtgate/queries/reference/main_test.go
- go/test/endtoend/vtgate/queries/reference/reference_test.go
- go/test/endtoend/vtgate/queries/reference/sschema.sql
- go/test/endtoend/vtgate/queries/reference/svschema.json
- go/test/endtoend/vtgate/queries/reference/uschema.sql
- go/test/endtoend/vtgate/queries/reference/uvschema.json
- go/vt/vtgate/planbuilder/operators/join_merging.go
- go/vt/vtgate/planbuilder/operators/joins.go
- go/vt/vtgate/planbuilder/testdata/reference_cases.json
This PR fixes the join merging logic for two reference tables. The merge should also handle the alternative routes of the reference table during merging.
This needs to be backported to all the supported versions as it causes planner time panic.
- Fixes https://github.com/vitessio/vitess/issues/15799
> fix: reference table join merge

- .github/workflows/upgrade_downgrade_test_query_serving_queries.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
- go/test/endtoend/backup/vtbackup/backup_only_test.go
- go/test/endtoend/cluster/vtctld_process.go
- go/test/endtoend/cluster/vtgate_process.go
- go/test/endtoend/cluster/vtorc_process.go
- go/test/endtoend/cluster/vttablet_process.go
- go/test/endtoend/reparent/plannedreparent/reparent_test.go
- go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
- go/test/endtoend/vtgate/queries/derived/cte_test.go
- go/test/endtoend/vtgate/queries/derived/derived_test.go
- go/test/endtoend/vtgate/queries/dml/dml_test.go
- go/test/endtoend/vtgate/queries/dml/insert_test.go
- go/test/endtoend/vtgate/queries/informationschema/informationschema_test.go
- go/test/endtoend/vtgate/queries/misc/misc_test.go
- go/test/endtoend/vtgate/queries/orderby/orderby_test.go
- go/test/endtoend/vtgate/queries/reference/reference_test.go
- go/test/endtoend/vtgate/queries/subquery/subquery_test.go
- go/test/endtoend/vtgate/queries/timeout/timeout_test.go
- go/test/endtoend/vtgate/queries/tpch/tpch_test.go
- go/test/endtoend/vtgate/schematracker/sharded/st_sharded_test.go
- go/test/endtoend/vtgate/schematracker/unsharded/st_unsharded_test.go
- go/test/endtoend/vtgate/vschema/vschema_test.go
This PR updates the query serving (queries) upgrade downgrade workflow to use the same version of the code as the binary we are running to execute the tests. That way, there won't be any imcopatibility between test code and binary version.
Moreover, all the "skip if binary version ..." calls were removed.
backporting this enhancement to all branches as it will fix most of our problems with backports
- Fixes https://github.com/vitessio/vitess/issues/16365
> Improve the queries upgrade/downgrade CI workflow by using same test code version as binary

- go/mysql/sqlerror/constants.go
- go/test/endtoend/transaction/twopc/twopc_test.go
- go/vt/vtgate/debug_2pc.go
- go/vt/vtgate/engine/transaction_status.go
- go/vt/vtgate/production.go
- go/vt/vtgate/tx_conn.go
- go/vt/vtgate/tx_conn_test.go
This PR updates the commit flow as per the new design doc on atomic distributed transactions.
- Any failure before a commit decision rollback the transaction.
- Any failure before conclude, records a warning and return an error.
- The user can track the transaction state by issuing `show warnings` and then extracting transaction ID. Later can issue `show transaction status for '<id>'` to know the current state of it.
- #16245 
> Modify distributed transaction commit flow

- go/mysql/capabilities/capability.go
- go/vt/schemadiff/capability.go
- go/vt/schemadiff/capability_test.go
While not documented in https://dev.mysql.com/doc/refman/8.0/en/innodb-online-ddl-operations.html, changing column visibility is `INSTANT`-able, and this PR adds this analysis in `schemadiff`.
While at it, `INSTANT` DDL analysis now also supports `CHANGE COLUMN` statements where the column name is unchanged, as well as `ALTER COLUMN` statements. It's noteworthy that `schemadiff` itself only generates `MODIFY COLUMN` statements and never either of these two, and this support comes just for completeness.
- https://github.com/vitessio/vitess/issues/14877
-   [ ] Tests were …
> `shcemadiff`: support `INSTANT` DDL for changing column visibility

- go/cmd/vtctldclient/command/throttler.go
For `v21`, this PR adds a deprecation message when the flags `--check-as-check-self` or `--check-as-check-shard` are specified. The flags are still allowed, but the new [Throttler multi metric](https://github.com/vitessio/vitess/pull/15988) approach provides a different (and better) mechanism, where you may specify the desired scope per metric. 
For example:
```sh
$ vtctldclient UpdateThrottlerConfig --app-name=all --app-metrics=loadavg,shard/lag,shard/threads_running commerce
$ vtctldclient UpdateThrottlerConfig --app-name=vstreamer --app-metrics=self/lag commerce
```
Both exist at the same time. Both are visible in `GetKeyspace`:
```sh
$ vtctldclient GetKeyspace commerce | jq .keyspace.throttler_config
```
```json
{
"enabled": true,
"threshold": 10.0,
"custom_query": "", …
```
> Deprecate `UpdateThrottlerConfig`'s `--check-as-check-self` and `--check-as-check-shard` flags

- go/test/endtoend/vreplication/multi_tenant_test.go
A `vdiff` bug, fixed in https://github.com/vitessio/vitess/pull/16307, meant that you couldn't use `vdiff` for multi-tenant workflows since it included a filter.
This PR runs `vdiff` to confirm that it was failing before the fix and works with the commits from that PR.
```
--- PASS: TestMultiTenantComplex (195.11s)
--- PASS: TestMultiTenantComplex/insertInitialData (0.11s)
--- PASS: TestMultiTenantComplex/vtctldclient_vdiff_mt.wf1 (5.26s)
--- PASS: TestMultiTenantComplex/vtctldclient_vdiff_mt.wf2 (5.28s)
--- PASS: TestMultiTenantComplex/vtctldclient_vdiff_mt.wf3 (5.26s)
--- PASS: TestMultiTenantComplex/vtctldclient_vdiff_mt.wf4 (5.25s)
--- PASS: TestMultiTenantComplex/vtctldclient_vdiff_mt.wf5 (5.28s)
--- PASS: TestMultiTenantComplex/vtctldclient_vdiff_mt.wf6 (5.29s)
--- PASS: …
```
> Multi-tenant Movetables: add e2e test for vdiff

- web/vtadmin/package-lock.json
We should backport the fix to all supported versions due to the severity.
- Fixes: https://github.com/vitessio/vitess/security/dependabot/383
> VTAdmin: Upgrade websockets js package

- go/test/endtoend/vtgate/misc_test.go
- go/vt/vtgate/executor_test.go
- go/vt/vtgate/vcursor_impl.go
This PR fixes the `show tables` on system schemas like `mysql`, `information_schema`, etc.
- Fixes https://github.com/vitessio/vitess/issues/16518
> fix: show tables to use any keyspace on system schema

- go/vt/vttablet/tabletserver/planbuilder/permission.go
- go/vt/vttablet/tabletserver/planbuilder/permission_test.go
- go/vt/vttablet/tabletserver/planbuilder/testdata/exec_cases.txt
For Select and Union queries, Vitess only checks for read permission on vttablet.
This PR changes to check on write permission for the Next Value of sequence table calls.
- Fixes https://github.com/vitessio/vitess/issues/16510
> fix: sequence table next value acl permission to writer role 

- .github/workflows/vitess_tester_vtgate.yml
- go/test/endtoend/vtgate/vitess_tester/two_sharded_keyspaces/queries.test
- go/vt/vtgate/planbuilder/operators/join_merging.go
- go/vt/vtgate/planbuilder/operators/sharded_routing.go
- go/vt/vtgate/planbuilder/operators/subquery_planning.go
- go/vt/vtgate/planbuilder/testdata/unsupported_cases.json
- test/templates/cluster_vitess_tester.tpl
This PR introduces a refined solution to the issue where vtgate stopped accepting cross-keyspace queries. In the original fix, we incorrectly rejected subqueries that weren't merged and failed to properly handle non-correlated subqueries from different keyspaces. This updated approach corrects the handling of these subqueries by planning them differently, ensuring that cross-keyspace functionality is restored in a more accurate and efficient manner.
This PR supersedes the previous fix and addresses the same underlying problem introduced in #12197 and initially addressed in #16515. …
> simplify merging logic

- go/vt/vtgate/engine/fake_vcursor_test.go
- go/vt/vtgate/engine/vindex_func.go
- go/vt/vtgate/executor_select_test.go
This PR sends error message back with `no database selected` when a vindex function query is executed without a default database.
Example:
```
mysql> select * from hash where id = 4;
ERROR 1046 (3D000): no database selected: use keyspace<:shard><@type> or keyspace<[range]><@type> (<> are optional)
mysql> use customer;
Database changed
mysql> select * from hash where id = 4;
+------------+--------------------------+--------------------------+----------------------+------------------------------------+--------------+
| id         | keyspace_id              | range_start              | range_end            | hex_keyspace_id                    | shard        |
+------------+--------------------------+--------------------------+----------------------+------------------------------------+------- …
```
> vindex function: error when keyspace not selected

- go/vt/vterrors/code.go
- go/vt/vtgate/tx_conn.go
- go/vt/vttablet/tabletserver/dt_executor.go
- go/vt/vttablet/tabletserver/dt_executor_test.go
- go/vt/vttablet/tabletserver/tx_prep_pool.go
- go/vt/vttablet/tabletserver/tx_prep_pool_test.go
This PR make few changes to the distributed transactions API on the vttablet
- Prepare API to rollback and release the transaction when 
- no DML is executed on the transaction (no error to return)
- DML executed on a reserved connection (return error as well to fail the prepare)
- CommitPrepare API to log a warning if failed to commit a transaction
- StartCommit API to fail if executed on a reserved connection and mark the transaction state to ROLLBACK
- #16245 
> vttablet api distributed transaction changes

- go/test/endtoend/vtgate/vitess_tester/join/join.test
- go/test/endtoend/vtgate/vitess_tester/join/vschema.json
- go/vt/vtgate/planbuilder/operators/apply_join.go
- go/vt/vtgate/planbuilder/operators/dml_with_input.go
- go/vt/vtgate/planbuilder/operators/hash_join.go
- go/vt/vtgate/planbuilder/operators/offset_planning.go
- go/vt/vtgate/planbuilder/testdata/aggr_cases.json
- go/vt/vtgate/planbuilder/testdata/from_cases.json
- go/vt/vtgate/planbuilder/testdata/vschemas/schema.json
This PR fixes 2 things in hash join planning - 
1. During offset planning, if hash join ends up creating a projection operator, the rewriter was still throwing it away because the offset planning visitor would return that there was no change to the operator.
2. During offset planning, hash join returns the expected column offset using the `columns` field. So the parent operators all expect to find fields of the length of `columns`. But then, during its own offset planning, hash join was reusing the column offsets that led to the panic described in https://github.com/vitessio/vitess/issues/16539
- Fixes https://github.com/vitessio/vitess/issues/16539 …
> Fix: Offset planning in hash joins

- web/vtadmin/src/components/routes/workflow/WorkflowStreams.tsx
I noticed a complaint of the linter in #16548. This PR resolve this.
> Remove unused `formatRelativeTime` import

- go/test/endtoend/vreplication/materialize_test.go
- go/test/endtoend/vreplication/vreplication_test.go
- go/vt/vtctl/workflow/framework_test.go
- go/vt/vtctl/workflow/server.go
- go/vt/vtctl/workflow/server_test.go
- go/vt/vtctl/workflow/traffic_switcher.go
- go/vt/vtctl/workflow/utils.go
This is a follow-up to: https://github.com/vitessio/vitess/pull/15977 We should backport the fix to v20, where that work was first added.
There were two problems:
1.   The concrete error type returned from the ExecuteFetch RPC call was a gRPC `status.Error` and NOT the `sqlerror.SQLError` type returned from the database failure so we needed to first convert it
2. The error code returned when the table did not exist was actually [`Error number: 1051; Symbol: [ER_BAD_TABLE_ERROR]`](https://dev.mysql.com/doc/mysql-errors/en/server-error-reference.html#error_er_bad_table_error)
This was missed due to inadequate testing. I've added an endtoend test here — along with updating the unit test (and framework) to test this behavior — which fails on main as expected:
```
❯ go test -v -timeout 10m …
```
> VReplication: Properly ignore errors from trying to drop tables that don't exist

- go/vt/vttablet/tabletmanager/vreplication/vplayer.go
- go/vt/vttablet/tabletmanager/vreplication/vreplicator_test.go
`VPlayer` was incorrectly identifying itself to the throttler as `vcopier`. As result, running `ApplyThrottlerConfig --throttle-app=vplayer` made no effect on VPlayer. This PR fixes the problem.
Context: https://github.com/vitessio/vitess/issues/16575 (this PR does not fix this issue, just related)
This is a bug. Backporting to 20, 19, 18 where this issue is relevant.
> Throttler/vreplication: fix app name used by VPlayer

- go/vt/vttablet/tabletserver/throttle/throttler.go
- go/vt/vttablet/tabletserver/throttle/throttler_test.go
Bugfix. See https://github.com/vitessio/vitess/issues/16554 for context.
Fixes https://github.com/vitessio/vitess/issues/16554
> Tablet throttler: remove cached metric associated with removed tablet

- go/test/endtoend/cluster/cluster_process.go
- go/test/endtoend/cluster/vtctl_process.go
- go/test/endtoend/encryption/encryptedreplication/encrypted_replication_test.go
- go/test/endtoend/encryption/encryptedtransport/encrypted_transport_test.go
- go/test/endtoend/mysqlctl/mysqlctl_test.go
- go/test/endtoend/mysqlctld/mysqlctld_test.go
- go/test/endtoend/sharded/sharded_keyspace_test.go
- go/test/endtoend/transaction/twopc/fuzzer/main_test.go
- go/test/endtoend/transaction/twopc/main_test.go
- go/test/endtoend/transaction/twopc/schema.sql
- go/test/endtoend/transaction/twopc/twopc_test.go
- go/test/endtoend/transaction/twopc/utils/utils.go
- go/test/endtoend/transaction/twopc/vschema.json
- go/vt/vterrors/code.go
- go/vt/vttablet/tabletserver/debug_2pc.go
- go/vt/vttablet/tabletserver/dt_executor.go
- go/vt/vttablet/tabletserver/dt_executor_test.go
- go/vt/vttablet/tabletserver/production.go
- go/vt/vttablet/tabletserver/tabletserver.go
- go/vt/vttablet/tabletserver/tx_engine.go
- go/vt/vttablet/tabletserver/tx_prep_pool.go
- go/vt/vttablet/tabletserver/tx_prep_pool_test.go
This PR adds an e2e test for testing atomic transactions with a PRS disruption. While adding the test, a bug was also noticed. This PR fixes that bug too. 
These are the following sequence of operations that led to the bug - 
1. Users run an atomic transaction and tries to commit it.
2. As part of the commit, vtgate tries to call `CommitPrepared` on all the tablets.
3. An arbitrary reason can call the `CommitPrepared` on a vttablet to stall (In the test we explicitly sleep for 5 seconds)
4. While the `CommitPrepared` call is stalled, a PRS is issued in that shard that changes the primary tablet.
5. During DemotePrimary, we rollback all the prepared transactions by calling `FetchAll` on the prepared pool.
6. `CommitPrepared` finally runs, but it doesn't find any connection since `FetchAll` …
> Atomic Transaction bug fix with PRS disruption

- go/vt/vttablet/tabletmanager/vreplication/vplayer.go
- go/vt/vttablet/tabletmanager/vreplication/vreplicator_test.go
`VPlayer` was incorrectly identifying itself to the throttler as `vcopier`. As result, running `ApplyThrottlerConfig --throttle-app=vplayer` made no effect on VPlayer. This PR fixes the problem.
Context: https://github.com/vitessio/vitess/issues/16575 (this PR does not fix this issue, just related)
This is a bug. Backporting to 20, 19, 18 where this issue is relevant.
> v18 backport: Throttler/vreplication: fix app name used by VPlayer (#16578)

- go/vt/vttablet/tabletmanager/vreplication/vplayer.go
- go/vt/vttablet/tabletmanager/vreplication/vreplicator_test.go
`VPlayer` was incorrectly identifying itself to the throttler as `vcopier`. As result, running `ApplyThrottlerConfig --throttle-app=vplayer` made no effect on VPlayer. This PR fixes the problem.
Context: https://github.com/vitessio/vitess/issues/16575 (this PR does not fix this issue, just related)
This is a bug. Backporting to 20, 19, 18 where this issue is relevant.
> v20 backport: Throttler/vreplication: fix app name used by VPlayer (#16578)

- go/vt/vttablet/tabletmanager/vreplication/vplayer.go
- go/vt/vttablet/tabletmanager/vreplication/vreplicator_test.go
`VPlayer` was incorrectly identifying itself to the throttler as `vcopier`. As result, running `ApplyThrottlerConfig --throttle-app=vplayer` made no effect on VPlayer. This PR fixes the problem.
Context: https://github.com/vitessio/vitess/issues/16575 (this PR does not fix this issue, just related)
This is a bug. Backporting to 20, 19, 18 where this issue is relevant.
> v19 backport: Throttler/vreplication: fix app name used by VPlayer (#16578)

- go/vt/vtgate/evalengine/cached_size.go
- go/vt/vtgate/evalengine/compiler_asm.go
- go/vt/vtgate/evalengine/fn_time.go
- go/vt/vtgate/evalengine/testcases/cases.go
- go/vt/vtgate/evalengine/translate_builtin.go
This PR adds implementation of [`PERIOD_DIFF`](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_period-diff) func in evalengine. This PR borrows some changes related to period functions from #16492.
- #9647 
> evalengine: Implement `PERIOD_DIFF`

- go/vt/vttablet/tabletmanager/vreplication/replicator_plan_test.go
- go/vt/vttablet/tabletmanager/vreplication/table_plan_builder.go
This is a quick bit of internal cleanup that improves the table plan builder's error messages so that they contain the table name. This is pretty important when a workflow is operating on thousands of tables.
> VReplication: Improve table plan builder errors

- go/vt/vtctl/workflow/framework_test.go
- go/vt/vtctl/workflow/server.go
- go/vt/vtctl/workflow/server_test.go
- go/vt/vtctl/workflow/utils.go
This is a follow-up to https://github.com/vitessio/vitess/pull/16260.
Somehow, in 3 places, the return was missed when the `LockName` call failed. That is corrected here, along with unit test additions to cover this scenario.
I also took the opportunity to unify the error handling and error messages.
- Follow-up to: https://github.com/vitessio/vitess/pull/16260
- Fixes: https://github.com/vitessio/vitess/issues/16559 …
> VReplication: Return lock error everywhere that LockName fails

- go/vt/vtgate/endtoend/aggr_test.go
- go/vt/vtgate/executor_select_test.go
- go/vt/vtgate/planbuilder/operators/aggregator.go
- go/vt/vtgate/planbuilder/operators/apply_join.go
- go/vt/vtgate/planbuilder/operators/ast_to_op.go
- go/vt/vtgate/planbuilder/operators/expressions.go
- go/vt/vtgate/planbuilder/operators/horizon.go
- go/vt/vtgate/planbuilder/operators/horizon_expanding.go
- go/vt/vtgate/planbuilder/operators/join_merging.go
- go/vt/vtgate/planbuilder/operators/offset_planning.go
- go/vt/vtgate/planbuilder/operators/ordering.go
- go/vt/vtgate/planbuilder/operators/phases.go
- go/vt/vtgate/planbuilder/operators/projection.go
- go/vt/vtgate/planbuilder/operators/projection_pushing.go
- go/vt/vtgate/planbuilder/operators/route_planning.go
- go/vt/vtgate/planbuilder/testdata/aggr_cases.json
- go/vt/vtgate/planbuilder/testdata/cte_cases.json
- go/vt/vtgate/planbuilder/testdata/from_cases.json
- go/vt/vtgate/planbuilder/testdata/memory_sort_cases.json
- go/vt/vtgate/planbuilder/testdata/postprocess_cases.json
- go/vt/vtgate/planbuilder/testdata/select_cases.json
- go/vt/vtgate/planbuilder/testdata/tpch_cases.json
While working on #16427, I've stumbled across quite a few annoyances in the code that needed fixing before we could finish the CTE work. Instead of making that PR even bigger, I'm extracting all the clean ups into this PR.
The kind of clean ups are:
* Use `AddWSColumn` instead of `AddColumn` to add `weight_strings`.
* Don't push down literals - just evaluate them in the vtgate
> Planner cleaning: cleanup and refactor

- go/mysql/conn.go
- go/vt/vttablet/endtoend/connecttcp/main_test.go
- go/vt/vttablet/endtoend/connecttcp/prepare_test.go
- go/vt/vttablet/tabletserver/connpool/dbconn.go
- go/vt/vttablet/tabletserver/dt_executor.go
- go/vt/vttablet/tabletserver/stateful_connection.go
- go/vt/vttest/local_cluster.go
This PR rejects distributed transactions prepared when carried on a non-unix socket connection.
- #16245 
> Reject atomic distributed transaction on a network connection

- go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
- go/vt/vttablet/onlineddl/executor.go
Fixes https://github.com/vitessio/vitess/issues/16591 by setting a high value for `lock_wait_timeout` in both cut-over sessions.
https://github.com/vitessio/vitess/issues/16591
> Online DDL: ensure high `lock_wait_timeout` in Vreplication cut-over

- go/vt/vtctl/workflow/framework_test.go
- go/vt/vtctl/workflow/materializer_env_test.go
- go/vt/vtctl/workflow/materializer_test.go
- go/vt/vtctl/workflow/mount_test.go
- go/vt/vtctl/workflow/resharder_test.go
- go/vt/vtctl/workflow/stream_migrator_test.go
- go/vt/vtctl/workflow/utils_test.go
- go/vt/vtctl/workflow/vreplication_stream_test.go
As part of the vtctldclient migration, we ported over a lot of existing code and wrote new code in the `go/vt/vtctl/workflow` package. However the unit test frameworks were not. While we have added some unit tests since, the current coverage is still very low.
This is one of multiple PRs that we will create to progressively increase coverage to a more acceptable level.
This PR has tests, among others, for: 
* the `Mount` commands
* `StreamMigrator`
* `ShardRoutingRules`
https://github.com/vitessio/vitess/issues/16499
-   [ ] Did …
> VReplication workflow package: unit tests for StreamMigrator, Mount et al

- go/vt/vttablet/tabletmanager/vreplication/replicator_plan.go
- go/vt/vttablet/tabletmanager/vreplication/vplayer.go
- go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go
This is a quick bit of internal cleanup that improves the replication plan builder's error messages so that they contain the table name. This is pretty important when a workflow is operating on thousands of tables. This is a sibling PR to: https://github.com/vitessio/vitess/pull/16588
It should have been changed in that PR as well, but here we are... 🙂 
I also took this opportunity to make two improvements to the event application errors in `vplayer`, for which replication plan builder errors would be one cause:
1. Include the table name in the error message (it was only included in the log message)
2. Add the stream position we were trying to process when encountering the error
To demonstrate:
```
./101_initial_cluster.sh; ./201_customer_tablets.sh
mysql commerce -e "create table t1 (id …
```
> VReplication: Improve replication plan builder and event application errors

- go.mod
- vitess-mixin/go.mod
In https://github.com/vitessio/vitess/pull/16599 we bumped the go version to 1.23.0, this PR fixes the go.mod files that were incorrectly updated.
> Fix go.mod files

- go/vt/vtgate/executor.go
Fixes https://github.com/vitessio/vitess/issues/16592
Fixes a bug with the vtgate query plan cache metrics that causes the `QueryPlanCacheMisses` to return hits instead.
The bug seems to have been introduced in https://github.com/vitessio/vitess/pull/13939
What is the policy for backporting metric fixes? Would be ideal for us if backported.
> Fix query plan cache misses metric

- go/mysql/fakesqldb/server.go
- go/vt/logutil/throttled.go
- go/vt/vttablet/tabletserver/schema/engine.go
- go/vt/vttablet/tabletserver/schema/engine_test.go
This PR fixes the issue described in https://github.com/vitessio/vitess/issues/16629. We will now log the error that we receive while reading the udfs but allow the schema tracker to continue.
We use a throttled logger for logging the error message to ensure we don't flood the logs with this error. We have hard-coded the throttled logger to only log the statement once every minute.
- Fixes https://github.com/vitessio/vitess/issues/16629
-   [x] …
> Log and ignore the error in reading udfs in schema tracker

- .github/workflows/static_checks_etc.yml
- misc/git/hooks/golangci-lint
We’ve recently updated to `golangci-lint v1.60.1`, but it was found to be a slower release. This PR upgrades the version to `v1.60.2`, which offers improved performance.
Additionally, this PR enhances the git hook to ensure that golangci-lint is updated only if the installed version is older than the required version. This prevents unnecessary downgrades and ensures that the tool is always up-to-date with the specified or newer version.
https://github.com/vitessio/vitess/pull/16599 …
> Update golangci-lint to newer faster version

- go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
- go/vt/sidecardb/schema/onlineddl/schema_migrations.sql
- go/vt/vttablet/onlineddl/schema.go
This PR introduces `schema_migrations. message_timestamp` column, which gets updated to current timestamp whenever `message` gets updated.
The column gets auto-populated with the same query that updates the `message`. There is thus no actual code change other than an SQL.
Fixes https://github.com/vitessio/vitess/issues/16632
> Online DDL: new `message_timestamp` column in `schema_migrations` table

- go/vt/vtgate/engine/concatenate.go
- go/vt/vtgate/engine/concatenate_test.go
- go/vt/vtgate/engine/fake_primitive_test.go
While looking at the flaky test pointed out in https://github.com/vitessio/vitess/issues/16641 we found several issues in concatenate engine primitive in the streaming mode. The following are the issues and the fixes in this PR - 
1. In the parallel streaming mode, when we calculate the final field types for the result using`getFieldTypes`, we were overriding the fields of one of the result packets that we got. If this was a packet from a source that needed coercion, because we overwrote the fields, with what we expect them to be, when we check if coercion is required we end up with false even when it requires coercion. This is fixed in the PR by storing the result fields separately and checking for needing coercion with the original fields of the result.
2. Another failure that was found …
> Fix race conditions in the concatenate engine streaming

- go/test/endtoend/vtgate/vitess_tester/cte/queries.test
- go/vt/vtgate/planbuilder/operators/SQL_builder.go
- go/vt/vtgate/planbuilder/operators/ast_to_op.go
- go/vt/vtgate/planbuilder/operators/cte_merging.go
- go/vt/vtgate/planbuilder/operators/join_merging.go
- go/vt/vtgate/planbuilder/operators/recurse_cte.go
- go/vt/vtgate/planbuilder/testdata/cte_cases.json
Issues in this first implementation found and fixed in this PR. They include:
- Correctly handle the case when we only use the CTE table in the RHS of the recursive UNION
- Merging CTEs in more situations
- Handle UNION DISTINCT in the CTE definition
- Stop predicate push down
Part of https://github.com/vitessio/vitess/issues/16415
> Additional recursive CTE work

- go/mysql/collations/colldata/cached_size.go
- go/sqltypes/cached_size.go
- go/tools/sizegen/sizegen.go
- go/vt/proto/query/cached_size.go
- go/vt/proto/topodata/cached_size.go
- go/vt/proto/vttime/cached_size.go
The `sizegen` code generator wasn't handling type aliases well, so `make sizegen` was failing:
```
2024/08/26 09:31:48 unhandled type: *types.Alias
panic: interface conversion: types.Type is *types.Alias, not *types.Named
goroutine 1 [running]:
main.(*sizegen).generateType.func1({0x741a58, 0xc09ef28840})
/home/runner/work/vitess/vitess/go/tools/sizegen/sizegen.go:152 +0x6f
main.findImplementations(0xc0949f9140, 0xc09e30c1e0, 0xc000031890)
/home/runner/work/vitess/vitess/go/tools/sizegen/sizegen.go:176 +0xee
main.(*sizegen).generateType(0xc000031ce8, 0xc0949f91a0, 0xc051cbe7b0, 0xc09e320e00)
/home/runner/work/vitess/vitess/go/tools/sizegen/sizegen.go:150 +0x285
main.(*sizegen).generateKnownType(0xc000031ce8, 0xc09e320e00)
```
This PR fixes sizegen so it can handle type aliases.
-   [x] …
> fix sizegen so it handles type aliases

- go/vt/vttablet/tabletmanager/vreplication/utils.go
- go/vt/vttablet/tabletmanager/vreplication/utils_test.go
If a tablet picker is configured to pick `REPLICA` tablet types only, and when it starts streaming the selected tablet is promoted to a `PRIMARY` because of a PRS or ERS, the vttablet returns an grpc error like `"error": "vttablet: rpc error: code = FailedPrecondition desc = wrong tablet type: PRIMARY, want: REPLICA or []",`
Currently all `FailedPrecondition`s are treated as unrecoverable errors for vreplication workflows. This PR adds an exception for  the `wrong tablet` `FailedPrecondition`error treats it as recoverable.
This will resolve situations where there was race where
* the tablet picker on the target chooses a tablet, type `REPLICA`
* the target is about to do a VStream RPC to that tablet. The RPC request has `query.Target` which has the expected `TabletType` 
* there is PRS …
> VReplication workflows: retry "wrong tablet type" errors

- go/vt/vtgate/planbuilder/operators/aggregator.go
- go/vt/vtgate/planbuilder/operators/delete.go
- go/vt/vtgate/planbuilder/operators/dml_with_input.go
- go/vt/vtgate/planbuilder/operators/fk_cascade.go
- go/vt/vtgate/planbuilder/operators/fk_verify.go
- go/vt/vtgate/planbuilder/operators/operator.go
- go/vt/vtgate/planbuilder/operators/rewriters.go
- go/vt/vtgate/planbuilder/operators/route.go
- go/vt/vtgate/planbuilder/operators/update.go
- go/vt/vtgate/semantics/dependencies.go
- go/vt/vtgate/semantics/real_table.go
This PR focuses on improving the performance of the Vitess planner by analyzing profiler output and implementing optimizations that reduce execution time, memory usage, and allocations. The changes are aimed at making the planner faster and more efficient, especially for complex queries.
The benchmarks were run on an Apple M1 Ultra and demonstrate significant improvements across various metrics:
* The execution time for the planner has been reduced by 22.41% on average.
* Notable improvements include:
* OLTP/Gen4-20: -27.45%
* TPCH/Gen4-20: -36.17%
* Planner/large_cases.json-gen4-20: -49.41%
* SelectVsDML/DML_(random_sample,_N=32)-20: -28.01%
* Memory usage has been reduced by 33.48% on average.
* Significant reductions were observed in:
* TPCH/Gen4-20: -55.71%
* …
> Performance improvements - Planner

- .github/workflows/static_checks_etc.yml
This PR changes the static checks workflow slightly to run all of its different checks if the workflow changes. We recently noticed that changing the linter version in the static checks workflow file, doesn't actually run the linter since there were no go file changes. This is however incorrect, and we should run all the steps of the workflow when the file changes.
> Run the static checks workflow if the file changes

- web/vtadmin/package-lock.json
This PR bumps our npm package `micromatch` from `4.0.5` to `4.0.8`. This fixes a CVE https://github.com/vitessio/vitess/security/dependabot/385 that is fixed in `4.0.8`.
> Update micromatch to 4.0.8

- Makefile
In https://github.com/vitessio/vitess/pull/16042 I modified the make targets touching our `vitess/lite` docker image, and the push target is a bit broken, it only pushes suffixed images (`percona80`, etc) and not `latest`. This PR is a merge of what we had before + what was fixed in 16042.
Backporting this to 20.0 as the original PR was merge there too.
> Fix `docker_lite_push` make target

- go/test/endtoend/vtcombo/recreate/recreate_test.go
- go/vt/vtcombo/tablet_map.go
Closes the query service on `DROP DATABASE`, which will close connection pools.
Fixes https://github.com/vitessio/vitess/issues/16605
> vtcombo: close query service on drop database

- go/test/endtoend/vtgate/vitess_tester/dual/queries.test
- go/test/endtoend/vtgate/vitess_tester/join/join.test
- go/vt/sqlparser/normalizer_test.go
- go/vt/sqlparser/precedence.go
- go/vt/sqlparser/precedence_test.go
- go/vt/vtgate/planbuilder/testdata/onecase.json
This PR the bug described in https://github.com/vitessio/vitess/issues/16590.
The problem with the precedence rules, where-in after normalization, we would print the query as follows - 
```sql
select 1 from dual where ~1 or 0 is null
```
This is different from the original query - 
```sql
select 1 from dual where (~(1 or 0)) is null
```
The problem has been fixed by updating the precedence rules by adding one for tilda op.
- Fixes https://github.com/vitessio/vitess/issues/16590 …
> Fix Precedence rule for Tilda op

- go/test/endtoend/utils/cmp.go
- go/test/endtoend/utils/utils.go
- go/test/endtoend/vtgate/gen4/system_schema_test.go
- go/test/endtoend/vtgate/grpc_api/acl_test.go
- go/test/endtoend/vtgate/lookup_test.go
- go/test/endtoend/vtgate/misc_test.go
- go/test/endtoend/vtgate/queries/informationschema/informationschema_test.go
- go/test/endtoend/vtgate/queries/timeout/timeout_test.go
- go/test/endtoend/vtgate/sequence/seq_test.go
- go/test/endtoend/vtgate/unsharded/main_test.go
We were using some anti-patterns in the testing code for vtgate package like -
```go
assert.Contains(t, err.Error(), ...)
```
instead we should be using 
```go
assert.ErrorContains(t, err, ....)
```
This PR fixes these anti-patterns.
This PR is the first change needed to fix the failing tests as seen in https://github.com/vitessio/vitess/actions/runs/10488116666/job/29052695413?pr=16619. The idea is to fix these anti-patterns, and then while running upgrade downgrade tests, we ignore `assert.ErrorContains` type of checks because we don't need to guarantee that the error messages don't change across version upgrades. 
This is also the reason this PR needs to be backported to release-20.
- …
> Fix error contain checks in vtgate package

- go/trace/trace.go
> bug: fix slice init length

- go/vt/discovery/healthcheck.go
- go/vt/discovery/keyspace_events.go
- go/vt/discovery/keyspace_events_test.go
- go/vt/srvtopo/discover.go
- go/vt/srvtopo/discover_test.go
- go/vt/vtgate/tabletgateway.go
- go/vt/vtgate/tabletgateway_flaky_test.go
- go/vt/vtgate/tabletgateway_test.go
This PR fixes the race described in https://github.com/vitessio/vitess/issues/16656. 
The fix for the race is to also wait for the keyspace event watcher to have seen the updates for primary tablets being serving if that is something the user has requested to wait on. This fixes the race because before starting query service we can now be certain that the keyspace event watcher has processed the healthcheck responses for primaries of all the shards in the keyspaces. This ensures that we will start buffering if a primary goes non-serving subsequently.
This PR adds unit tests to ensure the behaviour of the newly added functions is as intended. It also adds comments to parts of code it is not necessarily changing but would have facilitated in helping debug the issue faster.
- Fixes …
> Fix race condition that prevents queries from being buffered after vtgate startup

- go/vt/schemadiff/capability.go
- go/vt/schemadiff/capability_test.go
Rejecting the following scenarios:
- Reordering columns (either via `MODIFY COLUMN` or `CHANGE COLUMN`), e.g. `alter table t modify column i1 int after i2`
- Adding a non nullable, no-default `DATETIME`: `alter table t add column d5 datetime(3) not null`
This one is not documented but is nonetheless rejected by MySQL - for non empty tables.
We've found a myriad of nuances with relation to `DATETIME` and `TIMESTAMP`. The reason MySQL rejects the above is that it assumes the default is `0000-00-00 00:00:00`, which it does not allow. But it does allow the same for `TIMESTAMP`. In both cases, if the table is empty, it is allowed. So it's about _populating_ these columns rather than their definitions. There is further consideration for what constitutes a valid value for a `DATETIME` or a …
> schemadiff: more `INSTANT` algorithm considerations

- go/vt/schemadiff/errors.go
- go/vt/schemadiff/table.go
- go/vt/schemadiff/table_test.go
- go/vt/schemadiff/types.go
~~This PR introduces a new diff hint: `NonDeterministicDefaultStrategy`, which can take these values:~~
~~When it's set to `NonDeterministicDefaultReject`,~~
`schemadiff` now errors on table diffs where:
- A new column is added
- The column has an expression (non-literal) default value
- The expression contains a non-detereministic function, specifically one of:
- `SYSDATE()`
- `UUID()`
- `RAND()`
This matches MySQL behavior as in:
```
alter table t add column v varchar(36) NOT NULL DEFAULT (uuid());
ERROR 1674 (HY000): Statement is unsafe because it uses a system function that may return a different value on the slave.
```
There is no need to handle `MODIFY COLUMN` or `CHANGE COLUMN` statements, because those cannot introduce un-computed column data, and only operate on existing columns. …
> schemadiff: reject non-deterministic function in new column's default value

- go/vt/schemadiff/table.go
- go/vt/schemadiff/table_test.go
Quick followup to #16684, adding two more known non-deterministic functions.
#16684
> schemadiff: reject `uuid_short` and `random_bytes` in new column expression

- go/vt/vttablet/tabletserver/connpool/dbconn.go
- go/vt/vttablet/tabletserver/connpool/dbconn_test.go
This PR fixes the error codes returned when context expires on vttablet even before the execution of the query starts. Previously we would return the error by calling `fmt.Errorf`, which on being translated to grpc error codes, would result in `Code_UNKNOWN`. Instead if we use `vterrors.Errorf` and use `vtrpcpc.Code_CANCELLED`, we can get a better error code.
> Fix error code received from vttablets on context expiration

- .github/workflows/upgrade_downgrade_test_query_serving_queries.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml
This PR replaces the `ErrorContains` checks to just check for an `Error` instead while running upgrade downgrade tests. This is required because we don't guarantee that errors will be the same across different vitess version. 
The workings of the changes can be seen in the workflow run https://github.com/vitessio/vitess/actions/runs/10630690740/job/29470087067?pr=16688 in the `Convert ErrorContains to Error checks` step. I am copying a snippet so that it can be seen directly here - 
```go
diff --git a/go/test/endtoend/backup/vtbackup/backup_only_test.go b/go/test/endtoend/backup/vtbackup/backup_only_test.go
index 7dada7a77d..1fd6c601cf 100644
--- a/go/test/endtoend/backup/vtbackup/backup_only_test.go
+++ b/go/test/endtoend/backup/vtbackup/backup_only_test.go
@@ -74,9 +74,9 @@ func …
```
> Replace ErrorContains checks with Error checks before running upgrade downgrade

- go/test/endtoend/onlineddl/flow/onlineddl_flow_test.go
- go/test/endtoend/onlineddl/revert/onlineddl_revert_test.go
- go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
- go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go
- go/test/endtoend/onlineddl/vrepl_stress/onlineddl_vrepl_mini_stress_test.go
- go/test/endtoend/onlineddl/vrepl_stress_suite/onlineddl_vrepl_stress_suite_test.go
- go/test/endtoend/onlineddl/vrepl_suite/onlineddl_vrepl_suite_test.go
- go/test/endtoend/schemadiff/vrepl/schemadiff_vrepl_suite_test.go
Many (all) of the Online DDL CI tests used the test `TestSchemaChange` as the main entry point. They're in different packages and that's fine, but it made it more difficult for the maintainers to distinguish between the tests when looking at aggregated test failure reports.
In this PR we just change the name of the function per CI workflow.
> CI: rename `TestSchemaChange` to distinguish the tests

- doc/design-docs/AtomicTransactionsWithDisruptions.md
- go/test/endtoend/cluster/move_tables.go
- go/test/endtoend/cluster/vttablet_process.go
- go/test/endtoend/onlineddl/vtgate_util.go
- go/test/endtoend/transaction/twopc/stress/fuzzer_test.go
- go/test/endtoend/transaction/twopc/stress/main_test.go
- go/test/endtoend/transaction/twopc/stress/stress_test.go
This PR adds the test to verify `MoveTables` works with atomic transactions without any issues.
This PR also adds a design doc detailing how everything is supposed to work.
- #16245 
> Move tables with atomic transactions

- go/vt/vttablet/tabletserver/planbuilder/permission.go
- go/vt/vttablet/tabletserver/planbuilder/permission_test.go
This PR fixes the issue described in https://github.com/vitessio/vitess/issues/16542 and supersedes https://github.com/vitessio/vitess/pull/16548.
The ACLs for a CTE were failing because a new table is being defined and it doesn't require any permission checks. This PR fixes the issue by keeping track of the CTE scopes seen while building permissions. We use this to know if the table that we're trying to check permissions for is a CTE or not. If it is, then we conclude that the table doesn't require a permission check.
- Fixes https://github.com/vitessio/vitess/issues/16542 …
> Fix ACL checks for CTEs

- go/test/endtoend/vtgate/queries/dml/insert_test.go
During the PR https://github.com/vitessio/vitess/pull/16637, we introduced a test `TestInsertJson`. This test is failing during the upgrade test in release-20.0, because it tries to run it with a new vtgate and old vttablet - 
```
target: sks.-80.primary: vttablet: rpc error: code = InvalidArgument desc
```
- Fixes test failure https://github.com/vitessio/vitess/actions/runs/10680402366/job/29620236854?pr=16699 …
> Fix upgrade test in release-20 by skipping tests

- go/test/endtoend/cluster/move_tables.go
- go/test/endtoend/cluster/vttablet_process.go
- go/test/endtoend/transaction/twopc/stress/fuzzer_test.go
- go/test/endtoend/transaction/twopc/stress/stress_test.go
- go/test/endtoend/transaction/twopc/utils/utils.go
This PR reduces the flakiness in 2PC testing. There are 2 changes in this PR - 
1. Run `MoveTables Create` with the `--tablet-types REPLICA` flag so that the copier selects a replica to copy from instead of a primary. This is required because we have an open transaction against a primary and that blocks the `lock tables for read` statement that the copier runs.
2. Add a timeout to clearing out the tables data to prevent panics and instead show up an error. …
> Reduce flakiness in TwoPC testing

- go/mysql/replication/replication_status.go
- go/mysql/replication/replication_status_test.go
- go/vt/vtctl/reparentutil/replication.go
- go/vt/vtctl/reparentutil/replication_test.go
If there are only two replicas, and one has a GTIDSet that is a superset of the other, do not consider it as errant.
Of the two new unit tests, the second one (superset) fails without the code change in this PR.
This can cause serious issues, so I'm marking this for backport to all supported releases.
#16724 
> FindErrantGTIDs: superset is not an errant GTID situation

- web/vtadmin/src/components/routes/workflow/Workflow.tsx
- web/vtadmin/src/components/routes/workflow/WorkflowDetails.tsx
- web/vtadmin/src/components/routes/workflow/WorkflowStreams.tsx
- web/vtadmin/src/util/time.ts
Some changes to the `Workflow` screen:
- For Reshard workflows: shows source/target shards in the header
- Capitalize Keyspace: from Target keyspace to Target Keyspace
- Make timestamps more compact to make the display denser, like. mm/dd/yy HH:MM:SS UTC. (no century, 24 hour format)
- Add the units (seconds) to the replication lag
- If more than 8 shards: don’t show logs for now.
- In streams, show the source shard and target shard, and add link to tablet.
- Remove `Streams` Table from the Lag Graph tab
- Remove "Scroll To Streams" from tabs other than "Details"
- Reduce space above the Summary caption
- #16687
-   [ ] If this change is to be back-ported to previous releases, a …
> VTAdmin(web): Some tweaks in the workflow details

- .github/workflows/scorecards.yml
This is a quick follow-up to https://github.com/vitessio/vitess/pull/16538. The workflow has been [failing on main every time since it was merged](https://github.com/vitessio/vitess/commits/main/) with this error:
```
Error: Unable to resolve action `ossf/scorecard-action@v2`, unable to find version `v2`
```
That's because there are no major version tags (nor major.minor) used for this action: https://github.com/ossf/scorecard-action/tags
So this PR addresses that by using the latest version tag of `v2.4.0`.
- Follow-up to: https://github.com/vitessio/vitess/pull/16538
- …
> CI: Use valid tag for the ossf-scorecard action

- .github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml
- .github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml
- .github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml
- .github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml
This PR is a follow-up of https://github.com/vitessio/vitess/pull/16721 to make sure we use the proper golang version on the upgrade tests of release-18.0.
> [release-18.0] Bump upgrade tests to `go1.22.7`

- changelog/18.0/18.0.7/changelog.md
- changelog/18.0/18.0.7/release_notes.md
- changelog/18.0/README.md
Includes the release notes and release commit for the `v18.0.7` release. Once this PR is merged, we will be able to tag `v18.0.7` on the merge commit.
---
Note: manually generated by this command:
```sh
go run ./go/tools/release-notes/release_notes.go --version v18.0.7
go run ./go/tools/releases/releases.go
```
> [release-18.0] Release of `v18.0.7`

- .github/workflows/code_freeze.yml
- changelog/20.0/20.0.2/changelog.md
- changelog/20.0/20.0.2/release_notes.md
- changelog/20.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/401_scheduled_backups.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v20.0.2` release. Once this PR is merged, we will be able to tag `v20.0.2` on the merge commit.
> [release-20.0] Release of `v20.0.2`

- .github/workflows/code_freeze.yml
- changelog/18.0/18.0.7/changelog.md
- changelog/18.0/18.0.7/release_notes.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Fixing the mistake of https://github.com/vitessio/vitess/pull/16740#event-14209862684, by rewriting commit history and removing this commit:
```
commit 6937274d9aff8779f3af2ec1840b7f0f843d383d (HEAD -> release-18.0, upstream/release-18.0)
Author: Shlomi Noach <2607934+shlomi-noach@users.noreply.github.com>
Date:   Wed Sep 11 10:54:24 2024 +0300
[release-18.0] Release of `v18.0.7` (#16749)
Signed-off-by: Shlomi Noach <2607934+shlomi-noach@users.noreply.github.com>
```
https://github.com/vitessio/vitess/issues/16739
-   [ ] Did the …
> Fix release-18.0.7

- changelog/18.0/18.0.7/changelog.md
- changelog/18.0/18.0.7/release_notes.md
- changelog/18.0/README.md
This Pull Request copies the release notes found on `release-18.0` to keep release notes up-to-date after the `v18.0.7` release.
> [main] Copy `v18.0.7` release notes

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v19.0.7-SNAPSHOT) after the release of v19.0.6.
> [release-19.0] Bump to `v19.0.7-SNAPSHOT` after the `v19.0.6` release

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v20.0.3-SNAPSHOT) after the release of v20.0.2.
> [release-20.0] Bump to `v20.0.3-SNAPSHOT` after the `v20.0.2` release

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v18.0.8-SNAPSHOT) after the release of v18.0.7.
> [release-18.0] Bump to `v18.0.8-SNAPSHOT` after the `v18.0.7` release

- examples/operator/401_scheduled_backups.yaml
In the operator example 401_scheduled_backups.yaml the incorrect keyspace is used. Corrected `customer` to `commerce`
None
None
> Example operator 401_scheduled_backups.yaml incorrect keyspace

- go/test/endtoend/transaction/twopc/fuzz/fuzzer_test.go
- go/test/endtoend/transaction/twopc/fuzz/main_test.go
- go/test/endtoend/transaction/twopc/fuzz/schema.sql
- go/test/endtoend/transaction/twopc/fuzz/vschema.json
- go/test/endtoend/transaction/twopc/stress/stress_test.go
- go/test/endtoend/transaction/twopc/utils/utils.go
- test/config.json
Fuzzer test and Stress test were using common state which sometimes leave `twopc_fuzzer_update` table on 2 keyspaces.
It causes an ambiguous error on running move tables disruption on the stress test after fuzz test have completed.
The PR split these into two different packages so that they do not interact with each other.
> fix distributed transactions disruptions test with move table

- web/vtadmin/package-lock.json
This upgrades the `path-to-regexp` node package to the fixed versions recommended in the security alert: https://github.com/vitessio/vitess/security/dependabot/389
We should backport this to all supported Vitess versions (18,19,20) so that it is addressed in any subsequent patch releases.
- Fixes: https://github.com/vitessio/vitess/security/dependabot/389
> VTAdmin: Address security vuln in path-to-regexp node pkg

- .github/workflows/docker_build_base.yml
- .github/workflows/docker_build_lite.yml
- .github/workflows/docker_build_vttestserver.yml
- Makefile
This PR is a follow up of https://github.com/vitessio/vitess/pull/16622 where we removed some of the mysql 57 docker images, but some were forgotten. We were still trying to build mysql57 images for the new v19.0 patch release even though if we don't publish any more mysql57 bootstrap image.
> [release-19.0] Remove mysql57 from docker images

- go/vt/vttablet/tabletserver/planbuilder/permission.go
- go/vt/vttablet/tabletserver/planbuilder/permission_test.go
This PR fixes the issue described in https://github.com/vitessio/vitess/issues/16542 and supersedes https://github.com/vitessio/vitess/pull/16548.
The ACLs for a CTE were failing because a new table is being defined and it doesn't require any permission checks. This PR fixes the issue by keeping track of the CTE scopes seen while building permissions. We use this to know if the table that we're trying to check permissions for is a CTE or not. If it is, then we conclude that the table doesn't require a permission check.
> Backport: Fix ACL checks for CTEs (#16642)

- examples/common/scripts/vtadmin-up.sh
- web/vtadmin/package-lock.json
- web/vtadmin/package.json
Firstly, this is a follow-up to https://github.com/vitessio/vitess/pull/16770 and corrects the `path-to-regexp` dependency for `serve-handler` (the core HTTP request handler in `vtadmin-web`)  — it should have been upgraded to `3.3.0` there rather than `8.0.0`. Without this fix it failed to handle incoming requests after starting up:
```
git checkout main && make build
cd examples/local
./101_initial_cluster.sh; mysql < ../common/insert_commerce_data.sql
curl localhost:14201
❯ cat ${VTDATAROOT}/tmp/vtadmin-web.out
INFO  Accepting connections at http://localhost:14201/
HTTP  9/13/2024 8:26:32 AM 127.0.0.1 GET /
INFO  Gracefully shutting down. Please wait...
/Users/matt/git/vitess/web/vtadmin/node_modules/serve-handler/src/index.js:47
const expression = pathToRegExp(normalized, keys);
^ …
```
> VTAdmin: Fix serve-handler's path-to-regexp dep and add default schema refresh

- go/test/endtoend/onlineddl/exec_util.go
Some Online DDL tests run the `mysql` command line. When that execution fails, all we got was "exit status 1". We now ensure to capture standard error in a temp file, whose contents we read and add to the error message.
None.
> `endtoend`: better error reporting in Online DDL MySQL execution tests

- go/vt/vtgate/planbuilder/operators/delete.go
- go/vt/vtgate/planbuilder/operators/helpers.go
- go/vt/vtgate/planbuilder/operators/insert.go
- go/vt/vtgate/planbuilder/operators/route.go
- go/vt/vtgate/planbuilder/operators/table.go
- go/vt/vtgate/planbuilder/operators/update.go
- go/vt/vtgate/planbuilder/operators/vindex.go
Minimal change in how we gather which tables have been used by a query.
```
│  ../before  │              ../after              │
│   sec/op    │   sec/op     vs base               │
Planner/from_cases.json-gen4-20     7.490m ± 1%   7.436m ± 1%       ~ (p=0.089 n=10)
Planner/filter_cases.json-gen4-20   149.7m ± 1%   150.0m ± 1%       ~ (p=0.912 n=10)
Planner/large_cases.json-gen4-20    468.0µ ± 0%   469.9µ ± 1%       ~ (p=0.218 n=10)
Planner/aggr_cases.json-gen4-20     13.26m ± 1%   13.21m ± 1%       ~ (p=0.105 n=10)
Planner/select_cases.json-gen4-20   10.54m ± 1%   10.48m ± 1%       ~ (p=0.089 n=10)
Planner/union_cases.json-gen4-20    3.875m ± 0%   3.824m ± 1%  -1.32% (p=0.000 n=10)
geomean                             8.108m        8.077m       -0.39%
│  ../before   │ …
```
> Small fix to decrease memory allocation

- go/test/endtoend/vtgate/queries/timeout/timeout_test.go
As pointed out in https://github.com/vitessio/vitess/issues/16624, we weren't respecting overall query timeout. An attempt to fix it was made in https://github.com/vitessio/vitess/pull/16619. An alternate change in https://github.com/vitessio/vitess/pull/16735 has already fixed the issue. This PR adds a test to our test suite to check that is indeed the case.
- Fixes #16624 
> Add a test to verify we respect the overall query timeout

- MAINTAINERS.md
This PR removes Dkhenry from the areas of expertise section of the maintainers file.
> Remove former maintainer from areas of expertise section

- go/vt/vtgate/engine/fake_vcursor_test.go
- go/vt/vtgate/engine/plan_description.go
- go/vt/vtgate/engine/primitive.go
- go/vt/vtgate/engine/vexplain.go
- go/vt/vtgate/executor_vexplain_test.go
- go/vt/vtgate/vcursor_impl.go
With this PR we will now track another metric for `vexplain trace`: the amount of shards hit by each route. This metric will enable us to know if a plan hits more or less shards for the same result, which is an useful indicator of performance.
After running the 30x local examples here is what we get:
```
mysql> vexplain trace select * from corder\G
*************************** 1. row ***************************
Trace: {
"Variant": "Scatter",
"Keyspace": {
"Name": "customer",
},
"NoOfCalls": 1,
"AvgNumberOfRows": 5,
"MedianNumberOfRows": 5,
"ShardsQueried": 2,
"FieldQuery": "select order_id, customer_id, sku, price from corder where 1 != 1",
"Query": "select order_id, customer_id, sku, price from corder",
"Table": "corder"
} …
```
> Count how many shards were hit by routes when using `vexplain`

- go/vt/vtctl/workflow/framework_test.go
- go/vt/vtctl/workflow/server.go
- go/vt/vtctl/workflow/server_test.go
- go/vt/vtctl/workflow/workflow_state_test.go
- go/vt/vttablet/tabletmanager/rpc_vreplication_test.go
- go/vt/wrangler/traffic_switcher.go
We use the table routing rules to decide where reads and writes are routed for tables which are part of `MoveTables` workflows. 
For each table we have rules like 
```
t1 => source.t1 
source.t1 => source.t1
t1@replica => source.t1@replica
source.t1@replica => source.t1@replica
target.t1 => source.t1
```
when no traffic is switched, or when all traffic is switched:
```
t1 => target.t1 
source.t1 => target.t1
t1@replica => target.t1@replica
source.t1@replica => target.t1@replica
target.t1 => target.t1
```
To determine whether writes are switched, we check the route for `t1`. If it is pointing to `target` it is considered that writes have been switched.
The problem comes the same table exists in different source keyspaces. For example if there are two workflows one from `source1`=>`target1` …
> Workflow Status: change logic to determine whether `MoveTables` writes are switched

- go/vt/vttablet/tabletmanager/rpc_vreplication_test.go
The unit test `TestMoveTablesUnsharded` is increasingly flaky. Works locally everytime and also on a separate PR where I only enabled the unit test workflows, it didn't fail a few times I ran them. However on most PRs it seems to fail at least one of the tests (usually the 84 test, though that might be a coincidence).
For now skipping the test until we fix the flakiness.
> CI: Temporarily skip flaky TestMoveTablesUnsharded

- go/test/endtoend/vreplication/migrate_test.go
- go/vt/vtctl/workflow/materializer.go
- go/vt/vtctl/workflow/server.go
- go/vt/wrangler/materializer.go
- test/config.json
We use the target keyspace’s vindex for filtering out rows from the source intended for each target shard. The vindex is qualified by the target keyspace name. When the source cluster has a different name for the keyspace, it fails while trying to stream from the source cluster, because it cannot locate the vindex.
This PR sets the vindex scope to that of the source keyspace if the keyspace names differ. Note that it is assumed that the same vindexes are used on both keyspaces during a `Migrate`
https://github.com/vitessio/vitess/issues/16777
-   [ ] Tests were added or are …
> Migrate Workflow: Scope vindex names correctly when target and source keyspace have different names

- go/test/endtoend/vtgate/queries/timeout/timeout_test.go
This PR skips the test run when vttablet is not on v21.
> flaky test fix for query timeout change

- go/test/endtoend/backup/vtctlbackup/backup_utils.go
- go/test/endtoend/backup/vtctlbackup/pitr_test_framework.go
This is an update to the suite of `backup_pitr` tests. In these tests we restore to a given position or a given timestamp.
As a reminder, the PITR restore sets the tablet type to `DRAINED`, and with no primary configuration.
This PR goes an extra mile, after the server restored from backup and validated, to also check that it is able to join the replication stream. Normally you do not need it to, but if it _is_ able to, that's an extra confirmation that we've applied binlog events correctly.
- https://github.com/vitessio/vitess/issues/11227
- To be used by https://github.com/vitessio/vitess/pull/16295
-   [ ] If this change is to be back-ported to previous releases, a justification is …
> `backup_pitr` CI: validate rejoining replication stream

- go/test/endtoend/vtgate/queries/misc/misc_test.go
- go/vt/vtgate/executor_set_test.go
- go/vt/vtgate/safe_session.go
- go/vt/vtgate/safe_session_test.go
This pull request addresses a critical issue in the handling of time zone settings within our system. The root cause of the problem was that the time zone system setting was not being correctly fetched and interpreted, which led to it being ignored when evaluating the `now()` function.
Specifically, the issue arose because we were storing the time zone variable value using a literal SQL expression. This meant that when we tried to use this value, it was still in its raw, encoded form, rather than being properly decoded into a usable time zone string.
Fixes #16820
-   [x] …
> vtgate: Use the time zone setting correctly

- go/test/endtoend/vtgate/queries/timeout/timeout_test.go
This PR fixes the error messages check in the test `TestOverallQueryTimeout`. This is a test we introduced recently and noticed that there are actually two possible error messages that can be received based on whether it was vttablet or vtgate that sent it. 
This PR fixes the test expectations to align with this.
> Fix error message check on query timeout

- examples/compose/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/vttablet-up.sh
examples/compose/
- docker-compose.beginners.yml: fixed depends_on declarations for vtctld and vtgate services
- README.md: added ' -a' for 'docker-compose ps' for it to match the example output
- vttablet-up.sh: added 's' as units for '--queryserver-config-schema-reload-time 60'
> small fixes for docker-compose setup

- .github/workflows/docker_build_images.yml
The docker images build action was deleted temporarily in https://github.com/vitessio/vitess/pull/16759. However we do need this action to build for release tags. Given that we have v21.0 coming up, this PR adds the workflow back. However it only runs it for the tags
```
push:
branches:
- main
tags:
- 'v[2-9][0-9]*.*' # run only on tags greater or equal to v20.0.0 where this new way of building docker image was changed
workflow_dispatch:
```
Note that this has also added the `workflow_dispatch` trigger, so that we can manually run this from the GitHub UI easily if required. We had an issue recently with Docker Hub throttling and it was non-trivial to find the failed action to rerun. 
This also changes the github instance it runs on to `ubuntu-latest` in line with the recently announced …
> Docker Images Build CI action: add updated version from release-20.0 back in prep for v21 release

- web/vtadmin/package-lock.json
This upgrades JS dependencies to address high CVSS security vulnerabilities.
- Fixes: https://github.com/vitessio/vitess/security/dependabot/390
- Fixes: https://github.com/vitessio/vitess/security/dependabot/391
- Fixes: https://github.com/vitessio/vitess/security/dependabot/393
> VTAdmin: Upgrade deps to address security vulns

- go/vt/discovery/healthcheck.go
- go/vt/discovery/healthcheck_test.go
- go/vt/discovery/keyspace_events_test.go
- go/vt/discovery/topology_watcher_test.go
- go/vt/throttler/demo/throttler_demo.go
- go/vt/vtgate/tabletgateway.go
- go/vt/vttablet/tabletserver/txthrottler/tx_throttler.go
- go/vt/vttablet/tabletserver/txthrottler/tx_throttler_test.go
This PR resolves https://github.com/vitessio/vitess/issues/16074 by allowing filters to be passed into `discovery.NewHealthCheck(...)` _(vs. being inherited from flags only)_ as `vtgate` and `txthrottler` _(in `vttablet`)_ have very different expectations of filtering healthchecks
This change makes "filtering" a 1st-class feature of the healthcheck logic and both use-cases can pass in their required filter(s). This ability to pass filters will be used to filter the healthcheck streams for the `txthrottler` to the local-shard only, in order to resolve https://github.com/vitessio/vitess/issues/16074
- Fixes: https://github.com/vitessio/vitess/issues/16074, where `txthrottler` monitors an entire cell instead of the single-shard it should concern itself with
-   [x] "Backport to:" labels have …
> Support passing filters to `discovery.NewHealthCheck(...)`

- .github/workflows/assign_milestone.yml
This PR addresses this CI failure in Assign Milestone CI, due to `go.mod` now being required to get a golang version:
```bash
Error: The specified go version file at: go.mod does not exist
```
This regression/bug was introduced by https://github.com/vitessio/vitess/pull/16841
- Follow-up to: https://github.com/vitessio/vitess/pull/16841
> Checkout code earlier in Assign Milestone CI

- go/vt/vtgate/executor_test.go
- go/vt/vtgate/legacy_scatter_conn_test.go
- go/vt/vtgate/tx_conn.go
This PR rejects a Atomic Distributed Transaction Commit when the session have modified system settings or using temporary table or have savepoints inside the transaction.
This will be removed when the support is added for it.
- #16245 
> reject atomic distributed transaction on savepoints and modified system settings

- go/vt/mysqlctl/builtinbackupengine.go
- go/vt/mysqlctl/s3backupstorage/s3.go
- go/vt/mysqlctl/xtrabackupengine.go
This PR [fixes a long standing issue](https://github.com/vitessio/vitess/issues/14188) in the xtrabackup engine: the context used to `AddFiles` by the backup storage was canceled before `AddFiles` had the chance to complete. This problem can be experienced with the S3 backup storage, as it uploads the file through a goroutine, [Ceph also does that and have been impacted in the past too](https://github.com/vitessio/vitess/issues/8391). That goroutine wouldn't have time to complete before the `XtrabackupEngine.backupFiles` function returned and canceled the context through a `defer` statement. Leading to `AddFiles` failing since the context we pass got canceled.
To avoid this issue, we never really passed the context down to `AddFiles`. We attempted to pass the context in …
> Fix `xtrabackup`/`builtin` context when doing `AddFiles`

- go/vt/vtctl/workflow/traffic_switcher.go
- go/vt/vtctl/workflow/traffic_switcher_test.go
You can specify the columns which make up a vindex in two ways within the vschema:
1. The "legacy" way (a simple string): 
```
"corder": {
"column_vindexes": [
{
"column": "customer_id",
"name": "hash"
}
],
"auto_increment": {
"column": "order_id",
"sequence": "order_seq"
}
},
```
2. The "new" way (an array):
```
"product": {
"column_vindexes": [
{
"columns": [
"product_id"
],
"name": "hash"
}
],
"auto_increment": {
"column": "product_id",
"sequence": "product_seq"
}
}
```
The `MoveTables` target sequence initialization work (added in https://github.com/vitessio/vitess/pull/13656) only supports the legacy way. It needs to be updated to support either. 
That's exactly what this PR does. 🙂 
- Fixes: https://github.com/vitessio/vitess/issues/16861
-   [x] "Backport to:" labels have been …
> VReplication: Support both vindex col def formats when initing target sequences

- go/vt/discovery/healthcheck.go
- go/vt/discovery/healthcheck_test.go
- go/vt/discovery/keyspace_events_test.go
- go/vt/discovery/topology_watcher.go
- go/vt/discovery/topology_watcher_test.go
- go/vt/throttler/demo/throttler_demo.go
- go/vt/vtgate/tabletgateway.go
- go/vt/vttablet/tabletserver/txthrottler/tx_throttler.go
- go/vt/vttablet/tabletserver/txthrottler/tx_throttler_test.go
This PR is a manual backport of https://github.com/vitessio/vitess/pull/16170 to `release-19.0` _(as discussed offline with @deepthi)_
The reasoning for this backport is it resolves a regression in the `txthrottler` _(in `vttablet`)_ that causes a healthcheck stream to be opened to N x tablets _(every tablet in every cell)_, when only the local shard tablets are required. This regression began in v15 [when `go/vt/discovery` was refactored](https://github.com/vitessio/vitess/pull/10542)
https://github.com/vitessio/vitess/pull/16170 …
> [release-19.0] Support passing filters to `discovery.NewHealthCheck(...)` (#16170)

- go/vt/discovery/healthcheck.go
- go/vt/discovery/healthcheck_test.go
- go/vt/discovery/keyspace_events_test.go
- go/vt/discovery/topology_watcher_test.go
- go/vt/throttler/demo/throttler_demo.go
- go/vt/vtgate/tabletgateway.go
- go/vt/vttablet/tabletserver/txthrottler/tx_throttler.go
- go/vt/vttablet/tabletserver/txthrottler/tx_throttler_test.go
This PR is a manual backport of https://github.com/vitessio/vitess/pull/16170 to `release-20.0` _(as discussed offline with @deepthi)_ 
The reasoning for this backport is it resolves a regression in the `txthrottler` _(in `vttablet`)_ that causes a healthcheck stream to be opened to N x tablets _(every tablet in every cell)_, when only the local shard tablets are required. This regression began in v15 [when `go/vt/discovery` was refactored](https://github.com/vitessio/vitess/pull/10542)
https://github.com/vitessio/vitess/pull/16170 …
> [release-20.0] Support passing filters to `discovery.NewHealthCheck(…)` (#16170)

- .github/workflows/vitess_tester_vtgate.yml
- test/templates/cluster_vitess_tester.tpl
Upgrade the `vitess-tester` version we use to the latest one.
> upgrade vitess-tester to latest version

- .github/workflows/update_golang_version.yml
The go upgrade PR has not run in a few days since we changed the way we set up go in GHA. This PR fixes it.
> Fix golang upgrade workflow

- go/mysql/sqlerror/constants.go
- go/vt/vttablet/tabletserver/tabletserver.go
Add `ERInnodbIndexCorrupt` (error 1817) to the list of known MySQL errors. This can be used in the future to recognize terminal `ApplySchema` or Online DDL scenarios.
none
> MySQL errors: `ERInnodbIndexCorrupt`

- go/pools/smartconnpool/waitlist.go
- go/pools/smartconnpool/waitlist_test.go
Fixes a bug that causes `waitlist.expire` to only remove the first expired waiter on each invocation. This is due to calling `wl.list.Remove(e)` while traversing the list. This sets `e.Next` to `nil`, which terminates the loop. The fix is to remove waiters from the list after traversing it. 
I think this should be backported to v19+. With the right combination of client behavior, query timeouts, and transaction timeouts, this bug can lead to tablets locking up indefinitely with all attempts to get a connection timing out.
Fixes https://github.com/vitessio/vitess/issues/16896 …
> VTTablet: smartconnpool: notify all expired waiters

- go/vt/vtgate/engine/fake_vcursor_test.go
- go/vt/vtgate/engine/mirror.go
- go/vt/vtgate/engine/mirror_test.go
- go/vt/vtgate/engine/primitive.go
- go/vt/vtgate/logstats/logstats.go
- go/vt/vtgate/logstats/logstats_test.go
- go/vt/vtgate/vcursor_impl.go
- go/vt/vtgate/vcursor_impl_test.go
This PR adds a few new fields to log stats to provide visibility into traffic mirroring. The idea behind traffic mirroring is to see if the target of a VReplication workflow will perform as well as the source when queries are sent to it. In order to make that determination, we can send mirrored queries to the target with `MirrorTraffic`. However, we also need a way to compare the query execution times and errors of the source vs. target queries.
While working on this PR, I noticed a bug with how mirror target queries are bounded. The VTGate mirror primitive was written with the intention of having the mirror target be canceled if it continues executing for too long (hardcoded at 100ms) after the source primitive finishes executing. However as it is currently written the mirror target will …
> Query serving: incorporate mirror query results in log stats, fix mirror query max lag bug

- changelog/21.0/21.0.0/summary.md
MySQL 8.4 passes the test suites, but it's otherwise not yet tested. This should be good enough then to mark it as experimentally supported to ask community feedback and hopefully more people test it out.
Part of https://github.com/vitessio/vitess/issues/16466
> Add blurb about experimental 8.4 support

- go/test/endtoend/vtorc/general/vtorc_test.go
- go/test/endtoend/vtorc/utils/utils.go
- go/vt/vtorc/inst/analysis_dao.go
- go/vt/vtorc/inst/analysis_dao_test.go
- go/vt/vtorc/logic/tablet_discovery.go
- go/vt/vtorc/logic/tablet_discovery_test.go
This PR fixes the issue described in https://github.com/vitessio/vitess/issues/16887. VTOrc now remembers all the tablets in its state, even if they aren't of a replica type. We just ensure not to run any repairs on them. This ensures that all the shard metrics that VTOrc publishes like `ErrantGTIDTabletCount` are correct since it is seeing the full picture and not a part of it.
- Fixes https://github.com/vitessio/vitess/issues/16887 …
> Remember all tablets in VTOrc

- go/flags/endtoend/mysqlctld.txt
- go/flags/endtoend/vtbackup.txt
- go/flags/endtoend/vtcombo.txt
- go/flags/endtoend/vtctlclient.txt
- go/flags/endtoend/vtctld.txt
- go/flags/endtoend/vtgate.txt
- go/flags/endtoend/vtgateclienttest.txt
- go/flags/endtoend/vtorc.txt
- go/flags/endtoend/vttablet.txt
- go/flags/endtoend/vttestserver.txt
- go/vt/discovery/healthcheck.go
- go/vt/discovery/tablet_health_check.go
- go/vt/grpcclient/client.go
There's a concurrent connection dial limit implemented in the healthcheck code that doesn't semantically or logically belong here.
First, the healthcheck code does neither know nor care about the network protocol used to execute healthchecks. Arguably, there's no other protocol used for this apart from `grpc`, but it seems wrong to set up `grpc` connection specific options in the healthcheck code.
Additionally, the dial concurrency limit modifies the global `grpc` connection options the first time a healthcheck is started. That seems unexpected, and I believe we want the concurrency limit set for all `grpc` dial operations, irrespective of whether those connections are used for healtchecking or anything else.
This change moves the concurrency limit into the `grpcclient` package, and sets …
> Move concurrent connection dial limit out of `healthcheck`.

- go/vt/sqlparser/ast_funcs.go
- go/vt/vtgate/executor_vexplain_test.go
- go/vt/vtgate/planbuilder/operators/keys.go
- go/vt/vtgate/planbuilder/operators/keys_test.go
- go/vt/vtgate/testdata/executor_vexplain.json
In a PR merged earlier today, I accidentally failed to consider binary operators that have spaces in them, such as `not like` and `not in`. This is a fix for that oversight.
https://github.com/vitessio/vitess/pull/16892
> fix issue with json unmarshalling of operators with space in them

- go/cmd/vtctldclient/command/reparents.go
This PR fixes a typo introduced in #16852 that causes the new `--expected-primary` flag to update the wrong value, `--new-primary`
This slipped through our internal testing as we're using RPCs from code, not via the CLI 🤦 
https://github.com/vitessio/vitess/pull/16852
> Fix flag name typo from #16852

- go/test/endtoend/cluster/cluster_process.go
- go/test/endtoend/cluster/reshard.go
- go/test/endtoend/transaction/twopc/fuzz/fuzzer_test.go
- go/test/endtoend/transaction/twopc/main_test.go
- go/test/endtoend/transaction/twopc/twopc_test.go
- go/vt/vtgate/executor_test.go
- go/vt/vtgate/tx_conn.go
- go/vt/vttablet/endtoend/savepoint_test.go
- go/vt/vttablet/tabletserver/dt_executor.go
- go/vt/vttablet/tabletserver/planbuilder/plan.go
- go/vt/vttablet/tabletserver/query_executor.go
- go/vt/vttablet/tabletserver/tabletserver.go
- go/vt/vttablet/tabletserver/tx/api.go
- go/vt/vttablet/tabletserver/tx/api_test.go
- go/vt/vttablet/tabletserver/tx_engine.go
- go/vt/vttablet/tabletserver/tx_engine_test.go
- go/vt/vttablet/tabletserver/tx_pool.go
- go/vt/vttablet/tabletserver/tx_pool_test.go
This PR adds support for savepoints usage in atomic distributed transaction commit by storing the savepoints in the transaction query log and then reapplying them on a recovery.
- #16245 
> Add savepoint support to atomic distributed transaction

- go/vt/vtgate/executor_test.go
- go/vt/vtgate/plan_execute.go
When buffering is turned off in `vtgate` there is a possibility of a panic when a query is retried, because of this code
`timeout := e.resolver.scatterConn.gateway.buffer.GetConfig().MaxFailoverDuration / (MaxBufferingRetries - 1)`  introduced here: https://github.com/vitessio/vitess/pull/15701/files#diff-19aa815da9f21f65b55cc865090e2cefa77af98b30b134936853f7763898d255R107 in v20.0.
This PR uses the default timeout of 30 seconds, used earlier, if buffering is turned off.
https://github.com/vitessio/vitess/issues/16858
-   [ ] Did …
> VTGate MoveTables Buffering: Fix panic when buffering is disabled

- go/mysql/sqlerror/constants.go
- go/vt/vttablet/tabletmanager/vreplication/utils.go
- go/vt/vttablet/tabletserver/tabletserver.go
Add `ERWrongParamcountToNativeFct ` (error 1582) to the list of known MySQL errors. This can indicate terminal vreplication error, and otherwise could be helpful in Online DDL diagnostics.
none
> MySQL errors: `ERWrongParamcountToNativeFct`

- go/vt/binlog/binlogplayer/mock_dbclient.go
- go/vt/vttablet/tabletmanager/framework_test.go
- go/vt/vttablet/tabletmanager/rpc_vreplication_test.go
Since https://github.com/vitessio/vitess/pull/16583 we've seen the `TestMoveTablesUnsharded` and `TestMoveTablesSharded` tests become flaky. Especially the Sharded one.
The only directly relevant change made to these unit tests in that PR is adding the `vrdbClient.Reset()` call. That call however is not safe as it modifies the members while holding a mutex, most notably the done channel. The problem, however, is that we explicitly and intentionally do not take that mutex in the `Wait()` function, which is the primary user of that channel. 
It's not 100% clear that this was the cause of the flakiness, but given that it was the only directly relevant change, we know it's unsafe, and CI failures that I saw (I was unable to repeat the test failures locally) seemed to indicate a repeated …
> Flakes: Address flakes in TestMoveTables* unit tests

- web/vtadmin/src/components/inputs/Select.tsx
- web/vtadmin/src/components/routes/workflow/Workflow.tsx
- web/vtadmin/src/components/routes/workflow/WorkflowDetails.tsx
- web/vtadmin/src/hooks/api.ts
This PR adds refresh compatibility providing the user functionality to enable auto refresh workflow status after some selectable intervals (10s, 30s, 1m, 10m or Never.) Also, removes the redundant "Scroll to streams" link from all workflow pages. This PR is a follow-up to #16706.
- Fixes #16687 
> VTAdmin(web): Add refresh compatibility to workflow screen (all tabs)

- go/mysql/server_test.go
- go/vt/mysqlctl/fakemysqldaemon.go
- go/vt/vtctl/grpcvtctldserver/server_test.go
- go/vt/vttablet/tabletmanager/framework_test.go
- go/vt/wrangler/testlib/backup_test.go
- go/vt/wrangler/testlib/emergency_reparent_shard_test.go
- go/vt/wrangler/testlib/planned_reparent_shard_test.go
- go/vt/wrangler/testlib/reparent_utils_test.go
- go/vt/wrangler/traffic_switcher_env_test.go
This PR fixes some of the tests that we've noticed to be flaky in the CI.
- `TestTabletExternallyReparented` - In the check for the final list of tablets, we were using a context with a 10ms timeout. That is very low, even if all the topo calls are local (test uses memorytopo). In some cases, the final call to get tablets for a cell will expire, leading to incomplete list and a failure like so - 
```
2024-09-11T23:58:45.2613127Z === NAME  TestTabletExternallyReparented/success
2024-09-11T23:58:45.2613346Z     proto_compare.go:118: []: (-want +got)
2024-09-11T23:58:45.2613553Z           []*topodata.Tablet{
2024-09-11T23:58:45.2614267Z         - 	s`alias:{cell:"zone1" uid:100} keyspace:"testkeyspace" shard:"-" type:PRIMARY primary_term_start_time:{seconds:1000}`, …
```
> Flaky test fixes

- go/stats/export.go
- go/stats/export_test.go
safeJoinLabels is in a pretty hot path for builtinbackupengine, every Read/Write file operation requires 2 calls to this function through (*scopedStats).TimedIncrementBytes.
An optimization pass to this function was pretty low hanging fruit compared to trying to materialize/cache the label values correctly.
```
$ benchstat {before,after}.txt
goos: darwin
goarch: arm64
pkg: vitess.io/vitess/go/stats
cpu: Apple M1 Max
│  before.txt  │              after.txt              │
│    sec/op    │   sec/op     vs base                │
SafeJoinLabels/no_combined-10   204.40n ± 1%   84.58n ± 0%  -58.62% (p=0.000 n=10)
SafeJoinLabels/combined-10       87.54n ± 9%   30.98n ± 1%  -64.60% (p=0.000 n=10)
geomean                          133.8n        51.19n       -61.73%
│ before.txt  │ …
```
> go/stats: improve performance of safeJoinLabels

- .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
This PR reverts the changes made to the upgrade tests in #16494. The situation has evolved as follows - 
1. Prior to changes in #16494, we would always run the code in the branch for both upgrade and downgrade tests. This caused us to add `SkipIfBinaryBelowVersion` lines whenever we added a new feature, because the older binaries wouldn't support them, and downgrade tests would fail without them.
2. In #16494, we changed both upgrade and downgrade tests to use the code in the other branch. So, on main running downgrade tests would run tests from v20.0, and running upgrade tests from v20.0 would run tests from main. This caused a different issue where when we add a new test, it doesn't run in downgrade on main, and everything works, but then upgrade tests from v20.0 would run this new test …
> Change upgrade test to still use the older verion of tests

- go/test/endtoend/vtgate/vitess_tester/aggregation/aggregation.test
- go/vt/vtgate/planbuilder/operators/horizon_expanding.go
- go/vt/vtgate/planbuilder/plan_test.go
- go/vt/vtgate/planbuilder/testdata/aggr_cases.json
- go/vt/vtgate/planbuilder/testdata/cte_cases.json
Make sure to add columns needed by HAVING to the derived table.
Fixes #16965
> bugfix: add HAVING columns inside derived tables

- go/vt/vtgate/engine/route.go
- go/vt/vtgate/engine/vindex_lookup_test.go
This PR fixes the bug with route with lookup vindex where Vindex Lookup operator on calling the Route was not truncating the output. 
This was missed for non-streaming execution mode.
Backport Reason: This is correctness issue with the query result output.
- Fixes https://github.com/vitessio/vitess/issues/16965
> fix: route engine to handle column truncation for execute after lookup

- go/vt/vtctl/grpcvtctldserver/server.go
- go/vt/vtctl/grpcvtctldserver/server_test.go
This PR fixes the bug in GetUnresolvedTransactions wherein we don't show the complete list of participants but omit the metadata manager shard.
This is a forward port for https://github.com/vitessio/vitess/pull/16949
- #16245 
> Fix `GetUnresolvedTransactions` command for Vtctld

- go/test/endtoend/transaction/twopc/stress/main_test.go
- go/test/endtoend/transaction/twopc/stress/schema.sql
- go/test/endtoend/transaction/twopc/stress/stress_test.go
- go/test/endtoend/transaction/twopc/stress/vschema.json
- go/test/endtoend/transaction/twopc/twopc_test.go
- go/test/endtoend/transaction/twopc/utils/utils.go
- go/vt/vtgate/executor_test.go
- go/vt/vtgate/tx_conn.go
- go/vt/vttablet/sandboxconn/sandboxconn.go
- go/vt/vttablet/tabletserver/query_executor.go
- go/vt/vttablet/tabletserver/stateful_connection.go
- go/vt/vttablet/tabletserver/tx_engine.go
- go/vt/vttablet/tabletserver/tx_engine_test.go
- go/vt/vttablet/tabletserver/tx_pool.go
This PR adds the support to store the settings changes that were made in an atomic transaction so that redoing them works with those settings.
Vitess handles `SET <variable>=<value>` commands in different ways based on the settings variable that is being set - 
- `IgnoreThese` - Some variables like `big_tables` are just ignored by Vitess.
- `NotSupported` - Trying to set variables like `binlog_row_image` just fails.
- `ReadOnly` - These variables like `version` can only be read and not updated.
- `CheckAndIgnore` - These variables are ignored when tried to update.
- `VitessAware` - These variables change vitess behaviour. Sometimes, they are stored in the session and also sent down to vttablets to be set on MySQL. 
- `UseReservedConn` - We don't use reserved connections any more (we use …
> Support settings changes with atomic transactions

- go/mysql/server_test.go
We have seen the `TestServerStats` unit test fail pretty regularly, in particular in the `unit_race` workflow. Example failure:
```
--- FAIL: TestServerStats (0.02s)
server_test.go:265: listening on address '127.0.0.1' port 41297
server_test.go:1363: Running mysql command: /usr/bin/mysql [-v -v -v -e error -h 127.0.0.1 -P 41297 -u user1 -ppassword1]
server_test.go:670: 
Error Trace:	/opt/actions-runner/_work/vitess-private/vitess-private/go/mysql/server_test.go:670
Error:      	Not equal: 
expected: int(0)
actual  : int64(1)
Test:       	TestServerStats
Messages:   	connCount
```
I could not repeat the failure locally (despite trying many different methods), but in walking through the code it was clear that we had a potential race here. The race is this:
- The test starts a mysql server …
> Flakes: Address TestServerStats flakiness

- changelog/21.0/21.0.0/summary.md
This PR adds a missing v21 changelog for https://github.com/vitessio/vitess/pull/16852
cc @rohit-nayak-ps 
https://github.com/vitessio/vitess/pull/16852
> Add missing changelog for PR #16852

- go/vt/discovery/healthcheck.go
- go/vt/discovery/topology_watcher_test.go
This PR fixes the deadlock described in https://github.com/vitessio/vitess/issues/16994. 
The problem was that the sending on the channel `loadTabletsTrigger` in `updateHealth` was a blocking call. So, in this PR, I've changed the channel from being an unbuffered channel to a buffered channel of a single capacity. I have also updated the sending on the channel `loadTabletsTrigger` in `updateHealth` to be unblocking. 
This fix has 2 advantages - 
1. It fixes the deadlock, since now `updateHealth` cannot block on sending on the channel. It will either succeed in sending, or just move ahead since the channel would already be full.
2. Not super important, but still, if multiple `updateHealth` calls happen really quickly, we won't trigger multiple runs of loadTablet since we won't send on an …
> Fix deadlock between health check and topology watcher

- .github/CODEOWNERS
- go/vt/vtctl/workflow/server.go
- go/vt/vtctl/workflow/server_test.go
The vtctld client performed various input validations and handling for the [vdiff create command](https://vitess.io/docs/reference/programs/vtctldclient/vtctldclient_vdiff/vtctldclient_vdiff_create/) here: https://github.com/vitessio/vitess/blob/e881b9f36d9adb497cd6bd8304bb3e2fa6fd69b9/go/cmd/vtctldclient/command/vreplication/vdiff/vdiff.go#L95
People are, however, starting to use the `VtctldServer` RPCs directly rather than using `vtctldclient`. So specifically for the `VDiffCreate` RPC, we should do some of the defaults handling there. In this case we should generate a new UUID there if none was provided in the request. That's exactly what this PR does.
- Fixes: https://github.com/vitessio/vitess/issues/17001
-   [x] "Backport to:" labels have been added if this change should be …
> VDiff: Also generate default new UUID in VtctldServer VDiffCreate

- go/ioutil/writer.go
- go/vt/mysqlctl/fakemysqldaemon.go
- go/vt/mysqlctl/mysqlshellbackupengine.go
- go/vt/mysqlctl/mysqlshellbackupengine_test.go
This fixes an issue we noticed during testing where if the backup process (`mysqlsh`) fails, be it because of incorrect parameters, missing binary, etc, it won't release the global read lock we are holding on the instance. This ensures we are releasing the lock even if we hit an error early on.
I also added unit tests to capture when those particular scenarios happen.
Fixes https://github.com/vitessio/vitess/issues/17011, an issue introduced that only affects the new `mysqlshell` backup engine introduced in https://github.com/vitessio/vitess/pull/16295
-   [x] Tests were …
> fix releasing the global read lock when mysqlshell backup fails

- go/vt/vtctl/workflow/server.go
- go/vt/vtctl/workflow/server_test.go
In `GetWorkflows()` we use the following algo while collecting logs for a workflow.
We first sort all the streams of each shard by `streamID` in ASC order. Now, we call `fetchStreamLogs` for each workflow. Inside `fetchStreamLogs`, we fetch the streamLogs from each tablet. Now, we run a `for` loop across all the tablets we got from `results` (from query for fetching logs and results sorted by `streamID` in ASC order). Now, as we have already sorted the `shardStreams` by `streamID` and logs are also ordered by `streamID`, so we use a variable `streamIdx` which starts from 0. Now, we run a `for` loop across stream log results from that particular tablet (we got from the outer loop). In this loop, we update `streamIdx` in this code block:
```go
for streamIdx < len(streams) {
stream := …
```
> fix: Infinite logs in case of non-existent stream logs

- go/test/endtoend/vreplication/movetables_mirrortraffic_test.go
- go/test/endtoend/vreplication/partial_movetables_test.go
- go/test/endtoend/vreplication/vdiff_online_ddl_test.go
- go/test/endtoend/vreplication/vreplication_vtctldclient_cli_test.go
In https://github.com/vitessio/vitess/pull/16920 we changed the behavior of the minimal cluster setup so that it went from using a hardcoded value of 0 for the `replica` and `rdonly` tablet counts, to instead using the default globals for that (`defaultReplicas`, `defaultRdonly`): https://github.com/vitessio/vitess/pull/16920/files#diff-127f033346a57c5e68aaa42072891ad18fca2bd1463eb16cd16a23f74b136576R942
When working on that PR I noticed that the buffering test started failing every time and the cause was that it now had replicas (and rdonly tablets) and they could not keep up with the load being generated against the primary. So (v)replication could not catch up in time and the `vdiff` did not finish before the 30s timeout. I addressed that in the PR here: …
> VReplication: Restore previous minimal e2e test behavior

- go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go
- go/vt/vttablet/onlineddl/executor.go
- go/vt/vttablet/onlineddl/schema.go
- go/vt/vttablet/tabletmanager/vreplication/controller.go
- go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go
Today, `vreplication` based Online DDL reads `_vt.vreplication` table, and uses `state` and `message` columns as indicators to errors.
However, these columns, even if there's a terminal error, can be overwritten and shadowed by later changes to `vreplication` state, as described in https://github.com/vitessio/vitess/issues/16924.
Thankfully, `_vt.vreplication_log` persists all states and messages throughout the workflow's lifetime. In this PR, Online DDL ensures to search for error-indicating states/messages in `_vt.vreplication_log`. If found, these are picked and used by Online DDL to determine that the migration is broken, and advertised forward in `_vt.schema_migrations.message`.
We furthermore prepend:
- `terminal error:` prefix for terminal errors in vreplication.
- `vreplication:` …
> Online DDL: detect `vreplication` errors via `vreplication_log` history

- go/test/endtoend/cluster/vtgate_process.go
- go/test/endtoend/transaction/twopc/metric/main_test.go
- go/test/endtoend/transaction/twopc/metric/metric_test.go
- go/test/endtoend/transaction/twopc/metric/schema.sql
- go/test/endtoend/transaction/twopc/metric/vschema.json
- go/test/endtoend/transaction/twopc/metric_test.go
- go/test/endtoend/transaction/twopc/twopc_test.go
- go/test/endtoend/transaction/twopc/utils/utils.go
- go/test/endtoend/transaction/tx_test.go
- go/test/endtoend/vtgate/misc_test.go
- go/vt/vtgate/executor.go
- go/vt/vtgate/tx_conn.go
- go/vt/vttablet/tabletserver/debug_2pc.go
- go/vt/vttablet/tabletserver/dt_executor.go
- go/vt/vttablet/tabletserver/production.go
- go/vt/vttablet/tabletserver/tabletenv/stats.go
- go/vt/vttablet/tabletserver/tabletserver.go
- go/vt/vttablet/tabletserver/tx_engine.go
- test/config.json
This PR adds metrics to distributed transaction comit flow for tracking timings and failures.
New Metrics:
- VTGate
- `CommitModeTimings` - Timing metrics for commit (Single, Multi, TwoPC)
- `CommitUnresolved` - Counter for failure after Prepare
- VTTablet
- `UnresolvedTransaction` - Gauge to track current unresolved transactions in Metadata and Resource Manager.
- `CommitPreparedFail` - Transactions that failed to commit after prepare (classified into Retryable and Non-Retryable)
-  `RedoPreparedFail` - Transactions that failed to re-prepare (classified into Retryable and Non-Retryable)
- #16245 
> feat: add metrics for atomic distributed transactions

- .github/workflows/create_release.yml
This PR fixes the release workflow that build and push the release artefacts to a new release. This failed very recently as we released `v21.0.0-rc1`: https://github.com/vitessio/vitess/actions/runs/11339640858. As of now `v21.0.0-rc1` does not have any release artefacts attached to it.
The problem is that we are attempting to read `go.mod` before checking out the source code. This bug was introduced by https://github.com/vitessio/vitess/pull/16841
Since we will not be able to re-trigger the workflow on a `release` gh event (we can only on branch/tags), and the workflow we use depend on that, I am going to modify the workflow in another commit to allow it to run from this PR and build+push the release artefacts, that way everything is done within CI and not done manually.
As we changed …
> Fix the release workflow

- go/mysql/auth_server_clientcert_test.go
- go/mysql/auth_server_static.go
- go/mysql/auth_server_static_test.go
- go/mysql/handshake_test.go
- go/mysql/replication_test.go
- go/mysql/server_test.go
We've had some flakiness in the `go/mysql` package's unit tests, but in particular with `TestTLSRequired`:
```
--- FAIL: TestTLSRequired (3.03s)
server_test.go:1001: 
Error Trace:	go/mysql/server_test.go:1001
Error:      	"cannot send HandshakeResponse41: write tcp 127.0.0.1:33754->127.0.0.1:27379: write: connection reset by peer\nWrite(packet) failed\nconn 3 (errno 2013) (sqlstate HY000)" does not contain "remote error: tls: bad certificate"
Test:       	TestTLSRequired
```
That test is unique in the package in that it calls `Connect` multiple times. So we address that in this PR by adding handling for when the listener goes away for any reason.
In working on this, I also realized that these unit tests are all leaking goroutines. Which not only impacts the other tests in this package …
> Flakes: Setup new fake server if it has gone away

- config/vtorc/default.json
- examples/common/vtorc/config.json
- examples/compose/vtorc-up.sh
- examples/compose/vtorc/default.json
- go/test/endtoend/cluster/vtorc_process.go
This PR cleans up the usage of MySQL parameters that were removed  a while ago from VTOrc. The test code was still setting them, but they're no longer required.
> Remove mysql parameters from VTOrc setup

- go/test/endtoend/vtgate/queries/vexplain/vexplain_test.go
The fix in https://github.com/vitessio/vitess/pull/16988 makes a change here that's not really a breaking change, but it does break the test as the test matches the exact string output which changes here due to a binary value.
Needed for https://github.com/vitessio/vitess/pull/16988 which is a fix for https://github.com/vitessio/vitess/issues/16989. 
> Relax vexplain test for upcoming changes

- go/mysql/binlog_event_compression.go
- go/mysql/binlog_event_compression_test.go
This is a follow-up to https://github.com/vitessio/vitess/pull/16328. There we added usage of `sync.Pool`, however when putting the object back in the pool we used the wrong pool. Instead of using [the `statelessDocoderPool`](https://github.com/vitessio/vitess/blob/03b93a1e3b4cb2300c533832cc43e30b24d36106/go/mysql/binlog_event_compression.go#L84-L109) we were using another `sync.Pool` instance that also existed in the package: [`readersPool`](https://github.com/planetscale/vitess/blob/4522a0ad8930f3556627ec1ebbe69103f3b0fc01/go/mysql/conn.go#L247).
This caused the  `statelessDocoderPool` to NOT be used, but worse than that it could cause a panic when the `readersPool` was used here IF [`--mysql-server-pool-conn-read-buffers`](https://github.com/vitessio/vitess/blob/03b93a1e3b4cb2300c533832 …
> Use proper zstd decoder pool for binlog event compression handling

- go/cmd/vtctldclient/command/vreplication/vdiff/vdiff.go
- go/vt/proto/vtctldata/vtctldata.pb.go
- go/vt/vtctl/workflow/server.go
- proto/vtctldata.proto
This is some internal cleanup that I wanted to do after helping some people use[ the `VtctldServer` `VDiff` RPCs](https://github.com/vitessio/vitess/blob/4522a0ad8930f3556627ec1ebbe69103f3b0fc01/proto/vtctlservice.proto#L361-L365) directly. It's mostly comments, but it also enforces a couple of additional server side defaults in a sensible way (and which matches [the official vtlctld client flag defaults](https://github.com/vitessio/vitess/blob/main/go/cmd/vtctldclient/command/vreplication/vdiff/vdiff.go)). 
-   [x] Did the new …
> VDiff: Comment the VDiffCreate proto msg and set reasonable server side defaults

- changelog/21.0/21.0.0/changelog.md
- changelog/21.0/21.0.0/release_notes.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/401_scheduled_backups.yaml
- examples/operator/operator.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v21.0.0-RC2` release. Once this PR is merged, we will be able to tag `v21.0.0-RC2` on the merge commit.
> [release-21.0] Release of `v21.0.0-RC2`

- go/vt/vttablet/endtoend/queries_test.go
- go/vt/vttablet/tabletserver/planbuilder/plan.go
- go/vt/vttablet/tabletserver/planbuilder/testdata/exec_cases.txt
This PR fixes an issue in the tablet server where bind variables (bindvars) were not correctly handled in EXPLAIN queries. Queries such as:
```sql
EXPLAIN SELECT @p
``` 
were being sent with placeholders (e.g., `:__udvp`) still present, leading to a syntax error on MySQL, since our bindvar syntax is not compatible with MySQL’s native syntax.
Fixes #17053
> bugfix: treat EXPLAIN like SELECT

- go/test/endtoend/vreplication/sidecardb_test.go
- go/vt/vttablet/tabletserver/schema/engine.go
- go/vt/vttablet/tabletserver/schema/engine_test.go
- go/vt/vttablet/tabletserver/state_manager.go
- go/vt/vttablet/tabletserver/state_manager_test.go
We noticed that the sidecardb logic to detect schema changes in vitess internal tables is running on both the transitions of going to primary serving and primary non-serving. We think it would be a good idea to only do this when a primary is transitioning to serving state. A couple of reasons for it - 
1. `DemotePrimary` is already quite a heavy operation that sometimes times out, so we shouldn't do more work on this call.
2. If a primary tablet already applied the DDL changes when it went into serving state, then there should be no DDLs pending to be applied when it demoting itself. The check for finding the schema diff is therefore wasted effort at that point.
3. In `EmergencyReparentShard`, we demote the primary in parallel with stopping replication on replicas. This means that if even …
> Only run sidecardb change detection on serving primary tablets

- go/test/endtoend/transaction/twopc/main_test.go
This PR fixes the flaky test issue with twopc transactions test.
It now waits for vstream from all the shards before proceeding with the test case.
> fix: flaky test on twopc transaction

- go/vt/vttablet/onlineddl/executor.go
This PR adds more wrapping/clarifications to the `error` returned by `cutOverVReplMigration()`. The function already logs the required information. However, the error returned by the function is also captured in `vitess_migrations.message` column, and right nwo it is not informative enough. For example, it might read "due to context timeout" which isn't helpful if you don't know what specific operation was timing out. Again, the logs have the information, but it will be so much nicer to have more clarity in the `message` column.
None.
-   [ ] Tests were added or are not …
> Online DDL: better error messages in cut-over phase

- changelog/21.0/21.0.0/summary.md
This PR adds Atomic Distributed Transaction to release notes.
- #16245 
> [Direct PR][release note]: Atomic Distributed Transaction

- go/vt/vtgate/planbuilder/operator_transformers.go
- go/vt/vtgate/planbuilder/operators/SQL_builder.go
- go/vt/vtgate/planbuilder/operators/ast_to_op.go
- go/vt/vtgate/planbuilder/operators/delete.go
- go/vt/vtgate/planbuilder/operators/expressions.go
- go/vt/vtgate/planbuilder/operators/fk_cascade.go
- go/vt/vtgate/planbuilder/operators/fk_verify.go
- go/vt/vtgate/planbuilder/operators/update.go
- go/vt/vtgate/planbuilder/plancontext/planning_context.go
- go/vt/vtgate/planbuilder/testdata/foreignkey_cases.json
- go/vt/vtgate/planbuilder/testdata/from_cases.json
- go/vt/vtgate/planbuilder/testdata/postprocess_cases.json
- go/vt/vtgate/planbuilder/testdata/reference_cases.json
- go/vt/vtgate/planbuilder/testdata/select_cases.json
- go/vt/vtgate/planbuilder/testdata/tpcc_cases.json
This PR is on top of other planner bug fix PR that introduced a regression in a backport to v18.
- https://github.com/vitessio/vitess/pull/16962
> Fix release 18 again

- go/vt/vtgate/planbuilder/operators/plan_query.go
- go/vt/vtgate/planbuilder/testdata/select_cases.json
This PR modifies vtgate to bypass column availability checks when a query can be routed to a single shard, allowing MySQL to handle column validation directly. This prevents unnecessary ambiguous column errors at vtgate when schema tracking is disabled.
Fixes #17083
> Delegate Column Availability Checks to MySQL for Single-Route Queries

- changelog/21.0/21.0.0/changelog.md
- changelog/21.0/21.0.0/release_notes.md
- changelog/21.0/21.0.0/summary.md
This PR adds https://github.com/vitessio/vitess/issues/17063 to the known issue
> [release-21.0] Add release notes for known issue in v21.0.0

- go/vt/vtgate/planbuilder/operators/apply_join.go
- go/vt/vtgate/planbuilder/testdata/from_cases.json
Backport more fixes to the 18 branch
Fixes #16990
> bugfix: make sure to split predicates before planning them

- .github/workflows/update_golang_version.yml
Small follow up of the v21.0.0 code freeze. Since we created a new release branch, I am adding it to the Golang Upgrade GH Workflow.
> Add release-21.0 to the Golang Upgrade workflow

- go/vt/vtgate/planbuilder/testdata/from_cases.json
- go/vt/vtgate/semantics/analyzer_test.go
- go/vt/vtgate/semantics/early_rewriter.go
- go/vt/vtgate/semantics/early_rewriter_test.go
This PR addresses an uncaught index out of range panic encountered in Vitess 19.0 during the semantic analysis of certain join queries with non-authoritative tables in the vschema. Specifically, queries with a join on non-authoritative tables that should be merged due to sharding keys trigger a runtime panic if they order by one of these unknown columns.
Fixes #17104
> Bugfix for Panic on Joined Queries with Non-Authoritative Tables in Vitess 19.0

- go/vt/vttablet/tabletmanager/shard_sync_test.go
This PR fixes the flakiness in the test `TestShardSync`.
It was noticed that the test was flaky. The problem was that when the tablet is promoted to a primary type, it starts shard sync, but it happens asynchronously. In the meantime we also update the shard record in the topo server. If the shard record is updated before the shard watch for the record has started, the tablet doesn't run a shard sync loop for 30 seconds, and that fails the test.
This PR fixes the test by adding an explicit wait for the shard watch to have started.  …
> Fix flaky test `TestShardSync`

- go/cmd/vttablet/cli/cli.go
- go/cmd/vttablet/cli/cli_test.go
- go/vt/topo/server.go
As described in https://github.com/vitessio/vitess/issues/17093 we were closing the topo server in vttablet twice: in a defer function, and right before returning an error. This PR fixes the issue.
Using the same reproduction as the one detailed in the issue, we get:
```
$  kubectl logs example-vttablet-zone1-2469782763-bfadd780
W1028 20:22:32.006847       1 log.go:39] Failed to read in config : Config File "vtconfig" Not Found in "[/]". This is optional, and can be ignored if you are not using config files. For a detailed explanation, see https://github.com/vitessio/vitess/blob/main/doc/viper/viper.md#config-files.
I1028 20:22:32.014869       1 servenv_unix.go:57] Version: 22.0.0-SNAPSHOT (Git revision 4550640e0882ad71d79bde47e78f7e2123522145 branch …
```
> Fix panic in vttablet when closing topo server twice

- go/test/endtoend/vreplication/cluster_test.go
- go/test/endtoend/vreplication/config_test.go
- go/test/endtoend/vreplication/unsharded_init_data.sql
- go/test/endtoend/vreplication/vreplication_test.go
- go/vt/vttablet/tabletmanager/vreplication/replicator_plan.go
- go/vt/vttablet/tabletmanager/vreplication/table_plan_builder.go
- go/vt/vttablet/tabletmanager/vreplication/table_plan_partial.go
- go/vt/vttablet/tabletserver/vstreamer/helper_event_test.go
- go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go
We were using the lowercase column name when building the map of columns to ignore in the copy phase — where we copy the filtered rows from a SELECT statement on the source — but then using the case we got back from MySQL when checking the map. h/t to @aluque01 for doing all of the hard work around this in the issue.
Without the code fix, the tests such as `TestBasicV2Workflows` fail with:
```
=== NAME  TestBasicV2Workflows
resharding_workflows_v2_test.go:175: Executing workflow command: vtctldclient MoveTables --workflow wf1 --target-keyspace customer Create --source-keyspace product --tables customer,loadtest,vdiff_order,reftable,_vt_PURGE_4f9194b43b2011eb8a0104ed332e05c2_20221210194431 --defer-secondary-keys --cells zone1 --action_timeout=10m
helper_test.go:409:
Error Trace: …
```
> VReplication: Fixes for generated column handling

- go/test/endtoend/cluster/vtctldclient_process.go
- go/test/endtoend/transaction/twopc/utils/utils.go
This test fixes some flakiness observed in the `TestDisruptions` for two pc testing. There are 2 fixes in this PR - 
1. When we start a new shard, we weren't waiting for the primary tablet to be serving. This sometimes led to vreplication not finding a serving primary tablet to create vreplication streams at. This fails resharding workflow sometimes. The fix is to just wait for a serving tablet.
2. PlannedReparentShard sometimes was timing out because it took some time for the outstanding writes from being killed. Increasing the timeout made this less of an issue.
-   [x] …
> Fix flakiness in `TestDisruptions` for two pc testing

- changelog/18.0/18.0.0/summary.md
This PR adds the known issue with sidecard db where it continues to find a schema diff and applies the change that doesn't change the DDL. Caused when https://github.com/vitessio/vitess/pull/15859 was merged.
> [Direct PR] [release-18.0]: Add `sidecardb` known issue

- go/flags/endtoend/vtorc.txt
- go/vt/topo/keyspace.go
- go/vt/topo/shard.go
- go/vt/topo/tablet.go
- go/vt/topo/tablet_test.go
- go/vt/vtorc/logic/tablet_discovery.go
This PR adds [a similar optimization to this PR](https://github.com/vitessio/vitess/pull/14693) to `vtorc` by moving to using `ts.GetTabletsByCell(...)` and the new `ts.GetTabletsByShard(...)` methods to fetch tablets. These methods respect the concurrency limit flag for the topo and seem to be more efficient overall
Support for filtering by keyspace/shard was added to `ts.GetTabletsByCell(...)` which is called by `ts.GetTabletsByShard(...)`
[Related to this discussion](https://github.com/vitessio/vitess/issues/16761), we're unfortunately forced to fetch "all" records from the cell just to filter them out by keyspace/shard using `x != y`. In our production when fetching topo records for a single shard, < 0.5% of the topo records fetched are actually used - but that's nothing new
Resolves …
> Improve efficiency of `vtorc` topo calls 

- go/vt/vtgate/planbuilder/operators/keys.go
- go/vt/vtgate/planbuilder/operators/keys_test.go
- go/vt/vtgate/testdata/executor_vexplain.json
This PR enhances `GetVExplainKeys` to also list the join predicates that were used in the given query. This enable us to achieve https://github.com/vitessio/vt/pull/43 in `vt keys` and `vt benchstat`. Example output and usage were detailed in https://github.com/vitessio/vt/pull/43.
> List join predicates used in `GetVExplainKeys`

- go/vt/vtctl/workflow/materializer.go
- go/vt/vtctl/workflow/materializer_env_test.go
- go/vt/vtctl/workflow/materializer_test.go
- go/vt/vtctl/workflow/utils.go
This is a follow-up to https://github.com/vitessio/vitess/pull/16860 that addresses a couple of potential edge cases when we automatically replace the auto increment handling:
1. The sequence table name in the VSchema AutoIncrement definition needs to be SQL escaped as it contains e.g. dashes
2. The sequence table name is not unique across the Vitess cluster
This PR addresses those respectively by 1) ensuring that the sequence table name is always properly SQL escaped 2) qualifying the sequence table with the keyspace and ensuring that the keyspace name is also properly SQL escaped.
I think that we should backport this to v21 as it heads off potential bugs related to keyspaces and table names that must be SQL escaped along with potential bugs related to the non-qualified generated …
> VReplication: Qualify and SQL escape tables in created AutoIncrement VSchema definitions

- go/vt/vttablet/endtoend/call_test.go
- go/vt/vttablet/endtoend/config_test.go
- go/vt/vttablet/endtoend/transaction_test.go
- go/vt/vttablet/tabletserver/tabletserver.go
This PR fixes a bug in debug/env to also update both normal and found rows pool of Transaction Pool when modified through /debug/env UI of vttablet.
- https://github.com/vitessio/vitess/issues/17046
> Fix: Update found rows pool transaction capacity dynamically via vttablet debug/env

- go/test/endtoend/vtgate/vitess_tester/cte/queries.test
- go/vt/vtgate/planbuilder/operators/SQL_builder.go
- go/vt/vtgate/planbuilder/testdata/cte_cases.json
This PR addresses an issue where the Vitess planner was incorrectly handling recursive Common Table Expressions (CTEs) when column names were defined in the CTE declaration but not in the SELECT clause. Specifically, vtgate was stripping out the column names before passing the query to MySQL, resulting in query failures.
The fix ensures that column names defined in the CTE declaration are preserved, allowing recursive CTE queries to execute correctly in both Vitess and MySQL.
Fixes #17177 …
> bugfix: Handle CTEs with columns named in the CTE def

- web/vtadmin/src/components/dataTable/DataTable.tsx
- web/vtadmin/src/components/routes/workflow/WorkflowDetails.tsx
- web/vtadmin/src/components/routes/workflow/WorkflowVDiff.tsx
- web/vtadmin/src/hooks/useURLPagination.ts
`DataTable`(s) on workflow details tab have broken pagination. Every `DataTable` accessed the same query parameter from URL i.e. `page` to set and retrieve the current page number of `DataTable`. It was implemented in such a way that only a single `DataTable` should access the URL parameters at a time. 
This PR fixes this issue by customising the URL parameter used by each `DataTable`. While using multiple `DataTable` in a component, pass on an optional unique prop `pageKey` if we expect multiple `DataTable` using the same URL. Each `DataTable` will use a query parameter for fetching/modifying the page number based on it's own unique passed prop `pageKey`.
- #11690
-   [ ] If this change …
> VTAdmin: Support for multiple DataTable accessing same URL

- go/vt/topo/zk2topo/zk_conn.go
- go/vt/topo/zk2topo/zk_conn_test.go
This PR fixes a bug in the zookeeper topo logic that causes it to leak connections/memory during network partitions from zookeeper. As mentioned in the issue, this is due to the zookeeper connection library automatically re-opening connections under the hood, even after a disconnect. To fix this, this PR calls `conn.Close()` whenever there is a disconnect.
This fix has been tested extensively in production in Shopify. A side effect of this fix is that it leads to a query latency regression when topo server is down as mentioned in https://github.com/vitessio/vitess/issues/9147 unless the `srv_topo_cache_ttl` flag is set to a high value. This isn't the case currently because the `SrvKeyspace` watch established [here](https://github.com/vitessio/vitess/blob/9ed8ee2c1bba4c8784296bfae70e3562389 …
> Close zookeeper topo connection on disconnect

- go/vt/topo/zk2topo/zk_conn_test.go
This is a quick folllow-up to https://github.com/vitessio/vitess/pull/17136 as the new unit test quickly proved to be flaky in the CI ([example](https://github.com/vitessio/vitess/actions/runs/11750299985/job/32745454444?pr=17192)).
It also failed virtually every time for me locally. It was a timing issue where we restarted ZooKeeper and immediately tried to connect, but it was not yet ready to accept new connections. We address that by waiting until we are able to connect.
We should backport this test fix to v19, as we did the original PR.
Note: I confirmed that the new test, as it is in this PR, still fails on a branch without the fixes in #17136:
```
--- FAIL: TestZkConnClosedOnDisconnect (6.20s)
zk_conn_test.go:59:
Error Trace: …
```
> Flakes: Address flakiness in TestZkConnClosedOnDisconnect

- go/vt/vttablet/onlineddl/executor.go
Quick fix to the location of `defer lockConn.Recycle()` in `cutOverVReplMigration()`: should be written immediately after the connection has been acquired. As it stands right now, it is possible for the function to return error because the `defer` has been declared, leading to connection not getting recycled.
**To be backported to supported versions**
Fixes https://github.com/vitessio/vitess/issues/17206
> Online DDL: fix defer function, potential connection pool exhaustion

- go/test/endtoend/vreplication/movetables_buffering_test.go
For some reason running vdiff using both vtctlclient and vtctldclient immediately one after the another seems to cause the following vdiff to fail randomly. Tried doing it in the CLI and we are able to do this. Not sure whether there is some timing related issue, but it is pretty consistent also locally. For now just run in vtctldclient to avoid flakiness.
> VReplication fix Flaky e2e test TestMoveTablesBuffering

- .github/workflows/upgrade_downgrade_test_backups_e2e.yml
- .github/workflows/upgrade_downgrade_test_backups_manual.yml
- .github/workflows/upgrade_downgrade_test_onlineddl_flow.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema.yml
- .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml
- .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml
- .github/workflows/upgrade_downgrade_test_semi_sync.yml
- Makefile
- build.env
- docker/bootstrap/CHANGELOG.md
- docker/bootstrap/Dockerfile.common
- docker/lite/Dockerfile
- docker/lite/Dockerfile.percona80
- docker/vttestserver/Dockerfile.mysql80
- go.mod
- test.go
- test/templates/dockerfile.tpl
This PR bumps the Golang version to `go1.23.3`.
> [release-21.0] Upgrade the Golang version to `go1.23.3`

- go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
- go/vt/schema/ddl_strategy.go
- go/vt/schema/ddl_strategy_test.go
- go/vt/vttablet/onlineddl/executor.go
Per https://github.com/vitessio/vitess/issues/17162, we add a `--singleton-table` DDL strategy flag, which prevents an Online DDL submission for a table (or view) that is already pending an Online DDL operation.
Fixes https://github.com/vitessio/vitess/issues/17162
Documentation: https://github.com/vitessio/website/pull/1881
> Online DDL: `--singleton-table` DDL strategy flag

- go/vt/vttablet/tabletserver/health_streamer.go
- go/vt/vttablet/tabletserver/health_streamer_test.go
- go/vt/vttablet/tabletserver/messager/engine.go
- go/vt/vttablet/tabletserver/messager/engine_test.go
- go/vt/vttablet/tabletserver/schema/engine.go
This PR fixes the deadlocks in messager and health streamer as pointed out in #17229.
The fix to the deadlock for both the cases was to use two different mutexes. One that only protects against calling setup functions like `Open` and `Close` concurrently, and the other one that actually protects the fields. This helps in removing the deadlock since the function that runs on a broadcast from the schema engine would acquire a different mutex than the call to Close.
- Fixes #17229  …
> Fix deadlock in messager and health streamer

- go/flags/endtoend/vtcombo.txt
- go/flags/endtoend/vttablet.txt
- go/mysql/binlog_event_compression.go
- go/mysql/binlog_event_mysql56_test.go
- go/vt/vttablet/common/flags.go
Vitess supports [MySQL's binlog transaction compression](https://dev.mysql.com/doc/refman/en/binary-log-transaction-compression.html). That support lives primarily in a single file: https://github.com/vitessio/vitess/blob/main/go/mysql/binlog_event_compression.go
There's an important variable which controls HOW that work is done. That variable is currently a `const`: https://github.com/vitessio/vitess/blob/f6067e04dee063f4b6b254ca2b6caf7b2ba51df6/go/mysql/binlog_event_compression.go#L62-L65
That is currently hardcoded at 128MiB, which was somewhat arbitrary. The thinking was that all transactions will be compressed and you want to process them as fast as possible, while still being able to support payloads of virtually any size — the compressed transaction payload is limited by MySQL's …
> Binlog: Improve ZstdInMemoryDecompressorMaxSize management

- go/mysql/sqlerror/constants.go
- go/mysql/sqlerror/sql_error.go
- go/mysql/sqlerror/sql_error_test.go
- go/vt/vttablet/tabletmanager/vreplication/utils.go
- go/vt/vttablet/tabletmanager/vreplication/utils_test.go
Some of MySQL errors include more fine grained handler error codes, as seen in 
```cpp
bld/include/mysqld_ername.h:205:{ "ER_ERROR_DURING_COMMIT", 1180, "Got error %d - \'%-.192s\' during COMMIT","HY000", "", 162 },
```
For example: `ERROR HY000: Got error 149 - 'Lock deadlock; Retry transaction' during COMMIT`
Another example: `ER_ERROR_DURING_COMMIT` as described in https://github.com/vitessio/vitess/issues/17248.
With this PR we formally introduce `HandlerErrorCode`. We add `SQLError.HaErrorCode()` which uses regexp parsing on the error message to extract the handler error code, if any.
Furthermore, some of these handler error codes indicate an unrecoverable error for vreplication. ~~We meanwhile add a sample of those.~~ We list the full range of existing HA errors, and mark a select …
> Handle MySQL handler error codes

- go/test/endtoend/vtgate/queries/reference/reference_test.go
- go/vt/vtgate/planbuilder/operators/delete.go
- go/vt/vtgate/planbuilder/plan_test.go
- go/vt/vtgate/planbuilder/testdata/dml_cases_with_user_as_default.json
This PR fixes a regression introduced by https://github.com/vitessio/vitess/pull/15107, when a user is using (`use ks`) a sharded keyspace that has a reference table with its source in an unsharded keyspace, the query planner would not set the target keyspace correctly when rewriting the query graph, leading to the following plan:
```json
{
"QueryType": "UPDATE",
"Original": "update ambiguous_ref_with_source set done = true where id = 1;",
"OperatorType": "Update",
"Variant": "Reference",
"Keyspace": {
},
"TargetTabletType": "PRIMARY",
"Query": "update ambiguous_ref_with_source set done = true where id = 1",
"Table": "ambiguous_ref_with_source"
},
"TablesUsed": [
"main.ambiguous_ref_with_source",
"user.ambiguous_ref_with_source"
]
}
``` …
> Use proper keyspace when updating the query graph of a reference DML

- go/vt/servenv/grpc_server.go
- go/vt/vttest/local_cluster.go
- go/vt/vttest/vtprocess.go
When  `--grpc_bind_address` is supplied to `vttestserver`, it is now forwarded up to `vtcombo`.
Part of https://github.com/vitessio/vitess/issues/16798
> Add support for receiving `grpc_bind_adress` on `vttestserver`

- go/vt/binlog/binlogplayer/dbclient.go
- go/vt/binlog/binlogplayer/fake_dbclient.go
- go/vt/binlog/binlogplayer/mock_dbclient.go
- go/vt/vttablet/tabletmanager/vdiff/framework_test.go
- go/vt/vttablet/tabletmanager/vreplication/framework_test.go
- go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
- go/vt/wrangler/fake_dbclient_test.go
When `vreplicator` fails, check if its connection is closed, and if so, reopen it. This addresses https://github.com/vitessio/vitess/issues/17248 where the binlog connection auto closes itself in response to a bad commit (MySQL error `1180`), but will just as well apply to any situation where the connection closes. It's imperative to open the connection so as to be able to set state/message.
Fixes https://github.com/vitessio/vitess/issues/17248
-   [ ] …
> VReplication: recover from closed connection

- go/vt/vttablet/tabletserver/tx_pool.go
- go/vt/vttablet/tabletserver/tx_pool_test.go
- go/vt/vttablet/tabletserver/vstreamer/snapshot_conn.go
This was disabled in #16424, but we can clean up this additional code since it's unused.
Follow up to #16424
> Remove unused code for old START_GTID logic

- go/vt/vttablet/tabletserver/health_streamer.go
- go/vt/vttablet/tabletserver/health_streamer_test.go
While we fixed a couple of deadlocks in https://github.com/vitessio/vitess/pull/17230, one was left pending. It was found while testing for deadlocks in https://github.com/vitessio/vitess/pull/17238. 
The deadlock is similar to the ones fixed in https://github.com/vitessio/vitess/pull/17230, it was occurring between MakePrimary and the reload. The fix employed is to let go of the lock once it is not required instead of defering its unlocking.
- #17229 
- …
> Fix potential deadlock in health streamer

- go/test/endtoend/vtorc/general/vtorc_test.go
- go/vt/vtorc/inst/instance_dao.go
- go/vt/vtorc/inst/instance_dao_test.go
As pointed out in https://github.com/vitessio/vitess/issues/17254, there is a case where VTOrc is unable to detect errant GTIDs on a tablet that got demoted.
The underlying cause of the problem was that VTOrc was not running errant GTID detection for tablets that weren't connected to any primary. Previously it would fix the replication on the tablet first and then run errant GTID detection eventually to figure out if it had errant GTIDs. However, ever since we made the vttablets also run errant GTID detection on reparent (https://github.com/vitessio/vitess/pull/16833), VTOrc is unsuccessful in reparenting the tablet with errant GTIDs since the vttablets fail with an error.
The fix is to augment VTOrc to run errant GTID detection with the primary tablet that it would reparent the replica …
> Fix errant GTID detection in VTOrc to also work with a replica not connected to any primary

- go/vt/schemamanager/local_controller.go
- go/vt/schemamanager/local_controller_test.go
- go/vt/schemamanager/schemamanager.go
- go/vt/schemamanager/schemamanager_test.go
- go/vt/schemamanager/tablet_executor.go
- go/vt/vtctl/grpcvtctldserver/server.go
See context in https://github.com/vitessio/vitess/issues/15505
In this PR `ApplySchema` uses `ExecuteMultiFetchAsDba()` instead of `ExecuteFetchAsDba()`. This is scheduled for `v22`. In `v23` we will be able to clean up `ExecuteFetchAsDba()` as `ApplySchema` is the last use of `ExecuteFetchAsDba()` that is still allowed to pass multiple statements.
**Note:** hardly any tests changed, because the point is that the behavior is unchanged and that all the tests continue as expected when we switch from `ExecuteFetchAsDba()` to `ExecuteMultiFetchAsDba()`.
https://github.com/vitessio/vitess/issues/15505
-   [ ] If this change is to be back-ported to previous releases, a justification is …
> `Applyschema` uses `ExecuteMultiFetchAsDba`

- go/vt/sidecardb/schema/onlineddl/schema_migrations.sql
- go/vt/vttablet/onlineddl/executor.go
- go/vt/vttablet/onlineddl/schema.go
- go/vt/vttablet/onlineddl/vrepl.go
A new column in `schema_migrations`: `vreplication_lag_seconds` publishes the `vreplication` (rather, `vplayer`) lag on a vreplication migration. This is computed by the higher difference of vreplication's time updted and transaction timestamp compared with time now.
This just adds more visibility into the underlying workflow.
https://github.com/vitessio/vitess/issues/17264
> Online DDL: publish `vreplication_lag_seconds` from vreplication progress

- go/test/endtoend/cluster/vtctldclient_process.go
- go/test/endtoend/cluster/vttablet_process.go
This PR adds two enhancements in `go/test/endtoend/cluster`:
- `VtctldClientProcess` supports `Quiet` mode, where it does not log the command line invocation to standard output. The `Quiet` field is not thread safe.
This will be useful to reduce log clutter. I especially intend to use it to reduce `CheckThrottler` logs.
- `VttabletProcess` supports `MultiQueryTablet()`, complementing `MultiQueryTabletWithDB()`. This can be used to issue non-DB specific multi-query SQL from external source.
No issue for this PR.
-   [ ] Did the …
> A couple `endtoend` cluster tests enhancement

- go/vt/vtorc/inst/instance_dao.go
- go/vt/vtorc/inst/instance_dao_test.go
This PR fixes the issue described in https://github.com/vitessio/vitess/issues/17286. The problem was fixed by adding a conditional check to see if the tablet we're detecting errant GTIDs on is the primary tablet itself.
- Fixes https://github.com/vitessio/vitess/issues/17286
> Errant GTID detection fix for VTOrc

- go/vt/mysqlctl/builtinbackupengine.go
This PR makes sure we cancel the context only at the correct time. It was getting canceled too early which could lead to incomplete/failing backups with storage implementations that write concurrently (Ceph and S3).
This regression was introduced by: https://github.com/vitessio/vitess/pull/16856, backporting this to release-21.0 as the issue was introduced there. It would lead to the following error:
```
commerce/0 (zone1-0000000102): time:{seconds:1732657021 nanoseconds:695573000} file:"builtinbackupengine.go" line:509 value:"resetting mysqld super_read_only to true"
commerce/0 (zone1-0000000102): time:{seconds:1732657021 nanoseconds:696651000} file:"builtinbackupengine.go" line:526 value:"restarting mysql replication"
E1126 15:37:02.757871   98619 main.go:56] rpc error: code = Unknown …
```
> Fix how we cancel the context in the builtin backup engine

- .github/CODEOWNERS
- go/test/endtoend/transaction/twopc/twopc_test.go
This PR fixes flakiness in `TestReadTransactionStatus`. When we start a commit in a separate go routine, and then wait for 1 second for it to show up in the unresolved list, there is a race condition. If the commit starts a little bit later because the goroutine is not immediately scheduled, when we try to read the list of unresolved transactions with an abandoed age of 1 second, we might not read it, because its only like 0.9 seconds old.
This PR fixes this issue.
-   [x] Did the new or modified tests pass consistently locally …
> Fix flakiness in `TestReadTransactionStatus`

- changelog/21.0/21.0.0/summary.md
We think it's a good idea to also include a segment that just talks about the changes made to RPC calls in the release. This will help users see at a glance what RPCs have changed across different versions.
Diff of all services/proto changes b/w v20 and v21: https://gist.github.com/rohit-nayak-ps/ff70493906f84094e66f92262f9be842
> [Direct PR][release-21.0] Add RPC changes segment in the summary doc

- go/test/endtoend/transaction/twopc/fuzz/fuzzer_test.go
- go/test/endtoend/transaction/twopc/fuzz/main_test.go
- go/test/endtoend/transaction/twopc/fuzz/schema.sql
- go/test/endtoend/transaction/twopc/fuzz/vschema.json
This PR adds multi-table updates to the two pc fuzzer testing we have. This ensures we process multi-table DMLs correctly in our atomic transactions implementation. We didn't expect that there would be anything special about them to begin with, but it is always nice to have the assertions backed by actual tests.
- https://github.com/vitessio/vitess/issues/16245
> Add multi table updates in the 2pc fuzzer testing 

- go/test/endtoend/transaction/twopc/main_test.go
- go/test/endtoend/transaction/twopc/schema.sql
- go/test/endtoend/transaction/twopc/twopc_test.go
- go/test/endtoend/transaction/twopc/vschema.json
Like the last PR, this one too add tests for atomic distributed transactions. This time we're adding tests for vindexes. Like last time, we didn't expect anything to fail, but its always nice to have tests to verify the assumptions.
- Fixes #16245 
> Add test for vindexes in atomic transactions package

- go/test/vschemawrapper/vschema_wrapper.go
- go/vt/vtgate/planbuilder/builder.go
- go/vt/vtgate/planbuilder/bypass.go
- go/vt/vtgate/planbuilder/ddl.go
- go/vt/vtgate/planbuilder/operator_transformers.go
- go/vt/vtgate/planbuilder/plancontext/planning_context.go
- go/vt/vtgate/planbuilder/plancontext/planning_context_test.go
- go/vt/vtgate/planbuilder/plancontext/vschema.go
- go/vt/vtgate/planbuilder/select.go
- go/vt/vtgate/planbuilder/show.go
- go/vt/vtgate/vcursor_impl.go
`DefaultKeyspace` is poorly named - it tells us which database the user has selected with `use` or using the connection string.
> refactor: rename DefaultKeyspace() to CurrentKeyspace()

- go/vt/vtgate/dynamicconfig/config.go
- go/vt/vtgate/engine/cached_size.go
- go/vt/vtgate/engine/ddl.go
- go/vt/vtgate/engine/ddl_test.go
- go/vt/vtgate/executor.go
- go/vt/vtgate/executor_ddl_test.go
- go/vt/vtgate/planbuilder/builder.go
- go/vt/vtgate/planbuilder/ddl.go
- go/vt/vtgate/planbuilder/migration.go
- go/vt/vtgate/planbuilder/simplifier_test.go
- go/vt/vtgate/planbuilder/vexplain.go
- go/vt/vtgate/viperconfig.go
- go/vt/vtgate/vtgate.go
This allows configuring the vtgate DDL flags dynamically. With this, both online DDL and direct DDL can be disabled and enabled in vtgate without having to restart.
Fixes #17327 
> Allow for dynamic configuration of DDL settings

- .github/workflows/update_golang_version.yml
- Makefile
- build.env
- docker/bootstrap/CHANGELOG.md
- docker/bootstrap/Dockerfile.common
- docker/lite/Dockerfile
- docker/lite/Dockerfile.percona80
- docker/vttestserver/Dockerfile.mysql80
- go.mod
- test.go
- test/templates/dockerfile.tpl
This PR bumps the go version to `go1.23.4`.
> [main] Bump go version to 1.23.4

- Makefile
- build.env
- docker/bootstrap/CHANGELOG.md
- docker/bootstrap/Dockerfile.common
- docker/lite/Dockerfile
- docker/lite/Dockerfile.percona80
- docker/vttestserver/Dockerfile.mysql80
- go.mod
- test.go
- test/templates/dockerfile.tpl
This PR bumps the go version to `go1.23.4`.
> [release-21.0] Bump go version to 1.23.4

- go/vt/vtctl/workflow/framework_test.go
- go/vt/vtctl/workflow/resharder_test.go
This PR adds missing unit tests for `resharder.go`
The code coverage in main:
```
coverage: 59.8% of statements in vitess.io/vitess/go/vt/vtctl/workflow...
ok  	vitess.io/vitess/go/vt/vtctl/workflow	2.869s	coverage: 59.8% of statements in vitess.io/vitess/go/vt/vtctl/workflow...
```
The code coverage in this branch:
```
coverage: 60.6% of statements in vitess.io/vitess/go/vt/vtctl/workflow...
ok  	vitess.io/vitess/go/vt/vtctl/workflow	2.805s	coverage: 60.6% of statements in vitess.io/vitess/go/vt/vtctl/workflow...
```
Cmd used:
```sh
go test ./go/vt/vttablet/tabletmanager ./go/vt/vtctl/workflow -v -coverpkg=vitess.io/vitess/go/vt/vtctl/workflow... -coverprofile=c.out
```
- #16499
-   [ ] …
> test: Add missing unit tests in `vtctl/workflow`

- go/vt/vttablet/tabletmanager/vreplication/external_connector_test.go
- go/vt/vttablet/tabletmanager/vreplication/framework_test.go
- go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go
- go/vt/vttablet/tabletmanager/vreplication/vdbclient.go
- go/vt/vttablet/tabletmanager/vreplication/vplayer.go
- go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go
- go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
This is a quick follow-up to https://github.com/vitessio/vitess/pull/17166. When working on that, I did not realize that the unit test framework was explicitly disabling all experimental flags and thus we were not testing the new flag/default behavior. This PR removes that `vttablet.DefaultVReplicationConfig.ExperimentalFlags = 0` line in `framework_test.go` and adjusts the unit test expectations accordingly.
In working on this, it surfaced an issue with an extraneous BEGIN being used when in batching mode that was also corrected in `vdbclient.go`. Similarly, the unit tests surfaced an extraneous state update that was corrected here in `vreplicator.go`. Lastly, it also updates the vplayer so that batching is only done when in the running/replicating phase as intended.
- Follow-up to: …
> VReplication: Enable VPlayerBatching in unit tests

- go/test/endtoend/transaction/twopc/twopc_test.go
This PR fixes flakiness in `TestSemiSyncRequiredWithTwoPC`.
Previously, after the test was finished, we would run PRS in a defer function. But since we were PRSsing to the same tablet, we didn't actually end up changing the semi-sync settings. VTOrc would fix this, but it would race with the next test running.
This PR fixes this problem, by changing the primary first in the test itself that ensures semi-sync changes have taken effect.
- #16245 
-   [x] …
> Fix flakiness in `TestSemiSyncRequiredWithTwoPC`

- go/test/endtoend/vreplication/lookupindex_helper_test.go
- go/test/endtoend/vreplication/lookupindex_test.go
- go/vt/vtctl/workflow/materializer_test.go
- go/vt/vtctl/workflow/server.go
- go/vt/wrangler/materializer.go
- go/vt/wrangler/materializer_test.go
- test/config.json
There was an incorrect validation in `LookupIndex` that a non-unique vindex should have more than one columns. This PR removes that check.
We also add a new e2e test specifically around lookup vindexes to validate this change and add a framework to test lookup vindexes more extensively in the future.
This bug has been around since the beginning, so we should backport this to supported versions.
https://github.com/vitessio/vitess/issues/17302
-   [ ] …
> LookupVindex: fix CLI to allow creating non-unique lookups with single column

- go/test/endtoend/cluster/vtgate_process.go
- go/test/endtoend/vtgate/vschema/vschema_test.go
- go/viperutil/internal/sync/sync.go
- go/vt/vtgate/executor.go
- go/vt/vtgate/executor_set_test.go
- go/vt/vtgate/executor_test.go
- go/vt/vtgate/executor_vschema_ddl_test.go
- go/vt/vtgate/vschemaacl/vschemaacl.go
- go/vt/vtgate/vschemaacl/vschemaacl_test.go
This allows configuring the users for the vschema dynamically at runtime so you don't need to restart vtgate if this changes.
Fixes #17350
> Allow dynamic configuration of vschema acl

- go/vt/vtgate/planbuilder/plan_test.go
- go/vt/vtgate/planbuilder/testdata/select_cases.json
In a recent PR, we added a new field to the plan tests. We forgot to keep them around when tests fail. This PR makes sure to keep the field around even if tests fail.
Issue introduced in #17117
> test fix: make sure to keep the skipE2E field around

- go/vt/vttablet/tabletmanager/rpc_vreplication_test.go
There was an extra query that was being run when these tests failed. The query is called when the vreplication state is being updated. Looks like there is a race where a stream terminates in the test early some times before the state is updated.
This flakiness surfaced during v21, so backporting this to `release-21.0`
> Flaky test fix: TestMoveTablesSharded and TestMoveTablesUnsharded

- .github/workflows/scorecards.yml
We've received an email from GitHub about some versions of actions being shut down soon. Changing to newer versions instead.
The versions used here were sourced from:
- latest version of actions/upload-artifact
- recommended version of codeql-action/upload-sarif from https://github.com/ossf/scorecard/commits/main/.github/workflows/scorecard-analysis.yml
A backport to v21 is needed because this workflow is also active on that branch. …
> use newer versions of actions in scorecard workflow

- go/test/endtoend/transaction/twopc/twopc_test.go
Flaky fix done in https://github.com/vitessio/vitess/pull/17332, was somewhat incomplete. Post the changes, we still had a single shard left that didn't have its primary changed when we ran PRS after changing the keyspace durability policy. This causes the test to be flaky because VTOrc fixing the semi-sync races with the next transaction running.
- #16245 
> Ensure PRS runs for all the shards in `TestSemiSyncRequiredWithTwoPC`

- go/vt/logutil/logger.go
- go/vt/mysqlctl/blackbox/utils.go
This can trigger the race detector:
```
Read at 0x00c00031f900 by goroutine 64:
vitess.io/vitess/go/vt/mysqlctl/blackbox.AssertLogs()
/Users/dirkjan/code/vitessio/vitess/go/vt/mysqlctl/blackbox/utils.go:81 +0xb8
vitess.io/vitess/go/vt/mysqlctl/blackbox.TestExecuteBackupFailToWriteFileTwice()
/Users/dirkjan/code/vitessio/vitess/go/vt/mysqlctl/blackbox/backup_test.go:713 +0x7e8
testing.tRunner()
/opt/homebrew/Cellar/go/1.23.4/libexec/src/testing/testing.go:1690 +0x184
testing.(*T).Run.gowrap1()
/opt/homebrew/Cellar/go/1.23.4/libexec/src/testing/testing.go:1743 +0x40
Previous write at 0x00c00031f900 by goroutine 75:
vitess.io/vitess/go/vt/mysqlctl/blackbox.TestExecuteBackupFailToWriteFileTwice.NewMemoryLogger.func2() …
```
> Fix flaky mysqlctl blackbox test

- changelog/22.0/22.0.0/summary.md
- go/flags/endtoend/vtbackup.txt
- go/flags/endtoend/vtcombo.txt
- go/flags/endtoend/vtctld.txt
- go/flags/endtoend/vtgate.txt
- go/flags/endtoend/vtorc.txt
- go/flags/endtoend/vttablet.txt
- go/vt/discovery/healthcheck.go
- go/vt/discovery/topology_watcher.go
- go/vt/discovery/topology_watcher_test.go
- go/vt/topo/keyspace.go
- go/vt/topo/server.go
- go/vt/topo/shard.go
- go/vt/topo/stats_conn.go
- go/vt/topo/stats_conn_test.go
- go/vt/topo/tablet.go
- go/vt/topo/tablet_test.go
- go/vt/vtorc/logic/tablet_discovery.go
This PR implements the feature request https://github.com/vitessio/vitess/issues/17275 by ensuring that all topo read calls respect the `--topo_read_concurrency` flag, specifically `Get`, `GetVersion`, `List`, `ListDir` operations
As discussed in https://github.com/vitessio/vitess/issues/17275, there is a separate semaphore/limit for "global" and "cell" reads, ie: by default there can be up to 32 concurrent "global" topo reads and 32 concurrent reads per "local" cell
- Fixes: https://github.com/vitessio/vitess/issues/17275
- Sub-task of Tracking Issue: https://github.com/vitessio/vitess/issues/17330
-   [x] If this change is to be back-ported to previous releases, a justification is …
> Ensure all topo read calls consider `--topo_read_concurrency`

- config/mycnf/default.cnf
- config/mycnf/mariadb10.cnf
- config/mycnf/mysql57.cnf
- config/mycnf/mysql80.cnf
- config/mycnf/mysql8026.cnf
- config/mycnf/mysql84.cnf
- config/mycnf/sbr.cnf
This currently triggers a warning on more recent MySQL versions. Instead we can move it to the version specific files so we can use the correct non-deprecated name.
Part of improving things for #16466
> Use non-deprecated flags to skip replication

- go/vt/vtctl/workflow/switcher_dry_run_test.go
This PR adds unit tests for `switcher_dry_run.go`.
Coverage diff:
- Coverage on main
```
ok  	vitess.io/vitess/go/vt/vtctl/workflow	2.733s	coverage: 64.6% of statements
```
- Coverage on tests-switcher-dr
```
ok  	vitess.io/vitess/go/vt/vtctl/workflow	2.862s	coverage: 67.2% of statements
```
- #16499
> test: Include unit tests for `switcher-dry-run`

- go/test/endtoend/transaction/benchmark/bench_test.go
- go/test/endtoend/transaction/benchmark/schema.sql
- go/test/endtoend/transaction/benchmark/vschema.json
- go/test/endtoend/transaction/twopc/utils/utils.go
This PR benchmarks two Commit Modes:
1. Best Effort Commit (multi) – commits sequentially across shards.
2. Atomic Commit (TwoPC) – ensures atomicity through a multi-step process with parallel phases.
The benchmarks measure performance across transactions involving varying numbers of shards. 
Results are provided for 4, 8, and 16 shard configurations. 
4 shards
```
│ multi_v4.txt │             twopc_v4.txt             │
│    sec/op    │    sec/op     vs base                │
TwoPCCommit/SingleShard-8    756.5µ ± 1%   764.6µ ±  2%         ~ (p=0.180 n=6)
TwoPCCommit/TwoShards-8      1.545m ± 4%   3.386m ±  4%  +119.08% (p=0.002 n=6)
TwoPCCommit/ThreeShards-8    2.393m ± 2%   4.877m ± 14%  +103.82% (p=0.002 n=6)
TwoPCCommit/FourShards-8     3.309m ± 4%   6.098m ±  6%   +84.29% (p=0.002 n=6) …
```
> benchmark: TwoPC commit mode

- go/cmd/vttestserver/cli/main.go
- go/flags/endtoend/vttestserver.txt
- go/vt/vttest/local_cluster.go
- go/vt/vttest/vtprocess.go
This is a manual backport of #16338
> [release-19.0] parse transaction timeout as duration (#16338)

- go.mod
- go.sum
Addresses: https://github.com/vitessio/vitess/security/dependabot/400
I'm not sure why Dependabot failed to open a PR (N times)... perhaps we have a permission issue or something. Nothing obvious from the logs.
The bug is in the `x/net/html` package that we don't actually use in Vitess. The only place we use `x/net` at all is in some unit tests:
```
❯ git grep "x/net"
... (non code files)
go/vt/vtadmin/grpcserver/server_test.go:        "golang.org/x/net/nettest"
go/vt/vtctl/grpcvtctldserver/testutil/util.go:  "golang.org/x/net/nettest"
go/vt/vttablet/grpctmclient/cached_client_flaky_test.go:        "golang.org/x/net/nettest"
```
- Fixes: https://github.com/vitessio/vitess/security/dependabot/400
-   [x] "Backport to:" labels have been added if this change should be back-ported to release …
> Bump golang.org/x/net from 0.31.0 to 0.33.0

- go/vt/vttablet/tabletmanager/vreplication/table_plan_partial.go
- go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go
- go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
This is a quick follow-up to https://github.com/vitessio/vitess/pull/17345 
In backporting this in a fork, where the `--vreplication_experimental_flags` were being handled differently — 1) the noblob support was disabled in all unit tests *except* the noblob ones 2) vplayer batching was not enabled — I noticed some incorrect behavior.
Those fixes and adjustments are made here.
- Follow-up to: https://github.com/vitessio/vitess/pull/17345
-   [x] …
> VReplication: Handle --vreplication_experimental_flags options properly for partial images

- go/vt/vterrors/code.go
- go/vt/vttablet/tabletmanager/rpc_replication.go
- go/vt/vttablet/tabletmanager/rpc_replication_test.go
- go/vt/vttablet/tabletserver/controller.go
- go/vt/vttablet/tabletserver/state_manager.go
- go/vt/vttablet/tabletserver/state_manager_test.go
- go/vt/vttablet/tabletserver/tabletserver.go
- go/vt/vttablet/tabletservermock/controller.go
This PR adds the feature requested in https://github.com/vitessio/vitess/issues/17288.
We spawn a new goroutine when we start `DemotePrimary` and when enough time has passed such that DemotePrimary hasn't finished despite context cancellation, we deem it to be blocked. In this case we send an error in the health stream that the users can track and use to restart MySQL and vttablet.
- Fixes https://github.com/vitessio/vitess/issues/17288
-   [x] …
> Add a way to know if DemotePrimary is blocked and send it in the health stream

- go/test/endtoend/vreplication/lookup_vindex_helper_test.go
- go/test/endtoend/vreplication/lookup_vindex_test.go
Changing references from "lookup index" to "lookup vindex", which were typos from #17301.
We backport these to the same version the original PR was backported to.
https://github.com/vitessio/vitess/pull/17301
> LookupVindex bug fix: Fix typos from PR 17301

- go/cmd/internal/docgen/docgen.go
- go/cmd/internal/docgen/docgen_test.go
* We remove the commit hash from the generated docs which resulted in unnecessary commits
* There was a failure in the `sed` command to replace `<WORKDIR>` due to incorrect sed invocation. Fixed here.
* There were files where the `WORKDIR` sed was not happening: fixed
There is a related website PR https://github.com/vitessio/website/pull/1904 which will enhance the current `make` target to generate the docs to add modified content files to git with an appropriate git message including the current vitess hash.
We need to first merge this PR into main and then run `make generated-docs` in the website PR before it is ready.
-   [ ] If this change is to be back-ported to previous releases, a …
> CobraDocs: Remove commit hash from docs. Fix issue with workdir replacement

- examples/operator/operator.yaml
- go.mod
- go/flags/endtoend/vtbackup.txt
- go/flags/endtoend/vtctld.txt
- go/flags/endtoend/vttablet.txt
- go/vt/mysqlctl/s3backupstorage/s3.go
- go/vt/mysqlctl/s3backupstorage/s3_mock.go
- go/vt/mysqlctl/s3backupstorage/s3_test.go
This adds a new parameter to allow the operator to specify a minimum part size for the S3 uploads.
- Fixes: #17175
- Operator: https://github.com/planetscale/vitess-operator/pull/645
> add S3 minimum part size defined by the user

- go/cmd/internal/docgen/docgen.go
- go/cmd/internal/docgen/docgen_test.go
Manual backport of #17392 
We need to backport the original PR because we checkout previous releases while generating docs for previous versions and hence the older versions also need the fixes from #17392.
Hoping to piggyback backport these to v19/v20 as well using labels and not have to create manual backports.
#17392 
> [Direct PR] [V21 backport] CobraDocs: Remove commit hash from docs. Fix issue with workdir replacement (#17392)

- go/vt/vtgate/evalengine/testcases/cases.go
- go/vt/vttablet/tabletconntest/fakequeryservice.go
- go/vt/vttablet/tabletmanager/rpc_vreplication_test.go
- go/vt/vttablet/tabletmanager/vreplication/vplayer.go
- go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
There is a `goroutine` that runs which starts the `vplayer` thread for each workflow which is triggered by updating the `_vt.vreplication` table using `VExe`c . Now most of the time the test ends before it starts doing anything significant. The failure happens when it runs for a bit.
https://github.com/vitessio/vitess/pull/17166 has added a new query to that path and this was not expected by the db mock layer, which was the reported failure. But the solution is a bit more involved than just adding that query as an expected query. When the vplayer runs it requires some more mocking support. Needed to add an additional query and update the mock object for the `VStream()` API to return rather than panic. It doesn't matter what this mock returns since the test doesn't make use of the response …
> Flaky TestMoveTables(Un)sharded: Handle race condition 

- examples/backups/create_commerce_schema.sql
- examples/backups/create_customer_schema.sql
- examples/compose/default_vschema.json
- examples/compose/lookup_keyspace_vschema.json
- examples/compose/test_keyspace_vschema.json
- examples/compose/vtcompose/base_vschema.json
- examples/demo/schema/customer/vschema.json
- examples/local/create_commerce_schema.sql
- examples/local/vschema.json
- examples/local/vschema_customer_sharded.json
- examples/operator/create_commerce_schema.sql
- examples/operator/vschema_customer_sharded.json
- examples/region_sharding/create_main_schema.sql
This changes usage of `varbinary` to `varchar` in schemas used in the `/examples` folder. Schema fields like `keyspace_id` that use `varbinary` are excluded from the change.
This PR fixes #15997 
-   [x] Documentation: https://github.com/vitessio/website/pull/1901
> Feature Request: Change varbinary to varchar in schemas used in examples folder

- go/vt/vtgate/executorcontext/vcursor_impl.go
The new added planner e2e tests were flaky on `vexplain` as the fields used to log the shard and rows information were not protected from the concurrent writes.
This PR fixes it.
Backport to v21: Fixes a real issue that panic on concurrent write.
- Fixes https://github.com/vitessio/vitess/issues/17461
> vexplain to protect the log fields from concurrent writes

- changelog/22.0/22.0.0/summary.md
- go/test/endtoend/cluster/vtgate_process.go
- go/test/endtoend/vtgate/misc_test.go
- go/vt/discovery/replicationlag.go
Now that we have started making more and more flags as dynamic configurations in viper, we have settled on the default convention for this. We are using the same flag name as the key name in viper. The discovery flags that were added previously didn't follow this convention and have been changed to do so.
This PR is built on top of #17419 because it required some testing changes setup that that PR adds.
> Change keys of the discovery flags such that they conform to the convention

- go/vt/schemadiff/key.go
- go/vt/schemadiff/onlineddl.go
- go/vt/schemadiff/onlineddl_test.go
- go/vt/schemadiff/table.go
- go/vt/schemadiff/table_test.go
Keys may cover expressions, such as in `KEY idx1 ((id + 1))`. Such keys are not eligible for Online DDL (vreplication) iteration, because even if defined as `UNIQUE`, they cannot be trusted; the expression might un-unique the value (consider `((id * 0))` as a trivial example).
With this PR `schemadiff`s Online DDL analysis ignores keys that have expressions. The function `IndexDefinitionEntities()` likewise does not attempt to read column information from an index that has an expression.
Added various tests that would otherwise either return incorrect answer or panic with `panic: runtime error: invalid memory address or nil pointer dereference`.
As this can cause a crash scenario, marking for backport.
- fixes https://github.com/vitessio/vitess/issues/17477
- #10203 
-   [ ] "Backport …
> schemadiff: skip keys with expressions in Online DDL analysis

- changelog/22.0/22.0.0/summary.md
- go/test/endtoend/utils/cmp.go
- go/test/endtoend/vtgate/plan_tests/plan_e2e_test.go
- go/test/endtoend/vtgate/queries/misc/main_test.go
- go/test/endtoend/vtgate/queries/misc/misc_test.go
- go/vt/sqlparser/ast_test.go
- go/vt/vtgate/engine/cached_size.go
- go/vt/vtgate/engine/fake_vcursor_test.go
- go/vt/vtgate/engine/insert.go
- go/vt/vtgate/engine/insert_common.go
- go/vt/vtgate/engine/insert_select.go
- go/vt/vtgate/engine/primitive.go
- go/vt/vtgate/engine/set.go
- go/vt/vtgate/evalengine/cached_size.go
- go/vt/vtgate/evalengine/compiler_asm.go
- go/vt/vtgate/evalengine/compiler_test.go
- go/vt/vtgate/evalengine/expr_env.go
- go/vt/vtgate/evalengine/fn_misc.go
- go/vt/vtgate/evalengine/integration/comparison_test.go
- go/vt/vtgate/evalengine/translate_builtin.go
- go/vt/vtgate/executorcontext/vcursor_impl.go
- go/vt/vtgate/planbuilder/insert.go
- go/vt/vtgate/planbuilder/operator_transformers.go
- go/vt/vtgate/planbuilder/testdata/aggr_cases.json
- go/vt/vtgate/planbuilder/testdata/dml_cases.json
- go/vt/vtgate/planbuilder/testdata/set_cases.json
This PR improves `LAST_INSERT_ID(x)` behavior to align more closely with MySQL in various scenarios.
- **EvalEngine Enhancement**: We now handle `LAST_INSERT_ID(x)` queries directly in vtgate, allowing “dual-only” queries without sending them downstream to MySQL. 
```sql
select last_insert_id(123);
```
- VTGate-Calculated Values: Queries like:
```sql
SELECT last_insert_id(count(*)) FROM user WHERE foo = 'bar';
```
can be processed at vtgate level (aggregation across shards), rather than relying on MySQL for the final result.
- MySQL sets the session’s LAST_INSERT_ID value to the last row returned in ordered queries such as:
```sql
SELECT last_insert_id(col) FROM table ORDER BY foo;
```
In Vitess, we do **not** guarantee that the _last row_ dictates the session value. The session’s …
> Improved Compatibility Around LAST_INSERT_ID - evalengine

- java/example/pom.xml
- java/grpc-client/src/test/resources/ca.config
- java/pom.xml
This PR fixes 3 things
1. Protobuf java and protoc version
2. Mysql connection version upgrade to remove security alert (used only in test in vitess repo)
3. Fix TLS test by fixing the ca config.
Backport: Protobuf java and protoc version is mismatch in v21 causing issue in Debezium connector `vitess-grpc-client` upgrade.
- Fixes https://github.com/vitessio/vitess/issues/17482
> [Java] Fix dependency issues in Java package 

- .github/workflows/upgrade_downgrade_test_backups_e2e.yml
- .github/workflows/upgrade_downgrade_test_backups_manual.yml
- .github/workflows/upgrade_downgrade_test_onlineddl_flow.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries_2.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries_2_next_release.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema.yml
- .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml
- .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml
- .github/workflows/upgrade_downgrade_test_semi_sync.yml
- test/config.json
This splits the Upgrade Downgrade Queries CI workflow into 2 smaller flows to have shorter CI run time.
> split upgrade downgrade queries test to 2 CI workflows

- go/test/endtoend/onlineddl/flow/onlineddl_flow_test.go
Quick fix to Online DDL flow test flakiness, caused to to logging in a goroutine. We can add more synchronization to ensure the logging is only ever done while the tests is still running, but then again this logging is for convenience only. Switched to `fmt.Println` instead, it's just as informative.
https://github.com/vitessio/vitess/actions/runs/12676221410/job/35328963706?pr=17443
> CI: fix to Online DDL flow test, do not t.Log from within a goroutine

- go/test/endtoend/vreplication/helper_test.go
The current check for a workflow to reach a state (typically `Running`) was only checking for the first stream while parsing the json result of a workflow status check. This causes flakiness when there are multiple streams and the first one has reached `Running` but others are, say, `Copying`. 
This PR fixes the logic to indeed iterate over all streams.
The flakiness was introduced by #17441 in v22, so no need to backport.
-   [ ] Documentation was added …
> Fix flaky vreplication tests: correct logic that checks for workflow state in test helper

- go/test/vschemawrapper/vschema_wrapper.go
When using keyspaces in tests, the current schema wrapper we use makes it hard if we are missing a `main` keyspace. This change makes it easier to handle situations without this keyspace.
> test: make it easier to run tests without a main keyspace

- go/timer/randticker_test.go
Removing test that is very dependent on elapsed and local time. Noticed because it fails occassionally in CI requiring the entire unit test workflow to be rerun. Fails consistently 1-3% of the time locally. 
We are already testing the basic functionality elsewhere, so seemed a better option to remove than to try and fine tune the tolerance for the test.
Test has been around for 10 years, so backporting to supported versions.
-   [ ] Documentation was added …
> Flaky TestTickSkip: Remove inherently flaky test

- go/vt/vtctl/workflow/traffic_switcher.go
One line didn't get merged correctly while backporting: https://github.com/vitessio/vitess/pull/17364. This PR fixes that.
#17364 
#17340 
> [Direct PR] Fix merge issue in backport 

- go/vt/vtorc/discovery/queue.go
- go/vt/vtorc/logic/vtorc.go
This PR removes some unused code in discovery queue creation in VTOrc. It also cleans up the map and the mutex since we don't really need it, we only create a single queue in VTOrc.
> Remove unused code in discovery queue creation

- java/example/pom.xml
- java/jdbc/src/main/java/io/vitess/jdbc/VitessJDBCUrl.java
- java/jdbc/src/main/java/io/vitess/jdbc/VitessParameterMetaData.java
- java/jdbc/src/main/java/io/vitess/jdbc/VitessPreparedStatement.java
- java/jdbc/src/main/java/io/vitess/util/charset/CharsetMapping.java
- java/jdbc/src/main/java/io/vitess/util/charset/Collation.java
- java/jdbc/src/main/java/io/vitess/util/charset/MysqlCharset.java
- java/pom.xml
This PR upgrades the the deprecated mysql-connection-java artifact to mysql-connector-j.
Backport: Resolving security alert. 
> [Java]: Bump mysql-connector-java version from 8.0.33 to mysql-connector-j 8.4.0

- go.mod
- go.sum
Updates glog to v1.2.4 as a fix for CVE-2024-45339. 
https://groups.google.com/g/golang-announce/c/H-Q4ouHWyKs?pli=1
https://github.com/golang/glog/commit/a0e3c40a0ed0cecc58c84e7684d9ce55a54044ee
Backport to supported releases.
> CVE Fix: Update glog to v1.2.4

- go/vt/vterrors/code.go
A small change introduced to our error code led to the query serving error documentation generation to not work as expected: It was trying to parse the arguments (%s, %d, etc) in the strings and was printing things like `'%!s(MISSING)'` instead of `'%s'`. The issue is visible [in this PR](https://github.com/vitessio/website/pull/1905), specifically this commit: [vitessio/website@`98b15a1` (#1905)](https://github.com/vitessio/website/pull/1905/commits/98b15a1fcb8a153aad7f0b636b01b673e272b6f6).
We should backport this to 21.0 as the issue was first introduced there.
I have updated https://github.com/vitessio/website/pull/1905 with the newly generated docs for each branch (from 19 to main).
> Fix how we generate the query serving error documentation

- go/vt/vtgate/engine/fake_vcursor_test.go
- go/vt/vtgate/evalengine/fn_time.go
- go/vt/vtgate/executorcontext/safe_session.go
- go/vt/vtgate/executorcontext/safe_session_test.go
Conversion functions into a Go `time.Time` expect to have a valid `*time.Location` and will panic if passed in `nil`.
Before we used also here `nil` to signal no timezone is set (and thus falling back to `time.Local` implicitly, but it's better to always return a timezone explicitly and use `time.Local` where appropriate then.
Fixes #17545 
Marked also for back porting as this can panic. 
> Always return a valid timezone in cursor

- go/mysql/collations/colldata/cached_size.go
- go/sqltypes/cached_size.go
- go/tools/sizegen/sizegen.go
- go/vt/proto/query/cached_size.go
- go/vt/proto/topodata/cached_size.go
- go/vt/proto/vttime/cached_size.go
Important fix for memory calculations of in-memory data structures. Was causing OOMs in production.
In Go 1.23 a new type alias node was introduced for reflection, see https://github.com/golang/go/issues/63223. This initially caused the sizegen generation to crash, which was fixed by @systay in https://github.com/golang/go/issues/63223 but that fix was not complete. It still creates a ton of warnings since that change that were never fixed:
```
2025/01/16 15:51:18 unhandled type: *types.Alias
2025/01/16 15:51:18 unhandled type: *types.Alias
2025/01/16 15:51:18 unhandled type: *types.Alias
2025/01/16 15:51:18 unhandled type: *types.Alias
2025/01/16 15:51:18 unhandled type: *types.Alias
2025/01/16 15:51:18 unhandled type: *types.Alias
2025/01/16 15:51:18 unhandled type: *types.Alias …
```
> sizegen: do not ignore type aliases

- go/cmd/vtctldclient/command/vreplication/vdiff/vdiff.go
- go/cmd/vtctldclient/command/vreplication/vdiff/vdiff_test.go
The text template used for VDiff reports had an extraneous `%` sign in it (needed for `printf`, but NOT templates): https://github.com/vitessio/vitess/blob/eaaa2063ef870391bf17dbf3599978c4eba20868/go/cmd/vtctldclient/command/vreplication/vdiff/vdiff.go#L439
I would notice this every once in a while, but then forget about it. I'm finally cleaning that up here. 🙂 
Manual test :
```
cd examples/local
./101_initial_cluster.sh && mysql < ../common/insert_commerce_data.sql && ./201_customer_tablets.sh
table_file="${VTDATAROOT}/vt_0000000100/data/vt_commerce/customer.ibd"
commerce_primary_uid=$(vtctldclient GetTablets --keyspace commerce --tablet-type primary --shard "0" | awk '{print $1}' | cut -d- -f2 | bc)
size=$((5*1024*1024))
while [[ $(stat -f "%z" "${table_file}") -lt ${size} ]]; do …
```
> VDiff: Remove extra % sign in vdiff text report template

- go/vt/discovery/tablet_picker.go
- go/vt/discovery/tablet_picker_test.go
- go/vt/topo/tablet.go
During a VReplication workflow, if the workflow has its `tablet_types` setup as `primary`, it would panic. This PR fixes that.
This was added a while back, so we should backport to supported versions: https://github.com/vitessio/vitess/pull/14224/files#diff-1bcb2314a21db237d254efff723def4a78db39c34298592d0b0a9a72a58ef575R372
https://github.com/vitessio/vitess/issues/17571
> Tablet picker: Handle the case where a primary tablet is not setup for a shard

- .github/workflows/docker_build_images.yml
- Makefile
- docker/bootstrap/CHANGELOG.md
- docker/bootstrap/Dockerfile.mysql84
- docker/bootstrap/README.md
- docker/lite/Dockerfile.mysql84
- docker/utils/install_dependencies.sh
- docker/vttestserver/Dockerfile.mysql84
- go/tools/go-upgrade/go-upgrade.go
- test.go
Add MySQL8.4 docker images
Fixes #17519
> feat: add mysql 8.4 docker images

- docker/vttestserver/Dockerfile.mysql84
Corrects the version of Go and Debian used.
Edit:
Use the proper versions in the vttestserver. There was some concurrency issue when merging https://github.com/vitessio/vitess/pull/17563, https://github.com/vitessio/vitess/pull/17529 and https://github.com/vitessio/vitess/pull/17552
> Fix typos in MySQL 8.4 Dockerfile

- go/viperutil/config.go
- go/viperutil/config_test.go
As reported in https://github.com/vitessio/vitess/issues/17577, there was a bug in the code which wasn't catching file not found errors if the config file is explicitly provided.
This PR fixes this issue and adds tests to ensure that everything works as intended.
- Fixes https://github.com/vitessio/vitess/issues/17577
> Fix config file not found handling

- go/mysql/binlog_dump.go
- go/mysql/flavor_mysql.go
- go/mysql/replication/mysql56_gtid_set_test.go
- go/mysql/replication_test.go
The current MySQL flavor implementation for `ComBinlogDumpGTID` does not populate the event flags, and sends just 0. When requesting a GTID position, the flags must include `BinlogThroughGTID`. This is then reflected when parsing the event:
https://github.com/vitessio/vitess/blob/10ff5e372de283dbded889152abefccbb2f2c1f0/go/mysql/binlog_dump.go#L78-L89
If we don't populate the flag, we don't parse the GTID value.
this PR adds the necessary flag.
Furthermore, in compliance with MySQL server, we now actually also ignore the flag when parsing a ComBinlogDumpGTID packet. The `datasize` value is enough to determine that there is a GTID payload.
Fixes https://github.com/vitessio/vitess/issues/17579
-   [ ] "Backport to:" labels have been added if this change should be back-ported to release …
> `sendBinlogDumpCommand`: apply BinlogThroughGTID flag

- go/vt/vtadmin/cluster/cluster.go
fixing the cache duration for the SchemaCacheConfig items
Backport reason: bug affecting users requiring at least v20.
fixes #17608
> fix SchemaCacheConfig.DefaultExpiration

- go/mysql/binlog_dump.go
- go/mysql/flavor_mysql.go
- go/mysql/replication.go
- go/mysql/replication_test.go
Quick followup/fix to https://github.com/vitessio/vitess/pull/17580. https://github.com/vitessio/vitess/pull/17580 wasn't well tested, and although nothing in Vitess is actually calling `ComBinlogDumpGTID` with a GTID payload -- such calls fail. This is because the function attempts to run:
```go
position, err = replication.DecodePosition(gtid)
```
However, the encoded GTID does not have a `MySQL56/` prefix. Rightly so, because that's not in the MySQL protocol. The command `ComBinlogDumpGTID` is MySQL-specific (ie not MariaDB or any other flavor) and thus the GTID payload is necessarily a `MySQL56` flavor.
In addition, the GTID is written in `ComBinlogDumpGTID` as a SID block. This PR now also parses it back from a SID block form.
This PR fixes the issue and adds appropriate testing. …
> `parseComBinlogDumpGTID`: GTID payload is always 5.6 flavor

- .github/workflows/check_make_vtadmin_web_proto.yml
- .github/workflows/static_checks_etc.yml
- .github/workflows/vtadmin_web_build.yml
- .github/workflows/vtadmin_web_lint.yml
- .github/workflows/vtadmin_web_unit_tests.yml
- changelog/22.0/22.0.0/summary.md
- docker/binaries/vtadmin/Dockerfile
- web/vtadmin/README.md
- web/vtadmin/build.sh
- web/vtadmin/package-lock.json
- web/vtadmin/package.json
- web/vtadmin/src/proto/vtadmin.d.ts
This bumps to the latest Node LTS version with 22 and to NPM 11. Also bumps Vite to the latest as well to address a Dependanbot alert.
Fixes https://github.com/vitessio/vitess/security/dependabot/401
> Update to latest Nodejs LTS and NPM

- go/vt/sqlparser/normalizer.go
This PR reduces the ast walk in VTGate normalizer code.
Benchmark shows `~5% normalizer` improvement
```
goos: darwin
goarch: arm64
pkg: vitess.io/vitess/go/vt/sqlparser
cpu: Apple M1 Max
│ /Users/planetscale/benchmark/v2.txt │ /Users/planetscale/benchmark/v3.txt │
│               sec/op                │    sec/op     vs base               │
Normalize-4                                                    1.217µ ± 5%    1.103µ ± 1%   -9.41% (p=0.002 n=6)
NormalizeTraces/django_queries.txt-4                           185.9µ ± 2%    167.3µ ± 1%  -10.04% (p=0.002 n=6)
NormalizeTraces/lobsters.sql.gz-4                              9.613m ± 3%    8.348m ± 2%  -13.16% (p=0.002 n=6)
NormalizeVTGate-4                                              71.89m ± 1%    70.74m ± 1%   -1.60% (p=0.041 n=6) …
```
> Reduce VTGate Normalizer multiple AST walks 

- go/mysql/decimal/cached_size.go
- go/tools/sizegen/sizegen.go
- go/vt/schema/cached_size.go
- go/vt/sqlparser/cached_size.go
- go/vt/vtgate/evalengine/cached_size.go
- go/vt/vtgate/vindexes/cached_size.go
- go/vt/vttablet/tabletserver/rules/cached_size.go
This improves sizegen to handle additional types and also have a custom handler for big.Int since the size is computable with the given accessors and decimals are used pretty often.
This is follow up to #17556 which fixed #17555 to make it more robust for more types in the future. There's another path that now would panic on unknown types instead of silently ignoring them. 
> Improve sizegen to handle more types

- doc/internal/release/how-to-release.md
Skipping tests when releasing the Java packages is no longer required for versions >= v22.0.
> Update the how to release java docs

- java/example/src/main/java/io/vitess/example/MysqlJDBCExample.java
This uses the new style. We run this against a new enough MySQL version that this also works.
Should have changed this already as part of earlier #16466 work where we stopped using the old syntax on new enough MySQL.
> Remove deprecated syntax

- go/vt/schemadiff/errors.go
- go/vt/schemadiff/schema.go
- go/vt/schemadiff/schema_diff_test.go
- go/vt/schemadiff/schema_test.go
This PR adds schema-scope validations:
- In the same schema, no two `CHECK` constraints have the same name.
- In the same schema, no two `FOREIGN KEY` constraints have the same name.
Note: there is no problem for a `CHECK` constraint and for a `FOREIGN KEY` constraint to have the same name.
These validations are compliant with MySQL and are required, as MySQL strictly enforces this uniqueness.
- #10203 
> `schemadiff`: validate uniqueness of `CHECK` and of `FOREIGN KEY` constraints

- go/vt/vtctl/workflow/framework_test.go
- go/vt/vtctl/workflow/server_test.go
- go/vt/vtctl/workflow/traffic_switcher_test.go
- go/vt/vtctl/workflow/utils_test.go
This PR adds multiple unit tests in `vtctl/workflow`.
Test coverage on this branch (tests-workflow-server):
```
coverage: 69.1% of statements
ok  	vitess.io/vitess/go/vt/vtctl/workflow	2.741s	coverage: 69.1% of statements
```
Test coverage on main:
```
coverage: 66.7% of statements
ok  	vitess.io/vitess/go/vt/vtctl/workflow	2.876s	coverage: 66.7% of statements
```
Command used:
```
go test ./go/vt/vtctl/workflow --coverprofile=c.out
```
- #17572
- #16499
- …
> test: Add unit tests for `vtctl/workflow`

- go/vt/discovery/healthcheck.go
- go/vt/discovery/healthcheck_test.go
This PR fixes the problem described in https://github.com/vitessio/vitess/issues/17629. As pointed out in the issue, the problem is that the consumers aren't fast enough to ingest all the health check updates and that causes them to miss some of them.
This PR just increases the buffer size from 2 to 2048, so that the messages aren't dropped.
- #17629 
> [release-21.0] Increase health check buffer size

- go/test/endtoend/vreplication/cluster_test.go
- go/test/endtoend/vreplication/vreplication_test.go
- go/vt/vtctl/workflow/server.go
- go/vt/vtctl/workflow/stream_migrator.go
- go/vt/vtctl/workflow/switcher.go
- go/vt/vtctl/workflow/switcher_dry_run.go
- go/vt/vtctl/workflow/switcher_interface.go
- go/vt/vtctl/workflow/traffic_switcher.go
- go/vt/vtctl/workflow/workflows.go
This PR improves the error handling for cancel failures (see [issue](https://github.com/vitessio/vitess/issues/17620)). When the context changes are commented out in the PR branch we can see the new error handling in action here when using the manual test in the issue:
```
❯ vtctldclient MoveTables --workflow commerce2customer --target-keyspace customer switchtraffic
E0123 10:57:24.082537   40795 main.go:60] rpc error: code = Unknown desc = failed to sync up replication between the source and target: rpc error: code = DeadlineExceeded desc = context deadline exceeded
could not revert denied tables / shard access: Code: INTERNAL
keyspace commerce is not locked (no locksInfo)
cancel migration failed, manual cleanup work may be necessary
```
And with the context changes in place:
```
❯ …
```
> VReplication: Address SwitchTraffic bugs around replication lag and cancel on error

- .github/CODEOWNERS
- go/vt/vtctl/workflow/traffic_switcher_test.go
This PR makes two minor changes:
1. Adds `tabletmanager/vdiff` to GitHub CODEOWNERS (I noticed that it was not there from a recent PR)
2. Makes two minor unit test adjustments to deal with `golangci-lint` failures now on main:
```
❯ $(go env GOPATH)/bin/golangci-lint run go/... --timeout 10m
go/vt/vtctl/workflow/traffic_switcher_test.go:969:20: Error return value of `ts.cancelMigration` is not checked (errcheck)
ts.cancelMigration(ctx, sm)
^
go/vt/vtctl/workflow/traffic_switcher_test.go:1030:20: Error return value of `ts.cancelMigration` is not checked (errcheck)
ts.cancelMigration(ctx, sm)
^
```
This occurred because of two PRs that got merged concurrently today (new unit tests and changes to cancelMigration).
-   [x] "Backport to:" labels have been added if this change should be …
> VReplication: CODEOWNERS and unit test housekeeping

- go/vt/discovery/keyspace_events.go
- go/vt/vtgate/buffer/shard_buffer.go
In #17294 we moved some of the buffering related logs to level 2. However, we do want to always see Starting/Stopping/Draining messages which are emitted once per shard. What we wanted to suppress were the "disruption in shard resolved" type messages which we were logging up to n^2 times if you are concurrently running PRS on n shards.
Changes in this PR
- Continue to log Starting/Stopping/Draining once per shard
- Move "keyspace event resolved" logs per-shard to level 2
- add a log line for "keyspace is consistent" per keyspace, whenever it becomes consistent
No back ports are required since the original PR was not back ported.
#17294 
-   [ ] If this change is to be back-ported to …
> Improve vtgate logging for buffering

- go/test/endtoend/vreplication/vdiff_helper_test.go
- go/vt/binlog/binlogplayer/binlog_player.go
- go/vt/vtctl/vdiff_env_test.go
- go/vt/vtctl/workflow/resharder.go
- go/vt/vtctl/workflow/traffic_switcher.go
- go/vt/vtctl/workflow/utils.go
- go/vt/vttablet/endtoend/vstreamer_test.go
- go/vt/vttablet/onlineddl/executor.go
- go/vt/vttablet/tabletmanager/vdiff/utils.go
- go/vt/vttablet/tabletmanager/vreplication/insert_generator.go
- go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
- go/vt/vttablet/tabletserver/schema/tracker.go
- go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
- go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go
- go/vt/wrangler/keyspace.go
Don't directly interpolate these strings. We don't know of any user controllable ways to do this, but it's still too risky to ever do this. We always need to escape all strings.
Ideally we refactor this as well to use better statement binding in the future.
Marked this also for backports out of an abundance of care. We don't know of any way this would be abused, but we don't want to take the risk here either. 
https://github.com/vitessio/vitess/security/code-scanning/1928
https://github.com/vitessio/vitess/security/code-scanning/369 …
> Always make sure to escape all strings

- .github/workflows/codecov.yml
- .github/workflows/unit_race.yml
- .github/workflows/unit_race_evalengine.yml
- .github/workflows/unit_test_evalengine_mysql57.yml
- .github/workflows/unit_test_evalengine_mysql80.yml
- .github/workflows/unit_test_evalengine_mysql84.yml
- .github/workflows/unit_test_mysql57.yml
- .github/workflows/unit_test_mysql80.yml
- .github/workflows/unit_test_mysql84.yml
- build.env
- docker/mini/install_mini_dependencies.sh
- test/templates/unit_test.tpl
Upgrades etcd to match the version used in the operator in https://github.com/planetscale/vitess-operator/pull/654.
> Upgrade default etcd version to 3.5.17

- go/vt/mysqlctl/mysqld.go
Add `postflight_mysqld_start` and `preflight_mysqld_shutdown` hooks. This will allow users to take some action after Vitess starts `mysqld`, and before it is about to shut it down, all while allowing Vitess keep responsibility for actually starting/stopping `mysqld`.
- Fixes: https://github.com/vitessio/vitess/issues/17651
None.
> go/vt/mysqlctl: add postflight_mysqld_start and preflight_mysqld_shutdown hooks

- go/vt/vtcombo/tablet_map.go
- go/vt/vtctl/grpcvtctldserver/server.go
- go/vt/vtctl/grpcvtctldserver/testutil/test_tmclient.go
- go/vt/vtctl/reparentutil/emergency_reparenter.go
- go/vt/vtctl/reparentutil/emergency_reparenter_test.go
- go/vt/vttablet/common/config.go
- go/vt/vttablet/faketmclient/fake_client.go
- go/vt/vttablet/grpctmclient/client.go
- go/vt/vttablet/grpctmserver/server.go
- go/vt/vttablet/tabletmanager/rpc_agent.go
- go/vt/vttablet/tabletmanager/rpc_replication.go
- go/vt/vttablet/tabletserver/twopc.go
- go/vt/vttablet/tmclient/rpc_client_api.go
- go/vt/vttablet/tmrpctest/test_tm_rpc.go
We have various places where the types of what we parse and then use don't align. This is something CodeQL correctly warns about that it can lead to unexpected behavior with truncation.
This fixes those cases that CodeQL is complaining about.
https://github.com/vitessio/vitess/security/code-scanning/793
https://github.com/vitessio/vitess/security/code-scanning/792
https://github.com/vitessio/vitess/security/code-scanning/1931
https://github.com/vitessio/vitess/security/code-scanning/1927
https://github.com/vitessio/vitess/security/code-scanning/1926
https://github.com/vitessio/vitess/security/code-scanning/1925
https://github.com/vitessio/vitess/security/code-scanning/1924
https://github.com/vitessio/vitess/security/code-scanning/1923 …
> Fix integer parsing logic

- go/os2/file.go
- go/test/endtoend/backup/vtctlbackup/backup_utils.go
- go/test/endtoend/cluster/cluster_util.go
- go/test/endtoend/cluster/vttablet_process.go
- go/vt/mysqlctl/backupengine.go
- go/vt/mysqlctl/blackbox/utils.go
- go/vt/mysqlctl/builtinbackupengine.go
- go/vt/mysqlctl/filebackupstorage/file.go
- go/vt/mysqlctl/mysqld.go
This abstracts this ever so slightly into a new `os2.Create` to replace usages of `os.Create` across packages.
I didn't want to address every single use of `os.Create` within this PR, but ideally we'd review other uses and swap them to use this version.
This prevents files from being created and written with world read/write privileges. I strongly don't think any of these cases, that behavior was intentional, rather implicit due to using `os.Create` which internally uses 0666 permissions.
> [!NOTE]
> I think that this should be backported to all supported releases (back to v19 today) since it improves the product's security posture.
Fixes #17647 …
> Replace uses of os.Create with os2.Create within backup/restore workflows

- go/vt/vtgate/schema/tracker.go
- go/vt/vtgate/schema/tracker_test.go
- go/vt/wrangler/vdiff.go
- go/vt/wrangler/vdiff_test.go
The schema tracker was not using strict DDL parsing which means that on an unparsable table definition, it would panic later on.
The intent here always was from looking at the code to skip any table that can't be parsed properly, so let's do that here instead.
Marked for backporting as this can lead to a panic and vtgate being in a crash loop if there's a schema in MySQL that can't be parsed. 
Reported [here](https://vitess.slack.com/archives/C0PQY0PTK/p1738206413242479). 
Part of fixing https://github.com/vitessio/vitess/issues/17670 …
> Fix panic inside schema tracker

- go/pools/smartconnpool/pool.go
- go/pools/smartconnpool/pool_test.go
- go/pools/smartconnpool/waitlist.go
This is a potential fix for the issue described in https://github.com/vitessio/vitess/issues/17662. The bug report has a very comprehensive explanation of the bug (thank you!!), so I'll stick to explaining the fix here.
I've considered introducing stronger synchronization to the pool to prevent the race but decided against it because the race does not affect correctness, as the connections in the pool would only starve in situations where the service just stops receiving new requests over time. As long as the pool periodically receives connection requests, no connection can starve because the clients who raced with other clients and are stuck in the waitlist will wake up right away when the new connections come in. I don't think persistently slowing down the pool to handle for this corner …
> smartconnpool: do not allow connections to starve

- go/vt/vtctl/workflow/framework_test.go
- go/vt/vtctl/workflow/server_test.go
This PR adds some unit tests for some APIs in `server.go`
Test coverage on this branch:
```
vitess.io/vitess/go/vt/vtctl/workflow	2.786s	coverage: 69.1% of statements
```
Test coverage on main:
```
vitess.io/vitess/go/vt/vtctl/workflow	3.445s	coverage: 67.8% of statements
```
- #17572
> test: Add more unit tests for `server.go`

- go/vt/vttablet/tabletmanager/shard_sync.go
- go/vt/vttablet/tabletmanager/vdiff/controller.go
- go/vt/vttablet/tabletmanager/vdiff/engine.go
- go/vt/vttablet/tabletmanager/vdiff/framework_test.go
- go/vt/vttablet/tabletmanager/vdiff/stats.go
- go/vt/vttablet/tabletmanager/vdiff/workflow_differ_test.go
There is a race when vttablet starts and the vdiff engine opens. It starts vdiffs which need to be resumed where we restart vdiffs in error state concurrently with the vdiff engine init. It is possible that `globalStats` map is not initialized when a new controller gets added and the controller adds it self to the map.
This PR starts the goroutine that runs the controller thread only after the inits have been done.
```
if err := vde.initControllers(rows); err != nil {
return err
}
vde.updateStats()
// At this point we've fully and successfully opened so begin
// retrying error'd VDiffs until the engine is closed.
vde.wg.Add(1)
go func() {
defer vde.wg.Done()
if vde.fortests {
return
}
vde.retryErroredVDiffs()
}()
```
This was added way back, so we backport to all supported versions: …
> VDiff: fix race when a vdiff resumes on vttablet restart

- .github/workflows/update_golang_dependencies.yml
Small fix to the golang auto deps upgrade workflow, we were reading `go.mod` before checking out the code.
> Fix golang dependencies upgrade workflow

- go/mysql/capabilities/capability.go
- go/mysql/capabilities/capability_test.go
`go/mysql/capabilities` identifies and supports  `InnoDBParallelReadThreadsCapability`, which maps to [innodb_parallel_read_threads](https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_parallel_read_threads) introduced in `8.0.14`.
Now used yet at this time. To be potentially used in Online DDL, running a `SELECT COUNT(*)` exact row count while migration is running, so as to improve ETA/ratio
https://github.com/vitessio/vitess/pull/10445
-   [ ] Did the new or modified tests pass consistently locally and …
> Supporting `InnoDBParallelReadThreadsCapability`

- changelog/22.0/22.0.0/summary.md
- go/cmd/vttablet/cli/cli.go
- go/vt/tableacl/tableacl.go
- go/vt/vttablet/tabletserver/tabletserver.go
- go/vt/vttablet/tabletserver/tabletserver_test.go
This fixes potentially bringing down a tablet with an innocuous SIGHUP.
It also logs the fact it's reading the ACL file, to fix not getting any feedback on SIGHUP.
https://github.com/vitessio/vitess/issues/17139
Currently, deploying new ACL files is not only very involved because I have to test them against a running Vitess instance, but it's also very stressful to do `killall -SIGHUP vttablet` knowing that it can bring down the entire system.
Because of the risk of downtime caused by simple ACL definition mistakes, I think this is a candidate for back-porting.
https://github.com/vitessio/vitess/issues/17139
-   [ ] If this change is to be back-ported to previous releases, a …
> Don't exit tablet server on reloading invalid ACL

- go/vt/schemadiff/schema.go
- go/vt/schemadiff/schema_test.go
The UnsupportedConstruct error is returned for execution of select queries inside vtgate, but when we analyze views we don't care about those.
Views here are executed at the MySQL level though and always inside a single shard, so we don't want to return these errors.
The test example here shows a case where it thinks it's in sharded mode because of a missing dependency, but we only want to show that we're missing a table dependency.
Part of #10203 
-   [x] …
> Ignore execution time errors for schemadiff view analysis

- go/vt/vtgate/semantics/semantic_table.go
This PR introduces a small but valuable optimization to how dependencies are copied, resulting in performance improvements.
1. During tree walking, we clone parts of the AST and copy dependency/type info for each node. For example:
```go
output := sqlparser.CopyOnRewrite(in, pre, post, ctx.SemTable.CopySemanticInfo)
```
2. Here, `CopySemanticInfo` is called for each cloned node and internally invokes `CopyDependencies`.
3. Currently, `CopyDependencies` calculates dependencies by walking the entire subtree and then stores the results in the semantic table. This extra work is unnecessary—it can be done on demand.
4. This PR changes the logic to copy only the existing info for the specific node, rather than re-walking and recalculating for its entire subtree.
```
│ ../main.bench │ …
```
> Faster dependency copying

- go/vt/schemadiff/errors.go
- go/vt/schemadiff/schema.go
- go/vt/schemadiff/schema_test.go
An enhancement to `ViewDependencyUnresolvedError`, which is now more detailed and lists the names of missing referenced entities.
#10203 
> schemadiff: `ViewDependencyUnresolvedError` lists missing referenced entities

- go/test/endtoend/vreplication/cluster_test.go
- go/test/endtoend/vreplication/migrate_test.go
The [`vreplication_migrate` workflow](https://github.com/vitessio/vitess/blob/main/.github/workflows/cluster_endtoend_vreplication_migrate.yml) which runs the [`TestMigrateUnsharded` and `TestMigrateSharded`](https://github.com/vitessio/vitess/blob/main/go/test/endtoend/vreplication/migrate_test.go) tests [has been a *little* flaky](https://github.com/vitessio/vitess/actions/workflows/cluster_endtoend_vreplication_migrate.yml). The failures that I've seen are all related to port re-use. For example, from [the most recent non-PR changes related failure](https://github.com/vitessio/vitess/actions/runs/13165249145/job/36743668214): 
```
2025-02-05T19:46:04.6078463Z F0205 19:45:45.485443   37959 grpc_server.go:305] Cannot listen on port 28192 for gRPC: listen tcp 127.0.0.1:28192: bind: …
```
> CI: Add some randomness to the ports used in VReplication e2e tests

- go/vt/vttablet/tabletserver/state_manager_test.go
This PR fixes the data race found in `TestIsServingLocked` - 
```
Read at 0x00c0007b9e8f by goroutine 13510:
vitess.io/vitess/go/vt/vttablet/tabletserver.(*testDiskMonitor).IsDiskStalled()
/opt/actions-runner/_work/vitess-private/vitess-private/go/vt/vttablet/tabletserver/state_manager_test.go:157 +0x28
vitess.io/vitess/go/vt/vttablet/tabletserver.(*stateManager).isServingLocked()
/opt/actions-runner/_work/vitess-private/vitess-private/go/vt/vttablet/tabletserver/state_manager.go:793 +0xe1
vitess.io/vitess/go/vt/vttablet/tabletserver.(*stateManager).Broadcast()
/opt/actions-runner/_work/vitess-private/vitess-private/go/vt/vttablet/tabletserver/state_manager.go:736 +0x14a
vitess.io/vitess/go/vt/vttablet/tabletserver.(*stateManager).Broadcast-fm() …
```
> Fix data race in `TestIsServingLocked`

- examples/operator/operator.yaml
This is a follow up of the work done by @mcrauwel on https://github.com/planetscale/vitess-operator/pull/662. The CRDs are changing, and this PR makes sure the changes are reported on the vtop examples in the vitessio/vitess repository.
> `operator.yaml`: pass on the `sidecarDbName` when creating a keyspace

- go/cmd/vtcombo/cli/main.go
- go/cmd/vtctldclient/command/root.go
Inside vtcombo we were setting up the vtenv too early in `init()`. This leads to reading the MySQL version number before it actually is set from the given flags, ignoring the passed in option.
This moves it into the `run` function which is the appropriate place.
We do a similar fix for `vtctldclient` by making sure we initialize the vtenv inside the pre-run command instead of in the `init()` to avoid a potentially similar problem.
Don't know how to really test this further except for the manual testing I have done. There's nothing around tests that end up invoking the binary itself, which is needed to uncover this problem. 
Should we backport this fix?
Fixes #17645
-   [x] If this change …
> Fix vtcombo parsing flags incorrectly

- go/vt/vttablet/tabletmanager/vreplication/replicator_plan.go
- go/vt/vttablet/tabletmanager/vreplication/vcopier_atomic.go
Note that this doesn't fix the [underlying issue](https://github.com/vitessio/vitess/issues/17716
) that was reported but just fixes the panic, adds debug logging and returns an error so that vttablet doesn't crash.
It does fix a bug in a list initialization, used only for logging in atomicCopy mode, that was resulting in a confusing log message.
Unable to repro the underlying issue, so we will create a new issue with details when we get more info on it.
Backporting to all supported versions to prevent the panic.
Fixes https://github.com/vitessio/vitess/issues/17716
-   [ ] …
> Atomic Copy: Fix panics when the copy phase starts in some clusters

- go/acl/acl.go
- go/acl/acl_test.go
- go/acl/deny_all_policy.go
- go/acl/deny_all_policy_test.go
- go/acl/read_only_policy.go
- go/acl/read_only_policy_test.go
This removes the unused code found by deadcode in the go/acl package.
> Remove unused code from go/acl

- go/vt/vtgate/planbuilder/operators/subquery_planning.go
- go/vt/vtgate/planbuilder/testdata/select_cases.json
Subqueries inside subqueries were not handled well if they could all be merged into a single query.
Fixes #17775
> bugfix: support subqueries inside subqueries when merging

- go/vt/sqlparser/normalizer.go
- go/vt/sqlparser/parse_test.go
- go/vt/vtgate/planbuilder/testdata/unsupported_cases.json
As pointed out in https://github.com/vitessio/vitess/issues/17751, we shoud be failing assignment expressions with the proper error message.
- Fixes https://github.com/vitessio/vitess/issues/17751
> Fail assignment expressions with the correct message

- go/pools/smartconnpool/connection.go
- go/pools/smartconnpool/pool.go
- go/pools/smartconnpool/pool_test.go
- go/pools/smartconnpool/stack.go
- go/pools/smartconnpool/timestamp.go
We've had a report of a performance regression when migrating from an old Vitess version to a newer version that contains the new smart connection pool implementation. The system in question has inconsistent (spiky) load patterns _and_ quite stringent idle timeouts for connections.
Our assumption here is that the regression is caused by a combination of two factors: the new connection pool provides connections in a LIFO pattern (where the most recently returned to the pool is returned to the client on subsequent gets). This is as opposed to the old pool, which was FIFO, meaning that the pool would constantly cycle through all the available connections. In systems that are not at full capacity, the LIFO connection pool will continuously re-use a small subset of all the open connections. …
> smartconnpool: Better handling for idle expiration

- go/vt/vtctl/grpcvtctldserver/server.go
- go/vt/vtctl/grpcvtctldserver/server_test.go
- go/vt/vtctl/grpcvtctldserver/testutil/proto_compare.go
This sorts the results of GetTablets (which for my current use case, will sort the output of [ListShardTablets](https://vitess.io/docs/archive/12.0/reference/programs/vtctl/shards/#listshardtablets)) and allow it to be consistently grokkable due to it's deterministic ordering.
To test this change, I first modified the `TestGetTablets` unit test under server_test.go from calling `testutil.AssertSameTablets(t, tt.expected, resp.Tablets)`, which first sorts the expected and actual, to `			utils.MustMatch(t, tt.expected, resp.Tablets)`, the call made under the hood after sorting in `AssertSameTablets`. I got the following running `go test` with just that test change:
<details>
```
--- FAIL: TestGetTablets (0.02s)
--- FAIL: TestGetTablets/cells_filter (0.00s)
panic: interface conversion: …
```
> [Feature]: Sort results of getTablets for consistency in output/readability

- test/ci_workflow_gen.go
- test/templates/cluster_endtoend_test.tpl
- test/templates/cluster_endtoend_test_docker.tpl
- test/templates/cluster_endtoend_test_mysql57.tpl
- test/templates/cluster_vitess_tester.tpl
- test/templates/unit_test.tpl
This small tweak to `test/ci_workflow_gen.go` makes it more straightforward for forks of `vitessio/vitess` to modify the GitHub Actions runner used for heavier CI jobs _(modify the `const cores16RunnerName`)_
> Simply changing GH Actions runner

- go/test/endtoend/vreplication/fk_ext_test.go
- go/test/endtoend/vreplication/fk_test.go
- go/vt/vttablet/tabletmanager/vreplication/vcopier_atomic.go
Setting `--vreplication-parallel-insert-workers` greater than 1, had not been tested earlier for atomic copies. When a user attempted to do it, it caused a panic in `vttablet`. There were two fixes needed here:
1. The response needed to be cloned before passing it to the concurrent workers. This had been done for regular workflows but was missed in the atomic copy case.
2. The copy state for the last table was deleted incorrectly before the queue was closed (and all concurrent workers had stopped inserting). 
In addition the `TestFKWorkflow` e2e test has been changed to test with concurrent inserts. 
Fixes #17716 
-   [ ] If this change is to be back-ported to previous releases, a …
> VReplication Atomic Copy Workflows: fix bugs around concurrent inserts

- go/vt/topotools/mirror_rules.go
- go/vt/vtctl/workflow/server.go
- go/vt/vtctl/workflow/traffic_switcher.go
- go/vt/vttablet/tabletmanager/vreplication/controller.go
- go/vt/vttablet/tabletmanager/vreplication/vplayer.go
Currently when a multi-tenant SwitchWrites times out and `cancelMigration()` is called, we also add denied tables to the target keyspace's shard control. This is clearly incorrect behaviour since other tenants could be already migrated and live on the target keyspace.
This PR:
* changes this behaviour and no longer adds the denied tables to the target
* adds a lot of logs in cancelMigration(). Currently the logs are sent to the caller and not in the normal `vtctld` logs
* reduces the verbosity of logs where the entire binlogsource filter was being printed making the logs very noisy
https://github.com/vitessio/vitess/issues/17794
-   [ ] If this change is to be back-ported to previous …
> Multi-tenant workflow SwitchWrites: Don't add denied tables on cancelMigration()

- go/vt/topo/faketopo/faketopo.go
- go/vt/vtorc/logic/tablet_discovery.go
- go/vt/vtorc/logic/tablet_discovery_test.go
This PR improves the safety of `getAllTablets` in `go/vt/vtorc/logic/tablet_discovery.go`, which is used to get all tablet records from all cells
The new logic returns the tablets from `getAllTablets(...)` in a per-cell map _(as `map[string][]*topo.TabletInfo`)_ to ensure that only the cells that responded are operated on. A list of failed cells is also returned as `[]string`
This [avoids tablets from being forgotten](https://github.com/vitessio/vitess/blob/4f91fc93b7c28b610a32478e09e510554d096bd9/go/vt/vtorc/logic/tablet_discovery.go#L297-L313) when one more cells fail, because before this PR the SQL query to get aliases to forget in `refreshTablets(...)`  does not consider cells that never responded. This bug was introduced by https://github.com/vitessio/vitess/pull/17388
Closes …
> `vtorc`: improve handling of partial cell topo results

- test/ci_workflow_gen.go
This PR fixes a minor nit introduced by my PR https://github.com/vitessio/vitess/pull/17788
I didn't realize `test/ci_workflow_gen.go` had `const`/`var`s grouped by purpose, and I dumped my new consts in a group of `const` for MySQL versions. This PR moves the new `const`s to a new section
> nit: move new `const`s to own section

- go/pools/smartconnpool/stack.go
- go/pools/smartconnpool/stack_test.go
After upgrading to v19, we noticed a constant growth in memory usage in one of our keyspaces.
Looking at a heap profile, we noticed that the majority of this additional memory usage came from `bufio.NewReaderSize`, which was called as part of `mysql.newConn`.
@danieljoos and I believe we were able to trace this back to the new connection pool, when reserved connections are employed in a keyspace. We use reserved connections implicitly in this keyspace, to support `GET_LOCK()` queries.
`Pooled[C]` structs keep a pointer to the `next` connection in the stack. This pointer was only reset when a connection was returned to a connection stack, but not cleared when the connection was taken out of a stack. If a reserved connection `A` was pointing to a connection that was turned into a reserved …
> Fix a potential connection pool leak.

- go/cmd/vtcombo/cli/main.go
- go/cmd/vtctldclient/command/root.go
This is a (manual) backport of #17743
> [release-21.0] Fix vtcombo parsing flags incorrectly (#17743)

- go/pools/smartconnpool/pool.go
- go/pools/smartconnpool/pool_test.go
This PR complements the earlier change made in https://github.com/vitessio/vitess/pull/17757 by further refining the connection pool’s idle timeout behavior.
This implementation reduces connection churn. Instead of simply closing idle connections, they will now be closed and immediately reopened. This ensures that connections remain fresh and available, preventing unnecessary delays caused by frequent connection creation during traffic spikes.
Backport Reason: The previous iteration of this change was backported, so this update should be backported as well to maintain consistency and ensure the improvements apply across all relevant versions.
- Closes https://github.com/vitessio/vitess/issues/17819
-   [ ] "Backport to:" labels have been added if this change should be back-ported to …
> pool: reopen connection closed by idle timeout

- go/pools/smartconnpool/pool.go
- go/pools/smartconnpool/pool_test.go
This is a backport of https://github.com/vitessio/vitess/pull/17818
> [release-21.0] pool: reopen connection closed by idle timeout (#17818)

- go/pools/smartconnpool/pool.go
- go/pools/smartconnpool/pool_test.go
This is a backport of https://github.com/vitessio/vitess/pull/17818
> [release-20.0] pool: reopen connection closed by idle timeout (#17818)

- go/vt/discovery/tablet_picker.go
- go/vt/discovery/tablet_picker_test.go
- go/vt/vtgate/vstream_manager.go
This PR adds support in the [TabletPicker](https://vitess.io/docs/reference/vreplication/tablet_selection/) for excluding tablets that have MySQL replication lag higher than a given maximum value. It then uses this new support in the VTGate vstream manager to exclude candidates that would immediately [fail when we start the health check stream from the selected tablet](https://github.com/vitessio/vitess/blob/2118bc35d4711f2070b3dd1ae2d14decc28ca060/go/vt/vtgate/vstream_manager.go#L582-L584).
- Fixes: https://github.com/vitessio/vitess/issues/17833 …
> VReplication: Support excluding lagging tablets and use this in vstream manager

- docker/lite/Dockerfile
- docker/lite/Dockerfile.mysql84
- docker/lite/Dockerfile.percona80
This PR is a repeat of https://github.com/vitessio/vitess/pull/11968, but for the `docker/lite` container
TL;DR: allow `BUILD_NUMBER`, `BUILD_GIT_BRANCH`, `BUILD_GIT_REV` and `BUILD_TIME` to be set at docker build time, so metrics like `vtgate_build_information{}`/etc get the correct info
This is read from: https://github.com/vitessio/vitess/blob/main/tools/build_version_flags.sh#L31-L34. The `DEFAULT_` fallbacks are sometimes not desired, for example `BUILD_GIT_BRANCH` is often `HEAD`, not the real branch …
> Allow build git envs to be set in `docker/lite`

- go/vt/vttablet/tabletmanager/rpc_replication.go
- go/vt/vttablet/tabletmanager/rpc_replication_test.go
- go/vt/vttablet/tabletserver/controller.go
- go/vt/vttablet/tabletserver/tabletserver.go
- go/vt/vttablet/tabletservermock/controller.go
This PR fixes the issue pointed out in https://github.com/vitessio/vitess/issues/17822 by clearing the demote primary stalled field after the function finishes.
- Fixes https://github.com/vitessio/vitess/issues/17822
> Clear `demotePrimaryStalled` field after the function ends

- go/cmd/vtclient/cli/vtclient.go
- go/cmd/vtclient/cli/vtclient_test.go
- go/cmd/vtclient/vtclient.go
- go/vt/servenv/servenv.go
- It looks like cmd.Use was accidenatlly used instead of `cmd.Name()`
- `cmd.Use` is actaully the help text, not the name of the command
- This was not allowing commands to make use of registered/available flags for their use (IE --grpc_...)
Extra:
- Since a lot of these flags are initialized by functional callback, we should not rely on go-lang `init()` as the order can change and be somewhat arbitrary
- Refactored `init()` to `initializedFlags()` and called at runtime for vtclient
Fixes https://github.com/vitessio/vitess/issues/17801
-   [X] Tests were added or are not …
> Fix vtclient vtgate missing flags (specifically --grpc_*)

- go/vt/discovery/healthcheck.go
- go/vt/discovery/healthcheck_test.go
This PR fixes the problem described in https://github.com/vitessio/vitess/issues/17629. As pointed out in the issue, the problem is that the consumers aren't fast enough to ingest all the health check updates and that causes them to miss some of them.
This PR just increases the buffer size from 2 to 2048, so that the messages aren't dropped.
- Fixes #17629 
> Increase health check channel buffer

- go/vt/vtorc/inst/instance_dao.go
- go/vt/vtorc/inst/tablet_dao.go
This PR prevents a duplicate read of an instance in `inst.ReadTopologyInstanceBufferable(...)`, which is a pretty hot-path func
[Immediately before `fullStatus(...)` is called we call `inst.ReadTablet(...)`](https://github.com/vitessio/vitess/blob/45b588272166308174a20496294fd6fa145b091e/go/vt/vtorc/inst/instance_dao.go#L196) and today `fullStatus(...)` immediately does the same `inst.ReadTablet(...)` read again
-   [x] Did the new or modified tests pass consistently locally and on …
> `vtorc`: remove duplicate instance read from backend

- go/vt/vtgate/evalengine/cached_size.go
- go/vt/vtgate/evalengine/compiler.go
- go/vt/vtgate/evalengine/compiler_asm.go
- go/vt/vtgate/evalengine/compiler_asm_push.go
- go/vt/vtgate/evalengine/compiler_test.go
- go/vt/vtgate/evalengine/eval_temporal.go
- go/vt/vtgate/evalengine/expr_bvar.go
- go/vt/vtgate/evalengine/expr_collate.go
- go/vt/vtgate/evalengine/expr_column.go
- go/vt/vtgate/evalengine/fn_compare.go
- go/vt/vtgate/evalengine/fn_compare_test.go
- go/vt/vtgate/evalengine/fn_time.go
- go/vt/vtgate/evalengine/integration/comparison_test.go
- go/vt/vtgate/evalengine/testcases/cases.go
- go/vt/vtgate/evalengine/testcases/helpers.go
This is currently missing and leads to incorrect types to be returned for `LEAST` & `GREATEST` as comparison functions.
There's a little mismatch here in behavior compared to MySQL which I argue is actually a bug in MySQL. In MySQL, a temporal type always has the binary collation:
```
mysql> select NOW(6), collation(NOW(6));
+----------------------------+-------------------+
| NOW(6)                     | collation(NOW(6)) |
+----------------------------+-------------------+
| 2025-02-19 15:33:21.732301 | binary            |
+----------------------------+-------------------+
```
On MySQL 8.4, this results in:
```
mysql> select GREATEST(NOW(6), NOW(6)), collation(GREATEST(NOW(6), NOW(6)));
+----------------------------+-------------------------------------+
| …
```
> Implement temporal comparisons

- go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
- go/vt/vttablet/onlineddl/executor.go
- go/vt/vttablet/tabletserver/throttle/base/app_throttle.go
- go/vt/vttablet/tabletserver/throttle/throttlerapp/app.go
- go/vt/vttablet/tabletserver/throttle/throttlerapp/app_test.go
See https://github.com/vitessio/vitess/issues/17849 for details.
The online DDL executor checks the throttle ration for each migration;'s UUID and updates  `user_throttle_ratio` with the hihest ratio of (uuid-ratio, online-ddl ratio).
Fixes https://github.com/vitessio/vitess/issues/17849
> Online DDL: consider UUID throttle ratios in `user_throttle_ratio`

- go/vt/vttablet/tabletserver/throttle/base/metric_name.go
- go/vt/vttablet/tabletserver/throttle/base/metric_name_test.go
- go/vt/vttablet/tabletserver/throttle/base/metric_scope.go
- go/vt/vttablet/tabletserver/throttle/base/metric_scope_test.go
- go/vt/vttablet/tabletserver/throttle/base/self_metric.go
- go/vt/vttablet/tabletserver/throttle/check.go
General memory/allocation optimization: for purposes of gauge export, the throttler dynamically computes debug/var names, and turns metric and scope names into pascal case.
The way it's done right now is wasteful since the name is computed via regexp/string manipulation every single time. This PR pre-computes the metric pascal case for all metrics and scopes.
-
> Throttler: reduce regexp/string allocations by pre-computing pascal case

- go/vt/vtgate/planbuilder/operators/SQL_builder.go
- go/vt/vtgate/planbuilder/operators/filter.go
- go/vt/vtgate/planbuilder/operators/helpers.go
- go/vt/vtgate/planbuilder/operators/join.go
- go/vt/vtgate/planbuilder/operators/plan_query.go
- go/vt/vtgate/planbuilder/operators/projection.go
- go/vt/vtgate/planbuilder/operators/projection_pushing.go
- go/vt/vtgate/planbuilder/operators/query_planning.go
- go/vt/vtgate/planbuilder/operators/route_planning.go
- go/vt/vtgate/planbuilder/plan_test.go
Move most of the code in `Compact` implementations to run as normal push down rewriters instead.
> Small planner refactoring

- go/mysql/flavor_mysql.go
- go/vt/vttablet/endtoend/misc_test.go
- go/vt/vttablet/tabletserver/schema/engine.go
- go/vt/vttablet/tabletserver/schema/engine_test.go
For a specific `MoveTables` workflow, we are seeing timeouts on reloading the schema on unmanaged tables connected to the multi-tenant Aurora cluster with a massive number of tables.
For schema reloads, we are defaulting to using the "with sizes" query instead of just the "base tables" one. The "with sizes" one is significantly slower and is only needed by `Online DDL` migrations which we don't do on the unmanaged keyspaces.
This PR changes the VReplication related schema reloads to not include file size stats. We do reload stats for the periodic reload that is done on a timer at interval defined by the `vttablet` flag `--queryserver-config-schema-reload-time`.
Vitess now only supports MySQL 5.7 for imports, since 5.7 is EOL. So for the 5.7 flavor, which is the one used for many of the …
> VTTablet schema reload: include stats only on periodic reload, default to "base table" query for the "with sizes" query for 5.7 only

- go/vt/vttablet/tabletserver/vstreamer/planbuilder.go
- go/vt/vttablet/tabletserver/vstreamer/planbuilder_test.go
- go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go
This PR adds support for `IS NULL` filter in VStream.
- Fixes #17682
> VStream: Add `IS NULL` filter support

- go/cache/lru_cache_test.go
- go/event/event_test.go
- go/exit/exit_test.go
- go/history/history_test.go
- go/mysql/binlog_event_common_test.go
- go/mysql/binlog_event_mariadb_test.go
- go/pools/id_pool_test.go
- go/pools/resource_pool_test.go
- go/pools/smartconnpool/pool_test.go
- go/sqltypes/type_test.go
- go/stats/statsd/statsd_test.go
- replace instances of t.Errorf and t.Fatalf with assert and require
- #15182
> test: replace `t.Errorf` and `t.Fatalf` with `assert` and `require`

- go/vt/vtorc/inst/shard_dao.go
- go/vt/vtorc/inst/shard_dao_test.go
- go/vt/vtorc/logic/keyspace_shard_discovery.go
- go/vt/vtorc/logic/keyspace_shard_discovery_test.go
This PR adds stats for what keyspace/shards are being watched by VTOrc, populated using the backend database
While adding this support I noticed records are never deleted from the backend `vitess_shard` table, so I added support for stale records to be deleted in a similar way to tablets: by recording what was successfully "saved" in the latest polling and removing anything that was not in that list
Finally, shards that do not meet the `--clusters_to_watch` key-ranges will not be saved to the backend. Currently all shards of a keyspace are stored
Closes https://github.com/vitessio/vitess/issues/17816
-   [x] If this change is to be back-ported to previous releases, a justification is …
> Add stats for shards watched by VTOrc, purge stale shards

- go/flags/endtoend/vtorc.txt
- go/vt/vtorc/config/config.go
- go/vt/vtorc/inst/instance_dao.go
This PR migrates the concurrency control for VTOrc's backend to use `golang.org/x/sync/semaphore` and a flag is added to control the limit
> `vtorc`: use `golang.org/x/sync/semaphore`, add flag for db concurrency

- go/vt/vtorc/db/generate_base.go
This PR adds an index for `(hostname, port)` on the VTOrc `database_instance` table to avoid an expensive full table scan caused by `inst.ReadInstanceClusterAttributes` [looking for rows by `hostname` and `port`](https://github.com/slackhq/vitess/blob/main/go/vt/vtorc/inst/instance_dao.go#L488-L491)
In the future I'd like to do something smarter as discussed in https://github.com/vitessio/vitess/pull/17843, but for now this index performs much better than not-having it
-   [x] Did …
> `vtorc`: add index for `inst.ReadInstanceClusterAttributes` table scan

- go/vt/vtgate/schema/tracker.go
- go/vt/vtgate/schema/tracker_test.go
- go/vt/vttablet/sandboxconn/sandboxconn.go
Previously, schema tracking update calls to VTTablet via GetSchema RPC and access to the keyspace-to-update-controller mapping (tracked map) were using the same lock. These operations are unrelated, but GetSchema RPC calls can be slow due to network-related reasons.
As a result, fetching the update controller from the map was blocked, leading to:
- Slow processing of health updates
- Channel overflow, causing dropped health check updates
Introduced a separate mutex for managing access to the tracked map, ensuring that schema tracking operations are not blocked by RPC calls. This prevents delays in processing health updates and improves overall stability.
Backport Reason: Health check misses can lead to missing schema changes.
-   [x] "Backport to:" labels have been added if this change …
> Fix: Separate Lock for Keyspace to Update Controller Mapping in Schema Tracking

- go/vt/vtgate/schema/tracker_test.go
The Test was introduced in PR https://github.com/vitessio/vitess/pull/17873. 
This needs to be backported till v20 to have flaky fixes in all branches.
> Fix TestTrackerNoLock flaky test by increasing time to mark failure

- go/vt/vtgate/vstream_manager.go
- go/vt/vtgate/vstream_manager_test.go
Add more metrics for vstreams on vtgates.
Inspired partially by the [tablet vstream metrics](https://github.com/vitessio/vitess/blob/main/go/vt/vttablet/tabletserver/vstreamer/engine.go#L131-L147). Let me know if you think I should include any others. Once we are decided on the metrics list, I will put out docs PR.
- Fixes: https://github.com/vitessio/vitess/issues/17859
-   [x] Documentation: https://github.com/vitessio/website/pull/1948
> Add more vstream metrics for vstream manager

- go/vt/vtgate/evalengine/expr_bvar.go
- go/vt/vtgate/evalengine/translate_test.go
The evalengine compiler does not operate on arbitrary width types: once
a value is evaluated into the compiler stack, its type is fixed to the
widest possible for the representation (e.g. all signed values are
promoted to INT64, all unsigned values to UINT64, etc).
The BindVariable code was not taking this into account when evaluating
and pushing the value of a bind variable into the evaluation stack. A
bind variable with type INT32 was being pushed into the stack as an
INT64, but it kept its original type when statically typing the rest of
the stack, so it caused bad compilation.
Fixes #17888
-   [x] If this change is to be back-ported to previous releases, a justification is included …
> evalengine: normalize types during compilation

- examples/operator/operator.yaml
- tools/get_kubectl_kind.sh
This PR is a follow-up of the work done in https://github.com/planetscale/vitess-operator/pull/670. The controller tool package was upgraded to a newer version, along with the default K8S version, leading to changes in the example manifest we generate.
> Upgrade `sigs.k8s.io/controller-tools` and `KUBE_VERSION`

- go/cmd/vtbackup/cli/vtbackup.go
- go/flags/endtoend/vtbackup.txt
As described in https://github.com/vitessio/website/issues/1953, the help output of vtbackup is causing readability issues in our documentations. This PR fixes the output generated by vtbackup to be properly formatted in markdown.
A preview of the changes made to the help output can be seen on https://deploy-preview-1952--vitess.netlify.app/docs/22.0/reference/programs/vtbackup/ from PR: https://github.com/vitessio/website/pull/1952
- Part of https://github.com/vitessio/website/issues/1953
> Fix `vtbackup` help output

- go/cmd/vtclient/docgen/main.go
The generation of the CLI documentation for `vtclient` broke after https://github.com/vitessio/vitess/pull/17800. The flags were not initialized correctly, leading to the doc gen to generate an empty list of flags.
This can be tested with
```
$ go run ./go/cmd/vtclient/docgen/main.go
$ less doc/_index.md
```
> Fix how we generate `vtclient` CLI docs

- go/flags/endtoend/vtorc.txt
- go/vt/vtorc/config/config.go
- go/vt/vtorc/discovery/queue.go
- go/vt/vtorc/discovery/queue_test.go
- go/vt/vtorc/logic/vtorc.go
This PR cleans up the VTOrc discover queue code, mainly by removing all locking from `.Consume()`; this was achieved by adding `type queueItem struct` and pushing this to the channel instead, with the key and `time.Time` included. Previously this `time.Time` was stored in a `map` with mutex locks
The `.QueueLen()` now returns just the `len()` of the queue channel. Before this metric would include the length of the channel plus all that are "in processing" _(between `.Consume()` and `.Release()`)_, which I'm unsure is necessary. Simplifying this removed the need for a lock in `.QueueLen()`
Finally, the `--discovery-workers` flag was added to control how many workers consume the discovery queue
Benchmark:
```bash
tvaillancourt@tvailla-ltmawfe vitess % go test -v -bench=. …
```
> `vtorc`: cleanup discover queue, add concurrency flag

- changelog/22.0/22.0.0/summary.md
- go/flags/endtoend/vtcombo.txt
- go/flags/endtoend/vtgate.txt
- go/test/endtoend/vtgate/grpc_api/main_test.go
- go/vt/vtgate/grpcvtgateservice/server.go
This PR enables `grpc-send-session-in-streaming` as `true` by default and mark the flag as deprecated to be removed from future release.
- Follow up from https://github.com/vitessio/vitess/pull/14046
- #17734 
> VTGate: Session in StreamExecute response as default

- go/vt/vttablet/tabletserver/schema/engine.go
- go/vt/vttablet/tabletserver/schema/engine_test.go
This PR addresses a race condition in the Schema Engine related to updating the last changed time. The issue arises because this time is updated by both:
1. A ticker that periodically reloads the schema and updates the timestamp.
1. The VStream tracker process, which also modifies this value.
Logs from CI: 
```
Write at 0x00c0003d87c0 by goroutine 1861:
vitess.io/vitess/go/vt/vttablet/tabletserver/schema.(*Engine).reload()
/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/schema/engine.go:619 +0x28f9
vitess.io/vitess/go/vt/vttablet/tabletserver/schema.(*Engine).ReloadAtEx()
/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/schema/engine.go:393 +0x2a4
vitess.io/vitess/go/vt/vttablet/tabletserver/schema.(*Engine).ReloadAt() …
```
> fix: race on storing schema engine last changed time

- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/401_scheduled_backups.yaml
- examples/operator/operator.yaml
This Pull Request brings the changes made in https://github.com/planetscale/vitess-operator/pull/658 to the Vitess' examples. The operator manifest has changed with the new CRD definition, and the 101 through 306 steps now include a backup location.
> Use `vtbackup` in scheduled backups

- go/vt/vttablet/tabletserver/schema/engine.go
- go/vt/vttablet/tabletserver/schema/engine_test.go
This PR fixes the data race seen in schema engine.
This was caused by making changes in the PR https://github.com/vitessio/vitess/pull/17855 which does not take lock on calling the `reload` method causing multiple data race.
This also reverts a change made in PR to fix partial data race https://github.com/vitessio/vitess/pull/17914
> Fix data race in Schema Engine 

- .github/workflows/update_golang_version.yml
Removed the v19 branch from the golang upgrade CI workflow.
> v19 EOL: Remove v19 from Golang Update Version CI workflow

- go/vt/vttablet/tabletserver/throttle/throttler_test.go
We've seen some flakiness in `TestDormant`. This unit test runs the throttler, issues some checks, then waits a "dormant period" amount of time, then checks the throttler to see that it's dormant. While this passes consistently on local dev envs, it sometimes fails in GitHub CI due to slow runners. There's a potential for a race condition on slow runners, where the throttler is still not fast enough to enter the dormant period. The fix here is to add two "check intervals", which means extra two seconds, before checking that the throttler is dormant. This should be good enough: on one hand should add enough time for the throttler to turn dormant, on the other hand we still don't waste too much test time, and we do validate that the throttler ends up turning dormant (the precise timing is …
> Fix flakiness in throttler's `TestDormant`

- go/vt/vttablet/tabletmanager/rpc_replication_test.go
- go/vt/vttablet/tabletmanager/semisyncmonitor/monitor.go
- go/vt/vttablet/tabletmanager/semisyncmonitor/monitor_test.go
This PR fixes the bug described in https://github.com/vitessio/vitess/issues/17938. The problem of expecting incorrect number of fields has been fixed. There is an e2e test that would have caught this bug when the semi-sync monitor was introduced in #17763, but the test doesn't run on CI and I didn't run it locally after addressing the review comments as part of which I changed the query that the semi-sync monitor was running.
This time I have ensured that the e2e test is now working as expected after the fix.
- Fixes #17938 
- …
> Fix semi-sync monitor bug of expecting incorrect number of fields

- go/vt/schemadiff/capability.go
- go/vt/schemadiff/capability_test.go
Fixes https://github.com/vitessio/vitess/issues/17941, see description in issue.
https://github.com/vitessio/vitess/issues/17941
> `schemadiff`: explicit `ALGORITHM=INSTANT` counts as instant-able

- changelog/22.0/22.0.0/summary.md
- examples/compose/vttablet-up.sh
- go/test/endtoend/recovery/recovery_util.go
- go/test/endtoend/tabletmanager/tablet_health_test.go
- go/test/endtoend/tabletmanager/throttler_topo/throttler_test.go
- go/test/endtoend/vtorc/utils/utils.go
- go/vt/mysqlctl/mysqld.go
This PR deletes the flag deprecated in #14871.
#17734
> Remove deprecated `--disable_active_reparents` flag

- go/vt/vtgate/vtgate.go
- go/vt/vtgate/vtgate_test.go
Right now, `SrvKeyspace` and `SrvVSchema` for a cell are built only if a tablet for that keyspace/shard is deployed into that cell. This breaks migration architectures where you might deploy vtgates in all cells, but unmanaged tablets for the source database in only a subset of cells. What happens when you try to SwitchTraffic is that vtgates in cells without tablets will not be able to route traffic to a primary in a different cell.
In order to workaround this, people have been manually running RebuildKeyspaceGraph and RebuildVSchemaGraph commands.
The proposal is to make this part of vtgate initialization. If a vtgate is deployed in a cell, then it is fair to assume that it is intended to serve traffic. Hence, we can go ahead and build the SrvKeyspace and SrvVSchema for the keyspaces it …
> Rebuild `SrvKeyspace` and `SrvVSchema` during vtgate init if required

- go/mysql/auth_server.go
- go/mysql/auth_server_static.go
- go/mysql/auth_server_static_test.go
- go/mysql/auth_server_test.go
- go/mysql/vault/auth_server_vault.go
This allows for storing already hashed caching sha2 passwords for authentication. This way you can use the new authentication method without needing the password to be in plain text.
Fixes #17947 
> Add support for hashed caching sha2 passwords

- .github/workflows/cluster_endtoend_onlineddl_vrepl.yml
- .github/workflows/cluster_endtoend_onlineddl_vrepl_stress.yml
- .github/workflows/cluster_endtoend_onlineddl_vrepl_stress_suite.yml
- .github/workflows/cluster_endtoend_onlineddl_vrepl_suite.yml
- .github/workflows/cluster_endtoend_vreplication_basic.yml
- .github/workflows/cluster_endtoend_vreplication_migrate.yml
- .github/workflows/cluster_endtoend_vreplication_vtctldclient_vdiff2_movetables_tz.yml
- go/test/endtoend/vreplication/config_test.go
- go/test/endtoend/vreplication/unsharded_init_data.sql
- go/test/endtoend/vreplication/vdiff2_test.go
- go/vt/vttablet/tabletmanager/vdiff/table_differ.go
- test/ci_workflow_gen.go
There was a bug in the code that checks for primary key equivalents where only a single column was expected for a unique key. 
This has been fixed and the failing case added to the vdiff end to end tests.
The core functionality for PKE support was added in v19 in https://github.com/vitessio/vitess/pull/14794 and hence we backport this to supported versions.
fixes https://github.com/vitessio/vitess/issues/17969
-   [ ] Documentation was added or is not …
> VDiff: Fix bug with handling tables with no pks but only a unique key.

- go/vt/vtorc/logic/keyspace_shard_discovery.go
This PR moves to using an `errgroup` in VTOrc's `logic.RefreshAllKeyspacesAndShards()` in order for errors to passed up to the caller, also it feels a bit cleaner
> `vtorc`: use `errgroup` in keyspace/shard discovery

- go/vt/vtorc/logic/keyspace_shard_discovery.go
This PR fixes the recent import error in `keyspace_shard_discovery.go`.
> Fix `sync` import error in keyspace_shard_discovery.go

- go/vt/vtorc/inst/shard_dao.go
- go/vt/vtorc/inst/shard_dao_test.go
- go/vt/vtorc/inst/tablet_dao.go
- go/vt/vtorc/inst/tablet_dao_test.go
- go/vt/vtorc/logic/keyspace_shard_discovery.go
- go/vt/vtorc/logic/tablet_discovery.go
This PR adds stats to VTOrc to measure the number of tablets watched per cell and by keyspace/shard
While implementing this I realized this overlaps the `ShardsWatched` stats I already added in https://github.com/vitessio/vitess/pull/17815, which are now deleted by this PR. No release has occurred since that PR, so I think this is safe. The same metrics can be provided by the new metric `TabletsWatchedByShard`
-   [x] Did the new or modified tests pass consistently locally and on …
> `vtorc`: add tablets watched stats

- go/vt/mysqlctl/mysqlshellbackupengine.go
- go/vt/mysqlctl/mysqlshellbackupengine_test.go
> [release-21.0] fix flaky test on mysqlshell backup engine 

- go/test/endtoend/vtgate/queries/dml/dml_test.go
- go/test/endtoend/vtgate/queries/dml/main_test.go
- go/test/endtoend/vtgate/queries/dml/sharded_schema.sql
- go/test/endtoend/vtgate/queries/dml/vschema.json
The test was previously inserting a duplicate value into a unique vindex column. However, due to a bug, the test was incorrectly passing.
This bug has been fixed in [PR #17974](https://github.com/vitessio/vitess/pull/17974).
To ensure the tests go 🟢 on older releases, we need to update the test setup to use the correct configuration.
> [release-21.0] DML test fix for duplicate column value 

- go/vt/dbconfigs/credentials.go
- go/vt/vttablet/tabletserver/tabletenv/config.go
- go/vt/vttablet/tabletserver/tabletenv/config_test.go
- go/vt/vttablet/tabletserver/tabletenv/data/db_credentials.json
In https://github.com/planetscale/vitess-operator/pull/671 we are starting to use the `--unmanaged` vttablet flag introduced in https://github.com/vitessio/vitess/pull/14871. CI is showing an interesting failure where vttablet expects a password and user to be set via flags. The operator does set the user ([code](https://github.com/planetscale/vitess-operator/blob/08006336ff267678914cb2fac001fc5962f42f47/pkg/operator/vttablet/datastore.go#L115)); but the password is instead stored in a K8S `Secret` object, and is passed down to vttablet via the `--db-credentials-file` flag.
However, with the current implementation, vttablet does not take into account the password stored in `--db-credentials-file` when verifying the unmanaged tablet settings and fail early since we have not set the …
> Allow the use of db credentials when verifying unmanaged tablets config

- web/vtadmin/src/components/routes/Transactions.tsx
This is a UI fix to show distributed transaction participants as comma separated list
- https://github.com/vitessio/vitess/pull/17142
- https://github.com/vitessio/vitess/issues/16245
> vtadmin: display transaction participant list as comma separated

- go/test/endtoend/cluster/cluster_process.go
- go/test/endtoend/cluster/vtadmin_process.go
- go/test/endtoend/vtadmin/main_test.go
- go/vt/vtadmin/cluster/resolver/resolver.go
- go/vt/vtadmin/cluster/resolver/resolver_test.go
vtadmin’s discovery resolver was treating the cluster ID as the URL scheme when dialing vtgate and vtctld, which breaks if the cluster ID contains characters that are not valid in a URI scheme (e.g. `_`). This manifested as vtadmin-api failing to connect to vtgate/vtctld when a cluster ID such as `local_test` was used.
This change introduces a small `sanitizeScheme` helper in the vtadmin cluster resolver to strip or replace invalid characters and ensure the scheme starts with a letter. The resolver now keeps the original cluster ID around for logging/debugging but advertises the sanitized scheme to gRPC. vtctldclient and vtsql continue to use the original cluster ID.
To exercise this path an end‐to‐end vtadmin test now overrides its cluster ID to `local_test`, and a unit test was added to …
> vtadmin: allow cluster IDs with underscores by sanitizing resolver scheme

- go/vt/vtgate/planbuilder/operators/query_planning.go
- go/vt/vtgate/planbuilder/testdata/select_cases.json
This prevents the query planner from breaking up joins that can be passed through to a specific shard.
Fixes: https://github.com/vitessio/vitess/issues/17867
> Pass through predicates when trying to merge apply join.

- .github/workflows/cluster_endtoend_onlineddl_vrepl.yml
- .github/workflows/cluster_endtoend_onlineddl_vrepl_stress.yml
- .github/workflows/cluster_endtoend_onlineddl_vrepl_stress_suite.yml
- .github/workflows/cluster_endtoend_onlineddl_vrepl_suite.yml
- .github/workflows/cluster_endtoend_vreplication_basic.yml
- .github/workflows/cluster_endtoend_vreplication_migrate.yml
- .github/workflows/cluster_endtoend_vreplication_vtctldclient_vdiff2_movetables_tz.yml
- test/ci_workflow_gen.go
This (mostly) completes the migration of runners to the CNCF-hosted ones. 
There will still be one test (One of the race tests) that will remain on GH-Hosted. After KubeCon there will be similar PRs to handle re-naming the workers so the OS/Version are explicit. :) 
Prior PRs for context:
https://github.com/vitessio/vitess/pull/17879
https://github.com/vitessio/vitess/pull/17943
> re-replace most runners with the cncf-hosted runners

- go/vt/vtgate/planbuilder/operators/rewriters.go
- go/vt/vtgate/planbuilder/operators/route.go
- go/vt/vtgate/planbuilder/operators/route_planning.go
- go/vt/vtgate/planbuilder/testdata/mirror_cases.json
- go/vt/vtgate/planbuilder/testdata/vschemas/mirror_schema.json
- go/vt/vtgate/semantics/table_collector.go
Traffic mirroring is currently broken because it is not properly taking routing rules into account. This impacts `release-21.0`, thus backporting the fix to that branch.
There are two flaws, given the mirror rules and routing rules further down:
* When querying from `commerce.corder`, we seed operators with mirror source `commerce.corder` and mirror target `customer.corder`. That's good, but then later in planning we replace the mirror target with its routing rule destination `commerce.corder`. This results in mirroring back to `commerce.corder`.
* When querying from `corder` or `customer.corder`, we seed only from mirror source `commerce.corder`. This results in no mirroring.
*Mirror rules*
```json
{
"rules": [
{
"from_table": "commerce.corder@replica",
"to_table": "customer.corder", …
```
> go/vt/vtgate: take routing rules into account for traffic mirroring

- go/vt/vtgate/engine/route.go
- go/vt/vtgate/engine/route_test.go
Vitess always attempts to push sorting down to the underlying MySQL instances. When querying a single MySQL shard, the results returned are already sorted, eliminating the need for additional sorting at the vtgate level.
Previously, we determined whether vtgate-side sorting was needed based on the opcode. This PR simplifies the logic by checking at runtime how many shards are being queried, performing sorting at vtgate only when multiple shards are involved.
Closes #17997
-   [x] Did the new or modified tests pass consistently …
> Only sort when receiving results from multiple shards

- go/test/endtoend/vtorc/utils/utils.go
After the changes in https://github.com/vitessio/vitess/pull/17870, there are 2 tables that store the tablet type, and that affects the function checking for drained tablets count, making that test flaky. This PR fixes the check post those changes.
> Fix flakiness in checking for drained tablets in Vtorc test

- tools/get_next_release.sh
- tools/get_previous_release.sh
This PR reworks the way we run upgrade downgrade tests. Instead of running the upgrade-downgrade tests against the previous tagged release, we run them against the release branch.
The added advantage of this approach is that if we have a broken test, we can fix the test and not need a patch release just to get upgrade downgrade tests to take that change into account. 
> Use release branches for upgrade downgrade tests

- go/vt/vtorc/inst/analysis_dao.go
- go/vt/vtorc/inst/analysis_dao_test.go
- go/vt/vtorc/test/recovery_analysis.go
This PR fixes the issue described in https://github.com/vitessio/vitess/issues/18031 by augmenting the check for primary tablet mismatch to also take into account that the field can be empty and set to unknown.
- Fixes  https://github.com/vitessio/vitess/issues/18031
> Take into account the tablet type not being set while checking for primary tablet mismatch recovery

- go/test/endtoend/vtgate/queries/timeout/timeout_test.go
This PR increases the query timeout for `TestQueryTimeoutWithShardTargeting` to prevent flakiness caused by slow runners.
> Test: Increase query timeout to fix flaky test 'TestQueryTimeoutWithShardTargeting'

- go/test/endtoend/vtgate/queries/misc/misc_test.go
- go/vt/vtgate/engine/join.go
While working on other, unrelated issues, we noticed that outer joins where sometimes returning too few rows when run in OLAP.
This fix makes sure we return the same rows as MySQL.
Fixes #18041
> Bugfix: Missing data when running vtgate outer joins

- test/ci_workflow_gen.go
- test/templates/cluster_endtoend_test.tpl
- test/templates/cluster_endtoend_test_docker.tpl
- test/templates/cluster_endtoend_test_mysql57.tpl
- test/templates/cluster_vitess_tester.tpl
- test/templates/unit_test.tpl
This PR adds support for setting `GOPRIVATE` and setting a GitHub Access Token (PAT) in the templated CI job files
This is useful for users with private repo dependencies in their `go.mod`, for example a custom Durability Policy. The `git config ...insteadOf` method used is what the Go project FAQs recommend for users with a private golang dependency
This feature is disabled by default but can be enabled by defining `const goPrivate = ""`. When this is enabled the following diff to CI files will occur after `make generate_ci_workflows`:
```bash
diff --git a/.github/workflows/cluster_endtoend_ers_prs_newfeatures_heavy.yml b/.github/workflows/cluster_endtoend_ers_prs_newfeatures_heavy.yml
index ef256dd83a..b151bd0aad 100644
--- a/.github/workflows/cluster_endtoend_ers_prs_newfeatures_heavy.y …
```
> Add support for `GOPRIVATE` in CI templates

- changelog/22.0/22.0.0/summary.md
This PR prepares the release notes summary ahead of the `v22.0.0` code freeze. No major modification to the content itself,  besides the addition to the document of some metrics that were added in `v22` and not added to the notes. Otherwise, it is mostly some reorganization to make them cleaner and more readable.
- Part of #17898
> Reorganize the `v22.0.0` release notes

- go/vt/vttablet/endtoend/misc_test.go
- go/vt/vttablet/tabletserver/schema/engine.go
Fixes a bug where table size computation over a partitioned table only evaluates the size of the first partition, instead of the sum sizes of all partitions.
See https://github.com/vitessio/vitess/issues/18057 for details.
I refactored a block of code into its own function. But to clarify, this is the only change that was done. From:
```golang
if _, ok := innodbTablesStats[originalTableName]; !ok {
innodbTablesStats[originalTableName] = &Table{}
originalTable := innodbTablesStats[originalTableName]
originalTable.FileSize += fileSize
originalTable.AllocatedSize += allocatedSize
}
```
to:
```golang
if _, ok := innodbTablesStats[originalTableName]; !ok {
innodbTablesStats[originalTableName] = &Table{}
}
originalTable := innodbTablesStats[originalTableName]
originalTable.FileSize += fileSize …
```
> `engine.Reload()`: fix file size aggregation for partitioned tables

- go/tools/asthelpergen/integration/ast_path.go
- go/tools/asthelpergen/integration/ast_rewrite.go
- go/tools/asthelpergen/integration/integration_visit_test.go
- go/tools/asthelpergen/paths_gen.go
- go/tools/asthelpergen/rewrite_gen.go
- go/vt/sqlparser/ast_path.go
- go/vt/sqlparser/ast_rewrite.go
Adds infrastructure to be able to keep track of paths even when using the Visitable interface.
> Make it possible to use paths with Visitable nodes

- examples/operator/operator.yaml
This PR is a follow-up of https://github.com/planetscale/vitess-operator/pull/676, where I am porting the changes made to the default operator.yaml file we provide.
The orignal PR allows end-users to define a rolling update strategy for the vtgate deployment.
> Add deployment strategy to vtgate in `operator.yaml`

- web/vtadmin/src/components/routes/shard/Advanced.tsx
Added hostname alongside tablet Id on VTAdmin tablet selection drop-downs
- using a different text style for the hostname to improve readability
- displaying 'Unknown' when the hostname is missing 
Fixes #17954 
> VTAdmin: Show Hostname Alongside Tablet ID on tablet selection drop-downs

- go/vt/vttablet/tabletserver/schema/engine.go
- go/vt/vttablet/tabletserver/schema/engine_test.go
- go/vt/vttablet/tabletserver/schema/load_table.go
- go/vt/vttablet/tabletserver/schema/load_table_test.go
During schema refresh, Vitess loads field information by executing an impossible query (SELECT * FROM <table_name> WHERE 1 != 1), which is used by other components.
However, this information is irrelevant for views, as it is not consumed by any part of Vitess.
This PR skips the execution of this query for views, improving schema reload time, especially for complex views that take longer to process. By avoiding unnecessary queries, it optimizes the performance of the schema engine.
- Fixes https://github.com/vitessio/vitess/issues/18051
-   [ ] Tests were added or are not …
> Skip Field Query for Views During Schema Refresh to Improve Reload Time

- go/vt/vttablet/tabletmanager/vdiff/table_differ.go
- go/vt/vttablet/tabletmanager/vdiff/workflow_differ.go
- go/vt/vttablet/tabletmanager/vdiff/workflow_differ_test.go
This PR fixes the logic in vdiff that looks at extra source and target rows, if they are found, and checks to see if there are identical rows. This can happen if there is an issue in sorting the rows usually because of different collations on the source and target.  If matches are found, it removes them from the extra rows slices. 
This is a long standing issue, so backporting to supported versions.
Fixes https://github.com/vitessio/vitess/issues/18061
- …
> VDiff: Fix logic for reconciling extra rows

- go/vt/vtctl/reparentutil/util.go
- go/vt/vtctl/reparentutil/util_test.go
While working on https://github.com/vitessio/vitess/pull/18002, @deepthi mentioned that in the codebase we could have other instances where we ignore the fact that a tablet can have an unknown replication lag.
After looking through the code, the new primary election code in vtctld does not take into account `NULL` replication lag. With the current code, a replica that has an unknown replication lag but is the most advanced can become primary-elect. Since the tablet's replication lag (`status.ReplicationLagSeconds`) is set to 0 when it is unknown, it can be mistaken by "this tablet has no replication lag". 
This PR addresses this by filtering out tablets that have an unknown replication lag.
> Filter out tablets with unknown replication lag when electing a new primary

- go/vt/srvtopo/fakesrvtopo/fakesrvtopo.go
- go/vt/srvtopo/resolver.go
- go/vt/vtgate/executor.go
- go/vt/vtgate/executor_test.go
This PR fixes the issue described in https://github.com/vitessio/vitess/issues/18068. `SHOW VITESS_SHARDS` was ignoring the error from the underlying resilient query in the srvtopo server. This is incorrect and we should only ignore the error coming because of empty results. This PR fixes this problem after having introduced tests to ascertain it.
- Fixes https://github.com/vitessio/vitess/issues/18068
> Fix `SHOW VITESS_SHARDS` bug that led to incomplete output

- go/cmd/vtctldclient/command/vreplication/reshard/reshard.go
- go/test/endtoend/vreplication/vreplication_vtctldclient_cli_test.go
- go/vt/vtctl/workflow/server.go
- go/vt/vtctl/workflow/traffic_switcher.go
This fixes two issues with the `Reshard Cancel` command.
First, it exposes the `--keep-data` flag, so that the user can manage on whether copied data should be kept or thrown away when the workflow is cancelled.
Next, it changes the `Cancel` command so that instead of dropping the shards from the topology, we keep the shards in the topology but drop the created tables instead. This way, the shards will be reset to the same state they were in before the `Reshard` operation was started.
Fixes: #17965  …
> Fix `Reshard Cancel` behavior

- go/vt/dbconnpool/connection_pool.go
- go/vt/vttablet/endtoend/config_test.go
The App pool and Dba pool metrics got removed by https://github.com/vitessio/vitess/pull/14034
This PR adds them back.
- Fixes https://github.com/vitessio/vitess/issues/17957
> fix: App and Dba Pool metrics

- go/vt/vtorc/logic/tablet_discovery.go
- go/vt/vtorc/logic/topology_recovery.go
- go/vt/vtorc/logic/vtorc.go
- go/vt/vtorc/logic/vtorc_test.go
This PR adds stats to shard locks and `DiscoverInstance` in VTOrc 
Also `logic.LockShard(...)` was moved to `go/vt/vtorc/logic/topology_recovery.go` because it's not related to tablet discovery and is only called in `topology_recovery.go`
> `vtorc`: add stats to shard locks and instance discovery

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to update the SNAPSHOT version (v23.0.0-SNAPSHOT) after the release of v22.0.0-RC1.
> Bump to `v23.0.0-SNAPSHOT` after the `v22.0.0-RC1` release

- go/test/endtoend/preparestmt/stmt_methods_test.go
- go/test/vschemawrapper/vschema_wrapper.go
- go/vt/vtexplain/vtexplain_vtgate.go
- go/vt/vtgate/engine/fake_vcursor_test.go
- go/vt/vtgate/engine/metrics.go
- go/vt/vtgate/engine/plan_switcher.go
- go/vt/vtgate/engine/plan_switcher_test.go
- go/vt/vtgate/engine/primitive.go
- go/vt/vtgate/executor.go
- go/vt/vtgate/executor_framework_test.go
- go/vt/vtgate/executor_plan_test.go
- go/vt/vtgate/executor_test.go
- go/vt/vtgate/executorcontext/vcursor_impl.go
- go/vt/vtgate/executorcontext/vcursor_impl_test.go
This PR introduces a new metric to track the execution of Deferred Optimization in Vitess. Deferred Optimization enhances query planning by generating a more efficient plan during the first execution of a prepared statement.
The new metric helps monitor how often queries leverage this feature, providing insights into its impact.
- https://github.com/vitessio/vitess/pull/17992
- https://github.com/vitessio/vitess/issues/17840
> Add Deferred Optimization Execution Metric

- go/vt/vtgate/planbuilder/operators/plan_query.go
- go/vt/vtgate/planbuilder/testdata/select_cases.json
- go/vt/vtgate/semantics/analyzer.go
- go/vt/vtgate/semantics/binder.go
- go/vt/vtgate/semantics/check_invalid.go
- go/vt/vtgate/semantics/semantic_table.go
We were failing these queries if they were running against a sharded keyspace. We can lighten this limitation slightly, and allow these queries to execute if they can be planned into a single shard query.
Fixes https://github.com/vitessio/vitess/issues/18070
> bugfix: allow window functions when possible to push down

- misc/git/hooks/golangci-lint
The output for golang-ci-lint can be of 2 variants - 
```
golangci-lint has version 2.0.2 built with go1.24.1 from 2b224c2c on 2025-03-25T21:36:18Z
```
and 
```
golangci-lint has version v2.0.2 built with go1.24.1 from 2b224c2c on 2025-03-25T21:36:18Z
```
The script for golang-ci lint doesn't allow for the first variant. This PR fixes that by making the `v` optional.
> Fix golang-ci lint file to allow a version without preceding `v`

- go/vt/vtctl/grpcvtctldserver/server.go
- go/vt/vtctl/grpcvtctldserver/server_test.go
This PR fixes the issue described in #18113. Once the bug was found and a test was written to reproduce it, the fix was quite easy. We just need to start processing the resutls and consume them before we start writing to it. This way the writers can never be indefinitely blocked, because we will always have an active reader.
- Fixes #18113
> Fix deadlock in `ValidateKeyspace`

- go/cmd/vtctldclient/command/backups.go
This fixes an issue where the wrong variable was updated with the flag which was copy pasted originally but no replaced.
https://github.com/vitessio/vitess/pull/17923 fixed this on `main` and `release-22.0`, but that wasn't backported.
This backports only the fixed copy paste.
Fixes https://github.com/vitessio/vitess/issues/18045
> Fix backup shard copy paste error

- changelog/23.0/23.0.0/summary.md
- config/mycnf/mysql8026.cnf
- config/mycnf/mysql84.cnf
After #18033 added forward compatibility in the upcoming v22, we can make it the default in v23. 
Part of #17966
> Switch to using the default caching sha2 password

- go/test/endtoend/vtgate/queries/dml/dml_test.go
- go/test/endtoend/vtgate/queries/dml/main_test.go
- go/test/endtoend/vtgate/queries/dml/sharded_schema.sql
- go/test/endtoend/vtgate/queries/dml/vschema.json
This is a backport of https://github.com/vitessio/vitess/pull/17980
> [release-19.0] DML test fix for duplicate column value

- changelog/22.0/22.0.0/changelog.md
- changelog/22.0/22.0.0/release_notes.md
- changelog/22.0/README.md
This Pull Request copies the release notes found on `release-22.0` to keep release notes up-to-date after the `v22.0.0-RC1` release.
> [main] Copy `v22.0.0-RC1` release notes

- go/vt/vtgate/grpcvtgateservice/server.go
- go/vt/vtgate/vstream_manager.go
This PR adds extra log lines to try to localize where we are getting the frequent EOF errors we are seeing in a cluster.
- Fixes #18125
> VStream API: add additional log lines for debugging frequent eof errors during catchup

- changelog/20.0/20.0.7/changelog.md
- changelog/20.0/20.0.7/release_notes.md
- changelog/20.0/README.md
This Pull Request copies the release notes found on `release-20.0` to keep release notes up-to-date after the `v20.0.7` release.
> This Pull Request is part of https://github.com/vitessio/vitess/issues/18130
> [main] Copy `v20.0.7` release notes

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v21.0.5-SNAPSHOT) after the release of v21.0.4.
> This Pull Request is part of https://github.com/vitessio/vitess/issues/18129
> [release-21.0] Bump to `v21.0.5-SNAPSHOT` after the `v21.0.4` release

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v22.0.0-SNAPSHOT) after the release of v22.0.0-RC1.
> [release-22.0] Bump to `v22.0.0-SNAPSHOT` after the `v22.0.0-RC1` release

- go/test/endtoend/preparestmt/stmt_methods_test.go
- go/vt/vtgate/executor.go
- go/vt/vtgate/executor_select_test.go
This change allows Prepare to succeed even when the query plan cannot be fully constructed during prepare time—such as in cases involving constructs like correlated subqueries or complex union cases with derived tables. Instead of failing, Vitess now returns default field metadata with NULL_TYPE for unsupported expressions.
This enables applications to prepare statements upfront and execute them later with actual parameter values. During execution, Vitess can then use those values to generate optimized plans, potentially making previously unsupported queries fully supported at execution time.
- https://github.com/vitessio/vitess/issues/17840
-   [x] Documentation was …
> feat: support prepare even on plan failure to generate optimized plan on execution with values

- go/test/endtoend/vtgate/queries/misc/misc_test.go
- go/vt/vtgate/engine/plan.go
- go/vt/vtgate/executor.go
- go/vt/vtgate/executor_test.go
The bug https://github.com/vitessio/vitess/pull/18076 was tracked down to the plan key missing the tablet type information. This causes the vtgate to reuse the incorrect plan.
- Fixes https://github.com/vitessio/vitess/pull/18076
> Fix: Add tablet type to the plan key

- changelog/22.0/22.0.0/summary.md
This PR adds the summary note changes for unsharded support of `CREATE PROCEDURE`.
> Add summary note change for unsharded `create procedure` support

- go/test/endtoend/vtgate/queries/dml/dml_test.go
This test is asserting that we are doing the wrong thing. Let's skip it until we have backported the [fix](https://github.com/vitessio/vitess/pull/18151).
Fix on main: https://github.com/vitessio/vitess/pull/18151
> Skip end-to-end test

- go/test/endtoend/vtgate/queries/dml/dml_test.go
- go/test/endtoend/vtgate/queries/dml/insert_test.go
- go/test/endtoend/vtgate/queries/dml/sharded_schema.sql
- go/test/endtoend/vtgate/queries/dml/vschema.json
- go/vt/vtgate/engine/insert_common.go
vtgate was failing to insert to the base table when one of the vindexes reported it had ignored a row.
Fixes #17979
> bugfix: INSERT IGNORE not inserting rows

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v20.0.8-SNAPSHOT) after the release of v20.0.7.
> This Pull Request is part of https://github.com/vitessio/vitess/issues/18130
> [release-20.0] Bump to `v20.0.8-SNAPSHOT` after the `v20.0.7` release

- go/vt/proto/tabletmanagerdata/tabletmanagerdata.pb.go
- go/vt/proto/tabletmanagerdata/tabletmanagerdata_vtproto.pb.go
- go/vt/proto/tabletmanagerservice/tabletmanagerservice.pb.go
- go/vt/proto/tabletmanagerservice/tabletmanagerservice_grpc.pb.go
- go/vt/vtcombo/tablet_map.go
- go/vt/vtctl/workflow/framework_test.go
- go/vt/vtctl/workflow/sequences.go
- go/vt/vtctl/workflow/sequences_test.go
- go/vt/vttablet/faketmclient/fake_client.go
- go/vt/vttablet/grpctmclient/client.go
- go/vt/vttablet/grpctmserver/server.go
- go/vt/vttablet/tabletmanager/rpc_agent.go
- go/vt/vttablet/tabletmanager/rpc_vreplication.go
- go/vt/vttablet/tmclient/rpc_client_api.go
- go/vt/vttablet/tmrpctest/test_tm_rpc.go
- proto/tabletmanagerdata.proto
- proto/tabletmanagerservice.proto
- web/vtadmin/src/proto/vtadmin.d.ts
This PR adds 2 TMC RPCs:
- `GetMaxValueForSequences` : Gets the max used sequence value mapped with the provided backing sequence tables.
- `UpdateSequenceTables`: Updates all the sequence tables listed in the request, with the max value provided in the sequence metadata.
Instead of separate RPC calls for each table per shard, these 2 RPCs allow it to reduce to just 1 RPC call (all tables at once) per shard for fetching and updating max sequence value each.
- #17871
-   [ ] Did the new or modified tests pass consistently locally …
> Add TMC RPCs for updating sequences for `switchwrites`

- go/test/endtoend/vtgate/queries/misc/misc_test.go
- go/vt/vtgate/evalengine/translate_simplify.go
- go/vt/vtgate/planbuilder/testdata/from_cases.json
This PR fixes the tuple simplifier, ensuring that multi-column results remain as TupleExpr rather than being wrapped in a single Literal.
- Fixes https://github.com/vitessio/vitess/issues/18217
> fix: Preserve multi-column TupleExpr in tuple simplifier

- go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
- go/vt/vttablet/onlineddl/executor.go
Fixes https://github.com/vitessio/vitess/issues/17944
This PR introduces query buffering and forced query/transaction termination for special plan operations, which at this time include `INSTANT` DDL and range partition rotation.
- When a migration is deemed eligible to run as a "special operation" (is instant-able and `--prefer-instant-ddl` strategy flag is supplied, or is found to be a range partition rotation change)
- We now apply query buffering around the actual change
- In addition, if `--force-cut-over-duration` flag is nonzero, and irrespective of its value, we also issue a one time termination for queries and transactions holding locks or metadata locks on the migrated table, just before issuing the `ALTER TABLE` statement.
In the future we may also consider terminating …
> Query buffering, terminating blocking transactions for `INSTANT` DDL and other "special plans"

- go/vt/vttablet/tabletmanager/vreplication/vcopier.go
Prevent tablet crash by recovering panic in `vcopierCopyTaskResultHooks.sendTo`, also log the error in case there's a panic. This panic occurs if a callback added in `copyAll` tries to send a result to `resultCh` after the channel has been closed (since `copyAll` defers `close(resultCh)`). This can possibly occur if the context exceeds its deadline.
> Recover panic in vcopier due to closed channel

- go/test/endtoend/vtgate/queries/timeout/timeout_test.go
This PR fixes the test flake in `TestQueryTimeoutWithShardTargeting`
> test: TestQueryTimeoutWithShardTargeting fix flaky test

- go/vt/vtgate/planbuilder/operators/route_planning.go
- go/vt/vtgate/planbuilder/testdata/select_cases.json
This PR restores subquery merging behavior that was unintentionally broken by #11379, undoing the regression that reintroduced suboptimal query planning previously addressed in #10966.
Given a query like:
```sql
SELECT music.id
FROM music
WHERE music.id IN (
SELECT MAX(music.id)
FROM music
WHERE music.user_id IN (5, 6)
GROUP BY music.user_id
)
```
We expect the planner to merge the subquery and send at most one query per shard based on the `music.user_id IN (5, 6)` condition. Currently, however, the planner fails to do this and ends up sending multiple queries per shard.
Curiously, wrapping the subquery in a derived table works as expected:
```sql
SELECT music.id
FROM music
WHERE music.id IN (
SELECT * FROM (
SELECT MAX(music.id)
FROM music
WHERE music.user_id IN (5, 6)
GROUP BY …
```
> Fix subquery merging regression introduced in #11379

- go/test/endtoend/vreplication/vstream_test.go
- go/vt/proto/binlogdata/binlogdata.pb.go
- go/vt/proto/binlogdata/binlogdata_vtproto.pb.go
- go/vt/proto/vtgate/vtgate.pb.go
- go/vt/proto/vtgate/vtgate_vtproto.pb.go
- go/vt/vtgate/vstream_manager.go
- go/vt/vttablet/tabletserver/vstreamer/uvstreamer.go
- proto/binlogdata.proto
- proto/vtgate.proto
- web/vtadmin/src/proto/vtadmin.d.ts
This PR adds an optional `TablesToCopy` option/flag in `VStreamOptions`/`VStreamFlag` to add support for copying only specific tables in copy phase. We just add only mentioned tables to the `tablePlan` (which is used to specify the tables to be copied) in `uvstreamer`. If no tables are specified or `TablesToCopy` flag is `nil`, we follow the default behaviour of copying all tables.
Fixes #18160
> VStream: Add flag to support copying only specific tables

- go/vt/vttablet/tabletmanager/semisyncmonitor/monitor.go
- go/vt/vttablet/tabletmanager/semisyncmonitor/monitor_test.go
This PR fixes the deadlock described in https://github.com/vitessio/vitess/issues/18275. As the issue stated, the deadlock happens because we hold the mutex `mu` when closing the timer. We should prevent this because, the keephouse function (`checkAndFixSemiSyncBlocked`) also acquires that mutex.
This PR fixes this. In order to prevent acquiring the `mu` mutex but still guaranteeing that only one of Close and Open runs at a point in time, we had to introduce another mutex just for this purpose. A test has also been added that initially verified that the deadlock exists, and now verifies that the fix in this PR resolves the deadlock.
- Fixes #18275  …
> Fix deadlock in semi-sync monitor

- go/test/endtoend/vtgate/unsharded/main_test.go
- go/vt/sqlparser/ast.go
- go/vt/sqlparser/ast_equals.go
- go/vt/sqlparser/ast_format.go
- go/vt/sqlparser/ast_format_fast.go
- go/vt/sqlparser/cached_size.go
- go/vt/sqlparser/constants.go
- go/vt/sqlparser/normalizer.go
- go/vt/sqlparser/normalizer_test.go
- go/vt/sqlparser/parse_test.go
- go/vt/sqlparser/sql.go
- go/vt/sqlparser/sql.y
- go/vt/vtgate/planbuilder/testdata/ddl_cases.json
As stated in https://github.com/vitessio/vitess/issues/18278, when we added support for create procedures in https://github.com/vitessio/vitess/pull/17946, we made a couple of mistakes - 
1. `SET y = 4` statements get converted to `SET @@y = 4` which is incorrect. This was happening in the normalisation step of the planner. This has been fixed in this PR by skipping the entire normalisation step for create procedure statements.
2. `START TRANSACTION` statements get converted to `BEGIN` which eventually throw a parsing error. In a stored procedure a `BEGIN` statement is considered part of a `BEGIN...END` statement, so we need to preserve `START TRANSACTION` statements as is, and not change them to `BEGIN`. This is done by storing a new field in the AST to preserve the original type of the …
> Fix `SET` and `START TRANSACTION` in create procedure statements

- changelog/23.0/23.0.0/summary.md
- go/vt/vtgate/executor.go
- go/vt/vtgate/tx_conn.go
- go/vt/vtgate/tx_conn_test.go
This PR introduces a new counter metric `TransactionsProcessed` to VTGate to track the number of transactions processed, categorized by:
* Shard distribution: single or cross
* Transaction type: read only or read write
- Closes https://github.com/vitessio/vitess/issues/17585
> Add TransactionsProcessed metric to track transactions at VTGate

- go/vt/sqlparser/normalizer.go
- go/vt/sqlparser/normalizer_test.go
- go/vt/vtgate/executor_select_test.go
- go/vt/vtgate/planbuilder/operators/route_planning.go
- go/vt/vtgate/planbuilder/operators/union_merging.go
- go/vt/vtgate/planbuilder/testdata/select_cases.json
This PR adds two "naive" improvements to allow `UNION` queries to be merged in more cases.
The first change allows `UNION` subqueries that use `IN` conditions to be merged together correctly. It only works if tuples on the two subqueries we try to merge match exactly (same elements in the exact same order), or the tuple was normalized to the same bind variable (see the change below). This could be improved upon by doing a true "set" comparison (so that the order of values and duplicates don't affect the merge result).
~This probably should also be extended to allow merging queries where one side uses `foobar IN (1)` and the other side uses `foobar = 1`.~ Merging `foobar IN (1)` with `foobar = 1` already works, so I just added a test case to make sure it's covered.
~This change is …
> Improve `UNION` query merging

- go/vt/vtctl/workflow/materializer_test.go
- go/vt/vtgate/schema/tracker_test.go
This PR tries to fix flaky test.
- `TestTrackerNoLock` - increased test timeout.
- `TestCreateLookupVindexMultipleCreate` - changes regex to pass with basic check.
> flaky test fix TestTrackerNoLock and TestCreateLookupVindexMultipleCreate

- go/test/endtoend/preparestmt/stmt_methods_test.go
- go/test/endtoend/vtgate/queries/timeout/timeout_test.go
- go/vt/vtgate/engine/delete.go
- go/vt/vtgate/engine/update.go
- go/vt/vtgate/planbuilder/operator_transformers.go
- go/vt/vtgate/planbuilder/testdata/dml_cases.json
This PR fixes the issue with DML query (update / delete) generating None opcode.
- Fixes https://github.com/vitessio/vitess/issues/18271
> fix: handle dml query for None opcode

- go/vt/vtgate/planbuilder/operators/SQL_builder.go
- go/vt/vtgate/planbuilder/testdata/union_cases.json
Make sure to not miss LIMIT/OFFSET when merging UNION queries
Fixes #18360
> fix: keep LIMIT/OFFSET even when merging UNION queries

- go/vt/vttablet/tabletmanager/semisyncmonitor/monitor.go
It was noticed in the CI, that the test `TestDeadlockOnClose` was failing. We had added logs to print the stack traces to see what was going on, and now we have found the issue.
The problem was as follows - 
1. SemiSyncMonitor triggers a `write` operation after finding semi-sync is blocked. This write gets a connection and does a write.
2. Before the monitor can change the state of the monitor in `setIsBlocked`, the monitor is closed. This causes it to acquire the mutex and try and close the appPool.
3. This however creates a deadlock because the appPool can't close until the capacity reaches 0, and that won't happen because an active connection (held in the write method), hasn't yet been recycled, and that thread is blocked on trying to acquire the mutex in `setIsBlocked`.
The fix is …
> Fix: Deadlock in `Close` and `write` in semi-sync monitor.

- changelog/22.0/22.0.1/changelog.md
- changelog/22.0/22.0.1/release_notes.md
- changelog/22.0/README.md
This Pull Request copies the release notes found on `release-22.0` to keep release notes up-to-date after the `v22.0.1` release.
> [main] Copy `v22.0.1` release notes

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v21.0.6-SNAPSHOT) after the release of v21.0.5.
> [release-21.0] Bump to `v21.0.6-SNAPSHOT` after the `v21.0.5` release

- changelog/21.0/21.0.5/changelog.md
- changelog/21.0/21.0.5/release_notes.md
- changelog/21.0/README.md
This Pull Request copies the release notes found on `release-21.0` to keep release notes up-to-date after the `v21.0.5` release.
> [main] Copy `v21.0.5` release notes

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v20.0.9-SNAPSHOT) after the release of v20.0.8.
> [release-20.0] Bump to `v20.0.9-SNAPSHOT` after the `v20.0.8` release

- changelog/20.0/20.0.8/changelog.md
- changelog/20.0/20.0.8/release_notes.md
- changelog/20.0/README.md
This Pull Request copies the release notes found on `release-20.0` to keep release notes up-to-date after the `v20.0.8` release.
> [main] Copy `v20.0.8` release notes

- go/vt/topo/etcd2topo/file.go
- go/vt/topo/etcd2topo/server.go
- go/vt/topo/etcd2topo/server_test.go
- go/vt/topo/etcd2topo/watch.go
Fixes an issue during VTGate shutdown where `s.cli` is set to `nil` in `Close()` method while concurrent coroutines still try to access it, causing nil pointer dereference panics.
This fix replaces a panic (which crashes the process) with a graceful shutdown signal (which components handle cleanly). The error becomes part of the normal shutdown flow, not a failure condition.
Fixes #18350.
None.
> Make sure to check if the server is closed in etcd2topo

- go/vt/vttablet/tabletserver/vstreamer/rowstreamer.go
- go/vt/vttablet/tabletserver/vstreamer/rowstreamer_test.go
_This PR implements the fix for the bug mentioned #18391_ 
TL;DR
VStreamRows uses a broken heartbeat mechanism that only sends one heartbeat and then exits. In contrast, VStream (used in normal binlog replication) sends heartbeats continuously. This PR fixes the issue by introducing a proper loop in the rowstreamer.go heartbeat goroutine to ensure heartbeats are sent throughout the copy phase. 
We found this out because Some of our long-running schema changes failed due to missing heartbeats during the copy phase of VReplication. 
**This is already patched in our internal fork of vitess and has been tested to work correctly for all the failing cases we saw.**
We've identified a **critical architectural inconsistency** in Vitess VReplication that explains this seemingly contradictory …
> [Bugfix] Broken Heartbeat system in Row Streamer

- go/vt/vtgate/planbuilder/operators/horizon.go
- go/vt/vtgate/planbuilder/operators/route.go
- go/vt/vtgate/planbuilder/operators/union.go
- go/vt/vtgate/planbuilder/testdata/cte_cases.json
- go/vt/vtgate/planbuilder/testdata/large_union_cases.json
- go/vt/vtgate/planbuilder/testdata/select_cases.json
- go/vt/vtgate/planbuilder/testdata/union_cases.json
Until now we always wrapped a `UNION … ORDER BY` (or anything else that required weight_string() in UNIONs) in a derived table, which in turn forced MySQL to materialise the result set in a-temp table.  This patch keeps the fast path fast: we first attempt to plan the query without introducing a derived table, stitching the weight_string() expressions directly onto the UNION outputs.
If that optimistic plan hits an unsupported edge-case we gracefully fall back to the old, safe “derived table” strategy.  Nothing breaks, but common cases get a leaner plan.
Improves #18081
- …
> avoid derived tables for UNION when possible

- go/tools/asthelpergen/asthelpergen.go
- go/tools/asthelpergen/clone_gen.go
- go/tools/asthelpergen/design.md
- go/tools/asthelpergen/equals_gen.go
- go/tools/asthelpergen/rewrite_gen.go
Adds a design doc to the asthelpergen package, and does small refactorings cleaning up code to make it easier to read and work with
> asthelpergen: add design documentation

- config/embed.go
- config/mycnf/mysql90.cnf
- go/mysql/flavor.go
- go/mysql/flavor_mysql.go
- go/mysql/flavor_mysql_test.go
- go/mysql/flavor_test.go
- go/vt/mysqlctl/mysqld.go
- go/vt/mysqlctl/mysqld_test.go
Part of implementing https://github.com/vitessio/vitess/issues/17966
_This is already backported to our internal fork and runs correctly for all the UTs we were having issues with._
TL;DR
Vitess currently treats MySQL 9.x versions as 5.7 due to missing version handling in flavor.go.
This leads to a lot of tests not running on local and hence hampering developer experience. [ I myself ran into this while writing UT for  -- https://github.com/vitessio/vitess/pull/18390 ]
This PR updates the getFlavor logic to handle MySQL 9.x by mapping it to the existing MySQL 8.2 flavor.
Vitess currently does not recognize MySQL 9.x versions and defaults them to MySQL 5.7 flavor. This causes failures when MySQL 8+ features like innodb_sys_tablespaces are expected, especially in local tests.
This change …
> Handle MySQL 9.x as New Flavor in getFlavor()

- go/test/endtoend/topotest/consul/main_test.go
- go/test/endtoend/topotest/zk2/main_test.go
- go/vt/topo/test/lock.go
- go/vt/topo/test/trylock.go
- go/vt/topo/zk2topo/lock.go
- go/vt/topo/zk2topo/utils.go
This PR is a follow-up to: https://github.com/vitessio/vitess/pull/16260
I did not add the `NamedLock` test for `zk2` and `consul`. 🤦 Because of that... it was not until a Vitess user that is using ZooKeeper upgraded to v21 and reported the issue here that the problem was known: https://vitess.slack.com/archives/CMKTCUYNQ/p1750981149992529
In this PR we correct my initial mistake, adding the `NamedLock` test to the `zk2` and `consul` tests. 
I then fixed the `zk2` lock implementation so that it will always create the path that we're trying to lock (as I had initially expected it to behave). The issue was that it was only creating the lock paths recursively *one* level deep, which was enough for `Keyspace` and `Shard` locks, but not enough for the named locks. With this `zk2` locking …
> Topo: Add NamedLock test for zk2 and consul and get them passing

- go/vt/vtorc/inst/analysis_dao.go
- go/vt/vtorc/logic/topology_recovery.go
This PR renames the VTOrc term "cluster-wide" to "shard-wide" for clarity
Referring to a shard as a "cluster" seems to be a byproduct of old-Orchestrator, which referred to "groups" of instances as "clusters" _(and shards would be a "cluster")_
In Vitess, a "cluster" typically refers to all keyspaces/shards/`vtgate`s/topo, which makes the terminology (to me) at-odds
> `vtorc`: rename `isClusterWideRecovery` -> `isShardWideRecovery`

- go/test/endtoend/vreplication/fk_config_test.go
- go/test/endtoend/vreplication/fk_test.go
- go/test/endtoend/vreplication/helper_test.go
- go/vt/vttablet/tabletmanager/vreplication/vcopier_atomic.go
This PR
- fixes the atomic copy behaviour (specifically in `copyAll()`) where we missed executing post copy actions.
- Also, modifies the test `TestFKWorkflow` to confirm secondary keys in the target schema. 
- Also deletes the executed post copy actions from `_vt. post_copy_action` along with the existing state deletion from `_vt.copy_state`
- Fixes https://github.com/vitessio/vitess/issues/18353
> Perform post copy actions in atomic copy

- go/vt/vttablet/tabletserver/vstreamer/rowstreamer_test.go
Tests that were added in https://github.com/vitessio/vitess/pull/18390 were having race conditions.
Hence in this PR we have replaced non-atomic heartbeat counter with atomic operations to prevent race conditions when accessing the counter from multiple goroutines.
Changes:
- Use int32 with sync/atomic instead of regular int
- Replace direct increment with atomic.AddInt32()
- Replace direct reads with atomic.LoadInt32()
This ensures thread-safe access to the heartbeat counter in the test. …
> test: Fix race condition in TestStreamRowsHeartbeat

- go/vt/vttablet/onlineddl/executor.go
- go/vt/vttablet/onlineddl/schema.go
This PR introduces a new stats gauge for Online DDL, `OnlineDDLStaleMigrationMinutes`.
Vitess (vreplication based) migrations that are found `running` but show no vreplication liveness in the past `5` seconds are logged, and the metric `OnlineDDLStaleMigrationMinutes` is updates as the highest number of staleness minutes among them.
When all `running` migrations have liveness within the `5min` range, or if there's no running migrations, then `OnlineDDLStaleMigrationMinutes` is set to zero.
Fixes https://github.com/vitessio/vitess/issues/18416
-   [ ] Tests were added or are …
> Online DDL metrics: `OnlineDDLStaleMigrationMinutes`

- go/vt/vttablet/tabletserver/vstreamer/planbuilder.go
- go/vt/vttablet/tabletserver/vstreamer/rowstreamer.go
- go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
- go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go
⚠️ This is currently an experimental change. It is a breaking change in Vitess, so we need to evaluate any failing tests that need to be modified for this logic and validate that we are not breaking core Vitess workflows.
This PR changes the filter logic in vstreamer filters to send both Before and After images, if filter matches either for non-sharded workflows. Currently only the image which passes is sent, causing downstream consumers to treat the event incorrectly as an insert or delete, when it is actually an update.
For sharded workflows, the current behaviour continues, to support rows that migrate from one shard to another.
⚠️  Breaking Change
The following tests had to be updated: `TestFilteredInt` and `TestFilteredVarBinary`. The changes were to add both after/before images …
> VStreamer: change in filter logic

- go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
- go/vt/vttablet/onlineddl/executor.go
In Online DDL cut-over, and once vreplication is stopped just before renaming the tables, ensure to restart vreplication in case the cut-over ends up failing (specifically there is one remaining operation, the `RENAME`).
Another thing in this PR: when canceling a vreplication migration (can be due to user's explicit `CANCEL`, or due to failure), do not delete the vreplication entry, as it is useful for debugging/analysis purposes.
This is a bug that needs to be backported to supported versions.
Fixes https://github.com/vitessio/vitess/issues/18427
-   [ ] Tests were added …
> Online DDL: resume vreplication after cut-over/RENAME failure

- go/vt/srvtopo/watch.go
- go/vt/srvtopo/watch_test.go
- go/vt/topo/consultopo/server_flaky_test.go
The resilient watcher in go/vt/srvtopo/watch.go was notifying listeners during every refresh cycle, even when serving cached data during outages. This violated the expectation that watchers should only notify on actual value changes.
Modified the update() method in watch.go to only notify listeners when:
1. Successful updates - Always notify on new data
2. First-time failures - Only notify on initial errors when no cached data exists
During outages with cached data available, watchers remain silent while Get operations continue working from cache.
- Fixes https://github.com/vitessio/vitess/issues/18433
-   [x] If this change is to be back-ported to previous releases, a justification is …
> Fix watcher storm during topo outages

- go/test/endtoend/vreplication/partial_movetables_seq_test.go
- go/vt/vttablet/tabletmanager/rpc_vreplication.go
- test/config.json
This PR fixes the bug where outdated in-memory sequence info was being used after switching traffic even when we updated the `next_id` in sequence tables using `intialize-target-sequences`, resulting in duplicate entry errors on the vttablet.
To fix this, we reset sequence counters on sequence tables on the tablet containing the sequence tables whenever we switch traffic. This allows tablet to refetch the updated `next_id` from the database.
Also added an e2e test `TestSequenceResetOnSwitchTraffic` which confirms this behaviour. …
> Reset in-memory sequence info on vttablet on UpdateSequenceTables request

- go/flags/endtoend/vtbackup.txt
- go/flags/endtoend/vtcombo.txt
- go/flags/endtoend/vttablet.txt
- go/flags/endtoend/vttestserver.txt
- go/vt/mysqlctl/xtrabackupengine.go
- go/vt/mysqlctl/xtrabackupengine_test.go
This will let the operator choose if they wish to drain a tablet when taking an `xtrabackup` as discussed in https://github.com/vitessio/vitess/issues/18430
Fixes #18430
> make xtrabackup ShouldDrainForBackup configurable

- go/tools/go-upgrade/go-upgrade.go
```
func isSameVersion(a, b *version.Version) bool {
return a.Segments()[0] == b.Segments()[0] && a.Segments()[1] == b.Segments()[1] && a.Segments()[2] == b.Segments()[2]
}
```
This `isSameVersion` function also checks for the patch number.
#18252
> fix: update go-upgrade tool to check patch number (#18252)

- go/vt/sqlparser/impossible_query.go
- go/vt/sqlparser/impossible_query_test.go
- go/vt/vtgate/planbuilder/testdata/cte_cases.json
Looking over our impossible query formatter, I noticed it was not handling UNION queries very well. 
Added unit tests and fixed the behaviour so UNION queries also have `where 1 != 1` added to them.
Impossible queries are used to fetch column names and types for queries without actually fetching data. 
> bugfix: Fix impossible query for UNION

- go/vt/vtgate/planbuilder/operators/union.go
- go/vt/vtgate/planbuilder/testdata/union_cases.json
When planning UNIONs, Vitess was having a hard time handling column aliases correctly.
Fixes #18469
> fix: handle aliases in UNIONs better

- go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
- go/vt/sqlparser/analyzer.go
- go/vt/vtgate/engine/aggregations.go
- go/vt/vtgate/engine/cached_size.go
- go/vt/vtgate/engine/opcode/constants.go
- go/vt/vtgate/engine/ordered_aggregate.go
- go/vt/vtgate/engine/ordered_aggregate_test.go
- go/vt/vtgate/engine/scalar_aggregation.go
- go/vt/vtgate/engine/scalar_aggregation_test.go
- go/vt/vtgate/evalengine/eval_result.go
- go/vt/vtgate/planbuilder/operator_transformers.go
- go/vt/vtgate/planbuilder/operators/aggregation_pushing_helper.go
- go/vt/vtgate/planbuilder/operators/aggregator.go
- go/vt/vtgate/planbuilder/operators/queryprojection.go
- go/vt/vtgate/planbuilder/show.go
- go/vt/vtgate/planbuilder/testdata/aggr_cases.json
- go/vt/vtgate/planbuilder/testdata/cte_cases.json
- go/vt/vtgate/planbuilder/testdata/from_cases.json
- go/vt/vtgate/planbuilder/testdata/tpch_cases.json
- go/vt/vtgate/planbuilder/testdata/union_cases.json
- go/vt/vttablet/tabletmanager/vdiff/table_plan.go
- go/vt/vttablet/tabletmanager/vdiff/workflow_differ_test.go
- go/vt/wrangler/vdiff.go
- go/vt/wrangler/vdiff_test.go
Fixes an issue where scalar aggregations with literal values incorrectly returned NULL when the input result set was empty, instead of evaluating the literal expression.
When executing queries like:
```sql
SELECT 1 AS `id`, COUNT(*) FROM (SELECT `id` FROM table WHERE condition LIMIT 100) `t`
```
If the subquery returns no rows due to the WHERE condition, Vitess incorrectly returned:
```
(NULL, 0)
```
Instead of the expected MySQL-compatible result:
```
(1, 0)  
```
The issue occurred because the aggregation engine primitives depended on incoming rows to provide values. When no rows were present, literal expressions (like `1`) were treated the same as column references and returned NULL.
Allow the engine primitives to handle evaluating evalengine expressions to handle literals and …
> Fix scalar aggregation with literals in empty result sets

- go/test/endtoend/vtgate/grpc_api/prepare_test.go
- go/vt/vtgate/engine/simple_projection.go
- go/vt/vtgate/engine/simple_projection_test.go
When a simple projection ends up in a statement that is prepared, we end up directly calling `buildFields` from `GetFields`.
When we do that, we don't do the same check we do on results, which is that we have a names only optimization where `sc.Cols` is nil. This leads to building an empty fields list.
@systay @harshit-gangal I'd love to know if this investigation makes sense or if this bug is something else. Also I'm not really sure how we should best test this? Is the test I added enough here? 
Fixes #18488 
-   [x] Did the new …
> Fix for simple projection showing no fields

- go/mysql/auth_server_clientcert_test.go
- go/mysql/client_test.go
- go/mysql/conn.go
- go/mysql/conn_params.go
- go/mysql/conn_test.go
- go/mysql/fakesqldb/server.go
- go/mysql/handshake_test.go
- go/mysql/mysql_fuzzer.go
- go/mysql/server.go
- go/mysql/server_test.go
- go/vt/vtgate/plugin_mysql_server.go
- go/vt/vtgate/plugin_mysql_server_test.go
In [v22](https://github.com/vitessio/vitess/pull/18139), a new global flag was added in go/mysql which causes issues. Instead, we need to setup a configuration option like we do for all the other settings and pass those in from the appropriate places.
I have here explicitly opted for not refactoring the function arguments, since this is a regression we should backport and I want to do the most minimal work possible here.
Fixes #18506  …
> Fix regression in v22 around new flag setup

- go/test/endtoend/vtgate/schematracker/viewsdisabled/schema.sql
- go/test/endtoend/vtgate/schematracker/viewsdisabled/schema_views_disabled_test.go
- go/test/endtoend/vtgate/schematracker/viewsdisabled/vschema.json
- go/vt/vttablet/endtoend/rpc_test.go
- go/vt/vttablet/tabletserver/query_executor.go
- test/config.json
This PR fixes the GetSchema RPC to prevent returning view definitions when the `EnableViews` configuration is disabled in the tablet server.
The GetSchema RPC was not respecting the `EnableViews` configuration setting. When `EnableViews` was disabled, clients (including VTGate and other RPC consumers) could still fetch view definitions through the GetSchema RPC. This caused issues because:
- Clients would load view definitions during schema operations even when views were disabled
- Clients could then rewrite queries by replacing views with their underlying definitions
- This behavior was problematic when views were intentionally disabled in the tablet configuration
The RPC was inconsistent with the `EnableViews` setting, allowing access to view metadata that should have been unavailable. …
> Fix GetSchema RPC to prevent returning view definitions when EnableViews is disabled

- go/flags/endtoend/vtcombo.txt
- go/flags/endtoend/vtgate.txt
- go/flags/endtoend/vttablet.txt
- go/streamlog/streamlog.go
- go/streamlog/streamlog_test.go
- go/vt/vtgate/logstats/logstats.go
- go/vt/vtgate/logstats/logstats_test.go
- go/vt/vttablet/tabletserver/tabletenv/logstats.go
Currently vtgate/vttable query log supports flag --querylog-row-threshold uint to emit query log when the row count is over a threshold. This PR adds the flag --querylog-time-threshold time.duration to emit query log when the query execution time over the time threshold.
On MySQL side, we have slow-query-log which emits slow query based on either execution time or affected rows, it would be good vtgate/tablet can issue the query log using the same criteria so we can correlate the log from both vitess and mysql sides.
The implementation pretty much followed the code path for querylog-row-threshold, the new flag querylog-time-threshold takes in a duration argument.  The duration can be expressed in a form recognized by time.ParseDuration (e.g. 300ms, 100ns).
Unit tests are added to cover …
> Add support for querylog-time-threshold duration flag for query logging

- examples/operator/operator.yaml
Updates the example `operator.yaml` file to include the new CRD field for `fetchCredentials` introduced in https://github.com/planetscale/vitess-operator/pull/711.
* https://github.com/planetscale/vitess-operator/issues/549
* Should only be merged after https://github.com/planetscale/vitess-operator/pull/711 is merged.
> Add fetchCredentials to operator.yaml

- go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
- go/vt/vttablet/onlineddl/executor.go
Migration progress is based on table rows estimation. We can get to a `ready_to_complete=1` state
with progress 87% or another value that is way off. But once we realize the migration is ready to complete,
we know row copy is fully complete _and_ that vplayer is not far behind. So it's a better DX to report 100%.
- general: https://github.com/vitessio/vitess/issues/6926
> Online DDL: set migration's progress to 100% once it's `ready_to_complete`

- go/vt/vttablet/onlineddl/executor.go
Adding a log entry any time `ready_to_complete` changes (both when set as well as when cleared). This is useful for debugging why a migration was delayed to complete.
- #6926 
> OnlineDDL: log changes to `ready_to_complete`

- go/test/endtoend/vtgate/misc_test.go
- go/test/endtoend/vtgate/unsharded/main_test.go
- go/vt/vtgate/executor_stats_test.go
- go/vt/vtgate/plan_execute.go
This PR stops emitting QueryExecutionsByTable metrics on error cases.
> fix: emit QueryExecutionsByTable for success cases only

- go/test/endtoend/vtgate/queries/orderby/orderby_test.go
- go/vt/vtgate/planbuilder/operators/SQL_builder.go
- go/vt/vtgate/planbuilder/operators/route.go
- go/vt/vtgate/planbuilder/testdata/from_cases.json
This PR fixes the issue in the column name having the database qualifier being sent down to the tablet.
During planning it should be removed as the keyspace qualifier and database name can be different, for example when we switch writes and the application still targets the source keyspace before completing the workflow.
Earlier the removal of database qualifier was spread out for sharded query.
This PR now does is after the full query is built.
- Fixes https://github.com/vitessio/vitess/issues/18603 …
> fix: remove database qualifier after building query in operator to sql

- .github/workflows/docker_build_images.yml
- changelog/23.0/23.0.0/summary.md
I couldn't edit the branch in the original PR (https://github.com/vitessio/vitess/pull/18543), so this is the same code, plus an addition to release notes.
[Bullseye was EOL 1 year ago](https://www.debian.org/releases/), so it seems reasonable to stop doing that build. Open to keeping it if we see Docker Hub stats showing that it's active.
Trixie was just released on August 9, so it seems reasonable to start doing builds for it. This PR explicitly does not change the default debian tag to trixie, as it's worth letting it soak for a bit, and doesn't change the bootstrap builds for the same reason.
-   [x] If this change is to be back-ported to previous releases, a justification is …
> docker: add trixie and rm bullseye from build matrix

- changelog/23.0/23.0.0/summary.md
- go/mysql/sqlerror/sql_error.go
- go/test/endtoend/tabletmanager/tablet_test.go
- go/vt/vttablet/grpctmclient/client.go
- go/vt/vttablet/tabletmanager/rpc_server.go
- go/vt/vttablet/tabletserver/tabletserver.go
- go/vt/vttablet/tabletserver/throttle/base/metric_result.go
- go/vt/vttablet/tabletserver/throttle/throttler.go
This PR causes `tabletmanager` RPCs to return real gRPC/`vterrors` error codes, to address the `Unknown` error code `tabletmanager` RPCs currently return for problems executing an RPC. Now tablets with downed-`mysqld` will return the gRPC `Unavailable` code with the error message unchanged, for example
To achieve this, the existing `switch` statement in `tabletserver`'s `convertErrorCode(err error) error` func was moved to be a method of `*sqlerror.SQLError`: `VtRpcErrorCode() vtrpcpb.Code`. I did not name this `.ErrorCode()` because this would be confusing, as `sqlerrors.ErrorCode` is a type that is used for something else entirely
This has been tested in non-prod environment at Slack and things look good 👍 
```bash
rpc error: code = Unknown desc = …
```
> `tabletmanager`/`grpctmclient`: use `vtrpcpb`/gRPC error codes

- examples/common/backup-scripts/vttablet-up.sh
In `examples/common/backup-scripts/vttablet-up.sh`, which was added recently, we have two commented out lines which are using `//` to start the comment. Unfortunately, that's not how comments can be started in bash, leading to error messages (but is not sever enough to stop the script execution).
Let's just remove those two lines.
N/A
> Delete invalid comments.

- MAINTAINERS.md
This moves @notfelineit to the list of past maintainers, and adds @beingnoble03. Also removes leftover mention of @vmg.
N/A
> Update list of maintainers.

- go/vt/vttablet/tabletserver/querythrottler/config.go
- go/vt/vttablet/tabletserver/querythrottler/file_based_config_loader_test.go
- go/vt/vttablet/tabletserver/querythrottler/query_throttler.go
- go/vt/vttablet/tabletserver/querythrottler/query_throttler_test.go
This PR introduces option for having a "Dry Run Mode" in the Query Throttler system for Vitess tablets outlined in RFC https://github.com/vitessio/vitess/issues/18412  , First PR :https://github.com/vitessio/vitess/pull/18449
In this PR we are Implements a dry-run mode for the Query Throttler that allows observing throttling decisions without actually blocking queries.
- Query throttling is critical for database performance but can be risky when first deployed
- Operators need visibility into throttling behavior before enabling actual query blocking
- Testing throttling logic in production environments requires non-disruptive monitoring 
- Add DryRun boolean field to Config struct for controlling dry-runbehavior
- When dry-run is enabled, throttling decisions are logged as warnings but …
> [Query Throttler] Add dry-run mode

- go/vt/vttablet/tabletserver/querythrottler/file_based_config_loader_test.go
In this PR we are simplifying error handling assertions in Throttler FileBasedConfigLoader:
- Test file contained redundant expectedErrorNotNil boolean field
- Error checking logic was unnecessarily complex with dual boolean and string checks
- Test assertions were inconsistent between error cases and success cases
- Remove redundant expectedErrorNotNil field from test cases
- Simplify error assertion logic to check for empty/non-empty expectedError string
- Use require.EqualError for exact error message matching instead of require.Contains
- Clean up test struct field alignment for better readability
Test Plan:
- Existing test suite should continue to pass with improved assertion accuracy
- Error cases now have exact error message validation instead of substring matching
-   [ ] …
> Simplify error handling assertions in Throttler FileBasedConfigLoader

- docker/lite/Dockerfile.mysql80
Needed to properly build MySQL 8.0 containers. Follow-on to https://github.com/vitessio/vitess/pull/18692
> Build mysql80 Dockerfile with go1.25.1

- go/flags/endtoend/vtbench.txt
- go/flags/endtoend/vtclient.txt
- go/flags/endtoend/vtcombo.txt
- go/flags/endtoend/vttestserver.txt
- go/vt/vtgate/grpcvtgateconn/conn.go
- go/vt/vtgate/grpcvtgateconn/conn_rpc_test.go
- go/vt/vtgate/grpcvtgateconn/suite_test.go
- go/vt/vtgate/vtgateconn/vtgateconn.go
Minor enhancements to the vtgateconn grpc interface:
1. Expose the CloseSession method so callers can shut down a connection if not needed.
2. Add a flag to enable the grpc fail fast option as opposed to hard coding to false.
3. Expose RegisterFlags to be called outside the module
#18550
> vtgateconn minor enhancements

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to update the SNAPSHOT version (v24.0.0-SNAPSHOT) after the release of v23.0.0-RC1.
> This Pull Request is part of https://github.com/vitessio/vitess/issues/18594
> Bump to `v24.0.0-SNAPSHOT` after the `v23.0.0-RC1` release
