vitessio/vitess

go/vt/vtgate/vindexes/vschema.go, go/vt/vtgate/vindexes/vschema_test.go
Support keyspace qualifed names for sequences.
=> Fix for issue #2307

go/vt/schemamanager/schemaswap/schema_swap.go, test/schema_swap_test.py, test/tablet.py, test/utils.py
This change adds a set of tests executing schema swaps with different error
conditions. This also fixes a few bugs in the schema swap code discovered while
running these tests.
=> Add tests for schema swap code.

go/vt/binlog/binlogplayer/binlog_player.go, go/vt/mysqlctl/reparent.go, go/vt/mysqlctl/replication/replication.go, go/vt/worker/utils_test.go
Always use VARBINARY, and use 64k size.
=> Fixing replication position storage.

test/schema_swap_test.py
When vtctld just starts master election that it uses can take some time, and
during that time workflow manager won't be functional (it will return 'redirect'
on each attempt to poll). Thus I'm adding waiting for vtctld to be fully up and
functioning.
Also fixing a typo DELET->DELETE. I don't know how it sneaked in and didn't
break the test, it broke the test internally.
=> Add waiting for vtctld to be fully functional before the tests.

go/vt/tabletserver/codex.go, go/vt/tabletserver/codex_test.go, go/vt/vtgate/router.go, go/vt/vtgate/router_select_test.go
Handling list bind variables type *querypb.BindVariable with Type TUPLE, in vtgate and vttablet.
=> Handling querypb.BindVariable better for lists.

go/vt/tabletmanager/restore.go
If a restore process gets terminated somewhere in the beginning then the tablet
may be stuck with RESTORE type. If we issue a RestoreFromBackup RPC again it's
better to make it behave as if the tablet and MySQL were restarted completely
from scratch and set the type to init_tablet_type instead of keeping RESTORE
type.
=> Allow vttablet to automatically recover after a terminated restore.

examples/kubernetes/orchestrator-down.sh, examples/kubernetes/orchestrator-template.yaml, examples/kubernetes/orchestrator-up.sh
Per conversation with @enisoc: Added a Kubernetes configmap to the orchestrator wrapper scripts. Makes it easier to change the settings while using the default image.
=> create orchestrator configmap

go/sqltypes/value.go, go/sqltypes/value_test.go
@sougou this is the case I was referring to, finally found it.
=> Adding one extra conversion test.

go/vt/tabletserver/customrule/zkcustomrule/zkcustomrule.go
=> tabletserver simplify codes

test/tablet.py
I didn't find any reference for this.
=> test: tablet.py: Remove unused value.

go/vt/vtctl/vtctl.go, go/vt/wrangler/shard.go, test/vertical_split.py
It was wrong and confusing. Hopefully better now.
=> Fixing SetShardTabletControl blacklisted_tables.

go/vt/vitessdriver/driver_go18.go, go/vt/vitessdriver/driver_go18_test.go
=> go18: update to new BeginTx API

.travis.yml
We didn't post coverage to coveralls.io since September because of a change I made in test.go.
=> Fix running code average as part of Travis runs.

docs/sitemap.xml, docs/user-guide/topology-service.html
Some recent changes to docs were not published.
=> Publish site Tue Dec 20 15:25:17 PST 2016

helm/vitess/templates/_etcd.tpl, helm/vitess/templates/_orchestrator.tpl, helm/vitess/templates/_vtctld.tpl, helm/vitess/templates/_vtgate.tpl, helm/vitess/templates/_vttablet.tpl, helm/vitess/templates/vitess.yaml, helm/vitess/values.yaml
This is a collection of small fixes for flakiness during chart installation and at steady state.
=> Improve Helm chart reliability

go/vt/tabletmanager/rpc_external_reparent.go, go/vt/tabletmanager/rpc_replication.go, go/vt/vtgate/buffer/buffer.go, go/vt/vtgate/buffer/buffer_test.go, go/vt/vtgate/buffer/check_error_opensource.go, go/vt/vtgate/buffer/flags.go, go/vt/vtgate/buffer/shard_buffer.go, go/vt/vtgate/buffer/variables.go, go/vt/vtgate/gateway/discoverygateway.go, go/vt/worker/split_clone.go, test/config.json, test/tablet.py, test/utils.py, test/vtgate_buffer.py
The following features will be added in later commits:
- Enforced max failover duration.
- Buffer window i.e. evicting older entries from full buffer.
- Parallelized drain.
- Dry-run mode.
=> vtgate: Initial implementation of master buffer.

java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessPreparedStatementTest.java, java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessStatementTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/2406)
=> Generating all autoInc values from firstInsertId

docker/bootstrap/Dockerfile.common
That way unit tests (that now require etcd 3.0+) pass.
=> Using etcd 3.0.15 in bootstrap images.

doc/LaunchingVitess.md
The previous change only added it to the sidebar.
=> Add 2PC Guid to Launch doc

go/vt/vtgate/vindexes/numeric_static_map_test.go
Our internal implementation of Locate() does not support to be called from init().
Therefore, I've changed the test to create a new vindex in each test instance.
I've also added error checking for the creation of the vindex to make sure we don't swallow any errors.
I've fixed this code before in commit 1bcbff7f324bf86ff253292816b4efc1a7147bce but I forgot to add a proper warning in the code to make sure that it doesn't happen again. Therefore, the same issue was introduced in https://github.com/youtube/vitess/pull/2422. With the new warning, people should no longer eagerly revert it back to a global variable :)
@sougou @ashudeep-sharma I'm mentioning you here just as an FYI.
=> vtgate/vindexes: Do not run testfiles.Locate() from init() (2nd time).

go/vt/tabletserver/table_info.go
Kinda small change, makes my tests with mysqlconn easier.
=> Making maxrows consistent with what we expect.

examples/local/vtgate-up.sh
=> Changing default port to not conflict.

go/mysqlconn/client.go, go/mysqlconn/client_test.go, go/mysqlconn/constants.go
Was not working right for mysql 5.7.
And the test was not passing due to some extra flag.
=> Fixing mysqlconn client library.

go/vt/tabletmanager/rpc_replication.go, go/vt/vtgate/buffer/shard_buffer.go, test/mysql_flavor.py, test/tablet.py, test/vtgate_buffer.py
This code was already improved internally. No need to review it again.
=>  test: vtgate_buffer.py: Refactor test into a base class.

docker/orchestrator/build.sh
=> Update repo in docker orchestrator build.sh file

go/vt/topo/cell_info.go, go/vt/topo/topotests/cell_info_test.go, go/vt/vtctl/cell_info.go, test/topo_flavor/zk2.py
To change a CellInfo once it's created.
=> Adding 'vtctl UpdateCellInfo' command.

go/vt/vtgate/buffer/shard_buffer.go
=> vtgate/buffer: Fix lost lock when returning early.

go/vt/vtgate/gateway/discoverygateway.go
By default, vtgate retries a request two times.
If a buffering is already in progress, we'll buffer the request before the first retry.
When the buffering unblocks e.g. because the buffering window was exceeded, the request is retried and may fail. In the second retry, vtgate must not buffer the request again because the --vtgate_buffer_window limit was already exceeded.
BUG=26755052
=> vtgate/buffer: Buffer each request only once.

go/mysqlconn/replication/binlog_event.go, go/mysqlconn/replication/binlog_event_common.go, go/mysqlconn/replication/binlog_event_common_test.go, go/mysqlconn/replication/binlog_event_make.go, go/mysqlconn/replication/binlog_event_make_test.go, go/mysqlconn/replication/constants.go, go/mysqlconn/replication_test.go, go/vt/binlog/binlog_streamer.go, go/vt/binlog/binlog_streamer_rbr_test.go, go/vt/binlog/binlog_streamer_test.go
* can generate all RBR events for tests now.
* now binlog_streamer understands update RBR events, and generates a dummy SQL with values.
* now stuck on getting the table schema.
=> Replication: RBR work.

test/cluster/sandbox/initial_reparent.py, test/cluster/sandbox/kubernetes_components.py, test/cluster/sandbox/sandbox.py, test/cluster/sandbox/sandbox_utils.py, test/cluster/sandbox/sandbox_utils_test.py, test/cluster/sandbox/sandlet.py, test/cluster/sandbox/sandlet_test.py, test/cluster/sandbox/vitess_kubernetes_sandbox.py
BUG=33969078
This is a change to handle additional readability comments and has already been approved internally.
=> Address readability comments

test/horizontal_resharding_workflow.py
A separate pull request created for readability check later.
=> e2e test for horizontal resharding workflow

travis/install_grpc.sh
=> Updating PIP before installing grpcio.

go/mysqlconn/client_test.go, go/mysqlconn/conn.go, go/mysqlconn/fakesqldb/server.go, go/mysqlconn/query.go, go/mysqlconn/query_benchmark_test.go, go/mysqlconn/query_test.go, go/mysqlconn/schema.go, go/mysqlconn/schema_test.go, go/mysqlconn/sqldb_conn.go, go/vt/mysqlctl/mysql_daemon.go, go/vt/tabletserver/connpool_test.go, go/vt/tabletserver/dbconn_test.go, go/vt/tabletserver/message_manager_test.go, go/vt/tabletserver/messager_engine_test.go, go/vt/tabletserver/query_executor_test.go, go/vt/tabletserver/schema_info_test.go, go/vt/tabletserver/table_info_test.go, go/vt/tabletserver/tabletserver_test.go, go/vt/tabletserver/testutils_test.go, go/vt/tabletserver/twopc_test.go, go/vt/tabletserver/tx_engine_test.go, go/vt/tabletserver/tx_executor_test.go, go/vt/tabletserver/tx_pool_test.go, go/vt/wrangler/testlib/apply_schema_test.go, go/vt/wrangler/testlib/backup_test.go, go/vt/wrangler/testlib/copy_schema_shard_test.go, go/vt/wrangler/testlib/fake_tablet.go, go/vt/wrangler/testlib/init_shard_master_test.go
@sougou I still have a couple files to go, but this is how it's gonna look... I'll work on adding helper methods to limit duplicate code everywhere.
=> Using new mysqlconn/fakesqldb for all tests.

go/vt/vtgate/buffer/buffer.go, go/vt/vtgate/buffer/buffer_test.go, go/vt/vtgate/buffer/shard_buffer.go
=> vtgate/buffer: Move context canceled error to the group of other errors.

go/vt/discovery/healthcheck.go, go/vt/vtgate/buffer/buffer.go, go/vt/vtgate/buffer/buffer_test.go, go/vt/vtgate/buffer/flags.go, go/vt/vtgate/buffer/flags_test.go, go/vt/vtgate/buffer/shard_buffer.go, go/vt/vtgate/buffer/timeout_thread.go, go/vt/vtgate/buffer/variables.go, go/vt/vtgate/buffer/variables_test.go, go/vt/vtgate/gateway/discoverygateway.go, test/vtgate_buffer.py
Alain, sorry for this bigger review.
I've broken out the independent changes into separate commits. Therefore, please review one commit at a time. Thank you!
=> vtgate/buffer: Dry-run mode. More monitoring variables. Shutdown() support.

go/vt/tabletserver/endtoend/transaction_test.go
=> tabletserver: deflake some endtoend tests

examples/kubernetes/vtgate-controller-template.yaml, examples/kubernetes/vtgate-service-template.yaml, examples/kubernetes/vtgate-up.sh
I found this useful for testing the new mysql server protocol support.
=> configure the mysql server port in the kubernetes example

go/vt/mysqlctl/mysqld.go
@pivanof here you go, the my.cnf part taken out of #2541
=> allow my.cnf template file to be configurable

go/vt/tabletserver/splitquery/full_scan_algorithm.go, go/vt/tabletserver/splitquery/full_scan_algorithm_test.go
See b/34884766.
@dumbunny  PTAL.
=> Added 'force index (primary)` to FULL_SCAN queries.

bootstrap.sh, dev.env, travis/install_grpc.sh
The previous PR on this topic broke some systems. The current PR has been more widely tested.
=> Second effort at selecting python2 on all systems. Also quiet wget.

go/vt/tabletserver/splitquery/full_scan_algorithm_test.go
=> Fixes full_scan_algorithm_test to use capitalized PRIMARY

java/client/src/main/java/com/youtube/vitess/client/VTGateConn.java, java/client/src/main/java/com/youtube/vitess/client/VTGateTx.java
Pass directExecutor to transformAsync.
=> Pass MoreExecutors.directExecutor to Futures.transformAsync.

docs/user-guide/horizontal-sharding.html, docs/user-guide/sharding-kubernetes.html
This Pull Request corrects the Vschema Definition with the new version
=> Updating the example with New Vschema format

doc/HorizontalReshardingGuide.md, doc/ShardingKubernetes.md, docs/sitemap.xml, docs/user-guide/horizontal-sharding.html, docs/user-guide/sharding-kubernetes.html
Updating the VSchema Changes to markdown files.
=> Vschema doc fix

php/src/Vitess/ProtoUtils.php
=> update success flag

go/vt/vttablet/tabletserver/splitquery/equal_splits_algorithm.go, go/vt/vttablet/tabletserver/splitquery/full_scan_algorithm.go, go/vt/vttablet/tabletserver/splitquery/split_params.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tabletserver_test.go
=> Changing the errors SplitQuery returns to be from the vterrors package.

doc/APIScope.md
@sougou first draft, let's talk about it, or you can comment.
=> First version of a doc about API scope.

py/vttest/mysql_flavor.py
=> py/vttest: Remove unused import.

go/mysqlconn/client_test.go, go/mysqlconn/doc.go, go/mysqlconn/replication/binlog_event_rbr.go, go/mysqlconn/replication/binlog_event_rbr_test.go, go/mysqlconn/replication_test.go, go/mysqlconn/server_test.go, go/vt/binlog/binlog_streamer.go
Code coverage is now much better, with real interactions with MySQL.
=> Rbr: adding test with real DB, fixing problems.

.pullapprove.yml
This will allow her to LGTM changes from Reviewable.io where we use the "-bot" account.
=> Add Yipei's bot account as approver.

go/vt/vttablet/endtoend/message_test.go
=> vttablet endtoend: deflake message_test

travis/download_mariadb.sh
Fixes recent Travis build errors.
=> travis: Update MariaDB download URLs.

doc/HorizontalReshardingWorkflowGuide.md, go/vt/workflow/node.go, go/vt/workflow/resharding/horizontal_resharding_workflow_test.go, go/vt/workflow/resharding/tasks.go, vitess.io/_includes/left-nav-menu.html
1) fix typos in local env tutorial. Add the doc to left-menu
2) fix bug in error handling for vtworker's tasks
3) fix data racing issue in node.go (the bug number is only for this)
BUG=36510237
=> workflow: fix several bugs.

doc/VSchema.md
This is the VSchema user guide. This is mostly a superset of https://github.com/youtube/vitess/blob/master/doc/VTGateV3Features.md, which I plan to delete. I'm even thinking of deleting the Vindex design doc, but there could be arguments to keep it around.
=> VSchema documentation

go/vt/vtgate/plugin_mysql_server.go
=> Add flags for configuring ssl in vtgate mysql plugin

go/mysqlconn/auth_server.go, go/mysqlconn/constants.go, go/mysqlconn/server.go, go/mysqlconn/server_test.go
Mainly moving all related code in one place, and adding a unit test.
@bbeaudreault PTAL, but thanks for doing all the work on this :)
=> Refactoring dialog plugin code a bit.

test/cluster/k8s_environment.py, test/cluster/reparent_test.py, test/cluster/sandbox/example_sandbox.yaml, test/cluster/sandbox/vitess_kubernetes_sandbox.py
I was able to get orchestrator reparent tests working again. There may still be some flakiness that will need to be addressed.
=> Sandbox tests

.travis.yml, java/client/src/test/java/io/vitess/client/RpcClientTest.java, java/grpc-client/src/test/java/io/client/grpc/GrpcClientTlsTest.java
This reverts commit fe230ec02fc25ea367555ae67dbdcaceba4de007.
This commit was accidentally merged as part of https://github.com/youtube/vitess/pull/2726.
=> Revert "TEMP: Debug failing Java test."

java/pom.xml
Also remove the list of developers because it is outdated and at this point it would be impractical to list them all.
=> java: Update the project description and URL.

.travis.yml, doc/ClientLibraries.md, doc/Sharding.md, java/hadoop/src/main/java/io/vitess/hadoop/README.md
This change is part of https://github.com/youtube/vitess/issues/2725. I forgot to change "com/youtube/vitess" in the previous PR (https://github.com/youtube/vitess/pull/2726)
=> Rename all occurences of com/youtube/vitess/* to io/vitess/* as well.

go/mysqlconn/constants.go, go/vt/vttablet/tabletserver/tabletserver.go
=> tabletserver: ERServerShutdown->UNAVAILABLE

doc/Upgrading.md, docs/sitemap.xml, docs/user-guide/upgrading.html
Also: Specify compability guarantees.
=> doc: Change recommended upgrade order.

test/vtctld_web_test.py
=> Reduce vtctld webdriver test flakiness.

doc/internal/ReleaseInstructions.md, docs/internal/release-instructions.html
Dean, I want you to review this because you already reviewed the respective Maven POM changes (https://github.com/youtube/vitess/pull/2764). Thanks!
=> doc/internal: Add instructions how to release Java packages.

go/vt/vtgate/buffer/buffer_test.go
Addressed code review comment in https://github.com/youtube/vitess/pull/2599.
=> vtgate: Avoid tight loop in unit tests.

go/cmd/vttablet/status.go
=> bug: fix panic log spam

go/vt/topo/topoproto/tablet.go
@michael-berlin @sougou another one of these.
=> Replacing a proto equality.

ADOPTERS.md, README.md
Addresses #2789 
@adkhare @harshit-gangal @bbeaudreault @derekperkins @Rastusik @demmer @tirsen @rnavarro 
Let me know if you want anything changed.
=> doc: Create ADOPTERS.md

go/vt/vitessdriver/driver_go18.go, go/vt/vtgate/executor.go, go/vt/vtgate/executor_dml_test.go, go/vt/vtgate/executor_framework_test.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/executor_test.go, go/vt/vtgate/vcursor_impl.go, go/vt/vtgate/vtgate.go
Some more cleanup and addressed review comments:
* merge wrappedVSchema into vcursorImpl
* DeepEqual -> result.Equal
* exr->e
=> v3: more cleanup

data/test/vtgate/select_cases.txt, data/test/vtgate/unsupported_cases.txt, go/vt/vtgate/engine/primitive.go, go/vt/vtgate/engine/route.go, go/vt/vtgate/executor.go, go/vt/vtgate/executor_dml_test.go, go/vt/vtgate/planbuilder/expr.go, go/vt/vtgate/planbuilder/union.go, go/vt/vtgate/vcursor_impl.go, go/vt/vtgate/vindexes/lookup_hash_test.go, go/vt/vtgate/vindexes/lookup_internal.go, go/vt/vtgate/vindexes/vindex.go, go/vt/vttablet/tabletserver/connpool/dbconn.go, go/vt/vttablet/tabletserver/query_engine.go, go/vt/vttablet/tabletserver/query_engine_test.go, go/vt/vttablet/tabletserver/tabletenv/config.go
Three more trivial features:
* fix UNION merge logic. Separate it from subqueries.
* Rollback if a statement resulted in partial DML execution.
* new flag in vttablet to disable strict_trans_table check on popular demand.
=> v3: three features

go/vt/vtctl/vtctl.go, go/vt/wrangler/keyspace.go
=> Also removing SrvKeyspace in RemoveKeyspaceCell.

.codeclimate.yml
CodeClimate should run gofmt, golint and govet on every pull request for
us and post the result as a status. This will make it easier to find out
if somebody (accidentally) skipped our Git precommit hooks which run the
same tools.
=> Configure CodeClimate. Enable all Go engines.

go/vt/topo/replication.go
=> Fixing a couple proto compare.

java/jdbc/src/main/java/io/vitess/jdbc/VitessPreparedStatement.java, java/jdbc/src/main/java/io/vitess/jdbc/VitessResultSet.java, java/jdbc/src/test/java/io/vitess/jdbc/VitessPreparedStatementTest.java, java/jdbc/src/test/java/io/vitess/jdbc/VitessResultSetTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/2816)
=> Implement setClob and getClob

go/vt/mysqlctl/mysqld.go
@tirsen
I still need to figure out how to test this. But existing tests
are passing for now. Can you let me know if this fixes your problem?
=> fix for #2818

go/vt/sqlparser/analyzer.go, go/vt/sqlparser/analyzer_test.go, go/vt/sqlparser/comments.go
=> Handle comments in the prefix

go/vt/topo/topoproto/tablet.go, go/vt/vttablet/tabletmanager/binlog_players.go
Alain, you merged https://github.com/youtube/vitess/pull/2871/files a bit too fast :)
Here are the changes I would have asked for during a code review.
=> vttablet: Follow up fixes for new ParseTabletTypes method.

go/mysql/client.go, go/mysql/conn.go, go/mysql/conn_test.go, go/mysql/encoding.go, go/mysql/fakesqldb/server.go, go/mysql/query.go, go/mysql/query_test.go, go/mysql/server.go, go/mysql/server_test.go, go/mysql/streaming_query.go, go/vt/vtgate/plugin_mysql_server.go
Refactoring the reading of packets to also use the enum for state tracking. Adding a packet recycling method that can reclaim the memory. Adding a sync.Pool for better buffer management.
=> Mysql connector: better memory management.

doc/ScalabilityPhilosophy.md, doc/ServerConfiguration.md
Topology service was the old syntax.
Added a section on directory configuration.
=> Updating ServerConfiguration doc.

go/vt/vtctld/api_test.go
I don't know why this test passed earlier for me. Anyhoo
I'm going to just merge this. Otherwise, master is broken.
=> fix broken test

go/vt/sqlparser/analyzer.go, go/vt/sqlparser/analyzer_test.go
@sougou forgot about this -- wonder if we should make this relationship more obvious
=> support desc in preview

test/cluster/base_environment.py
The logic was added in https://github.com/youtube/vitess/pull/2920.
=> Add a comment explaining the special logic for IPv6 handling.

go/vt/servenv/buildinfo.go, tools/build_version_flags.sh
@giaquinti I'm assigning you as reviewer :)
Thank you for your PR. Let me know if this change works for you.
=> buildinfo: --version output: Use shorter hash and add Git branch.

go/vt/vttablet/tabletserver/messager/message_manager_test.go
I saw this race a couple of times because the Purge threads would
race with SetChannel(nil). Instead, I've just created a buffered
channel, which won't cause things to get blocked.
=> messages: fix race in test

data/test/tabletserver/stream_cases.txt, go/vt/vttablet/tabletserver/planbuilder/plan.go
@sougou is this what you had in mind? i think we should unify the code path with Build (for Execute), but perhaps this can work for now?
=> allow show and other commands in streaming mode

go/vt/vttablet/tabletmanager/action_agent.go, go/vt/vttablet/tabletmanager/healthcheck.go, go/vt/vttablet/tabletmanager/healthcheck_test.go
Even if it's zero.
BUG=62771731
=> Not rechecking MySQL port if we already got it.

go/vt/topo/etcd2topo/error.go, go/vt/vttablet/endtoend/misc_test.go
It seems the etcd library may return an Unavailable error in some cases, so
now we classify this as topo.ErrTimeout.
Also trying to reduce TestConsolidation flakiness.
BUG=34073858
=> Trying to reduce flakiness of a couple tests.

go/vt/binlog/binlog_streamer.go, go/vt/binlog/binlog_streamer_rbr_test.go
Need to use WHERE value is NULL.
Added unit test case.
@tirsen thanks for the fix!
=> RBR: WHERE value=NULL doesn't work.

go/vt/topo/etcd2topo/error.go
It seems we're getting gRPC errors directly.
=> Trying to process etcd error properly.

go/vt/topo/etcd2topo/error.go, go/vt/vterrors/grpc.go, go/vt/vttablet/tabletconn/grpc_error.go, vendor/vendor.json
New version of:
- gRPC and dependencies (http2, ...)
- etcd v3 client.
Replaced a couple instance of gRPC deprecated calls.
=> Upgrading a few golang vendored libraries.

go/cmd/vtcombo/main.go, go/cmd/vttablet/vttablet.go, go/mysql/conn_params.go, go/mysql/conn_test.go, go/vt/mysqlctl/cmd.go, go/vt/mysqlctl/mysqld.go, go/vt/vttablet/endtoend/framework/server.go, go/vt/vttablet/tabletserver/testutils_test.go
This reverts commit a55ebb0e5bd0294360d68700d70e124b8b79fdee.
This is causing some tests to fail on import. So, I'm reverting
this for now.
I'll be pushing this through since it's a broken build.
=> Revert "bug: fail early on invalid connection parameters"

java/jdbc/src/main/java/io/vitess/jdbc/VitessPreparedStatement.java, java/jdbc/src/test/java/io/vitess/jdbc/VitessPreparedStatementTest.java
@harshit-gangal we need to be able to call setObject with a byte array. Added that and updated test.
=> Handle PreparedStatement setObject with byte array

go/vt/vttest/environment.go, go/vt/vttest/local_cluster.go
So we can customize it in environments that can reserve ports.
=> Moving a function in vttest, so port allocation can be customized.

java/client/src/main/java/io/vitess/client/cursor/Row.java, java/client/src/test/java/io/vitess/client/cursor/CursorTest.java, java/jdbc/src/main/java/io/vitess/jdbc/VitessResultSet.java, java/jdbc/src/test/java/io/vitess/jdbc/VitessResultSetTest.java
@harshit-gangal 
i'd like to call attention to CursorTest.java L337
if you change that to something non ascii, "მოგზაურობა" for example, the test fails.
also, i'm not so sure about L339 what Type makes for the best test there.
=> implement getBinaryStream/getBinaryInputStream

go/vt/vtctld/realtime_status_test.go, go/vt/vtctld/tablet_data_test.go, go/vt/worker/legacy_split_clone_test.go, go/vt/worker/split_clone_test.go, go/vt/worker/split_diff_test.go, go/vt/worker/vertical_split_clone_test.go, go/vt/worker/vertical_split_diff_test.go, go/vt/wrangler/testlib/fake_tablet.go, go/vt/wrangler/testlib/wait_for_drain_test.go, go/vt/wrangler/testlib/wait_for_filtered_replication_test.go, vendor/vendor.json
The newest gRPC library doesn't allow registering services after Serve()
is called (which makes sense!). Fixing all tests to not do that.
=> Updating to newest gRPC, fixing tests.

java/client/pom.xml, java/client/src/main/java/io/vitess/client/VTGateBlockingConn.java, java/client/src/main/java/io/vitess/client/VTGateBlockingConnection.java, java/client/src/main/java/io/vitess/client/VTGateBlockingTx.java, java/client/src/main/java/io/vitess/client/VTGateConn.java, java/client/src/main/java/io/vitess/client/VTGateConnection.java, java/client/src/main/java/io/vitess/client/VTGateTx.java, java/example/pom.xml, java/example/src/main/java/io/vitess/example/VitessClientExample.java, java/grpc-client/pom.xml, java/hadoop/pom.xml, java/jdbc/pom.xml, java/pom.xml
This PR is in initial stage.
Raising as to get initial feedback.
Changes:
- New Connection class to keep communicate with VTGate
- Use session rather than traditional way
- No v2 APIs
- Deprecating old Class - VTGateConn & VTGateTx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/2995)
=> Low level Java Client Changes for Vitess new API

go/vt/vttablet/endtoend/config_test.go, go/vt/vttablet/tabletserver/query_engine.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/tabletenv/config.go, go/vt/vttablet/tabletserver/tabletenv/tabletenv.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tabletserver_test.go
Fixes: #3017 
@bbeaudreault 
@sougou 
I'd like to add a test in config_test just below the typo i've fixed. any handy example of a test where we make sure something is logged?
=> implement warning on row threshold

go/vt/vterrors/vterrors.go, go/vt/vttablet/endtoend/acl_test.go, go/vt/vttablet/endtoend/misc_test.go, go/vt/vttablet/endtoend/transaction_test.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tabletserver_test.go
Fixes: #3016
@bbeaudreault 
@alainjobart
=> add callerid information to tablet errors, when TerseErrors is false

java/jdbc/src/main/java/io/vitess/jdbc/ConnectionProperties.java, java/jdbc/src/main/java/io/vitess/jdbc/VitessConnection.java, java/jdbc/src/main/java/io/vitess/jdbc/VitessDriver.java, java/jdbc/src/main/java/io/vitess/jdbc/VitessJDBCUrl.java, java/jdbc/src/main/java/io/vitess/util/Constants.java, java/jdbc/src/test/java/io/vitess/jdbc/ConnectionPropertiesTest.java, java/jdbc/src/test/java/io/vitess/jdbc/VitessDriverTest.java, java/jdbc/src/test/java/io/vitess/jdbc/VitessJDBCUrlTest.java
Motivation:
- Make TABLE_TYPE property to camel case like others "tabletType"
- Allow Keyspace, catalog, shard to be set from property as well
=> Connection property changes

go/cmd/vtclient/vtclient.go, go/vt/vterrors/vterrors.go, go/vt/vtgate/engine/route.go, go/vt/vtgate/vtgate.go, go/vt/worker/command.go, go/vt/worker/vtworkerclient/wrapper.go, go/vt/worker/vtworkerclienttest/client_testsuite.go
=> add new vterrors.Wrap and vterrors.Wrapf, properly wrap errors in route.go

go/vt/vttablet/tabletserver/messager/engine.go, go/vt/vttablet/tabletserver/planbuilder/plan.go
@sougou 
I may do quick little PRs like this as I encounter un-coded errors, until you get around the full thing
=> return a vterror with proper error code instead of a normal error

data/test/tabletserver/exec_cases.txt, go/vt/vttablet/endtoend/queries_test.go, go/vt/vttablet/tabletserver/planbuilder/query_gen.go
=> preserve orderby for delete and update rewrites

go/mysql/constants.go, go/vt/vttablet/tabletserver/tabletserver.go
=> add codes for ER_BAD_FIELD_ERROR and treat as NOT_FOUND

doc/GettingStarted.md
Right now the GettingStarted doc formatting looks weird. As everything bellow that is formatted as code. which is incorrect due to a bad formatting.
=> fix formatting on doc

config/init_db.sql, examples/local/vtgate-up.sh, examples/local/vttablet-up.sh, go/cmd/vttablet/vttablet.go, go/mysql/fakesqldb/server.go, go/vt/dbconfigs/dbconfigs.go, go/vt/vttablet/endtoend/framework/client.go, go/vt/vttablet/endtoend/framework/server.go, go/vt/vttablet/endtoend/main_test.go, go/vt/vttablet/endtoend/misc_test.go, go/vt/vttablet/heartbeat/reader.go, go/vt/vttablet/heartbeat/reader_test.go, go/vt/vttablet/heartbeat/writer.go, go/vt/vttablet/heartbeat/writer_test.go, go/vt/vttablet/tabletserver/connpool/dbconn.go, go/vt/vttablet/tabletserver/connpool/dbconn_test.go, go/vt/vttablet/tabletserver/connpool/pool.go, go/vt/vttablet/tabletserver/connpool/pool_test.go, go/vt/vttablet/tabletserver/messager/engine.go, go/vt/vttablet/tabletserver/messager/message_manager_test.go, go/vt/vttablet/tabletserver/query_engine.go, go/vt/vttablet/tabletserver/schema/engine.go, go/vt/vttablet/tabletserver/schema/load_table_test.go, go/vt/vttablet/tabletserver/tabletenv/config.go, go/vt/vttablet/tabletserver/twopc.go, go/vt/vttablet/tabletserver/tx_engine.go, go/vt/vttablet/tabletserver/tx_pool.go, go/vt/vttablet/tabletserver/tx_pool_test.go, go/vt/vttest/local_cluster.go, py/vttest/mysql_db_mysqlctl.py
* Addresses https://github.com/youtube/vitess/issues/3044.
* The core of the changes are located in pool.go and dbconn.go
* Unit and integration
* Local cluster
=> Add mysql creds propagation

go/vt/vtgate/executor.go, go/vt/vtgate/executor_test.go
Issue #3041
This changes behavior of autocommit to be closer to mysql. The main
difference is that we don't start an implicit transaction if
autocommit is 0 because this will break legacy.
Implicit transactions  will be added in 3.1 after all the
clients have been upgraded.
=> v3: make autocommit behave more like mysql

go/cmd/vtexplain/.gitignore, go/cmd/vtexplain/vtexplain.go, go/mysql/fakesqldb/server.go, go/vt/vtexplain/vtexplain.go, go/vt/vtexplain/vtexplain_test.go, go/vt/vtexplain/vtexplain_topo.go, go/vt/vtexplain/vtexplain_vtgate.go, go/vt/vtexplain/vtexplain_vttablet.go, go/vt/vtexplain/vtexplain_vttablet_test.go, go/vt/vtgate/executor.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/tabletserver.go, vendor/vendor.json
This PR contains the implementation of vtexplain as described in #3062.
Now that #3062 is merged I've rebased this on top of the latest master.
=> vtexplain implementation

go/vt/vtexplain/vtexplain_test.go
The recent merge of the upsert work caused conflicts with the vtexplain
tests since the query plans changed.
=> update vtexplain test to pass with the upsert changes

go/vt/vtgate/executor.go, go/vt/vtgate/executor_dml_test.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/executor_test.go
* add support in executorExec to normalize the query when there is a
specific shard target
* add a number of tests for both forced shard queries, the normalization,
and expected treatment of leading and trailing comments
=> add vtgate support to normalize queries when routed to a specific shard

go/vt/vttablet/heartbeat/reader.go
We discovered a rare deadlock that could occur when a Stop() is happening at the same time as readHeartbeat is running.  Stop would be waiting on `r.ticks.Stop()` (which waits until the `timerStop` msg is read, and it would have the lock at this time.  `readHeartbeat` would be waiting on the lock to update `lastKnownLag`.
This PR breaks this into two locks, because they really didnt need to be linked.
@sougou @acharis
=> Fix heartbeat deadlock

doc/GettingStarted.md, docs/getting-started/local-instance.html
=> Example scripts will start 5 tablets and not 3

go/vt/vtgate/buffer/flags.go
Nominating @rnavarro as reviewer.
=> Clarify vtgate buffer flags.

.pullapprove.yml
Add: bbeaudreault, demmer, harshit-gangal
Remove: erzel, thompsonja
Order alphabetically
=> admin: update pullapprove

go/vt/discovery/healthcheck.go
We'd like to verify that all of our vtgates are healthy during rolling restarts. This api will allow us to get a machine-parseable version of the gateway status displayed on the vtgate ui. I refactored the CacheStatus endpoint to return a map, because that is easier to use from a consumer and also avoids an allocation.
@sougou
=> add an endpoint for serving the discovery gateway's cache status

go/vt/vtgate/executor_select_test.go, go/vt/vtgate/planbuilder/from.go, go/vt/vtgate/planbuilder/route.go
@sougou @giaquinti 
https://github.com/youtube/vitess/issues/3069
This is what was talked about in #vitess but ... it doesn't work.
If you grep around for information_schema and find some tests, and flip the case, you'll see.
This is WIP both because it needs tests, and because it's not really working.
Secondarily, please also furnish a list of what you consider "system schemas"
=> information_schema case-insensitivity

vitess.io/preview-site.sh, vitess.io/publish-site.sh
Also: Infer $VTTOP if it is not set.
=> vitess.io: Allow scripts to be run from any current working directory.

go/sqltypes/arithmetic.go, go/sqltypes/arithmetic_test.go
=> v3: allow date/time comparison as strings

go/mysql/server_test.go
Per comments in #3216, I went ahead an updated this test a well to be consistent.
=> Test cleanup per code review

go/vt/vtexplain/vtexplain_vtgate.go, go/vt/vtgate/executor.go, go/vt/vtgate/executor_framework_test.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/vtgate.go
This commit added support for queryCacheSize in VtGate.
=> Adds query cache size option to VtGate

misc/git/hooks/pylint, tools/pylint.sh
It's installed in a different place on my Mac.
=> misc: Allow to override the location for pylint via gpylint.

go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tabletserver_test.go
This is limited to as_transaction=true RPCs that contain a single query inside.
Executing single DMLs on vttablet this way is beneficial because there are less round trips for BeginExecute() and Commit() involved both between the user and vtgate and vtgate and vttablet.
As this RPC endpoint gets used for DMLs as well, hot row protection should cover it too.
BUG=66906815
=> vttablet: Integrate hot row protection for ExecuteBatch queries.

go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tabletserver_test.go
The last round of rework didn't account for the fact that the error object coming back from mysql already contains a copy of the full expanded sql query, and so even though we were applying the truncation limit to the error as well as the query + bind vars, the resulting log could be more than 2x the configured limit.
Instead change the logic so that it truncates the combined string right before logging it.
I ran the new code on one of our test servers with a query that deliberately overflows a column with the settings `-queryserver-config-terse-errors` and `-sql-max-length-errors 1024`
Before:
`Oct  9 16:07:24 tablet-dev-xxxxx vttablet[5161]: I1009 16:07:24.296165    5161 tabletserver.go:1340] Data too long for column 'value' at row 1 (errno 1406) (sqlstate 22001) during query: insert …
=> rework the tabletserver log truncation again

.codeclimate.yml
=> Add shellcheck to .codeclimate.yml

data/test/vtexplain/test-schema.sql, data/test/vtexplain/unsharded-output.json, data/test/vtexplain/unsharded-output.txt, data/test/vtexplain/unsharded-queries.sql, go/vt/sqlparser/ast.go
Fix a bug in `sqlparser.SQLType()` for float columns as described in #3328.
=> vtexplain fix float columns

go/vt/mysqlctl/s3backupstorage/s3.go
Add support to the s3 backup uploader to enable server side encryption:
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html
=> add s3 backup provider option for server-side encryption

go/vt/mysqlctl/grpcmysqlctlclient/client.go
Thanks to @rajatgoel for the catch
=> grpc: fix typo

java/client/src/main/java/io/vitess/client/VTSession.java, java/jdbc/src/main/java/io/vitess/jdbc/VitessConnection.java, java/jdbc/src/test/java/io/vitess/jdbc/VitessConnectionTest.java
We've been running with this code for a few weeks. I finally got us rebased back on master with @harshit-gangal's v3 code so can upstream this now.
=> Add JDBC support for setting transaction isolation on connection

Makefile, go/vt/vtexplain/vtexplain_vttablet.go, go/vt/vttablet/tabletserver/messager/message_manager_test.go, test/config.json
* Fixed race in vtexplain
* Fixed race in message_manager_test
=> travis: resurrect unit_race

go/mysql/client_test.go, go/mysql/endtoend/client_test.go, go/mysql/endtoend/main_test.go, go/vt/vtexplain/vtexplain_flaky_test.go
* Deflake mysql/endtoend test
* Disable vtexplain_flaky_test.go (created Issue #3368)
* Start using t.Helper where applicable
=> test: deflake some tests

Makefile
@vmg and I needed to run `make docker_base` on our servers to build and push a custom docker image to our registry.
However, make was requiring `protoc` to be installed.
This changes the Makefile to only raise an error if protoc is not present inside the proto tasks.
=> Make sure proto is only required on proto tasks

java/client/src/main/java/io/vitess/client/VTGateConnection.java, java/client/src/main/java/io/vitess/client/VTSession.java
LastCall check made at VTGate connection level which avoided any client to use multiple connection.
It is moved to session level. So that for a session multiple calls are not made which can corrupt the transaction.
Now, a single VTGate connection can be used by Connection pool.
=> [Bug Fix] - fixes client for using multiple connection

vitess.io/Gemfile, vitess.io/Gemfile.lock
=> Upgrade pygments.rb and drop yajl-ruby

go/vt/discovery/replicationlag.go, go/vt/discovery/replicationlag_test.go
=> Makes the min number of discoverable tablets with low rep lag configurable.

go/vt/discovery/replicationlag.go, go/vt/discovery/replicationlag_test.go
If only two tablets are there, with replication lag of 3h and 30h, we'd
return nothing. We want to return both.
=> Handling a corner case in discovery.

go/vt/worker/chunk.go
Issue #3407
Error messages did not specify the tablet or table they were
failing on.
=> worker: improved error message on generateChunks

go/vt/wrangler/testlib/reparent_external_test.go
@sougou this is broken right now. See description for why and the fix. It's the time.Minute /* finalizeTimeout */ to 2s line fix.
(that breaks my vttest PR, that's why I investigated).
=> Test fix from Sugu's gRPC changes.

go/vt/mysqlctl/slave_connection.go
And adding a big TODO for demmer@ to keep the work going. :)
It always bothered me that SlaveConnection was in mysqlctl, when it
doesn't need to be any more (since we migrated the connection type to
go/mysql package). This prepares the move to binlog/.
=> Simplifying SlaveConnection in mysqlctl.

go/vt/vttablet/tabletmanager/action_agent.go, go/vt/vttablet/tabletserver/replication_watcher.go, go/vt/vttablet/tabletserver/tabletserver.go
Introduced a regression in my last PR.
=> Using Dba connection for SlaveConnection.

data/test/vtgate/postprocess_cases.txt, go/vt/sqlparser/ast.go, go/vt/vtgate/planbuilder/builder.go, go/vt/vtgate/planbuilder/join.go, go/vt/vtgate/planbuilder/limit.go, go/vt/vtgate/planbuilder/ordered_aggregate.go, go/vt/vtgate/planbuilder/postprocess.go, go/vt/vtgate/planbuilder/route.go, go/vt/vtgate/planbuilder/subquery.go, go/vt/vtgate/planbuilder/vindex_func.go
Sugu said "This is similar to ORDER BY NULL. We should just support it with push-down.",
so I've tried that.
=> push down "order by rand()"

go/cache/lru_cache.go, go/cache/lru_cache_test.go, go/vt/vtgate/executor.go, go/vt/vttablet/tabletserver/query_engine.go
=> lru_cache: export eviction stats

doc/vtctlReference.md, go/vt/grpcclient/client.go, go/vt/vtctl/vtctl.go, go/vt/vttablet/grpctmclient/client.go
Adding package docs to two packages where it was missing.
Remove 3 extra lines of code.
Re-generate vtctl doc.
=> Minor fixes.

java/client/src/main/java/io/vitess/client/RefreshableVTGateConnection.java, java/client/src/main/java/io/vitess/client/VTGateConnection.java, java/jdbc/src/main/java/io/vitess/jdbc/ConnectionProperties.java, java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java, java/jdbc/src/test/java/io/vitess/jdbc/ConnectionPropertiesTest.java
Here we add a jdbc option to refresh the connection if the keystore file has changed.
@harshit-gangal
=> refresh vtgate SSL connections on a timer

doc/ScalabilityPhilosophy.md
More work needs to be done here. For now, I've removed comments
that are completely obsolete.
=> doc: update ScalabilityPhilosophy.md

examples/kubernetes/vttablet-up.sh, examples/local/vttablet-up.sh
@arthurnn we'll need this patch for our experiment on vertical resharding.
=> examples: make scripts more generic

doc/ScalabilityPhilosophy.md, docs/user-guide/scalability-philosophy/index.html
Forgot this step before I merged the previous change (and the two review comments)
=> doc: publish site for scalability philosophy

go/vt/topo/srv_vschema.go, go/vt/vtctl/vtctl.go, test/vtgatev3_test.py
And test. Fixing the formatting of vtgatev3_test.py too.
BUG=36031364
=> Adding 'vtctl DeleteSrvVSchema' command.

go/vt/vtgate/gateway/status.go, go/vt/vtgate/gateway/status_test.go
Integer numbers don't show QPS less than one.
BUG=63717455
=> Changing vtgate QPS reporting to float.

go/vt/vtgate/resolver.go
=> Removing duplicate package comments.

go/vt/mysqlctl/mycnf.go
This bug has confused many people because it just crashes vttablet
with a mysterious SIGSEGV. The problem was a bug in the error
propagation of mycnf which was using old panic style error handling.
This also addresses what #3195 was trying to fix.
=> bug: fix mycnf error propagation

go/sqltypes/arithmetic.go, go/sqltypes/arithmetic_test.go, go/vt/vtgate/engine/limit_test.go, go/vt/vtgate/engine/ordered_aggregate_test.go, go/vt/vtgate/executor_dml_test.go, go/vt/vtgate/vindexes/hash_test.go, go/vt/vtgate/vindexes/numeric_static_map_test.go, go/vt/vtgate/vindexes/numeric_test.go, go/vt/vttablet/tabletserver/codex_test.go
Alternate fix for #3247, along with test fixes.
=> bug: quote strings in parse errors

go/vt/vtqueryserver/endtoend_test.go
Turns out in our internal test environment, the file systems for these
files can't have unix sockets. This also makes it consistent with the
other tests in the directory.
=> Using temp dir for unix socket instead of vttest.

data/test/vtgate/unsupported_cases.txt, go/vt/vtgate/planbuilder/dml.go
Per discussion, this was too radical. We should not support this.
=> Multi shard DELETE with LIMIT clause should not be supported

go/vt/vtgate/executor_stream_test.go, java/client/src/test/java/io/vitess/client/RpcClientTest.java
Flagged by our internal tools.
=> Removing useless conversion, fixing govet warning in test.

java/jdbc/src/main/java/io/vitess/jdbc/ConnectionProperties.java, java/jdbc/src/main/java/io/vitess/jdbc/VitessResultSet.java, java/jdbc/src/main/java/io/vitess/util/Constants.java, java/jdbc/src/test/java/io/vitess/jdbc/ConnectionPropertiesTest.java, java/jdbc/src/test/java/io/vitess/jdbc/VitessResultSetTest.java
This implements zeroDateTimeBehavior=convertToNull like the standard
MySQL driver.
=> Support zeroDateTimeBehavior=convertToNull

go/cmd/vttablet/status.go, go/vt/discovery/healthcheck.go, go/vt/servenv/status.go, go/vt/servenv/status_test.go, go/vt/srvtopo/resilient_server.go, go/vt/status/status.go
Signed-off-by: Alain Jobart <alainjobart@google.com>
=> Changing web function paths to vitessio.

go/vt/vtgate/engine/delete_test.go, go/vt/vtgate/engine/fake_vcursor_test.go, go/vt/vtgate/engine/insert_test.go, go/vt/vtgate/engine/join.go, go/vt/vtgate/engine/merge_sort.go, go/vt/vtgate/engine/merge_sort_test.go, go/vt/vtgate/engine/route.go, go/vt/vtgate/engine/route_test.go, go/vt/vtgate/engine/update_test.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/planbuilder/from.go
Added tests for Route primitive. Also made some tweaks:
* Got rid of scatterParams: code is simpler
* Fixed a streaming bug where field had to be fetched
even if no route was found.
=> v3: route tests

misc/git/commit-msg.signoff
This should help reduce the annoyance, especially having to retype your commit message.
=> Prompt to add DCO signoff in git hook.

go/vt/vtqueryserver/vtqueryserver.go
Background:
When mysql was restarted from underneath vtqueryserver, we observed that it detected the mysql host went away and transitioned into the NOT_SERVING state.
```
I0227 16:20:14.745843    4291 tabletserver.go:618] Check MySQL failed. Shutting down query service
I0227 16:20:14.745869    4291 tabletserver.go:281] TabletServer state: SERVING -> SHUTTING_DOWN
I0227 16:20:14.745879    4291 tabletserver.go:520] Executing complete shutdown.
I0227 16:20:14.745909    4291 tx_engine.go:179] No grace period specified: performing normal wait.
I0227 16:20:14.746217    4291 tabletserver.go:526] Shutdown complete.
I0227 16:20:14.746225    4291 tabletserver.go:281] TabletServer state: SHUTTING_DOWN -> NOT_SERVING
````
This was a terminal state for vtqueryserver.
Proposed change:
Add a timer to …
=> Add healthcheck timer to vtqueryserver

travis/install_grpc.sh
thsi fixes our build. i'm not sure why others haven't popped up in slack with this same problem.
Signed-off-by: Alex Charis <acharis@hubspot.com>
=> point to correct location for grpc_python_plugin

go/vt/vttablet/endtoend/config_test.go
It turns out the previous test succeeded only if both goroutines
tried to get a connection from the pool concurrently. Make the
test more reliable by sending three queries in parallel so that
one should succeed, one should be blocked getting a connection
from the pool, and the third should always fail.
Signed-off-by: Michael Demmer <mdemmer@slack-corp.com>
=> improve reliability of TestConnPoolWaitCap

java/jdbc/src/main/java/io/vitess/jdbc/VitessPreparedStatement.java, java/jdbc/src/main/java/io/vitess/jdbc/VitessStatement.java, java/jdbc/src/main/java/io/vitess/util/StringUtils.java, java/jdbc/src/test/java/io/vitess/jdbc/VitessStatementTest.java
follow mysql-connector-j by making upsert statements have at most one generated key
=> fix getGeneratedKeys for batch of upserts

README.md
=> cncf: add cii badge

doc/MySQLServerProtocol.md
Signed-off-by: Ryan Kennedy <rckenned@gmail.com>
=> Fixes some typos in the MySQL server protocol documentation

go/vt/discovery/tablet_stats_cache.go
Using a channel to serialize updates. Otherwise, when two tablets update
their records at the same time, the resulting aggregate stats may appear
out of order, and not be correct. This introduced flakiness in our tests
(detected internally by our build tools, at least, haven't checked
travis).
=> Serializing srvtopo aggregate updates.

go/mysql/auth_server_static.go, go/mysql/auth_server_static_test.go
If you use the -mysql_auth_server_static_file parameter to vtgate,
this will allow `sudo kill -HUP $VTGATE_PID` to cause the config
to be re-read from the file. Note: this only changes the configuration
at the time of connecting to vtgate, not dynamically for existing connections.
(Simon said MySQL grants work like that too.)
Signed-off-by: Scott Lanning <scott.lanning@booking.com>
=> allow SIGHUP of vtgate to reload mysql_auth_server_static_file

go/vt/vtgate/vtgate.go
Line [1070](https://github.com/vitessio/vitess/blob/master/go/vt/vtgate/vtgate.go#L1070) and [1072](https://github.com/vitessio/vitess/blob/master/go/vt/vtgate/vtgate.go#L1072) of vtgate log the request when there are unknown errors. This could cause bindVars to leak into the logs. In our case bindVars could have PII information and we wouldn't like those to end up in the logs. Following a similar approach to the one in the tablet server, this PR adds a config setting to enable terse errors on vtgate. When on, the request map is stripped from the logs. 
* I tested this locally. I was looking into adding unit tests into this, but it requires a slightly bigger refactor in vtgate. To do this we will need to do something similar to what is done in the …
=> Strip bindVars from response when terse errors is on

README.md
Re: the cii badging / license scans
Ref: @caniszczyk
=> doc(readme): add license scan status and report

docker/k8s/vtworker/Dockerfile
Signed-off-by: Derek Perkins <derek@derekperkins.com>
=> docker: add vtworker Dockerfile

doc/GettingStarted.md, examples/local/env.sh, examples/local/etcd-down.sh, examples/local/etcd-up.sh, examples/local/topo-etcd2.sh, examples/local/topo-zk2.sh
Signed-off-by: yangxuanjia <yangxuanjia@jd.com>
=> add local etcd test env

doc/VTGateSubqueries.md
I hit some unpleasant corner cases with subquery handling. So, I thought I should write up a design doc about how I plan to address them.
=> v3: subquery handling design

doc/TwoPhaseCommitGuide.md
Fixed the ACID Isolation explanation and a typo
=> Fix 2pc guide

doc/VSchema.md
Signed-off-by: jvaidya <jitendra.vaidya@gmail.com>
=> Fix the "Update" section.

doc/ServerConfiguration.md
Signed-off-by: jvaidya <jitendra.vaidya@gmail.com>
=> fix supported data types

go/vt/concurrency/error_recorder.go, go/vt/wrangler/schema.go
Fixes #2763.
Technically #​2763 is an unresolved error report, but seeing as more than a year has passed, I assume we can consider the suggested PR part of it only as a resolution.
=> Wrangler error reporting

go/vt/vttablet/tabletmanager/rpc_replication.go
While I was testing high availability and reparents, I noticed that some transactions were not completing because the database was put in RO mode while they were running.
Changing the order fixed this problem.
=> During reparent, first stop queries to vttablet, then set the db to RO

data/test/vtgate/dml_cases.txt, data/test/vtgate/unsupported_cases.txt, go/vt/vtgate/engine/update.go, go/vt/vtgate/engine/update_test.go, go/vt/vtgate/executor_dml_test.go, go/vt/vtgate/planbuilder/update.go, test/vtgatev3_test.py
The following adds support to scattered update statements.  This should complete the work started in: https://github.com/vitessio/vitess/pull/3593 
Locally and unit.
=> Adds support to scattered updates

go/vt/discovery/topology_watcher.go
Add some visibility into the internals of the topology watcher.
Signed-off-by: Michael Demmer <mdemmer@slack-corp.com>
=> add some counters for the TopologyWatcher

java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/hadoop/pom.xml, java/jdbc/pom.xml, java/jdbc/src/main/java/io/vitess/util/Constants.java, java/pom.xml
Signed-off-by: Harshit Gangal <harshit.gangal@gmail.com>
=> JDBC version change for 2.2 release

go/vt/grpcclient/client.go
* Adds gRPC client keepalive and window size knobs. 
* I tested manually that the settings are working as expected. I'm still doing work on how to tune them :)
=> Add grpc client knobs

doc/GettingStartedKubernetes.md, examples/kubernetes/configure.sh
fixed the link pointing to NFS storage on kubernetes
=> fixed dead link in doc

go/mysql/binlog_event_rbr.go, go/mysql/binlog_event_rbr_test.go
Signed-off-by: xhh1989 <xuhaihua1989@gmail.com>
=> binlog player maybe failed with decimal type

doc/GitHubWorkflow.md
Without the Signed-off-by the DCO check will fail
=> docs: suggest to use git commit -s

doc/ServerConfiguration.md
=> docs: remove duplicate /debug/health on server-configuration

doc/internal/PublishWebsite.md
Looks like this was copy-pasted from the publish info
=> docs: use the correct script for website preview

go/vt/sqlparser/comments.go, go/vt/sqlparser/comments_test.go, go/vt/vtgate/executor.go, go/vt/vtgate/executor_test.go, go/vt/vtgate/planbuilder/builder.go, go/vt/vtgate/planbuilder/delete.go, go/vt/vtgate/planbuilder/insert.go, go/vt/vtgate/planbuilder/update.go, go/vt/vttablet/tabletserver/planbuilder/plan.go, go/vt/vttablet/tabletserver/planbuilder/plan_test.go, go/vt/vttablet/tabletserver/query_engine.go, go/vt/vttablet/tabletserver/query_engine_test.go
Adds directive to skip query plan cache using comments.
=> Adds directive to skip query plan cache from comments

doc/meetups_notes/05-10-2018.md
=> Meetup notes 05-10-2018

java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/hadoop/pom.xml, java/jdbc/pom.xml, java/pom.xml
Signed-off-by: Harshit Gangal <harshit.gangal@gmail.com>
=> java: Bump SNAPSHOT version to 3.0.0 after Vitess release 2.2.0.

doc/Monitoring.md, go/cmd/vtctld/plugin_opentsdb.go, go/cmd/vtgate/plugin_opentsdb.go, go/cmd/vttablet/plugin_opentsdb.go, go/cmd/vtworker/plugin_opentsdb.go, go/stats/opentsdb/opentsdb.go, go/stats/opentsdb/opentsdb_test.go
=> Basic support for -stats_backend opentsdb

go/vt/binlog/binlog_streamer.go
I missed this bug fix. The current code doesn't update
position correctly.
=> binlog_streamer: fix position bug

java/jdbc/src/main/java/io/vitess/jdbc/VitessResultSet.java, java/jdbc/src/main/java/io/vitess/util/Constants.java, java/jdbc/src/test/java/io/vitess/jdbc/VitessResultSetTest.java
This closes PR: https://github.com/vitessio/vitess/pull/3902
=> Java zero timestamp config

java/jdbc/src/main/java/io/vitess/jdbc/VitessResultSet.java, java/jdbc/src/main/java/io/vitess/util/Constants.java, java/jdbc/src/test/java/io/vitess/jdbc/VitessResultSetTest.java
Fixes #2135.
More or less just familiarising myself with more of the codebase. I'm not super familiar with Java so my style might be out.
=> Remaining JDBC zero-timestamp config values

doc/meetups_notes/06-14-2018.md
Resubmitting doc and PR for June 2018 monthly meeting.
* Date/Time
* Access details
* Agenda
Signed-off-by: Adrianna Tan <skinnylatte@gmail.com>
=> Submitting agenda for June 2018 Vitess monthly meeting

doc/meetups_notes/06-14-2018.md
* Participants
* Meeting minutes
* Action Items
Signed-off-by: Adrianna Tan <skinnylatte@gmail.com>
=> Updated meeting notes with minutes from June 2018's vitess monthly meeting

go/vt/workflow/resharding/parallel_runner.go, go/vt/workflow/resharding/parallel_runner_test.go
Recently, I discovered that stopping an interactive workflow was still migrating the serving types. After some debugging of the code, I noticed that [waiting for approval](https://github.com/tinyspeck/vitess/blob/master/go/vt/workflow/resharding/parallel_runner.go#L132) has the following code:
```
select {
case <-firstTaskApproved:
p.mu.Lock()
defer p.mu.Unlock()
p.updateApprovalActionLocked(0, actionNameApproveFirstTaskDone, workflow.ActionStateDisabled, workflow.ActionStyleTriggered)
case <-p.ctx.Done():
return
}
```
This means that, stopping a workflow effectively approves it. For most tasks, this is not an issue because they are checking explicitly at each step if the context have been cancelled: 
```
if err := checkDone(ctx); err != nil {
return err
}
```
However, this is not the …
=> Avoid executing tasks when workflow is cancelled

go/cmd/vttestserver/main.go
=> Support specifying mysql_bind_host for vttestserver

go/vt/topo/shard.go, go/vt/worker/split_clone.go
Signed-off-by: Michael Pawliszyn <mpawliszyn@gmail.com>
=> Allow clones between differently named shards.

go/vt/vttablet/tabletmanager/action_agent.go, go/vt/vttablet/tabletmanager/state_change.go
Adds a stat to track the tablet type in a format that's exportable to Prometheus.
=> Add a stat to track the tablet type for Prometheus.

dev.env
=> dev.env: fix pypath typo

doc/VtExplain.md
Replace the output section with the more up-to-date format and add some explanatory text for how to interpret it.
=> update vtexplain docs

test/schema_swap_test.py
There is a race condition when applying the main schema, and then applying a schema swap change, that may get to replica tablets before the main schema, and therefore fail. So we just wait for the schema to be there before the schema swap.
Signed-off-by: Alain Jobart <alainjobart@google.com>
=> Fixing flakiness of schema_swap_test.py.

go/vt/vttablet/tabletmanager/action_agent.go
Signed-off-by: Michael Pawliszyn <mikepaw@squareup.com>
=> Adds the TabletAlias to the vars page json.

go/vt/topo/errors.go, go/vt/topo/server.go
Signed-off-by: Andres Taylor <antaylor@squareup.com>
=> Better error message when topology implementation is not found

go/mysql/query_benchmark_test.go
This should be indicative for changing ephemeral packets allocation strategies
=> [go/mysql] add benchmark for random query sizes

go/sqltypes/value.go, go/vt/sqlparser/analyzer.go, go/vt/sqlparser/analyzer_test.go
=> #4145 changes based on review

examples/kubernetes/guestbook/requirements.txt, test/cluster/keytar/requirements.txt
=> security: fix reported security issues

go/cmd/vtbench/vtbench.go, go/vtbench/client.go, go/vtbench/vtbench.go
* Allow vtbench to use mysql socket connections.
=> Allow vtbench to use mysql socket connections

go/vt/sqlparser/sql.go, vendor/vendor.json
It adds pgzip libraries needed for faster compression PR: https://github.com/vitessio/vitess/pull/4221
Signed-off-by: Rafael Chacon <rafael@slack-corp.com>
=> Adds dependencies needed for pull/4221

go/vt/vtgate/engine/route.go
We use this to measure impact of introducing lookup tables.
=> Metrics for scatter queries

.travis.yml, doc/GettingStarted.md, doc/GettingStartedKubernetes.md, docker/bootstrap/Dockerfile.common, test/cluster/keytar/config/vitess_config.yaml, vagrant-scripts/bootstrap_vm.sh
Just checking to see if this will pass tests, after @acharis asked about it in Slack.
cc @sougou
=> go: update to go 1.11

go/vt/vtgate/engine/route.go
As discussed in #4240 this is no longer needed.
CC @tirsen
=> Revert pull request #4235 from tirsen/scatter-metrics

go/mysql/conn.go
Signed-off-by: Alexander Morozov <lk4d4math@gmail.com>
=> [go/mysql] get rid of unnecessary switches for ephemeral policy

doc/VTTabletModes.md, vitess.io/_includes/left-nav-menu.html, vitess.io/user-guide/vtexplain.md, vitess.io/user-guide/vttablet-modes.md
Long overdue documentation on how to launch vttablet in various modes.
=> VTTablet Modes

go/vt/worker/split_clone_cmd.go, go/vt/worker/vertical_split_clone_cmd.go
=> Clarify unit for replication lag

doc/vtctlReference.md, go/vt/vtctl/vtctl.go, go/vt/wrangler/keyspace.go, test/resharding.py, test/vertical_split.py
CancelResharding works for horizontal and vertical resharding
as long as migration hasn't started.
=> resharding: CancelResharding

docker/bootstrap/Dockerfile.common, docker/bootstrap/Dockerfile.mariadb, docker/bootstrap/Dockerfile.mysql56, docker/bootstrap/Dockerfile.mysql57, docker/bootstrap/Dockerfile.percona, docker/bootstrap/Dockerfile.percona57, docker/test/run.sh, go/vt/worker/interactive.go, java/client/pom.xml, java/grpc-client/pom.xml, java/hadoop/pom.xml, java/jdbc/pom.xml, java/pom.xml, test/environment.py
The unit tests expect the user to be vitess, however that has a
negative impact on our ability to build the software inside the
containers. This specifically requires the user to be vitess for
testing
Signed-off-by: DK <dk@planetscale.com>
=> Forcing the docker unit tests builds to run with the user vitess

docker/k8s/pmm-client/Dockerfile, helm/vitess/README.md, helm/vitess/values.yaml
The updated docker image has already been pushed.
=> helm: update pmm-client from 1.14.1 to 1.15.0

go/vt/mysqlctl/backup.go
This has been tested to work on our infrastructure with both MySQL 8 and MySQL 5.7. There should be no backwards compatibility issues. The only potential side effect is if there were subdirectories that were previously ignored because they contained `.sdi` or `.ibd` files and not a `.frm` file. Those directories will now be copied and restored. There is nothing that will be excluded that was previously included.
Fixes #4307
=> mysqlctl: support MySQL 8 backups

go/vt/vttablet/tabletmanager/rpc_query.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/tabletserver.go
In a few places, we were simply dropping errors.
=> Make sure to not drop errors

docker/k8s/orchestrator/Dockerfile, helm/vitess/values.yaml
I already pushed the updated image
=> docker/helm: update orchestrator to v3.0.13

go/mysql/auth_server.go, go/mysql/flavor.go
Simplifes cases of strings.Index with strings.Contains. Inspired by https://staticcheck.io/docs/gosimple#S1003
=> simplify cases of strings.Index with strings.Contains

go/mysql/server.go
fixes #4332
Signed-off-by: Daniël van Eeden <git@myname.nl>
=> Handle AuthSwitch for MySQL 8.0 client

go/vt/servenv/grpc_server_auth_static.go
- Update error and success messages to reflect the actual grpc_server_auth flag
Signed-off-by: avaidyanatha <avaidyanatha@ucsb.edu>
=> Updating messages for grpc_server_auth

docker/k8s/Dockerfile
=> helm: include default-fast.cnf for tests and demos

docker/k8s/pmm-client/Dockerfile, helm/vitess/Chart.yaml, helm/vitess/README.md, helm/vitess/templates/_orchestrator.tpl, helm/vitess/templates/_pmm.tpl, helm/vitess/templates/_vtctld.tpl, helm/vitess/templates/_vtgate.tpl, helm/vitess/templates/_vttablet.tpl, helm/vitess/values.yaml
Lots of cleanup to the helm charts. Thanks to @msolters for the work to get `pmm-client` running more reliably.
@sougou Can you make sure that the resource changes I made didn't impact your minikube demo?
Also, I took off the beta note from the readme and bumped the chart to 1.0.
=> helm: general cleanup + pmm fixes + 1.0!

java/grpc-client/src/main/java/io/vitess/client/grpc/GrpcClientFactory.java
to implement custom consul-template based vtgate discovery at Slack
Signed-off-by: Yuichi Sasaki <ysasaki@slack-corp.com>
=> Allow to set custom LoadBalancer.Factory and NameResolver.Factory

helm/vitess/templates/_vttablet.tpl
=> helm: add missing default

go/vt/dbconfigs/dbconfigs.go
Signed-off-by: Michael Pawliszyn <mikepaw@squareup.com>
=> Adds setting the DB server name using a parameter.

go/vt/vtctl/vtctl.go
* Adds vtctl command to list all tablets in all cells. Existent one requires cell to be a parameter.
=> List all tablets in all cells

go/vt/binlog/keyspace_id_resolver.go, go/vt/vtgate/vindexes/vschema.go, go/vt/vtgate/vindexes/vschema_test.go, go/vt/worker/key_resolver.go
=> use lower cost vindex if possible when primary vindex is too expensive

examples/local/README.md, examples/local/env.sh
Signed-off-by: Jitendra Vaidya <jitendra.vaidya@gmail.com>
=> Fix docs. Make sure that env.sh does not set VTTOP if already set.

go/vt/worker/multi_split_diff.go
=> Fix MultiSplitDiff incorrectly logging "have already found differences"

go/vt/vttablet/tabletmanager/restore.go, test/backup.py
=> change ClusterAlias in _vt.local_metadata to be keyspace/shard

go/mysql/conn.go
Replacement for https://github.com/vitessio/vitess/pull/4547 as I messed up something trying to do the sign-off and couldn't figure out how to fix it. (sorry).
=> Change common unhandled packet error message to clarify origin

doc/Upgrading.md, doc/V3HighLevelDesign.md, go/vt/automation/wait_for_filtered_replication_task.go, go/vt/throttler/max_replication_lag_module_test.go, go/vt/vttablet/tabletserver/connpool/dbconn_test.go, go/vt/workflow/parallel_runner.go, test/TestingStrategy.md
=> Update the func md txt file

misc/git/hooks/unused
Signed-off-by: Tanmoy Krishna Das <tanmoykrishnadas@gmail.com>
=> fixed typo in the command to install unused

doc/GettingStarted.md, doc/meetups_notes/05-10-2018.md
1. "necessery" to "necessary" in line 171.
2. "documenation" to "documentation" in line 36.
=> Fix some typos in docs

docker/test/run.sh, go/vt/mysqlctl/cephbackupstorage/ceph.go, vendor/vendor.json
I'm not sure how to test this, though
cc @harshit-gangal @dweitzman @hmcgonig @trevex
=> update minio-go version to 6.0.16

go/vt/schemamanager/schemamanager_test.go
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
=> Fix small errors in printing

go/vt/binlog/binlogplayer/binlog_player.go, go/vt/mysqlctl/query.go, go/vt/vttablet/tabletmanager/vreplication/vplayer.go
=> Prefer predefined constants for mysql errors

doc/GettingStartedKubernetes.md, doc/ServerConfiguration.md, doc/ShardingKubernetes.md, doc/ShardingKubernetesWorkflow.md, doc/VitessOverview.md
This PR replaces deprecated links in docs with the latest and correct ones.
=> Update deprecated links in doc

examples/helm/kmysql.sh
Just a change to clarify the purpose of the script.
=> Changed the comment to refer to "the mysql client" rather than vtctlclient

go/bucketpool/bucketpool.go, go/bucketpool/bucketpool_test.go
Signed-off-by: Nguyen Hai Truong <nguyenhaitruonghp@gmail.com>
=> Adding copyright headers

doc/Troubleshooting.md, go/vt/vttablet/tabletmanager/vreplication/player_plan.go, test/worker.py
This commit intends to remove some duplicated words for reading easily.
Co-Authored-By: Nguyen Phuong An <AnNP@vn.fujitsu.com>
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
=> Remove the duplicated words

test/cache_invalidation.py, test/encrypted_transport.py, test/tabletmanager.py, test/tabletmanager2.py, test/vtgate_buffer.py
This PR fixes many typos in Vitess test code.
=> Fix many typos in test code

doc/meetups_notes/details.md
=> meetup details

MAINTAINERS.md
=> fix mismatched parens

bootstrap.sh, docker/bootstrap/Dockerfile.common, test/environment.py
There is currently a defect in chromium that causes it to crash, this pins chromium to a previous version
=> Updating chromedriver dependencies and pinning chromium version

helm/vitess/Chart.yaml
Signed-off-by: Gary Edgar <gary@planetscale.com>
=> Chart.yaml: Update icon URL

go/vt/topo/topotests/srv_keyspace_test.go
=> Fix flaky test

docker/k8s/vtexplain/Dockerfile
Signed-off-by: Vitalii <vit.stoyan@gmail.com>
=> Add vtexplain Dockerfile

go/vt/vttablet/tabletmanager/state_change.go
=> log actual error when GetSrvKeyspace fails

go/cmd/vttestserver/main.go, go/vt/vttest/local_cluster.go, go/vt/vttest/vtprocess.go
=> Add flag for extending the transaction timeout in vttestserver

docker/k8s/vtexplain/Dockerfile
Signed-off-by: Vitalii <vit.stoyan@gmail.com>
=> Change a source for vtexplain image

doc/ServerConfiguration.md, doc/TopologyService.md
specifed -> specified
symetrical -> symmetrical
=> Fix some spell problems of doc/ServerConfiguration.md doc/TopologyService.md

go/mysql/flavor.go
Signed-off-by: xichengliudui <liuduidui@beyondcent.com>
=> Using const() defines constants together

go/vt/vttablet/tabletserver/query_executor.go
When autocommit is activated, skip logging `begin` and `commit` to the vttablet query logs.
This should really be done in a more structured way by exporting the executed statements out of the TxPool, but since this is just for forensics and logging, this simpler approach should suffice.
As-yet untested but it seems like it should work :)
=> omit misleading begin/commit logs in autocommit transactions

doc/meetups_notes/06-14-2018.md, doc/vtctlReference.md
Fix spelling mistakes I found.
=> Fix spelling mistakes of doc

go/vt/vttablet/tabletconntest/fakequeryservice.go, go/vt/vttablet/tabletserver/rules/map_test.go, go/vt/workflow/resharding/workflow.go, go/vt/wrangler/cleaner.go, test.go
Signed-off-by: xichengliudui <liuduidui@beyondcent.com>
=> Using const() defines constants together (part:1)

doc/VitessApi.md, examples/helm/kmysql.sh, go/cmd/automation_client/automation_client.go, go/cmd/mysqlctl/mysqlctl.go, go/cmd/vtctld/schema.go, go/cmd/vtexplain/vtexplain.go
Find more spelling problems and fix them.
=> Fix some spelling mistakes

test/backup.py, test/xtrabackup_xtra.py
This is a regression introduced in #4803.
=> tests were running with wrong backup engine setting

go/mysql/auth_server_static.go, go/mysql/auth_server_static_test.go
Reload credentials when certain duration that is defined by the user has passed.
=> Rotate credentials for vtgate.

doc/vtctlReference.md, go/vt/topo/locks.go, go/vt/vtctl/vtctl.go, go/vt/wrangler/shard.go
* For completeness, make sure you can set IsMasterServing via a vtctl command. 
* This was a leftover of: https://github.com/vitessio/vitess/issues/4496
* Tested this locally.
=> Refactor SetShardServingTypes into SetShardIsMasterServing

web/vtctld2/src/app/workflows/workflow-list.component.ts
Signed-off-by: eleven <looker_pc@163.com>
=> should use ' to take place of "

web/vtctld2/src/app/shared/dialog/dialog-settings.ts, web/vtctld2/src/app/workflows/node.ts
Signed-off-by: eleven <looker_pc@163.com>
=> need a space before =

go/vt/vterrors/vterrors.go
=> rename flag per naming convention

go/vt/vtctl/vtctl.go
=> Fix vtctl commandline help for StringMapValues, including mentioning InitTablet tags

go/flagutil/flagutil.go, go/flagutil/flagutil_test.go
=> Add error handling for parsing StringMapValues instead of panicking

go/cacheservice/cacheservice.go
Signed-off-by: xichengliudui <liuduidui@beyondcent.com>
=> update cacheservice Using var block

examples/local/env.sh, examples/local/etcd-down.sh, examples/local/etcd-up.sh
=> Enable etcd topo server to on OSX

go/vt/servenv/grpc_server.go
=> Don't ignore grpc start up error

azure-pipelines.yml
CNCF has support from Azure to have projects use Azure DevOps. This is trying out this functionality
=> Initial Setup of azure-pipeline to run CI on Azure

go/vt/topo/etcd2topo/watch.go
- Delete watchers on retry and create new ones
- Create external context that cancels all internal watchers that have been summoned on retry
=> Fix etcd watcher leak

go/vt/topo/memorytopo/memorytopo.go
Signed-off-by: Isaac Anastasoff <isaac@planetscale.com>
=> Increased memorytopo generation pool size to 1 << 60

helm/vitess/README.md, helm/vitess/values.yaml
Rename secret name (myuser_password -> myuser-password) to matched regex pattern accepted by kubernetes and match the template example
=> Update helm/readme (myuser_password -> myuser-password)

test/config.json
In a recent build, shard 0-2 took ~15 minutes, whereas shard 3 took 35+ minutes and shard 4 took 20+ minutes.
=> rebalance tests so that travis build finishes sooner

go/vt/vtgate/resolver.go, go/vt/vtgate/resolver_test.go
Heartbeat events can OOM vtgate because they accumulate if there
are no real events. Removing it for now because the info is
currently not usable by the subscriber.
We need to think of a good model for this.
=> vstream: remove heartbeat events

examples/kubernetes/etcd-service-template.yaml
Add ETCD image repository information to facilitate the use of some intranet users
=> add etcd repository support

go/cmd/zk/zkcmd.go, go/vt/topo/zk2topo/election.go, go/vt/topo/zk2topo/error.go, go/vt/topo/zk2topo/file.go, go/vt/topo/zk2topo/lock.go, go/vt/topo/zk2topo/utils.go, go/vt/topo/zk2topo/zk_conn.go, go/vt/zkctl/zkctl.go, vendor/vendor.json
=> use z-division fork of go-zookeper

bootstrap.sh
Disable tests by default.
Fixes #4984
=> Change BUILD_TESTS default to 0

bootstrap.sh
The docker image failed to include selenium, breaking tests.
=> revert BUILD_TESTS=0

docker/bootstrap/Dockerfile.common
=> Pin Dockerfile.common base golang image to specific OS version (Debian Stretch)

go/vt/vttablet/tabletmanager/vreplication/vcopier.go
correct message for easy understanding.
Signed-off-by: ethan <guangming.wang@daocloud.io>
=> cleanup: error message word correction

go/vt/vtgate/planbuilder/select.go
Signed-off-by: ethan <guangming.wang@daocloud.io>
=> cleanup: correct word mis-spell in error msg

go/cmd/vtgateclienttest/services/echo.go, go/vt/proto/vtgate/vtgate.pb.go, java/client/src/main/java/io/vitess/client/RpcClient.java, java/client/src/test/java/io/vitess/client/RpcClientTest.java, java/grpc-client/src/main/java/io/vitess/client/grpc/GrpcClient.java
Adds the shiny, new VStream RPC to the Java GRPC client.
Signed-off-by: Paul Hemberger <phemberger@hubspot.com>
cc @leoxlin
=> add vstream to java grpc client

go/vt/vtgate/executor.go, go/vt/vtgate/executor_test.go, go/vt/vtgate/vtgate.go
=> vtgate: warning threshold for in-memory rows

go/mysql/binlog_event_json.go, go/mysql/binlog_event_json_test.go
@makmanalp
I think we've finally gotten to the bottom of this. This is mostly work by @deepthi 
Fixes #4801
Signed-off-by: Alex Charis <acharis@hubspot.com>
=> fix readVariableInt; add test

go/mysql/binlog_event_json.go, go/mysql/binlog_event_json_test.go
=> JSON String length computation: docs and unit tests

go/mysql/binlog_event_json_test.go
this silences some doubts of mine.
@deepthi 
Signed-off-by: Alex Charis <acharis@hubspot.com>
=> add a testcase to binlog_event_json_test

go/vt/vtctl/vtctl.go
Signed-off-by: John Watson <johnw@planetscale.com>
=> Fix ApplyRoutingRules -rules_file flag

go/cmd/vtbackup/vtbackup.go
If the latest backup is incomplete, we should ignore it and take another one.
Signed-off-by: Anthony Yeh <enisoc@planetscale.com>
=> vtbackup: Only consider complete backups when looking for latest backup.

go/vt/vttablet/tabletserver/txserializer/tx_serializer.go
=> cleanup: word correction in tx_serializer.go

go/vt/worker/split_clone_cmd.go, go/vt/worker/vertical_split_clone_cmd.go
=> package/worker: misspelled word in html template correction

go/vt/topo/tablet.go
Make the comment more readable
=> fix wrong spells in tablet.go

go/stats/opentsdb/opentsdb.go
Make the comment more readable
=> fix wrong spells in opentsdb.go

go/mysql/query.go, go/vt/vtgate/executor_dml_test.go
Merged prepared statement code changes did not take into account
staticcheck warnings. This PR addresses those warnings.
=> Address staticcheck warnings in prepared statement

go/vt/binlog/slave_connection.go
Make the comment more readable
=> fix wrong spells in slave_connection.go

go/vt/topo/keyspace.go, go/vt/topo/keyspace_test.go
=> keyspace.go: cleanup typo in error message

go/mysql/client.go
=> cleanup: fix typos in mysql/client.go

go/vt/vtgate/engine/insert.go
=> cleanup: engine/insert.go comment fix typo

go/vt/vttablet/tabletserver/txlogz.go
Make the comment more readable
=> fix mis-spelling in txlogz.go

go/cmd/vtclient/vtclient.go
=> vtclient: Add sequential id generation and throttling

go/vt/topo/vschema.go
=> routing rules: handle corner case in delete

go/vt/sqlparser/analyzer.go, go/vt/sqlparser/analyzer_test.go
Signed-off-by: Adam Saponara <as@php.net>
=> Fix bug in `sqlparser.Preview`

go/vt/topo/zk2topo/zk_conn.go
Make sure we re-resolve the DNS name every time we reconnect to a
server. In environments where DNS changes often such as Kubernetes we
can't cache the IP address.
=> Don't cache Zookeeper DNS

go/vt/wrangler/keyspace.go
Motivation:
I'm Yufei from Square Cash and we are using Vitess to scale our database.
We encountered an issues during a split this Monday. Basically we saw the source shard stopped taking traffic but the two target shards didn't pick up the traffic, and that leads to a downtime..
@tirsen helped us identified why the split stuck. It's because we found that our zookeeper can't refreshState on the source shard for some reason, it stuck there when running the command. 
So creating this PR to make sure we do not turn off the query service on the source if we found there is problem with either refreshState on the source or refreshState on the target
Question:
1: How to test this, i couldn't figure out how to mock the failure behavior by looking at the existing test
2: Is it worth writing a test …
=> RefreshMaster on both source and target before turning off query service on source during splitting

MAINTAINERS.md
=> maintainers: add morgo and systay

go/vt/vttablet/tabletmanager/vreplication/replicator_plan_test.go, go/vt/vttablet/tabletmanager/vreplication/table_plan_builder.go
=> vreplication: ability to exclude tables

go/trace/opentracing.go, go/trace/plugin_jaeger.go
I believe this is more idiomatic golang, and it makes it
easier to work with the code base on modern IDEs.
=> Use interfaces instead of functions

go/vt/vtgate/executor.go, test/prepared_statement_test.py
This PR fixes issue #5204 
Now it can return an appropriate error instead of panicking
=> Fixed Panic for handlePrepare in Prepared statements

doc/TwoPhaseCommitDesign.md
=> Grammar tweak

Makefile
=> Fix for #5214 by adding back bits of install_protoc-gen-go

ADOPTERS.md
=> Add New Relic to Adopters

ADOPTERS.md
=> Add Weave to adopters

MAINTAINERS.md
=> maintainers: add enisoc

go/vt/vttablet/queryservice/queryservice.go, go/vt/vttablet/tabletmanager/healthcheck.go, go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tmclient/rpc_client_api.go
=> Perfect comments

go/stats/export.go, go/vt/sqlparser/ast.go, go/vt/topo/consultopo/lock.go, go/vt/topo/etcd2topo/watch.go, go/vt/topo/memorytopo/lock.go, go/vt/topo/topoproto/destination.go
=> Correct word spelling mistakes

go/bucketpool/bucketpool_test.go, go/mysql/query_test.go
=> Improve the quality of the documents

java/jdbc/src/main/java/io/vitess/util/StringUtils.java
Signed-off-by: xichengliudui <1693291525@qq.com>
=> Update the parameter name in the comment

go/vt/vttablet/tabletmanager/rpc_external_reparent.go, go/vt/vttablet/tabletmanager/rpc_external_reparent_test.go, go/vt/wrangler/reparent.go
This reverts commit 2731866eac422d59650156c2393ce8330f689499, reversing
changes made to 698935b6368707871beb6e11b3fc224d093c8921.
=> Revert "Merge pull request #5203 from systay/never-master"

GOVERNANCE.md
Signed-off-by: xichengliudui <liuduidui@beyondcent.com>
```
1: I think Collaborators list is the Contributors list so I have updated the first connection
2: The remaining hyperlinks should have been removed
```
=> fix 404 page not found

java/client/src/main/java/io/vitess/client/RefreshableVTGateConnection.java, java/grpc-client/src/main/java/io/vitess/client/grpc/RetryingInterceptor.java, java/grpc-client/src/main/java/io/vitess/client/grpc/RetryingInterceptorConfig.java, java/grpc-client/src/main/java/io/vitess/client/grpc/StaticAuthCredentials.java, java/grpc-client/src/test/java/io/client/grpc/GrpcClientStaticAuthTest.java, java/grpc-client/src/test/java/io/client/grpc/GrpcClientWithRetriesTest.java, java/grpc-client/src/test/java/io/vitess/client/grpc/RetryingInterceptorTest.java
=> add License in *.java files in java directory

go/vt/sqlparser/parse_test.go, go/vt/sqlparser/test_queries/django_queries.txt
Relevant issue: #5166 
As per discussion with @morgo and @saifalharthi, I've written a sample test for queries which came from django. I've currently hardcoded the source file path for the log file, need to find out where to store the set of `.txt` logs which @saifalharthi has passed to me
Signed-off-by: j0 <lee.yi.jie.joel@gmail.com>
=> Test Vitess against django queries

misc/git/hooks/gofmt, misc/git/hooks/goimports, misc/git/hooks/golint, misc/git/hooks/govet, misc/git/hooks/pylint, misc/parse_cover.py
#5279 
These are unmodified files missing in #5330 .
=> add license in /misc file

go/mysql/server.go
=> Remove SSLv3 Support

proto/automation.proto, proto/automationservice.proto, proto/binlogdata.proto, proto/binlogservice.proto, proto/logutil.proto, proto/mysqlctl.proto, proto/query.proto, proto/queryservice.proto, proto/replicationdata.proto, proto/tableacl.proto, proto/tabletmanagerdata.proto, proto/tabletmanagerservice.proto, proto/throttlerdata.proto, proto/throttlerservice.proto, proto/time.proto, proto/topodata.proto, proto/vschema.proto, proto/vtctldata.proto, proto/vtctlservice.proto, proto/vtgate.proto, proto/vtgateservice.proto, proto/vtrpc.proto, proto/vttest.proto, proto/vtworkerdata.proto, proto/vtworkerservice.proto, proto/workflow.proto
=> add license in helm/misc/proto

bootstrap.sh
Make the booststrap.sh download the correct consul for aarch64
Change-Id: I7c96f7596f6c6a7496e34715d477185d55db5324
Signed-off-by: Jiamei.Xie <Jiamei.Xie@arm.com>
=> Fix consul dependency issue for arm.

Makefile, bootstrap.sh, dev.env
=> add license in other files

java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/hadoop/pom.xml, java/jdbc/pom.xml, java/pom.xml
Signed-off-by: Harshit Gangal <harshit.gangal@gmail.com>
Setting java release version to 4.0
=> [JAVA] Vitess JDBC release 4.0

.github/workflows/local-example.yml, examples/local/101_initial_cluster.sh
Relates to #5418 and several other support requests.
+ small fix to GitHub action
=> Add stronger protection against running as root

bootstrap.sh
Make the booststrap.sh install correct chromedriver for aarch64
Change-Id: Iefa98ed7918725f00fb8db131cae12383c44c42e
Signed-off-by: Jiamei.Xie <Jiamei.Xie@arm.com>
=> Fix chromedriver dependency issue for aarch64.

java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/hadoop/pom.xml, java/jdbc/pom.xml, java/pom.xml
Signed-off-by: Harshit Gangal <harshit.gangal@gmail.com>
=> java: Bump SNAPSHOT version to 4.1-SNAPSHOT after Vitess release 4.0

examples/local/101_initial_cluster.sh
This was added to master in https://github.com/vitessio/vitess/pull/5419 , but is desirable. So backporting to release-4.0 branch.
=> Back port stronger root protection

docker/lite/Dockerfile
=> change lite Dockerfile to fetch latest xtrabackup

.github/ISSUE_TEMPLATE/question.md, README.md
=> Update slack links

helm/release.sh, helm/vitess/CHANGELOG.md, helm/vitess/Chart.yaml, helm/vitess/README.md, helm/vitess/templates/_orchestrator.tpl, helm/vitess/templates/_pmm.tpl, helm/vitess/templates/_vttablet.tpl, helm/vitess/values.yaml
* update helm docker images to 1.0.7-5 which supports opentracing
* update default MySQL image to Percona 5.7.26
* documentation for enabling Jaeger opentracing
=> update helm vitess docker images

go/vt/vttablet/tabletmanager/vreplication/vplayer.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_test.go, go/vt/vttablet/tabletmanager/vreplication/vstreamer_client.go, go/vt/vttablet/tabletmanager/vreplication/vstreamer_client_test.go
=> build: fix broken build

go/vt/servenv/status.go, go/vt/vtgate/engine/delete.go, go/vt/vtgate/engine/fake_primitive_test.go, go/vt/vtgate/engine/insert.go, go/vt/vtgate/engine/join.go, go/vt/vtgate/engine/limit.go, go/vt/vtgate/engine/memory_sort.go, go/vt/vtgate/engine/ordered_aggregate.go, go/vt/vtgate/engine/primitive.go, go/vt/vtgate/engine/pullout_subquery.go, go/vt/vtgate/engine/route.go, go/vt/vtgate/engine/subquery.go, go/vt/vtgate/engine/update.go, go/vt/vtgate/engine/vindex_func.go, go/vt/vtgate/executor.go, go/vt/vtgate/executor_scatter_stats.go, go/vt/vtgate/executor_scatter_stats_test.go, go/vt/vtgate/executor_stats.go
We use something like this to keep track of expensive queries
=> Scatter query statistics

.gitignore
=> git: ignore py-vtdb instead of py-vtdb/

go.mod, go/vt/vtgate/executor.go, go/vt/vtgate/executor_test.go
=> Add fix for SHOW FULL COLUMNS when query has a qualifier

go/vt/vtgate/planbuilder/from.go, go/vt/vtgate/planbuilder/testdata/from_cases.txt
=> v3: resolve information_schema cols correctly

.github/workflows/unit_race.yml, go/mysql/auth_server_clientcert_test.go, go/mysql/auth_server_static.go, go/mysql/auth_server_static_test.go, go/mysql/handshake_test.go, go/mysql/replication_constants.go, go/mysql/server.go, go/mysql/server_test.go, go/vt/vtaclcheck/vtaclcheck.go, go/vt/vtgate/executor_test.go, go/vt/vtgate/mysql_protocol_test.go, go/vt/vtgate/plugin_mysql_server.go, go/vt/vtgate/plugin_mysql_server_test.go, go/vt/vtgate/vtgate.go, tools/unit_test_race.sh
=> tests: fix unit_race

docker/bootstrap/Dockerfile.mysql57-arm64v8, docker/bootstrap/build.sh
Install correct mysql and xtrabackup for aarch64
Change-Id: Icbb1c06b9066eac7786eccb62b5dc3737650b17e
Signed-off-by: Jiamei.Xie <Jiamei.Xie@arm.com>
=> Modify Dockerfile.mysql57 to support aarch64

.github/workflows/cluster_endtoend_shard14.yml, go/test/endtoend/backup/backup_test.go, go/test/endtoend/backup/main_test.go, go/test/endtoend/cluster/cluster_process.go, go/test/endtoend/cluster/cluster_util.go, go/test/endtoend/cluster/vttablet_process.go, go/test/endtoend/recovery/main_test.go, go/test/endtoend/recovery/recovery_test.go, go/test/endtoend/sharding/initialsharding/sharding_util.go, test/config.json
Converted [backup test](https://github.com/vitessio/vitess/blob/master/test/backup.py) to go.
=> Converted Backup test to go version

.github/workflows/unit.yml
These comments are now obsolete. The issues have been closed, and the unit tests for these matrix.name's has been enabled.
=> Remove out of date comments

.github/workflows/cluster_endtoend.yml, test/config.json
Signed-off-by: Ajeet jain <ajeet@planetscale.com>
=> [Testing] Reconfigured the matrix for endtoend cluster tests

go/test/endtoend/sharding/resharding/resharding_base.go, test/config.json
Issue: 
```
Error:      	Expected nil, but got: &mysql.SQLError{Num:2012, State:"HY000", Message:"immediate error from server errorCode=1040 errorMsg=Too many connections", Query:""}
```
Signed-off-by: Ajeet jain <ajeet@planetscale.com>
=> [Fixing endtoend cluster test] Trying to reuse the conn for bulk queries in resharding

go/vt/vtgate/planbuilder/testdata/postprocess_cases.txt, go/vt/vtgate/vtgate_test.go
Although it is spelling mistakes, it might make an affects while reading.
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
=> Remove duplicated words

docker/bootstrap/Dockerfile.mysql56, docker/orchestrator/Dockerfile
Change the short gpg key into long gpg key to avoid collisions
Change-Id: If26d2e45f5e745058a3614faa1244bfc35033d4e
Signed-off-by: Jiamei.Xie <Jiamei.Xie@arm.com>
=> Change the short gpg key into long gpg key

ADOPTERS.md
Fix http link to https link for security, modify many link
http to https in the project.
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
=> Securing many http links to https links

go/vt/sqlparser/parse_test.go
Upon merging  #5690, I noticed I left an unfortunate error buried in the testing logic. It felt wrong to leave it there without a fix! Here's the patch.
=> trivial patch to #5690 testing logic

go/mysql/conn.go
=> Address #5734 by forming MySQL error packet on query parse error during

go/vt/vtctld/vtctld.go
=> Add web_dir options back so as to not break existing binaries. Options are ignored

.github/workflows/unit.yml
=> Add percona 56 new dependency

go/vt/mysqlctl/gcsbackupstorage/gcs.go, go/vt/topo/locks.go
=> delete deprecated flags

MAINTAINERS.md
=> correct email address

go/vt/vtgate/vstream_manager.go, go/vt/vtgate/vstream_manager_test.go, go/vt/vttablet/sandboxconn/sandboxconn.go
Approach is similar to how journal events are handled by vreplication.
=> vstream: handle journal events

.github/workflows/cluster_endtoend.yml, Makefile, go/test/endtoend/cluster/topo_process.go, test.go, test/config.json, tools/e2e_go_test.sh
After all the python tests are migrated we will remove the files' names from config and update the logic in test.go
+ updated the typo in flag `--topo-flavor`
+ updated the shell script to pass all the args
+ fixed consul and zk2 setup in github actions
Signed-off-by: Ajeet jain <ajeet@planetscale.com>
=> updated config.json to use dummy file name

go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
Will address tests, etc. in #5817 ;  the pattern is unsustainable.
=> Add credentials plugin lookup for vstreamer master position lookup.

go/test/endtoend/worker/worker_test.go
Signed-off-by: saurabh <saurabh.408@gmail.com>
=> worker_test fix

doc/V3HighLevelDesign.md
Signed-off-by: Pham Duc Hanh <hanhpd@fujitsu.com>
=> trivial fix typo

go/vt/vtgate/executor.go, go/vt/vtgate/executor_test.go
=> Pass SQL_QUOTE_SHOW_CREATE keyword

go/vt/vttablet/tabletmanager/action_agent.go
=> Use a timeout to update topo during vttablet shutdown

go/vt/vtgate/executor.go, go/vt/vtgate/executor_test.go
=> Add keyword support for unique_checks

go/vt/sqlparser/analyzer_test.go, go/vt/sqlparser/parse_test.go, go/vt/vtgate/executor.go, go/vt/vtgate/executor_test.go
=> Add transaction_read_only keyword

test/config.json
Fixing unit test runs via docker . 
Signed-off-by: saurabh <saurabh.408@gmail.com>
=> Reverting unit test case docker scripts config

examples/are-you-alive/go.mod, go/test/endtoend/cellalias/cell_alias_test.go, go/test/endtoend/cluster/cluster_process.go, go/test/endtoend/sharding/base_sharding.go, go/test/endtoend/sharding/initialsharding/sharding_util.go, go/test/endtoend/sharding/mergesharding/mergesharding_base.go, go/test/endtoend/sharding/resharding/resharding_base.go
This testcase is for #5911 
As of now, we expect queries to fail unless vtgate is restarted. When the issue is fixed, the testcase can change to expect them to succeed.
=> vtgate cellsAlias test

go/test/endtoend/cluster/cluster_process.go
Cluster endtoend tests sometimes hang in GitHub Actions. The most likely problem is port conflicts.
This PR attempts to fix that.
Cc @arindamnayak
=> tests: check whether port is available before reserving

go/vt/mysqlctl/azblobbackupstorage/azblob.go
Azure uses an Async upload thread backed by a pipe to upload files. Since the Flush call doesn't wait for the upload to finish this can cause a context cancelled error. This change uses a seperate context that can be cancelled by a call to Abort()
=> Altering the context for azblob to outlive the AddFile request

go/vt/vttablet/tabletserver/planbuilder/testdata/exec_cases.txt
=> tabletserver: fix broken test

go/test/endtoend/messaging/cluster_ops_test.go, go/test/endtoend/messaging/main_test.go, go/test/endtoend/messaging/message_test.go, go/vt/vttablet/tabletserver/messager/cache.go, go/vt/vttablet/tabletserver/messager/message_manager.go, go/vt/vttablet/tabletserver/messager/message_manager_test.go, go/vt/vttablet/tabletserver/planbuilder/builder.go, go/vt/vttablet/tabletserver/planbuilder/plan_test.go, go/vt/vttablet/tabletserver/planbuilder/testdata/exec_cases.txt, go/vt/vttablet/tabletserver/query_executor_test.go, go/vt/vttablet/tabletserver/schema/load_table.go, go/vt/vttablet/tabletserver/schema/load_table_test.go, go/vt/vttablet/tabletserver/schema/schematest/schematest.go, go/vt/vttablet/tabletserver/tabletserver_flaky_test.go, go/vt/vttablet/tabletserver/testutils_test.go
Closes #5947 
Details are also covered in the issue.
=> messaging: simplified -> Breaking Change

Makefile, go/vt/proto/vtgate/vtgate.pb.go
=> proto: remove python builds

misc/git/hooks/golangci-lint
=> pre-commit: disable broken golangci-lint

go/vt/vtgate/vindexes/region_experimental.go
As a follow up to #5806, improve documentation on RegionExperimental vindex.
=> RegionExperimental: improve doc

go/test/endtoend/backup/vtctlbackup/backup_utils.go, go/vt/mysqlctl/xtrabackupengine.go
=> add option to pass in flags to xtrabackup prepare phase

go/vt/vtgate/vtgate.go
=> Fix transaction_mode parsing

helm/vitess/templates/_cron-jobs.tpl, helm/vitess/templates/_jobs.tpl, helm/vitess/templates/_keyspace.tpl, helm/vitess/templates/_orchestrator.tpl, helm/vitess/templates/_pmm.tpl, helm/vitess/templates/_shard.tpl, helm/vitess/templates/_vtctld.tpl, helm/vitess/templates/_vtgate.tpl, helm/vitess/templates/_vttablet.tpl, helm/vitess/templates/vitess.yaml, helm/vitess/values.yaml
Reverts vitessio/vitess#5853
Signed-off-by: Derek Perkins <derek@nozzle.io>
=> Revert "Enable alternate registries to be able to be used"

go/vt/vtctld/vtctld.go
I found this typo while going through the code.
=> Fix typo functionnality -> functionality

go/vt/vttablet/tabletserver/messager/message_manager.go, go/vt/vttablet/tabletserver/messager/message_manager_test.go, go/vt/vttablet/tabletserver/schema/engine_test.go, go/vt/vttablet/tabletserver/schema/load_table.go, go/vt/vttablet/tabletserver/schema/load_table_test.go, go/vt/vttablet/tabletserver/schema/schema.go
=> messaging: support min/max backoff

go/vt/servenv/servenv.go
=> For all binaries, print version output on startup

bootstrap.sh, examples/local/scripts/k3s-up.sh
Add a check with an exit to the k3s-up.sh script
Signed-off-by: Carson Anderson <ca@carsonoid.net>
=> Change bootstrap.sh k3s error to a warning

go/vt/vttablet/tabletmanager/vreplication/vplayer.go
tables in RDS.
This is a hokey way to do it, but this is necessary, since these
events come through as SBR, even if the RDS master is using RBR...
If you don't have this patch, vreplication from an RDS instance
will be overrun with errors like:
E0324 18:35:09.185588 1200506 controller.go:150] stream 2: filter rules
are not supported for SBR replication: ...
=> Skip any binlog events with DML related to the "mysql.rds_*" special

.github/workflows/cluster_endtoend.yml, .github/workflows/cluster_initial_sharding_multi.yml, test/config.json
Signed-off-by: Arindam Nayak <arindam.nayak@outlook.com>
=> Moved inital sharding multi to independent workflow

examples/compose/vtcompose/vtcompose.go
Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>
=> vtcompose: add err check

go/vt/vtgate/executor.go
=> Do not cache plan with nil instructions

go/vt/vtgate/executor.go, go/vt/vtgate/plan_execute.go
=> Revert "Stream query counts"

examples/helm/101_initial_cluster.yaml, examples/helm/201_customer_keyspace.yaml, examples/helm/202_customer_tablets.yaml, examples/helm/203_vertical_split.yaml, examples/helm/204_vertical_migrate_replicas.yaml, examples/helm/205_vertical_migrate_master.yaml, examples/helm/206_clean_commerce.yaml, examples/helm/301_customer_sharded.yaml, examples/helm/302_new_shards.yaml, examples/helm/303_horizontal_split.yaml, examples/helm/304_migrate_replicas.yaml, examples/helm/305_migrate_master.yaml, examples/helm/306_down_shard_0.yaml, examples/helm/307_delete_shard_0.yaml, examples/helm/308_final.yaml, examples/helm/kmysql.sh, helm/vitess/templates/_vttablet.tpl
* Changed commands to work with latest minikube.
* Fixed 308 script to actually delete the job.
* Fixed minikube commands to work with the latest version.
=> helm: fix examples

go/vt/vttablet/heartbeat/writer.go, go/vt/vttablet/heartbeat/writer_test.go
Fixes #5822, fixes #4071.
cc @acharis @gedgar 
=> heartbeat: create table only on master with binlog ON, use app_user not dba_user

go/vt/vttablet/tabletserver/tabletserver_test.go
=> test: deflake acl test

go/vt/sqlparser/ast.go, go/vt/sqlparser/rewriter.go, go/vt/sqlparser/sql.go, go/vt/sqlparser/sql.y, go/vt/vtgate/engine/plan_description.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/bypass_cases.txt, go/vt/vtgate/planbuilder/testdata/ddl_cases.txt, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/planbuilder/testdata/memory_sort_cases.txt, go/vt/vtgate/planbuilder/testdata/other_admin_cases.txt, go/vt/vtgate/planbuilder/testdata/other_read_cases.txt, go/vt/vtgate/planbuilder/testdata/postprocess_cases.txt, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/planbuilder/testdata/set_cases.txt, go/vt/vtgate/planbuilder/testdata/set_sysvar_cases.txt, go/vt/vtgate/planbuilder/testdata/use_cases.txt, go/vt/vtgate/planbuilder/testdata/vindex_func_cases.txt, go/vt/vtgate/planbuilder/testdata/wireup_cases.txt
In the plan descriptions, there is no need to add an empty `Variant`.
=> Misc cleanups

go/vt/vtgate/planbuilder/builder.go, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
=> Fixed error message on database ddl query execution

examples/local/205_clean_commerce.sh, test/local_example.sh
=> Local example: Drop commerce tables after they are moved to the customer keyspace

go/vt/topo/etcd2topo/server_test.go
Signed-off-by: Zhang Zhihui <zhangzh.fnst@cn.fujitsu.com>
=> etcd2topo/server_test: add err check

go/vt/sqlparser/parse_test.go, go/vt/sqlparser/token.go
https://dev.mysql.com/doc/refman/8.0/en/identifiers.html
=> parser: allow '$' in identifiers

go/test/endtoend/vtgate/lookup_test.go, go/test/endtoend/vtgate/sequence/seq_test.go, go/vt/vtgate/endtoend/lookup_test.go, go/vt/vtgate/vindexes/consistent_lookup.go, go/vt/vtgate/vindexes/consistent_lookup_test.go
=> Fix owned table name formatting and duplicate error code in consistent lookup

go/test/endtoend/vtgate/setstatement/sysvar_test.go, go/vt/vtgate/safe_session.go
=> make setsysvar map for first time

go/vt/vtgate/executor_set_test.go
=> enable set statement test

examples/local/205_clean_commerce.sh
This is updated in the Docs here: https://github.com/vitessio/website/pull/451
=> Change local example to use DropSources

go/vt/mysqlctl/s3backupstorage/retryer.go, go/vt/mysqlctl/s3backupstorage/s3.go
Fixes a known issue in release by backporting #6182
=> Backport s3 retry from #6182 to release branch

go/vt/vtgate/executor.go, go/vt/vtgate/executor_test.go, go/vt/vtgate/plan_execute.go, go/vt/vtgate/plan_executor_test.go, go/vt/vtgate/vcursor_impl.go, go/vt/vtgate/vcursor_impl_test.go
=> Get cached vschema from executor

go/vt/vtgate/executor.go, go/vt/vtgate/executor_test.go
Signed-off-by: Adam Saponara <as@php.net>
=> Fix panic with `select database()` in OLAP mode (#6200)

go/vt/vttablet/tabletmanager/vreplication/external_connector_test.go
=> Ext Connector Test: Fix race conditions while expecting queries

go/vt/vtexplain/vtexplain_flaky_test.go, go/vt/vtexplain/vtexplain_vtgate.go
=> vtexplain: use DiscoveryGateway with LegacyHealthCheck

go/cmd/vtcombo/main.go, go/cmd/vtcombo/status.go
=> vtcombo: use new gateway/healthcheck

go/netutil/netutil_test.go
Signed-off-by: ZouYu <zouy.fnst@cn.fujitsu.com>
=> Add unit test for ResolveIPv4Addrs

java/pom.xml
=> Bump Netty to 4.1.48.Final and tcnative to 2.0.30.Final

go/vt/vtgate/executor.go, go/vt/vtgate/executor_test.go
Signed-off-by: Adam Saponara <as@php.net>
=> backport #6205 to 6.0 release branch

go/test/endtoend/vtgate/setstatement/udv_test.go, go/vt/sqlparser/expression_rewriting.go, go/vt/sqlparser/expression_rewriting_test.go, go/vt/vtgate/evalengine/expressions.go, go/vt/vtgate/executor.go, go/vt/vtgate/executor_select_test.go
=> backport #6308 to 6.0 release branch

go/vt/vttablet/endtoend/misc_test.go
=> tests: deflake TestConsolidation

go/vt/vttablet/tabletserver/tabletenv/config.go, go/vt/vttablet/tabletserver/tabletenv/config_test.go
=> config: fix heartbeat interval regression

go/vt/sqlparser/parse_test.go
=> more dollar sign tests

go/vt/vttablet/tabletserver/tabletenv/config.go, go/vt/vttablet/tabletserver/tabletenv/config_test.go
=> backport #6357 (config: fix heartbeat interval regression) to 6.0 release branch

go/vt/vtgate/endtoend/vstream_test.go, go/vt/vtgate/vstream_manager.go
Ref: https://github.com/vitessio/vitess/issues/6391
=> VStream Client: send current position events immediately

go/vt/workflow/resharding/mock_resharding_wrangler_test.go, go/vt/workflow/resharding/resharding_wrangler.go, go/vt/workflow/resharding/workflow.go
=> ReshardingWorkflow: rename interface to address linter suggestion

go/vt/vttablet/tabletmanager/rpc_lock_tables.go
We were leaking a connection every time we failed to acquire the lock.
=> TabletManager: Fix DBA conn leak in LockTables.

go/vt/vttablet/endtoend/vstreamer_test.go, go/vt/vttablet/tabletserver/schema/tracker.go
=> schema_version table: change schemax to longblob

go/vt/vttablet/tabletserver/tabletserver_test.go, go/vt/vttablet/tabletserver/tx_engine_test.go
=> updated parameter list in test to new method

go/test/endtoend/cluster/cluster_util.go
Signed-off-by: Arindam Nayak <arindam.nayak@outlook.com>
=> removed error check while verifying the replication

go/vt/vttablet/tabletserver/schema/tracker.go
=> Schema version table: create _vt db if required

go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/planbuilder/select.go, go/vt/vtgate/planbuilder/testdata/lock_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
=> block lock function usage other than dual table

java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/jdbc/pom.xml, java/pom.xml
=> [java] bump java version to 7.0 for release-7.0

java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/jdbc/pom.xml, java/pom.xml
=> [java] bump java version to 8.0.0-SNAPSHOT for next release

go/vt/vtgate/executor_set_test.go, go/vt/vtgate/planbuilder/set.go
=> Settings tweak backport

doc/releasenotes/7_0_0_release_notes.md
I thought it would be a good idea to store the release notes in version control.
For future releases we can start a working document early on and edit it until we are done.
=> 7.0.0 release notes

go/mysql/flavor.go, go/vt/mysqlctl/mycnf_gen.go, go/vt/topo/tablet.go, go/vt/vttablet/tabletmanager/restore.go, go/vt/wrangler/cleaner.go
A few were missed in the previous round, and some crept in through PRs.
=> replace more uses of slave with replica/replication

go/vt/discovery/healthcheck.go, go/vt/discovery/healthcheck_test.go, go/vt/discovery/tablet_health_check.go, go/vt/vtgate/vschema_manager.go
Do not add tablet that is going down.
=> Add diagnostic logging to healthcheck.

go/vt/vttablet/endtoend/main_test.go, go/vt/vttablet/endtoend/reserve_test.go, go/vt/vttablet/tabletserver/query_executor.go
=> backport #6514 to 7.0 release branch

go/vt/vtgate/executor.go, go/vt/vtgate/executor_set_test.go
=> Backport of 6495 to release 6.0

go/test/endtoend/vtgate/lookup_test.go, go/vt/vtgate/planbuilder/dml.go, go/vt/vtgate/planbuilder/testdata/dml_cases.txt
Fixes: https://github.com/vitessio/vitess/issues/6541
=> support vindex update or delete when destination is provided by client in dml query

go/test/endtoend/vtgate/misc_test.go, go/vt/vttablet/tabletserver/planbuilder/plan.go
=> Make sure to handle EXPLAIN on tablets

go/vt/discovery/tablets_cache_status.go, go/vt/vtgate/scatter_conn.go, go/vt/vttablet/tabletserver/health_streamer.go, go/vt/vttablet/tabletserver/schema/historian.go, go/vt/vttablet/tabletserver/schema/historian_test.go, go/vt/vttablet/tabletserver/schema/tracker.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go, go/vt/wrangler/materializer.go, go/vt/wrangler/materializer_test.go, go/vt/wrangler/vexec.go
=> build: replace gogo proto with golang

go/test/endtoend/vreplication/cluster.go, go/vt/discovery/healthcheck_test.go, go/vt/discovery/legacy_healthcheck_flaky_test.go, go/vt/discovery/tablet_picker.go, go/vt/discovery/tablet_picker_test.go, go/vt/worker/legacy_split_clone_test.go, go/vt/worker/multi_split_diff_test.go, go/vt/worker/split_clone_flaky_test.go, go/vt/worker/split_diff_test.go, go/vt/worker/vertical_split_clone_test.go, go/vt/worker/vertical_split_diff_test.go, go/vt/wrangler/testlib/apply_schema_flaky_test.go, go/vt/wrangler/testlib/backup_test.go, go/vt/wrangler/testlib/copy_schema_shard_test.go, go/vt/wrangler/testlib/emergency_reparent_shard_test.go, go/vt/wrangler/testlib/external_reparent_test.go, go/vt/wrangler/testlib/migrate_served_from_test.go, go/vt/wrangler/testlib/migrate_served_types_test.go, go/vt/wrangler/testlib/permissions_test.go, go/vt/wrangler/testlib/planned_reparent_shard_test.go, go/vt/wrangler/testlib/reparent_utils_test.go, go/vt/wrangler/testlib/version_test.go, go/vt/wrangler/traffic_switcher_env_test.go, go/vt/wrangler/traffic_switcher_test.go
Backport of #6546 
Co-authored-by: Rohit Nayak <rohit@planetscale.com>
=> tablet_picker: keep trying to find a tablet until context expires 

examples/compose/vtcompose/vtcompose.go, examples/compose/vttablet-up.sh
context: https://github.com/vitessio/vitess/pull/6584
as per @deepthi 's review, I'm cherry-picking https://github.com/vitessio/vitess/pull/6584's change into `release-7.0`
=> vtcompose/docker-compose: fix InitShardMaster

go/pools/numbered.go, go/pools/numbered_test.go, go/vt/vttablet/endtoend/connkilling/connkiller_test.go, go/vt/vttablet/endtoend/connkilling/main_test.go, go/vt/vttablet/endtoend/connkilling/reserve_test.go, go/vt/vttablet/endtoend/framework/server.go, go/vt/vttablet/tabletserver/stateful_connection.go, go/vt/vttablet/tabletserver/stateful_connection_pool.go, go/vt/vttablet/tabletserver/tx_engine.go, go/vt/vttablet/tabletserver/tx_pool.go
=> Backport: Close Idle reserved connections and Rollback Idle transactions: Release 7.0

go/mysql/constants.go
=> Trivial copy-pasta comment fixup

go/test/endtoend/cluster/vtgate_process.go, go/test/endtoend/vtgate/setstatement/main_test.go, go/vt/vtgate/executor_set_test.go, go/vt/vtgate/planbuilder/builder.go, go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/planbuilder/set.go, go/vt/vtgate/planbuilder/testdata/set_sysvar_disabled_cases.txt, go/vt/vtgate/vcursor_impl.go, go/vt/vtgate/vtgate.go
enabled as default on master
disabled as default on release 7.0 branch
#6562
=> ForwardPort: Passthrough System Variables enabled on flag

go/vt/discovery/fake_healthcheck.go, go/vt/vtgate/discoverygateway.go, go/vt/vtgate/discoverygateway_test.go, go/vt/vtgate/tabletgateway.go, go/vt/vtgate/tabletgateway_test.go
=> tablet gateway: unit tests

go/sqltypes/proto3_test.go
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>
=> Add unit test for func Proto3ValuesEqual.

go/vt/wrangler/vexec.go, go/vt/wrangler/vexec_test.go
We were not proto3-decoding the result.
=> Fix workflow CopyState fetching (and thus printing).

go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_init_test.go
=> Backport: tm: add more logging to checkMastership

go/cmd/vtbackup/vtbackup.go, go/test/endtoend/backup/vtbackup/backup_only_test.go, go/vt/mysqlctl/backup.go, go/vt/vttablet/tabletmanager/restore.go, go/vt/wrangler/testlib/backup_test.go
=> Backport restore: do not change tablet type to RESTORE if not actually performing a restore

.github/CODEOWNERS
=> add andres and harshit as code owners to query routing part

MAINTAINERS.md
=> maintainers: add shlomi-noach

go/vt/vttablet/tabletserver/tabletenv/config.go, go/vt/vttablet/tabletserver/tabletenv/config_test.go
=> Backport: Turn off schema tracker by default

go/test/endtoend/vreplication/config.go, go/vt/wrangler/vdiff.go
Backporting #6640  
Signed-off-by: Rohit Nayak rohit@planetscale.com
=> Backport: VDiff: fix panic for tables with a unicode_loose_md5 vindex

go/test/endtoend/vtgate/setstatement/sysvar_test.go, go/vt/vtgate/safe_session.go
=> [Backport] Fix reserved connection in autocommit mode on DML #6748

go/vt/sqlparser/ast.go, go/vt/sqlparser/precedence_test.go, go/vt/sqlparser/tracked_buffer.go
=> Backport #6758 operator precedence must take associativity into consideration

go/vt/sqlparser/ast.go, go/vt/sqlparser/precedence_test.go, go/vt/sqlparser/tracked_buffer.go
=> Backport of #6758 operator precedence must take associativity into consideration

.github/CODEOWNERS
=> Add myself (Rohit) to CODEOWNERS

go/vt/mysqlctl/schema.go, go/vt/mysqlctl/tabledefinitions_test.go
=> sort tabledefinitions before comparing them

MAINTAINERS.md
[Alkin](https://github.com/askdba) will be helping us with community, developer relations, releases etc.
=> Add Alkin to maintainers

bootstrap.sh
=> download zookeeper 3.4.14 from archive site

go/mysql/auth_server_static_test.go
=> Stabilize test

go/vt/wrangler/vexec.go, go/vt/wrangler/vexec_test.go
rather print no output if there are no workflows.
=> Workflow listall with no workflows was missing newline

go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go
To avoid the quagmire of character set/collations, vreplication does a "set names binary" on its source and target connections. While this works for common materializations, if a filter contains a mysql string function, mysql reports an "invalid string" while converting the raw bytes to a string. 
This PR shows a workaround where the user can cast the column as part of the filter using the correct charset/collation. 
We need to see if there is a proper solution to fix this reliably.
=> Materialization and character sets: Add test to verify/demo a workaround for charset issues while using string functions in filters

MAINTAINERS.md
=> Add Rohit Nayak to maintainers

go/vt/vttablet/tabletserver/tabletserver.go
This PR corrects how health is determined for non-serving tablet types, such as SPARE.
=> Correct Health Check for Non-Serving Types

java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/jdbc/pom.xml, java/pom.xml
Update version to 8.0.0 for release
=> [8.0] [Java] Update version to 8.0.0 for release

java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/jdbc/pom.xml, java/pom.xml
=> [Java] Bump SNAPSHOT version to 9.0 after Vitess release 8.0

go/test/endtoend/vtgate/unsharded/main_test.go, go/vt/vttablet/tabletserver/planbuilder/permission.go, go/vt/vttablet/tabletserver/planbuilder/plan.go, go/vt/vttablet/tabletserver/planbuilder/testdata/exec_cases.txt, go/vt/vttablet/tabletserver/query_executor.go, test/config.json
Added end to end test folder to config.json and fixes a bug in load from statement's permissions required.
=> Fixes a bug in Load From statement

go/test/endtoend/vreplication/config.go, go/vt/vttablet/tabletserver/vstreamer/snapshot_conn.go
=> Backport #6845

go/vt/discovery/tablet_picker.go, go/vt/wrangler/vdiff.go
=> VDiff/Tablet Picker: fix issue where vdiff sleeps occasionally for tablet picker retry interval

tools/rowlog/rowlog.go, tools/rowlog/rowlog.md
Tool developed while researching a issue faced during a migration. More details in the doc which is part of this PR
=> VReplication: Tool to diagnose vreplication issues in production

go/vt/discovery/tablet_picker.go, go/vt/wrangler/vdiff.go
=> VDiff/Tablet Picker: fix picker retry logic to handle canceled context

doc/releasenotes/8_0_0_release_notes.md
Forward port of #6790
Release notes for 8.0
=> 8_0_0 Release Notes

docker/k8s/vttablet/Dockerfile, docker/lite/install_dependencies.sh
Adds curl as a dependency of the lite images
fixes #6962
=> Adding curl as dependency

go/sqltypes/type.go
Signed-off-by: zouyu <zouy.fnst@cn.fujitsu.com>
=> Fix comment typo

go/vt/sysvars/sysvars.go
Closes: https://github.com/vitessio/vitess/issues/5076
=> allow time_zone in reserved connection

go/vt/binlog/binlogplayer/binlog_player.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletmanager/vreplication/stats.go, go/vt/vttablet/tabletmanager/vreplication/stats_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go
Fixes https://github.com/vitessio/vitess/issues/6946
=> VReplication: Don't update tx timestamp on heartbeat

README.md
=> Updates to Contacts section as Reporting

go/test/endtoend/vtgate/aggr_test.go, go/test/endtoend/vtgate/misc_test.go, go/vt/vtgate/engine/distinct_test.go, go/vt/vtgate/planbuilder/ordered_aggregate.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
Use distinct primitive to solve more queries.
=> Use distinct primitive to solve more queries

go/vt/sqlparser/parse_table.go, go/vt/sqlparser/parse_table_test.go, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/planbuilder/testdata/schema_test.json, go/vt/vtgate/vindexes/vschema.go, go/vt/vtgate/vindexes/vschema_test.go
Fixes #6123
There is currently no documentation of vschema that I can update. I will work on creating a full spec for the vschema. At that point, I'll cover this change also.
=> vschema: support back-quoted names

go/vt/vttablet/tabletserver/tabletserver.go
Fixes the `/healthz` issue raised in #6822 
=> Fix regression in /healthz

MAINTAINERS.md
Updating Email Associated with Maintainer Account
=> Updating Email Address

.github/CODEOWNERS
=> Update morgo changes

go/vt/proto/vschema/vschema.pb.go, proto/vschema.proto
Signed-off-by: David Morhovich <david@planetscale.com>
=> Fixes comment to mention the existence of reference tables.

java/client/pom.xml, java/grpc-client/pom.xml, java/grpc-client/src/main/java/io/vitess/client/grpc/GrpcClientFactory.java, java/grpc-client/src/main/java/io/vitess/client/grpc/StaticAuthCredentials.java, java/jdbc/pom.xml, java/jdbc/src/test/java/io/vitess/jdbc/VitessPreparedStatementTest.java, java/jdbc/src/test/java/io/vitess/jdbc/VitessResultSetTest.java, java/jdbc/src/test/java/io/vitess/jdbc/VitessStatementTest.java, java/pom.xml
Cherry-picked the changes from #6923 without the `go` changes. 
Does this look OK, @dkhenry?
=> Updating Java unit tests for JDK9+ compatability

doc/V3HighLevelDesign.md
Found a minor markdown error while reading the doc and decided to file a PR
YES | NO
READY
Fix minor typo in `V3 high level design documentatino`
=> Fix trivial typo

docker/lite/Dockerfile.ubi7.mysql57, docker/lite/Dockerfile.ubi7.mysql80, docker/lite/Dockerfile.ubi7.percona57, docker/lite/Dockerfile.ubi7.percona80
=> Fix broken package ref in UBI docker build

examples/demo/README.md
added readme for the demo example
- 
=> added readme for the demo example

go/sqltypes/result_test.go
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>
- 
=> Add unit test case to improve test coverage for go/sqltypes/result.go

go/vt/orchestrator/agent/agent_dao.go
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>
=> Fix incorrect comments

.github/pull_request_template.md
=> Add VTAdmin to list of components in PR template

go/vt/sqlparser/ast.go, go/vt/sqlparser/parse_test.go
Fixed Create Table format method to format the parsed query correctly.
Fixes https://github.com/vitessio/vitess/issues/7195
=> fix create table format function to include if not exists

Makefile
- 
It was required to have mysqlctl as well as mysqlctld cc: @sougou 
=> Add mysqlctl to docker images

go/vt/wrangler/vexec.go, go/vt/wrangler/vexec_plan.go, go/vt/wrangler/vexec_test.go, go/vt/wrangler/wrangler_env_test.go
=> Backport 7342: Workflow Show: use timeUpdated to calculate vreplication lag

go/vt/vtctl/vtctl.go
Original issue: https://github.com/vitessio/vitess/pull/7361
=> Backport 7361: vtctl: Add missing err checks for VReplication v2

go/mysql/conn_test.go
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>
- 
=> Fix some comment typos

java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/jdbc/pom.xml, java/pom.xml
Change Java version to 9.0 for release.
=> Update Java version to 9.0

doc/releasenotes/9_0_0_release_notes.md
=> 9.0.0 Release Notes

java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/jdbc/pom.xml, java/pom.xml
Updates the pom files to use the version on `master`, which is v10.0.0
=> update java versions to 10.0.0

.github/CODEOWNERS
@vmg for /go/cache
@GuptaManan100 for /go/vt/sqlparser
=> Add new code owners

go/vt/vtctl/reparentutil/emergency_reparenter_test.go
=> Fix unit test fail after merge

README.md, SEVERITY.md
https://github.com/vitessio/vitess/issues/7485
- 
=> Add Severity Labels document

go/test/fuzzing/oss_fuzz_build.sh
This PR adds the OSS-fuzz build script to Vitess's own repository. Currently this build script is hosted on OSS-fuzz's repository, and I am moving it over here to make it easier to make modifications to it such as adding new fuzzers.
Once this PR is merged, I will amend the necessary changes on the OSS-fuzz side.
Note: This adds a new `fuzzing` directory to `/go/test `
None
=> Fuzzing: Add oss-fuzz build script

README.md
Just shuffling punctuation around 😄 
N/A
N/A 
=> Move some commas around in README.md :)

MAINTAINERS.md
Add Andrew Mason to Maintainers List
=> Add Andrew Mason to Maintainers List

go/test/endtoend/vtgate/misc_test.go, go/vt/vtexplain/testdata/multi-output/selectsharded-output.txt, go/vt/vtexplain/testdata/selectsharded-queries.sql, go/vt/vtgate/planbuilder/filtering.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt
=> [9.0] make sure to handle subqueries on top of subqueries

java/pom.xml
Updating Guava dependency to 31.1.1-jre.
=> [Java] Guava update to 31.1.1

go/vt/vtgate/executor.go
=> [9.0] make sure to not log sensitive information

doc/releasenotes/10_0_0_release_notes.md, go/vt/servenv/version.go
In preparation for v10.0.RC1 release notes. 
- 
=> 10_0_RC1 Release Notes

go/vt/servenv/version.go
Updating latest snapshot image version. 
=> Update version for latest snapshot

go/vt/vtgate/semantics/analyzer_test.go
small PR that just turns one test into a table driven test
=> clean up test

go/stats/statsd/statsd_test.go
=> TestMakeCommonTags Flaky Test: match elements 

go/vt/vtadmin/cluster/discovery/discovery.go, go/vt/vtexplain/vtexplain.go, go/vt/vtexplain/vtexplain_vttablet.go, go/vt/vtexplain/vtexplain_vttablet_test.go, go/vt/vttablet/tabletmanager/tm_init.go
This PR fixes all the racy tests in our unit test suite that I've managed to reproduce locally. @shlomi-noach: these are all legit and should get the build closer to consistently green, but if you can think of any flaky race that I've missed, please let me know.
- 
=> ci: fix all racy tests

go/test/endtoend/vtgate/reservedconn/reconnect1/main_test.go, go/test/endtoend/vtgate/reservedconn/reconnect2/main_test.go, go/vt/discovery/fake_healthcheck.go, go/vt/discovery/healthcheck.go, go/vt/srvtopo/resolver.go, go/vt/vterrors/constants.go, go/vt/vtgate/discoverygateway.go, go/vt/vtgate/gateway.go, go/vt/vtgate/safe_session.go, go/vt/vtgate/scatter_conn.go, go/vt/vtgate/scatter_conn_test.go, go/vt/vtgate/tabletgateway.go, go/vt/vtgate/tx_conn.go, go/vt/vttablet/sandboxconn/sandboxconn.go, go/vt/vttablet/tabletconntest/fakequeryservice.go, go/vt/vttablet/tabletserver/state_manager.go, go/vt/vttablet/tabletserver/state_manager_test.go, test/config.json
=> [10.0] Fix bug with reserved connections to stale tablets

go.mod, go/vt/vttablet/tabletserver/debugenv.go, go/vt/vttablet/tabletserver/health_streamer.go, go/vt/vttablet/tabletserver/state_manager.go
=> [10.0] Allow modification of tablet unhealthy_threshold via debugEnv

java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/jdbc/pom.xml, java/pom.xml
Preparing Java packages for 10.0 release
=> java: prepare java version for release 10.0

go/test/fuzzing/oss_fuzz_build.sh, go/vt/vtgate/engine/fuzz_flaky_test.go
This PR adds a fuzzer for `vtgate/engine`.
It also updates the OSS-fuzz build file to include this fuzzer.
=> vtgate/engine: Add fuzzer

go/vt/vttablet/tabletserver/vstreamer/fuzz.go
This PR adds a fuzzer for the vstreamer package.
Adding the build instruction for OSS-fuzz in a separate PR.
Feel free to merge if CI is green.
=> vstreamer: Add fuzzer

go/test/fuzzing/oss_fuzz_build.sh, go/vt/vtgate/planbuilder/fuzz.go
This PR fixes the planbuilder and adds it to the OSS-fuzz build script.
=> Planbuilder: Fix fuzzer

go/sqltypes/value.go, go/vt/sqlparser/parse_test.go
Fixes encoding of sql strings
Fixes #8026
=> Fixes encoding of sql strings

Makefile
=> Automate version naming and release tagging

go/test/endtoend/vtgate/reservedconn/reconnect1/main_test.go, go/test/endtoend/vtgate/reservedconn/reconnect2/main_test.go, go/vt/discovery/fake_healthcheck.go, go/vt/discovery/healthcheck.go, go/vt/srvtopo/resilient_server_test.go, go/vt/srvtopo/resolver.go, go/vt/vterrors/constants.go, go/vt/vtgate/discoverygateway.go, go/vt/vtgate/gateway.go, go/vt/vtgate/safe_session.go, go/vt/vtgate/scatter_conn.go, go/vt/vtgate/scatter_conn_test.go, go/vt/vtgate/tabletgateway.go, go/vt/vtgate/tx_conn.go, go/vt/vttablet/sandboxconn/sandboxconn.go, go/vt/vttablet/tabletconntest/fakequeryservice.go, go/vt/vttablet/tabletserver/state_manager.go, go/vt/vttablet/tabletserver/state_manager_test.go, test/config.json
=> [9.0] Fix bug with reserved connections to stale tablets

go/vt/vtgate/planbuilder/ddl.go, go/vt/vtgate/planbuilder/testdata/bypass_cases.txt
* Backports https://github.com/vitessio/vitess/pull/8013 to 9.0.
=> [9.0] ddl bypass planner

go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/traffic_switcher_test.go
=> MoveTables: Refresh SrvVSchema and source tablets on completion

examples/operator/101_initial_cluster.yaml, examples/operator/201_customer_tablets.yaml, examples/operator/302_new_shards.yaml, examples/operator/306_down_shard_0.yaml, examples/operator/operator.yaml, examples/operator/vtorc_example.yaml
Pin Vitess and Operator versions to examples.
=> Post v10.0.1 updates

web/vtadmin/package-lock.json, web/vtadmin/package.json, web/vtadmin/src/components/Icon.tsx, web/vtadmin/src/components/routes/Debug.module.scss, web/vtadmin/src/components/routes/Debug.tsx, web/vtadmin/src/components/routes/Schema.module.scss, web/vtadmin/src/components/routes/Schema.tsx, web/vtadmin/src/components/routes/Schemas.tsx, web/vtadmin/src/components/routes/Workflows.tsx, web/vtadmin/src/components/tooltip/HelpTooltip.module.scss, web/vtadmin/src/components/tooltip/HelpTooltip.tsx, web/vtadmin/src/components/tooltip/Tooltip.module.scss, web/vtadmin/src/components/tooltip/Tooltip.tsx, web/vtadmin/src/index.css
Finally! Hopefully the code is well-documented enough to be self-explanatory. 
I wish I could say the same for the help-text I added, but I am by no means a copywriter of any skill so suggestions are (always) welcome. 
Here's some screenshots:
N/A
N/A
=> [vtadmin-web] Add Tooltip + HelpTooltip components

go/vt/vttablet/onlineddl/executor.go
Online DDL: tablets do periodic checks to see whether new migrations were submitted, and also, in the case of VReplication, they do periodic checks to see if a migration is completed. The normal check interval is `1 minute`, and there's already some boosting whenever we heuristically expect more work to come.
This PR adds a bit more boost: whenever new migration_ starts_, we schedule more _ticks_ tun run within the next X seconds. These help us with very quick migrations, in particular VReplication, which runs independently and asycnhronously.
Meaning, we will detect sonner, rather than later, that a VReplication migration is complete, and will move on, sooner rather than later, to the next migraiton.
- Tracking: #6926
=> OnlineDDL: more migration check ticks upon migration start

doc/releasenotes/8_0_0_release_notes.md
Document #8080 as a known issue.
#8080
=> 8.0.0: update release notes with known issue #8080

doc/releasenotes/9_0_0_release_notes.md
Document #8080 as a known issue.
#8080
=> 9.0.0: update release notes with known issue #8080

doc/releasenotes/10_0_0_release_notes.md
Document #8080 as a known issue.
#8080
=> 10.0.0: update release notes with known issue #8080

doc/releasenotes/10_0_0_release_notes.md
Add Known Issues to 10.0 release notes.
=> Release notes: add Known Issues

go/test/endtoend/vtctldweb/vtctld_web_main_test.go, tools/rowlog/rowlog.go
Signed-off-by: Zou Yu <zouy.fnst@cn.fujitsu.com>
=> Fix some static check warning

go/test/endtoend/tabletgateway/buffer/buffer_test.go, go/vt/vtgate/buffer/buffer.go, go/vt/vtgate/scatter_conn.go, go/vt/vttablet/tabletserver/state_manager.go, go/vt/vttablet/tabletserver/tx_engine.go, go/vt/vttablet/tabletserver/tx_engine_test.go
Reserved connections were not working well during reparenting. This PR makes it work.
=> Fix buffering when using reserved connections

.github/workflows/pr-labels.yml
followup to #8147 
the workflow doesn't seem to kick when labels are added to a PR. This PR attempts to fix this.
#8146
=> trigger pr-labels workflow when labels added/removed from PR

doc/releasenotes/9_0_2_release_notes.md, java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/jdbc/pom.xml, java/pom.xml
=> Release 9.0.2

doc/releasenotes/10_0_2_release_notes.md, go/vt/servenv/version.go, java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/jdbc/pom.xml, java/pom.xml
=> Release 10.0.2

go/vt/vtgate/planbuilder/route_planning.go
Minor refactoring to make the code easier to read and extend.
=> gen4: minor refactoring to improve readability

Makefile
Signed-off-by: Gary Edgar <gary@planetscale.com>
=> Makefile: fix cross-build comments

doc/releasenotes/9_0_0_release_notes.md
This pull request addresses issues with the Version 9 Release Notes. 
https://github.com/vitessio/vitess/issues/8212
=> Updates and Corrections to v9 Release Notes

go/test/endtoend/recovery/unshardedrecovery/recovery.go, go/vt/mysqlctl/xtrabackupengine.go
Updates the 10.0 branch with fixes from the 9.0 branch
#8340
=> Merge 9.0 into 10.0

doc/releasenotes/9_0_0_release_notes.md
Merging the `release-9.0` branch into the `release-10.0` branch since there has been a few changes in the former.
=> Merge release-9.0 into release-10.0

go/test/endtoend/cluster/topo_process.go
=> endtoend: change log level of etcd start from error to info
