go/cmd/vtctld/vtctld.go
go/vt/topo/test/faketopo/faketopo.go
go/vt/vtctl/plugin_zktopo.go
go/vt/vtctl/reparent.go
go/vt/vtctl/vtctl.go
go/vt/worker/split_clone.go
go/vt/worker/split_clone_test.go
go/vt/worker/topo_utils.go
go/vt/worker/vertical_split_clone.go
go/vt/wrangler/cleaner.go
go/vt/wrangler/clone.go
go/vt/wrangler/keyspace.go
go/vt/wrangler/rebuild.go
go/vt/wrangler/reparent.go
go/vt/wrangler/reparent_action.go
go/vt/wrangler/reparent_brutal.go
go/vt/wrangler/reparent_graceful.go
go/vt/wrangler/schema.go
go/vt/wrangler/shard.go
go/vt/wrangler/split.go
go/vt/wrangler/tablet.go
go/vt/wrangler/testlib/fake_tablet.go
go/vt/wrangler/wrangler.go
go/vt/wrangler/zkns.go

@enisoc @aaijazi 
Almost there on removing context from wrangler.

Replication

---

bootstrap.sh
doc/GettingStarted.md
test/environment.py

- Check for missing environment variables and emit a more useful error.
- Don't try to run as root, since it doesn't work anyway.
- Update recommended versions in GettingStarted.md.
- Add instructions for testing with etcd.

Address some common Getting Started issues.

---

go/vt/topotools/topology.go
go/vt/topotools/topology_test.go

Displaying only the first part of the IP is not useful.

Don't shorten host for display if it's an IP address.

---

go/vt/tabletserver/sqlquery.go
go/vt/tabletserver/tx_pool.go

Two trivial log msg changes. Making them slightly more explicit.

---

go/cmd/bsongen/bsongen_test.go

@sougou 
It was also sometimes skipping the comment, which caused test failures
in Travis.

Fix bsongen_test skipImports function.

---

go/vt/tableacl/tableacl.go
go/vt/tableacl/tableacl_test.go
go/vt/tabletserver/query_executor.go

Do not perform access checks when table ACL is disabled

---

go/cmd/vtctld/topo_data.go
go/cmd/vtctld/topo_data_test.go
go/cmd/vtctld/vtctld.go

Still somewhat rough and not very generic.
@sougou let's talk about it tomorrow... obviously doesn't do much at all.

First pass at some JSON API for ajax pages.

---

go/vt/worker/clone_utils.go

Refactored executeFetchWithRetries based on @enisoc's suggestions.  I also added a wait, so that vtworkers won't be overrun in case of failures, and added more explicit logging.
Still to come: re-resolving  and unit tests.
@alainjobart

Add logging and a wait to executeFetchWithRetries

---

go/vt/client2/tablet/tclient.go
go/vt/tabletmanager/binlog.go
go/vt/tabletserver/gorpctabletconn/conn.go
go/vt/topo/tablet.go
go/vt/wrangler/zkns.go
py/vtdb/topo_utils.py
py/vtdb/topology.py
py/vtdb/vtgatev2.py
test/client_test.py
test/fake_zkocc_config.json
test/reparent.py
test/secure.py
test/sharded.py
test/vertical_split.py
test/vertical_split_vtgate.py
test/vtdb_test.py
test/vtgatev2_test.py
test/zkocc_test.py

rename _vtocc, _vts and _mysql in vitess client

---

examples/kubernetes/README.md
examples/kubernetes/guestbook/main.py
examples/local/client.py
examples/local/vtctld-up.sh
examples/local/vtgate-up.sh
examples/local/vttablet-up.sh
examples/local/zk-up.sh

Fix clients for _vt port rename.
Other minor fixes.

Update Kubernetes and local cluster examples.

---

.travis.yml
go/vt/vtgate/scatter_conn.go
go/vt/vtgate/vtgate.go
go/vt/vtgate/vtgate_test.go
py/vtdb/vtgatev2.py
test/vtgatev2_test.py

Fix many lint errors.
@alainjobart @sougou

Suppress tx_pool_full log.

---

test/secure.py

@sougou 
- Remove extra wait for pid port; pid is served from the main port now.
- Use wait_step instead of fixed wait for test condition.

Deflake secure.py test_restart method.

---

test/vtctld_test.py

fix typo, use assertTrue instead of assertIn in vtctld_test

---

go/cmd/vtworker/status.go
go/vt/servenv/status.go

Add access control for vtworker actions

---

go/vt/vtgate/vtgate.go

Add VTGate url on error message returned.

---

go/cmd/vtocc/vtocc.go
go/sync2/semaphore.go
go/sync2/semaphore_test.go
go/vt/tabletmanager/after_action.go
go/vt/tabletserver/query_engine.go
go/vt/tabletserver/queryctl.go
go/vt/tabletserver/request_context.go
go/vt/tabletserver/rowcache_invalidator.go
go/vt/tabletserver/sqlquery.go
go/vt/tabletserver/tablet_error.go
test/queryservice_tests/nocache_tests.py

Detailed comments are in the commit log. I got all the tests to pass, but they were flaky just as before. So, I don't know if these changes introduce additional flakiness. Let's hope not :).

Improved connection error handling

---

go/vt/vtgate/scatter_conn.go
go/vt/vtgate/scatter_conn_test.go

VTGate commit/rollback will fail if session object is not valid

---

go/vt/tabletmanager/healthcheck.go

for a full cycle.
@enisoc @guoliang100

Triggering a healthcheck at vttablet startup, no need to wait

---

examples/kubernetes/guestbook/main.py
examples/local/client.py
py/vtdb/vtgate_cursor.py
test/client_test.py
test/java_vtgate_test_helper.py
test/vtgatev2_test.py

@guoliang100 @enisoc @henryanand

Removed the dependency of topology from vtgate client.

---

test/java_vtgate_test_helper.py

Reverted a previous change to include topology again.

---

examples/kubernetes/README.md
examples/kubernetes/etcd-controller-template.yaml
examples/kubernetes/vtctld-pod.yaml
examples/kubernetes/vtgate-controller.yaml
examples/kubernetes/vttablet-pod-template.yaml

With the new logging features in Kubernetes, you no longer have to SSH into the node to see logs.

Log to stderr so it gets picked up by Kubernetes logsaver.

---

py/vtdb/db_object.py
test/client_test.py

Streaming support in client libraries.

---

test/java_vtgate_test_helper.py

@henryanand 
So we can rewrite part of it on import.

Split main() in java test helper.

---

go/vt/worker/diff_utils_test.go

@aaijazi 
I had this in my git stash from a while ago when I was trying to work on coverage for vt/worker/diff_utils. I figured I should commit it to avoid duplication of work.

Add some tests for vt/worker/diff_utils.

---

go/vt/worker/vertical_split_clone_test.go

The same style as SplitCloneWorker. This isn't the most useful test, but is at least a decent smoke test that the worker runs and copies a table successfully. 
@alainjobart @enisoc

Added integration tests for VerticalSplitCloneWorker

---

go/vt/tabletmanager/gorpctmclient/gorpc_client.go
go/vt/tabletmanager/gorpctmclient/gorpc_client_test.go

Fix TabletManagerClient.IsTimeoutError so that it doesn't always return true

---

go/cmd/vtocc/status.go
go/cmd/vtocc/vtocc.go
go/cmd/vttablet/health.go
go/cmd/vttablet/status.go
go/cmd/vttablet/vttablet.go
go/vt/tabletmanager/after_action.go
go/vt/tabletmanager/agent.go
go/vt/tabletmanager/agent_rpc_actions.go
go/vt/tabletmanager/healthcheck.go
go/vt/tabletmanager/healthcheck_test.go
go/vt/tabletserver/customrule/filecustomrule/filecustomrule.go
go/vt/tabletserver/customrule/filecustomrule/filecustomrule_test.go
go/vt/tabletserver/customrule/zkcustomrule/zkcustomrule.go
go/vt/tabletserver/customrule/zkcustomrule/zkcustomrule_test.go
go/vt/tabletserver/dbconn.go
go/vt/tabletserver/gorpcqueryservice/sqlquery.go
go/vt/tabletserver/queryctl.go
go/vt/tabletserver/queryz.go
go/vt/tabletserver/rowcache_invalidator.go
go/vt/tabletserver/schemaz.go
go/vt/tabletserver/status.go
go/vt/tabletserver/stream_queryz.go
go/vt/tabletserver/tx_pool.go

and mocking of the query service. Still needs some cleanup,
but it's a good time to get a review.
@sougou @enisoc @aaijazi @yaoshengzhe

Adding QueryServiceControl interface, to handle registration

---

doc/LifeOfAQuery.md

replace relative links in LifeOfAQuery.md

---

go/cmd/vtgate/vtgate.go
go/vt/tabletserver/gorpctabletconn/conn.go
go/vt/vtgate/gorpcvtgateservice/server.go
go/vt/vtgate/resolver.go
go/vt/vtgate/scatter_conn.go
go/vt/vtgate/shard_conn.go
go/vt/vtgate/vtgate.go
test/utils.py
test/vtgatev2_test.py

Change default flag values, and remove a timeout check

---

test/vtgatev2_test.py

@guoliang100 @alainjobart @shrutip

Test case to verify VtGate fail-fast behavior

---

test/vtgatev2_test.py

Comment out a testcase which is not valid under current design.

---

doc/VTGateV3.md

It's got all the text. A few diagrams will probably be helpful.
It's a start.

V3 design doc

---

test/vtgatev2_test.py

Ignore the test case for a future fix.

---

vitess.io/_config.yml

add http:// prefix to vitess.io url

---

go/vt/worker/clone_utils.go
go/vt/worker/split_clone_test.go
go/vt/worker/vertical_split_clone_test.go

@alainjobart 
I started down the path of writing tests, but they're too flakey to be worthwhile for now. I'll probably revisit them in the future.

Add better error handling/retry logic to worker destination writes.

---

doc/LifeOfAQuery.md

doc: Proof-read Life of a Query and made some corrections.

---

go/vt/vtctl/vtctl.go

Adding a 'vtctl help [command]' command.

---

examples/kubernetes/README.md
examples/kubernetes/advanced.md
examples/kubernetes/cluster-down.sh
examples/kubernetes/cluster-up.sh
examples/kubernetes/vttablet-down.sh
examples/kubernetes/vttablet-up.sh

Add scripts to automate bringing up multi-sharded clusters on GCE.

---

go/cmd/vttablet/status.go
go/vt/tabletmanager/agent_rpc_actions.go
go/vt/tabletmanager/agentrpctest/test_agent_rpc.go
go/vt/tabletmanager/healthcheck_test.go
go/vt/tabletmanager/reparent.go
go/vt/topo/helpers/copy_test.go
go/vt/topo/tablet.go
go/vt/topo/test/tablet.go
go/vt/vtctl/vtctlclienttest/client.go
go/vt/wrangler/testlib/fake_tablet.go

@enisoc 
Been talking about this for a while, this seems to work now...

Resharding

---

vitess.io/_includes/google-analytics.html
vitess.io/_layouts/default.html
vitess.io/_layouts/home.html

put GA: UA-60219601-1 on vitess.io

add google analytics for vitess.io

---

test/vtgatev2_test.py

Update vtgatev2 integration test

---

go/cmd/vtgate/vtgate.go
go/vt/vtgate/resolver.go
go/vt/vtgate/resolver_test.go
go/vt/vtgate/router_framework_test.go
go/vt/vtgate/router_select_test.go
go/vt/vtgate/sandbox_test.go
go/vt/vtgate/scatter_conn.go
go/vt/vtgate/scatter_conn_test.go
go/vt/vtgate/shard_conn.go
go/vt/vtgate/shard_conn_test.go
go/vt/vtgate/vertical_split_test.go
go/vt/vtgate/vtgate.go
go/vt/vtgate/vtgate_test.go
test/utils.py

Add separate parameter for per connection timeout

---

go/vt/tabletserver/streamlogger.go
go/vt/vtgate/vtgateconntest/client.go

Fixing this test to use strings.Contains instead of equal.

---

go/vt/vtgate/gorpcvtgateconn/conn.go
go/vt/vtgate/proto/vtgate_proto.go
go/vt/vtgate/vtgateconn/vtgateconn.go
go/vt/vtgate/vtgateconntest/client.go

Fixing SplitQuery for vtgate go client.

---

.travis.yml
Dockerfile
bootstrap.sh
travis/install_grpc.sh
travis/install_protobuf.sh

Docker and travis: build and install as root in /
@enisoc @henryanand I tested docker and bootstrap.sh, let's see how travis responds to this...

Fixing the scripts to build grpc and protobuf better.

---

doc/HorizontalReshardingGuide.md
doc/Resharding.md
doc/VitessOverview.md

@alainjobart 
This should close #441

Add a step-by-step horizontal sharding guide

---

Dockerfile

Fix noninteractive error when docker building

Fix noninteractive error when docker building

---

go/vt/vtgate/scatter_conn.go

Add vars to count tablet query error.

---

Dockerfile

Add VOLUME for vtdataroot
For more friendly data backup/restore/migrate/share

Add VOLUME for vtdataroot

---

go/proc/counting_listener_test.go
go/vt/dbconnpool/connection.go
go/vt/tabletserver/cache_pool.go
go/vt/tabletserver/connpool_test.go
go/vt/tabletserver/dbconn.go
go/vt/tabletserver/query_engine.go
go/vt/tabletserver/queryctl.go
go/vt/tabletserver/request_context.go
go/vt/tabletserver/rowcache.go
go/vt/tabletserver/schema_info.go
go/vt/tabletserver/sqlquery.go
go/vt/tabletserver/tablet_error.go
go/vt/tabletserver/tx_pool.go
test/queryservice_tests/cache_tests.py
test/queryservice_tests/test_env.py

This has a bunch of misc fixes. Each CL has its own fix.

Misc fixes

---

go/stats/export.go

I expect most users will only need to push to a single back-end at a time, and this makes it easy to have plug-ins installed for multiple backends but only push metrics to a single one. Otherwise, you'd have to go about deleting all the plugin files that you didn't want.
@enisoc @alainjobart

Only support emitting stats to a single backend at a time, selected with the --stats_backend flag

---

doc/Monitoring.md

@enisoc - will wait for an LGTM from you.

Add documentation about monitoring metrics

---

go/cmd/zkclient2/zkclient2.go
go/stats/influxdbbackend/influxdb_backend.go
test/zkocc_test.py

Move InfluxDB init into servenv.OnRun as it depends on flags and logging

---

go/vt/tabletmanager/agent.go

Publish TargetTabletType as a debug var

---

py/vtdb/vtgate_utils.py
py/vtdb/vtgatev2.py

Cleaned up vtgatev2_exception logging.

---

go/vt/tabletserver/fakesqldb/conn.go

add fakesqldb package which provides a fake implementation of sqldb.Conn

add a fake implementation of sqldb.Conn

---

py/vtdb/vtclient.py
test/vtdb_test.py

Removed the retry on txn pool full.

---

test/tablet.py

Using faster my.cnf in tests. not sure how we got rid of that.

---

go/stats/counters.go
go/vt/worker/clone_utils.go
go/vt/worker/split_clone.go
go/vt/worker/split_clone_test.go
go/vt/worker/split_diff.go
go/vt/worker/sqldiffer.go
go/vt/worker/vertical_split_clone.go
go/vt/worker/vertical_split_clone_test.go
go/vt/worker/vertical_split_diff.go
go/vt/worker/worker.go

Add variables to track additional worker state, useful for monitoring and testing

---

bootstrap.sh
go/vt/proto/tabletmanager/tabletmanager.pb.go
go/vt/proto/vtctl/vtctl.pb.go
travis/install_grpc.sh

The new one is not working right because of some broken dependencies.

Fixing the version of grpc to a well-known working version.

---

go/vt/vtgate/srv_topo_server.go

@guoliang100 
This patch add cached endpoint details to vtgate status page. Endpoints' ip:port addresses are added to status page and we have different colors to indicate healthiness:
Red: the endpoint is not healthy at all
Orange: the endpoint is not fully healthy, but can be used somehow
Green: the endpoint is fully healthy

Add endpoint details to vtgate status

---

go/cacheservice/cacheservice.go
go/cmd/vtocc/vtocc.go
go/cmd/vttablet/vttablet.go
go/memcache/memcache.go
go/vt/tabletserver/cache_pool.go

CacheService is an interface for cache services like memcache.

add CacheService interface

---

examples/kubernetes/cluster-down.sh
examples/kubernetes/cluster-up.sh
examples/kubernetes/vttablet-pod-benchmarking-template.yaml
examples/kubernetes/vttablet-pod-template.yaml
examples/kubernetes/vttablet-up.sh

@enisoc @henryanand 
Also fixed up deleting forwarding-rules and target-pools as the default naming presumably changed with a k8s update.

Enable support for running vttablets on SSD on GKE

---

doc/GettingStarted.md

@alainjobart @enisoc 
Installing that on my system seemed to make grpc a lot happier.

Add python-virtualenv to requirements for getting started

---

go/vt/tabletserver/cache_pool.go
go/vt/tabletserver/cache_pool_test.go
go/vt/tabletserver/query_engine.go

1. add cache pool unit test.
2. add a new statsURL param in NewCachePool function instead of
using a statsURL constant.

add cache pool unit test

---

examples/kubernetes/README.md
examples/kubernetes/cluster-down.sh
examples/kubernetes/cluster-up.sh

Update kubernetes example

---

doc/GettingStartedKubernetes.md

Update Kubernetes doc for move from gcloud preview to alpha.

---

go/cmd/vtworker/split_clone.go
go/cmd/vtworker/split_diff.go
go/cmd/vtworker/vertical_split_diff.go

in skipping all tables.
@aaijazi

vtworker: Fix bug that an empty form value for "excludeTables" resulted

---

go/timer/randticker_test.go
go/vt/tabletserver/queryctl.go
go/vt/tabletserver/sqlquery.go
go/vt/tabletserver/sqlquery_test.go
go/vt/tabletserver/tablet_error.go

Bind vars can contain PII. So, we need the option to suppress them.
I also have a fix for a recent flakyness.

Support for terse error

---

go/vt/tabletserver/fakesqldb/conn.go

add the ability in fakesqldb.Conn to reject certain queries.
This helps to test failure modes in queryservice unit tests.

add reject query support in fakesqldb

---

go/vt/vtgate/scatter_conn_test.go
go/vt/vtgate/shard_conn.go
go/vt/vtgate/shard_conn_test.go

Do not retry for tx_pool_full error

---

examples/kubernetes/cluster-down.sh
examples/kubernetes/cluster-up.sh
examples/kubernetes/newrelic.sh
examples/kubernetes/newrelic_start_agent.sh
examples/kubernetes/newrelic_start_mysql_plugin.sh
examples/kubernetes/vtgate-controller-benchmarking-template.yaml
examples/kubernetes/vtgate-controller-template.yaml
examples/kubernetes/vtgate-service.yaml
examples/kubernetes/vtgate-up.sh
examples/kubernetes/vttablet-pod-benchmarking-template.yaml
examples/kubernetes/vttablet-pod-template.yaml
examples/kubernetes/vttablet-up.sh

Contains the following updates:
1. Improvements for multiple clusters under the same project
2. Can create more nodes than vttablets
3. Added vtgate benchmarking templates (for GOMAXPROCS)
4. Retry logic when setting node labels
5. Can specify number of VTGate replicas
6. Default vtgate template to use external load balancer.
7. Newrelic monitoring (mysql plugin not currently used, breaks replication)

Updated k8s scripts for benchmarking efforts

---

go/vt/callinfo/callinfo.go
go/vt/callinfo/plugin_rpcwrap.go
go/vt/tabletmanager/rpc_server.go
go/vt/tabletserver/query_executor.go
go/vt/tabletserver/query_list.go
go/vt/tabletserver/streamlogger.go

Make CallInfo an interface, and generate fields on demand.

---

examples/kubernetes/vttablet-pod-benchmarking-template.yaml
examples/kubernetes/vttablet-pod-template.yaml
examples/kubernetes/vttablet-up.sh

My last commit messed up bringing up multisharded clusters :)
@enisoc @henryanand

Add a separate shard_label parameter to vttablet templates

---

go/vt/tabletserver/query_executor_test.go

@alainjobart @yaoshengzhe @henryanand

Fix CallInfo related problem in test.

---

go/cmd/vtgate/status.go
go/vt/callinfo/callinfo.go
go/vt/tabletserver/query_list.go
go/vt/vtgate/gorpcvtgateservice/server.go
go/vt/vtgate/srv_topo_server.go
test/vtgatev2_test.py

@guoliang100 @alainjobart 
TODO: testing. Planning on doing at least a one-off test with an invalid keyspace and verifying that it works.

Use CallInfo in VTGate, and restore context HTML to vtgate status page

---

go/vt/tabletserver/querylogz.go
go/vt/tabletserver/queryz.go
go/vt/tabletserver/schemaz.go
go/vt/tabletserver/stream_queryz.go
go/vt/tabletserver/streamlogger.go
go/vt/tabletserver/txlogz.go

@guoliang100 @alainjobart 
Alain's recent refactor ended up killing a method that we actually needed, so I put it back in. Also added logging to that hopefully this kind of problem will be easier to track down.
Longer-term: we should eventually have debug page tests as part of our integration test suite, I think. This is the second one that we've caught in the past couple of weeks.

Fix /querylogz

---

go/vt/vtgate/proto/batch_query_shard_bson.go
go/vt/vtgate/proto/entity_ids_query_bson.go
go/vt/vtgate/proto/key_range_query_bson.go
go/vt/vtgate/proto/keyspace_id_batch_query_bson.go
go/vt/vtgate/proto/keyspace_id_query_bson.go
go/vt/vtgate/proto/query_bson.go
go/vt/vtgate/proto/query_shard_bson.go
go/vt/vtgate/proto/vtgate_proto.go
go/vt/vtgate/proto/vtgate_proto_test.go
go/vt/vtgate/resolver.go
go/vt/vtgate/router.go
go/vt/vtgate/scatter_conn.go
go/vt/vtgate/scatter_conn_test.go
go/vt/vtgate/vertical_split_test.go
go/vt/vtgate/vtgate.go
py/vtdb/vtgate_cursor.py
py/vtdb/vtgatev2.py
py/vtdb/vtgatev3.py

Allow client speficies if a query should not be in a transaction.

---

go/vt/tableacl/tableacl_test.go
test/vtgatev2_test.py

@aaijazi @yaoshengzhe @alainjobart

Disable two failing tests.

---

go/vt/vtgate/shard_conn.go
go/vt/vtgate/shard_conn_test.go

@alainjobart @shrutip @aaijazi

Do not connection_life to re-connect for master.

---

go/vt/tabletserver/fakesqldb/conn.go
go/vt/tabletserver/tx_pool_test.go

add more test cases to test tx pool failure modes, this increases the test
coverage to 100%.

improve tx_pool unit test

---

go/vt/tabletserver/queryctl.go
go/vt/tabletserver/queryz.go
go/vt/tabletserver/queryz_test.go
go/vt/tabletserver/schema_info_test.go
go/vt/tabletserver/testutils_test.go

1. move registerQueryzHandler to queryctl.go
2. move newTestSchemaInfo from schema_info_test.go to testutils_test.go

add queryz unit test

---

go/vt/tabletserver/sqlquery_test.go

My previous changes were outdated and broke some tests. Fixed now.

Fixing broken tests

---

go/vt/tabletserver/cache_pool_test.go
go/vt/tabletserver/fakecacheservice/fakecacheservice.go
go/vt/tabletserver/fakecacheservice/fakecacheservice_test.go
go/vt/tabletserver/testutils_test.go

1. add checkTabletError test func in testutils_test.go
2. add methods to enable/disable fakecacheservice
3. add two test cases to cache pool: 1) cachepool failed to update MemcacheStats 2) ccachepool failed to start because of it cannot connect to memcache.

improve cache pool unit test

---

go/vt/tabletserver/querylogz.go
go/vt/tabletserver/querylogz_test.go

go/streamlog/streamlog.go starts a separate go routine for each new logger instance.
In the querylogz_test.go, it tries to call logger.Send(logStats) and then assumes this
logStats has been delivered. Then it calls querylogzHandler and verifies the result.
However, it is not guaranteed the message will be delivered after Send call, because Send
just put the message into dataQueue and only the go routine delivers it to each consumers.

fix querylogz test race conditions

---

go/vt/tabletserver/codex.go
go/vt/tabletserver/codex_test.go

1. use TabletError for panics in resolvePKValues and resolveValue.
2. add test cases to test error scenarios.

improve codex unit test coverage

---

go/vt/tabletserver/connpool_test.go

1. remove old unit test rely on local mysql instance
2. add unit test using fake mysql db implementation

impove connpool unit test

---

go/vt/vtgate/resolver.go
go/vt/vtgate/resolver_test.go
go/vt/vtgate/scatter_conn.go
go/vt/vtgate/scatter_conn_test.go
go/vt/vtgate/shard_conn.go
go/vt/vtgate/vtgate.go
go/vt/vtgate/vtgate_test.go
test/vtgatev2_test.py

Inside VTGate, log tabletconn.ServerErrors to Infof instead of Errorf

---

.gitignore

git: Ignore Eclipse Pydev file ".pydevproject".

---

travis/install_grpc.sh

Fix installing gRPC if it's not installed system wide.

---

java/vtgate-client/src/test/java/com/youtube/vitess/vtgate/integration/VtGateIT.java

Removing integration test for case that is now allowed.

---

go/vt/vtgate/shard_conn.go

Add stats to track dangling tablet conn.

---

test/schema.py

@michael-berlin @enisoc 
Quick fix to get this test passing.
Real fix is to remote start replication on old master, but it's more involved so will be a next CL.

Fixing this test, replication isn't restarted any more.

---

test.go

Previously, each test would freshly re-copy the working repo before
running. Changes to the files could affect the next test in the series.
Now the entire invocation of test.go uses the same snapshot of the
working dir.
This required a global cleanup step, to delete the temp dir, so I
reworked signal handling to be global. This also opens the door to
running tests in parallel within a given test.go invocation.

test.go: verbose logs, copy working repo to tempdir

---

examples/kubernetes/README.md
examples/kubernetes/cluster-down.sh
examples/kubernetes/cluster-up.sh
examples/kubernetes/util/get_forwarded_pool.sh

Updates for k8s updates to forwarding-rule/target-pool naming

---

proto/tabletmanager.proto
proto/vtctl.proto

@sougou @enisoc 
Will need to import this ASAP too.

Removing 'optional' keyword as it is implied by proto3.

---

go/vt/mysqlctl/proto/schema.go
go/vt/mysqlctl/proto/schema_test.go
go/vt/schemamanager/schemamanager.go
go/vt/schemamanager/schemamanager_test.go
go/vt/schemamanager/tablet_executor.go
test/schema.py

Two commits:
1. return error when schema change fails
2. add schema diffs in schemamanager
1). Make DiffSchema compare table views.
2). Add schema diffs in schemamanager. Each schema changes have to change
table structure and schemanager rejects a sql that does not change
any table definition.

autoschema rework

---

go/vt/health/health.go
go/vt/health/health_test.go
go/vt/mysqlctl/health.go
go/vt/tabletmanager/healthcheck.go
go/vt/tabletmanager/healthcheck_test.go

Removing dependency from go/vt/health and go/vt/mysqlctl to topo.

---

go/vt/tabletmanager/reparent.go

@alainjobart 
Export counts and histogram as debug vars for:
* time until new master is visible
* time until full rebuild is complete

Report timings of fast external reparents.

---

doc/SchemaManagement.md

1. Old vtctl commands ApplySchemaShard, ApplySchemaKeyspace, PreflightSchema
have been removed.
2. ApplySchema only supports doing schema changes for the whole keyspace.

remove deprecated information in schema management doc

---

Makefile
doc/HorizontalReshardingGuide.md
go/vt/worker/clone_utils.go
go/vt/worker/split_clone.go
go/vt/worker/split_clone_test.go
go/vt/worker/vertical_split_clone.go
go/vt/worker/vertical_split_clone_test.go
go/vt/worker/worker.go
test/config.json
test/tablet.py
test/utils.py
test/worker.py

@thompsonja - this is my attempt at making a more environment-unaware, readable integration test. 
@alainjobart 
I still want to add one more test for if a destination mysql is killed during worker copy.

Added worker.py to cover worker integration tests

---

doc/BackupAndRestore.md

@enisoc @aaijazi 
This is the last piece for that effort for now. :)

Adding doc for OS Backup and Restore.

---

java/vtgate-client/src/main/java/com/youtube/vitess/vtgate/Exceptions.java
java/vtgate-client/src/main/java/com/youtube/vitess/vtgate/Row.java

Import java changes

---

examples/kubernetes/README.md
examples/kubernetes/cluster-up.sh

@enisoc It was easier to just create a new PR instead of undoing #720 :)

replace gcloud alpha container kubectl with kubectl

---

go/vt/mysqlctl/backup.go

@alainjobart 
We are probably doing a bad job of checking these errors in a lot of
places, but it's particularly important to get it right for backups.
We don't worry about Close() on the Reader side.
When using an AllErrorRecorder, we don't have to worry about hiding the
Write error with a Close error. But we do need to make sure not to call
Close as part of saving the arguments of a defer statement.

Check error on Close() and Flush() in Backup.

---

go/vt/topo/test/lock.go

We were cancelling the wrong context and then using it.
@aaijazi @enisoc @sougou 
First one to get to this wins the right to also approve the import that will fix the flaky google3 tests. :)

Fixing race conditions in this test.

---

README.md

@enisoc @rushiagr to address https://github.com/youtube/vitess/issues/734

Update Getting Started links

---

examples/kubernetes/cluster-up.sh
examples/kubernetes/newrelic.sh

Couple small fixes to bringing up a cluster on k8s and starting new relic

---

vitess.io/css/extra.css

add margin-left and width properties back.

fix extra.css

---

go/cmd/vtctld/actions.go
go/cmd/vtctld/vtctld.go

Using contexts in a more standard way.

---

py/vtdb/tablet.py

Slightly safer handling of Err in Python clients

---

go/vt/wrangler/permissions.go
go/vt/wrangler/schema.go
go/vt/wrangler/testlib/permissions_test.go
go/vt/wrangler/version.go

Using Alias.IsZero() more often.
@enisoc @yaoshengzhe

Adding unit test for permissions.

---

doc/GettingStarted.md

Mention checking FD limits in Getting Started.

---

go/vt/mysqlctl/backup.go
go/vt/mysqlctl/mysqld.go

@alainjobart 
The new backup.py test was failing in Docker, but passing outside Docker. It turns out that RunMysqlUpgrade() was broken, but the test was passing on machines that happened to have a default-configured mysqld running at the time.
1) mysqld needs to be running to use mysql_upgrade.
2) mysql_upgrade needs to be told how to connect to mysqld.

Fix mysql_upgrade during Restore.

---

doc/GettingStartedKubernetes.md

In response to: https://groups.google.com/forum/#!topic/vitess/sCKrGTD5KHQ

Describe how to directly connect to mysqld.

---

examples/kubernetes/cluster-up.sh
examples/kubernetes/util/get_forwarded_pool.sh

k8s benchmarking - use 'kubectl get nodes' to obtain node names

---

Godeps/Godeps.json

For example, "godep restore" didn't work.
@aaijazi @enisoc 
Ammar, I think you went too Go crazy here :)
The only thing which I don't understand yet: The file is supposed to be generated automatically. But I assume we have maintained it manually in the past?

Fix godeps config file and broke all godep commands.

---

doc/HorizontalReshardingGuide.md
test/worker.py

@michael-berlin @enisoc 
As mentioned in person, reverting this seems to significantly improve test flakiness.

Revert worker test changes

---

go/vt/mysqlctl/mysqld.go

Fix mysql_upgrade again.

---

go/vt/proto/queryservice/queryservice.pb.go
proto/queryservice.proto

Small change, last one in this branch before I switch to forked repository.
@enisoc

Renaming SqlQuery to just Query to be shorter.

---

test.go
test/config.json

For example:
```
$ go run test.go -retry 1 -runs 100 some_flaky_test
...
42 PASSED, 0 FLAKY, 58 FAILED, 0 SKIPPED
```

test.go: Add flakiness measurement tools.

---

go/vt/vtgate/shard_conn.go

Clean up log for new tablet connection.

---

test.go
test/config.json

Now there's just one command to run everything.
Also, unit tests will be re-run to check for flakiness.

test.go: Add unit tests as a target in test/config.json.

---

go/cmd/automation_client/automation_client.go
go/cmd/automation_server/automation_server.go

Binaries for automation client and server

---

misc/git/hooks/golint

Git hook golint improvements

---

go/vt/tabletserver/tabletconntest/tabletconntest.go

@alainjobart 
I'll merge after you, this is needed before importing.

Improvements to tabletconntest

---

go/cmd/vtctlclient/main.go
go/vt/automation/copy_schema_shard_task.go
go/vt/automation/copy_schema_shard_task_test.go
go/vt/automation/scheduler.go
go/vt/automation/vtctlclient_wrapper.go
go/vt/vtctl/fakevtctlclient/fakevtctlclient.go
go/vt/vtctl/fakevtctlclient/fakevtctlclient_test.go
go/vt/vtctl/vtctlclient/interface.go
go/vt/vtctl/vtctlclient/wrapper.go

Automation: CopySchemaShard task and fake for vtctlclient.

---

go/vt/vtgate/srv_topo_server.go

Use own context to query topo.

---

go/zk/zkns/pdns/pdns_test.go

I don't fully understand why, but now it passes with no warning.
@sougou @guoliang100

Fix for thread sanetizer-reported issue.

---

doc/GettingStartedKubernetes.md

* Explain Vitess-specific terms when they're first used.
* Explain what etcd is and why we need it.
* Link to other Vitess docs for more detail.
* Mention how you can see the requests being handled for the Guestbook.

Clarifications for GettingStartedKubernetes doc.

---

go/vt/worker/split_diff.go
go/vt/worker/sqldiffer.go
go/vt/worker/vertical_split_diff.go
test/resharding.py

diff workers now return an error when they detect a mismatch

---

java/vtgate-client/src/test/java/com/youtube/vitess/vtgate/integration/DataTypesIT.java
java/vtgate-client/src/test/java/com/youtube/vitess/vtgate/integration/FailuresIT.java
java/vtgate-client/src/test/java/com/youtube/vitess/vtgate/integration/StreamingServerShutdownIT.java
java/vtgate-client/src/test/java/com/youtube/vitess/vtgate/integration/StreamingVtGateIT.java
java/vtgate-client/src/test/java/com/youtube/vitess/vtgate/integration/VtGateIT.java
java/vtgate-client/src/test/java/com/youtube/vitess/vtgate/integration/hadoop/MapReduceIT.java
java/vtgate-client/src/test/java/com/youtube/vitess/vtgate/integration/util/SetupCommand.java
java/vtgate-client/src/test/java/com/youtube/vitess/vtgate/integration/util/TestEnv.java
java/vtgate-client/src/test/java/com/youtube/vitess/vtgate/integration/util/Util.java
test/java_vtgate_test_helper.py

Its' easier to keep state that way, and terminate all
processes right away, without forking something else.
@enisoc @guoliang100 @aaijazi whoever feels more comfortable with java, please! :)

Leaving java_vtgate_test_helper.py while running java tests.

---

doc/GettingStartedKubernetes.md
examples/kubernetes/etcd-controller-template.yaml
examples/kubernetes/etcd-down.sh
examples/kubernetes/etcd-service-template.yaml
examples/kubernetes/etcd-up.sh
examples/kubernetes/guestbook-controller.yaml
examples/kubernetes/guestbook-down.sh
examples/kubernetes/guestbook-service.yaml
examples/kubernetes/guestbook-up.sh
examples/kubernetes/vtctld-pod.yaml
examples/kubernetes/vtctld-service.yaml
examples/kubernetes/vtgate-benchmarking-up.sh
examples/kubernetes/vtgate-controller-template.yaml
examples/kubernetes/vtgate-down.sh
examples/kubernetes/vtgate-pod-benchmarking-template.yaml
examples/kubernetes/vtgate-service.yaml
examples/kubernetes/vtgate-up.sh
examples/kubernetes/vttablet-pod-benchmarking-template.yaml
examples/kubernetes/vttablet-pod-template.yaml

Update Kubernetes API from v1beta3 to v1.

---

go/vt/status/status.go
go/vt/tabletmanager/agent.go

Removing two obsolete flags.

---

doc/GettingStartedKubernetes.md
examples/kubernetes/create_test_table.sql
examples/kubernetes/guestbook/README.md
examples/kubernetes/guestbook/main.py
examples/kubernetes/guestbook/static/script.js

@alainjobart @dumbunny 
The Guestbook app is now sharding-ready.

Add multi-page feature to Guestbook sample app.

---

test/java_vtgate_test_helper.py

@aaijazi will only do that once google3 change to not use these is submitted.

Remove now unused code inside java_vtgate_test_helper.py.

---

go/vt/logutil/throttled_test.go

The check for skippedCount=1 after logging, but before the throttler
prints anything, cannot be done without racing. It's not necessary
anyway because the resulting log line proves the value of skippedCount.
When checking the value of skippedCount after the throttler prints,
we need to acquire the lock so we know the throttler's goroutine has
had a chance to finish and update skippedCount.

Fix data race in throttled logger test.

---

Makefile

Build all flavors in make docker_bootstrap.

---

test/rowcache_invalidator.py

Deflake rowcache_invalidator test.

---

go/vt/topotools/rebuild.go
go/vt/topotools/rebuild_test.go
go/vt/vtctl/vtctl.go
go/vt/zktopo/serving_graph.go

Deprecate lock_srvshard flag.

---

doc/GettingStartedKubernetes.md
doc/ShardingKubernetes.md
examples/kubernetes/env.sh
examples/kubernetes/kvtctl.sh
examples/kubernetes/vtctld-up.sh
examples/kubernetes/vttablet-down.sh

@thompsonja - This is inspired by your cluster-up.sh script. I got tired of setting up the kvtctl alias every time. :)

[k8s] Add kvtctl.sh script to find vtctld address automatically

---

go/cmd/automation_client/automation_client.go

@alainjobart Merging this right away because it is already imported.

automation_client: Add missing method from interface flag.Var.

---

go/vt/worker/interactive.go
go/vt/worker/status.go

vtworker: Fix that commands on the webinterface were not protected by

---

go/cmd/vtworker/plugin_grpcvtworkerserver.go
go/vt/worker/grpcvtworkerserver/server.go

@aaijazi just FYI
I'm merging this right away.

vtworker: Fix header and comment.

---

go/vt/worker/vtworkerclient/client_testsuite.go
proto/vtworkerservice.proto

@alainjobart @aaijazi 
I'm merging this right away because Alain already approved these changes internally.

vtworker client_testsuite fixes

---

go/vt/vtctl/vtctl.go
go/vt/wrangler/keyspace.go
go/vt/wrangler/shard.go
test/keyspace_test.py

Add recursive mode to DeleteKeyspace and DeleteShard.

---

go/vt/vtctl/vtctl.go
go/vt/wrangler/keyspace.go
go/vt/wrangler/shard.go
test/keyspace_test.py

@alainjobart 
Also add RemoveKeyspaceCell command.

Add recursive mode to RemoveShardCell command.

---

go/vt/binlog/event_streamer.go

Simplifying this code. No need to create intermediate structures

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/client.go
Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/client_test.go
Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/cluster.go
Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/error.go
Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/get.go
Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/member.go
Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/member_test.go
Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/options.go
Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/requests.go
Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/requests_test.go
Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/set_curl_chan_test.go
Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/version.go
doc/GettingStarted.md
docker/bootstrap/Dockerfile.common
docker/etcd-lite/Dockerfile
docker/etcd-lite/build.sh
docker/etcd/Dockerfile
examples/kubernetes/etcd-controller-template.yaml
examples/kubernetes/etcd-up.sh
test/topo_flavor/etcd.py

Update to etcd v2.0.13

---

Makefile
go/cmd/automation_server/plugin_gorpcvtctlclient.go
go/cmd/automation_server/plugin_grpcvtworkerclient.go
go/vt/automation/change_slave_type_task.go
go/vt/automation/copy_schema_shard_task.go
go/vt/automation/horizontal_resharding_task.go
go/vt/automation/horizontal_resharding_task_test.go
go/vt/automation/scheduler.go
go/vt/automation/split_clone_task.go
go/vt/automation/split_clone_task_test.go
go/vt/automation/split_diff_task.go
go/vt/automation/vtworkerclient_wrapper.go
go/vt/vtctl/fakevtctlclient/fake_loggerevent_streamingclient.go
go/vt/vtctl/fakevtctlclient/fake_loggerevent_streamingclient_test.go
go/vt/vtctl/fakevtctlclient/fakevtctlclient.go
go/vt/worker/fakevtworkerclient/fakevtworkerclient.go
go/vt/worker/grpcvtworkerclient/client.go
go/vt/worker/vtworkerclient/interface.go
test/automation_horizontal_resharding.py
test/config.json
test/schema.py
test/utils.py
test/worker.py

@alainjobart @aaijazi 
I recommend to review the different commits using the "commits" view from Github and not the "files" view because I tried to keep logical changes between the same commit.

End-to-end test for open-source automation of horizontal resharding.

---

java/vtgate-client/src/main/java/com/youtube/vitess/vtgate/VtGate.java
java/vtgate-client/src/main/java/com/youtube/vitess/vtgate/rpcclient/RpcClient.java
java/vtgate-client/src/main/java/com/youtube/vitess/vtgate/rpcclient/gorpc/GoRpcClient.java
java/vtgate-client/src/test/java/com/youtube/vitess/vtgate/integration/VtGateIT.java
test/client_test.py

@michael-berlin @yaoshengzhe 
These changes got left out. My java tests don't work yet. So,
I found these only on import. This is a backport of the changes
I had to make to get the import tests to pas.

vtgate: batch api changes

---

examples/local/vttablet-up.sh

@alainjobart 
This is to help with answering #868.

Add backup settings to local vttablet-up.sh.

---

go/cmd/vtworkerclient/vtworkerclient.go
go/vt/automation/vtworkerclient_wrapper.go
go/vt/worker/vtworkerclient/wrapper.go
test/utils.py

vtworker fixes

---

go/cmd/vtctld/api.go
go/cmd/vtctld/tablet_data.go
go/cmd/vtctld/tablet_data_test.go
go/cmd/vtctld/vtctld.go
web/vtctld/app.css
web/vtctld/app.js
web/vtctld/index.html
web/vtctld/keyspaces.html
web/vtctld/shard.html

web/vtctld: Show real-time tablet stats.

---

go/cmd/vtctld/api.go
go/cmd/vtctld/vtctld.go
web/vtctld/action-dialog.html
web/vtctld/app.js
web/vtctld/keyspaces.html
web/vtctld/shard.html

web/vtctld: Hook up actions in new interface.

---

go/vt/tabletmanager/agent.go
go/vt/tabletmanager/healthcheck.go
go/vt/vtctl/vtctl.go
go/vt/worker/split_clone.go
go/vt/worker/split_diff.go
go/vt/worker/sqldiffer.go
go/vt/worker/topo_utils.go
go/vt/worker/vertical_split_clone.go
go/vt/worker/vertical_split_diff.go
test/initial_sharding.py
test/resharding.py
test/vertical_split.py

Fix typos and outdated comments

---

go/streamlog/streamlog_test.go

Fixing test flakiness.

---

go/timer/randticker.go

@alainjobart @sougou @yaoshengzhe @enisoc

Fix race condition in RandTicker

---

go/cmd/vtctld/api_test.go
go/vt/topo/shard.go

Add unit tests for new vtctld API.

---

java/vtgate-client/src/main/java/com/youtube/vitess/vtgate/Field.java
java/vtgate-client/src/main/java/com/youtube/vitess/vtgate/FieldType.java
java/vtgate-client/src/main/java/com/youtube/vitess/vtgate/hadoop/utils/GsonAdapters.java
java/vtgate-client/src/main/java/com/youtube/vitess/vtgate/hadoop/writables/KeyspaceIdWritable.java
java/vtgate-client/src/main/java/com/youtube/vitess/vtgate/hadoop/writables/RowWritable.java
java/vtgate-client/src/test/java/com/youtube/vitess/vtgate/DateTypesTest.java
java/vtgate-client/src/test/java/com/youtube/vitess/vtgate/FieldTest.java
java/vtgate-client/src/test/java/com/youtube/vitess/vtgate/integration/hadoop/MapReduceIT.java
java/vtgate-client/src/test/java/com/youtube/vitess/vtgate/rpcclient/gorpc/BsonifyTest.java

1. Move FieldType enum out of Field class.
2. Move GsonAdapters to hadoop/utils
3. Move BsonifyTest to vtgate/rpcclient/gorpc

move bson code to vtgate/rpcclient/gorpc

---

go/vt/wrangler/validator.go
go/vt/wrangler/validator_test.go

Fix normalize ip parsing for ipv6 localhost

---

test/worker.py

worker.py: Remove duplicate CopySchemaShard command.

---

go/vt/binlog/proto/proto3.go
go/vt/mysqlctl/proto/proto3.go
go/vt/proto/replicationdata/replicationdata.pb.go
go/vt/proto/tabletmanagerdata/tabletmanagerdata.pb.go
go/vt/tabletmanager/grpctmclient/client.go
go/vt/tabletmanager/grpctmserver/server.go
proto/replicationdata.proto
proto/tabletmanagerdata.proto
py/vtproto/replicationdata_pb2.py
py/vtproto/tabletmanagerdata_pb2.py

Much simpler than the big proto file.
@enisoc @liguo

Now using strings in remote RPC communication for replication position.

---

test/reparent.py

reparent.py: Fix style issues.

---

examples/kubernetes/vttablet-down.sh

@enisoc 
In #907 I had reverted a change to vttablet yaml files but forgot to also revert the same change in vttablet-down.sh

Fix vttablet-down.sh

---

examples/kubernetes/vitess-up.sh

@enisoc 
I totally promise this is the last commit relating to kubernetes multi cell changes... I hope :[

Fix vitess-up.sh default initial master tablet

---

go/vt/tableacl/tableacl.go
go/vt/tableacl/tableacl_test.go

1. table names or prefixes should be sorted.
2. acl entries should not have two overlaped entries (overlap means a concrete table name will
match both entries).
3. '%' should be presented only as the last character of a name, meaning this is a prefix.

always validate tableacl config before using it.

---

Makefile
py/vtdb/db_object.py
py/vtdb/sql_builder.py
test/sql_builder_test.py

Refactor sql_builder.py

---

go/vt/vtgate/srv_topo_server.go

fix toposerver to tolerate nil return from GetEndPoints()

---

go/vt/vtctl/query.go
test/reparent.py
test/rowcache_invalidator.py
test/secure.py
test/sharded.py
test/tablet.py
test/tabletmanager.py
test/vertical_split.py

Also various small cleanups in integration tests.
@enisoc @sougou

Adding 'vtctl VtTabletExecute' command, using it in a few places.

---

Makefile
tools/build_version_flags.sh

Go 1.5 compatibility fixes

---

go/vt/wrangler/testlib/fake_tablet.go

before assuming the HTTP server is up.
@enisoc @michael-berlin

Fixing race condition: upon tablet startup, wait for ping to work

---

doc/vtctlReference.md
doc/vtctl_go_reference.py

and running it for up-to-date doc.
(Andy, this is the latest version from your root, we can just use this one here now, I just fixed the imports and command line parameter parsing, that's it).
@enisoc @yaoshengzhe @AndyDiamondstein

Submitting the script to generate the vtctl reference doc,

---

docker/lite/build.sh
examples/kubernetes/vtctld-pod.yaml
go/cmd/vtctld/vtctld.go
test/utils.py
web/vtctld/api.js
web/vtctld/schema.js

@alainjobart 
It works both when accessed directly via Node IP and also through the apiserver proxy.

Enable new vtctld UI in Kubernetes

---

go/vt/topotools/rebuild.go

Remove unused -lock_srvshard flag.

---

data/test/sqlparser_test/parse_pass.sql
go/vt/sqlparser/ast.go
go/vt/sqlparser/ast_test.go
go/vt/sqlparser/sql.go
go/vt/sqlparser/sql.y
go/vt/sqlparser/token.go

@yaoshengzhe @guokeno0 
I've also added some misc fixes related to operator precedence and test coverage.

sqlparser: support << and >> operators

---

misc/git/hooks/golint

Revert "Fix golint pre commit hook for non-interactive shell."

---

go/vt/automation/cluster_operation_instance.go
go/vt/automation/scheduler.go
go/vt/automation/scheduler_test.go
go/vt/automation/task_containers.go
go/vt/automation/testutils_test.go

@aaijazi 
See the commit messages for the full story :-)

automation: Fix data race.

---

misc/git/hooks/golint

@enisoc 
https://github.com/youtube/vitess/pull/958 broke Alain's workflow.
The first commit is cherry-picked from that PR and the second commit is the fix.

Fix golint pre commit hook for non-interactive shell (2nd try).

---

doc/BackupAndRestore.md
vitess.io/_layouts/base.liquid
vitess.io/css/extra.css
vitess.io/user-guide/backup-and-restore.md

Add backup and restore document to left nav and modify document based on feedback from Alain. Also fix anchor links.

Backup restore

---

py/zk/zkocc.py
test/custom_sharding.py
test/initial_sharding.py
test/mysql_flavor.py
test/python_client_test.py
test/reparent.py
test/resharding.py
test/rowcache_invalidator.py
test/schema.py
test/tablet.py
test/tabletmanager.py
test/topo_flavor/etcd.py
test/topo_flavor/zookeeper.py
test/update_stream.py
test/utils.py
test/vertical_split.py
test/vertical_split_vtgate.py
test/vtctld_test.py
test/worker.py
test/zkocc_test.py

https://github.com/plobsing/vitess/commit/48808a8003482a941bf2030563b5a8008a70ecaa

Re-applying fixes from:

---

test/reparent.py

after external reparent.
@enisoc @guoliang100 Trying to reproduce the bug, can't so far.

Adding integration test to make sure master health is correct

---

go/vt/tabletserver/grpcqueryservice/server.go
go/vt/tabletserver/tabletconntest/tabletconntest.go

Add back unit tests for error handling in tabletconn

---

go/vt/topo/tablet.go

Add back TabletAddr to topo/tablet.go

---

web/vtctld/shard.js

web/vtctld: Fix shard dashboard for new topo structures.

---

go/vt/automation/copy_schema_shard_task.go
go/vt/automation/copy_schema_shard_task_test.go
go/vt/automation/horizontal_resharding_task.go
go/vt/automation/horizontal_resharding_task_test.go
go/vt/automation/scheduler.go
go/vt/automation/scheduler_test.go
go/vt/automation/split_clone_task.go
go/vt/automation/split_clone_task_test.go
go/vt/automation/split_diff_task.go
go/vt/automation/task.go
go/vt/automation/testutils_test.go
go/vt/automation/vtworkerclient_wrapper.go
test/automation_horizontal_resharding.py

Make parameter validation more strict: Unknown parameters are no longer
supported.
Fixed minor issues e.g. error messages must not be capitalized.

automation: Extend Task interface to support optional parameters.

---

go/vt/wrangler/testlib/reparent_external_test.go
go/zk/fakezk/fakezk.go
go/zk/fakezk/fakezk_test.go

Fix test races found through wrangler/testlib

---

docker/bootstrap/Dockerfile.common
docker/test/run.sh
java/gorpc/pom.xml
test/config.json

This makes test.go also run the Java tests.

Add Java tests to Docker test runner

---

go/vt/vtgate/resolver_test.go
go/vt/vtgate/router_framework_test.go
go/vt/vtgate/sandbox_test.go
go/vt/vtgate/scatter_conn_test.go
go/vt/vtgate/shard_conn_test.go
go/vt/vtgate/vertical_split_test.go

@alainjobart @michael-berlin @enisoc

Reduce unit test flakiness

---

go/cmd/automation_client/automation_client.go
go/vt/automation/horizontal_resharding_task.go
go/vt/automation/scheduler.go
go/vt/automation/vtctlclient_wrapper.go
go/vt/automation/wait_for_filtered_replication_task.go
go/vt/tabletserver/grpcqueryservice/server.go
go/vt/tabletserver/sqlquery.go
go/vt/vtctl/vtctl.go
go/vt/wrangler/testlib/wait_for_filtered_replication_test.go

automation: Add task WaitForFilteredReplication.

---

data/test/sqlparser_test/parse_fail.sql
data/test/tabletserver/exec_cases.txt
data/test/tabletserver/stream_cases.txt
data/test/vtgate/select_cases.txt
go/vt/sqlparser/token.go
go/vt/tabletserver/sqlquery.go
go/vt/tabletserver/sqlquery_test.go

@guoliang100 @nurblieh @aaijazi 
Some minor tweaks in error messages that have great usability improvements.

Error message improvements

---

Makefile
test/environment.py
test/utils.py

(after adding a rule to build before tests).
Global build takes about 2s to build all binaries, and it saves
about 4s in one run of mysqlctl.py, so it's gonna be good!
@enisoc @michael-berlin @dumbunny This is what I had in mind...

Adding utils.py option to skip builds, using it in the Makefile

---

py/vtdb/vtgatev2.py
test/python_client_test.py

This reverts commit 0b77390fbc41b356dd34fb9b8b3428444fa05a68.
Reason: Broke internal users.

Revert "Add optional effective_caller_id parameter to vtgate_client.py."

---

go/netutil/netutil.go

netutil: Fix go vet errors and error formatting.

---

py/vtdb/vtgate_cursor.py
py/vtdb/vtgatev2.py
test/python_client_test.py
test/vertical_split.py

Propagate effective_caller_id parameter from vtgate_cursor to

---

test/utils.py

Also passing correct prototol to vtworker.

---

doc/Reparenting.md
doc/VitessOverview.md
vitess.io/_layouts/base.liquid
vitess.io/user-guide/reparenting.md

Also fix broken link in overview.

Modify reparenting guide and add to left nav for http://vitess.io.

---

go/vt/vtgate/bsonp3vtgateconn/conn.go
go/vt/vtgate/bsonp3vtgateservice/server.go
php/README.md
php/src/GoRpcClient.php
php/src/VTGateConn.php
php/src/VTProto.php
php/tests/VTGateConnTest.php
php/tests/VTProtoTest.php

PHP: Implement streaming execute, split query, etc.

---

py/vtdb/vtgate_client.py
py/vtdb/vtgatev2.py
test/python_client_test.py

Make vtgate_client.CallerID object to provide a common object to pass

---

go/zk/fakezk/fakezk.go

It could cause race conditions in tests, since data can change
underneath the caller after we return it.

fakezk: Don't return pointers to internal structures.

---

proto/vtgateservice.proto

@AndyDiamondstein So we can keep moving on the groups :)

Adding comments to the proto definition, and API groups.

---

go/mysql/mysql.go
go/vt/tabletserver/sqlquery.go
go/vt/tabletserver/tablet_error.go

Demote MySQL DataOutOfRange errors (errno 1264)

---

go/vt/vtgate/gateway.go
go/vt/vtgate/resolver.go
go/vt/vtgate/scatter_conn.go
go/vt/vtgate/shardgateway.go
go/vt/vtgate/vtgate.go

Further refactor around Gateway interface.

---

go/vt/vtgate/gateway.go
go/vt/vtgate/shardgateway.go

Update the shardgateway identifier.

---

go/cmd/vtgateclienttest/services/callerid.go
go/cmd/vtgateclienttest/services/echo.go
go/cmd/vtgateclienttest/services/errors.go
go/cmd/vtgateclienttest/services/fallback.go
go/cmd/vtgateclienttest/services/terminal.go
go/vt/client/fakeserver_test.go
go/vt/vtgate/bsonp3vtgateconn/conn.go
go/vt/vtgate/bsonp3vtgateservice/server.go
go/vt/vtgate/fakerpcvtgateconn/conn.go
go/vt/vtgate/gorpcvtgateconn/conn.go
go/vt/vtgate/gorpcvtgateservice/server.go
go/vt/vtgate/grpcvtgateconn/conn.go
go/vt/vtgate/grpcvtgateservice/server.go
go/vt/vtgate/resolver.go
go/vt/vtgate/resolver_test.go
go/vt/vtgate/topo_utils.go
go/vt/vtgate/vtgate.go
go/vt/vtgate/vtgate_test.go
go/vt/vtgate/vtgateconn/vtgateconn.go
go/vt/vtgate/vtgateconntest/client.go
go/vt/vtgate/vtgateservice/interface.go
java/grpc-client/src/test/java/com/youtube/vitess/client/grpc/GrpcClientTest.java
php/tests/VTGateConnTest.php

Changing type used by ExecuteEntityIds to be the proto3 one.

---

go/cmd/vtgateclienttest/services/fallback.go
go/cmd/vtgateclienttest/services/terminal.go
go/vt/client/fakeserver_test.go
go/vt/vtgate/vtgate.go
go/vt/vtgate/vtgateconntest/client.go
go/vt/vtgate/vtgateservice/interface.go

(this is a short term fix to an internal google issue).
@enisoc @guoliang100 @apmichaud

Adding GetSrvShard to the vtgate server internal API.

---

test/utils.py
test/worker.py

NOTE: Changes were already LGTM'd internally.

Exporting internal changes back to open-source.

---

go/vt/vterrors/vterrors.go
go/vt/vtgate/sandbox_test.go
go/vt/vtgate/scatter_conn_test.go
go/vt/vtgate/shard_conn.go
go/vt/vtgate/shard_conn_flaky_test.go

@sougou @alainjobart 
Added more tests, now I have a high degree of confidence that this works :)

Fix for ShardConn not propagating error codes

---

go/vt/tabletserver/tablet_error_test.go
go/vt/vtgate/scatter_conn_test.go
go/vt/vtgate/vtgate_error.go
go/vt/vtgate/vtgate_error_test.go

Add unit tests for some vtgate error handling logic

---

go/vt/tabletserver/gorpctabletconn/conn_test.go
go/vt/tabletserver/grpctabletconn/conn_test.go
go/vt/tabletserver/tabletconntest/tabletconntest.go
go/vt/vtgate/gorpcvtgateconn/conn_rpc_test.go
go/vt/vtgate/grpcvtgateconn/conn.go
go/vt/vtgate/grpcvtgateconn/conn_rpc_test.go
go/vt/vtgate/vtgateconn/vtgateconn.go
go/vt/vtgate/vtgateconn/vtgateconn_test.go
go/vt/vtgate/vtgateconntest/client.go

@alainjobart 
more testing for error codes, and a bug fix that those tests exposed.
Next up: fixing up BsonP3, then the internal versions, and then cleaning up lots of protos.

Check error codes in conn tests

---

test/TestingStrategy.md

Figured it's better if it's written down, as it's not obvious yet in the tree.

First version of a doc to describe our testing strategy for Vitess.

---

go/vt/automation/scheduler_test.go

@sougou 
Exported from Google CL.

Replace context.TODO() with context.Background() in tests.

---

go/vt/proto/vtgate/vtgate.pb.go
java/client/src/main/java/com/youtube/vitess/client/RpcClient.java
java/grpc-client/src/main/java/com/youtube/vitess/client/grpc/GrpcClient.java
proto/vtgate.proto
py/vtproto/vtgate_pb2.py

@alainjobart @enisoc 
Won't check this in until all internal changes are done

Remove RPCError from proto3 responses where it's unused

---

py/vttest/environment.py
py/vttest/local_database.py
py/vttest/mysql_db_mysqlctl.py
py/vttest/mysql_flavor.py
py/vttest/run_local_database.py

@alainjobart 
This has the changes needed to launch a standalone mysql instance.

vttest: prep for go queryservice test

---

java/vtgate-client/src/main/java/com/youtube/vitess/vtgate/rpcclient/RpcClient.java
java/vtgate-client/src/main/java/com/youtube/vitess/vtgate/rpcclient/gorpc/GoRpcClient.java

Use Object instead of com.youtube.vitess.proto.Vtgate.Session to avoid
import error.

change java client executeBatch function signature.

---

go/vt/vttest/environment.go
go/vt/vttest/local_cluster.go
go/vt/vttest/local_cluster_test.go
py/vttest/local_database.py

Simple go wrappers for launching py/vttest/run_local_databse.py.
The LaunchVitess test is still not working. We'll have to
troubleshoot it later.

vttest: go side of things

---

go/cmd/vtgate/vtgate.go
go/vt/discovery/fake_health_check_test.go
go/vt/discovery/healthcheck.go
go/vt/discovery/healthcheck_test.go
go/vt/vtgate/discoverygateway.go
go/vt/vtgate/gateway.go
go/vt/vtgate/resolver.go
go/vt/vtgate/resolver_test.go
go/vt/vtgate/router_framework_test.go
go/vt/vtgate/router_select_flaky_test.go
go/vt/vtgate/scatter_conn.go
go/vt/vtgate/scatter_conn_test.go
go/vt/vtgate/shardgateway.go
go/vt/vtgate/vertical_split_test.go
go/vt/vtgate/vtgate.go
go/vt/vtgate/vtgate_test.go

First code piece of OS gateway, and linking to vtgate and health check

---

go/vt/discovery/fake_health_check_test.go
go/vt/discovery/healthcheck.go

@alainjobart @sougou @guokeno0

Add stats to HealthCheck, and export its cache.

---

doc/GettingStartedKubernetes.md
examples/kubernetes/env.sh
examples/kubernetes/etcd-controller-template.yaml

Fix issues when running Kubernetes example on Vagrant

---

go/vt/discovery/healthcheck.go

@guoliang100 had to make this change for import to work, shard is reserved there.

Changing a name to avoid internal conflict.

---

go/vt/vttest/environment.go
go/vt/vttest/local_cluster.go
go/vt/vttest/local_cluster_test.go
py/vttest/environment.py
py/vttest/fakezk_config.py
py/vttest/local_database.py
py/vttest/vt_processes.py

Fixing vttest for go / vitess.

---

go/vt/topotools/topology.go

Removing a couple usages of old topo.TabletType.

---

go/cmd/vtcombo/main.go
go/cmd/vtcombo/plugin_bsonp3vtgateservice.go
go/cmd/vtcombo/plugin_gorpcvtgateservice.go
go/cmd/vtcombo/plugin_grpcvtgateservice.go
go/cmd/vtcombo/tablet_map.go
go/cmd/vttablet/vttablet.go
go/vt/binlog/updatestreamctl.go
go/vt/tabletmanager/agent.go
go/vt/tabletserver/tabletserver.go
py/vttest/environment.py
py/vttest/local_database.py
py/vttest/run_local_database.py
py/vttest/vt_processes.py
test/tablet.py
test/vttest_sample_test.py

@sougou @enisoc @guoliang100 
I am able to run queries through it, seems to work. The end-to-end tests are not there yet (as we are missing gRPC python client), I am planning on using google3 tests for full validation for now. I need to fix the plumbing in google3 (and BUILD files too) so I'd like to start with that.

vtcombo initial addition.

---

doc/vtctlReference.md
go/cmd/vtcombo/tablet_map.go
go/vt/tabletmanager/after_action.go
go/vt/tabletmanager/agent.go
go/vt/tabletserver/customrule/filecustomrule/filecustomrule.go
go/vt/tabletserver/customrule/zkcustomrule/zkcustomrule.go
go/vt/tabletserver/query_executor_test.go
go/vt/tabletserver/query_rule_info.go
go/vt/tabletserver/queryctl.go
go/vt/tabletserver/schema_info.go
go/vt/vtctl/query.go
go/vt/vtgate/vtgate_test.go
py/vttest/local_database.py
py/vttest/vt_processes.py
test/custom_sharding.py
test/utils.py
test/vttest_sample_test.py

@sougou you can re-organize the tabletserver code later if you want, this felt like the easiest way.
@enisoc for general review.

vtcombo next step, now KeyspaceIds queries should work.

---

java/client/src/test/java/com/youtube/vitess/client/cursor/CursorTest.java
java/grpc-client/src/test/java/com/youtube/vitess/client/grpc/GrpcClientTest.java

java: Add @RunWith annotation on new tests.

---

examples/local/vtctld-up.sh
examples/local/vtgate-up.sh
examples/local/vttablet-up.sh

@alainjobart 
Fixes https://groups.google.com/d/msg/vitess/8veHu0MW9jE/uFT-xzuOBAAJ

examples/local: Add -service_map flags since bson is no longer default.

---

py/vtdb/dbexceptions.py
py/vtdb/tablet.py
py/vtdb/vtgate_client.py
py/vtdb/vtgate_utils.py
py/vtdb/vtgatev2.py
py/vtdb/vtgatev3.py
test/java_vtgate_test_helper.py
test/python_client_test.py
test/utils.py
test/vtgate_utils_test.py

Primary: @dumbunny 
FYI: @alainjobart

Stop parsing errors in python vtgate client

---

go/mysql/mysql.go
go/vt/tabletserver/endtoend/framework/client.go
go/vt/tabletserver/endtoend/framework/logtracker.go
go/vt/tabletserver/endtoend/nocache_test.go
go/vt/tabletserver/endtoend/transaction_test.go
go/vt/tabletserver/query_engine.go
go/vt/tabletserver/query_executor.go
go/vt/tabletserver/query_executor_test.go
go/vt/tabletserver/tabletserver.go
go/vt/tabletserver/tx_pool.go
go/vt/tabletserver/tx_pool_test.go
test/queryservice_tests/nocache_tests.py

Transaction Fetcher in framework.
Transaction tests.
Tweaked some mysql vars.
Moved some timeouts from inner objects to TabletServer.

tabletserver endtoend: WIP

---

go/vt/vtgate/discoverygateway.go
go/vt/vtgate/gateway.go
go/vt/vtgate/scatter_conn.go
go/vt/vtgate/shardgateway.go

Update Gateway interface.

---

test/python_client_test.py

Disable some tests that don't work for all clients

---

go/vt/tabletserver/endtoend/framework/logtracker.go
go/vt/tabletserver/endtoend/framework/server.go
go/vt/tabletserver/endtoend/nocache_test.go
go/vt/tabletserver/endtoend/transaction_test.go
go/vt/tabletserver/query_executor.go
go/vt/tabletserver/schema_info.go
go/vt/tabletserver/tabletserver.go

This reverts commit bf185cb9dbfac57a4624a982888b671f6743f42b, reversing
changes made to 347c76ff509a376551ec0e0c963a87530026df02.

Revert "Merge branch 'suguwork'"

---

.travis.yml
travis/check_make_proto.sh

If not, the test fails and the author of the pull request has to run
"make proto" locally and include its changes.

travis: Add check if generated protobuf and gRPC files are up to date.

---

go/vt/tabletserver/endtoend/framework/logtracker.go
go/vt/tabletserver/endtoend/framework/server.go
go/vt/tabletserver/endtoend/nocache_test.go
go/vt/tabletserver/endtoend/transaction_test.go
go/vt/tabletserver/query_executor.go
go/vt/tabletserver/schema_info.go
go/vt/tabletserver/schema_info_test.go
go/vt/tabletserver/tabletserver.go

And fix the part that broke the build.

tabletserver: revert the revert

---

docker/bootstrap/Dockerfile.common
php/README.md
travis/php_init.sh

Pin PHPUnit to a version that supports PHP 5.3.

---

go/cmd/vtcombo/tablet_map.go

@aaijazi 
Again tests inside google3 found this one.

Fixing a case where err could be nil and trigger a panic.

---

go/cmd/vtgate/status.go

Add healthcheck stats to status page.

---

go/cmd/vtcombo/tablet_map.go
go/vt/tabletserver/tabletconn/grpc_error.go

@aaijazi This is better, you're right.

Changing the code a bit after comments.

---

go/vt/discovery/healthcheck.go

- Do no reconnect when error is set by tablet
- Remove spamming logs
- Fix cells for CacheStatus

Fix a few things in HealthCheck

---

go/cmd/vtgate/vtgate.go

Add flag for health check retry delay.

---

java/client/src/main/java/com/youtube/vitess/client/cursor/StreamCursor.java
java/client/src/test/java/com/youtube/vitess/client/RpcClientTest.java

java: Allow getFields() before next() in StreamCursor.

---

go/vt/topotools/tablet.go

@alainjobart 
We were already calling GetTablet within ChangeType, so there was no
attempt to ensure consistency with any previous node version seen by the
caller. Given that, there's no reason not to retry the update in
ChangeType if we get a bad node version.

topotools.ChangeType: Retry on bad node version.

---

doc/GettingStartedKubernetes.md
doc/ShardingKubernetes.md
examples/kubernetes/README.md
examples/kubernetes/guestbook/Dockerfile
examples/kubernetes/guestbook/build.sh
examples/kubernetes/guestbook/extract.sh
examples/kubernetes/sharded-vtworker.sh
examples/kubernetes/vtgate-controller-template.yaml
examples/kubernetes/vttablet-pod-benchmarking-template.yaml
examples/kubernetes/vttablet-pod-template.yaml
examples/kubernetes/vtworker-pod-template.yaml

Kubernetes config and doc updates

---

doc/Concepts.md
doc/GettingStartedKubernetes.md

Small fixes to the Kubernetes Getting Started guide.

---

go/vt/discovery/healthcheck.go

Fix status html for healthcheck

---

doc/ClientLibraries.md

Removed reference to the v3 Go client.
Preview: http://imgur.com/MhoZcAG
@enisoc

doc: Re-wrote section for Go client.

---

go/cmd/vtgateclienttest/services/errors.go
java/client/src/main/java/com/youtube/vitess/client/Proto.java
java/client/src/main/java/com/youtube/vitess/client/VTGateTx.java
java/client/src/test/java/com/youtube/vitess/client/RpcClientTest.java
java/grpc-client/src/main/java/com/youtube/vitess/client/grpc/GrpcClient.java
java/grpc-client/src/main/java/com/youtube/vitess/client/grpc/GrpcStreamAdapter.java

java/client: Implement canonical error conversion.

---

doc/ClientLibraries.md
doc/GettingStarted.md
doc/GettingStartedKubernetes.md
doc/ShardingKubernetes.md
examples/kubernetes/sharded-vtworker.sh

doc: Small fixes after going through the Kubernetes guides.

---

go/mysql/mysql.go
go/vt/tabletserver/tablet_error.go
go/vt/tabletserver/tabletserver.go

@guokeno0 @sougou 
My plan is to, in a few weeks, collect all these errors together under the BAD_INPUT error code. And then look at the error code and demote all errors that fall under BAD_INPUT, as well as exclude them from our error counters.

Demote one more MySQL error from the logs

---

py/vttest/vt_processes.py

@enisoc will merge and import now.

Adding longer timeouts for unit tests.

---

go/vt/discovery/healthcheck.go

Add logging and status to healthcheck.

---

py/vtdb/vtgate_client.py
py/vttest/environment.py
test/gorpc_protocols_flavor.py
test/grpc_protocols_flavor.py
test/protocols_flavor.py
test/vttest_sample_test.py

This requires using the protocol from flavors.
Also using ValueError exception instead of plain Exception
in vtgate_client.py.
@dumbunny @aaijazi

Adding a unit test of the vttest setup in vttest_sample_test.py.

---

go/cmd/vtgate/vtgate.go
go/vt/discovery/fake_health_check_test.go
go/vt/discovery/healthcheck.go
go/vt/vtgate/balancer.go
go/vt/vtgate/discoverygateway.go
go/vt/vtgate/discoverygateway_test.go

Implement gateway with discovery module.

---

py/vtdb/__init__.py

Simple removal of unused imports in py/vtdb/__init__.py.

Clean up py/vtdb/__init__.py.

---

go/vt/vtgate/gorpcvtgateconn/conn_rpc_test.go
go/vt/vtgate/gorpcvtgateservice/server.go
go/vt/vtgate/vtgate.go
java/vtgate-client/src/main/java/com/youtube/vitess/vtgate/RPCError.java
java/vtgate-client/src/main/java/com/youtube/vitess/vtgate/SplitQueryResponse.java
java/vtgate-client/src/main/java/com/youtube/vitess/vtgate/rpcclient/gorpc/Bsonify.java
java/vtgate-client/src/main/java/com/youtube/vitess/vtgate/rpcclient/gorpc/GoRpcClient.java
test/java_vtgate_test_helper.py
test/python_client_test.py
test/utils.py

This isn't ready for review yet, I'm creating the PR to trigger Travis builds. I believe the Java client needs a good deal of work still.

Remove --rpc-only-in-reply flag from VTGate

---

examples/demo/cgi-bin/data.py
examples/demo/index.html
examples/demo/run.py
examples/demo/schema/lookup/lookup_schema.sql
examples/demo/schema/user/user_schema.sql
examples/demo/schema/vschema.json
go/cmd/vtcombo/main.go
go/vt/tabletserver/endtoend/config_test.go
go/vt/tabletserver/endtoend/transaction_test.go
py/vttest/local_database.py
py/vttest/run_local_database.py
py/vttest/vt_processes.py

The v3 demo has been changed to use vttest, and there is a script
that brings up everything, and tears down at the end.
The one problem with the new scheme is that the querylog
doesn't tell you which tablet the query came from. Something
to think about in the future.

v3 demo: is now self-contained

---

test/java_vtgate_test_helper.py
test/vtgatev2_test.py

@dumbunny (this is already part of the import)

Removing a couple unused imports.

---

go/vt/discovery/healthcheck.go

Update healthcheck status message

---

doc/HorizontalReshardingGuide.md
examples/local/vttablet-up.sh

Update horizontal sharding guide

---

java/client/src/main/java/com/youtube/vitess/client/cursor/Row.java
java/hadoop/src/main/java/com/youtube/vitess/hadoop/RowWritable.java
java/hadoop/src/main/java/com/youtube/vitess/hadoop/VitessInputFormat.java
java/hadoop/src/main/java/com/youtube/vitess/hadoop/VitessRecordReader.java

cursor.Row implments Writable interface which only presents in hadoop.
To get rid of this dependency, a new RowWritable class is created.

Add RowWritable class in hadoop package

---

go/vt/tabletserver/tabletserver.go

@guokeno0 @alainjobart 
We discovered an interesting race condition between Begin
and StopServer:
* Begin gets called: reserves a request, but takes time to
perform the next step, state is SERVING.
* StopService gets called: transitions state to SHUTTING_DOWN.
* StopService calls WaitForTx: the pool is empty. So, it
proceeds to perform other shutdown operations.
* Begin opens a transaction, because it was given permission.
The pool is not empty any more.
* StopService calls txpool.Close, which gets angry because
no transactions should be in it.
One possible solution I considered was to reserve an entry
in the transaction pool during startRequest. Then Begin would
later fill it out with the connection obtained after BEGIN
succeeded.  This would eliminate the race, but it also
introduces …

tabletserver: fix race condition

---

Makefile
docker/etcd-lite/build.sh

docker: Add Makefile rule for building etcd-lite image.

---

go/vt/binlog/updatestreamctl.go
test/vtgatev2_test.py

Using protocol_flavors in vtgatev2_test.

---

go/vt/discovery/healthcheck.go
go/vt/discovery/healthcheck_test.go

Update cachestatus to show unknown endpoints as well.

Fix race condition in add/remove endpoint in healthcheck.

---

test/config.json
test/vtctld_test.py

@enisoc @sougou This was broken, but was undetected. Fixing both.

Fixing vtctld test, adding it to travis run.

---

go/cmd/vtcombo/tablet_map.go

Only setting the sharding info in vtcombo for sharded keyspaces.

---

test/update_stream.py

@enisoc @sougou @guoliang100 whoever gets there first :)

Fix flakiness in this test: ReloadSchema might be asynchronous.

---

py/vttest/local_database.py

Also add more checks and clearer error messages.
h/t to @michael-berlin

Only consider *.sql files when applying schema.

---

py/vttest/local_database.py

Reverts youtube/vitess#1235
Internal end-to-end tests are breaking due to the hard error. To unbreak the import for other people, I'm reverting this now.
I'll fix the internal tests first and then re-add these changes.

Revert "Only consider *.sql files when applying schema."

---

go/vt/tabletserver/query_executor.go

Slightly improve an error message for DMLs outside of transactions

---

go/cmd/vtcombo/tablet_map.go
go/cmd/vtgateclienttest/goclienttest/echo.go
go/cmd/vtgateclienttest/services/echo.go
go/vt/tabletserver/grpcqueryservice/server.go
go/vt/tabletserver/grpctabletconn/conn.go
go/vt/tabletserver/proto/proto3.go
go/vt/vtgate/grpcvtgateconn/conn.go
go/vt/vtgate/proto/proto3.go
go/vt/vtgate/scatter_conn.go

Plumb the error all the way through the stack.
I didn't spot any proto3 tests to which i could add something, but let me know if i just missed them.

Introduce error for types that can't be bound to proto3.

---

test/worker.py

Make some fixes for test/worker.py now that we create the db on shard init

---

go/vt/binlog/updatestreamctl.go
go/vt/etcdtopo/client_test.go
go/vt/etcdtopo/keyspace.go
go/vt/etcdtopo/lock.go
go/vt/etcdtopo/server_test.go
go/vt/etcdtopo/shard.go

etcd: Use TTL on locks to avoid orphans.

---

go/vt/worker/clone_utils.go

Add more logging on errors for clone_utils.go:resolveDestinationShardMaster

---

go/vt/vtgate/discoverygateway.go
go/vt/vtgate/shard_conn.go

Make all fields in ShardConnError public.

---

php/tests/VTGateConnTest.php

@alainjobart 
It was depending on map ordering.

php: Deflake testEchoSplitQuery()

---

go/vt/tabletserver/customrule/filecustomrule/filecustomrule_test.go
go/vt/tabletserver/customrule/zkcustomrule/zkcustomrule_test.go
go/vt/tabletserver/endtoend/acl_test.go
go/vt/tabletserver/endtoend/framework/debugvars.go
go/vt/tabletserver/planbuilder/plan.go
go/vt/tabletserver/query_engine.go
go/vt/tabletserver/query_rule_info.go
go/vt/tabletserver/query_rule_info_test.go
go/vt/tabletserver/query_rules.go
go/vt/tabletserver/query_rules_test.go
go/vt/tabletserver/schema_info.go

@guokeno0 
* Improved JSON syntax for bindvar constraints
* /debug/query_rules URL to view current rule sets

query_rules improvements

---

go/vt/automation/migrate_served_types_task.go
go/vt/automation/migrate_served_types_task_test.go

NOTE: Changes were already LGTM'd internally.

automation: Added "cell" parameter to MigrateServedTypes task.

---

misc/git/hooks/pylint
py/vtdb/base_cursor.py
py/vtdb/keyrange_constants.py
py/vtdb/keyspace.py
py/vtdb/vtgate_cursor.py
py/vtdb/vtgatev3.py

This uses /usr/bin/gpylint; systems without gpylint will
skip this check.
@mberlin

Add pylint pre-commit hook.

---

.travis.yml
bootstrap.sh
dev.env
docker/bootstrap/Dockerfile.common
docker/lite/Dockerfile
docker/lite/Dockerfile.mariadb
examples/local/env.sh
go/zk/zkctl/zksrv.sh

Upgrade to ZooKeeper 3.4.6.

---

docker/bootstrap/README.md

@enisoc 
FYI: I used http://dillinger.io/ to preview the markdown and it worked pretty well :) It's behavior is a little bit different from the Github display, but after all it gets very close.

docker: Document how to update the bootstrap images.

---

misc/git/hooks/pylint
py/vtdb/__init__.py
py/vtdb/topology.py
py/vtdb/vtgate_client.py
py/vtdb/vtgate_utils.py

Fix pylint issues in a handful of easy-to-fix python files.

Improve pylint pre-commit hook

---

go/cmd/vtworker/vtworker.go
go/vt/worker/instance.go
go/vt/worker/interactive.go
go/vt/worker/split_clone_test.go
go/vt/worker/split_diff_cmd.go
go/vt/worker/split_diff_test.go
go/vt/worker/vertical_split_clone_test.go
go/vt/worker/vertical_split_diff_test.go
go/vt/worker/vtworkerclient/client_testsuite.go

@alainjobart 
Making the internal go vet happy ;-)
Also fixing one possible bug when triggering SplitDiff through the webinterface.

worker: Plumb context.Background() through from main().

---

go/vt/discovery/healthcheck.go
go/vt/discovery/healthcheck_test.go
go/vt/tabletmanager/binlog.go
go/vt/vtgate/discoverygateway.go
go/vt/vtgate/shard_conn.go
go/vt/vtgate/shardgateway.go
go/vt/vtgate/vtgate_error.go
go/vt/vtgate/vtgate_error_test.go

- Add a field indicating an endpoint is added, which is then sent out to listener.
- Change StatsUpdate to send EndPointStats.
- Make some func public.

HealthCheck module improvements.

---

go/vt/automation/copy_schema_shard_task.go
go/vt/automation/copy_schema_shard_task_test.go
go/vt/automation/migrate_served_types_task.go
go/vt/automation/migrate_served_types_task_test.go
go/vt/automation/split_clone_task.go
go/vt/automation/split_diff_task.go
go/vt/automation/testutils_test.go

automation: CopySchemaShard: Add parameter "exclude_tables".

---

test/vtctld_test.py
travis/install_grpc.sh

This test shows how gRPC doesn't exit properly.
@enisoc @michael-berlin

grpc update, and new streaming rpc test.

---

go/vt/automation/migrate_served_types_task.go
go/vt/automation/migrate_served_types_task_test.go

Fix cells parameter for vtctl MigrateServedTypes automation task.

---

go/vt/discovery/replicationlag.go
go/vt/discovery/replicationlag_test.go
go/vt/vtgate/discoverygateway.go
go/vt/vtgate/discoverygateway_test.go

Implement endpoint filter by replication lag.

---

go/cmd/vtgateclienttest/goclienttest/errors.go
go/cmd/vtgateclienttest/services/errors.go

vtgateclienttest: Implement error tests for Go

---

go/vt/schemamanager/local_controller_test.go
go/vt/schemamanager/schemamanager.go
go/vt/schemamanager/schemamanager_test.go
go/vt/schemamanager/tablet_executor.go
go/vt/tabletmanager/agent_rpc_actions.go
go/vt/tabletmanager/agentrpctest/test_agent_rpc.go
go/vt/tabletmanager/faketmclient/fake_client.go
go/vt/tabletmanager/grpctmclient/client.go
go/vt/tabletmanager/grpctmserver/server.go
go/vt/tabletmanager/tmclient/rpc_client_api.go
go/vt/worker/clone_utils.go
go/vt/wrangler/tablet.go
test/resharding.py
test/tabletmanager.py

This feels simpler everywhere, except for one place where we're lacking
the right helper methods, but I know this is coming in Sugu's next changes.
@sougou @dumbunny

Changing tabletmanager API to use the proto3 QueryResult directly.

---

go/vt/tabletmanager/after_action.go
go/vt/tabletmanager/healthcheck_test.go
go/vt/tabletserver/config.go
go/vt/tabletserver/tabletserver.go
go/vt/tabletserver/tabletserver_test.go
go/vt/tabletserver/tabletservermock/controller.go

tabletserver: lameduck & secondary serving types

---

go/cmd/vttablet/status.go
go/vt/tabletserver/status.go
go/vt/tabletserver/tabletserver.go

@sougou 
This was a feature request from SRE.

tabletserver: Add state history to status page.

---

test/backup.py
test/reparent.py
test/rowcache_invalidator.py
test/sharded.py
test/utils.py

@alainjobart 
and more pylint fixes

test: Remove invocations of vtgate where it's (no longer?) necessary.

---

test/python_client_test.py

Enable python client tests for all protocols

---

go/vt/discovery/fake_health_check_test.go
go/vt/discovery/topology_watcher_test.go

Fix race condition in discovery test

---

go/vt/tabletserver/proto/proto3.go

One change needed for import.

---

go/vt/tabletserver/proto/proto3.go
go/vt/tabletserver/proto/structs.go

Removing a few obsolete BSON structures.

---

go/vt/topo/server.go
go/vt/topo/shard.go
go/vt/wrangler/reparent.go
go/vt/wrangler/tablet.go

Will be more resilient to underlying shard updates.
@michael-berlin @enisoc

Using ShardUpdateFields in reparent in a few places.

---

go/cmd/vtcombo/tablet_map.go
go/vt/discovery/healthcheck_test.go
go/vt/tabletmanager/binlog_test.go
go/vt/tabletserver/grpctabletconn/conn.go
go/vt/tabletserver/tabletconn/tablet_conn.go
go/vt/tabletserver/tabletconntest/tabletconntest.go
go/vt/vtgate/discoverygateway.go
go/vt/vtgate/gateway.go
go/vt/vtgate/resolver.go
go/vt/vtgate/resolver_test.go
go/vt/vtgate/sandbox_test.go
go/vt/vtgate/scatter_conn.go
go/vt/vtgate/scatter_conn_test.go
go/vt/vtgate/shard_conn.go
go/vt/vtgate/shardgateway.go
go/vt/vtgate/vertical_split_test.go
go/vt/vtgate/vtgate.go

@sougou @enisoc 
Would like to merge and import as soon as possible, so I can go on vacation happier... ;)

Switching tabletconn API out of tproto.QueyrResultList.

---

.travis.yml
Makefile
go/vt/tabletmanager/agentrpctest/test_agent_rpc.go
tools/unit_test_race.sh
travis/download_mariadb.sh

Travis: Switch to Go 1.5. Fix that unit_test_race fails when a race is found.

---

test/update_stream.py

Fixing a source of flakiness in this test.

---

test/vtgatev2_test.py

Make vtgatev2 test less flaky.

---

bootstrap.sh
go/vt/vtctl/vtctl.go
go/vt/vtgate/scatter_conn.go
go/vt/vtgate/topo_utils.go
test/initial_sharding.py

Re-upload of Erez PR: https://github.com/youtube/vitess/pull/1370 + test fix to let Travis pass.

Fixing vtctl and execute keyranges + test fix

---

examples/demo/client.php
examples/local/client.go
examples/local/client.php
examples/local/client.py
examples/local/vtgate-up.sh
php/README.md
php/composer.lock
test/local_example.sh
travis/php_grpc.sh
travis/php_init.sh

These are alternative clients that show how to do the same thing as examples/local/client.py in other languages. This came about because a user got stuck on the fact that php/demo.php was incompatible with examples/local.

Add more sample clients for examples/local.

---

go/vt/etcdtopo/keyspace.go
go/vt/etcdtopo/shard.go
go/vt/etcdtopo/tablet.go
go/vt/topo/test/keyspace.go
go/vt/topo/test/shard.go
go/vt/topo/test/tablet.go

@alainjobart 
We just started using this for UpdateTablet, and it turns out it was never implemented for etcdtopo.

etcdtopo: Implement unconditional updates.

---

examples/local/client.go
go/cmd/vtclient/vtclient.go
go/vt/vitessdriver/driver.go
go/vt/vitessdriver/driver_test.go
go/vt/vitessdriver/fakeserver_test.go
test/vtgatev3_test.py

vitessdriver: Add helper methods and refactor tests.

---

test/custom_sharding.py

Removing one source of flakiness in this test.

---

examples/demo/run.py

demo: set web_dir for vtctld

---

go/vt/tabletserver/status.go

Fixing wrap around in minutes in vttablet's QPS graph.

---

go/cmd/vtcombo/main.go
go/cmd/vtcombo/plugin_gorpcvtctlserver.go
go/cmd/vtcombo/plugin_grpcvtctlserver.go
go/cmd/vtcombo/tablet_map.go
py/vttest/environment.py
test/vttest_sample_test.py

@sougou @michael-berlin
Now for instance 'Ping' in the exported vtctld UI works, or remote vtctl commands using vtctlclient to vtcombo also work.

Adding vtctl RPC interface to vtcombo, with unit test.

---

go/vt/tabletserver/dbconn.go
go/vt/tabletserver/query_executor.go
go/vt/tabletserver/schema_info.go

Adding trace spans for 3 areas in tabletserver.

---

go/vt/discovery/healthcheck.go
test/tablet.py
test/topo_flavor/etcd.py
test/topo_flavor/server.py
test/topo_flavor/zookeeper.py
test/utils.py
test/vtgate_gateway_flavor/discoverygateway.py
test/vtgate_gateway_flavor/gateway.py
test/vtgate_gateway_flavor/shardgateway.py
test/vtgatev2_test.py

Update vtgatev2 test to better support testing gateway implementations.

---

examples/kubernetes/advanced.md
examples/kubernetes/vitess-up.sh
examples/kubernetes/vtgate-controller-benchmarking-template.yaml

Update k8s scripts and docs

---

java/client/src/main/java/com/youtube/vitess/client/cursor/Cursor.java
java/client/src/main/java/com/youtube/vitess/client/cursor/FieldMap.java
java/client/src/main/java/com/youtube/vitess/client/cursor/Row.java
java/client/src/main/java/com/youtube/vitess/client/cursor/SimpleCursor.java
java/client/src/main/java/com/youtube/vitess/client/cursor/StreamCursor.java
java/hadoop/src/main/java/com/youtube/vitess/hadoop/RowWritable.java

@erzel 
Sometimes we want the type conversion offered by Row,
without the QueryResult processing of Cursor.

java: Make Row class more useful without Cursor.

---

test/environment.py
test/gorpc_protocols_flavor.py
test/grpc_protocols_flavor.py
test/protocols_flavor.py
test/tablet.py
test/utils.py
test/vtgatev3_test.py

So we can switch to explicit registration, instead of having modules
register themselves, which is not very pythonic.
@dumbunny @aaijazi

Re-organizing the imports in the tests.

---

go/vt/tabletserver/tabletserver.go

Fix recorded start time for transaction calls

---

go/vt/tabletmanager/binlog.go
go/vt/worker/split_clone_test.go
go/vt/worker/split_diff_test.go
go/vt/worker/topo_utils.go
go/vt/worker/vertical_split_clone_test.go
go/vt/worker/vertical_split_diff_test.go
test/binlog.py
test/initial_sharding.py
test/resharding.py
test/vertical_split.py

Use better endpoint management for workers finding rdonly instances.

---

test/vtgatev2_test.py

but we're going away from it.
@guoliang100

Removing obsolete test. It's only valid for gorpc now,

---

go/vt/vtctld/api.go
go/vt/vtctld/api_test.go
web/vtctld/api.js

@enisoc as we discussed, this is unused.

Removing unused GetEndPoints vtctld API.

---

java/example/src/main/java/com/youtube/vitess/example/VitessClientExample.java
java/grpc-client/src/main/java/com/youtube/vitess/client/grpc/GrpcClient.java

java/example: Use try-resource blocks instead of close() statements.
@enisoc

java/client: More specific error for failed connections.

---

go/vt/topotools/rebuild_shard.go

@alainjobart 
These were logged originally to verify that contention was rare.
If it turned out to be common in practice, we should go back to
pessimistic locking.
Contention on the serving graph has indeed been rare, but when it does
happen, these messages are [confusing](https://groups.google.com/d/msg/vitess/NOD1YWWc2SM/isxuFD9QEwAJ) because they seem to indicate a
problem.

Remove confusing log messages in serving graph rebuild.

---

doc/V3HighLevelDesign.md
doc/V3VindexDesign.md
doc/VTGateV3Features.md
go/vt/vitessdriver/doc.go

This is an export of my initial draft. More iterations will follow later.

V3 high level desgin

---

go/vt/vtctl/vtctl.go

@enisoc based on our discussions earlier today.

Add GetKeyspaces to vtctld

---

go/vt/tabletmanager/actionnode/actionnode.go
go/vt/tabletmanager/actionnode/structs.go
go/vt/wrangler/schema.go

vtctl: Remove old, now unused, ApplySchemaShard code.

---

go/vt/automation/copy_schema_shard_task.go
go/vt/automation/copy_schema_shard_task_test.go
go/vt/automation/horizontal_resharding_task.go
go/vt/automation/migrate_served_from_task.go
go/vt/automation/migrate_served_types_task.go
go/vt/automation/scheduler.go
go/vt/automation/scheduler_test.go
go/vt/automation/split_clone_task.go
go/vt/automation/split_clone_task_test.go
go/vt/automation/split_diff_task.go
go/vt/automation/vertical_split_clone_task.go
go/vt/automation/vertical_split_diff_task.go
go/vt/automation/vertical_split_task.go
go/vt/automation/vertical_split_task_test.go
go/vt/automation/wait_for_filtered_replication_task.go
go/vt/topo/topoproto/shard.go
go/vt/worker/vertical_split_clone.go
go/vt/worker/vtworkerclient/interface.go
test/automation_vertical_split.py
test/config.json
test/vertical_split.py

automation: Cluster operation for vertical split.

---

travis/install_protobuf.sh

The grpc library has not yet been updated for a renamed function in
protobuf v3.0.0-beta-2:
https://github.com/grpc/grpc/issues/4505

Revert to protobuf v3.0.0-beta-1

---

doc/vtctlReference.md
doc/vtctl_go_reference.py

The problems aries from the change in syntax in the source tree,
as we don't put the structure name in the data definition any more.

Fixing the vtctl doc command script, and re-running it.

---

travis/install_protobuf.sh

Protobuf beta 2 on OSX (on Linux, beta 1 stays as before)

---

test/vertical_split.py

@alainjobart 
I've made the changes we talked about earlier today.

Various improvements to vertical_split.py.

---

py/vtdb/vtgate_client.py
py/vtdb/vtgate_cursor.py
py/vtdb/vtgatev2.py

@dumbunny Exporting changes that were made internally. I'll merge this after tests pass.

Pass kwargs through from the VtGate cursor to the VtGateConnection

---

examples/kubernetes/guestbook/main.py

guestbook: Fix vtgate address.

---

examples/kubernetes/guestbook-down.sh

Fix typo in guestbook-down.sh

---

go/vt/tabletserver/query_service_stats.go
go/vt/tabletserver/schema_info.go
go/vt/tabletserver/schema_info_test.go
go/vt/tabletserver/tabletserver_test.go

An error when loading schema at tablet start up shouldn't be fatal

---

go/vt/discovery/topology_watcher.go
go/vt/discovery/topology_watcher_test.go
go/vt/tabletmanager/binlog.go
go/vt/worker/topo_utils.go
test/tablet.py

@guoliang100 @alainjobart 
Liang, this isn't the change I talked about with you some minutes ago. Instead, these are some smaller things which I discussed with Alain yesterday.
In particular, Stop() was missing on the watcher instances. I assume just calling Stop() is the right way to do?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1456)

Fix small things around the discovery module.

---

py/vtdb/grpc_vtgate_client.py
py/vtdb/keyrange_constants.py
py/vtdb/vtgate_client.py
py/vtdb/vtgate_utils.py
py/vtdb/vtgatev2.py
test/grpc_protocols_flavor.py
test/keyspace_test.py
test/python_client_test.py
test/utils.py
test/vertical_split.py
test/vtgatev2_test.py
test/vtgatev3_test.py

It passes python_client_test so far, not more.
Stuck on the batch API for now, not sure we need the dual-API.
@aaijazi if you're curious. Not ready to pull in yet.

Adding a gRPC python client for vtgate / Vitess.

---

go/cmd/vtcombo/main.go
go/sqldb/conn.go

@guoliang100 @sougou 
This will help us track the number of used ports in tests.

Add a counter for new MySQL connections

---

bootstrap.sh
doc/GettingStarted.md
travis/install_grpc.sh

Build process compatible with OS X after integrating Grpc 0.12

OS X compatibility with Grpc 0.12

---

py/vtdb/grpc_vtgate_client.py
py/vtdb/vtgatev2.py
test/keyspace_test.py
test/python_client_test.py

Few grpc python client fixes, adding more tests.

---

py/vtdb/grpc_vtgate_client.py
py/vtdb/vtgate_cursor.py
py/vtdb/vtgatev2.py
test/config.json
test/custom_sharding.py
test/python_client_test.py

Also a few fixes from previous reviews.
@dumbunny @aaijazi @enisoc

Mainly adding ExecuteShards support for python client.

---

py/vtdb/vtgate_client.py

@dumbunny @enisoc @aaijazi from the import linter.

Fixign a few minor things in this file.

---

data/test/tabletserver/exec_cases.txt
go/vt/sqlparser/analyzer.go
go/vt/tabletserver/endtoend/nocache_case_test.go
go/vt/tabletserver/planbuilder/dml.go
go/vt/tabletserver/query_executor_test.go

@aaijazi 
Need to get this in.
This reverts commit 8b627165ebfc7904f49097601ae6146ede5caa91.

Revert "tabletserver: insert...select must lock rows"

---

examples/kubernetes/guestbook/Dockerfile
examples/kubernetes/guestbook/main.py

Switch guestbook app to gRPC.

---

test/vtgatev2_test.py

Reduce vtgatev2_test flakiness.

---

go/cmd/vtgateclienttest/goclienttest/echo.go
go/cmd/vtgateclienttest/goclienttest/errors.go
go/vt/vitessdriver/driver.go
go/vt/vtgate/fakerpcvtgateconn/conn.go
go/vt/vtgate/gorpcvtgateconn/conn.go
go/vt/vtgate/grpcvtgateconn/conn.go
go/vt/vtgate/vtgateconn/vtgateconn.go
go/vt/vtgate/vtgateconntest/client.go

vtgate: Remove notInTransaction and asTransaction parameter from transaction object Execute* methods.

---

go/vt/binlog/binlogplayertest/player.go

@michael-berlin @enisoc @aaijazi same change as made internally.

Resetting panic variable in this test so it can run multiple times.

---

go/stats/rates.go
go/stats/rates_test.go

Instead of using time.Now() and sleeping for predictable times, and be at the mercy of the underlying hardware performance, use a faked clock and fixed values, and don't even sleep.
@michael-berlin @enisoc @guoliang100 @aaijazi no flakes guaranteed!

Deflaking rates unit tests.

---

go/vt/sqlannotation/sqlannotation.go

@michael-berlin please take a look. Thanks.

Adding varz for replication unfriendly statements

---

go/vt/tabletserver/tabletserver.go

Cleaned my workspace and created this new one
@sougou @erzel

log SQL and BindVariables for splitquery

---

go/vt/automation/split_clone_task.go
go/vt/automation/vertical_split_clone_task.go

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1514)

Expose the vtworker *Clone parameter "destination_pack_count" in the respective automation tasks.

---

go/vt/sqlparser/analyzer.go
go/vt/tabletserver/endtoend/nocache_case_test.go
go/vt/tabletserver/planbuilder/dml.go

Fixed insert statements as discussed here:
https://groups.google.com/forum/#!topic/vitess/z9-IJAnNPhE
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1515)

fix - null as primary key is allowed in an insert statement with auto_increment

---

go/vt/tabletserver/schema_info.go

it makes vtcombo startup somewhat faster.
@sougou
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1517)

Parallelizing the schema load. On servers with 100s of tables,

---

go/vt/binlog/binlogplayer/binlog_player.go

@alainjobart
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1520)

binlog: Log for show queries how long they took.

---

go/vt/mysqlctl/replication.go
go/vt/tabletmanager/restore.go
go/vt/tabletmanager/rpc_replication.go
go/vt/wrangler/testlib/semi_sync_test.go
test/mysql_flavor.py

Fixes https://github.com/youtube/vitess/pull/1521#issuecomment-189566221
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1529)

Fixes for new semi-sync handling.

---

go/vt/discovery/replicationlag.go

@alainjobart @sougou @enisoc
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1530)

Rename the LowReplicationLag flag var, so it can be used outside.

---

examples/local/vttablet-down.sh
examples/local/vttablet-up.sh
java/example/src/main/java/com/youtube/vitess/example/VitessClientExample.java

@michael-berlin It turns out #1531 will need more work, so I'm separating these to unblock #1534.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1535)

Test fixes

---

php/src/Vitess/ProtoUtils.php
php/tests/ProtoUtilsTest.php
php/tests/TestUtils.php

@sougou
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1536)

php: Fix zero-length edge case in RowValues().

---

go/vt/vtgate/gateway.go
go/vt/vtgate/gateway_test.go

@alainjobart
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1540)

Improve Gateway status collection performance.

---

go/vt/worker/topo_utils.go

@alainjobart
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1542)

worker: Use context with timeout for initial wait for rdonly endpoints.

---

doc/BackupAndRestore.md
doc/GettingStartedKubernetes.md
doc/vtctlReference.md
examples/kubernetes/guestbook/main.py
go/vt/vtctl/reparent.go
go/vt/vtctl/vtctl.go

Hey, I just went through the tutorial/documentation at vitess.io and fixed some of the documentation as I found old references, incomplete text, typos, etc. This is my first time submitting a pull request to this repository, so please let me know if I should do this some other way.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1525)

update vitess documentation

---

go/stats/histogram.go
go/stats/timings.go

Types that collect samples need hooks for integrating with
other similar systems. This is an already approved internal change.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1543)

add hook to histogram and timings

---

examples/kubernetes/vtgate-controller-benchmarking-template.yaml
examples/kubernetes/vtgate-controller-template.yaml
examples/local/vtgate-up.sh
test/config.json
test/custom_sharding.py
test/initial_sharding.py
test/keyspace_test.py
test/keyspace_util.py
test/local_example.sh
test/utils.py
test/vertical_split.py

@guoliang100
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1531)

Switch tests and examples to vtgate discoverygateway.

---

go/cmd/vtgate/index.go
go/cmd/vttablet/index.go

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1546)

Redirect to /debug/status instead of 404 Not Found.

---

examples/local/client.py
py/vtdb/__init__.py
py/vtdb/grpc_vtgate_client.py
py/vtdb/proto3_encoding.py
py/vtdb/vtgate_client.py
py/vtdb/vtgatev2.py
test/custom_sharding.py
test/python_client_test.py
test/vtgatev2_test.py
test/vttest_sample_test.py

@dumbunny
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1548)

Factoring out some common code in proto3 python client.

---

travis/install_grpc.sh

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1538)

OSX compatibility with grpc 0.13 integration

---

go/cmd/vtcombo/tablet_map.go
go/vt/discovery/healthcheck.go
go/vt/discovery/healthcheck_test.go
go/vt/proto/automationservice/automationservice.pb.go
go/vt/proto/binlogservice/binlogservice.pb.go
go/vt/proto/mysqlctl/mysqlctl.pb.go
go/vt/proto/queryservice/queryservice.pb.go
go/vt/proto/tabletmanagerservice/tabletmanagerservice.pb.go
go/vt/proto/vtctlservice/vtctlservice.pb.go
go/vt/proto/vtgateservice/vtgateservice.pb.go
go/vt/proto/vtworkerservice/vtworkerservice.pb.go
go/vt/tabletmanager/binlog_players_test.go
go/vt/tabletserver/grpcqueryservice/server.go
go/vt/tabletserver/grpctabletconn/conn.go
go/vt/tabletserver/tabletconn/tablet_conn.go
go/vt/tabletserver/tabletconntest/tabletconntest.go
go/vt/vtctl/query.go
go/vt/vtctl/vtctl.go
go/vt/vtctld/tablet_data.go
go/vt/vtgate/sandbox_test.go

@alainjobart @michael-berlin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1555)

Improve StreamHealth RPC by reducing goroutine usage.

---

go/vt/vtgate/scatter_conn.go
go/vt/vtgate/scatter_conn_test.go
go/vt/vtgate/vtgate_test.go

@dumbunny  Can you take a look? This code adds shuffling of the query-parts returned by splitquery.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1564)

Wrote shuffle query parts and test

---

py/vtdb/grpc_vtgate_client.py
py/vtdb/proto3_encoding.py
test/gorpc_protocols_flavor.py
test/grpc_protocols_flavor.py
test/protocols_flavor.py
test/vtgatev3_test.py

Already approved internally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1573)

Using a new method in protocols_flavor for types.

---

examples/kubernetes/guestbook/main.py
py/vtctl/grpc_vtctl_client.py
py/vtdb/grpc_update_stream.py
py/vtdb/grpc_vtgate_client.py

@alainjobart
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1576)

Fix guestbook for new bind variable syntax.

---

go/vt/tabletserver/fakecacheservice/fakecacheservice.go
go/vt/tabletserver/fakecacheservice/fakecacheservice_test.go
go/vt/tabletserver/tabletconntest/tabletconntest.go
go/vt/worker/split_diff.go
go/vt/worker/vertical_split_diff.go
go/zk/zkctl/zkctl.go

@sougou
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1584)

Don't treat arbitrary strings as format strings.

---

go/cmd/vtcombo/tablet_map.go
go/vt/logutil/proto3.go
go/vt/tabletmanager/agentrpctest/test_agent_rpc.go
go/vt/tabletmanager/faketmclient/fake_client.go
go/vt/tabletmanager/grpctmclient/client.go
go/vt/tabletmanager/tmclient/rpc_client_api.go
go/vt/vtctl/fakevtctlclient/fake_loggerevent_streamingclient.go
go/vt/vtctl/fakevtctlclient/fake_loggerevent_streamingclient_test.go
go/vt/vtctl/fakevtctlclient/fakevtctlclient.go
go/vt/vtctl/grpcvtctlclient/client.go
go/vt/vtctl/vtctl.go
go/vt/vtctl/vtctlclient/interface.go
go/vt/vtctl/vtctlclient/wrapper.go
go/vt/vtctl/vtctlclienttest/client.go
go/vt/worker/fakevtworkerclient/fakevtworkerclient.go
go/vt/worker/grpcvtworkerclient/client.go
go/vt/worker/vtworkerclient/interface.go
go/vt/worker/vtworkerclient/wrapper.go
go/vt/worker/vtworkerclienttest/client_testsuite.go
go/vt/wrangler/testlib/vtctl_pipe.go
go/vt/wrangler/testlib/wait_for_drain_test.go

The definition is in logutil, as it is shared by multiple
clients.
@enisoc @michael-berlin this takes care of 3 RPCs at once.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1582)

Replacing channels in vtctl clients with interface.

---

go/vt/worker/diff_utils.go
go/vt/worker/split_diff.go
test/resharding.py
test/utils.py

@alainjobart @michael-berlin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1588)

Fully support using a custom sharding column

---

go/stats/counters.go
go/stats/counters_test.go
go/stats/histogram.go
go/stats/timings.go

Otherwise it imposes global locking in VTGate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1587)

Remove unnecessary blocking in stats package.

---

go/cmd/vtcombo/tablet_map.go
go/sqltypes/result.go
go/vt/discovery/healthcheck_test.go
go/vt/tabletmanager/binlog_players_test.go
go/vt/tabletserver/grpctabletconn/conn.go
go/vt/tabletserver/tabletconn/tablet_conn.go
go/vt/tabletserver/tabletconntest/tabletconntest.go
go/vt/vtgate/discoverygateway.go
go/vt/vtgate/discoverygateway_test.go
go/vt/vtgate/gateway.go
go/vt/vtgate/sandbox_test.go
go/vt/vtgate/scatter_conn.go
go/vt/vtgate/shard_conn.go
go/vt/vtgate/shard_conn_flaky_test.go
go/vt/vtgate/shardgateway.go
go/vt/worker/diff_utils.go
go/vt/worker/split_clone.go
go/vt/worker/vertical_split_clone.go

Instead of using a channel, use a recv interface.
@guoliang100 @enisoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1597)

Changing RPC style for tabletconn.StreamExecute.

---

go/vt/vtgate/planbuilder/expr.go
go/vt/vtgate/planbuilder/from.go
go/vt/vtgate/planbuilder/generator.go
go/vt/vtgate/planbuilder/join.go
go/vt/vtgate/planbuilder/postprocess.go
go/vt/vtgate/planbuilder/route.go
go/vt/vtgate/planbuilder/select.go

@alainjobart 
Concerns so far:
* planBuilder interface has become big, but I think this should be it. Hopefully, nothing more will be added.
* route.go is sucking a lot of functions. Still growing. We'll see how big it gets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1596)

V3: object orientation WIP

---

go/vt/vtgate/planbuilder/expr.go
go/vt/vtgate/planbuilder/generator.go
go/vt/vtgate/planbuilder/join.go
go/vt/vtgate/planbuilder/jointab.go
go/vt/vtgate/planbuilder/route.go
go/vt/vtgate/planbuilder/select.go

@alainjobart 
generator kind of became very small, but I'm keeping it separate. I think it can accumulate some common wire-up code between various builders. It's renamed to jointab now.
I think next part will be separating out the engine. We'll see how that goes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1600)

V3: OO continued

---

go/cmd/vtgateclienttest/goclienttest/echo.go
go/cmd/vtgateclienttest/goclienttest/errors.go
go/vt/vitessdriver/driver.go
go/vt/vitessdriver/streaming_rows.go
go/vt/vitessdriver/streaming_rows_test.go
go/vt/vtgate/fakerpcvtgateconn/conn.go
go/vt/vtgate/grpcvtgateconn/conn.go
go/vt/vtgate/vtgateconn/vtgateconn.go
go/vt/vtgate/vtgateconntest/client.go

@guoliang100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1598)

Changing vtgate go client to Recv method.

---

go/vt/vtgate/vindexes/vschema.go
go/vt/vtgate/vindexes/vschema_test.go

This change also prepares us to search tables by keyspace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1606)

v3: Allow dup tables in vschema

---

go/vt/tabletserver/query_executor.go
go/vt/tabletserver/tabletserver.go

@alainjobart @sougou @guokeno0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1611)

Demote ErrFail to Info level in tabletserver

---

go/vt/vtgate/discoverygateway.go
go/vt/vtgate/shard_conn.go
go/vt/vtgate/txbuffer/tx_buffer.go
go/vt/vtgate/txbuffer/tx_buffer_test.go

@alainjobart @enisoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1612)

Return an error when tx buffer is full

---

go/cmd/vtcombo/main.go
go/cmd/vtgate/vtgate.go
go/vt/topo/test/vschema.go
go/vt/vtgate/planner.go
go/vt/vtgate/router.go
go/vt/vtgate/router_framework_test.go
go/vt/vtgate/router_select_test.go
go/vt/vtgate/vtgate.go
go/vt/vtgate/vtgate_test.go

@alainjobart 
* Plumb initialization context from main function.
* Verify GetShardNames in vschema test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1618)

v3: misc fixes

---

java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java
java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessDriver.java
java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessJDBCUrl.java
java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java
java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java
java/jdbc/src/main/java/com/flipkart/vitess/util/Constants.java
java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessDriverTest.java
java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessPreparedStatementTest.java
java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessStatementTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1632)

[Vitess JDBC] Added stream execution with connection property param and simple execution as default

---

go/vt/tabletserver/splitquery/doc.go
go/vt/tabletserver/splitquery/equal_splits_algorithm.go
go/vt/tabletserver/splitquery/full_scan_algorithm.go
go/vt/tabletserver/splitquery/split_params.go
go/vt/tabletserver/tabletserver.go
go/vt/tabletserver/tabletserver_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1633)

Making SplitQueryV2 return TabletError

---

go/vt/automation/resolver/resolver.go
go/vt/automation/vtctlclient_wrapper.go
go/vt/automation/vtworkerclient_wrapper.go
go/vt/worker/vtworkerclienttest/client_testsuite.go

Note: Changes were already LGTM'd internally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1637)

Export internal changes.

---

go/vt/discovery/healthcheck.go

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1640)

Fix healthcheck ipv6 bug

---

doc/vtctlReference.md
go/vt/vtctl/vtctl.go

@sougou
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1641)

vtctl: Fix vschema commands for new keyspace argument.

---

doc/GettingStartedKubernetes.md
doc/ShardingKubernetes.md
examples/kubernetes/create_test_table.sql
examples/kubernetes/guestbook-down.sh
examples/kubernetes/guestbook/main.py
examples/kubernetes/vschema.json

@sougou 
So much cleaner this way. :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1642)

guestbook: Update to use V3 for sharding and resharding.

---

Makefile
bootstrap.sh
vendor/vendor.json

@enisoc @alainjobart 
The gRPC library itself is already pinned by "govendor" and protects as
from breaking changes. The plugin was recently updated and broke us
again. Now this should no longer happen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1645)

bootstrap: Pin protobuf plugin which generates gRPC Go code.

---

go/vt/vttest/local_cluster.go
py/vttest/init_data_options.py
py/vttest/local_database.py
py/vttest/run_local_database.py

@alainjobart 
@dumbunny 
Please take a look.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1646)

Adding a flag to run_local_database.py to allow populating the databa with initial random data.

---

go/vt/proto/vtgate/vtgate.pb.go
go/vt/tabletserver/splitquery/equal_splits_algorithm.go
proto/vtgate.proto

@dumbunny
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1651)

Made equal_splits use the first split_column if more than one is give rather than complain

---

examples/demo/run.py

@sougou
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1653)

examples: Log port of v3 demo on stdout.

---

go/vt/tabletserver/splitquery/equal_splits_algorithm.go

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1657)

Added a workaround for b/28409793

---

go/vt/worker/fake_pool_connection_test.go
go/vt/worker/split_clone_test.go
go/vt/worker/utils_test.go
go/vt/worker/vertical_split_clone_test.go

- Moved out into own file.
- More code reuse between tests.
- Split split_clone_test.go into multiple tests to better sepearate between a test which tests the normal case and tests which test specific error situations.
Do not review this. It was already LGTM'd in https://github.com/youtube/vitess/pull/1667 and I'll merge it shortly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1670)

worker: Refactored FakePoolConnection.

---

go/vt/tabletserver/tabletconn/tablet_conn.go
go/vt/vtgate/discoverygateway_test.go
go/vt/vtgate/vtgate.go
go/vt/vtgate/vtgate_test.go

unit test is in the discovery gateway code.
@guoliang100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1675)

Adding unit test for BeginExecute{,Batch}. Removing tabletconn.Cancelled.

---

go/vt/throttler/thread_throttler.go
go/vt/throttler/thread_throttler_test.go
go/vt/throttler/throttler.go
go/vt/throttler/throttler_test.go
go/vt/worker/clone_utils.go
go/vt/worker/defaults.go
go/vt/worker/executor.go
go/vt/worker/split_clone.go
go/vt/worker/split_clone_cmd.go
go/vt/worker/split_clone_test.go
go/vt/worker/vertical_split_clone.go
go/vt/worker/vertical_split_clone_cmd.go
go/vt/worker/worker.go

@alainjobart as primary reviewer
@dumbunny as secondary reviewer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1677)

worker: Support fixed rate throttling for SplitClone and VerticalSplitClone

---

go/cmd/vtgateclienttest/services/errors.go
go/mysql/mysql.go
go/mysql/vtmysql.c
go/mysql/vtmysql.h
go/sqldb/sql_error.go
go/vt/tabletserver/query_executor_test.go
go/vt/tabletserver/tablet_error.go
go/vt/tabletserver/tablet_error_test.go
go/vt/tabletserver/tabletserver.go
go/vt/tabletserver/tabletserver_test.go
java/client/src/main/java/com/youtube/vitess/client/Proto.java
java/client/src/main/java/com/youtube/vitess/client/SQLFuture.java
java/client/src/test/java/com/youtube/vitess/client/ProtoTest.java
java/client/src/test/java/com/youtube/vitess/client/RpcClientTest.java
java/grpc-client/src/main/java/com/youtube/vitess/client/grpc/GrpcClient.java
java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessPreparedStatementTest.java

@sougou 
Fixes #1676
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1680)

java: Populate MySQL errno and SQLSTATE in SQLExceptions

---

java/jdbc/pom.xml
travis/download_mariadb.sh

Removed Shaded plugin from pom.xml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1681)

jdbc jar as thin client jar

---

go/vt/tabletmanager/init_tablet.go

@alainjobart 
I found a race with ZK when many tablets try to init at the same time.
In ZK, creating the shard consists of creating multiple paths
(the shard record itself, /action, etc.). If the second tablet to init
sees that the shard record exists, but tries to lock the shard before
the /action path exists, it will fail.
As a workaround, I've changed the shard lock to use UpdateShardFields
because the lock is not required according to our revised locking
guidelines. We only need to ensure the consistency of the shard record
with itself, and UpdateShardFields can do that. This gets around the ZK
race because it doesn't depend on any of the secondary paths existing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …

InitTablet: Don't need shard lock to add cell.

---

go/vt/tabletserver/tabletserver.go
go/vt/tabletserver/tabletserver_test.go

I was overzealous when I removed sessionID, and missed a few cases.
This should fix it.
@sougou @enisoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1691)

Fixing target handling in tabletserver.

---

go/cmd/vtcombo/main.go
go/vt/discovery/healthcheck_wait.go
go/vt/vtgate/discoverygateway.go
py/vttest/environment.py

@alainjobart @enisoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1696)

Fix discovery gateway handling, and also vtcombo.

---

go/cmd/vtctl/vtctl.go
go/vt/servenv/run.go
go/vt/vtctl/query.go
go/vt/vtctl/reparent.go
go/vt/wrangler/testlib/vtctl_pipe.go
test/utils.py

@guoliang100 I ended up leaving vtgate queries in, as they can be a good debugging tool (from vtctl command line especially).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1700)

Protecting vtctl Queries with a flag

---

doc/Concepts.md

@alainjobart 
I did an update pass over everything in this page.
* Fix some stuff that was misleading (namely replica vs rdonly)
* Update for removal of serving graph.
* Document more tablet types.
* Document keyspace graph.
* Clarify topology section.
* Sneak in "toposphere"...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1705)

Update Concepts doc.

---

go/vt/worker/split_diff_test.go
go/vt/worker/topo_utils.go
go/vt/worker/utils_test.go
go/vt/worker/vertical_split_diff_test.go
go/vt/wrangler/cleaner.go

@michael-berlin ready for review now, integrated your comments on the commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1704)

Reworking cleaner code.

---

doc/VitessReplication.md
vitess.io/_includes/left-nav-menu.html
vitess.io/user-guide/vitess-replication.md

@enisoc this is the same doc as the one that was sent for review earlier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1713)

Adding doc for replication.

---

go/vt/binlog/binlogplayer/binlog_player.go
go/vt/binlog/binlogplayer/binlog_player_test.go
go/vt/binlog/binlogplayer/vtclient.go
go/vt/tabletmanager/binlog_players.go
go/vt/tabletmanager/binlog_players_test.go
go/vt/tabletmanager/healthcheck_test.go
go/vt/throttler/thread_throttler.go
go/vt/throttler/throttler.go
go/vt/throttler/throttler_test.go
go/vt/worker/defaults.go
go/vt/worker/split_clone.go
go/vt/worker/utils_test.go
go/vt/worker/vertical_split_clone.go

@alainjobart
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1707)

binlogplayer: Enable throttler in filtered replication.

---

doc/VitessReplication.md

@alainjobart
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1723)

Document Vitess semi-sync enforcement option.

---

go/vt/automation/horizontal_resharding_task.go
go/vt/automation/horizontal_resharding_task_test.go
go/vt/automation/split_clone_task.go
go/vt/automation/split_clone_task_test.go
go/vt/automation/split_diff_task.go
go/vt/automation/vertical_split_clone_task.go
go/vt/automation/vertical_split_diff_task.go
go/vt/automation/vertical_split_task.go
go/vt/automation/vertical_split_task_test.go
go/vt/worker/defaults.go
go/vt/worker/split_clone.go
go/vt/worker/split_clone_cmd.go
go/vt/worker/split_diff.go
go/vt/worker/split_diff_cmd.go
go/vt/worker/topo_utils.go
go/vt/worker/vertical_split_clone.go
go/vt/worker/vertical_split_clone_cmd.go
go/vt/worker/vertical_split_diff.go
go/vt/worker/vertical_split_diff_cmd.go
go/vt/wrangler/keyspace.go
test/automation_horizontal_resharding.py
test/binlog.py
test/initial_sharding.py
test/merge_sharding.py
test/resharding.py
test/vertical_split.py
test/worker.py

@alainjobart
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1728)

worker: Replace "endpoints" with "tablets" in flags and variables.

---

Makefile
docker/bootstrap/README.md

Running a single target is simpler than a series of commands.
@enisoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1733)

Makefile: Add targets docker_bootstrap_test and docker_bootstrap_push.

---

data/test/schema/test_keyspace/vtgate_test.sql
data/test/schema/vschema.json
java/client/pom.xml
java/client/src/main/java/com/youtube/vitess/client/Proto.java
java/client/src/main/java/com/youtube/vitess/client/cursor/Row.java
java/client/src/test/java/com/youtube/vitess/client/BindVarTest.java
java/client/src/test/java/com/youtube/vitess/client/RpcClientTest.java
java/client/src/test/java/com/youtube/vitess/client/TestEnv.java
java/client/src/test/java/com/youtube/vitess/client/TestUtil.java
java/hadoop/pom.xml
java/hadoop/src/main/java/com/youtube/vitess/hadoop/RowWritable.java
java/hadoop/src/main/java/com/youtube/vitess/hadoop/VitessConf.java
java/hadoop/src/main/java/com/youtube/vitess/hadoop/VitessInputFormat.java
java/hadoop/src/main/java/com/youtube/vitess/hadoop/VitessRecordReader.java
java/hadoop/src/test/java/com/youtube/vitess/hadoop/MapReduceIT.java

@alainjobart 
This is based on an old test that got left behind in the conversion to
the new proto3-based Java client. I've updated it to use VSchema, which
removes the need for the test to know about keyspace IDs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1732)

java: Add back Hadoop MapReduce integration test.

---

py/vtdb/proto3_encoding.py
test/vtgatev3_test.py

@enisoc @sougou 
(will rebase before submit, only look at last commit, rest is me messing up my branches)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1738)

Keyspace in python v3 client

---

examples/demo/schema/vschema.json
go/vt/vtgate/planner.go
go/vt/vtgate/router_framework_test.go
go/vt/vtgate/vindexes/lookup_hash.go
go/vt/vtgate/vindexes/lookup_hash_test.go
go/vt/vtgate/vindexes/lookup_hash_unique_test.go
go/vt/vtgate/vindexes/vschema.go
go/vt/vtgate/vindexes/vschema_test.go
test/vtgatev3_test.py

@alainjobart 
Camel case vindex params look odd after the rest of the
tags got lowercased. This change makes them also lowercase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1735)

v3 vschema: lower case vindex params

---

go/vt/discovery/replicationlag.go
go/vt/discovery/replicationlag_test.go

@alainjobart 
It covers the case like [1s, 1s, 100m, 200m] which is relatively common.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1743)

Run replication lag filter again, if the first run removed one tablet.

---

.travis.yml
doc/GettingStarted.md
doc/Reparenting.md
doc/V3HighLevelDesign.md
doc/Vision.md
doc/VitessOverview.md
docker/bootstrap/Dockerfile.common
docker/lite/Dockerfile
docker/lite/Dockerfile.mariadb
docker/lite/Dockerfile.mysql56
docker/lite/Dockerfile.percona
examples/kubernetes/vttablet-pod-benchmarking-template.yaml
examples/local/vttablet-up.sh

@sougou 
These are no longer needed after #1742.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1744)

Clean up memcached dependencies.

---

go/cmd/vtcombo/main.go
go/cmd/vtgate/vtgate.go
go/vt/vtgate/vtgate.go
go/vt/vtgate/vtgate_test.go

@alainjobart
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1747)

Remove VTGate max-in-flight.

---

examples/kubernetes/vttablet-pod-benchmarking-template.yaml
examples/kubernetes/vttablet-pod-template.yaml
examples/local/vttablet-up.sh
go/vt/discovery/healthcheck.go
go/vt/tabletmanager/healthcheck.go
go/vt/tabletmanager/init_tablet.go
go/vt/tabletmanager/init_tablet_test.go

@enisoc would be the best reviewer, but has a lot on his plate. @michael-berlin can you please take a look?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1752)

Retiring target_tablet_type for good.

---

doc/Upgrading.md
vitess.io/_includes/left-nav-menu.html
vitess.io/user-guide/upgrading.md

Already LGTM'd by Alain.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1753)

doc: Document how to do Vitess upgrades.

---

doc/BackupAndRestore.md
doc/Reparenting.md
doc/SchemaManagement.md
doc/Sharding.md

@enisoc Can you please have a look at the changes in the BackupAndRestore.md file? I simplified the section about bootstrapping new tablets. Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1751)

doc: Couple minor fixes.

---

doc/PivotSchemaChanges.md
doc/SchemaManagement.md
doc/VitessReplication.md
vitess.io/_includes/left-nav-menu.html
vitess.io/user-guide/pivot-schema-changes.md

Already LGTM'd by @alainjobart.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1755)

doc: Tutorial how to manually carry out a pivot schema change.

---

test/environment.py
test/tablet.py

@alainjobart
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1758)

Add the option in test/environment.py for lameduck flag.

---

publish-site.sh

@enisoc @alainjobart @sougou
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1754)

publish-site.sh: Fix issues which let the script fail for me.

---

go/vt/vtgate/planner.go
go/vt/vtgate/vtgate.go
test/vtgatev3_test.py

@alainjobart
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1760)

vtgate: support for /debug/health

---

go/vt/topo/test/serving.go

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1762)

Fixing test to never call with nil.

---

examples/demo/run.py
go/vt/vttest/local_cluster.go
proto/vttest.proto
py/vttest/run_local_database.py

@enisoc @dumbunny @erzel first one to get to this wins! ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1768)

Deprecating --topology in run_local_database.py.

---

go/vt/tabletmanager/grpctmclient/client.go
go/vt/tabletmanager/grpctmserver/server_test.go

Introducing a pool of connections for high QPS access too.
@michael-berlin this will look familiar. :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1767)

Clean-up for gRPC tm client.

---

go/vt/vtctl/vtctl.go
test/reparent.py

More details in help, and sorting the intended way. With test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1769)

vtctl ShardReplicationPositions improvements.

---

go/vt/schemamanager/tablet_executor_test.go

@alainjobart
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1771)

schemamanager: Split two unit tests because they test different things.

---

test/schema.py
test/tablet.py
test/tabletmanager.py
test/utils.py

Otherwise it spams the vtctld logs.
@enisoc @michael-berlin first one to look!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1774)

Only enable schema watcher when needed.

---

go/vt/throttler/throttler.go
go/vt/throttler/throttler_test.go

@alainjobart
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1781)

throttler: Fix that the rate could not be set to zero (no progres).

---

java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessJDBCUrl.java
java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java
java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessJDBCUrlTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1780)

[JDBC Driver] Adding keyspace name while creating connection

---

go/vt/vtgate/vtgateconn/vtgateconn.go

I'm hardcoding the constant instead. This is consistant with other *_protocol flags.
@alainjobart
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1791)

vtgate: Remove constant which was only used in one place.

---

go/vt/vtgate/vindexes/unicodeloosemd5.go

@michael-berlin #1787 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1793)

vindexes: fix data race bug with collator

---

test/schema.py

@ashudeep-sharma
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1795)

test: schema.py: Remove implemented TODO.

---

doc/LaunchingVitess.md
go/vt/vtgate/router.go
go/vt/vtgate/vtgate.go
test/keyspace_util.py
test/vtgatev3_test.py

@sougou @erzel
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1789)

Fixing SplitQuery API for v3.

---

doc/LaunchingVitess.md

@alainjobart
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1800)

Launch doc updates

---

doc/LaunchingVitess.md

@sougou 
The lists must have an empty line before them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1805)

Fix lists on the LaunchingVitess page.

---

go/vt/tabletserver/connpool.go

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1807)

Fix minor typo.

---

go/vt/proto/automation/automation.pb.go
go/vt/proto/automationservice/automationservice.pb.go
go/vt/proto/binlogdata/binlogdata.pb.go
go/vt/proto/binlogservice/binlogservice.pb.go
go/vt/proto/logutil/logutil.pb.go
go/vt/proto/mysqlctl/mysqlctl.pb.go
go/vt/proto/query/query.pb.go
go/vt/proto/queryservice/queryservice.pb.go
go/vt/proto/replicationdata/replicationdata.pb.go
go/vt/proto/tableacl/tableacl.pb.go
go/vt/proto/tabletmanagerdata/tabletmanagerdata.pb.go
go/vt/proto/tabletmanagerservice/tabletmanagerservice.pb.go
go/vt/proto/throttlerdata/throttlerdata.pb.go
go/vt/proto/throttlerservice/throttlerservice.pb.go
go/vt/proto/topodata/topodata.pb.go
go/vt/proto/vschema/vschema.pb.go
go/vt/proto/vtctldata/vtctldata.pb.go
go/vt/proto/vtctlservice/vtctlservice.pb.go
go/vt/proto/vtgate/vtgate.pb.go
go/vt/proto/vtgateservice/vtgateservice.pb.go
go/vt/proto/vtrpc/vtrpc.pb.go
go/vt/proto/vttest/vttest.pb.go
go/vt/proto/vtworkerdata/vtworkerdata.pb.go
go/vt/proto/vtworkerservice/vtworkerservice.pb.go
vendor/vendor.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1812)

Update vendored grpc-go and regenerate protos.

---

doc/GettingStarted.md

Clarified directions on how to clone the github repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1813)

Updated directions in the getting started section of the doc

---

travis/download_mariadb.sh

---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1820)

Bump travis download_mariadb script from 10.0.25 to 10.0.26

---

Makefile
test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1818)

test.go: Run multiple flavors, and optionally run in parallel.

---

vitess.io/package.json

The invalid JSON tripped up the initial import of codeclimate.com.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1822)

vitess.io: Fix invalid JSON in package.json.

---

test/base_sharding.py
test/utils.py

@enisoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1821)

test: Unflake check if throttlers are registered.

---

go/vt/worker/row_aggregator.go
go/vt/worker/row_differ.go
go/vt/worker/split_clone.go
go/vt/worker/split_clone_cmd.go
go/vt/worker/split_clone_test.go
test/resharding.py

@enisoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1837)

worker: SplitClone: Do not use the IN expression for multi-row DELETEs.

---

go/vt/worker/diff_utils.go
go/vt/worker/row_aggregator.go
go/vt/worker/row_differ.go
go/vt/worker/split_clone.go
go/vt/worker/split_clone_test.go
go/vt/worker/vertical_split_clone.go
test/base_sharding.py
test/initial_sharding.py
test/legacy_resharding.py
test/merge_sharding.py
test/resharding.py

@enisoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1836)

worker: Fix problem when primary key columns are not the first columns in the table definition.

---

.travis.yml
test.go
test/config.json

@enisoc 
Added some logic to test.go to allow the user to exclude specifically tests by tag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1838)

Exclude webdriver tests from Travis PRs

---

.travis.yml
test.go

@enisoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1840)

Unbreak travis config

---

go/vt/worker/restartable_result_reader.go
go/vt/worker/restartable_result_reader_test.go

@alainjobart
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1847)

worker: Fix full table scans in restarted streaming queries.

---

go/vt/binlog/binlogplayertest/player.go
go/vt/tabletmanager/agentrpctest/test_agent_rpc.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1849)

Adding unit test for utf8 characters.

---

test/utils.py
test/vtctld_web_test.py
web/vtctld/keyspaces.html
web/vtctld/keyspaces.js

@thompsonja
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1852)

Add vtctld tests

---

php/src/Vitess/Proto/Automationservice/AutomationClient.php
php/src/Vitess/Proto/Binlogservice/UpdateStreamClient.php
php/src/Vitess/Proto/Mysqlctl/MysqlCtlClient.php
php/src/Vitess/Proto/Queryservice/QueryClient.php
php/src/Vitess/Proto/Tabletmanagerservice/TabletManagerClient.php
php/src/Vitess/Proto/Throttlerservice/ThrottlerClient.php
php/src/Vitess/Proto/Vtctlservice/VtctlClient.php
php/src/Vitess/Proto/Vtgateservice/VitessClient.php
php/src/Vitess/Proto/Vtworkerservice/VtworkerClient.php

@michael-berlin @alainjobart 
Apparently these files were not generated for quite some time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1854)

Regenerate php protobuf files.

---

go/vt/automation/split_clone_task.go
go/vt/automation/split_clone_task_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1856)

Exporting internal changes back to open-source. (Added --offline and --online flags to SplitClone automation task.)

---

docker/bootstrap/Dockerfile.common
test/vtctld_web_test.py

@thompsonja
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1859)

Fix webdriver test in Docker mode

---

go/vt/worker/row_differ.go
test/resharding.py

If a row already exists on the destination with a different keyspace_id on a different destination shard, we cannot use UPDATE. Instead, we must DELETE the old row from the old destination shard and INSERT the new row to the new destination shard.
@alainjobart @enisoc @apmichaud
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1865)

worker: SplitClone: Handle keyspace_id changes properly.

---

go/vt/binlog/binlogplayer/binlog_player.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1866)

Fix panic in BinlogPlayer.

---

go/vt/sqlannotation/sqlannotation.go
go/vt/sqlannotation/sqlannotation_test.go
go/vt/vtgate/resolver.go
go/vt/vtgate/vtgate.go

NOTE: This is an automated export. Changes were already LGTM'd
internally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1868)

Refactor IsDML and ignore leading whitespace

---

doc/LaunchingVitess.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1881)

Updating multi-cell part of the doc.

---

composer.json
docker/bootstrap/Dockerfile.common

As discussed in #1879, I made this pull request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1880)

replaced dattoo/protobuf-php to stanley-cheung/protobuf-php

---

go/vt/etcdtopo/config.go
go/vt/etcdtopo/election.go
go/vt/etcdtopo/lock.go
go/vt/topo/helpers/tee.go
go/vt/topo/server.go
go/vt/topo/test/election.go
go/vt/topo/test/faketopo/faketopo.go
go/vt/topo/test/testing.go
go/vt/zktopo/election.go
go/zk/zkconn.go

Along with unit test.
Implementing it for zookeeper and etcd.
@michael-berlin @pivanof will work on internal implementation as you guys review this, so if you don't like the interface, please get back to me asap... thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1886)

Adding master election interface to topo.Impl.

---

doc/ReplicationStreamTiming.md

Copy of the internal doc, with all the internal stuff cleaned up. ;)
@sougou
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1889)

Adding ReplicationStreamTiming.md doc.

---

go/vt/discovery/healthcheck.go
go/vt/vtgate/gatewaytest/grpc_discovery_test.go

@michael-berlin two small fixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1892)

Healthcheck

---

misc/git/hooks/tslint

@enisoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1899)

misc: Add precommit hook for tslint.

---

go/vt/logutil/console_logger_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1902)

Update console_logger_test.go.  Already approved internally

---

go/vt/tableacl/tableacl.go
go/vt/tableacl/tableacl_test.go
vendor/vendor.json

@mattharden will merge this once travis passes, as it was approved internally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1903)

Export internal changes

---

go/zk/config.go

5s seems to be a bit low, especially with servers under load.
@michael-berlin let's see how this works... if the timeouts persist, then we have another issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1905)

Increasing default ZK session timeout to 30s.

---

doc/vtctlReference.md
go/vt/discovery/fake_healthcheck.go
go/vt/discovery/healthcheck.go
go/vt/discovery/healthcheck_test.go
go/vt/discovery/replicationlag.go
go/vt/discovery/replicationlag_test.go
go/vt/discovery/tablet_stats_cache.go
go/vt/discovery/tablet_stats_cache_test.go
go/vt/discovery/utils.go
go/vt/vtctl/vtctl.go
go/vt/vtctld/api_test.go
go/vt/vtgate/gateway/discoverygateway.go
go/vt/vtgate/gateway/discoverygateway_test.go
go/vt/vtgate/gateway/gateway.go
go/vt/vtgate/gateway/l2vtgategateway.go
go/vt/vtgate/gatewaytest/grpc_discovery_test.go
go/vt/vtgate/l2vtgate/l2vtgate.go
go/vt/vtgate/scatter_conn.go
go/vt/vtgate/vtgate_test.go
go/vt/wrangler/keyspace.go
go/vt/wrangler/testlib/wait_for_drain_test.go

@michael-berlin I think it's all of it, let me know if I missed some fixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1910)

Tightening a bunch of lose ends in gateway.

---

go/vt/throttler/throttler.go
go/vt/throttler/throttler_test.go

@alainjobart 
I was trying out a new Go linter tool on the throttler package and it complained about this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1912)

throttler: Move testing only code to *_test.go file.

---

go/vt/mysqlctl/gcsbackupstorage/gcs.go
vendor/vendor.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1915)

Switching to new version of google API.

---

.gitignore

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1916)

New gitignore to ignore bower components

---

go/vt/vtctld/api.go
go/vt/vtctld/api_test.go
go/vt/vtctld/realtime_status.go
go/vt/vtctld/realtime_status_test.go
go/vt/vtctld/tablet_stats_cache.go
go/vt/vtctld/tablet_stats_cache_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1917)

vtctld: support per-keyspace data generation in realtime stats backend 

---

go/cmd/automation_client/automation_client.go
vendor/vendor.json

And new option in gRPC options to turn of FailFast.
The automation client can wait until context deadline.
@enisoc

New version of grpc go client.

---

go/vt/vtctld/tablet_stats_cache.go

@pivanof @michael-berlin 
fixed golint error in tablet_stats_cache.go

fixed golint error

---

go/vt/vttime/clock.go
go/vt/vttime/doc.go
go/vt/vttime/interval.go
go/vt/vttime/interval_test.go
go/vt/vttime/test_clock.go
go/vt/vttime/time_clock.go
go/vt/vttime/time_clock_test.go

We're going to add a time Interval to each statement in replication.
@pivanof

Adding a vttime library. To be used soon.

---

.travis.yml
Makefile
go/race/norace.go
go/race/race.go
go/vt/logutil/logger_test.go
go/vt/worker/split_clone.go
go/vt/worker/split_clone_test.go
go/vt/worker/tablet_tracker.go
go/vt/worker/tablet_tracker_test.go
tools/unit_test_race.sh
tools/unit_test_runner.sh

@enisoc 
The Go data race test was not executed on Travis for several months.
This lead to the introduction of data races which I fixed in this PR as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1919)

Fix Travis Go data race test.

---

web/vtctld2/package.json
web/vtctld2/src/app/api/keyspace.service.ts
web/vtctld2/src/app/app.module.ts
web/vtctld2/src/app/app.routes.ts
web/vtctld2/src/main.ts

Changed to importing modules for bootstrapping. @enisoc

vtctld2: Update Angular 2 to RC5

---

go/vt/vtctld/realtime_status_test.go
go/vt/vtctld/tablet_stats_cache.go

vtctld - Fixed data race error in tablet_stats_cache

---

go/vt/worker/chunk.go
go/vt/worker/clone_utils.go
go/vt/worker/diff_utils.go
go/vt/worker/legacy_split_clone.go
go/vt/worker/legacy_split_clone_test.go
go/vt/worker/restartable_result_reader.go
go/vt/worker/restartable_result_reader_test.go
go/vt/worker/row_aggregator.go
go/vt/worker/split_clone.go
go/vt/worker/split_clone_test.go
go/vt/worker/split_diff_test.go
go/vt/worker/utils_test.go
go/vt/worker/vertical_split_clone.go
go/vt/worker/vertical_split_clone_test.go
go/vt/worker/vertical_split_diff_test.go

@enisoc 
Fixes https://github.com/youtube/vitess/issues/1939

worker: Escape all identifiers.

---

web/vtctld2/src/app/app.component.html
web/vtctld2/src/app/dashboard/dashboard.component.html
web/vtctld2/src/app/shared/add-button.component.css
web/vtctld2/src/app/shared/add-button.component.html
web/vtctld2/src/app/topo/topo-browser.component.html
web/vtctld2/src/main.css

vtctld2: Fix scrolling on dashboard.

---

go/vt/automation/split_clone_task.go
go/vt/automation/split_clone_task_test.go
go/vt/automation/vertical_split_clone_task.go
go/vt/automation/vertical_split_clone_task_test.go

automation: Updated parameters for SplitClone and VerticalSplitClone tasks.

---

go/vt/vtctld/api.go
go/vt/vtctld/api_test.go
go/vt/vtctld/realtime_status_test.go
go/vt/vtctld/tablet_stats_cache.go
go/vt/vtctld/tablet_stats_cache_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1946)

Added new API call for one tablet's health

---

web/vtctld2/src/app/api/tablet-status.service.ts
web/vtctld2/src/app/status/heatmap.component.html
web/vtctld2/src/app/status/heatmap.component.ts
web/vtctld2/src/app/status/status.component.html
web/vtctld2/src/app/status/status.component.ts

@thompsonja @michael-berlin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/1945)

Heatmap populates with values from service

---

go/vt/worker/chunk.go
go/vt/worker/defaults.go
go/vt/worker/legacy_split_clone.go
go/vt/worker/legacy_split_clone_cmd.go
go/vt/worker/legacy_split_clone_test.go
go/vt/worker/restartable_result_reader_test.go
go/vt/worker/split_clone.go
go/vt/worker/split_clone_cmd.go
go/vt/worker/split_clone_test.go
go/vt/worker/vertical_split_clone_cmd.go
go/vt/worker/vertical_split_clone_test.go
test/binlog.py
test/initial_sharding.py
test/legacy_resharding.py
test/merge_sharding.py
test/resharding.py
test/vertical_split.py

worker: *Clone: Add --chunk_count and --min_rows_per_chunk parameters.

---

go/vt/automation/split_clone_task.go
go/vt/automation/split_clone_task_test.go
go/vt/automation/vertical_split_clone_task.go
go/vt/automation/vertical_split_clone_task_test.go

automation: Expose --max_tps for (Vertical)SplitClone tasks.

---

go/vt/wrangler/schema.go

@alainjobart 
I'm addressing feedback here.

vtctl: CopySchemaShard: Clarify error message when the table creation fails.

---

go/vt/worker/split_clone_cmd.go
go/vt/worker/vertical_split_clone_cmd.go

vtworker: Fix default for --min_rows_per_chunk flag.

---

go/vt/automation/split_clone_task.go
go/vt/automation/split_clone_task_test.go
go/vt/automation/vertical_split_clone_task.go
go/vt/automation/vertical_split_clone_task_test.go
go/vt/worker/defaults.go
go/vt/worker/split_clone.go
go/vt/worker/split_clone_cmd.go
go/vt/worker/vertical_split_clone_cmd.go

If turned on, it will enable the adaptive throttler which throttles the write rate (queries/second) based on the replication lag of all replicas in the same cell.
@alainjobart

worker: *Clone: Add new flag --max_replication_lag.

---

web/vtctld2/src/app/status/status.component.html

Replaced paper dropdowns with primeNg dropdowns

---

web/vtctld2/src/app/app.module.ts

vtctld2: Fix @angular2-material import paths.

---

go/vt/throttler/replication_lag_cache.go
go/vt/throttler/replication_lag_cache_test.go

Fix another one off error in the same file.
Added tests to increase the coverage to 100%.

throttler: replicationLagCache: Fix panic due to a one off error.

---

go/cmd/zk/zkcmd.go
go/vt/tabletserver/customrule/zkcustomrule/zkcustomrule_test.go
go/vt/topo/helpers/copy_test.go
go/vt/topo/helpers/tee_topo_test.go
go/vt/zktopo/convert.go
go/vt/zktopo/election.go
go/vt/zktopo/explorer.go
go/vt/zktopo/file.go
go/vt/zktopo/keyspace.go
go/vt/zktopo/lock.go
go/vt/zktopo/replication_graph.go
go/vt/zktopo/server.go
go/vt/zktopo/serving_graph.go
go/vt/zktopo/shard.go
go/vt/zktopo/tablet.go
go/vt/zktopo/vschema.go
go/vt/zktopo/watch.go
go/vt/zktopo/zktestserver/testserver.go
go/vt/zktopo/zktestserver/zktopo_test.go
go/zk/fakezk/fakezk.go
go/zk/fakezk/fakezk_test.go
go/zk/metaconn.go
go/zk/zkconn.go
go/zk/zkutil.go
go/zk/zkutil_test.go

(based on my other branch that was already approved and will be merged soon).
@enisoc @michael-berlin whoever gets there first.

Switching zk lowlevel API from string to []byte.

---

travis/download_mariadb.sh

I'll double check that this fixes the travis issue.

Bump Travis MariaDB to 10.0.27

---

bootstrap.sh
go/cmd/zkctl/zkctl.go
go/stats/promstats/collector.go
go/timer/timer_flaky_test.go
go/vt/mysqlctl/fileutil.go
go/vt/mysqlctl/replication.go
go/vt/tableacl/tableacl_test.go
go/vt/tableacl/testlib/testlib.go
go/vt/tabletmanager/agentrpctest/test_agent_rpc.go
go/vt/tabletserver/endtoend/framework/testcase.go
go/vt/tabletserver/query_engine.go
go/vt/tabletserver/tabletconntest/fakequeryservice.go
go/vt/tabletserver/tabletconntest/tabletconntest.go
go/vt/tabletserver/testutils_test.go
go/vt/tabletserver/tx_pool.go
go/vt/throttler/record.go
go/vt/topo/memorytopo/memorytopo.go
go/vt/topo/test/election.go
go/vt/vtctld/tablet_data_test.go
go/vt/vtgate/gateway/discoverygateway.go
go/vt/vtgate/gateway/l2vtgategateway.go
go/vt/vtgate/vtgate_test.go
go/vt/vtgate/vtgateconntest/client.go
go/vt/worker/defaults.go
go/vt/worker/split_clone.go
go/zk/config.go
go/zk/zkutil.go
misc/git/hooks/unused

It is from this repository: https://github.com/dominikh/go-unused
As part of this change:
- adding download of the tool to bootstrap.sh.
- re-enabling a few tests that were disabled.
- removing a bunch of unused code.

Adding 'unused' go code hook.

---

go/vt/topo/memorytopo/memorytopo.go
misc/git/hooks/unused

Beautifying the go 'unused' script a bit.

---

examples/local/vtctld-up.sh
go/cmd/vtcombo/main.go
go/vt/vtctld/api_test.go
go/vt/vtctld/tablet_stats_cache.go
test/config.json
test/vtctld2_web_status_test.py
web/vtctld2/src/app/api/topology-info.service.ts
web/vtctld2/src/app/status/heatmap.component.html
web/vtctld2/src/app/status/status.component.html
web/vtctld2/src/app/status/status.component.ts

@thompsonja
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/2018)

Web webdriver tests

---

go/vt/vterrors/vterrors.go

@alainjobart Can you please take a look?
Thanks.

Made vterrors.WithSuffix and vterrors.WithPrefix preserve the error code if the input error implemented the VtError interface.

---

go/vt/vtctld/tablet_stats_cache.go
web/vtctld2/src/app/status/heatmap.component.html
web/vtctld2/src/app/status/heatmap.component.ts
web/vtctld2/src/app/status/status.component.css
web/vtctld2/src/app/status/status.component.html
web/vtctld2/src/app/status/status.component.ts
web/vtctld2/src/app/status/tablet-popup.component.html
web/vtctld2/src/app/status/tablet-popup.component.ts

Same commits as in https://github.com/youtube/vitess/pull/2021 but merge conflicts are fixed.

vtctld: Misc Realtime Status fixes.

---

go/vt/key/key.go
go/vt/key/key_test.go

NOTE: This change was already LGTM'd internally and does not require a second approval.

key: Add helper function to enumerate equal-width shards.

---

go/vt/throttler/max_replication_lag_module.go

I recommend to review each commit separately.

throttler: Various small fixes.

---

bootstrap.sh

sed command modification ... I hope thiw won't break anything :)

bootstrap.sh modification - compatibility with mysql 5.7 under osx 

---

go/vt/tabletserver/tx_prep_pool.go
go/vt/tabletserver/tx_prep_pool_test.go

Infrastructural component for managing prepared connections.

2pc: TxPreparedPool

---

go/vt/logz/logz_utils.go
go/vt/throttler/max_replication_lag_module.go
go/vt/throttler/max_replication_lag_module_test.go
go/vt/throttler/memory.go
go/vt/throttler/throttlerlogz.go
go/vt/throttler/throttlerlogz_test.go
go/vt/worker/split_clone.go

+ various other fixes.
I recommend to review changes per commit.

throttler: Generalize "replica under test" concept.

---

go/vt/tabletserver/query_executor.go
go/vt/tabletserver/query_executor_test.go
go/vt/tabletserver/tablet_error.go
go/vt/tabletserver/tabletserver.go
go/vt/tabletserver/tabletserver_test.go
go/vt/tabletserver/tx_pool.go
go/vt/tabletserver/tx_pool_test.go
go/vt/tabletserver/tx_prep_pool.go
go/vt/tabletserver/tx_prep_pool_test.go

* Remove panics from TxPool, because we need finer control
on error handling.
* TxPool level Prepare functionality. A higher layer will be
added later.

2pc: Prepare WIP

---

py/vtdb/grpc_vtgate_client.py
py/vtdb/proto3_encoding.py
py/vtdb/vtgate_client.py
test/cache_invalidation.py
test/config.json
test/update_stream.py

And supporting features in the python client.

Adding cache invalidation test.

---

go/vt/tabletmanager/rpc_external_reparent.go

And increasing a timeout value. We've seen a failure in new master
talking to old master (that has no impact on serving, but the old master
was left in a weird state). So adding more time and logging.
(internal bug is b/31187004 )

Adding more logging in external reparent.

---

go/vt/vtgate/vtgate.go

Start counting them in a stats var instead

Stop logging every context timeout in vtgate

---

go/cmd/topo2topo/topo2topo.go
go/vt/etcdtopo/keyspace.go
go/vt/topo/helpers/copy.go
go/vt/topo/helpers/copy_test.go
go/vt/topo/helpers/tee.go
go/vt/topo/helpers/tee_test.go
go/vt/topo/keyspace.go
go/vt/topo/server.go
go/vt/topo/test/faketopo/faketopo.go
go/vt/topo/test/keyspace.go
go/vt/topo/test/shard.go
go/vt/vtctl/vtctl.go
go/vt/wrangler/rebuild.go
go/vt/zktopo/keyspace.go
test/reparent.py

It would wipe out a production install, not a good thing for a repair
script.

Removing dangerous repair code.

---

test/cache_invalidation.py

We used to close the connection and hope it would interrupt the
streaming RPC. Some RPC libraries don't interrupt on-going connections,
but instead wait for them to finish. So now we first stop the streaming
connection (by setting a flag, and forcing an event), and then close the
connection.

Fixing cache test invalidator shutdown.

---

go/vt/binlog/eventtoken/compare.go
go/vt/binlog/eventtoken/compare_test.go
go/vt/tabletserver/tabletserver.go
py/vtdb/event_token.py
test/cache_invalidation.py

In go, adding both MariaDB and MySQL 5.6.
In python, just adding MariaDB for now.

Implementing more GTID comparison for event token.

---

go/vt/logutil/logger.go
go/vt/topo/replication.go
go/vt/topo/topotests/replication_test.go

Adding unit tests for FixShardReplication too.

Also removing bad tablets in FixShardReplication.

---

go/vt/worker/split_clone.go

worker: Fix invalid format string.

---

go/vt/workflow/websocket.go
test/utils.py

Fixing a couple workflow minor things.

---

data/test/vtgate/select_cases.txt
data/test/vtgate/unsupported_cases.txt
go/vt/vtgate/planbuilder/route.go

This Pull Request tracks the issue https://github.com/youtube/vitess/issues/2109
@sougou : PTAL

Supporting ShardKey = xyz in parenthesis : vitess issue 2109

---

data/test/vtgate/select_cases.txt
go/vt/vtgate/planbuilder/route.go
go/vt/vtgate/planbuilder/symtab.go

This Pull Request tracks the changes for issue: https://github.com/youtube/vitess/issues/2110
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/youtube/vitess/2121)

Adding Support for Column Aliasing in Select Queries. Issue 2110

---

go/vt/tabletmanager/action_agent.go
go/vt/tabletmanager/init_tablet.go
go/vt/tabletmanager/restore.go
go/vt/tabletmanager/rpc_external_reparent.go
go/vt/tabletmanager/rpc_replication.go
go/vt/tabletmanager/state_change.go
go/vt/topo/replication.go
go/vt/topo/tablet.go
go/vt/topo/topotests/replication_test.go
go/vt/topo/topotests/tablet.go

Fixes two somewhat related init bugs in TabletManager.

Tabletmanager fixes.

---

travis/install_grpc.sh

Fix for OSX Sierra build of Protobuf bundled with Grpc

---

go/vt/discovery/healthcheck.go
go/vt/discovery/healthcheck_test.go

When a new tablet is added via AddTablet() HealthCheck currently will notify
listener about the tablet only when the connection to the tablet is established
successfully and when first health message is received. But the tablet can be
unavailable for a long time, and all this time the listener will not be aware of
the tablet existence at all. This may hinder a proper usage of things like
TabletStatsCache. To fix this I'm changing HealthCheck to send initial
notification with Serving == false immediately after AddTablet(), and only after
that wait for the first health message from the tablet.
Also the current implementation of RemoveTablet() just cancels context in the
healthCheckConn object which causes checkConn() function to return immediately.
But that means that listener may not …

Fix HealthCheck notifications about Up/Down tablets.

---

go/vt/mysqlctl/backup.go

If there are no backups at all, we assume the shard is being initialized
and allow tablets to start up empty without restoring anything.
If any backups are found, but none can be read successfully either
because they are incomplete or because of transient network errors,
we should not start up empty. The existence of even a partial backup
implies that the shard has already begun accepting data, so it's better
to fail until a complete backup is accessible.

restore: Don't start up empty if backups exist.

---

go/vt/tabletserver/sandboxconn/sandboxconn.go
go/vt/tabletserver/tablet_error.go
go/vt/tabletserver/tablet_error_test.go
go/vt/vtgate/scatter_conn.go
go/vt/vtgate/vtgate.go
go/vt/vtgate/vtgate_test.go

Better error handling in vtgate. No more string parsing, use canonical codes more.
Also adding a few tests to make sure error propagation through vtgate preserves canonical error codes.

Vtgate errors.

---

test/vtctld_web_test.py

Not quite sure why this behavior has changed.

Fix command check in webdriver test.

---

bootstrap.sh

Update chromedriver version in bootstrap (2.20 -> 2.24)

---

test/vtctld_web_test.py

For some reason I merged my previous PR into another branch instead of master :|

Actually fix webdriver test command check.

---

go/cmd/l2vtgate/main.go
go/vt/vtgate/gatewaytest/grpc_discovery_test.go
go/vt/vtgate/l2vtgate/l2vtgate.go
test/vtgatev2_test.py

Same stats that vtgate exposes. So it's easier for monitoring. Also
adding end-to-end tests for them.

Adding stats to l2vtgate.

---

go/cmd/vtcombo/tablet_map.go
go/vt/discovery/healthcheck.go
go/vt/discovery/healthcheck_test.go
go/vt/tabletmanager/binlog_players_test.go
go/vt/tabletserver/grpctabletconn/conn.go
go/vt/tabletserver/sandboxconn/sandboxconn.go
go/vt/tabletserver/tabletconn/tablet_conn.go
go/vt/tabletserver/tabletconntest/tabletconntest.go
go/vt/vtctl/query.go
go/vt/vtctld/tablet_data.go
go/vt/vtgate/gateway/discoverygateway.go
go/vt/vtgate/gateway/discoverygateway_test.go
go/vt/vtgate/gateway/gateway.go
go/vt/vtgate/gateway/l2vtgategateway.go
go/vt/vtgate/gateway/shard_error.go
go/vt/vtgate/gatewaytest/suite.go
go/vt/vtgate/l2vtgate/l2vtgate.go
go/vt/vtgate/masterbuffer/masterbuffer.go
go/vt/vtgate/masterbuffer/masterbuffer_test.go
go/vt/vtgate/resolver.go
go/vt/vtgate/scatter_conn.go
go/vt/worker/diff_utils.go
go/vt/worker/legacy_split_clone.go
go/vt/worker/restartable_result_reader.go
go/vt/worker/split_clone.go
go/vt/worker/split_diff.go
go/vt/worker/vertical_split_diff.go

This is the first pass. More improvements may be possible.

consolidate TabletConn and Gateway interfaces

---

go/vt/tabletserver/sandboxconn/sandboxconn.go
go/vt/vtgate/resolver.go
go/vt/vtgate/resolver_test.go
go/vt/vtgate/router_framework_test.go
go/vt/vtgate/router_select_test.go
go/vt/vtgate/scatter_conn.go
go/vt/vtgate/scatter_conn_test.go
go/vt/vtgate/tx_conn.go
go/vt/vtgate/tx_conn_test.go
go/vt/vtgate/vtgate.go

This is the core VTGate functionality for the commit flow. Some
more wire-up will be done after the rollback flow is implemented.

2pc: VTGate coordinator functionality

---

java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java
java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessDatabaseMetaData.java
java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java
java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java
java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessDatabaseMetadataTest.java

Implemented getUserName method and fetchSize methods

---

go/vt/tabletserver/endtoend/transaction_test.go
go/vt/tabletserver/sandboxconn/sandboxconn.go
go/vt/tabletserver/tabletserver_test.go
go/vt/tabletserver/twopc.go
go/vt/tabletserver/tx_executor_test.go
go/vt/vtgate/resolver_test.go
go/vt/vtgate/router_framework_test.go
go/vt/vtgate/router_select_test.go
go/vt/vtgate/scatter_conn.go
go/vt/vtgate/scatter_conn_test.go
go/vt/vtgate/tx_conn.go
go/vt/vtgate/tx_conn_test.go

Also cleaned up some boiler-plate code in tests.

2pc: Resume Transaction functionality

---

go/vt/mysqlctl/mysql_daemon.go
go/vt/mysqlctl/replication.go
go/vt/tabletmanager/restore.go
go/vt/tabletmanager/rpc_actions.go
go/vt/tabletmanager/rpc_replication.go
go/vt/tabletmanager/state_change.go
test/backup.py
test/reparent.py
test/tablet.py
test/tabletmanager.py

Should fix:
https://github.com/youtube/vitess/issues/2195

Enabling / Disabling semi-sync on ChangeType.

---

travis/download_mariadb.sh

The old version is not available any more.

Upgrading MariaDB version.

---

go/cmd/vtgateclienttest/goclienttest/echo.go
go/vt/tabletserver/querytypes/proto3.go
go/vt/tabletserver/querytypes/proto3_test.go
go/vt/tabletserver/tabletconntest/fakequeryservice.go
go/vt/vitessdriver/fakeserver_test.go
go/vt/vtgate/topo_utils_test.go
go/vt/vtgate/vtgateconntest/client.go
java/client/src/test/java/com/youtube/vitess/client/RpcClientTest.java
php/tests/VTGateConnTest.php
py/vtdb/vtgate_client_testsuite.py

This reverts commit 38749981eade0095204f10112c8134c8cebc2648, reversing
changes made to 189b5b455da4a08d62f9045275632410e7b6776c.

Revert "Merge pull request #2191 from alainjobart/bind"

---

go/vt/vtgate/tx_conn.go
go/vt/workflow/long_polling.go

This Pull Request contains fix for #2227

Fix for build failure on OS X, vitess issue 2227

---

go/vt/tabletmanager/action_agent.go
go/vt/tabletmanager/init_tablet.go

When vttablet starts up, it may try to update the global topology
records. Now we will retry these changes up until the original context
deadline. That way if we're throttled for instance, it will eventually
go through.

Retry global topo changes upon failure.

---

go/vt/schemamanager/schemaswap/schema_swap.go

This change adds the detailed indication of everything schema swap is doing. I
consider this UI (in particular the set of nodes) is final, though interaction
between them will change a little when I add good error processing.

Add detailed UI to schema swap workflow.

---

bootstrap.sh
go/cmd/vtcombo/main.go
test/environment.py
test/vtctld_web_test.py

- Update chromedriver in bootstrap from 2.24 to 2.25.
- Update vtcombo to guarantee zk config file is created.
- Move webdriver creation to environment.py.
@alainjobart

Webdriver test updates.

---

go/vt/schemamanager/schemaswap/schema_swap.go

When Vitess-driven reparents are disabled in vtctld then the schema swap will
execute 'reparent_away' hook on the master tablet which will have to do the
reparenting.

Add support for non-Vitess driven reparents to schema swap.

---

docs/resources/roadmap.html
vitess.io/resources/roadmap.md

Adding vertical split to existing keyspace to the roadmap.

Minor doc change.

---

go/vt/tabletserver/logstats.go
go/vt/tabletserver/logstats_test.go
go/vt/tabletserver/query_executor_test.go
go/vt/tabletserver/querylogz_test.go
go/vt/tabletserver/schema_info_test.go
go/vt/tabletserver/sysloglogger/sysloglogger_test.go
go/vt/tabletserver/tabletserver.go
go/vt/tabletserver/tabletserver_test.go
go/vt/tabletserver/tx_executor_test.go

LogStats: exporting context, adding target.
