go/mysql/conn.go, go/mysql/server.go, go/vt/vttablet/tabletmanager/rpc_lock_tables.go, go/vt/vttablet/tabletmanager/rpc_query.go, go/vt/vttablet/tabletmanager/rpc_query_test.go, go/vt/wrangler/testlib/apply_schema_flaky_test.go, go/vt/wrangler/testlib/copy_schema_shard_test.go
In order to allow schema names that need to be escaped, we must backtick db names before sending them to MySQL.
Fixes #6545
=> Make sure to backtick schema names properly

go/test/endtoend/vtgate/setstatement/sysvar_test.go, go/vt/vtgate/legacy_scatter_conn_test.go, go/vt/vtgate/safe_session.go, go/vt/vtgate/scatter_conn.go, go/vt/vtgate/scatter_conn_test.go, go/vt/vtgate/tx_conn_test.go, go/vt/vttablet/sandboxconn/sandboxconn.go
When a reserved connection is used in transaction it is natural to call rollback/commit when a query execution failed.
But, when a reserved connection is used in non-transaction/autocommit mode, VTGate needs to handle to case to release the held reserved connection in session, to move forward on next query and recreate the reserved connection with correct settings.
=> Remove shard session held in vtgate for reserved connection on connection failure

go/test/endtoend/vtgate/setstatement/sysvar_test.go, go/vt/vtgate/legacy_scatter_conn_test.go, go/vt/vtgate/safe_session.go, go/vt/vtgate/scatter_conn.go, go/vt/vtgate/scatter_conn_test.go, go/vt/vtgate/tx_conn_test.go, go/vt/vttablet/sandboxconn/sandboxconn.go
=> Backport of 6522 to release 7.0

go/vt/vttablet/tabletmanager/replmanager.go
replmanager never logged the first failure due to bad initialization.
=> tm: minor logging fix

go/test/endtoend/vreplication/cluster.go, go/vt/discovery/healthcheck_test.go, go/vt/discovery/legacy_healthcheck_flaky_test.go, go/vt/discovery/tablet_picker.go, go/vt/discovery/tablet_picker_test.go, go/vt/worker/legacy_split_clone_test.go, go/vt/worker/multi_split_diff_test.go, go/vt/worker/split_clone_flaky_test.go, go/vt/worker/split_diff_test.go, go/vt/worker/vertical_split_clone_test.go, go/vt/worker/vertical_split_diff_test.go, go/vt/wrangler/testlib/apply_schema_flaky_test.go, go/vt/wrangler/testlib/backup_test.go, go/vt/wrangler/testlib/copy_schema_shard_test.go, go/vt/wrangler/testlib/emergency_reparent_shard_test.go, go/vt/wrangler/testlib/external_reparent_test.go, go/vt/wrangler/testlib/migrate_served_from_test.go, go/vt/wrangler/testlib/migrate_served_types_test.go, go/vt/wrangler/testlib/permissions_test.go, go/vt/wrangler/testlib/planned_reparent_shard_test.go, go/vt/wrangler/testlib/reparent_utils_test.go, go/vt/wrangler/testlib/version_test.go, go/vt/wrangler/traffic_switcher_env_test.go, go/vt/wrangler/traffic_switcher_test.go
There was a bug in the tablet_picker implementation which could cause it to loop forever.
1. We were not checking whether the context is still valid.
2. If there are non-zero tablets of any kind, but zero tablets of the desired type, we loop forever (see 1.)
Along with fixing the above problem, this change has a few other improvements
- Always use a short context for topo calls
- Do retry if a tablet is not found, but only after a delay.
=> tablet_picker: keep trying to find a tablet until context expires

go/vt/vtgate/executor.go, go/vt/vtgate/executor_set_test.go
=> Backport: HandleSet in executor to handle multiple settings in single set statement

go/test/endtoend/cluster/vtgate_process.go, go/test/endtoend/vtgate/setstatement/main_test.go, go/vt/vtgate/executor_set_test.go, go/vt/vtgate/planbuilder/builder.go, go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/planbuilder/set.go, go/vt/vtgate/planbuilder/testdata/set_sysvar_disabled_cases.txt, go/vt/vtgate/vcursor_impl.go, go/vt/vtgate/vtgate.go
Disabling usage of reserved connection on system settings by default on 7.0 release branch.
=> passthrough system settings disabled by default

go/test/endtoend/vtgate/misc_test.go, go/vt/vttablet/tabletserver/planbuilder/plan.go
=> Backport: Make sure to handle EXPLAIN on vttablet

go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/traffic_switcher_env_test.go, go/vt/wrangler/traffic_switcher_test.go, go/vt/wrangler/vdiff_env_test.go, go/vt/wrangler/vexec_test.go, go/vt/wrangler/wrangler_env_test.go
VReplication creates a reverse workflow on SwitchWrites so that it is possible to revert a MoveTables or Reshard. However the cell/tablet_types columns in _vt.vreplication are currently not updated with the options provided on the command line.
This PR fixes that:
* we use the same tablet_types in the reverse workflow 
* we use the same cells list, except: if the source and target keyspaces are different and the forward workflow included the 
target's cell (but not the source's) we use the source cell instead.
We chose this approach instead of adding more cli options to specify tablet_types/cells for the reverse workflow as a simpler initial implementation. We can add the extra options if we find valid use-cases for it.
=> Reverse workflow: update cells/tablet_types

go/vt/wrangler/vexec.go
=> Vtctl Workflow cmd: don't expect all shards to have workflow streams

go/vt/vtctld/api.go, go/vt/vtctld/api_test.go
_(A continuation of https://github.com/vitessio/vitess/pull/6524, abandoned due to `git rebase` issues 🤞)_
This PR adds realtime health stats to the vtctld `/api/keyspace/<ks>/tablets/<shard>` HTTP API endpoint. This extends the PR @shlomi-noach made in https://github.com/vitessio/vitess/pull/4232
The tablet health metrics are needed for [`github.com/github/freno`](https://github.com/github/freno) to understand if a `vttablet` is ready for probes for replication lag. In today's implementation that looks for any tablet-type == `REPLICA` it is possible for an unhealthy `vttablet` _(replication is `STOP SLAVE`'d, mysqld crashed, etc)_ to continue to be probed by Freno because it is unable to detect tablet health from the current API endpoint
This PR also adds a `cell` and `cells` (CSV list) …
=> Add realtime health stats to vtctld /api/keyspace/ks/tablets API

go/pools/numbered.go, go/pools/numbered_test.go, go/vt/vttablet/endtoend/connkilling/connkiller_test.go, go/vt/vttablet/endtoend/connkilling/main_test.go, go/vt/vttablet/endtoend/connkilling/reserve_test.go, go/vt/vttablet/endtoend/framework/server.go, go/vt/vttablet/tabletserver/stateful_connection.go, go/vt/vttablet/tabletserver/stateful_connection_pool.go, go/vt/vttablet/tabletserver/tx_engine.go, go/vt/vttablet/tabletserver/tx_pool.go
Currently reserved connections and transactions both are killed after a specific connection timeout from the time of its first use.
This change make use of last connection used time to see if the connection is idle for a certain time.
The current modification changes the logic for both reserved and transaction connection to use last used time. Also, the transaction connections will call rollback rather than closing the underlying connection.
Open Discussion Point: 
1. Should transaction connection killer still continue to use created time to identify the idle transactions or it can use the last used time?
2. Should transaction connection killer still continue to close idle transaction or it can be changed to do rollback instead?
=> Close Idle reserved connections and Rollback Idle transactions

examples/compose/vtcompose/vtcompose.go, examples/compose/vttablet-up.sh
Fixes https://github.com/vitessio/vitess/issues/6521
This PR removes deprecated `InitTablet` and introduces `InitShardMaster`. This is done by:
- running one docker
- per shard
- after all shard tablets are initialized
- that executes `InitShardMaster` on the `*01` tablet (e.g. `test-201`)
=> vtcompose/docker-compose: fix InitShardMaster

go/vt/mysqlctl/schema.go
- One-pass access for PrimaryKeyColumns
- getPrimaryKeyColumns retrieves multiple tables from information_schema.key_column_usage instead of using SHOW INDEX
- Parallel requests for Column metadata and Create Table schema
- Filters out tables before doing expensive operations
Mutex version of:
https://github.com/vitessio/vitess/pull/6255
=> GetSchema: Batch/parallel access to underlying mysqld for lower latency

web/vtctld2/package-lock.json
https://github.com/vitessio/vitess/pull/6603 modified package-lock.json significantly. It is unclear if this file should be checked in for the (very old) vtctld version of the build tooling (for newer ones it clearly says it should be committed: https://medium.com/coinmonks/everything-you-wanted-to-know-about-package-lock-json-b81911aa8ab8). 
This PR reverts package-lock.json to the one previous to #6603 
=> Reverting package-lock.json to the one pre-PR #6603

go/vt/wrangler/testlib/emergency_reparent_shard_test.go
This PR removes an expectation that we can know for sure what the queries will be on replicas in an ERS situation. `SetMaster` calls are done in the background as a best effort approach, so we can only check for error, and the query list of the new master.
=> Fix: Remove SetMaster Query Expectation from ERS Test

go/vt/wrangler/materializer.go, go/vt/wrangler/materializer_env_test.go, go/vt/wrangler/materializer_test.go
Backporting: Materialize: Only get schema from source tablets if target is missing tables #6601
Signed-off-by: Rohit Nayak rohit@planetscale.com
=> Backport 6601

doc/releasenotes/7_0_1_release_notes.md
As discussed earlier, we'll store release notes in version control so that we can iterate on them before creating the release.
=> 7.0.1 release notes

go/vt/vtctl/vtctl.go, go/vt/wrangler/vexec.go, go/vt/wrangler/vexec_test.go
This PR renames the `List` subcommand to `Show` and expands the metadata to also return `TabletControls` and whether the master of each shard is currently serving write traffic. This PR also changed the `listStreams` method to be named `ShowWorkflow` to fit the new subcommand nomenclature, and makes it public so `vitess-operator` can use this wrangler method, and expose replication status information in a k8s friendly way.
=> Workflow: List -> Show, and Expand Metadata

go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_init_test.go
=> tm: add more logging to checkMastership

go/test/endtoend/vtgate/misc_test.go, go/vt/sqlparser/ast_funcs.go, go/vt/vtgate/executor.go, go/vt/vttablet/tabletserver/planbuilder/builder.go, go/vt/vttablet/tabletserver/planbuilder/plan.go, go/vt/vttablet/tabletserver/planbuilder/plan_test.go, go/vt/vttablet/tabletserver/planbuilder/testdata/exec_cases.txt, go/vt/vttablet/tabletserver/query_engine.go, go/vt/vttablet/tabletserver/query_executor.go
When writing a query using SHOW TABLES, a common query is something :
```
SHOW TABLES FROM keyspace WHERE Tables_in_keyspace = 'table'
```
because the underlying database does not always use the same database name as the keyspace name, we need to rewrite the query before sending it down to MySQL.
Fixes #6446
=> Rewrite SHOW TABLES

go/vt/vtctl/vtctl.go
=> Minor addition to Materialize help text.

go/sync2/semaphore.go, go/sync2/semaphore_test.go, go/vt/vttablet/tabletmanager/replmanager.go, go/vt/vttablet/tabletmanager/rpc_server.go, go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_state.go
A deadlock was found during a PRS. The root cause was a fix where we changed the replmanager to take the action lock. Otherwise, it would potentially race and conflict with other actions. But this led to a deadlock because `PromoteReplica` also waits for the replmanager to finish its fix.
We could have spot-fixed this for the specific use case. But in the interest of preventing other corner cases, the better fix was to change replmanager to not wait if it couldn't obtain a lock.
However, the implementation of `lock` with context timeout was flawed, because it wouldn't really timeout if the context expired. So, I implemented a new AcquireContext in sync2.Semaphore to, which encouraged to fix the flaky tests there.
Using the semaphore allowed me to implement a real `tryLock`, and …
=> tm: fix replmanager deadlock

go/vt/servenv/grpc_server.go
* Makes sure grpc_server_keepalive_enforcement_policy_min_time has a value that is compatible with grpc_keepalive_timeout. The value for the timeouts was recently change, but the enforcement policy was not updated. 
* Fixes this issue: https://github.com/vitessio/vitess/pull/5922#issuecomment-672269584
* I did not test this PR. but I think CI should be sufficient.
=> Updates enforcement policy to match the one from the client

go/sync2/semaphore.go, go/sync2/semaphore_test.go, go/vt/vttablet/tabletmanager/replmanager.go, go/vt/vttablet/tabletmanager/rpc_server.go, go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_state.go
of #6625 
A deadlock was found during a PRS. The root cause was a fix where we changed the replmanager to take the action lock. Otherwise, it would potentially race and conflict with other actions. But this led to a deadlock because PromoteReplica also waits for the replmanager to finish its fix.
We could have spot-fixed this for the specific use case. But in the interest of preventing other corner cases, the better fix was to change replmanager to not wait if it couldn't obtain a lock.
However, the implementation of lock with context timeout was flawed, because it wouldn't really timeout if the context expired. So, I implemented a new AcquireContext in sync2.Semaphore to, which encouraged to fix the flaky tests there.
Using the semaphore allowed me to implement a real tryLock, and …
=> Backport: tm: fix replmanager deadlock

go/vt/binlog/binlogplayer/binlog_player.go, go/vt/vttablet/tabletmanager/vreplication/engine.go, go/vt/vttablet/tabletmanager/vreplication/engine_test.go
Change the `source` column to have unlimited size (4gb), to allow for larger vreplication source content, such as many tables.
- Should cause no issues with current code.
- Ideally has no performance impact for same-size `source` column data.
=> VReplication: _vt.vreplication source column VARBINARY->BLOB

go/vt/vtgate/executor_test.go, go/vt/vtgate/plan_execute.go
plan type will be used to set logstats stmtType instead of a preview call to avoid string manipulation calls.
=> Removed sqlparser.preview to set logstats stmtType and use plan.type

go/vt/discovery/replicationlag.go, go/vt/vttablet/tabletserver/tabletenv/config.go
=> Update some option docstrings for accuracy.

go/vt/discovery/tablet_picker.go
Also, check for cell before cellsAlias to reduce the number of topo errors.
=> tablet picker: use partial result from GetTabletMap if it is available

go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_init_test.go, go/vt/vttablet/tabletmanager/tm_state.go, go/vt/vttablet/tabletmanager/tm_state_test.go
This fixes a bug where checkMastership changes the internal state, but initTablet doesn't know about it.
=> tm init: publish displayState

go/vt/binlog/binlogplayer/binlog_player.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer.go, go/vt/wrangler/vexec.go, go/vt/wrangler/vexec_test.go, go/vt/wrangler/wrangler_env_test.go
This PR:
1. Updates `_vt.vreplication` row timestamp w/ each heartbeat that happens outside of a transaction. This improves the accuracy of the transaction_timestamp recorded for each `_vt.vreplication` row, and allows anyone inspecting the `_vt.vreplication` table to get an accurate read on replication lag.
2. Adds MaxVReplicationLag to `Workflow Show` subcommand, which displays the maximum vreplication lag seen across all shards.
3. Updates tests accordingly.
=> Update VReplication Timestamp w/ Heartbeat

go/vt/vttablet/queryservice/wrapped.go
We have checked for transaction ID and blocked any retry in wrapped queryservice. We should also do the same for reserved Connection.
=> Retry should not happen when in dedicated connection

go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletmanager/vreplication/replicator_plan.go, go/vt/vttablet/tabletmanager/vreplication/replicator_plan_test.go, go/vt/vttablet/tabletmanager/vreplication/table_plan_builder.go, go/vt/vttablet/tabletmanager/vreplication/vcopier.go, go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer.go, go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
Initial implementation for handling charset collations during the catchup phase of vreplication. 
We cast the values on both the lhs and rhs to the charset and collation of the columns in the catchup query.
=> VRepl Collations: find collations for char primary keys and cast comparison during catchup

go/test/endtoend/cluster/vttablet_process.go
With this fix the vttablet querylogs will be published in tmp folder like vtgate querylogs for end to end test run.
=> fix path for vttablet query log in end to end test

docker/bootstrap/Dockerfile.common
That version isn't supported any more. Hopefully, whatever problem
the default version had is fixed by now.
=> build: remove chromium hard-coding

Makefile
=> Address #6631 by reducing optimization level

go/vt/vtctl/vtctl.go
=> Clarify/expand MoveTables CLI help.

go/sqltypes/bind_variables.go, go/test/endtoend/vtgate/misc_test.go, go/vt/vtexplain/vtexplain_flaky_test.go, go/vt/vtgate/engine/route.go, go/vt/vtgate/planbuilder/select.go, go/vt/vttablet/tabletserver/query_executor.go
=> fix: information schema for non existent schema

go/vt/vttablet/tabletserver/vstreamer/uvstreamer.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go, go/vt/wrangler/vdiff.go, go/vt/wrangler/vdiff_test.go
Improved a few error messages during MoveTables and VDiff
=> VRep: improve few error/log messages

docker/lite/install_dependencies.sh
Signed-off-by: John Watson <johnw@planetscale.com>
=> Try to install apt keys from list of different keyservers

go/test/endtoend/vtgate/setstatement/main_test.go, go/test/endtoend/vtgate/setstatement/sysvar_test.go, go/vt/vtgate/scatter_conn.go
We need to reset the session when a query execution failed on a reserved connection outside of a transaction due to connection idle timeout.
Without this, the current session will be not usable to run any other queries forward.
=> Reset Session for Reserved Connection Query Failure

go/cmd/vtbackup/vtbackup.go, go/test/endtoend/backup/vtbackup/backup_only_test.go, go/vt/mysqlctl/backup.go, go/vt/vttablet/tabletmanager/restore.go, go/vt/wrangler/testlib/backup_test.go
=> restore: do not change tablet type to RESTORE if not actually performing a restore

go/vt/discovery/tablet_picker.go, go/vt/vtctl/vtctl.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go, go/vt/wrangler/vdiff.go, go/vt/wrangler/vdiff_test.go
We had added a few logs while debugging issues where vdiff was stopping early during a Twitter migration. These are useful for vreplication observability in general.
=> VDiff logs: additional logging around vdiff/vstreamer for observability

go/stats/histogram.go, go/stats/histogram_test.go, go/stats/timings_test.go, go/vt/servenv/exporter_test.go, go/vt/vttablet/endtoend/config_test.go, go/vt/vttablet/tabletserver/repltracker/reader.go, go/vt/vttablet/tabletserver/repltracker/reader_test.go, go/vt/vttablet/tabletserver/repltracker/repltracker.go
Fixes #6528 
Sample output from /debug/vars: 
```
"HeartbeatLagNsHistogram": {"0": 0, "1ms": 0, "10ms": 0, "100ms": 16, "1s": 58, "10s": 3, "100s": 0, "1000s": 0, ">1000s": 0, "Count": 77, "Total": 21665771418},
```
=> heartbeat: lag histogram

go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_init_test.go, go/vt/vttablet/tabletmanager/tm_state.go, go/vt/vttablet/tabletmanager/tm_state_test.go
=> Backport: tm init: publish displayState

go/test/endtoend/vtgate/misc_test.go, go/vt/vtgate/executor.go
=> Allow switching between OLAP and OLTP

go/vt/wrangler/vexec_test.go
=> Workflow test: fix flaky test. remove obsolete code

go/sqltypes/named_result_test.go
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>
=> Add unit test case to improve test coverage for go/sqltypes/named_result.go

docker/lite/Dockerfile.ubi7.mysql57, docker/lite/Dockerfile.ubi7.mysql80, docker/lite/Dockerfile.ubi7.percona57, docker/lite/Dockerfile.ubi7.percona80
I had to make these URL changes to get the UBI image to build.
=> docker/lite: Fix package URLs for ubi images.

.github/workflows/docker_test_1.yml, .github/workflows/docker_test_2.yml, go/test/endtoend/reparent/main_test.go, go/test/endtoend/reparent/reparent_test.go, go/vt/mysqlctl/backup.go, test/config.json
When the desired database is present, we should not check for the existence of tables.
The presence of the database is sufficient to tell us that the instance has been initialized and hence should not be restored from backup.
=> restore: checkNoDB should not require tables to be present 

go/test/endtoend/vreplication/helper.go, go/test/endtoend/vreplication/vreplication_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer.go, go/vt/wrangler/traffic_switcher.go
There was a regression in https://github.com/vitessio/vitess/pull/6635 due to which unsaved events were not being saved on a heartbeat.
This resulted in SwitchWrites failing because shards where there no activity relevant to the stream would never catchup to the master position. This bug manifested when one switched back and forth between forward and reverse workflows without any
new relevant writes (matching the keyspace id) to the target shard. 
Also added more logs for observability.
=> Fix unsaved event regression

go/vt/vttablet/tabletserver/tabletenv/config.go, go/vt/vttablet/tabletserver/tabletenv/config_test.go
The schema tracker streams all binlog events and hence can cause heavy cpu utilization with high write qps. So we turn it off by default and let the user explicitly turn it on.
=> Turn off schema tracker by default

go/test/endtoend/vtgate/misc_test.go, go/vt/vtgate/engine/singlerow.go, go/vt/vtgate/executor_select_test.go
Signed-off-by: Andres Taylor <andres@planetscale.com>
=> make sure dual queries set found_rows correctly

docker/k8s/Dockerfile, docker/k8s/logrotate/Dockerfile, docker/k8s/logtail/Dockerfile, docker/k8s/mysqlctld/Dockerfile, docker/k8s/orchestrator/Dockerfile, docker/k8s/pmm-client/Dockerfile, docker/k8s/vtbackup/Dockerfile, docker/k8s/vtctl/Dockerfile, docker/k8s/vtctlclient/Dockerfile, docker/k8s/vtctld/Dockerfile, docker/k8s/vtexplain/Dockerfile, docker/k8s/vtgate/Dockerfile, docker/k8s/vttablet/Dockerfile, docker/k8s/vtworker/Dockerfile, helm/release.sh
- upgrade from stretch to buster, also cleans up extra spaces and enables build args for release orchestration
- before this, releases weren't deterministic and weren't even coordinated between image repos. This cleans it up, plus uses new docker ARGs to automate the release
=> helm & docker/k8s update

docker/base/Dockerfile, docker/base/Dockerfile.mariadb, docker/base/Dockerfile.mariadb103, docker/base/Dockerfile.mysql56, docker/base/Dockerfile.mysql80, docker/base/Dockerfile.percona, docker/base/Dockerfile.percona57, docker/base/Dockerfile.percona80, docker/lite/Dockerfile.alpine, docker/lite/Dockerfile.mariadb, docker/lite/Dockerfile.mariadb103, docker/lite/Dockerfile.mysql56, docker/lite/Dockerfile.mysql57, docker/lite/Dockerfile.mysql80, docker/lite/Dockerfile.percona, docker/lite/Dockerfile.percona57, docker/lite/Dockerfile.percona80, docker/lite/Dockerfile.testing, docker/lite/Dockerfile.ubi7.mysql57, docker/lite/Dockerfile.ubi7.mysql80, docker/lite/Dockerfile.ubi7.percona57, docker/lite/Dockerfile.ubi7.percona80, tools/build_version_flags.sh
Expose `BUILD_NUMBER` at Docker build time.
We currently let to override `BUILD_NUMBER` at build time in a non-Docker environment, I think we should let to do the same in Docker. This will let user to build Vitess, via Docker, using something like:
```
docker build \
--no-cache \
--build-arg BUILD_NUMBER="$BUILD_NUMBER" \
-t "${IMAGE_TAG}" \
-f "${GIT_CHECKOUT}/docker/base/Dockerfile.${FLAVOR}" .
```
=> Docker - allow BUILD_NUMBER variable override

go/test/endtoend/cluster/vtctlclient_process.go, go/test/endtoend/sharding/base_sharding.go, go/test/endtoend/sharding/initialsharding/sharding_util.go, go/test/endtoend/sharding/mergesharding/mergesharding_base.go, go/test/endtoend/sharding/resharding/resharding_base.go, go/test/endtoend/sharding/verticalsplit/vertical_split_test.go
The sharding tests were expecting an exact number of queries and
transactions to be processed by vreplication. But this is not
as deterministic as it used to be. All these tests are already
verifying the target using SplitDiff, which is the more reliable
way to verify correctness.
=> e2e: deflake sharding tests

go/mysql/endtoend/main_test.go, go/vt/mysqlctl/capabilityset.go, go/vt/mysqlctl/mysqld.go, go/vt/mysqlctl/mysqld_test.go
=> Mysql -ssl tag is deprecated in the later versions of mysql

go/vt/vttablet/tabletmanager/vreplication/external_connector.go
This PR just changes the db user to allprivs instead of dba to prevent inadvertent writes into schema_version when a tablet transitions from master to replica.
We have a separate issue where reparent tests are failing with tracker on. But on further investigation it looks like that those tests are not setting up and tearing down the cluster correctly leading to tablets resuming from their earlier state and binlogs being thus in unexpected states. That is being fixed in #6726  and if any related tracker bugs are found we will fix them as part of that issue.  
=> Change tracker to use allprivs instead of dba

go/test/endtoend/vtgate/concurrentdml/main_test.go, go/vt/vtgate/vcursor_impl.go
* Allow query like `update t1 set c2 = 200 where c2 = 100`
* This disables support of update followed by insert having save consistent lookup vindex value.
Support above query takes more priority than trying to throw error for seconds case without stuck on lock wait timeout error.
=> Allow Update of same vindex using same vindex lookup on consistent lookup vindex

go/test/endtoend/vreplication/vreplication_test.go, test/config.json
VReplication e2e tests never ran in CI. We traced the errors to insufficient resources: either file handles or aio handles. These are set as 64K in /etc/security/limits.conf and /proc/sys/fs/aio-max-nr and they cannot be overwritten by sudo. 
For now, until we can figure out to increase the hard limits:
* The basic test runs only with masters (replicas set to 0)
* The three tests have been separated into different test "shards" (22/23/24 atm). 
=> VReplication e2e tests: Simplify and split tests to overcome current CI resource constraints

go/vt/vtctl/vtctl.go
we no longer auto-generate docs from vtctl.go
=> Remove auto-generation comment

go/vt/mysqlctl/s3backupstorage/s3.go
Updates the s3 ListAllBackups() function to to work from the root directory 
Signed-off-by: Yujie Zhu <yujiezhu718@gmail.com>
=> upstream s3 ListBackups bug fix for vtbackup_cleaner

go/test/endtoend/vtgate/reservedconn/sysvar_test.go, go/vt/vtgate/safe_session.go
Issue:
If there is any session system variable settings applied on Vitess which needs to be handled through reserved connection.
Then a followed up dml can fail with error
`BUG: SafeSession.AppendOrUpdate: unexpected autocommit state `
This happens because the reserved connection is not short lived and needs to be stored in shard session so the same connection be used for future queries for the current session which have the applied system settings.
=> Fix reserved connection in autocommit mode on DML

go/vt/sqlparser/ast.go, go/vt/sqlparser/precedence_test.go, go/vt/sqlparser/tracked_buffer.go
The Vitess AST printer was not taking associativity into consideration and stripping away parenthesis when it should not.
Fixes #6734
=> operator precedence must take associativity into consideration

go/vt/vtgate/plugin_mysql_server.go, go/vt/vtgate/plugin_mysql_server_test.go
=> Replaced Error with a warning in case parsing of VT_SPAN_CONTEXT fails

go/test/endtoend/tabletmanager/tablet_test.go, go/vt/vttablet/tabletmanager/rpc_replication.go, go/vt/vttablet/tabletmanager/tm_state.go
During PlannedReparents, it is possible that a tablet advertises itself as MASTER while mysql is still read_only because `ChangeTabletType` triggers a health broadcast. 
This PR adds a call to `SetReadOnly` inside `ChangeTabletType` when the new tablet_type is MASTER.
Remove the call from `PromoteReplica` since it is no longer needed there.
=> tm: call setReadOnly inside ChangeTabletType

go/vt/wrangler/vexec.go, go/vt/wrangler/vexec_test.go
This PR cleans up noisy logging related to workflow methods, and moves printing logic up a level so that direct Wrangler method calls aren't printing output intended purely for vtctl command use from a console.
=> Refactor: Cleanup Noisy Workflow Logging

doc/releasenotes/7_0_2_release_notes.md
=> 7.0.2 Release Notes

go/vt/vttablet/tabletmanager/restore.go
During fast-forward, the VStream code can get stuck sending
data to the channel. This will cause Close to hang waiting
for VStream to exit. I've changed the VStream call back to
end the stream as soon as the target position was reached.
=> pitr: fix deadlock in ff code

go/vt/vtctl/vtctl.go, go/vt/vtctl/vtctl_test.go
=> Add GenerateShardRanges to vtctl commands

go/vt/vttablet/tabletserver/vstreamer/planbuilder.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go
Currently replication streams fail even if tables that do not participate in a migration are dropped (or renamed) during a table migration (eg. with gh-ost). This PR fixes that bug by bypassing code that was being unnecessarily called for tables that do not participate in the workflow.
=> Materialization: Do not error if tables that are not part of the stream go missing

go/vt/vtgate/engine/insert.go, go/vt/vtgate/engine/insert_test.go
This adds support to generate a sequence value when a 0 is passed instead of just null. This is the default behavior for MySQL.
Also need to look into detecting when sql_mode has been set to  NO_AUTO_VALUE_ON_ZERO and handle that accordingly. I'm not sure the best way to go about that so any guidance there would be appreciated.
Ref https://github.com/vitessio/vitess/pull/4751
=> Zero autoinc mode

go/vt/vttablet/tabletserver/vstreamer/testenv/testenv.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go, go/vt/vttest/environment.go
There are certain SET statements that seem to make it to the binlogs. One reported by a user is the "SET PASSWORD" query. 
Currently vstreamer throws an error in the logs if it encounters a SET. Note that data replication is not affected. However this
causes errors in the logs. 
We are going to send an OTHER event just like for DBA commands like REPAIR or ACL ones like GRANT/REVOKE. 
A few interesting points which caused challenges while testing:
* SET PASSWORD has been removed in 8.0.11 and above
* An option log_builtin_as_identified_by_password has to be set. Otherwise a SET PASSWORD goes into the binlogs as
an ALTER ... This seems to be off by default
* On MariaDB the default seems to be to pass the SET PASSWORD through. They do not have that variable.
So for simplicity the test only …
=> VStreamer: handle SET statements in the binlog stream

go/vt/orchestrator/http/api.go, go/vt/orchestrator/logic/topology_recovery_dao.go
This fixes a few `govet` errors in `orchestrator`, which fail pre-commit hooks.
=> fixed orchestrator govet errors

go/vt/mysqlctl/schema.go, go/vt/mysqlctl/tabledefinitions_test.go
=> sort tabledefinitions before comparing them

go/test/endtoend/vtgate/concurrentdml/main_test.go, go/vt/vtexplain/testdata/multi-output/updatesharded-output.txt, go/vt/vtexplain/vtexplain_vttablet.go, go/vt/vtgate/autocommit_test.go, go/vt/vtgate/engine/update.go, go/vt/vtgate/engine/update_test.go, go/vt/vtgate/executor_dml_test.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/planbuilder/testdata/dml_cases.txt, go/vt/vtgate/planbuilder/update.go
Same value vindex update are avoided by checking the old and the new value. Vitess does not perform string comparisons due to collation so for vindex involving varchar, etc. are updated even if they have same new and old values.
With this change, the string comparison is sent down to mysql through owned vindex lookup query, so there is no additional hop added and the comparison is handled by mysql.
If it returns true then the vindex is not updated.
=> Update Vindex only on changes

go/test/endtoend/tabletmanager/tablet_test.go, go/vt/vttablet/tabletmanager/restore.go, go/vt/vttablet/tabletmanager/rpc_actions.go, go/vt/vttablet/tabletmanager/rpc_backup.go, go/vt/vttablet/tabletmanager/rpc_replication.go, go/vt/vttablet/tabletmanager/tm_state.go, go/vt/vttablet/tabletmanager/tm_state_test.go
In #6762 we changed ChangeTabletType to also set read-write on MASTER instances. However, this should not be done when dealing with externally managed tablets because it will invariably fail and could cause the whole action to fail.
This PR makes it optional so that only active cluster management functions attempt to change the read_only property of the underlying DB.
=> tm: change how SetReadOnly is called to avoid errors from externally managed tablets

go/vt/orchestrator/config/config.go, go/vt/orchestrator/inst/instance_topology_dao.go, go/vt/orchestrator/inst/tablet_dao.go, go/vt/orchestrator/logic/tablet_discovery.go
=> orc: use contexts with timeout for remote operations

go/test/endtoend/reparent/main_test.go, go/test/endtoend/reparent/reparent_test.go, go/vt/mysqlctl/backup.go
=> Backport: checkNoDB should not require tables to be present

go/vt/mysqlctl/schema.go
Rename function to keep lint happy
=> Fix dbname that needs escaping that we broke in fce4cfd894

go/vt/vtgate/vcursor_impl_test.go
Fixes #6799. vtgate tests pass on both go1.15 and go1.14
=> Update build errors in ./go/vt/vtgate for go1.15

go/vt/vttablet/tabletmanager/restore.go, go/vt/vttablet/tabletmanager/rpc_actions.go, go/vt/vttablet/tabletmanager/rpc_backup.go, go/vt/vttablet/tabletmanager/rpc_replication.go, go/vt/vttablet/tabletmanager/tm_state.go, go/vt/vttablet/tabletmanager/tm_state_test.go
Backport of #6762 and #6786.
Hand-edited because cherry-picking the commits produces too many conflicts.
=> tm: call SetReadOnly inside ChangeTabletType 

go/test/endtoend/orchestrator/orc_test.go
=> orc tests: add more cases

go/mysql/conn.go, go/mysql/conn_test.go, go/mysql/query_test.go, go/mysql/server.go, go/mysql/server_test.go
When a multi-statement query is received, any errors should abort the execution of the remaining queries.
The `execQuery` and `handleNextCommand` were returning an error, but not actually using the error value - just checking if it was nil or not.
We need to be able to know on the outside of `execQuery` if an error occured and if it was an error we need to close the connection for or if it was a simple execution error.
Fixes #6747
=> Fix error around breaking of multistatements

go/test/endtoend/orchestrator/orc_test.go
disable TER test until it can be made reliable.
=> orc tests: don't set DbName for tests that don't need it. 

go/vt/vttablet/tabletserver/bench_test.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tabletserver_test.go
Fixes #6753 #6757 
Adds the functionality of replacing the database name in MySQL output with the keyspace name to the tablet server.
=> Mask database name

docker/mini/vttablet-mini-up.sh, examples/local/scripts/vttablet-up.sh, go/test/endtoend/tabletmanager/throttler/throttler_test.go, go/vt/vttablet/tabletserver/repltracker/repltracker.go, go/vt/vttablet/tabletserver/repltracker/repltracker_test.go, go/vt/vttablet/tabletserver/repltracker/writer.go, go/vt/vttablet/tabletserver/tabletenv/config.go, go/vt/vttablet/tabletserver/throttle/check_result.go, go/vt/vttablet/tabletserver/throttle/throttler.go
followup to https://github.com/vitessio/vitess/pull/6668
This PR introduces `-enable-lag-throttler` feature flag (bool). By default `-enable-lag-throttler` is `false`.
When `-enable-lag-throttler=true`, the vttablet throttler functionality is activated:
- throttler will probe mysql servers for lag
- throttler will aggregate probed data
- implicitly active heartbeat writer regardless of heartbeat config.
cc @aquarapid
=> vttablet throttler feature flag: -enable-lag-throttler

go/vt/servenv/grpc_server.go, go/vt/vtctl/vtctl.go
=> Fix and clarify some help options

go/test/endtoend/orchestrator/orc_test.go, go/vt/orchestrator/db/generate_base.go, go/vt/orchestrator/inst/tablet_dao.go, go/vt/orchestrator/logic/tablet_discovery.go, go/vt/topotools/utils.go
=> Add clusters_to_watch flag to orchestrator. Defaults to all clusters.

go/test/endtoend/vreplication/cluster.go, go/vt/discovery/tablet_picker.go, go/vt/mysqlctl/schema.go, go/vt/vttablet/tabletserver/binlog_watcher.go, go/vt/vttablet/tabletserver/schema/engine.go, go/vt/vttablet/tabletserver/state_manager.go, go/vt/vttablet/tabletserver/vstreamer/planbuilder.go, go/vt/vttablet/tabletserver/vstreamer/rowstreamer.go, go/vt/vttablet/tabletserver/vstreamer/uvstreamer.go, go/vt/wrangler/fake_dbclient_test.go, go/vt/wrangler/keyspace.go, go/vt/wrangler/materializer.go, go/vt/wrangler/materializer_env_test.go, go/vt/wrangler/materializer_test.go, go/vt/wrangler/resharder.go, go/vt/wrangler/resharder_env_test.go, go/vt/wrangler/resharder_test.go, go/vt/wrangler/stream_migrater_test.go, go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/traffic_switcher_env_test.go, go/vt/wrangler/traffic_switcher_test.go
Workflow artifacts like entries in the _vt.vreplication and _vt.resharding_journal tables, if not cleaned up, after a workflow is completed can cause strange errors during subsequent workflows. DropSources clears these, but users don't always run DropSources. Added validations include:
* a check if previous _vt.vreplication entries exist in frozen state
* a check if resharding journals from a previous reshard are present on the current target 
Also
* add tables to the VSchema during movetables for unsharded keyspace targets (some workflows fail with a "table not found"
if user tries to reshard it and has only specified a csv table list to the movetables)
* more error logs for workflows for debugging purposes. Currently errors are just returned to the grpc client and hence not logged in …
=> Add validations and logs to fix common issues faced during MoveTables/Reshard

go/test/endtoend/vreplication/cluster.go, go/vt/vttablet/tabletserver/binlog_watcher.go, go/vt/vttablet/tabletserver/state_manager.go, go/vt/vttablet/tabletserver/vstreamer/uvstreamer.go
Start watcher if historian is on. Currently if we set only TrackSchemaVersions on a replica the historian is never called to manage schema versions since the Replication Watcher is off by default and hence no vstreams run. This change also turns on the watcher if the historian is enabled.
=> Fix issues with missing tables in vstreams

go/vt/binlog/binlogplayer/binlog_player.go, go/vt/vttablet/tabletmanager/vreplication/controller.go, go/vt/vttablet/tabletmanager/vreplication/stats.go, go/vt/vttablet/tabletmanager/vreplication/vplayer.go, go/vt/vttablet/tabletmanager/vreplication/vreplicator.go, go/vt/vttablet/tabletserver/vstreamer/copy.go, go/vt/vttablet/tabletserver/vstreamer/engine.go, go/vt/vttablet/tabletserver/vstreamer/uvstreamer.go, go/vt/vttablet/tabletserver/vstreamer/uvstreamer_test.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
Signed-off-by: Rohit Nayak rohit@planetscale.com
=> vrepl metrics: add metrics around vstreamer and vreplication metrics

docker/k8s/Dockerfile, docker/k8s/mysqlctld/Dockerfile, docker/k8s/orchestrator/Dockerfile, docker/k8s/pmm-client/Dockerfile, docker/k8s/vtbackup/Dockerfile, docker/k8s/vtctl/Dockerfile, docker/k8s/vtctlclient/Dockerfile, docker/k8s/vtctld/Dockerfile, docker/k8s/vtgate/Dockerfile, docker/k8s/vttablet/Dockerfile, docker/k8s/vtworker/Dockerfile, helm/release.sh
Without ARG defaults, automated docker builds are failing. This also tags the 7.0.2 release.
=> helm/docker: fix Docker builds + tag 7.0.2

go/vt/vttablet/tabletserver/tx_pool.go, go/vt/vttablet/tabletserver/tx_pool_test.go
The transaction limiter reduces a caller ID's quota within the transaction
pool to some fraction of the overall pool size. We've found it useful for
tightening the blast radius when a single client starts to have long
transactions for whatever reason.
We noticed in a development enviornment that the tx limiter was preventing
any new transactions for a particular caller ID even though no transactions
for that user were already in progress.
I'm not too familiar with this code, although it seems a bit brittle. In this PR
I've tried to make sure that if there's an error grabbing a connection from the
connection pool or if a connection is killed by the transaction killer, tx limiter
quota is restored.
I'd love for anyone who is to take a close look at this.
It seems possible that killed …
=> tx limiter: fix quota leak if Begin() errors or if the tx killer runs

go/vt/vttablet/onlineddl/executor.go
Minor bugfix that should make it to `8.0`: migrations should use low-priority throttling, same as table purge.
=> online-DDL: migration uses low priority throttling

go/test/endtoend/vtgate/misc_test.go, go/vt/sqlparser/ast_rewriting.go, go/vt/sqlparser/bind_var_needs.go, go/vt/sqlparser/expression_rewriting.go, go/vt/sqlparser/expression_rewriting_test.go, go/vt/sqlparser/rewriter_api.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/planbuilder/expr.go, go/vt/vtgate/planbuilder/testdata/dml_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
This PR adds logic to simplify subquery expressions that are simple to unnest.
If a query contains an expression looking something like:
```
SELECT * FROM user WHERE col = (SELECT 42)
```
this PR will unnest that subquery so that the query that is planned is instead:
```
SELECT * FROM user WHERE col = 42
```
Fixes #6827
=> Unnest simple subqueries

go/vt/discovery/healthcheck.go, go/vt/discovery/healthcheck_test.go
Healthcheck was incorrectly excluding non-local cell tablets. This fix ensures that healthcheck will connect to and monitor all tablets in `cells_to_watch`. However, only tablets that are MASTER/local cell/same cell alias will be stored in the list of healthy tablets.
Fixes #6846 
Testing:
- added unit tests
- manually tested with local multi-cell cluster
=> healthcheck: should receive healthcheck updates from all tablets in cells_to_watch

go/vt/topo/shard.go, go/vt/topo/shard_test.go, go/vt/topo/srv_keyspace.go
https://github.com/vitessio/vitess/issues/6793
MoveTables adds a TabletControl record for the master, blacklisting the participating tables for all cells. Multiple MoveTables workflows might be active. User can SwitchWrites on multiple workflow while retaining the blacklists until they are ready to DropSources. Currently only one list is allowed per tablet type in a keyspace.
Legacy workflows do not use the MASTER tablet type, while the new workflow only uses the MASTER. So the change in this PR supplements the existing logic: no mods to existing logic.
We allow the master blacklist for a keyspace to be table-oriented: user can ask for sets of tables to be added or removed from the blacklist. Adding a table to the blacklist which already contain this table is an error since a table cannot …
=> Allow multiple blacklists for master

examples/operator/operator.yaml
Hi Team.
I have been testing the backup configuration and I believe the backup engine description included in `operator.yaml` is not accurate. As specified in [backupengine.go\#L41](https://github.com/vitessio/vitess/blob/58f8fbb9343817815548a3f1994e11645df8d961/go/vt/mysqlctl/backupengine.go\#L41) the restores will always be done with whichever engine created the backup.
I have successfully performed the following tests:
1. Restore a tablet with `xtrabackup` configuration in a running Shard with tablets configured with `builtin` option. The tablet is successfully restored using the existing builtin backup.
2. Backup the newly restored tablet. The backup is done using `xtrabackup` as expected.
3. Restore a tablet with `xtrabackup` configuration. The restore succeeds using the latest …
=> Update `operator.yaml` backup engine description 

Makefile
This restores the behavior of make install to limit binaries installed in docker images.
=> Modify targets to restore behavior of make install

go/vt/key/destination.go, go/vt/key/key.go
This will be an iterative PR, and I'll try and fix some tests as we go along.
=> Fixing some flaky tests

go/vt/vtgate/vtgate.go
We are still not recommending users to enable reserved connections. 
Only enable it while you do something that you know needs reserved connections, such as an installation or to do a report.
If you by accident execute a SET statement during the setup of a connection with Vitess, so that all your connections end up needing reserved connections, you loose the benefits of connection pooling and this will put a heavy burden on your tablets.
=> [8.0] Disable reserved connections by default

go/test/endtoend/messaging/message_test.go
There seems to be an intrinsic race in the message manager's TestConnection test due to the goroutine in stream.MessageStream. Added sleeps before validations to see if that will fix the flakiness.
=> Flaky test: attempt to fix TestConnection in go/test/endtoend/messaging

go/vt/mysqlctl/azblobbackupstorage/azblob.go, go/vt/mysqlctl/gcsbackupstorage/gcs.go
fixes the search prefix to prevent it from becoming `//` when the directory is at root
Similar to #6732 
Signed-off-by: Yujie Zhu <yujiezhu718@gmail.com>
=> fix ListBackups for gcp and az to work with root directory

go/vt/vtgate/planbuilder/select.go, go/vt/vtgate/planbuilder/testdata/from_cases.txt
When we encounter a comparison with `table_schema` in the `WHERE` clause of an information_schema query, we extract the other side of the comparison and turn it into an `evalengine` expression. These expressions can be evaluated on the vtgate, and Vitess uses this information to figure out where it needs to send the query.
The issue here is when Vitess fails to transform the expression from an AST expression to a `evalengine` expression. 
Instead of failing the query, we should just not do that particular rewrite 
Fixes #6827
=> INFORMATION_SCHEMA.TABLE_SCHEMA comparison with dynamic value bugfix

docker/bootstrap/Dockerfile.common, docker/bootstrap/Dockerfile.mariadb, docker/bootstrap/Dockerfile.mariadb103, docker/bootstrap/Dockerfile.mysql56, docker/bootstrap/Dockerfile.mysql57, docker/bootstrap/Dockerfile.mysql80, docker/bootstrap/Dockerfile.percona, docker/bootstrap/Dockerfile.percona57, docker/bootstrap/Dockerfile.percona80, docker/lite/Dockerfile.mariadb, docker/lite/Dockerfile.mariadb103, docker/lite/Dockerfile.mysql56, docker/lite/Dockerfile.mysql57, docker/lite/Dockerfile.mysql80, docker/lite/Dockerfile.percona, docker/lite/Dockerfile.percona57, docker/lite/Dockerfile.percona80, docker/lite/Dockerfile.testing, docker/lite/install_dependencies.sh, docker/orchestrator/build.sh
Upgrade Docker images from Debian 9 (stretch) to Debian 10 (Buster). This PR was highly inspired by https://github.com/vitessio/vitess/pull/6129 (happy to close this if Morgan wants to complete his PR).
This PR also includes the following changes:
- move from `openjdk-8-jdk` to `default-jdk`
- removed misc dependencies no longer need
- install maven and etcd from repos
Debian Stretch is EOL since 2020-07-06 and Buster was released in July 2019. This deprecation is also blocking us from upgrading to go 1.15 https://github.com/vitessio/vitess/pull/6792
I'm not sure if it's enough but the build of the bootstrap images completes ✅  
<details>
```
➜  vitess git:(buster) ✗ make docker_bootstrap
building bootstrap image: common
[+] Building 132.7s (13/13) FINISHED
=> [internal] load …
```
=> Docker - upgrade to Debian Buster

docker/bootstrap/Dockerfile.common, docker/bootstrap/Dockerfile.mariadb, docker/bootstrap/Dockerfile.mariadb103, docker/bootstrap/Dockerfile.mysql56, docker/bootstrap/Dockerfile.mysql57, docker/bootstrap/Dockerfile.mysql80, docker/bootstrap/Dockerfile.percona, docker/bootstrap/Dockerfile.percona57, docker/bootstrap/Dockerfile.percona80, docker/lite/Dockerfile.mariadb, docker/lite/Dockerfile.mariadb103, docker/lite/Dockerfile.mysql56, docker/lite/Dockerfile.mysql57, docker/lite/Dockerfile.mysql80, docker/lite/Dockerfile.percona, docker/lite/Dockerfile.percona57, docker/lite/Dockerfile.percona80, docker/lite/Dockerfile.testing, docker/lite/install_dependencies.sh, docker/orchestrator/build.sh
This is a cherry-pick of #6833 for the 8.0 release branch (as requested by @deepthi [here](https://github.com/vitessio/vitess/pull/6833#issuecomment-709462574)).
=> Docker - upgrade to Debian Buster (release-8.0)

go/cmd/vtcombo/main.go, go/vt/srvtopo/resolver_test.go, go/vt/topotools/rebuild_keyspace.go, go/vt/vtcombo/tablet_map.go, go/vt/vtctl/vtctl.go, go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_init_test.go, go/vt/worker/legacy_split_clone_test.go, go/vt/worker/multi_split_diff_test.go, go/vt/worker/split_clone_flaky_test.go, go/vt/worker/split_diff_test.go, go/vt/worker/vertical_split_clone_test.go, go/vt/worker/vertical_split_diff_test.go, go/vt/wrangler/keyspace.go, go/vt/wrangler/rebuild.go, go/vt/wrangler/testlib/external_reparent_test.go, go/vt/wrangler/testlib/find_tablet_test.go, go/vt/wrangler/testlib/migrate_served_types_test.go, go/vt/wrangler/testlib/shard_test.go, go/vt/wrangler/traffic_switcher_env_test.go
When using Point-in-time Recovery, users may sometimes want to restore a subset of shards, especially if the keyspace has a large number of shards.
Previously, a keyspace would not go to SERVING unless the shards spanned the full keyrange. This PR turns off those checks for SNAPSHOT keyspaces. 
=> allow incomplete SNAPSHOT keyspaces

go/vt/vtgate/planbuilder/select.go, go/vt/vtgate/planbuilder/testdata/from_cases.txt
If we encounter a `table_schema` comparison in a information_schema query, we'll just not rewrite it when we cant evaluate the expression on vtgate
This is a cherry-pick of #6881
=> Allow table_schema comparisons

go/vt/vttablet/tabletserver/health_streamer.go, go/vt/vttablet/tabletserver/state_manager.go, go/vt/vttablet/tabletserver/status.go
Today, if vtgate is slow to receive health updates from a tablet the tablet may
simply throw away the most recent status update instead of buffering it.
Since there's no periodic forced state push and discarded state is the most
recent one, this creates a possibility that a gate can permenently and incorrectly
believe that a tablet is not serving. You could have a healthy master tablet and a
gate that doesn't believe it's healthy and the only fix today would be to do an
operation and restart the gate.
The fix in this PR is to cancel the streaming health RPC if the buffer overflows rather
than discarding the most recent state update. Whenever the gate or its network connection
gets unwedged it'll realize that the streaming health RPC is canceled and open up a new
streaming health RPC where …
=> tablet streaming health fix: never silently skip health state changes

go/vt/vttablet/onlineddl/executor.go
In the following statement:
```
ALTER WITH 'gh-ost' '--throttle-query="SELECT SLEEP(1)"' TABLE t DROP COLUMN c
```
the current behavior wrongly parses the command line options as `'--throttle-query="SELECT` and `SLEEP(1)"`, because of the space, ignoring the quotes. This PR fixes that by using a more sophisticated parser.
This should ideally make it into 8.0.
=> 8.0 Bugfix: fix parsing of online-ddl command line options

go/vt/vttablet/onlineddl/executor.go
Co-submission of https://github.com/vitessio/vitess/pull/6899, going into `master`.
In the following statement:
```
ALTER WITH 'gh-ost' '--throttle-query="SELECT SLEEP(1)"' TABLE t DROP COLUMN c
```
the current behavior wrongly parses the command line options as `'--throttle-query="SELECT` and `SLEEP(1)"`, because of the space, ignoring the quotes. This PR fixes that by using a more sophisticated parser.
=> Fix parsing of online-ddl command line options

bootstrap.sh
A new repository, https://github.com/vitessio/vitess-resources, was created so as to mirror various resources needed by the Vitess build/bootstrap process. Instead of relying on those resources to exists in their original locations (e.g. `apache.,org`), we put them in https://github.com/vitessio/vitess-resources and fetch it from there.
This is an ongoing process; we'll iterate some resources one by one.
=> Pulling bootstrap resources from vitess-resources

go/vt/hook/hook.go, go/vt/hook/hook_test.go, go/vt/mysqlctl/builtinbackupengine.go, go/vt/mysqlctl/builtinbackupengine_test.go, go/vt/mysqlctl/fakemysqldaemon/fakemysqldaemon.go, go/vt/mysqlctl/mysqld.go
Resolves #6848 
Notable changes:
- hooks can now be passed contexts via the `ExecuteContext` method. All hooks are now implemented with `exec.CommandContext` under the hood instead of `exec.Command`. Current callers are unaffected, and can opt in to switching over at their discretion.
- adds a new `HookResult.ExitStatus` type for hooks that exceed their context deadline/timeout.
- `FakeMysqlDaemon.Start()` and `FakeMysqlDaemon.Shutdown()` are configurable via the `FakeMysqlDaemon.StartupTime` and `FakeMysqlDaemon.ShutdownTime` respectively, to artificially cause delay in tests.
=> Add timeout for mysqld_shutdown

go.mod, go.sum, go/vt/discovery/healthcheck.go
In a multi-cell scenario, we want to exclude REPLICA/RDONLY tablets in other cells from vtgate routing.
There was a bug in the logic in healthcheck that excludes these tablets. Whenever there was a healthcheck update for a tablet in "another" cell, all tablets in the healthy list were being dropped out.
Tested manually using a multi-cell cluster. An endtoend test will be added in a separate PR.
=> healthcheck: use isIncluded correctly to fix replica/rdonly routing bug

go/vt/hook/hook.go, go/vt/hook/hook_test.go, go/vt/mysqlctl/builtinbackupengine.go, go/vt/mysqlctl/builtinbackupengine_test.go, go/vt/mysqlctl/fakemysqldaemon/fakemysqldaemon.go, go/vt/mysqlctl/mysqld.go
This backports the changes in #6849 to the 8.0 release branch.
=> Backport pull request #6849 (add timeout for mysqld_shutdown) to 8.0

go/vt/vttablet/endtoend/misc_test.go, go/vt/vttablet/tabletserver/query_executor.go
When I originally added support for leading margin comments I made a mistake in this code:
https://github.com/vitessio/vitess/pull/3892/files#diff-799d4762d9e64026cb623db2defeb53209df055a99c1106f535006a89e7b812aR851
The code has become much more clear now, but at the time I ended up including the leading comment in a value
that should have been the query without comments.
=> query consolidator: fix to ignore leading margin comments

go/vt/vtctl/vtctl.go, go/vt/wrangler/vdiff.go, go/vt/wrangler/vdiff_test.go
A VDiff over an entire workflow can several hours or even days to run on large tables. It is useful sometimes during debugging to run a quick sanity check to find if the basic flow is working. 
This would have helped us, for example, when we recently had to debug a movetables workflow which was throwing errors while copying and a spot check of just the initial few rows would have led us to the problem.
=> VDiff: add ability to limit number of rows to compare

go/mysql/constants.go, go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go
co-submission of https://github.com/vitessio/vitess/pull/6909
This fixes a bug where the `master` tablet may be `read_only` when attempting to apply the online DDL schema (`_vt.schema_migrations` table).
With this PR we ensure schema is deployed before any online DDL operation.
It's noteworthy that we move away from `WithDDL`, which was meant to solve this exact problem, but is not strict enough. For this PR, we choose a smaller fix, but later on we may want to improve upon `WithDDL`.
=> OnlineDDL bugfix: make sure schema is applied on tablet

go/mysql/constants.go, go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go
This fixes a bug where the `master` tablet may be `read_only` when attempting to apply the online DDL schema (`_vt.schema_migrations` table).
With this PR we ensure schema is deployed before any online DDL operation.
It's noteworthy that we move away from `WithDDL`, which was meant to solve this exact problem, but is not strict enough. For this PR, we choose a smaller fix, but later on we may want to improve upon `WithDDL`.
This should be merged in `8.0`.
=> [8.0] OnlineDDL bugfix: make sure schema is applied on tablet

go.mod, go.sum, go/test/endtoend/vreplication/config.go, go/vt/vttablet/tabletserver/vstreamer/snapshot_conn.go
Currently we set the timezone of the mysql connection to be UTC while replicating. However during the copy phase it is still using the default timezone. This causes columns of the timestamp datatype to be incorrect on the target.
=> VReplication: Set time zone to UTC while streaming rows

go.mod, go.sum, go/vt/discovery/healthcheck.go
This backports the fix for a pretty serious bug from #6904.
=> [8.0] healthcheck: use isIncluded correctly to fix replica/rdonly routing bug

doc/releasenotes/7_0_3_release_notes.md
=> 7.0.3 Release Notes

docker/bootstrap/Dockerfile.common, docker/bootstrap/Dockerfile.mariadb, docker/bootstrap/Dockerfile.mariadb103, docker/bootstrap/Dockerfile.mysql56, docker/bootstrap/Dockerfile.mysql57, docker/bootstrap/Dockerfile.mysql80, docker/bootstrap/Dockerfile.percona, docker/bootstrap/Dockerfile.percona57, docker/bootstrap/Dockerfile.percona80, docker/lite/Dockerfile.mariadb, docker/lite/Dockerfile.mariadb103, docker/lite/Dockerfile.mysql56, docker/lite/Dockerfile.mysql57, docker/lite/Dockerfile.mysql80, docker/lite/Dockerfile.percona, docker/lite/Dockerfile.percona57, docker/lite/Dockerfile.percona80, docker/lite/Dockerfile.testing, docker/lite/install_dependencies.sh, docker/orchestrator/build.sh
Reverts vitessio/vitess#6888
docker/lite builds are broken with this PR. We need some additional changes on top to get them working again.
For 8.0 we will go back to stretch and stay on go 1.13.
=> Revert "Docker - upgrade to Debian Buster (release-8.0)"

docker/lite/install_dependencies.sh
The lite builds are using Buster. This fixes the dependencies for that version
=> Change dependencies for lite builds

go/test/endtoend/vtgate/misc_test.go, go/vt/vtgate/executor.go
=> [8.0] Fix error handling in olap mode

go/test/endtoend/vtgate/misc_test.go, go/vt/vtgate/executor.go
=> [Forward Port] #6940 - Fix error handling in olap mode

docker/lite/install_dependencies.sh
=> [8.0] docker: pin mysql 5.7 and 8.0 versions for xtrabackup compatibility

doc/releasenotes/8_0_0_release_notes.md
=> 8_0_0 Release Notes

docker/lite/install_dependencies.sh
MySQL 5.6 is generally unsupported in the newest Debian. This adds the requisite overrides to get it to build on the buster-slim images
=> Fixing the 5.6 builds of vitess/lite

go/vt/vtgate/executor_set_test.go, go/vt/vtgate/planbuilder/set.go, go/vt/vtgate/planbuilder/testdata/set_cases.txt
When the client issue a set statement with global scope, Vitess will validate against the database settings and if it mismatch then will log the info message about ignoring it.
Fixes: https://github.com/vitessio/vitess/issues/6647
=> Set Global 

go/mysql/binlog_event_rbr.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletmanager/vreplication/table_plan_builder.go, go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go, go/vt/vttablet/tabletmanager/vreplication/vreplicator.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go
=> Binary PK: fix bug where padding of binary columns was being done incorrectly

docker/lite/install_dependencies.sh
The default mariadb-server is now 10.3, pin it to 10.2 so we have the correct version
=> Pin mariadb to use mariadb-server-10.2

go/mysql/binlog_event_rbr.go, go/mysql/binlog_event_rbr_test.go
with zeroes when extracting from binlogs, or DECIMAL
types with non-fractional part > 9 digits may
end up vreplicated as a broken number with
a space.
Previously submitted as #6183 ;  added testcase
and reproduced by using a column of type
DECIMAL(20,2) and value 1.10 
=> Pad non-fractional part of DECIMAL type

go/mysql/conn.go, go/mysql/conn_test.go
In case we encounter an error while writing an error packet, we should close the connection. Also if we are able to write the error packet successfully we should keep the connection open for further requests.
=> [8.0] Bug which caused the connection to not close in case of error writing an error packet

go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go, go/vt/vttablet/tabletmanager/vreplication/vreplicator.go, go/vt/wrangler/vexec.go, go/vt/wrangler/vexec_test.go
Show Error state for a Running or Stopped workflow only if the message column in _vt.vreplication contains the string error since it is also used by other apps like vdiff for alert messages. Currently it shows Error if message is non-empty.
=> Vtctld Workflow Command: fix error state in Workflow Show

go/mysql/conn.go, go/mysql/conn_test.go
In case we encounter an error while writing an error packet, we should close the connection. Also if we are able to write the error packet successfully we should keep the connection open for further requests.
=> Bug which caused the connection to not close in case of error writing an error packet

doc/VitessSlackGuidelinesv1_0.md
=> Vitess Slack Guidelines v1.0

go/vt/discovery/healthcheck_test.go
In #6904, I promised to add an endtoend test for the bugfix. Since then I have been able to reproduce the problem with a unit test, which I present here :smiley: 
=> Healthcheck: add unit test for multi-cell replica configurations

go/vt/vttablet/tabletserver/connpool/dbconn.go
These spots should be truncated to the length set by the `sql-max-length-errors` flag. Long log lines can blow up the log file sizes and certain log handling programs can choke on long log lines.
=> Truncate logged query in dbconn.go.

go/netutil/netutil_test.go
Signed-off-by: zouyu <zouy.fnst@cn.fujitsu.com>
I get the error when I run the unit test: 
```
go/netutil/netutil_test.go:59:30: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
FAIL	vitess.io/vitess/go/netutil [build failed]
FAIL
```
go version: go1.15.2 linux/amd64
=> Fix unit test error

go.mod, go.sum, go/mysql/binlog_event_json.go, go/mysql/binlog_event_json_test.go, go/mysql/binlog_event_rbr.go, go/mysql/binlog_event_rbr_test.go, go/mysql/endtoend/replication_test.go, go/vt/mysqlctl/query.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletmanager/vreplication/json_docs_test.go, go/vt/vttablet/tabletmanager/vreplication/replicator_plan.go, go/vt/vttablet/tabletmanager/vreplication/table_plan_builder.go, go/vt/vttablet/tabletmanager/vreplication/vplayer.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go, go/vt/vttablet/tabletserver/vstreamer/testenv/testenv.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go
This is a major refactor of the support for JSON columns in vreplication. The key changes are:
* a two pass parser using an intermediate AST and the ajson package. Parsing of the binlog json representation generates an ajson AST. Producing the json string to apply changes in sql on the target is done by ajson's unmarshall functionality. This removes code for escaping strings which added complexity and was buggy. Also the code used to do both steps in a single pass making it difficult to maintain. 
* more tests added for vreplication code paths
* added tests for "large" json docs
* needed to cast json columns to utf8mb4 during vreplication since we use binary charsets, due to this bug https://bugs.mysql.com/bug.php?id=93052 fixed in MySQL 8.0.14
* partial json is still not supported.
* it …
=> VReplication: refactored and enhanced support for JSON columns

go/mysql/conn.go, go/mysql/query.go
Use an ephemeral buffer when reading from mysql in the tablet `ReadQueryResult`.
Simple change to use an ephemeral buffer instead of allocating a new one for each read. This should save on GC.
=> use ephemeral buffer when reading rows

go/pools/id_pool.go, go/pools/id_pool_test.go, go/vt/binlog/binlog_connection.go
Addresses #6939. 
This partially returns to the implementation we had before #5998 ; in that we use an ID pool, but now we randomize the initial value.
=> Return to re-using server IDs for binlog connections

go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_init_test.go, go/vt/vttablet/tabletmanager/tm_state_test.go
Fixes https://github.com/vitessio/vitess/issues/6988
=> Correctly initialize the TabletType stats

go/pools/resource_pool.go
* Use vterrors for timeout errors in resource pool. This will make sure that error code is propagated correctly.
=> Adds better error when there are timeouts in resource pools

go/test/endtoend/vtgate/misc_test.go, go/vt/sqlparser/ast.go, go/vt/sqlparser/ast_funcs.go, go/vt/sqlparser/constants.go, go/vt/sqlparser/parse_test.go, go/vt/sqlparser/sql.go, go/vt/sqlparser/sql.y, go/vt/vtgate/engine/concatenate.go, go/vt/vtgate/engine/concatenate_test.go, go/vt/vtgate/engine/fake_vcursor_test.go, go/vt/vtgate/engine/primitive.go, go/vt/vtgate/planbuilder/concatenate.go, go/vt/vtgate/planbuilder/route.go, go/vt/vtgate/planbuilder/route_test.go, go/vt/vtgate/planbuilder/testdata/union_cases.txt, go/vt/vtgate/planbuilder/union.go, go/vt/vtgate/vcursor_impl.go
Planner improvements that allow UNION to be solved in a single route instead of being sent as separate queries and the concatenated at the vtgate level.
Example query:
```sql
select id from user 
union all 
select id from music
```
Before this change, this would have been solved by sending two scatter queries to all shards - one querying for `user` and one for `music`.
```json
{
"Original": "select id from user union all select id from music",
"OperatorType": "Concatenate",
"Inputs": [
{
"Variant": "SelectScatter",
"Keyspace": {
},
"FieldQuery": "select id from user where 1 != 1",
"Query": "select id from user",
"Table": "user"
},
{
"Variant": "SelectScatter", …
```
=> Improved support for UNION

go/vt/vtgate/safe_session.go
Instead of specifying each field and checking for non-equality use `proto.equal` method
=> use proto equal method 

go/vt/vtctl/vtctl.go, go/vt/wrangler/vdiff.go, go/vt/wrangler/vdiff_test.go, test/local_example.sh
* Lock target keyspace while taking snapshots of a table for vdiff for synchronizing multiple in-flight vdiffs for a workflow 
* Fix issue where target streams were not getting restarted: in case of some timeouts while syncing source and target to take snapshots, the targets stayed in a Stopped state. Ref: https://github.com/vitessio/vitess/issues/7010
=> VDiff: lock keyspace while snapshoting, restart target in case of errors

go/vt/vttablet/tabletmanager/vreplication/controller.go, go/vt/vttablet/tabletmanager/vreplication/controller_test.go, go/vt/vttablet/tabletmanager/vreplication/engine_test.go, go/vt/vttablet/tabletmanager/vreplication/journal_test.go, go/vt/vttablet/tabletmanager/vreplication/stats.go, go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go
* Tablet picker: surface errors and selected source tablets both in _vt.vreplication and debug vars. This can help resolve issues where vreplication is not progressing/starting and an incorrect tablet is selected or there is no tablet available for the cell/tablet_type parameters specified.
=> VRepl/Tablet Picker: improve observability of selected tablet

examples/compose/config/init_db.sql, examples/compose/docker-compose.beginners.yml, examples/compose/schemaload.sh, examples/compose/vtcompose/vtcompose.go, examples/compose/vttablet-up.sh
This PR replaces the huge `vitess: base` images >2G with the `vitess:lite` image.
The objective is to make it quicker for someone to spin up a docker-compose example.
A secondary objective is to mirror operator design and discard the `InitShardMaster` introduced [here](https://github.com/vitessio/vitess/pull/6584) by implementing orchestrator.
@sougou @shlomi-noach @deepthi
=> Replace vitess:base with vitess:lite images for docker-compose services

go/vt/workflow/parallel_runner_test.go
Fix for https://github.com/vitessio/vitess/issues/6948
The double close is due to a close when the buffered channel is blocked:
https://github.com/vitessio/vitess/blob/a3e3e0aa26de0e78d6b2d4e3b36e978ddcafdba8/go/vt/workflow/node.go#L387
Increasing the channel's buffer size dramatically certainly isn't a bulletproof fix, but I was not able to reproduce the issue after this change.
=> fix flakey TestParallelRunnerApprovalFirstRunningSecondRunning test

go/mysql/encoding.go, go/mysql/query.go, go/mysql/query_test.go, go/sqltypes/type.go
Fixes: #6986 
MYSQL_TYPE_YEAR in binary protocol needs to be handled as Varbinary than YEAR i.e. treat as length encoded string over uint16.
=> Fix COM_STMT_EXECUTE packet decode

go/test/endtoend/vreplication/cluster.go, go/test/endtoend/vreplication/helper.go, go/test/endtoend/vreplication/vreplication_test.go, go/vt/wrangler/traffic_switcher.go, test/config.json
Two of the e2e tests related to cell aliases are hanging, timing out in SwitchWrites, once in a while in CI. I am unable to reproduce the issues locally. The tests developed organically and it seemed like a good idea to refactor them a bit to make them more readable, make it easier (hopefully) to find and fix the flakiness and also make it easier to write more e2e tests in the future.
=> VReplication E2E Tests: Refactored  tests for readability and attempting to fix flakiness

go/mysql/constants.go, go/vt/vttablet/tabletserver/query_engine.go
Fixes #7038
This change makes IsConnErr treat "Too man connections" as a normal
error, allowing vttablet to continue serving. The same check is also
added to IsMySQLReachable in case it happens to get called through
a different code path.
The error code returned by mysql (2012) is more generic. So, we also
have to check for the specific substring.
It's hard to reliably test this using automated testing. Instead, I
manually created a state where mysql ran out of connections, verified
that vttablet did shut down, and also verified that vttablet continued
to serve after this fix.
=> vttablet: don't shutdown on too many connections

go/vt/wrangler/vexec.go, go/vt/wrangler/vexec_test.go, go/vt/wrangler/wrangler_env_test.go
* Workflow ListAll now includes stopped workflows. It was implemented to only give the active workflows as per PSDB's requirement. However this is confusing for regular users who don't see a created workflow if streams are in Stopped state. 
* Also improved output for ListAll: in particular, when there are no workflows an explicit message is provided instead of nothing
* If an invalid workflow name is provided Workflow Show now errors out (earlier an inconsistent output was shown)
=> Vtctld Workflow command: minor fixes

go/test/endtoend/vtgate/misc_test.go, go/vt/vtgate/engine/route.go, go/vt/vtgate/engine/route_test.go, go/vt/vtgate/planbuilder/route.go, go/vt/vtgate/planbuilder/route_test.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt
Fixes #6609 
The details of the fix are explained in the issue.
* Added a new Route opcode: `SelectMultiEqual`
* The Values field for the opcode contains the list of vindex input values to route on
* The plan builder uses a different code path for composite IN clause vs. the simple case.
* The plan works for nested composites also.
* If the operand values don't match or are non-trivial, we fall back to `SelectScatter`.
=> vtgate: route using vindex for composite IN clause

go/mysql/binlog_event.go, go/mysql/conn.go
Using the tool https://github.com/orijtech/structslop, I got this recommendation. 
```
~/dev/vitess/go/mysql/binlog_event.go:130:19: struct has size 56 (size class 64), could be 48 (size class 48), you'll save 25.00% if you rearrange it to:
struct {
HeaderSizes       []byte
ServerVersion     string
FormatVersion     uint16
HeaderLength      byte
ChecksumAlgorithm byte
}
~/dev/vitess/go/mysql/conn.go:81:11: struct has size 240 (size class 240), could be 224 (size class 224), you'll save 6.67% if you rearrange it to:
struct {
fields                 []*query.Field
schemaName             string
ClientData             interface{}
conn                   net.Conn
flavor                 flavor
ServerVersion          string
User                   string
UserData               Getter
bufferedReader …
```
=> Optimise struct field layout

go/test/endtoend/vtgate/lookup_test.go, go/vt/vtgate/engine/route.go, go/vt/vtgate/engine/route_test.go
NO
READY
SelectNone opcode was not handled for StreamExecute. This PR fixes it.
#7048 
=> fix #7048 for SelectNone in StreamExecute route engine

examples/compose/README.md, examples/compose/docker-compose.beginners.yml, examples/compose/tablet.yml, examples/compose/vtcompose/vtcompose.go, examples/compose/vttablet-up.sh
This PR allows one to define the `vitess:lite` image to be used when running the compose stack.
The env variable to be set is `VITESS_TAG`
@sougou
=> Allow custom image tags in compose

go/vt/vtctl/vtctl.go, go/vt/vtgate/evalengine/arithmetic.go, go/vt/vtgate/vindexes/consistent_lookup_test.go, go/vt/wrangler/materializer.go, go/vt/wrangler/materializer_test.go
* Added option -all to allow all tables to be moved. It is possible to exclude some tables using the -exclude option. Currently exclude list is a csv one with table names to be excluded.
* Validate that table names provided match with those in the source
=> MoveTables: validate that source tables exist, move all tables 

go/vt/vtgate/planbuilder/testdata/union_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
Some of the queries in the `unsupported_queries.txt` file were queries that will never be supported. These have been moved out from this file.
=> clean up plan building test cases

go/vt/key/key.go, go/vt/key/key_test.go, go/vt/vtgate/engine/fake_vcursor_test.go, go/vt/vtgate/engine/primitive.go, go/vt/vtgate/engine/vindex_func.go, go/vt/vtgate/engine/vindex_func_test.go, go/vt/vtgate/planbuilder/testdata/vindex_func_cases.txt, go/vt/vtgate/planbuilder/vindex_func.go, go/vt/vtgate/vcursor_impl.go
=> Support for hex & shard in vindex query

go/test/endtoend/onlineddl/onlineddl_test.go, go/vt/vtgate/vtgate.go
Quick followup to #7045 , this PR makes both `vtgate` and `vtctl` use same command line flag name `ddl_strategy`, which is also compatible with the session variable `@@ddl_strategy`.
Context: #6782
=> vtgate -ddl-strategy flag renamed to -ddl_strategy

go/vt/vttablet/onlineddl/executor.go
(mostly) Fixes https://github.com/vitessio/vitess/issues/7005
In this PR, a tablet terminates any migration found to be running which it did not spawn itself.
This is done by a simple heuristic: a tablet only runs a single migration at a time. So if a migration is found to be running, which does not have the UUID of the current/last running migration, then it can't have been executed by this tablet. It must have been executed by a former tablet which crashed.
To clarify, the migration will only be killed once a new process of `vttablet` is up. There's still a scenario where a `vttablet` crashes, migration somehow proceeds, _and completes_ before the new `vttablet` is started.
For now, this is good enough.
=> Online DDL: cancel running migrations executed by another tablet

go/vt/sqlparser/ast.go, go/vt/sqlparser/expression_rewriting.go, go/vt/sqlparser/rewriter.go, go/vt/sqlparser/sql.go, go/vt/sqlparser/sql.y, go/vt/vtgate/planbuilder/expr.go, go/vt/vtgate/planbuilder/from.go, go/vt/vtgate/planbuilder/select.go, go/vt/vttablet/tabletserver/planbuilder/permission.go
They are very similar in syntax, but one is a table expression and one is a value expression. No need to make the planner more complex by making it have to tell the two uses apart - easier if the parser differentiates between them.
=> separate sub-query and derived table into different structs

go/vt/vtgate/planbuilder/grouping.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt
A bug in the code allowed any expression to be accepted, as long as the first expression in the GROUP BY list is valid.
=> Make sure to check all GROUP BY columns

go/vt/vtctl/endtoend/get_schema_test.go, go/vt/vtctl/vtctl.go
If you are attempting to get aggregate table sizes across a keyspace, this requires one call to `GetSchema` per shard, which result in the caller to vtctl needing to `json2.Unmarshal` the same info (create table statement, column info) N times, when we know it's not going to change. This flag will allow a user to make one `GetSchema` call to get the schema, and then N-1 `GetSchema -table_sizes_only` calls for the rest of the shards, and results in much less data transfer and much faster (3-4x faster by some metrics I took) response times.
Closes #6987
=> Add option to GetSchema to only send the row count and data length over the wire

go/vt/sqlparser/analyzer_test.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go
Closes #7089
VStreamer was treating StmtComment as an unsupported statement. This PR sends an OTHER event for comments.
=> VReplication: Handle comment statement type in vstreamer

MAINTAINERS.md
=> Update maintainers of Vitess

go/vt/schemamanager/tablet_executor.go, go/vt/schemamanager/tablet_executor_test.go, go/vt/sqlparser/ast.go, go/vt/sqlparser/ast_test.go, go/vt/sqlparser/normalizer.go, go/vt/topotools/vschema_ddl.go, go/vt/vtctl/vtctl.go, go/vt/vtexplain/vtexplain.go, go/vt/vtexplain/vtexplain_vttablet.go, go/vt/vtgate/engine/fake_vcursor_test.go, go/vt/vtgate/engine/primitive.go, go/vt/vtgate/engine/vschema_ddl.go, go/vt/vtgate/vcursor_impl.go, go/vt/vttablet/tabletserver/vstreamer/planbuilder.go, go/vt/wrangler/materializer.go
All the occurences of DDL struct have been converted to DDLStatement interface. This is done so that further addition of newer constructs to DDLStatement interface does not affect the current functionality. The end goal is to remove the various functions added to the interface in this PR and convert them to a type switch for specific constructs.
=> Convert usages of DDL struct to DDLStatement interface

examples/local/401_teardown.sh
Adds timeout to checking for tablets in case vtctd is already down.
If it is, that line will hang for an hour currently.
=> Adds timeout to checking for tablets.

Makefile
Hi, thanks for this project! This adds `vtctl` to `make install-local` (noticed it was missing when following the [Getting Started](https://vitess.io/docs/get-started/local/) docs).
=> Add vtctl to make install-local

go/cmd/vtcombo/plugin_grpcvtgateservice.go, go/cmd/vttestserver/vttestserver_test.go, go/vt/vttest/environment.go
Currently, if you try to use `vtctlclient VtGateExecute` against `vttestserver`, it doesn't work. This fixes that.
=> Allows for vttestserver and vtcombo to respond to VtGateExecute.

go.sum, go/test/endtoend/vreplication/vreplication_test.go, go/vt/vttablet/tabletmanager/vreplication/controller.go, go/vt/wrangler/traffic_switcher.go
NO
Some of the vreplication e2e tests, especially MultiCell and CellAlias have been flaky: they timeout during SwitchWrites. Looks like the underlying cause is a race condition while switching writes and reads back and forth. To help reduce flakiness and add more visibility in case of errors we:
* Log state of streams and shard positions around where the tests are flaky
* Added sleeps after inserting data but before doing switching back and forth. There is an underlying race condition which will be logged as an issue, but in the interests of reducing CI flakiness adding these sleeps while we find a fix for it
* Specify PK explicitly, since using an autoincrement seems to cause some flakiness due to the inserted row going to a different …
=> VReplication e2e: Fine tuned test to reduce flakiness and added more logging to debug future flakiness 

go/vt/vtgate/evalengine/expressions.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/planbuilder/system_tables.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
Adds support for all the rails queries using information_schema
=> Adds support for all the rails queries using information_schema

go/test/endtoend/onlineddl/onlineddl_test.go
NO
**READY**
Fix missed rename in onlineddl_test
https://github.com/vitessio/vitess/commit/7703097743218d2a0b64351df71947ebbdc2f673
None.
=> Fix missed rename in onlineddl_test

go/test/endtoend/vtgate/system_schema_test.go, go/vt/sqlparser/ast_rewriting.go, go/vt/sqlparser/ast_rewriting_test.go, go/vt/vtgate/executor.go, go/vt/vtgate/planbuilder/builder.go, go/vt/vtgate/planbuilder/from.go, go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/planbuilder/route.go, go/vt/vtgate/vcursor_impl.go
NO
**READY**
This PR allows setting system schema as default database name on connect or with `use` statement. 
Fixes #7146 
=> Allow system table to be set as default database

proto/query.proto
NO
**READY**
So. This is a little bit embarassing!
For [VTAdmin](https://github.com/vitessio/vitess/issues/7117) (and our internal tool), we use the [protobufjs](https://github.com/protobufjs/protobuf.js) library to generate TypeScript types and bindings from Vitess protos. 
Unfortunately, protobufjs has a "quirk" with the `allow_alias` option, where the option _must_ appear before aliased IDs (otherwise you get a compilation error). Given that the proto3 spec does not specify order mattering, I think it's safe to assume that this is a bug in protobufjs. I've ticketed this here: https://github.com/protobufjs/protobuf.js/issues/1521  I'm... not entirely sure how easy the fix will be.
In the meantime, this PR does the …
=> Move allow_alias option in MySqlFlag enum to precede the aliased IDs

go.mod, go.sum, go/test/endtoend/vreplication/vreplication_test.go, go/vt/wrangler/traffic_switcher.go
While switching writes we first stop writes on the source and then wait for the targets to catchup to the source gtid positions. We then set the position that the target reached as the start position of the reverse workflow (if requested by user).  
A target can have more than one sources. Currently the target position is determined by the getting MasterPosition from mysql when the first source stream catches up. This is a bug since other source streams that are still running can advance the target's position. In such a case we can set the start position of the reverse replication stream to be in the past. Example: we may set the startPos to be 1-53 (where the first source stream caught up) where as the server is already at 1-66 (where …
=> SwitchWrites bug: reverse replication workflows can have wrong start positions

go/vt/vttablet/tabletserver/vstreamer/vstreamer.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go
Schema migrations using gh-ost/pt-osc create temporary tables as part of the artifacts created during a migration. Since events from these tables are in the binlogs, vstreamer ends up treating them as regular tables which start participating in movetables (without filters) and in resharding workflows. Their events are also streamed by the VStream API if not explicitly filtered out.
This PR uses the functionality provided by the schema migration package to identify internal tables and ignores them at the vstreamer level.
Fixes issue referred to here:
https://github.com/vitessio/vitess/issues/7078#issuecomment-734924465
=> VStreamer: Ignore temp tables created by onlineddl 

go/test/endtoend/onlineddl/onlineddl_test.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/query_executor_test.go
Signed-off-by: Andrei Sura <andrei.sura@sharpspring.com>
This pr is fixing an issue encountered when executing a query involving the dual table (there was a previous pr which fixed a similar issue but it seems that it does not address all code paths)
- as `root` this query works
```
select 0 as x union select 1;
+---+
| x |
+---+
| 0 |
| 1 |
+---+
```
- as a simple user I get the following error
```
vttablet: rpc error: code = PermissionDenied desc = table acl error: "xyz" [] cannot run Select on table "dual" (CallerID: xyz)
```
=> fix error: cannot run Select on table "dual"

go/test/endtoend/onlineddl/onlineddl_test.go
NO
ready
The existing `endtoend/online_ddl` tests use `gh-ost`, and assume they run on `Linux/amd64`: the `gh-ost` binary used is self extracted from VTTablet.
However, some of our developers use MacOS; the `gh-ost` binray compiled to `Linux/amd64` will not run on MacOS. 
Developers can now set the system variable `VITESS_ENDTOEND_GH_OST_PATH` to the fullpath of their `gh-ost` binary (compiled to `Darwin`).
If you're running on `Linux/amd64` you don't need to do anything.
tracking: #6926 
cc @GuptaManan100
=> Online DDL endtoend tests to support MacOS

go/vt/discovery/healthcheck.go, go/vt/discovery/healthcheck_test.go
NO
**READY**
When a tablet goes away, the healthy list needs to be updated.
Fixes #7123
=> healthcheck: healthy list should be recomputed when a tablet is removed

go/vt/vtgate/planbuilder/memory_sort.go, go/vt/vtgate/planbuilder/ordering.go, go/vt/vtgate/planbuilder/testdata/memory_sort_cases.txt
NO
**READY**
Add support for unary expression in order by column
=> add support for unary expression in order by column

go/vt/vtgate/planbuilder/route.go, go/vt/vtgate/planbuilder/testdata/memory_sort_cases.txt
NO
**READY**
Currently we add aliasedExpr as is to the weightstring function this causes issue for aliased columns
Fixes #7036 
=> Add only expr of aliasedExpr to weightstring function

go/vt/sqlparser/ast_rewriting.go, go/vt/sqlparser/ast_rewriting_test.go
NO
**READY**
With the change in #7150, `dual` table should be escaped from rewriting. 
=> Skip query rewriting for dual table

go/vt/vttablet/tabletmanager/vreplication/vdbclient.go, go/vt/vttablet/tabletmanager/vreplication/vplayer.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go, go/vt/vttablet/tabletmanager/vreplication/vreplicator.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
* Make default relay log size signficantly larger,
30k -> 250k. Improves performance tables with
larger rows significantly.
* Fix bug where we were fetching MaxSize instead of
MaxItems number of rows from VReplication source.
=> Make VReplication relay log size & rows configurable.

go/vt/vtgate/executor.go
Signed-off-by: hzhou <hzhou@pinterest.com>
NO
**READY**
This helps us spotting the SQL which exceeded the max memory rows
- [ X ]  logging
=> log sql which exceeds max memory rows

go/vt/vtexplain/vtexplain_vttablet.go, go/vt/vtexplain/vtexplain_vttablet_test.go
NO
**READY**
Adds support for detecting sequence tables via the required comment. Works transparently and what a user expects so I don't think it requires extra docs. Added a unit test for it.
- https://github.com/vitessio/vitess/issues/6919
- [x ] Tests
- [x ] Documentation
Makes feature work as expected so no need for extra docs.
None
=> add sequence table support for vtexplain

examples/operator/101_initial_cluster.yaml, examples/operator/201_customer_tablets.yaml, examples/operator/302_new_shards.yaml, examples/operator/306_down_shard_0.yaml, examples/operator/operator.yaml
NO
READY
Change images to 
```images:
vtctld: vitess/lite:v8.0.0
vtgate: vitess/lite:v8.0.0
vttablet: vitess/lite:v8.0.0
vtbackup: vitess/lite:v8.0.0
mysqld:
mysql56Compatible: vitess/lite:v6.0.20-20200429
mysqldExporter: prom/mysqld-exporter:v0.11.0
```
- [ X ] Tests
Please verify Operator vs Vitess version compatibility.
- [ X]  Cluster Management
=> Update Vitess v8.0 images

docker/lite/Dockerfile.ubi7.mysql57, docker/lite/Dockerfile.ubi7.mysql80, docker/lite/Dockerfile.ubi7.percona57, docker/lite/Dockerfile.ubi7.percona80
rpms directly.  Should be less brittle.
Fixes #7184 properly
=> Convert CentOS extra packages installation to yum instead of downloading

go/vt/mysqlctl/query.go, go/vt/mysqlctl/replication_test.go
YES 
READY
If we do any SQL commend with password, Vitess will log it. And currently vitess only redact master password.
This PR tries to redact any password in the SQL query so that people won't see it as plain text in the log
This addresses https://github.com/vitessio/vitess/issues/7197:
NA
=> Redact password

.github/CODEOWNERS
NO
**READY**
Over the next few weeks, @ajm188 and I will be working through the [vtctld service tickets](https://github.com/vitessio/vitess/projects/9). Concretely, we'll be posting PRs just like https://github.com/vitessio/vitess/pull/7201 for each of the commands we're migrating. 
To be super up front about the risk: our PRs _will_ be updating `go/vt/vtctl/vtctl.go`, which _could_ affect downstream Vitess deployments. Hence we're being extra careful about backwards compatibility. Our timeline and rollout for this work is described in detail in the RFC: https://github.com/vitessio/vitess/issues/7058.
- #7128 Initial implementation of vtctld service
- #7201 Add FindAllShardsInKeyspace …
=> Add @ajm188 + @doeg to CODEOWNERS for vtctld service files

.github/pull_request_template.md
Followup to an internal discussion, I've made some changes to the pull request template:
- Removed "Status" section. If the PR is a draft, then the developer should "create draft pull request", this is a built in GitHub feature.
- Aggregated "Backport" together with tests & documentation checkboxes. Everything is in a checkbox
- Clarified "test" and "documentation" meaning
- Turned most instruction to HTML comment. The developer will be able to read them. Most (in my experience) submissions may forget/neglect to actually modify those instructions. So having them as comment means they're readable upon submission, but hidden after submission.
cc @deepthi @askdba
=> Updated pull request template to add more clarity

go/vt/vttablet/onlineddl/executor.go
NO
READY
Fixing an issue raised in chat by @aquarapid, this PR:
- Uses more explicit name for the online DDL executor database pool
- Sets pool size to `3` rather than `1`. Originally I thought all operations would necessarily be sequential, and so set max pool size to `1`. Operations are not all sequential now, and in hindsight it was wrong to set to `1`.
=> Online DDL executor databae pool size increase

examples/local/301_customer_sharded.sh
When doing create_customer_sharded.sql (removing auto-increments) before vschema_customer_sharded.json (applying VIndex), there is a short period of time where INSERTs in the customer and corder tables would fail if the customer_id or order_id is not set.  Doing vschema_customer_sharded.json before create_customer_sharded.sql remove this failure possibility.
=> Do vschema_customer_sharded.json before create_customer_sharded.sql.

.github/CODEOWNERS
We forgot to add ourselves as codeowners to a couple of vtadmin-related files 😸 
- https://github.com/vitessio/vitess/pull/7202
- https://github.com/vitessio/vitess/pull/7187
N/A
=> Add @ajm188 + @doeg as vtadmin codeowners

go/vt/topo/zk2topo/zk_conn.go
Signed-off-by: JohnnyThree <whereshallyoube@gmail.com>
DialZK timeout seems does not take effect under such situation .
So here set context with timeout to make sure that dialZk will perform as expected
- 
=> fix meta data related operation hang when zk down

docker/local/run.sh, go/vt/vtadmin/cluster/discovery/discovery.go, go/vt/vtadmin/cluster/discovery/discovery_static_file.go, go/vt/vtadmin/cluster/discovery/discovery_static_file_test.go
Two changes in this PR:
- Adds a service discovery implementation using static files
- Exposes the vtgate gRPC port `:15991` in `./docker/local/run.sh` so that vtadmin (running outside of Docker) can issue requests
The best part is that now we can run vtadmin-api _and_ vtadmin-web locally, using a local Vitess ([in Docker](https://vitess.io/docs/get-started/local-docker/) or otherwise). 🎉 So we can add data fetching (and real data) to vtadmin-web 😈 finally the fun begins. 
We can enhance this later on by watching the cluster config file(s) for changes so updates don't require a restart of vtadmin-api. 
Many thanks as always to @ajm188 for answering my eight million golang questions! 💛 
First, you'll want to run Vitess itself …
=> [vtadmin] Add static file service discovery implementation

go/cmd/vttablet/status.go, go/vt/vttablet/endtoend/config_test.go, go/vt/vttablet/endtoend/framework/debugvars.go, go/vt/vttablet/endtoend/transaction_test.go, go/vt/vttablet/tabletserver/debugenv.go, go/vt/vttablet/tabletserver/query_engine.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/status.go, go/vt/vttablet/tabletserver/tabletserver.go
NO
READY
Feature implemented as specified in RFC.
Also added links to the new page from `/debug/status`
Fixes #7171 
Fixes #2983
None
=> vttablet: debug/env page to change variables in real-time

go/vt/vtctld/action_repository.go, go/vt/vtctld/api.go, go/vt/vtctld/api_test.go, go/vt/vtctld/vtctld.go
I was working on an internal POC when I needed to refactor some code around `actions_repository.go`; I noticed something that bothered me: most action functions received `http.Request`. It bothered me because I wanted to be able to run some actions irrespective of `http`. After looking deeper, I noticed no existing action uses the `http.Request`.
So this PR is code cleanup for removing `http.Request` from function signatures and callers, without affecting app logic.
=> action_respository: no need for http.Request

go/vt/vtgate/safe_session.go
Signed-off-by: Andrei Sura <andrei.sura@sharpspring.com>
We encountered a situation in our deployment where we saw repeatedly this message which was not very helpful
```
got a different alias for the same target
```
With this change the logs display more information which we used for debugging.
No related issue
Does not affect deployments
=> improve-log: FAILED_PRECONDITION

docker/local/Dockerfile
We use `docker/lite/install_dependencies.sh` to install mysql57 server and client
An internal discussion leading to the finding that `make docker_local` is broken:
```
$ make docker_local
Building vitess/local
Sending build context to Docker daemon  245.5MB
Step 1/20 : ARG bootstrap_version=0
Step 2/20 : ARG image="vitess/bootstrap:${bootstrap_version}-common"
Step 3/20 : FROM "${image}"
0-common: Pulling from vitess/bootstrap
b5fccd3d6845: Pull complete 
c25b21fd76f9: Pull complete 
ae6bd386dfb5: Pull complete 
66273862a1f5: Pull complete 
8dd00d46b611: Pull complete 
3a2640662882: Pull complete 
c7af44a17df4: Pull complete 
20e3098c40d6: Pull complete 
e5b9ee5cef7e: Pull complete 
45a16634d019: Pull complete 
341a945a6f03: Pull complete 
c2ee08fcd4ea: Pull complete 
241f187361b4: Pull …
```
=> make docker_local: fix missing mysql_server package

go/test/endtoend/vreplication/vreplication_test.go, go/test/endtoend/vreplication/vreplication_test_env.go, go/vt/wrangler/materializer.go, go/vt/wrangler/switcher.go, go/vt/wrangler/switcher_dry_run.go, go/vt/wrangler/switcher_interface.go, go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/traffic_switcher_test.go, go/vt/wrangler/workflow_test.go
* Delete routing rules when a MoveTables workflow is marked as completed or aborted
* Update source/target vschema to reflect the new tables when a MoveTables workflow is completed/aborted
#7217
=> MoveTables: delete routing rules and update vschema on Complete and Abort

go/test/endtoend/vreplication/resharding_workflows_v2_test.go, go/vt/vtctl/vtctl.go, go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/traffic_switcher_test.go, go/vt/wrangler/workflow.go
When a MoveTables or Reshard Start is invoked:
* polls streams on target 
* if the Message column contains an Error report it 
* if streams don't start before the timeout specified stop polling
Note that the workflow itself is not aborted. This just tells the user that there are possible issues and they need to fix it and then possibly restart the streams using the Workflow command or VExec/VReplicationExec if any custom repair is needed.
#7071
=> V2 Workflow Start: wait for streams to start and report errors if any while starting a workflow

go/test/endtoend/vreplication/vreplication_test_env.go, go/vt/wrangler/switcher_dry_run.go, go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/traffic_switcher_test.go
DropSources (achieved via the Complete subcommand in the v2 MoveTables command) supports a rename flag for MoveTables workflows. Tables are renamed as _<table_name> (see PR https://github.com/vitessio/vitess/pull/6383) . This change uses a similar logic to that used by pt-osc when it drops tables using the rename template _<table_name>_old. 
Reasons:
* we now use a more standard convention
* VReplication already ignores such tables, so they won't show up in vreplication workflows and vstream api events
https://github.com/vitessio/website/pull/655
=> DropSources: change table rename logic

go/vt/sqlparser/analyzer.go, go/vt/vtgate/executor.go
NO
**READY**
Caching plans other than select and dml queries does not give any plan benefits. Those queries are mostly that needs to be  re-planned.
TBD
=> cache only dml and select plans

docker/local/Dockerfile
The current MoveTables user guide https://vitess.io/docs/user-guides/migration/move-tables/ doesn't work with the local dockerfile setup as the guide expects SQL files to be available in the relative path `../common`. Because that directory isn't copied into the top-level `/vt` directory they aren't available for the entrypoint working directory. This PR copies `examples/common` into `/vt/common` to make the docker environment match the user guide expectations.
I'd also note that I tested this on the `v8.0.0` tag, as  `make docker_local` was broken for me the latest `master:HEAD` ea65a1cf3429997f3173097f9995d89417df3e10 with `Docker version 1.13.1` (admittedly an older version):
```
$ make docker_local
Building vitess/local
Sending build context to Docker daemon 235.2 MB
Step 1/22 : ARG …
```
=> local docker: copy examples/common into /vt/common to match MoveTables user guide

web/vtadmin/README.md, web/vtadmin/package-lock.json, web/vtadmin/package.json, web/vtadmin/src/api/http.test.ts, web/vtadmin/src/api/http.ts, web/vtadmin/src/components/App.tsx, web/vtadmin/src/hooks/api.ts, web/vtadmin/src/index.tsx, web/vtadmin/src/react-app-env.d.ts
**tl;dr:**
This PR implements the humble beginnings of our vtadmin-api HTTP fetchers using native fetch and [react-query](https://react-query.tanstack.com/). The API boundary is one of the spicier parts of any client, particularly when it comes to testing and (strong) typing. To that end, I focused on adding a bunch of tests + commentary -- I would love your feedback on these parts, in particular, if you have any.
Now the usual rambling... 
[react-query](https://react-query.tanstack.com/) is still somewhat new to me, and [Mock Service Workers](https://github.com/mswjs/msw) are brand new to me. I _really_ like how this implementation came together, but I expect a lot of unknown unknowns (for me) here. So I've tried to keep this implementation very modular + flexible in anticipation of us …
=> [vtadmin] Query vtadmin-api from vtadmin-web with fetch + react-query

go/test/endtoend/mysqlserver/main_test.go, go/test/endtoend/preparestmt/stmt_methods_test.go, go/test/endtoend/vtcombo/vttest_sample_test.go, go/vt/vtctld/redirection.go, go/vt/worker/executor.go
What it says in the title. Also reorder some imports to follow the "stdlib/3rdparty+vitess/proto" pattern.
- From [this discussion](https://github.com/vitessio/vitess/pull/7240#discussion_r551208289)
=> Fix all occurrences of `fmt.Sprint(x)` where x is `int`

docker/vttestserver/Dockerfile.mysql57, docker/vttestserver/Dockerfile.mysql80
There has been a request for a vttestserver docker image for testing purposes.
We already have a [Dockerfile](https://github.com/vitessio/vitess/blob/master/docker/lite/Dockerfile.testing) that does this for mysql57.
The files in this PR are just a little bit different.
- mysql57 and mysql80 flavors
- startup command that runs vttestserver using provided arguments
- removed orchestrator/web because I don't think that is required
Fixes #7203
Run as follows
```
$ docker run -e PORT=9997 -e NUM_SHARDS="1,1" -e KEYSPACES="hello,bye" --network host -d vitess/vttestserver:mysql57
1c64f5b029b198eee678ab9defa78419b11e8c8332c5326b996763404bfeb2e0
$ docker exec -it 1c64f5b029b198eee678ab9defa78419b11e8c8332c5326b996763404bfeb2e0 /bin/bash …
```
=> docker images for vttestserver

go/test/endtoend/vtgate/lookup_test.go, go/test/endtoend/vtgate/main_test.go, go/test/utils/diff.go, go/vt/vtexplain/testdata/multi-output/selectsharded-output.txt, go/vt/vtgate/executor_framework_test.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/vindexes/lookup_internal.go
We can't bundle together multiple varchar values and query the lookup vindexes using IN queries, because when we do, we then have to be able to compare varchar values at the vtgate level, and that is not always safe.
Fixes #7254
=> Don't turn varchar vindex queries into IN

go/test/endtoend/vtgate/lookup_test.go, go/test/endtoend/vtgate/main_test.go, go/test/utils/diff.go, go/vt/vtexplain/testdata/multi-output/selectsharded-output.txt, go/vt/vtgate/executor_framework_test.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/vindexes/lookup_internal.go
we can't group together multiple varchar values into a IN query,
because that forces use to compare varchar values on the vtgate
level which we can't do correctly yet
This is a backport of #7268 that solves #7254
=> [9.0] don't try to compare varchars in vtgate

go/test/endtoend/vtgate/lookup_test.go, go/test/endtoend/vtgate/main_test.go, go/test/utils/diff.go, go/vt/vtexplain/testdata/multi-output/selectsharded-output.txt, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/vindexes/lookup_internal.go
we can't group together multiple varchar values into a IN query,
because that forces use to compare varchar values on the vtgate
level which we can't do correctly yet
This is a backport of #7268 that solves #7254
=> [8.0] don't try to compare varchars in vtgate

go/test/endtoend/vtgate/lookup_test.go, go/test/endtoend/vtgate/main_test.go, go/test/utils/diff.go, go/vt/vtexplain/testdata/multi-output/selectsharded-output.txt, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/vcursor_impl_test.go, go/vt/vtgate/vindexes/lookup_internal.go
we can't group together multiple varchar values into a IN query,
because that forces use to compare varchar values on the vtgate
level which we can't do correctly yet
This is a backport of #7268 that solves #7254
=> [7.0] don't try to compare varchars in vtgate

docker/lite/install_dependencies.sh
Make docker build a bit more robust 
=> Make dependency install a bit more robust

go/vt/sqlparser/ast_funcs.go, go/vt/sqlparser/ast_test.go
Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>
Add `AddWhere` function to `Update` AST type, mirroring `Select.AddWhere` and making AST manipulation slightly easier.
None nessecary.
=> Add Update.AddWhere to mirror Select.AddWhere

go/vt/sqlparser/parse_test.go
Merely adding a few test cases for `parse_test.go` to validate some `CREATE TABLE` variations.
=> Added some unit test cases for CREATE TABLE parser

go/test/endtoend/vtgate/misc_test.go, go/vt/vtgate/vtgate.go
Removed the resolver logic when shard targeting. This enabled planing to be done for all queries. Planner knows how to work with shard targeting.
- Fixes https://github.com/vitessio/vitess/issues/7259
=> removed resolver usage from StreamExecute

go/vt/vtctl/vtctl.go
This was a regression introduced in #7128.
This restores the original json format of the old vtctl API, which I broke when trying to reimplement the old API in terms of the new. Example (using the local example): first the new, changed output, and then the old, correct output:
```
❯ vtctlclient -server "localhost:15999" FindAllShardsInKeyspace commerce
{
"0": {
"keyspace": "commerce",
"name": "0",
"shard": {
"master_alias": {
"cell": "zone1",
"uid": 100
},
"master_term_start_time": {
"seconds": 1610412569,
"nanoseconds": 995650000
},
"is_master_serving": true
}
}
}
❯ cd -
~/work/vitess
❯ make build
Mon Jan 11 19:50:24 EST 2021: Building source tree
❯ cd -
~/work/vitess/examples/local
❯ ./scripts/vtctld-down.sh
Stopping vtctld...
❯ ./scripts/vtctld-up.sh
Starting vtctld...
❯ vtctlclient …
```
=> [vtctld] Fix accidentally-broken legacy vtctl output format

go/test/endtoend/vreplication/resharding_workflows_v2_test.go, go/vt/vtctl/vtctl.go, go/vt/workflow/manager.go, go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/workflow.go, go/vt/wrangler/workflow_test.go
For neutral naming, all references to workflow.Abort renamed to workflow.Cancel.
=> Vreplication V2 Workflows: rename Abort to Cancel

.github/workflows/cluster_endtoend_11.yml, .github/workflows/cluster_endtoend_12.yml, .github/workflows/cluster_endtoend_13.yml, .github/workflows/cluster_endtoend_14.yml, .github/workflows/cluster_endtoend_15.yml, .github/workflows/cluster_endtoend_16.yml, .github/workflows/cluster_endtoend_17.yml, .github/workflows/cluster_endtoend_18.yml, .github/workflows/cluster_endtoend_19.yml, .github/workflows/cluster_endtoend_20.yml, .github/workflows/cluster_endtoend_21.yml, .github/workflows/cluster_endtoend_22.yml, .github/workflows/cluster_endtoend_23.yml, .github/workflows/cluster_endtoend_24.yml, .github/workflows/cluster_endtoend_26.yml, .github/workflows/cluster_endtoend_27.yml, .github/workflows/golangci-linter.yml, test/templates/cluster_endtoend_test.tpl
Add descriptive names for cluster endtoend tests and golangci-lint checks.
This is needed to manage branch protection rules, otherwise all these checks show up as `build`.
Also, once a PR is merged, this is the name that is visible when you go back and look at the status of checks at the time of merge.
#7258 
=> Descriptive names for CI checks

go/vt/vtctl/vtctl.go
This backports #7285 to the 9.0 release.
#7285 
=> Backport: [vtctld] Fix accidentally-broken legacy vtctl output format

go/vt/sqlparser/ast_funcs.go, go/vt/sqlparser/constants.go, go/vt/sqlparser/parse_test.go, go/vt/sqlparser/sql.go, go/vt/sqlparser/sql.y, go/vt/vtgate/executor_test.go, go/vt/vtgate/planbuilder/show.go
Added default databases when calling 'show databases'. 
Previously show databases and keyspaces acted as the same. 
https://github.com/vitessio/vitess/issues/7158
- 
- [Tests Added] Tests were added or are not required
- [Not required ] Documentation was added or is not required
- [x ]  Query Serving
- [x ]  Build
=> added default databases when calling 'show databases'

go/vt/sqlparser/ast_rewriting.go, go/vt/sqlparser/ast_rewriting_test.go, go/vt/sysvars/sysvars.go, go/vt/vtgate/executor.go
Signed-off-by: Akilan <me@akilan.io>
added vitess_version as variable
fixes https://github.com/vitessio/vitess/issues/3112
- [ x] Tests were added or are not required
- [ not added] Documentation was added or is not required
=> added vitess_version as variable

docker/vttestserver/Dockerfile.mysql57, docker/vttestserver/Dockerfile.mysql80
Adds an optional `MYSQL_BIND_HOST` environment variable to the `vttestserver` container; if included, this is passed as `-mysql_bind_host` to `vttestserver`
- #7203
- #7262
Run as follows:
```
$ docker run --rm -d -p33577:33577 -e PORT=33574 -e KEYSPACES=test -e NUM_SHARDS=1 -e MYSQL_BIND_HOST=0.0.0.0 vitess/vttestserver:mysql57
2c04c50156bd9ad7cac4b3f41bb653de37b78a0505c4154f1491e8d2730f5336
$ mysql -h127.0.0.1 -p33577
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1
Server version: 5.7.9-Vitess MySQL Community Server (GPL)
Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.
Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.
Type 'help;' or …
```
=> docker/vttestserver:  Add MYSQL_BIND_HOST env

.github/CODEOWNERS, go/vt/proto/vtadmin/vtadmin.pb.go, go/vt/vtadmin/api.go, go/vt/vtadmin/api_test.go, go/vt/vtadmin/cluster/cluster.go, go/vt/vtadmin/cluster/config.go, go/vt/vtadmin/cluster/config_test.go, go/vt/vtadmin/cluster/discovery/discovery.go, go/vt/vtadmin/cluster/discovery/discovery_consul.go, go/vt/vtadmin/cluster/discovery/discovery_static_file.go, go/vt/vtadmin/cluster/discovery/discovery_static_file_test.go, go/vt/vtadmin/cluster/discovery/fakediscovery/discovery.go, go/vt/vtadmin/cluster/file_config_test.go, go/vt/vtadmin/cluster/flags.go, go/vt/vtadmin/credentials/credentials.go, go/vt/vtadmin/credentials/credentials_test.go, go/vt/vtadmin/http/keyspaces.go, go/vt/vtadmin/vtctldclient/config.go, go/vt/vtadmin/vtctldclient/config_test.go, go/vt/vtadmin/vtctldclient/proxy.go, go/vt/vtadmin/vtsql/config.go, go/vt/vtadmin/vtsql/credentials.go, go/vt/vtctl/grpcvtctldclient/client.go, go/vt/vtctl/grpcvtctldclient/client_test.go, go/vt/vtctl/grpcvtctldserver/server_test.go, go/vt/vtctl/grpcvtctldserver/testutil/util.go, proto/vtadmin.proto
~~(I still need to deploy this fully to test, hence draft. But all feedback welcome!!)~~ Confirmed it works, yay!
This does the following:
* Adds `vtctldclient.Proxy` to vtadmin, semantically similar to `vtsql.DB` but for vtctldclient connections.
* Adds GetKeyspaces rpc to the vtadmin service, and implements it
* (minor) testing refactors for grpcvtctldserver, grpcvtctldclient
* (minor) adds vtctld discovery to the discovery interface, implements for all current implementations (static + consul)
- 
=> [vtadmin] Add vtctld proxy to vtadmin API, add GetKeyspaces endpoint

docker/local/run.sh, web/vtadmin/README.md
A couple tiny changes to get ✨ https://github.com/vitessio/vitess/pull/7266 ✨ working with local Docker! (I promise promise to add a tidy make target in lieu of those ~~four~~ five README steps... soon... 🙈)
- https://github.com/vitessio/vitess/pull/7266
N/A
=> Expose vtctld gRPC port in local Docker example + update VTAdmin README

go/vt/vtgate/vtgate.go
Changing system settings at database connection level should be known to user and almost all libraries do this at start time which will impact how the Vitess connection pooling behaves.
Setting this to false for the release.
=> Default to false for system settings to be changed per session at the database connection level

go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/select.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/bypass_cases.txt, go/vt/vtgate/planbuilder/testdata/dml_cases.txt, go/vt/vtgate/planbuilder/testdata/filter_cases.txt, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/planbuilder/testdata/lock_cases.txt, go/vt/vtgate/planbuilder/testdata/postprocess_cases.txt, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/planbuilder/testdata/set_cases.txt, go/vt/vtgate/planbuilder/testdata/transaction_cases.txt, go/vt/vtgate/planbuilder/testdata/union_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt, go/vt/vtgate/planbuilder/testdata/use_cases.txt, go/vt/vtgate/planbuilder/testdata/vindex_func_cases.txt, go/vt/vtgate/planbuilder/testdata/wireup_cases.txt, go/vt/vtgate/semantics/analyzer.go, go/vt/vtgate/semantics/analyzer_test.go
- https://github.com/vitessio/vitess/issues/7280
=> Gen4: Add Limit clause support

go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/planbuilder/querygraph.go, go/vt/vtgate/planbuilder/querygraph_test.go, go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/select.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/bypass_cases.txt, go/vt/vtgate/planbuilder/testdata/dml_cases.txt, go/vt/vtgate/planbuilder/testdata/filter_cases.txt, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/planbuilder/testdata/lock_cases.txt, go/vt/vtgate/planbuilder/testdata/postprocess_cases.txt, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/planbuilder/testdata/set_cases.txt, go/vt/vtgate/planbuilder/testdata/transaction_cases.txt, go/vt/vtgate/planbuilder/testdata/union_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt, go/vt/vtgate/planbuilder/testdata/use_cases.txt, go/vt/vtgate/planbuilder/testdata/vindex_func_cases.txt, go/vt/vtgate/planbuilder/testdata/wireup_cases.txt, go/vt/vtgate/semantics/analyzer.go, go/vt/vtgate/semantics/semantic_state.go
=> Gen4: Handling subquery in query graph

web/vtadmin/package-lock.json, web/vtadmin/package.json, web/vtadmin/src/components/App.module.scss, web/vtadmin/src/components/App.tsx, web/vtadmin/src/components/routes/Debug.tsx, web/vtadmin/src/components/routes/Tablets.tsx
Adds react router + a /debug page. Another tiny PR pulled out of a bigger branch. 
For a little context, I plan to co-opt the debug page as an informal style guide as I add all of the components in the [Figma spec](https://www.figma.com/file/By3SoETBRHpOirv3Ctfxdq/Designs). (In the past, I've used [Storybook](https://storybook.js.org/) for this, but I think that's _way_ overkill for what we need for the near future.)
No one asked, but my $0.02 anyway (haha). I personally prefer [ui-router](https://ui-router.github.io/) over [React Router](https://reactrouter.com/). (I think it's more straightforward.) That said, the ui-router documentation is _very_ painful to navigate. React Router has better documentation and I think it's …
=> Add React Router + a skeleton /debug page to VTAdmin

web/vtadmin/src/components/App.module.scss, web/vtadmin/src/components/App.tsx, web/vtadmin/src/components/NavRail.module.scss, web/vtadmin/src/components/NavRail.tsx, web/vtadmin/src/components/routes/Error404.module.scss, web/vtadmin/src/components/routes/Error404.tsx, web/vtadmin/src/index.css
:sparkles: Staged at http://vtadmin.puppy.software ✨ 
What this does:
- Adds the NavRail component. The sidebar, that is. :) 
- Simplifies CSS variables for light/dark themes.
What this does not do:
- This isn't pixel perfect quite yet. I expect more CSS tweaks to come. :) 
- This makes no attempt at a _really nice_ responsive layout. It is, however, a _serviceable_ responsive layout since it technically "works" for any viewport... as long as you don't mind scrolling, hehe. 
N/A
=> Add NavRail component

go/mysql/binlog_event_rbr.go, go/mysql/binlog_event_rbr_test.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go
Currently in VStreamer ROW Events, Decimal numbers get prefix-padded with 0s when precision is greater than 12. 
e.g. for a value of 1.23,  DECIMAL(12,2) gives 1.23, DECIMAL(13,2) gives 000000001.23
This PR removes these extra 0s so, for the example above, we return 1.23 for DECIMAL(13,2)
#7282
=> VStreamer Events: remove preceding zeroes from decimals in Row Events

.github/workflows/cluster_endtoend_upgrade.yml, go/test/endtoend/cluster/cluster_process.go, go/test/endtoend/cluster/mysqlctl_process.go, go/test/endtoend/cluster/vtctlclient_process.go, go/test/endtoend/versionupgrade/upgrade_test.go, test.go, test/config.json
Backport of https://github.com/vitessio/vitess/pull/7294
Followup to team discussion, we wish to add CI (endtoend) tests that validate an upgrade from a previous tagged version.
This PR introduces `endtoend` version upgrade test, specifically testing an upgrade path from `v8.0.0`. (side note, `v9.0.0` will be released later this month, and then we will add a test for a `v9.0.0` upgrade path).
The test verifies that a vitess cluster which was built, started and populated by a `v8.0.0` release, is readable by a `HEAD` (the PR branch) build.
The way this works:
- `.github/workflows/cluster_endtoend_upgrade.yml` is the workflow file
- it checks out `v8.0.0`, and builds the binaries
- stores binaries in a safe place
- checks out `HEAD`
- gets the binaries we built for `v8.0.0`
- runs …
=> Backport: Testing version upgrade/downgrade path from/to 8.0

go.mod, go.sum, go/test/endtoend/vreplication/resharding_workflows_v2_test.go, go/test/endtoend/vreplication/vreplication_test.go, go/test/endtoend/vreplication/vreplication_test_env.go, go/vt/vtctl/vtctl.go, go/vt/vtgate/discoverygateway_test.go, go/vt/vttablet/tabletmanager/vreplication/engine.go, go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/traffic_switcher_env_test.go, go/vt/wrangler/traffic_switcher_test.go, go/vt/wrangler/workflow.go, go/vt/wrangler/workflow_test.go
In V2 the Start sub-command both creates the workflow and starts the streams. This is confusing since it is the same term used to set the state of  a workflow to Running in the Workflow command.
We had just Replica as a default for tablet types that the tablet picker would use to choose a source tablet for vreplication streams. However for initial migration into Vitess users just have a single vttablet proxying their existing MySQL server and thus have just a Master tablet type. This would result in the vreplication streams getting stuck. With this PR this default is both replica and master.
Many setups do not have rdonly tablets. (Also rdonly is going to be deprecated _soon_). Currently we only consider a workflow as fully switched forward if all tablet types are switched. Thus users are …
=> VReplication: Miscellaneous improvements

go/vt/srvtopo/resilient_server.go
when local cell topo  server is down, all commands related with function GetSrvKeyspaceNames are hanging
Added topo timeout and when local cell topo is broken , will use cache instead , make sure not too much effect on vtgate
Signed-off-by: JohnnyThree <whereshallyoube@gmail.com>
- 
=> fix hang when local topo was down

.github/pull_request_template.md
As discussed in an internal meeting, we see many contributions that are not linked with an existing issue or a prior discussion.
This PR updated th epull request template to first and foremost ask the submitter to read the Contributing guide on the Vitess docs.
=> Pull Request template: link to contribution guide

examples/common/select_commerce_data.sql, examples/operator/README.md
In #7245 we removed a file (`select_commerce_data.sql`) from the operator example. However, the README still points to the deleted file.
This PR fixes the README to use the correct path to the file.
In addition, the `use` command in that file only worked for the local example, not the operator example.
That has also been fixed.
#7245 
A website PR will be created after 9.0 is released and we have archived the 9.0 docs.
=> fix common select script to work for both local and operator examples

go/vt/wrangler/vexec.go, go/vt/wrangler/vexec_plan.go, go/vt/wrangler/vexec_test.go, go/vt/wrangler/wrangler_env_test.go
1. There was a problem in the initial implementation of determining MaxVReplicationLag, which was the seconds since `transaction_timestamp`. MaxVReplicationLag is used, in a Reshard workflow, by the operator to determine when resharding is completed. See https://github.com/vitessio/vitess/issues/6946, which logs the problem and fixes it. However this fix was problematic for two reasons:
* `transaction_timestamp` is 0 as long as the stream is in the copy phase. If there are no new writes on the source once the copy phase is completed then the value does not get updated
* there are cases when there are no writes on the source relevant to a target. In this case the `transaction_timestamp` column for that stream does not get updated as there …
=> Workflow Show: use timeUpdated to calculate vreplication lag

go/vt/vtctl/vtctl.go
Return error immediately if the target keyspace is unknown. Do
the same for the source keyspace. Currently, the code will
attempt to continue with a bad keyspace name.
Signed-off-by: Jordan Moldow <jmoldow@alum.mit.edu>
- 
=> vtctl: Add missing err checks for VReplication v2

go/vt/mysqlctl/xtrabackupengine.go
Use vttablet option `xtrabackup_root_path` to find the `xbstream` binary.
If the option is not specified, we will continue to expect it to be present in PATH.
This behavior is consistent with how we treat the `xtrabackup` binary.
Fixes #7356
=> use provided xtrabackup_root_path to find xbstream 

web/vtadmin/src/components/Button.module.scss, web/vtadmin/src/components/TextInput.module.scss, web/vtadmin/src/components/TextInput.tsx, web/vtadmin/src/components/routes/Debug.module.scss, web/vtadmin/src/components/routes/Debug.tsx, web/vtadmin/src/index.css
✨ Staged at http://vtadmin.puppy.software/debug
A first pass at a TextInput component. I'll probably still mess with it but...! It's something. Also normalized the button heights to match the text input. 
Couple caveats:
- Haven't tested this on Firefox or IE
- Component documentation is... lacking. 😊 
**N/A**
**N/A**
=> Add TextInput component

web/vtadmin/src/components/App.module.scss, web/vtadmin/src/components/NavRail.module.scss, web/vtadmin/src/components/NavRail.tsx, web/vtadmin/src/index.css
As it says on the tin! 
Before:
After: 
**N/A**
**N/A**
=> Add icons + focus state to NavRail

go/mysql/server.go, go/test/endtoend/vtgate/misc_test.go, go/vt/servenv/buildinfo.go, go/vt/servenv/buildinfo_test.go, go/vt/servenv/version.go, go/vt/sqlparser/ast_rewriting.go, go/vt/sqlparser/ast_rewriting_test.go, go/vt/sysvars/sysvars.go, go/vt/vtgate/executor.go, go/vt/vtgate/plugin_mysql_server.go
This PR changes the `@@version` and `@@version_comment` values to include information about the Vitess version.
It also removed the recently added `@@vitess_version`.
The change includes a new file, `version.go` that contains very little. It's kept minimal like this to be easy for our release scripts to update the named version.
```sql
mysql> select @@version;
+------------------------------+
| @@version                    |
+------------------------------+
| 5.7.9-vitess-10.0.0-SNAPSHOT |
+------------------------------+
mysql> select @@version_comment;
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| @@version_comment …
```
=> Change @@version and @@version_comment

.github/pull_request_template.md, .github/workflows/check_runs_analysis.yaml
The check runs analysis CI job sends the contents of the analysis, encoded as `base64`, with a `curl` command. Currently as an argument, but that content grew to be too long.
With this PR, we write the content to file, and ask `curl` to attach it. With this approach the size limitation is lifted.
https://github.com/vitessio/vitess/issues/7382
- 
CI
cc @deepthi
=> CI: check run analysis to post JSON from file

go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_init_test.go, go/vt/vttablet/tabletmanager/tm_state_test.go
=> 8.0 backport: Correctly initialize the TabletType stats

go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_init_test.go, go/vt/vttablet/tabletmanager/tm_state_test.go
Similar to #6989, we should update the counter for TabletType during startup
Fixes #7389 
#6988 
=> Add 1 to statsTabletTypeCounts during startup

go/mysql/constants.go, go/vt/vtgate/planbuilder/builder.go, go/vt/vtgate/planbuilder/testdata/ddl_cases.txt
Fixes the error messages in drop, create and alter database commands. Fixes #7396.
=> Fixes the error messages in drop, create and alter database commands

go/sqltypes/bind_variables.go, go/sqltypes/value.go, go/test/endtoend/vtgate/reservedconn/main_test.go, go/test/endtoend/vtgate/reservedconn/sysvar_test.go, go/vt/vtgate/evalengine/evalengine.go, go/vt/vtgate/executor_select_test.go, go/vt/vttablet/endtoend/misc_test.go
This PR fixes https://github.com/vitessio/vitess/issues/7301. As detailed in the issue, selecting a `VitessAware` system variable without involving MySQL/Vttablets might return a nil result.
- https://github.com/vitessio/vitess/issues/7301
=> Fix VitessAware system variables of type boolean return NULL when MySQL is not involved

.github/CODEOWNERS, go/protoutil/doc.go, go/protoutil/duration.go, go/protoutil/duration_test.go, go/vt/vtctl/grpcvtctldserver/server.go
We're going to be dealing with a lot of duration pb types.
- 
=> Add protoutil package, refactor ISP to use it

go/vt/topotools/position_searcher.go, go/vt/topotools/position_searcher_test.go, go/vt/wrangler/reparent.go
This is so later I can use it in both `wrangler` and `grpcvtctldserver`.
As a show of good faith (I was going to anyway but let's pretend!), I've
also added some test cases.
- 
=> Extract the `maxReplPosSearch` struct out to `topotools`

web/vtadmin/src/api/http.test.ts, web/vtadmin/src/api/http.ts, web/vtadmin/src/react-app-env.d.ts
As the title says, this adds a build flag for vtadmin-web to configure the [fetch `credentials` property](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#sending_a_request_with_credentials_included) when making requests against vtadmin-api. This is useful for VTAdmin deployments that use cookie-based authentication.
I tested this out by deploying it internally. 🎉 Exciting! 
(This PR is identical to https://github.com/vitessio/vitess/pull/7413 modulo a small comment change. 🤔 I can't seem to re-open that PR against this same (downstream) branch, hence a new PR. Sorry about that!) 
N/A
N/A
=> Add vtadmin-web build flag for configuring fetch credentials

go/vt/vtadmin/api.go, go/vt/vtadmin/api_test.go
Updates vtadmin-api's `/api/gates` endpoint to return cluster information. 
Previously:
```
{"result":{"gates":[{"hostname":"127.0.0.1:15991"}]},"ok":true}
```
Currently:
```
{"result":{"gates":[{"hostname":"127.0.0.1:15991","cluster":{"id":"id1","name":"cluster1"}}]},"ok":true}
```
N/A
N/A
=> Add `cluster` field to vtadmin-api's /api/gates response

go/vt/concurrency/error_group.go, go/vt/wrangler/reparent.go
This is part of a larger effort to migrate `PlannedReparentShard` and `EmergencyReparentShard` for #7428, and I'm trying to lead with some refactors to make the actual final change less scary (I'm working on a few more extractions that will have tests attached to them, which should hopefully give us even more confidence in the final change).
- #7428 
=> Add `ErrorGroup` to package concurrency, use in `waitOnNMinusOneTablets`

go/cmd/vtctldclient/internal/command/root.go
What it says in the title. I noticed this while I was doing testing for #7395.
Before (`SilenceErrors: false`):
```
❯ vtctldclient --server "localhost:15999" DeleteKeyspace commerce >/dev/null
Error: DeleteKeyspace(commerce) error: rpc error: code = Unknown desc = keyspace commerce still has 1 shards; use Recursive=true or remove them manually; please check the topo
E0127 20:20:34.651188   89060 main.go:42] DeleteKeyspace(commerce) error: rpc error: code = Unknown desc = keyspace commerce still has 1 shards; use Recursive=true or remove them manually; please check the topo
```
After (`SilenceErrors: true`):
```
❯ vtctldclient --server "localhost:15999" DeleteKeyspace commerce >/dev/null
E0127 20:21:43.410431   89307 main.go:42] DeleteKeyspace(commerce) error: rpc error: code = Unknown …
```
=> [vtctldclient] Set `SilenceErrors` on the root command, so we don't double-log

docker/k8s/vtexplain/Dockerfile
Add `VT_BASE_VER` to vtexplain so that we can build release versions of the docker image.
Use `lite` as base for vtctlclient because `k8s` image ~is no longer being updated.~ has not been updated since 8.0.
#7399 
#7401 
=> Fix Dockerfiles for vtexplain and vtctlclient

go/test/endtoend/vtgate/reservedconn/udv_test.go, go/vt/vttablet/tabletserver/planbuilder/plan.go, go/vt/vttablet/tabletserver/planbuilder/testdata/exec_cases.txt, go/vt/vttablet/tabletserver/planbuilder/testdata/pool_unsafe_cases.txt, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/query_executor_test.go
Fixed the Set statements to build the query using bind vars passed.
Also, disable the use of set statements outside of reserved connections.
- Fixes https://github.com/vitessio/vitess/issues/7375
=> Fix Set Statement in Tablet when executed with bindvars

go/test/endtoend/vtgate/system_schema_test.go, go/vt/vtgate/engine/route.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/planbuilder/testdata/from_cases.txt
- Fixes https://github.com/vitessio/vitess/issues/7408
=> Fix information_schema query with system schema in table_schema filter

go/vt/sysvars/sysvars.go
- Fixes https://github.com/vitessio/vitess/issues/7351
=> added information_schema_stats_expiry to allowed list of set vars

go/vt/vtgate/executor.go, go/vt/vtgate/executor_stream_test.go
- Fixes https://github.com/vitessio/vitess/issues/7447
=> Olap error message fix

go/vt/vtctl/reparentutil/replication.go, go/vt/vtctl/reparentutil/replication_test.go, go/vt/vtctl/reparentutil/util.go, go/vt/vtctl/reparentutil/util_test.go, go/vt/wrangler/reparent.go
This PR extracts some reparent code from methods on the `Wrangler` struct to top-level functions, and adds tests for them. I'm doing this in advance to allow some code sharing between the legacy and new vtctld grpc APIs, to make those diffs smaller and less risky.
**Important**: This PR also contains a bugfix in `FindValidEmergencyReparentCandidates` (formerly `(*Wrangler).findValidReparentCandidates`) that would cause a non-deterministic panic, depending on what order the
`replicationStatusMap` is first iterated over in. The panic happens as follows:
Assume you have 2 tablets in the status map. One tablet has a GTID-based relay log position, and the other has a non GTID-based relay log position.
If the GTID tablet comes first, then `isGtidBased` gets set to a pointer to true, and when we …
=> [vtctld / wrangler] Extract some reparent methods out to functions for shared use between wrangler and VtctldServer

go/vt/vttablet/tabletmanager/vreplication/engine.go, go/vt/vttablet/tabletserver/gc/tablegc.go
In https://github.com/vitessio/vitess/pull/7364 we introduced [client.go](https://github.com/vitessio/vitess/pull/7364/files#diff-1e881a210b1fd5f748a4952b1b5cc5ad9d1b60c35f0fe53ab90c071b5174d6c3), a throttler client, which we then used in tabletserver/tablegc, vreplication/engine and vstreamer/engine.
In the first two, I used the wrong check type: `ThrottleCheckSelf`, where in fact I should have used `ThrottleCheckPrimaryWrite` because table GC and vreplication/engine both _write to a primary_ and should therefore consider replication lag on the shard. This must have been a copy+paste mistake.
The reason endtoend tests didn't catch this is that we don't have the capacity to run replicas on our vreplication tests, and so we only have primaries; in that scenario both types of checks …
=> Throttler: fix to client usage in vreplication and table GC

web/vtadmin/src/components/routes/Clusters.tsx, web/vtadmin/src/components/routes/Debug.tsx, web/vtadmin/src/components/routes/Gates.tsx, web/vtadmin/src/components/routes/Keyspaces.tsx, web/vtadmin/src/components/routes/Schemas.tsx, web/vtadmin/src/components/routes/Tablets.tsx, web/vtadmin/src/hooks/useDocumentTitle.ts
You'd _think_ an effectively two-line change to update the `document.title` wouldn't require 30 lines of commentary and caveats... and _yet_. 
N/A
**N/A**
=> [vtadmin-web] Set document.title from route components

go/cmd/vtctldclient/cli/cobra.go, go/cmd/vtctldclient/internal/command/backups.go, go/cmd/vtctldclient/internal/command/cells.go, go/cmd/vtctldclient/internal/command/doc.go, go/cmd/vtctldclient/internal/command/keyspaces.go, go/cmd/vtctldclient/internal/command/reparents.go, go/cmd/vtctldclient/internal/command/schema.go, go/cmd/vtctldclient/internal/command/shards.go, go/cmd/vtctldclient/internal/command/tablets.go, go/cmd/vtctldclient/internal/command/vschemas.go
Also includes a lot of documentation about why we want this thing, which
hopefully is clear!
- #7147 
=> Provide named function for squashing usage errors; start using it

.github/workflows/cluster_endtoend_11.yml, .github/workflows/cluster_endtoend_12.yml, .github/workflows/cluster_endtoend_13.yml, .github/workflows/cluster_endtoend_14.yml, .github/workflows/cluster_endtoend_15.yml, .github/workflows/cluster_endtoend_16.yml, .github/workflows/cluster_endtoend_17.yml, .github/workflows/cluster_endtoend_18.yml, .github/workflows/cluster_endtoend_19.yml, .github/workflows/cluster_endtoend_20.yml, .github/workflows/cluster_endtoend_21.yml, .github/workflows/cluster_endtoend_22.yml, .github/workflows/cluster_endtoend_23.yml, .github/workflows/cluster_endtoend_24.yml, .github/workflows/cluster_endtoend_26.yml, .github/workflows/cluster_endtoend_27.yml, .github/workflows/cluster_endtoend_vreplication_basic.yml, .github/workflows/cluster_endtoend_vreplication_cellalias.yml, .github/workflows/cluster_endtoend_vreplication_multicell.yml, .github/workflows/cluster_endtoend_vreplication_v2.yml, .github/workflows/unit_test_mariadb101.yml, .github/workflows/unit_test_mariadb102.yml, .github/workflows/unit_test_mariadb103.yml, .github/workflows/unit_test_mysql57.yml, .github/workflows/unit_test_mysql80.yml, .github/workflows/unit_test_percona56.yml, test/ci_workflow_gen.go, test/config.json
* Added descriptive names for vreplication shards
* Moved v2 e2e test to its own shard 
I did this because it was failing often while trying to create a replica, presumably running out of resources. I thought it might be because there were other tests running. However I am still seeing this happening while CI ran for this PR.
=> CI Tests: Add descriptive names to vrep shards. Update test generator script

go/test/endtoend/vtgate/misc_test.go, go/vt/sqlparser/analyzer.go, go/vt/sqlparser/ast.go, go/vt/sqlparser/parse_test.go, go/vt/sqlparser/rewriter.go, go/vt/sqlparser/sql.go, go/vt/sqlparser/sql.y, go/vt/vtgate/executor_test.go, go/vt/vtgate/planbuilder/builder.go, go/vt/vtgate/planbuilder/explain.go, go/vt/vtgate/planbuilder/other_read.go, go/vt/vtgate/planbuilder/testdata/other_read_cases.txt, go/vt/vttablet/sandboxconn/sandboxconn.go, go/vt/vttablet/tabletserver/planbuilder/permission.go, go/vt/vttablet/tabletserver/planbuilder/plan.go, go/vt/vttablet/tabletserver/planbuilder/testdata/stream_cases.txt, go/vt/wrangler/vexec_test.go
- Fixes https://github.com/vitessio/vitess/issues/5907
=> Describe table to route based on table name and qualifier

go/vt/concurrency/error_group.go, go/vt/concurrency/error_group_test.go
=> [concurrency] Add guard against potentially blocking forever in ErrorGroup.Wait() when NumGoroutines is 0

docker/k8s/vtexplain/Dockerfile
Fix vtexplain Dockerfile so that it can be built off a branch instead of always using latest.
We don't really need this change on the main branch, but we will need it on the next release branch, so it needs to go in.
#7401 
=> Add VT_BASE_VER to vtexplain/Dockerfile

docker/k8s/vtctlclient/Dockerfile
Install curl into the docker image vitess/vtctlclient. That way,
for clients using this container, not only can they interact
with vtctld via vtctlclient, but they can also interact with
vtctld and other Vitess components via their HTTP APIs, and can
also interact with the Kubernetes API server over HTTP.
Signed-off-by: Jordan Moldow <jmoldow@alum.mit.edu>
When tested with Docker Desktop for Mac, Docker version 20.10.2,
using the command
docker build --compress -f Dockerfile -t "vitess/vtctlclient:latest" .
the original Dockerfile generates an artifact that is 94.4MB
(according to docker image ls), whereas the new Dockerfile
generates a 102MB image, about an 8% increase in the image's
size.
I would understand if the team would rather not include this dependency in this slim image. …
=> docker vitess/vtctlclient: Install curl

go/stats/histogram.go, go/stats/hooks.go, go/stats/statsd/statsd.go, go/stats/statsd/statsd_test.go, go/stats/timings.go
This PR adds a hook interface for different backend to register timing and histogram metrics.
The main motivation comes from the integration with statsd: 
the statsd API for timing / histogram takes a name and value, and it will aggregate the percentile metrics for us. This makes it really hard to parse the histogram data from vitess as latency in statsd. 
We currently just represent them as a plain gauges with bucket suffix - this is not a very helpful metrics to understand the latency performance.
This PR adds a statsdHook, different stats backend can choose to add different hooks for timing and histogram, and when we add timing / histogram, Vitess will also try to invoke the hook function as well. 
**One caveat**: this setup only applies to …
=> Add hook for statsd integration

go/vt/sqlparser/ast.go, go/vt/sqlparser/parse_test.go
Removes printing of ENFORCED word so that statements remain compatible with mysql 5.7
Fixes #7456
=> Removes printing of ENFORCED word so that statements remain compatible with mysql 5.7

go/mysql/fakesqldb/server.go, go/mysql/flavor.go, go/mysql/flavor_filepos.go, go/mysql/flavor_mariadb.go, go/mysql/flavor_mariadb_binlog_playback.go, go/mysql/flavor_mariadb_test.go, go/mysql/flavor_mysql.go, go/mysql/flavor_mysql_test.go, go/mysql/schema.go, go/vt/vtexplain/vtexplain_vttablet.go, go/vt/vttablet/tabletserver/connpool/dbconn.go, go/vt/vttablet/tabletserver/query_engine_test.go, go/vt/vttablet/tabletserver/query_executor_test.go, go/vt/vttablet/tabletserver/schema/engine.go, go/vt/vttablet/tabletserver/schema/engine_test.go, go/vt/vttablet/tabletserver/schema/load_table.go, go/vt/vttablet/tabletserver/schema/load_table_test.go, go/vt/vttablet/tabletserver/schema/main_test.go, go/vt/vttablet/tabletserver/schema/schema.go, go/vt/vttablet/tabletserver/schema/schematest/schematest.go, go/vt/vttablet/tabletserver/tabletserver_test.go
Adds more information per table in the exposed tablet metrics. They now include `FileSize` and `AllocatedSize`.
From the [mysql docs](https://dev.mysql.com/doc/refman/5.7/en/information-schema-innodb-sys-tablespaces-table.html):
> FILE_SIZE
> The apparent size of the file, which represents the maximum size of the file, uncompressed. This column pertains to the InnoDB transparent page compression feature.
> 
> ALLOCATED_SIZE
> The actual size of the file, which is the amount of space allocated on disk. This column pertains to the InnoDB transparent page compression feature.
We do this by extending the query we already use to keep track of tables on the server so it returns more data.
- Query Serving
=> Publish table size on schema 

go/vt/vtgate/engine/primitive.go, go/vt/vtgate/executor.go, go/vt/vtgate/executor_scatter_stats.go, go/vt/vtgate/logstats.go, go/vt/vtgate/queryz_test.go, go/vt/vtgate/resolver.go, go/vt/vtgate/vcursor_impl.go, go/vt/vttablet/tabletserver/cached_size.go, go/vt/vttablet/tabletserver/query_engine.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/queryz.go
The mutexes that were guarding the 'stats' section of plans in vtgate
and vttablet were not being properly obeyed. A lot of the code was
accessing the stats without acquiring the mutex first, mostly because
there is no global consistency requirement between all the fields of the
stats. Because of this, remove the Mutexes from both plans and switch to
using Atomic operations to handle the stats fields. This reduces the
sizes of the plans on cache and improves the accuracy of our memory
usage metrics, since we do not have accurate size calculations for mutex
objects, as they're foreign to the project.
=> plan: remove mutexes

docker/vttestserver/Dockerfile.mysql57, docker/vttestserver/Dockerfile.mysql80, go/vt/vttest/vtprocess.go
Exposes the `-mysql_server_version` parameter in `vttestserver`, and changes the `vitess/vttestserver` container images to set it appropriately.
- Fixes #7470 
N/A - only impacts new `vttestserver` runs
=> Enable -mysql_server_version in vttestserver, and utilize it in vttestserver container images

go/vt/vtadmin/api_test.go, go/vt/vtctl/grpcvtctldserver/server_test.go, go/vt/vtctl/grpcvtctldserver/testutil/util.go, go/vt/vtctl/reparentutil/emergency_reparenter.go, go/vt/vtctl/reparentutil/emergency_reparenter_test.go, go/vt/wrangler/reparent.go
Mostly what it says in the title. I'll follow up with a `PlannedReparenter` PR soonish to do the same thing to that set of functionality.
This for increasing test coverage on the ERS code as well as to set us
up for code reuse between the new vtctld and legacy vtctl RPCs in a
future PR.
- #7428 
=> [vtctld/wrangler] Extract `EmergencyReparentShard` logic to dedicated struct and add unit tests

web/vtadmin/package-lock.json, web/vtadmin/package.json, web/vtadmin/src/components/dataTable/DataTable.tsx, web/vtadmin/src/components/dataTable/PaginationNav.module.scss, web/vtadmin/src/components/dataTable/PaginationNav.test.tsx, web/vtadmin/src/components/dataTable/PaginationNav.tsx, web/vtadmin/src/components/routes/Clusters.tsx, web/vtadmin/src/components/routes/Gates.tsx, web/vtadmin/src/components/routes/Keyspaces.tsx, web/vtadmin/src/components/routes/Schemas.tsx, web/vtadmin/src/components/routes/Tablets.tsx, web/vtadmin/src/hooks/useURLPagination.test.tsx, web/vtadmin/src/hooks/useURLPagination.ts, web/vtadmin/src/hooks/useURLQuery.test.tsx, web/vtadmin/src/hooks/useURLQuery.ts, web/vtadmin/src/index.css, web/vtadmin/tsconfig.json
:sparkles: Staged at http://vtadmin.puppy.software, with a modified `DEFAULT_PAGE_SIZE` of 5 to show the pagination. :) 
Changes in this PR:
- Adds a DataTable component. At the moment, this only handles pagination. This will become more... robust.
- Adds a couple of hooks for working with URL query parameters: `useURLQuery` and `useURLPagination`. Plus, lots of tests. 
I've yet to spend much (any) time worrying about memoization or performance -- I'll do a performance pass when we have filtering, loading state, etc. in place. 
I also pinky-promise that I will write some sort of (heavy scare quotes) "best practices" doc around testing. It's wonderfully easy... but not necessarily straightforward. 😈 …
=> [vtadmin-web] Add DataTable component with URL pagination

go/vt/vtctl/vtctl.go, go/vt/wrangler/materializer.go, go/vt/wrangler/materializer_test.go, go/vt/wrangler/resharder.go, go/vt/wrangler/resharder_test.go, go/vt/wrangler/workflow.go
Details in the related issue https://github.com/vitessio/vitess/issues/7452
=> MoveTables/Reshard: add flags to start workflows in a stopped state and to stop workflow once copy is completed

dev.env, go/cache/cache.go, go/cache/ristretto/bloom/bbloom.go, go/cache/ristretto/bloom/bbloom_test.go, go/cache/ristretto/cache.go, go/cache/ristretto/policy.go, go/mysql/fakesqldb/server.go, go/vt/vttablet/endtoend/config_test.go, go/vt/vttablet/endtoend/queries_test.go, go/vt/vttablet/tabletserver/query_engine.go, go/vt/vttablet/tabletserver/query_engine_test.go, go/vt/vttablet/tabletserver/tabletenv/config_test.go, go/vt/vttablet/tabletserver/tabletserver.go
Some bug fixes, refactorings and more benchmarks for the LFU implementation. Getting it in better shape before we switch to it by default.
- https://github.com/vitessio/vitess/pull/7439
=> LFU Cache Fixes

go/test/endtoend/preparestmt/stmt_methods_test.go, go/vt/vtgate/executor.go, go/vt/vtgate/executor_select_test.go
Fixes #7379 
Some queries need extra bindvars injected before executing. The error here was that for the field type query during `PREPARE`, we were not setting all the required bindvars.
Signed-off-by: Andres Taylor <andres@planetscale.com>
=> make sure to add necessary bindvars when preparing queries

go/vt/vtctl/reparentutil/emergency_reparenter.go, go/vt/vtctl/reparentutil/emergency_reparenter_test.go, go/vt/vtctl/reparentutil/replication.go, go/vt/vtctl/reparentutil/replication_test.go
This introduces two background goroutines and contexts derived from
`context.Background()` to poll and signal for (1) at least one replica
finished successfully and (2) all replicas finished, regardless of
status, respectively.
The overall `promotePrimary` function returns error conditions based on
which of those contexts gets signaled first. We still fail if
`PromoteReplica` fails, which gets checked first, but this covers the
case where we're not running with semi-sync, and none of the replicas
are able to reparent even if the new primary is able to populate its
reparent journal (in the semi-sync case, if 0 replicas succeed to
`SetMaster`, than the primary will fail to `PromoteReplica`, so this was
already covered there).
Fixes #7480  …
=> [reparentutil / ERS] confirm at least one replica succeeded to `SetMaster`, or fail

go/test/endtoend/cluster/cluster_process.go, go/test/endtoend/cluster/topo_process.go, go/test/endtoend/topotest/consul/main_test.go, go/test/endtoend/topotest/etcd2/main_test.go, go/test/endtoend/topotest/zk2/main_test.go, go/test/endtoend/vtgate/unsharded/main_test.go, go/vt/srvtopo/resilient_server.go, test.go, test/config.json
=> Fix for Query Serving when Toposerver is Down

go/vt/servenv/pprof.go, go/vt/servenv/pprof_test.go, go/vt/servenv/servenv.go
The current `servenv` package provides some knobs to enable _some_ of the profiling options in the Go runtime (but not all of them). In order to fully cover all the use cases that we'll require for profiling Vitess, I've decided to implement an aggregated `-pprof` flag with a comprehensive syntax, instead adding more one-off flags to `servenv`. The new flag handles all the existing profile options + all the others that are available in the Go runtime, and allows configuring the output path of the profiles.
We're hoping to wire up this new flag to @frouioui's new benchmarking implementation. 
=> servenv: provide a global flag for profiling

go/vt/sqlparser/parse_table.go, go/vt/sqlparser/parse_table_test.go
On Vschema Generation we parse the table and it did not handled reserved and non-reserved keywords.
- Fixes https://github.com/vitessio/vitess/issues/7371
=> Fix table parsing on VSchema generation

go/vt/mysqlctl/backup.go
Add metrics to track backup/restore operations duration.
N/A
Before
```
vitess@47039963e297:/vt/src/vitess.io/vitess/examples/local$ curl -i -s localhost:15101/metrics | grep vttablet_backup
vttablet_backup_duration_seconds 0
```
```
vitess@47039963e297:/vt/src/vitess.io/vitess/examples/local$ vtctlclient Backup zone1-0000000101
I0218 12:55:41.952392   48318 main.go:67] I0218 12:55:41.951644 backup.go:163] I0218 12:55:41.947789 builtinbackupengine.go:141] Hook: , Compress: true
I0218 12:55:41.952878   48318 main.go:67] I0218 12:55:41.951707 backup.go:163] I0218 12:55:41.950990 builtinbackupengine.go:151] getting current replication status
I0218 12:55:41.961514   48318 main.go:67] I0218 12:55:41.960952 backup.go:163] I0218 12:55:41.960720 …
```
=> go/vt/mysqlctl/backup.go: add backup/restore duration stats

go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/traffic_switcher_test.go
This PR fixes two refresh problems during vreplication workflows:
* SrvVSchema was not being rebuilt after DropSources resulting in existing routing rules still being visible to vtgate since vttablets still saw the old rules. This PR updates the SrvVSchema when routing rules are modify.
* When blacklisted tables are updated only the current primary tablet was being refreshed. However this causes a problem if there is a reparenting operation. This PR now refreshes all tablets in the shard.
https://github.com/vitessio/vitess/issues/7477
=> MoveTables: Refresh SrvVSchema (for Routing Rules) and source tablets (for Blacklisted Tables) on completion

go/vt/vttablet/tabletmanager/vreplication/stats.go, test/local_example.sh
Adds a new stat on the `/debug/vars` page to publish state of a stream (Running/Stopped). Looks like:
`"VReplicationStreamState": {"cust2cust_reverse.3": "Running", "cust2cust_reverse.2": "Running"}`
=> VReplication Stats: publish the state of streams 

go/mysql/server.go
This PR adds a new `PreHandleFunc` field to the Listener struct. The
the goal of this hook is to inspect the connection or add a custom
TLS termination. Because  MySQL does TLS termination differently, it'll
allow us to terminate first and then let the handler continue processing
the connection according to the MySQL protocol.
I initially wanted it to make a part of the `Handler` interface, but
that would be a breaking change. If we're ok breaking it, I can make it
part of the handler.
=> mysql/server: add PreHandleFunc hook for connections

.github/workflows/check_runs_analysis.yaml, .github/workflows/cluster_endtoend_upgrade.yml
Two CI tests don't make sense on repositories forked from https://github.com/vitessio/vitess:
- CI upgrade, because the tags `v8.0.0` or `v9.0.0` etc. only exist on `vitessio/vitess`
- check runs analysis, because the `metrics` branch only exists on `vitessio/vitess`
This PR only runs these tests on `vitessio/vitess`.
=> CI: skip some tests on forked repos

go/vt/vtadmin/api_test.go, go/vt/vtctl/endtoend/get_schema_test.go, go/vt/vtctl/grpcvtctldserver/server_test.go, go/vt/vtctl/grpcvtctldserver/testutil/test_tmclient.go, go/vt/vtctl/reparentutil/emergency_reparenter_test.go, go/vt/vtctl/reparentutil/planned_reparenter_test.go
This PR unifies the various mock tmclient implementations I've added for testing different vtctld functions. It also moves us further from a singleton mocking pattern, which will let us parallelize our test suite even further.
- #7058 
=> [vtctld | tests only] testtmclient refactor

go/vt/vtgate/executor_test.go, go/vt/vtgate/planbuilder/show.go, go/vt/vtgate/planbuilder/testdata/show_cases.txt, go/vt/vtgate/planbuilder/testdata/show_cases_no_default_keyspace.txt
- Forward Port https://github.com/vitessio/vitess/pull/7530
=> Show anywhere plan fix to consider default keyspace

go/vt/vtgate/executor_test.go, go/vt/vtgate/planbuilder/show.go, go/vt/vtgate/planbuilder/testdata/show_cases.txt, go/vt/vtgate/planbuilder/testdata/show_cases_no_default_keyspace.txt
Some of the show queries used first stored keyspace from the toposerver and did not acknowledge the default keyspace. The change is to use take default keyspace into consideration.
- 
=> [9.0] Show anywhere plan fix to consider default keyspace

go/vt/vttablet/tabletserver/query_engine_test.go, go/vt/vttablet/tabletserver/query_executor_test.go, go/vt/vttablet/tabletserver/schema/engine.go, go/vt/vttablet/tabletserver/schema/engine_test.go, go/vt/vttablet/tabletserver/schema/main_test.go, go/vt/vttablet/tabletserver/tabletserver_test.go
We want to be able to track how much work the underlying storage has had to do, not just see how much output there's been.
Related Issue: #7372
=> Add innodb_read_rows as vttablet metric

web/orchestrator/public/js/orchestrator.js
Reported for both `vitess` and `orchestrator`, `orchestrator` allows a XSS attack via `orchestrator-msg` param. This PR sanitizes `orchestrator-msg` param.
related orchestrator PR: https://github.com/openark/orchestrator/pull/1313
=> orchestrator: prevent XSS attack via 'orchestrator-msg' params

go/vt/servenv/buildinfo.go, go/vt/servenv/buildinfo_test.go, go/vt/sqlparser/comments.go, go/vt/sqlparser/parse_test.go, go/vt/sqlparser/parser.go, go/vt/sqlparser/token.go, go/vt/sqlparser/token_test.go
Added MySQL Version that the parser would emulate for special comments
Fixes #7482
=> Use the emulated MySQL version for special comments

go/vt/vtgate/scatter_conn.go, go/vt/vtgate/scatter_conn_test.go
When is connection is marked as reserved and not in transaction. If the connection remains ideal for 30 secs (default). It is killed in vttablet, but the VTGate session does not clear this information.
When the user hits a query on the same session, if the error returned from vttablet is `transaction x ended at ...` then VTGate handles this error and recreate the connection with the right properties. 
But if it received `transaction x not found` then it is not handled and the session is not usable. 
The current change handles this scenario as well.
- 
=> Reset Session for Reserved Connection when the connection id is not found

go/cache/ristretto/cache.go, go/vt/vttablet/endtoend/framework/testcase.go, go/vt/vttablet/endtoend/queries_test.go, go/vt/vttablet/tabletserver/query_executor_test.go, go/vt/vttablet/tabletserver/tabletserver.go
`TestQueryExecutorPlans` and `TestQueries` have been intermittently flaky since I introduced the new cache implementation. MY BAD. It's not clear from reading the code, but these tests are run sequentially and expect the results of the previous execution to be in cache, so we need to ensure that the cache has settled before we attempt the next test.
Took me a while to figure out!
=> vttablet: fix flaky tests

go/vt/vtgate/scatter_conn.go, go/vt/vtgate/scatter_conn_test.go
=> [9.0] Reset Session for Reserved Connection when the connection id is not found

web/vtadmin/package.json, web/vtadmin/src/components/TextInput.module.scss, web/vtadmin/src/components/routes/Tablets.module.scss, web/vtadmin/src/components/routes/Tablets.tsx, web/vtadmin/src/util/filterNouns.test.ts, web/vtadmin/src/util/filterNouns.ts, web/vtadmin/src/util/tokenize.test.ts, web/vtadmin/src/util/tokenize.ts
✨ Staging: http://vtadmin.puppy.software/
https://user-images.githubusercontent.com/855595/108375401-ea6b4680-71cf-11eb-8df6-f25e3cd4086b.mov
This is still VERY rough around the edges, but I'm happy with it so far! I feel like this implementation atones for a lot of the sins I committed in our internal prototype. :') It's also super performant, despite not spending any time on performance specifically! 
That said! The _behaviour_ of this also differs significantly from our internal prototype. In a good way, I hope, but you never know! To that end, I'm leaving a lot of the polish for later so we can focus on the functional bits first. 
By "polish", I mean things like:
- Persisting search state in the URL
- Dropdown filters
- …
=> [vtadmin-web] An initial pass for tablet filters

web/vtadmin/package-lock.json, web/vtadmin/package.json, web/vtadmin/src/components/TextInput.tsx, web/vtadmin/src/components/inputs/Label.module.scss, web/vtadmin/src/components/inputs/Label.tsx, web/vtadmin/src/components/inputs/Select.module.scss, web/vtadmin/src/components/inputs/Select.tsx, web/vtadmin/src/components/routes/Debug.module.scss, web/vtadmin/src/components/routes/Debug.tsx
https://user-images.githubusercontent.com/855595/108565302-6f3e8900-72d2-11eb-92e9-55bbb9b425ee.mov
A quick first pass at a Select component using [Downshift](https://github.com/downshift-js/downshift) (which is very good indeed). I expect to refine this a fair amount since I'll be adding other components (Multiselect, Combobox, etc.) that will share a lot of styling + behaviour. But this felt like a good stopping point!
I'll also note that the "Clear selection" button is a still little clunky, since it doesn't play very nicely with Downshift's exceedingly-reasonable-yet-somewhat-aggressive tabindex management. It works fine, but is not keyboard accessible.
Not staged, since https://github.com/vitessio/vitess/pull/7515 is …
=> [vtadmin-web] Add a Select component

go/vt/vtctl/vtctl.go, go/vt/wrangler/keyspace.go, go/vt/wrangler/traffic_switcher.go
This PR changes MigrateServedTypes to refresh both Replicas and Rdonly tablets after every migration. Ran into an issue during a migration in which a replica was promoted to primary but hadn't been refreshed since we initially only refreshed tablets with `servedType`. With the primaries migrated and refreshed but not the replicas, when there is a failover before the replicas have had their state refreshed, the replica will still believe it is in a split state causing it not to serve until RefreshState is done on the host. 
- 
=> Refresh replicas and rdonly after MigrateServedTypes except on skipRefreshState.

go/cache/cache.go, go/cache/cache_test.go
It was just an over-eager check. Unit tests have been introduced
- Fixes https://github.com/vitessio/vitess/issues/7549
=> cache: handle all possible initialization cases

go/vt/vtctl/vtctl.go, go/vt/wrangler/materializer_test.go
PR for #7555
* Add cells and tablet_types parameters
* Also change -cell to cells in CreateVLookupIndex
=> Materialize: Add cells and tablet_types parameters

web/vtadmin/src/components/routes/Tablets.test.tsx, web/vtadmin/src/components/routes/Tablets.tsx, web/vtadmin/src/util/filterNouns.ts
Staged: http://vtadmin.puppy.software/tablets
Three small bugfixes on the tablets page:
- Fixes a bug where filtering by `type:` didn't work, as the row property used `displayType` rather than `type`
- Fixes a bug where some tablet types were displayed incorrectly due to duplicate values in the TabletType enum
- Fixes a bug where tablet sort order was unstable for tablets of the same type; an additional sort on `alias` is added.
- Adds tests for the above. :) 
Ultimately, I think it'd be good to have the API return a readable tablet type string (in addition to, or perhaps instead of the numeric `tablet.type` value). This way, any other callers to `/api/tablets` will see `PRIMARY` instead of `MASTER`, `RDONLY` instead of `BATCH`, etc. 
- N/A
N/A
=> Three small bugfixes in Tablets table around stable sort order, display type lookup, and filtering by type

go/vt/vttablet/endtoend/framework/testcase.go, go/vt/vttablet/endtoend/queries_test.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
This is a small benchmark suite for `vttablet` queries which I've started running to find hotspots.
So far, I found two fixes that are trivial and give a measurable improvement in the flame graphs. `vstreamer` is hot!
=> vttablet: benchmarks and two small optimizations

test/ci_workflow_gen.go
In https://github.com/vitessio/vitess/pull/7419 I accidentally dropped shard `26` from workflow generator. This PR restores it.
I dropped it because I extracted `onlineddl_ghost` test out of `26` and into its own shard. But I missed the fact there was another test, `vitess.io/vitess/go/test/endtoend/recovery/pitrtls`, still using `26`.
Nothing is terribly broken right now: `26` stills runs in CI. It will take someone to re-run `make generate_ci_workflows` to actually remove it. This hasn't happened yet.
=> Restore CI workflow shard 26, accidentally dropped

go/vt/sqlparser/parse_next_test.go, go/vt/sqlparser/parse_test.go, go/vt/sqlparser/token.go
Vitess treats everything after `-- ` as a comment just like MySQL. This means that the query `SET @S = 1--4` is valid on both MySQL and Vitess. Refer to https://dev.mysql.com/doc/refman/8.0/en/ansi-diff-comments.html for MySQL documentation regarding the same
-  Fixes #7580 
=> Corrects the comment handling in vitess

go/tools/asthelpergen/integration/rewriter.go, go/tools/asthelpergen/rewriter_gen.go, go/vt/sqlparser/rewriter.go
When visiting slice elements, we were creating a closure over the index variable, like so:
```go
case *IndexHints:
for x, el := range n.Indexes {
a.apply(node, el, func(newNode, container SQLNode) {
container.(*IndexHints).Indexes[x] = newNode.(ColIdent) // x is closed over
})
}
```
this PR changes these code snippets to be explicit about the parameter, like this:
```go
case *IndexHints:
for x, el := range n.Indexes {
a.apply(node, el, func(idx int) func(SQLNode, SQLNode) {
return func(newNode, container SQLNode) {
container.(*IndexHints).Indexes[idx] = newNode.(ColIdent)
}
}(x))
```
Even though the latter looks a little worse, what with the creation of a function for each element, the benchmarks show a small but significant improvement:
```
name                     old time/op  new …
```
=> Optimise AST rewriting

go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/filter_cases.txt, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/planbuilder/testdata/postprocess_cases.txt, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt, go/vt/vtgate/planbuilder/testdata/wireup_cases.txt, go/vt/vtgate/semantics/analyzer.go, go/vt/vtgate/semantics/analyzer_test.go
Then Gen4 planner is growing, but there is still a lot of query types that are not supported. This PR makes sure to fail the unsupported cases instead of producing bad plans.
Gen4 tracking #7280
- [x ]  Query Serving
No docs are needed.
=> gen4: fail unsupported queries

docker/k8s/Dockerfile, docker/k8s/mysqlctl/Dockerfile, helm/release.sh
The Vitess Connector is using the `vitess/base` docker image as the base image to copy useful binaries, such as `mysqlctl`, `vtctl`, etc. The `vitess/base` docker image is huge (6.56GB). In order to avoid downloading this huge image, this PR creates the `mysqlctl` docker image, so that users can copy `mysqlctl` from this much smaller docker image.
The new docker image `vitess/mysqlctl` should be pushed to DockerHub.
Related Slack discussion: https://vitess.slack.com/archives/C0PQY0PTK/p1612339740175400
=> Add mysqlctl docker image

go/mysql/schema.go, go/tools/asthelpergen/asthelpergen.go, go/tools/sizegen/sizegen.go, go/vt/vtexplain/vtexplain_vttablet.go, go/vt/vttablet/tabletserver/schema/engine.go
This PR add Show Status query to vtexplain so that it no longer throws warnings in the tests and makes asthelpergen, sizegen quite.
- Fixes #7564 
=> Add Show Status query to vtexplain and make asthelpergen/sizegen quiet

go/vt/servenv/pprof.go
This is going to make wiring the profiling to the benchmark system much more straightforward. cc @frouioui 
- 
=> pprof: allow stopping profiling early with a signal

go/vt/vtadmin/api_test.go, go/vt/vtctl/grpcvtctldserver/testutil/util.go
This is a test-code–only change for VtctldServer and VTAdmin to make these recursive test server setups a little nicer to write, and to make doing table-driven tests on arbitrary numbers of vtctlds manageable.
I also added some reuse of a background context to these tests while I was there.
=> [vtadmin/testutil] Add testutil helper to manage the complexity of recursively calling WithTestServer

go/vt/schemamanager/tablet_executor.go, go/vt/vtctl/vtctl.go
This PR introduces `-skip_preflight` flag to `vtctl ApplySchema`. Preflight checks test the sanity of the schema change. As example, if we add a column `c` to a table that already has column `c`, preflight checks will intercept the error and the query never gets sent to the backend tables.
However, preflight checks don't always make sense:
- With online DDL, I could submit migration#1: `add column c`, and migration#2 `add key c_idx(c)`. If migration#1 still runs when I submit migration#2, preflight rejects migration#2. This is counter productive to the online DDL concept.
- On unmanaged setups, preflight may not have the privileges to run, thus becoming impossible to execute.
The new flag `-skip_preflight`, defaults `false` for backwards compatibility, completely disables the use of …
=> ApplySchema: -skip_preflight

go/vt/servenv/pprof.go, go/vt/servenv/pprof_test.go
After running long benchmarks while profiling Vitess, the profiles start to get too big for `go tool pprof` and return an EOF error. To counterattack this issue, we decided to stop recording at any given time by using https://github.com/vitessio/vitess/pull/7594, and without affecting the benchmarks.
However, we also want to control when to start recording. In the case of the benchmarks, we often have long preparation times where we insert and "warm-up" the system before practicing the actual benchmark. This is what this pull request brings: start recording at any given moment based on a received signal (USR1).
cc @vmg 
- https://github.com/vitessio/arewefastyet/issues/53
- https://github.com/vitessio/vitess/pull/7594
=> Addition of waitSig pprof argument to start recording on USR1

docker/lite/Dockerfile.ubi7.mysql57, docker/lite/Dockerfile.ubi7.mysql80, docker/lite/Dockerfile.ubi7.percona57, docker/lite/Dockerfile.ubi7.percona80, docker/lite/install_dependencies.sh
=> Add percona-toolkit (for pt-osc/pt-online-schema-change) to the docker/lite images

go/test/fuzzing/oss_fuzz_build.sh, go/test/fuzzing/parser_fuzzer.go
This PR adds more fuzzers to Vitess. It also renames the existing sqlparser fuzzer and moves that fuzzer into `/go/test/fuzzing` 
Furthermore the oss-fuzz build script is updated to include the added fuzzers.
- 
=> Fuzzing: Add more fuzzers

go/vt/srvtopo/resilient_server_test.go
This test is failing frequently in CI. We can revert this PR once the test is fixed.
#6134 
=> tests: disable flaky test until it can be fixed

go/mysql/conn.go, go/mysql/sql_error.go, go/test/endtoend/vtgate/unsharded/main_test.go, go/vt/sqlparser/parse_test.go, go/vt/sqlparser/parser.go, go/vt/vterrors/state.go, go/vt/vttablet/tabletserver/query_engine_test.go
=> empty statement error code change in sql parsing

go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go, go/vt/vttablet/tabletserver/tabletserver.go
Objective: make both migration progress and ETA accessible to the user.
Initial commits:
This PR adds the column `eta_seconds` to `_vt.schema_migrations` and provides the following initial support:
- Initializes with negative value (negative means "N/A", unknown)
- accepts a `eta=?` query param on `/schema-migration/report-status` (which is called on `gh-ost` and `pt-osc` migrations)
- reports `GH_OST_ETA_SECONDS` in `gh-ost` status hook
TODO/related:
- Depends on this `gh-ost` build: https://github.com/openark/gh-ost/pull/17
- Tracking: #6926 
- - suggested syntax: https://github.com/vitessio/vitess/issues/7604
=> Online DDL: internal support for eta_seconds

go/vt/vtadmin/api.go, go/vt/vtadmin/grpcserver/server.go
What it says in the title.
Then, update vtadmin's API to default to registering itself as SERVING
under the "vtadmin.VTAdminServer" name.
- Closes #7634 
=> [vtadmin] Add support for additional service healthchecks in grpcserver

go/vt/proto/vtadmin/vtadmin.pb.go, go/vt/vtadmin/api.go, go/vt/vtadmin/api_test.go, go/vt/vtadmin/cluster/cluster.go, go/vt/vtadmin/cluster/cluster_test.go, go/vt/vtadmin/cluster/trace.go, go/vt/vtadmin/http/vschemas.go, go/vt/vtadmin/testutil/cluster.go, go/vt/vtadmin/testutil/vtctldclient.go, proto/vtadmin.proto, web/vtadmin/src/proto/vtadmin.d.ts, web/vtadmin/src/proto/vtadmin.js
This PR adds the `GetVSchema` and `GetVSchemas` endpoints to vtadmin-api.
- Closes #7624 
I've canaried this internally and looks good.
=> [vtadmin] vschemas api endpoints

go/mysql/server_test.go
Fixes flaky test failure:
```
--- FAIL: TestListenerShutdown (0.00s)
Error:     server_test.go:250: listening on address '::1' port 40883
Error:     server_test.go:1330: Expected connRefuse delta=1, got 1
FAIL
```
=> tests: reset stat at the beginning of test

go/vt/vtadmin/api.go, go/vt/vtadmin/cluster/cluster.go, go/vt/vtadmin/cluster/discovery/discovery.go, go/vt/vtadmin/cluster/discovery/discovery_consul.go, go/vt/vtadmin/cluster/discovery/discovery_static_file.go, go/vt/vtadmin/vtctldclient/proxy.go, go/vt/vtadmin/vtsql/vtsql.go
This PR wraps a bunch of places where errors happen with additional context around what failed. Because debugging should be less hard.
- Closes #7633 
=> [vtadmin] propagate error contexts

go/vt/vtadmin/api_test.go, go/vt/vtadmin/cluster/cluster_test.go, go/vt/vtadmin/cluster/config_test.go, go/vt/vtadmin/cluster/discovery/discovery_consul_test.go, go/vt/vtadmin/cluster/discovery/discovery_static_file_test.go, go/vt/vtadmin/cluster/discovery/discovery_test.go, go/vt/vtadmin/cluster/discovery/fakediscovery/discovery_test.go, go/vt/vtadmin/cluster/file_config_test.go, go/vt/vtadmin/cluster/flags_test.go, go/vt/vtadmin/credentials/credentials_test.go, go/vt/vtadmin/vtctldclient/config_test.go, go/vt/vtadmin/vtsql/config_test.go, go/vt/vtadmin/vtsql/vtsql_test.go
This PR contains a bunch of miscellaneous refactors to vtadmin tests, namely:
* use of subtests (`t.Run(...)`) in places where it was previously missing
* use of `t.Parallel()` in most places
* fixing a test in `package discovery` that would panic if you tried running it twice, allowing us to run tests now with `-count=N` for N > 1.
* bulk replacement of inlined `context.Background()` calls with a single, shared context per test function
- 
=> [vtadmin] test refactors

go/vt/vttablet/tabletserver/gc/tablegc.go
By way of optimization, our table lifecycle mechanism only purges rows on the primary tablet. It does so by disabling binary logging. Here's the explanation that is in the code:
```
// Disable binary logging, re-enable afterwards
// The idea is that DROP TABLE can be expensive, on the primary, if the table is not empty.
// However, on replica the price is not as high. Therefore, we only purge the rows on the primary.
// This saves a lot of load from the replication stream, avoiding excessive lags. It also
// avoids excessive IO on the replicas.
// (note that the user may skip the PURGE step if they want, but the step is on by default)
```
With this PR, we disable binary logging on best-effort basis. Here's the explanation that is in the PR's code:
```
// However, disabling SQL_LOG_BIN …
```
=> Table GC: disable binary logging on best effort basis

web/vtadmin/src/api/http.ts, web/vtadmin/src/components/App.tsx, web/vtadmin/src/components/Code.module.scss, web/vtadmin/src/components/Code.tsx, web/vtadmin/src/components/routes/Schema.module.scss, web/vtadmin/src/components/routes/Schema.tsx, web/vtadmin/src/components/routes/Schemas.tsx, web/vtadmin/src/hooks/api.ts, web/vtadmin/src/index.css
Pretty straightforward! Only instruments the loading + error handling behaviour for now.
Eventually, this page will show things like:
- Detailed column information
- Vindex data
- Data size + row distribution
- ... and anything else we can think of. 😎 (We have a bigger list.) 
I'll add syntax highlighting later on. I'm not super happy with any of the options + want to be thoughtful about it. 
OK
404
Error
- https://github.com/vitessio/vitess/pull/7596
N/A
=> [vtadmin-web] Add simple /schema view with table definition

go/mysql/mysql_fuzzer.go, go/test/fuzzing/oss_fuzz_build.sh
This PR adds 3 fuzzers for mysql endpoints with amendments to the oss-fuzz build file
- 
=> Fuzzing: Add 3 fuzzers for mysql endpoints

go/test/endtoend/vtgate/unsharded/main_test.go, go/vt/vtgate/executor_dml_test.go, go/vt/vtgate/scatter_conn.go, go/vt/vttablet/sandboxconn/sandboxconn.go, go/vt/vttablet/tabletserver/tx_pool.go
The issue is when the session is in reserved connection and the connection is timeout. 
Next time there is a transaction, that failed with a weird error of tablet alias not matching.
The fix has three parts.
1. If the transaction query fails on a reserved connection do not update the session as the transaction id is not generated.
2. Retry the transaction as this is a new transaction getting created and we can recreate the reserved connection.
3. If the reserved connection is not found on tablet, then it was throwing UNKNOWN error code then the expected code of ABORTED.
=> Fix for reserved connection usage with transaction

go/vt/vtadmin/api.go, go/vt/vtadmin/cluster/cluster.go, go/vt/vtadmin/cluster/discovery/discovery_static_file.go, go/vt/vtadmin/vtadminproto/trace.go, go/vt/vtadmin/vtctldclient/proxy.go, go/vt/vtadmin/vtsql/vtsql.go
This PR does two things:
1. Refactors to support code reuse without over tracing. This is mostly a process of:
a. Move code to private function
b. Do tracing in public function, then call private function.
c. Other internal code that was calling the public function, now calls the private, and we don't double trace (e.g. it would not make sense for `VTGateProxy.Ping` to create a root span called "VTGateProxy.PingContext", which it would if we tried to add tracing there while also having `Ping` call `PingContext`)
2. Instrument tracing through more vtadmin API endpoints.
3. (okay I lied, three things) Add some helpers for common span annotations.
=> [vtadmin] tracing refactor

go/mysql/auth_server_clientcert_test.go, go/mysql/handshake_test.go, go/mysql/server_test.go, go/vt/servenv/grpc_server.go, go/vt/tlstest/tlstest_test.go, go/vt/vtgate/plugin_mysql_server.go, go/vt/vtgate/plugin_mysql_server_test.go, go/vt/vttls/vttls.go
Certificate chain (or Chain of Trust) is made up of a list of certificates that start from a server's certificate and terminate with the root certificate. If your server's certificate is to be trusted, its signature has to be traceable back to its root CA. However in case of Vitess we cannot see the full list of certificates. The change is to pass the full list of certs.
https://github.com/vitessio/vitess/issues/7608
Tested in my local env.
=> add combine TLS certs feature

go/cmd/vtctldclient/internal/command/reparents.go
- 
- @deepthi do you know if this needs to be backported to 9.0?
=> Check error response before attempting to access InitShardPrimary response

go/vt/vttablet/endtoend/transaction_test.go, go/vt/vttablet/tabletserver/planbuilder/builder.go, go/vt/vttablet/tabletserver/planbuilder/plan.go, go/vt/vttablet/tabletserver/planbuilder/testdata/exec_cases.txt, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/query_executor_test.go, go/vt/vttablet/tabletserver/rules/rules_test.go
Currently, we do not allow select query with a lock to be executed on mysql outside of a transaction. In MySQL, this is a lock no-op.
Therefore this change is to no handle this case and treat it like a select query and allow it to be executed outside of transaction. For Vitess also it will be a lock no-op.
- Fixes https://github.com/vitessio/vitess/issues/7571
=> Allow Select with lock to pass through in vttablet

SECURITY.md
Removing Google Groups references from the documented SECURITY process.
- 
=> Update to remove Google Groups

go/vt/discovery/healthcheck.go, go/vt/discovery/healthcheck_test.go, go/vt/discovery/tablet_health_check.go
There are error conditions from a tablet health check that require the healthy tablet list to be updated.
* Tablet host/port is taken over by a different tablet (Fixed in #7176)
* Healthcheck stream returns an error (this can be for any reason including tablet being down) #7472 
* Healthcheck times out #7177 
* These conditions need to be handled for all tablet types (primary/non-primary)
Fixes #7472 
Fixes #7177 
Unit tests were added for each case. For #7472 I also followed the provided testing procedure to reproduce the problem and confirmed that the fix works.
```
mysql> show vitess_tablets;
+-------+----------+-------+------------+---------+------------------+------------------+----------------------+
| Cell  | Keyspace | Shard | TabletType | …
```
=> healthcheck: update healthy tablets correctly when a stream returns an error or times out

go/mysql/binlog_event.go, go/mysql/binlog_event_common.go, go/mysql/binlog_event_filepos.go, go/mysql/replication_constants.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
The binlog streamer does not handle the `transaction_payload_event`, which is sent when binlog compression is used. Currently these events were being silently dropped by VReplication. The copy phase succeeds, but no events are processed while replicating and no error is reported.
With this PR, the VStreamer will error out if it detects binlog compression so that it is reported back to the user. The output of `Workflow Show` would display something like:
```
"Pos": "MySQL56/963a4ef5-8333-11eb-a12a-04ed332e05c2:1-42",
"StopPos": "",
"State": "Error",
"DBName": "vt_customer",
"TransactionTimestamp": 1615554393,
"TimeUpdated": 1615554417,
"Message": "Error: vttablet: rpc error: code = Unknown desc = stream (at source tablet) error @ 963a4ef5-8333-11eb-a12a-04ed332e05c2:1-43: VReplication does …
```
=> VReplication: error out if binlog compression is turned on

go/vt/vttablet/endtoend/config_test.go, go/vt/vttablet/tabletserver/tabletserver.go
@shlomi-noach has detected a flaky test (e.g. https://github.com/vitessio/vitess/pull/7663/checks?check_run_id=2109940790) which I suspect is related to `SchemaChanged` events flushing our cache in the middle of a test. The current version of the test just sleeps for a small while to prevent this, but in practice this may not be enough. A new helper method has been introduced that waits for `T` seconds without any `SchemaChanged` events, because at the start of these tests we can see more than one of these events, which may lag between each other.
=> tabletserver: more resilient wait for schema changes

.github/workflows/check_formatting.yml, .github/workflows/check_make_parser.yml, .github/workflows/check_make_visitor.yml, .github/workflows/cluster_endtoend.yml, .github/workflows/cluster_endtoend_upgrade.yml, .github/workflows/cluster_initial_sharding_multi.yml, .github/workflows/create_release.yml, .github/workflows/docker_test_1.yml, .github/workflows/docker_test_2.yml, .github/workflows/docker_test_3.yml, .github/workflows/e2e_race.yml, .github/workflows/endtoend.yml, .github/workflows/ensure_bootstrap_updated.yml, .github/workflows/golangci-linter.yml, .github/workflows/sonar_analysis.yml, .github/workflows/unit.yml, .github/workflows/unit_race.yml, go/vt/vtgate/planbuilder/filtering.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt
During a refactoring of the planner code in the V9.0.0 release, this query type was broken. This restored the capability to plan IN sub queries on top of other IN sub queries.
(This is a backport of #7682)
=> [9.0] fix regression - should be able to plan subquery on top of subquery

go/vt/vtgate/planbuilder/builder.go, go/vt/vtgate/planbuilder/testdata/flush_cases.txt
- Fixes https://github.com/vitessio/vitess/issues/7607
=> fix flush statement planner

go/test/endtoend/vtgate/unsharded/main_test.go, go/vt/vtgate/executor_dml_test.go, go/vt/vtgate/scatter_conn.go, go/vt/vttablet/sandboxconn/sandboxconn.go, go/vt/vttablet/tabletserver/tx_pool.go
Backport of https://github.com/vitessio/vitess/pull/7646
=> [9.0] Fix for reserved connection usage with transaction

go/vt/vtctl/reparentutil/emergency_reparenter.go
Closes #7691.
Pretty much what it says in the issue description. We're binding that `status` variable on each iteration to the goroutine we're spawning to prevent potentially telling tablet A to wait for tablet B's StopPosition.
- Closes #7691.
- This bug was introduced in https://github.com/vitessio/vitess/pull/7523, which is tagged for 10.0, so this either needs to be backported to that release branch, or just simply pulled in as-normal. I'm not sure what the status there is. @askdba can you advise, and I can do the backport if needed?
=> [reparentutil | ERS] Bind status variable to each goroutine in WaitForRelayLogsToApply

go/vt/servenv/run.go
In #7563, we fixed the panic reported in #7261. However, there is a bug in that PR, as reported by @yangxuanjia [here](https://github.com/vitessio/vitess/pull/7563#issuecomment-800118897).
This PR fixes that bug.
Tested manually that master vttablet shuts down when tablet record is deleted, using local_example (`examples/local`).
#7261  
=> servenv: fix var shadowing caused by short variable declaration

go/vt/vitessdriver/driver.go, go/vt/vtadmin/vtsql/config.go, go/vt/vtadmin/vtsql/config_test.go, go/vt/vtadmin/vtsql/vtsql.go, go/vt/vtadmin/vtsql/vtsql_test.go
This PR fixes a longstanding issue in vtadmin, where if vtadmin had `Dial`-ed a cluster, obtained a connection to a vtgate, and that vtgate was torn down, that cluster would become unusable without restarting vtadmin, and we would see the following, forever:
```
W0317 12:23:29.496680       7 clientconn.go:1191] grpc: addrConn.createTransport failed to connect to {${somehostname} 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp ${someaddr}: connect: connection refused". Reconnecting...
```
To fix this, I've introduced the following:
* An implementation of the `database/sq/driver.Pinger` interface in `vitessdriver`, which just issues a `select 1` query.
* A call to `Ping` during `VTGateProxy.Dial` in the case where the proxy has a non-nil connection. We set …
=> [vitessdriver|vtadmin] Support Ping in vitessdriver, use in vtadmin to healthcheck connections during Dial

examples/local/scripts/vtadmin-up.sh, examples/local/vtadmin/discovery.json, go/vt/vtadmin/vtctldclient/proxy.go, go/vt/vtadmin/vtsql/vtsql.go
This PR does two things:
* Remove our poorly-and-not-actually-supported TLS based grpc connections, by always specifying `grpc.WithInsecure` when dialing vtctlds and vtgates. We'll come back around to make this more robust and flexible.
* Add scripts to run vtadmin-{api,web}, with the local example.
To run, `cd examples/local; ./101_initial_cluster.sh; ./vtadmin-up.sh`, and ctrl-C at any point to tear down the vtadmin components. `401_teardown.sh` is still used to tear down the other components, as per usual.
Example: 
- Closes #7598 
=> [vtadmin] add to local example

go/mysql/conn.go
For each column defination we send a seperate TCP packet containing the MySQL Packet.
This change is to send single TCP packet containing all the MySQL Packets for COM_PREPARE.
This is similar to what MySQL does.
=> COM_PREPARE - Single TCP response packet with all MySQL Packets

go/vt/vtgate/planbuilder/system_tables.go, go/vt/vtgate/planbuilder/testdata/select_cases.txt
Planner to consider `routine_schema` as db column for `information_schema` query
=> more system schema queries

go/vt/vttablet/endtoend/compatibility_test.go, go/vt/vttablet/endtoend/main_test.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tabletserver_test.go
We replace the database name with keyspace name for all the cases expect show queries.
The current change is to replace only if keyspace name is different than database name and also only for select queries when the fields database name is set to underlying database name.
=> Replace the database name in result fields only if needed

go/mysql/mysql_fuzzer.go
This PR adds a requirement to two of the mysql fuzzers that the input length must be greater than 10.
- 
=> Mysql Fuzzer: Add requirement for minimum length of input data

go/tools/asthelpergen/integration/ast_helper.go, go/tools/asthelpergen/integration/integration_rewriter_test.go, go/tools/asthelpergen/integration/test_helpers.go, go/tools/asthelpergen/integration/types.go, go/tools/asthelpergen/rewrite_gen.go, go/vt/sqlparser/ast_funcs.go, go/vt/sqlparser/ast_helper.go, go/vt/sqlparser/ast_rewriting.go, go/vt/sqlparser/ast_rewriting_test.go, go/vt/sqlparser/normalizer.go, go/vt/sqlparser/rewriter_api.go, go/vt/sqlparser/rewriter_test.go, go/vt/sqlparser/walker_test.go, go/vt/vtgate/planbuilder/ddl.go, go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/select.go, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/semantics/analyzer.go, go/vt/vttablet/tabletserver/planbuilder/builder.go, go/vt/wrangler/materializer.go
Removed closures from the ast re-writer and changed re-writer to not return an error.
There is 60%+ improvement on CPU and 15% in memory allocation.
```
name                        old time/op    new time/op    delta
RewriteLargeExpression/1-8     459ns ± 1%     189ns ±10%  -58.87%  (p=0.008 n=5+5)
RewriteLargeExpression/2-8     460ns ± 2%     183ns ±10%  -60.34%  (p=0.008 n=5+5)
RewriteLargeExpression/3-8    8.79µs ± 1%    3.25µs ± 5%  -63.03%  (p=0.008 n=5+5)
RewriteLargeExpression/4-8    3.41µs ± 4%    1.25µs ± 3%  -63.31%  (p=0.008 n=5+5)
RewriteLargeExpression/5-8     400ns ± 2%     171ns ± 1%  -57.26%  (p=0.008 n=5+5)
RewriteLargeExpression/6-8     121µs ± 3%      40µs ± 7%  -67.11%  (p=0.008 n=5+5)
name                        old alloc/op   new alloc/op   delta …
```
=> making fast AST rewriter faster

go/vt/vtadmin/api.go
(I took the easy way out, because the longer-term fix is much more, uh, involved 😅)
This PR adds a synchronization lock to concurrent vtexplain requests. I also took this opportunity to give us some rudimentary insight into how long we're stuck waiting on that lock, as well as to ensure we clean up the execution environment after each request.
- This is the short-term fix described in #7723. I'll tackle the vtexplain refactor later, at which point we can remove this lock.
=> [vtadmin] vtexplain lock

go/vt/vtgate/planbuilder/show.go, go/vt/vtgate/planbuilder/testdata/show_cases_no_default_keyspace.txt
Earlier the query failed with error
```
"show full columns from sys.sys_config"
keyspace sys not found in vschema
```
Fix is to send this to any shard of any keyspace as system schema does not change.
=> show columns query on system schema

go/mysql/mysql_fuzzer.go
This PR adds another fuzzer for the mysql package.
The fuzzer is currently very slow, and I will tweak it a bit to get execution speed up. Nevertheless it will be great to get it merged to track the development through OSS-fuzz as it gets improved.
- 
=> Fuzzing: Add new mysql fuzzer

Makefile, go/cmd/vttestserver/main.go, go/cmd/vttestserver/vttestserver_test.go, go/test/endtoend/vtcombo/vttest_sample_test.go, go/vt/mysqlctl/mycnf_gen.go, go/vt/vttest/environment.go, go/vt/vttest/local_cluster.go, go/vt/vttest/mysqlctl.go
This is an attempt at making the `vttestserver` container honour a persisted data directory.
There were a few changes required to get here and I'm happy to split into multiple PRs:
* Previously, the `vttestserver` binary did not correctly handle interruption signals. As such, the `defer cluster.TearDown()` was not run in `go/cmd/vttestserver/main.go`. I have added a signal handler to correctly run deferred functions.
* The `mysqlctl` binary was previously always run with the `init` subcommand. We now check if the directory provided in `-data_dir` argument already exists, and if so, we use the `mysqlctl start` command instead!
* I have added a `-keep_data` flag to `vttestserver` binary. This will guard all existing invocations from the new codepath and keeps things backwards compatible. …
=> Make vttestserver compatible with persistent data directories

go/test/endtoend/vtgate/misc_test.go, go/vt/vtexplain/testdata/multi-output/selectsharded-output.txt, go/vt/vtexplain/testdata/selectsharded-queries.sql, go/vt/vtgate/planbuilder/filtering.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt
Planning subqueries on top of subqueries was not working as expected. We broke planning of this with the 9.0 release. This is to fix this regression.
#7682 
=> make sure to handle subqueries on top of subqueries

examples/local/README.md, examples/region_sharding/README.md, go.sum
Example README files were pointing to an old file that has been removed.
Note: I'm not sure why the `go.sum` file changed. The `gomod-tidy` CI action should have failed before now on whichever PR caused the changes.
#6072
=> examples: source correct shell script in README

tools/make-release-packages.sh
Adding vtorc binary for build packages. 
https://github.com/vitessio/vitess/issues/7733
- 
=> Add vtorc binary for rpm,deb builds

web/vtadmin/src/hooks/api.ts
A tiny bit of janitorial work pulled out of the demo branch.
This updates vtadmin-web's API hooks to:
- Add a passthrough for react-query `options`, which are not used _yet_ (I know, I know) but establish a pattern that will be used in the future, starting with workflows. 
- Clean up types
- Add a bit of commentary
N/A
N/A
=> [vtadmin-web] Add comments + 'options' parameter to API hooks

go/test/endtoend/vtgate/system_schema_test.go, go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/planbuilder/testdata/sysschema_default.txt, go/vt/vtgate/vcursor_impl.go
If a system schema is selected as a database the dual query fails
```
use `mysql`;
select @@max_allowed_packet from dual;
ERROR: "keyspace mysql not found in vschema"
```
The fix is to send to any keyspace if default is system schema.
=> Fix dual table query when system schema is selected database

web/vtadmin/src/components/routes/Clusters.tsx, web/vtadmin/src/components/routes/Gates.tsx, web/vtadmin/src/components/routes/Keyspaces.tsx, web/vtadmin/src/components/routes/Schemas.tsx, web/vtadmin/src/components/routes/Tablets.module.scss, web/vtadmin/src/components/routes/Tablets.tsx, web/vtadmin/src/index.css
Continuing the theme of "tiny janitorial PRs pulled out of the demo branch", this one adds a common `max-width` class so our infrastructure tables don't look so goofy on wide screens. (Mobile-friendly layout to come... someday... 😊)
I realize this seems like a fair amount of repetition _but_ I don't want to put the max-width in the top-level App component as that ends up being really inflexible when we do want the full width. (Like super long names on detail pages, for example.) 
N/A
N/A
=> [vtadmin-web] Add common max-width to infrastructure table views

go/vt/vtgate/grpcvtgateconn/fuzz_flaky_test.go
This PR adds a fuzzer. 
The actual fuzzing happens at line 105-114. Everything prior to that is setup.
The file is named `_flaky_test.go` because the fuzzer uses some test utils and interferes with unit tests. Naming it `_flaky_test.go` is a recommendation by the CI and removes the breakages of unit tests.
- 
=> grpcvtgateconn: Add fuzzer

go/vt/vttest/environment.go
https://github.com/vitessio/vitess/pull/7718 created a regression wherein the logs directory was not created if its parent directory already existed. The problematic line is at https://github.com/vitessio/vitess/pull/7718/files#diff-7be49867c740adb69b3abbb3d0bbbe92e1d34fcb944d2c5a3efa99f6a1439006R245. This PR fixes that issue.
=> Fixes bug that prevents creation of logs directory

go/vt/mysqlctl/fakemysqldaemon/fakemysqldaemon.go, go/vt/vttablet/tabletmanager/restore.go, go/vt/vttablet/tabletmanager/rpc_backup.go, go/vt/vttablet/tabletmanager/rpc_replication.go, go/vt/wrangler/testlib/backup_test.go
In #7576 we intended to introduce a check in `startReplication` to skip waiting if `disable_active_reparents` is set. The check was incorrect, this PR fixes it.
#7576 breaks the case fixed in #5000, so I have added the necessary tests to ensure this doesn't break again.
Also, call `orc.EndMaintenance` only if the backup/restore process is successful.
#7657
#4426
=> restore: check disable_active_reparents properly before waiting for position update

web/vtadmin/src/api/http.ts, web/vtadmin/src/components/App.tsx, web/vtadmin/src/components/NavRail.tsx, web/vtadmin/src/components/routes/Workflows.tsx, web/vtadmin/src/hooks/api.test.tsx, web/vtadmin/src/hooks/api.ts
- Adds react-query hooks for the `/api/workflows` endpoint
- Updates the NavRail (sidebar) with workflow counts
- Adds a very rudimentary `/workflows` view as a placeholder for later. 
N/A
N/A
=> [vtadmin-web] Add hooks + skeleton view for workflows

go/test/endtoend/preparestmt/main_test.go, go/test/endtoend/preparestmt/stmt_methods_test.go
The issue was reported for rust mysql driver. Checking if the same issue is there on go mysql driver.
- https://github.com/vitessio/vitess/issues/7661
=> added information_Schema query on prepare statement

go/mysql/endtoend/query_test.go, go/test/endtoend/vtgate/misc_test.go, go/test/endtoend/vtgate/unsharded/main_test.go, go/vt/vttablet/endtoend/main_test.go, go/vt/vttablet/endtoend/misc_test.go
- https://github.com/vitessio/vitess/issues/7661
- Reported as bug to MySQL https://bugs.mysql.com/bug.php?id=103155
=> Tests for numeric_precision and numeric_scale columns in information_schema

go/vt/vtgate/executor.go
We need to queries from inadvertently being logged with sensitive data. 
=> make sure to not log sensitive information

go/vt/vtadmin/cluster/cluster.go, go/vt/vtadmin/cluster/cluster_test.go
This fixes a bug in the size aggregation code where, I removed what I thought was a redundant check on `tablet.Tablet.Keyspace`, we could end up picking a tablet in `ks1/-80` when we were looking for `ks2/-80` (because we only compared the shard name).
I also removed a reference to a non-existent variable in a log line while I was here.
- 
=> [vtadmin] GetSchema(s) should always check keyspace field when filtering tablets

web/vtadmin/src/api/http.ts, web/vtadmin/src/components/App.tsx, web/vtadmin/src/components/routes/Workflow.tsx, web/vtadmin/src/components/routes/Workflows.tsx, web/vtadmin/src/hooks/api.test.tsx, web/vtadmin/src/hooks/api.ts
I am once again asking you to ignore this terrible placeholder UI, as the goal of this PR is to add query and caching behaviour for the `/workflow/...` view. 
Here's screenshots anyway:
- https://github.com/vitessio/vitess/pull/7762
N/A
=> [vtadmin-web] Add hooks + skeleton view for workflow details

web/vtadmin/src/components/routes/Schemas.module.scss, web/vtadmin/src/components/routes/Schemas.tsx
A dumb little PR that adds a filter input to the Schemas view, as we have on the Tablets view. 
"Hasty" because this filter input should be extracted into its own component (since we'll use it all over the place) BUT I am impatient and wanted something rudimentary right now as I'm adding table sizes + row counts. :') 
N/A
N/A
=> [vtadmin-web] Add a hasty filter input to the /schemas view

go/vt/vtgate/endtoend/misc_test.go, go/vt/vttest/vtprocess.go
Due to regression in mysql for numeric_precision and numeric_scale for mysql 8.0, we need to disable field caching for the vtcombo server.
https://bugs.mysql.com/bug.php?id=103155
=> [vttest] disable field caching in vttest

go/vt/vtgate/executor_test.go, go/vt/vtgate/planbuilder/builder.go, go/vt/vtgate/planbuilder/ddl.go, go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/vcursor_impl.go, go/vt/vtgate/vtgate.go
Vitess today allowed foreign keys constraint to be sent down to the mysql to be applied on the table. 
In a sharded keyspace, they might not be correctly set and would fail user queries. 
This change is to provide a `-foreign_key` flag on VTGate with default "allow" but with an option to change it to "disallow" 
=> Disallow foreign key constraint on ddl

go.mod, go.sum, go/mysql/mysql_fuzzer.go
Since each iteration spends lots of time setting up the necessary infrastructure, we increase the number of calls to the target API during each iteration.
For performance, we parse each mysql statement in the very beginning and abort if it is invalid sql.
=> mysql_fuzzer: Make more calls during each iteration

go.mod, go.sum
Update moby/term to fix darwin build issue, as described in #7788 
- Fixes #7788
=> update moby/term to fix darwin build issue

go/vt/binlog/binlogplayer/mock_dbclient.go, go/vt/vttablet/tabletmanager/rpc_vreplication.go, go/vt/vttablet/tabletmanager/vreplication/engine.go, go/vt/vttablet/tabletmanager/vreplication/engine_test.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/wrangler/testlib/fake_tablet.go, go/vt/wrangler/testlib/migrate_served_from_test.go, go/vt/wrangler/testlib/migrate_served_types_test.go, go/vt/wrangler/traffic_switcher_env_test.go
Signed-off-by: Malcolm Akinje <makinje@slack-corp.com>
This PR helps solve issue #7585 by allowing `VEngine.Exec` to take a runAsAdmin parameter which will decide whether to use the `Dba` or `Filtered` db user.
- #7585 
=> Use Dba user when Vexec is runAsAdmin

go/bucketpool/bucketpool.go, go/mysql/conn.go, go/mysql/query.go, go/mysql/server.go, go/mysql/streaming_query.go, go/vt/sqlparser/keywords.go, go/vt/vttablet/endtoend/stream_test.go
Hi! Here's a small list of optimizations for `vttablet` and it's connection to the MySQL upstream server.
Brief explanation for each follows:
- `sqlparser: do not lookup keywords if they're too long`: this is going to apply to all SQL parsing in Vitess, also to `vtgate`. It's most noticeable on synthetic queries, like the ones we were using for benchmarking the MySQL client, with large keywords. The idea is this: when building the perfect map for SQL keywords in the parser, we keep track of the longest and the shortest of the keywords. That way, when looking up keywords afterwards, we don't have to bother hashing the potential keyword if it's either shorter than the shortest keyword we know, or longer than the longest.
- `mysql: do not copy bytes that are immediately cast to string`: the …
=> perf: vttablet/mysql optimizations

Makefile, go.sum, go/cmd/vtorc/main.go, go/vt/orchestrator/db/db.go, go/vt/orchestrator/external/golib/sqlutils/sqlutils.go, go/vt/orchestrator/inst/cluster_test.go
We're trying to solve two related issues here:
1. Since the introduction of `vtorc`, all the different binaries have ballooned up in size and dependencies, because the CGo dependencies of `orchestrator` (namely, SQLite) were being propagated through the build.
2. Since newer versions of Go have been released, dynamically linked Go binaries depend on newer versions of `libc` that are not available on older OSSes.
Let's try to fix the two issues at once: first, we stop importing the `go-sqlite` package on `orchestrator`'s `sqlutils` package, because it's being used in other parts of the codebase. We can add the dependency at the root of the binary itself. Secondly, we update our `Makefile` so that CGo is disabled by default for all binaries except `vtorc`.
Building Vitess with CGo disabled …
=> make: build vitess as static binaries by default

go/vt/vttablet/tabletmanager/vreplication/stats.go
Prometheus requires the . (period) separator between dimensions and was dropping the VReplicationErrors metrics due to the use of _ as a delimiter at one place.
- #7804 
=> VReplicationErrors metric: use . as delimiter instead of _ to behave well with Prometheus

Makefile, go.sum, go/cmd/vtorc/main.go, go/vt/orchestrator/db/db.go, go/vt/orchestrator/external/golib/sqlutils/sqlutils.go, go/vt/orchestrator/inst/cluster_test.go
Backport for 10.0 of https://github.com/vitessio/vitess/pull/7795
- 
=> make: build vitess as static binaries by default (10.0 backport)

docker/vttestserver/Dockerfile.mysql57, docker/vttestserver/Dockerfile.mysql80
In both `vttestserver` container images, this sets `max_connections` to 1000 on the underlying MySQL daemons
N/A
N/A
=> docker/vttestserver:  Set max_connections in default-fast.cnf at container build time

go/vt/vtadmin/api_test.go, go/vt/vtadmin/cluster/cluster.go, go/vt/vtadmin/cluster/cluster_test.go
This effectively accounts for corner cases where there is an empty shard which happens to also be marked as serving.
- 
=> Update `GetSchema` filtering to exclude shards where `IsMasterServing` but no `MasterAlias`

docker/lite/install_dependencies.sh, go/vt/vttablet/tabletserver/throttle/throttler.go
since the xtrabackup issue has been resolved.
* Remove comment implying we do not support 8.0
=> Bump MySQL version for docker builds to 8.0.23

web/vtadmin/src/components/dataTable/DataCell.tsx, web/vtadmin/src/components/routes/Clusters.tsx, web/vtadmin/src/components/routes/Gates.tsx, web/vtadmin/src/components/routes/Keyspaces.tsx, web/vtadmin/src/components/routes/Schemas.tsx, web/vtadmin/src/components/routes/Tablets.tsx, web/vtadmin/src/components/routes/Workflows.tsx, web/vtadmin/src/index.css
A couple of straightforward styling changes that I keep re-implementing in my bigger branches. 😎  Figured I should just pull them out into their own thing:
- Adds a DataCell component for consistent styling. (A separate component will make more sense when we do rowspan grouping... I admit right now it's kinda overkill, haha. But! Still convenient.) 
- Renders cluster as secondary text where it "makes sense", which is (for now) when the cardinality of clusters is << the cardinality of whatever the table is rendering. Every cluster has many tablets, for example, so a separate "cluster" column is quite redundant when every row on a page is for the same cluster. Some tables, though, only have one or two columns right now, and in …
=> [vtadmin-web] Add DataCell component

go/vt/binlog/binlogplayer/binlog_player.go, go/vt/vttablet/tabletmanager/vreplication/replicator_plan.go, go/vt/vttablet/tabletmanager/vreplication/replicator_plan_test.go, go/vt/vttablet/tabletmanager/vreplication/stats.go, go/vt/vttablet/tabletmanager/vreplication/table_plan_builder.go, go/vt/vttablet/tabletmanager/vreplication/vcopier.go, go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer.go, go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
For high QPS systems the catchup phase of vreplication workflows is unnecessarily slow. Dmls that are out of the range of the primary key range that has already been copied do not need to be applied to the target db.  To avoid this we would have had to do the arithmetic, of comparing PKs, in code. This is a hard problem mainly due to character collations and also needing to support all possible PK data types as well as composite keys. So currently we do the comparison in sql by adding the range check in a where clause. So all out-of-range rows will result in noops. However these are still being executed on the mysql server using up unnecessary cpu cycles. 
Most schemas have a preponderance of tables with a single column (usually an _id_). …
=> VReplication: optimize the catchup phases by filtering out rows which not within range of copied pks during inserts

web/vtadmin/src/components/NavRail.tsx, web/vtadmin/src/components/routes/Schemas.tsx, web/vtadmin/src/hooks/api.ts, web/vtadmin/src/util/tableDefinitions.test.ts, web/vtadmin/src/util/tableDefinitions.ts
This rewrites the `Schema[] -> TableDefinition[]` logic as a utility function instead of a query hook. This feels like a better separation of concerns (more reusable + easier to test), albeit slightly less convenient (since components need to call, and usually memoize, the `getTableDefinitions` transform).
One note is that `getTableDefinitions` now returns tables that define `table_size` but not `table_definition`. This unearthed a minor bug, https://github.com/vitessio/vitess/issues/7820. The user-facing behaviour is that tables that have a size but no table definition will link to a schema detail route that 404s, even though the table _technically_ exists. As described in #7820, once the bug is fixed the front-end won't need …
=> Rewrite useTableDefinitions hook as getTableDefinitions util

web/vtadmin/src/components/dataTable/DataTable.tsx, web/vtadmin/src/components/routes/Schemas.tsx, web/vtadmin/src/index.css, web/vtadmin/src/util/formatBytes.test.ts, web/vtadmin/src/util/formatBytes.ts
Not much to say here beyond what the title + inline comments mention!
N/A
N/A
=> [vtadmin-web] Display (approximate) table sizes + row count on /schemas view

Makefile
Signed-off-by: Gary Edgar <gary@planetscale.com>
Adds a `cross-build` target which allows you to cross-compile Vitess binaries.
This makes it easier build a slim client tarball (namely, vtexplain + vtctl{,d}client) for OSX from Linux, which we can start including in PlanetScale's biweekly Vitess release. 
- 
=> Makefile: add cross-build target for cross-compiling client binaries

go/stats/export.go, go/stats/export_test.go, go/stats/opentsdb/opentsdb.go, go/stats/statsd/statsd.go, go/stats/statsd/statsd_test.go
Opentsdb and statsd both support common tags that can be attached to all the metrics we emitted. They are useful to identify the latency at keyspace or shard level. However there is no easy way to integrate with that. 
This PR does 2 things:
1. passes the common tags from a comma-separated string and we can tag the stats client directly
2. minor change on opentsdb and statsd init process by adding `InitWithoutServenv` so that we can init them without servenv. This can be useful to reuse the stats backend on other binaries that does not use servenv (e.g., vtorc, vtbench)
- https://github.com/vitessio/vitess/issues/7647
=> Add common tags for stats backends that support it

tools/rowlog/rowlog.go
The vstream skew alignment feature had a breaking change wrt to the  API: it now takes an additional parameter to hold flags that can be specified. This PR updates rowlog to use the new API.
=> Rowlog: Update rowlog for the API change made for the vstream skew alignment feature

go/vt/vtexplain/testdata/multi-output/selectsharded-output.txt, go/vt/vtexplain/testdata/selectsharded-queries.sql, go/vt/vtexplain/vtexplain_vttablet.go
Handle Join query in vtexplain vttablet to mock the data.
- Fixes #6918
=> VTExplain: Add support for multi table join query

go/mysql/server_test.go
Added some sleep and sync around the listener Accept go routine.
- 
=> Attempt to fix TLS Server Flaky test

go/vt/wrangler/wrangler_env_test.go
The wrangler test framework was incorrectly creating a lot of unnecessary logs like shown below. The fake tablets it creates don't always contain a valid QueryService implementation since the tests don't need it. The tablet picker started logging these as warnings  when it was reimplemented resulting in inaccurate logs.
This PR returns a fake queryserivice in such cases so that the picker doesn't log them. Some residual logs are also removed.
```
In WranglerTest dialer
In WranglerTest dialer
In WranglerTest dialer
In WranglerTest dialer
W0413 14:28:22.422144   31135 tablet_picker.go:133] unable to connect to tablet for alias cell:"cell1" uid:10 
W0413 14:28:22.422121   31135 tablet_picker.go:133] unable to connect to tablet for alias …
```
=> Wrangler tests: Return a fake tablet in the wrangler test dialer to avoid tablet picker errors spamming the test logs

misc/git/commit-msg.signoff
This has been bothering me for a while. Our git commit hooks sometimes fail to detect signatures and sometimes don't insert them properly. This PR improves our hooks by using the new `git interpret-trailers` command, which has been available in Git for a couple years now and is designed just for this use case.
- 
=> git: improve signoff detection

examples/are-you-alive/cmd/are-you-alive/main.go
=> correct several wrong words

web/vtadmin/src/components/routes/Schemas.tsx, web/vtadmin/src/components/routes/Tablets.tsx, web/vtadmin/src/hooks/useSyncedURLParam.test.tsx, web/vtadmin/src/hooks/useSyncedURLParam.ts, web/vtadmin/src/util/filterNouns.ts
This adds `useSyncedURLParam`, a hook for synchronizing values (particularly user input) with the URL. The principle here is that every view of VTAdmin should be encoded in the URL, so it's easy to share what you're seeing with someone else. 😎 
https://user-images.githubusercontent.com/855595/114622966-a864fb00-9c7c-11eb-98c4-05eb3690be74.mov
This is a fairly straightforward implementation to get something out the door. I already have some improvements in mind, based on our internal prototype, so I added a fair amount of commentary + unit tests so it's easy to update down the road. 
N/A 
N/A
=> [vtadmin-web] Add useSyncedURLParam hook to persist filter parameter in the URL

go/vt/vttablet/tabletserver/stream_consolidator_test.go
This is a flaky test that @harshit-gangal detected. I'm quite sure this is the proper fix.
Fixes #7832
Fixes #7837 
=> tabletserver: fix flaky test

go/vt/vtadmin/cluster/flags.go
A short-and-sweet one! I noticed we were missing a `return nil` in the case where a flag in the cluster DSN began with `vtctld-`, which meant that we were both correctly sending that flag off to the `VtctldClientProxy` for later parsing, _but also_ falling through and attempting to match it against the discovery regexp (which, thankfully, would promptly fail to match). (Compare this block against the block just above where the flag begins with `vtsql-` to see the difference).
This PR adds in that missing return, and also logs any flag that falls through to the discovery case that does not match the regexp, so we can more easily catch (relatively harmless) issues like this if they happen in the future.
- 
=> Add missing return in `vtctld-*` DSN case, and log any flag that gets ignored

tools/make-release-packages.sh
Add vtctldclient in binary packages.
- #7874  
cc @askdba
=> add vtctldclient to binary directory

web/vtadmin/src/components/routes/Gates.module.scss, web/vtadmin/src/components/routes/Gates.tsx
A small PR to restructure the /gates view + add a filter input. (If... you hadn't noticed, I'm still favoring repetition over (bad) abstraction for these list views on purpose, since they'll diverge in significant ways when we add the dropdown filters and ... I've already made the mistake of poor abstraction in our internal prototype.) 😎 
Before:
After:
N/A
N/A
=> [vtadmin-web] Display more data on /gates view and add filtering

go/vt/vtgate/vtgate.go
- resolves https://github.com/vitessio/vitess/issues/7859
=> log unsupported queries

go/vt/vtadmin/api.go, go/vt/vtadmin/errors/errors.go, go/vt/vtadmin/errors/typed_error.go
=> [vtadmin] Promote ErrNoSchema to a TypedError which returns http 404

.github/workflows/cluster_endtoend_upgrade.yml
I've missed an update to CI's upgrade tests. Updating now to compare vs `v9.0.0`. Release `v10.0.0` is expected in a couple weeks, and we'll update this tests again in two weeks to reflect that release.
=> upgrade tests: test against v9.0.0

go.mod, go.sum, go/cmd/rulesctl/cmd/add.go, go/vt/vttablet/customrule/filecustomrule/filecustomrule.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/rules/cached_size.go, go/vt/vttablet/tabletserver/rules/rules.go, go/vt/vttablet/tabletserver/rules/rules_test.go
Oh shoot - sorry, I did not mean to merge this upstream. I thought the PR was to merge in our fork 🤦 : Reverts vitessio/vitess#7784
=> Revert "[tablet, queryrules] Extend query rules to check comments"

.github/workflows/fossa.yml
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>
=> FOSSA scan added

go/test/fuzzing/oss_fuzz_build.sh
This PR adds two more fuzzers to the build script. 
The coverage build is also deactivated since there are issues with getting it to work.
=> Fuzzing: Fixup oss-fuzz build script

go/mysql/mysql_fuzzer.go
This PR amends a mysql fuzzer. It adds a helper function to create and send packets to the open connection made by the fuzzer.
=> mysql: Small adjustments to fuzzer

go/test/endtoend/vtgate/reservedconn/sysvar_test.go, go/vt/sqlparser/parse_test.go, go/vt/sqlparser/parser.go, go/vt/vtgate/engine/set.go, go/vt/vtgate/executor.go, go/vt/vtgate/executor_dml_test.go, go/vt/vtgate/executor_set_test.go, go/vt/vtgate/executor_test.go, go/vt/vtgate/mysql_protocol_test.go, go/vt/vtgate/planbuilder/bypass.go, go/vt/vtgate/planbuilder/grouping.go, go/vt/vtgate/planbuilder/ordering.go, go/vt/vtgate/planbuilder/queryprojection.go, go/vt/vtgate/planbuilder/set.go, go/vt/vtgate/planbuilder/show.go, go/vt/vtgate/planbuilder/show_test.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/set_cases.txt, go/vt/vtgate/vcursor_impl.go, go/vt/vtgate/vcursor_impl_test.go, go/vt/vttablet/tabletserver/query_engine_test.go
Removes redundant code and updates some error messages.
=> Minor cleanups around errors on the vtgate

config/mycnf/default.cnf, go/bytes2/buffer.go, go/sqltypes/value.go, go/test/endtoend/cluster/cluster_process.go, go/test/endtoend/cluster/vtgate_process.go, go/test/endtoend/cluster/vttablet_process.go, go/test/endtoend/vreplication/cluster.go, go/test/endtoend/vreplication/migrate_test.go, go/test/endtoend/vreplication/performance_test.go, go/test/endtoend/vreplication/resharding_workflows_v2_test.go, go/test/endtoend/vreplication/vreplication_test.go, go/vt/mysqlctl/mycnf.go, go/vt/mysqlctl/mycnf_flag.go, go/vt/mysqlctl/mycnf_gen.go, go/vt/mysqlctl/rice-box.go, go/vt/servenv/pprof.go, go/vt/sqlparser/parsed_query.go, go/vt/vttablet/tabletmanager/vreplication/replicator_plan.go, go/vt/vttablet/tabletmanager/vreplication/vcopier.go
These upcoming weeks I'm going to be working on `vreplication` performance. It's a pretty complex part of Vitess' codebase and it hasn't received a lot of performance tuning in the past so I'm hoping to get up to speed with the implementation and give it some perf attention.
Let's take a look at the changes in this PR, commit by commit:
- `endtoend: improve vreplication tests`: Critically, there are currently no benchmarks for `vreplication`, and it turns out, the system is complex enough (with interdependencies between `vtctl`, `vtgate`, `vttablet` and `mysqld`) that writing microbenchmarks for it is not feasible. To get a starting point for performance tuning instead, I've written some end-to-end performance tests, which give us benchmarking estimates and let us look at the performance …
=> vreplication: performance & benchmarks (table copying)

go/vt/discovery/healthcheck.go, go/vt/discovery/healthcheck_test.go
When VTGate gets an error from the primary tablet connection, it should not just nuke out all the healthy tablets. Because an external reparent process might have already changed the primary tablet.
Instead we should only try to remove the tablet with stream error from the map
- https://github.com/vitessio/vitess/issues/7906
=> Check tablet alias before removing after error stream

go/vt/sqlparser/parse_test.go, go/vt/sqlparser/token.go
Handles the panic when there is an EOF after @ symbol as the tokenizer used to try to find a token after the @ symbol.
=> Panic when EOF after @ symbol

go/vt/vtgate/planbuilder/fuzz.go
This PR adds a fuzzer for vtgate/planbuilder.
An update in the OSS-fuzz build script is required, but I will add that in a separate PR since https://github.com/vitessio/vitess/pull/7782 is currently a blocker for that.
=> Planbuilder: Add fuzzer

go/vt/vtgate/engine/merge_sort.go, go/vt/vtgate/executor_select_test.go, go/vt/vttablet/sandboxconn/sandboxconn.go
Fixes https://github.com/vitessio/vitess/issues/7908
Merge sort is used when VTGate needs to merge the incoming sorted streams. The Bug was around if the callback returns and go routines that are handling those streams needs to be closed.
This is usually achieved by using cancellable context. The new context that was created was not passed to those goroutines so even  the context was cancelled the goroutines were stuck waiting.
=> Memory Sort to close the goroutines when callback returns error 

web/vtadmin/src/api/http.ts, web/vtadmin/src/components/routes/Schema.module.scss, web/vtadmin/src/components/routes/Schema.tsx, web/vtadmin/src/hooks/api.ts, web/vtadmin/src/util/vschemas.test.ts, web/vtadmin/src/util/vschemas.ts
As the title says, this PR introduces vindexes (when defined) to the Schema view. 
Same general caveat that this is just a first pass -- indeed, I just copied this from our internal prototype. 😊  I think there's more we can do here, like link to other tables, add lil tooltips, etc. I'm certainly interested in ideas here, now or whenever. 
Here's what it looks like with local Vitess, for a table with vindexes and for one without:
And here's a slightly more complicated example from the unit tests 🐕 
N/A
N/A
=> [vtadmin-web] Display vindex data on Schema view

go/vt/vtctl/vtctl.go
Quick fix for a minor bug: if you run `vtctl ApplySchema -ddl_strategy=foobar ...`, then `vtctl` must return error because `foobar` is an invalid strategy. Right now it skips the migration but does not report an error.
- Backport of https://github.com/vitessio/vitess/pull/7923
=> vtctl: return error on invalid ddl_strategy

go/test/endtoend/vtgate/keyspace_watches/keyspace_watch_test.go, go/vt/discovery/healthcheck.go, go/vt/vtgate/discoverygateway.go, go/vt/vtgate/vcursor_impl.go, go/vt/vtgate/vtgate.go
When we started working on online DDL support as a first-party action we introduced a dependency in the vtgate to be able to modify the topology. This conflicts with limitations enforced by a [KeyspaceFilteringServer](https://github.com/vitessio/vitess/blob/master/go/vt/srvtopo/keyspace_filtering_server.go#L39-L45) which has a access to only a subset of the topo.
As a protective measure when attempting to gain access to the Write-enabled topo.Server a filtering server throws an error. Since this happens as part of the vcursor setup to support schema changes all vtgate routing was failing if `-keyspaces_to_watch` was passed to the vtgate.
I fixed this, added a new endtoend integration test to prevent future regressions, and updated how we deal with the flag value to more closely match an …
=> Fix + integration test for `keyspaces_to_watch` routing regression [fixes #7882]

tools/rowlog/rowlog.go
Backporting: Rowlog: Update rowlog for the API change made for the vstream skew alignment feature #7809
=> Backport 7809: Update rowlog for the API change made for the vstream skew alignment feature

go/vt/vtgate/engine/merge_sort.go, go/vt/vtgate/executor_select_test.go, go/vt/vttablet/sandboxconn/sandboxconn.go
=> [10.0] Squashed backport of #7903

go/test/endtoend/vtgate/keyspace_watches/keyspace_watch_test.go, go/vt/discovery/healthcheck.go, go/vt/vtgate/discoverygateway.go, go/vt/vtgate/vcursor_impl.go, go/vt/vtgate/vtgate.go
Cherry-pick from #7873 
#7882 
=> [10.0] Fix for keyspaces_to_watch regression

go/vt/discovery/healthcheck.go, go/vt/discovery/healthcheck_test.go
=> [10.0] Update healthy tablets correctly for primary down

.github/workflows/endtoend.yml, .github/workflows/unit_race.yml, .github/workflows/unit_test_mariadb101.yml, .github/workflows/unit_test_mariadb102.yml, .github/workflows/unit_test_mariadb103.yml, .github/workflows/unit_test_mysql57.yml, .github/workflows/unit_test_mysql80.yml, .github/workflows/unit_test_percona56.yml, test/ci_workflow_gen.go
Revert running unit tests inside docker.
This allows us to add mariadb102 back to the unit test matrix.
#7868 
=> CI: Revert docker change for unit tests from #7868

go/cmd/vtcombo/plugin_grpcvtctldserver.go, go/vt/vttest/environment.go, go/vt/vttest/environment_test.go
1. build and run vttestserver: `make build; ./bin/vttestserver`
2. get gRPC port: `sudo lsof -iTCP -P -sTCP:LISTEN | grep vtcombo | awk '{print $9}' | sort | head -n 2 | head -n 1 | sed 's/.*://'`
3. run client:
```
❯ ./bin/vtctldclient --server "localhost:12592" GetKeyspaces
[
{
"name": "test_keyspace",
"keyspace": {}
}
]
```
- Closes #7894 
=> Add VtctldServer to vtcombo

.github/workflows/cluster_endtoend_tabletmanager_tablegc.yml, go/test/endtoend/tabletmanager/tablegc/tablegc_test.go, test/ci_workflow_gen.go, test/config.json
Fixes https://github.com/vitessio/vitess/issues/7878
=> Fixing flaky endtoend/tablegc tests

web/vtadmin/src/components/routes/Workflows.module.scss, web/vtadmin/src/components/routes/Workflows.tsx
A couple of minor changes to the Workflows view, namely:
- Adds URL-persisted filtering
- Renders the source/target shards for each workflow in the list
Before:
After: 
N/A
N/A
=> [vtadmin-web] Add filtering and source/target shards to Workflows view

go/test/endtoend/onlineddl/singleton/onlineddl_singleton_test.go, go/test/endtoend/onlineddl/vtgate_util.go, go/vt/schema/ddl_strategy.go, go/vt/schemamanager/tablet_executor.go, go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go
Followup to #7785
This PR introduces `ddl_strategy` now supports `-singleton-context` flag.
- `-singleton` rejects a migration if there's any other pending migration
- `-singleton-context` rejects a migration is there's any other pending migration that has a different migration context.
With `-singleton-context`, it is possible to submit multiple migrations which all share the same migration context. For example, the following is allowed:
```
vtctlclient ApplySchema -ddl_strategy="online -singleton-context" -sql "drop table if exists t1; drop table if exists t2; drop table if exists t3;" commerce
```
The above submits three migrations. All three will be accepted. For comparison, running the above with `-singleton` would accept the first migration (`drop table if exists t1`) and reject the …
=> Online DDL: introducing ddl_strategy `-singleton-context` flag

examples/compose/vtcompose/vtcompose.go
Signed-off-by: Zou Yu <zouy.fnst@cn.fujitsu.com>
=> Fix a gofmt warning

go/vt/vtctl/workflow/traffic_switcher.go, go/vt/vtctl/workflow/traffic_switcher_test.go, go/vt/wrangler/stream_migrater.go, go/vt/wrangler/switcher_dry_run.go, go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/traffic_switcher_test.go, go/vt/wrangler/vdiff.go, go/vt/wrangler/workflow.go
This is the first in a series of PRs to make VDiff runnable from the new `grpcvtctldserver` (in order to do that we eventually need the `vdiff` struct to be defined outside of `package wrangler` so that both `wrangler` and `grpcvtctldserver` can use it, so that's where this is headed).
To start, I extracted `buildTargets` as a publicly exported function, and then updated all callsites to work on the new types. These should be functionally equivalent.
In the next PR, I'll be looking at moving parts of `trafficSwitcher` struct to `package workflow`
- #7931 
=> [workflow] extract migration targets from wrangler

doc/releasenotes/10_0_0_release_notes.md
Updated v10.0.0 Release Notes 
This version includes all changes since v10.0RC1
=> v10 GA Release Notes

go/mysql/conn.go, go/mysql/endtoend/query_test.go, go/mysql/query.go, go/mysql/query_test.go, go/mysql/server_test.go, go/mysql/streaming_query.go, go/sqltypes/proto3.go, go/test/endtoend/messaging/message_test.go, go/vt/dbconnpool/connection.go, go/vt/vttablet/tabletserver/throttle/client.go, go/vt/vttablet/tabletserver/vstreamer/planbuilder.go, go/vt/vttablet/tabletserver/vstreamer/resultstreamer.go, go/vt/vttablet/tabletserver/vstreamer/rowstreamer.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
Hi all! This week we're doing performance for the `vreplication` _client_. As discussed on our previous PR, the replication process is already bottlenecked on MySQL insert performance, so any optimizations we perform on the client at this point are not going to show up on wall time, but they're still very relevant because the replicator runs inside of the `vttablet`s, so reducing CPU usage here allows us to serve more queries concurrently with the replication process.
For this round of optimizations, I've simply chipped away at all the warm points in the profile for a `vttablet` client performing replication. Let's break down the individual optimizations in this PR, starting with the whole profile:
I've annotated the warm spots in the profile in green. Let's go through them from left to …
=> perf: vreplication client CPU usage

go/vt/binlog/binlogplayer/mock_dbclient.go, go/vt/vttablet/tabletmanager/vreplication/controller_plan.go, go/vt/vttablet/tabletmanager/vreplication/engine.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletmanager/vreplication/utils.go, go/vt/vttablet/tabletmanager/vreplication/vcopier.go, go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go, go/vt/vttablet/tabletmanager/vreplication/vreplicator.go, go/vt/wrangler/fake_dbclient_test.go, test/local_example.sh
This PR adds a new table to the _vt sidecar database. The `_vt.vreplication_log` table will record certain types of events. To start with we record
* stream creation along with stream parameters
* stream errors 
* state changes
* key workflow steps (currently start and end of the copy phase) (Todo)
```
CREATE TABLE IF NOT EXISTS _vt.vreplication_log (
id BIGINT(20) AUTO_INCREMENT,
vrepl_id INT NOT NULL,
type VARBINARY(256) NOT NULL,
state VARBINARY(100) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
message text NOT NULL,
count BIGINT(20) NOT NULL DEFAULT 1,
PRIMARY KEY (id))
```
The value of the message will usually be a string. In the case of stream inserts it records all the parameters including the …
=> VReplication: add table for logging stream errors, state changes and key workflow steps

docker/vttestserver/run.sh
This adds an environment variable to pass through to vttestserver's `-charset` command-line flag, and defaults it to `utf8mb4`.  This, among other things, enables a portion Prisma's integration test suite that validates certain Unicode support.
#7942
This only changes the vttestserver containers.  @harshit-gangal mentioned in #7942 making it the default in vttablet.  This PR does _not_ do that, so I don't disagree with leaving that issue open if we consider that a requirement.
=> docker/vttestserver/run.sh:  Add $CHARSET environment variable

java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/jdbc/pom.xml, java/pom.xml
Bump SNAPSHOT version to 11.0.0-SNAPSHOT after Vitess release v10
=> java: Bump SNAPSHOT version to 11.0.0-SNAPSHOT after Vitess release v10

go/tools/release-notes/release_notes.go
Signed-off-by: Florent Poinsard <florent.poinsard@outlook.fr>
Changing the way we list items in the release notes template. We were previously using `-`, which is now replaced by `*`. This is done to ease the work on release notes once they are on Goolge Docs.
cc @askdba
=> Modification of the Markdown list format in the release notes template

go/tools/release-notes/release_notes.go, go/tools/release-notes/release_notes_test.go
Add a footer with commit count and list of authors to the generated release notes. 
Example footer for the V10.0 release:
----
The release includes 1487 commits (excluding merges)
Thanks to all our contributors: @AdamKorcz, @Akilan1999, @GuptaManan100, @Johnny-Three, @ajm188, @aquarapid, @askdba, @deepthi, @dkhenry, @doeg, @epk, @eselyavka, @falun, @fatih, @frouioui, @guidoiaquinti, @hallaroo, @harshit-gangal, @hkdsun, @hs0210, @jmoldow, @keweishang, @mcronce, @narcsfz, @rohit-nayak-ps, @setassociative, @shlomi-noach, @sougou, @systay, @tomwilkie, @vamc19, @vmg
----
=> Add commit count and authors to the release notes

go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_state.go, go/vt/vttablet/tabletmanager/tm_state_test.go
Signed-off-by: Guido Iaquinti <giaquinti@slack-corp.com>
Add a new metric in `vttablet` to keep track if the keyspace partition it belongs to is serving or not. This metric can be useful for external systems to automatically enable/disable alerts.
In order to don't add additional watches to the topology service (as we don't want those to linearly scale with the number of vttablets), we refresh the serving keyspace view in TabletManager only when `RefreshFromTopoInfo` is called.
Note: this PR is still a WIP but I'll appreciate an early feedback. 
N/A
N/A
=> vttablet/tabletmanager: add isInSRVKeyspace/isShardServing

go/vt/binlog/binlogplayer/binlog_player.go, go/vt/binlog/binlogplayer/binlog_player_test.go, go/vt/binlog/binlogplayer/mock_dbclient.go, go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/tabletmanager/vreplication/controller.go, go/vt/vttablet/tabletmanager/vreplication/controller_test.go, go/vt/vttablet/tabletmanager/vreplication/engine.go, go/vt/vttablet/tabletmanager/vreplication/engine_test.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletmanager/vreplication/vcopier.go, go/vt/vttablet/tabletmanager/vreplication/vplayer.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go, go/vt/withddl/withddl.go
`_vt.vreplication` has new column, `rows_copied`, which is updated periodically during `vreplication` work, to reflect the actual number of rows written on the target table.
The value is written together with `time_updated`, so it does not get transactionally synced with each copy iteration, it follows closely though, and makes a good estimate.
This will be later used by Online DDL to track Vreplication-based migration progress & ETA. 
- Replaces https://github.com/vitessio/vitess/pull/7963
- Tracking: #6926
=> VReplication: tracking `rows_copied`

web/vtadmin/src/components/dataTable/DataCell.module.scss, web/vtadmin/src/components/routes/Keyspaces.module.scss, web/vtadmin/src/components/routes/Keyspaces.tsx, web/vtadmin/src/util/keyspaces.test.ts, web/vtadmin/src/util/keyspaces.ts
The branch I'm working on to add the Keyspace details view is getting big, so I'm peeling off this PR-sized chonk to add standard URL filtering to the Keyspaces view. 
Important note that filtering keyspaces by "has non-serving shards" will require some changes to how the `filterNouns` function works + is not included this change. 
N/A
N/A
=> [vtadmin-web] Add filtering + shard counts/status to Keyspaces view

web/vtadmin/src/components/pips/ShardServingPip.tsx, web/vtadmin/src/components/routes/Tablets.tsx, web/vtadmin/src/util/tablets.ts
A few more small changes that will come in handy for the Keyspace + Workflow views:
- Extracts some Tablet formatters + other utils to `utils/tablets.ts`
- Displays shard serving status on the Tablets view
Before:
After:
N/A
=> [vtadmin-web] Display shard state on Tablets view + extract tablet utilities 

go/test/endtoend/vtgate/prefixfanout/main_test.go, go/vt/vtgate/engine/fake_vcursor_test.go, go/vt/vtgate/engine/route_test.go, go/vt/vtgate/planbuilder/route.go, go/vt/vtgate/vindexes/cached_size.go, go/vt/vtgate/vindexes/cfc.go, go/vt/vtgate/vindexes/cfc_test.go, go/vt/vtgate/vindexes/vindex.go
The purpose of this vindex is to shard the rows based on the prefix of
sharding key. Imagine the sharding key is defined as (s1, s2, ... sN), a
prefix of this key is (s1, s2, ... sj) (j <= N). This vindex puts the rows
with the same prefix among a same group of shards instead of scatter them
around all the shards. The benefit of doing so is that prefix queries will
only fanout to a subset of shards instead of all the shards. Specifically
this vindex maps the full key, i.e. (s1, s2, ... sN) to a
`key.DestinationKeyspaceID` and the prefix of it, i.e. (s1, s2, ... sj)(j<N)
to a `key.DestinationKeyRange`. Note that the prefix to key range mapping is
only active in 'LIKE' expression. When a column with CFC defined appears in
other expressions, e.g. =, !=, IN etc, it behaves exactly as other …
=> Introduce Concatenated Fixed-width Composite or CFC vindex

go/cmd/vtadmin/main.go, go/vt/vtadmin/api.go, go/vt/vtadmin/http/api.go, go/vt/vtadmin/http/experimental/tablets.go
This PR adds an experimental, http-only endpoint to vtadmin for making passthrough requests to a tablet's `/debug/vars` endpoint.
Example:
```
amason@some-host:~/vitess$ curl -s "${VTADMIN_URL}/api/experimental/tablet/${TABLET_HOSTNAME}/debug/vars | jq '.result.BuildGitBranch' 
HEAD
```
=> [vtadmin] experimental tabletdebug

go/vt/vtctl/workflow/state.go, go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/workflow.go, go/vt/wrangler/workflow_test.go
Even _moar_ refactors! ~~This is the last one before the Big One to move traffic switcher out~~ (I lied, there's one more after this :lolsob:). This one moves out `wrangler.workflowState` to `workflow.State`.
- #7931
=> [wrangler|workflow] Extract `workflowState` and `workflowType` out to `package workflow`

go/vt/vtctl/workflow/vreplication_stream.go, go/vt/wrangler/stream_migrater.go, go/vt/wrangler/stream_migrater_test.go, go/vt/wrangler/switcher_dry_run.go, go/vt/wrangler/traffic_switcher.go
More incremental refactors! This one pulls out the private `vrStream` type to `workflow.VReplicationStream` and also defines a list type to provide the behaviors of `tabletStreamValues`, `tabletStreamWorkflows`, `copyTabletStreams`
- #7931
=> [wrangler|workflow] Extract vrStream type to workflow.VReplicationStream

go/vt/topotools/keyspace.go, go/vt/topotools/routing_rules.go, go/vt/topotools/routing_rules_test.go, go/vt/wrangler/keyspace.go, go/vt/wrangler/traffic_switcher.go
I am moving these to `package topotools` to reuse this code in both
`package grpcvtctldserver` (which wrangler imports) and `package
wrangler`.
- #7931
=> [wrangler|topotools] Migrate `UpdateShardRecords`, `RefreshTabletsByShard`, and `{Get,Save}RoutingRules`

go/vt/vtctl/vtctl.go, go/vt/vtctld/vtctld.go, go/vt/wrangler/schema.go, go/vt/wrangler/schema_test.go, go/vt/wrangler/workflow.go, go/vt/wrangler/workflow_test.go
Signed-off-by: Malcolm Akinje <makinje@slack-corp.com>
This PR adds in vschema validation during creation of a ReshardWorkflow. If any of the source shards have tables in their `_vt` database that are not in the vschema then the creation of the ReshardWorkflow will fail. We will then return which shards failed their vschema checks and what tables caused their respective failures.
#7620
=> VSchema Validation on ReshardWorkflow Creation

go/vt/srvtopo/resilient_server.go
Addresses #8010 ;  allowing defaults to work in more cases, and bringing us somewhat closer to the effective value (infinite) before #7278.  Seems like a reasonable compromise.
=> Increase the default srv_topo_timeout

web/vtadmin/package-lock.json, web/vtadmin/package.json, web/vtadmin/src/components/pips/StreamStatePip.tsx, web/vtadmin/src/components/routes/Workflows.tsx, web/vtadmin/src/index.css, web/vtadmin/src/util/time.ts, web/vtadmin/src/util/workflows.test.ts, web/vtadmin/src/util/workflows.ts
What the title says! This adds timestamps and stream counts to the Workflows view.
Before:
Various afters:
N/A
N/A
=> [vtadmin-web] Display timestamps + stream counts on Workflows view

go/vt/vtgate/planbuilder/ddl.go, go/vt/vtgate/planbuilder/testdata/bypass_cases.txt
If there is destination set on the session it will bypass the DDL planner.
Fixes: https://github.com/vitessio/vitess/issues/8001
=> DDL bypass plan

go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
In a few references in code and in the docs website I found that `Only "in_keyrange" expressions are supported in the where clause` - while that's not true and `vreplication` also supports plain equality comparisons like `WHERE somecol='blah'` (here's [the code](https://github.com/vitessio/vitess/blob/172fac7dec8b11937a4efb26ebf4bedf1771f189/go/vt/vttablet/tabletserver/vstreamer/planbuilder.go#L374); it was shipped as part of https://github.com/vitessio/vitess/pull/5949).
I'd like this to be clearly documented for others.
=> Update vreplicator docs

go/vt/vttablet/tabletmanager/vreplication/stats.go
The vreplication error metric started with a number. Fixed by prefixing with the workflow name. Per prometheus docs the required naming convention is:
```
Label names may contain ASCII letters, numbers, as well as underscores. They must match the regex [a-zA-Z_][a-zA-Z0-9_]*. Label names beginning with __ are reserved for internal use.
```
=> Change vreplication error metric name to start with a string to pass prometheus validations

go/vt/vtgate/engine/set.go, go/vt/vtgate/engine/set_test.go
…system settings value
Rather than returning the error, we will just log the error as the intention for executing the query it to validate the current setting and eventually ignore it anyways. There is no benefit of returning the error back to client.
Fixes https://github.com/vitessio/vitess/issues/7981
=> Ignore the error and log as warn if not able to validate the current system setting for check and ignore case

go/vt/wrangler/vdiff.go, go/vt/wrangler/vdiff_test.go
VDiff takes a long time to run (from several hours to days). We had added logging to show progress in the vtctld log files to give users an ability to monitor liveness of the vdiff run as well as get an idea of when it might complete. The code added used a logarithmic algo so that it should log some output even for small tables. On profiling it turns out to use 5-10% of the total VDiff CPU utilization. As users start running vreplication workflows on huge tables this can add up.
This PR simpifies this by logging only once every 10 million rows. This is perfectly fine for really long running since it should print the logs every few minutes. VDiffs on small tables anyway finish within a few minutes.
=> VDIff: fix performance regression introduced by progress logging 

go/vt/wrangler/vdiff.go, go/vt/wrangler/vdiff_test.go
VDiff compares text columns using the weight_string() of the value. However there are times when weight_string() can return a null value. Per the mysql reference
```
String-valued functions return NULL if the length of the result would be greater than the value of the max_allowed_packet system variable.
```
It is possible that just one of the weight_string(), for source or target is null or both are null, depending on the configuration of the source and target servers. Currently if one is null vdiff detects a mismatch and if both are null then it is considered a match. This is incorrect since, in such cases, vdiff needs to compare the actual data.
This PR detects such a condition and uses a byte compare instead.
See related issue for more details and repro.
Signed-off-by: Rohit Nayak …
=> VDiff: Use byte compare if weight_string() returns null for either source or target

go/vt/vttablet/tabletmanager/vreplication/vcopier.go
* Bug Fix
Several of the vreplication metrics were recently updated to no longer be
correct. Specifically time.Now() is no longer executed when the function
starts and is instead executed when the defer statement is called after the end
of the function.
This updates the metrics to properly execute time.Now() at the start
of the functions.
=> vreplication: fix vreplication timing metrics

go/vt/wrangler/traffic_switcher.go
See #8019 for details.
- Fixes #8019
=> Pass the provided keyspace through to `UpdateDisableQueryService` rather than hard-coding the sourceKeyspace

Makefile
Adds a little script that helps us create the release tags
=> Added release script to the makefile

go/vt/vttablet/tabletserver/livequeryz.go
The link is displayed on the /livequeryz endpoint so there is no need for the
link to be absolute. The fact that this link is absolute currently means that
it does not work when it is behind a proxy like the PlanetScale configuration.
=> livequeryz: livequeryz/terminate link should be relative

go/vt/topo/keyspace.go
I caught this while setting up `errcheck` in our linter, and I'm glad I did!
- @deepthi I'm not sure how to force a failure on a single `GetShard` call (without failing the earlier `GetShardNames` call) in order to write a test case; do you have any ideas/suggestions?
=> Add missing return on a failed `GetShard` call in `FindAllShardsInKeyspace`

go/mysql/binlog_event_rbr.go, go/test/endtoend/vreplication/config.go, go/test/endtoend/vreplication/helper.go, go/test/endtoend/vreplication/unsharded_init_data.sql, go/test/endtoend/vreplication/vreplication_test.go, go/test/endtoend/vreplication/vreplication_test_env.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletmanager/vreplication/table_plan_builder.go, go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go, go/vt/vttablet/tabletserver/vstreamer/planbuilder.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go
For fixed length binary columns, mysql internally pads the values on the right will nulls. However the binlogs contain the original value. This leads to a problem in vreplication workflows if a binary column is used as a sharding key.
During the copy phase the row is read using a mysql select and the column has the padded value. However while replicating we get the unpadded value. This means that we get different keyspace_ids. We found bugs where the copy phase inserted the row in one shard but the update during the catchup phase routed this row to another shard where, of course, the update failed.
The PR pads the value found in the binlog to match the value returned my mysql to fix this issue. …
=> VReplication: Pad binlog values for binary() columns to match the value returned by mysql selects

go/vt/vtgate/engine/merge_sort.go, go/vt/vtgate/executor_select_test.go, go/vt/vttablet/sandboxconn/sandboxconn.go
=> [9.0] Memory Sort to close the goroutines when callback returns error

go/vt/vtgate/engine/fake_vcursor_test.go, go/vt/vtgate/engine/route.go, go/vt/vtgate/engine/route_test.go
Closes https://github.com/vitessio/vitess/issues/7919
=> Scatter errors as warning in olap query

go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go
=> Handle online DDL user creation if we do not have SUPER privs (e.g. AWS Aurora)

go/vt/vttablet/tabletmanager/tm_state_test.go
Signed-off-by: Guido Iaquinti <giaquinti@slack-corp.com>
This is a follow up of #7929 to add an additional test for `func (ts *tmState) Open()` as requested by @rafael [here](https://github.com/vitessio/vitess/pull/7929#discussion_r622267106).
N/A
N/A
=> vttablet/tabletmanager - add additional test for tmstate.Open()

go/test/endtoend/cluster/cluster_process.go, go/test/endtoend/cluster/topo_process.go, go/test/endtoend/topotest/consul/main_test.go, go/test/endtoend/topotest/etcd2/main_test.go, go/test/endtoend/topotest/zk2/main_test.go, go/test/endtoend/vtgate/unsharded/main_test.go, go/vt/srvtopo/resilient_server.go, test.go, test/config.json
=> [9.0] Fix for Query Serving when Toposerver is Down

go/vt/vtgate/engine/set.go, go/vt/vtgate/engine/set_test.go
Rather than returning the error, we will just log the error as the intention for executing the query it to validate the current setting and eventually ignore it anyways. There is no benefit of returning the error back to client.
Fixes #7981
Backport of #8004
=> ignore the error and log as warn if not able to validate the current system settings value

go/vt/mysqlctl/builtinbackupengine.go, go/vt/vttablet/tabletmanager/restore.go, go/vt/vttablet/tabletmanager/rpc_backup.go, go/vt/vttablet/tabletmanager/tm_init.go, go/vt/wrangler/testlib/backup_test.go
When the vttablet flag -disable_active_reparents is set, then vitess should not be managing the mysql level replication.
However, it turns out that this was not being respected by backup/restore.
This PR fixes that by adding checks of the flag before restarting replication after a backup/restore. In terms of backup, this is only applicable to offline backups.
In addition, we put the vttablet into orchestrator maintenance mode during backup/restore. We require replication to be off and we do not want orchestrator noticing that it is off and enabling it again while a backup or restore is in progress.
Backport of #7576
=> Backport: Respect -disable_active_reparents in backup/restore

go/vt/vttablet/onlineddl/vrepl.go
Signed-off-by: Shlomi Noach <2607934+shlomi-noach@users.noreply.github.com>
A small fix. While reviewing some work @fatih was doing  I realized that the way OnlineDDL/Vrepl identifies virtual columns is incorrect. Per documentation: https://dev.mysql.com/doc/refman/8.0/en/show-columns.html, a virtual columns is identified by either `VIRTUAL GENERATED` or `VIRTUAL STORED`.
The existing code only identifies `VIRTUAL GENERATED` columns; this PR identifies both types of virtual columns.
- tracking: #6926
=> VReplication Online DDL: fix classification of virtual columns

go/vt/vtctl/grpcvtctldserver/server.go, go/vt/vtctl/vtctl.go
=> Add RemoteOperationTimeout to both legacy and grpc `ChangeTabletType` implementations.

go/test/endtoend/vreplication/cluster.go, go/test/endtoend/vreplication/vreplication_test.go, go/vt/binlog/binlogplayer/binlog_player.go, go/vt/binlog/binlogplayer/binlog_player_test.go, go/vt/vttablet/tabletmanager/vreplication/engine.go, go/vt/vttablet/tabletmanager/vreplication/vcopier.go, go/vt/vttablet/tabletmanager/vreplication/vplayer.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go, go/vt/vttablet/tabletmanager/vreplication/vreplicator.go, go/vt/wrangler/vdiff.go, go/vt/wrangler/vexec.go, go/vt/wrangler/vexec_test.go, go/vt/wrangler/wrangler_env_test.go, tools/rowlog/rowlog.go
During the replication phase of a workflow the gtid of every transaction is recorded in the `pos` column of the `_vt.vreplication` table so that the target can keep track of their current position with respect to the source. We also have a heartbeat (default 1 second, configurable to a maximum of one minute) that updates the `time_updated` column for a proof-of-life of the stream. 
For long running workflows this can cause a significant increase in the size of binlogs especially in cases where there is a high write QPS or if there have been a lot of reparenting operations increasing the size of each gtid. This problem is accentuated because in the full mode of RBR (which Vitess requires) the gtids are present both in the before and after …
=> VReplication: ability to compress gtid when stored in _vt.vreplication's pos column

go/test/endtoend/vtgate/gen4/gen4_test.go, go/test/endtoend/vtgate/gen4/main_test.go, go/vt/vtgate/planbuilder/select.go, go/vt/vtgate/planbuilder/testdata/memory_sort_cases.txt
This is support for queries which does not have column in the select list but have column in order by clause
like `select col from user order by id`
Related: https://github.com/vitessio/vitess/issues/7280
=> Gen4: Support for order by column not present in projection

go/test/endtoend/vtgate/system_schema_test.go, go/vt/vtgate/engine/route.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/planbuilder/testdata/ddl_cases.txt, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/vindexes/vschema.go, go/vt/vtgate/vindexes/vschema_test.go, go/vt/vtgate/vtgate_test.go
If the information_schema query contains a table and schema both and schema is actual db name different from keyspace name, then the query fails.
```
mysql> use commerce;
Database changed
mysql> select CONSTRAINT_NAME, TABLE_NAME from information_schema.table_constraints where constraint_schema = 'vt_commerce' and table_name = 't';
ERROR 1105 (HY000): keyspace vt_commerce not found in vschema
```
=> System schema query predicate fix

web/vtadmin/src/api/http.ts, web/vtadmin/src/components/App.tsx, web/vtadmin/src/components/routes/VTExplain.module.scss, web/vtadmin/src/components/routes/VTExplain.tsx, web/vtadmin/src/hooks/api.ts
This adds a hasty VTExplain UI that does the 🏆 Absolute Bare Minimum 🏆 _but_ it unblocks some internal work. 
I'll file a bunch of cards under https://github.com/vitessio/vitess/projects/12 for known enhancements (since we've accumulated a bunch on our internal prototype that are relevant here).
N/A
=> [vtadmin-web] The hastiest-ever VTExplain UI

web/vtadmin/README.md, web/vtadmin/package-lock.json, web/vtadmin/package.json
....Hey pal, you ever wanna analyze the size of your bundle?
This adds the very useful [source-map-explorer](https://create-react-app.dev/docs/analyzing-the-bundle-size/), which looks like this: 
N.B. Big lolsob at that 850 KB of generated protobuf files. I'm _hoping_ the fix for that will be some relatively straightforward [protobufjs tweaks](https://github.com/protobufjs/protobuf.js). So I don't forget: https://github.com/vitessio/vitess/projects/12#card-60828184
N/A
N/A
=> [vtadmin-web] Add source-map-explorer util

go/mysql/endtoend/schema_change_test.go, go/vt/vttablet/tabletserver/health_streamer.go, go/vt/vttablet/tabletserver/health_streamer_test.go
Instead of deleting everything and refilling the table on every change, we only remove the rows for the updated tables and fill those in again.
=> Update the schema copy with minimal changes

web/vtadmin/src/hooks/useSyncedURLParam.ts, web/vtadmin/src/hooks/useURLPagination.ts, web/vtadmin/src/hooks/useURLQuery.test.tsx, web/vtadmin/src/util/queryString.ts
Currently, VTAdmin by default parses numeric URL query parameters as numbers. This resulted in unintended behaviour with shard filtering, where filtering by a string like "000" (to, say, find shard `0001-0002`) would be parsed as `0` (no leading zeroes) and would _also_ evaluate as falsey, which caused a host of other unfun side-effects. 
In this screenshot, I tried to filter by "00". Note the `?filter=0` in the URL and the empty text input:
It turns out that _not_ parsing booleans/numbers is the more common VTAdmin use case. The one exception so far is pagination, were we do want `page=1` to parse as an integer. 
Here's what it looks like with the fix:
N/A
N/A
=> [vtadmin-web] Do not parse numbers/booleans in URL query parameters by default

go/vt/discovery/fake_healthcheck.go, go/vt/discovery/healthcheck.go, go/vt/vtgate/legacy_scatter_conn_test.go, go/vt/vtgate/scatter_conn.go, go/vt/vtgate/scatter_conn_test.go, go/vt/vttablet/sandboxconn/sandboxconn.go
If PRS is going on, then Query serving will fail with the recent change in reserved connection fix. Before sending to tablet there was check introduce to see if the tablet is serving and the target has not changed then send the query to vttablet.
This is not true for transaction as we want the query which is in transaction to be sent down to get the transaction completed, also the PRS is waiting for any outstanding transaction to get completed.
So, this change is to remove the logic around it and the reserved connection will reset the shard session only when the error is received from the vttablet and there is no pre-check for it.
---
This is a combination of 3 commits.
* remove precheck of tablet serving and target
* remove the additional logic and return error if queryservice not found …
=> [10.0] Queryservice fix

go/vt/vttablet/endtoend/framework/client.go, go/vt/vttablet/tabletserver/query_executor_test.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tabletserver_test.go, go/vt/vttablet/tabletserver/twopc.go, go/vt/vttablet/tabletserver/tx_engine.go
There was a "deadlock" here if you use semi-sync **and**
twopc during a failover, because we open the twopc
engine first, and it immediately tries to create its 
metadata tables in `_vt`.  On the PRS target, that
then hangs if using semi-sync, and since the code
to do the repointing of the replicas to the new master
sits "behind" the twopc engine open, the PRS would
never complete. 
=> Make TwoPC engine initialization async.

go/vt/schema/online_ddl.go, go/vt/vtgate/engine/cached_size.go, go/vt/vtgate/engine/ddl.go, go/vt/vtgate/executor.go, go/vt/vtgate/executor_ddl_test.go, go/vt/vtgate/planbuilder/builder.go, go/vt/vtgate/planbuilder/ddl.go, go/vt/vtgate/planbuilder/explain.go, go/vt/vtgate/planbuilder/migration.go, go/vt/vtgate/vtgate.go
We add a `-enable_direct_ddl` (bool) flag to `vtgate`. The default is `true`.
It is now possible to disable direct DDL via `vtgate.` If you run `vtgate -enable_direct_ddl=false`, then, for example:
```
$ mysql
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1
mysql> select @@ddl_strategy;
+----------------+
| @@ddl_strategy |
+----------------+
| direct         |
+----------------+
mysql> create table my_test(id int primary key);
ERROR 1105 (HY000): direct DDL is disabled
```
This variable only controls `direct` (non-online) DDLs. As reminder, online DDL can be controlled via `-enable_online_ddl`. It is possible to enable one and disable another, enable both, or disable both.
cc @piki @deepthi @mavenraven
=> Support for vtgate -enable_direct_ddl flag

go/vt/vttablet/onlineddl/executor.go
a bogus (e.g. private) hostname and/or port.
=> Fix ghost/pt-osc in the external DB case where MySQL might be reporting

go/vt/discovery/fake_healthcheck.go, go/vt/discovery/healthcheck.go, go/vt/vtgate/legacy_scatter_conn_test.go, go/vt/vtgate/scatter_conn.go, go/vt/vtgate/scatter_conn_test.go, go/vt/vttablet/sandboxconn/sandboxconn.go
An issue was introduced In a recent fix (#8041) which was a backport of #7879 
Before sending queries to a tablet, #7879 changed the behaviour to check if the tablet is ready to answer, by checking it's ServingStatus and that the tablet type hasn't changed.
If PlannedReparentShard is going on, this check should not be done for transactions in flight.
The vttablet waits for inflight transactions to get commit/rollback i.e. we want queries to existing transaction to be sent down to get the transaction completed, even if the tablet is currently saying it is NotServing.
The test that exposed this issue was already in the code base: go/test/endtoend/tabletgateway/buffer/buffer_test.go became flaky after #7879 was merged.
So, to fix the issue, the pre-check is removed from Gateway when getting …
=> [9.0] Queryservice fix

web/vtadmin/src/components/App.tsx, web/vtadmin/src/components/links/KeyspaceLink.tsx, web/vtadmin/src/components/routes/Keyspaces.tsx, web/vtadmin/src/components/routes/Schema.tsx, web/vtadmin/src/components/routes/Schemas.tsx, web/vtadmin/src/components/routes/Tablets.tsx, web/vtadmin/src/components/routes/Workflow.tsx, web/vtadmin/src/components/routes/Workflows.tsx, web/vtadmin/src/components/routes/keyspace/Keyspace.module.scss, web/vtadmin/src/components/routes/keyspace/Keyspace.tsx, web/vtadmin/src/components/routes/keyspace/KeyspaceShards.test.tsx, web/vtadmin/src/components/routes/keyspace/KeyspaceShards.tsx
This PR adds the foundation for the Keyspace detail view, starting with a listing of shards + tablets.
A caveat: grouping table rows by shard complicates the filtering, since `filterNouns` wasn't written to handle nested properties. For now, "kinda gross but exhaustively commented hacks that work 90% of the time in this one place" seemed a better trade-off than "don't add filtering until we can handle this in a nicely generalized way". (Especially since using a library like https://fusejs.io is a better long-term filtering solution _anyway_ ... who wants to maintain regexes? (Not me!)). I ticketed https://github.com/vitessio/vitess/projects/12#card-60968004 to investigate a more robust solution, when we get time.
Here's what …
=> [vtadmin-web] Add Keyspace detail view

web/vtadmin/src/components/routes/Debug.module.scss, web/vtadmin/src/components/routes/Debug.tsx, web/vtadmin/src/components/tabs/Tab.module.scss, web/vtadmin/src/components/tabs/Tab.tsx, web/vtadmin/src/components/tabs/TabContainer.module.scss, web/vtadmin/src/components/tabs/TabContainer.tsx, web/vtadmin/src/index.css
Tabs! Looks like this:
N/A
N/A
=> [vtadmin-web] Add Tab components

go/vt/vtadmin/errors/typed_error.go
=> [vtadmin-api] Replace magic numbers with `net/http` constants

go/vt/discovery/healthcheck.go, go/vt/discovery/tablet_health_check.go
=> healthcheck: attempt to update primary only if the current tablet is serving

go/vt/mysqlctl/fakemysqldaemon/fakemysqldaemon.go, go/vt/vttablet/tabletmanager/restore.go, go/vt/vttablet/tabletmanager/rpc_backup.go, go/vt/vttablet/tabletmanager/rpc_replication.go, go/vt/wrangler/testlib/backup_test.go
Backport of #7703 
Fixes #8108
=> [9.0] restore: check disable_active_reparents properly before waiting for position update

go/vt/vttablet/tabletmanager/restore.go, go/vt/vttablet/tabletmanager/tm_init.go
This PR adds a new hook called `vttablet_restore_done`, which fires, in a background goroutine, whenever a tablet has finished restoring. In the case where a restore failed, we include the error string in the hook env.
We also now track start/stop time of `restoreDataLocked`, and provide both of those as utc RFC3339 timestamps in the env, as well as the standard Go-formatted duration of `stop - start`.
Finally, I also updated the default `tabletmanager.hookExtraEnv` to include the tablet's keyspace and shard.
<details><summary>No hook</summary>
```
$ cd "$VTROOT"
$ ls | grep vttablet_restore_done
$ cd examples/local && ./101_initial_cluster.sh >/dev/null && cd -
```
Snippet of tablet logs:
```
I0429 22:51:33.071145   30140 metadata_tables.go:72] Populating _vt.local_metadata table... …
```
=> Add `vttablet_restore_done` hook

docker/lite/install_dependencies.sh
Fixes #8140.  Increases image size by < 0.5 MB
=> Add libwww-perl to allow pt-osc wrapper to work in vitess/lite

go/cmd/vttablet/vttablet.go, go/vt/mysqlctl/metadata_tables.go, go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_init_test.go, go/vt/vttablet/tabletmanager/tm_state.go, go/vt/vttablet/tabletmanager/tm_state_test.go
TODO.
This means we call `PopulateMetadataTables` on:
* `(*tmState).ChangeTabletType`
* `(*tmState).RefreshFromTopoInfo`
* `(*tmState).RefreshFromTopo` (via `RefreshFromTopoInfo`)
* `(*tmState).Open`
```
❯ vtctldclient --server "localhost:15999" GetTablets
zone1-0000000100 commerce 0 master SFO-M-AMASON02:15100 SFO-M-AMASON02:17100 [] 2021-05-12T15:48:34Z
zone1-0000000101 commerce 0 replica SFO-M-AMASON02:15101 SFO-M-AMASON02:17101 [] <null>
zone1-0000000102 commerce 0 rdonly SFO-M-AMASON02:15102 SFO-M-AMASON02:17102 [] <null>
mysql> select * from _vt.local_metadata;
+---------------+------------------+-------------+
| name          | value            | db_name     |
+---------------+------------------+-------------+
| Alias         | …
```
=> [tm_state] updateLocked should re-populate local metadata tables to reflect promotion rule changes

.github/workflows/pr-labels.yml
Fixes #8146 
Adding a ci job to fail a PR if it does not have at least one `Component: ...` label and at least one `Type: ...` label.
- https://github.com/vitessio/vitess/issues/8146
=> CI: fail PR if it does not have required labels

go/vt/vttablet/tabletmanager/vreplication/engine.go, go/vt/vttablet/tabletmanager/vreplication/vcopier.go, go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go, go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
VReplication decides to switch from catchup to bulk copy when the replica lag is under a threshold. This was 10 seconds, which could cause a problem under certain circumstances (see https://github.com/vitessio/vitess/issues/8104). 
The default has been increased to a minute and it also been made into a flag `-vreplication_replica_lag_tolerance <seconds>` in case fine tuning is needed. 
The time for which the bulk insert phase runs is currently 1 hour. That can now be changed via a flag `-vreplication_copy_phase_duration <seconds>`. You will not need to modify either of these normally.
https://github.com/vitessio/vitess/issues/8104
=> VReplication Copy Phase: Increase default replica lag tolerance. Also make it and copy timeout modifiable via flags

go/vt/vtctl/workflow/vexec/query_plan.go, go/vt/wrangler/vexec.go
We have users listing workflows frequently using vexec looking for monitoring purposes and the log lines removed in the PR are spamming their logs.
=> VReplication: remove noisy vexec logs

java/example/pom.xml, java/example/src/main/java/io/vitess/example/MysqlJDBCExample.java, java/pom.xml, test/client_jdbc.sh
Added MySQL JDBC driver to test it with Vitess and also shows that @<tablet_type> works in the connection string.
Closes #7916
=> [Java] JDBC mysql driver test

examples/local/scripts/vtadmin-up.sh, go/cmd/vtadmin/main.go, go/vt/vtadmin/http/api.go, go/vt/vtadmin/http/experimental/tablets.go
- Renames flag 'http-tablet-fqdn-tmpl' to 'http-tablet-url-tmpl' (since it requires the protocol)
- Updates the local example to include both `http-tablet-url-tmpl` and `tablet-fqdn-tmpl` flags
<details>
<summary> curl "http://localhost:14200/api/tablets" | jq . </summary>
```json
{
"result": {
"tablets": [
{
"cluster": {
"id": "local",
"name": "local"
},
"tablet": {
"alias": {
"cell": "zone1",
"uid": 100
},
"hostname": "localhost",
"keyspace": "commerce",
"shard": "0",
"type": 1,
"master_term_start_time": {
"seconds": 1621541573
}
},
"state": 1,
"FQDN": "localhost:15100"
},
{
"cluster": {
"id": "local",
"name": "local"
},
"tablet": {
"alias": {
"cell": "zone1",
"uid": 101
},
"hostname": "localhost",
"keyspace": "commerce",
"shard": "0",
"type": 2
},
"state": 1,
"FQDN": "localhost:15101" …
```
=> [vtadmin-api] Rename flag 'http-tablet-fqdn-tmpl' to 'http-tablet-url-tmpl' + update vtadmin flags for local example

examples/local/scripts/vtadmin-up.sh, go/cmd/vtadmin/main.go
=> Add `--tracer` flag to vtadmin and actually start tracing

go/vt/vtgate/planbuilder/jointree_transformers.go, go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt, go/vt/vtgate/planbuilder/testdata/wireup_cases.txt
This pull request adds support for `WHERE col IN (...)` statements in Gen4.
Related to #7280.
=> Gen4: planning Select IN

go/mysql/binlog_event_rbr.go, go/test/endtoend/vreplication/config.go, go/test/endtoend/vreplication/helper.go, go/test/endtoend/vreplication/unsharded_init_data.sql, go/test/endtoend/vreplication/vreplication_test.go, go/test/endtoend/vreplication/vreplication_test_env.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletmanager/vreplication/table_plan_builder.go, go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go, go/vt/vttablet/tabletserver/vstreamer/planbuilder.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go
Backport of : https://github.com/vitessio/vitess/pull/7969
Related Issue: #8080 
=> Backport of 7969 into 10.0

go/tools/astfmtgen/main.go, go/tools/asthelpergen/asthelpergen.go, go/tools/asthelpergen/main/main.go, go/tools/common/common.go, go/tools/sizegen/sizegen.go
During code generation, we were not checking if the loaded packages contained any errors. 
We should only use the input packages if they can load without errors
=> Make sure to only allow codegen when the rest of the code compiles

go/vt/vttablet/tabletmanager/vreplication/engine.go
With a recent change we ended up creating a new stats object for every call to VReplicationExec, as part of creating a new VDBClient. However each stats object also creates a goroutine which never gets cleaned up. In PSDB there is a monitoring call to get a list of all workflows every few seconds. This creates resource starvation due to the number of orphan goroutines that keep running.
This PR fixes this immediate problem by only creating the VDBClient on insert/update/delete and not select. 
In the long term we need to cleanup the goroutines for stats objects that are no longer in scope.
=> VReplicationExec: don't create new stats objects on a select

Makefile
In the 9.0 branch, we are not using the `version.go` file, so it should not be created by the release script
=> Update do_release to work in the 9.0 branch

examples/local/scripts/vtadmin-up.sh, web/vtadmin/src/api/http.ts, web/vtadmin/src/components/App.tsx, web/vtadmin/src/components/links/ExternalTabletLink.tsx, web/vtadmin/src/components/links/TabletLink.tsx, web/vtadmin/src/components/routes/Tablets.tsx, web/vtadmin/src/components/routes/Workflow.tsx, web/vtadmin/src/components/routes/keyspace/KeyspaceShards.tsx, web/vtadmin/src/components/routes/tablet/Tablet.module.scss, web/vtadmin/src/components/routes/tablet/Tablet.tsx, web/vtadmin/src/hooks/api.ts, web/vtadmin/src/react-app-env.d.ts
- Adds a very hasty Tablet view... who doesn't love un-highlighted JSON? 
- Adds links to external tablet pages (i.e., on the tablet itself) when the FQDN build flag is defined
- Adds a feature flag + hooks, etc. for querying the experimental /debug/vars endpoint
I'm not going to include a screenshot since some of debug vars contain machine information. 😎 And.. y'know, it looks like JSON. 
N/A
N/A
=> [vtadmin-web] The hastiest Tablet view (+ experimental debug vars)

go/vt/vtctl/workflow/server.go, go/vt/vtctl/workflow/server_test.go, go/vt/wrangler/materializer.go, go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/traffic_switcher_env_test.go, go/vt/wrangler/traffic_switcher_test.go
What it says in the title. I think long-term that the (newly-named) `CheckReshardingJournalExistsOnTablet` should stop being exported, but we need to access it from package wrangler for now, so I left a TODO comment.
Also, the previous implementation had an unnecessary check on `if !exists` which would always be true, so I removed the check.
[Edit] Oh, also, this is almost certainly going to run into merge conflicts with #8190 so 🤷 I'll just rebase whichever one loses
#7931
=> [workflow] Cleanup wrangler wrappers, migrate `checkIfJournalExistsOnTablet` to package workflow

go/test/endtoend/cluster/topo_process.go, go/test/endtoend/topotest/consul/main_test.go, go/vt/srvtopo/resilient_server.go, go/vt/srvtopo/resilient_server_test.go
This PR fixes an issue that arises when a topo server is unavailable to serve traffic either due to a new election or restart or any other cause. In the case where we find an unknown error, we should not clear the topo cache.
This PR also updates the consul test suite to spawn an actual server and not one using `-dev` option which creates an in-memory server.
Fixes #7191
=> query serving to continue when topo server restarts

docker/vttestserver/run.sh, go/cmd/vttestserver/main.go, go/cmd/vttestserver/vttestserver_test.go, go/vt/vttest/local_cluster.go, go/vt/vttest/vtprocess.go
* Add `-foreign_key_mode`, `enable_online_ddl`, and `-enable_direct_ddl` to `vttestserver`
* Pass all three through to underlying `vtcombo` process
* Add `$FOREIGN_KEY_MODE`, `$ENABLE_ONLINE_DDL`, and `$ENABLE_DIRECT_DDL` to `vttestserver` container image
N/A
N/A
=> Add options to vttestserver to pass -foreign_key_mode, -enable_online_ddl, and -enable_direct_ddl through to vtcombo

go/vt/topo/topoproto/tablet.go, go/vt/topo/topoproto/tablet_test.go
Signed-off-by: Hormoz Kheradmand <hormoz.kheradmand@shopify.com>
Closes https://github.com/vitessio/vitess/issues/6041
vttablet fails to parse tablet-aliases with more than one `-` in the cell name.
This is especially problematic because cells are often named after GCP/AWS zones, which are often valid DNS-1123 labels (consists of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character. [see similar validation in the `kubernetes/kubernetes` repository](https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L107-L124))
Since this parser has been out in the wild for a while, I am not sure how strict we want to make the format. I chose to include the …
=> Correctly parse cell names with dashes in tablet aliases

web/vtadmin/src/components/App.tsx, web/vtadmin/src/components/routes/workflow/Workflow.tsx, web/vtadmin/src/components/routes/workflow/WorkflowStreams.module.scss, web/vtadmin/src/components/routes/workflow/WorkflowStreams.tsx
- Adds two tabs ("Streams", "JSON") to the Workflow view
- Extracts WorkflowStreams into its own component, with no actual changes
This diff looks a lot worse than it is!
N/A
N/A
=> [vtadmin-web] Add tabs to Workflow view

go/vt/topo/etcd2topo/server.go
Add `WithBlock` to client config.
Ref: https://etcd.io/docs/next/upgrades/upgrade_3_3/#upgrades-to--v3314
This is backwards-compatible with etcd 3.3.10.
#8204
Unit and endtoend tests ran locally with 3.3.10 and 3.3.14
=> etcd: add grpc.WithBlock to client config

go/mysql/conn.go, go/mysql/conn_test.go
The is needed to handle multiple net.Conn implementation and to know the type of connection created.
=> Expose inner net.Conn to be able to write better unit tests

go/vt/vtgate/planbuilder/concatenate.go, go/vt/vtgate/planbuilder/expr.go, go/vt/vtgate/planbuilder/join.go, go/vt/vtgate/planbuilder/joinGen4.go, go/vt/vtgate/planbuilder/jointree_transformers.go, go/vt/vtgate/planbuilder/logical_plan.go, go/vt/vtgate/planbuilder/memory_sort.go, go/vt/vtgate/planbuilder/merge_sort.go, go/vt/vtgate/planbuilder/ordered_aggregate.go, go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/planbuilder/pullout_subquery.go, go/vt/vtgate/planbuilder/route.go, go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/select.go, go/vt/vtgate/planbuilder/selectGen4.go, go/vt/vtgate/planbuilder/sql_calc_found_rows.go, go/vt/vtgate/planbuilder/vindex_func.go
Renamed reference of v4 to Gen4 and moved Gen4 select plan code to selectGen4.
#7280
=> [Gen4] some renaming from v4 to Gen4 

go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tabletserver_test.go
-restore_from_backup), as we do in the Vitess Operator, /healthz
reports "ok" until MySQLd is up, which is bad.  Explicitly check for the
not connected state, and add tests for the /healthz handler.
Fixes #8237
One issue here is that there may be existing operational flows that depend on this broken behavior.
=> When MySQLd is starting under vttablet control (e.g. when using

go/cmd/vtgate/vtgate.go, go/vt/vtgate/discoverygateway.go, go/vt/vtgate/gateway.go, go/vt/vtgate/tabletgateway.go, go/vt/vttablet/tabletserver/tabletserver.go
Taken from https://github.com/vitessio/vitess/pull/7251 to get it merged.
1.modify proper annotations for gates
2.add CheckCellFlags function to give valid check before gates creating
3.CheckCellFlags will  help to avoid strange behaviors when there are invalid parameters of the cell-related set 
vtgate brings up but actually does not work correctly.
Before  : 
when you are setting cell wrong you will get some confusing error outputs like :
now you will see it a bit clear:
You could also set cell flag correct but cells_to_watch flag with two does not existing cells but vtgate will could also bring up but just will serve not as expectingly. like below:
also if you Accidentally  configured -tablet_types_to_wait flag wrongly like below:
also, vtgate will runs but when you are using a command …
=> vtgate: validate important flags during startup

go/vt/vtctl/vtctl.go, go/vt/vtctl/workflow/server.go, go/vt/vtctl/workflow/traffic_switcher.go, go/vt/wrangler/stream_migrater_test.go, go/vt/wrangler/switcher.go, go/vt/wrangler/switcher_dry_run.go, go/vt/wrangler/switcher_interface.go, go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/traffic_switcher_test.go, go/vt/wrangler/workflow.go, go/vt/wrangler/workflow_test.go
Finally picking up this workstream again. This does pretty much what it says in the title, with a couple important notes to add here:
* In the original implementation of `getCellsWithShardReadsSwitched`, there was never a case where `noControls` would be set to false (because it's initialized to `true`, and there's only one branch where we say `if len(parition.GetShardTabletControls()) == 0) { noControls = true }`. I believe this to be a (apparently harmless) bug, so I've changed the implementation to initialize `noControls` to false. **No tests broke when I made this change.**
* I updated the `getCellsWith{Shard,Table}ReadsSwitched` functions to take a `topodatapb.TabletType` argument rather than a string representing the tablet type. This made a call to `strings.EqualFold` from …
=> [workflow] Migrate `getCellsWith{Shard,Table}ReadsSwitched`, `TrafficSwitchDirection` and `TableRemovalType` to package workflow

go/vt/vttablet/tabletserver/schema/tracker.go, go/vt/vttablet/tabletserver/schema/tracker_test.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
A user had a problem migrating from Vitess 7.0 to Vitess 10.0. Their vreplication workflows were not making any forward progress in the replication mode after the migration. The cause was a custom heartbeat that was running at 2 qps which was implementing a `pseudo-gtid` similar to http://code.openark.org/blog/mysql/pseudo-gtid-ascending. The query would look like `DROP VIEW IF EXISTS pseudo_gtid._pseudo_gtid_hint__asc:55B364E3:0000000000056EE2:6DD57B85`
As part of DDL processing the VStreamer reloaded the schema for each heartbeat. In addition the tracker would also have tried to update the schema version table. Reloading schemas is expensive and doing it twice a second broke vstreamer processing.
This PR changes the logic to only reload schemas if a ddl is for a table in the current …
=> Tracker/VStreamer: only reload schema for tables in current database and not for internal table artifacts

go/vt/sqlparser/ast.go, go/vt/sqlparser/ast_clone.go, go/vt/sqlparser/ast_equals.go, go/vt/sqlparser/ast_format.go, go/vt/sqlparser/ast_format_fast.go, go/vt/sqlparser/ast_rewrite.go, go/vt/sqlparser/ast_visit.go, go/vt/sqlparser/cached_size.go, go/vt/sqlparser/precedence_test.go, go/vt/sqlparser/random_expr.go, go/vt/sqlparser/sql.go, go/vt/sqlparser/sql.y, go/vt/vtgate/planbuilder/route.go, go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/route_planning_test.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt, go/vt/vtgate/planbuilder/testdata/schema_test.json
Makes it possible for gen4 to plan `LIKE`, `IN`, `NOT IN`, and `IS NOT NULL` plans better.
#7280
=> gen4: plan more opcodes

go/mysql/binlog_event_json.go, go/vt/vttablet/tabletmanager/vreplication/json_docs_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
In JSON Objects and Arrays some data types are inlined. The existing code only expected that 2 byte values (int16s, literals, null) could be inlined. However for "large" documents (> 64K) mysql also inlines 4 byte values (int32s). This resulted in out-of-bounds panics because the inline 32-bit integers were treated as offsets into the document.
While the main reason of this PR is to fix the inline bug, we take this opportunity to:
* some refactoring to remove unnecessary logic, simplify code, improve comments
* adds defensive guards before accessing data to check if calculated offsets are out of bounds. This would mean that our parser is not complete but now it logs the full data as well as information about all columns parsed to-date. This will tell us both the binary value that is …
=> Binlog JSON Parser: handle inline types correctly for large documents

go/vt/mysqlctl/backup.go, go/vt/mysqlctl/metadata_tables.go, go/vt/vttablet/tabletmanager/restore.go
This is a follow-up PR to address some comments on #8107, just to address the public API surface of `mysqlctl.MetadataManager`.
I need to think through a bit more about how to work through the behaviors of `-init_populate_metadata` and `-restore_from_backup` to simplify (and hopefully clarify) the checks we currently do in `populateLocalMetadatLocked`, so I'm going to do that in a second PR.
- #8107
=> [mysqlctl] Restructure `MetadataManager` to reduce public API surface area

go/test/endtoend/onlineddl/vtgate_util.go
Signed-off-by: Alex Charis <alex.charis@shopify.com>
Fix build:
https://vitess.slack.com/archives/CMDJ2KFEZ/p1622754128052700
@shlomi-noach
=> remove duplicate ReadMigrations, fixing build

go/cmd/vtadmin/main.go, go/flagutil/optional.go, go/trace/plugin_datadog.go, go/trace/plugin_jaeger.go
Closes #8198.
A common pain point with the standard `package flag` is the inability to
tell whether a flag was set on the command line or not. You can check
against the default value, but that's not perfect either, because then
you cannot tell the difference between a flag that was not specified at
all and a flag that was set to exactly the default value.
Enter `OptionalFlag`. We define some structs that wrap a primitive
(`float64` for example) with a boolean flag to track whether `Set()` was
ever called on the flag. Since, for the jaeger sampler params, we only
need a `string` for the sampler type and a `float64` for the sampling
rate, I only implemented `OptionalFlag` for those two types for now.
Plus, all of this becomes obsolete if we move to `cobra`, so I wasn't
highly-motivated to …
=> [trace] Add optional flags to support flexible jaeger configs

go/test/endtoend/onlineddl/ghost/onlineddl_ghost_test.go, go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go, go/vt/vttablet/tabletserver/tabletserver.go
This PR introduces a new column `rows_copied` in `_vt.schema_migrations` table and in the output for `SHOW VITESS_MIGRATIONS ...` queries.
`rows_copied` is either an exact or close estimate of the number of rows copied from the original table into the ghost table during a migration.
- If the migration is successfully complete then `rows_copied` is the exact number of rows.
- If the migration is failed then `rows_copied` value can be slightly below the actual number of rows copied, depending on the type of failure.
The value gets populated in this PR by `gh-ost` migrations. Work on https://github.com/vitessio/vitess/pull/8015 will make the value available in `online` (vreplication) migrations, too.
There's an `endtoend` test that verifies the behavior in a sharded cluster.
- #6926
=> Online DDL: report rows_copied for migration (initial support in gh-ost)

go/vt/vtctl/grpcvtctldserver/server.go, go/vt/vtctl/workflow/server.go
I'll follow up with another PR that does the rest of the tracing, but I want this one now :) 
#8265
=> [workflow] Add tracing to `GetWorkflows` endpoint

go/cmd/vtadmin/main.go
This is a very small improvement to the current tracing setup in vtadmin. Rather than calling `.Close()` on the traceCloser directly, we call the wrapper in `package trace` which logs, and therefore gives us visibility into, errors that happen during the close.
=> [vtadmin] Ensure we log any errors when closing the tracer

go/test/endtoend/tabletmanager/tablegc/tablegc_test.go, go/vt/vttablet/tabletserver/gc/tablegc.go
Fixes https://github.com/vitessio/vitess/issues/7984
https://github.com/vitessio/vitess/issues/7984 only happens on GitHub CI, never locally. This is the 2nd time I'm looking into it, with same conclusion: it's a timing/timeout issue. In this PR I make the parge check interval configurable, and set it to `5s` as opposed to `1min`, expecting the test to now pass.
https://github.com/vitessio/vitess/issues/7984
=> Fix TableGC flaky test by reducing check interval

go/cmd/vtadmin/main.go, go/flagutil/sets.go, go/vt/vtadmin/api.go, go/vt/vtadmin/http/api.go, go/vt/vtadmin/http/debug/debug.go
This adds debug endpoints to vtadmin-api, namely the `/debug/pprof/` friends, and also a `/debug/env` to show environment variables available to the vtadmin-api process.
net/http/pprof was being stubborn about how to get it to play nicely with gorilla/mux, but I managed to get it working, unfortunately at the cost of making the route registration a bit more confusing.
We also add some config options to opt users out of debug endpoints entirely, as well as to control the behavior of the `/debug/env` endpoint to sanitize, or omit entirely, any environment variables that may be sensitive.
<details>
<summary>No changes to flags:</summary>
```
❯ curl -s localhost:14200/debug/env | grep CDPATH
CDPATH=:/Users/amason/work:/Users/amason/work
```
</details>
<details>
<summary>Adding …
=> [vtadmin] Add debug endpoints

go/vt/vttablet/endtoend/vstreamer_test.go
This PR is an attempt to fix the flakiness detected recently in `TestSchemaVersioning` such as 
```
--- FAIL: TestSchemaVersioning (0.18s)
Error:     vstreamer_test.go:168: expectLog: got too many events: insert into vitess_version values(1, 10): evs
[type:GTID timestamp:1623069305 gtid:"MySQL56/b1f2fc17-c78c-11eb-a879-000d3ae5ac36:1-323" current_time:1623069305115892459 type:FIELD timestamp:1623069305 field_event:{table_name:"vitess_version" fields:{name:"id1" type:INT32 table:"vitess_version" org_table:"vitess_version" database:"vttest" org_name:"id1" column_length:11 charset:63 flags:32768} fields:{name:"id2" type:INT32 table:"vitess_version" org_table:"vitess_version" database:"vttest" org_name:"id2" column_length:11 charset:63 flags:32768}} current_time:1623069305196910293 type:ROW …
```
=> Schema Tracking Flaky Test: Ignore unrelated gtid progress events

go/mysql/schema.go, go/test/endtoend/vtgate/main_test.go, go/test/endtoend/vtgate/misc_test.go, go/vt/discovery/tablet_health.go, go/vt/vtgate/engine/fuzz_flaky_test.go, go/vt/vtgate/engine/insert_test.go, go/vt/vtgate/engine/update_test.go, go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/schema/tracker.go, go/vt/vtgate/schema/tracker_test.go, go/vt/vtgate/schema/uptate_controller.go, go/vt/vtgate/schema/uptate_controller_test.go, go/vt/vtgate/vindexes/vschema.go, go/vt/vtgate/vindexes/vschema_test.go, go/vt/vtgate/vschema_manager.go, go/vt/vtgate/vschema_manager_test.go, go/vt/vtgate/vtgate.go, go/vt/vttablet/tabletserver/vstreamer/engine.go, go/vt/vttablet/tabletserver/vstreamer/fuzz.go, go/vt/vttablet/tabletserver/vstreamer/local_vschema_test.go, go/vt/vttablet/tabletserver/vstreamer/planbuilder_test.go
Load full schema only on start of VTGate and when the tablet goes from non-serving to serving on primary tablet.
Fixed some corner cases. 
#7994 
#7995
=> Schema Tracking: Optimize and Bug Fix

Makefile, go/vt/proto/binlogdata/binlogdata_vtproto.pb.go, go/vt/proto/query/query_vtproto.pb.go, go/vt/vttablet/grpcqueryservice/server.go, go/vt/vttablet/grpctabletconn/conn.go, go/vt/vttablet/tabletmanager/vreplication/vcopier.go
This is the optimization that is fully described in [this blog post](https://vitess.io/blog/2021-06-03-a-new-protobuf-generator-for-go/). The blog post also includes a performance graph so this issue description is rather light. :)
I'm actively looking at more places where memory pooling makes sense, but for now VReplication is a clear winner and I think we can merge this right away.
=> proto: enable pooling for vreplication

go/vt/topo/topoproto/keyspace.go, go/vt/vtctl/grpcvtctldserver/server.go, go/vt/vtctl/grpcvtctldserver/topo.go
This adds tracing to the remaining vtctldserver endpoints.
- Closes #8265
=> [vtctldserver] Add tracing

go/vt/topo/cell_info.go, go/vt/topo/topotests/cell_info_test.go
A couple other changes here, in addition to the title:
- Store the output cells in a set to dedupe the final slice. This covers
the case where a caller passes `"alias,cell1"` where `cell1` is in the
cell list for `alias`. Without a set, it would appear twice in the final
result.
- Add an inner function to correct `defer` semantics on the cancel
funcs. Defering within the scope of a for loop is generally not what we
want, since all of the deferred functions will pile up until the total
function is done.
Fixes #8290
=> [topo] Refactor `ExpandCells` to not error on valid aliases

go/test/endtoend/vreplication/materialize_test.go, go/vt/vttablet/tabletserver/vstreamer/planbuilder.go, go/vt/vttablet/tabletserver/vstreamer/planbuilder_test.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go, go/vt/wrangler/materializer.go, test/config.json
This PR fixes a bug where comparison filters were being ignored in Materialize workflows if the source keyspace was sharded.
In addition, it adds support for additional operators (`>, >=, <, <=, <>`) . The filter expression can chain multiple comparison operations using `and` only.
Examples:
```
select * from t1 where id = 1
select * from t1 where id <> 1
select * from t1 where val > 'abc'
select * from t1 where id >= 1
select * from t1 where id < 2 and val <= 'xyz'
```
=> Materialize: Add additional comparison operators in Materialize and fix bug where they not applied for sharded keyspaces

go/vt/discovery/tablet_picker.go, go/vt/vtctl/vtctl.go, go/vt/vttablet/tabletmanager/vreplication/engine.go, go/vt/wrangler/fake_dbclient_test.go, go/vt/wrangler/resharder.go, go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/traffic_switcher_env_test.go, go/vt/wrangler/traffic_switcher_test.go
This PR addresses an edge case while switching writes. 
* VReplication Workflow is setup with `-tablet_types` selected as `RDONLY`
* Source keyspace has RDONLY tablets and the forward replication is completed
* Reads are switched to the target keyspace
* `SwitchWrites` is called next to switch all traffic to the target, with the `-reverse_replication true` flag
* However there are no RDONLY tablets on the target, so the reverse replication workflow never starts
* User only finds out after the writes are switched. In the meanwhile due to problems on the target 
the user tries to rollback by reversing the writes. 
* This fails with a timeout waiting for the source to catchup with the target
This PR adds a check on invoking SwitchWrites that there are tablets available to source data from …
=> Switchwrites: error if no tablets available on target for reverse replication

go/vt/vtctl/grpcvtctldserver/server_test.go
=> Use shared testing helper which guards against races in tmclient construction

web/vtadmin/package-lock.json, web/vtadmin/package.json, web/vtadmin/src/api/http.test.ts, web/vtadmin/src/api/http.ts, web/vtadmin/src/api/responseTypes.ts, web/vtadmin/src/errors/bugsnag.ts, web/vtadmin/src/errors/errorHandler.test.ts, web/vtadmin/src/errors/errorHandler.ts, web/vtadmin/src/errors/errorHandlers.ts, web/vtadmin/src/errors/errorTypes.ts, web/vtadmin/src/index.tsx, web/vtadmin/src/react-app-env.d.ts
- Adds a generic + extensible interface for observability into client-side errors.
- Implements the `ErrorHandler` interface for [Bugsnag](https://www.bugsnag.com), for deployments that use it.
Implementations for other monitoring services (common ones being [Sentry](https://sentry.io/welcome/), [Rollbar](https://rollbar.com/guides/javascript-exception-handling/), [Datadog](https://docs.datadoghq.com/logs/log_collection/javascript/), etc.) are left as future enhancements. 😸 (I briefly considered implementing one other, to prove the concept, but... it didn't really make sense to add an integration that no one uses!) I looked into the JavaScript libraries for the aforementioned monitoring services and all of them fit nicely into …
=> [vtadmin-web] Add client-side error handling interface + Bugsnag implementation

go/cmd/vtctlclient/main.go, go/cmd/vtctldclient/internal/command/legacy_shim.go, go/cmd/vtctldclient/internal/command/root.go, go/cmd/vtctldclient/plugin_grpcvtctlclient.go, go/vt/vtctl/grpcclientcommon/dial_option.go, go/vt/vtctl/grpcvtctlclient/client.go, go/vt/vtctl/grpcvtctldclient/client.go
This PR adds a shim to the new vtctldclient to allow running legacy vtctl commands that have not yet been migrated. The intention here is to allow users to start updating any scripts they have now (going from `vtctlclient [args ...]` to `vtctldclient LegacyVtctlCommand -- [args ...]`), and then dropping the old client should be ideally a no-op, or at least far less painful.
<details>
<summary>client-side help</summary>
```
❯ vtctldclient LegacyVtctlCommand -h
LegacyVtctlCommand uses the legacy vtctl grpc client to make an
ExecuteVtctlCommand rpc to a vtctld.
This command exists to support a smooth transition of any scripts that relied on
vtctlclient during the migration to the new vtctldclient, and will be removed,
following the Vitess project's standard deprecation cycle, once all …
```
=> [vtctldclient] Add legacy shim

go/test/endtoend/docker/vttestserver.go, go/test/endtoend/docker/vttestserver_test.go
This PR adds the tests for the docker image `vttestserver`. The tests are not run in CI but can be run by hand manually.
Adds tests for #8210
=> Vttestserver docker test

web/vtadmin/src/components/routes/workflow/WorkflowStreams.tsx
A small bugfix to display target shard, instead of source shard, for workflow streams. 😊 
N/A
N/A
=> [vtadmin-web] Small bugfix where stream source displayed instead of target

go/vt/vtctl/grpcvtctldserver/server_test.go
Prior to this change, running the full `grpcvtctldserver` test suite a few times would occasionally produce a panic, ultimately owing to: `fatal error: concurrent map read and map write`. The stack, which I didn't copy, and the RNG deities are not cooperating right now, points back to `tmclient.NewTabletManagerClient` coming from various tests here.
So, I went through the tests and found any test that was using `t.Parallel()` (good!) but not using the `testutil.NewVtctldServerWithTabletManagerClient()` (less good!).
=> [vtctldserver] Update tests to prevent races during tmclient init

go/vt/binlog/binlogplayer/binlog_player.go, go/vt/vttablet/tabletmanager/vreplication/stats.go, go/vt/vttablet/tabletmanager/vreplication/vplayer.go
Adds a new metric to display vreplication lags in the form of a gauge for easier display in VTAdmin.
Example:
```
"VReplicationLag": {"1":[1.6,4.8,4.8,4.8,4.8,10.8,13.8,9,4.8,4.8,4.6,4.8,9.6,5.2,10.2,6.4,5.8,6.4,6.4,6.4,6.4,6.4,6.4,6.4,6.4,6.4,7.2,6.4,6.4,6.4,6.4,6.4,6.4,6.4,6.4,9.8,8,8,8.2,7.6,8.4,7.2,8,6.8,6.4],
"10":[4.8,4.8,4.8,4.8,4.8,4.8,4.8,4.8,4.6,4.8,4.8,5.2,4.8,4.8,4.8,4.8,4.8,4.8,4.8,4.8,4.8,0,0,0,0,0,0,0,0,0],
"11":[4.8,4.8,4.8,4.8,4.8,4.8,4.8,4.8,4.4,4.8,4.8,5.2,4.8,4.8,4.8,4.8,4.8,4.8,4.8,4.8,5,0,0,0,0,0,0,0,0,0],
"All":[4.8,4.8,4.8,4.8,4.8,4.8,4.8,4.8,4.6,4.8,4.8,5.2,4.8,4.8,4.8,4.8,4.8,4.
```
=> New VReplication lag metric 

go/tools/release-notes/release_notes.go, go/tools/release-notes/release_notes_test.go
Make sure to include squashed PRs in release notes
=> include squashed PRs in release notes

.github/workflows/pr-labels.yml
fixes https://github.com/vitessio/vitess/issues/8324
`pr-labels` workflow to only check for an actual pull request.
https://github.com/vitessio/vitess/issues/8324
=> pr-labels workflow: only check actual PRs

go/test/endtoend/recovery/unshardedrecovery/recovery.go, go/vt/mysqlctl/xtrabackupengine.go
Resubmission of https://github.com/vitessio/vitess/pull/8317
Instead of backporting commits into earlier versions, we want to apply changes in earlier versions, then merge forward.
This will merge into `release-9.0` branch
Copy of original comment from @deepthi :
---
Some of the xtrabackup tests have been flaky for a while. Today @vmg was able to extract the actual error from a failing test.
This seems to be a known issue with a documented workaround. Implementing the workaround.
https://www.percona.com/blog/2017/08/08/avoiding-the-an-optimized-without-redo-logging-ddloperation-has-been-performed-error-with-percona-xtrabackup/
The blog post has 3 suggestions:
* `--lock-ddl` : only works with Percona MySQL server, we are running community MySQL server in  CI
* `--lock-ddl-per-table`: did …
=> workaround xtrabackup error using mysql global variable old_alter_table

go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go
An attempt at fixing #8323 
What happens in #8323 is that a `update _vt.vreplication set pos=` query is encountered unexpectedly. This query can appear due to heartbeat leftovers from a previous test or from a heartbeat race condition.
This PR allows for just a little bit of noise to pass through: `expectDBClientQueries` supports `skippableOnce` optional list of queries. It's OK to hit _at most_ one of given skippable queries, _once_, while iterating expected queries.
- https://github.com/vitessio/vitess/issues/8323
-
=> Heuristic fix for a flaky test: allow for some noise to pass through

go/vt/vtctl/workflow/server.go
`scanWorkflow` involves a remote call to a tablet to get the
`copy_state` rows for the workflow stream associated with that tablet.
Calling this concurrently gives us a noticeable speedup, especially on
workflows involving many streams.
- Closes #8271
=> [workflow] Call `scanWorkflow` concurrently

doc/releasenotes/9_0_0_release_notes.md
This pull request backports a pull request with the Version 9 Release Notes into the `release-9.0` branch. 
Related issue: https://github.com/vitessio/vitess/issues/8212
Backport of #8295
=> Backport of Updates and Corrections to v9 Release Notes to `release-9.0`

go/cmd/vtadmin/main.go, go/trace/logger.go, go/trace/plugin_datadog.go, go/trace/plugin_jaeger.go, go/trace/trace.go
This PR adds a new flag to `package trace` to initialize the opentracing tracer (either jaeger or datadog) with a logger attached. I've also introduced a struct that implements both jaeger's and datadog's logger interfaces using the `go/vt/log` package under the hood.
<details>
<summary> jaeger + <code>JAEGER_REPORTER_LOG_SPANS=true</code> + <code>-tracing-enable-logging</code></summary>
```
I0608 12:08:21.671954       8 logger.go:32] Reporting span xxxxxxxxxxxxxxxx:aaaaaaaaaaaaaaaa:bbbbbbbbbbbbbbbb:1
I0608 12:08:21.671978       8 logger.go:32] Reporting span xxxxxxxxxxxxxxxx:bbbbbbbbbbbbbbbb:cccccccccccccccc:1
I0608 12:08:21.672031       8 logger.go:32] Reporting span xxxxxxxxxxxxxxxx:dddddddddddddddd:eeeeeeeeeeeeeeee:1
I0608 12:08:21.765381       8 logger.go:32] Reporting span …
```
=> [trace] Add logging support to opentracing plugins

go/vt/vttablet/tabletmanager/vreplication/replicator_plan.go, go/vt/vttablet/tabletmanager/vreplication/table_plan_builder.go, test/config.json
Fixes https://github.com/vitessio/vitess/issues/8351
These two PRs:
- https://github.com/vitessio/vitess/pull/8322
- https://github.com/vitessio/vitess/pull/8345
Introduced a conflict. Because both were open at the same time and both merged to `main` without merging the 1st into the 2nd, this conflict was only seen in `main` after both merged.
The nature of the bug:
- In #8322 we introduce casting to `utf8mb4` for texts. 
- In #8345 we introduce a test where a text column is part of a primary key, and is modified via `UPDATE`
Now, when the text is `CONVERT`ed, then it becomes a function and ceases to be a text, and is not found to be part of the primary key anymore.
This PR takes care of that edge case.
https://github.com/vitessio/vitess/issues/8351
=> Bugfix: assign cexpr.references for column CONVERTed to utf8mb4

go/vt/vtadmin/vtctldclient/proxy.go
Exactly what it says in the title. This gives us info about the cluster that we're dialing, as well as the underlying vtctld hostname we're using, including when the dial is a no-op.
=> [vtctldproxy] Add more annotations to vtctld Dial calls

go/mysql/conn.go, go/mysql/conn_test.go, go/mysql/query.go, go/mysql/query_test.go
During high load, if prepared statements are used, the parameter values could accidentally get overwritten with dirty data from other concurrent connections.
This PR fixes this by copying the data before releasing the buffer.
=> Prepared statement buffer concurrent bug fix

go/test/endtoend/reparent/utils_test.go, go/vt/vttablet/tabletmanager/tm_state.go
This is a partial revert of #8107. Calling `populateMetadata` in `updateLocked` causes `publishState` to fail when semi-sync is enabled.
TBD
=> tm state: don't populate metadata in updateLocked 

go/vt/discovery/replicationlag.go, go/vt/vtgate/debugenv.go, go/vt/vtgate/executor_scatter_stats.go, go/vt/vtgate/vtgate.go, go/vt/vttablet/tabletserver/debugenv.go
Similar to the vttablet /debug/env handler, borrow the code to make one for vtgate.
Initial use-case is to enable changing new healthcheck flags without a vtgate restart.  Having the getter/setters for the various flags in `replicationlag.go` is not idiomatic, but it minimizes changes.  Open to suggestions.
Not putting for this on the vtgate homepage (yet).
=> Add /debug/env for vtgate

go/vt/schema/online_ddl.go, go/vt/vtgate/planbuilder/ddl.go
Online DDL does not support foreign keys. We used a link to @shlomi-noach 's personal blog post, in error messages, to explain why. Now that https://vitess.io/blog/2021-06-15-online-ddl-why-no-fk/ is published, we change the link to this more official post.
- #6926
=> Update link to 'Why FK not supported in Online DDL' blog post

go/vt/wrangler/materializer.go
ExternalizeVindex was missing a step to rebuild the SrvVSchema at the end. Without this vtgate won’t be notified of the vschema change. Reported by a user who faced this issue: they are on 8.0.
=> ExternalizeVindex: refresh SrvVSchema after an ExternalizeVindex flow

go/vt/vtctl/grpcvtctldserver/topo.go, go/vt/vttablet/tabletmanager/shard_sync.go, go/vt/vttablet/tabletmanager/shard_sync_test.go, go/vt/vttablet/tabletmanager/tm_init_test.go, go/vt/wrangler/tablet.go
This PR makes it explicit in all the places and `shard_sync` that the timestamp for the master term is the authoritative source of information for who is the master. We sync the information between the tablet record and shard record based on the timestamp.
=> Make timestamp authoritative for master information

go/vt/sqlparser/ast.go, go/vt/vtgate/planbuilder/join.go, go/vt/vtgate/planbuilder/jointree.go, go/vt/vtgate/planbuilder/jointree_transformers.go, go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/planbuilder/project.go, go/vt/vtgate/planbuilder/route.go, go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/selectGen4.go, go/vt/vtgate/planbuilder/testdata/alterVschema_cases.txt, go/vt/vtgate/planbuilder/testdata/call_cases.txt, go/vt/vtgate/planbuilder/testdata/ddl_cases.txt, go/vt/vtgate/planbuilder/testdata/ddl_cases_no_default_keyspace.txt, go/vt/vtgate/planbuilder/testdata/filter_cases.txt, go/vt/vtgate/planbuilder/testdata/flush_cases.txt, go/vt/vtgate/planbuilder/testdata/migration_cases.txt, go/vt/vtgate/planbuilder/testdata/other_admin_cases.txt, go/vt/vtgate/planbuilder/testdata/other_read_cases.txt, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/planbuilder/testdata/show_cases.txt, go/vt/vtgate/planbuilder/testdata/symtab_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt, go/vt/vtgate/semantics/analyzer.go, go/vt/vtgate/semantics/analyzer_test.go, go/vt/vtgate/semantics/semantic_state.go
This PR will make sure that the gen4 planner does one of the following:
- Produces a correct query (correct here means "does what the user wants", not necessarily the same thing that V3 did)
- Produces a correct error (if the query is wrong, it should be detected and failed correctly)
- Produce a Gen4NotSupported error. This makes it easy to fall back on V3 when gen4 does not yet support the query.
#7280
Continuation of #8359
=> Gen4 fail more2

go/mysql/server_test.go, go/mysql/sql_error.go, go/test/endtoend/vtgate/misc_test.go, go/test/endtoend/vtgate/unsharded/main_test.go, go/vt/sqlparser/parse_test.go, go/vt/vterrors/state.go, go/vt/vtgate/planbuilder/delete.go, go/vt/vtgate/planbuilder/testdata/dml_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt, go/vt/vttablet/tabletserver/tx_pool_test.go
DML queries are rewritten to add a `limit` clause to protect from rogue queries. 
Delete has some special syntax that does not allow the `limit` clause.
To overcome the limitation, a special case of single table reference is rewritten to allow the `limit` clause.
https://github.com/vitessio/vitess/issues/6854
=> Delete table reference alias support

go/test/endtoend/vreplication/config.go, go/test/endtoend/vreplication/vreplication_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go, go/vt/wrangler/traffic_switcher.go
For sharded streams we add filters like `select * from customer where in_keyrange(customer_id, 'keyspace1.hash', '-7f')` where the vindex is scoped by the source keyspace. This is needed since other keyspaces might also contain vindexes of the same name and using just the vindex name would create an ambiguity. 
This logic was missing while creating reverse streams which this PR adds.
https://github.com/vitessio/vitess/issues/8259
=> VReplication Reverse Workflows: add keyspace scope to vindex while creating reverse vreplication streams

go/vt/vtctl/grpcvtctldserver/server.go
We always want to base off the total number of backups, not the total
number after applying the overall limit.
tl;dr I'm bad at math. Consider this:
* 25 total backups
* `limit = 10`
* `detailedLimit = 5`
Then,
* `totalBackups = req.Limit` = 10
* `backupsToSkip = len(bhs) - totalBackups` = 25 - 10 = 15
* `backupsToSkipDetails = totalBackups - detailedLimit` = 10 - 5 = 5
this means we would skip getting details for only the first 5 backups, and show details for the remaining `25 - 5 = 20` backups (then, after applying the overall limit, we would show details for all 10 backups).
=> [grpcvtctldserver] Fix backup detail limit math

go/vt/wrangler/vdiff.go, go/vt/wrangler/vdiff_test.go
Signed-off-by: Malcolm Akinje <makinje@slack-corp.com>
This PR modifies VDiff by now ignoring tables that pass the `IsInternalOperationTableName` method.
=> Ignore Internal Operation Tables From Vdiff

web/vtadmin/src/components/routes/Workflows.tsx, web/vtadmin/src/components/routes/stream/Stream.tsx, web/vtadmin/src/components/routes/workflow/Workflow.tsx, web/vtadmin/src/index.tsx, web/vtadmin/src/util/workflows.test.ts, web/vtadmin/src/util/workflows.ts
Two small things:
- Adds a `getStream` util + tests, which will be useful for the stream detail views over the next little bit.
- Removes a few `refetchInterval` parameters so queries will fetch less frequently. Once per second is more frequently than is really necessary, especially for views that aren't charts. 
- Updates all components by default to no longer refetch every time the window receives focus via react-query's [`refetchOnWindowFocus` option](https://react-query.tanstack.com/guides/important-defaults). In the future, this will be parameterized with build flags. 
N/A
N/A
=> [vtadmin-web] Add getStream util + tune refetch intervals

go/vt/vtctl/vtctl.go
Per https://github.com/vitessio/vitess/issues/6926#issuecomment-817619302, we are deprecating:
- `vtctl OnlineDDL revert ...`
- `vtctl VExec`
Deprecation will spawn two versions (and code removal following that). In v11 we merely log a warning message that these commands will be deprecated in next version.
- https://github.com/vitessio/vitess/issues/6926#issuecomment-817619302
=> v11: deprecation message for a couple Online DDL related commands

go/test/endtoend/cluster/vttablet_process.go, go/test/endtoend/vreplication/cluster.go, go/test/endtoend/vreplication/vreplication_test.go, go/vt/vttablet/tabletserver/stream_consolidator_test.go
* TestConsolidatorMemoryLimits is failing consistently. To unblock PRs we temporarily skip TestConsolidatorMemoryLimits while it gets fixed
* One cause for flakiness in vreplication e2e tests is that the TearDown step of the tests seem to hang, after the test runs successfully, causing the 10 minute per-test timeout to be triggered failing the test. The teardown logic has been changed to wait at most for a minute for the teardown. Also shutdown vttablets in parallel instead of sequentially, which should speed up the tests.
Also
* A previous PR had replaced `log.Infof` with `t.Logf` causing these logs to be shown in red in the CI console adding noise while debugging failing tests. This has been reverted.
=> CI: Skip TestConsolidatorMemoryLimits, refactor e2e test cluster setup to reduce vreplication e2e test flakiness

go/vt/vttablet/tabletmanager/vreplication/vplayer.go
=> Ignore SBR statements from pt-table-checksum

go/test/endtoend/onlineddl/exec_util.go, go/test/endtoend/onlineddl/vrepl_stress/onlineddl_vrepl_mini_stress_test.go, go/test/endtoend/onlineddl/vtgate_util.go, go/vt/vttablet/onlineddl/executor.go
Fixes a bug in OnlineDDL/VReplication where we would not wait for the correct position before cutting over. Now waiting for the correct position.
In https://github.com/vitessio/vitess/pull/8364#issuecomment-869136323 I found data inconsistency that didn't seem to be related to the PR.
In this PR we intensify the stress in the `onlineddl_vrepl_stress` test so as to surface the problem.
#6926
=> OnlineDDL/Vreplication stress test: investigating failures

Makefile, misc/git/commit-msg, misc/git/hooks/golint, misc/git/hooks/govet, misc/git/pre-commit
This improves a few bits for the Go build setup. With the recent move to Go 1.16, there's no need anymore to specify GO111MODULE as the default value is now that it is on.
Additionally, it enables `-trimpath` to remove build specific paths from the final release artifacts.
Lastly, this cleans up a bunch of usage of GOPATH. Go itself now falls back to `~/go` if it is not set and we can depend on this default for commands and don't need to set anything manually.
`go env GOPATH` still works and returns this fallback if GOPATH is not set. This further simplifies setup and means people don't need to configure GOPATH anymore separately either.
=> Small build improvements

go/vt/grpcclient/client.go, go/vt/vttablet/grpctmclient/cached_client.go, go/vt/vttablet/grpctmclient/cached_client_test.go, go/vt/vttablet/grpctmclient/client.go, go/vt/vttablet/grpctmserver/server.go, go/vt/vttablet/grpctmserver/server_test.go, go/vt/vttablet/tmrpctest/test_tm_rpc.go
(Issue to come, I mainly want to see how this does in CI, even though I know it works in practice).
tl;dr: the oneshot dialing strategy of the existing grpc implementation of TabletManagerClient results in a lot of connection churn when doing a high volume of tabletmanager RPCs (which happens when doing VReplicationExec calls on workflows for larger keyspaces, for example). In addition, this can cause the number of osthreads to spike as the go runtime has to park more and more goroutines on the syscall queue in order to wait for those connections, which can result in crashes under high enough load.
This aims to fix that by introducing a per-tablet connection cache. The main reason I don't want to expand the use of the `usePool` flag in the old implementation is:
* we still create N …
=> [grpctmclient] Add support for (bounded) per-host connection reuse

go/vt/vttablet/tabletserver/query_engine_test.go, go/vt/vttablet/tabletserver/stream_consolidator_test.go
This test is flaky and I'm debugging it on CI
=> consolidation: Fix flaky test

web/vtadmin/src/components/pips/BackupStatusPip.tsx
A small fix for https://github.com/vitessio/vitess/pull/8409. As it says in the title, this sets Backup status indicators to be the correct colours. (Sigh. Juggling too many things today.) 😊 
https://github.com/vitessio/vitess/pull/8409
N/A
=> [vtadmin-web] Set Backup status indicators to the correct colours 

go/pools/rpc_pool.go, go/pools/rpc_pool_test.go, go/vt/vtadmin/api_test.go, go/vt/vtadmin/cluster/cluster.go, go/vt/vtadmin/cluster/cluster_internal_test.go, go/vt/vtadmin/cluster/cluster_test.go, go/vt/vtadmin/cluster/config.go, go/vt/vtadmin/cluster/flags.go, go/vt/vtadmin/errors/errors.go, go/vt/vtadmin/testutil/cluster.go
This adds an RPCPool specialization on top of the generic pools.ResourcePool, and then adds several read pools (named this way so we don't need to rename (and rename the flags) when we add the r/w pools later). The main reason I'm not using sync2.Semaphore is because the timeout/context semantics don't work for our use case. With the semaphore, you can _either_ use the semaphore's timeout _or_ the context timeout, but what I want is to always use the minimum of the two. RPCPool does exactly that, plus we get all the stats/metrics of ResourcePool "for free".
From there, we add 4 rpc pools:
* topoReadPool - for making general requests that end up reading from the topo, things like GetKeyspace, GetVSchema, etc
* backupReadPool - for making requests that hit the backups endpoints, this is …
=> [vtadmin] cluster rpc pools

go/mysql/mysql56_gtid_set.go, go/mysql/mysql56_gtid_set_test.go, go/mysql/replication_status.go, go/test/endtoend/reparent/reparent_test.go, go/vt/vttablet/tabletmanager/rpc_replication.go
Already approved as #8319 ; redone to clean up the commit list which was polluted with hundreds of merge commits.
* Fixes #8316, where ERS thinks that a replica has an errant GTID, when it actually does not
* Fixes #8333 where we do not clear the `do_not_replicate` sentinel flag that we create during ERS (and other steps) to ensure that replication reporter does not automatically restart replication after we have (intentionally) stopped it.
=> Fix problematic ERS cases

go/vt/vtgate/engine/route.go, go/vt/vtgate/planbuilder/jointree.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt
When evaluating the cost of plans, gen4 was not comparing route costs correctly. This PR updates how this is done.
#7280
=> Gen4 cost calculation tweak

go/vt/topo/consultopo/lock.go
Vitess assumes the process gets the lock if the error is nil https://github.com/vitessio/vitess/blob/main/go/vt/topo/locks.go
However, consul will return nil error when the context timeout’d before the process get the lock: https://github.com/hashicorp/consul/blob/master/api/lock.go#L185 - which means anyone will get the lock after the context timeout.
This means after the context timeout, everyone that is waiting for the lock will get one
This PR make sure we will raise error if the lost chan returned is nil, we should not assume we have the lock
https://github.com/vitessio/vitess/issues/8309
=> Use consul lock properly

go/vt/discovery/tablet_picker.go, go/vt/discovery/tablet_picker_test.go
Add a new metric to count number of times that a picker did not find a tablet  for streaming. The count is keyed of the tuple (cells, keyspace, shard, tablet types).
=> Tablet Picker: add metric to record lack of available tablets

go/vt/vtexplain/testdata/multi-output/selectsharded-output.txt, go/vt/vtexplain/testdata/selectsharded-queries.sql, go/vt/vtexplain/testdata/test-schema.sql, go/vt/vtexplain/testdata/test-vschema.json, go/vt/vtgate/vindexes/lookup_internal.go
Today only integral values are batches for lookup queries as they are comparable.
This PR introduces "batch_lookup" param to the Vindex and if provided, try to batch the result set.
This relies on that the collation is utf8 and case sensitive.
This helps optimize for the case where the user knows how the vindex will behave for its values.
=> added batch lookup param to lookup vindex

go/vt/vtadmin/vtctldclient/proxy_test.go
This PR adds a test case for VTAdmin's existing vtctld `Dial` function.
Figured I'd peel off this one lil test case from the larger reconnect branch I'm working on, since it _simply_ tests our current behaviour. 
N/A
N/A
=> [vtadmin] Add a vtctld Dialer unit test

go/cmd/vtadmin/main.go, go/vt/vtadmin/api.go, go/vt/vtadmin/api_test.go
For some other branches, the API is going to need more options that
don't fit neatly into either the grpcserver.Options or http.Options
structs, so this will give us a more general scope to put them in.
I'm getting this refactor in now because the diff is noisy, and I don't
want it in the way of those other changes.
=> [vtadmin] Add Options struct to wrap grpc/http options

go/mysql/auth_server_clientcert_test.go, go/mysql/client.go, go/mysql/conn_params.go, go/mysql/handshake_test.go, go/mysql/ldapauthserver/auth_server_ldap.go, go/mysql/mysql_fuzzer.go, go/mysql/server_test.go, go/vt/grpcclient/client.go, go/vt/servenv/grpc_server.go, go/vt/tlstest/tlstest_test.go, go/vt/vtgate/plugin_mysql_server.go, go/vt/vtgate/plugin_mysql_server_test.go, go/vt/vttls/vttls.go, misc/git/hooks/goimports
TLS 1.0 & TLS 1.1 are deprecated and shouldn't be used anymore. There are however many older MySQL versions out there where the latest 5.6, 5.7 or 8.0 patch release isn't used which means they don't have a build against OpenSSL with latest TLS support.
This means we can't easily change the minimum version to always be TLS 1.2, but the best possible option is to create flag instead.
The changes here add support for that flag. The default still is TLS 1.2 as the minimum version, but people who run against an older MySQL can use a new flag to override this and still allow TLS 1.0 or TLS 1.1 if desired.
Related to #4254 since this implements a minimal TLS version configuration option. The option is only added / used for the MySQL Vitess connects to and the LDAP server used.
Internally for …
=> Allow for configuration of the minimal TLS version

go/vt/topo/k8stopo/server.go
The existing documentation was sparse, and didn't explain that
Vitess is capable of auto-discovering its enclosing Kubernetes
API server if the topo_k8s_* flags are left unspecified.
=> Enhance k8stopo flag documentation

go/test/endtoend/vtgate/main_test.go, go/test/endtoend/vtgate/misc_test.go, go/test/endtoend/vtgate/mysql80/main_test.go, go/test/endtoend/vtgate/mysql80/misc_test.go, go/vt/sqlparser/ast.go, go/vt/sqlparser/ast_funcs.go, go/vt/sqlparser/parse_test.go
This PR fixes the bug which parenthesised `CURRENT_TIMESTAMP` aliases in `DEFAULT` clause, causing them not to work against MySQL 5.7.
- Fixes #8424
=> Current_timestamp aliases should not be parenthesised for DEFAULT clause

go/test/endtoend/cluster/vtctl_process.go, go/test/endtoend/vreplication/config.go, go/vt/vtgate/evalengine/arithmetic.go, go/vt/vtgate/evalengine/arithmetic_test.go, go/vt/vtgate/vindexes/consistent_lookup_test.go, go/vt/wrangler/vdiff.go
Fixed an issue in `VDiff`, which was failing for columns of the BIT data type since it was not part of the comparable types in `NullsafeCompare()`. 
Couple of additional changes found during testing:
* `CreateKeyspace` fails randomly in CI. Added additional logging to debug this if it happens again
* Fix for a regression introduced where an error was being checked late in `vdiff`, causing a panic on accessing the returned object. 
=> VDiff: Add BIT datatype to list of byte comparable types

go/vt/sqlparser/keywords.go, go/vt/sqlparser/parse_test.go, go/vt/vtgate/planbuilder/testdata/show_cases.txt
Rows is a reserved word as of [MariaDB 10.2.4](https://mariadb.com/kb/en/mariadb-1024-release-notes/) and [MySQL 8.0.2](https://dev.mysql.com/doc/mysqld-version-reference/en/keywords-8-0.html). If a table has a column named `rows` (an unfortunate legacy choice) then, for example, VReplication will fail to copy data from the table with:
```
Error: vttablet: rpc error: code = Unknown desc = You have an error in your SQL syntax; check the 
manual that corresponds to your MariaDB server version for the right syntax to use near 'rows, othercol1,
othercol2' at line 1 (errno 1064) (sqlstate 42000) during query: select id, rows, othercol1, othercol2 
from table_xyz order by id
```
I am not very clear on the responsibility of these keywords, listed in `sqlparser/keywords.go` vs. the …
=> Add `rows` as keyword in sqlparser

.github/workflows/cluster_endtoend_mysql80.yml, go/test/endtoend/onlineddl/vrepl_suite/testdata/enum/alter, go/test/endtoend/vtgate/main_test.go, go/test/endtoend/vtgate/misc_test.go, go/test/endtoend/vtgate/mysql80/main_test.go, go/test/endtoend/vtgate/mysql80/misc_test.go, go/vt/sqlparser/ast_format.go, go/vt/sqlparser/ast_format_fast.go, go/vt/sqlparser/ast_funcs.go, go/vt/sqlparser/parse_test.go, go/vt/vtgate/planbuilder/testdata/ddl_cases.txt, go/vt/vttablet/tabletserver/planbuilder/testdata/exec_cases.txt, test/ci_workflow_gen.go, test/config.json
Forward port for the PR #8468 
- Fixes #8424
=> Fix for function calls in DEFAULT value of CREATE TABLE statement in release-11.0

go/mysql/conn.go, go/mysql/constants.go
Signed-off-by: JohnnyThree <whereshallyoube@gmail.com>
=> fix when show tables record too much error log "Got unhandled packet.."

go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
```
goroutine profile: total 5614
5423 @ 0x43b3c5 0x4059fa 0x405755 0x1346ceb 0x4728e1
#	0x1346cea	vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.(*vstreamer).parseEvents.func2+0xaa	vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer.go:279
```
There are reports of these leaking goroutines causing OOMs. I have not been able to reproduce it. I think this can only happen if vstreamer is failing to parse events resulting in the context being cancelled, with some events still present in the `throttledEvents` channel. 
In the normal course of events, including errors that I can think of, we should not see this since the binlog streamer will close its channel causing the goroutine to return. So presumably there is an issue with this vreplication workflow causing these …
=> Return from throttler goroutine if context is cancelled to prevent goroutine leaks

go/vt/vttablet/tabletmanager/vreplication/stats.go
Metric was setup incorrectly with two dimensions instead of three causing Prometheus errors.
=> Fix vreplication error metric

go/vt/vtctl/backup.go, go/vt/vtctl/reparent.go, go/vt/vtctl/reparentutil/planned_reparenter.go, go/vt/vtctl/vtctl.go, go/vt/vtctld/vtctld.go, go/vt/wrangler/schema.go, go/vt/wrangler/schema_test.go, go/vt/wrangler/tablet.go, go/vt/wrangler/testlib/backup_test.go, go/vt/wrangler/testlib/copy_schema_shard_test.go, go/vt/wrangler/testlib/emergency_reparent_shard_test.go, go/vt/wrangler/testlib/external_reparent_test.go, go/vt/wrangler/testlib/find_tablet_test.go, go/vt/wrangler/testlib/migrate_served_from_test.go, go/vt/wrangler/testlib/migrate_served_types_test.go, go/vt/wrangler/testlib/permissions_test.go, go/vt/wrangler/testlib/planned_reparent_shard_test.go, go/vt/wrangler/testlib/reparent_utils_test.go, go/vt/wrangler/testlib/shard_test.go
Deprecate vtctl command flags that contain `master` and introduce replacements that use `primary` instead.
Full list is documented in linked issue.
Along the way I needed to make changes in `wranger/testlib` so I went through and cleaned up all references in that package.
#7114 
All changes are fully backwards-compatible and will remain so in release 12. Old flags will be removed in release 13, so users are advised to change their scripts and tooling before then.
=> naming: deprecate old flags and create new ones (master->primary)

go/vt/sqlparser/ast_format.go, go/vt/sqlparser/ast_format_fast.go, go/vt/sqlparser/parse_test.go
Currently parsing the following query
```sql
create table function_default (x bool DEFAULT true)
```
gives the output
```sql
create table function_default (x bool DEFAULT (true))
```
but this is incorrect and will not work against MySQL5.7. This PR fixes it.
- Fixes #8501
=> boolean values should not be parenthesised in default clause

go/mysql/server.go
Found while reviewing https://github.com/vitessio/vitess/pull/8503 (by @dbussink). This is an actual error in the auth code, that should abort right away if TLS is required and the connection doesn't have it. The logic error has been there for a while.
I'm thinking this is probably worth a backport just for safety, even though it may not be exploitable. cc @deepthi
=> mysql/server: abort connection if secure transport is required

Makefile, go/tools/release-notes/release_notes.go
Adding a `known issues` section to release notes. Issues can be added to this section by labeling them with `Known issue: <release-branch>`, where `<release-branch>` is the name of the release branch we write the notes for.
A new flag is added to the program to specify the branch name:
```sh
make FROM="v11.0.1" TO="v11.0.2" RELEASE_BRANCH="release-11" release-notes 
```
=> Addition of known issues to release notes

go/vt/vtgate/planbuilder/abstract/queryprojection.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/memory_sort_cases.txt, go/vt/vtgate/planbuilder/testdata/postprocess_cases.txt, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/planbuilder/testdata/stream_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt, go/vt/vtgate/semantics/analyzer.go, go/vt/vtgate/semantics/analyzer_test.go
Refactored distinct plan to use oa engine. 
Added additional supported plans or add failure messages for Gen4 errors to plan tests.
Added support for grouping, aggregations in join query.
#7280
=> Gen4: Distinct plan refactor and support grouping and aggregation on join query

go.mod, go.sum, go/cmd/rulesctl/cmd/add.go, go/vt/vttablet/customrule/filecustomrule/filecustomrule.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/rules/cached_size.go, go/vt/vttablet/tabletserver/rules/rules.go, go/vt/vttablet/tabletserver/rules/rules_test.go
:warning: Caveat is that I pulled the PR and description from https://github.com/vitessio/vitess/pull/7784 since it was accidentally merged that into upstream instead of the TS branch so it's a little non-trivial to just reopen it due to the revert (afaik). I did _not_ do any additional retesting relying on the unit tests etc to do their thing.
This PR makes three changes
1. It introduces an optional us of `fsnotify` to watch for changes vs the rules file
2. it extends rules evaluation to support comparison vs leading/trailing comments
3. It adds support to specify leading/trailing comments as part of rule creation in `rulesctl`
We use [fsnotify](https://pkg.go.dev/github.com/fsnotify/fsnotify) which seems to be the generally accepted approach. There are some gymnastics necessary as …
=> [tablet, queryrules] Extend query rules to check comments

go/mysql/auth_server_clientcert.go
Should be `mysql_clientcert_auth_method`.
=> go/mysql/auth: fix error message for wrong auth method.

go/vt/schema/tablegc_test.go, go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go
Fixes #8498
Fixes #8499 (possibly)
- stale migration analysis did not update completed_timestamp. As result lifecycle would not run. Now that's fixed.
- retroactively updating completed_timestamp for existing NULL entries
- liveness_timestamp now always set with started_timestamp, so that it is never NULL even if migration didn't report liveness. This is essential for detecting and marking stale migrations
- when garbage collecting artifacts, RENAME statement would create collissions between artifacts of same migration. This is now solved by assigning distinct timestamps to artifacts of same migration
- on the safe side, though there is no evidence this ever happened, whenever an artifact is added, we set cleanup_timestamp to be NULL
- #8498 
- #8499 
- #6926
=> Fixing multiple issues related to onlineddl/lifecycle

go/vt/schema/tablegc_test.go, go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go
Backport suggested by @deepthi in https://github.com/vitessio/vitess/pull/8500#issuecomment-884360924
Fixes #8498
Fixes #8499 (possibly)
- stale migration analysis did not update completed_timestamp. As result lifecycle would not run. Now that's fixed.
- retroactively updating completed_timestamp for existing NULL entries
- liveness_timestamp now always set with started_timestamp, so that it is never NULL even if migration didn't report liveness. This is essential for detecting and marking stale migrations
- when garbage collecting artifacts, RENAME statement would create collissions between artifacts of same migration. This is now solved by assigning distinct timestamps to artifacts of same migration
- on the safe side, though there is no evidence this ever happened, whenever an artifact …
=> Backport: Fixing multiple issues related to onlineddl/lifecycle

go/vt/vtgr/controller/refresh.go, go/vt/vtgr/controller/refresh_test.go, go/vt/vtgr/controller/repair.go, go/vt/vtgr/vtgr.go, go/vt/vtgr/vtgr_test.go
VTGR relies on the lock from topo server. Most of the topo lock uses health-check of session to determine if a process is still holding the lock. This is not ideal for lock release process during a restart with SIGHUP. Take consul as an example, the session check by default uses serfHealth, which is a health check on the node level - even if the process restart because the node is healthy, consul will think the lock is still being held until the TTL. As a result, during a deploy, there could be TTL period of time that VTGR cannot grab the lock and fix the cluster.
This PR handle the SIGHUP signal by explicitly release the lock that was held to avoid the situation above.
https://github.com/vitessio/vitess/issues/8386
=> Handle lock release with SIGHUP in VTGR

doc/vtadmin/api-server.md, doc/vtadmin/cluster-config.md, doc/vtadmin/clusters.yaml, doc/vtadmin/discovery.md, go/vt/vtadmin/README.md
This is all I had time to put together before a vacation, and something is better than nothing!
=> Initial pass at some vtadmin docs

examples/local/202_move_tables.sh, examples/local/203_switch_reads.sh, examples/local/204_switch_writes.sh, examples/local/205_clean_commerce.sh, examples/local/303_reshard.sh, examples/local/304_switch_reads.sh, examples/local/305_switch_writes.sh, examples/local/306_down_shard_0.sh, examples/region_sharding/203_reshard.sh, go/test/endtoend/recovery/pitr/shardedpitr_test.go, go/test/endtoend/vreplication/helper.go, go/test/endtoend/vreplication/resharding_workflows_v2_test.go, go/test/endtoend/vreplication/vreplication_test.go, go/vt/vtctl/vtctl.go, test/local_example.sh
This PR 
* makes v2 flows as the default and requires `-v1` to be specified to use the v1 `MoveTables` or `Reshard`
* changes the local examples to use the v2 vreplication CLI UX. 
* The vitess.io documentation has been updated at [https://github.com/vitessio/website/pull/784](https://github.com/vitessio/website/pull/784). It will be merged once 10.0 docs are archived.
* V1 tests have been modified to add the `v1` parameter to the `MoveTables` and `Reshard` vtctl commands
* V2 tests have been modified to remove the `v2` parameter to the vtctl commands
* A deprecation statement is displayed if the v1 commands are used
* The v2 flows have been around for over six months know. Since they are not the default, they have not seen a lot of usage in the field. So we continue to call the v2 flow …
=> Change local example to use v2 vreplication flows

go/vt/binlog/binlogplayer/binlog_player.go, go/vt/binlog/binlogplayer/dbclient.go, go/vt/binlog/binlogplayer/fake_dbclient.go, go/vt/discovery/tablet_picker.go, go/vt/vttablet/tabletmanager/vreplication/controller.go, go/vt/vttablet/tabletmanager/vreplication/utils.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go, go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
* Errors like duplicate key errors while bulk inserting during the copy phase can generate huge log lines. Since we also write to `_vt.vreplication_log` that table also gets filled up fast since we keep retrying within vreplication. This PR truncates the logs both in the file logs and in the `_vt.vreplication_log` table
* The logic for updating count of recurring errors in `_vt.vreplication_log` was not working because the controller would set the state of the restarted workflow again, which was getting logged to `_vt.vreplication_log` alternating with the actual error. This has been fixed by ignoring this spurious state change log
* Some unnecessary/repetitive log lines have been removed
One reason why log files were filling up is that we retry the workflow on error every 5 seconds, by …
=> Fix VReplication logging to file and db

go/test/endtoend/cluster/vtctl_process.go, go/test/endtoend/vreplication/config.go, go/vt/binlog/binlogplayer/binlog_player.go, go/vt/binlog/binlogplayer/dbclient.go, go/vt/binlog/binlogplayer/fake_dbclient.go, go/vt/discovery/tablet_picker.go, go/vt/discovery/tablet_picker_test.go, go/vt/vtgate/evalengine/arithmetic.go, go/vt/vtgate/evalengine/arithmetic_test.go, go/vt/vtgate/vindexes/consistent_lookup_test.go, go/vt/vttablet/tabletmanager/vreplication/controller.go, go/vt/vttablet/tabletmanager/vreplication/stats.go, go/vt/vttablet/tabletmanager/vreplication/utils.go, go/vt/vttablet/tabletmanager/vreplication/vplayer.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go, go/vt/vttablet/tabletmanager/vreplication/vreplicator.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go, go/vt/wrangler/vdiff.go
Backport of the following PRs from main into release 11.0:
* https://github.com/vitessio/vitess/pull/8403
Tablet Picker: add metric to record lack of available tablets
* https://github.com/vitessio/vitess/pull/8396
Ignore SBR statements from pt-table-checksum
* https://github.com/vitessio/vitess/pull/8483
Fix vreplication error metric
* https://github.com/vitessio/vitess/pull/8489
Return from throttler goroutine if context is cancelled to prevent goroutine leaks
* https://github.com/vitessio/vitess/pull/8401
VDiff: Add BIT datatype to list of byte comparable types 
* https://github.com/vitessio/vitess/pull/8521
Fix VReplication logging to file and db
=> Backports of #8403 #8483 #8489 #8401 #8521 #8396 from main into release 11.0

go/mysql/endtoend/schema_change_test.go, go/mysql/schema.go, go/test/endtoend/vtgate/schematracker/sharded/st_sharded_test.go, go/vt/vttablet/tabletserver/health_streamer.go
This pull request makes VTTablet clear only the rows that match the current database name and the updated tables in `schemacopy` ; instead of clearing all the rows that match the updated tables. This will be useful for @GuptaManan100 when testing the Rails guide against a sharded cluster. 
VTTestServer uses a single MySQL instance where the different shards are suffixed in the `table_schema` column by their name (`-80`, `80-`, etc). Removing all the rows from the `schemacopy` tables was making the shards not agreeing and made them repetitively send schema updates to VTGate.
After testing VTTestServer with schema tracking enabled: it is preferable to lower the schema update interval in the VTTablets or add multiple timeouts in the Rails test suite. 
Resolves #8510
=> Clear only the current shard's schemacopy rows  during schema reload

.github/workflows/cluster_endtoend_upgrade.yml
This pull request changes the `cluster_endtoend_upgrade` workflow (`Cluster (upgrade)`) by dynamically choosing the Vitess tag on which to downgrade/upgrade the cluster.
=> Automatically use the latest tag of Vitess for cluster upgrade E2E test

go/test/endtoend/reparent/reparent_test.go, go/vt/vtctl/reparentutil/planned_reparenter.go
Report an informative error message if there is no replica in primary's cell to PRS to.
Fixes #8528 
=> Enhance PRS error message

go/vt/vtcombo/tablet_map.go, go/vt/vttablet/faketmclient/fake_client.go, go/vt/vttablet/tmclient/rpc_client_api.go
Since we introduced new RPCs in #8473, #8512, #8513 and #8520 we need corresponding functions in the client interface.
#7114
=> naming: deprecate funcs and add new ones in TabletManagerClient interface

.github/workflows/cluster_endtoend_vstream_failover.yml, go/test/endtoend/vreplication/vstream_test.go, go/vt/discovery/tablet_picker.go, go/vt/topo/tablet.go, go/vt/vtgate/discoverygateway.go, go/vt/vtgate/vstream_manager.go, go/vt/vtgate/vstream_manager_test.go, test/ci_workflow_gen.go, test/config.json
Currently the VStream API can specify a tablet type (MASTER or REPLICA) to stream from. In cases where the tablet stops serving (crash/manually shut down) and there are no more tablets of that type then it errors out and the client has to retry. While this is an inconvenience it is not a huge issue since, in any case, users have to handle network errors and maintain state to resume the streaming. 
However there are a couple of issues not handled correctly:
* when there is a reparent (say we are streaming from the primary and it is now deemed to be a replica, or vice-versa), but the tablet itself is  healthy and its type has changed.
* when there is a large underlying replication lag and the tablet is unhealthy but still serving
In such cases we continue to stream events from the current …
=> VStream API: handle reparenting and unhealthy tablets

doc/releasenotes/11_0_0_release_notes.md, go/vt/servenv/version.go, java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/jdbc/pom.xml, java/pom.xml
=> Vitess  Release 11.0.0
