- go/mysql/conn.go
- go/mysql/conn_test.go
- go/mysql/query.go
- go/mysql/query_test.go
- go/vt/wrangler/materializer.go
Moving the changes from 8.0 to 9.0
> Merge 8.0 into 9.0

- go/vt/vtexplain/vtexplain_vttablet.go
- go/vt/vttablet/onlineddl/executor.go
- go/vt/vttablet/onlineddl/schema.go
This is to avoid vtexplain tests being flaky.
> Add online ddl on start queries to schema list in vtexplain tablet

- .github/workflows/build_github_docker_images.yml
Initial GitHub Docker Build Setup
https://github.com/vitessio/builds/issues/1
> Initial GitHub Docker Build Setup

- go/test/fuzzing/oss_fuzz_build.sh
- go/vt/vtgate/grpcvtgateconn/fuzz_flaky_test.go
Fixes the broken OSS-fuzz coverage build.
> fuzzing: Fix OSS-fuzz coverage build

- web/vtadmin/src/api/http.ts
- web/vtadmin/src/components/App.tsx
- web/vtadmin/src/components/NavRail.tsx
- web/vtadmin/src/components/pips/BackupStatusPip.tsx
- web/vtadmin/src/components/routes/Backups.tsx
- web/vtadmin/src/hooks/api.ts
- web/vtadmin/src/util/backups.ts
This is a very hasty (but solid!) UI on top of the /api/backups endpoint added in https://github.com/vitessio/vitess/pull/8301. 
I don't have any screenshots to share this time, unfortunately, since we haven't configured this for the local example. It looks like pretty much every other list view. :) 
- https://github.com/vitessio/vitess/pull/8301
> [vtadmin-web] Add Backups view

- doc/releasenotes/10_0_1_release_notes.md
- doc/releasenotes/10_0_2_release_notes.md
- doc/releasenotes/11_0_0_release_notes.md
- doc/releasenotes/9_0_1_release_notes.md
- doc/releasenotes/9_0_2_release_notes.md
Adds release notes for the upcoming release 11 and for older branches as well
> Add release notes for all the versions

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Incrementing version number from `11.0.0-SNAPSHOT` to `12.0.0-SNAPSHOT`.
> Incrementing to release 12.0.0-SNAPSHOT

- go/mysql/mysql56_gtid_set.go
- go/mysql/mysql56_gtid_set_test.go
- go/mysql/replication_status.go
- go/test/endtoend/reparent/reparent_test.go
- go/vt/vttablet/tabletmanager/rpc_replication.go
> Merge release 8.0 into 9.0

- go/test/endtoend/onlineddl/exec_util.go
- go/test/endtoend/onlineddl/vrepl_stress/onlineddl_vrepl_mini_stress_test.go
- go/test/endtoend/onlineddl/vtgate_util.go
- go/vt/vttablet/onlineddl/executor.go
> Merge release-11.0 into main

- go/vt/vtexplain/vtexplain_vttablet.go
- go/vt/vttablet/onlineddl/executor.go
- go/vt/vttablet/tabletserver/query_executor_test.go
- go/vt/vttablet/tabletserver/tabletenv/config.go
- go/vt/vttablet/tabletserver/tabletenv/config_test.go
Adds flag to vttablet to disallow online DDL statements. It is used in vtexplain.
> Adds flag to vttablet to disallow online DDL statements

- go/vt/vtgate/planbuilder/queryprojection.go
- go/vt/vtgate/planbuilder/queryprojection_test.go
> query projection test

- .github/workflows/cluster_endtoend_mysql80.yml
- go/test/endtoend/vtgate/main_test.go
- go/test/endtoend/vtgate/misc_test.go
- go/test/endtoend/vtgate/mysql80/main_test.go
- go/test/endtoend/vtgate/mysql80/misc_test.go
- go/vt/sqlparser/ast_format.go
- go/vt/sqlparser/ast_format_fast.go
- go/vt/sqlparser/ast_funcs.go
- go/vt/sqlparser/parse_test.go
- go/vt/vtgate/planbuilder/testdata/ddl_cases.txt
- go/vt/vttablet/tabletserver/planbuilder/testdata/exec_cases.txt
- test/ci_workflow_gen.go
- test/config.json
Forward port for the PRs #8425 and #8442 
- Fixes #8424 in release-10.0
> Fix for function calls in DEFAULT value of CREATE TABLE statement in release-10.0

- go/vt/topo/consultopo/lock.go
- go/vt/topo/consultopo/server.go
- go/vt/topo/consultopo/server_flaky_test.go
When Consul creates lock, it needs to create a session for the lock. By default, session uses serfHealth check for liveness check: https://www.consul.io/api-docs/session, which is a node level healthy-check from gossip protocal. 
This means when the process restarted, if the node is still healthy, the session will remain alive up to 2*TTL (15sec) = 30 sec - during this period of time, other process cannot get the lock.
To address that, this PR exposes an optional flag to pass in customized session checks so the the session will expire automatically once the health check failed.
https://github.com/vitessio/vitess/issues/8297
> Expose topo_consul_lock_session_checks to allow customized consul session check

- .github/workflows/cluster_endtoend_mysql80.yml
- go/test/endtoend/onlineddl/vrepl_suite/testdata/enum/alter
- go/test/endtoend/vtgate/main_test.go
- go/test/endtoend/vtgate/misc_test.go
- go/test/endtoend/vtgate/mysql80/main_test.go
- go/test/endtoend/vtgate/mysql80/misc_test.go
- go/vt/sqlparser/ast_format.go
- go/vt/sqlparser/ast_format_fast.go
- go/vt/sqlparser/ast_funcs.go
- go/vt/sqlparser/parse_test.go
- go/vt/vtgate/planbuilder/testdata/ddl_cases.txt
- go/vt/vttablet/tabletserver/planbuilder/testdata/exec_cases.txt
- test/ci_workflow_gen.go
- test/config.json
Forward port for the PR #8476 
- Fixes #8424
> Fix for function calls in DEFAULT value of CREATE TABLE statement in main

- go/vt/vtgate/planbuilder/abstract/queryprojection_test.go
- go/vt/vtgate/semantics/analyzer.go
Very small change to make it easier to find where an error is produced.
> improve the Gen4NotSupportedF error

- go/vt/vtadmin/grpcserver/server.go
What it says in the title. This is an extraction from a longer running branch that can be merged in isolation.
> Add support for passing custom interceptors to vtadmin grpcserver

- go/vt/sqlparser/ast_format.go
- go/vt/sqlparser/ast_format_fast.go
- go/vt/sqlparser/parse_test.go
> boolean values should not be parenthesised in default clause - release 11

- go/test/endtoend/cluster/topo_process.go
- go/test/endtoend/topotest/consul/main_test.go
- go/vt/srvtopo/resilient_server.go
- go/vt/srvtopo/resilient_server_test.go
> [11.0] query serving to continue when topo server restarts

- go/mysql/auth_server.go
- go/mysql/server.go
This change fixes the handshake protocol with the MySQL client. The 8.0.25 and earlier MySQL client will always send `caching_sha2_password` as the default (if not configured otherwise), but it won't yet send the actual scramble.
That handshake indicates that the client does support that method, but it doesn't send any yet sensitive information over the wire. Our current logic assumes that if a certain method is sent by the client, it also sends a complete authentication plugin data, but that's not the case.
The way to request the client to send the full data is to return an auth switch packet with the same method again.
This change fixes any auth server that tries to implement multiple methods at once like mysql_native_password and caching_sha2_password so it doesn't error out on clients …
> Fix handshake protocol with MySQL client

- go/test/endtoend/cluster/topo_process.go
- go/test/endtoend/topotest/consul/main_test.go
- go/vt/srvtopo/resilient_server.go
- go/vt/srvtopo/resilient_server_test.go
> query serving to continue when topo server restarts - main

- go/vt/vtgate/vtgate.go
Disable changing system settings without allowing it explicitly.
> [11.0] Disable allowing set statements on system settings by default

- doc/releasenotes/11_0_0_release_notes.md
Updated the release notes for version 11 with the newest changes on the `release-11` branch since we tagged RC-1.
> Updated release 11 notes with newest changes since RC1

- go/vt/vtgate/semantics/semantic_state.go
Tries to use the dependency cache for more types.
> gen4: make sure to check for cached values in more places

- go/vt/vtgate/planbuilder/abstract/join.go
- go/vt/vtgate/planbuilder/abstract/left_join.go
- go/vt/vtgate/planbuilder/abstract/querygraph.go
- go/vt/vtgate/planbuilder/abstract/queryprojection.go
- go/vt/vtgate/planbuilder/abstract/queryprojection_test.go
- go/vt/vtgate/planbuilder/expand_star_test.go
- go/vt/vtgate/planbuilder/horizon_planning.go
- go/vt/vtgate/planbuilder/jointree.go
- go/vt/vtgate/planbuilder/route_planning.go
- go/vt/vtgate/planbuilder/testdata/select_cases.txt
- go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
- go/vt/vtgate/semantics/analyzer.go
- go/vt/vtgate/semantics/analyzer_test.go
- go/vt/vtgate/semantics/semantic_state.go
Adds support for resolving columns using column vindexes in Gen4
#7280
> Adds support for resolving columns using column vindexes in Gen4

- go/vt/vtgate/engine/ordered_aggregate.go
- go/vt/vtgate/planbuilder/plan_test.go
- go/vt/vtgate/semantics/analyzer.go
- go/vt/vtgate/semantics/binder.go
- go/vt/vtgate/semantics/scoper.go
- go/vt/vtgate/semantics/table_collector.go
- go/vt/vtgate/semantics/typer.go
Splits up the big complex `analyzer.go` into smaller pieces that should be easier to understand.
#7280
> gen4: Refactoring of semantic analysis

- go/test/endtoend/vtgate/unsharded/main_test.go
- go/vt/sqlparser/ast_funcs.go
- go/vt/sqlparser/parse_test.go
This PR fixes the parenthesising of negative float values to emulate MySQL behaviour
- Fixes #8574
> Negative float default

- examples/legacy_local/101_initial_cluster.sh
- examples/legacy_local/201_customer_keyspace.sh
- examples/legacy_local/205_vertical_migrate_master.sh
- examples/legacy_local/206_clean_commerce.sh
- examples/legacy_local/305_migrate_master.sh
- examples/legacy_local/scripts/vtgate-up.sh
- examples/local/101_initial_cluster.sh
- examples/local/204_switch_writes.sh
- examples/local/305_switch_writes.sh
- examples/local/orc_test.sh
- examples/local/scripts/vtgate-up.sh
- examples/region_sharding/201_main_sharded.sh
- examples/region_sharding/202_new_tablets.sh
- examples/region_sharding/203_reshard.sh
- examples/region_sharding/205_switch_writes.sh
- examples/region_sharding/scripts/vtgate-up.sh
> Inclusive Naming: Change master to primary in examples:local,legacy_local,region_sharding

- doc/vitess_api_reference.py
- doc/vtctl_go_reference.py
- go/vt/discovery/utils_test.go
- go/vt/wrangler/testlib/external_reparent_test.go
- go/vt/wrangler/testlib/find_tablet_test.go
A few files still had the old copyright from pre-CNCF days.
None
> fix copyright

- go/vt/vtexplain/testdata/multi-output/unsharded-output.txt
- go/vt/vtexplain/testdata/twopc-output/unsharded-output.txt
- go/vt/vtexplain/testdata/unsharded-queries.sql
- go/vt/vtexplain/vtexplain_vttablet.go
Signed-off-by: Saimadhav Heblikar <saimadhavheblikar@gmail.com>
#8348
> [vtexplain] prevent panic on show tables/show full tables

- go/vt/vtgate/planbuilder/route_planning.go
- go/vt/vtgate/planbuilder/testdata/from_cases.txt
- go/vt/vtgate/planbuilder/testdata/lock_cases.txt
- go/vt/vtgate/planbuilder/testdata/select_cases.txt
- go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
- go/vt/vtgate/semantics/analyzer.go
Gen4 plan for dual table query and locking function.
#7280
> Gen4: Dual table query processing at vtgate and locking function support

- go/vt/vttablet/onlineddl/executor.go
Backport of #8624 to release-11.0 branch
#8655
> onlineddl Executor: build schema with DBA user

- go/vt/wrangler/materializer.go
Forward port of #8373 to main
#8656
> Refresh SrvVSchema after an ExternalizeVindex: was missing

- go/vt/vtgate/planbuilder/gen4_planner.go
- go/vt/vtgate/planbuilder/horizon_planning.go
- go/vt/vtgate/planbuilder/rewrite.go
- go/vt/vtgate/planbuilder/rewrite_test.go
- go/vt/vtgate/planbuilder/route_planning.go
- go/vt/vtgate/planbuilder/testdata/aggr_cases.txt
- go/vt/vtgate/planbuilder/testdata/postprocess_cases.txt
- go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
- go/vt/vtgate/planbuilder/testdata/wireup_cases.txt
- go/vt/vtgate/semantics/analyzer.go
- go/vt/vtgate/semantics/analyzer_test.go
- go/vt/vtgate/semantics/binder.go
- go/vt/vtgate/semantics/scoper.go
- go/vt/vtgate/semantics/semantic_state.go
Add support for having clause in Gen4 plan.
- #7280 
- Closes https://github.com/vitessio/vitess/issues/8576
> Gen4: Having clause support

- go/mysql/mysql56_gtid_set.go
- go/mysql/mysql56_gtid_set_test.go
- go/mysql/replication_status.go
- go/test/endtoend/reparent/reparent_test.go
- go/vt/vttablet/tabletmanager/rpc_replication.go
Some fixups for conflicts during merge to align with new naming.
> Port #8422 to main branch

- go/vt/vtgate/planbuilder/rewrite.go
- go/vt/vtgate/planbuilder/route_planning.go
- go/vt/vtgate/planbuilder/route_planning_test.go
- go/vt/vtgate/planbuilder/testdata/filter_cases.txt
- go/vt/vtgate/planbuilder/testdata/postprocess_cases.txt
- go/vt/vtgate/planbuilder/testdata/tpcc_cases.txt
- go/vt/vtgate/planbuilder/testdata/tpch_cases.txt
- go/vt/vtgate/semantics/semantic_state.go
This PR adds support for the remaining queries with subqueries in Gen4
#7280
> Support for remaining subquery queries in Gen4

- Makefile
> Backport to 11: Updated Makefile do_release script to include godoc steps

- doc/releasenotes/11_0_1_release_notes.md
11.0.1 Release Notes
Latest release notes for 11.0.1
> 11.0.1 Release Notes

- examples/local/scripts/vtadmin-up.sh
- examples/local/vtadmin/rbac.yaml
> Update vtadmin local scripts to enable basic rbac

- go/stats/statsd/statsd.go
Signed-off-by: Yang Wu <y.wu4515@gmail.com>
We used to only export certain metrics for memstats in stastd.
Instead we should export all that's available
https://github.com/vitessio/vitess/issues/8776
> Export memstats for statsd backend

- go/vt/vttablet/onlineddl/vrepl.go
- go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
Backport of https://github.com/vitessio/vitess/pull/8763 to the release-11.0 branch.
https://github.com/vitessio/vitess/issues/8759
> Fix how we identify MySQL generated columns

- go/vt/vtgate/planbuilder/route_planning.go
- go/vt/vtgate/planbuilder/testdata/select_cases.txt
This pull request allows merging duals with other routes.
- #7280
> Gen4: Merge duals

- go/vt/vtgate/planbuilder/testdata/aggr_cases.txt
- go/vt/vtgate/planbuilder/testdata/ddl_cases.txt
- go/vt/vtgate/planbuilder/testdata/ddl_cases_no_default_keyspace.txt
- go/vt/vtgate/planbuilder/testdata/from_cases.txt
- go/vt/vtgate/planbuilder/testdata/postprocess_cases.txt
- go/vt/vtgate/planbuilder/testdata/select_cases.txt
- go/vt/vtgate/planbuilder/testdata/systemtables_cases.txt
- go/vt/vtgate/planbuilder/testdata/tpch_cases.txt
- go/vt/vtgate/planbuilder/testdata/union_cases.txt
- go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
- go/vt/vtgate/planbuilder/testdata/vindex_func_cases.txt
Updated all valid plan output
#7280
> Gen4: added all valid plan output

- examples/local/README.md
- examples/operator/README.md
- vitess-mixin/tools.go
When we made the v2 syntax the new default, all the scripts in `examples/local` were updated but not the README file.
The README file in `examples/operator` also needed to be updated because the old syntax doesn't work any more (unless you provide `-v1` as a flag)
#8553
> examples: update README to use new vreplication command syntax

- MAINTAINERS.md
Adding @GuptaManan100 to maintainers.
> add Manan to maintainers

- web/vtadmin/src/components/routes/Tablets.test.tsx
- web/vtadmin/src/components/routes/Tablets.tsx
- web/vtadmin/src/components/routes/keyspace/KeyspaceShards.test.tsx
> [vtadmin] s/master/primary in vtadmin frontend code

- go/test/endtoend/cluster/cluster_process.go
- go/vt/vtgate/planbuilder/from.go
- go/vt/vtgate/planbuilder/horizon_planning.go
- go/vt/vtgate/planbuilder/ordering.go
- go/vt/vtgate/planbuilder/route.go
- go/vt/vtgate/planbuilder/select.go
- go/vt/vtgate/planbuilder/testdata/onecase.txt
- go/vt/vtgate/planbuilder/testdata/union_cases.txt
- go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
- go/vt/vtgate/semantics/analyzer.go
- go/vt/vtgate/semantics/analyzer_test.go
- go/vt/vtgate/semantics/binder.go
- go/vt/vtgate/semantics/dependencies.go
- go/vt/vtgate/semantics/derived_table.go
- go/vt/vtgate/semantics/early_rewriter.go
- go/vt/vtgate/semantics/real_table.go
- go/vt/vtgate/semantics/scoper.go
- go/vt/vtgate/semantics/semantic_state.go
- go/vt/vtgate/semantics/table_collector.go
- go/vt/vtgate/semantics/vindex_table.go
- go/vt/vtgate/semantics/vtable.go
This pull request improves the overall logic and readability of the analyzer. In addition to that, issue #8831 is fixed through this pull request.
- #7280
- Fixes #8831
> Gen4: improve analyzer's logic

- go/vt/vttablet/tabletserver/tabletenv/config.go
- go/vt/vttablet/tabletserver/tabletenv/config_test.go
> Fix typo in pool config syntax.  Fixes #8819

- .github/docker/unit_test_race/Dockerfile
- .github/workflows/unit_race.yml
This pull request moves the `unit_race` CI workflow to the self-hosted runners in order to reduce its flakiness.
> Move unit test race to self hosted runners

- go/vt/sqlparser/parse_test.go
- go/vt/vtgate/planbuilder/abstract/queryprojection.go
- go/vt/vtgate/planbuilder/abstract/queryprojection_test.go
- go/vt/vtgate/planbuilder/testdata/from_cases.txt
- go/vt/vtgate/planbuilder/testdata/select_cases.txt
- go/vt/vtgate/semantics/analyzer.go
This PR fails the wrong usage pf next val statements.
- #7280
> added checks for next val misplaced statements and validate the table is sequence table

- go/vt/vtctl/vtctl.go
Updated CLI usage and help statements for Reshard/MoveTables and Workflow for v2
> vtctl help/usage update

- go/vt/discovery/keyspace_events.go
- go/vt/vtgate/tabletgateway.go
While I was answering questions by @sonne5 in https://github.com/vitessio/vitess/pull/8700, I noticed the code is not clear enough to be merged without comments. I described the consolidation algorithm in this PR with more detail.
- https://github.com/vitessio/vitess/pull/8700
> discovery: document KeyspaceEventWatcher

- web/vtctld2/src/app/dashboard/shard.component.ts
- web/vtctld2/src/app/dashboard/tablet.component.html
- web/vtctld2/src/app/dashboard/tablet.component.ts
Signed-off-by: zhaochen72 <zhaochen5@jd.com>
Fixes https://github.com/vitessio/vitess/issues/8888
> fix Unknown command StartSlave and StopSlave

- doc/releasenotes/12_0_0_summary.md
In #8877, we enhanced the release notes generation to be able to take a file and add it at the top of the generated release notes.
This is the first version of such a summary for the upcoming release 12.0
#8877
> add summary notes v1 for 12.0 release

- web/vtadmin/package-lock.json
This updates the browserlist version to keep our [target browsers](https://github.com/tinyspeck/vitess/blob/2b8a026ce9d89b07a41b071c89cbd3bb8cccf12d/web/vtadmin/package.json#L58-L69) up to date; see https://github.com/browserslist/browserslist#browsers-data-updating. 
N/A
N/A
> [vtadmin-web] Update browserslist

- doc/releasenotes/12_0_0_release_notes.md
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Release v12 commits
- Release notes updated
- Release Snapshot move updated
> Release 12.0.0 GA

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Incrementing version number from `12.0.0-SNAPSHOT` to `13.0.0-SNAPSHOT`.
> Incrementing to release 13.0.0-SNAPSHOT

- go/vt/vtgate/engine/ordered_aggregate_test.go
- go/vt/vtgate/evalengine/arithmetic.go
- go/vt/vtgate/evalengine/arithmetic_test.go
Fixes an error that crept in by merging two separate PRs
> fix compilation error on main

- doc/releasenotes/12_0_0_summary.md
Add information regarding default flag change of `enable_system_settings` 
https://github.com/vitessio/website/pull/862
> Add enable_system_settings flag change to 12.0.0 release summary 

- go.mod
- go.sum
Upgrades go-fuzz-headers to include latest APIs.
> Fuzzing: Upgrade go-fuzz-headers

- doc/releasenotes/12_0_0_summary.md
Add information regarding default flag change of enable_system_settings
- backport of https://github.com/vitessio/vitess/pull/9144
> [12.0] Add enable_system_settings flag change to 12.0.0 release summary

- MAINTAINERS.md
* Updates email in the maintainer list
> Email update for Rafael Chacón

- go/vt/topo/faketopo/faketopo.go
A small issue crept in after merging a PR yesterday. This is trying to fix the issue.
#9182
> Fix main build error

- go/vt/vttablet/tabletserver/messager/engine.go
- go/vt/vttablet/tabletserver/messager/engine_test.go
- go/vt/vttablet/tabletserver/messager/message_manager.go
- go/vt/vttablet/tabletserver/messager/message_manager_test.go
- go/vt/vttablet/tabletserver/tabletserver.go
- go/vt/vttablet/tabletserver/tabletserver_test.go
> Backport to v12: messager: cleanup interdependecies

- test/local_example.sh
> Backport 9211: Fix local change that was committed erroneously

- misc/git/hooks/golangci-lint
Fix the `paste` command used in linter.
> fix: paste command in linter

- go/test/endtoend/reparent/plannedreparent/reparent_test.go
This PR adds an e2e test verifying that a drained lagging tablet does not fail PRS
- https://github.com/vitessio/vitess/issues/7000
> Add test to PRS with Drained tablet

- go/test/endtoend/preparestmt/stmt_methods_test.go
- go/test/endtoend/vtgate/misc_test.go
- go/vt/vtgate/executor.go
this pull request handles show statement in prepare calls.
- fixes #9268
> Fix show statement in prepare call

- examples/operator/README.md
Add a note and example of how to edit the YAML file for pointing to MySQL 8.0 Vitess builds.
> Update vtop README file for MySQL 80

- go/vt/vtexplain/vtexplain.go
- go/vt/vtgate/executor.go
- go/vt/vtgate/plan_execute.go
- go/vt/vtgate/safe_session.go
- go/vt/vtgate/vcursor_impl.go
Some refactor on rollback on partial query execution code.
- #9266
> refactor: more cleaner rollback on error code with additional comments

- doc/releasenotes/12_0_1_release_notes.md
- doc/releasenotes/12_0_1_summary.md
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This pull request follows the release of v12.0.1. We are incrementing the patch release number in the version and pom.xml files as well as adding the release notes documents.
> Patch release 12.0.1 update

- doc/releasenotes/11_0_2_release_notes.md
- doc/releasenotes/11_0_2_summary.md
This pull request updates the release note documents following the release of v11.0.2.
> Release note documents for v11.0.2

- doc/releasenotes/12_0_1_release_notes.md
- doc/releasenotes/12_0_1_summary.md
This pull request updates the release note documents following the release of v12.0.1.
> Release note documents for v12.0.1

- doc/releasenotes/11_0_2_release_notes.md
- doc/releasenotes/11_0_2_summary.md
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This pull request follows the release of v11.0.2. We are incrementing the patch release number in the version and pom.xml files as well as adding the release notes documents.
> Patch release 11.0.2 update

- go/test/endtoend/vtorc/utils/utils.go
- test/config.json
Fix Vtorc CI configuration file to run all the tests. Also, this PR disables the super-read-only flag on vtorc tests, since the tests use DDLs to clean the mysql instances before reusing them.
> Fix vtorc tests ci

- doc/releasenotes/11_0_3_release_notes.md
- doc/releasenotes/11_0_3_summary.md
This pull request follows the release of v11.0.3 by adding the corresponding release notes documents to the docs.
> Addition of the release notes documents for 11.0.3

- doc/releasenotes/11_0_3_release_notes.md
- doc/releasenotes/11_0_3_summary.md
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This pull request follows the v11.0.3 patch release by adding the related release notes documents to the release-11.0 branch.
> Update release notes with v11.0.3

- doc/releasenotes/12_0_2_release_notes.md
- doc/releasenotes/12_0_2_summary.md
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This pull request follows the v12.0.2 patch release by adding the related release notes documents to the release-12.0 branch.
> Update release notes with v12.0.2

- doc/releasenotes/12_0_2_release_notes.md
- doc/releasenotes/12_0_2_summary.md
This pull request follows the release of v12.0.2 by adding the corresponding release notes documents to the docs.
> Addition of the release notes documents for v12.0.2

- doc/releasenotes/10_0_3_release_notes.md
- doc/releasenotes/10_0_3_summary.md
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This pull request follows the release of v10.0.3. We are incrementing the patch release number in the version and pom.xml files as well as adding the release notes documents.
> Patch release 10.0.3 update 

- doc/releasenotes/10_0_3_release_notes.md
- doc/releasenotes/10_0_3_summary.md
This pull request updates the release note documents following the release of v10.0.3.
> Release note documents for v10.0.3

- doc/releasenotes/10_0_4_release_notes.md
- doc/releasenotes/10_0_4_summary.md
This pull request follows the release of `v10.0.4` by adding the corresponding release notes documents to the docs.
> Addition of the release notes documents for 10.0.4

- doc/releasenotes/10_0_4_release_notes.md
- doc/releasenotes/10_0_4_summary.md
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This pull request follows the `v10.0.4` patch release by adding the related release notes documents to the `release-10.0` branch.
> Update release notes with v10.0.4

- go/vt/mysqlctl/fakemysqldaemon/fakemysqldaemon.go
- go/vt/vtgate/scatter_conn_test.go
- go/vt/wrangler/materializer_test.go
- go/vt/wrangler/resharder_test.go
- go/vt/wrangler/tablet.go
- go/vt/wrangler/testlib/semi_sync_test.go
- go/vt/wrangler/vdiff_env_test.go
> Replace master with primary

- go/vt/vtctl/grpcvtctldserver/testutil/util.go
- go/vt/vtctl/grpcvtctldserver/topo.go
- go/vt/vtctl/reparentutil/emergency_reparenter.go
- go/vt/vtctl/vtctl.go
> changed master to primary

- go/vt/vttablet/tabletmanager/tm_init_test.go
This PR fixes the flakiness in the tm_state_test file. This flakiness was traced to there being a race condition between 2 different runs of `RefreshFromTopoInfo`. The flakiness is fixed by altering the wait condition in the initialization phase of the tests.
> Fix flakiness in tm_state_test

- GOVERNANCE.md
- STEERING.md
> Steering committee doc

- doc/releasenotes/10_0_0_release_notes.md
- doc/releasenotes/10_0_1_release_notes.md
- doc/releasenotes/10_0_2_release_notes.md
- doc/releasenotes/10_0_3_release_notes.md
- doc/releasenotes/10_0_3_summary.md
- doc/releasenotes/10_0_4_release_notes.md
- doc/releasenotes/10_0_4_summary.md
This pull request updates the release 10 notes with regard to the latest log4j update (`2.17.1`) and the known issue (#9174).
> [10.0] Update 10.0 release notes

- doc/releasenotes/11_0_4_release_notes.md
- doc/releasenotes/11_0_4_summary.md
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This pull request contains the changes made while releasing `v11.0.4`.
> [11.0] Release `v11.0.4` changes

- doc/releasenotes/12_0_3_release_notes.md
- doc/releasenotes/12_0_3_summary.md
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This pull request contains the changes made while releasing `v12.0.3`.
> [12.0] Release `v12.0.3` changes

- doc/releasenotes/10_0_5_release_notes.md
- doc/releasenotes/10_0_5_summary.md
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This pull request includes the changes made during the release of `v10.0.5`.
> [10.0] Release `v10.0.5` changes

- doc/releasenotes/10_0_0_release_notes.md
- doc/releasenotes/10_0_1_release_notes.md
- doc/releasenotes/10_0_2_release_notes.md
- doc/releasenotes/10_0_3_release_notes.md
- doc/releasenotes/10_0_3_summary.md
- doc/releasenotes/10_0_4_release_notes.md
- doc/releasenotes/10_0_4_summary.md
- doc/releasenotes/10_0_5_release_notes.md
- doc/releasenotes/10_0_5_summary.md
This pull request updates the release 10 notes with regard to the latest log4j update (2.17.1) and the known issue (#9174).
> Update 10.0 release notes

- go/vt/vtgate/simplifier/simplifier.go
- go/vt/vtgate/simplifier/simplifier_test.go
Clean up of the simplifier by removing all the goroutine and sync stuff in the code.
> Refactor of simplifier

- doc/releasenotes/12_0_0_release_notes.md
- doc/releasenotes/12_0_0_summary.md
- doc/releasenotes/12_0_1_release_notes.md
- doc/releasenotes/12_0_1_summary.md
- doc/releasenotes/12_0_2_release_notes.md
- doc/releasenotes/12_0_2_summary.md
This pull request updates the 12.0 release notes on `release-12.0` to mirror what's written on the releases page and the main branch.
> [12.0] Mirror the 12.0 release notes with the releases page and `main`

- go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
This is a trivial follow-up to https://github.com/vitessio/vitess/pull/9505
We should `defer` the reset function _before_ checking the error just to be extra safe (even though the connection/session in use should be closed anyway). When doing this we should not return `nil` for the reset function or we'll get a `SEGFAULT` when leaving the stack frame.
/HT to @shlomi-noach as I think he tried to help me avoid this in the initial PR but I missed it. 🙂 
- Follow-up to: https://github.com/vitessio/vitess/pull/9505
> Additional safety in vreplicator sql_mode handling

- doc/releasenotes/13_0_0_summary.md
Moved the `vtctl/vtctlclient ApplySchema` enhancement to the proper section.
> Reorganized v13.0 summary notes

- go/mysql/client_test.go
- go/mysql/conn.go
Changed `t.Errorf` and `t.Fatalf` statements to `assert`, `require`, and so on.
Also fixed a linter error in `conn.go`.
> Changed to assert and require for tests

- examples/operator/README.md
More detailed example of how to use mysql80 images
None
> examples: how to use mysql80 images with operator

- go/vt/vttablet/tabletserver/schema/engine.go
This flag sets twice in near lines
> Fix: removed flag set duplicate

- GUIDING_PRINCIPLES.md
Remove reference to PMC
#9366 #9478
> Remove reference to PMC

- doc/releasenotes/13_0_0_summary.md
We have new stuff to talk about!
cc @frouioui @deepthi
> releasenotes: improve 13.0 summary

- go/test/endtoend/vtorc/general/vtorc_test.go
- go/test/endtoend/vtorc/utils/test_config_semi_sync.json
- go/test/endtoend/vtorc/utils/utils.go
This PR adds a test to the vtorc test suite verifying that vtorc fixes semi-sync on a tablet if it is not correctly set.
- #6769
> Adds a test for checking vtorc fixes semi-sync correctly

- java/pom.xml
This PR updates the java dependencies of major components.
> java: updates all major dependencies to latest

- go/cache/cache.go
- go/cache/lru_cache.go
- go/cache/lru_cache_test.go
- go/cache/null.go
- go/cache/ristretto/cache.go
- go/vt/vtgate/executor.go
> Add hit/miss tracking for vtgate plan cache

- java/pom.xml
This PR fixes the java release issues by fixing the pom
> java: fixes java release

- doc/releasenotes/13_0_0_release_notes.md
This adds the contributors to the 13.0 release notes (got lost in the mix)
> Add contributors to 13.0 release notes

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Moving dev/main to 14.0.0-SNAPSHOT now that 13.0.0-rc1 is released.
> Moving dev to 14.0.0-SNAPSHOT

- .github/CODEOWNERS
Adding @notfelineit to all the things! Frances, I just added you to everything that I'm added to, but you can absolutely feel free to tweak this as you like! 
I wish this had a nicer benefit than "more emails than you ever wanted" but 😎 
N/A
N/A
> Add @notfelineit to CODEOWNERS

- go/stats/counter.go
`Set` function was introduced for a Counter type in #9609. The comment for this change was missed and is added in this PR.
> Add a comment on how to use set for a counter

- MAINTAINERS.md
Needed to do this anyway, and it's an excuse to test out my ssh signing and remember how to do PRs with all the labels here.
(looks like github's signature verification doesn't support [ssh signing](https://blog.dbrgn.ch/2021/11/16/git-ssh-signatures/) yet)
- n/a
> Update maintainer email address for Andrew Mason

- examples/operator/operator.yaml
- tools/do_release.sh
> Use latest vitess-operator example CRDs

- doc/releasenotes/13_0_0_release_notes.md
- doc/releasenotes/13_0_0_summary.md
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/operator.yaml
- examples/operator/vtorc_example.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This pull request pushes the `v13.0.0` release commit and the "back to dev" mode commit too.
> Release `13.0` commit and back to development mode

- go/vt/vtgate/vcursor_impl.go
This pull request backports commit https://github.com/vitessio/vitess/commit/3567a8cbc5becf0642358a529f380e0bf9309dd1 that @vmg made in https://github.com/vitessio/vitess/pull/9698.
> Fix `TestGen4SelectDBA` flakiness

- go/test/endtoend/sharded/sharded_keyspace_test.go
This PR fixes the flakiness in the test `TestShardedKeyspace` which was uncovered after it failed 5 times on a PR with unrelated changes https://github.com/vitessio/vitess/actions/runs/1897285262/attempts/5
> Fix flakiness in TestShardedKeyspace

- go/mysql/endtoend/query_benchmark_test.go
This pull request adds several benchmarks that show how fast certain ways of setting system variables are.
In each benchmark we `insert` one row, `select` it, `update` it, and `delete` it. There are four groups of benchmarks:
- One where we set the variables only once (`BenchmarkSetVarsSingleSet`)
- One where we use `SET_VAR` in every query (`BenchmarkSetVarsWithQueryHints`)
- One where we set the variables before every query (`BenchmarkSetVarsMultipleSets`)
- One where we set the variables during every query using semi-colon (`BenchmarkSetVarsMultipleSetsInSameStmt`)
We run each group twice:
- Once with no sleep
- Another with a 1ms sleep between each iteration 
```
goos: darwin
goarch: amd64
pkg: vitess.io/vitess/go/mysql/endtoend
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz …
```
> Micro benchmarks for setting system variables

- .github/workflows/upgrade_downgrade_test_backups_e2e.yml
- .github/workflows/upgrade_downgrade_test_backups_manual.yml
- .github/workflows/upgrade_downgrade_test_query_serving.yml
- .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml
- .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml
- tools/get_latest_release.sh
This PR is the backport for PRs #9745 and #9784 for release-13.0
> Backport: Upgrade Downgrade fix to use the PR base to figure out which tag to use to run against

- doc/releasenotes/14_0_0_summary.md
This pull request updates the v14 summary with the latest change brought by #9767.
> Update v14 summary with the latest change to `JoinCondition` rewriting

- .github/CODEOWNERS
This PR adds GuptaManan100 as a code owner for VTOrc
> Add GuptaManan100 as a codeowner for VTOrc

- .github/CODEOWNERS
What it says in the title. This is primarily for VEP-4.
> Add @ajm188 to codeowners for CLI-related packages

- go/cmd/vtexplain/vtexplain.go
- go/cmd/vttestserver/main.go
- go/vt/vtexplain/testdata/multi-output/selectsharded-output.txt
- go/vt/vtgate/planbuilder/builder.go
- go/vt/vtgate/vtgate.go
Release 14 is still a long way away, but we might as well do this change now to flush out any bugs.
> Make gen4 the default planner for release 14

- .github/CODEOWNERS
These are areas of focus or interest that I want to help with reviews on.
> Add Matt Lord to CODEOWNERS

- go/vt/vttablet/onlineddl/executor.go
This PR just unifies all places where `onlineddl.Executor` calls `VReplicationExec()`. From now on, all these calls go through `e.vreplicationExec()` where:
- A `Once.Do()` ensures to init `_vt.vreplication`
- In the future, consolidate creation of `tmclient` and `tablet`.
This works around remaining issue described in #9817 and which is generically solved in #9860; but this PR has its own merits. Once #9860 is merged and good, then we can consider removing the `Once.Do()` aforementioned code.
- #6926
> OnlineDDL executor: route all VReplicationExec through single function

- go/test/endtoend/vreplication/migrate_test.go
- go/test/endtoend/vreplication/resharding_workflows_v2_test.go
- go/test/endtoend/vreplication/vreplication_test.go
> [VEP4, phase 1] [endtoend/vreplication] update flags in tests

- go/test/endtoend/recovery/pitr/shardedpitr_test.go
- go/test/endtoend/recovery/pitrtls/shardedpitr_tls_test.go
- go/test/endtoend/recovery/recovery_util.go
- go/test/endtoend/recovery/shardedrecovery/sharded_recovery_test.go
- go/test/endtoend/recovery/unshardedrecovery/recovery.go
More of the same cleanup work.
#9895
> [VEP4, phase 1] Update flags in `endtoend/recovery`

- go/vt/wrangler/workflow_test.go
I had this test fail in [CI](https://github.com/vitessio/vitess/runs/5598763583?check_suite_focus=true) with the following:
```
--- FAIL: TestCanSwitch (0.15s)
[715](https://github.com/vitessio/vitess/runs/5598763583?check_suite_focus=true#step:7:715)
--- FAIL: TestCanSwitch/High_Lag (0.03s)
[716](https://github.com/vitessio/vitess/runs/5598763583?check_suite_focus=true#step:7:716)
workflow_test.go:158: 
[717](https://github.com/vitessio/vitess/runs/5598763583?check_suite_focus=true#step:7:717)
Error Trace:	workflow_test.go:158
[718](https://github.com/vitessio/vitess/runs/5598763583?check_suite_focus=true#step:7:718)
Error:      	"replication lag 6s is higher than allowed lag 5s" does not contain "replication lag 7s is higher than allowed lag 5s"
```
We switch to a regexp, to check that …
> deflake TestCanSwitch by switching from exact string match to loose regex

- go/test/endtoend/sharded/sharded_keyspace_test.go
- go/test/endtoend/sharding/initialsharding/sharding_util.go
- go/test/endtoend/sharding/mergesharding/mergesharding_base.go
- go/test/endtoend/sharding/resharding/resharding_base.go
> [VEP4, phase 1] Update flags and imports for `endtoend/{sharded,sharding}`

- go/test/endtoend/worker/worker_test.go
- go/trace/plugin_jaeger.go
Made it through the endtoend tests! (More still to come, though :/ )
#9895
> [VEP4, phase1] fix flags in tests in `endtoend/worker` and strings in `go/trace`

- go/test/endtoend/vtcombo/recreate/recreate_test.go
- go/test/endtoend/vtcombo/vttest_sample_test.go
> [VEP4, phase 1] [endtoend/vtcombo] fix flags in tests

- GITHUB_SELF_HOSTED_RUNNERS.md
This PR adds the information of the newly introduced single-self-hosted runner to the Self hosted runner docs.
> Add single self-hosted runner information

- go/test/endtoend/versionupgrade/upgrade_test.go
More (if you're wondering why I'm opening so many, it's to simplify potential endtoend test debugging/troubleshooting)
#9895
> [VEP4, phase 1] fix flags in tests `endtoend/versionupgrade`

- go/cmd/vtctldclient/command/tablets.go
Follow-up on #9667
```
➜  local git:(andrew/getversion-cli) ✗ vtctldclient --server ":15999" GetTabletVersion zone1-100
{planetscale andrew 1648489745 f500f6ec33}
```
> [vtctldclient] Add entrypoint for GetVersion rpc

- go/vt/vttablet/onlineddl/vrepl.go
This is just a small change due to a complaint from an upgraded linter version.
> Minor fix requested by linter

- go/test/endtoend/worker/worker_test.go
As seen in the comment https://github.com/vitessio/vitess/issues/9985#issuecomment-1079666698, the test `TestReparentDuringWorkerCopy` is flaky.
The PR #9986 tried to fix it by adding a 1 second wait between the two PRS calls. That did seem to resolve the problem on local testing but the CI is still flaky. This PR reverses that change and instead goes ahead with the alternate proposed fix https://github.com/vitessio/vitess/pull/9986#discussion_r835756712.
#9985
> Alternate fix for flaky TestReparentDuringWorkerCopy

- web/vtadmin/src/proto/vtadmin.d.ts
Signed-off-by: notfelineit <notfelineit@gmail.com>
This PR runs `make vtadmin_web_proto_types`.
N/A
N/A
> [VTAdmin Web] Make Protos

- go/vt/vtadmin/cluster/discovery/fakediscovery/discovery.go
Because grpc is triggering calls to ResolveNow in a background goroutine,
which in turn make calls to a Discovery implementation (fakediscovery, in
these cases), we can have a data race when trying to wipe out a particular
fakediscovery's host set.
Before:
```
$ go test -race ./go/vt/vtadmin/... >/dev/null ; echo $?
1
```
After:
```
$ go test -race ./go/vt/vtadmin/... >/dev/null; echo $?
0
```
> [vtadmin|tests] Add mutex to prevent data races in tests using cluster/resolver

- go/test/endtoend/vtgate/misc_test.go
- go/vt/vtgate/executor_test.go
- go/vt/vtgate/planbuilder/explain.go
- go/vt/vtgate/planbuilder/plan_test.go
- go/vt/vtgate/planbuilder/plancontext/vschema.go
- go/vt/vtgate/vcursor_impl.go
> Backport to 13.0: Route explain tab plan to the proper Keyspace

- go/test/endtoend/messaging/message_test.go
As part of flaky test debugging for https://github.com/vitessio/vitess/issues/9949
Let's improve the test assertions in this file so we can figure out exactly why the debug client count is not what we expect it to be.
cc @deepthi
> endtoend: improve assertionsin message_test

- go/vt/mysqlctl/fakemysqldaemon/fakemysqldaemon.go
- go/vt/vttablet/tabletmanager/replmanager.go
- go/vt/vttablet/tabletmanager/rpc_replication.go
- go/vt/vttablet/tabletmanager/rpc_replication_test.go
- go/vt/wrangler/tablet.go
Backport to release-13 of #9859
> Fix the race between PromoteReplica and replication manager tick (#9859) - release 13

- MAINTAINERS.md
> Add Matt Lord to maintainers

- go/vt/vttablet/onlineddl/executor.go
We encountered an issue where a query was mutated by the parser such that the parser itself [could not parse it again](https://github.com/vitessio/vitess/issues/10064). This should not happen, but as it did, Online DDL got into a weird situation where it was given a well formed statement that was empty (an `alter create table t` with nothing else to follow). Specifically, it was not `IsFullyParsed()`.
In an ideal world we shouldn't re-validate something that went through the parser, but it's prudent for Online DDL's executor to do this double validation, and reject a statement if it's not `IsFullyParsed()`. With this PR the executor returns a clear error `"error parsing statement"` rather than attempt to execute a malformed query.
- https://github.com/vitessio/vitess/issues/10064
- #6926
> OnlineDDL: double statement validation upon submission

- .github/workflows/cluster_endtoend_mysql80.yml
- .github/workflows/cluster_endtoend_upgrade.yml
- .github/workflows/e2e_race.yml
- .github/workflows/legacy_local_example.yml
- .github/workflows/local_example.yml
- .github/workflows/region_example.yml
- .github/workflows/unit_test_mysql80.yml
- go/test/endtoend/vtgate/misc_test.go
- go/vt/vtgate/executor_test.go
- go/vt/vtgate/planbuilder/builder.go
- go/vt/vtgate/planbuilder/explain.go
- go/vt/vtgate/planbuilder/plan_test.go
- go/vt/vtgate/vcursor_impl.go
- test/templates/unit_test.tpl
This is a backport of https://github.com/vitessio/vitess/pull/10027.
> Backport to 11.0: Route explain tab plan to the proper Keyspace

- go/vt/vtgate/planbuilder/horizon_planning.go
- go/vt/vtgate/planbuilder/testdata/select_cases.txt
This Pull Request backports the changes made in https://github.com/vitessio/vitess/pull/10069.
> [13.0] Fix Gen4 only_full_group_by regression

- go/vt/mysqlctl/fakemysqldaemon/fakemysqldaemon.go
- go/vt/vttablet/tabletmanager/replmanager.go
- go/vt/vttablet/tabletmanager/rpc_replication.go
- go/vt/vttablet/tabletmanager/rpc_replication_test.go
> Fix the race between PromoteReplica and replication manager tick (#9859) - release 11

- .github/workflows/check_formatting.yml
- .github/workflows/check_make_sizegen.yml
- .github/workflows/legacy_local_example.yml
- .github/workflows/local_example.yml
- .github/workflows/region_example.yml
This Pull Request fixes several workflows that broke after merging the new paths-filter feature (https://github.com/vitessio/vitess/pull/10031).
- These issues were observed in https://github.com/vitessio/vitess/pull/10083 and https://github.com/vitessio/vitess/pull/10081
> Repair paths-filter workflows

- .github/workflows/cluster_endtoend_mysql80.yml
- .github/workflows/cluster_endtoend_upgrade.yml
- .github/workflows/e2e_race.yml
- .github/workflows/legacy_local_example.yml
- .github/workflows/local_example.yml
- .github/workflows/region_example.yml
- .github/workflows/unit_test_mysql80.yml
- go/test/endtoend/vtgate/misc_test.go
- go/test/endtoend/vtgate/utils/utils.go
- go/vt/vtgate/executor_test.go
- go/vt/vtgate/planbuilder/builder.go
- go/vt/vtgate/planbuilder/explain.go
- go/vt/vtgate/planbuilder/plan_test.go
- go/vt/vtgate/vcursor_impl.go
- test/templates/unit_test.tpl
This is a backport of #10027 into the `release-12.0` branch.
> Backport to 12.0: Route explain tab plan to the proper Keyspace

- doc/releasenotes/13_0_1_release_notes.md
This Pull Request adds the release notes for v13.0.1.
- https://github.com/vitessio/vitess/issues/10032
> Addition of release notes for v13.0.1

- go/vt/vtadmin/api.go
- go/vt/vtadmin/cluster/cluster.go
- go/vt/vtadmin/cluster/cluster_test.go
just some extra cleanup!! very smol change
- #10109
- #10108 
> [vtadmin] Remove Tablets option for GetSchema(s)

- doc/releasenotes/13_0_1_release_notes.md
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/vtorc_example.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This Pull Request updates the different version constants following the release of v13.0.1. The related release notes is also added in this PR.
- https://github.com/vitessio/vitess/issues/10032
> Release 13.0.1

- go/vt/vtgate/planbuilder/abstract/operator_test.go
Fix flaky TestOperator
Fixes #10112
> unit test: sort map before converting to string

- go/vt/vtgate/engine/gen4_compare_v3.go
This PR fixes the `TryStreamExecute` of the `Gen4CompareV3` planner. @systay found that we need to use a mutex when appending new rows from the children's engine Primitive.
> Fix StreamExecute in Gen4CompareV3

- docker/bootstrap/CHANGELOG.md
When we started versioning the bootstrap images, a Changelog file was added to provide a human-readable history.
This PR adds all known versions to that file.
-   [ ] "Backport me!" label has been added if this change should be backported NO
> bootstrap changelog

- .github/workflows/comment_pull_request.yml
This PR changes the format of the `comment_pull_request`.
> Applied some format check on the comment_pull_request workflow

- go/vt/vtexplain/vtexplain_vtgate.go
In vtExplain output, commit order depends upon the shard order that gets added to shard session first. This is non-deterministic. So added logic to sort the shard session lexicographically.
> fix: vtexplain commit order flaky

- go/vt/vtadmin/cluster/cluster.go
Apparently it's been so long so I've done one of these I forgot about the RPC pools. This adds the topoReadPool semantics to the apis I added in #10227 
#10227 #8705 
> [vtadmin] `GetCell{Infos,Aliases}`: Add missing topoReadPool management

- go/vt/vtadmin/cluster/cluster_internal_test.go
- go/vt/vtadmin/cluster/cluster_test.go
- go/vt/vtadmin/vtctldclient/fakevtctldclient/vtctldclient.go
This adds unit tests for the cluster methods added in #10325 
#10325 
> [vtadmin] tablet topotools tests

- go/vt/vtadmin/cluster/cluster.go
The schema cache has a backfill goroutine running which depends on the
clutser's Vtctld, so there's a more subtle `Close` ordering dependency
here.
It's okay (and good!) to close caches concurrently, and proxy connections
concurrently, but never concurrently _with each other_, and always do the
caches first.
```
go test -count=10 -race ./go/vt/vtadmin/...
```
^ passes with these changes, but can fail without.
> [vtadmin] Fix data race in vtadmin

- go/vt/vtadmin/api.go
Following up on #7723 and #10374, this removes the now–unnecessary mutex guarding concurrent vtexplain Init calls.
- Closes #7723
- #10374 
> [vtadmin] Remove mutex, now that vtexplain has no global state

- .github/CODEOWNERS
The title says it all. I want to start acting as the owner of vtexplain.
> Add systay as owner of vtexplain

- doc/releasenotes/12_0_4_release_notes.md
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This PR is a follow up of [Release `v12.0.4`](https://github.com/vitessio/vitess/releases/tag/v12.0.4). The release notes are updated along with the hardcoded version strings.
> Release `12.0.4`

- go/vt/vtadmin/api_authz_test.go
- go/vt/vtadmin/testutil/authztestgen/config.json
- go/vt/vtadmin/testutil/authztestgen/template.go
- go/vt/vtadmin/vtctldclient/fakevtctldclient/vtctldclient.go
This covers all RPCs from A-D, alphabetically.
I stopped there because ERS is being renamed in #10404 and I didn't want to deal with the conflicts.
#10397 
> [vtadmin] authz tests part1

- go/vt/vtgate/errorsanitizer/error_sanitizer.go
- go/vt/vtgate/errorsanitizer/error_sanitizer_test.go
Removing code = \S+ can be removed completely as a cut point. There is useful content after it that would be nice to preserve. 
We can replace important PII stuff with '<val>' duplicate entry
> making log sanitization more precise

- go/vt/vtadmin/api_authz_test.go
- go/vt/vtadmin/testutil/authztestgen/config.json
- go/vt/vtadmin/testutil/authztestgen/main.go
- go/vt/vtadmin/testutil/authztestgen/template.go
This will be useful for some of the getter tests I'm working on, and I wanted to isolate the template changes into their own PR for easier review
- #10397 
- #10415 
> [vtadmin] Refactor authztestgen template to allow multiple test clusters

- examples/local/101_initial_cluster.sh
- examples/local/401_teardown.sh
What it says in the title. Note that (primarily for anyone using this as prior art for the other examples), this is working because vtctld is running with `grpc-vtctld` in its `service_map` already ([c.f.](https://github.com/vitessio/vitess/blob/main/examples/local/scripts/vtctld-up.sh#L31)), which is required for vtadmin to be able to make the gRPC calls it needs.
(I omitted some of the normal output for other components just to make it fit)
```
➜  local git:(andrew/vtadmin/local-example) ✗ ./101_initial_cluster.sh 
add /vitess/global
add /vitess/zone1
add zone1 CellInfo
Created cell: zone1
etcd start done...
Starting vtctld...
Starting MySQL for tablet zone1-0000000100...
Starting vttablet for zone1-0000000100...
HTTP/1.1 200 OK
Date: Fri, 03 Jun 2022 17:42:29 GMT
Content-Type: …
```
> Add vtadmin to local example by default

- go/vt/vtadmin/api_authz_test.go
- go/vt/vtadmin/testutil/authztestgen/config.json
- go/vt/vtadmin/testutil/authztestgen/template.go
This finishes all the getters (except the Schema ones)
#10397 
> [vtadmin] authz tests -  getters part3

- doc/releasenotes/14_0_0_release_notes.md
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This PR is a follow-up to the `v14.0.0-RC1` release. The different version constants have been incremented to `v15.0.0-SNAPSHOT` and the `v14.0.0` releases notes are added to the codebase.
> Post release `v14.0.0-RC1` steps

- .github/workflows/static_checks_etc.yml
- doc/releasenotes/14_0_0_summary.md
Adds a few lines to the release notes for release 14.
> docs: added to the release notes

- go/vt/vtadmin/cluster/cluster.go
- go/vt/vtadmin/cluster/cluster_internal_test.go
- go/vt/vtadmin/cluster/config.go
- go/vt/vtadmin/cluster/flags.go
This back ports #10460 to v14 release branch.
> Rename ERS/PRS pools+flags properly (#10460)

- go/vt/vtadmin/api_authz_test.go
- go/vt/vtadmin/testutil/authztestgen/config.json
- go/vt/vtadmin/vtctldclient/fakevtctldclient/vtctldclient.go
This adds authz tests for every. single. tablet. action. 🎉 
#10397 
> [vtadmin] authz tests - tablet actions

- web/vtadmin/README.md
This fixes a build issue of the form:
```
Creating an optimized production build...
Failed to compile.
Error: error:0308010C:digital envelope routines::unsupported
at String.replace (<anonymous>)
```
-   [x] Tests were added or are not required -- N/A
> [vtadmin] Document known issue with node versions 17+

- go/vt/vttablet/onlineddl/executor.go
Adding some long overdue logging at important points in the Online DDL automaton logic: pre/port migration submission, cancellation/cleanup and more.
#6926 
> OnlineDDL executor: adding log entries

- go/vt/vtadmin/api_authz_test.go
- go/vt/vtadmin/testutil/authztestgen/config.json
- go/vt/vtadmin/testutil/authztestgen/template.go
- go/vt/vtadmin/vtctldclient/fakevtctldclient/vtctldclient.go
- web/vtadmin/package-lock.json
This backports #10481 and #10486 to the 14.0 release branch.
> [backport] [vtadmin] Add remaining authz tests

- go/tools/release-notes/release_notes.go
- go/tools/release-notes/release_notes_test.go
> [12.0] Rework the generation of the release notes

- go/tools/release-notes/release_notes.go
- go/tools/release-notes/release_notes_test.go
> [11.0] Rework the generation of the release notes

- web/vtadmin/README.md
backports #10483 to release-14.0
> [backport] Document known issue with node versions 17+ (#10483)

- doc/releasenotes/14_0_0_summary.md
Adds a little info about gen4 to the release notes for v14.0.0
Content backported from #10475
> Release notes on query serving

- go/vt/vtadmin/api_authz_test.go
- go/vt/vtadmin/testutil/authztestgen/template.go
This backports #10555 to the 14.0 so we don't have to fight flakes when backporting actual bugfixes
#10549 
> [backport] use individual API instances for certain test cases (#10555)

- .github/CODEOWNERS
Removing myself from codepaths that aren't explicitly VTAdmin-related. :)
> Remove @doeg from a subset of CODEOWNERS

- go/vt/orchestrator/config/config.go
- go/vt/orchestrator/logic/topology_recovery.go
- go/vt/orchestrator/logic/topology_recovery_test.go
This PR is the backport for #10519 which tests and fixes a panic in vtorc.
> Backport to release-14: Fix panic in VTOrc (#10519)

- .github/workflows/static_checks_etc.yml
- .golangci.yml
- go/mysql/conn_flaky_test.go
- go/test/endtoend/cluster/vtctlclient_process.go
- go/test/endtoend/utils/mysql.go
- go/test/endtoend/vtorc/utils/utils.go
- go/tools/release-notes/release_notes.go
- go/vt/grpcclient/client.go
- go/vt/grpcclient/client_flaky_test.go
- go/vt/grpcoptionaltls/server_test.go
- go/vt/vtadmin/grpcserver/server_test.go
- go/vt/vtadmin/vtctldclient/proxy.go
- go/vt/vtadmin/vtsql/vtsql.go
- go/vt/vtgate/engine/lock.go
- go/vt/vtgate/evalengine/integration/comparison_test.go
- go/vt/vtgate/executor_framework_test.go
- go/vt/vtgate/planbuilder/abstract/operator_test.go
- go/vt/vtgate/vtgate_test.go
- go/vt/vttablet/tabletmanager/vreplication/vreplicator_test.go
- misc/git/hooks/golangci-lint
> update golangci-lint to 1.46.2

- .github/workflows/static_checks_etc.yml
- .github/workflows/upgrade_downgrade_test_backups_e2e.yml
- .github/workflows/upgrade_downgrade_test_backups_manual.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema.yml
- .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml
- .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml
- tools/get_previous_release.sh
This is a backport of #10504 on `release-14.0`.
> [14.0] Take into account `github.ref` when doing upgrade-downgrade tests

- docker/lite/Dockerfile.alpine
- docker/lite/Dockerfile.mariadb
- docker/lite/Dockerfile.mariadb103
- docker/lite/Dockerfile.mysql80
- docker/lite/Dockerfile.percona57
- docker/lite/Dockerfile.percona80
- docker/lite/Dockerfile.testing
- docker/lite/Dockerfile.ubi7.mysql57
- docker/lite/Dockerfile.ubi7.mysql80
- docker/lite/Dockerfile.ubi7.percona57
- docker/lite/Dockerfile.ubi7.percona80
- docker/lite/Dockerfile.ubi8.arm64.mysql80
- docker/lite/Dockerfile.ubi8.mysql80
This is a forward-port of https://github.com/vitessio/vitess/pull/10581.
> add vtadmin web files to all lite images (#10581)

- doc/releasenotes/14_0_0_changelog.md
- doc/releasenotes/14_0_0_release_notes.md
- doc/releasenotes/14_0_0_summary.md
This PR adds the v14 release notes documents.
> Addition of the v14 release notes documents

- doc/releasenotes/14_0_0_changelog.md
- doc/releasenotes/14_0_0_release_notes.md
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/operator.yaml
- examples/operator/vtorc_example.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This PR updates the version constants and release notes documents
> Post release 14.0.0 updates

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This PR reverts the version constant incrementation from `14.0.1` to `14.0.0` in order to prepare the re-release of `v14.0.0`.
> Revert snapshot incrementation in release-14.0

- .github/workflows/close_stale_pull_requests.yml
> Allow manual workflow_dispatch for close_stale_pull_requests

- doc/releasenotes/14_0_0_changelog.md
- doc/releasenotes/14_0_0_release_notes.md
This PR updates the release documents on main for `v14`.
> Addition of the v14 release docs on main

- doc/releasenotes/14_0_0_changelog.md
- doc/releasenotes/14_0_0_release_notes.md
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This PR contains the `v14.0.0` tagged commit and the incrementation to `14.0.1-SNAPSHOT`.
> Release of v14.0.0 on release-14.0

- .github/workflows/release_notes_label.yml
> [14] Fixed the release notes CI check helper (#10574)

- .github/workflows/release_notes_label.yml
> [12] Fixed the release notes CI check helper (#10574)

- .github/workflows/release_notes_label.yml
> [11] Fixed the release notes CI check helper (#10574)

- go/test/endtoend/onlineddl/revert/onlineddl_revert_test.go
This Pull Request fixes the flakiness induced by schema tracking in Online DDL Revert tests.
The interval at which vttablet sends schema updates has been lowered to `0.1` second instead of `5` seconds.
- fix https://github.com/vitessio/vitess/issues/10674
- Part of https://github.com/vitessio/vitess/issues/10620
> Fix Online DDL Revert flakiness

- doc/releasenotes/14_0_0_release_notes.md
- doc/releasenotes/14_0_0_summary.md
This PR documents the known issue https://github.com/vitessio/vitess/issues/10650 in the release notes of 14.0
-   [x] Documentation was added or is not required - Website docs - https://github.com/vitessio/website/pull/1097
> Add the vtorc discovery bug as a known issue to 14.0

- go/test/endtoend/vtgate/misc_test.go
- go/vt/vtgate/planbuilder/physical/route_planning.go
- go/vt/vtgate/planbuilder/testdata/select_cases.txt
> [release-14.0] BugFix: Keep predicates in join when pushing new ones (#10715)

- go/test/endtoend/vtgate/misc_test.go
- go/vt/vtgate/planbuilder/physical/route_planning.go
- go/vt/vtgate/planbuilder/testdata/select_cases.txt
This is a backport of https://github.com/vitessio/vitess/pull/10715
> [release-13.0] BugFix: Keep predicates in join when pushing new ones (#10715)

- doc/releasenotes/14_0_1_summary.md
This Pull Request updates the release notes for the `v14.0.1` patch release.
- #10654 
> [14] Addition of the release notes summary for v14.0.1

- doc/releasenotes/13_0_2_summary.md
This Pull Request adds the release summary for the upcoming patch release: `v13.0.2`.
- #10653
> [13] Release summary 13.0.2

- doc/releasenotes/14_0_1_changelog.md
- doc/releasenotes/14_0_1_release_notes.md
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/vtorc_example.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This Pull Request is a follow-up to the `v14.0.1` release. It updates the release notes and increments the different version constants.
- https://github.com/vitessio/vitess/issues/10654
> Post release `v14.0.1`

- doc/releasenotes/13_0_2_changelog.md
- doc/releasenotes/13_0_2_release_notes.md
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/vtorc_example.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This Pull Request is a follow-up to the `v13.0.2` release. It includes the new release notes and changelog along with the incrementation of the version constants.
- https://github.com/vitessio/vitess/issues/10653
> Post release `v13.0.2`

- doc/releasenotes/14_0_1_changelog.md
- doc/releasenotes/14_0_1_release_notes.md
This Pull Request adds the release notes and changelog for the `v14.0.1` release.
- https://github.com/vitessio/vitess/issues/10654
> Addition of the release notes for v14.0.1

- .github/workflows/cluster_endtoend_upgrade.yml
- doc/releasenotes/12_0_5_summary.md
- go/test/endtoend/cluster/cluster_process.go
- go/test/endtoend/cluster/vtctlclient_process.go
This Pull Request adds the release summary for v12.0.5.
- https://github.com/vitessio/vitess/issues/10846
> Addition of the release summary for v12.0.5

- doc/releasenotes/13_0_2_changelog.md
- doc/releasenotes/13_0_2_release_notes.md
This Pull Request adds the changelog and release notes for `v13.0.2`.
- https://github.com/vitessio/vitess/issues/10653
> Addition of the release notes for `v13.0.2`

- doc/releasenotes/12_0_5_changelog.md
- doc/releasenotes/12_0_5_release_notes.md
- docker/lite/Dockerfile.mysql57
- docker/lite/Dockerfile.mysql80
- docker/lite/install_dependencies.sh
- go/tools/release-notes/release_notes.go
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This Pull Request is a follow-up of `v12.0.5`, it updates the different version constants and adds the release notes.
- https://github.com/vitessio/vitess/issues/10846
> Release `v12.0.5`

- doc/releasenotes/12_0_5_changelog.md
- doc/releasenotes/12_0_5_release_notes.md
This Pull Request adds the release notes for `v12.0.5`.
- https://github.com/vitessio/vitess/issues/10846
> Addition of the release notes for v12.0.5

- doc/releasenotes/15_0_0_summary.md
Add index to v15 summary.
Fix typos, re-word and re-organize.
> release notes: add index to v15 summary

- go/vt/mysqlctl/builtinbackupengine.go
The progress while taking a backup, calculates percentage on basis of file size to be written. The file size is calculate on basis of original size but consider for example if we are compressing then the real size to calculate the progress against should not be the original but the size of file after the compression (in denominator). This was resulting in giving an impression as something is weird with backup and it never reaches to 100% (only in progress bar, in reality it does though) if there is compression enabled.
This change will calculate the percentage using what is read instead of what is write because write can be compressed  making it hard to find the right denominator for percentage. Functionally nothing was wrong. Its …
> Fixing logic for backup progress

- go/vt/vttablet/tabletmanager/rpc_replication.go
This PR fixes the downgrade part of the problem as described in #10916.
After this change using backups created from v14 work fine with binaries of v13.
The proposed fix is to run the ALTER statement after taking the primary position. This allows for the statement to be replicated to the replicas if it succeeds.
- #10916 
> BugFix: Using backups from v14 should work with v13

- go/vt/vtgate/vstream_manager.go
This is a backport of: https://github.com/vitessio/vitess/pull/10571
- 🍒 ⛏️ of: https://github.com/vitessio/vitess/pull/10571
> Backport: VStream API: Fix vtgate memory leaks when context gets cancelled

- go/vt/vtgate/grpcvtgateconn/conn.go
This migrates the flags defined for `grpcvtgateconn` to `pflag` and scopes them to the appropriate binaries.
Closes https://github.com/vitessio/vitess/issues/10934
> [cli] [grpcvtgateconn] Migrate `vtgate/grpcvtgateconn` flags to `pflag`

- go/vt/vtgate/grpcvtgateservice/server.go
This package is also imported by `vtgateclienttest`, but let's see how the full test suite fairs without it!
Closes #10935.
> [cli] [vtgate] Migrate `grpcvtgateservice` flags to `pflag` and scope to appropriate binaries.

- go/vt/sqlparser/parse_next_test.go
- go/vt/topo/helpers/copy.go
- go/vt/topo/k8stopo/server_flaky_test.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
Fixes #10772
> fix minor code unreachability error

- .github/workflows/upgrade_downgrade_test_backups_e2e.yml
- .github/workflows/upgrade_downgrade_test_backups_manual.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema.yml
- .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml
- .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml
These weren't fixed as part of #10757, because they were hand-written and not generated from a template.
#10757 
> CI: change upgrade/downgrade tests to use vitessio fork of go-junit-report

- doc/SeparatingVttabletMysql.md
- go/flags/endtoend/vttablet.txt
- go/flagutil/flagutil.go
- go/vt/mysqlctl/backupengine.go
- go/vt/vttablet/tabletmanager/orchestrator.go
- go/vt/vttablet/tabletmanager/restore.go
- go/vt/vttablet/tabletmanager/rpc_lock_tables.go
- go/vt/vttablet/tabletmanager/rpc_replication.go
- go/vt/vttablet/tabletmanager/shard_sync.go
- go/vt/vttablet/tabletmanager/tm_init.go
- go/vt/vttablet/tabletmanager/tm_init_test.go
- go/vt/vttablet/tabletmanager/tm_state.go
- go/vt/vttablet/tabletmanager/tm_state_test.go
Does what it says on the tin. This one was pretty straightforward.
Closes #10980.
> [cli] [tabletmanager] Migrate all tabletmanager flags to `pflag`

- go/test/endtoend/utils/mysql.go
- go/test/endtoend/utils/utils.go
- go/test/endtoend/vtgate/gen4/gen4_test.go
- go/test/endtoend/vtgate/queries/foundrows/found_rows_test.go
- go/test/endtoend/vtgate/queries/misc/main_test.go
- go/test/endtoend/vtgate/queries/misc/schema.sql
- go/test/endtoend/vtgate/queries/misc/vschema.json
- go/test/endtoend/vtgate/queries/normalize/main_test.go
- go/test/endtoend/vtgate/queries/normalize/schema.sql
- go/test/endtoend/vtgate/queries/union/main_test.go
- go/test/endtoend/vtgate/queries/union/schema.sql
- go/test/endtoend/vtgate/queries/union/vschema.json
- go/test/endtoend/vtgate/queries/vtexplain/main_test.go
- go/test/endtoend/vtgate/queries/vtexplain/vtexplain_test.go
This PR changes Gen4's queries end-to-end tests, so they are all formatted similarly.
> Format Gen4 end-to-end tests

- go/flags/endtoend/vtexplain.txt
- go/vt/vttablet/onlineddl/executor.go
Updates onlineddl related flag references specified in #10976
Fixes #10976
> [cli] [tabletserver/onlineddl] Migrate onlineddl flags to pflags

- go/vt/status/status.go
Title is description.
Closes #10854.
> [cli] [status] Migrate go/vt/status to pflag

- go/vt/vttablet/grpctabletconn/conn.go
- go/vt/vttablet/grpctmclient/cached_client.go
- go/vt/vttablet/grpctmclient/client.go
This migrates the flags in `grpctabletconn` and `grpctmclient` to `pflag`, following the binary dependencies done in #10999 and #11066 respectively (with the exception of the addition of `vtbench`, which imports and uses `grpctabletconn` directly, rather than going indirectly through `tabletconn.Dialer()`.
- Closes #10974.
- Closes #10975.
> [cli] [grpc{tabletconn,tmclient}] Migrate flags to `pflag`

- .github/workflows/unit_race.yml
- .github/workflows/unit_test_mariadb103.yml
- .github/workflows/unit_test_mysql57.yml
- .github/workflows/unit_test_mysql80.yml
- test/templates/unit_test.tpl
Extracted from https://github.com/vitessio/vitess/pull/11026
https://github.com/vitessio/vitess/pull/11026
> Upgrade CI for unit tests to Ubuntu 20.04

- go/flags/endtoend/vtctld.txt
- go/flags/endtoend/vtexplain.txt
- go/streamlog/streamlog.go
- go/vt/vtgate/logstats/logstats.go
- go/vt/vtgate/logstats/logstats_test.go
- go/vt/vtgate/querylogz_test.go
- go/vt/vttablet/filelogger/filelogger_test.go
- go/vt/vttablet/sysloglogger/sysloglogger_test.go
- go/vt/vttablet/tabletserver/query_engine.go
- go/vt/vttablet/tabletserver/query_engine_test.go
- go/vt/vttablet/tabletserver/query_list.go
- go/vt/vttablet/tabletserver/querylogz_test.go
- go/vt/vttablet/tabletserver/tabletenv/config.go
- go/vt/vttablet/tabletserver/tabletenv/logstats.go
- go/vt/vttablet/tabletserver/tabletenv/logstats_test.go
- go/vt/vttablet/tabletserver/txlogz.go
- go/vt/vttablet/tabletserver/txlogz_test.go
- go/vt/vttablet/tabletserver/txserializer/tx_serializer.go
- go/vt/vttablet/tabletserver/txserializer/tx_serializer_test.go
Updates tabletenv related flag references specified in https://github.com/vitessio/vitess/issues/10746
Fixes #10746
> [cli] [tabletserver/streamlog] Migrate streamlog flags to pflags

- doc/releasenotes/12_0_6_summary.md
This Pull Request adds the release summary for `v12.0.6`.
> [release-12.0] Addition of the release summary for `v12.0.6`

- doc/releasenotes/13_0_3_summary.md
This Pull Request adds the release summary for `v14.0.3`.
> [release-13.0] Addition of the release summary for `v13.0.3`

- doc/releasenotes/14_0_2_summary.md
This Pull Request adds the release summary for `v14.0.2`.
> [release-14.0] Addition of the release summary for v14.0.2

- doc/releasenotes/13_0_3_changelog.md
- doc/releasenotes/13_0_3_release_notes.md
- doc/releasenotes/13_0_3_summary.md
This Pull Request adds the release notes for `v13.0.3`.
> Addition of the release notes for `v13.0.3`

- doc/releasenotes/13_0_3_changelog.md
- doc/releasenotes/13_0_3_release_notes.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/vtorc_example.yaml
- go/tools/release-notes/release_notes.go
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This PR contains the changes done to `release-13.0` to release `v13.0.3`.
> Release `v13.0.3`

- go/vt/orchestrator/inst/instance.go
- go/vt/orchestrator/inst/instance_dao.go
- go/vt/orchestrator/inst/instance_topology.go
- go/vt/orchestrator/util/math.go
This PR move math package from external library to util package. All the functions are more like helper functions rather then using some external library. Also removed un-used methods.
> Moving math package from external libarary

- doc/releasenotes/12_0_6_changelog.md
- doc/releasenotes/12_0_6_release_notes.md
- doc/releasenotes/12_0_6_summary.md
This Pull Request adds the release notes for `v12.0.6`.
> Addition of the release notes for `v12.0.6`

- doc/releasenotes/12_0_6_changelog.md
- doc/releasenotes/12_0_6_release_notes.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/vtorc_example.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
This Pull Request includes the commit that were done during the release process of `v12.0.6`.
> Release `12.0.6`

- go/flags/endtoend/vtexplain.txt
- go/flags/endtoend/vtgr.txt
- go/vt/servenv/grpc_server_auth_mtls.go
- go/vt/servenv/grpc_server_auth_static.go
Missed this in #11146 somehow.
- #11146
- #11144 
> [cli] [servenv] Migrate missed auth flag to pflag

- go/pools/resource_pool.go
- go/vt/vttablet/tabletserver/connpool/pool.go
- go/vt/vttablet/tabletserver/connpool/pool_test.go
This PR adds metrics around the usage of settings pool.
- #9706 
> adding setting pool metrics

- examples/region_sharding/101_initial_cluster.sh
- examples/region_sharding/301_teardown.sh
- examples/region_sharding/scripts/vtadmin-down.sh
- examples/region_sharding/scripts/vtadmin-up.sh
- examples/region_sharding/scripts/vtorc-down.sh
- examples/region_sharding/scripts/vtorc-up.sh
- examples/region_sharding/scripts/vttablet-up.sh
- examples/region_sharding/vtadmin/discovery.json
- examples/region_sharding/vtadmin/rbac.yaml
- examples/region_sharding/vtorc/config.json
This PR adds VTOrc and VTAdmin to the region example.
> Add VTOrc and VTAdmin to Region example

- go/cmd/vtadmin/main.go
- go/cmd/vtctldclient/command/root.go
- go/vt/servenv/buildinfo.go
- go/vt/servenv/servenv.go
What it says on the tin.
- Relates to #11144.
- Closes #10909.
> [cli] [servenv] Migrate `--version` flag to pflag, and also add to `vtctldclient` and `vtadmin`

- go/cmd/query_analyzer/query_analyzer.go
- go/cmd/rulesctl/main.go
- go/cmd/vtbench/vtbench.go
- go/cmd/vtclient/vtclient.go
- go/cmd/vtctldclient/main.go
- go/cmd/vtorc/main.go
- go/flags/endtoend/vtgr.txt
- go/mysql/collations/integration/collations_test.go
- go/mysql/collations/local.go
- go/vt/servenv/buildinfo.go
- go/vt/servenv/mysql.go
- go/vt/sqlparser/parser.go
- go/vt/vtgate/engine/memory_sort_test.go
- go/vt/vtgate/engine/ordered_aggregate_test.go
- go/vt/vtgate/engine/route_test.go
- go/vt/vtgate/evalengine/comparisons_test.go
- go/vt/vtgate/evalengine/integration/comparison_test.go
- go/vt/vtgate/plugin_mysql_server.go
- go/vt/vttest/vtprocess.go
I think I got the command list right, but could use a second pair of eyes on that.
Closes #11144.
> [cli] [servenv] Migrate `--mysql_server_version` to pflag

- tools/do_release.sh
This PR changes the do_release script so that three commits are created when doing a release. Two of them (the release notes and the tag commits) will be in one Pull Request, and the third commit (the one to go back to dev mode) will be in a second Pull Request.
Since we started squashing Pull Requests, we could not differentiate the commit where we do the release/tag and the commit where we go back to dev mode. They were squashed together. This became a problem when we needed to build the Docker images manually. To avoid a similar problem in the future, we are now creating two Pull Request :)
Additionally, the script has more verbose and guides the user with the precise command to open the Pull Requests. Example:
```
----------------
Release preparations successful. Two branches were …
```
> Improve the `do_release` script to have two different Pull Requests instead of one during a release

- doc/internal/ReleaseInstructions.md
This Pull Request updates the release documentation. The release process had some recent changes that need to be documented.
The changes brought by the following PRs are documented in this PR:
- https://github.com/vitessio/vitess/pull/11178
- https://github.com/vitessio/vitess/pull/11197
> Update the release documentation

- go/vt/vttablet/tabletserver/connpool/dbconn.go
- go/vt/vttablet/tabletserver/connpool/dbconn_test.go
This PR handles the case when a reconnect happens from vttablet and the old connection has system setting so that the new connection also applies the same settings.
- #9706 
> Reapply system settings on connection reconnect

- .github/docker/cluster_test_vtorc/Dockerfile
- .github/workflows/cluster_endtoend_vtorc.yml
- test/ci_workflow_gen.go
This PR moves the VTOrc tests to self-hosted runner so that we can track where the flakiness is coming from.
> Move vtorc to self-hosted runner

- go/test/endtoend/backup/transform/backup_transform_utils.go
- go/test/endtoend/cluster/cluster_util.go
> Adding tablet startup check

- go/vt/vtctl/reparentutil/planned_reparenter.go
- go/vt/vtctl/reparentutil/planned_reparenter_flaky_test.go
Up until now `PlannedReparentShard` has always assumed that the caller knows what they are doing and is only invoking `PlannedReparentShard` with the correct parameters, only when everything is up. 
But this assumption has quickly changed with VTOrc running `PlannedReparentShard` on an `electNewPrimary` recovery.
That recovery is triggered whenever there is no primary tablet in a shard. 
This has caused an issue which is described in the first issue of https://github.com/vitessio/vitess/issues/11295#issuecomment-1253910772. VTOrc ends up starting `PRS` just as it discovers one tablet from a shard that is coming up. 
This call ends up failing because there is a single tablet available and the durability policy of the keyspace is semi_sync. So PlannedReparentShard cannot succeed. It ends up …
> Improve PRS to validate new primary can make forward progress

- go/cmd/vtctlclient/main.go
- go/flags/endtoend/vtctlclient.txt
Also straightforward; to see the net diff on the help output, see: https://github.com/vitessio/vitess/commit/860f3f49ab222a0d691da66b5e569e95ec4bff7f#diff-9bd1c0e6760da5ae755c55352c16ac648b8d121910d10fcf0f6d187e2a4cfa6d
- Closes #11281.
> [vtctlclient] Migrate to pflag

- go/flags/endtoend/vtctld.txt
- go/flags/endtoend/vtexplain.txt
- go/vt/srvtopo/discover_test.go
- go/vt/srvtopo/query.go
- go/vt/srvtopo/resilient_server.go
- go/vt/srvtopo/resilient_server_test.go
This migrates the following tools to pflag:
* `go/vt/srvtopo`
- Closes https://github.com/vitessio/vitess/issues/10853
> srvtopo pflags migration

- go/vt/vttablet/tabletserver/debugenv.go
It seems that https://github.com/vitessio/vitess/pull/10547/files#diff-bfcaf2fd4864f36315b4a7620cb0f55c116a102e2a22b9cdc1197a3d3bf7020bL42 broke the debug/env, resulting in errors like:
```
tmp/vttablet.andrew.log.INFO.20220924-062954.21582:E0924 06:32:18.599365   21582 debugenv.go:194] debugenv: couldn't execute template: template: debugenv:3:8: executing "debugenv" at <.Name>: can't evaluate field Name in type tabletserver.envValue
```
Fixes #11346.
> Fix tablet debug/env template variable name

- Makefile
- go/tools/asthelpergen/asthelpergen.go
- go/tools/asthelpergen/main/main.go
- misc/git/hooks/asthelpers
This migrates the asthelpergen to use pflags.
Fixes #11298
> [asthelpergen] Migrate to pflags

- go/vt/vttablet/endtoend/settings_test.go
- go/vt/vttablet/tabletserver/query_engine.go
This PR checks the type of the cache value before returning it.
- Fixes https://github.com/vitessio/vitess/issues/11371
> Handle cache value type correctly

- go/tools/release-notes/release_notes.go
> [release-14.0] Add hyperlink in the release changelog (#11241)

- go/flags/endtoend/vtctlclient.txt
- go/flags/endtoend/vtctld.txt
- go/flags/endtoend/vtctldclient.txt
- go/flags/endtoend/vtexplain.txt
- go/flags/endtoend/vtgate.txt
- go/flags/endtoend/vtgr.txt
- go/flags/endtoend/vtorc.txt
- go/flags/endtoend/vttablet.txt
- go/flags/endtoend/vttestserver.txt
- go/vt/grpcclient/client.go
- go/vt/grpcclient/client_auth_static.go
- go/vt/vtctl/grpcvtctlclient/client_test.go
- go/vt/vtgate/grpcvtgateconn/conn_rpc_test.go
- go/vt/vtgate/grpcvtgateconn/fuzz_flaky_test.go
- go/vt/vttablet/tabletconntest/tabletconntest.go
Some cleanup that was missed in some other migrations I did, plus some net-new work.
- Relates to #10806.
- Relates to #10934.
- Relates to #10979.
- Closes #10891.
> [grpcclient] Migrate `--grpc_auth_static_client_creds` to pflag

- .github/docker/cluster_test_vtorc_8.0/Dockerfile
- .github/workflows/cluster_endtoend_vtorc_8.0.yml
- test/ci_workflow_gen.go
This PR moves vtorc-8.0 workflow to the self-hosted runners to de-flake them.
> Move vtorc-8.0 to self-hosted runner

- doc/internal/ReleaseInstructions.md
> [release-12.0] Update the release documentation (#11174)

- .github/workflows/codeql_analysis.yml
This Pull Request adds a new workflow created from the CodeQL template. This workflow aims to report any code vulnerabilities and errors in the Go, JavaScript, and Python code. The workflow runs on the main and the releases branch and on a CRON (every Monday). The workflow does not fail if it finds vulnerabilities; however, a comprehensive report is available on the Security page of this repository. A sample for this branch's report is available here: https://github.com/vitessio/vitess/security/code-scanning?query=is%3Aopen+branch%3Aadd-codeql-cron++.
> Add a CodeQL workflow to check vulnerabilities in the codebase

- go/cmd/rulesctl/cmd/main.go
- go/cmd/vtadmin/main.go
- go/cmd/vtctldclient/main.go
- go/flags/endtoend/vtctldclient.txt
- go/internal/flag/flag.go
- go/mysql/collations/integration/main_test.go
I applied this to everywhere I think needs it. The doc comment on `TrickGlog` explains everything (if it doesn't, let me know and I'll make it so!)
- Closes #11283.
- Closes #11276.
> [cli] Begrudgingly shim `flag.Parse` call to trick glog

- doc/releasenotes/14_0_3_changelog.md
- doc/releasenotes/14_0_3_release_notes.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/vtorc_example.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and tag commit for the v14.0.3 release.
> Release of v14.0.3

- doc/releasenotes/14_0_3_changelog.md
- doc/releasenotes/14_0_3_release_notes.md
- doc/releasenotes/14_0_3_summary.md
This PR adds the release notes for `v14.0.3` on `main`.
- #11397
> Release notes 14.0.3 on main

- go/pools/resource_pool_test.go
This PR try to reduce the flaky ness of the test `TestIdleTimeoutCreateFail`
> test: deflake TestIdleTimeoutCreateFail

- go/cmd/vtorc/main.go
Spotted this while I was prepping around for an unrelated reason.
> [vtorc] Remove duplicated vt/log import

- examples/local/vtadmin/rbac.yaml
- examples/region_sharding/vtadmin/rbac.yaml
This is a backport of https://github.com/vitessio/vitess/pull/11463
> Backport: Give all permissions in rbac in examples

- go/test/endtoend/vtgate/queries/aggregation/schema.sql
This PR fixes the syntax error introduced by https://github.com/vitessio/vitess/pull/11459.
> Fix aggregation end-to-end test PRIMARY KEY

- web/vtadmin/src/components/routes/tablet/FullStatus.tsx
This is a backport for https://github.com/vitessio/vitess/pull/11470.
> Backport (15.0): Full Status tab improvements for VTAdmin

- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/operator.yaml
This PR fixes the Vitess operator example by updating the crds and the corresponding changes to the yaml files.
> Fix Vitess Operator example

- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/operator.yaml
Forward port of https://github.com/vitessio/vitess/pull/11546
> ForwardPort: Fix Vitess Operator example

- .github/workflows/code_freeze.yml
- doc/releasenotes/15_0_0_changelog.md
- doc/releasenotes/15_0_0_release_notes.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/operator.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and tag commit for the v15.0.0 release.
> Release of v15.0.0

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v15.0.1-SNAPSHOT) after the release of v15.0.0.
> Back to dev mode after v15.0.0

- doc/internal/ReleaseInstructions.md
While doing the release 15.0, I found some gaps in release notes. This PR adds details to help release notes easy to follow.
> update release notes after 15.0

- doc/releasenotes/15_0_0_release_notes.md
- doc/releasenotes/15_0_0_summary.md
> [cherry-pick]fix vdiff release notes (#11595)

- go/test/endtoend/utils/mysql.go
This helper for endtoend tests was using the global `dbconfigs` struct for initialization, which prevents running more than one endtoend test in a single package, because the global dbconfigs can only be initialized once. This is a much more elegant solution for running tests that doesn't require shared global state.
> endtoend: fix dbconfig initialization for endtoend tests

- go/cmd/vtctldclient/command/reparents.go
- go/flags/endtoend/vtctldclient.txt
- go/vt/vtctl/reparent.go
This PR is a forward port of https://github.com/vitessio/vitess/pull/11557
- #6612
> [ForwardPort] Deprecate InitShardPrimary command (#11557)

- doc/releasenotes/15_0_0_release_notes.md
- doc/releasenotes/15_0_0_summary.md
Add a mention in the release notes for the removed `--db-config-*-*` vttablet flags.
> Mention the `--db-config-*-*` flag in the release notes

- .github/pull_request_template.md
- go.mod
- go.sum
PR fixes 
1. Use a released version instead of random SHA
2. Fixes typo in the pull request template
> update jsonparser dependency

- .github/workflows/static_checks_etc.yml
- go.sum
- go/test/endtoend/utils/cmp.go
- go/test/endtoend/vtgate/queries/derived/derived_test.go
- go/tools/ci-config/main.go
- test/config.json
> Addition of a CI tool to detect dead links in test/config.json (#11668)

- .github/CODEOWNERS
Add another EU user to .github/workflows for review approvals ...
> CODEOWNERS: Add rohit to .github/workflows

- go/test/endtoend/vtgate/queries/derived/derived_test.go
- go/test/endtoend/vtgate/queries/derived/main_test.go
- go/vt/vtgate/planbuilder/physical/route_planning.go
- go/vt/vtgate/planbuilder/testdata/select_cases.json
This is a backport of #11379. It fixes the issue described in https://github.com/vitessio/vitess/issues/11763.
Fix https://github.com/vitessio/vitess/issues/11763
> Push down derived tables under route when possible

- go/vt/vttablet/onlineddl/executor.go
Noticed a place where a returned `err` is unchecked. Failing to check it causes a dereference of `nil` pointer. The scenario where said error happens is extremely unlikely in the first place, which is why we haven't seen this before.
Also, while we're here, adding more verbosity to a few error messages in `SubmitMigration()`.
#6926
> Online DDL: adding error check; more verbose error messages

- doc/releasenotes/14_0_4_summary.md
This PR prepares the release notes summary for the release of `v14.0.4`
Fixes https://github.com/vitessio/vitess/issues/11748
> Prepare the release notes summary for `v14.0.4`

- .github/workflows/cluster_endtoend_onlineddl_declarative.yml
- .github/workflows/cluster_endtoend_onlineddl_declarative_mysql57.yml
- .github/workflows/cluster_endtoend_onlineddl_ghost.yml
- .github/workflows/cluster_endtoend_onlineddl_ghost_mysql57.yml
- .github/workflows/cluster_endtoend_onlineddl_revert.yml
- .github/workflows/cluster_endtoend_onlineddl_revert_mysql57.yml
- .github/workflows/cluster_endtoend_onlineddl_revertible.yml
- .github/workflows/cluster_endtoend_onlineddl_revertible_mysql57.yml
- .github/workflows/cluster_endtoend_onlineddl_scheduler.yml
- .github/workflows/cluster_endtoend_onlineddl_scheduler_mysql57.yml
- .github/workflows/cluster_endtoend_onlineddl_singleton.yml
- .github/workflows/cluster_endtoend_onlineddl_singleton_mysql57.yml
- .github/workflows/cluster_endtoend_onlineddl_vrepl.yml
- .github/workflows/cluster_endtoend_onlineddl_vrepl_mysql57.yml
- .github/workflows/cluster_endtoend_onlineddl_vrepl_stress.yml
- .github/workflows/cluster_endtoend_onlineddl_vrepl_stress_mysql57.yml
- .github/workflows/cluster_endtoend_onlineddl_vrepl_stress_suite.yml
- .github/workflows/cluster_endtoend_onlineddl_vrepl_stress_suite_mysql57.yml
- .github/workflows/cluster_endtoend_onlineddl_vrepl_suite.yml
- .github/workflows/cluster_endtoend_onlineddl_vrepl_suite_mysql57.yml
- .github/workflows/cluster_endtoend_schemadiff_vrepl.yml
- .github/workflows/cluster_endtoend_schemadiff_vrepl_mysql57.yml
- .github/workflows/cluster_endtoend_tabletmanager_throttler_topo.yml
- test/ci_workflow_gen.go
- test/templates/cluster_endtoend_test.tpl
- test/templates/cluster_endtoend_test_mysql57.tpl
This Pull Request fixes the issue described in https://github.com/vitessio/vitess/issues/11826.
- Fixes https://github.com/vitessio/vitess/issues/11826
> Trigger OnlineDDL workflow when test data changes

- .github/CODEOWNERS
> [release-15.0] codeowners: have at least two for almost every package (#11639)

- .github/CODEOWNERS
> [release-14.0] codeowners: have at least two for almost every package (#11639)

- go/mysql/collations/coercion.go
- go/mysql/collations/integration/coercion_test.go
> [release-15.0] collations: fix coercion semantics according to 8.0.31 changes (#11487)

- docker/release.sh
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v15.0.2-SNAPSHOT) after the release of v15.0.1.
> Back to dev mode after v15.0.1

- doc/releasenotes/15_0_1_changelog.md
- doc/releasenotes/15_0_1_release_notes.md
- doc/releasenotes/15_0_1_summary.md
Copying summary, release-notes & change-log from release15.0 to main.
> Release notes for 15.0.1

- doc/releasenotes/14_0_4_changelog.md
- doc/releasenotes/14_0_4_release_notes.md
- doc/releasenotes/14_0_4_summary.md
This PR is adding the release summary for the v14.0.4 release.
- #11846
> Release notes summary of `14.0.4`

- doc/releasenotes/14_0_4_changelog.md
- doc/releasenotes/14_0_4_release_notes.md
- docker/release.sh
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/vtorc_example.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and tag commit for the v14.0.4 release.
> Release of v14.0.4

- doc/releasenotes/15_0_1_release_notes.md
- doc/releasenotes/15_0_1_summary.md
We realized we should mentioned about vtadmin issue (https://github.com/vitessio/vitess/issues/11679) in our summary and release notes explicitly. Therefore updating them with the issue.
> updating summary and release notes for v15.0.1

- Makefile
Issue has all the details.
Closes #11856.
> [cleanup] Explicitly include DDLStrategySetting in the sizegen target

- go/vt/vttablet/tabletserver/state_manager.go
- go/vt/vttablet/tabletserver/state_manager_test.go
This PR fixes the bug uncovered in https://github.com/vitessio/vitess/issues/11885#issuecomment-1339141876. 
The main issue is that when we call `CheckMySQL` we do not set the correct wanted state. This leads to new queries not being blocked while we are waiting for the requests waitgroup to be empty. 
After looking at the history of how the code evolved in https://github.com/vitessio/vitess/issues/11885, the intent of the code and the bug was clear.
This PR fixes the bug and augments an existing test to verify that we indeed do not allow new queries to come in when checkMySQL has started running.
- Fixes #11885 
> Fix CheckMySQL by setting the correct wanted state

- docker/release.sh
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v14.0.5-SNAPSHOT) after the release of v14.0.4.
> Back to dev mode after v14.0.4

- go/vt/vttablet/tabletserver/state_manager.go
- go/vt/vttablet/tabletserver/state_manager_test.go
This is a backport PR for https://github.com/vitessio/vitess/pull/11895
> [release-13.0] Fix CheckMySQL by setting the correct wanted state #11895

- go/vt/vtgate/engine/fake_vcursor_test.go
- go/vt/vtgate/engine/primitive.go
- go/vt/vtgate/vcursor_impl.go
Reverts vitessio/vitess#11926. After a call with @harshit-gangal and @systay we decided to revert this unrequired change.
> Revert - Better clone of the VCursor

- doc/releasenotes/15_0_2_changelog.md
- doc/releasenotes/15_0_2_release_notes.md
This is a follow-up PR for the `v15.0.2` release. This PR adds the release notes docs.
> Release notes for `v15.0.2`

- .github/CODEOWNERS
This PR fixes https://github.com/vitessio/vitess/issues/11980.
> Add manan and florent to Docker files CODEOWNERS

- .github/CODEOWNERS
> Add manan and florent to Docker files CODEOWNERS (#11981)

- examples/operator/101_initial_cluster.yaml
This PR fixes the rbac config in the vtop example as pointed out in #11665 
- #11665 
> Fix rbac config in the vtop example

- go/cmd/vtctldclient/command/shard_routing_rules.go
- go/cmd/vtctldclient/command/throttler.go
- go/cmd/vtctldclient/command/topology.go
- go/flags/endtoend/vtctldclient.txt
Applying @mattlord's feedback from https://github.com/vitessio/website/pull/1177
https://github.com/vitessio/website/pull/1177 
> [vtctldclient|docs] apply doc feedback based on website PR feedback

- doc/releasenotes/15_0_2_changelog.md
- doc/releasenotes/15_0_2_release_notes.md
- doc/releasenotes/15_0_2_summary.md
- docker/release.sh
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/operator.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and tag commit for the v15.0.2 release.
> Release of v15.0.2

- go/test/endtoend/vtgate/queries/misc/misc_test.go
- go/vt/vtgate/evalengine/convert.go
- go/vt/vtgate/evalengine/translate.go
- go/vt/vtgate/evalengine/translate_test.go
> [release-15.0] BugFix: Cast expression translation by evaluation engine (#12111)

- docker/release.sh
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v15.0.3-SNAPSHOT) after the release of v15.0.2.
> Back to dev mode after v15.0.2

- go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
- go/vt/vttablet/onlineddl/executor.go
Fixes https://github.com/vitessio/vitess/issues/12208
I mean, the code which https://github.com/vitessio/vitess/pull/12169 replaced, strictly said:
> // We wrap everything in a function because we want the mutex released. We will need to reaquire it later on
> // for other bookkeeping work.
So here we are. This PR re-introduces a similar function wrap, to release the mutex before running the callback.
- https://github.com/vitessio/vitess/issues/12208
- #6926
> Online DDL: fix deadlock by releasing mutex before calling callback

- .github/workflows/code_freeze.yml
Code Freeze of release-16.0
- #11749
> Code freeze of release-16.0

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Bump reported version of main to 17.0.0 SNAPSHOT
- #11749 
> Bump reported version of main to 17.0.0 SNAPSHOT

- doc/releasenotes/16_0_0_changelog.md
- doc/releasenotes/16_0_0_release_notes.md
This PR fixes the release notes and addresses the comments in #12235
- #11749
> Fix release notes on release-16.0

- go/test/endtoend/vreplication/cluster_test.go
- go/test/endtoend/vreplication/vreplication_test.go
This is a backport of https://github.com/vitessio/vitess/pull/12271.
> [release-16.0] Download mariadb from vitess-resources (#12271)

- doc/releasenotes/16_0_0_release_notes.md
- doc/releasenotes/16_0_0_summary.md
This PR fixes the summary and release notes for release-16.0. There were changes to both the files that weren't reflected in the other. This PR syncs both of them together.
- #11749 
> Fix summary and release notes

- tools/release_utils.sh
This PR fixes the release script for updating the correct version in the docker script.
> Fix release script for the version in the docker script

- tools/do_release.sh
This PR fixes the release script for updating the correct version in the docker script for release-15.0. 
> [release-15.0] Fix release script for the version in the docker script

- doc/releasenotes/16_0_0_changelog.md
- doc/releasenotes/16_0_0_release_notes.md
- doc/releasenotes/16_0_0_summary.md
This PR copies the release notes, changelog and summary files from release-16.0 to main.
- #11749 
> Copy release notes from release-16 to `main`

- .github/workflows/static_checks_etc.yml
- go/vt/vtgate/evalengine/api_arithmetic.go
- go/vt/vtgate/evalengine/api_arithmetic_test.go
- go/vt/vtgate/evalengine/api_types.go
- go/vt/vtgate/evalengine/arithmetic.go
- go/vt/vtgate/evalengine/casting_test.go
- go/vt/vtgate/evalengine/eval.go
- go/vt/vtgate/evalengine/eval_numeric.go
- go/vt/vtgate/evalengine/eval_result.go
- go/vt/vtgate/evalengine/format.go
- misc/git/hooks/golangci-lint
Recently added code started producing linter warnings. This PR fixes that.
Also updates the CI checks to be aligned with the pre-commit checks.
Issue introduced in #12247
> fix linter warnings

- go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
- go/vt/vtgate/planbuilder/horizon_planning.go
- go/vt/vtgate/planbuilder/testdata/aggr_cases.json
- go/vt/vtgate/planbuilder/testdata/tpch_cases.json
This PR is the backport of https://github.com/vitessio/vitess/pull/12298
> [14.0] Fix aggregation on outer joins

- go/test/endtoend/vtgate/transaction/tx_test.go
- go/vt/vtgate/engine/fake_vcursor_test.go
- go/vt/vtgate/engine/set.go
- go/vt/vtgate/engine/set_test.go
This PR is backport of from https://github.com/vitessio/vitess/pull/12281
> [16.0] fix: transaction_isolation to be applied at session level

- go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
- go/vt/vtgate/planbuilder/horizon_planning.go
- go/vt/vtgate/planbuilder/testdata/aggr_cases.json
- go/vt/vtgate/planbuilder/testdata/tpch_cases.json
This PR is the backport of https://github.com/vitessio/vitess/pull/12298
> [15.0] Fix aggregation on outer joins (#12298)

- go/vt/schemadiff/table_test.go
- go/vt/sqlparser/ast_format.go
- go/vt/sqlparser/ast_format_fast.go
- go/vt/sqlparser/sql.go
- go/vt/sqlparser/sql.y
- go/vt/sqlparser/tracked_buffer_test.go
This fixes a bunch of additional canonical casing bugs in the parser. 
Fixes https://github.com/vitessio/vitess/issues/12392
> Fix additional casting bugs in the sqlparser

- doc/releasenotes/16_0_0_summary.md
This PR updates the release notes summary for views.
- part of #11559 
> Add release notes summary for views

- doc/releasenotes/16_0_0_summary.md
This is a forward port of the PR #12422 
> Add release notes summary for views (#12422)

- .github/pull_request_template.md
This PR adds a bullet point in the pull request templates' checklist, to make sure that the author has verified the tests that are modified or added aren't flaky.
> Update the pull request template to include a checkpoint for verifying modified/created tests aren't flaky

- doc/internal/ReleaseInstructions.md
This PR updates the release documentation to also include steps on how to merged during code-freeze. 
> Add steps on how to merge during code-freeze

- go/mysql/schema.go
- go/vt/vtgate/planbuilder/ddl.go
- go/vt/vtgate/planbuilder/testdata/unsupported_cases.json
- go/vt/vtgate/planbuilder/testdata/view_cases.json
- go/vt/vttablet/endtoend/views_test.go
- go/vt/vttablet/tabletserver/health_streamer.go
- go/vt/vttablet/tabletserver/health_streamer_test.go
- go/vt/vttablet/tabletserver/query_executor.go
This is a forward port of #12409.
> [main] Create Views allowed for same keyspace (#12409)

- .github/workflows/code_freeze.yml
This is a code-freeze for v16.0.0
#12293 
> Code freeze of release-16.0 for v16.0.0

- go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
- go/vt/vtgate/engine/scalar_aggregation.go
- go/vt/vtgate/engine/scalar_aggregation_test.go
- go/vt/vtgate/executor_select_test.go
This is a forwardport of #12468.
> [main] Fix scalar aggregation engine primitive for column truncation (#12468)

- doc/releasenotes/16_0_0_summary.md
- Added experimental note to dynamic throttler configuration
- Fixed typo, and lights rearranged content
#12470 
> release notes: mark dynamic throttler configuration as experimental

- go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
- go/vt/vtgate/engine/scalar_aggregation.go
- go/vt/vtgate/engine/scalar_aggregation_test.go
- go/vt/vtgate/executor_select_test.go
> [releaes-15.0] Fix scalar aggregation engine primitive for column truncation (#12468)

- go/vt/vtgate/planbuilder/testdata/dml_cases.json
- go/vt/vtgate/planbuilder/testdata/select_cases.json
- go/vt/vtgate/semantics/semantic_state.go
---------
This is a backport of #12484
> [release-14.0] BugFix: Unsharded query using a derived table and a dual table (#12484)

- .github/workflows/upgrade_downgrade_test_backups_e2e.yml
- .github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml
- .github/workflows/upgrade_downgrade_test_backups_manual.yml
- .github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml
- .github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml
- .github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml
- .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml
- .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml
This PR makes all Upgrade/Downgrade job unique in our workflows, this in preparation to re-enable the required checks on our Upgrade/Downgrade suite.
> Make upgrade downgrade job names unique

- doc/releasenotes/16_0_0_changelog.md
- doc/releasenotes/16_0_0_release_notes.md
- doc/releasenotes/16_0_0_summary.md
This PR copies the release notes and changelog from release-16.0.0 to main.
- #12293 
> Copy release notes from release-16.0.0 to main

- docker/release.sh
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v16.0.1-SNAPSHOT) after the release of v16.0.0.
> Back to dev mode after v16.0.0

- go/vt/vtorc/logic/topology_recovery.go
This fix PR fixes https://github.com/vitessio/vitess/issues/12509
> Fix unhandled error in VTOrc `recoverDeadPrimary`

- .github/workflows/upgrade_downgrade_test_backups_e2e.yml
- .github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml
- .github/workflows/upgrade_downgrade_test_backups_manual.yml
- .github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml
- .github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml
- .github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml
- .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml
- .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml
> [release-16.0] Make upgrade downgrade job names unique

- go/mysql/collations/internal/uca/iter_fast_900.go
> collations: fix sorting in UCA900 collations (#12555)

- doc/internal/ReleaseInstructions.md
This PR includes slight enhancements to the release instructions for gaps that were found during the v16 GA release.
> Improve release instructions post `v16.0.0 GA` release

- go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
- go/test/endtoend/vtgate/queries/aggregation/schema.sql
- go/test/endtoend/vtgate/queries/aggregation/vschema.json
- go/vt/vtgate/executor_select_test.go
- go/vt/vtgate/planbuilder/abstract/queryprojection.go
- go/vt/vtgate/planbuilder/gen4_planner.go
- go/vt/vtgate/planbuilder/horizon_planning.go
- go/vt/vtgate/planbuilder/testdata/aggr_cases.json
- go/vt/vtgate/planbuilder/testdata/select_cases.json
- go/vt/vtgate/semantics/semantic_state.go
> [release-14.0] Make sure to not push down expressions when not possible (#12607)

- go/vt/mysqlctl/schema.go
Cherry pick of https://github.com/vitessio/vitess/pull/12641 for `release-15.0`
--
Identify the two scenarios where a table may be dropped while we're inspecting the schema. Either we get a `(errno 1146)` error code, or the table does not appear in `information_schema` even after it did, before. 
The fix is to silently ignore tables hitting this scenario.
- Fixes: https://github.com/vitessio/vitess/issues/12640
> Cherry pick v15: Mysqld.GetSchema: tolerate tables being dropped while inspecting schema

- tools/make-release-packages.sh
> [release-16.0] Add the vtadmin web directory to the release packages (#12639)

- go/vt/mysqlctl/schema.go
Cherry pick of https://github.com/vitessio/vitess/pull/12641 for `release-16.0`
--
Identify the two scenarios where a table may be dropped while we're inspecting the schema. Either we get a `(errno 1146)` error code, or the table does not appear in `information_schema` even after it did, before. 
The fix is to silently ignore tables hitting this scenario.
- Fixes: https://github.com/vitessio/vitess/issues/12640
> Cherry pick v16: Mysqld.GetSchema: tolerate tables being dropped while inspecting schema

- go/vt/vtgate/planbuilder/operators/derived.go
- go/vt/vtgate/planbuilder/testdata/info_schema57_cases.json
- go/vt/vtgate/planbuilder/testdata/info_schema80_cases.json
> [release-16.0] Always add columns in the `Derived` operator (#12634)

- go/test/endtoend/reparent/newfeaturetest/reparent_test.go
- go/vt/vtctl/grpcvtctldserver/endtoend/init_shard_primary_test.go
- go/vt/vttablet/tabletmanager/tm_init.go
- go/vt/vttablet/tabletmanager/tm_init_test.go
- go/vt/wrangler/testlib/backup_test.go
- go/vt/wrangler/testlib/copy_schema_shard_test.go
- go/vt/wrangler/testlib/emergency_reparent_shard_test.go
- go/vt/wrangler/testlib/external_reparent_test.go
- go/vt/wrangler/testlib/permissions_test.go
- go/vt/wrangler/testlib/planned_reparent_shard_test.go
- go/vt/wrangler/testlib/reparent_utils_test.go
- go/vt/wrangler/testlib/version_test.go
> [release-16.0] Fix initialization code to also stop replication to prevent crash #12534

- go/vt/vtgate/planbuilder/physical/operator_funcs.go
- go/vt/vtgate/planbuilder/testdata/select_cases.json
> [release-14.0] Always add columns in the `Derived` operator

- go/vt/sqlparser/ast_funcs.go
- go/vt/sqlparser/ast_test.go
- go/vt/vtgate/planbuilder/operators/SQL_builder.go
- go/vt/vtgate/planbuilder/testdata/aggr_cases.json
> [planner bugfix] add expressions to HAVING (#12668)

- .github/workflows/update_golang_version.yml
- go.mod
- go.sum
- go/tools/go-upgrade/go-upgrade.go
> [release-16.0] Auto upgrade the Golang version (#12585)

- .github/workflows/update_golang_version.yml
- go.mod
- go.sum
- go/tools/go-upgrade/go-upgrade.go
> [release-15.0] Auto upgrade the Golang version (#12585)

- go/vt/vttablet/tabletserver/repltracker/reader.go
- go/vt/vttablet/tabletserver/repltracker/reader_test.go
- go/vt/vttablet/tabletserver/repltracker/writer_test.go
> [release-14.0] Reset the current lag when closing the replication lag reader. (#12683)

- changelog/16.0/16.0.1/summary.md
- changelog/16.0/README.md
This PR adds the `v16.0.1` release notes summary.
- https://github.com/vitessio/vitess/issues/12697
> Addition of the `v16.0.1` release summary

- .github/workflows/code_freeze.yml
Code-freeze for `releaes-16.0` for v16.0.1 patch.
- #12697
> Release 16.0 code freeze for 16.0.1 patch release

- .github/workflows/code_freeze.yml
> Code freeze of `release-14.0` for `v14.0.5`

- .github/workflows/code_freeze.yml
> Code freeze of release-15.0

- docker/release.sh
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v15.0.4-SNAPSHOT) after the release of v15.0.3.
> Back to dev mode after v15.0.3

- docker/release.sh
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v14.0.6-SNAPSHOT) after the release of v14.0.6.
> Back to dev mode after v14.0.5

- docker/release.sh
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v16.0.2-SNAPSHOT) after the release of v16.0.1.
> Back to dev mode after v16.0.1

- .github/workflows/create_release.yml
- .github/workflows/docker_test_cluster_10.yml
- .github/workflows/docker_test_cluster_25.yml
- .github/workflows/endtoend.yml
- .github/workflows/sonar_analysis.yml
- .github/workflows/static_checks_etc.yml
- .github/workflows/upgrade_downgrade_test_backups_manual.yml
- .github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
> [release-15.0] Remove unnecessary code bits in workflows (#12756)

- .github/workflows/assign_milestone.yml
> [release-14.0] Automatically add milestone to new Pull Request (#12759)

- go/vt/wrangler/fake_dbclient_test.go
We have tests like `TestMoveTablesV2` which end up reading and writing queries concurrently. This causes the race detector to appropriately trigger and detect issues here.
See failures like in https://github.com/vitessio/vitess/actions/runs/4570206997/jobs/8067282756
> fakedbclient: Add locking to avoid races

- go/cmd/vtorc/main.go
- go/vt/servenv/servenv.go
Remembering to clean up some old TODOs I left from 2 versions ago.
> Cleanup TODOs in vtorc flag parsing code from v15

- go/vt/vtgate/planbuilder/abstract/derived.go
- go/vt/vtgate/planbuilder/abstract/operator_test.go
- go/vt/vtgate/planbuilder/testdata/aggr_cases.json
- go/vt/vtgate/planbuilder/testdata/unsupported_cases.json
> [release-14.0] planbuilder bugfix - do not push aggregations into derived tables

- go/cmd/vtorc/main.go
- go/vt/servenv/servenv.go
This is a backport of #12787.
cc @ajm188
> [release-16.0] Cleanup TODOs in vtorc flag parsing code from v15 (#12787)

- go/vt/wrangler/fake_dbclient_test.go
> [release-14.0] fakedbclient: Add locking to avoid races (#12814)

- go/vt/wrangler/fake_dbclient_test.go
> [release-16.0] fakedbclient: Add locking to avoid races (#12814)

- go/vt/vtgate/planbuilder/abstract/derived.go
- go/vt/vtgate/planbuilder/testdata/aggr_cases.json
- go/vt/vtgate/planbuilder/testdata/unsupported_cases.json
> [release-15.0] planbuilder bugfix - do not push aggregations into derived tables

- go/test/endtoend/cellalias/cell_alias_test.go
- go/test/endtoend/cluster/cluster_process.go
- go/test/endtoend/cluster/vtgate_process.go
- go/test/endtoend/recovery/unshardedrecovery/recovery.go
- go/test/endtoend/utils/utils.go
- go/test/endtoend/vreplication/resharding_workflows_v2_test.go
- go/test/endtoend/vreplication/vreplication_test.go
- go/test/endtoend/vreplication/vschema_load_test.go
- go/test/endtoend/vreplication/vstream_test.go
- go/test/endtoend/vtgate/schematracker/loadkeyspace/schema_load_keyspace_test.go
- go/test/endtoend/vtgate/schematracker/restarttablet/schema_restart_test.go
- go/test/endtoend/vtgate/schematracker/unauthorized/unauthorized_test.go
- go/test/endtoend/vtgate/tablet_healthcheck_cache/correctness_test.go
> [release-16.0] Fix `vtgate_schema_tracker` flaky tests (#12780)

- go/test/endtoend/cellalias/cell_alias_test.go
- go/test/endtoend/cluster/cluster_process.go
- go/test/endtoend/cluster/vtgate_process.go
- go/test/endtoend/recovery/unshardedrecovery/recovery.go
- go/test/endtoend/utils/utils.go
- go/test/endtoend/vreplication/materialize_test.go
- go/test/endtoend/vreplication/migrate_test.go
- go/test/endtoend/vreplication/performance_test.go
- go/test/endtoend/vreplication/resharding_workflows_v2_test.go
- go/test/endtoend/vreplication/time_zone_test.go
- go/test/endtoend/vreplication/vdiff2_test.go
- go/test/endtoend/vreplication/vreplication_test.go
- go/test/endtoend/vreplication/vschema_load_test.go
- go/test/endtoend/vreplication/vstream_test.go
- go/test/endtoend/vtgate/schematracker/loadkeyspace/schema_load_keyspace_test.go
- go/test/endtoend/vtgate/schematracker/restarttablet/schema_restart_test.go
- go/test/endtoend/vtgate/schematracker/unauthorized/unauthorized_test.go
- go/test/endtoend/vtgate/tablet_healthcheck_cache/correctness_test.go
> [release-15.0] Fix `vtgate_schema_tracker` flaky tests (#12780)

- go/test/endtoend/vreplication/config_test.go
- go/vt/vttablet/tabletmanager/vreplication/framework_test.go
- go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go
- go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go
- go/vt/vttablet/tabletserver/vstreamer/testenv/testenv.go
- go/vt/vttablet/tabletserver/vstreamer/vstreamer_flaky_test.go
This is on top of #12861 but showcases a bunch of tests are broken. We never noticed since we were never running these tests even when we should. It means either the tests are broken or the underlying code is broken.
Uncovered in due to the work in #12861
> vreplication: Run all appropriate tests

- go/vt/vtgate/semantics/analyzer.go
- go/vt/vtgate/semantics/early_rewriter.go
- go/vt/vtgate/semantics/early_rewriter_test.go
- go/vt/vtgate/semantics/semantic_state.go
In a recent PR, I cleaned up a little too much. Re-introducing the expanded columns field that we want around.
#12894
> feat: re-introduce expanded columns info in semantic state

- go/vt/vtgate/planbuilder/testdata/select_cases.json
- go/vt/vtgate/semantics/analyzer_test.go
- go/vt/vtgate/semantics/scoper.go
- go/vt/vtgate/semantics/semantic_state.go
- go/vt/vtgate/semantics/table_set.go
> [release-15.0] planner fix: scoping rules for JOIN ON expression inside a subquery

- go/test/endtoend/cluster/cluster_process.go
- go/test/endtoend/reparent/prssettingspool/main_test.go
- go/test/endtoend/reparent/prssettingspool/schema.sql
- go/test/endtoend/reparent/utils/utils.go
- go/vt/vtgate/safe_session.go
- test/config.json
This is forward port of https://github.com/vitessio/vitess/pull/12779 from branch 15.0
> [16.0] Fix: reset transaction session when no reserved connection

- go/cmd/zkctl/zkctl.go
- go/mysql/datetime/helpers.go
- go/mysql/datetime/types.go
- go/mysql/query_test.go
- go/vt/external/golib/sqlutils/sqlutils.go
- go/vt/vtgr/config/vtgr_config.go
- go/vt/vtgr/controller/refresh.go
- go/vt/vtorc/inst/instance_binlog.go
- go/vt/vtorc/inst/instance_dao.go
This is unused code, so let's remove it from here.
> sqlutils: Cleanup dead code

- go/vt/vttablet/tabletserver/query_executor.go
- go/vt/vttablet/tabletserver/tx_engine.go
`govet` helpfully pointed these out while I was working on another branch, so I extracted a cleanup
N/A
> [vttablet] cleanup unused code in tabletserver

- go/vt/vtgate/executor_select_test.go
In the Executor plan cache, we use Ristretto Cache which uses a buffer channel to store the item. Sometime it can take time before the plan cache could be visible.
So, I changed the test to re-check the plan cache for the expected entry.
> test: fix cfc flaky test

- go/vt/vttablet/onlineddl/executor.go
The [atomic Online DDL cut-over](https://github.com/planetscale/vitess-private/pull/1295) algorithm uses a `RENAME` statement, that places a metadata lock on the affected tables. In any case of error (deadlock, timeout, other), the operation bails out, and `KILL`s the `RENAME` query.
In the current logic, the `KILL` query is invoked as a deferred function, whichever the migration result is - even if successful. This is fine logic-wise, since there's nothing to kill, really. However, this is both wasteful and noisy. If we can avoid running a query, we should. Monitoring for `KILL` queries, which normally indicate something significant, can be noisy if there's a lot of migrations.
This PR does not invoke `KILL` is the `RENAME` was successful.
#6926 
-   [ ] "Backport to:" labels have been …
> OnlineDDL/vitess: only KILL 'RENAME' statement if not known to be successful

- .gitignore
- go/vt/vtgate/planbuilder/operator_transformers.go
- go/vt/vtgate/planbuilder/testdata/union_cases.json
This is a backport of https://github.com/vitessio/vitess/pull/12968.
> [release-15.0] fix: union distinct between unsharded route and sharded join (#12968)

- .gitignore
- go/vt/vtgate/planbuilder/operator_transformers.go
- go/vt/vtgate/planbuilder/testdata/union_cases.json
This is a backport of https://github.com/vitessio/vitess/pull/12968.
> [release-14.0] fix: union distinct between unsharded route and sharded join (#12968)

- go/mysql/conn.go
- go/pools/resource_pool.go
- go/stats/counter.go
- go/stats/prometheusbackend/prometheusbackend.go
- go/textutil/hash.go
- go/vt/external/golib/sqlutils/sqlutils.go
- go/vt/schemadiff/diff.go
- go/vt/sqlparser/ast_funcs.go
- go/vt/topo/locks.go
- go/vt/vtadmin/http/keyspaces.go
Fix the inconsistency between the first word and the method name in the comment.
> fix some code comments throughout the codebase

- .github/workflows/code_freeze.yml
- changelog/16.0/16.0.2/changelog.md
- changelog/16.0/16.0.2/release_notes.md
- changelog/16.0/README.md
- docker/release.sh
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/operator.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the v16.0.2 release. Once this PR is merged, we will be able to tag v16.0.2 on the merge commit.
- #12879
> Release of v16.0.2

- docker/release.sh
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v16.0.3-SNAPSHOT) after the release of v16.0.2.
> Back to dev mode after v16.0.2

- .github/workflows/update_golang_version.yml
This Pull Request fixes something wrong in the auto-upgrade-golang tooling, the workflow would fail when detecting if a previous upgrade PR was created or not.
> Fix auto-upgrade-golang tooling

- examples/operator/README.md
Use latest k8s version in example for it to work.
- Fixes https://github.com/vitessio/vitess/issues/13094 
> Use latest k8s for operator example to work

- web/vtadmin/vite.config.ts
This PR fixes the asset paths for VTAdmin so that we can open schema/shard pages in new tabs
`index.html` before
```
[build] cat index.html                                                                                                                                                                                                                    22:45:37  ☁  main ☀
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<link rel="icon" href="./favicon.ico" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="theme-color" content="#000000" />
<link rel="apple-touch-icon" href="/logo192.png" />
<link rel="manifest" href="./manifest.json" />
<script src="./config/config.js"></script>
...
<title>VTAdmin</title>
<script type="module" crossorigin …
```
> update vite base to respect absolute path

- go/vt/vttablet/onlineddl/executor.go
While experimenting with another PR, I noticed that in the Online DDL cut-over phase, if the `RENAME TABLE` statement returns with error:
- The error is reported in the vttablet logs
- The flow is technically correct, but ends up terminating on timeout
- The error is not reported in the `schema_migrations` table
This PR catches the unexpected early return from `RENAME TABLE`, and breaks the migration earlier, and also returning with said error.
As result we don't wait for the timeout, and the `schema_migrations.message` column clearly indicates the error.
The reason we've never noticed this before, is that the common scenario for `RENAME` failing is a timeout, which is superfluous to our timeout test in code, and so this error is implicitly reported as timeout anyway.
In my offline …
> Online DDL: better reporting of error message when RENAME fails

- ADOPTERS.md
Added Vinted to `ADOPTERS.md`.
Website [already updated](https://github.com/vitessio/website/pull/1041).
> Add Vinted to the list of adopters

- changelog/17.0/17.0.0/summary.md
Review and cleanup of the release notes summary for v17.
- Fixes: https://github.com/vitessio/vitess/issues/13139
> Review and cleanup of v17 RC release notes summary

- .github/workflows/code_freeze.yml
Freeze the new release-17.0 branch for the RC-1 release.
- https://github.com/vitessio/vitess/issues/13138
> Code freeze of release-17.0

- go/mysql/fakesqldb/server.go
- go/vt/vttablet/tabletserver/health_streamer.go
- go/vt/vttablet/tabletserver/health_streamer_test.go
- go/vt/vttablet/tabletserver/state_manager.go
This PR is a back port of https://github.com/vitessio/vitess/pull/13184 to release-15.0
- https://github.com/vitessio/vitess/issues/13182
> [15.0] Fix: errant GTID in health streamer (#13184)

- go/mysql/fakesqldb/server.go
- go/vt/vttablet/tabletserver/health_streamer.go
- go/vt/vttablet/tabletserver/health_streamer_test.go
- go/vt/vttablet/tabletserver/state_manager.go
This PR is a back port of https://github.com/vitessio/vitess/pull/13184 to release-14.0
- https://github.com/vitessio/vitess/issues/13182
> [14.0] Fix: errant GTID in health streamer (#13184)

- .github/workflows/code_freeze.yml
Code freeze in preparation for v17.0.0-rc2.
- Part of: https://github.com/vitessio/vitess/issues/13295
> Code freeze of release-17.0 for rc2

- go/vt/sqlparser/parse_test.go
- go/vt/sqlparser/sql.go
- go/vt/sqlparser/sql.y
- go/vt/sqlparser/token.go
> [release-15.0] Remove indentation limit in the sqlparser (#13158)

- go/vt/sqlparser/parse_test.go
- go/vt/sqlparser/sql.go
- go/vt/sqlparser/sql.y
- go/vt/sqlparser/token.go
> [release-16.0] Remove indentation limit in the sqlparser (#13158)

- changelog/17.0/17.0.0/release_notes.md
- changelog/17.0/17.0.0/summary.md
- go/cmd/vtgr/main.go
- go/flags/endtoend/vtgr.txt
> [release-17.0] Deprecate VTGR (#13301)

- .github/workflows/code_freeze.yml
- changelog/17.0/17.0.0/changelog.md
- changelog/17.0/17.0.0/release_notes.md
- docker/release.sh
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the v17.0.0-rc2 release. Once this PR is merged, we will be able to tag v17.0.0-rc2 on the merge commit.
> Release of v17.0.0-rc2

- changelog/17.0/17.0.0/changelog.md
- changelog/17.0/17.0.0/release_notes.md
This forward ports the release notes changes from the v17.0.0-rc2 release PR: https://github.com/vitessio/vitess/pull/13305
- https://github.com/vitessio/vitess/pull/13305
> Update release notes for 17.0.0-rc2

- go/cmd/vtctldclient/command/reparents.go
See https://github.com/vitessio/website/pull/1467. Once the back ports are created I will regenerate the docs for those pages.
https://github.com/vitessio/website/pull/1467
-   [-] Tests were added or are not required
-   [-] Did the new or modified tests pass consistently locally and on the CI
> update link for reparenting guide

- changelog/17.0/17.0.0/release_notes.md
- changelog/17.0/17.0.0/summary.md
This PR enhances the release notes summary for the upcoming `v17.0.0` release.
- https://github.com/vitessio/vitess/issues/13151
> Prepare and clean summary docs for `v17.0.0`

- docker/release.sh
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v17.0.1-SNAPSHOT) after the release of v17.0.0.
> Back to dev mode after v17.0.0

- Makefile
- doc/internal/ReleaseInstructions.md
- go/tools/release-notes/release_notes.go
This is a backport of #13273 and #13310
> [release-16.0] Set the number of threads for release notes generation with a flag

- go/vt/mysqlctl/fakemysqldaemon/fakemysqldaemon.go
- go/vt/mysqlctl/replication.go
- go/vt/vtctl/grpcvtctldserver/endtoend/init_shard_primary_test.go
- go/vt/vttablet/tabletmanager/rpc_replication.go
- go/vt/vttablet/tabletmanager/tm_init_test.go
- go/vt/wrangler/testlib/backup_test.go
- go/vt/wrangler/testlib/copy_schema_shard_test.go
- go/vt/wrangler/testlib/emergency_reparent_shard_test.go
- go/vt/wrangler/testlib/external_reparent_test.go
- go/vt/wrangler/testlib/permissions_test.go
- go/vt/wrangler/testlib/planned_reparent_shard_test.go
- go/vt/wrangler/testlib/reparent_utils_test.go
- go/vt/wrangler/testlib/version_test.go
> [release-15.0] Prevent resetting replication every time we set replication source (#13377)

- go/vt/mysqlctl/fakemysqldaemon/fakemysqldaemon.go
- go/vt/mysqlctl/replication.go
- go/vt/vtctl/grpcvtctldserver/endtoend/init_shard_primary_test.go
- go/vt/vttablet/tabletmanager/rpc_replication.go
- go/vt/vttablet/tabletmanager/tm_init_test.go
- go/vt/wrangler/testlib/backup_test.go
- go/vt/wrangler/testlib/copy_schema_shard_test.go
- go/vt/wrangler/testlib/emergency_reparent_shard_test.go
- go/vt/wrangler/testlib/external_reparent_test.go
- go/vt/wrangler/testlib/permissions_test.go
- go/vt/wrangler/testlib/planned_reparent_shard_test.go
- go/vt/wrangler/testlib/reparent_utils_test.go
- go/vt/wrangler/testlib/version_test.go
> [release-16.0] Prevent resetting replication every time we set replication source (#13377)

- go/event/syslogger/fake_logger.go
- go/event/syslogger/syslogger_test.go
- go/vt/vttablet/tabletserver/schema/engine.go
- go/vt/vttablet/tabletserver/schema/engine_test.go
This is a backport of https://github.com/vitessio/vitess/pull/13421.
> [release-15.0] Ignore error while reading table data in Schema.Engine reload (#13421)

- go/vt/vtorc/server/api.go
> [release-16.0] Remove excessive logging in VTOrc APIs (#13459)

- go/vt/vtorc/server/api.go
> [release-15.0] Remove excessive logging in VTOrc APIs (#13459)

- go/viperutil/internal/sync/sync_test.go
Skipping in CI until I fix the flakiness
#13498 
> [vipersync] skip flaky test

- go/test/endtoend/vtorc/general/vtorc_test.go
- go/test/endtoend/vtorc/primaryfailure/primary_failure_test.go
- go/test/endtoend/vtorc/readtopologyinstance/main_test.go
- go/test/endtoend/vtorc/utils/utils.go
This PR is a backport of #13489
> [release-17.0]: Fix flakiness in VTOrc tests (#13489)

- go/vt/mysqlctl/mysqld.go
> mysqlctl: Remove noisy log line

- go/tools/release-notes/release_notes.go
- go/tools/release-notes/release_notes_test.go
> [release-16.0] Optimize release notes generation to use GitHub Milestones (#13398)

- go/tools/release-notes/release_notes.go
- go/tools/release-notes/release_notes_test.go
> [release-17.0] Optimize release notes generation to use GitHub Milestones (#13398)

- .github/workflows/code_freeze.yml
> Code freeze of release-15.0 for release of v15.0.4

- .github/workflows/code_freeze.yml
This accomplishes the code-freeze of release-16.0 for the release of v16.0.3.
- #13612 
> Code freeze of release-16.0 for release of v16.0.3

- go/test/endtoend/recovery/recovery_util.go
- go/test/endtoend/recovery/unshardedrecovery/recovery.go
- go/vt/vttablet/tabletmanager/restore.go
This is a backport of https://github.com/vitessio/vitess/pull/13557
> backport fix 13557 to v15

- .github/workflows/code_freeze.yml
- changelog/15.0/15.0.4/changelog.md
- changelog/15.0/15.0.4/release_notes.md
- changelog/15.0/README.md
- docker/release.sh
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/operator.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the v15.0.4 release. Once this PR is merged, we will be able to tag v15.0.4 on the merge commit.
> Release `v15.0.4`

- .github/workflows/code_freeze.yml
- changelog/17.0/17.0.1/changelog.md
- changelog/17.0/17.0.1/release_notes.md
- changelog/17.0/README.md
- docker/release.sh
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/operator.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the v17.0.1 release. Once this PR is merged, we will be able to tag v17.0.1 on the merge commit.
- https://github.com/vitessio/vitess/issues/13611
> Release of v17.0.1

- docker/release.sh
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v15.0.5-SNAPSHOT) after the release of v15.0.4.
> Back to dev mode after v15.0.4

- .github/workflows/code_freeze.yml
Code Freeze for `v16.0.3`
- https://github.com/vitessio/vitess/issues/13787
> Release 16.0 code freeze for `v16.0.3` release

- .github/workflows/code_freeze.yml
Freeze the release-17.0 branch in preparation for the 17.0.2 release.
- Part of: https://github.com/vitessio/vitess/issues/13786
> Release 17.0.2 code freeze

- .github/workflows/code_freeze.yml
- changelog/16.0/16.0.4/changelog.md
- changelog/16.0/16.0.4/release_notes.md
- changelog/16.0/README.md
- docker/release.sh
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/operator.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the v16.0.4 release. Once this PR is merged, we will be able to tag v16.0.4 on the merge commit.
Release Issue - https://github.com/vitessio/vitess/issues/13787
> Release of v16.0.4

- .github/workflows/code_freeze.yml
- changelog/17.0/17.0.2/changelog.md
- changelog/17.0/17.0.2/release_notes.md
- changelog/17.0/README.md
- docker/release.sh
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/operator.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the v17.0.2 release. Once this PR is merged, we will be able to tag v17.0.2 on the merge commit.
> Release of v17.0.2

- docker/release.sh
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v16.0.5-SNAPSHOT) after the release of v16.0.4.
#13808
> Back to dev mode after v16.0.4

- docker/release.sh
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v17.0.3-SNAPSHOT) after the release of v17.0.2.
> Back to dev mode after v17.0.2

- .github/workflows/cluster_endtoend_backup_pitr_xtrabackup.yml
- .github/workflows/cluster_endtoend_xb_backup.yml
- .github/workflows/cluster_endtoend_xb_recovery.yml
- .github/workflows/codeql_analysis.yml
- .github/workflows/endtoend.yml
- .github/workflows/unit_race.yml
- .github/workflows/unit_test_mysql57.yml
- .github/workflows/unit_test_mysql80.yml
- .github/workflows/upgrade_downgrade_test_backups_e2e.yml
- .github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml
- .github/workflows/upgrade_downgrade_test_backups_manual.yml
- .github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml
- .github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml
- .github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml
- .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml
- .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml
- go/cmd/vttestserver/vttestserver_test.go
- go/test/endtoend/utils/utils.go
- go/vt/grpcclient/client_flaky_test.go
- go/vt/vttest/toxiproxyctl.go
- test/templates/cluster_endtoend_test.tpl
- test/templates/cluster_endtoend_test_docker.tpl
- test/templates/cluster_endtoend_test_self_hosted.tpl
- test/templates/unit_test.tpl
- test/templates/unit_test_self_hosted.tpl
This is a collection of changes that address GitHub Actions failures seen when performing some tests against various self-hosted runners.
> CI: Misc test improvements to limit failures with various runners

- go/cmd/vtcombo/main.go
- go/test/endtoend/reparent/newfeaturetest/reparent_test.go
- go/vt/mysqlctl/fakemysqldaemon/fakemysqldaemon.go
- go/vt/mysqlctl/mysql_daemon.go
- go/vt/mysqlctl/replication.go
- go/vt/vterrors/code.go
- go/vt/vttablet/tabletmanager/rpc_actions.go
- go/vt/vttablet/tabletmanager/rpc_replication.go
- go/vt/vttablet/tabletmanager/tm_init.go
> [release-16.0] Fix: convertBoolToSemiSyncAction method to account for all semi sync actions (#13075)

- go/cmd/vtcombo/main.go
- go/test/endtoend/reparent/newfeaturetest/reparent_test.go
- go/vt/mysqlctl/fakemysqldaemon/fakemysqldaemon.go
- go/vt/mysqlctl/mysql_daemon.go
- go/vt/mysqlctl/replication.go
- go/vt/vttablet/tabletmanager/rpc_actions.go
- go/vt/vttablet/tabletmanager/rpc_replication.go
- go/vt/vttablet/tabletmanager/tm_init.go
> [release-15.0] Fix: convertBoolToSemiSyncAction method to account for all semi sync actions (#13075)

- go/cmd/zkctld/docgen/main.go
ummm ... im sorry 😭 
on the other hand, only happened once at the very end of the migration!
#14094 
-   [x] Documentation was added or is not required (will run against main when merged)
> fix bad copy-paste in zkctld docgen

- .github/workflows/code_freeze.yml
- tools/code_freeze.sh
This PR is prep work for v18 release.
> Code freeze of release-18.0

- .github/workflows/code_freeze.yml
This PR accomplishes the code freeze of `release-15.0` for `v15.0.5`
- https://github.com/vitessio/vitess/issues/14139
> Code freeze of release-15.0 for `v15.0.5`

- docker/release.sh
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v17.0.4-SNAPSHOT) after the release of v17.0.3.
> Back to dev mode after v17.0.3

- docker/release.sh
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v15.0.6-SNAPSHOT) after the release of v15.0.5.
> Back to dev mode after v15.0.5

- docker/release.sh
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v16.0.6-SNAPSHOT) after the release of v16.0.5.
> Back to dev mode after v16.0.5

- web/vtadmin/package-lock.json
This is after running `npm audit fix`.
> Update vtadmin dependencies

- go/test/endtoend/vtgate/queries/random/random_test.go
- go/vt/vtgate/evalengine/translate_card.go
- go/vt/vtgate/planbuilder/operators/projection.go
- go/vt/vtgate/semantics/semantic_state.go
> Planner bugfix

- go/vt/wrangler/fake_tablet_test.go
> [release-18.0] TestStreamMigrateMainflow: fix panic in test

- docker/release.sh
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v18.0.0-SNAPSHOT) after the release of v18.0.0.
> Back to dev mode after v18.0.0

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v16.0.7-SNAPSHOT) after the release of v16.0.6.
> Back to dev mode after v16.0.6

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v17.0.5-SNAPSHOT) after the release of v17.0.4.
> Back to dev mode after v17.0.4

- changelog/18.0/18.0.0/summary.md
When #13137 was implemented, it was not added to the summary release notes for v18. Since this is a major change, it should be documented in the release notes.
#13137 
> release notes: add FK import to summary

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-18.0` for `v18.0.1`
> [release-18.0] Code Freeze for `v18.0.1`

- .github/workflows/code_freeze.yml
- changelog/18.0/18.0.1/changelog.md
- changelog/18.0/18.0.1/release_notes.md
- changelog/18.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the v18.0.1 release. Once this PR is merged, we will be able to tag v18.0.1 on the merge commit.
> Release of v18.0.1

- changelog/18.0/18.0.1/changelog.md
- changelog/18.0/18.0.1/release_notes.md
- changelog/18.0/README.md
This PR moves release notes of v18.0.1 to main
> v18.0.1 release notes to main

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v18.0.2-SNAPSHOT) after the release of v18.0.1.
> Back to dev mode after v18.0.1

- go/vt/vttablet/tabletserver/tabletserver.go
This PR adds an error log to newly added code in https://github.com/vitessio/vitess/pull/14565 to help with debugging.
- Addresses review comment https://github.com/vitessio/vitess/pull/14565#discussion_r1408268841
> Add log for error to help debug

- .github/workflows/cluster_endtoend_mysql_server_vault.yml
- .github/workflows/static_checks_etc.yml
This PR adds a small step to the static check GHA workflow to ensure that all workflows have been correctly generated.
> Add step to static check to ensure consistency of GHA workflows

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-18.0` for `v18.0.2`
> [release-18.0] Code Freeze for `v18.0.2`

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-17.0` for `v17.0.5`
> [release-17.0] Code Freeze for `v17.0.5`

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-16.0` for `v16.0.7`
> [release-16.0] Code Freeze for `v16.0.7`

- .github/workflows/code_freeze.yml
- changelog/16.0/16.0.7/changelog.md
- changelog/16.0/16.0.7/release_notes.md
- changelog/16.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v16.0.7` release. Once this PR is merged, we will be able to tag `v16.0.7` on the merge commit.
> [release-16.0] Release of `v16.0.7`

- .github/workflows/code_freeze.yml
- changelog/17.0/17.0.5/changelog.md
- changelog/17.0/17.0.5/release_notes.md
- changelog/17.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v17.0.5` release. Once this PR is merged, we will be able to tag `v17.0.5` on the merge commit.
> [release-17.0] Release of `v17.0.5`

- .github/workflows/code_freeze.yml
- changelog/18.0/18.0.2/changelog.md
- changelog/18.0/18.0.2/release_notes.md
- changelog/18.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v18.0.2` release. Once this PR is merged, we will be able to tag `v18.0.2` on the merge commit.
> [release-18.0] Release of `v18.0.2`

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v16.0.8-SNAPSHOT) after the release of v16.0.7.
> Back to dev mode after v16.0.7

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v18.0.3-SNAPSHOT) after the release of v18.0.2.
> Back to dev mode after v18.0.2

- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the changes required to go back into dev mode (v17.0.6-SNAPSHOT) after the release of v17.0.5.
> Back to dev mode after v17.0.5

- README.md
👋  Non-code change to the project’s README 📓
- Corrects non-functioning `issue` link
- Updates link text to be descriptive (to help the user understand what they are clicking on, rather than “here”) ([source](https://developer.chrome.com/docs/lighthouse/seo/link-text))
- Simplifies some language 😁 
> Improve links in README

- go/list/list_test.go
Add tests for list initialization, insertion, removal, and element retrieval.
Improve Unit Test Coverage https://github.com/vitessio/vitess/issues/14931
> tests: add tests for `go/list`

- go/vt/vtgate/engine/opcode/constants_test.go
Bumps coverage to 100% for `vt/vtgate/engine/opcode`
#14931
> tests: add tests for `vt/vtgate/engine/opcode`

- changelog/19.0/19.0.0/summary.md
Updates the summary information with new changes added in v19
https://github.com/vitessio/vitess/issues/15131
> summary: updated summary with 19.0 changes

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-19.0` for `v19.0.0-RC1`
> [release-19.0] Code Freeze for `v19.0.0-RC1`

- .golangci.yml
- go/vt/mysqlctl/mysqlctlproto/backup_test.go
- go/vt/sqlparser/comments_test.go
- go/vt/throttler/max_replication_lag_module_test.go
Some go1.22 changes and some `assert`/`require` changes.
- https://github.com/vitessio/vitess/issues/15182
- https://github.com/vitessio/vitess/issues/15183
> modernize various tests

- docker/vttestserver/Dockerfile.mysql57
- docker/vttestserver/Dockerfile.mysql80
Quick fix on two things I saw while fixing https://github.com/vitessio/vitess/issues/15231.
> use proper mysql version in the `vttestserver` images

- go/vt/vtgate/planbuilder/rewrite.go
- go/vt/vtgate/planbuilder/testdata/dml_cases.json
- go/vt/vtgate/planbuilder/testdata/onecase.json
- go/vt/vtgate/planbuilder/testdata/select_cases.json
- go/vt/vtgate/planbuilder/testdata/vschemas/schema.json
This PR fixes the issue with query rewrite to also remove the table name qualifier.
- Fixes https://github.com/vitessio/vitess/issues/15248
[ Regression in v18 and v19]
> Fix routing rule query rewrite

- changelog/20.0/20.0.0/summary.md
- go/flags/endtoend/mysqlctl.txt
- go/flags/endtoend/mysqlctld.txt
- go/flags/endtoend/topo2topo.txt
- go/flags/endtoend/vtaclcheck.txt
- go/flags/endtoend/vtbackup.txt
- go/flags/endtoend/vtbench.txt
- go/flags/endtoend/vtclient.txt
- go/flags/endtoend/vtcombo.txt
- go/flags/endtoend/vtctlclient.txt
- go/flags/endtoend/vtctld.txt
- go/flags/endtoend/vtexplain.txt
- go/flags/endtoend/vtgate.txt
- go/flags/endtoend/vtgateclienttest.txt
- go/flags/endtoend/vtorc.txt
- go/flags/endtoend/vttablet.txt
- go/flags/endtoend/vttestserver.txt
- go/flags/endtoend/zkctl.txt
- go/vt/servenv/http.go
- go/vt/servenv/pprof.go
What it says in the title.
#14796 
> Make `--pprof-http` default to false

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-19.0` for `v19.0.0`
> [release-19.0] Code Freeze for `v19.0.0`

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-17.0` for `v17.0.6`
> [release-17.0] Code Freeze for `v17.0.6`

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-19.0` for `v19.0.1`
> [release-19.0] Code Freeze for `v19.0.1`

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-18.0` for `v18.0.3`
> [release-18.0] Code Freeze for `v18.0.3`

- changelog/17.0/17.0.0/release_notes.md
- changelog/17.0/17.0.0/summary.md
- changelog/17.0/17.0.6/changelog.md
- changelog/17.0/17.0.6/release_notes.md
- changelog/17.0/17.0.6/summary.md
- changelog/17.0/README.md
This Pull Request copies the release notes found on `release-17.0` to keep release notes up-to-date after the `v17.0.6` release.
> Copy `v17.0.6` release notes on `main`

- .github/workflows/code_freeze.yml
- changelog/19.0/19.0.1/changelog.md
- changelog/19.0/19.0.1/release_notes.md
- changelog/19.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v19.0.1` release. Once this PR is merged, we will be able to tag `v19.0.1` on the merge commit.
> [release-19.0] Release of `v19.0.1`

- MAINTAINERS.md
> update andrew's email

- go/vt/vtgate/evalengine/api_type_aggregation.go
- go/vt/vtgate/evalengine/api_type_aggregation_test.go
- go/vt/vtgate/planbuilder/testdata/info_schema80_cases.json
- go/vt/vtgate/planbuilder/testdata/union_cases.json
We were missing type handling for TEXT columns.
Fixes https://github.com/vitessio/vitess/issues/15521
> test: failing unit test for type aggregation

- go/vt/vtadmin/http/tablets.go
- go/vt/vtgate/engine/fuzz.go
- go/vt/vtgate/plugin_mysql_server.go
> chore: fix function names

- go/vt/vtctl/reparentutil/emergency_reparenter.go
- go/vt/vtctl/reparentutil/emergency_reparenter_test.go
This PR filters the tablet map using the valid candidates list before reparenting to intermediate source. Given that we already know that some of the tablets aren't valid (and possibly unreachable), it is better to not even try to reparent them, since we need to wait for all the replicas and this potentially adds a lot of time to the ERS.
This also fixes the issue described in https://github.com/vitessio/vitess/issues/15531
- Fixes https://github.com/vitessio/vitess/issues/15531 …
> Filter tablet map using valid candidates before reparenting to intermediate source

- go/vt/wrangler/vexec_plan.go
> Fix misorganized annotations

- CONTRIBUTING.md
Periodically we will get contributions that only change a few words in comments. We wish to avoid spending time and CI resources on such PRs.
> amend contributing guide to ban trivial contributions

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-19.0` for `v19.0.2`
> [release-19.0] Code Freeze for `v19.0.2`

- .github/workflows/code_freeze.yml
- changelog/19.0/19.0.2/changelog.md
- changelog/19.0/19.0.2/release_notes.md
- changelog/19.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v19.0.2` release. Once this PR is merged, we will be able to tag `v19.0.2` on the merge commit.
> [release-19.0] Release of `v19.0.2`

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-18.0` for `v18.0.4`
> [release-18.0] Code Freeze for `v18.0.4`

- .github/workflows/code_freeze.yml
- changelog/19.0/19.0.3/changelog.md
- changelog/19.0/19.0.3/release_notes.md
- changelog/19.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v19.0.3` release. Once this PR is merged, we will be able to tag `v19.0.3` on the merge commit.
> [release-19.0] Release of `v19.0.3`

- MAINTAINERS.md
So long, and thanks for all the fish.
> remove koz from active maintainer list

- go/flagutil/flagutil_test.go
This PR adds all the missing/required tests and refactors existing tests for `go/flagutil`
- #14931 
- #15182 
> test: Add missing tests and refactor existing tests for `go/flagutil`

- go/vt/vtorc/inst/analysis.go
- go/vt/vtorc/inst/analysis_dao.go
- go/vt/vtorc/test/recovery_analysis.go
This PR removes more unused code in VTOrc
> Remove unused code in VTOrc

- MAINTAINERS.md
The maintainers have decided to add @timvaillancourt to the team.
> add Tim Vaillancourt to maintainers

- ADOPTERS.md
It is public knowledge that Vitess is used at Shopify (see blog like [this](https://shopify.engineering/horizontally-scaling-the-rails-backend-of-shop-app-with-vitess)), also the Shopify logo was added in [this website PR](https://github.com/vitessio/website/pull/1713)
This PR adds Shopify to `ADOPTERS.md`
> Add Shopify to `ADOPTERS.md`

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-19.0` for `v19.0.4`
> [release-19.0] Code Freeze for `v19.0.4`

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-18.0` for `v18.0.5`
> [release-18.0] Code Freeze for `v18.0.5`

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-17.0` for `v17.0.7`
> [release-17.0] Code Freeze for `v17.0.7`

- .github/workflows/code_freeze.yml
- changelog/19.0/19.0.4/changelog.md
- changelog/19.0/19.0.4/release_notes.md
- changelog/19.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v19.0.4` release. Once this PR is merged, we will be able to tag `v19.0.4` on the merge commit.
> [release-19.0] Release of `v19.0.4`

- .github/workflows/code_freeze.yml
- changelog/18.0/18.0.5/changelog.md
- changelog/18.0/18.0.5/release_notes.md
- changelog/18.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v18.0.5` release. Once this PR is merged, we will be able to tag `v18.0.5` on the merge commit.
> [release-18.0] Release of `v18.0.5`

- .github/workflows/code_freeze.yml
- changelog/17.0/17.0.7/changelog.md
- changelog/17.0/17.0.7/release_notes.md
- changelog/17.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v17.0.7` release. Once this PR is merged, we will be able to tag `v17.0.7` on the merge commit.
> [release-17.0] Release of `v17.0.7`

- .gitignore
- go/vt/vtgate/planbuilder/plan_test.go
This is a backport of #15922
The bot backport got closed by mistake.
> [release-19.0] test: Cleaner plan tests output (#15922)

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-20.0-rc` for `v20.0.0-RC1`
> [release-20.0-rc] Code Freeze for `v20.0.0-RC1`

- .github/CODEOWNERS
This PR adds me _(@timvaillancourt)_ to a few code paths I'm somewhat familiar with or would like to be more familiar with (for now)
N/A
> Add `timvaillancourt` to some `CODEOWNERS` paths

- changelog/20.0/20.0.0/changelog.md
- changelog/20.0/20.0.0/release_notes.md
- changelog/20.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/401_scheduled_backups.yaml
- examples/operator/operator.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v20.0.0-RC1` release. Once this PR is merged, we will be able to tag `v20.0.0-RC1` on the merge commit.
> [release-20.0-rc] Release of `v20.0.0-RC1`

- changelog/20.0/20.0.0/changelog.md
- changelog/20.0/20.0.0/release_notes.md
- changelog/20.0/README.md
This Pull Request copies the release notes found on `release-20.0-rc` to keep release notes up-to-date after the `v20.0.0-RC1` release.
> [main] Copy `v20.0.0-RC1` release notes

- changelog/20.0/20.0.0/changelog.md
- changelog/20.0/20.0.0/release_notes.md
- changelog/20.0/README.md
This Pull Request copies the release notes found on `release-20.0-rc` to keep release notes up-to-date after the `v20.0.0-RC1` release.
> [release-20.0] Copy `v20.0.0-RC1` release notes

- docker/binaries/vtadmin/Dockerfile
- docker/local/install_local_dependencies.sh
Update node version for vtadmin/docker
https://github.com/vitessio/vitess/issues/16010
> Docker/vtadmin: Update node version

- .github/workflows/unit_race.yml
- .github/workflows/unit_race_evalengine.yml
The changes in #16143 missed adding summary to unit-race and unit-race-evalengine.
> Add Summary in unit-race workflow

- go/test/endtoend/vtgate/queries/timeout/timeout_test.go
This PR fixes the flaky test in TestQueryTimeoutWithShardTargeting on error checking.
Flaky Test fixes are backported to have less CI failures.
> fix flaky test TestQueryTimeoutWithShardTargeting

- changelog/20.0/20.0.0/changelog.md
- changelog/20.0/20.0.0/release_notes.md
This Pull Request copies the release notes found on `release-20.0-rc` to keep release notes up-to-date after the `v20.0.0-RC2` release.
> [release-20.0] Copy `v20.0.0-RC2` release notes

- .github/workflows/code_freeze.yml
- changelog/20.0/20.0.0/changelog.md
- changelog/20.0/20.0.0/release_notes.md
- changelog/20.0/20.0.0/summary.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/401_scheduled_backups.yaml
- examples/operator/operator.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v20.0.0` release. Once this PR is merged, we will be able to tag `v20.0.0` on the merge commit.
> [release-20.0-rc] Release of `v20.0.0`

- changelog/20.0/20.0.0/changelog.md
- changelog/20.0/20.0.0/release_notes.md
This Pull Request copies the release notes found on `release-20.0-rc` to keep release notes up-to-date after the `v20.0.0` release.
> [main] Copy `v20.0.0` release notes

- .github/workflows/build_docker_images.yml
Follow-up of https://github.com/vitessio/vitess/pull/16339 where we added an `echo` command in the workflow but the command was not working.
> Fix echo command in build docker images workflow

- .github/workflows/vitess_tester_vtgate.yml
- go/test/endtoend/vtgate/vitess_tester/tpcc/tpcc.test
- go/test/endtoend/vtgate/vitess_tester/tpch/tpch.test
- test/ci_workflow_gen.go
- test/templates/cluster_vitess_tester.tpl
> [release-18] Vitess tester workflow (#16127)

- .github/workflows/vitess_tester_vtgate.yml
- go/test/endtoend/vtgate/vitess_tester/tpcc/tpcc.test
- go/test/endtoend/vtgate/vitess_tester/tpch/tpch.test
- test/ci_workflow_gen.go
- test/templates/cluster_vitess_tester.tpl
> [release-19] Vitess tester workflow (#16127)

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-18.0` for `v18.0.6`
> [release-18.0] Code Freeze for `v18.0.6`

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-19.0` for `v19.0.5`
> [release-19.0] Code Freeze for `v19.0.5`

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-20.0` for `v20.0.1`
> [release-20.0] Code Freeze for `v20.0.1`

- .github/workflows/code_freeze.yml
- changelog/20.0/20.0.1/changelog.md
- changelog/20.0/20.0.1/release_notes.md
- changelog/20.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/401_scheduled_backups.yaml
- examples/operator/operator.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v20.0.1` release. Once this PR is merged, we will be able to tag `v20.0.1` on the merge commit.
> [release-20.0] Release of `v20.0.1`

- go/vt/proto/tabletmanagerdata/tabletmanagerdata_vtproto.pb.go
- go/vt/proto/vtctldata/vtctldata_vtproto.pb.go
Was broken in #16691
@frouioui How did that PR pass while this was broken? 
> Fix generated proto

- .github/workflows/upgrade_downgrade_test_query_serving_queries.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml
This PR is a back port of #16688
> [release-18.0] Replace ErrorContains checks with Error checks before running upgrade downgrade

- .github/workflows/upgrade_downgrade_test_query_serving_queries.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml
This PR is a backport of #16688
> [release-19.0] Replace ErrorContains checks with Error checks before running upgrade downgrade

- .github/workflows/upgrade_downgrade_test_query_serving_queries.yml
- .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema.yml
- .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml
This PR is a backport of #16688
> [release-20.0] Replace ErrorContains checks with Error checks before running upgrade downgrade

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-18.0` for `v18.0.7`
> [release-18.0] Code Freeze for `v18.0.7`

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-19.0` for `v19.0.6`
> [release-19.0] Code Freeze for `v19.0.6`

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-20.0` for `v20.0.2`
> [release-20.0] Code Freeze for `v20.0.2`

- .github/workflows/code_freeze.yml
- changelog/18.0/18.0.7/changelog.md
- changelog/18.0/18.0.7/release_notes.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v18.0.7` release. Once this PR is merged, we will be able to tag `v18.0.7` on the merge commit.
> [release-18.0] Release of `v18.0.7`

- .github/workflows/code_freeze.yml
- changelog/19.0/19.0.6/changelog.md
- changelog/19.0/19.0.6/release_notes.md
- changelog/19.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v19.0.6` release. Once this PR is merged, we will be able to tag `v19.0.6` on the merge commit.
> [release-19.0] Release of `v19.0.6`

- go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go
- go/vt/vtgate/planbuilder/operators/SQL_builder.go
- go/vt/vtgate/planbuilder/operators/horizon_expanding.go
- go/vt/vtgate/planbuilder/operators/queryprojection.go
- go/vt/vtgate/planbuilder/testdata/aggr_cases.json
This is a backport of #16366
Fixes #16927
> backport 16384 to release-18

- java/client/src/main/java/io/vitess/client/VTGateBlockingConnection.java
- java/client/src/main/java/io/vitess/client/VTGateConnection.java
- java/client/src/main/java/io/vitess/client/VTSession.java
- java/client/src/main/java/io/vitess/client/grpc/tls/TlsOptions.java
- java/grpc-client/pom.xml
- java/grpc-client/src/main/java/io/vitess/client/grpc/RetryingInterceptor.java
- java/grpc-client/src/test/java/io/vitess/client/grpc/RetryingInterceptorTest.java
- java/jdbc/src/main/java/io/vitess/jdbc/VitessConnection.java
- java/jdbc/src/main/java/io/vitess/jdbc/VitessDriver.java
- java/jdbc/src/main/java/io/vitess/jdbc/VitessJDBCUrl.java
- java/jdbc/src/main/java/io/vitess/jdbc/VitessStatement.java
- java/jdbc/src/main/java/io/vitess/util/charset/CharsetMapping.java
- java/pom.xml
This PR updates the Java dependencies to latest versions and modifies the code to use the latest available packages.
Java v21 was released with all these changes so it should be present on the v21 branch.
Most of the changes were necessitated by stricter code style checks done by the newer version of the updated packages.
> java package updates for grpc and protobuf and release plugins

- doc/internal/release/eol-process.md
This small PR updates the EOL documentation to include the updates required to the `Update Golang Version` workflow once we EOL a version.
> Update the EOL documentation

- go/vt/vttablet/endtoend/framework/server.go
This PR will stop emitted `config` not found logs from throttler for e2e test in vttablet.
Example:
```
throttler.go:592] Throttler.retryReadAndApplyThrottlerConfig(): error reading throttler config. Will retry in 10s. Err=node doesn't exist: keyspaces/vttest/SrvKeyspace
```
> e2e framework change to find empty throttler config

- go/cmd/vttestserver/cli/main.go
- go/flags/endtoend/vttestserver.txt
- go/vt/vttest/local_cluster.go
- go/vt/vttest/vtprocess.go
This is a manual backport of #16338
> [release-20.0] parse transaction timeout as duration (#16338)

- .github/CODEOWNERS
- MAINTAINERS.md
Andrew is no longer active in the community. We thank him for his many contributions over several years.
> Move Andrew Mason to emeritus

- .clomonitor.yml
- README.md
CNCF maintains a website that checks for various compliance things. There are a few things there that we should pass because we maintain them, but in a slightly different way than what they check for. I've added wording to the README that will let us pass the roadmap and community meeting checks, and added configuration to exempt us from the slack_presence check. We are not in CNCF slack or Kubernetes slack, we have our own.
Along the way, I also re-wrote the top part of the README to better reflect what Vitess is today versus what it was 7 years ago.
https://clomonitor.io/projects/cncf/vitess
-   [x] If this change is to be back-ported to previous releases, a justification is included …
> Get some CLOMonitor checks passing

- go/bytes2/buffer.go
- go/bytes2/buffer_test.go
- go/cache/theine/bf/bf.go
- go/cache/theine/bf/bf_test.go
- go/cmd/vtctldclient/command/framework_test.go
- go/sqltypes/value_test.go
- go/test/vschemawrapper/vschema_wrapper.go
- go/vt/schemadiff/table.go
- go/vt/sqlparser/rewriter_api.go
- go/vt/sqlparser/tracked_buffer.go
- go/vt/vttablet/onlineddl/executor.go
- go/vt/vttablet/onlineddl/vrepl.go
- go/vt/wrangler/testlib/fake_tablet.go
This removes a bunch of code identified by deadcode as not used across a few packages.
> Remove bits of unused code across various packages

- go/vt/vtgate/planbuilder/operators/subquery_planning.go
- go/vt/vtgate/planbuilder/testdata/select_cases.json
This is a backport of https://github.com/vitessio/vitess/pull/17764
> backport: support subqueries inside subqueries when merging (Release 19.0)

- .github/CODEOWNERS
This adds Shlomi & Frances to CODEOWNERS for VReplication related code paths!
None
-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches **N/A**
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description **N/A**
-   [x] Tests were added or are not required **N/A**
-   [x] Did the new or modified tests pass consistently locally and on CI? **N/A**
-   [x] Documentation was added or is not required **N/A**
None
> Add Shlomi & Frances to VReplication CODEOWNERS

- .github/CODEOWNERS
Small update to the codeowners file to add myself as a reviewer for backup related changes.
> Add @frouioui to CODEOWNERS for backups

- MAINTAINERS.md
I left PlanetScale at the end of February, 2025 so changing the email address to my personal one.
> Update email address for mattlord

- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/401_scheduled_backups.yaml
- examples/operator/README.md
- examples/operator/operator.yaml
- examples/operator/pf.sh
- test/vtop_example.sh
This is a follow up of the work done in https://github.com/planetscale/vitess-operator/pull/666.
> Support multiple namespaces with the vitess-operator

- .github/workflows/cluster_endtoend_onlineddl_vrepl.yml
- .github/workflows/cluster_endtoend_onlineddl_vrepl_stress.yml
- .github/workflows/cluster_endtoend_onlineddl_vrepl_stress_suite.yml
- .github/workflows/cluster_endtoend_onlineddl_vrepl_suite.yml
- .github/workflows/cluster_endtoend_vreplication_basic.yml
- .github/workflows/cluster_endtoend_vreplication_migrate.yml
- .github/workflows/cluster_endtoend_vreplication_vtctldclient_vdiff2_movetables_tz.yml
- go/vt/vttablet/tabletserver/schema/engine.go
- test/ci_workflow_gen.go
https://github.com/vitessio/vitess/pull/17855 introduced a bug where a codepath which expected the additional columns from a "WithSizes" query was not handled, resulting in VTTablet panics when a 5.7 flavor was used.
This was only released to v22, so no need to backport.
fixes https://github.com/vitessio/vitess/issues/17856
> Schema Engine Reload: check for file and allocated size columns to be available 

- go/test/endtoend/cluster/topo_process.go
Since we have already checked err before and returned != nil, err must be nil here. In fact, it should return cerr.
> fix: fix incorrect nil return value

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-22.0` for `v22.0.0-RC1`
> [release-22.0] Code Freeze for `v22.0.0-RC1`

- changelog/22.0/22.0.0/changelog.md
- changelog/22.0/22.0.0/release_notes.md
- changelog/22.0/22.0.0/summary.md
- changelog/22.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/401_scheduled_backups.yaml
- examples/operator/operator.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v22.0.0-RC1` release. Once this PR is merged, we will be able to tag `v22.0.0-RC1` on the merge commit.
> [release-22.0] Release of `v22.0.0-RC1`

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-21.0` for `v21.0.4`
> This Pull Request is part of https://github.com/vitessio/vitess/issues/18129
> [release-21.0] Code Freeze for `v21.0.4`

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-20.0` for `v20.0.7`
> This Pull Request is part of https://github.com/vitessio/vitess/issues/18130
> [release-20.0] Code Freeze for `v20.0.7`

- .github/workflows/code_freeze.yml
- changelog/21.0/21.0.4/changelog.md
- changelog/21.0/21.0.4/release_notes.md
- changelog/21.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/401_scheduled_backups.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v21.0.4` release. Once this PR is merged, we will be able to tag `v21.0.4` on the merge commit.
> This Pull Request is part of https://github.com/vitessio/vitess/issues/18129
> [release-21.0] Release of `v21.0.4`

- go/test/endtoend/vtgate/queries/misc/misc_test.go
PR https://github.com/vitessio/vitess/pull/18149 removed TableName from the plan output as it was deprecated in favour of TableUsed. The test in v22 was expecting it so, this PR restrict the check to v22 and lower VTGate version. 
> [release-22.0]: skip test check for upgrade test for TestStraighJoin

- changelog/22.0/22.0.0/summary.md
Edited for correctness and readability. A few changes are still pending from other maintainers.
#17898 
> copy edit release notes to prepare for v22 GA

- go/test/endtoend/preparestmt/stmt_methods_test.go
- go/test/endtoend/vtgate/queries/dml/insert_test.go
- test/config.json
Added a test in prepared statement that tests json doc column type.
Added prepared statements test suite to upgrade/downgrade test flow.
> [release-21.0] json array insert test

- go/test/endtoend/preparestmt/stmt_methods_test.go
- go/test/endtoend/vtgate/queries/dml/insert_test.go
- test/config.json
https://github.com/vitessio/vitess/pull/18194
Porting it to `main`
> json array insert test

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-22.0` for `v22.0.1`
> [release-22.0] Code Freeze for `v22.0.1`

- .github/workflows/code_freeze.yml
- changelog/22.0/22.0.1/changelog.md
- changelog/22.0/22.0.1/release_notes.md
- changelog/22.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/401_scheduled_backups.yaml
- examples/operator/operator.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v22.0.1` release. Once this PR is merged, we will be able to tag `v22.0.1` on the merge commit.
> [release-22.0] Release of `v22.0.1`

- .github/workflows/code_freeze.yml
This Pull Request freezes the branch `release-20.0` for `v20.0.8`
> [release-20.0] Code Freeze for `v20.0.8`

- .github/workflows/code_freeze.yml
- changelog/20.0/20.0.8/changelog.md
- changelog/20.0/20.0.8/release_notes.md
- changelog/20.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/401_scheduled_backups.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v20.0.8` release. Once this PR is merged, we will be able to tag `v20.0.8` on the merge commit.
> [release-20.0] Release of `v20.0.8`

- .github/workflows/code_freeze.yml
- changelog/21.0/21.0.5/changelog.md
- changelog/21.0/21.0.5/release_notes.md
- changelog/21.0/README.md
- examples/compose/docker-compose.beginners.yml
- examples/compose/docker-compose.yml
- examples/compose/vtcompose/docker-compose.test.yml
- examples/compose/vtcompose/vtcompose.go
- examples/operator/101_initial_cluster.yaml
- examples/operator/201_customer_tablets.yaml
- examples/operator/302_new_shards.yaml
- examples/operator/306_down_shard_0.yaml
- examples/operator/401_scheduled_backups.yaml
- go/vt/servenv/version.go
- java/client/pom.xml
- java/example/pom.xml
- java/grpc-client/pom.xml
- java/jdbc/pom.xml
- java/pom.xml
Includes the release notes and release commit for the `v21.0.5` release. Once this PR is merged, we will be able to tag `v21.0.5` on the merge commit.
> [release-21.0] Release of `v21.0.5`

- MAINTAINERS.md
This PR updates the email in the maintainers file.
> Update email in Maintainers file

- go/vt/vttablet/tabletserver/repltracker/writer.go
Very simple change to add a bit more context to errors in `heartbeatWriter`.
> `heartbeatWriter`: wrap error with more info

- go/vt/mysqlctl/mysqlshellbackupengine.go
This is a fix for a log message that is being emitted incorrectly.
> fix log message on mysqlshell backup

- .github/CODEOWNERS
- MAINTAINERS.md
Hello 👋
This PR remove me from the list of maintainers and code owners
> Remove myself from the maintainer list
