.github/pull_request_template.md
We used to have a question on the PR template asking whether the PR needed to be backported.
Adding that back because we have gone back to doing backports instead of forward merges.
=> add question on backporting back to PR template

docker/vttestserver/run.sh
When restarting vttestserver after an ungraceful shutdown mysql doesn't start up due to the lingering sock files. Took the snippet from `vitess/examples/compose/vttablet-up.sh` and added it to `vttestserver`'s `run.sh`: https://github.com/vitessio/vitess/blob/345d30a061c2d30a88ab986728bbdda44230b9ac/examples/compose/vttablet-up.sh#L90-L94 
- https://github.com/vitessio/vitess/pull/5115
=> Remove lingering mysqld sock files on vttestserver container startup

go/vt/sqlparser/ast.go, go/vt/sqlparser/ast_funcs.go, go/vt/vtgate/planbuilder/abstract/fuzz.go, go/vt/vtgate/planbuilder/abstract/operator_test.go, go/vt/vtgate/planbuilder/expand_star_test.go, go/vt/vtgate/planbuilder/jointree_transformers.go, go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/semantics/analyzer.go, go/vt/vtgate/semantics/analyzer_test.go, go/vt/vtgate/semantics/semantic_state.go
This PR adds support for comments and comment directives in Gen4.
#7280
=> Adds support for comments and comment directives in Gen4

Makefile
This pull request modifies the `do_release` target of the Makefile to include the steps to create the godoc / go modules tags.
The `do_release` must be called as followed: 
```
make RELEASE_VERSION="11.0.1" GODOC_RELEASE_VERSION="0.11.1" DEV_VERSION="11.0.2-SNAPSHOT" do_release
```
The process google docs has been updated accordingly.
cc @systay @askdba
=> Updated Makefile do_release script to include godoc steps

go/vt/servenv/grpc_server.go
Signed-off-by: Josh Chorlton <choo@stripe.com>
Just registers the grpc server in `servenv` as part of the [reflection API](https://github.com/grpc/grpc-go/blob/master/Documentation/server-reflection-tutorial.md). This should allow us to run `grpcurl ... list`.
It's just a nice-to-have convenience thing. It's more useful as vitess combines servers into a single entrypoint with servers activated by flag, so we can trivially tell what RPCs are available without digging through source.
N/A
- [ x] Tests were added or are not required
- [ x] Documentation was added or is not required
I'd appreciate some help testing this. I tried to get a quick vitess server up and running just to make sure it didn't crash on boot. I couldn't find instructions, and couldn't find a grpc server that was trivial …
=> support grpc reflection on APIs

go/test/endtoend/vtgate/gen4/gen4_test.go, go/vt/vtgate/engine/ordered_aggregate.go, go/vt/vtgate/engine/ordered_aggregate_test.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
This PR adds support for doing multiple distinct aggregation functions in ordered aggregate primitive.
#7280
=> Gen4: Support multiple distinct aggregation functions in the query

go/vt/vtgate/planbuilder/abstract/queryprojection.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/postprocess_cases.txt
Adds support for ordering by NULL in gen4
#7280
=> Adds support for ordering by NULL in gen4

go/mysql/conn.go, go/mysql/conn_test.go, go/mysql/query.go, go/mysql/query_test.go
Backport of #8294
During high load, if prepared statements are used, the parameter values could accidentally get overwritten with dirty data from other concurrent connections.
This PR fixes this by copying the data before releasing the buffer.
=> Copy parameter data from byte buffer in COM_STMT_SEND_LONG_DATA

examples/local/202_move_tables.sh, examples/local/203_switch_reads.sh, examples/local/204_switch_writes.sh, examples/local/205_clean_commerce.sh, examples/local/303_reshard.sh, examples/local/304_switch_reads.sh, examples/local/305_switch_writes.sh, examples/local/306_down_shard_0.sh, examples/region_sharding/203_reshard.sh, go/test/endtoend/recovery/pitr/shardedpitr_test.go, go/test/endtoend/vreplication/helper.go, go/test/endtoend/vreplication/resharding_workflows_v2_test.go, go/test/endtoend/vreplication/vreplication_test.go, go/vt/vtctl/vtctl.go, test/local_example.sh
This PR 
* makes v2 flows as the default and requires `-v1` to be specified to use the v1 `MoveTables` or `Reshard`
* changes the local examples to use the v2 vreplication CLI UX. 
* The vitess.io documentation has been updated at [https://github.com/vitessio/website/pull/784](https://github.com/vitessio/website/pull/784). It will be merged once 10.0 docs are archived.
* V1 tests have been modified to add the `v1` parameter to the `MoveTables` and `Reshard` vtctl commands
* V2 tests have been modified to remove the `v2` parameter to the vtctl commands
* A deprecation statement is displayed if the v1 commands are used
* The v2 flows have been around for over six months know. Since they are not the default, they have not seen a lot of usage in the field. So we continue to call the v2 flow …
=> Change local example to use v2 vreplication flows and change default to v2 from v1

go/vt/vtctl/vtctl.go, go/vt/wrangler/materializer.go, go/vt/wrangler/materializer_test.go
This is PR for issue  #8571 , which is to allow forces vreplication to continue after backfill with an owner being provided.
#8571
=> Customized CreateLookUpVindex to Include a Flag to Continue Vreplication After Backfill with an Owner Provided

go/vt/srvtopo/query.go, go/vt/srvtopo/query_srvkeyspacenames.go, go/vt/srvtopo/resilient_server.go, go/vt/srvtopo/resilient_server_test.go, go/vt/srvtopo/status.go, go/vt/srvtopo/watch.go, go/vt/srvtopo/watch_srvkeyspace.go, go/vt/srvtopo/watch_srvvschema.go
Making progress on https://github.com/vitessio/vitess/issues/8462
After several meetings with the team, we've decided that the only reliable way to detect is whether a failover or a resharding operation is over is by watching _both_ the `SrvKeyspace` and `SrvVSchema` changes in real time.
The current `ResilientServer` design does not allow for this, however.
- `SrvKeyspace` can only be accessed with a getter (i.e. there is no way to subscribe to changes in the keyspace), even though this functionality is actually watching the topology server in its underlying implementation.
- `SrvVSchema` can be subscribed for event changes, however, this is very expensive because the `Watch` call will open a watcher to the underlying topo server for each call, and we already have a couple of those calls …
=> srvtopo: resilient watcher

go/test/endtoend/vtgate/misc_test.go, go/vt/sqlparser/ast_rewriting.go, go/vt/sqlparser/ast_rewriting_test.go
Currently our rewriter, incorrectly rewrites a subquery which is part of an IN clause
For example, consider the following query - 
```sql
SELECT id FROM user WHERE id IN (SELECT 1 FROM DUAL)
```
This query is rewritten to -
```sql
SELECT id FROM user WHERE id IN 1
```
but this is syntactically wrong. Instead we must rewrite it to - 
```sql
SELECT id FROM user WHERE id IN (1)
```
This PR fixes this problem
-  #8522
=> Fixes subquery rewrite when it is part of IN clause

go/vt/vtctl/vtctl.go
Found this by inspection after a user reported an issue.  We are using 
the cells variable as the new usage;  but we were still passing the old
cell variable to the lower code.  As a result, if you pass the `-cells`
directive to CreateLookupVindex, it was effectively ignored. 
=> Fix passing the wrong cell/cells variable to CreateLookupVindex

go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
Fail query plan for unsupported aggregate function which needs handling on VTGate.
#7280
=> Fail plan for unsupported aggregate function

go/vt/vtctl/vtctl.go
this year in PR #7275 to change the vreplication_tablet_type defaults.
Will be reviewing the docs separately to see if any adjustments are required.
=> Update MoveTables CLI help to reflect change we made at the beginning of

go/vt/vttablet/onlineddl/executor.go
Fixes https://github.com/vitessio/vitess/issues/8621
Using DBA account to creating `_vt.*` schema (namely `_vt.schema_migrations`)
DBA account is privileged, as opposed to `app` account which may not have the privileges to create the schema.
cc @aquarapid
=> onlineddl Executor: build schema with DBA user

go/vt/vttablet/tabletserver/schema/engine.go, go/vt/vttablet/tabletserver/schema/engine_test.go
Schema engine tracks `file_size` and `allocated_size` stats for each table. However, when a table is dropped, the stats are not reset.
=> schema engine: reset table size stats when a table is dropped

go.mod, go.sum
`go get -u github.com/aws/aws-sdk-go@v1.34.2 && go mod tidy`
- Closes #8615
=> Bump aws-sdk-go to v1.34.2

go/vt/orchestrator/app/cli.go, go/vt/orchestrator/http/api.go, go/vt/orchestrator/inst/analysis.go, go/vt/orchestrator/inst/analysis_dao.go, go/vt/orchestrator/inst/analysis_test.go, go/vt/orchestrator/inst/cluster.go, go/vt/orchestrator/inst/cluster_test.go, go/vt/orchestrator/inst/durability.go, go/vt/orchestrator/inst/instance.go, go/vt/orchestrator/inst/instance_dao.go, go/vt/orchestrator/inst/instance_topology.go, go/vt/orchestrator/inst/instance_topology_dao.go, go/vt/orchestrator/inst/minimal_instance.go, go/vt/orchestrator/inst/tablet_dao.go, go/vt/orchestrator/logic/orchestrator.go, go/vt/orchestrator/logic/tablet_discovery.go, go/vt/orchestrator/logic/topology_recovery.go, go/vt/topo/tablet.go
Cleanup references to master and slave in `vt/orchestrator` in functions and variables 
- Fixes #7110
=> Fixing vtorc naming convention - Functions and Variables

go/vt/vtgate/planbuilder/jointree.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt
This pull request removes the `Gen4 unsupported error` when dealing with vindex predicates other than `equal`, `in`, `not in`, `like`.
=> Gen4: Removed default case when dealing with weird/non-unique vindex predicate

go/test/endtoend/vtgate/vschema/vschema_test.go, go/vt/srvtopo/keyspace_filtering_server.go, go/vt/srvtopo/keyspace_filtering_server_test.go, go/vt/srvtopo/resilient_server_test.go, go/vt/srvtopo/server.go, go/vt/srvtopo/srvtopotest/passthrough.go, go/vt/srvtopo/watch.go, go/vt/srvtopo/watch_srvkeyspace.go, go/vt/srvtopo/watch_srvvschema.go, go/vt/vtexplain/vtexplain_topo.go, go/vt/vtgate/executor_test.go, go/vt/vtgate/executor_vschema_ddl_test.go, go/vt/vtgate/sandbox_test.go, go/vt/vtgate/vcursor_impl_test.go, go/vt/vtgate/vschema_manager.go, go/vt/vttablet/tabletserver/vstreamer/engine.go
From @vmg: 
"Here's a feature I forgot to implement in my previous PR. We're gonna need to stop watching specific keyspaces once we detect their cluster event is finished."
cc @deepthi @harshit-gangal @rohit-nayak-ps 
#8462
=> srvtopo: allow unwatching from watch callbacks

go/test/endtoend/reparent/reparent_test.go, go/test/endtoend/reparent/utils_test.go
Extended timeout for replication restoration, which sometimes seems to
take a while in CI.
Additionally made test insert rows truly unique, which I'm not sure
fixed anything but makes it much easier to check the state of
replication.
Signed-off-by: Aaron Young <young@squareup.com>
=> Fixes for reparent endtoend test flakiness

go/vt/servenv/run.go, go/vt/servenv/servenv.go, go/vt/servenv/servenv_test.go
This PR adds a new `--onclose_timeout` flag that adds a timeout for
`onClose` hooks. It's very similar to the existing `--onterm_timeout`
flag.
The flag will be helpful for services that use the `--lameduck-period` flag
in conjunction with `onClose` hooks. In this scenario, a service can't add 
timeouts to `onClose` hooks; hence blocking the service shutdown.
=> servenv: add `--onclose_timeout` flag

go/cmd/vtbackup/vtbackup.go, go/test/endtoend/backup/vtbackup/backup_only_test.go
a clean MySQL shutdown & startup cycle to work around xtrabackup
DDL bugs (see https://jira.percona.com/browse/PXB-2205).  xtrabackup
`-lock-ddl` (which is the default) is not sufficient to fix this, and we
have run into this in real-world scenarios.  See #8610 
=> Add `-full_flush` parameter for vtbackup, which performs

go/vt/vttablet/endtoend/connkilling/connkiller_test.go
Updated the assert checking for tx killer to double the time for tx timeout value to cover up any delayed case.
=> increase conn killer check to double the tx timeout value

go/vt/vtgate/planbuilder/route.go, go/vt/vtgate/planbuilder/route_test.go, go/vt/vtgate/planbuilder/testdata/dml_cases.txt
Make sure to merge subqueries where either the inner or the outer are reference tables.
Fixes #8638
=> Handle subquery merging with references correctly

go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/routetree.go, go/vt/vtgate/planbuilder/testdata/from_cases.txt
In gen4, we were only comparing the column names of available vindexes, when
we should be checking column name and table.
Fixes #8580
=> Check table and not just column name

go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/planbuilder/testdata/postprocess_cases.txt, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/planbuilder/testdata/show_cases.txt, go/vt/vtgate/planbuilder/testdata/systemtables_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt, go/vt/vtgate/semantics/analyzer.go
Support added for query comments, locking reads statements and select with into query
#7280
=> Gen4: added support for query comments, locking reads, select with into

.github/CODEOWNERS, MAINTAINERS.md
Add @deepthi to general vitess and resharding, remove from parser. EDIT: Add @vmg to parser.
Fix link to @vmg's GH profile
Add @ph14 to CODEOWNERS (replacing #6841)
=> update MAINTAINERS and CODEOWNERS for deepthi, pH14 and vmg

go/vt/vtgate/planbuilder/abstract/fuzz.go, go/vt/vtgate/planbuilder/abstract/operator_test.go, go/vt/vtgate/planbuilder/abstract/queryprojection_test.go, go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/planbuilder/rewrite.go, go/vt/vtgate/planbuilder/rewrite_test.go, go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/testdata/ddl_cases_no_default_keyspace.txt, go/vt/vtgate/planbuilder/testdata/filter_cases.txt, go/vt/vtgate/planbuilder/testdata/postprocess_cases.txt, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/semantics/analyzer.go, go/vt/vtgate/semantics/analyzer_test.go, go/vt/vtgate/semantics/scoper.go, go/vt/vtgate/semantics/semantic_state.go
This pull request moves the expand star inside the semantic analysis. Before, we were doing expand star once the semantic analysis was done, which led to the issue #8575.
Resolves #8575
#7280
=> Gen4: Move expand star inside the semantic analysis

go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt, go/vt/vtgate/planbuilder/testdata/from_cases.txt
This pull request slightly improves the merge of join in Gen4 by keeping vindex name and vindex. That way `SelectEqualUnique` can be planned correctly.
Additionally, the expected outputs for the Gen4 planner got added to multiple join and derived table plans.
__________
**Plans went from:**
```json
{
"Original": "select user_extra.id from user join user_extra on user.col = user_extra.col where user.id = 5 and user_extra.user_id = 5",
"Variant": "SelectEqualUnique",
"Keyspace": {
},
"FieldQuery": "select user_extra.id from `user`, user_extra where 1 != 1",
"Query": "select user_extra.id from `user`, user_extra where `user`.id = 5 and user_extra.user_id = 5 and `user`.col = user_extra.col", …
```
=> Gen4: keep vindex name and values while merging inner joins

go/vt/vtgate/vstream_manager.go, go/vt/vtgate/vstream_manager_test.go
Fix and re-enable tests disabled in #8692 
#8692
=> tests: use AtomicInt32 instead of int to fix races

examples/compose/client.sh, examples/local/201_newkeyspace_tablets.sh
`Vitess/base` is built using `root` and `pkg/cache` is mostly `root`, but the default user is later changed to `vitess` so using the example `client.go` fails on `/go/pkg/cache` permissions. This fixes that without changing docker image and keeping it localized just to the shell script.
Adding a script I find useful for adding additional arbitrary keyspaces in the `docker_local` container.
Signed-off-by: Matt Lord <mattalord@gmail.com>
https://github.com/vitessio/vitess/pull/5863
h/t to @dartov for the compose part -- carrying his PR forward.
=> Improve the Docker local and compose examples

go/vt/srvtopo/keyspace_filtering_server.go, go/vt/srvtopo/server.go, go/vt/srvtopo/srvtopotest/passthrough.go, go/vt/vtexplain/vtexplain_topo.go, go/vt/vtgate/sandbox_test.go, go/vt/vtgate/vcursor_impl_test.go
Splitting from https://github.com/vitessio/vitess/pull/8700 for easier review. This is also pretty straightforward: just exposing this API in the interface.
cc @deepthi @harshit-gangal 
- https://github.com/vitessio/vitess/pull/8700
=> srvtopo: expose WatchSrvKeyspace

go/test/endtoend/vtgate/misc_test.go, go/vt/vtgate/endtoend/misc_test.go, go/vt/vtgate/engine/rename_fields.go
This pull request fixes a panic in vtgate that happens when a `show tables` or a `use <database>` query is sent to Vitess after entering `olap` mode.
Fixes #8694
=> Fixing a panic in vtgate with OLAP mode

go/vt/vtgate/grpcvtgateservice/server.go
Now the underlying streamExecute uses plan builder to build and execute the query.
The VStream API pass on the tablet type received from the request. 
Earlier it was hardcoded to use a PRIMARY tablet but now it uses what the user has passed in the request.
For query-based streaming through MySQL protocol, it is already handled for cases when tablet type is not set.
For direct VStream API calls, the fallback logic is added to use PRIMARY tablet type if not provided.
- Fixes #8676 
- [] Tests were added or are not required
=> default to primary tablet if not set in VStream api

go/vt/vtgate/grpcvtgateservice/server.go
This is a backport of #8755
#8755
=> Backport into 11: default to primary tablet if not set in VStream api

go/test/endtoend/vtgate/misc_test.go, go/vt/vtgate/endtoend/misc_test.go, go/vt/vtgate/engine/rename_fields.go
This is a backport of #8722 into the `release-11.0` branch.
- Original PR: #8722
- Issue: #8694
=> Backport to 11: Fixing a panic in vtgate with OLAP mode

go/test/endtoend/vtgate/mysql80/main_test.go, go/test/endtoend/vtgate/mysql80/misc_test.go, go/vt/servenv/buildinfo.go, go/vt/servenv/buildinfo_test.go, go/vt/sqlparser/parser.go, go/vt/sqlparser/token.go, go/vt/sqlparser/version_test.go, go/vt/vtgate/plugin_mysql_server.go, go/vt/vttest/vtprocess.go
We were reading the version flag before having parsed the flags, and that does not work, so the running version was always set to 5.7
Fixed #8753
=> Fix bug in parsing of version comments

go/vt/vtgate/planbuilder/from.go, go/vt/vtgate/planbuilder/testdata/from_cases.txt
This pull request fixes an issue that is encountered when v3 joins two routes that have `SysTableTableName` fields. v3 was not merging the two maps resulting in errors like the one below:
```
ERROR 1105 (HY000) at line 1: target: keyspace1.0.primary: vttablet: rpc error: code = InvalidArgument desc = missing bind var table_name (CallerID: userData1)
```
A plan test was added through this pull request to reproduce the issue.
- https://github.com/planetscale/beta/discussions/91
=> Proper merge of the SysTableTableName fields when joining two routes

go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/testdata/select_cases.txt
This PR adds support for pinned tables in Gen4
#7280
=> Support for pinned tables in Gen4

go/vt/dbconfigs/dbconfigs.go
Signed-off-by: Matt Lord <mattalord@gmail.com>
When tablets do not connect to mysqld via a unix domain socket, TLS is a concern. And given the version of MySQL involved and the specifics of the key materials used you may need the tablet to [support older ciphers](https://github.com/vitessio/vitess/blob/da96136fe5f430ee8f83b0d447286ba1b9f45341/go/vt/vttls/vttls.go#L33-L59). 
This was seen when using RDS/Aurora instances as the vttablet then uses TCP/IP to communicate with mysqld and you likely want to use TLS to protect that network communication. The [RDS CA bundle](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html) does not seem to support ECDHE ciphers. And you may simply be using an [older version of MySQL that does not have TLS 1.2 …
=> Allow min TLS version for tablet to mysqld conns

go/vt/sqlparser/parser.go
We should only parse the MySQL Server Version flag if it is provided
=> fix parsing of MySQL Server Version flag

go/vt/vttablet/onlineddl/vrepl.go, go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
This PR is trying to fix problem mentioned in Issue #8759 (caused by PR #8129 )
For the same create table statement in MySQL5.6/5.7 & MySQL8 will write different `Extra` table metadata.
This lead to a misjudgment on how we identify a generated column,  especially on `DEFAULT CURRENT_TIMESTAMP` columns (additional metadata added in I_S in MySQL 8).
```sql
CREATE TABLE toki_test4 (
id int AUTO_INCREMENT,
org_value INTEGER,
doubled_value INTEGER AS (`org_value` * 2) STORED, -- NOTE: generated column is not supported in MySQL5.6
doubled_value_virtual INTEGER AS (`org_value` * 2),  -- NOTE: generated column is not supported in MySQL5.6
created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`id`)
);
```
MySQL5.6
```sql
desc toki_test4; …
```
=> Fix how we identify MySQL generated columns

go.mod, go.sum, go/vt/orchestrator/kv/consul.go
This is a subset of the code changes made in https://github.com/vitessio/vitess/pull/8786, specifically the changes to `go/vt/orchestrator` so that we can remove `armon/consul-api` as a dependency.
This is a follow-up to #8784.
#8785
=> Remove consul-api usage in favor of official consul/api

go/vt/vtctl/vtctl.go
Signed-off-by: Matt Lord <mattalord@gmail.com>
Before this, we were printing out [the constant defined here](https://pkg.go.dev/time#pkg-constants) rather than using that as a formatting directive applied to the current time. For example:
```
$ vtctlclient -server localhost:15999 SwitchReads -tablet_type=rdonly -reverse -dry_run targetkeyspace.workflowname
Dry Run results for SwitchReads run at 02 Jan 06 15:04 MST
Parameters: -tablet_type=rdonly -reverse -dry_run targetkeyspace.workflowname
```
This PR simply corrects that (and also adjusts the print formatting parameter ordering in the generic output).
=> Print actual current datetime for vtctl dry run commands

go/vt/vtctl/vtctl.go
Noticed this the other day.
Before:
```
❯ vtctlclient -server ":15999" GetRoutingRules -h
{}
```
After:
```
❯ vtctlclient -server ":15999" GetRoutingRules -h
Usage: GetRoutingRules 
Displays the VSchema routing rules.
```
=> [vtctl] Add missing call to `flag.Parse` in `commandGetRoutingRules`

docker/vttestserver/run.sh
Fixed filename for the configuration file in Vttestserver docker file. Earlier, we rewrote `default-fast.cnf` to `test-suite.cnf`. This PR fixes one remaining reference
- Fixes #8808
=> Fixed filename for the configuration file in Vttestserver

go/vt/vtgate/planbuilder/gen4_planner.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/querytree_transformers.go, go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/route_planning_test.go, go/vt/vtgate/planbuilder/routetree.go
Change planner context as reference to be passed to function calls.
It does not look like a significant impact.
```
name                                        old allocs/op  new allocs/op  delta
OLTP/Gen4-8                                    312µs ± 9%     338µs ± 1%     ~     (p=0.056 n=5+5)
OLTP/Gen4Greedy-8                              336µs ± 1%     339µs ± 0%     ~     (p=0.111 n=5+4)
OLTP/Gen4Left2Right-8                          329µs ± 8%     339µs ± 2%     ~     (p=0.421 n=5+5)
OLTP/Gen4WithFallback-8                        345µs ± 1%     344µs ± 3%     ~     (p=0.222 n=5+5)
TPCC/Gen4-8                                   2.30ms ± 2%    2.42ms ± 3%   +5.31%  (p=0.008 n=5+5)
TPCC/Gen4Greedy-8                             2.27ms ± 1%    2.40ms ± 1%   +6.08%  (p=0.008 n=5+5) …
```
=> [Gen4] change planning context to be a reference

go/cmd/vtctldclient/internal/command/tablets.go, go/vt/proto/vtctldata/vtctldata.pb.go, go/vt/proto/vtctldata/vtctldata_vtproto.pb.go, go/vt/proto/vtctlservice/vtctlservice.pb.go, go/vt/proto/vtctlservice/vtctlservice_grpc.pb.go, go/vt/vtctl/grpcvtctldclient/client_gen.go, go/vt/vtctl/grpcvtctldserver/server.go, go/vt/vtctl/grpcvtctldserver/server_test.go, go/vt/vtctl/grpcvtctldserver/testutil/test_tmclient.go, go/vt/vtctl/vtctl.go, proto/vtctldata.proto, proto/vtctlservice.proto, web/vtadmin/src/proto/vtadmin.d.ts, web/vtadmin/src/proto/vtadmin.js
As it says, only thing worth noting is that I combined the legacy `SetReadOnly` and `SetReadWrite` rpcs into the one `SetWritable` with a boolean argument. The naming didn't feel as nice to me on the start/stop replication, so I left those separate.
```
❯ vtctldclient --server ":15999" SetWritable zone1-100
❯ vtctldclient --server ":15999" SetWritable zone1-100 --read-only
❯ vtctldclient --server ":15999" SetWritable zone1-101
❯ vtctldclient --server ":15999" StopReplication zone1-100
❯ vtctldclient --server ":15999" StartReplication zone1-100
E0914 09:52:19.457448   97517 main.go:42] rpc error: code = Unknown desc = TabletManager.StartReplication on zone1-0000000100 error: ExecuteFetch(START SLAVE) failed: The server is not configured as slave; fix in config file or with CHANGE MASTER TO …
```
=> [vtctld] Add `SetWritable`, `StartReplication` and `StopReplication` rpcs

go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/query_executor_test.go, go/vt/vttablet/tabletserver/tabletenv/config.go
vtgate username and tablet type a query was sent to.  Helpful for
auditing and log analysis happening on the MySQL level.
Addresses #8761
=> Add optional query annotations, i.e. prefix SQL comments indicating the

go/vt/vtgr/controller/diagnose.go, go/vt/vtgr/controller/diagnose_test.go, go/vt/vtgr/controller/group_test.go, go/vt/vtgr/controller/refresh.go, go/vt/vtgr/controller/refresh_test.go, go/vt/vtgr/controller/repair.go, go/vt/vtgr/controller/repair_test.go, go/vt/vtgr/vtgr.go, go/vt/vtgr/vtgr_test.go
Signed-off-by: Yang Wu <y.wu4515@gmail.com>
When we deploy VTGR in more than one region, we usually deploy one mysql group per region to avoid cross-region paxos round. 
Because of that, we need to define an "active" region for VTGR: only VTGR in the active region will do the `tmc.ChangeType` call. VTGR in the inactive region will just maintain the mysql group without modifying vttablet records in topo server
See the diagram in #8779 for more illustration
Resolves https://github.com/vitessio/vitess/issues/8779
=> Add isActive flag to vtgr to support multi-cell topology

go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/memory_sort_cases.txt, go/vt/vtgate/planbuilder/testdata/postprocess_cases.txt
This change to make the addition of weight_string function to select list to be compatible with sql_mode = full_group_by
by adding to the group by list.
#7280
=> add weight_string function to group by if it is added to select list

go/test/endtoend/vtgate/schematracker/sharded/st_sharded_test.go, go/vt/vtgate/schema/tracker.go, go/vt/vtgate/schema/tracker_test.go, go/vt/vtgate/vtgate.go
Schema tracking queries sent down to the vttablet will use the provided user in vtgate via flag `schema_change_signal_user`
- Fixes #8793
=> VtGate schema tracker to use provided user

.github/workflows/check_make_visitor.yml, go/tools/asthelpergen/asthelpergen.go, go/tools/asthelpergen/main/main.go, go/tools/goimports/goimports.go, go/tools/sizegen/sizegen.go
This pull request fixes a similar issue as the one solved by #8828. The `asthelpergen` generates files that are not formatted using `goimports`, which ultimately makes `TestFullGeneration` fail with the following output when local files are formatted correctly:
```
--- FAIL: TestFullGeneration (1.76s)
asthelpergen_test.go:32: 
Error Trace:	asthelpergen_test.go:32
Error:      	Should be empty, but was ['/home/runner/work/vitess/vitess/go/tools/asthelpergen/integration/ast_clone.go' has changed]
Test:       	TestFullGeneration
FAIL
FAIL	vitess.io/vitess/go/tools/asthelpergen	1.769s
```
In this pull request, I have taken what was done in #8828 and applied it to the `asthelpergen`.
- #8828
=> Apply goimports in `asthelpergen`

go/vt/vttablet/onlineddl/executor.go
In online migration cutover phase, run the `RENAME TABLE` operation using the vt_dba user instead of vt_app.
Fixes #8835
=> Use vt_dba user for online schema migration cutover phase

go/vt/vtgate/endtoend/aggr_test.go, go/vt/vtgate/engine/cached_size.go, go/vt/vtgate/engine/ordered_aggregate.go, go/vt/vtgate/engine/route.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/planbuilder/concatenate.go, go/vt/vtgate/planbuilder/grouping.go, go/vt/vtgate/planbuilder/join.go, go/vt/vtgate/planbuilder/join2.go, go/vt/vtgate/planbuilder/logical_plan.go, go/vt/vtgate/planbuilder/memory_sort.go, go/vt/vtgate/planbuilder/merge_sort.go, go/vt/vtgate/planbuilder/ordered_aggregate.go, go/vt/vtgate/planbuilder/ordering.go, go/vt/vtgate/planbuilder/postprocess.go, go/vt/vtgate/planbuilder/pullout_subquery.go, go/vt/vtgate/planbuilder/route.go, go/vt/vtgate/planbuilder/sql_calc_found_rows.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/memory_sort_cases.txt, go/vt/vtgate/planbuilder/vindex_func.go
The regression in the linked issue was found to be occurring from adding weight_string function due to order by as introduced in #7678.
MySQL does not support the generated query -
```sql
select ascii(val1) as a, count(*), weight_string(ascii(val1)) from aggr_test group by a order by a asc
```
In order to fix this, we also add the weight_string function to the group by clause as follows -
```
select ascii(val1) as a, count(*), weight_string(ascii(val1)) from aggr_test group by a, weight_string(ascii(val1)) order by a asc
```
Fixes #8855
This is a backport of #8856
=> Fixed regression for grouping by integer functions

go/vt/vtgate/planbuilder/route.go, go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/testdata/sysschema_default.txt
SelectDBA queries were not being merged properly when occurring as subqueries. This PR fixes that both for V3 and Gen4 planners.
- Fixes https://github.com/vitessio/vitess/issues/8729
=> fix merging dba query as a subquery both in v3 and gen4

go/vt/vtgr/controller/repair.go, go/vt/vtgr/controller/repair_test.go, go/vt/vtgr/db/mock_mysql.go, go/vt/vtgr/db/mysql.go
Signed-off-by: Yang Wu <y.wu4515@gmail.com>
This PR improves the deterministic of the bootstrap logic. Specifically:
- when we bootstrap, instead of picking a random node, we do a sort so that every time we are using the same node
- on rebootstrap, we pass in the group name instead of checking local group_replication_group_name, which can be empty if the bootstrap failed earlier
After this fix, we should only generate group name in bootstrap and it is only executed when there are 5 nodes in group without a group name
=> Improve deterministic of bootstrap

go/cmd/vtctldclient/internal/command/serving_graph.go, go/cmd/vtctldclient/internal/command/shards.go, go/vt/proto/vtctldata/vtctldata.pb.go, go/vt/proto/vtctldata/vtctldata_vtproto.pb.go, go/vt/proto/vtctlservice/vtctlservice.pb.go, go/vt/proto/vtctlservice/vtctlservice_grpc.pb.go, go/vt/vtctl/grpcvtctldclient/client_gen.go, go/vt/vtctl/grpcvtctldserver/server.go, go/vt/vtctl/grpcvtctldserver/server_test.go, go/vt/vtctl/vtctl.go, go/vt/wrangler/shard.go, proto/vtctldata.proto, proto/vtctlservice.proto, web/vtadmin/src/proto/vtadmin.d.ts
This PR migrates the following RPCs to the new VtctldServer:
- `SetShardIsPrimaryServing`
- `SetShardTabletControl`
- `RebuildKeyspaceGraph`
```
❯ vtctldclient --server ":15999" SetShardIsPrimaryServing -h 2>&1 | less
❯ vtctldclient --server ":15999" GetTablets
zone1-0000000100 commerce 0 primary localhost:15100 localhost:17100 [] 2021-09-19T19:57:38Z
zone1-0000000101 commerce 0 replica localhost:15101 localhost:17101 [] <null>
zone1-0000000102 commerce 0 rdonly localhost:15102 localhost:17102 [] <null>
❯ vtctldclient --server ":15999" SetShardIsPrimaryServing commerce/0 false
{
"primary_alias": {
"cell": "zone1",
"uid": 100
},
"primary_term_start_time": {
"seconds": "1632081458",
"nanoseconds": 536266000
},
"key_range": null,
"source_shards": [],
"tablet_controls": [], …
```
=> [vtctld] migrate more util rpcs

go/vt/key/key.go, go/vt/key/key_test.go, go/vt/topo/srv_keyspace.go
We ran into an issue similar to the one in https://github.com/vitessio/vitess/pull/8296. While trying to switch traffic we found the following error:
```
E0922 08:33:05.346443    2565 main.go:67] E0922 15:33:05.346176 traffic_switcher.go:470] switchShardReads failed: partial result: non-contiguous KeyRange values for RDONLY 
```
This PR has three changes:
* adds a new function to the `key` package so it can check for contagious key ranges. It makes sure this function accounts for padding (in the same way as other key ranges comparison functions). 
* Starts using that function in `OrderAndCheckPartitions`.
* Refactors some code duplication in the tests.
* https://github.com/vitessio/vitess/pull/8296
- [] Should this PR be backported?
I don't know. Maybe?? I think this will only affect …
=> Fix for padding in OrderAndCheckPartitions 

go/vt/sqlparser/rewriter_api.go, go/vt/vtgate/planbuilder/gen4_planner.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/select.go, go/vt/vtgate/planbuilder/sql_calc_found_rows.go, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt, go/vt/vtgate/semantics/analyzer.go, go/vt/vtgate/semantics/analyzer_test.go
Adds support in the gen4 planner for SQL_CALC_FOUND_ROWS.
It does this by sharing most of the logic from the V3 planner.
#7280
=> Gen4: SQL_CALC_FOUND_ROWS support

Makefile, doc/internal/ReleaseInstructions.md, go/tools/release-notes/integration/summary.md, go/tools/release-notes/release_notes.go, go/tools/release-notes/release_notes_test.go
This pull request improves the content of our release notes by:
- filter the pull requests listed in the changelog, only pull requests labeled with `release-notes` will appear.
- add a new section listing pull requests that need more information (deprecation notice, feature description, etc), this section will be filled manually post-generation.
- add the ability to import a README at the top of the release notes that will be used as the `announcement` section.
- better formating of the release notes document.
----
**Sample output:**
> make release-notes FROM="v11.0.0" TO="upstream/main" VERSION="v12.0.0" SUMMARY="./my/path/file.md"
```txt
We are shipping the Gen4 planner within this release.
We reduced the duration of our CI builds by using self-hosted runners.
> TODO: please detail …
```
=> Enhancement of the release notes generation

go/vt/vtctl/backup.go
Follow-up to: https://github.com/vitessio/vitess/pull/8824
I noticed this oversight after it was merged. :-)
Signed-off-by: Matt Lord <mattalord@gmail.com>
https://github.com/vitessio/vitess/pull/8824
=> Correctly identify backup timestamp var as a string

go/test/endtoend/vtgate/found_rows_test.go
This pull request remove the `t.Skip` in the end-to-end test `TestFoundRows` since this feature got supported by Gen4 through PR https://github.com/vitessio/vitess/pull/8878. The test was originally skipped with the addition of `Gen4CompareV3` (https://github.com/vitessio/vitess/pull/8858).
Since we are doing select on a sharded keyspace with a limit, `order by`'s got added to ensure the results are always in the same order between Gen4 and V3 executions.
- #7280
=> Gen4: unskipped TestFoundRows test since it is supported in Gen4

go/vt/vtgate/planbuilder/abstract/concatenate.go, go/vt/vtgate/planbuilder/abstract/operator_test.go, go/vt/vtgate/planbuilder/abstract/operator_test_data.txt, go/vt/vtgate/planbuilder/abstract/querygraph.go, go/vt/vtgate/planbuilder/concantenatetree.go, go/vt/vtgate/planbuilder/concatenateGen4.go, go/vt/vtgate/planbuilder/jointree.go, go/vt/vtgate/planbuilder/querytree.go, go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/route_planning_test.go, go/vt/vtgate/planbuilder/subquerytree.go, go/vt/vtgate/semantics/analyzer_test.go, go/vt/vtgate/semantics/binder.go, go/vt/vtgate/semantics/derived_table.go, go/vt/vtgate/semantics/semantic_state.go, go/vt/vtgate/semantics/table_collector.go, go/vt/vtgate/semantics/tabletset.go, go/vt/vtgate/semantics/tabletset_test.go, go/vt/vtgate/semantics/vtable.go
This was requested by @systay on Slack. We need a `TableSet` data structure that can support more than 64 tables. We're doing this right here in the smallest possible space: `TableSet` is now 16 bytes large and packs a small, single-word bitmap that is used when the set contains less than 64 tables, and a pointer to an implementation of an arbitrarily large set.
This implementation is pretty straightforward -- I don't believe it can be optimized further like we'd do in C/C++/Rust. For completeness, these kind of implementations are usually done like this in non-GC'ed languages:
Instead of the 16-byte `struct` we have here with `struct TableSet{ small uint64; large *largeTableSet }`, we'd have a single-field struct with a single word in it: `struct TableSet { set uintptr }`. When trying to …
=> gen4: implement a growable semantics.TableSet

go/vt/vtgate/engine/join.go, go/vt/vtgate/engine/plan_description.go, go/vt/vtgate/planbuilder/abstract/concatenate.go, go/vt/vtgate/planbuilder/abstract/derived.go, go/vt/vtgate/planbuilder/abstract/join.go, go/vt/vtgate/planbuilder/abstract/operator.go, go/vt/vtgate/planbuilder/abstract/operator_test.go, go/vt/vtgate/planbuilder/abstract/querygraph.go, go/vt/vtgate/planbuilder/abstract/queryprojection.go, go/vt/vtgate/planbuilder/abstract/queryprojection_test.go, go/vt/vtgate/planbuilder/abstract/subquery.go, go/vt/vtgate/planbuilder/abstract/vindex.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/planbuilder/querytree_transformers.go, go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/ddl_cases.txt, go/vt/vtgate/planbuilder/testdata/memory_sort_cases.txt, go/vt/vtgate/planbuilder/testdata/systemtables_cases.txt, go/vt/vtgate/planbuilder/testdata/tpch_cases.txt, go/vt/vtgate/planbuilder/testdata/union_cases.txt, go/vt/vtgate/semantics/analyzer.go
More gen4 small fixes
- Grouping on top of PulloutSubqueries
- UNION between SELECT * queries
- Compact joins - after creating the operator tree, there might have opened up new opportunities to merge QueryGraphs
- Merge UNIONs more aggressively - when it's a UNION DISTINCT, we can reorder the SELECTs to see if there are more chances to merge routes together
#7280
=> Gen4: Even more fixes

go/vt/vtgate/planbuilder/testdata/tpch_cases.txt
This pull request updates the expected output of the plan tests for TPCH queries 16 and 18. The newly introduced behavior for `in`/`not in` subqueries is to add a `__sq_has_values` argument, this change got merged at the same time as another pull request, which led to incorrect plan tests.
cc @mattlord for analyzing the issue
- #7280
=> Updated the expected outpout of tpch plan tests

go/vt/vtctl/reparentutil/planned_reparenter_test.go
This pull request fixes `TestPlannedReparenter_performGracefulPromotion`'s flakiness by increasing the timeout limit.
- fixes #7577
=> fix planned reparent test flakiness

go/vt/vtadmin/http/debug/cluster.go, go/vt/vtgate/debugenv.go, go/vt/vtgate/executor_scatter_stats.go, go/vt/vttablet/tabletserver/debugenv.go, go/vt/vttablet/tabletserver/twopcz.go
This PR replaces `fmt.Sprintf` calls with `fmt.Fprintf` and friends
where it is possible.
The `w.Write([]byte(fmt.Sprintf(...)))` pattern is quite inefficient, it allocates
3x more than `fmt.Fprintf`.
I see that this PR changes only some debug and observability-related code. Anyway, I hope it will be helpful.
=> Use `fmt.Fprintf` instead of `fmt.Sprintf`

go/vt/vtgate/schema/tracker_test.go
Higher time-out for less flaky test
=> set higher timeout, so we get less false negatives

go/test/endtoend/cluster/cluster_process.go, go/test/endtoend/vtgate/godriver/main_test.go, go/vt/vtgate/grpcvtgateservice/server.go
The go vitess driver uses StreamExecute to execute the `stream * from <message_table>`. In the grpc request if the target is not provided then it sets to <request.keyspace>@<request.tablet_type>
If the request.tablet_type is not set then the default is `unknown` tablet type.
The fix is to not set the the default target if tablet type is not provided.
Later in the code there is check to use `default_tablet_type` of vtgate to server the query if the tablet_type is not present in the target.
- Fixes https://github.com/vitessio/vitess/issues/8676
=> grpc streamexecute to set a target if tablet type is provided

go/mysql/sql_error.go, go/mysql/sql_error_test.go
Fixes #8852 
See original PR #6630
This is a potential breaking change for those that depended on the old behavior of `ERTooManyUserConnections` being returned on a too-large `SELECT`, and mapped that to some application-side action.
Not addressed in this PR, but we should probably add an end-to-end test here to catch if/when the upstream gRPC error message is ever changed, since we track upstream gRPC now after having been frozen for years.
=> Handle mapping of gRPC packet overflows to `ERTooManyUserConnections` for SELECT cases too

go/vt/vttablet/tabletserver/tabletenv/config.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tabletserver_test.go
* Modify -queryserver-config-terse-errors to also redact bind vars in
error logs, not just returned errors.
* Remove bind variables in panic handling path if terse errors are on too.
This modifies current behavior.  If anyone feels strongly that they should have bind variable values in the error logs, but not in the returned errors to the client, we should make this a separate option.
**Not** marking as a breaking change, since it changes logging behavior;  but not query returns/behavior.
=> Modify terse errors to also redact errors in logs

go/vt/topo/cell_info.go, go/vt/topo/memorytopo/directory.go, go/vt/topo/memorytopo/file.go, go/vt/topo/memorytopo/lock.go, go/vt/topo/memorytopo/memorytopo.go, go/vt/topo/topotests/cell_info_test.go
Implements the fix proposed in #8220. When `GetSrvKeyspaceNames` fails (for reasons _other_ than NoNode) _and_ the context expired, we assume it's because the local cell is shutdown, spin up a background context, and delete it anyway.
```
❯ vtctlclient -server "localhost:15999" AddCellInfo -server_address "localhost:99999" -root "/vitess/zone2" zone2
❯ vtctlclient -server ":15999" GetCellInfoNames
zone1
zone2
❯ vtctlclient -server "localhost:15999" DeleteCellInfo zone2
DeleteCellInfo Error: rpc error: code = Unknown desc = can't list SrvKeyspace entries in the cell; use -force flag to continue anyway (e.g. if cell-local topo was already permanently shut down): failed to create topo connection to localhost:99999, /vitess/zone2: context …
```
=> Fix `DeleteCellInfo(force=true)` with downed local topo

web/vtadmin/src/components/routes/shard/Shard.tsx, web/vtadmin/src/components/routes/shard/ShardTablets.module.scss, web/vtadmin/src/components/routes/shard/ShardTablets.tsx
This adds tablets to the shard view:
(Quick note on ordering! This implementation uses VTAdmin's default tablet ordering, which lists primaries first, then alphabetically by tablet type. In this case `PRIMARY`, `RDONLY`, `REPLICA`. It does _not_ sort alphabetically by alias by default. Adding react-table (noted below) will let us add table sorting, which should make this less (in my opinion) weird.) 
... and a placeholder: 
Very straightforward. I admit I kept things pretty simple to get this out the door, as this unblocks me from (a) simplifying the keyspace shard table, and then (the piece of been wanting to do forever) (b) rewrite the DataTable component to use react-table 🎉 
N/A
N/A
=> [vtadmin-web] Add tablets to Shard view

.github/workflows/cluster_endtoend_vtgate_tablet_healthcheck_cache.yml, go/test/endtoend/cluster/vttablet_process.go, go/test/endtoend/tabletgateway/vtgate_test.go, go/test/endtoend/vtgate/tablet_healthcheck_cache/correctness_test.go, go/vt/discovery/tablet_health_check.go, test/config.json
If a tablet's health check runs concurrently with its deletion then you can end up with a timing issue where the goroutine getting the status from `vtgate`->`vttablet` via an RPC call has a connection related error (e.g. context cancelled or EOF) but a copy of the tablet's healthcheck cache record is made and that copy's updated state is stored in the healthcheck cache *after* the tablet has gone away. Thus you can end up with a zombie tablet record in the healthcheck cache.
The shorter your [`-health_check_interval` tablet flag](https://vitess.io/docs/reference/programs/vttablet/) is (default is 30s), the more likely you will encounter this. I was able to [repeat it quite easily and regularly](https://github.com/vitessio/vitess/issues/8465#issuecomment-951433088) in the [`docker_local` …
=> Remove tablet healthcheck cache record on error

go/vt/vtctl/vtctl.go, go/vt/wrangler/keyspace.go
Did an audit on the usage of 'horizontal split' and 'vertical split' to see if there were further references after the following commit:
685c221
Hopefully this should remove the rest of the references that aren't in split_clone go files.
#8843
- [ X ] Documentation was added or is not required
=> updating usage of vertical and horizontal splits

go/test/endtoend/preparestmt/stmt_methods_test.go, go/vt/vtgate/engine/lock.go, go/vt/vtgate/planbuilder/select.go, go/vt/vtgate/planbuilder/testdata/lock_cases.txt
This PR adds support for using advisory lock in prepare query by implementing GetFields method in lock primitive.
=> Lock primitive GetFields implementation

go/vt/vtgate/engine/comparer.go, go/vt/vtgate/engine/distinct.go, go/vt/vtgate/engine/ordered_aggregate.go, go/vt/vtgate/engine/ordered_aggregate_test.go, go/vt/vtgate/evalengine/arithmetic.go, go/vt/vtgate/evalengine/arithmetic_test.go, go/vt/vtgate/vindexes/consistent_lookup.go, go/vt/vttablet/tabletmanager/vreplication/replicator_plan.go, go/vt/vttablet/tabletserver/vstreamer/planbuilder.go, go/vt/wrangler/vdiff.go
- #8991
Adds in the collation module into the Vitess Code which can then be used to replace instances of the `weight_string` function used in the vitess codebase. The major change that this PR makes is with the `NullSafeComparator`
https://github.com/vitessio/vitess/blob/315d90751886b5901672a7278623de7d48aa4ec2/go/vt/vtgate/evalengine/arithmetic.go#L187
which now takes in additional collation info parameter which is used by the `collations.LookupByID` to find out the collation and then use it to collate the `varchar` strings based on their collation set.
So given the `NullSafeComparator` needs access to collation info we intend to provide the information available to it by updating the function calls and trying to fetch charset info from the `result` or `Fields` available at the least …
=> Collations Module Integration

.github/workflows/vtadmin_web_build.yml, .github/workflows/vtadmin_web_lint.yml, web/vtadmin/.stylelintrc, web/vtadmin/README.md, web/vtadmin/package-lock.json, web/vtadmin/package.json, web/vtadmin/src/components/TextInput.module.scss
**🎃 This PR should be squash-merged.**
tl;dr: This upgrades vtadmin-web to use node v16.13.0, which is the LTS [as of October 26th, 2021](https://nodejs.org/en/about/releases/). It also upgrades [node-sass](https://www.npmjs.com/package/node-sass) (by replacing with [sass](https://www.npmjs.com/package/sass)) and [react-scripts](https://www.npmjs.com/package/react-scripts) to their latest versions. 
Long version! This upgrades node to current LTS. 
The node upgrade unearthed build errors with node-sass, which ended up being an unpleasant rathole of dependencies until I came across the fix mentioned in https://github.com/facebook/create-react-app/issues/11037#issuecomment-870565090; namely, to switch from [node-sass](https://www.npmjs.com/package/node-sass) (which is now deprecated) to …
=> [vtadmin-web] Upgrade to node v16.13.0 LTS

go/vt/vtctl/grpcvtctldserver/server.go, go/vt/vtctl/schematools/copy.go, go/vt/vtctl/schematools/diff.go, go/vt/vtctl/schematools/schematools.go, go/vt/worker/multi_split_diff.go, go/vt/worker/split_clone.go, go/vt/worker/split_diff.go, go/vt/worker/vertical_split_diff.go, go/vt/wrangler/materializer.go, go/vt/wrangler/schema.go, go/vt/wrangler/vdiff.go
This is a preparatory PR to make migrating `CopySchemaShard` (next on my plate) a smaller overall change. Moves `wr.CopySchemaShard` and `wr.GetSchema` to `schematools` functions, and updates all callsites.
I then proceeded to mangle the diff in the vtworker tests by tidying up the imports. **Aside:** can we delete the worker code for v13?
#9122
=> [schematools] Move more functions out of `wrangler` to package importable by `grpcvtctldserver`

go/test/endtoend/onlineddl/declarative/onlineddl_declarative_test.go, go/vt/vttablet/onlineddl/executor.go
Followup to #9089 
This PR respects `--allow-zero-in-date` for `ddl_strategy` in the following:
- Any `CREATE TABLE` statement, whether online or not
- Any `-declarative` migration, whether it turns out to be an actual `CREATE TABLE` or an `ALTER TABLE`.
I believe this completes and covers all cases for `--allow-zero-in-date`.
`endtoend` tests added for validation.
Documentation PR to follow.
=> Respect --allow-zero-in-date in CREATE and in -declarative migrations

go.mod, go/vt/vtadmin/cluster/config.go, go/vt/vtadmin/cluster/config_test.go, go/vt/vtadmin/cluster/file_config.go, go/vt/vtadmin/cluster/file_config_test.go
This PR switches vtadmin `FileConfig.Set` to use viper to load configs.
[This issue][1] does a good job explaining the why behind this
admittedly-hacky code. What I would have preferred to do is add
`UnmarshalJSON`, `UnmarshalTOML`, (and so on) methods to both
`FileConfig` and `Config`, but switching to viper means we don't invoke
those custom unmarshalers _at all_, because viper is going from
$file_bytes=>`map[string]interface{}`=(via mapstructure)>$your_type.
So, we define a temporary struct (so far, so good) that will play nicely
with mapstructure's unmarshaling. We then take those string maps and
hand them off to the individual Config structs to run through the
kv-`parseOne` loop as before.
Since we're using viper to load from files now (and viper does not
invoke our custom unmarshal …
=> [vtadmin] viper config support

doc/internal/ReleaseInstructions.md
This pull request adds the `SUMMARY` variable to the `make do_release` examples in the release instructions.
=> Updated make do_release command example in the release instructions

go/mysql/server_flaky_test.go, go/vt/proto/tabletmanagerservice/tabletmanagerservice_grpc.pb.go, go/vt/vttablet/grpctmclient/client.go, go/vt/vttablet/grpctmserver/server.go, proto/tabletmanagerservice.proto
Forward merge from release-12.0.
Strictly speaking we could have skipped this port, but it makes the actual deletion of deprecated RPCs much simpler.
#9059
=> tabletmanager: correct implementations of deprecated RPCs for backwards compatibility

go/vt/wrangler/traffic_switcher.go
This PR is a small refactor to reduce the number of wrangler methods we passthrough, and invoke more `worfklow.Server` methods directly, the ultimate goal being to get trafficSwitcher completely over to `package workflow`
#7931
=> [wrangler] `getWorkflowState` refactor

go/vt/servenv/buildinfo.go, go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_init_test.go
This PR is both a feature request and the implementation (I will retcon an issue, but in this case the code was so small I found it was easier to discuss the concrete implementation than the abstract description).
This modifies both `servenv.versionInfo` and `tabletmanager.BuildTabletFromInput` to the aim of getting the metadata in the tablet process's `servenv.AppVersion` into the topo, so that others can access it (without needing to `curl $tablet/debug/vars | jq '.BuildHost'`, for e.g.)
<details>
<summary>Demo</summary>
```
I1009 18:24:22.974719   75906 main.go:67] I1009 22:24:22.974216 tablet_executor.go:277] Received DDL request. strategy=direct
I1009 18:24:23.374617   75906 main.go:67] I1009 22:24:23.374484 tablet_executor.go:277] …
```
=> [RFC] Add version-info to tablet tags in the topo

go/vt/wrangler/workflow.go
This corrects the boolean param passing order to DropSources made by v2 vreplication flows
Fixes #9174
=> Fix boolean parameter order in DropSources call for v2 flows

.github/workflows/cluster_endtoend_upgrade.yml, examples/legacy_local/101_initial_cluster.sh, examples/legacy_local/202_customer_tablets.sh, examples/legacy_local/302_new_shards.sh, go/test/endtoend/cluster/cluster_process.go, go/test/endtoend/cluster/vtctlclient_process.go, go/test/endtoend/mysqlctl/mysqlctl_test.go, go/test/endtoend/mysqlctld/mysqlctld_test.go, go/test/endtoend/sharding/base_sharding.go, go/test/endtoend/sharding/resharding/resharding_base.go, go/test/endtoend/tabletmanager/main_test.go, go/test/endtoend/tabletmanager/primary/tablet_test.go, go/test/endtoend/tabletmanager/tablegc/tablegc_test.go, go/test/endtoend/tabletmanager/throttler/throttler_test.go, go/test/endtoend/tabletmanager/throttler_custom_config/throttler_test.go, go/vt/discovery/healthcheck.go, go/vt/discovery/legacy_healthcheck.go, go/vt/vtctl/backup.go, go/vt/vtctl/reparent.go, go/vt/vtctl/vtctl.go, go/vt/vttablet/tabletmanager/vreplication/stats.go, go/vt/wrangler/testlib/planned_reparent_shard_test.go
This is a BREAKING CHANGE!!!
- Delete deprecated flags, commands and metrics.
- Remove checks for "master" tablet_type in tests, they should all now be "primary"
- Change upgrade tests to only run against most recent version (12.0), they will no longer work against older versions.
Fixes #8838 
Any deployment code/scripts that use the old flags or commands will need to change. Full list is in #8838
=> Inclusive naming: removing vtctl flags and commands that were deprecated in 12.0

GITHUB_SELF_HOSTED_RUNNERS.md
While using the self hosted runners today to check some flaky tests, I realised that there are a few steps that I am using frequently like copying the files from the docker container to the server and then finally scp them to my local system for ease of use. These steps aren't documented and are really useful for anyone trying to use the self-hosted runners to fix flaky tests.
This PR adds those missing steps and improves the docs for using self-hosted runners.
=> Improve self hosted runner docs

go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/querytree_transformers.go, go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/planbuilder/testdata/systemtables_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
This PR adds support to merge DBA queries in Gen4 if they are being routed to the same keyspace
=> Gen4: Improve merging of DBA queries

.golangci.yml
Small bug in the previous PR:
The `new` flag will only check the _LAST_ commit in a PR, not all of
them. We only want to use `--new` when running in a git post-commit
hook.
=> ci: do not run golangci-lint with `new` in CI

test/config.json
This PR increases the retry count on some flaky end-to-end tests. This does not reduce any flakyness of the tests, but the contributor will see less unrelated test failure.
=> add more retries to cluster end to end tests

go/vt/topo/faketopo/faketopo.go, go/vt/vttablet/tabletmanager/tm_state.go, go/vt/vttablet/tabletmanager/tm_state_test.go
Topo write error during TabletManager.ChangeType resulting in actual successful topo write led to a bug where the vttablet did not update its state to reflect the change and did not converge with shard sync.
Consider the case where we try to upgrade a replica to a primary tablet. Before we change the internal state of the tablet, we try to write to the topo server.
Assume that the write succeeds but an error is returned from the topo server. In this case, the tablet does not update its local information and continues to believe it is a replica. All the other tablets and vtgate register this change because of shard-sync and make changes accordingly. 
Since we do not start shard-sync for replica tablets, the tablet does not converge to the correct state. 
We are left in a state where the …
=> Topo write error in change tablet type

go/vt/sqlparser/ast_funcs.go, go/vt/vtgate/planbuilder/abstract/operator.go, go/vt/vtgate/planbuilder/abstract/operator_test.go, go/vt/vtgate/planbuilder/abstract/operator_test_data.txt, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/planbuilder/testdata/schema_test.json, go/vt/vtgate/planbuilder/testdata/systemtables_cases.txt
The gen4 planner was not sending on the queries with the database name stripped from expressions in the query.
Fixes #9135 
Fixes #8054
=> Remove keyspace from query before sending it on

go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_init_test.go
This is follow-up to #8973 and fixes #9186.
Without changing any of the flags in the local example:
```
❯ vtctlclient -server ":15999" ListAllTablets
zone1-0000000100 commerce 0 primary localhost:15100 localhost:17100 [] 2021-11-10T20:29:30Z
zone1-0000000101 commerce 0 replica localhost:15101 localhost:17101 [] <null>
zone1-0000000102 commerce 0 rdonly localhost:15102 localhost:17102 [] <null>
```
Fixes #9186
=> Default buildinfo tablet tags to off

go/cmd/vtcombo/main.go, go/test/endtoend/vtcombo/recreate/recreate_test.go, go/test/endtoend/vtcombo/vttest_sample_test.go
The development workflow in many frameworks (e.g. Rails) relies heavily on the ability to drop and (re)create databases. The `vttest` dbddl plugin for `vtcombo` supports these statements, but dropping and recreating a sharded keyspace via these statements results in an unsharded keyspace.
This changes the code in `vtcombo` to check the original topology configuration to determine the number of shards to use when recreating a keyspace.
N/A
=> vtcombo: `CREATE DATABASE` creates shards as specified by the topology

go/test/endtoend/vtgate/misc_test.go, go/vt/vtgate/engine/concatenate.go
When executing `UNION` queries, the individual queries are sent concurrently to the tablets. For `information_schema`  queries, the bind variables are changed before sending them down to the tablet. These two features together lead to one map being iterated over while being updated, which is a no-no that will panic.
The solution is to make a copy of the bindvars before executing the individual queries of the `UNION`.
Fixes #9139
=> make sure to copy bindvars when using them concurrently

go/vt/topo/conn.go, go/vt/topo/consultopo/election.go, go/vt/topo/consultopo/server_flaky_test.go, go/vt/topo/etcd2topo/election.go, go/vt/topo/etcd2topo/lock.go, go/vt/topo/helpers/copy_test.go, go/vt/topo/helpers/tee.go, go/vt/topo/k8stopo/election.go, go/vt/topo/keyspace.go, go/vt/topo/keyspace_test.go, go/vt/topo/memorytopo/election.go, go/vt/topo/shard.go, go/vt/topo/stats_conn.go, go/vt/topo/stats_conn_test.go, go/vt/topo/test/election.go, go/vt/topo/zk2topo/election.go, go/vt/vtctld/workflow.go
- Rename functions in topo package
- Deprecate some stats - `NewMasterParticipation`
- Add new stats as replacements - `NewLeaderParticipation`
Note: I verified that vitess-operator does not use any of the functions that are being renamed.
Fixes #8620
=> Inclusive naming: master->primary in topo package

go/vt/topotools/tablet.go, go/vt/wrangler/traffic_switcher.go
Continuing to chip away at isolatable pieces before the big final move of `*wrangler.trafficSwitcher`
#7931
=> Move `doCellsHaveRdonlyTablets` to topotools

.golangci.yml, go/vt/vttablet/tabletserver/messager/engine.go, go/vt/vttablet/tabletserver/messager/engine_test.go, go/vt/vttablet/tabletserver/messager/message_manager.go, go/vt/vttablet/tabletserver/messager/message_manager_test.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tabletserver_test.go
When the Messager engine is shutting down and the Engine has been
closed, there may be other goroutines still attempting to access the
Engine to generate queries. Since the Engine takes its own internal
mutex while it's closing itself down, these other goroutines can
deadlock it by calling into any method in the Engine.
To prevent this deadlock, we're using an atomic test that will fail fast
any engine operations as soon as the engine has started shutting down.
Signed-off-by: Vicent Marti <vmg@strn.cat>
---
This is a potential fix for https://github.com/vitessio/vitess/issues/8909, which is proving itself really hard to reproduce.
cc @derekperkins -- could you please try this in your system and see if the deadlocking stops?
cc @aquarapid @deepthi 
- …
=> messager: do not lock when testing for openness

test/local_example.sh
A local change to local_example.sh used for local testing made it to a commit:
https://github.com/vitessio/vitess/commit/b7ced6123e3a7eace52c2def259c7900a7c8cafb
This PR reverts that.
https://github.com/vitessio/vitess/pull/8630
=> Local example: fix local change that was committed erroneously

web/vtadmin/tailwind.config.js
... so _that's_ what `extend` is for. 🤡  I noticed classes like `text-red-500` weren't working and it's because I put the `textColors` config in the [wrong place](https://tailwindcss.com/docs/theme#extending-the-default-theme).
A fix for https://github.com/vitessio/vitess/pull/9215
N/A
=> [vtadmin-web] Bugfix to stop overwriting default tailwindcss text color rules

go/vt/vtgate/engine/comparer.go, go/vt/vtgate/engine/memory_sort_test.go, go/vt/vtgate/engine/merge_sort_test.go, go/vt/vtgate/engine/route.go, go/vt/vtgate/engine/route_test.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/memory_sort.go, go/vt/vtgate/planbuilder/ordering.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/planbuilder/testdata/memory_sort_cases.txt, go/vt/vtgate/planbuilder/testdata/oltp_cases.txt, go/vt/vtgate/planbuilder/testdata/postprocess_cases.txt
This PR adds collation support to the `engine` module specifically focused on making `comparer` struct collation aware by including collation ID in it which can then be passed down to the `NullSafeCompare` responsible for actually comparing values.
https://github.com/vitessio/vitess/blob/f085f12b1cd38a9bcf907604a747af308e93c4fd/go/vt/vtgate/engine/comparer.go#L26
To be able to pass down collation ID into the `comparer` struct we need to contain it further up the module level i.e. in `OrderByParams`.
https://github.com/vitessio/vitess/blob/f085f12b1cd38a9bcf907604a747af308e93c4fd/go/vt/vtgate/engine/route.go#L128
- As the params are populated in `planBuilder` it becomes trivial to extract collation ID in most cases.
The plan builder tests were updated so that testing can be done for …
=> Collations Integration Ordering

go/vt/vtgate/planbuilder/abstract/queryprojection.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
This pull request allows queries with a group by on a sharding key to pass through when it is a single route.
- fixes #9221
=> Gen4: allow group by queries with sharding keys to pass through when it is a single route

misc/git/hooks/golangci-lint
As suggested by @ajm188 in https://github.com/vitessio/vitess/pull/9049, the `--new` flag to `golangci-lint` that we're running in our post-commit hook doesn't work great if you have untracked files, if you're doing a partial commit, etc.
I'm switching the post-commit hook to work only on the packages that have actually been touched by the last commit. This code looks a lot like the one we had before except:
- We're running `revive` to check our style
- We're not running `golangci-lint` once for each package. We can just pass all the packages to a single invocation to significantly speed up processing time.
- https://github.com/vitessio/vitess/pull/9049
=> git: optimize golangci-lint post-commit hook

go/test/endtoend/vtgate/misc_test.go, go/vt/vtgate/engine/concatenate.go
When executing `UNION` queries, the individual queries are sent concurrently to the tablets. For `information_schema`  queries, the bind variables are changed before sending them down to the tablet. These two features together lead to one map being iterated over while being updated, which is a no-no that will panic.
The solution is to make a copy of the bindvars before executing the individual queries of the `UNION`.
Fixes #9139
Backport of #9191
=> [12.0] make sure to copy bindvars when using them concurrently

go/vt/vtadmin/api.go, go/vt/vtadmin/http/experimental/whoami.go, go/vt/vtadmin/rbac/authentication.go
We're just pulling the actor out of the current request, assuming that the actor making this request is also the actor making other requests, for the purposes of the frontend.
I added a "dumb" authenticator to test both versions, which looks like:
```diff
diff --git a/go/vt/vtadmin/rbac/authentication.go b/go/vt/vtadmin/rbac/authentication.go
index a43dcbb2e1..f5cb42f86c 100644
--- a/go/vt/vtadmin/rbac/authentication.go
+++ b/go/vt/vtadmin/rbac/authentication.go
@@ -134,6 +134,19 @@ func RegisterAuthenticator(name string, f func() Authenticator) {
authenticators[name] = f
}
+type dumbAuthn struct{}
+
+func (authn *dumbAuthn) Authenticate(ctx context.Context) (*Actor, error) { return nil, nil }
+func (authn *dumbAuthn) AuthenticateHTTP(r …
```
=> Add experimental `whoami` api endpoint

go/test/endtoend/vreplication/migrate_test.go, go/vt/vtctl/vtctl.go, go/vt/wrangler/workflow.go
Workflow Create polls the status of all vreplication streams for _timeout_ seconds (default:30) and reports an error if all streams are deemed not to have started. 
Currently we poll for each stream to reach the Running state. This is incorrect we start with the copy phase which can take a significant amount of time for large data. This PR also checks for the Copying state.
It is expected that, if the workflow is configured correctly, the default 30 seconds will be enough for all streams to find source tablets to start the copy phase.
#9000
=> VReplication Workflow Create: Check for Copying state while waiting for streams to start

go/vt/vttablet/tabletserver/txthrottler/mock_healthcheck_test.go, go/vt/vttablet/tabletserver/txthrottler/mock_throttler_test.go, go/vt/vttablet/tabletserver/txthrottler/mock_topology_watcher_test.go, go/vt/vttablet/tabletserver/txthrottler/tx_throttler_test.go, go/vt/workflow/resharding/mock_resharding_wrangler_test.go, go/vt/workflow/resharding/resharding_wrangler.go
This updates our `go:generate` directives to work with the version of mockgen we upgraded to in May, and then runs the generators, which produced some mostly comment-only diffs.
Follow-up tasks: https://github.com/vitessio/vitess/issues/9148
=> [mockgen] update generator directives and regenerate

go/vt/vtctl/vtctl.go
The `Workflow` command takes a `keyspace.workflow`  spec to identify which workflow to operate on. All actions except `listall` require a workflow to be specified. The validation for this fails if the user specifies the trailing  `.`  but nothing after that. It then resolves to an empty workflow string and internally this results in the action to be operated on *all* workflows.
#9137
=> vtctlclient Workflow command: handle empty workflow name in a keyspace.workflow spec 

go/cmd/vtbackup/vtbackup.go, go/test/endtoend/reparent/plannedreparent/reparent_test.go, go/vt/mysqlctl/builtinbackupengine.go, go/vt/schemamanager/tablet_executor.go, go/vt/vtctl/grpcvtctldserver/server.go, go/vt/vtctl/grpcvtctldserver/server_slow_test.go, go/vt/vtctl/grpcvtctldserver/server_test.go, go/vt/vtctl/grpcvtctldserver/testutil/test_tmclient.go, go/vt/vtctl/reparentutil/emergency_reparenter.go, go/vt/vtctl/reparentutil/emergency_reparenter_test.go, go/vt/vtctl/reparentutil/planned_reparenter.go, go/vt/vtctl/reparentutil/planned_reparenter_flaky_test.go, go/vt/vtctl/reparentutil/replication.go, go/vt/vtctl/reparentutil/replication_test.go, go/vt/vtctl/reparentutil/util.go, go/vt/vtctl/reparentutil/util_test.go, go/vt/vttablet/tabletmanager/restore.go, go/vt/vttablet/tmrpctest/test_tm_rpc.go, go/vt/worker/diff_utils.go, go/vt/worker/multi_split_diff.go, go/vt/worker/split_diff.go, go/vt/worker/vertical_split_diff.go, go/vt/wrangler/keyspace.go, go/vt/wrangler/reparent.go, go/vt/wrangler/schema.go, go/vt/wrangler/vdiff_env_test.go
Replace calls to deprecated RPCs with new ones.
Fixes #8837 
This is not a breaking change per se. However, it does mean that a new vtctld will not work against a vttablet that is pre-12.0.
=> Inclusive naming: use new RPCs in vtctl/vtctld/wrangler etc.

go/vt/logz/logz_utils.go
Signed-off-by: notfelineit <notfelineit@gmail.com>
This PR is part of a continuing effort to remove or update jQuery across the vitess repo. In particular, it removes jQuery from the `logz` package used to render sortable tables in the vtgate UI, by rewriting the logic in pure javascript.
Functionality has been tested manually, and currently works:
pt. 1 of jquery removal/migration was merged: https://github.com/vitessio/vitess/pull/9239
No further deployment steps are needed.
=> Migrate jQuery (pt. 2/3) 

go/mysql/collations/golden_test.go, go/mysql/collations/mysqlversion.go, go/mysql/collations/tools/makecolldata/mysqlversions.go
Small change to the Collations package: a test (turned off by default) that prints an up-to-date table with all the collations that we support for each MySQL version. The table can be added to our docs and it looks very neat: https://github.com/vitessio/website/pull/883
- https://github.com/vitessio/website/pull/883
=> collations: implement TestSupportTables

go/vt/wrangler/workflow.go
This PR backports #9175 to the 12.0 release branch
#9174
=> [backport] Fix boolean parameter order in DropSources call for v2 flows

go/vt/vtgate/planbuilder/abstract/concatenate.go, go/vt/vtgate/planbuilder/testdata/systemtables_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
This PR add support for filter on derived union system table with star projection.
- Closes https://github.com/vitessio/vitess/issues/9214
=> Gen4: filter on derived union system table with star projection

go/vt/vtgate/executor.go, go/vt/vtgate/executor_test.go
When using a `show vitess_shards like 'keyspace1/%'`
filter, actually use the keyspace part of the query to limit the
keyspaces for which we fetch all shards, instead of getting all
shards from all keyspaces the vtgate knows about and then
filtering them out. This probably does not matter unless you
have a lot of shards and/or are running `show vitess_shards`
like this frequently.
=> Do keyspace filtering when possible with `show vitess_shards`

go/vt/vtctl/vtctl.go
Signed-off-by: hallaroo 
@aquarapid found a couple places in the help where [-dry_run] was replaced with [-dry-run]. This PR changes this back as [-dry-run] is not the correct usage, it should be the underscore one.
e.g.:
`SwitchReads Error: rpc error: code = Unknown desc = flag provided but not defined: -dry-run
E1116 15:14:07.388982   98844 main.go:76] remote error: rpc error: code = Unknown desc = flag provided but not defined: -dry-run
`
Not 100% sure when this was introduced but found the same issue in https://github.com/vitessio/vitess/pull/9177/ 
- [ - ] Tests were added or are not required
- [ - ] Documentation was added or is not required
=> changing -dry-run to -dry_run

doc/releasenotes/12_0_0_release_notes.md, doc/releasenotes/12_0_1_release_notes.md, go/vt/vtctl/vtctl.go
Fixes #9193 
Followup to https://github.com/vitessio/vitess/pull/8972
This PR restores `vtctl VExec` functionality. It was removed based on the assumption the only uses for this command were for Online DDL command. This was wrong, and VExec is also used as a wrapper around VReplication.
For now, we restore the full functionality, although we intend to deprecate use of VExec for Online DDL. See some discussion in https://github.com/vitessio/vitess/pull/8972
cc @deepthi @hallaroo @mattlord
=> restore 'vtctl VExec' command (backport v12)

go/test/endtoend/tabletgateway/vtgate_test.go, go/test/endtoend/vtgate/tablet_healthcheck_cache/correctness_test.go, go/vt/discovery/healthcheck.go, go/vt/discovery/tablet_health_check.go, go/vt/discovery/topology_watcher.go, test/config.json
There was a race condition between [deleting a tablet's healthcheck record](https://github.com/vitessio/vitess/blob/693c5dbdeacdd7a705b46ebce6776a5256c8cfef/go/vt/discovery/healthcheck.go#L379-L408) from the authoritative map ([`hc.healthByAlias`](https://github.com/vitessio/vitess/blob/693c5dbdeacdd7a705b46ebce6776a5256c8cfef/go/vt/discovery/healthcheck.go#L227)) and [updating the same tablet's health data record](https://github.com/vitessio/vitess/blob/693c5dbdeacdd7a705b46ebce6776a5256c8cfef/go/vt/discovery/healthcheck.go#L410-L485) ([`hc.healthData`](https://github.com/vitessio/vitess/blob/693c5dbdeacdd7a705b46ebce6776a5256c8cfef/go/vt/discovery/healthcheck.go#L227)).
This could cause us to effectively re-add an updated copy of the tablet healthcheck record after it's been deleted …
=> Prevent Race Conditions Between Tablet Deletes and Updates

go/mysql/collations/8bit.go, go/mysql/collations/collation.go, go/mysql/collations/integration/helpers_test.go, go/mysql/collations/integration/wildcard_test.go, go/mysql/collations/internal/charset/charset.go, go/mysql/collations/internal/uca/collation.go, go/mysql/collations/internal/uca/layout.go, go/mysql/collations/multibyte.go, go/mysql/collations/remote/collation.go, go/mysql/collations/uca.go, go/mysql/collations/unicode.go, go/mysql/collations/wildcard.go, go/mysql/collations/wildcard_test.go
I've added support to the `collations` package to perform collation-aware wildcard matching. I've written an API optimized for our evaluation engine, where you pass in a pattern (i.e. the right side of the `LIKE` operator) and it compiles it to a `WildcardPattern` matcher that can be repeatedly be called on different values for the left side to see if they match.
The wildcard patterns are pre-processed and optimized: any wildcards that can be matched using `Collate` directly (i.e. wildcards without any special matching characters, or wildcards where the only special character is at the end, `"foobar%"`) will not use the wildcard matcher.
I've added comprehensive tests for all collations and many different patterns against a live MySQL instance.
cc @systay @frouioui 
- …
=> collations: Wildcard matching for the 'LIKE' operator

go/vt/vtgate/engine/comparer.go, go/vt/vtgate/engine/memory_sort_test.go, go/vt/vtgate/engine/ordered_aggregate.go, go/vt/vtgate/engine/ordered_aggregate_test.go, go/vt/vtgate/engine/route_test.go, go/vt/vtgate/evalengine/arithmetic.go, go/vt/vtgate/evalengine/arithmetic_test.go
While working on #9155 it was suggested by @frouioui that we can use better error formatting to explicitly let the user know about the error being caused due to missing collation information or it is an unsupported collation.
Earlier the case for missing collation information was being suggested as a `UnsupportedComparisonError` error but given collation support is inbound we should update the error message to explicitly tell in case of `text` values that collation information is missing using `UnsupportedCollationError`
To support this the following was done:
- Error message was updated in `UnsupportedCollationError`
- `if` check with `text` types now also handles the case for `collation.Unknown`
- Accommodate the return of `UnsupportedCollationError` in `ordered_aggregate.go` and …
=> Explicit Collation Error

go/vt/vtexplain/vtexplain_vttablet.go, go/vt/vtexplain/vtexplain_vttablet_test.go
When running `vtexplain` with a query that joins tables that have matching column names with differing types, it would fail with an error like `unknown error: column type mismatch for column`. This was caused by having similarly named columns (but with different types) on the different tables.
`vtexplain` builds an internal map of column names to their respective types, build only builds a single map for all tables in the query - so if the tables have columns that share the name but different types, the code would fail with an error.
This pull request changes `vtexplain` to build a map per table, which allows `vtexplain` to handle these types of queries correctly.
=> vtexplain: correct handling of column types for queries involving multiple tables

go/vt/vttablet/tabletmanager/replmanager.go, go/vt/vttablet/tabletmanager/replmanager_test.go, go/vt/vttablet/tabletmanager/rpc_replication.go, go/vt/vttablet/tabletmanager/rpc_replication_test.go
During the call to `PromoteReplica`, we initially stop the replication manager health ticks.
The steps for that we follow are `PromoteReplica` -> `tm.changeTypeLocked` -> `tm.tmState.ChangeTabletType` -> `ts.updateLocked(ctx)` -> `ts.tm.replManager.SetTabletType(ts.tablet.Type)` .
This is called with PRIMARY as the tablet type which stops the ticks.
But in the PRs, #8422 and #8745, we started calling `tm.replManager.setReplicationStopped(false)` to reset the replication manager's state to not indicate that replication had been stopped. As a side-effect, we also enabled the replication manager ticks in this call. This should not be done on a PRIMARY tablet since it does not replicate from any other tablet.
This led to logs being seen on the primary tablet similar to `Failed to reconnect to …
=> Replication manager should not start health ticks after calling Promote Replica

go/test/endtoend/preparestmt/stmt_methods_test.go, go/test/endtoend/vtgate/misc_test.go, go/vt/vtgate/executor.go
This PR fixes the bug of handling show statements via plan or legacy way.
- fixes #9268
- backport of #9280
=> [12.0] Fix for show commands in prepare statement

go/mysql/sql_error.go, go/vt/sqlparser/parse_test.go, go/vt/vterrors/state.go, go/vt/vtgate/evalengine/comparisons.go, go/vt/vtgate/evalengine/comparisons_test.go, go/vt/vtgate/evalengine/convert.go, go/vt/vtgate/evalengine/convert_test.go, go/vt/vtgate/evalengine/evalengine.go, go/vt/vtgate/evalengine/expressions.go
As a long term goal, we want to replace the usage of `PlanValue` everywhere. To accomplish this change, we need to add an implementation to `evalengine.Expr` which can store tuples and evaluate them. This PR accomplishes that change. It introduces a new implementation of `evalengine.Expr` which stores multiple values and also changes the `EvalResult` struct to be able to store multiple results for intermediate steps.
- #7280
=> Add Tuples and InOp implementation to EvalEngine

go/vt/mysqlctl/backup.go
In short, we are blindly setting `super_read_only` off in the restore flow, in case the default my.cnf params has `super_read_only=ON`.  This allows us to populate our metadata tables without running into write issues.
Tested manually and by the current DB restore e2e flow.
=> Set super_read_only off during restore;  achieves same as PR #8929

go/mysql/flavor_mysql.go, go/test/endtoend/mysqlserver/main_test.go, go/test/endtoend/mysqlserver/mysql_server_test.go
Tested locally with both 5.7 and 8.0.
Will see if I can find somewhere in the e2e tests to add a partitioned table to exercise this.
Fixes #9180
=> Fix table/sizes query, to allow vttablet schema engine to see partitioned tables

go/test/endtoend/vtgate/partialfailure/main_test.go, go/test/endtoend/vtgate/utils/utils.go, go/vt/sqlparser/comments.go, go/vt/vtadmin/api.go, go/vt/vtexplain/testdata/multi-output/updatesharded-output.txt, go/vt/vtexplain/vtexplain.go, go/vt/vtexplain/vtexplain_flaky_test.go, go/vt/vtexplain/vtexplain_vttablet.go, go/vt/vtgate/autocommit_test.go, go/vt/vtgate/executor.go, go/vt/vtgate/executor_dml_test.go, go/vt/vtgate/executor_framework_test.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/executor_test.go, go/vt/vtgate/plan_execute.go, go/vt/vtgate/safe_session.go, go/vt/vtgate/vcursor_impl.go, go/vt/vttablet/sandboxconn/sandboxconn.go, test/config.json
This PR reverses the effect of partial dml query execution instead of rolling back the complete transaction when the transaction is explicitly created by the user.
- Closes #9266
=> Better handling of partial dml query exec in transaction

go/vt/vtgate/planbuilder/abstract/fuzz.go
Removes the implementation of `FakeSI` and uses the one from the `semantics` package instead.
=> Fuzzing: Refactor abstract_fuzzer

go/vt/vtctl/reparentutil/util.go, go/vt/vtctl/reparentutil/util_test.go
While choosing the new primary in PRS, we should be using the relay log position, if it is available. This PR makes that change and adds tests for it.
- Closes #5991
This PR has been created on top of #9259, and it should be merged after it.
=> Use relay log position in PRS while choosing the new primary

docker/vttestserver/run.sh, go/cmd/vttestserver/main.go, go/vt/vttest/local_cluster.go, go/vt/vttest/vtprocess.go
This PR adds support for changing Planner Version in vttestserver docker image by providing the environment variable. This is needed for the rails sharded blog, so that the readers can follow along with the code examples if they want to without bringing up the entire Vitess cluster, but just using the docker image for vttestserver. However, rails only works with Gen4, so we need the functionality for changing the planner version.
=> Add support for changing Planner Version in vttestserver docker image

web/vtadmin/README.md, web/vtadmin/package.json
This adds a lil helper command for running vtadmin-web against the local example in dev mode, to complement some docs I'm writing. (It effectively matches what's in the [vtadmin-up.sh script](https://github.com/vitessio/vitess/blob/main/examples/local/scripts/vtadmin-up.sh), but I didn't want to conflate the two since I think of vtadmin-up.sh as for running VTAdmin, not developing it.) 
N/A
N/A
=> [vtadmin-web] Add 'npm run local' command

go/mysql/auth_server.go, go/mysql/auth_server_clientcert.go, go/mysql/auth_server_none.go, go/mysql/auth_server_static.go, go/mysql/ldapauthserver/auth_server_ldap.go, go/mysql/vault/auth_server_vault.go
The TLS client certificates can simply be derived based on the
mysql.Conn passed through, but passing through the actual Conn, gives us
access to Conn.ClientData or anything else an Auth{Method,Server} might need to
implement.
It's arguable that if we need access to the lower level Conn, we could
simply implement the actual HandleAuthPluginData instead of these
*Storage interfaces, and that's true. But not all AuthMethods can get
away with this because they need to write to the Conn's connection using
private functions.
For example, the `mysqlCachingSha2AuthMethod` needs to write more data
on the socket after calling `UserEntryWithCacheHash`, so to write a new
`UserEntryWithCacheHash` that needs data from `mysql.Conn`, I'm left
wtih no other options since I can't vendor or reimplement the …
=> mysql: Pass mysql.Conn through {Hash,PlainText,Caching}Storage interfaces

go/vt/vttablet/tabletserver/repltracker/writer.go, go/vt/vttablet/tabletserver/repltracker/writer_test.go
As described in the issue, we do not want the heartbeat writer to be using the `vt_dba` user which has super privileges. This creates issues with PRS wherein, the insert commands succeed even after the mysql instance has been set to read only causing the old primary to diverge from the new primary.
This PR changes the user back to `vt_app`. 
- Fixes #9290
=> Change heartbeat writer to use vt_app user

go/vt/sqlparser/ast_funcs.go, go/vt/sqlparser/parse_test.go
This PR avoids adding parenthesis around null value in default for BLOB, TEXT, GEOMETRY and JSON column.
- Fixes #9297
=> fix: avoid parenthesis around default null in BLOB, TEXT, GEOMETRY and JSON column

web/vtadmin/src/components/Button.module.scss, web/vtadmin/src/components/Code.module.scss, web/vtadmin/src/components/TextInput.module.scss, web/vtadmin/src/components/charts/charts.scss, web/vtadmin/src/components/inputs/Select.module.scss, web/vtadmin/src/components/layout/WorkspaceTitle.module.scss, web/vtadmin/src/components/routes/Backups.tsx, web/vtadmin/src/components/routes/Debug.tsx, web/vtadmin/src/components/routes/Gates.tsx, web/vtadmin/src/components/routes/Keyspaces.tsx, web/vtadmin/src/components/routes/Schemas.tsx, web/vtadmin/src/components/routes/Tablets.tsx, web/vtadmin/src/components/routes/Vtctlds.tsx, web/vtadmin/src/components/routes/Workflows.module.scss, web/vtadmin/src/components/routes/Workflows.tsx, web/vtadmin/src/components/routes/keyspace/Keyspace.module.scss, web/vtadmin/src/components/routes/keyspace/KeyspaceShards.tsx, web/vtadmin/src/components/routes/schema/Schema.module.scss, web/vtadmin/src/components/routes/schema/Schema.tsx, web/vtadmin/src/components/routes/shard/Shard.module.scss, web/vtadmin/src/components/routes/shard/ShardTablets.module.scss, web/vtadmin/src/components/routes/tablet/Tablet.module.scss, web/vtadmin/src/components/routes/workflow/WorkflowStreams.tsx, web/vtadmin/src/components/tabs/TabContainer.module.scss, web/vtadmin/src/components/tooltip/Tooltip.module.scss, web/vtadmin/src/index.css, web/vtadmin/tailwind.config.js
This consolidates all of our font sizing variables into the tailwind.config.js file. Since we use a 10px basis, as opposed to the tailwind/browser default of 16px, our font scale differs from [the tailwind docs](https://tailwindcss.com/docs/font-size), hence the overrides. (This will also make it 1000x easier to adjust font sizes if we do ever decide to change the rem basis.) 
Also added some lorem ipsum to the /debug page until we get Storybook set up. 
- #9215 
N/A
=> [vtadmin-web] Consolidate font sizing into tailwind.config.js

Makefile
Signed-off-by: John Watson <johnw@planetscale.com>
With `.ONESHELL` enabled in the Makefile, it disables the default behavior of failing targets if any command fails. As the default is only `.SHELLFLAGS = -c`.
=> Re-enable default Make behavior of failing target if any command fails

doc/releasenotes/13_0_0_summary.md, go/vt/schemamanager/tablet_executor.go, go/vt/vtctl/vtctl.go, go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go
Followup to https://github.com/vitessio/vitess/pull/9171
In https://github.com/vitessio/vitess/pull/9171 we introduced `ALTER VITESS_MIGRATION '...' COMPLETE` command. This PR complements the SQL interface by adding a `vtctl OnlineDDL <keyspace> complete <uuid>` command.
To be documented.
Tracking: #6926
=> Online DDL: vtctl OnlineDDL supports 'complete' command

go/cmd/vttablet/vttablet.go
[`ricebox`](https://github.com/GeertJohan/go.rice) is an interesting tool to embed assets in binaries. As best I can tell, it does some hackery with symbol tables and embedding extraneous zips in binaries to make assets available at runtime.
This is not really compatible with golang's standard tooling (or bazel), it's manipulation that must be done after-build (at least for `append`).
Notably, the ricebox embedded assets don't actually seem to be critical to run-time. At least, with `gh-ost`, there's a flag to override the bin.
Can we eliminate the dependence on this `ricebox` if the `gh-ost` bin is overridden?
- None
None
=> only grab gh-ost exec if not overridden

go/mysql/flavor.go, go/mysql/replication_status.go, go/test/endtoend/tabletmanager/main_test.go, go/test/endtoend/tabletmanager/tablet_health_test.go, go/vt/vttablet/tabletserver/repltracker/poller.go
When mysqld tells us that [`seconds_behind_master`](https://dev.mysql.com/doc/refman/5.7/en/show-slave-status.html) is unknown (`NULL`) — or we get back any other value that cannot be converted to a uint — let's estimate the replication lag seconds value ([`seconds_behind_master` itself is fuzzy](https://dev.mysql.com/doc/refman/5.7/en/replication-administration-status.html)) in vttablet's healthcheck stats using the last seen value and the time elapsed since. This gives us the most accurate estimate possible of the replica lag when the replica cannot talk to its source and is constantly retrying and in a state where `Slave_IO_Running` == `Connecting`, [which we consider to be equivalent to running](https://github.com/vitessio/vitess/blob/5c7ee04b64ecf2cbe7b7430091f7e14d16f39723/go/mysql/f …
=> Estimate replica lag when seconds behind from mysqld is unknown

go/test/endtoend/tabletmanager/throttler/throttler_test.go, go/vt/vttablet/tabletserver/throttle/mysql/mysql_throttle_metric.go, go/vt/vttablet/tabletserver/throttle/mysql/probe.go, go/vt/vttablet/tabletserver/throttle/throttler.go
In this PR we override the existing throttler behavior for shard health checks.
A shard is considered healthy if all replicas are lagging within a certain threshold. 
Today, the primary tablet acquires the identities of all shard's tablets, filters the relevant tablets, then records the hostname.port of the **MySQL** servers of those tablets. It continuously polls these MySQL servers directly for replication lag.
In this PR, the primary tablet no longer accesses those MySQL servers directly (the code to do that is still here, but never used). Instead, it accesses the tablet's HTTP interface for `/throttler/check-self`. On each replica tablet, that check already reflects the replication lag status of the tablet. So now the primary tablet acquires lag information indirectly via HTTP …
=> Tablet throttler: check replicas via HTTP rather than via MySQL

go/vt/topo/vschema.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletserver/schema/engine.go, go/vt/vttablet/tabletserver/schema/engine_test.go, go/vt/vttablet/tabletserver/schema/schema.go, go/vt/vttablet/tabletserver/vstreamer/rowstreamer_test.go, go/vt/vttablet/tabletserver/vstreamer/testenv/testenv.go, go/vt/vttablet/tabletserver/vstreamer/uvstreamer_flaky_test.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer_flaky_test.go
This is based off of the external PR https://github.com/vitessio/vitess/pull/9306 to try to fix the failing tests
This PR addresses the following bug in schema engine reload process:
* The schema engine depends on the `information_schema.tables create_time` field to tell when a table is updated. Unlike the name might indicate, this field is updated when a structural DDL is performed on a table (e.g. a column add/delete).
* As an optimization, the schema engine keeps track of the last time it loaded (reloaded) the schema, and saves this timestamp (called `lastChange`).
* When reloading schema, for each table we then check the `create_time` for that table against this saved timestamp, and if it's older, we skip examining the table further for changes.
* Vitess online DDL swaps the tables, …
=> Schema Engine: fix to account for  Online DDL swapped tables 

.github/workflows/vtadmin_web_lint.yml, web/vtadmin/.npmrc, web/vtadmin/package-lock.json, web/vtadmin/src/proto/vtadmin.d.ts
This closes https://github.com/vitessio/vitess/issues/9321 by enforcing installed node/npm versions match the semvers specified in the package.json's `engines` property. We do this with npm's [`engine-strict` flag](https://docs.npmjs.com/cli/v8/using-npm/config#engine-strict). 
(Rant about "why does this even require a separate, special flag and yet another got-dang repo dotfile arghhhh" has been redacted.)
🚨 **Going forward, `make vtadmin_web_proto_types` will fail if a developer's local node/npm install is too old.** Here's what it looks like:
```bash
🍕~/workspace/vitess $ nvm use 14.15.3
Now using node v14.15.3 (npm v6.14.9)
🍕~/workspace/vitess $ make vtadmin_web_proto_types
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported …
```
=> [vtadmin-web] Enforce node + npm versions with .npmrc

web/vtadmin/src/components/dropdown/MenuItem.tsx, web/vtadmin/src/components/routes/Debug.tsx, web/vtadmin/tailwind.config.js
This extends tailwind's colour palette with our own, which handily generates a bunch of utility classes for us for background colour, etc. (Eventually, we may want to replace tailwind's default palette entirely, for simplicity... but this is fine for now.) 
I also renamed "vitess-blue" to "vtblue" since it saves a few characters. :) 
At some point I'll do a pass to update everything that's presently using bespoke CSS to instead use the generated tailwind utility classes.
N/A
N/A
=> [vtadmin-web] Add colours to tailwind.config.js

go/vt/vttablet/tabletmanager/vreplication/controller.go, go/vt/vttablet/tabletmanager/vreplication/engine.go, go/vt/vttablet/tabletmanager/vreplication/utils.go, go/vt/vttablet/tabletmanager/vreplication/vreplicator.go, go/vt/vttablet/tabletserver/repltracker/writer.go, go/vt/vttablet/tabletserver/repltracker/writer_test.go, go/vt/vttablet/tabletserver/schema/tracker.go, go/vt/withddl/withddl.go, go/vt/withddl/withddl_test.go
Currently the heartbeat writer uses `vt_app` user to create the database, table and also run the upsert commands. This isn't correct since `vt_app` might not have the `CREATE` privilege, causing the create database and table commands to fail. This PR addresses this issue by creating 2 app pools, one for `vt_app` to run the insert commands and `vt_allprivs` to run the create commands.
As part of this PR, `WithDDL` has also changed, and now takes two functions instead of one in its `Execute` method. The second function, if provided, is used for running the DDL commands. This allows the caller of this function to have two different execution functions for DDLs and other queries. This change will be helpful in the future too, in all the other usages of `WithDDL` which are using the `vt_app` …
=> Make the heartbeat writer use 2 pools

go/vt/vttablet/tabletserver/throttle/config/mysql_config.go, go/vt/vttablet/tabletserver/throttle/mysql/mysql_throttle_metric.go, go/vt/vttablet/tabletserver/throttle/mysql/probe.go, go/vt/vttablet/tabletserver/throttle/mysql/probe_test.go, go/vt/vttablet/tabletserver/throttle/throttler.go
Followup to #9334 
Since #9334 is merged, the throttler no longer directly accesses MySQL on other tablets. As such, there's no longer need in:
- A special throttler user account 
- Any user/password configuration
- logic to open a remote connection
- any special logic upon promotion to leader (other than generate a Tick)
This PR cleans up all the above with minor refactoring/changes.
#9334
=> Throttler: cleaning up legacy remote MySQL connection logic

go/vt/vtgate/engine/cached_size.go, go/vt/vtgate/engine/delete.go, go/vt/vtgate/engine/delete_test.go, go/vt/vtgate/engine/dml.go, go/vt/vtgate/engine/update.go, go/vt/vtgate/engine/update_test.go, go/vt/vtgate/evalengine/expressions.go, go/vt/vtgate/planbuilder/dml.go, go/vt/vtgate/planbuilder/testdata/dml_cases.txt, go/vt/vtgate/planbuilder/testdata/oltp_cases.txt, go/vt/vtgate/planbuilder/testdata/tpcc_cases.txt, go/vt/vtgate/semantics/semantic_state.go
Changes the planner and engine primitives to use the new evalengine expressions instead of PlanValue. This is in preparation for multi column vindex support.
=> Multi column vindex support for DML

java/pom.xml
Bumps log4j-api from 2.13.3 to 2.15.0.
---
updated-dependencies:
- dependency-name: org.apache.logging.log4j:log4j-api
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
#9348 #9349
=> build(deps): bump log4j-api from 2.13.3 to 2.15.0 in /java

config/mycnf/mysql57.cnf, config/mycnf/mysql80.cnf, doc/releasenotes/13_0_0_summary.md, go/vt/mysqlctl/backup.go, go/vt/vttablet/tabletmanager/rpc_replication.go, go/vt/vttablet/tabletmanager/shard_sync.go
While looking into #9290 we discovered that the heartbeat writer was creating errant transactions during a failover (PlannedReparent). While we need to fix that properly, it has been suggested that we should run with `super_read_only` on MySQL versions that support it.
This PR does two things.
- change default for use_super_read_only to true
- set super-read-only in cnf files
#9290 
It is expected that this change is safe and backwards-compatible. Anyone who is relying on the current behavior should pass `-use_super_read_only=false` on the vttablet command line, and make sure they are using a custom my.cnf instead of the one provided as the default by Vitess.
=> Change default for super_read_only to true

.github/workflows/check_make_parser.yml, .github/workflows/check_make_sizegen.yml, .github/workflows/check_make_visitor.yml, .github/workflows/cluster_endtoend_mysql80.yml, .github/workflows/cluster_endtoend_upgrade.yml, .github/workflows/e2e_race.yml, .github/workflows/legacy_local_example.yml, .github/workflows/local_example.yml, .github/workflows/region_example.yml
Actions workflows that run on `ubuntu-latest` have been failing for ~12 hours now.
This is because of changes made to the images
https://github.com/actions/virtual-environments/pull/4708
https://github.com/actions/virtual-environments/pull/4674
~Since the image already includes a mysql install, perhaps we can stop trying to install it ourselves.~
Let's try to install the latest 8.0.x version ourselves.
=> CI: ubuntu-latest now has MySQL 8.0.26, let us override it with latest 8.0.x

go/vt/discovery/healthcheck.go, go/vt/discovery/topology_watcher.go, go/vt/discovery/topology_watcher_test.go, go/vt/vtgate/tabletgateway_test.go
There's an interesting race condition when starting/stopping a healthcheck.
1. Create `NewHealthCheck`
2. `NewHealthCheck` spawns topo-watchers in goroutines
3. `hc.Close()` is called
4. `Stop()` is called on the topo-watchers
5. The topo-watcher cancels the ctx and calls `Wait()` on the wait-group. The `Wait()` returns immediately, because the `Start()` goroutine hasn't even started yet. So nothing was ever added to the wait-group.
6. You close the topo-srv, which should be safe, because the health-check has already been closed
7. The `Start()` goroutine now fires, which calls `tw.loadTablets()` (before even checking ctx!). This will NPE because the topo-srv has already been closed.
I actually managed to reproduce this with a test.
There's another potential fix here:
- Move `loadTablets` …
=> Fix race condition when rapidly starting/stopping health check

.github/workflows/check_make_parser.yml, .github/workflows/check_make_sizegen.yml, .github/workflows/check_make_visitor.yml, .github/workflows/cluster_endtoend_mysql80.yml, .github/workflows/cluster_endtoend_upgrade.yml, .github/workflows/e2e_race.yml, .github/workflows/legacy_local_example.yml, .github/workflows/local_example.yml, .github/workflows/region_example.yml
This is a backport of #9368 to fix the CI build by overriding ubuntu-latest MySQL version.
- #9368
=> [11.0] CI: ubuntu-latest now has MySQL 8.0.26, let us override it with latest 8.0.x

.github/workflows/check_make_parser.yml, .github/workflows/check_make_sizegen.yml, .github/workflows/check_make_visitor.yml, .github/workflows/cluster_endtoend_mysql80.yml, .github/workflows/cluster_endtoend_upgrade.yml, .github/workflows/e2e_race.yml, .github/workflows/legacy_local_example.yml, .github/workflows/local_example.yml, .github/workflows/region_example.yml
This is a backport of #9368 to fix the CI build by overriding ubuntu-latest MySQL version.
- #9368
=> [12.0] CI: ubuntu-latest now has MySQL 8.0.26, let us override it with latest 8.0.x

.github/workflows/check_make_parser.yml, .github/workflows/check_make_sizegen.yml, .github/workflows/check_make_visitor.yml, .github/workflows/cluster_endtoend_mysql80.yml, .github/workflows/cluster_endtoend_upgrade.yml, .github/workflows/e2e_race.yml, .github/workflows/legacy_local_example.yml, .github/workflows/local_example.yml, .github/workflows/region_example.yml
This is a backport of #9368 to fix the CI build by overriding ubuntu-latest MySQL version.
- #9368
=> [10.0] CI: ubuntu-latest now has MySQL 8.0.26, let us override it with latest 8.0.x

java/pom.xml
Bumps log4j-api from 2.13.3 to 2.15.0.
---
updated-dependencies:
- dependency-name: org.apache.logging.log4j:log4j-api
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
- Backport of #9348 #9349
=> [11.0] build(deps): bump log4j-api from 2.13.3 to 2.15.0 in /java

java/pom.xml
Bumps log4j-api from 2.13.3 to 2.15.0.
---
updated-dependencies:
- dependency-name: org.apache.logging.log4j:log4j-api
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
- Backport of #9348 #9349
=> [10.0] build(deps): bump log4j-api from 2.13.3 to 2.15.0 in /java

.github/workflows/cluster_endtoend_mysql80.yml, .github/workflows/cluster_endtoend_onlineddl_scheduler.yml, .github/workflows/cluster_endtoend_upgrade.yml, .github/workflows/e2e_race.yml, .github/workflows/legacy_local_example.yml, .github/workflows/local_example.yml, .github/workflows/region_example.yml, test/ci_workflow_gen.go, test/templates/cluster_endtoend_test_mysql80.tpl
Limiting the new/additional work we do in the CI in order to limit the time and effort required to meet the primary objective: ensure that we deterministically install the latest MySQL 8.0 release from the official MySQL APT repo. 
Follow-up on: https://github.com/vitessio/vitess/pull/9368
Caused by: https://github.com/actions/virtual-environments/pull/4674
=> CI: Simplify Changes to Explicitly Install and Configure MySQL8

doc/releasenotes/13_0_0_summary.md, go/vt/vtgate/buffer/buffer_test.go, go/vt/vtgate/buffer/flags.go, go/vt/vtgate/buffer/flags_test.go, go/vt/vtgate/gateway.go, go/vt/vtgate/sandbox_test.go
Signed-off-by: FancyFane <fane@planetscale.com>
The current buffer implementation leads to inconsistent behavior during testing. This pull request purposes changing the default buffering implementation after seeing these inconsistencies resolved with the `keyspace_events` implementation. 
Fixes #9359 #9346 #9356 
n/a
=> Change default buffer implementation #9359

go.mod, go.sum, go/test/endtoend/vreplication/resharding_workflows_v2_test.go, go/test/endtoend/vreplication/vreplication_test.go, go/vt/wrangler/materializer.go
When a sharded table with autoincrement  is moved using MoveTables to an unsharded keyspace, currently the related sequence information is not carried over into the target (unsharded) keyspace's vschema.
This PR fixes that by copying over the sequence info from the source schema for that table. This is verified by adding this use-case to the v2 end-to-end test.
#9002
=> MoveTables: update vschema while moving tables with autoincrement from sharded to unsharded

.github/workflows/cluster_endtoend_vreplication_basic.yml, .github/workflows/cluster_endtoend_vreplication_v2.yml, test/ci_workflow_gen.go, test/templates/cluster_endtoend_test_docker.tpl
This PR is an attempt to make a couple of flaky vreplication end to end tests less flaky. 
The causes of the flakiness were the same old issues related to mysql not starting or ports not being available and it occurs at different points, like:
```
2021-12-14T12:00:51.2859900Z I1214 11:55:35.775352   18070 vtctlclient_process.go:183] Executing vtctlclient with command: vtctlclient -server localhost:15999 CreateShard customer/-60
2021-12-14T12:00:51.2861868Z I1214 11:55:35.790850   18070 cluster.go:306] Adding Primary tablet
2021-12-14T12:00:51.2863948Z I1214 11:55:35.790923   18070 mysqlctl_process.go:124] Starting mysqlctl with command: [mysqlctl -log_dir /home/runner/work/vitess/vitess/vtdataroot/vt_2025146392/vreple2e_956177/tmp -tablet_uid 1000 -mysql_port 17306 init -init_db_sql_file …
```
=> Move two flaky vreplication e2e tests test to docker

go/test/endtoend/onlineddl/revert/onlineddl_revert_test.go, go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go
Small but useful change: add a new column in `schema_migrations` table, called `reverted_uuid`. For most migrations the value will be empty; but for `REVERT` migrations, this will indicate the UUID of the migration being reverted. We also index this column.
This makes it easier to find: "given a migration UUID has there been a REVERT on this migration? Was it successful? Have there perhaps been multiple attempts at revert? Has any attempt been successful?"
I expect these type of questions to be needed when managing reverted migrations.
endtoend tests added to validate populated column value.
#6926
=> Online DDL: add formal 'reverted_uuid' column

java/pom.xml
This is a backport of #9387 into release-10.
=> [10.0] build(deps): bump log4j-core from 2.15.0 to 2.16.0 in /java 

java/pom.xml
This is a backport of #9387 into release-11.
=> [11.0] build(deps): bump log4j-core from 2.15.0 to 2.16.0 in /java

java/pom.xml
This is a backport of #9387 into release-12.
=> [12.0] build(deps): bump log4j-core from 2.15.0 to 2.16.0 in /java

examples/operator/101_initial_cluster.yaml, examples/operator/201_customer_tablets.yaml, examples/operator/302_new_shards.yaml, examples/operator/306_down_shard_0.yaml, examples/operator/vtorc_example.yaml
This pull request is changing the docker images used in the operator example. They will now use `v10.0.4` (latest patch release, to be released soon). Previous versions of `v10` contained (CVE-2021-44228
& CVE-2021-45046) which will be fixed in `v10.0.4`.
=> [10.0] change operator example to use v10.0.4 docker images

examples/operator/101_initial_cluster.yaml, examples/operator/201_customer_tablets.yaml, examples/operator/302_new_shards.yaml, examples/operator/306_down_shard_0.yaml, examples/operator/vtorc_example.yaml
This pull request is changing the docker images used in the operator example. They will now use `v11.0.3` (latest patch release, to be released soon). Previous versions of `v11` contained (CVE-2021-44228
& CVE-2021-45046) which will be fixed in `v11.0.3`.
=> [11.0] change operator example to use v11.0.3 docker images

doc/releasenotes/11_0_0_release_notes.md, doc/releasenotes/11_0_1_release_notes.md, doc/releasenotes/11_0_2_release_notes.md, doc/releasenotes/11_0_2_summary.md, doc/releasenotes/11_0_3_release_notes.md, doc/releasenotes/11_0_3_summary.md
This pull request updates the release notes of the 11.0.*  releases by adding the Log4j vulnerability to the list of known issues, along with #9174.
=> Updated the 11_0 release documents with latest known issues

doc/releasenotes/12_0_0_release_notes.md, doc/releasenotes/12_0_0_summary.md, doc/releasenotes/12_0_1_release_notes.md, doc/releasenotes/12_0_1_summary.md
This pull request updates the release notes of the 12.0.0 and 12.0.1 releases by adding the Log4j vulnerability to the list of known issues, along with #9174 for 12.0.0 since a fix is available in >= 12.0.1.
=> Updated the 12_0 release documents with latest known issues

doc/releasenotes/12_0_0_release_notes.md, doc/releasenotes/12_0_0_summary.md, doc/releasenotes/12_0_1_release_notes.md, doc/releasenotes/12_0_1_summary.md
This pull request updates the release notes of the `12.0.0` and `12.0.1` releases by adding the Log4j vulnerability to the list of known issues, along with https://github.com/vitessio/vitess/issues/9174 for `12.0.0` since a fix is available in `>= 12.0.1`.
=> [12.0] Updated the 12_0 release documents with latest known issues

go/vt/vtctl/vtctl.go
Missed one in #9179
This is a breaking change.
#8838
Anyone using the old flag should change their scripts to use the new flag.
=> vtctl: delete deprecated flag

go/vt/topotools/utils.go
=> replace master with primary

go.mod, go.sum
This pull request upgrades the `go-proxyproto` package to version `v0.6.1` (https://github.com/pires/go-proxyproto/releases/tag/v0.6.1). A couple of vulnerabilities were found in versions `< 0.6.0`:
- CVE-2021-23409
- CVE-2021-23351
=> Upgrade `go-proxyproto` to `v0.6.1` to fix vulnerabilities

go/vt/vtgate/engine/vindex_func.go, go/vt/vtgate/engine/vindex_func_test.go, go/vt/vtgate/planbuilder/abstract/vindex.go, go/vt/vtgate/planbuilder/filtering.go, go/vt/vtgate/planbuilder/project.go, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
=> Add list support to vindex functions

go/vt/vtgate/engine/vindex_func.go
Trivial follow-up to https://github.com/vitessio/vitess/pull/9426. I didn't notice the double import (because I had used vtrpc vs. vtrpcpb in one spot) before it was merged. 
https://github.com/vitessio/vitess/pull/9426
=> Trivial: remove redundant import

go/vt/vtgate/plugin_mysql_server.go
Occasionally we will see CI test failures due to a `vtgate` segfaulting during shutdown, e.g.:
```
vitess.io/vitess/go/event.(*Hooks).Fire.func1(0xc000b2e0c0)
vitess.io/vitess/go/vt/vtgate/plugin_mysql_server.go:540 +0x3f
vitess.io/vitess/go/vt/vtgate.rollbackAtShutdown()
vitess.io/vitess/go/vt/vtgate/plugin_mysql_server.go:534 +0x48
vitess.io/vitess/go/vt/vtgate.rollbackAtShutdown.func1()
goroutine 408 [running]:
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xef5b08]
panic: runtime error: invalid memory address or nil pointer dereference
I1222 12:37:17.231378       1 servenv.go:199] OnClose hooks timed out
I1222 12:37:17.231330       1 servenv.go:183] Firing OnClose hooks and waiting up to 1ns for them
I1222 12:37:17.231308       1 run.go:71] Shutting down gracefully
``` …
=> Handle race condition during vtgate shutdown

go/vt/wrangler/workflow.go, go/vt/wrangler/workflow_test.go
Currently SwitchTraffic requires TabletTypes to be all lowercase. This PR makes it case-insensitive.
=> Fixed case-sensitive TabletType in SwitchTraffic

go/vt/vtctl/vtctl.go, go/vt/wrangler/stream_migrater_test.go, go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/traffic_switcher_test.go, go/vt/wrangler/workflow.go
Once you've [completed a MoveTables](https://vitess.io/docs/13.0/reference/vreplication/complete/) e.g., you may want to keep the routing rules around for a while as you find and fix any application code that is still using the old keyspace. 
This adds a `-keep_routing_rules` flag to the `vtctl MoveTables {Complete,Cancel}` commands for the v2 workflows to support this use case.
=> Add flag to keep routing rules in v2 vrepl workflows

go/test/endtoend/vtgate/gen4/gen4_test.go, go/test/endtoend/vtgate/gen4/main_test.go, go/vt/vtgate/engine/insert.go, go/vt/vtgate/engine/insert_test.go, go/vt/vtgate/engine/route_test.go, go/vt/vtgate/executor_framework_test.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/planbuilder/dml.go, go/vt/vtgate/planbuilder/insert.go, go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/routetree.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt, go/vt/vtgate/vindexes/region_experimental.go, go/vt/vtgate/vindexes/region_experimental_test.go, go/vt/vtgate/vindexes/region_json.go, go/vt/vtgate/vindexes/vindex.go, go/vt/vtgate/vindexes/vschema.go, go/vt/vtgate/vindexes/vschema_test.go
This PR adds a new function to MultiColumn Vindex interface to provide information that the multi-column vindex supports partial vindex selection (i.e. fanout to subset of shards if part of the column values are provided).
Eg.
```
cola, colb, colc forms a multicolumn vindex
then providing values for cola or (cola and colb) the vindex should be able to fan out the query to subset of shards.
```
The user does not have to provide any additional information in the VSchema. Based on the table that uses multi-column vindex which allows partial vindex column selection, Vitess will handle it internally and the planner will be able to utilize those columns for vindex selection.
This PR also modifies the existing `region_experimental` vindex to handle partial column values i.e. if only `region_id` …
=> Multicolumn partial vindex selection

go/test/endtoend/vtgate/unsharded/main_test.go, go/vt/vttablet/tabletserver/tabletserver.go
This PR fixes a misleading error mapping for row limit error.
=> Fix misleading error mapping for row limit error

go/cmd/vtbackup/vtbackup.go, go/vt/discovery/topology_watcher.go, go/vt/mysqlctl/reparent.go, go/vt/vtctl/grpcvtctldserver/endtoend/init_shard_primary_test.go, go/vt/vtgate/executor_stream_test.go, go/vt/vttablet/tabletmanager/rpc_replication.go, go/vt/wrangler/testlib/emergency_reparent_shard_test.go, go/vt/wrangler/testlib/planned_reparent_shard_test.go
Part 1 of renaming master_alias to primary_alias
#8619
=> reparent_journal: add backwards compatible alter statement

Makefile, docker/k8s/Dockerfile, docker/lite/Dockerfile.mysql57, tools/make-release-packages.sh
Signed-off-by: Adam Jedro <adamjedro@gmail.com>
This adds `vtadmin` binary (server) to the release package and Docker images. I would like to run `vtadmin` for qa/prod clusters but unless binary is in the official package I am not allowed to do it.
=> Add vtadmin binary to release and Docker images

go/test/endtoend/vtgate/gen4/gen4_test.go, go/test/endtoend/vtgate/gen4/main_test.go, go/vt/vtgate/executor_framework_test.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/executor_test.go, go/vt/vtgate/vindexes/binary.go, go/vt/vtgate/vindexes/binarymd5.go, go/vt/vtgate/vindexes/cfc.go, go/vt/vtgate/vindexes/cfc_test.go, go/vt/vtgate/vindexes/hash.go, go/vt/vtgate/vindexes/multicol.go, go/vt/vtgate/vindexes/multicol_test.go, go/vt/vtgate/vindexes/numeric.go, go/vt/vtgate/vindexes/numeric_static_map.go, go/vt/vtgate/vindexes/reverse_bits.go, go/vt/vtgate/vindexes/unicodeloosemd5.go, go/vt/vtgate/vindexes/unicodeloosexxhash.go, go/vt/vtgate/vindexes/vindex.go, go/vt/vtgate/vindexes/xxhash.go
This PR adds a new generic MultiColumn Vindex that can be used only as a primary vindex.
This Vindex takes in 3 inputs
1. `column_count` - the number of columns that would be provided for using the vindex.
2. `column_vindex` - hashing function each column will use to provide hash value for that column
3. `column_bytes` - bytes to be used from each column's hash value after applying hashing function on it to produce keyspace id.
Usage in VSchema:
```json
"vindexes": {
"multicol_vdx": {
"type": "multicol",
"params": {
"column_count": "3",
"column_bytes": "1,3,4",
"column_vindex": "hash,binary,unicode_loose_xxhash"
}
}
}
```
```json
"tables": {
"multicol_tbl": {
"column_vindexes": [
{
"columns": ["cola","colb","colc"],
"name": "multicol_vdx"
}
]
}
}
```
`column_count` is the mandatory …
=> Subsharding vindex

java/pom.xml
This is a backport of #9423 to upgrade `log4j` to version `2.17.1`.
=> [12.0] build(deps): bump log4j-api from 2.16.0 to 2.17.1 in /java

java/pom.xml
This is a backport of #9423 to upgrade `log4j` to version `2.17.1`.
=> [11.0] build(deps): bump log4j-api from 2.16.0 to 2.17.1 in /java

java/pom.xml
This is a backport of #9423 to upgrade `log4j` to version `2.17.1`.
=> [10.0] build(deps): bump log4j-api from 2.16.0 to 2.17.1 in /java

go/test/endtoend/vreplication/cluster.go, go/test/endtoend/vreplication/helper.go, go/test/endtoend/vreplication/materialize_test.go, go/vt/vttablet/tabletmanager/vreplication/replicator_plan_test.go, go/vt/vttablet/tabletmanager/vreplication/table_plan_builder.go, go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go, test/config.json
This PR fixes a bug where a column cannot be referred to multiple times in a Filter. There was an incorrect optimization in vstreamer where a column was being ignored while creating the source query if it was already seen.
So a materialize `source_expression` like `select id, val, ts, dayofmonth(ts) as day from mat` would fail since `ts` was mentioned twice in the select list. 
In addition, a new test has been added that confirms that Materialize filters can contain user-defined functions: we can define a `source_expression` like `select id, val, ts, customFunc1(id, val) as x from mat`. This is more an observation rather than a new feature, since, to our query parser, a custom function looks like just a pre-defined mysql function.  It is being stated explicitly since we had earlier …
=> Allow source columns to be specified multiple times in a vreplication rule filter

go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go, go/test/endtoend/onlineddl/vtctlutil.go, go/vt/schemamanager/tablet_executor.go
Followup to #9303, which added support for `ALTER VITESS_MIGRATION` in `vtctl ApplySchema`. 
Unfortunately, on sharded keyspaces an internal validation fails the statement. This PR fixes the validation to allow `ALTER VITESS_MIGRATION` even in sharded (multi-shard) environments.
- Tracking: #6926
=> vtctl: Allow ALTER VITESS_MIGRATION commands in sharded environment

go/vt/orchestrator/ssl/ssl.go, go/vt/topo/zk2topo/zk_conn.go
This call tries to setup a single name for the validation, but this call is deprecated as the built in logic now iterates through the available certificates and picks the right one.
There's no reason to keep this call because of the improved logic in Go itself, so it's best to remove it.
=> Remove deprecated call for TLS config

go/vt/sqlparser/parse_test.go, go/vt/sqlparser/token.go, go/vt/sqlparser/token_test.go
This PR fixes the tokeniser to return an `ID` token when we see letters after numbers instead of returning errors, since this is closer to MySQL. `3t2` is a valid `ID` and should be parsed correctly. It can be a table name too. This means that the following query is valid and should work correctly in Vitess - 
```sql
create table 3t2 (c1 bigint not null, c2 text, primary key(c1))
```
Even after the changes the following query does not work with Vitess - 
```sql
create table 2t.3t2 (c1 bigint not null, c2 text, primary key(c1))
```
This is a valid MySQL query but does not yet work with Vitess. The problem is that the tokenizer takes `.3` as a single token which causes parsing error. We should instead be using `.` as a separate token and then `3t2` as an identifier. This highlights another …
=> Fix parsing table name starting with a number.

.github/docker/cluster_test_14/Dockerfile, .github/docker/cluster_test_vtorc/Dockerfile, .github/workflows/cluster_endtoend_14.yml, .github/workflows/cluster_endtoend_vtorc.yml, test/ci_workflow_gen.go
`reparent` and `vtorc` tests have been flaky recently. This PR moves them to the self-hosted runners so that the flakiness can be traced and reproduced.
=> Move reparent and vtorc tests to self-hosted runners

go/vt/orchestrator/ssl/ssl.go, go/vt/vttls/vttls.go
This was done long ago when upstream Go had no mitigations in place for CBC oracle attacks. For the legacy ciphers they do now, so having these different definitions isn't really suited anymore.
In general, Go has a good upstream TLS configuration so we should modify / configure as little as possible so I think it's better to remove this customization.
It has cause some issues like https://github.com/vitessio/vitess/pull/9399 before removing it also prevents similar issues in the future if Go improves cipher support.
=> Remove SSL cipher customization

go/vt/vtgate/executor_stream_test.go, go/vt/vtgate/executor_vstream_test.go
The vtgate unit test TestVStreamSQLUnsharded is failing with races detected. It is not clear whether the issue is with the underlying functionality or with the test setup. Since it is blocking other PRs, let's skip it  for now (in any case the functionality it tests is experimental and hence not critical).
=> Temporarily Skip 'vstream from' test 

go/vt/vtgate/planbuilder/abstract/join.go, go/vt/vtgate/planbuilder/fallback_planner.go, go/vt/vtgate/planbuilder/fallback_planner_test.go, go/vt/vtgate/planbuilder/gen4_planner.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt, go/vt/vtgate/semantics/analyzer.go, go/vt/vtgate/semantics/analyzer_test.go, go/vt/vtgate/semantics/semantic_state.go
A minor planner fix
When using the `Gen4fallback` planner, we were not protecting the AST from changes from the Gen4 planner, which lead to the V3 planner getting an already updated AST and failing
=> Gen4Fallback bug fix

doc/releasenotes/11_0_0_release_notes.md, doc/releasenotes/11_0_1_release_notes.md, doc/releasenotes/11_0_2_release_notes.md, doc/releasenotes/11_0_2_summary.md, doc/releasenotes/11_0_3_release_notes.md, doc/releasenotes/11_0_3_summary.md
This pull request updates the release notes of the 11.0.* releases by adding the Log4j vulnerability to the list of known issues, along with #9174.
=> [11.0] Updated the 11_0 release documents with latest known issues

.github/workflows/upgrade_downgrade_test_query_serving.yml
Following the release of the new automation around upgrade downgrade testing, @deepthi observed a bug in the CI. The bug appears when a commit onto a pull request created from a `vitessio/vitess` branch (instead of a remote branch). Pushing a commit on a `vitessio/vitess` branch triggers a `push` event on GitHub Actions. Since the Actions is started by a `push` and not by a `pull_request` event, previously the `get_upgrade_downgrade_label.Check Label` step would fail since there are no labels attached to push/commit.
To fix this issue, an if statement is added to `get_upgrade_downgrade_label.Check Label` (later renamed to `Check Label for PR`) to enable the step only if the event triggering the workflow is `pull_request`. 
- This fix should be ported to …
=> Fix how `Check Label` is run during upgrade downgrade testing

doc/releasenotes/11_0_0_release_notes.md, doc/releasenotes/11_0_1_release_notes.md, doc/releasenotes/11_0_2_release_notes.md, doc/releasenotes/11_0_2_summary.md, doc/releasenotes/11_0_3_release_notes.md, doc/releasenotes/11_0_3_summary.md, doc/releasenotes/11_0_4_release_notes.md, doc/releasenotes/11_0_4_summary.md, doc/releasenotes/12_0_0_release_notes.md, doc/releasenotes/12_0_0_summary.md, doc/releasenotes/12_0_1_release_notes.md, doc/releasenotes/12_0_1_summary.md, doc/releasenotes/12_0_2_release_notes.md, doc/releasenotes/12_0_2_summary.md, doc/releasenotes/12_0_3_release_notes.md, doc/releasenotes/12_0_3_summary.md
This pull request follows the release of `v11.0.4` and `v12.0.3`. The release notes related to these releases are added to `main` through this pull request.
`v10.0.5`'s notes are not included in this pull request. An older pull request (https://github.com/vitessio/vitess/pull/9472) is already taking care of updating all `v10.0.*` release notes on main.
All the previous release notes for `11.0` and `12.0` were updated through this pull request to mirror what's written on both the releases page and the corresponding release branches.
=> Addition of v11.0.4 and v12.0.3 release notes to main

go/vt/vtctl/reparentutil/emergency_reparenter.go, go/vt/vtctl/reparentutil/emergency_reparenter_test.go
The error seen in #9502 is traced to the context passed from `reparentReplicas` being cancelled. We exit out of `EmergencyReparentShard` just as we know that 1 replica succeeded in setting the primary correctly, but the other replicas might still be in flight when ERS ends. So we should not be cancelling their contexts until they are finished or the timeout has expired. This PR fixes this issue.
- Fixes #9502
=> Fix for context cancellation in ERS

go/vt/vttablet/grpctabletconn/conn.go
In the previous implementation, the last iteration of the for loop
leaves behind an object to get GC'd since it never gets released back to
the pool when the function returns.
Also should be a minor optimization by re-using the VStreamRowsResponse
rather than returning it to the pool each iteration.
=> vttablet: Better use of vtprotobuf memory pool

go/mysql/collations/cached_size.go, go/tools/sizegen/sizegen.go, go/vt/vtgate/engine/cached_size.go, go/vt/vtgate/vindexes/cached_size.go
We never got around to implementing support for Array types in `sizegen`, so the size of the wildcard struct, which kept a pointer to an array inside, was slightly off.
cc @systay
=> sizegen: add support for arrays

go/vt/vttablet/tabletserver/connpool/pool.go
Stats should be available at the tablet's `/debug/vars` page
Follow-up to: https://github.com/vitessio/vitess/pull/9484
=> Add stats to track when a pool's waiter queue is full

go/test/endtoend/cluster/mysqlctl_process.go
It was noticed that the cluster 14 tests were a little flaky and on further investigation, it turned out that the reason for this flakiness was MySQL not shutting down properly and using the full 5 minute wait time given to it. On further investigation and looking at logs with @mattlord, it turned out that the reason that MySQL was hanging was because it was waiting for a Semi-sync ack for an internal Vitess command (guess) even though the socket file had disappeared and all the connections to the replicas had been closed. We are still unsure whether this is a MySQL bug or some configuration issue.
We discussed 3 possible solutions for fixing the CI - 
1. reduce the wait_time for the semi-sync acks by reducing the value for `rpl_semi_sync_master_timeout`. But this parameter is only …
=> Fix flakiness in reparent tests

go/vt/topo/topoproto/tablet.go, go/vt/vttablet/tabletmanager/vreplication/controller_test.go, go/vt/vttablet/tabletmanager/vreplication/engine.go, go/vt/vttablet/tabletmanager/vreplication/engine_test.go
When people update to a new version, any instances of "master" in the vreplication table should be changed to "primary".
=> Fixed legacy vreplication data that may be using master tablet type

go/vt/vtgate/planbuilder/derivedtree.go, go/vt/vtgate/planbuilder/route_planning.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt, go/vt/vtgate/planbuilder/testdata/tpch_cases.txt
This PR fixes a bug in Gen4 planner for join query pushing output column on left-hand side.
=> Fix: push output columns on lhs than on jointree, handle derived table table push output column correctly

doc/releasenotes/13_0_0_summary.md, go/vt/vtgate/gateway.go, go/vt/vtgate/tabletgateway.go
VTGate's `gateway_implementation` flag is now deprecated, and any value provided is ignored. `tabletgateway` is now the only supported implementation.
#9218 
Scripts used to run `vtgate` will need to be updated to drop this flag. It will be removed in a future release (14.0)
=> Deprecate and ignore `gateway_implementation` flag to vtgate.

go/vt/vtgate/engine/delete.go, go/vt/vtgate/engine/delete_test.go, go/vt/vtgate/engine/dml.go, go/vt/vtgate/engine/route.go, go/vt/vtgate/engine/update.go, go/vt/vtgate/engine/update_test.go, go/vt/vtgate/planbuilder/delete.go, go/vt/vtgate/planbuilder/dml.go, go/vt/vtgate/planbuilder/testdata/dml_cases.txt, go/vt/vtgate/planbuilder/testdata/schema_test.json, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt, go/vt/vtgate/planbuilder/update.go
This PR adds support for multi-column vindex selection and execution in update and delete queries.
- #3481
=> Multicolumn vindex support in update and delete queries

go/vt/vtgate/evalengine/comparisons.go, go/vt/vtgate/evalengine/convert_test.go, go/vt/vtgate/evalengine/eval_result.go, go/vt/vtgate/evalengine/integration/comparison_test.go, go/vt/vtgate/evalengine/integration/fuzz_test.go, go/vt/vtgate/evalengine/integration/testdata/mysql_golden_1637776444.json, go/vt/vtgate/evalengine/integration/testdata/mysql_golden_1642153591.json, go/vt/vtgate/evalengine/integration/testdata/mysql_golden_1642436036.json, go/vt/vtgate/evalengine/integration/testdata/mysql_golden_1642499325.json, go/vt/vtgate/simplifier/expression_simplifier.go
With this last set of fixes, I can run a random expression fuzzer for 1min+ locally and not find any mismatches between the evaluation results of MySQL and ours. #9153 
I am 100% sure there are still corner cases that we're not handling properly, but we should be wildly more compatible than we were before I started this refactoring project, and I believe the `evalengine` is stable enough now to ship in the next version of Vitess and being enabled by default.
cc @deepthi @systay
=> evalengine: some last fixes

go/mysql/conn_flaky_test.go, go/mysql/fakesqldb/server.go, go/mysql/mysql_fuzzer.go, go/mysql/server.go, go/mysql/server_flaky_test.go, go/vt/vtgate/plugin_mysql_server.go, go/vt/vtgate/plugin_mysql_server_test.go
This is is useful to determine the intermediate state after
NewConnection and before ConnectionClosed, basically for a handler to
know if authentication, etc, were successful. NewConnection is way too
soon in the process to determine if the connection got fully
established.
Signed-off-by: Matt Robenolt <matt@ydekproductions.com>
=> mysql: Add ConnectionReady callback to Handler interface

go/test/endtoend/reparent/newfeaturetest/reparent_test.go, go/vt/vtctl/reparentutil/emergency_reparenter.go, go/vt/vtctl/reparentutil/emergency_reparenter_test.go, go/vt/vttablet/tabletmanager/rpc_replication.go
This PR adds support in `EmergencyReparentShard` to be used for initializing the shard too instead of `InitShardPrimary` or `PlannedReparentShard`. There were 2 fixes that were needed for the end to end test to work -
1. In `EmergencyReparentShard` we should be calling `InitPrimary` instead of `PromoteReplica` the first time around so that the initial database and tables are created before semi-sync settings are fixed. Otherwise the call just blocks and times out. This change is very similar to the one made in `PlannedReparentShard` in #9276. We are using the same criterion of `PrimaryAlias` in `ShardInfo` being nil to know that this is the first time a primary is being setup for the shard.
2. There is a bug that I found in `InitPrimary` RPC. In case we call `DemotePrimary` on one of the …
=> Fix Ers to be used for initialization as well

examples/are-you-alive/pkg/client/client.go, examples/compose/fix_replication.sh, go/test/endtoend/cluster/cluster_process.go, go/vt/vttablet/grpctabletconn/conn.go, go/vt/vttablet/tabletconntest/fakequeryservice.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/tabletenv/config.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/worker/executor.go, go/vt/worker/worker.go
Delete code that was kept around until we passed v12.0
A few other miscellaneous fixes
#7113
=> naming: delete old code that was needed for version compatibility

Makefile
`GOOS=linux GOARCH=arm64 make cross-build` currently fails on amd64 (linux), because we invoke the rice binary, which will be built using arm64, and the exec will fail.
Fixes #9539
=> Allow cross-build to work for cross-architecture too (e.g. arm64 on amd64)

go/vt/vtgate/planbuilder/gen4_planner.go, go/vt/vtgate/planbuilder/simplifier_test.go, go/vt/vtgate/planbuilder/single_sharded_shortcut.go, go/vt/vtgate/planbuilder/testdata/ddl_cases.txt, go/vt/vtgate/planbuilder/testdata/filter_cases.txt, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/planbuilder/testdata/onecase.txt, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/semantics/analyzer_test.go, go/vt/vtgate/semantics/semantic_state.go
During semantic analysis, which happens very early in the query planning process, we have enough information to know that the query is only addressing a single, unsharded keyspace.
In this situation, we can just clean up the query minimally and then send it to the tablet. This way any shortcomings in the rest of the planner does not have to impact these type of queries.
Fixes #9509
=> Faster and safer unsharded query planning

go/test/endtoend/vtorc/general/main_test.go, go/test/endtoend/vtorc/gracefultakeover/main_test.go, go/test/endtoend/vtorc/primaryfailure/main_test.go
In the vtorc test suite, if the cluster isn't setup properly and errors out, we should not be calling teardown on it since it leads to panic. This prevents the actual error to be logged. This PR fixes this issue.
=> Fix panic in vtorc tests

go/mysql/conn_flaky_test.go, go/mysql/fakesqldb/server.go, go/mysql/mysql_fuzzer.go, go/mysql/server.go, go/mysql/server_flaky_test.go, go/vt/vtgate/plugin_mysql_server.go, go/vt/vtgate/plugin_mysql_server_test.go
This follows the pattern of how a gRPC service is generated via
protobuf.
The idea being, you embed the mysql.UnimplementedHandler struct into
your Handler implementation, and this gives you all of the optional
callbacks without needing to explicitly declare them within your
Handler.
This also allows your Handler to be more forwards compatible with adding
new methods that you may not need or care about.
In this PR, it gives us an opportunity also to clean up a bunch of the
test cases that stub in no-op implementations.
As a note, it'd be nice to have this also stub in _all_ of the methods
and return errors, but that might be a harder sell since it's sorta
required to implement them all or you're going to have a Bad Time. Maybe
if the server.go code would be a little better at handling it, …
=> mysql: Add UnimplementedHandler struct

go/test/endtoend/vtgate/misc_test.go, go/test/endtoend/vtgate/mysql80/derived/derived_test.go, go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/test/endtoend/vtgate/queries/informationschema/informationschema_test.go, go/vt/sqlparser/ast_funcs.go, go/vt/sqlparser/comments.go, go/vt/vtgate/planbuilder/builder.go, go/vt/vtgate/planbuilder/fallback_planner.go, go/vt/vtgate/planbuilder/fallback_planner_test.go, go/vt/vtgate/planbuilder/gen4_compare_v3_planner.go, go/vt/vtgate/planbuilder/gen4_planner.go, go/vt/vtgate/planbuilder/physical/route_planning.go, go/vt/vtgate/planbuilder/plancontext/planning_context.go, go/vt/vtgate/planbuilder/plancontext/vschema.go, go/vt/vtgate/planbuilder/select.go, go/vt/vtgate/planbuilder/testdata/wireup_cases.txt, go/vt/vtgate/planbuilder/union.go, go/vt/vtgate/vcursor_impl.go
Two minor planner improvements - first a query hint that allow users to select the planner to use. Sometimes we want to be able to specify a different planner than the one the vtgate is configured with, and this query hint enables this.
```sql
select /*vt+ PLANNER=gen4 */ * from commerce;
```
Also re-introduces the left-to-right planner which mimics `straight join` on mysql, which was lost during the refactor of gen4 this week.
=> Planner improvements

go/cmd/vttestserver/main.go, go/mysql/client.go, go/mysql/collations/8bit.go, go/mysql/collations/env.go, go/mysql/conn.go, go/mysql/conn_params.go, go/mysql/constants.go, go/mysql/endtoend/query_test.go, go/mysql/fakesqldb/server.go, go/mysql/schema.go, go/mysql/server.go, go/test/endtoend/vtgate/reservedconn/main_test.go, go/test/endtoend/vtgate/reservedconn/sysvar_test.go, go/vt/dbconfigs/dbconfigs.go, go/vt/dbconfigs/dbconfigs_test.go, go/vt/mysqlctl/mysqld.go, go/vt/vtgate/evalengine/convert.go, go/vt/vtgate/executor.go, go/vt/vtgate/planbuilder/show.go, go/vt/vtgate/vcursor_impl.go, go/vt/vttablet/endtoend/connkilling/main_test.go, go/vt/vttablet/endtoend/main_test.go, go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_init_test.go, go/vt/vttablet/tabletserver/vstreamer/testenv/testenv.go, go/vt/vttest/local_cluster.go, go/vt/vttest/mysqlctl.go, go/vt/vttest/vtprocess.go
OK, after a lot of testing I have what I believe is a working solution for the weird collation behavior we've been seeing in Vitess clusters. What I figured out is that the workaround that we implemented in our MySQL connection code to support collations >255 was not really working. As a reminder, when connecting to a MySQL server, a handshake is performed between client and server to agree on a "connection charset" (as defined in the MySQL documentation). Now, two critical facts about this: the wire protocol only has 1 byte for this charset, so it's not possible to use charsets higher than 255; and what the documentation calls "charset" is in fact the ID of a full collation, that can very well go above 255.
This PR hence does the following things:
1. It removes the `db_collation` flag …
=> mysql: use UTF8mb4 as consistent connection charset

doc/releasenotes/13_0_0_summary.md, go/vt/vtctl/vtctl.go
`vtctl OnlineDDL show ...` command now exports all column of `schema_mgirations` table, instead of selected columns. This is to bring `OnlineDDL show` on par with `SHOW VITESS_MIGRATIONS LIKE ...` output.
Also, the command now supports `-json` flag.
Examples:
```shell
$ vtctlclient OnlineDDL commerce show 9d078a8e_7756_11ec_a656_0a43f95f28a3
+------------------+----+--------------------------------------+----------+-------+--------------+-------------+----------------------------------------+----------+---------+---------------------+---------------------+---------------------+---------------------+---------------------+---------------------+---------------------+------------------+----------+-------------------------------------------------------------+---------+------------------+------- …
```
=> vtctl OnlineDDL show: export all columns, support -json

go/test/endtoend/vtgate/gen4/gen4_test.go, go/vt/vtgate/engine/delete.go, go/vt/vtgate/engine/delete_test.go, go/vt/vtgate/engine/dml.go, go/vt/vtgate/engine/update.go, go/vt/vtgate/engine/update_test.go, go/vt/vtgate/planbuilder/dml.go, go/vt/vtgate/planbuilder/testdata/dml_cases.txt, go/vt/vtgate/planbuilder/testdata/schema_test.json, go/vt/vtgate/vindexes/consistent_lookup.go
This PR adds supported for extracting routing information from update/delete query and using non-unique lookup vindex if available and having lowest cost among other options.
=> non-unique vindex routing in update and delete query

go/vt/vtgate/planbuilder/testdata/dml_cases.txt
CI is currently failing with
```
--- FAIL: TestPlan (0.12s)
--- FAIL: TestPlan/dml_cases.txt (0.01s)
--- FAIL: TestPlan/dml_cases.txt/2913_V3:_#_update_with_routing_using_non-unique_lookup_vindex_ (0.00s)
plan_test.go:603: V3 - dml_cases.txt:2913
Diff:
  strings.Join({
  	... // 302 identical bytes
  	"lse,\n    \"Query\": \"update multicol_tbl set x = 42 where `name` =",
  	" 'foo'\",\n    \"Table\": \"multicol_tbl\",\n    \"Values\": [\n      \"VAR",
- 	"BINARY",
+ 	"CHAR",
  	"(\\\"foo\\\")\"\n    ],\n    \"Vindex\": \"name_muticoltbl_map\"\n  }\n}",
  }, "")
[{
"QueryType": "UPDATE",
"Original": "update multicol_tbl set x = 42 where name = 'foo'",
"OperatorType": "Update",
"Variant": "Equal",
"Keyspace": {
},
"TargetTabletType": …
```
=> tests: fix CI failure

examples/legacy_local/scripts/vtctld-up.sh, examples/local/101_initial_cluster.sh, examples/local/scripts/vtctld-up.sh
A new flag `-durability_policy` for vtctld was introduced and it should now be provided in the local examples. This PR accomplishes that change of adding the new flag to vtctld-up.sh in all the examples which are using semi-sync. 
We also start using PlannedReparentShard for cluster initialisation in the example.
The changes to the scripts have been tested locally by inserting data, reading it, performing failovers (both planned and emergency) and inserting and reading data again. I have also checked the logs and verified that everything is in order.
- #9533
=> Add durability flag in local examples

doc/releasenotes/13_0_0_summary.md
The only notable change I have for the Vitess 13 release. :) Happy to expand if this isn't verbose enough.
Mentions the node upgrade in https://github.com/vitessio/vitess/pull/9136. 
N/A
=> Update 13.0 release notes to mention vtadmin-web node LTS requirement

go/cmd/vtctl/vtctl.go, go/test/endtoend/cluster/cluster_util.go, go/test/endtoend/cluster/vtctl_process.go
This PR adds a warning to the vtctl binary stating that it should only be used for VDiff workflows and vtctld with vtctlclient should be preferred for everything else.
After this change running the vtctl binary looks like this - 
```sh
~/vitess: vtctl ListAllTablets
W0129 06:00:35.034992   59439 vtctl.go:88] WARNING: vtctl should only be used for VDiff workflows. Consider using vtctldclient for all other commands.
F0129 06:00:35.035721   59439 server.go:224] topo_global_server_address must be configured
```
- #9529
=> Add warning to vtctl binary

go/netutil/conn_test.go, go/test/fuzzing/tablet_manager_fuzzer.go, go/test/fuzzing/vtctl_fuzzer.go, go/test/fuzzing/vttablet_fuzzer.go, go/vt/binlog/grpcbinlogplayer/player_test.go, go/vt/grpcoptionaltls/server_test.go, go/vt/servenv/exporter_test.go, go/vt/throttler/grpcthrottlerclient/grpcthrottlerclient_test.go, go/vt/tlstest/tlstest_test.go, go/vt/vitessdriver/driver_test.go, go/vt/vtadmin/vtctldclient/proxy_test.go, go/vt/vtctl/grpcvtctlclient/client_test.go, go/vt/vtgate/grpc_discovery_test.go, go/vt/vtgate/grpcvtgateconn/conn_rpc_test.go, go/vt/vtgate/grpcvtgateconn/fuzz_flaky_test.go, go/vt/vttablet/endtoend/framework/server.go, go/vt/vttablet/grpctabletconn/conn_benchmark_test.go, go/vt/vttablet/grpctabletconn/conn_test.go, go/vt/vttablet/grpctmserver/server_test.go, go/vt/worker/grpcvtworkerclient/client_test.go, go/vt/workflow/long_polling_test.go, go/vt/workflow/websocket_test.go, go/vt/wrangler/testlib/throttler_test.go, go/vt/wrangler/testlib/vtctl_pipe.go
Running the unit tests on macOS produces a bunch of popups asking whether .test executables should be allowed to accept incoming network connections.
It is annoying because they steal the focus, and it is not desirable to turn off the firewall to avoid them.
This PR attempts to fix _most_ of these warnings/errors. There are still a few that I couldn't trace to the source and some that I couldn't change without causing tests to fail.
=> tests: change the way we call net.Listen to avoid annoying popups on macOS

examples/operator/101_initial_cluster.yaml, examples/operator/201_customer_tablets.yaml, examples/operator/302_new_shards.yaml, examples/operator/306_down_shard_0.yaml, examples/operator/README.md, examples/operator/operator.yaml
This pull request changes the Docker tag used in the vitess operator examples. Previously, they were using `v12.0.0` on `main` which is incorrect, we want people using `main` to use the latest builds of Vitess.
- Contributes to https://github.com/vitessio/vitess/issues/9566
=> Changed vitess operator examples to use `latest` on main

Makefile, tools/do_release.sh
This pull request adds some logic to `do_release` to automatically update the vitess-operator example during a release.
In the `./examples/operator`, both the Kubernetes YAML files and the README are updated during the release. The `vitess/lite` Docker image will be tagged to the new release (`$RELEASE_VERSION`), and the `planetscale/vitess-operator` image will use the value of `$VTOP_VERSION` as a tag. Note that `$VTOP_VERSION` is not required to run `do_release`, if no value is passed, the `planetscale/vitess-operator` image will remain the same.
- Contributes to https://github.com/vitessio/vitess/issues/9566
=> Automatically update vitess-operator example during a release

go/vt/servenv/grpc_server.go
* Register gRPC health service to support health checks. See [GRPC Health Checking Protocol](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) and [grpc_health_v1](https://pkg.go.dev/google.golang.org/grpc/health/grpc_health_v1).
* This change affects all use cases of `servenv.GRPCServer`
Fixes #9333
=> Add support for health service in gRPC server

docker/k8s/Dockerfile, docker/k8s/logrotate/Dockerfile, docker/k8s/logtail/Dockerfile, docker/k8s/mysqlctl/Dockerfile, docker/k8s/mysqlctld/Dockerfile, docker/k8s/orchestrator/Dockerfile, docker/k8s/pmm-client/Dockerfile, docker/k8s/vtbackup/Dockerfile, docker/k8s/vtctl/Dockerfile, docker/k8s/vtctlclient/Dockerfile, docker/k8s/vtctld/Dockerfile, docker/k8s/vtexplain/Dockerfile, docker/k8s/vtgate/Dockerfile, docker/k8s/vttablet/Dockerfile, docker/k8s/vtworker/Dockerfile, docker/release.sh
This is an update to the release process for the `/docker/k8s/...` images for individual binaries. This should all be pushed into Docker Hub configuration, and then `release.sh` can be removed I just haven't had the chance to do it. I still manually build and publish images from my machine for every release.
=> docker: k8s release process updates

tools/web_bootstrap.sh, web/vtctld2/README.md, web/vtctld2/package-lock.json
Node v8.0.0 was giving me all kinds of trouble with `npm install`. This PR updates vtctld2 to use node v8.17, the last 8.x LTS version prior to the [8.x EOL in 2020](https://blog.risingstack.com/update-nodejs-8-end-of-life-no-support/). 
Having a somewhat-improved version of 8.x will make it easier to upgrade a handful of other vtctld2 dependencies. :) 
I also committed changes to package-lock.json that resulted from `npm install` after the version upgrade. 
I manually validated that the vtctld2 UI still works by running everything locally. 
N/A
There is no action required in this PR for Vitess operators. The UI [hosted by the vtctld](https://github.com/vitessio/vitess/blob/411a983/go/vt/vtctld/vtctld.go) service uses static files, which I've rebuilt with `make web_build` in this PR. …
=> Update web/vtctld2 to use node v8.17 

go/sqltypes/named_result.go, go/test/endtoend/tabletgateway/buffer/reshard/sharded_buffer_test.go, go/test/endtoend/vreplication/cluster.go, go/test/endtoend/vreplication/resharding_workflows_v2_test.go, go/test/endtoend/vreplication/vreplication_test.go, go/vt/binlog/binlogplayer/binlog_player.go, go/vt/vtctl/vtctl.go, go/vt/vttablet/tabletmanager/vreplication/engine_test.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go, go/vt/vttablet/tabletmanager/vreplication/vreplicator.go, go/vt/wrangler/doc_test.md, go/vt/wrangler/fake_dbclient_test.go, go/vt/wrangler/traffic_switcher_env_test.go, go/vt/wrangler/traffic_switcher_test.go, go/vt/wrangler/vexec.go, go/vt/wrangler/vexec_plan.go, go/vt/wrangler/vexec_test.go, go/vt/wrangler/workflow.go, go/vt/wrangler/workflow_test.go, go/vt/wrangler/wrangler_env_test.go
This PR adds logic to measure the estimated lag between the last transaction at the source and the last transaction seen by the target. The target persists the transaction timestamp of each seen event in `_vt.vreplication`. The target may not receive events from the source in two cases: 
* where there is no activity at the source relevant to the target
* when the source is disconnected from the target (due to a vstreamer error, network issue or source tablets being unavailable). 
To differentiate between this the source starts sending "heartbeats" (special internal VEvents) every second if there are no actual events to be sent. As part of this PR we also start storing the last heartbeat time in `_vt.vreplication`.  
We calculate the transaction lag based on the transaction timestamp and …
=> SwitchTraffic: check vreplication lag before switching

go/vt/vtgate/evalengine/collate.go, go/vt/vtgate/evalengine/comparisons.go, go/vt/vtgate/evalengine/convert.go, go/vt/vtgate/evalengine/evalengine.go, go/vt/vtgate/evalengine/integration/comparison_test.go, go/vt/vtgate/evalengine/integration/fuzz_test.go, go/vt/vtgate/evalengine/mysql_test.go, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
No more new features for the `evalengine` but let's get some more fixes in: this fixes a crash when comparing strings that have different explicit vs implicit charsets.
=> collations: fix coercion between character sets

web/vtadmin/package-lock.json, web/vtadmin/package.json
This updates to postcss v8.4.6 in order to fix [CVE-2021-23566](https://www.whitesourcesoftware.com/vulnerability-database/CVE-2021-23566) in the nested [nanoid](https://www.npmjs.com/package/nanoid) dependency. 
For reference, here is the [postcss CHANGELOG](https://github.com/postcss/postcss/blob/main/CHANGELOG.md).
- postcss was last updated in #9493 
VTAdmin operators are recommended to redeploy VTAdmin to pick up the fix.
=> [vtadmin-web] Update postcss to v8.4.6

go/vt/vtctld/vtctld.go, go/vt/vtctld/vtctld_test.go
This PR closes #9194 by adding a flag to enable/disable the vtctld2 UI. This default value is true, which means that the vtctld2 UI will continue to be enabled by default. In other words, **nothing will change unless operators explicitly opt out**  of the vtctld2 UI. 
With `-enable_vtctld_ui=false`, any requests to any of the following vtctld URLs will 404:
- /app/
- /app/**/*
- Any other unrecognized path, as those all get redirected to /app/ by [this handler](https://github.com/vitessio/vitess/blob/66109e7f240b3fe45e4da2dc0c9db488b14682f9/go/vt/vtctld/vtctld.go#L139-L142)
This flag does not affect the HTTP API that the vtctld serves on /api/ (used by the web app).
I went back and forth for far too long on whether the flag should be `enable_` (and default to true) or `disable_` (and …
=> [vtctld] Add 'enable_vtctld_ui' flag to vtctld to explicitly enable (or disable) the vtctld2 UI

go/sqltypes/value.go
We replace the use of RegExps with Byte comparisons which should be much faster.
It's also simpler to read IMO since we're already using Byte slice indexes in related code.
Finally, it's actually more precise as it:
1. Allows for X'1' and x'1' (MySQL accepts both)
2. Requires x0\<byte\> as MySQL does not accept simply `0x` (it does
accept `x''` though)
```
mysql> select @@version;
+-----------+
| @@version |
+-----------+
| 8.0.27    |
+-----------+
mysql> select x'';
+----------+
| x''      |
+----------+
| 0x       |
+----------+
mysql> select X'01';
+--------------+
| X'01'        |
+--------------+
| 0x01         |
+--------------+
mysql> select 0X01;
ERROR 1054 (42S22): Unknown column '0X01' in 'field list' …
```
=> Improve performance of hex type decoding

go/sqltypes/value.go
We replace the use of RegExps with Byte comparisons which should be much faster.
It's also simpler to read IMO since we're already using Byte slice indexes in related code.
Finally, it's actually more precise as it:
1. Allows for X'1' and x'1' (MySQL accepts both)
2. Requires x0\<byte\> as MySQL does not accept simply `0x` (it does
accept `x''` though)
```
mysql> select @@version;
+-----------+
| @@version |
+-----------+
| 8.0.27    |
+-----------+
mysql> select x'';
+----------+
| x''      |
+----------+
| 0x       |
+----------+
mysql> select X'01';
+--------------+
| X'01'        |
+--------------+
| 0x01         |
+--------------+
mysql> select 0X01;
ERROR 1054 (42S22): Unknown column '0X01' in 'field list' …
```
=> Backport: Improve performance of hex type decoding

go/vt/vttablet/tabletserver/connpool/dbconn.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/stateful_connection.go, go/vt/vttablet/tabletserver/stateful_connection_pool.go, go/vt/vttablet/tabletserver/tabletenv/config.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tabletserver_test.go, go/vt/vttablet/tabletserver/tx/api.go, go/vt/vttablet/tabletserver/tx_pool.go
Add a new `vttablet` flag:
- Name: `sanitize_log_messages`
- Default: false (no change in behavior, opt-in)
- Description: Do not log potentially sensitive information in INFO, WARNING, and ERROR log messages such as query parameters
Use this where we make calls to `log.Info[f]`, `log.Warning[f]`, and `log.Error[f]` (glog) to ensure that we are sanitizing any potentially sensitive information. For example, here as this includes queries in the log message:
```
log.Warningf("killing transaction (exceeded timeout: %v): %s", tp.Timeout(), conn.String(tp.env.Config().SanitizeLogMessages))
```
Initially this will be used primarily to redact query/bind parameters from logged queries but this can be used going forward to sanitize any potentially sensitive information in the log messages. …
=> Support sanitizing potentially sensitive information in log messages

go/vt/vtadmin/api.go, go/vt/vtadmin/cluster/discovery/discovery.go, go/vt/vtadmin/cluster/discovery/discovery_dynamic.go, go/vt/vtadmin/cluster/discovery/discovery_dynamic_test.go, go/vt/vtadmin/cluster/discovery/discovery_json.go, go/vt/vtadmin/cluster/discovery/discovery_json_test.go
This PR greatly simplifies JSON discovery by:
- Renaming JSONDiscovery to DynamicDiscovery
- Refactoring out key logic in StaticFileDiscovery to JSONDiscovery
- Embedding JSONDiscovery in both StaticFileDiscovery and DynamicDiscovery, since they are both JSON-based
N/A
N/A
=> [VTAdmin] Simplify JSON Discovery

go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tabletserver_test.go
This effectively reverts https://github.com/vitessio/vitess/pull/9094.
That PR made undocumented behavior changes in a development release: `13.0.0-SNAPSHOT` (never part of a GA/stable release). It added some log message redaction behavior to the `-queryserver-config-terse-errors` flag and altered the meaning/intention of that flag. Additionally, we did not audit the `vttablet` codebase at that time to ensure that sensitive log messages were actually sanitized in all known potential places (it focused on one specific error message location).
In https://github.com/vitessio/vitess/pull/9550 we intended to properly sanitize all potentially sensitive `vttablet` log messages and we added a new flag for this purpose: `-sanitize_log_messages`. That work was complicated, however, by the fact that …
=> Remove queryserver-config-terse-errors impact on log messages

go/vt/vtgate/engine/ordered_aggregate.go, go/vt/vtgate/engine/ordered_aggregate_test.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/ordered_aggregate.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/memory_sort_cases.txt, go/vt/vtgate/planbuilder/testdata/oltp_cases.txt
While working on something related, we realized that collations were not being handled correctly on distinct aggregations.
This is a backport of #9639 
Example:
```sql
select foo, count(distinct bar) from tbl group by foo
```
For this query, if `bar` is a text column, we need to store collation information in the plan. Added this information to the plan description to make it easy to test.
=> [backport] Extract collation data to enable distinct aggregation

go/vt/vtctl/vtctl.go
The list command was renamed to show and list was deprecated. This wasn't updated in these error messages yet.
=> Update error description for deprecated command

web/vtadmin/package-lock.json, web/vtadmin/package.json
Backport of https://github.com/vitessio/vitess/pull/9612, which fixes [CVE-2021-23566](https://www.whitesourcesoftware.com/vulnerability-database/CVE-2021-23566) in the nested [nanoid](https://www.npmjs.com/package/nanoid) dependency. 
https://github.com/vitessio/vitess/pull/9612
=> [vtadmin-web] Update postcss to v8.4.6 (backport) 

go/vt/vttablet/tabletserver/connpool/dbconn.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/stateful_connection.go, go/vt/vttablet/tabletserver/stateful_connection_pool.go, go/vt/vttablet/tabletserver/tabletenv/config.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tabletserver_test.go, go/vt/vttablet/tabletserver/tx/api.go, go/vt/vttablet/tabletserver/tx_pool.go
This backports two related PRs together. Please see https://github.com/vitessio/vitess/pull/9634 for additional details.
This maintains consistent/unchanged behavior for `-queryserver-config-terse-errors` between 12.0 and 13.0 while adding support for sanitizing log messages with the new `-sanitize_log_messages` flag.
Backports: 
- https://github.com/vitessio/vitess/pull/9550
- https://github.com/vitessio/vitess/pull/9634
=> Backport: Add sanitize_log_messages and remove queryserver-config-terse-errors impact on log messages

go/vt/vttablet/onlineddl/executor.go
Migration cleanup happens either on:
- explicit `ALTER VITESS_MIGRATION ... CLEANUP` query
- automated migration garbage collection
In either case, migration cleanup now also makes sure to delete any associated `vreplication` workflow used by the migration. There can only be one such workflow, and one exists when the migration is `ALTER` or an `ALTER`'s `REVERT` with 'online' strategy.
- Tracking: #6926 
cc @aquarapid
=> OnlineDDL: delete _vt.vreplication entry as part of CLEANUP operation

.github/workflows/check_make_proto.yml, go/vt/proto/query/query.pb.go, tools/check_make_proto.sh
This pull request adds the `check_make_proto` workflow to the CI. The workflow checks that the `go/vt/proto/*.pb.go` files are in accordance with the `proto/*.proto` files. This is done by running the `make proto` command and diffing `git status`'s output before and after executing the `make proto`.
If there is a diff (a drift), the workflow lists the files that are not in accordance. A commit that exhibits this behavior can be found [here](https://github.com/vitessio/vitess/pull/9644/commits/a96bb3350591db945bdea182e5cb2f1e7159de47), with its failing `check_make_proto` workflow [here](https://github.com/vitessio/vitess/runs/5095360428?check_suite_focus=true).
- Solves #9588
=> Check for proto drift in the CI

go/sqltypes/type.go, go/vt/vtgate/evalengine/arithmetic.go, go/vt/vtgate/evalengine/arithmetic_expr.go, go/vt/vtgate/evalengine/arithmetic_expr_test.go, go/vt/vtgate/evalengine/arithmetic_test.go, go/vt/vtgate/evalengine/comparisons.go, go/vt/vtgate/evalengine/convert.go, go/vt/vtgate/evalengine/eval_result.go, go/vt/vtgate/evalengine/evalengine.go, go/vt/vtgate/evalengine/expressions.go, go/vt/vtgate/evalengine/format.go, go/vt/vtgate/evalengine/func.go, go/vt/vtgate/evalengine/integration/comparison_test.go, go/vt/vtgate/evalengine/integration/fuzz_test.go, go/vt/vtgate/evalengine/logical.go, go/vt/vtgate/evalengine/simplify.go, go/vt/vtgate/evalengine/unary.go
This is a cleanup PR: the new implementation of the `evalengine` was using an ugly mixture of SQL types from `querypb` and from `sqltypes`, even though all these constants are aliases between each other.
This PR cleans this mess by switching everything to the constants defined in `sqltypes`, which are more readable.
While I was here, I also added a randomization element to the integration tests: now every test run decides at random whether to simplify the tested expressions before evaluation. The expressions should (obviously) give identical results with and without simplification, so this randomization is a good way to ensure this property over time without doubling the duration of the integration tests, which are already quite long.
=> evalengine: use sqltypes

web/vtadmin/.stylelintrc, web/vtadmin/package-lock.json, web/vtadmin/package.json, web/vtadmin/src/components/charts/charts.scss, web/vtadmin/src/index.css, web/vtadmin/src/style/fonts.css
This updates stylelint from version 13.x to version 14, the latest version. [Here is the changelog](https://github.com/stylelint/stylelint/blob/main/CHANGELOG.md).
The only meaningful change for us is that must now explicitly include support for SCSS. I had to tweak a few of the rules when switching from `stylelint-config-standard` to `stylelint-config-standard-scss`. In particular, overriding the default rules for class- and property-patterns is required since SCSS seems to prefer kebab-case, whereas we use lowerCamelCase in order to import class names in .tsx files using SCSS modules.
N/A
N/A
=> [vtadmin-web] Upgrade stylelint + related dependencies to latest

go/test/endtoend/tabletmanager/commands_test.go, go/test/endtoend/tabletmanager/main_test.go
While working on [something else](https://github.com/vitessio/vitess/pull/9655) (which will be closed, [see here](https://github.com/vitessio/vitess/pull/9655#issuecomment-1033903896) for why), I was surprised to see that we have 0 tests (unit or e2e) for the [TabletManager's `GetSchema` RPC call](https://github.com/vitessio/vitess/blob/2a4550de4652bb2f8e4a1b81b4a9a7b15976e19f/go/vt/proto/tabletmanagerservice/tabletmanagerservice_grpc.pb.go#L148-L155). 
> It is tested indirectly through `MoveTables` and `Reshard` workflow related tests.
This PR adds a dedicated e2e test for it.
- https://github.com/vitessio/vitess/pull/9655
=> Add e2e test for the TabletManager GetSchema RPC

go/stats/counter.go, go/vt/vttablet/tabletserver/schema/engine.go, go/vt/vttablet/tabletserver/schema/engine_test.go
It makes more sense to store innodbRowsRead in a counter instead of a gauge since Mysql exporter (prometheus) also does so https://github.com/prometheus/mysqld_exporter/blob/c9d7a01501d047ddc3d0c03c33c262e12d28dd59/collector/global_status.go#L163-L166. This PR accomplishes that change.
=> Store innodbRowsRead in a Counter instead of a Gauge

go/vt/vtgate/planbuilder/physical/route_planning.go, go/vt/vtgate/planbuilder/testdata/from_cases.txt
Gen4 was not checking if two tables on unsharded keyspaces where on the same keyspace.
Fixes #9662
=> Gen4: make sure to not merge unsharded tables from different keyspaces

go/vt/vtexplain/testdata/multi-output/selectsharded-output.txt, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/planbuilder/builder.go, go/vt/vtgate/planbuilder/physical/route_planning.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/planbuilder/testdata/tpch_cases.txt
Routing for queries that contain outer join was not being handled correctly.
It would require a lot of changes to support these queries correctly in V3, so instead this fix makes it so the gen4 planner is used in the presence of outer joins.
If you know that you want to use the v3 planner, that can still be accomplished by using the query hint `/*vt+ PLANNER=v3 */`
Fixes #7700
=> Use the gen4 planner for queries with outer joins

go/mysql/flavor_mysql.go
Querying the `information_schema` tables can be quite expensive in MySQL 5.7.
On the test database I'm using (169 tables), each execution of the `TablesWithSize57` query takes multiple seconds, making this query unbearably slow.
But the runtime of this query can be improved with a few tricks.
For reference, here's the original query:
```sql
SELECT t.table_name, t.table_type, unix_timestamp(t.create_time), t.table_comment, sum(i.file_size), sum(i.allocated_size) 
FROM information_schema.tables t, information_schema.innodb_sys_tablespaces i 
WHERE t.table_schema = database() and 
(i.name = concat(t.table_schema,'/',t.table_name) or i.name like concat(t.table_schema,'/',t.table_name, '#p#%')) 
group by t.table_name, t.table_type, unix_timestamp(t.create_time), t.table_comment, i.file_size …
```
=> Improve performance of information schema query.

go/cmd/vtcombo/main.go, go/test/endtoend/vtcombo/vttest_sample_test.go, go/vt/vttest/local_cluster.go
This PR introduces a new flag to vtcombo (`-json_topo`) which allows a user to load a topology file from a JSON-encoded document.
In our testing setup we create topology files dynamically. JSON is easier to generate from a range of sources.
I don't think this applies to vtcombo?
=> Add flag to vtcombo to load a json-encoded test topology file

doc/releasenotes/10_0_4_release_notes.md, doc/releasenotes/14_0_0_summary.md, go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go, go/vt/vttablet/onlineddl/executor.go
Followup to https://github.com/vitessio/vitess/pull/9325. In this PR we reject a migration if submitted with same UUID and different `migration_context`.
As reminder, the user is allowed to supply their own migration UUIDs via `vtctl ApplySchema -uuid_list='...'`. This functionality is used to allow the user control and idempotency over their migrations.
UUID is a unique migration identifier. It is impossible to have any two migrations on same shard with same UUID. Hence, when one submits `-uuid_list=...` with an already existing UUID, their submission does not create a new migration. However, it is then also reasonable to expect that the user provides `-migration_context`. If the same migration is submitted twice or more, with same UUID and same `migration_context`, that is fine. The …
=> OnlineDDL: reject duplicate UUID with different migration_context

go/vt/vtgate/planbuilder/physical/route_planning.go, go/vt/vtgate/planbuilder/testdata/from_cases.txt
This is a backport of https://github.com/vitessio/vitess/pull/9665
- Backports: https://github.com/vitessio/vitess/pull/9665
- Fixes (in v13.0): https://github.com/vitessio/vitess/issues/9662
=> BACKPORT: Gen4: make sure to not merge unsharded tables from different keyspaces

go/vt/vttablet/tabletmanager/restore.go, go/vt/wrangler/testlib/backup_test.go
Do not attempt to setup replication when [active reparents are disabled](https://github.com/vitessio/vitess/blob/3adcf439960fbbde3d7f82998717a89f6ebcfb60/go/vt/mysqlctl/mysqld.go#L64).
It makes no sense to do any replication configuration related work as part of a [`RestoreFromBackup`](https://github.com/vitessio/vitess/blob/3adcf439960fbbde3d7f82998717a89f6ebcfb60/go/vt/vttablet/tabletmanager/rpc_backup.go#L155) RPC call because[ we do not ever start replication automatically when active reparents are disabled](https://github.com/vitessio/vitess/search?q=disableActiveReparents). We only need to restore the data and save the associated replication state metadata -- then it's up to the operator to (optionally) complete the replication setup if and as needed at a later time.
As a Vitess …
=> Skip repl config in restore when active reparents disabled

go/test/endtoend/vtorc/utils/utils.go
This PR removes the `use_super_read_only_flag` from the VTOrc test suite and instead turns super read only off before cleaning the underlying MySQL instance (removing old databases, etc).
=> Remove the use_super_read_only flag in VTOrc tests

doc/releasenotes/13_0_0_release_notes.md, go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go, go/test/endtoend/onlineddl/vrepl_stress_suite/onlineddl_vrepl_stress_suite_test.go, go/test/endtoend/onlineddl/vrepl_suite/onlineddl_vrepl_suite_test.go, go/vt/schema/ddl_strategy.go, go/vt/schema/ddl_strategy_test.go, go/vt/schema/online_ddl_test.go, go/vt/schemamanager/tablet_executor_test.go, go/vt/vttablet/onlineddl/executor.go
**BACKPORT** of https://github.com/vitessio/vitess/pull/9642
Naming is hard, and the `online` ddl-strategy was created in the hope/intention that it becomes the one and only (or the default) strategy. This takes longer than hoped for, and the term "online" is confusing.
This PR introduces a `vitess` strategy. It is identical in all functionality to `online`: `vitess` is an online (see the confusion?) strategy that uses VReplication as the underlying backend for `ALTER TABLE` operations; just like `online` strategy.
At this time, the two strategies `vitess` and `online` co-exist side by side. For backwards compatibility, we do not modify one into another at this time. At some point in the future we will implicitly change any `online` strategy into `vitess`. But we're not there yet.
In the …
=> v13 BACKPORT: OnlineDDL: 'vitess' strategy, synonym for 'online'

go/vt/vttablet/tabletmanager/restore.go, go/vt/wrangler/testlib/backup_test.go
This back ports https://github.com/vitessio/vitess/pull/9675 to vitess 13.0. Please see there for more details.
Backports: https://github.com/vitessio/vitess/pull/9675
=> BACKPORT: Skip repl config in restore when active reparents disabled

go/vt/vtexplain/testdata/gen4-queries.sql, go/vt/vtexplain/testdata/multi-output/gen4-output.txt, go/vt/vtexplain/testdata/test-schema.sql, go/vt/vtexplain/testdata/test-vschema.json, go/vt/vtexplain/vtexplain_flaky_test.go
This PR adds a test in vtexplain to show subshard vindex routing.
The test works locally, but on CI it fails with the error `limit on 8128 simultaneously alive goroutines is exceeded, dying`.
To show subsharding works, I have to create 512 shards.
Below is the test result.
```
----------------------------------------------------------------------
select * from user_region where regionId = 2305843009213693952 /* subshard */
1 ks_sharded/1f80-2000: select * from user_region where regionId = 2305843009213693952 limit 10001 /* subshard */
1 ks_sharded/2000-2080: select * from user_region where regionId = 2305843009213693952 limit 10001 /* subshard */
1 ks_sharded/2080-2100: select * from user_region where regionId = 2305843009213693952 limit 10001 /* subshard */ …
```
=> vtexplain: added multicol test to show subshard routing

go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go
When running `vitess` (formerly known as `online`) migrations, the Online DDL executor initiates a `VReplication` flow. However, it does so via gRPC, since Online DDL runs on tabletserver and VReplication on tabletmanager. So Online DDL doesn't have ownership nor direct access to VReplication's state and flows.
We recently hit an issue where `_vt.vreplication` table was missing a column; `VReplication` did not happen to run a ny query that would cause its own `WithDDL` to upgrade the table and add the new column.
In this PR, the first time (in the process' lifetime) Online DDL attempts to run a vitess (vreplication) migration, it requests vreplication to run an intentionally invalid query: 
```sql
SELECT no_such_column__init_ddl FROM _vt.vreplication LIMIT 1
```
we know this query will …
=> OnlineDDL: force (once) vreplication's WithDDL to run before running a vitess migration

go/vt/sqlparser/ast_funcs.go, go/vt/vtgate/planbuilder/operator_to_query.go, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/planbuilder/testdata/tpcc_cases.txt
This pull request fixes an issue encountered when we plan a query that can be merged in a single route and contains a derived table with one of the following: having, group by, order by, limit.
The planner was not adding those clauses to the merged query leading to invalid results being returned.
A query like this:
```sql
select 1 
from (
select col, count(*) as a 
from main.unsharded
group by col
having a > 0 
limit 12 offset 0) as f
left join unsharded as u on f.col = u.id
```
Would produce a plan that contains a query like this:
```sql
select 1
from (
select col, count(*) as a
from unsharded) as f
left join unsharded as u on f.col = u.id
```
=> Fixed missing order/group by, limit, having in derived

go/cmd/vttestserver/main.go, go/vt/vtgate/vtgate.go
Very small PR changing the wording for the `planner_version` flag. Gen4 is no longer considered experimental.
=> Change wording on vtgate flag description

go/vt/vtctld/vtctld.go, go/vt/vtctld/workflow.go, go/vt/workflow/long_polling.go, go/vt/workflow/long_polling_test.go, go/vt/workflow/manager.go
This PR fixes vtctld logging which is currently leaking http header values that can contain PII.
Fixes #8277
=> Fixes #8277: vtctld logs leak pii http headers

go/vt/binlog/binlogplayer/binlog_player.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go
This back ports https://github.com/vitessio/vitess/pull/9700 to vitess 13.0. Please see there for more details.
Backports: https://github.com/vitessio/vitess/pull/9700
=> Backport #9700: Use WithDDL while updating time_heartbeat

go/cmd/vtctl/vtctl.go, go/cmd/vtworker/vtworker.go, go/test/endtoend/vtorc/utils/test_config_crosscenter_prefer.json, go/test/endtoend/vtorc/utils/test_config_crosscenter_prefer_prevent.json, go/vt/orchestrator/config/config.go, go/vt/orchestrator/logic/orchestrator.go, go/vt/vtctl/grpcvtctldserver/endtoend/init_shard_primary_test.go, go/vt/vtctl/grpcvtctldserver/server_test.go, go/vt/vtctl/reparentutil/durability.go, go/vt/vtctl/reparentutil/durability_test.go, go/vt/vtctl/reparentutil/emergency_reparenter_test.go, go/vt/vtctl/reparentutil/reparent_sorter_test.go, go/vt/vtctld/vtctld.go, go/vt/worker/vertical_split_clone_test.go, go/vt/wrangler/testlib/emergency_reparent_shard_test.go
The DurabilityParams argument was added to the Durability interface for testing purposes. Currently we are in a state wherein we have can specify that map from vtorc but not from any other place. Therefore we are removing this parameter.
=> Remove the DurabilityParams argument to the durability interface

go/vt/binlog/binlogplayer/binlog_player.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go
#9538 introduced a regression with existing clusters because a new column `time_heartbeat` was added to `_vt.vreplication` and the `WithDDL` package was not used while updating this new column.  The workflow would stall with these errors 
```
E0215 20:03:45.678794       1 dbclient.go:107] error in stream 14, retrying after 5s: error Unknown column 'time_heartbeat' in 'field list' (errno 1054) (sqlstate 42S22) during query: update _vt.vreplication set time_updated=1644955425, time_heartbeat=1644955425 where id=1 updating time
```
This PR has the following changes:
* the heartbeat update query is modified to use `WithDDL`.
* a test around this change to confirm that the column gets recreated
* a new query added to the `WithDDLInitialQueries` list: it accesses the new  `time_heartbeat` …
=> VReplication Workflows: Use WithDDL while updating time_heartbeat to be backwardly compatible with upgrades to existing cluster

go/test/endtoend/vreplication/resharding_workflows_v2_test.go, go/test/endtoend/vreplication/vreplication_test.go, test/config.json
Since adding the lag check during cutover the v2 test is being very flaky in CI. Locally it never fails. 
It seems that there is some side-effect of the test code which waits for flakiness. While that is researched/fixed, this PR bypasses the check for now. 
It also changes the number of retries to 1 for the v2 test since retries always fail
=> VReplication V2 test: bypass newly added lag test which is causing flakiness in CI

web/vtadmin/.stylelintrc, web/vtadmin/package-lock.json, web/vtadmin/package.json, web/vtadmin/src/components/charts/charts.scss, web/vtadmin/src/index.css, web/vtadmin/src/style/fonts.css
This backports https://github.com/vitessio/vitess/pull/9654, since it updates a few dependencies that were flagged as out-of-date by `npm audit`. 
- https://github.com/vitessio/vitess/pull/9654/
=> [vtadmin-web] Upgrade stylelint + related dependencies to latest (backport) 

web/vtadmin/src/api/http.test.ts, web/vtadmin/src/api/http.ts, web/vtadmin/src/components/ReadOnlyGate.test.tsx, web/vtadmin/src/components/ReadOnlyGate.tsx, web/vtadmin/src/components/routes/Tablets.tsx, web/vtadmin/src/components/routes/tablet/Tablet.tsx, web/vtadmin/src/react-app-env.d.ts, web/vtadmin/src/util/env.ts
This adds a new build flag to vtadmin-web: `REACT_APP_READONLY_MODE`. This flag will hide any UI controls that correspond to write actions (i.e., `POST`/`PUT`/`DELETE` request) and, further, will prevent those requests from being sent at all.
As noted in the comments, this flag only affects the UI. If write actions are a concern, Vitess operators are encouraged to also configure vtadmin-api for role-based access control (RBAC) if needed; see https://github.com/vitessio/vitess/blob/main/go/vt/vtadmin/rbac/rbac.go.
And, as noted in https://github.com/vitessio/vitess/issues/9726:
> A more elegant, long-term solution I'd like to consider is to hide or show UI controls based on the user's authorizations, derived from the RBAC …
=> [vtadmin-web] Add REACT_APP_READONLY_MODE flag

doc/releasenotes/13_0_0_summary.md
Backport of https://github.com/vitessio/vitess/pull/9735 so I'm only including backport reviewers. :) If there's feedback to be addressed on https://github.com/vitessio/vitess/pull/9735, I will be sure to update this PR as well.
=> Update release notes with web/vtctld2 deprecation announcement and flag (backport)

go/vt/vtctl/backup.go, go/vt/vttablet/tabletmanager/rpc_replication.go, go/vt/wrangler/tablet.go, go/vt/wrangler/testlib/backup_test.go, go/vt/wrangler/testlib/emergency_reparent_shard_test.go, go/vt/wrangler/testlib/planned_reparent_shard_test.go
Backport PR for #9725 
After this change, vtctld will send an additional RPC for `SetReplicationSource` after `Backup` and `RestoreFromBackup` have run. This is needed for maintaining backward compatibility during the upgrade downgrade process.
vtctld from (version 13 and 14) - Will pass the correct semi-sync information in the `SetReplicationSource` RPC
vttablets from version 13 - Will ignore the semi-sync value passed and will use the `enable_semi_sync` flag
vttablets from version 14 - Will use the information passed in the RPC to set the semi-sync correctly.
vttablets from version 13 could have made autonomous decisions on whether semi-sync is supposed to be set or not. But in release 14, `enable_semi_sync` is deprecated, and the only way to know whether to set semi-sync or not will …
=> Backport: fix semi-sync for Backup and RestoreFromBackup commands by calling SetReplicationSource RPC

go/vt/servenv/mysql.go, tools/do_release.sh
Between v12 and v13, new code was written to the version.go file, however, `do_release` would override the `version.go` file with the latest release's information, removing other code written in that file. This pull request fixes that.
=> Fix output issue in the do_release script

Makefile, docker/bootstrap/build.sh, docker/test/run.sh
Signed-off-by: FancyFane <fane@planetscale.com>
This pull request fixes permission changes being set when `make docker_lite` is ran locally. A backup of permissions is made before the offending `chmod` command, and these permissions are restored after the build is complete. Preventing the user from having incorrect permissions in their local Vitess repository. 
n/a
=> Permission fixes for Docker builds

web/vtadmin/package-lock.json, web/vtadmin/package.json
This is a backport for https://github.com/vitessio/vitess/pull/9737. Including it in the 13.0 release since it resolves a CVE raised by `npm audit` in the nested node-fetch dependency: https://github.com/advisories/GHSA-r683-j2x4-v87g
This is the last dependency update I expect to backport to 13.0. :)
=> [vtadmin-web] Update msw to latest (v0.36.8) (backport) 

examples/operator/operator.yaml, tools/do_release.sh
This pull request uses the latest CRDs of the vitess-operator following the recent changes made in vitess-operator. The `operator.yaml` is now usable with the most recent version of Kubernetes that vitess-operator supports `1.22.*` as of today.
Additionally, a minor fix in the `do_release` script is pushed in this pull request. When updating the Docker tag in the vitess-operator examples, the `v` of `vX.X.X` was missing.
The entire vitess-operator example was tested on both `main` and `release-13.0`.
=> Use latest vitess-operator example CRDs

examples/operator/101_initial_cluster.yaml, examples/operator/201_customer_tablets.yaml, examples/operator/302_new_shards.yaml, examples/operator/306_down_shard_0.yaml
This pull request updates the tag used by the vitess-operator Docker image. There was a typo, the `v` of `v13.0.0-rc1` was missing.
=> Fixed tagged images in vitess-operator examples

web/vtadmin/package-lock.json, web/vtadmin/package.json
This updates [msw](https://www.npmjs.com/package/msw) to v0.36.8. Changelog is [here](https://github.com/mswjs/msw/releases), though no changes were required for us (yay). 
This resolves a CVE raised by `npm audit` in the nested node-fetch dependency: https://github.com/advisories/GHSA-r683-j2x4-v87g
A few interesting features I found in the changelog:
- [`rest.all` "captures all REST API requests regardless of method"](https://github.com/mswjs/msw/releases/tag/v0.36.0)
- [Route matching now uses the same logic as ExpressJS](https://github.com/mswjs/msw/releases/tag/v0.36.0)
N/A
N/A
=> [vtadmin-web] Update msw to latest (v0.36.8)

go/vt/vttablet/tabletserver/planbuilder/builder.go, go/vt/vttablet/tabletserver/planbuilder/plan.go, go/vt/vttablet/tabletserver/query_engine.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/rules/map.go, go/vt/vttablet/tabletserver/rules/rules.go, go/vt/vttablet/tabletserver/rules/rules_test.go
Issue found: when query rules are applied to a table (e.g. `UpdateSourceDeniedTables`), query executor still lets some queries run and operate on the applied table. Specifically, it allows `SELECT`/`UPDATE`/`DELETE` queries that reference multiple tables to go unchecked.
Say table `corder` is denied. the following query gets rejected:
```sql
select * from corder;
ERROR 1105 (HY000) at line 1: target: commerce.0.primary: vttablet: rpc error: code = FailedPrecondition desc = disallowed due to rule: enforce denied tables (CallerID: userData1)
```
while the following query is allowed:
```sql
select * from corder, customer
```
As it turns out, the plan completely ignores the rules if it does not have exactly one referenced table. This is a bug and the behavior is undesired.
In this PR the …
=> Query plan/rules: apply for multi-table statement

go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/testdata/union_cases.txt
This pull request adds support to push expressions to a union. Previously, queries like:
```sql
select 1
from (
select id+42 as foo
from user
union
select 1+id as foo
from unsharded
) as t
```
Would fail because the `1` was not allowed to be pushed down.
=> Push projection to union

go/vt/orchestrator/config/config.go
This PR just adds 2 comments explaining MySQLTopologyUser and MySQLReplicaUser parameters for VTOrc, so that the difference between the two is clearer.
=> Improve explanation of MySQLTopologyUser and MySQLReplicaUser so that their difference is clearer

go/sqltypes/bind_variables.go, go/vt/vtgate/evalengine/eval_result.go, go/vt/vtgate/evalengine/translate_test.go
Signed-off-by: Alon Kenneth <11458012+akenneth@users.noreply.github.com>
Add missing support for `uint32` bindvars mapping.
* Fixes https://github.com/vitessio/vitess/issues/9756
=> Add support for uint32 bind var + test

.github/workflows/upgrade_downgrade_test_backups_e2e.yml, .github/workflows/upgrade_downgrade_test_backups_manual.yml, .github/workflows/upgrade_downgrade_test_query_serving.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml, tools/get_latest_release.sh
@GuptaManan100 and I paired up on this pull request to improve the upgrade downgrade testing workflows by choosing the latest release in a better way.
Before, every commit would be tested against the last major release, even if this commit is made on, for instance, the `release-12.0` branch. ~~Now, commits made against a release branch are tested against the previous release branch (commits to `release-13.0` will be tested against `release-12.0`) ; and commits made to `main` and other branches are tested against the latest release branch.~~
Now, commits made against a release branch are tested against the previous releases' latest patch release and commits made to `main` and other branches are tested against the last major release tag unless a new release brach has been created without a …
=> Improve upgrade downgrade workflows' strategy

examples/demo/demo.go
The return value was changed from `[]byte` to `([]byte, error)` a little
while ago, making it impossible to run the demo.
This handles the error and returns nil after logging the error in case
the conversion fails.
- Fixes: https://github.com/vitessio/vitess/issues/9763#issuecomment-1048419739
=> demo.go: fix call to ToBytes

go/vt/vttablet/tabletserver/gc/tablegc.go
Signed-off-by: Ankit Malpani <malpani@stripe.com>
Use admin user for tablet GC operations.
Context: Currently `vt_app` user is used for internal table GC operations. This however does not have enough privileges (like `alter/drop`) in all setups which results in GC failures. This change moves internal GC operations to be invoked as dba user
Fixes https://github.com/vitessio/vitess/issues/9689
- Should this PR be backported? - no
- Tests were added or are not required - tablegc unit tests pass but they dont exercise permission changes
- Documentation was added or is not required - not required
n/a
=> Use AllPrivs user for table GC transitions

go/vt/wrangler/materializer.go, go/vt/wrangler/materializer_test.go
We did not check for [the saved StopAfterCopy config value](https://github.com/vitessio/vitess/blob/2c0a29df5d513167ac0f600d8916128b15d1063e/go/vt/wrangler/materializer.go#L679) (➡️  [here for the `INSERT` to generate the `_vt.vreplication` row](https://github.com/vitessio/vitess/blob/2c0a29df5d513167ac0f600d8916128b15d1063e/go/vt/wrangler/materializer.go#L1087)) in the workflow [when attempting to externalize it](https://github.com/vitessio/vitess/blob/2c0a29df5d513167ac0f600d8916128b15d1063e/go/vt/wrangler/materializer.go#L758-L782). When the [`-continue_after_copy_with_owner=true`](https://vitess.io/docs/13.0/user-guides/configuration-advanced/createlookupvindex/) flag ([added in v12.0](https://github.com/vitessio/vitess/pull/8572/commits/7e7722ac7b51aa62c42b81a7e679e8acb1c15384)) was …
=> Externalize Lookup VIndexes properly when not stopping after copy

Makefile
Make executes each line in its own shell, so the `cd` had no effect on
the subsequent `go` invocations. Fix this by making each line `cd`
individually.
none
None – development workflow fix only
=> Fix `make embed_config` target

Makefile
The [example/demo app](https://github.com/vitessio/vitess/tree/main/examples/demo) is apparently used more than we may have thought. [A change in Vitess 13.0](https://github.com/vitessio/vitess/commit/d3dd227c325e6d558c1af6457ee3f0ab5282887d) caused the demo app to break, so this work adds a unit test for it which is simply to ensure that it builds.
- Related to: https://github.com/vitessio/vitess/pull/9615
- Related to: https://github.com/vitessio/vitess/issues/9763
=> Add unit test for the demo app

.github/workflows/upgrade_downgrade_test_backups_e2e.yml, .github/workflows/upgrade_downgrade_test_backups_manual.yml, .github/workflows/upgrade_downgrade_test_query_serving.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml
Before #9745 we used to build a matrix from the latest releases. So, if the step to get the latest releases was skipped, our matrix used to be empty and no workflow for the upgrade downgrade steps used to run.
In #9745, we moved from a matrix having a single element to a string storing the releaes/tag to run the test against. So, when the step to get latest release was skipped, the output was still a string albeit an empty one. This triggered the next workflow to run with an empty previous release/tag like in https://github.com/vitessio/vitess/runs/5310337523?check_suite_focus=true.
This PR fixes this issue, so that the job to run the upgrade-downgrade test only works when the previous job of getting the release to test against succeeds.
=> Fix upgrade-downgrade CI workflows running even when Skip label specified

go/cmd/vttestserver/main.go, go/vt/vttest/local_cluster.go, go/vt/vttest/vtprocess.go
Signed-off-by: Brendan Dougherty <brendan.dougherty@shopify.com>
Adds the enable_system_settings option to vttestserver so that it can be passed to VTGate via vtcombo.
N/A
N/A
=> vttestserver: add enable_system_settings option

.github/workflows/vtadmin_web_build.yml, .github/workflows/vtadmin_web_lint.yml, .github/workflows/vtadmin_web_unit_tests.yml, web/vtadmin/src/util/__snapshots__/tabletDebugVars.test.ts.snap
Well this is an embarrassing oversight! 🤡 Better late than never!
Here's what it looks like when it fails on purpose: https://github.com/tinyspeck/vitess/runs/5254002448?check_suite_focus=true
**Edited to add:** I also switched our CI tests from using `npm install` to using `npm ci`, since... this is the exact use case for `npm ci`. :) 
N/A
N/A
=> Add CI workflow for vtadmin-web unit tests

go/cmd/vtctl/vtctl.go
This removes a warning from the example scripts.
Before:
```
➜  local git:(afe22c6ba3) ✗ ./101_initial_cluster.sh 
add /vitess/global
add /vitess/zone1
add zone1 CellInfo
W0225 12:00:46.596158   80901 vtctl.go:88] WARNING: vtctl should only be used for VDiff workflows. Consider using vtctldclient for all other commands.
```
After:
```
➜  local git:(andrew/better-vtctl-warning-placement) ✗ ./101_initial_cluster.sh 
add /vitess/global
add /vitess/zone1
add zone1 CellInfo
Created cell: zone1
```
=> Move deprecation warning to just before we actually invoke the legacy command path

go/test/endtoend/vreplication/config.go, go/test/endtoend/vreplication/unsharded_init_data.sql, go/vt/vtgate/evalengine/comparisons.go
We switched to using evalengine for `VDiff` comparisons in https://github.com/vitessio/vitess/pull/9679.
What we didn't realize at the time is that evalengine did not support comparing `TEXT` columns. When doing a `VDiff` against a table that has them, you get the following error (you can see a failed test after the test changes [here](https://github.com/vitessio/vitess/runs/5342687212?check_suite_focus=true)):
```
VDiff Error: rpc error: code = Unknown desc = diff: types are not comparable: TEXT vs TEXT
```
There's no logical reason for this as a `TEXT` field for in memory processing is no different from a `VARCHAR`. The main differences are the on disk format which stores the values off page due to the large maximum size for the type. The same is true for `BLOB` and `VARBINARY` fields, …
=> Add TEXT field comparison support to evalengine (for VDiff)

bootstrap.sh
Currently, we don't provide a `protoc` binary for osx/arm64
combinations (i.e. "M1 Macs"), and neither does upstream
protobuf.
The current upstream suggested workaround is to build from source or use
unsigned binaries.
Luckily, if you have Rosetta installed on your machine (which for a while
was required to [run `man` without errors](https://apple.stackexchange.com/questions/430310/apple-silicon-usr-bin-mandoc-bad-cpu-type-in-executable/430311#430311), it's actually totally fine to run the x86-64 version.
So, we just warn the user we're doing this and install the other binary.
```
➜  vitess git:(andrew/protoc-m1) ✗ rm -rf dist/vt-protoc-*    
➜  vitess git:(andrew/protoc-m1) ✗ 
➜  vitess git:(andrew/protoc-m1) ✗ make minimaltools >/dev/null
WARN: Installing x86_64 protoc on arm macos; …
```
=> Hack to allow `bootstrap.sh` to run cleanly on fresh M1

go/sqltypes/type.go, go/sqltypes/type_test.go, go/vt/vtgate/evalengine/arithmetic.go, go/vt/vtgate/evalengine/arithmetic_expr.go, go/vt/vtgate/evalengine/bit.go, go/vt/vtgate/evalengine/collate.go, go/vt/vtgate/evalengine/comparisons.go, go/vt/vtgate/evalengine/convert.go, go/vt/vtgate/evalengine/eval_result.go, go/vt/vtgate/evalengine/evalengine.go, go/vt/vtgate/evalengine/func.go, go/vt/vtgate/evalengine/hex.go, go/vt/vtgate/evalengine/logical.go, go/vt/vtgate/evalengine/simplify.go, go/vt/vtgate/evalengine/translate.go
Since we've started using the evaluation engine for VDiff, @mattlord has found several issues where our type coverage was not good enough and we were failing to operate on types that were (in theory) supported but that we failed to handle because our type checks where too constricted (e.g. `TEXT` vs `CHAR` vs `VARCHAR`).
This PR attempts to fix any further cases that may come up in the future by switching the `evalengine` to using the `sqltypes.IsXXX` category checks instead of explicitly comparing against specific types. It also cleans up some technical debt by renaming some helper methods which were IMO a bit confusing.
=> evalengine: more comprehensive type coverage

go/vt/vtgate/engine/filter.go, go/vt/vtgate/engine/projection.go, go/vt/vtgate/engine/set.go, go/vt/vtgate/evalengine/comparisons_test.go, go/vt/vtgate/evalengine/expressions.go
When we need to calculate the type of a column, it's more accurate and safer to use the field information from the incoming result, and not just look at the values.
It's not a problem in `main`, but another [PR](#9643) will push the evalengine to need to do this.
=> evalengine: Use field information when doing type calculation on columns

go/vt/vtgate/engine/ordered_aggregate.go, go/vt/vtgate/engine/ordered_aggregate_test.go, go/vt/vtgate/engine/scalar_aggregation.go, go/vt/vtgate/engine/scalar_aggregation_test.go, go/vt/vtgate/planbuilder/grouping.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/ordered_aggregate.go, go/vt/vtgate/planbuilder/ordering.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/planbuilder/testdata/oltp_cases.txt, go/vt/vtgate/planbuilder/testdata/postprocess_cases.txt, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/planbuilder/testdata/tpch_cases.txt, go/vt/vtgate/planbuilder/testdata/union_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
For aggregations without grouping columns (`select count(*) from tbl`), we could use a simple engine primitive.
This PR implements the scalar aggregation engine primitive, that handles these types of situations.
=> Split aggregation in scalar and ordered aggregation

go/test/endtoend/onlineddl/ghost/onlineddl_ghost_test.go, go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go, go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go, go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go, go/vt/vttablet/tabletserver/tabletserver.go
This PR adds `ready_to_complete` column in `_vt.schema_migrations` which is then visible in `SHOW VITESS_MIGRATIONS ...` output.
The use case is intended for postponed migrations (although it provides visibility for non-postponed migrations as well): if a migration is postponed, the user wants to know "is now a good time to cut-over" ie run a `ALTER VITESS_MIGRATION ... COMPLETE` and expect a near-immediate cut-over.
`ready_to_complete` is a boolean (values `0` or `1`) that indicates that the migration is generally capable of cutting over. Specifically:
- `CREATE` and `DROP` migrations will always exhibit the value of `1` (immediately or shortly after submission). Note that this is true even if the migrations are still `queued`. Once they exhibit `1`, they stay with `1`.
- `vitess` …
=> Online DDL: ready_to_complete hint column

go/vt/vttablet/tabletserver/txserializer/tx_serializer.go, go/vt/vttablet/tabletserver/txserializer/tx_serializer_test.go
The transaction serializer — which offers "hot row protection" that can be enabled in vttablets using the [`-enable_hot_row_protection`](https://vitess.io/docs/14.0/reference/programs/vttablet/) flag — logs the `key` for its map at various times. The key consists of the table name and the `WHERE` clause and the `WHERE` clause can contain sensitive info so we should be sanitizing it for log messages when the vttablet [`-sanitize_log_messages`](https://vitess.io/docs/14.0/reference/programs/vttablet/) flag is enabled. 
We should also be sanitizing the key in the returned error message when the vttablet [`-queryserver-config-terse-errors`](https://vitess.io/docs/14.0/reference/programs/vttablet/) flag is enabled.
- Fixes: https://github.com/vitessio/vitess/issues/9801
=> Sanitize tx serializer log & error messages

go/vt/binlog/binlogplayer/mock_dbclient.go, go/vt/vttablet/tabletmanager/vreplication/engine.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/withddl/withddl.go
This PR runs a "fake" query using WithDDL on tablet startup so that we reach the desired schema right at the start rather than auto-magically during a WithDDL.Exec() invocation.
Since we don't enforce the usage of WithDDL.Exec() statically, it is possible for code to execute queries directly and cause regressions. Example: new code on an existing cluster expects a new column but does not use WithDDL.Exec() and hence that column never gets created.
=> Run WithDDL queries on tablet startup

go/vt/vtctl/workflow/stream_migrator.go
We were not checking for this when it can be null due to processing an internal table such as those used for OnlineDDL.
- Follow-up to: https://github.com/vitessio/vitess/pull/9578
- Fixes: https://github.com/vitessio/vitess/issues/9826
=> Check for nil vschema.Table in StreamMigrator

go/mysql/client.go, go/mysql/conn.go, go/mysql/conn_params.go, go/mysql/endtoend/client_test.go, go/vt/dbconfigs/dbconfigs.go
We added the functionality to handle processing these fields a while ago, but it was disabled by default. This PR adds a flag, that will make itself available in all VTTablet instances, that lets users control this functionality at launch.
cc @piki @deepthi
=> mysql: add a flag to handle EnableQueryInfo

go/vt/vtctl/reparentutil/emergency_reparenter.go, go/vt/vtctl/reparentutil/emergency_reparenter_test.go, go/vt/vtctl/reparentutil/promotionrule/promotion_rule.go, go/vt/vtctl/reparentutil/util.go, go/vt/vtctl/reparentutil/util_test.go
After the changes in #9765, we filter valid candidate list and remove any tablets not from the same cell as the previous primary (when `PreventCrossCellPromotion` is specified), before we choose the primary candidate for promotion. This allows us to simplify the function significantly since it no longer needs to handle the case where `PreventCrossCellPromotion` is specified.
This PR changes the unit tests for the function and simplifies it.
=> Internal cleanup for choosing primary in ERS

go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer.go
There is a code-path in `applyEvents()` in `vplayer.go` where it waits on a throttler check and sleeps if it is determined that a wait is needed. If the context is cancelled here then it can loop infinitely. The vreplication controller tries to shutdown due to the context failure, but it waits for all streams to end. This results in a deadlock.
This PR checks for a context cancellation in between throttle checks.
#9827
=> Check if context is cancelled in applyEvents() loop to avoid deadlocks

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/question.yml
This pull request changes the rendering type of the text fields in the issue templates. Some fields were using incoherent types (i.e: `shell` instead of `markdown`).
The templates can be previewed [here](https://github.com/frouioui/issue-template/issues/new/choose).
=> Fix rendering type in issue templates

go/sqlescape/ids.go, go/sqlescape/ids_test.go, go/vt/worker/restartable_result_reader.go, go/vt/worker/row_aggregator.go
Using a strings.Builder over a bytes.Buffer yields one less allocation
per call due to the final .String() call requring an allocation with
bytes.Buffer, while strings.Builder is simply a pointer cast to a
string.
Also minor nits:
* Iterating over the string bytes, rather than runes is quite a bit
faster, and we don't care about runes.
In general there are lots of places just glancing over the codebase that
are using bytes.Buffer in places that I'm pretty confident could/should
be converted over to strings.Builder instead. Constructing SQL strings,
etc. These would all likely benefit from a decent performance boost, but
I'm not entirely qualified to make these sweeping core changes in ways
that I can't easily test. But they should be reasonably easy to audit
and swap. They maintain the …
=> sqlescape: Improve performance of EscapeID

go/vt/topo/helpers/copy.go, go/vt/topo/helpers/copy_test.go
This updates `helpers.CopyShardReplications` to build a set of tablet aliases in the fromTS topo so that repeated copies are idempotent.
Fixes #9844
=> [topo/helpers] Make CopyShardReplications idempotent

go/test/endtoend/vtgate/queries/subquery/subquery_test.go, go/vt/sqlparser/ast_funcs.go, go/vt/vtgate/planbuilder/rewrite.go
This pull request fixes #9854 by using `HasValues` arguments instead of the regular `Name` argument for `EXISTS` subqueries.
- Fixes #9854 
- Unblock #9710
=> Fix `__sq_has_values1` error with `PulloutSubquery`

go/vt/vtctl/vtctl.go
This adds some cursory documentation for the `LegacyVtctlCommand` and `VtctldCommand` modes.
Example:
```
bash-3.2$ vtctl $TOPOLOGY_FLAGS help  | grep "Command"
W0307 11:22:40.763787   10524 vtctl.go:153] WARNING: vtctl should only be used for VDiff workflows. Consider using vtctldclient for all other commands.
LegacyVtctldCommand <command> [args...]
VtctldCommand <command> [args ...]
bash-3.2$ vtctl $TOPOLOGY_FLAGS help VtctldCommand
W0307 11:22:57.421730   10534 vtctl.go:153] WARNING: vtctl should only be used for VDiff workflows. Consider using vtctldclient for all other commands.
Runs the vtctl request through the new vtctldclient program syntax. This will become the default in a later version of Vitess.
```
Closes #9822.
=> Add help text for LegacyVtctlCommand and VtctldCommand

go/vt/vttablet/tabletmanager/tm_state.go
There is currently the possibility of an infinite loop inside `ChangeTabletType()` because we don't check for context cancellation inside an active polling loop. This PR adds the check.
#9838
=> TabletManager: Check for context cancellation in loop within ChangeTabletType()

go/vt/vtgate/engine/join.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/filter_cases.txt, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/planbuilder/testdata/large_cases.txt, go/vt/vtgate/planbuilder/testdata/memory_sort_cases.txt, go/vt/vtgate/planbuilder/testdata/postprocess_cases.txt, go/vt/vtgate/planbuilder/testdata/rails_cases.txt, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/planbuilder/testdata/symtab_cases.txt, go/vt/vtgate/planbuilder/testdata/systemtables_cases.txt, go/vt/vtgate/planbuilder/testdata/tpcc_cases.txt, go/vt/vtgate/planbuilder/testdata/tpch_cases.txt, go/vt/vtgate/planbuilder/testdata/union_cases.txt, go/vt/vtgate/planbuilder/testdata/vindex_func_cases.txt, go/vt/vtgate/planbuilder/testdata/wireup_cases.txt, test/config.json
Small PR that makes the plan descriptions containing join columns slightly easier to read.
Up until now, the list of columns that the join primitive produces has been shown using a list of integers, such as:
```
{
"Original": "select user.name, music.genre from user join music on user.musicId = music.id",
"OperatorType": "Join",
"Variant": "Join",
"JoinColumnIndexes": "-2,1",
"Inputs": [
{
"Query": "select `user`.musicId, `user`.`name` from `user`",
},
{
"Query": "select music.genre from music where music.id = :user_musicId",
}
]
}
}
```
The interesting part here is **"JoinColumnIndexes": "-2,1"**.
Negative numbers come from the left, so -2 here means the second column coming from the left …
=> feat: make the join columns output easier to read

go/vt/vtgate/planbuilder/operator_to_query.go, go/vt/vtgate/planbuilder/single_sharded_shortcut.go, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/semantics/semantic_state.go
This PR fixes a panic on table sorting on the final plan query output. It was caused when a query contains a join inside a derived table.
=> fix: planner panic on derived tables sorting in query builder 

go/test/endtoend/vreplication/config.go, go/test/endtoend/vreplication/resharding_workflows_v2_test.go, go/vt/vttablet/tabletmanager/vreplication/replicator_plan.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go
With MySQL [ENUM types](https://dev.mysql.com/doc/refman/en/enum.html) you define a list of valid values for the column as a list of strings. What MySQL stores in the table[space] and writes to row based binary log events, however, is [the index](https://dev.mysql.com/doc/refman/en/enum.html#enum-indexes) value.
In VReplication's `VPlayer` component — which runs on the target tablet and applies row based binlog events received from the `VStreamer` component on the source tablet — we generate `DELETE` and `UPDATE` statements with a `WHERE` clause that contains the `PRIMARY KEY` columns (or other unique equivalents) so that statement applies to a unique row. When the `PRIMARY KEY` contains an `ENUM` field then that field will always be used in the `WHERE` clause. But because the _**index …
=> VPlayer: use stored/binlogged ENUM index value in WHERE clauses

examples/local/101_initial_cluster.sh, examples/local/301_customer_sharded.sh
```
New VSchema object:
{
"sharded": false,
"vindexes": {},
"tables": {
"corder": {
"type": "",
"column_vindexes": [],
"auto_increment": null,
"columns": [],
"pinned": "",
"column_list_authoritative": false
},
"customer": {
"type": "",
"column_vindexes": [],
"auto_increment": null,
"columns": [],
"pinned": "",
"column_list_authoritative": false
},
"product": {
"type": "",
"column_vindexes": [],
"auto_increment": null,
"columns": [],
"pinned": "",
"column_list_authoritative": false
}
},
"require_explicit_routing": false
}
If this is not what you expected, check the input data (as JSON parsing will skip unexpected fields).
Waiting for vtgate to be up...
vtgate is up!
```
Closes #7219
=> Migrate remaining vtctldclient commands in local example

go/cmd/mysqlctl/mysqlctl.go, go/cmd/vtbackup/vtbackup.go, go/cmd/vtbench/vtbench.go, go/cmd/vtclient/vtclient.go, go/cmd/vtclient/vtclient_test.go, go/cmd/vtctldclient/command/legacy_shim.go, go/cmd/vtctldclient/command/root.go, go/cmd/vtctldclient/command/vschemas.go, go/cmd/vtexplain/vtexplain.go, go/cmd/vttablet/vttablet.go, go/cmd/vttestserver/main.go, go/cmd/vttestserver/vttestserver_test.go, go/cmd/vttlstest/vttlstest.go, go/vt/vttest/environment.go, go/vt/vttest/environment_test.go, go/vt/vttest/local_cluster.go, go/vt/vttest/mysqlctl.go, go/vt/vttest/vtprocess.go
This tidies up flag examples, usages strings, error strings, and tests in `go/cmd` with the exception of `vtorc` because (1) it's under active development, and (2) it doesn't hook through any of the existing deprecation mechanisms/servenv/flag shims.
#9895
=> [VEP-4, phase 1] Flag cleanup in `go/cmd`

go/vt/vtctl/vtctl.go, go/vt/wrangler/materializer.go, go/vt/wrangler/materializer_test.go, go/vt/wrangler/workflow.go
This PR adds a `drop_constraints` switch to `MoveTables` which will allow us to automatically strip constraints on tables in the target keyspace when importing a database into Vitess. 
Setting this to true causes us to use the `createDDLAsCopyDropConstraint` create DDL mode, which will strip all constraints from the table before creating it in Vitess. 
https://github.com/vitessio/vitess/blob/6fce6c66899dbd593e5d4e80ce7d2ff95046e13f/go/vt/wrangler/materializer.go#L1034-L1041
=> Add `--drop_constraints` to MoveTables

go/test/endtoend/tabletmanager/tablet_health_test.go, go/test/endtoend/tabletmanager/tablet_test.go, go/test/endtoend/vault/vault_test.go
=> [VEP 4, phase 1] Cleanup flags in `endtoend/vault` (and some comments in `endtoend/tabletmanager`)

go/cmd/tools.go, go/mysql/vault/auth_server_vault.go, go/test/endtoend/backup/vtctlbackup/backup_utils.go, go/test/endtoend/cluster/topo_process.go, go/test/endtoend/cluster/vtctl_process.go, go/test/endtoend/cluster/vtgr_process.go, go/test/endtoend/cluster/vtworker_process.go, go/test/endtoend/encryption/encryptedreplication/encrypted_replication_test.go, go/test/endtoend/migration/migration_test.go, go/test/endtoend/preparestmt/main_test.go, go/test/endtoend/reparent/plannedreparent/reparent_test.go, go/vt/vttablet/tabletmanager/rpc_backup.go
More cleanup work for single- to double-dash flags. See [VEP-4](https://github.com/vitessio/enhancements/blob/main/veps/vep-4.md)
#9895
=> [VEP-4, part 1] Flag cleanup in `go/mysql` and some endtoend tests

go/test/endtoend/vtgate/schematracker/loadkeyspace/schema_load_keyspace_test.go, go/test/endtoend/vtgate/tablet_healthcheck_cache/correctness_test.go, go/test/endtoend/vtorc/utils/utils.go
More of the same flag cleanup.
#9895
=> [VEP4, phase1] Cleanup flags in `endtoend/vtgate` and `endtoend/vtorc`

test/region_example.sh
After I changed the example to use v2 vreplication commands instead of v1, it started failing on several PRs (though it passed on the original PR #9875)
Temporarily adding a sleep to allow it to finish.
We should investigate whether v2 is slower than v1, keeping in mind that this is a tiny dataset.
#9875
=> region_example: sleep 5s before switching reads to allow copy to finish

go/test/endtoend/vreplication/config.go, go/test/endtoend/vreplication/resharding_workflows_v2_test.go, go/vt/vttablet/tabletmanager/vreplication/replicator_plan.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go
This backports https://github.com/vitessio/vitess/pull/9868 to v13.0 — it will be incorporated in any subsequent future 13.0 point release but will not trigger one directly. Please see the original PR for additional details.
- Backports: https://github.com/vitessio/vitess/pull/9868
- Fixes: https://github.com/vitessio/vitess/issues/9546
=> Backport: VReplication: use stored/binlogged ENUM index value in WHERE clauses

.github/workflows/cluster_endtoend_schemadiff_vrepl.yml, .github/workflows/cluster_endtoend_vreplication_across_db_versions.yml, .github/workflows/cluster_endtoend_vtgate_tablet_healthcheck_cache.yml, test/ci_workflow_gen.go
When working on https://github.com/vitessio/vitess/pull/9106 I didn't yet understand how the CI workflows were managed and I must have simply copied and edited another existing workflow file rather than using the auto generation tooling.
This PR corrects that mistake and other changes resulting from a subsequent `make generate_ci_workflows` run.
- Follow-up to: https://github.com/vitessio/vitess/pull/9106
=> Properly generate vtgate_tablet_healthcheck_cache workflow

go/vt/vtctl/query.go
This deprecates the following commands, to take effect in 14.0:
- `VtGateExecute`
- `VtTabletExecute`
- `VtTabletBegin`
- `VtTabletCommit`
- `VtTabletRollback`
- `VtTabletStreamHealth`
After 14.0, we'll delete the commands, flag, and associated code, which is tracked in #9933.
```
➜  local git:(andrew/deprecate-vtctl-querycommands) ✗ vtctlclient --server ":15999" help | grep -E 'Vt(Tablet|Gate)'
(DEPRECATED) VtGateExecute -server <vtgate> [-bind_variables <JSON map>] [-keyspace <default keyspace>] [-tablet_type <tablet type>] [-options <proto text options>] [-json] <sql>
(DEPRECATED) VtTabletExecute [-username <TableACL user>] [-transaction_id <transaction_id>] [-options <proto text options>] [-json] <tablet alias> <sql>
(DEPRECATED) VtTabletBegin [-username <TableACL user>] <tablet …
```
=> [vtctl] Deprecate query commands

.github/workflows/cluster_endtoend_schemadiff_vrepl.yml, .github/workflows/cluster_endtoend_vreplication_across_db_versions.yml, .github/workflows/cluster_endtoend_vreplication_basic.yml, .github/workflows/cluster_endtoend_vreplication_cellalias.yml, .github/workflows/cluster_endtoend_vreplication_migrate.yml, .github/workflows/cluster_endtoend_vreplication_multicell.yml, .github/workflows/cluster_endtoend_vreplication_v2.yml, go/test/endtoend/vreplication/cluster.go, go/test/endtoend/vreplication/vreplication_test.go, test/ci_workflow_gen.go, test/templates/cluster_endtoend_test.tpl, test/templates/cluster_endtoend_test_mysql80.tpl
The `vreplication*` tests were flaky, but out of those the [`vreplication_across_db_versions`](https://github.com/vitessio/vitess/blob/main/.github/workflows/cluster_endtoend_vreplication_across_db_versions.yml) test was the most flaky. If the machine they were running on seemed to be under stress and have resource contention, then that seemed to in turn cause at least one of the `vreplication*` tests to fail (typically failing to start one of the mysqld instances later on in the test). This work:
1. Increases the OS AIO request limit for the machine where it runs (this can be necessary with a lot of mysqld's doing a lot of I/O)
2. Explicitly ensures we have 0 replica and rdonly tablets for the tests
3. Modifies the MySQL cnf file used so that we use minimal resources and reduce …
=> Address flakiness of vreplication tests

.github/workflows/cluster_endtoend_ers_prs_newfeatures_heavy.yml, .github/workflows/cluster_endtoend_shardedrecovery_stress_verticalsplit_heavy.yml, .github/workflows/cluster_endtoend_vtctlbackup_sharded_clustertest_heavy.yml, .github/workflows/cluster_endtoend_worker_vault_heavy.yml, test/ci_workflow_gen.go, test/config.json
In https://github.com/vitessio/vitess/pull/9935 we added support for marking a test as requiring additional configuration in order to limit resource usage. This was done to make our heaviest (vreplication) tests more reliable as they would often fail when there was any resource contention on the runners. In this PR we're leveraging that work to modify some of the generic Cluster e2e tests that also often failed when resource contention seemed high.
In the process we also rename those tests to be something more meaningful and append `_heavy` to the name as a generic marker that they should be configured to limit resource usage. So going forward we can append that string to any other test name if we feel that resource contention is the common cause of failures.
- Related to: …
=> Address flakiness of some cluster e2e tests

.github/workflows/cluster_endtoend_mysql80.yml, .github/workflows/cluster_endtoend_upgrade.yml, .github/workflows/e2e_race.yml, .github/workflows/legacy_local_example.yml, .github/workflows/local_example.yml, .github/workflows/region_example.yml, .github/workflows/unit_test_mysql80.yml, go/vt/sqlparser/ast.go, go/vt/sqlparser/parse_test.go, go/vt/sqlparser/parser.go, go/vt/sqlparser/sql.go, go/vt/sqlparser/sql.y, test/templates/cluster_endtoend_test.tpl, test/templates/unit_test.tpl
Backport of #8094 for release 10.
Fixes #9921
=> Backport: Set fully parsed to false when ignoring errors

go/test/endtoend/cluster/cluster_process.go, go/test/endtoend/cluster/vtctl_process.go, go/test/endtoend/cluster/vtctlclient_process.go, go/test/endtoend/cluster/vtgate_process.go, go/test/endtoend/utils/utils.go, go/test/endtoend/vtgate/queries/subquery/subquery_test.go, go/test/endtoend/vtgate/schematracker/sharded/st_sharded_test.go, go/test/endtoend/vtgate/schematracker/unsharded/st_unsharded_test.go
This pull request adds a new helper function to the `endtoend/utils` package that skips a test if the major version of a binary is below a certain increment.
Some new functionalities can only be tested from a certain version of `vtgate`, `vttablet`, etc. However, the upgrade-downgrade tests execute all the end-to-end tests of a package regardless of which binary version supports them. This new helper function alleviates this issue.
Recently, the `TestSubqueriesExists` test started failing in the upgrade-downgrade test suite. This test uses a vtgate feature that only exists in `>= 14`, thus the new helper function is called at the beginning of the test to skip it if vtgate is below `v14`.
=> Skip end-to-end test if binary is below a certain major version

go/vt/vtgate/engine/concatenate.go, go/vt/vtgate/engine/limit.go
Some of our end-to-end tests for UNION were flaky and failing intermittently. These changes make the concatenate and the limit operator more resilient to running concurrent queries.
Fixes #9945
=> fix: make concatenate and limit concurrent safe

examples/local/backups/restart_tablets.sh
The upgrade downgrade backups manual test has been flaky on the ci for a while. On investigation of the same with the help of https://github.com/vitessio/vitess/pull/9944 led to the following discovery - 
While restarting the tablets with a backup, the tablet transitions to `RESTORE` type to restore from the local backup. Without waiting for the backup to finish, we call `InitShardPrimary` which sees the tablet type as `RESTORE` and turns off semi-sync on that tablet.
Later restoration completes and the tablet transitions to `REPLICA`, but its semi-sync settings aren't fixed, which leads to the primary stalling indefinitely on writes.
This PR fixes this issue by first waiting for the restoration phase to finish before calling InitShardPrimary. Earlier we had a 5 second hard wait to ensure …
=> Flakiness fix for Upgrade Downgrade Backup Manual test

go/vt/vtgate/engine/concatenate.go, go/vt/vtgate/engine/limit.go
Some of our end-to-end tests for UNION were flaky and failing intermittently. These changes make the concatenate and the limit operator more resilient to running concurrent queries.
Fixes #9945
Backport of #9979
=> [V13] fix: make concatenate and limit concurrent safe

go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
VStreamer caches a "table plan" for each new table it encounters via the binlog TABLE_MAP_EVENT.  
MySQL internally generates a unique (incrementing) id for a table as it inserts them into the binlog. The first time we see an id, we compute the table plan (essentially the list of columns with name and type information). If we get the same id again, we currently assume it is the same table and use the cached plan. 
However when the mysql server restarts it starts a new numbering for table ids and depending on the DMLs encountered the table id map can be different from the earlier one. 
Thus the binlog will contain the same id for different tables. While streaming from an older GTID, it can happen that we have cached a plan for table1 for id 100, say. And later we get the same id 100 for …
=> VStreamer: recompute table plan if a new table is encountered for the same id

go/vt/vtgate/planbuilder/physical/subquery_planning.go, go/vt/vtgate/planbuilder/route.go, go/vt/vtgate/planbuilder/testdata/select_cases.txt
This PR adds an empty map if the system table map is uninitialized in route.
- Fixes https://github.com/vitessio/vitess/issues/9653
=> fix: dual query with exists clause having system table query in it

go/vt/wrangler/materializer.go, go/vt/wrangler/materializer_test.go
In case we handle table names here with for example a dash in them, we should escape it consistently like how we escape values in other parts of the vschema as well.
Additionally, use the proper escape functionality instead of manually putting the string between backticks to ensure consistent behavior.
This would break an existing specific case in a vschema, namely using a table reference to a table that requires escaping. However, I think there's other areas already where this breaks from what I can gather so not sure if that's a practical concern then or not.
=> Improve escape handling for vindex materializer

go/test/endtoend/onlineddl/vrepl_suite/testdata/fail-duplicate-entry2/alter, go/test/endtoend/onlineddl/vrepl_suite/testdata/fail-duplicate-entry2/create.sql, go/test/endtoend/onlineddl/vrepl_suite/testdata/fail-duplicate-entry2/expect_failure
This PR adds a endtoend test for the `vreplication` suite to validate a unique key violation scenario. The expecteation is for `vreplication` to fail the migration due to a unique key.
- #6926
=> More testing for vreplication unique key violation protection

go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/semantics/analyzer.go
We don't support multiple distinct columns when aggregating on the vtgate, but there is no reason we should not allow it against single shards.
Fixes #9927
=> fix: allow multiple distinct columns on single shards

go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/semantics/analyzer.go, go/vt/vtgate/semantics/scoper.go
We do some special handling of scopes in ORDER BY, to allow the use of both aliases introduced in the SELECT expressions, but also columns coming from a table not listed in the SELECT list. These scoping rules should not be used on the ORDER BY that can be used inside the `group_concat` aggregation function.
=> ORDER BY scoping rules should not be used in group_concat

.github/workflows/golangci-linter.yml, .golangci.yml, go/vt/tlstest/tlstest.go, misc/git/hooks/golangci-lint
Here's a couple things that were broken after the 1.18 upgrade:
- the `tlstest` package was signing our certs with SHA1, which has been deprecated in 1.18. Change it to use sha256 to fix the tests.
- `golangci-lint` was properly installed in CI, but not locally, so some people were seeing local errors.
cc @systay @ajm188
=> Compatibility Fixes for 1.18

go/test/endtoend/worker/worker_test.go
As seen in the comment https://github.com/vitessio/vitess/issues/9985#issuecomment-1079666698, the test `TestReparentDuringWorkerCopy` is flaky.
This PR fixes by adding a 1 second wait between the two PRS calls. This makes it so that the retry loop of the failing query due to the first PRS would have run successfully by then.
Fixes #9985
=> Flaky TestReparentDuringWorkerCopy fix

.github/workflows/cluster_endtoend_vtorc.yml, .github/workflows/cluster_endtoend_vtorc_8.0.yml, test/ci_workflow_gen.go, test/config.json
This PR moves the VTOrc tests to run against MySQL 8.0 instead of MySQL 5.7
=> Move VTOrc tests to run against MySQL 8.0

go/vt/vtgate/engine/fake_vcursor_test.go, go/vt/vtgate/engine/primitive.go, go/vt/vtgate/engine/route.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/scatter_conn.go, go/vt/vtgate/vcursor_impl.go
This PR ignore the session setting related to transaction and reserved connection and always go through the `EXECUTE` call on the tabletserver.
sequence does not require a connection most of the time and even if a new set of sequence cache is required it is executed using its little own transaction in tabletserver ([ignoring conn passed](https://github.com/vitessio/vitess/blob/2b5f72c5dd0411c3ff9da4517c4a8d32c4f57fc5/go/vt/vttablet/tabletserver/query_executor.go#L133,L146) and [own transaction](https://github.com/vitessio/vitess/blob/2b5f72c5dd0411c3ff9da4517c4a8d32c4f57fc5/go/vt/vttablet/tabletserver/query_executor.go#L563)) ignoring the connection id provided by the vtgate or a new one started with `Begin` or `Reserve` calls.
- Fixes #9851
=> Fix: Sequence query to ignore reserved and transaction

go/vt/servenv/buildinfo_test.go, tools/build_version_flags.sh
Signed-off-by: Ankit Malpani <malpani@stripe.com>
Track full git sha1 string instead of the short version
This is needed for our deployment monitoring systems to identify and remediate any stale running vttablets
```
Before Change:
"BuildGitRev": "c7481c8249"
"BuildInformation": {"<redacted>.1644873069.c7481c8249.<branch>.4": 1}
After Change:
"BuildGitRev": "1d878d8a0be09b678bb4490060e8f23f890ddb92"
"BuildInformation": {"<redacted>.1648062731.1d878d8a0be09b678bb4490060e8f23f890ddb92.<branch>.48": 1},
```
An alternate is to not change the existing `BuildGitRev` but introduce a new variable `BuildGitFullRev`. I thought that would be redundant and hence updating the existing value to be complete
Fixes https://github.com/vitessio/vitess/issues/9952
- [no] Should this PR be backported?
- …
=> Track full git sha1 string instead of the short version

go/test/endtoend/tabletmanager/custom_rule_topo_test.go
This PR fixes the flakiness of the `TestTopoCustomRule`.
#9946
=> Fix Flaky TestTopoCustomRule

go/test/endtoend/vtgate/schema/schema_test.go, go/vt/schemamanager/tablet_executor.go, go/vt/vttablet/tabletmanager/rpc_query.go
Fixes https://github.com/vitessio/vitess/issues/9996
Previously, `vtctlclient ApplySchema -skip_preflight -strategy "direct -allow-zero-in-date"` would prepend a given SQL with a `set @@session.sql_mode=` before sending to `ExecuteFetchAsDba`. This caused errors in the SQL to be silently dropped.
Now, instead, we embed a `/*vt+ allowZeroInDate=true */` hint in the SQL (only applicable to DDLs, which is fine, this is all we need).
Then, on `tabletmaneger`'s side, we parse the query, and if we're able to find such `/*vt+ allowZeroInDate=true */`, we run `set @@session.sql_mode=` before actually executing the SQL.
- https://github.com/vitessio/vitess/issues/9996
- caused by #9273 
Added validation test
=> ApplySchema: allow-zero-in-date embedded as query comment in call to ExecuteFetchAsDba

web/vtadmin/src/components/ReadOnlyGate.tsx, web/vtadmin/src/components/routes/tablet/Tablet.test.tsx, web/vtadmin/src/components/routes/tablet/Tablet.tsx, web/vtadmin/src/components/tabs/Tab.tsx, web/vtadmin/src/components/tabs/TabContainer.tsx
This fixes a bug where the ReadOnlyGate component was breaking redirects when used within a `<Switch>`:
Turns out my comment was wholly incorrect! Writing these tests took way more time than it was worth! And, best of all, this will likely need to be [rewritten](https://reactrouter.com/docs/en/v6/upgrading/v5#remove-redirects-inside-switch) when we upgrade to the next version of react-router anyway! 🤡 Oh well.
N/A
N/A
=> [vtadmin-web] Fix default redirect on Tablet view

docker/release.sh
This cleans up the release process for all the docker images inside /docker/k8s
- upgrades to v13 + defaults the base image to bullseye (discussed with @mattlord [here](https://github.com/vitessio/vitess/pull/9561#issuecomment-1024837539))
- explicitly build amd64 images (I accidentally pushed arm64 images from a new Mac)
- change paths to run in place - prior to this, it required to be executed in the /docker/k8s directory as ../release.sh. That was just an artifact after it moved from the since deleted /helm directory
=> docker: cleanup of release.sh

go/test/endtoend/vtgate/reservedconn/reconnect3/main_test.go, go/test/endtoend/vtgate/reservedconn/reconnect4/main_test.go, go/vt/vterrors/constants.go, go/vt/vtgate/scatter_conn.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tx_engine.go, test/config.json
This PR fixes issues with reserved connection when the vttablet or the underlying MySQL process is down.
The VTGate needs to understand the error codes/messages to redirect it to the new available tablet.
```
Issue 1: 
MySQL error: code 2002/2003 when the underlying MySQL is not available for connection.
Issue 2: 
Vttablet is down: ERROR 1105 (HY000): tablet: cell:"zone1" uid:100 is either down or nonexistent
Issue 3:
Vttablet tx engine is closed: tx engine can't accept new connections in state NotServing
```
In all the above scenarios the current reserved connection held should be dropped and a new one should be created by calling the ReserveExecute API to the tablet.
=> Fix: reserved connection retry logic when vttablet or mysql is down

go/vt/sqlparser/ast_rewriting.go, go/vt/sqlparser/ast_rewriting_test.go, go/vt/vtgate/planbuilder/physical/route_planning.go, go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/planbuilder/testdata/select_cases_with_default.txt
Fixes two different bugs -
1. Queries with a dual subquery should not be replaced with literals when inside an `EXISTS` call
2. When merging routes where one side is a reference route, we have to copy keyspace information as well
Fixes #9900
Backport of #10007
=> gen4: Fix sub query planning when the outer query is a dual query

go/vt/vtgate/planbuilder/operator_to_query.go, go/vt/vtgate/planbuilder/single_sharded_shortcut.go, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/semantics/semantic_state.go
This PR fixes a panic on table sorting on the final plan query output. It was caused when a query contains a join inside a derived table.
Backport of https://github.com/vitessio/vitess/pull/9869
=> 13.0: fix: planner panic on derived tables sorting in query builder

go/test/endtoend/cluster/cluster_process.go, go/test/endtoend/cluster/vtgate_process.go, go/test/endtoend/vtgate/queries/subquery/subquery_test.go, go/test/endtoend/vtgate/schematracker/sharded/st_sharded_test.go, go/test/endtoend/vtgate/utils/utils.go
This pull request is a backport of #9975, allowing us to skip certain end-to-end tests based on the major version of a binary. One of the subquery end-to-end test is skipped when ran with vtgate below v14.
- Backport of #9975
=> Backport: Skip end-to-end test if binary is below a certain major version 

go/test/endtoend/vtgate/misc_test.go, go/vt/vtgate/executor_test.go, go/vt/vtgate/planbuilder/explain.go, go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/planbuilder/plancontext/vschema.go, go/vt/vtgate/vcursor_impl.go
This pull request introduces `FindKeyspace` to the `VSchema` interface, allowing us to route explain queries to the proper keyspace regardless if the target is a MySQL table or a Vindex table.
Based on the issue reported in #10019, running a query that describes a Vindex led to a `panic` in VTGate. When running the local example to have a sharded cluster, the queries that follow used to crash:
```
mysql> use customer;
mysql> desc hash;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    8
Current database: customer
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    9
Current database: customer
ERROR 2013 (HY000): Lost connection to MySQL server during …
```
=> Route explain tab plan to the proper Keyspace

go/test/endtoend/onlineddl/vrepl_suite/testdata/update-pk-col-uppercase/alter, go/test/endtoend/onlineddl/vrepl_suite/testdata/update-pk-col-uppercase/create.sql, go/vt/vttablet/tabletmanager/vreplication/table_plan_builder.go
Currently, vreplication maps `pkCol` (primary key column list) based on lower case column names. This is incorrect, and went under the radar because it only shows in a specific scenario: a PK column that is non-lower case is updated during vreplication workflow.
The fix is an extract from @rohit-nayak-ps 's #9742, where he just recently identified the same.
Added a `onlineddl/vrepl-suite` test to validate new behavior (the test fails without the fix in this PR).
=> VReplication: maintain original column case for pkCols

go/vt/vtadmin/cluster/cluster_test.go, go/vt/vtadmin/cluster/discovery/discovery.go, go/vt/vtadmin/cluster/discovery/discovery_consul.go, go/vt/vtadmin/cluster/discovery/discovery_json.go, go/vt/vtadmin/cluster/discovery/fakediscovery/discovery.go, go/vt/vtadmin/cluster/resolver/resolver.go, go/vt/vtadmin/cluster/resolver/resolver_test.go, go/vt/vtadmin/vtctldclient/config.go, go/vt/vtadmin/vtctldclient/config_test.go, go/vt/vtadmin/vtctldclient/fakevtctldclient/vtctldclient.go, go/vt/vtadmin/vtctldclient/proxy.go, go/vt/vtadmin/vtctldclient/proxy_test.go, go/vt/vtadmin/vtsql/config.go, go/vt/vtadmin/vtsql/config_test.go, go/vt/vtadmin/vtsql/vtsql.go, go/vt/vtadmin/vtsql/vtsql_test.go, go/vt/vtctl/grpcvtctldclient/client_test.go, go/vt/vtctl/localvtctldclient/client.go, go/vt/vtctl/vtctldclient/client.go
This PR introduces a custom grpc resolver based on our `discovery.Discovery` interface for use in both vtctld and vtgate grpc communication in vtadmin.
There are two* main drawbacks to the current discovery/dialing approach in both vtctldclient and vtsql for vtadmin:
1. If there are N potential hosts to connect to, a given vtadmin process will pick exactly one and send all traffic for all requests to that host for its lifetime. This both unevenly distributes load and could in theory overwhelm the one host connected.
2. This one's only sort of a drawback, as we've taken steps in both #7709 and #9915 to detect and mitigate, but grpc's "design" "philosophy" is that it'll "handle" transient failures and try in the background (_forever ..._) to reestablish. This means if a vtctld/vtgate goes …
=> [vtadmin] custom discovery resolver

go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletmanager/vreplication/vplayer.go
There is a code-path in `applyEvents()` in `vplayer.go` where it waits on a throttler check and sleeps if it is determined that a wait is needed. If the context is cancelled here then it can loop infinitely. The vreplication controller tries to shutdown due to the context failure, but it waits for all streams to end. This results in a deadlock.
This PR checks for a context cancellation in between throttle checks.
Original PR: #9833 
#9827
=> Backport #9833: Check if context is cancelled in applyEvents() loop to avoid deadlocks

go/vt/vttablet/tabletmanager/tm_state.go
There is currently the possibility of an infinite loop inside `ChangeTabletType()` because we don't check for context cancellation inside an active polling loop. This PR adds the check.
Original PR: #9842 
#9838
=> Backport #9842: TabletManager: Check for context cancellation in loop within ChangeTabletType()

go/vt/vtadmin/vtsql/config.go, go/vt/vtadmin/vtsql/config_test.go, go/vt/vtadmin/vtsql/vtsql.go, go/vt/vtadmin/vtsql/vtsql_test.go
Now that custom resolvers exist, we can rely on the underlying grpc
balancer/resolver/clientconn state management to ensure we have
healthy connections (e.g., our resolver will return N hosts from
discovery, which grpc will transition to/among).
Spun up 2 gates in a static discovery configuration:
```
"vtgates": [
{
"host": {
"hostname": "localhost:15992"
}
},
{
"host": {
"hostname": "localhost:15991"
}
}
]
```
(NB: the default gRPC balancer is `pick_first`, so all dials will end up on `:15992`)
Next, I started vtadmin, ensured we were connected, and then killed the gate running on `:15922`. Here are the logs (_note because this is static discovery, the first gate is still in the list, hence the fail/success/fail/success pattern in the logs as gRPC tries the first host, then the next_): …
=> [vtsql] Remove vtsql.PingContext check from dial calls

examples/local/scripts/vtadmin-up.sh, go/cmd/vtadmin/main.go, go/vt/vtadmin/api.go, go/vt/vtadmin/grpcserver/server.go
This started off as a branch to more properly use the health server, but then ended up doing some misc cleanup and adding in channelz, which I wanted to do as well.
Main changes:
1. Add `--rbac` to the vtadmin-up example script.
2. Remove  `Services` from `grpcserver.Options`, since (a) we're gonna inspect the server for what services are registered and (b) there was no flag to ever let users set custom services anyway!! 🙈 
3. Add an option to enable [channelz](https://grpc.io/blog/a-short-introduction-to-channelz/), which is useful for debugging (I was playing around with this when working on the custom resolver stuff)
First, I started vtadmin without `--grpc-enable-channelz` and tried to run a client against it. As expected, it failed with:
```
F0405 09:07:41.291721   63470 main.go:22] …
```
=> [vtadmin] grpc healthserver + channelz

web/vtadmin/src/components/Spinner.module.scss, web/vtadmin/src/components/Spinner.tsx, web/vtadmin/src/components/placeholders/QueryErrorPlaceholder.test.tsx, web/vtadmin/src/components/placeholders/QueryErrorPlaceholder.tsx, web/vtadmin/src/components/placeholders/QueryLoadingPlaceholder.test.tsx, web/vtadmin/src/components/placeholders/QueryLoadingPlaceholder.tsx, web/vtadmin/src/components/routes/keyspace/Keyspace.tsx, web/vtadmin/src/components/routes/keyspace/KeyspaceShards.tsx, web/vtadmin/src/components/routes/keyspace/KeyspaceVSchema.tsx, web/vtadmin/src/setupTests.ts
This adds a /vschema route to view the (JSON) vschema for a keyspace. 
We can certainly experiment with less... JSON-y ways of presenting this data, but JSON is a good place to start.
Here's a couple of examples:
As part of this, I wanted to take a little time for loading and error handling state. To that end, I've added three new components: `Spinner`, `QueryLoadingPlaceholder`, and `QueryErrorPlaceholder`. In order to keep this PR small, I've only used them in this one view. I'll update everywhere else in a separate PR. 
I wanted to keep the loading and error placeholders in separate components for flexibility; components that define a more involved loading UX, like a skeleton table, can then just use the error placeholder on its own. Also... `Spinner` is dead simple and could probably …
=> [vtadmin-web] Add /vschema route to Keyspace detail view + QueryErrorPlaceholder and QueryLoadingPlaceholder components

go/vt/vtgr/controller/diagnose.go, go/vt/vtgr/controller/diagnose_test.go, go/vt/vtgr/controller/repair_test.go
This is an improvement on how we handle network partition. VTGR used to rely to "UNREACHABLE" state to determine network partition, it is not always reliable since when a node is really "partitioned", it will also possible to be unreachable. It introduced a race condition when the network is flapping: a partitioned VTGR will see everyone is OFFLINE and try to rebootstrap the group, if network recovered during the rebootstrap, VTGR will stop the functioning group incorrectly.
To address the issue, this PR mainly does two things:
1. Do not allow bootstrap unless we can reach expected number of nodes.
2. Do not allow rebootstrap unless we see all the nodes unless there is an override.
This helps VTGR to avoid some "false positive" diagnoses and hence avoid further incorrect repair …
=> Improve network partitions handling

go/test/endtoend/vreplication/vreplication_test.go, go/vt/binlog/binlogplayer/binlog_player.go, go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go, go/vt/vttablet/tabletmanager/vreplication/engine.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go, test/region_example.sh
https://github.com/vitessio/vitess/pull/9817 was calling `WithDDL.ExecIgnore()` which _does not_ run the initial WithDDL queries to create the `_vt` schema. We need  to use `WithDDL.Exec()` instead for that.  However after trying that we found that some tests were failing. This happens when a primary is coming up, semi-sync is enabled, but there are no other replicas. This causes the tablet to deadlock and never come up.
So we just add the "impossible" query from the previous PR to the `WithDDLInitialQueries` list so that we will always run all the `_vt` schema queries, when a workflow starts.
We will also need the change in #9861, to handle the code paths using `VReplicationExec`  and `VExec`. This PR was originally supposed to make that redundant (since we planned to create the `_vt` …
=> Change logic to reach desired _vt schema on vreplication startup

go/vt/vtadmin/api.go, go/vt/vtadmin/debug.go
Dynamic clusters currently make any api endpoint accessing `.clusters` or `.clusterMap` not thread safe, as the dynamic handler _could_ be mutating those structures as another endpoint attempts to access them. This fixes that by adding a mutex (abstracted away under the `getCluster(s)ForRequest`) and all other callsites updated to use that.
There's a second piece around duplicate clusters which @notfelineit is working on.
- #9544
- #10043
=> [vtadmin] threadsafe dynamic clusters

.github/docker/cluster_test_12/Dockerfile, .github/docker/cluster_test_18/Dockerfile, .github/workflows/cluster_endtoend_12.yml, .github/workflows/cluster_endtoend_18.yml, .github/workflows/cluster_endtoend_vtorc_8.0.yml, test/ci_workflow_gen.go, test/config.json
It is getting very hard to reproduce some of the flaky tests like `TestFallbackSecurityPolicy` (https://github.com/vitessio/vitess/issues/9946) and `TestReparenting` (https://github.com/vitessio/vitess/issues/9949). 
Shard 12 and 18 are being moved to the self-hosted runners so that the next time this failure occurs, we have the associated logs.
- https://github.com/vitessio/vitess/issues/9946
- https://github.com/vitessio/vitess/issues/9949
=> Move Shard 12 and 18 CI tests to self hosted runners

go/flags/endtoend/flags_test.go, go/vt/vttablet/tabletserver/tabletenv/config.go, go/vt/vttablet/tabletserver/tabletenv/config_test.go
The `--sanitize_log_messages` vttablet flag was errantly/accidentally removed in: https://github.com/vitessio/vitess/pull/9923
We re-add it here and ensure it's there and working in the `TestFlags` unit test. This was ultimately caused by me not adding (didn't know better at the time) a unit test for the new config option when adding it in https://github.com/vitessio/vitess/pull/9550. 
⚠️ NOTE: after realizing that the unit test wouldn't have caught this either... I added a new e2e test to check the command flags to be sure that we're intentional about changes and can prevent future accidental changes. This e2e test will be run as part of [the generic endtoend workflow](https://github.com/vitessio/vitess/blob/b979359f861d838ed3e0d7adc3cbba57a2975c7e/test/config.json#L26-L36). ⚠️ 
- …
=> Re-add sanitize_log_messages flag and add tests for flags

go/vt/vtctl/throttler.go
The new VReplication flows do not rely on these, which means we can delete them after vtworker is gone.
```
➜  local git:(andrew/vtctldserver-deprecate-throttler) ✗ vtctlclient --server ":15999" help | grep Throttler                  
Resharding Throttler:
(DEPRECATED) ThrottlerMaxRates -server <vtworker or vttablet>
(DEPRECATED) ThrottlerSetMaxRate -server <vtworker or vttablet> <rate>
(DEPRECATED) GetThrottlerConfiguration -server <vtworker or vttablet> [<throttler name>]
(DEPRECATED) UpdateThrottlerConfiguration -server <vtworker or vttablet> [-copy_zero_values] "<configuration protobuf text>" [<throttler name>]
(DEPRECATED) ResetThrottlerConfiguration -server <vtworker or vttablet> [<throttler name>]
➜  local git:(andrew/vtctldserver-deprecate-throttler) ✗ vtctlclient --server …
```
=> [vtctl] Deprecate Throttler RPCs

go/test/endtoend/vtgate/reservedconn/reconnect3/main_test.go, go/test/endtoend/vtgate/reservedconn/reconnect4/main_test.go, go/vt/vterrors/constants.go, go/vt/vtgate/scatter_conn.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tx_engine.go, test/config.json
This is backport PR of #10005 
This PR fixes issues with reserved connection when the vttablet or the underlying MySQL process is down.
The VTGate needs to understand the error codes/messages to redirect it to the new available tablet.
```
Issue 1: 
MySQL error: code 2002/2003 when the underlying MySQL is not available for connection.
Issue 2: 
Vttablet is down: ERROR 1105 (HY000): tablet: cell:"zone1" uid:100 is either down or nonexistent
Issue 3:
Vttablet tx engine is closed: tx engine can't accept new connections in state NotServing
```
In all the above scenarios the current reserved connection held should be dropped and a new one should be created by calling the ReserveExecute API to the tablet.
=> [13.0] Fix: reserved connection retry logic when vttablet or mysql is down

go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/semantics/analyzer.go
=> 13.0 fix: allow multiple distinct columns on single shards

go/vt/vtgate/planbuilder/physical/subquery_planning.go, go/vt/vtgate/planbuilder/route.go, go/vt/vtgate/planbuilder/testdata/select_cases.txt
This is backport of PR #9969 
This PR adds an empty map if the system table map is uninitialized in route.
- Fixes https://github.com/vitessio/vitess/issues/9653
=> [13.0] fix: dual query with exists clause having system table query in it

go/vt/vtgate/engine/fake_vcursor_test.go, go/vt/vtgate/engine/primitive.go, go/vt/vtgate/engine/route.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/scatter_conn.go, go/vt/vtgate/vcursor_impl.go
This is backport of #9968 
This PR ignore the session setting related to transaction and reserved connection and always go through the `EXECUTE` call on the tabletserver.
sequence does not require a connection most of the time and even if a new set of sequence cache is required it is executed using its little own transaction in tabletserver ([ignoring conn passed](https://github.com/vitessio/vitess/blob/2b5f72c5dd0411c3ff9da4517c4a8d32c4f57fc5/go/vt/vttablet/tabletserver/query_executor.go#L133,L146) and [own transaction](https://github.com/vitessio/vitess/blob/2b5f72c5dd0411c3ff9da4517c4a8d32c4f57fc5/go/vt/vttablet/tabletserver/query_executor.go#L563)) ignoring the connection id provided by the vtgate or a new one started with `Begin` or `Reserve` calls.
- Fixes #9851
=> [13.0] Fix: Sequence query to ignore reserved and transaction

doc/releasenotes/14_0_0_summary.md, go/test/endtoend/tabletmanager/throttler/throttler_test.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/throttle/throttler.go
- `/throttler/throttle` now accepts `ratio` query param, `float64` in the range `[0..1]`
Example usage:
```sh
curl -s 'http://127.0.0.1:15100/throttler/throttle-app?app=vreplication&duration=1h&ratio=0.2' | jq .
```
```json
{
"AppName": "vreplication",
"ExpireAt": "2022-04-06T10:19:52.897780736Z",
"Ratio": 0.2
}
```
- support `/throttler/throttled-apps` to get information about apps currently throttled.
Example output:
```sh
curl -s http://127.0.0.1:15100/throttler/throttled-apps | jq .
```
```json
{
"abusing-app": {
"Object": {
"AppName": "abusing-app",
"ExpireAt": "2032-04-03T09:18:30.331164282Z",
"Ratio": 1
},
"Expiration": 0
},
"vreplication": {
"Object": {
"AppName": "vreplication",
"ExpireAt": "2022-04-06T10:19:52.897780736Z",
"Ratio": 0.2
},
"Expiration": 0
}
}
```
- Tests to …
=> tablet lag throttler: small API improvements

go/vt/schemadiff/diff.go, go/vt/schemadiff/diff_test.go, go/vt/schemadiff/schema.go, go/vt/schemadiff/schema_test.go, go/vt/schemadiff/table.go, go/vt/schemadiff/types.go, go/vt/schemadiff/view.go, go/vt/schemadiff/view_test.go
Up till now [schemadiff](https://github.com/vitessio/vitess/pull/9719) allowed us to compare a table with another table, or a view with another view. This is [now in use](https://github.com/vitessio/vitess/pull/9772) in declarative schema changes.
This PR introduces schema comparisons.
A `Schema` is a collection of database objects -- right now this means tables and views. You may load a schema by:
- a list of well formed entities, or
- a list of well formed `Statement`s, or
- a list of `CREATE ...` queries, or
- a SQL blob that contains multiple `CREATE` queries
A schema is validated upon loading:
- can't have two objects with same name
- all view dependencies are resolved
As for the latter: `schemadiff` parses each view and analyze its dependencies. It validates that all dependencies …
=> schemadiff: load, normalize, validate and compare schemas

go/vt/discovery/tablet_picker.go, go/vt/discovery/utils.go, go/vt/vtctl/vtctl.go, go/vt/vttablet/tabletmanager/vreplication/engine.go, go/vt/wrangler/workflow.go, go/vt/wrangler/workflow_test.go
This changes the defaults for [tablet selection](https://vitess.io/docs/14.0/reference/vreplication/tablet_selection/) when choosing vreplication sources so that we use a `REPLICA` tablet when one is available and only fall back to using a `PRIMARY` tablet when necessary.
This is a good default as the vreplication workflow can have a very significant impact on the source tablet and should generally not be done on a `PRIMARY` tablet when possible since it's likely serving production traffic.
- ???
=> Prefer using REPLICA tablets when selecting vreplication sources

go/cmd/vtadmin/main.go, go/vt/vtadmin/api.go, go/vt/vtadmin/api_test.go, go/vt/vtadmin/cluster/dynamic/api.go, go/vt/vtadmin/cluster/dynamic/cluster.go, go/vt/vtadmin/cluster/dynamic/cluster_test.go, go/vt/vtadmin/cluster/dynamic/interceptors.go, go/vt/vtadmin/http/api.go, misc/errcheck_excludes.txt
This refactor enables the specifying of a dynamic cluster via [grpc metadata](https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md) in addition to an http cookie.
**NOTE** this deprecates the `--http-enable-dynamic-clusters` flag in favor of the `--enable-dynamic-clusters`. After we've deployed this, I'll circle back around to clean up the flag.
- `curl`-ing with a cookie still works, as before
- grpc demo: https://gist.github.com/ajm188/5b5c8ba0cc5660298697e0f762081d45
The first thing we do is extract as much of the non-"related to serving an http request" code out of `ServeHTTP(w, r)` as possible, moving it to `package dynamic` (in `vitess.io/vitess/go/vt/vtadmin/cluster/dynamic`). Now, the ServeHTTP handler "simply":
1. says "hey, here's a cookie, can you get me a …
=> [vtadmin] grpc dynamic clusters

go/cmd/vtadmin/main.go
After #10050, dynamic clusters are no longer http-only, and as a result you should use the less now–confusingly-named `--enable-dynamic-clusters` flag.
#10050
=> [vtadmin] Remove deprecated dynamic cluster flag

go/vt/vterrors/constants.go, go/vt/vtgate/scatter_conn.go
Case: when a connection to VTGate has reserved connection and no transaction open on it.
This PR removed the specific error message check when vtgate receives `code_unavailable` grpc message from API call to vttablet. This will ensure that the query is routed through gateway and will reach the healthy tablet to serve the query.
=> Always reset reserved shard session on CODE_UNAVAILABLE

go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/testdata/select_cases.txt
This PR fixes https://github.com/vitessio/vitess/issues/9889.
=> Fix Gen4 only_full_group_by regression

go/vt/vtadmin/api_test.go, go/vt/vtadmin/cluster/config.go, go/vt/vtadmin/cluster/dynamic/cluster.go, go/vt/vtadmin/cluster/dynamic/cluster_test.go
This PR changes the unmarshalling technique used for dynamic cluster configs, to support a fully-configured dynamic cluster with parity to what you can do on the CLI.
The most notable changes for end users are:
- you must specify an `id` key rather than a `name` key. you _should_ also specify a `name` key, but it's not strictly required.
- you must specify your discovery implementation name. this means you can use dynamic clusters with _other_ discovery implementations (like consul!) "for free" 
- when using dynamic discovery with a dynamic cluster (boy that's a lotta "dynamic"), you are technically going through a double layer (mmmm, burritosssss) of json unmarshalling, which means your `discovery-dynamic-discovery` option must be properly quoted and escaped (see the tests).
Below are …
=> [vtadmin] full dynamic cluster config

go/cmd/vtexplain/vtexplain.go
This Pull Request makes the `--planner-version` flag of VTExplain case-insensitive. Previously, when running a VTExplain command with the default planner-version value, the following error would show up:
```
ERROR: invalid value specified for planner-version of 'gen4' -- valid values are V3 and Gen4
```
This was happening because the default value is set to `gen4` instead of `Gen4`. The behavior used in VTGate regarding case insensitivity was copied to VTExplain.
=> Case-insensitive planner-version flag in VTExplain

go/test/endtoend/cluster/vtctlclient_process.go
For whatever reasons, we've been seeing more InnoDB Deadlock errors when getting the workflow status for VDiff lately (e.g. [here](https://github.com/vitessio/vitess/runs/5996959498?check_suite_focus=true) and virtually all failures for [the workflow](https://github.com/vitessio/vitess/actions/workflows/cluster_endtoend_vreplication_across_db_versions.yml)). This work adds retry support (up to 10 times) when this occurs, with a sleep of 1 second in between tries to give the database state time to clear up.
> I suspect that some recent changes have made these deadlocks more likely — at least in our VReplication e2e tests where we only have `PRIMARY` tablets and we do a lot of VReplication workflows in quick succession — especially with MySQL 8.0 as the usage of MySQL 8 on the target …
=> Address flakiness of vreplication v2 workflow test

.github/pull_request_template.md
I've long found it unsatisfying that the "Should this PR be backported?" item in the PR template is not easily check-off-able. (I always check it off but add a "no" comment, lol.) So I tweaked the wording to be a bit less ambiguous + to satisfy such completionist tendencies. 
N/A
N/A
=> Tweak backport checklist item wording in pull_request_template.md

go/vt/vtgate/planbuilder/physical/route_planning.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt
When using a vindex is difficult because the necessary predicates are hidden behind `OR`, we can try and see if the `OR`s can be merged into an `IN` instead, which is easier to plan efficiently.
=> Gen4 feature: optimize OR queries to IN

go/vt/mysqlctl/fakemysqldaemon/fakemysqldaemon.go, go/vt/vttablet/tabletmanager/replmanager.go, go/vt/vttablet/tabletmanager/rpc_replication.go, go/vt/vttablet/tabletmanager/rpc_replication_test.go
=> Fix the race between PromoteReplica and replication manager tick (#9859) - release 12

web/vtadmin/package-lock.json, web/vtadmin/package.json
This updates vtadmin-web to [react-scripts@5.0.1](https://github.com/facebook/create-react-app/releases/tag/v5.0.1). This implicitly addresses the [CVE](https://github.com/advisories/GHSA-xvch-5gv4-984h) in the transient [minimist](https://www.npmjs.com/package/minimist) dependency. 
Nothing interesting-to-us in the [release notes ](https://github.com/facebook/create-react-app/releases/tag/v5.0.1) for this version. I verified that running, building, etc. all still works. 
N/A
N/A
=> [vtadmin-web] Update to react-scripts@5.0.1

go/vt/vttablet/tabletmanager/vreplication/controller_test.go, go/vt/vttablet/tabletmanager/vreplication/engine.go, go/vt/vttablet/tabletmanager/vreplication/engine_test.go, go/vt/wrangler/fake_dbclient_test.go
In 13.0 we added a migration sql to change existing vreplication metadata.
We should not need that any longer.
Fixes #9514
Related to #9497 
=> remove changeMasterToPrimary, we no longer need it

go/vt/mysqlctl/reparent.go, go/vt/vtctl/grpcvtctldserver/endtoend/init_shard_primary_test.go, go/vt/wrangler/testlib/emergency_reparent_shard_test.go, go/vt/wrangler/testlib/planned_reparent_shard_test.go
Rename the column for new installs where table will get created
Add an alter statement for upgrades
Change all places where we access the column to use the new name
Fixes #8619 
Related #9439
=> rename master_alias to primary_alias in reparent_journal table

go/mysql/flavor.go, go/mysql/flavor_filepos.go, go/mysql/flavor_mariadb.go, go/mysql/flavor_mysql.go, go/mysql/flavor_mysqlgr.go, go/vt/mysqlctl/replication.go
After https://github.com/vitessio/vitess/pull/9512 we always attempted to start the replication `SQL_Thread`(s) when waiting for a given position. The problem with this, however, is that [if the `SQL_Thread` is running but the `IO_Thread` is not then the tablet repair does not try and start replication on a replica tablet](https://github.com/planetscale/vitess/blob/ef7363e918e5c7093d72f15471f4c0d408ac0d10/go/vt/vttablet/tabletmanager/replmanager.go#L106-L117). So in certain states such as when initializing a shard, replication may end up in a non-healthy state and never be repaired.
This changes the behavior so that:
1. We only attempt to start the `SQL_Thread`(s) if it's not already running
2. If we explicitly start the `SQL_Thread(s)` then we also explicitly reset it to what it was …
=> Only start SQL thread temporarily to WaitForPosition if needed

go/vt/vtadmin/api.go, go/vt/vtadmin/api_test.go, go/vt/vtadmin/cluster/cluster.go
This is part 1 of a preparatory refactor to get caching in front of /schema related endpoints (which I'm writing up an issue for and will post here when I have it). The main effort is to get all of the fetching logic happening at the cluster-level instead of the api-level, so that we can have per-cluster caches.
- TK
- (my first pass at this refactor actually broke several schema-related tests, which makes me pretty confident i've got it right this time -- also I tested locally)
=> [vtadmin] Refactor api.getSchemas => cluster.GetSchemas

go/vt/schemamanager/tablet_executor.go
In `ApplySchema`, there is a check for big schema changes. This is a legacy check from a time when we did not support online DDL. Big-schema-changes is _mostly_ skipped when there are online DDLs. However, one step is not skipped, which is `GetSchema`. 
Currently, we first `GetSchema`, then iterate all DDLs, and for each DDL check if it is online or not, and if not  - whether it is a "big change".
When all DDLs are online, the `GetSchema` step is wasteful. It reads all tables with some metadata.
In this PR, we first do a preliminary check to see whether there is at all any non-online DDL. If there is at least one non-online DDL, we proceed with `GetSchema`. But if all DDLs are online - we skip `GetSchema` altogether.
- #6926 
-   [ ] "Backport me!" label has been added if this change …
=> OnlineDDL: skip GetSchema where possible

examples/local/401_teardown.sh, examples/local/scripts/vtadmin-down.sh, examples/local/scripts/vtadmin-up.sh, web/vtadmin/package-lock.json, web/vtadmin/package.json
A few changes in this one with the goal of making VTAdmin more straightforward to run as part of the "Get Started" example:
- Instead of running vtadmin-web with webpack-dev-server, which starts up with hot reloading (unnecessary) and also hogs the foreground (annoying), this does a production build of the vtadmin-web static files and then serves them (with [serve](https://www.npmjs.com/package/serve)) in the background. (I don't feel strongly about using the `serve` library, and tbh I resent that it added 950+ lines to package-lock.json, but I think it's good enough for now.)
- Adds `vtadmin-down.sh` + calls it from `401_teardown.sh`
Now running VTAdmin with the local example is 𝒜 𝒮𝒾𝓂𝓅𝓁𝑒 𝑀𝒶𝓉𝓉𝑒𝓇 of `./scripts/vtadmin-up.sh`, …
=> [vtadmin] Improve vtadmin-{up,down}.sh scripts for the local example

doc/releasenotes/13_0_0_release_notes.md
Signed-off-by: Phani Raj <phani@planetscale.com>
Updates release notes to add the new `caller_id` parameter to `ApplySchema`
=> add caller_id to 13.0.0 release notes

tools/shell_functions.inc
For more complex integer operations in most modern shells you should use double parens (shell uses `let` builtin) or double brackets (shell uses `test` builtin) to ensure proper variable expansion and expression evaluation (we explicitly use [`bash`](https://www.gnu.org/software/bash/manual/html_node/Bash-Builtins.html) today in the build scripts).
In this case the lack of determinism and potential errors in [the go version check](https://github.com/planetscale/vitess/blob/b5ca7a6326d54d52842f1571f8a100b4497f7d1b/tools/shell_functions.inc#L20-L35) comes from expansion of variables w/o a declared type (`declare -i number` or `typeset -in`) or implicit type via e.g. `let foo=${bar}+0`. So if we did not get a valid integer from any of the regexp capture groups (in my case I had go 1.18 …
=> Make go version check reliable by using double brackets

go/vt/vtgate/planbuilder/aggregation_pushing.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/tpch_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
Adds the capability of building aggregation plans on top of derived tables.
-   [ ] "Backport me!" label has been added if this change should be back ported
=> feat gen4: allow pushing aggregations inside derived tables

go/mysql/flavor.go, go/mysql/flavor_filepos.go, go/mysql/flavor_mariadb.go, go/mysql/flavor_mysql.go, go/mysql/flavor_mysqlgr.go, go/vt/mysqlctl/replication.go
**:warning: This does not require/warrant another 13.0 patch release but rather should be included in the next patch release whenever it's made :warning:** 
After https://github.com/vitessio/vitess/pull/9512 we always attempted to start the replication `SQL_Thread`(s) when waiting for a given position. The problem with this, however, is that [if the `SQL_Thread` is running but the `IO_Thread` is not then the tablet repair does not try and start replication on a replica tablet](https://github.com/planetscale/vitess/blob/ef7363e918e5c7093d72f15471f4c0d408ac0d10/go/vt/vttablet/tabletmanager/replmanager.go#L106-L117). So in certain states such as when initializing a shard, replication may end up in a non-healthy state and never be repaired.
This changes the behavior so that:
1. We only …
=> Backport: Only start SQL thread temporarily to WaitForPosition if needed

go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go, go/vt/schemadiff/types.go
Diffing partitions is a complex topic. There can be scenarios where a change of partitioning scheme required an entire rebuild of the table (e.g. change of number of `HASH` partitions), and cases where optimally one could get by with only modifying some of the partitions (e.g. `COALESCE` two partitions into one).
Normally, when we see a diff of partitions, we just invoke an `ALTER TABLE... PARTITION BY...` with the entire new partitioning scheme. The idea? Even a `COALESCE` for two partitions out of `200` is a blocking schema change. As we push forward Online DDL, we are opinionated that it's better to rebuild the entire table, online, than just `2` partitions out of `200`, in a blocking operation.
However, there are exceptions to this.
A common partitioning scheme that does not require …
=> schemadiff: support for RangeRotationStrategy diff hint

.github/CODEOWNERS
As more people have gotten up to speed with messaging, I think it makes sense to be specific in CODEOWNERS. This incidentally also removes since deleted helm permissions
=> CODEOWNERS: specify messaging related folders

go/vt/sysvars/sysvars.go, go/vt/vtgate/executor.go, go/vt/vtgate/executor_set_test.go
This PR avoids using the reserved connection for Show query and handles `show variables` by doing variable replace at vtgate level.
=> Avoid enabling reserved connection on show query

go/vt/sqlparser/ast_format.go, go/vt/sqlparser/ast_format_fast.go, go/vt/sqlparser/tracked_buffer_test.go
Fixes https://github.com/vitessio/vitess/issues/10143, requested by @shlomi-noach 
=> sqlparser: fix canonical formatting for enums

go/vt/vterrors/constants.go, go/vt/vtgate/scatter_conn.go, go/vt/vtgate/scatter_conn_test.go, go/vt/vttablet/tabletserver/tx_pool.go
This PR fixes an issue with reserved connection session reset when the reserved connection is blocked by connection_killer for being idle for 'X' allocated time. As the connection is now getting closed, the query received on that session should be able to ask for a new reserved connection to execute the query on the vttablet.
=> fix: handle reserved connection reset when tx killer has locked the connection

go/vt/schemadiff/diff_test.go, go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go, go/vt/schemadiff/types.go, go/vt/schemadiff/view.go, go/vt/schemadiff/view_test.go
`Entities() (from Entity, to Entity)` return from "from" and "to" entities for the diff.
- When the diff is e.g. a `AlterTableEntityDiff`, this returns both the "from"'s CreateTable and the "to"s CreateTable.
- if the diff is a `CreateTableEntityDiff` then there's only a "to" ; "from" is `nil`.
- if the diff is a `DropTableEntityDiff` then there's only a "from" ; "to" is `nil`.
this is symmetrical in View diffs.
cc @dbussink
=> schemadiff: EntityDiff has a 'Entities() (from Entity, to Entity)' function

go/test/endtoend/messaging/main_test.go, go/test/endtoend/messaging/message_test.go, go/test/endtoend/vtgate/godriver/main_test.go, go/vt/vttablet/tabletserver/messager/message_manager.go, go/vt/vttablet/tabletserver/messager/message_manager_test.go, go/vt/vttablet/tabletserver/planbuilder/testdata/schema_test.json
There's conditional behavior and code paths in the message manager when the number of receivers is 0. The main mutex and the stream mutex locks are used to ensure overall consistency. But:
1. The order that those locks are taken in was not enforced or consistent
2. There was a gap in the poller between when the 0 receiver code path was checked — specifically that it was NOT 0 — and the main mutex lock was taken to ensure that this invariant holds during the polling run here: https://github.com/vitessio/vitess/blob/c9853797bda8752202583695133c41a25d390930/go/vt/vttablet/tabletserver/messager/message_manager.go#L752-L787
In [`unsubscribe()` we have the main mutex](https://github.com/vitessio/vitess/blob/c9853797bda8752202583695133c41a25d390930/go/vt/vttablet/tabletserver/messager/message_man …
=> Avoid deadlocks related to 0 receiver behavior

go/test/endtoend/vtgate/queries/subquery/subquery_test.go, go/vt/vtgate/engine/route.go, go/vt/vtgate/engine/route_test.go, go/vt/vtgate/engine/routing.go, go/vt/vtgate/planbuilder/gen4_planner.go, go/vt/vtgate/planbuilder/physical/subquery_planning.go, go/vt/vtgate/planbuilder/routeGen4.go, go/vt/vtgate/planbuilder/testdata/select_cases.txt
Queries that follow the following pattern - 
```mysql
select exists(select * from foo where some_field=some_value)
```
The table `foo` would has a lookup vindex on `some_field` and there are no matching rows for `some_value`. What Vitess would do when no shards could be found to route to is to return an empty result. This is correct for most cases, but not always. The query above would return an empty result instead of a `0`.
- Fixes #10144 
-   [x] "Backport me!" label has been added if this change should be backported YES
=> Fix for empty results when no shards can be found to route to

go/test/endtoend/reparent/newfeaturetest/reparent_test.go, go/vt/mysqlctl/replication.go, go/vt/vtctl/grpcvtctldserver/server_slow_test.go, go/vt/vtctl/grpcvtctldserver/server_test.go, go/vt/vtctl/reparentutil/emergency_reparenter_test.go, go/vt/vtctl/reparentutil/replication.go, go/vt/vtctl/reparentutil/replication_test.go
Backport of #10148 to release-13.0
=> Do not mutate replication state in WaitSourcePos and ignore tablets with SQL_Thread stopped in ERS (#10148) - Release 13.0

go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go
`NewCreateTableEntity` now normalizes a table upon creation, modifying its `CreateStatement` into a canonical form.
This PR is a first in several iterations. This PR ensures all keys are named. For example, in the following statement:
```sql
create table t2 (id int primary key, i int, key (i))
```
the key over `i` is not named.
`normalize()` will set a name to the key. The name is chosen in similar way to MySQL's algorithm:
- Try the name of first column covered by the key, `i` in our example
- If that name is taken, try `i_2`
- If that name is taken, try `i_3`
- etc.
unit tests added to both validate and explain the logic.
Note that normalization edits the `CreateTable` statement in-place.
=> schemadiff: normalize() table. Set names to all keys

go/vt/schemadiff/diff_test.go, go/vt/schemadiff/schema.go
`Schema.Apply()` returns a new, likely modified, schema. But it must not affect the receiver schema.
This PR:
- Uses query export/import to ensure the two schemas do not share any pointers/maps/slices
- Adds tests to validate schema is unaffected by `Apply()`
=> schemadiff: schema is immutable through Apply()

go/vt/sqlparser/ast_format.go, go/vt/sqlparser/ast_format_fast.go, go/vt/sqlparser/tracked_buffer_test.go
In case of a `CREATE TABLE` statement, the options are rendered directly and the TableOptions logic is not used. This means it doesn't handle character set or collation options like an `ALTER TABLE` does.
This updates the logic to be consistent with column level settings and with `ALTER TABLE`.
Part of extension work after https://github.com/vitessio/vitess/pull/9719
=> sqlparser: Handle case sensitive AST option for table options

doc/releasenotes/14_0_0_summary.md, go/test/endtoend/onlineddl/singleton/onlineddl_singleton_test.go, go/vt/vttablet/onlineddl/executor.go
When a migration runs with [-singleton-context](https://vitess.io/docs/13.0/user-guides/schema-changes/ddl-strategy-flags/) ddl strategy flag, and with context `A`, then another migration with `-singleton-context` can only be submitted if it has same context `A`, and cannot be submitted if it has context `B`. Note, the submission itself returns with an error.
We want to have better user experience when it comes to [reverts](https://vitess.io/docs/13.0/user-guides/schema-changes/revertible-migrations/). Reverts may be long running and are allowed to run concurrently to other migrations.
A REVERT can run without a `-singleton-context` flag. In fact, this is the canonical way of running it. So we do not fail submitting a REVERT even if there are pending migrations.
However, what happens when …
=> Relax singleton-context constraint for pending non-singleton-context reverts

go/vt/vtgate/engine/routing.go, go/vt/vtgate/planbuilder/route_test.go
This changes the engine opcode list to be according to most preferable first.
Based on feedback from #10151
=> refactor: move the Subshard opcode

go/vt/sqlparser/ast_format.go, go/vt/sqlparser/ast_format_fast.go, go/vt/sqlparser/sql.go, go/vt/sqlparser/sql.y, go/vt/sqlparser/tracked_buffer_test.go, go/vt/vtgate/engine/cached_size.go
This value has different casing in the canonical format from MySQL, so the parser here should not always uppercase the value assigned for the engine.
Part of extension work after https://github.com/vitessio/vitess/pull/9719
=> Emit the ENGINE field for table options as case sensitive

go/vt/vtadmin/cluster/resolver/resolver.go, go/vt/vtadmin/cluster/resolver/resolver_test.go, go/vt/vtadmin/internal/backoff/backoff.go, go/vt/vtadmin/internal/backoff/backoff_test.go, go/vt/vtadmin/internal/rand/rand.go, go/vt/vtadmin/vtctldclient/config_test.go, go/vt/vtadmin/vtsql/config_test.go
This PR updates the cluster discovery resolver to make `ResolveNow` a non-blocking call, by signaling on a channel to watcher goroutine which is continually updating the address list for a cluster component with backoff on failure. It's largely a port of grpc-go's dns-resolver with the "do a dns lookup" replaced with "make a discovery call". (See [dns_resolver](https://github.com/grpc/grpc-go/blob/3bf6719fc8ab5dac43b8494fcdc7e892efde6ea1/internal/resolver/dns/dns_resolver.go#L209) for reference).
The only notable changes are:
* I added extra backoff strategies, namely "linear" (which does `cur + multiplier` instead of exponential's `cur * multiplier`) and "none" (which never backs-off).
* I fixed the backoff for exponential and linear, to prevent jittering from exceeding the configured …
=> [vtadmin] non-blocking resolver

go/test/endtoend/tabletmanager/tablet_test.go, go/vt/vttablet/tabletmanager/tm_state.go, go/vt/vttablet/tabletmanager/tm_state_test.go
SetServingType can result in error. Although we have forever retries to fix these transient errors but, under certain conditions these errors are non-transient (see https://github.com/vitessio/vitess/issues/10145).
There is no way to distinguish between retry (transient) and non-retryable errors, therefore we will always return error from 'SetServingType' and 'applyDenyList' to our client. It is up to them to handle it accordingly.
UpdateLock is called from 'ChangeTableType', 'Open' and 'RefreshFromTopoInfo'. For 'Open' and 'RefreshTopoInfo' we don't need to propagate error to client hence no changes there but we will propagate error from 'ChangeTableType' to client.
This is a bug. I will discuss with team if it needs a back …
=> Propagate error from 'updateLocked' to client

.github/workflows/cluster_endtoend_vtgate_general_heavy.yml, .github/workflows/cluster_endtoend_vtgate_vindex_heavy.yml, .github/workflows/cluster_endtoend_xb_backup.yml, go/test/endtoend/cluster/cluster_process.go, go/test/endtoend/cluster/vtgate_process.go, go/test/endtoend/vtgate/prefixfanout/main_test.go, test/ci_workflow_gen.go, test/config.json
The `vtgate_vindex`->`prefixfanout` tests have been flaky, particularly when GitHub Actions is slower/has more resource contention than usual. 
In this PR we make the following changes:
1. Add code to wait for the `vttablet`s to be seen as healthy and serving (in `TestMain`) by the `vtgate` before executing any tests
- Correct the `WaitForTabletsToHealthyInVtgate()` function as it was always waiting for 1 `replica` tablet in each shard to be seen as healthy and serving in the `vtgate` but `replica` tablets are _optional_ and we have none of them in the cluster used for the `prefixfanout` test
2. Mark the `vtgate_vindex` test as heavy since even with a long wait we still seemed unable to have mysqld start at times
- Although I later realized that this was caused by the …
=> Address flakiness of vtgate_vindex.prefixfanout tests

go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go, go/vt/sqlparser/ast_format.go, go/vt/sqlparser/tracked_buffer_test.go
In the parser when generating a query, unsigned and zerofill are always rendered lowercase in canonical MySQL output.
Additionally, zerofill is deprecated for integer values similar to the length. Zerofill does still have a side effect though which is that it also does mark the field as unsigned.
The normalization now removes the zerofill attribute, but sets unsigned to true if it was used to keep this side effect.
Also see https://dev.mysql.com/doc/refman/8.0/en/numeric-type-attributes.html for the reference documentation on how this works.
- #10203 
=> Fix handling of unsigned and zerofill in parser and normalization

go/test/endtoend/onlineddl/vrepl_stress_suite/onlineddl_vrepl_stress_suite_test.go
Discussion: https://github.com/vitessio/vitess/issues/8969#issuecomment-1120394834
Gonna create this PR as `Draft` and run `vrepl_stress_suite` multiple times to see if this fixes the flakiness. The tests have been stable for months, and recently became flaky. First suspicion is GitHub CI runners getting slower.
https://github.com/vitessio/vitess/issues/8969#issuecomment-1120394834
=> CI: fix flaky test via extended timeout in vrepl_stress_suite

go/test/endtoend/cluster/vtgate_process.go, go/test/endtoend/vtgate/queries/foundrows/found_rows_test.go
The test `TestFoundRows` runs queries that are dependent on schema tracking running successfully before the queries are executed. This however, makes the test flaky since some times, schema tracking doesn't run before we execute the queries, which leads to errors.
This PR fixes this issue, by waiting for the schema-tracking to run and mark the table used as authoritative before we run any queries against it.
-   [x] "Backport me!" label has been added if this change should be backported -> Forward port required
=> Flaky test fix: TestFoundRows

go/vt/vtadmin/cluster/cluster.go, go/vt/vtadmin/cluster/cluster_test.go, go/vt/vtadmin/cluster/config.go, go/vt/vtadmin/testutil/cluster.go, go/vt/vtadmin/vtsql/config.go, go/vt/vtadmin/vtsql/vtsql.go, go/vt/vtadmin/vtsql/vtsql_test.go, go/vt/vtgate/vtgateconn/vtgateconn.go
This builds on #10233, but for vtsql this time (it's based on the same branch, so it should be merged _after_ that PR).
It's the same changes, applied in the same order (config options, context plumbing through the call stack, etc etc) but applied to the `DB` interface and `VTGateProxy` type instead. In addition:
- make `vtgateconn`'s private `drivers` map thread safe. this was tripping the race detector during tests (see 69cf2f2975585025aea1cc7ab58d35aa1d5b4dfa)
=> [vtadmin] Removing explicit Dial-ing for vtsql proxy

examples/legacy_local/scripts/vtctld-up.sh, examples/local/scripts/vtctld-up.sh, go/cmd/vtctl/vtctl.go, go/cmd/vtworker/vtworker.go, go/flags/endtoend/flags_test.go, go/test/endtoend/backup/transform/backup_transform_utils.go, go/test/endtoend/backup/vtbackup/main_test.go, go/test/endtoend/backup/vtctlbackup/backup_utils.go, go/test/endtoend/recovery/pitr/shardedpitr_test.go, go/test/endtoend/recovery/pitrtls/shardedpitr_tls_test.go, go/test/endtoend/recovery/shardedrecovery/sharded_recovery_test.go, go/test/endtoend/recovery/unshardedrecovery/recovery.go, go/test/endtoend/reparent/emergencyreparent/ers_test.go, go/test/endtoend/reparent/newfeaturetest/reparent_test.go, go/test/endtoend/reparent/utils/utils.go, go/test/endtoend/sharding/initialsharding/sharding_util.go, go/test/endtoend/sharding/mergesharding/mergesharding_base.go, go/test/endtoend/sharding/resharding/resharding_base.go, go/test/endtoend/vault/vault_test.go, go/test/endtoend/vtorc/utils/utils.go, go/vt/vtctld/vtctld.go, go/vt/vttablet/tabletmanager/rpc_replication.go, go/vt/vttablet/tabletmanager/rpc_replication_test.go
We found a problem with the current implementation of the durability_policy flag. This flag only takes one value for the vtctld binary. This is incorrect, because people can be running multiple keyspaces each having its own different durability_policy. Since vtctld is a global component, we cannot require the user to create a vtctld for each keyspace having different durability_policies.
The proposed solution is to store the durability_policy in the topo server instead of having it as a flag. This change however will also require a two release upgrade process. In release-13 we are using the flag `enable_semi_sync` flag, and we want to continue doing that in release-14. We also want to deprecate the durability_policy flag. 
This PR reintroduces the enable_semi_sync flag and its usage. It …
=> Revert semi_sync change to reintroduce enable_semi_sync and remove durability_policy

go/vt/schemadiff/schema.go, go/vt/schemadiff/schema_test.go, go/vt/schemadiff/table.go, go/vt/schemadiff/view.go
This adds a number of convenience methods to schemadiff that are useful when working with schema related objects and inspecting what a schema looks like.
It avoids having to do some casts often when for example you only care about getting a table from a schema (and not views).
The diff methods are useful when getting the underlying object so you don't have to grab it with `Statement()` and then cast it again to the real underlying `sqlparser` object.
#10203 
=> Add convenience functions for working with schemadiff objects

go/vt/sqlparser/ast_format.go, go/vt/sqlparser/tracked_buffer_test.go
Like other character sets, these are lowercase in canonical MySQL output, so that should be matched here.
#10203 
=> Fix formatting of character set annotation on string literals

go/vt/vtgate/evalengine/eval_result.go, go/vt/vtgate/evalengine/integration/comparison_test.go
Did you know that `float64` to `uint64` conversion is implementation defined behavior in Go? That's right. `float64(-2.0)` returns different results between x64 and an M1 Mac using ARM64. @systay noticed this.
Fortunately for us it is also undefined behavior in C and C++ so I've reverse engineered the trick they're using there by trial and error: it's the most obvious solution. Explained below:
```
// We want to convert a float64 to its uint64 representation.
// However, the cast `uint64(f)`, when f < 0, is actually implementation-defined
// behavior in Go, so we cannot use it here.
// The most noticeable example of this are M1 Macs with their ARM64 chipsets, where
// the underflow is clamped at 0:
//
//		GOARCH=amd64 | uint64(-2.0) == 18446744073709551614
// 		GOARCH=arm64 | uint64(-2.0) …
```
=> evalengine: proper float to integer conversions

web/vtadmin/package.json
In https://github.com/vitessio/vitess/pull/10081 I changed the vtadmin-web port in `./vtadmin-up.sh` from `3000` to `14201`, and updated vtadmin-api's `--http-origin` flag accordingly. 
I did not, however, remember to update the port in this `npm run local` script, which means it was still running on `3000` and then getting CORS errors when configured to request a vtadmin-api started by way of `./vtadmin-up.sh`. 
This fixes a regression after https://github.com/vitessio/vitess/pull/10081
N/A
=> [vtadmin-web] Add `PORT=14201` to 'npm run local' to avoid CORS errors in dev mode

go/vt/vttablet/endtoend/transaction_test.go, go/vt/vttablet/tabletserver/query_executor.go
This is a bug where long running streaming queries with transaction fails to shutdown gracefully. Previously during execStreamSQL we were adding query to OLAP queryList regardless of whether it is transactional or not. With this change we put streaming transaction queries to stateful list, which result it in graceful shutdown of these queries during handleShutdownGracePeriod  if it exceeds the grace period.
I decided to pass isTransaction as parameter to execStreamSQL because I don't want execStreamSQL to have a logic of isTransaction. Let me know if you feel otherwise.  …
=> check for connectionID before adding to querylist

.github/workflows/cluster_endtoend_xb_backup.yml, .github/workflows/cluster_endtoend_xb_recovery.yml, test/templates/cluster_endtoend_test.tpl
The [XtraBackup 2.4.26 release](https://docs.percona.com/percona-xtrabackup/2.4/release-notes/2.4/2.4.26.html) fixes [the SEGFAULTs we encountered with 2.4.25](https://jira.percona.com/browse/PXB-2756), which led to us [pinning the version at 2.4.24 temporarily](https://github.com/vitessio/vitess/pull/10194).
ℹ️ NOTE: I'm leaving the version pinning code in place so that we can easily pin it again in the future if needed (it also provides a template for how we could pin the version of other packages).
- Follow-up to: https://github.com/vitessio/vitess/pull/10194
=> Revert to using XtraBackup 2.4-latest now that 2.4.26 is out

go/vt/sqlparser/ast_format.go, go/vt/sqlparser/tracked_buffer_test.go
These do not change casing in MySQL so they should not be canonicalized to uppercase in the canonical uppercase form either.
This also will lead to spurious incorrect diffs with schemadiff potentially.
Found when working on #10203
=> Fix formatting for function expressions and booleans

go/vt/vtgate/executor.go, go/vt/vttablet/tabletserver/tabletserver.go
We were experiencing `fatal error: concurrent map iteration and map write` panic on `bind_variables` access in logstats. 
Changed the logic to copy `bind_variables` in the planning phase to logstats.
=> fix: copy bindvariables in logstats

go/test/endtoend/onlineddl/ghost/onlineddl_ghost_test.go, go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go, go/vt/vttablet/tabletserver/repltracker/writer.go, go/vt/vttablet/tabletserver/throttle/throttler.go
#10198 introduced `--heartbeat_on_demand_duration` flag. The flag was added to multiple `onlineddl` `endtoend` testing workflows. A couple, but specifically `onlineddl_vrepl` started exhibiting recurring failures.
The flag is opt-in so no hard done to anyone. So no pressure other than CI jobs failing. https://github.com/vitessio/vitess/pull/10236 was first merged to revert the CI changes.
I was happy to then be able to reproduce the issue on a local dev env. As always with GitHub CI, it's about thresholds and execution speed, and I was able to figure out a configuration setup that makes the problem reproducible.
I'm also happy to have pinpointed the problem. There was a race condition.
- on one hand, `RequestHeartbeats()` calls were selectively accepted/dropped - as expected
- on the …
=> Fix to --heartbeat_on_demand_duration race condition

go/vt/vtgate/engine/set_test.go
These tests are specific for behavior on MySQL 5.7 and right now depend on the default defined in the sqlparser.
In order to be able at some point in the future change the default sqlparser version, these tests should be explicit which behavior is verified against which MySQL version.
There are already tests that explicit test things for MySQL 8.0, so also explicitly set MySQL 5.7 if we need to as well.
Found when working on #10203 and looking at what it takes to update the default sqlparser version at some point in the future.
=> Make the tests explicit for the SET variables for MySQL 5.7

go/test/endtoend/vtgate/queries/union/union_test.go, go/vt/vtgate/engine/concatenate.go, go/vt/vtgate/engine/concatenate_test.go, go/vt/vtgate/engine/fake_vcursor_test.go, go/vt/vtgate/engine/primitive.go, go/vt/vtgate/vcursor_impl.go
Engine primitives communicate with each other all the time. When they do, the context passed between them is not passed explicitly as a method call argument as is normally done in golang code. Instead it's baked into one of the fields of the `vcursor` instance that engine primitives receive when executing.
The problem with this setup is when we concurrently call multiple children, like UNION does. The way that the context was shared between primitives means that sometimes, by mistake, one primitive would cancel another primitives context.
This manifested as intermittent errors when doing queries containing lots of UNION code. …
=> fix: concatenate engine primitive

go/test/endtoend/cluster/vttablet_process.go
This should reduce some CI flakes due to ephemeral issues. For example, I've periodically seen failures in `TestV2WorkflowsAcrossDBVersions/reshardMerchant3to1Merge` here ([recent failure](https://github.com/vitessio/vitess/runs/6393037092?check_suite_focus=true#step:10:1008)):
```
I0511 17:42:11.027619   17525 vttablet_process.go:466] Executing query select count(*) from _vt.vreplication where workflow = "m3m1" and db_name = "vt_merchant-type" and pos = '' on zone1-2000
1029
vttablet_process.go:470: Deadlock found when trying to get lock; try restarting transaction (errno 1213) (sqlstate 40001) during query: select count(*) from _vt.vreplication where workflow = "m3m1" and db_name = "vt_merchant-type" and pos = ''
```
That can happen because when we get any error we fail today: …
=> CI: Add query retries to vttablet process

go/test/endtoend/tabletmanager/throttler/throttler_test.go
Quick fix to `tabletmanager_throttler` test that increases a timeout to reduce flakiness. The change to timeout is legit an immaterial to the overall test, and can combat some race condition or slowness in some test envs.
=> Fix `tabletmanager_throttler` flakyness: increase wait time

go/vt/orchestrator/logic/topology_recovery.go
The team tackled some `GracefulPrimaryTakeover` CI scenarios which were difficult to interpret. This PR adds some auditing in `GracefulPrimaryTakeover`, in particular around `AttemptRecoveryRegistration()`. In fact, any code path following `AttemptRecoveryRegistration()` must be audited; any early return must be visible, because those code paths can block the next recovery attempt.
=> vtorc: more auditing in GracefulPrimaryTakeover

go/vt/vtgate/executor.go, go/vt/vtgate/executor_select_test.go
When using the `vtgate` `--no_scatter` flag (or the comment directive equivalent), we expect all scatter queries to fail.
However, we cache the plan for the scatter before checking the query for validity (i.e. if using the no-scatter flag or comment, return an appropriate error).  When the query is repeated, we pull it from the cache and return it, never checking for the no-scatter flag or comment.
=> Do not cache plans that are invalid because of `--no_scatter`

.github/workflows/check_make_vtadmin_web_proto.yml, tools/check_make_vtadmin_web_proto.sh
This pull request adds the `check_make_vtadmin_web_ proto` workflow to the CI. The workflow checks that the generated vtadmin javascript types files are in sync with the proto files. This is done by running the `make vtadmin_web_proto_types` command and diffing `git status`'s output before and after.
If there is a diff (a drift), the workflow lists the files that are not in accordance: in this case the generated vtadmin proto files.
I manually tested this action by adding a dummy field to a proto and testing it both locally and in CI.
#9001
=> Check for vtadmin JS types drift in CI

web/vtadmin/src/components/DangerAction.tsx, web/vtadmin/src/components/routes/tablet/Advanced.tsx
A tiny little refactor (prefactor?!) as a precursor to #8732, since I'm going to be using that `DangerAction` component on the Shard page. Also added a couple of missing copyrights. 
Prefactor for #8732
N/A
=> [vtadmin] Rehome DangerAction component in a common folder

go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go, go/vt/schemadiff/view.go, go/vt/schemadiff/view_test.go
This adds additional normalization rules for schemadiff to reduce churn around default options and to remove things that are not supported.
- `USING BTREE` on an index is the default, so we drop that if specified.
- `VISIBLE` is the default for columns & indexes, so this is dropped when specified.
- `ALGORITHM = undefined` is the default for a `CREATE VIEW` so this is dropped when specified.
- `SQL SECURITY DEFINER` is the default for a `CREATE VIEW` so this is dropped when specified.
Part of #10203
=> Add additional normalization rules for schemadiff

.gitattributes
This adds a .gitattributes file and flags the files in [web/vtadmin/src/proto/](https://github.com/vitessio/vitess/tree/main/web/vtadmin/src/proto) as "generated files" to hide them by default in GitHub's diff view. These are the JS/TS bindings produced by `make vtadmin_web_proto_types`, so these files don't require manual review. (Doubly so now that we have CI in place to validate them thanks to #10256!) 
This feature is documented here: https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
Here's a before and after of what it looks for an unrelated branch of mine:
N/A
-   [x] …
=> Mark web/vtadmin/src/proto/** as generated files in .gitattributes

.gitignore
When running go programs in VS Code's debugger, it rather vexingly plops a `__debug_bin` file in the working tree. This file should never be committed, but it's very easy to do accidentally! Ask me how I know! 😎 
N/A
N/A
=> Add VS Code's __debug_bin to .gitignore

go.mod, go.sum, go/vt/workflow/manager.go
This removes using an additional UUID package. This was the only place this package was used, everywhere else uses github.com/google/uuid. Even this library uses that package as a dependency.
Fewer dependencies is better and also updating github.com/google/uuid while I was at it.
=> Remove usage of additional uuid package

go/test/endtoend/cluster/vtorc_process.go, go/test/endtoend/vtorc/general/vtorc_test.go, go/test/endtoend/vtorc/gracefultakeover/graceful_takeover_test.go, go/test/endtoend/vtorc/utils/utils.go, go/vt/orchestrator/logic/topology_recovery.go
Whenever we `AttemptRecoveryRegistration`, we should also be eventually calling `resolveRecovery` when our recovery completes, irrespective of it failing or not.
We weren't doing this in 2 places, `fixReplica` and `fixPrimary`. This caused the following failure - 
- We ran a `fixReplica` failure on tablet A.
- We didn't resolve the recovery on tablet A.
- We called `GracefulPrimaryTakeover` API on tablet A. This API call should succeed as it does not wait for any tablets in active recovery.
- However, this call blocks because we haven't resolved a previous recovery, so it is still assumed to be in progress.
- We wait until `ClearActiveRecoveries` removes all the old recoveries.
This behaviour is incorrect, as we are making an API call wait for the duration of `RecoveryPeriodBlockSeconds` …
=> BugFix: Resolve Recoveries at the end

doc/releasenotes/14_0_0_summary.md
Aligning with https://github.com/vitessio/website/pull/1020, we point out in `v14` release notes that Online DDL is generally available and no longer experimental (exception: `pt-osc` remains experimental)
- https://github.com/vitessio/website/pull/1020
- #6926 
=> v14 release notes: Online DDL is production ready

doc/releasenotes/14_0_0_summary.md, go/flags/endtoend/flags_test.go, go/vt/vttablet/onlineddl/executor.go
The flag `` was removed in https://github.com/vitessio/vitess/pull/9816 as part of removal of all `vtctld` logic for online DDL.
https://github.com/vitessio/vitess/pull/9816/files#diff-54b6f6d46473450637d28b579e506030060f186bb1cee4d61fea8a8b4fa99b93L45-L47
However, we did not deprecate it in an orderly fashion.
This PR re-introduces the flag, and 
https://github.com/vitessio/vitess/pull/9816
cc @rsajwani @deepthi
=> Deprecate flag --online_ddl_check_interval

web/vtadmin/src/components/routes/tablet/Advanced.tsx
A small fix for the warnings on the tablet "Advanced" tab (e.g., http://localhost:14201/tablet/local/zone1-101/advanced)
Relates to #9401
N/A
=> [vtadmin] Fix warning 'div cannot appear as a descendant of p'

web/vtadmin/package-lock.json, web/vtadmin/package.json, web/vtadmin/src/api/http.ts, web/vtadmin/src/components/App.tsx, web/vtadmin/src/components/forms/FormError.tsx, web/vtadmin/src/components/inputs/Select.tsx, web/vtadmin/src/components/routes/Keyspaces.tsx, web/vtadmin/src/components/routes/createKeyspace/CreateKeyspace.test.tsx, web/vtadmin/src/components/routes/createKeyspace/CreateKeyspace.tsx, web/vtadmin/src/hooks/api.ts
Adds a form to create a new keyspace. For vtctld2 parity, this includes the `sharding_column_name` input.
A few caveats/follow-ups I'll mention:
-  I didn't include the `CreateKeyspace -force` functionality since it's rather spicy + I'd like to do a bit more research first in order to write proper help text. 
- As you can see in the gif, the Keyspace detail page looks very bare (broken, in fact!) for keyspaces without any shards. The "better empty table state" is a widespread issue so I won't address it here. 
- `CreateKeyspace.test.tsx` is a beast of a test but it does (I think!) a pretty thorough job of testing the "golden path" for this form. 
Closes #8703 
- …
=> [vtadmin] Add CreateKeyspace bindings + form UI

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/ordered_aggregate.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt
Adds support for using aggregation functions in the HAVING clause. 
The plan will just look up the value of the aggregation in the column offset after aggregation has been performed.
=> feat: use column offsets when HAVING predicate has aggregation

web/vtadmin/src/components/DangerAction.test.tsx, web/vtadmin/src/components/DangerAction.tsx, web/vtadmin/src/components/routes/tablet/Advanced.tsx
The same DangerAction we know and love, but (further) generalized for use in contexts other than the Tablet page. This is another prefactor for deleting a shard (#8732), which is up next. 
(The tablet in the above gif doesn't disappear right away; this is expected + noted in the snackbar notification.)
Obligatory Top Gun reference:
- Prefactor for #8732 
- Follow-up to #10293 
N/A
=> [vtadmin] Further generalize DangerAction component

go/flags/endtoend/flags_test.go, go/vt/vtctld/vtctld.go, go/vt/vttablet/onlineddl/executor.go
Signed-off-by: Shlomi Noach <2607934+shlomi-noach@users.noreply.github.com>
https://github.com/vitessio/vitess/pull/10308  reintroduced `--online_ddl_check_interval` for backwards compatibility, but erroneously in `vttablet` rather than in `vtctld`. This PR hopefully sets things straight by reintroducing the flag in `vtctld`.
- https://github.com/vitessio/vitess/pull/10308 
- #9816 
=> The flag --online_ddl_check_interval belongs in vtctld

web/vtadmin/src/components/ActionPanel.test.tsx, web/vtadmin/src/components/ActionPanel.tsx, web/vtadmin/src/components/routes/tablet/Advanced.test.tsx, web/vtadmin/src/components/routes/tablet/Advanced.tsx
Further adventures in generalizing the DangerAction component! The original is very well-written + made these refactors nice and straightforward. :chef-kiss: 
- Renames the component from `DangerAction` to `ActionPanel`, and adds a `danger` prop to preserve the scary styling when necessary. 🎃 
- Updates all of the mutation triggers on the `tablet/advanced` page to use `ActionPanel` in its less scary form.
- Makes the confirmation input optional.
- Adds a `disabled` prop
- Lots more tests
Using `ActionPanel` under the hood, everything works as before:
- Continuation of #10319 
- Prefactor for #8723, #8738
N/A
=> [vtadmin] Further generalize DangerAction into ActionPanel

go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go, go/vt/schemadiff/types.go
As part of `validate()` process, we now look into any existing generated column, and verify they only reference existing columns.
- #10203 
=> schemadiff: validate columns referenced by generated columns

web/vtadmin/src/components/App.tsx, web/vtadmin/src/components/placeholders/QueryLoadingPlaceholder.tsx, web/vtadmin/src/components/routes/Clusters.tsx, web/vtadmin/src/components/routes/Gates.tsx, web/vtadmin/src/components/routes/Keyspaces.tsx, web/vtadmin/src/components/routes/Schemas.tsx, web/vtadmin/src/components/routes/Tablets.tsx, web/vtadmin/src/components/routes/Vtctlds.tsx, web/vtadmin/src/components/routes/Workflows.tsx
- Adds `QueryLoadingPlaceholder` loading state to all the entity table views (tablets, clusters, etc.) 
- Updates default redirect from `/tablets` to `/schemas`
- Updates `QueryLoadingPlaceholder` to accept multiple `queries` (or, as before, just one `query`)
Updating the default redirect from `/tablets` to `/schemas` was a little feature request from Slack, and it makes sense to me! 
(I think an even better UX would be to store, say, the user's last browsed entity table view and persist that in local storage, but ofc that's a lot more complicated.)
Since the /schemas view is the slowest of all the views (and for us it's _very_ slow indeed, so #10120 is highly anticipated!) I also took this chance to add `QueryLoadingPlaceholder` since before it was simply blank and looked pretty broken. …
=> [vtadmin] Add loading placeholder for entity table views + update default redirect to /schemas

go/cmd/vtadmin/main.go, go/vt/vtadmin/grpcserver/server.go
This PR adds (yet another) new config option to specify an endpoint to serve prom metrics on, via HTTP. It also adds the missing `grpc_prom.Register` call.
I threw together a quick grpc client and made a GetClusters call, and then:
```
➜  vitess git:(andrew/vtadmin-goes-to-prom) ✗ curl -s localhost:14200/metrics | grep "OK.*GetClusters"
grpc_server_handled_total{grpc_code="OK",grpc_method="GetClusters",grpc_service="vtadmin.VTAdmin",grpc_type="unary"} 1
```
-   [x] Documentation was added or is not required => I will follow up with a docs PR for the website!!
=> [vtadmin] Add prom metrics endpoint support

go/vt/schemadiff/diff_test.go, go/vt/schemadiff/mysql.go, go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go
Integral lengths here don't really have much meaning anymore and it is deprecated and slated to be removed in MySQL. However, applications do depend on these lengths today.
One very specific example is that Ruby on Rails depends on this length for its type mapping. It maps a tinyint(1) to a boolean value, but it doesn't do that just for a tinyint. This means that even if this has no meaning in the MySQL context, it does have meaning in the application context.
Likewise, there's probably cases that depend on zerofill as well, so let's not remove that either.
Part of #10203
=> Remove normalization of integral length types

web/vtadmin/src/api/http.ts, web/vtadmin/src/components/routes/keyspace/Advanced.test.tsx, web/vtadmin/src/components/routes/keyspace/Advanced.tsx, web/vtadmin/src/components/routes/keyspace/Keyspace.tsx, web/vtadmin/src/hooks/api.ts
Part of https://github.com/vitessio/vitess/issues/8738
This adds a very straightforward UI control that maps to the [ReloadSchemaKeyspace](https://vitess.io/docs/13.0/reference/programs/vtctl/schema-version-permissions/#reloadschemakeyspace) command by way of the `/api/schemas/reload` endpoint added in https://github.com/vitessio/vitess/pull/10300. 
The copy in the gifs below is ever so slightly out of date; I've updated it to the following to account for not including the `include_primary` parameter:
> Reloads the schema on all the tablets, **except the primary tablet** ...
Here's the flow for the keyspace/advanced route when a keyspace doesn't exist. (I think there are opportunities to be more consistent about this particular error flow across VTAdmin, as some polish before GA.) 
I have …
=> [vtadmin] Add keyspace/advanced view + ReloadSchemaKeyspace control

go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go, go/test/endtoend/onlineddl/vtgate_util.go
This PR adds a `endtoend` test to cover the following scenario:
- a multisharded keyspace
- migration starts on all shards (2 in this test)
- one shard is faster than the other. The migration is complete on one shard, but still running on another.
- migration cancelled by user (obviously only affects the running migration, transitioning it into `failed` state)
- user issues a `REVERT VITESS_MIGRATION`
- revert applied to both shards
- revert is successful on the first shard, where the original migration completed. Revert fails on the 2nd shard, because you can't revert a failed migration
- `SHOW VITESS_MIGRATIONS` returns status for both shards, and correctly indicates the successful and failed revert.
There are no logic changes in this PR. The new test validates existing behavior.
#6926 …
=> OnlineDDL: adding an endtoend test to validate partial shard REVERT

web/vtadmin/README.md, web/vtadmin/package-lock.json, web/vtadmin/package.json
This removes the [source-map-explorer](https://www.npmjs.com/package/source-map-explorer) dependency. 
I do find it quite useful! But its infrequent update schedule means it tends to accumulate `npm audit` and Dependabot warnings. I use this package so seldomly that `npm install`ing (with no save) when needed makes a lot more sense than keeping this in the `package.json`.
The main argument I see for keeping it in there would be if we wanted to integrate it into CI or something. Would be cool! But using something like https://github.com/bundlewatch/bundlewatch would be even cooler, without the dependency overhead. 😎 To consider for later. 
N/A
- …
=> [vtadmin] Remove source-map-explorer dependency

go/vt/schemadiff/diff_test.go, go/vt/schemadiff/mysql.go, go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go
This adds back the integer normalization to remove the length, but with one very specific exception.
MySQL maps the boolean type to a `tinyint(1)`, so that is the only special case where we can't remove the length. The canonical MySQL behavior on all other integer types and for all other lengths is that it is removed / ignored.
Part of #10203
=> Add better int normalization

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/vt/sqlparser/ast.go, go/vt/sqlparser/ast_clone.go, go/vt/sqlparser/ast_equals.go, go/vt/sqlparser/ast_format.go, go/vt/sqlparser/ast_format_fast.go, go/vt/sqlparser/ast_funcs.go, go/vt/sqlparser/ast_rewrite.go, go/vt/sqlparser/ast_visit.go, go/vt/sqlparser/cached_size.go, go/vt/vtgate/engine/projection_test.go, go/vt/vtgate/evalengine/translate.go, go/vt/vtgate/planbuilder/abstract/queryprojection.go, go/vt/vtgate/planbuilder/aggregation_pushing.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/ordered_aggregate.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/onecase.txt, go/vt/vtgate/planbuilder/testdata/systemtables_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt
This change makes it possible for the gen4 planner to accept aggregation functions in `HAVING` that are not returned to the user, such as:
```sql
select id 
from tbl 
group by id 
having count(*) > 10
```
=> [gen4] More aggregation support

web/vtadmin/package-lock.json
This updates a few nested/transitive dependencies of `react-scripts` to address some `npm audit` warnings:
- `ejs`
- `async`
- `webpack-dev-server`
Directly updating nested dependencies like this is very much NOT my preferred way of dealing with `npm audit` warnings, but the CRA project [takes a strong stance](https://github.com/facebook/create-react-app/issues/11174) on this and, in any case, we're already on the latest version of `react-scripts`, [v5.0.1](https://github.com/facebook/create-react-app/releases/tag/v5.0.1).
I validated these updates by running `npm run local` locally, and also by doing a build (which is also enforced in CI). `react-scripts` is run at build time, _not_ run time, so the risk here is low as described in that [react-scripts …
=> [vtadmin] Update ejs, async, and webpack-dev-server dev dependencies

go/vt/vtadmin/api.go
I extracted this out of another PR I'm working on because it's self-contained and useful! (the ShardResource thing is coming from that, by way of explanation). Anyway, onward!
<hr/>
This refactors `getTabletForAction` => `getTabletForResourceAndAction` to support more resource types (`rbac.ShardResource` being my immediate use case), as well as return the `cluster.Cluster` object the tablet was found in.
Returning the cluster directly minimizes the number of times we need
to hold the `clusterMap` mutex, since every request needs to
(1) get the tablet then
(2) get the cluster for that tablet
we already have the cluster, so we iterate twice and return it directly
- …
=> [vtadmin] Refactor getTabletForAction

go/test/endtoend/vtgate/queries/union/union_test.go, go/vt/vtgate/engine/concatenate.go, go/vt/vtgate/engine/concatenate_test.go, go/vt/vtgate/engine/fake_vcursor_test.go, go/vt/vtgate/engine/primitive.go, go/vt/vtgate/vcursor_impl.go
Engine primitives communicate with each other all the time. When they do, the context passed between them is not passed explicitly as a method call argument as is normally done in golang code. Instead it's baked into one of the fields of the `vcursor` instance that engine primitives receive when executing.
The problem with this setup is when we concurrently call multiple children, like UNION does. The way that the context was shared between primitives means that sometimes, by mistake, one primitive would cancel another primitives context.
This manifested as intermittent errors when doing queries containing lots of UNION code.
This is a backport of #10257
-   [x] …
=> Backport R13: concatenate engine primitive

go/test/endtoend/vtgate/queries/union/union_test.go, go/vt/vtgate/engine/concatenate.go, go/vt/vtgate/engine/concatenate_test.go, go/vt/vtgate/engine/fake_vcursor_test.go, go/vt/vtgate/engine/limit.go, go/vt/vtgate/engine/primitive.go, go/vt/vtgate/vcursor_impl.go
This is the backport of two different fixes that aim to make the `UNION` execution on vtgate more stable.
Backport of #9979 & #10257 
=> [V12] Backport of two UNION fixes

go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go, go/vt/schemadiff/types.go
This adds additional improvements for schemadiff. Each commit is a small separate improvement. 
First there are some typo fixes and we switch to using an sqlparser constant for the tinyint instead of the string. Secondly, we add normalization of `index` to `key`, to match how MySQL behaves and to ensure that alter statements like `add index` result in a schema that is the same as `add key`.
Lastly, we add validation of column references in function indexes very similarly as in https://github.com/vitessio/vitess/pull/10328. This change also updates behavior for dropping a column when a functional index is present, since that should be blocked:
```
mysql> create table t (id int primary key, i int, key id_idx((IF(id, 0, 1))), key i_idx((IF(i,0,1))));
Query OK, 0 rows affected (0.02 sec) …
```
=> Additional schemadiff improvements for indexes

go.mod, go/vt/schemadiff/diff.go, go/vt/schemadiff/diff_test.go, go/vt/schemadiff/errors.go, go/vt/schemadiff/schema.go, go/vt/schemadiff/schema_test.go, go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go, go/vt/schemadiff/types.go, go/vt/schemadiff/view.go, go/vt/schemadiff/view_test.go, go/vt/wrangler/resharder.go
These changes more all the schemadiff errors we expose for consumers to be structured. With structured errors it's possible to get access to more specifics from an error, like which table, column, index etc. is affected by the issue. This allows better structured error reporting to the user.
The changes here are best reviewed commit by commit, with first some refactoring and cleanup and then changes to the new structured error types. 
It also address some small typos and an issue with how it was still possible to have schemadiff panic so it moves some checks around strict DDL parsing as well.
Part of #10203
=> Structured schemadiff errors

go/vt/schemadiff/errors.go, go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go
This PR validates that columns covered by a foreign key do in fact exist. Note that this validation only applies to _current_ table, and does not validate the _referenced columns_ in the parent table.
#10203 
#10189 
=> schemadiff: validate columns referenced by FOREIGN KEY

go/vt/vtgate/executor_dml_test.go, go/vt/vtgate/executor_framework_test.go, go/vt/vtgate/safe_session.go, go/vt/vtgate/vtgate.go, go/vt/vtgate/vtgate_test.go
This PR removed the internal savepoint created during the execution of a DML when the query execution is complete.
When a query is executed and it is detected that it will go to multiple shard then vitess created an internal savepoint for that transaction.
Once the query execution is complete that savepoint has no purpose.
Other things about keeping that savepoint around is that the next query if it goes to different shard then the old internal savepoint will also be sent along and created which has no use for the current query.
=> Remove internal savepoint post query execution

go/vt/vtexplain/testdata/multi-output/updatesharded-output.txt, go/vt/vtexplain/testdata/updatesharded-queries.sql, go/vt/vtexplain/vtexplain_vtgate.go, go/vt/vtgate/autocommit_test.go, go/vt/vtgate/executor_dml_test.go, go/vt/vtgate/executor_framework_test.go, go/vt/vtgate/plan_execute.go, go/vt/vtgate/safe_session.go, go/vt/vtgate/vcursor_impl.go
Backport of https://github.com/vitessio/vitess/pull/10223
This PR reduces the effect of creating unnecessary calls to vttablet to create savepoints. The logic of savepoints in transactions was introduced in 13.0 as part of MySQL compatibility work where any cross-shard query fails it should not rollback the transaction (old behavior) instead should only rollback the effect of the query (current behavior). This boosts the Vitess query-serving performance by 7%.
=> [13.0] partial dml execution logic enhancement

go/test/endtoend/vtgate/lookup_test.go, go/vt/sqlparser/ast_funcs.go, go/vt/sqlparser/ast_rewriting.go, go/vt/vtgate/planbuilder/gen4_planner.go
We should not use the `NoRoutesSpecialHandling` mode for vindex lookup queries.
This PR changes when we apply this special handling mode. Before, we did it for all plans that were single routes, with this change we are more conservative and only use it in one of two situations:
1. All select expressions are aggregations, and we have no grouping defined. These queries should not return empty result when nothing matches the WHERE clause, instead they need to return special empty values. Think `select count(*) from tbl`.
2. When the query is a `dual` query. If we have been able to merge a `dual` query with a subquery, we need to run the query and return something, even if no routes can be found to match the subquery predicates. This is because the `dual` table always returns a single row. …
=> Fix failure when Unowned lookup IS NULL

go/vt/vtadmin/api.go, go/vt/vtadmin/cluster/cluster.go, go/vt/vtadmin/vtctldclient/fakevtctldclient/vtctldclient.go, go/vt/vtadmin/vtsql/vtsql.go
This PR enhances the `io.Closer` implementation of Cluster to also cleanly close any open gRPC connections (to vtgate/vtctld) and then use this when evicted old dynamic clusters, as well as address an issue in `api.clusters` management which I'll discuss in a bit!
The change is in 4 parts:
1. vtsql.Close was mutating `vtgate.conn`, which query-related methods would check and return `ErrConnClosed` if it was `nil`. This causes data races (ty `go test -race`). No one was explicitly relying on that named error anyway, so I removed it in favor of just letting queries fail if the gRPC connection gets closed out from under them (which produces a similar error string).
a. Then, to continue supporting an `is_connected` field in the debug info, I added a `closed` flag which _is_ guarded by the …
=> [vtadmin] cluster Closer implementation + dynamic Cluster bugfix

examples/compose/vttablet-up.sh, go/cmd/vtctldclient/command/keyspaces.go, go/cmd/vtworker/vtworker.go, go/flags/endtoend/flags_test.go, go/test/endtoend/cluster/vttablet_process.go, go/vt/binlog/keyspace_id_resolver.go, go/vt/vtctl/vtctl.go, go/vt/worker/grpcvtworkerclient/client.go, go/vt/worker/vtworkerclient/interface.go, go/vt/wrangler/keyspace.go, vitess-mixin/e2e/vttablet-up.sh
The legacy sharding code — e.g. `SplitClone` — has long since been replaced by VReplication based workflows like `MoveTables`.
This PR ensures that all related user commands are clearly marked as deprecated so that all related code can be removed in v15.
- https://github.com/vitessio/vitess/issues/9219
- https://github.com/vitessio/vitess/pull/10278
-   [x] Documentation: https://github.com/vitessio/website/pull/1027
=> Ensure all legacy sharding commands are clearly deprecated

go/vt/wrangler/tablet.go, go/vt/wrangler/tablet_test.go
This PR makes sure that `wrangler.DeleteTablet()` no longer returns an error when deleting a Primary if a `Shard` no longer exists. A `Shard` might not exist, when for example someone explicitly deletes it before calling `wrangler.DeleteTablet()`. By making this change, the `wrangler.DeleteTablet()` function is also idempotent, and safe to use in reconciling loops (such as in Kubernetes Operators).
=> vt/wrangler: fix deleting primary tablet if `Shard` does not exist

go/vt/schema/online_ddl.go
Followup to #9816 , this PR removes functions and constants that are unused. There is no behavior impact because no one calls these functions. Just clenaup.
#6926 
#9816 
=> Cleanup: removed legacy, unused code (online DDL paths in topo)

go/cmd/vtaclcheck/tableacl2.json, go/test/endtoend/messaging/main_test.go, go/test/endtoend/messaging/message_test.go, go/vt/vttablet/tabletserver/schema/load_table.go, go/vt/vttablet/tabletserver/schema/load_table_test.go
this enables users to set an allow-list of columns that will be loaded into memory and streamed to subscribers when they call `stream * from tbl`
#9666
=> messaging: support vt_message_cols to limit cols

go/vt/vtgate/engine/filter.go
Very small fix for an engine primitive. It was not executing it's input using the buffering execution offered by the vcursor.
=> fix: filter was not using the vcursor buffering execution

go/vt/vtexplain/vtexplain.go, go/vt/vtexplain/vtexplain_test.go, go/vt/vtexplain/vtexplain_vtgate.go
vtexplain was not checking if the keyspaces in the vschema were loaded correctly before using it.
Fixes #10020
=> fix: check that all keyspaces loaded successfully before using them

examples/compose/README.md, examples/local/README.md, examples/operator/README.md
Continuation of #9875. Fixes the commands in the readme files.
#9733 
=> Fix commands in readme files to use double dashes for arguments

go/vt/vtgate/buffer/shard_buffer.go, go/vt/vtgate/errorsanitizer/errorSanitizer.go, go/vt/vtgate/errorsanitizer/errorSanitizer_test.go
This is an effort to sanitize and redact PII from error logging.
Important Note: I am not able to use *terseErrors (vtgate-config-terse-errors) , given its defined in vtgate package and using it in shared_buffer.go results in circular dependency. It will require some refactoring which I believe we can do in separate task.
=> Sanitize log messages

.gitattributes, go/vt/mysqlctl/rice-box.go, go/vt/mysqlctl/rice_box_test.go
We recently had an issue where the `init_db.sql` has been updated but the corresponding rice box was not updated.  (rice box reference: https://github.com/GeertJohan/go.rice)
All files in the config directory are part of this rice box. This PR adds a unit test to compare these files on disk with that embedded in the rice box.
The other rice-box usage is around the old vtctld UI and embedded vitess binaries, those are not tested for.
=> Unit test to confirm that the mysqlctl rice box is current

examples/are-you-alive/schemas/README.md, examples/compose/lvtctl.sh, examples/local/backups/start_cluster.sh, examples/local/backups/stop_tablets.sh, examples/local/orc_test.sh, examples/operator/pf.sh, examples/region_sharding/201_main_sharded.sh, go/test/endtoend/keyspace/keyspace_test.go, go/test/endtoend/vtgate/reservedconn/reconnect3/main_test.go, go/test/endtoend/vtgate/reservedconn/reconnect4/main_test.go, go/vt/vtctl/backup.go, go/vt/vtctl/cell_info.go, go/vt/vtctl/cells_aliases.go, go/vt/vtctl/query.go, go/vt/vtctl/reparent.go, go/vt/vtctl/throttler.go, go/vt/vtctl/topo.go, go/vt/vtctl/vtctl.go, go/vt/vtctl/workflow.go, test/client_test.sh
I did an audit of the vtctl related code and updated all `vtctl`/`vtctlclient` related help output to use the new flag syntax (primarily double dashes for long flag names) where it was not already done.
I also updated any related `vtctl`/`vtctlclient` usage code in our examples and tests that still needed it.
=> Update vtctl help output to use double dashes for long flag names

go/vt/vtgate/planbuilder/physical/route.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt
When a query is using a `IS NULL` predicate against a lookup vindex column, we should have a very hight cost for these, since they will always need to do a scatter query. The lookup table is keyed by the column and so does not support `null` values.
#10346
=> feat: do not use lookup vindexes for IS NULL predicates

go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go
Column names are case insensitive. So should be our checks in `postApplyNormalize` and `Validate()` as we look into columns referenced by check constraints.
#10203 
=> schemadiff: column name check in CHECK constraint is case insensitive

go/vt/vtgate/planbuilder/route.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt
Does the same thing that we did for gen4 recently - do not plan vindex lookup queries against null values, since they are not supported.
Gen4 change: #10388
l
=> feat: make v3 not plan IS NULL queries against a lookup vindex

doc/releasenotes/14_0_0_summary.md, go/cmd/vtexplain/vtexplain.go
vtexplain mistakenly used `planner-version` instead of `planner_version`, note the underscore vs the hyphen.
We want to keep the same flag that the vtgate is using, so this PR changes it to use the new flag.
=> replace planner-version with planner_version in vtexplain

go/vt/vtctl/grpcvtctldserver/testutil/test_tmclient.go, go/vt/vtctl/reparentutil/planned_reparenter_flaky_test.go, go/vt/vtctl/reparentutil/replication.go
This PR makes two minor changes - 
1. Adds 2 more logging statements to ERS for better debugging
2. Adds a test to planned reparent shard tests to verify that it sets the correct value of semi-sync when performing promotion.
=> Addition of more logging to ERS and tests to PRS

go/test/endtoend/vtgate/sec_vind/main_test.go, go/test/endtoend/vtgate/sec_vind/schema.sql, go/test/endtoend/vtgate/sec_vind/vschema.json, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/planbuilder/select.go, test/config.json
In a recent change (#10152), we introduced a special mode handling when no routes are found for a query. 
This introduced an issue that was later fixed for gen4 (#10346), but here I missed fixing the same issue for v3.
Needs to be backported to R13 since the above changes were backported.
#10152 Bug introduced
#10346 Bug fixed for Gen4
Fixes #10301
=> v3: Fix issue when no routes are found from a lookup

go/vt/vtadmin/api.go, go/vt/vtadmin/api_authz_test.go, go/vt/vtadmin/api_test.go, go/vt/vtadmin/cluster/cluster_internal_test.go, go/vt/vtadmin/cluster/cluster_test.go, go/vt/vtadmin/testutil/authztestgen/config.json, go/vt/vtadmin/testutil/authztestgen/template.go, go/vt/vtadmin/vtctldclient/fakevtctldclient/vtctldclient.go
This adds authz tests for the following RPCs:
- GetBackups
- GetCellInfos
- GetCellsAliases
It also includes a fix for handling where GetBackupsRequest.RequestOptions could be nil, which, in `(*cluster.Cluster).GetBackups` when we annotate the span, could segfault.
#10397 
=> [vtadmin] authz tests - getters part1

go/cmd/vttestserver/vttestserver_test.go, go/mysql/auth_server_clientcert_test.go, go/mysql/client_test.go, go/mysql/handshake_test.go, go/mysql/server_flaky_test.go, go/streamlog/streamlog_flaky_test.go, go/vt/grpcoptionaltls/server_test.go, go/vt/mysqlctl/backup_test.go, go/vt/mysqlctl/filebackupstorage/file_test.go, go/vt/schemamanager/local_controller_test.go, go/vt/sqlparser/parse_test.go, go/vt/tlstest/tlstest_test.go, go/vt/topo/consultopo/server_flaky_test.go, go/vt/topo/etcd2topo/server_test.go, go/vt/topo/k8stopo/server_flaky_test.go, go/vt/vtexplain/vtexplain_test.go, go/vt/vtgate/plugin_mysql_server_test.go, go/vt/vttablet/filelogger/filelogger_test.go, go/vt/wrangler/testlib/backup_test.go, go/vt/wrangler/testlib/vtctl_topo_test.go
A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := ioutil.TempDir("", "")
require.NoError(t, err)
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```
=> test: use `T.TempDir` to create temporary test directory

go/vt/vtgate/engine/projection.go
Input to the engine primitive should not be executed directly and should instream use the vcursor primitive functions to execute them as they handle buffering logic if needed.
This PR fixes it for projection primitive for the bug introduced in #10384 
=> fix: use vcursor to execute the projection input

go/test/endtoend/onlineddl/vrepl_stress_suite/onlineddl_vrepl_stress_suite_test.go
fixing `Cluster (onlineddl_vrepl_stress_suite) mysql80` flakyness. 
=> fixing vrepl_stress_suite flakyness

go/vt/vttablet/tabletserver/throttle/config/config.go, go/vt/vttablet/tabletserver/throttle/config/mysql_config.go, go/vt/vttablet/tabletserver/throttle/config/store_config.go, go/vt/vttablet/tabletserver/throttle/throttler.go
Fixes https://github.com/vitessio/vitess/issues/10400
The tablet throttler code was contributed at about the same time as https://github.com/vitessio/vitess/pull/7189, and while superficially `/debug/env` supported a dynamic change of `ThrottleMetricThreshold`, the tablet throttler itself did not re-read that value dynamically; it only applied it once upon initialization.
As of this PR, the value is reflected dynamically. A change to `ThrottleMetricThreshold` will be reflected in the throttler's behavior, or can be seen in its API, e.g.:
```shell
% curl -s http://localhost:15100/throttler/check | jq .
{
"StatusCode": 200,
"Value": 4,
"Threshold": 50,
"Message": ""
}
```
Do note that change may take up to `10sec` to take effect, per …
=> Tablet throttler: dynamic ThrottleMetricThreshold

go/vt/vtadmin/api_authz_test.go, go/vt/vtadmin/testutil/authztestgen/config.json, go/vt/vtadmin/testutil/authztestgen/main.go, go/vt/vtadmin/testutil/authztestgen/template.go, go/vt/vtadmin/testutil/cluster.go, go/vt/vtadmin/vtctldclient/fakevtctldclient/vtctldclient.go
This takes us through `Get[A-S].*` (with the exception of the schema ones, because I'm putting off writing the mock data because it's gonna be annoying (i will do it, though, i promise!))
#10397 
=> [vtadmin] authz tests - getters part2

doc/releasenotes/12_0_4_release_notes.md
This PR is a follow-up of [Release `v12.0.4`](https://github.com/vitessio/vitess/releases/tag/v12.0.4). The release notes are updated.
=> Release notes documents for `v12.0.4` on `main`

examples/compose/orchestrator/default.json, examples/operator/vtorc_example.yaml, go/test/endtoend/cluster/vtorc_process.go, go/test/endtoend/vtorc/general/vtorc_test.go, go/test/endtoend/vtorc/gracefultakeover/graceful_takeover_test.go, go/test/endtoend/vtorc/primaryfailure/primary_failure_test.go, go/test/endtoend/vtorc/utils/utils.go, go/vt/orchestrator/config/config.go, go/vt/orchestrator/db/generate_base.go, go/vt/orchestrator/inst/analysis_dao.go, go/vt/orchestrator/inst/analysis_dao_test.go, go/vt/orchestrator/inst/durability.go, go/vt/orchestrator/inst/instance_dao.go, go/vt/orchestrator/inst/instance_topology_dao.go, go/vt/orchestrator/inst/keyspace_dao.go, go/vt/orchestrator/inst/keyspace_dao_test.go, go/vt/orchestrator/inst/tablet_dao.go, go/vt/orchestrator/logic/keyspace_discovery.go, go/vt/orchestrator/logic/keyspace_discovery_test.go, go/vt/orchestrator/logic/orchestrator.go, go/vt/orchestrator/logic/tablet_discovery.go, go/vt/orchestrator/logic/topology_recovery.go, go/vt/orchestrator/test/recovery_analysis.go, go/vt/topo/keyspace.go, go/vt/topotools/keyspace.go, vitess-mixin/e2e/orchestrator/default.json
This PR continues the work of using the durability policy stored in the topo server started in https://github.com/vitessio/vitess/pull/10392. 
We make changes to VTOrc in this PR to deprecate and remove the `Durability` configuration. Instead VTOrc will now also read the durability policy from the topo server. Since, VTOrc needs this information for running the error analysis, it will also need to store the same in its data store to avoid a call to the topo server on each error analysis tick.
This PR accomplishes all of these changes and makes it so that VTOrc too can work with multiple keyspaces having different durability policies.
This PR also adds the check to VTOrc to ignore snapshot keyspaces when running error analysis
VTOrc will ignore keyspaces which don't have their …
=> Use Durability Policy in the topo server in VTOrc and deprecate Durability config

.github/workflows/cluster_endtoend_topo_connection_cache.yml, go/test/endtoend/topoconncache/main_test.go, go/test/endtoend/topoconncache/topo_conn_cache_test.go, go/vt/topo/server.go, test/ci_workflow_gen.go, test/config.json
Co-authored-by: Rameez Sajwani <rameezwazirali@hotmail.com>
Issue: vtctlclient ListAllTablets does not show those tablets in cells that were deleted and re-added with same name.
The root cause is that we cache connections to cells by name, and the name is being re-used.
We are fixing this by caching the CellInfo along with conn so that we can verify that it is the exact "same" cell before using the cached connection.
We create a cell "abc" with some rootPath like path1/abc. Then we delete it, and create it again with the same name but a different path like path2/abc.
The vtctld cache will continue to contains a connection with path path1/abc which no longer exists.
-   [ ] "Backport me!" label has been added if this change should …
=> topo: cache CellInfo along with conn

go/flags/endtoend/flags_test.go, go/vt/vttablet/tabletmanager/rpc_replication.go
In this PR we change the default for the vttablet `--use_super_read_only` flag back to false (it was changed to true in v13 via https://github.com/vitessio/vitess/pull/9312).
We are doing this because when this flag is true you may not be able to restart a replica/rdonly vttablet process. This is because:
1. The tablet has enabled `super_read_only` in its mysqld because it's a replica tablet.
2. When a tablet starts up, it attempts to run some DDL statements as the DBA user such as `CREATE DATABASE IF NOT EXISTS _vt` and that will fail with an error because the mysqld has `super_read_only` enabled.
3. So the tablet will not be able to come back up properly.
We really should be enabling `super_read_only`, both in the config file and in the tablet via this flag, as without that we will in …
=> Change use_super_read_only default back to false

examples/operator/101_initial_cluster.yaml
Here we halve the request and double the limit for RAM in [the example cluster.](https://vitess.io/docs/14.0/get-started/operator/) We do this because:
1. We don't need/want everything to have the [Guaranteed QoS](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed) (request == limit)
2. It's common for mysqld (especially 8.0) to go beyond the old limit and end up in a crash loop
Fixes: https://github.com/vitessio/vitess/issues/9141
=> Halve request and double limit for RAM in the example cluster

go/mysql/schema.go
Accessing the `information_schema.columns` table is expensive in MySQL 5.7, especially when it's accessed in a nested loop (e.g. via a `JOIN`). The query to detect schema changes was accessing `information_schema.columns` multiple times, which could easily add up to execution times of 0.5 seconds per query on my test system.
This pull request proposes a replacement query that is more careful about accessing `information_schema.columns` (and `_vt.schemacopy`) only once to determine all tables that have been modified and need to be re-cached.
See https://github.com/vitessio/vitess/pull/9632 for a similar optimization made previously.
-   [ ] Documentation was added or …
=> Improve performance of the `DetectSchemaChange` query

.github/workflows/upgrade_downgrade_test_query_serving.yml, .github/workflows/upgrade_downgrade_test_query_serving_queries.yml, .github/workflows/upgrade_downgrade_test_query_serving_schema.yml, go/test/endtoend/vtgate/schema/schema_test.go, test/config.json
This Pull Request reduces the flakiness recently observed in the query serving upgrade downgrade tests. The disks of the machines would run out of storage, which ultimately fails the tests.
The following error can be observed:
```
Error: No space left on device :
```
The flakiness/overuse of the disks is limited by splitting the query serving upgrade downgrade tests into two distinct groups: `queries` and `schema`. All the tests under `.../vtgate/queries/...` will be grouped in the new workflow `Upgrade Downgrade Testing Query Serving (Queries)`; And all the tests under `.../vtgate/*schema*/...` will be grouped in the workflow `Upgrade Downgrade Testing Query Serving (Schema)`.
-   [x] Tests were added or are …
=> Divide query serving upgrade downgrade tests in two groups to limit disk usage per workflow

go/mysql/flavor.go, go/mysql/flavor_mysql.go, go/mysql/flavor_mysqlgr.go, go/mysql/flavor_test.go
Followup to https://github.com/vitessio/vitess/pull/10445:
- `mysqlGRFlavor` now implements `supportsCapability(...)` for all relevant capabilities
- Added a couple new capabilities
- https://github.com/vitessio/vitess/pull/10445
=> Flavor capabilities: MySQL GR and more

go/vt/vtadmin/cluster/cluster.go, go/vt/vtadmin/cluster/cluster_internal_test.go, go/vt/vtadmin/cluster/config.go, go/vt/vtadmin/cluster/flags.go
I missed this when doing #10404 🙈; ideally this lands in 14.0
=> [vtadmin] Rename ERS/PRS pools+flags properly

.github/workflows/comment_pull_request.yml
This PR updates the review checklist with an item to make sure new/modified workflows are reviewed properly.
=> Update the comment for review checklist with an item for CI workflows

docker/vttestserver/run.sh, go/cmd/vtcombo/main.go, go/cmd/vtexplain/vtexplain.go, go/cmd/vtgate/vtgate.go, go/cmd/vttestserver/main.go, go/flags/endtoend/flags_test.go, go/test/endtoend/cluster/vtgate_process.go, go/test/endtoend/tabletmanager/qps_test.go, go/test/endtoend/vtcombo/vttest_sample_test.go, go/test/endtoend/vtgate/partialfailure/main_test.go, go/vt/env/env.go, go/vt/vtexplain/vtexplain_vtgate.go, go/vt/vtgate/executor.go, go/vt/vtgate/executor_dml_test.go, go/vt/vtgate/executor_framework_test.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/executor_stream_test.go, go/vt/vtgate/executor_test.go, go/vt/vtgate/plan_execute.go, go/vt/vtgate/vcursor_impl.go, go/vt/vtgate/vcursor_impl_test.go, go/vt/vtgate/vtgate.go, go/vt/vtgate/vtgate_test.go, go/vt/vttest/local_cluster.go, go/vt/vttest/vtprocess.go
This is a backport that changes the flag `planner_version` to `planner-version` in a few places.
Backport of #10453
=> backport: change planner_version to planner-version everywhere

go/vt/schemadiff/diff_test.go, go/vt/schemadiff/schema.go, go/vt/schemadiff/table.go, go/vt/schemadiff/types.go
Similarly to https://github.com/vitessio/vitess/pull/10472 that heuristically identifies renamed columns, this PR heuristically identifies renamed tables.
A new diff hint `TableRenameStrategy` can take the values:
- `TableRenameAssumeDifferent` (default); for backwards compatibility, `schemadiff` does not try to resolve renames. It treats a table rename like a `DROP TABLE` + `CREATE TABLE`
- `TableRenameHeuristicStatement`: `schemadiff` attempts to generate a `RENAME TABLE` statement for what it suspects to be a table rename.
The heuristic is simple: identify what looks to be a `DROP`ped table and what looks to be a `CREATE`d table, see if their schema is identical (other than their names), and turns that into a `RENAME`.
There can be a scenario where multiple dropped tables have the same …
=> schemadiff: TableRenameStrategy in DiffHints

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/vt/vtgate/planbuilder/aggregation_pushing.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/tpch_cases.txt
This PR fixes an aggregation-grouping bug in gen4 that does non-scalar aggregates on a top of a join. 
This happens when the left side of the join has data and no data is present on the right hand side.
If the right hand side of the join only contains an aggregation then even though the table has no data it will return count(*) as `0` and that will get mapped to the join output.
To avoid such scenario the change adds a grouping condition on the right hand side using literal 1 so that the rows from right hand side is only returned when the join condition matches.
-   [X] "Backport me!" label has been added if this change should be backported 14.0
=> fix: aggregation empty row on join with grouping and aggregations

go/vt/vtadmin/api_authz_test.go, go/vt/vtadmin/testutil/authztestgen/config.json, go/vt/vtadmin/vtctldclient/fakevtctldclient/vtctldclient.go, web/vtadmin/package-lock.json
Everything except `(Find|Get)Schema`, `GetSchemas`, and `VTExplain` (which are coming next).
#10397 
=> [vtadmin] Add authz tests for remaining non-schema related actions

go/vt/vtadmin/api_authz_test.go, go/vt/vtadmin/testutil/authztestgen/config.json, go/vt/vtadmin/testutil/authztestgen/template.go
This is stacked on top of #10481 and should be merged after that PR (plus a rebase, and re-codegen).
This is the last of the authz tests to add:
```
$ diff -q <(cat ./proto/vtadmin.proto | grep 'rpc' | awk '{print $2}' | awk -F '(' '{print $1}' | sort) <(cat ./go/vt/vtadmin/testutil/authztestgen/config.json | jq -r '.tests[].method' | sort)
$ echo $?
0
```
#10397 
=> [vtadmin] Add schema-related authz tests

go/tools/asthelpergen/asthelpergen.go
Changes so `make codegen` doesn't stop because of compilation errors on the files with static methods (`ast_rewrite.go`, `ast_visit.go`, `ast_equals.go` and `ast_clone.go`). Since these files will be overwritten anyway, if all the compilation errors are on these, we'll just ignore the error.
Unfortunately, this does not work for the `ast_format_fast` generator. It produces methods that are interface implementations, and errors here are more difficult to ignore.
=> feat: don't stop if compilation errors are happening on the generated files

go/vt/vtgate/evalengine/translate.go, go/vt/vtgate/planbuilder/horizon_planning.go
This was accidentally removed in https://github.com/vitessio/vitess/pull/10512 but it shouldn't have
been.
It also updates the usage of a `type_` variable which the linters on older releases that use Go 1.17 will complain about (but the linter was disabled for Go 1.18). 
#10512
=> Add back unary single column expression check

go/vt/vtctl/grpcvtctldserver/server.go, go/vt/vtctl/reparentutil/durability.go, go/vt/vtctl/reparentutil/emergency_reparenter.go, go/vt/vtctl/reparentutil/planned_reparenter.go, go/vt/vtctl/reparentutil/replication.go, go/vt/wrangler/reparent.go
This PR is the backport for #10516 which removes a log statement that was being overtly noisy.
=> Backport to release-14: Remove logging in GetDurabilityPolicy #10516

.github/workflows/comment_pull_request.yml
This cherry-picks #10471 and adds the review checklist to the `release-13.0` branch.
=> Add review checklist on `release-13.0`

go/vt/vtadmin/api_authz_test.go, go/vt/vtadmin/testutil/authztestgen/config.json
What it says on the tin.
Before, `go test -race -run '.*Schema.*' -count=10 ./go/vt/vtadmin/` failed reliably locally, and passes reliably (N=3, to be fair) now.
=> [vtadmin/tests] Serialize Schema test cases to avoid cache backfill races

go/test/endtoend/vtctldweb/vtctld_web_test.go
Signed-off-by: notfelineit <notfelineit@gmail.com>
The selenium test for `TestCreateKs` is always flaky. After hunting around the web, my hunch is that _sometimes_ the DOM has not updated before the test executes `getDashboardKeyspaces`. To address randomness in DOM rendering, I've added an explicit wait for the DOM to refresh and render the new keyspace HTML objects. While that seems weird, at the end of the day there is some randomness in DOM rendering (from the network, machine, etc.).
I think this is the issue because while the test only tests creating 1 new keyspace `test-keyspace-3`, the failing tests show that none of the keyspaces show up (which doesn't make any sense):
```
I0610 00:59:44.459026   13243 vschema_manager.go:102] Received vschema update
vtctld_web_test.go:137: 
Error …
```
=> Fixing flaky vtctld2 web test

.github/workflows/upgrade_downgrade_test_backups_e2e.yml, .github/workflows/upgrade_downgrade_test_backups_manual.yml, .github/workflows/upgrade_downgrade_test_query_serving.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml, tools/get_previous_release.sh
This is a backport of #10504 on `release-13.0`.
- fixes https://github.com/vitessio/vitess/pull/10503
=> [13.0] Take into account `github.ref` when doing upgrade-downgrade tests

go/vt/vtadmin/testutil/authztestgen/functions.go, go/vt/vtadmin/testutil/authztestgen/main.go, go/vt/vtadmin/testutil/authztestgen/template.go
This extends the `authztestgen` code to include a template to also generate the markdown table of RBAC rules on the website, used in https://github.com/vitessio/website/pull/1018.
Explicitly calling these out (happy to hear disagreement on either point!):
- I don't think we should bother backporting this PR.
- I think this is one of the very few cases we actually want release-notes-none, but happy to hear disagreement!
=> [vtadmin] Add authzdocsgen to generate some website docs

.github/workflows/upgrade_downgrade_test_backups_e2e.yml, .github/workflows/upgrade_downgrade_test_backups_manual.yml, .github/workflows/upgrade_downgrade_test_query_serving.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml
This Pull Request changes the Go version used in the upgrade downgrade tests. It was set to `go1.17.11`, with this change it will use `go1.18.3` which is compatible with any release of Vitess.
While fixing this problem, I have realized that upgrade downgrade tests on `v13` are testing the current commit and the latest version of vitess, which is in this case: `release-14.0` ; instead it should use the "previous" release: `release-12.0`. I will open a follow-up issue.
=> Fix upgrade-downgrade build on `release-13.0`

go/tools/release-notes/release_notes.go, go/tools/release-notes/release_notes_test.go
=> [14.0] Rework the generation of the release notes

go/vt/vttablet/tabletserver/schema/engine.go, go/vt/vttablet/tabletserver/schema/engine_test.go
We had found a deadlock which resulted in schema Engine close being blocked. 
The steps that led to the deadlock are - 
* We start the schema engine shutdown (engine.Close())
* we take the schema engine mutex lock, and start the rest of the schema engine shutdown
* but before we can get to stopping the timer for the schema reload
* the timer starts up and executes engine.ReloadAt, which tries to take the schema engine mutex lock (waits).
* At this point engine.Close() tries to stop the timer, but since the timer is executing, that waits for the execution to complete.  And we have a deadlock.
This PR adds a unit test for this failure and also fixes it. 
The proposed fix is to try and stop the timer in a separate go routine and wait for it to finish **after** releasing the mutex lock. What …
=> Fix schema engine close and ticks race

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/test/endtoend/vtgate/queries/aggregation/schema.sql, go/test/endtoend/vtgate/queries/aggregation/vschema.json, go/vt/vtgate/engine/ordered_aggregate.go, go/vt/vtgate/engine/projection_test.go, go/vt/vtgate/engine/scalar_aggregation.go, go/vt/vtgate/engine/scalar_aggregation_test.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/ordered_aggregate.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/planbuilder/testdata/memory_sort_cases.txt, go/vt/vtgate/planbuilder/testdata/postprocess_cases.txt, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/planbuilder/testdata/tpch_cases.txt, go/vt/vtgate/planbuilder/testdata/union_cases.txt
Backport of PR #10465 
This PR fixes two bugs in scalar aggregation engine primitive
1. Scalar aggregation was returning wrong output for empty row on count aggregation
2. Scalar aggregation in streaming mode was not handling empty row and also final convert logic.
This was caused when we moved from using AggregateSum over AggregateCount as opcode for count(*). As the actual operation at the engine primitive level was sum of count, this caused a negative effect of returning `NULL` for empty row instead of `0`.
=> [14.0] fix: scalar aggregation engine primitive

go/vt/vtadmin/api_authz_test.go, go/vt/vtadmin/testutil/authztestgen/template.go
use individual API instances for certain test cases to prevent cross-test pollution. i've left a loop running overnight and we're at ~1500 successful test runs
fixes #10549 
=> [vtadmin] fix flaky GetSchemas test cases

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/vt/vtgate/planbuilder/aggregation_pushing.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.txt, go/vt/vtgate/planbuilder/testdata/tpch_cases.txt
Backport of https://github.com/vitessio/vitess/pull/10480
This PR fixes an aggregation-grouping bug in gen4 that does non-scalar aggregates on a top of a join. 
This happens when the left side of the join has data and no data is present on the right hand side.
If the right hand side of the join only contains an aggregation then even though the table has no data it will return count(*) as `0` and that will get mapped to the join output.
To avoid such scenario the change adds a grouping condition on the right hand side using literal 1 so that the rows from right hand side is only returned when the join condition matches.
=> [14.0] fix: aggregation empty row on join with grouping and aggregations

go/vt/orchestrator/config/config.go, go/vt/orchestrator/logic/topology_recovery.go, go/vt/orchestrator/logic/topology_recovery_test.go
A panic was seen in VTOrc with the following log - 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xec5205]
goroutine 1444 [running]:
vitess.io/vitess/go/vt/orchestrator/logic.electNewPrimary({_, _}, {{{0xc00134cd70, 0xc}, 0xcea}, {{0xc00134ce80, 0xc}, 0xcea}, 0x2, {0x0, ...}, ...}, ...)
vitess.io/vitess/go/vt/orchestrator/logic/topology_recovery.go:1778 +0x485
vitess.io/vitess/go/vt/orchestrator/logic.executeCheckAndRecoverFunction({{{0xc00134cd70, 0xc}, 0xcea}, {{0xc00134ce80, 0xc}, 0xcea}, 0x2, {0x0, 0x0, 0x0}, ...}, ...)
vitess.io/vitess/go/vt/orchestrator/logic/topology_recovery.go:1395 +0xbbe
vitess.io/vitess/go/vt/orchestrator/logic.CheckAndRecover.func1() …
```
=> Fix panic in VTOrc

doc/releasenotes/14_0_0_summary.md, doc/releasenotes/15_0_0_summary.md
Amendment to https://github.com/vitessio/vitess/pull/10443; https://github.com/vitessio/vitess/pull/10443 was created pre v14, but did not make it to v14. However, it was merged with v14 release notes.
This PR moves the PR's release notes out of v14 and into v15; it also reflects updates to the metrics format.
https://github.com/vitessio/vitess/pull/10443
=> Throttler stats: amendment

go/flags/endtoend/vttablet.txt, go/vt/vttablet/tabletmanager/vreplication/controller.go, go/vt/vttablet/tabletmanager/vreplication/last_error.go, go/vt/vttablet/tabletmanager/vreplication/last_error_test.go, go/vt/vttablet/tabletmanager/vreplication/utils.go, go/vt/vttablet/tabletmanager/vreplication/vplayer_flaky_test.go, go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
As part of an initial design decision, VReplication workflows always retry in case it encounters an error after sleeping for 5 seconds. The reasoning was that, for large reshards/migrations and perpetual materialize workflows, we could often encounter recoverable errors like PRS, restarting of vttablets/mysql servers, network partitions etc. So rather than error out waiting for an operator to manually restart workflows we decided to keep retrying. 
Since we only retried every five seconds any resource wastage due to continuously retrying unrecoverable workflows would be small and in most cases we would transparently recover and make forward progress with minimum downtime. This is especially important for Materialize workflows were the user is expecting near realtime performance.
Usually …
=> Fail VReplication workflows on errors that persist and unrecoverable errors

go/vt/vtgate/vstream_manager.go
This PR fixes a couple of memory leaks in the VStream API which was causing vtgates to OOM.
* Check for cancelled context when events received from the source were being sent into a event channel for eventual streaming to the vstream api client.
* When a context is cancelled, in the vstream API we need to return an error in the health streamer callback. Otherwise it keeps streaming and leaking (goroutines and ) grpc request buffers.
=> VStream API: Fix vtgate memory leaks when context gets cancelled

go/vt/vtgate/vstream_manager.go
This PR fixes a couple of memory leaks in the VStream API which was causing vtgates to OOM.
* Check for cancelled context when events received from the source were being sent into a event channel for eventual streaming to the vstream api client.
* When a context is cancelled, in the vstream API we need to return an error in the health streamer callback. Otherwise it keeps streaming and leaking (goroutines and ) grpc request buffers.
=> Cherry pick of VStream API: Fix vtgate memory leaks when context gets cancelled

.github/workflows/release_notes_label.yml
This PR fixes the improper quoting in the release notes label CI workflow which was causing it to fail.
Additionally, the helper shows the actual release summary filename.
=> Fixed the release notes CI check helper

docker/lite/Dockerfile.alpine, docker/lite/Dockerfile.mariadb, docker/lite/Dockerfile.mariadb103, docker/lite/Dockerfile.mysql80, docker/lite/Dockerfile.percona57, docker/lite/Dockerfile.percona80, docker/lite/Dockerfile.testing, docker/lite/Dockerfile.ubi7.mysql57, docker/lite/Dockerfile.ubi7.mysql80, docker/lite/Dockerfile.ubi7.percona57, docker/lite/Dockerfile.ubi7.percona80, docker/lite/Dockerfile.ubi8.arm64.mysql80, docker/lite/Dockerfile.ubi8.mysql80
In #9405 we added vtadmin web files (not binaries) to only the mysql57 version of `vitess/lite`. This PR adds them to all flavors of the `lite` image.
#9405 #10543
=> add vtadmin web files to all lite images

doc/releasenotes/14_0_0_summary.md, go/test/endtoend/vreplication/config_test.go, go/test/endtoend/vreplication/vdiff2_test.go, go/test/endtoend/vreplication/vdiff_helper_test.go, go/test/endtoend/vreplication/vreplication_test.go, go/vt/vtctl/vdiff2.go, go/vt/vttablet/tabletmanager/vdiff/action.go, go/vt/vttablet/tabletmanager/vdiff/controller.go, go/vt/vttablet/tabletmanager/vdiff/report.go, go/vt/vttablet/tabletmanager/vdiff/schema.go, go/vt/vttablet/tabletmanager/vdiff/table_differ.go, go/vt/vttablet/tabletmanager/vdiff/utils.go, go/vt/vttablet/tabletmanager/vdiff/workflow_differ.go, go/vt/wrangler/vdiff2.go
This is a backport of https://github.com/vitessio/vitess/pull/10497. While the primary intention of that work was to add a new feature — namely `Resume` — in the process of implementing that it became clear that [the existing VDiff2 work in 14.0](https://github.com/vitessio/vitess/pull/10382) could easily produce incorrect results and was not easy to validate or debug. There were also a number of other smaller/minor bugs that were fixed in that work. All of this made it very challenging for early adopters to try it out, get value, and provide meaningful feedback (which was the entire reason to get the experimental version into 14.0 in the first place). Because of this, combined with the fact that VDiff2 is experimental and has isolated code, we are backporting this work for 14.0 GA …
=> Backport: VDiff2: Support Resuming VDiffs

.github/workflows/upgrade_downgrade_test_backups_e2e.yml, .github/workflows/upgrade_downgrade_test_backups_manual.yml, .github/workflows/upgrade_downgrade_test_query_serving_queries.yml, .github/workflows/upgrade_downgrade_test_query_serving_schema.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml
This Pull Request removes the job that checks the `skip upgrade downgrade` label in the upgrade downgrade workflows.
=> Removed the check label in upgrade downgrade tests

go/vt/mysqlctl/fakemysqldaemon/fakemysqldaemon.go, go/vt/mysqlctl/mysql_daemon.go, go/vt/mysqlctl/schema.go, go/vt/schemamanager/schemamanager_test.go, go/vt/schemamanager/tablet_executor.go, go/vt/vtcombo/tablet_map.go, go/vt/vtctl/grpcvtctldserver/server.go, go/vt/vtctl/grpcvtctldserver/testutil/test_tmclient.go, go/vt/vtctl/schematools/diff.go, go/vt/vtctl/schematools/schematools.go, go/vt/vttablet/faketmclient/fake_client.go, go/vt/vttablet/grpctmclient/client.go, go/vt/vttablet/grpctmserver/server.go, go/vt/vttablet/tabletmanager/rpc_agent.go, go/vt/vttablet/tabletmanager/rpc_schema.go, go/vt/vttablet/tabletmanager/vdiff/workflow_differ.go, go/vt/vttablet/tabletmanager/vreplication/vreplicator.go, go/vt/vttablet/tmclient/rpc_client_api.go, go/vt/vttablet/tmrpctest/test_tm_rpc.go, go/vt/worker/multi_split_diff.go, go/vt/worker/split_clone.go, go/vt/worker/split_diff.go, go/vt/worker/vertical_split_diff.go, go/vt/wrangler/materializer.go, go/vt/wrangler/materializer_env_test.go, go/vt/wrangler/resharder_env_test.go, go/vt/wrangler/schema.go, go/vt/wrangler/vdiff.go, go/vt/wrangler/vdiff_env_test.go, go/vt/wrangler/wrangler_env_test.go
This is a code cleanup PR, following up on Vitess Office Hours from `2022-06-23`.
We "unexplode" the `GetSchema` function signature, across the board, and reuse `tabletmanagerdatapb.GetSchemaRequest` as a replacement container for the multiple arguments it receives. Example:
```go
GetSchema(ctx context.Context, request *tabletmanagerdatapb.GetSchemaRequest) (*tabletmanagerdatapb.SchemaDefinition, error)
```
In some places we now just need to pass the request around. In others (notably `vdiff` related code) we programmatically construct a `tabletmanagerdatapb.GetSchemaRequest` instance and send it to `GetSchema`.
I think this went well. The code is simpler; when constructing `tabletmanagerdatapb.GetSchemaRequest`, we only point out the non-default variables, which is very clear. In the …
=> Cleanup: un-explode GetSchema and reuse GetSchemaRequest struct

go/test/endtoend/cluster/topo_process.go, go/test/endtoend/vreplication/cluster_test.go
We were relying on an ENV variable being set — `ETCDCTL_API=2` — when running tests locally with [etcd 3.4+ where the v2 api is disabled by default](https://etcd.io/docs/v3.4/upgrades/upgrade_3_4/#make-etcd---enable-v2false-default).
And we were swallowing errors when creating the initial topo data. This led to confusing test failures later on when e.g.
creating the keyspace:
```
E0615 13:58:10.394159   48632 vtctl_process.go:66] CreateKeyspace returned err: exit status 255, output: E0615 13:58:10.276250   48641 vtctl.go:170] action failed: CreateKeyspace GetKnownCells failed: node doesn't exist: /vitess/global/cells/
```
-   [x] Tests were updated
=> Make etcd based tests more deterministic and surface errors

doc/releasenotes/14_0_0_summary.md
This Pull Request updates the release-14 summary in preparation for the `v14` GA.
Includes:
- A backport of #10567.
=> [14.0] Update and prepare the `v14.0.0` summary

doc/releasenotes/14_0_0_release_notes.md, doc/releasenotes/14_0_0_summary.md
We forgot to document this in the summary release notes.
#10595 
-   [x] Documentation was added or is not required https://github.com/vitessio/website/pull/1078
=> release notes: schema tracking no longer experimental

go/test/endtoend/vreplication/vdiff2_test.go, go/test/endtoend/vreplication/vdiff_helper_test.go, go/vt/vtctl/vdiff2.go, go/vt/vttablet/tabletmanager/vdiff/action.go, go/vt/vttablet/tabletmanager/vdiff/schema.go, go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/vexec.go
The primary thing that this PR does is add the `VDiff -- --v2 <keyspace>.<workflow> delete {all,<UUID>}` VDiff command action. 
Secondly, it purges any VDiff records for a workflow when that workflow is deleted via:
- &lt;workflow&gt; complete
- &lt;workflow&gt; cancel
- &lt;workflow&gt; delete
Lastly, it also adds a `--verbose` flag for `VDiff show` output.
- Fixes: https://github.com/vitessio/vitess/issues/10609
-   [x] Documentation: https://github.com/vitessio/website/pull/1079
=> Implement VDiff2 Delete Action

go/vt/sqlparser/testdata/select_cases.txt
There are over 500 test cases in `select_cases.txt` that are all invalid because it uses `select from`. This is more likely a mistake, since the queries are valid if this is changed to `select * from`.
Moving this exercises more valid queries and improves test coverage. Having 500+ cases that all test the exact same parse error isn't useful so I think this change is a net improvement.
Found as part of work on #10203 & #8604
=> Use many more valid test cases

go.mod
We Slack have regular security vulnerability scan on all software we are using in production. The latest scan detect some golang packages that Vitess uses exposing security vulnerabilities. Thus in this PR, we are trying to upgrade the versions of those packages.
=> upgrade versions of security vulnerable packages crypto/net/serf

tools/unit_test_runner.sh
Some tests use `t.TempDir` ([docs](https://pkg.go.dev/testing#B.TempDir)) to create temp dirs for storing per-test
files, such as MySQL configuration files and logs.
On Mac OS, this can generate long directory names, such as
`/var/folders/96/k7gzd7q10zdb749vr02q7sjh0000gn/T/tmp.yqDFqOY3`. If during
a test a mysqld socket is put in a long directory like that, mysql
client won't be able to connect to it, and the test will fail.
This commit modifies `tools/unit_test_runner.sh` so that on Mac OS, as
long as TMPDIR isn't already set, it will export
`TMPDIR=/tmp/vttest_XXXXX` (where `XXXXXX` is dynamically replaced with
random characters). Golang uses that as a base for further temporary
files and directories.
Fixes #10649
-   [x] "Backport me!" label has been added if this change should be …
=> test: for unit tests set TMPDIR=/tmp_XXXXXX on mac

go/vt/orchestrator/logic/tablet_discovery.go, go/vt/orchestrator/logic/topology_recovery.go
This PR changes the last remaining recovery function of VTOrc `fixReplica` to also use TabletManagerClient RPCs instead of running operations on the MySQL instance directly. 
In `fixReplica`, there are multiple things that need to be fixed - 
- The correct primary source should be set
- Replication should be started
- Correct semi-sync settings should be set
- The tablet should be read-only
The first 3 things are accomplished by `SetReplicationSource` RPC and the last by `SetReadOnly` RPC. Functionally, there is no difference from the user standpoint, but internally, now VTOrc talks to MySQL through the vttablet. 
As part of the PR, I also clean up the `fixPrimary` function. The code to set semi-sync directly on the MySQL instance was redundant since the following RPC already accomplished …
=> Use TMC RPCs in VTOrc

go/test/endtoend/vtorc/general/vtorc_test.go, go/test/endtoend/vtorc/utils/utils.go, go/vt/orchestrator/inst/instance_dao.go
This PR adds and end to end reproducing the linked issue wherein if the durability policy is set after VTOrc startup, VTOrc cannot pick up the changes and does not discover the vttablets at all, even after a lot of time elapses.
The problem was found in the loop where we refresh the MySQL information for vttablets. There we were only looking for tablets that were outdated i.e. their last valid check was older than the configured time.
In case the durability policy doesn't exist when the tablets are first discovered, we do not read the MySQL information and exit out early, leading to the tablet not being present in the `database_instance` table at all.
Therefore, the fix entails also checking for these tablets as well in the refresh code. The way to find these tablets is to find the ones …
=> Fix VTOrc Discovery to also retry discovering tablets which aren't present in database_instance table

go/test/endtoend/vtctldweb/vtctld_web_test.go
This is a backport of https://github.com/vitessio/vitess/pull/10541.
=> [13.0] Fixing flaky vtctld2 web test (#10541)

go/test/endtoend/vtctldweb/vtctld_web_test.go
This is a backport of https://github.com/vitessio/vitess/pull/10541.
=> [14.0] Fixing flaky vtctld2 web test (#10541)

go/test/endtoend/reparent/newfeaturetest/reparent_test.go
This PR is the equivalent of the commit https://github.com/vitessio/vitess/pull/10665/commits/b4b3848c7ef6f5a2f6c75c7dc886dfff7a58d428 on main. It changes the test `TestFullStatus` to run with MySQL 8.0 too and also reduces  the flakiness of the test
=> Fix full status test to work with both MySQL versions and de-flake it

go/vt/vtgate/executor.go, go/vt/vtgate/logstats.go, go/vt/vtgate/logstats_test.go, go/vt/vttablet/tabletserver/query_engine.go
We have seen the cache miss metric numbers are typically on the higher side. I looks like we are trying to get plan from cache for SQL queries like "COMMIT", "ROLLBACK" etc. This result in unnecessary increment in cache miss counter. 
Also inorder to debug better we are adding PlanCache field in logstats object.
#10626 
=> Fix stats for cache miss and add CachePlan for Vtgate

go/test/endtoend/utils/utils.go, go/test/endtoend/vtgate/reservedconn/main_test.go, go/test/endtoend/vtgate/reservedconn/sysvar_test.go
This PR fixes the e2e test setup for reserved connection where the parameter to be set on vtgate was set on vttablet. This fixes that.
=> test: set parameter on vtgate than on vttablet

doc/releasenotes/15_0_0_summary.md
As part of this PR https://github.com/vitessio/vitess/pull/10632 the vindex interface methods were modified to add context to the method parameters.
This PR documents those breaking change in the summary release notes.
- https://github.com/vitessio/vitess/pull/10632
=> added vindex interface breaking change to summary notes

go/vt/vtgate/tabletgateway.go, go/vt/vtgate/tx_conn_test.go
In MULTI transactional mode, errors can occur at different phases:
1. When the transaction is started (e.g. with `BEGIN`).
2. Inside the transaction.
3. When the transaction is committed (e.g. with `COMMIT`).
Error messages generated within-transaction include the shard name,
e.g.:
> ERROR 1317 (70100): target: keyspace2.c0-.primary: vttablet: ...
However, messages generated in the commit phase do not:
> ERROR 1317 (70100): vttablet: rpc error: code = Canceled desc...
This commit injects shard name into commit-phase errors.
#10692 
=> Inject shard name in commit-phase multi-shard errors

go/test/endtoend/vtgate/reservedconn/main_test.go, go/test/endtoend/vtgate/reservedconn/sysvar_test.go
Backport of https://github.com/vitessio/vitess/pull/10698
This PR fixes the e2e test setup for reserved connection where the parameter to be set on vtgate was set on vttablet. This fixes that.
=> [14.0] set parameter on vtgate than on vttablet

go/vt/schemamanager/tablet_executor.go
This PR optimizes calls to `ApplySchema`, as following:
Previously, and when multiple SQLs are received, `ApplySchema` would call a `ReloadSchema` after every single SQL execution, and wait on replica to catch up. This is wasteful, because the schema is known to change again and again for next SQLs.
As of this PR, TabletExecutor first applies all SQLs (still one by one), and then, once for each shard, waits on replication lag and calls `ReloadSchema`.
Online DDL calls are asynchronous. The schema is not going to change after submitting the Online DDL anyway. If all SQLs are Online DDLs, then we skip `ReloadSchema` altogether.
We make no change to existing tests. We expect this refactor to pass all tests.
#6926 
-   [ ] "Backport me!" label has been added if this change should be …
=> Tablet Executor: consolidate ReloadSchema calls, and skip for Online DDL

go/test/endtoend/reparent/emergencyreparent/ers_test.go, go/test/endtoend/reparent/plannedreparent/reparent_test.go, go/test/endtoend/reparent/utils/utils.go
The `ers_prs_heavy` workflow has been very flaky in this PR: https://github.com/vitessio/vitess/pull/10639. Often having to run 4+ times to succeed. I suspect that all of [the new DDL](https://github.com/vitessio/vitess/pull/10639/files#diff-0842ac0cabd40352e88bfcb98b9a9ae213d441b11eabc4bc51afbd47e211db56) executed at tablet init when the VDiff engine opens is causing replication to be slightly slower and thus we're getting this basic error from various individual tests (the ID and specific test differing on the failed runs):
```
2022-07-17T21:32:58.8852569Z     utils.go:348: 
2022-07-17T21:32:58.8852912Z         	Error Trace:	utils.go:354
2022-07-17T21:32:58.8853472Z         	            				utils.go:348
2022-07-17T21:32:58.8853942Z         	            				utils.go:526 …
```
=> Reduce Flakiness of ERS/PRS e2e Tests Using Retries With a Timeout

go/vt/vtgate/planbuilder/gen4_compare_v3_planner.go
This PR fixes a bug in the Gen4CompareV3 planner wherein it reverted to running the Gen4 planner when it got an `Update` query. This change affected the future queries coming in which weren't run with Gen4CompareV3 and instead run with Gen4 only.
Fixes https://github.com/vitessio/vitess/issues/10721
=> BugFix: Gen4CompareV3 planner reverted to Gen4 on Update queries

go/test/endtoend/vtgate/misc_test.go, go/vt/vtgate/planbuilder/physical/route_planning.go, go/vt/vtgate/planbuilder/testdata/select_cases.txt
This PR fixes the bug found in https://github.com/vitessio/vitess/issues/10713. 
The plan for the query found there with Gen4 using the vschema provided was - 
```json
{
"Original": "select user.id, team.id from user join team_member on user.id = team_member.user join team on team_member.team = team.id where user.email = 'alice@gmail.com'",
"OperatorType": "Join",
"Variant": "Join",
"JoinColumnIndexes": "L:0,R:0",
"JoinVars": {
"user_id": 0
},
"TableName": "`user`_team, team_member",
"Inputs": [
{
"Variant": "EqualUnique",
"Keyspace": {
"Name": "customer",
},
"FieldQuery": "select `user`.id from `user` where 1 != 1",
"Query": "select `user`.id from `user` where `user`.email = 'alice@gmail.com'",
"Table": …
```
=> BugFix: Keep predicates in join when pushing new ones

go/test/endtoend/reparent/emergencyreparent/ers_test.go, go/test/endtoend/reparent/plannedreparent/reparent_test.go, go/test/endtoend/reparent/utils/utils.go
This PR cleans up the ERS and PRS tests by removing `setupShardLegacy`. We should use `setupShard` instead since we did the release. If we need version specific flags, then we should use the `version` information that we store now instead of duplicating the setup functions.
=> Cleanup: ERS and PRS tests by removing setupShardLegacy

go/timer/rate_limiter.go, go/vt/schemamanager/tablet_executor.go, go/vt/topo/locks.go
Followup to #10719. Before applying DDLs, `TabletExecutor` acquires a _keyspace_ lock. It then iterates all SQLs, applies them, and finally releases the lock.
When there's a large number of SQLs, the iteration can take a lon gtime. #10719 already reduces that time. However, applying SQLs can still take longer than the lock timeout. What we've seen happening was that SQLs were applied, but when it came to unlocking the keyspace, the lock was expired and the unlock operation failed.
In this PR we renew the lock on each SQL iteration. This is a naive implementation and perhaps too aggressive. We could later refine this to renew once per X seconds, for example. **UPDATE:** now calls are rate limited.
With this change, the lock will not expire on reasonable DDLs. Specifically, Online DDLs are …
=> ApplySchema: renew keyspace lock while iterating SQLs

.golangci.yml
Doing this is almost always a bug anyway so we should lint for this to avoid problems.
This would have caught the bug that was plaguing us in https://github.com/vitessio/vitess/pull/10739 as it's easy to overlook this type of issue. So we'd rather prefer the linter catches it for next time.
Adding because of the issue found in https://github.com/vitessio/vitess/pull/10739
=> Add the linter for exporting a loop variable through a pointer reference

go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/vexec.go, go/vt/wrangler/workflow.go
It is possible that the _vt.vdiff tables do not exist when attempting to purge records when a vreplication workflow is deleted, so we no longer log the resulting errors
fixes #10726
=> VDiff2: ignore errors while attempting to purge vdiff tables 

go/mysql/collations/tools/makecolldata/contractions.go, go/vt/vtgate/engine/cached_size.go
The logic here was accidentally correct since we always in practice grab the pointer only on the last iteration, so it works.
But the loop pointer linter catches this as an issue which is a good thing. Let's make it explicit how we capture this variable so there's no confusion and the linter also is happy about it.
This is the only other case the new linter alerts on in the codebase it looks apart from the bug fix that is in progress in https://github.com/vitessio/vitess/pull/10739
=> Be explicit about capturing the pointer

go/test/endtoend/cluster/vtgate_process.go, go/test/endtoend/vtgate/schematracker/unauthorized/unauthorized_test.go
This PR updates the flag used in the end-to-end tests for the planner version. If the binary `vtgate` is below version `14` (which is the case during upgrade downgrade tests on `release-14.0`, we use vtgate `13` at some point), the flag `--planner-version`  is unknown and leads to the test failing to start, and ultimately, timeout.
We do not need to backport or forward port this as this issue is only happening in `release-14.0`. For the issue to be reproduced, we need to run the end-to-end tests that live on `v14.x` with a vtgate built using `<= v13.x` code.
=> Use the old planner version flag in v14 upgrade-downgrade tests

go/vt/vtcombo/tablet_map.go, go/vt/vtgate/vstream_manager.go, go/vt/vttablet/endtoend/vstreamer_test.go, go/vt/vttablet/grpcqueryservice/server.go, go/vt/vttablet/grpctabletconn/conn.go, go/vt/vttablet/queryservice/queryservice.go, go/vt/vttablet/queryservice/wrapped.go, go/vt/vttablet/sandboxconn/sandboxconn.go, go/vt/vttablet/tabletconntest/fakequeryservice.go, go/vt/vttablet/tabletmanager/vdiff/table_differ.go, go/vt/vttablet/tabletmanager/vreplication/external_connector.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletserver/tabletserver.go
Similar to #10578 , we change function signatures:
- `VStream()` now uses `VStreamRequest` instead of 4 arguments
- `VStreamRows()` now uses `VStreamRowsRequest` instead of 3 argument
After this change, it is cleaner to pass the request, and easier to add new flags/parameters -- we just need to add them to `proto` as fields in `VStreamRequest/VStreamRowsRequest` instead of editing a dozen files and edit function signatures again.
none. similar to #10578
=> refactor: unexplode VStreamRows() and reuse VStreamRowsRequest, unexplode VStream() and reuse VStreamRequest

go/vt/vtctl/vtctl.go, go/vt/wrangler/workflow.go
This change was missed in https://github.com/vitessio/vitess/pull/9904 so it doesn't work for v2 right now.
https://github.com/vitessio/vitess/pull/9904 which missed this change
This also will need to be backported to 14 then which is missing this bit as well.
=> Add drop_foreign_keys to v2 MoveTables command

go/vt/vttablet/onlineddl/executor.go
As we look to reduce the footprint of `ApplySchema`, we removed excessive calls to `ReloadSchema` (see linked PRs follwing). We also noted that any `ReloadSchema` for Online DDL operations is irrelevant in `ApplySchema` because the actual schema change runs asynchronously, and almost certainly _after_ `ApplySchema` completes.
In this PR we make sure to call `ReloadSchema` at the end of any successful schema change. Up till now, this was only true for `vitess` `ALTER` migrations. Not it applies to `CREATE`, `DROP`, `gh-ost`, `pt-osc` migrations, including "fast" migrations and View migrations.
In the future we wish to further reduce the footprint by only reloading a single table, instead of the entire schema.
No tests are changed. We expect all existing tests to pass.
- …
=> Online DDL: issue a ReloadSchema at the completion of any migration

go/vt/vtgate/vstream_manager.go
This PR fixes a couple of memory leaks in the VStream API which was causing vtgates to OOM.
* Check for cancelled context when events received from the source were being sent into a event channel for eventual streaming to the vstream api client.
* When a context is cancelled, in the vstream API we need to return an error in the health streamer callback. Otherwise it keeps streaming and leaking (goroutines and ) grpc request buffers.
https://github.com/vitessio/vitess/pull/10571
=> [release-13.0] VStream API: Fix vtgate memory leaks when context gets cancelled #10571

go/vt/wrangler/traffic_switcher.go, go/vt/wrangler/vexec.go, go/vt/wrangler/workflow.go
It is possible that the _vt.vdiff tables do not exist when attempting to purge records when a vreplication workflow is deleted, so we no longer log the resulting errors
fixes #10726
=>  [release-14.0] VDiff2: ignore errors while attempting to purge vdiff tables (#10725)

go/timer/rate_limiter.go, go/timer/rate_limiter_test.go, go/vt/schemamanager/tablet_executor.go, go/vt/topo/locks.go, go/vt/vttablet/onlineddl/executor.go
This is the combined cherry pick of the following PRs:
- https://github.com/vitessio/vitess/pull/10719
- https://github.com/vitessio/vitess/pull/10727
- https://github.com/vitessio/vitess/pull/10755
- https://github.com/vitessio/vitess/pull/10739
- https://github.com/vitessio/vitess/pull/10766
All these PRs address a specific issue: the calls to `ReloadSchema` on `ApplySchema`. Combined, they reduce the amount of `ReloadSchema` operations from `O(n^2)` to `O(n)`. They also ensure `ReloadSchema` is calls at the end of any Online DDL migration; previously the calls to `ReloadSchema` were out of sync with Online DDL migrations.
=> Backport v14: reduce ApplySchema complexity, normalize calls to `ReloadSchema`

go/test/endtoend/onlineddl/vrepl_stress_suite/onlineddl_vrepl_stress_suite_test.go, go/timer/rate_limiter.go, go/timer/rate_limiter_test.go
Backport of https://github.com/vitessio/vitess/pull/10779
=> Backport v14: fixing onlineddl_vrepl_stress_suite flakiness in CI (#10779)

go/vt/vtcombo/tablet_map.go, go/vt/vtctl/query.go, go/vt/vtexplain/vtexplain_vttablet.go, go/vt/vtgate/scatter_conn.go, go/vt/vtgate/tabletgateway_test.go, go/vt/vttablet/endtoend/framework/client.go, go/vt/vttablet/grpcqueryservice/server.go, go/vt/vttablet/grpctabletconn/conn.go, go/vt/vttablet/queryservice/fakes/stream_health_query_service.go, go/vt/vttablet/queryservice/queryservice.go, go/vt/vttablet/queryservice/wrapped.go, go/vt/vttablet/sandboxconn/sandboxconn.go, go/vt/vttablet/tabletconntest/fakequeryservice.go, go/vt/vttablet/tabletconntest/tabletconntest.go, go/vt/vttablet/tabletserver/query_executor_test.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tabletserver_test.go
This adds a small wrapper struct instead of separate return arguments to make it easier to refactor and change this in the future.
This is a much simpler alternative to https://github.com/vitessio/vitess/pull/10775 which ended up being much more invasive with all the conversion changes etc.
The changes here are much more targeted and only specifically for transaction / reservation related return values so we can simplify those explicitly. 
See https://github.com/vitessio/vitess/pull/10671 for similar refactors.
=> Unexplode return values for queryservice

go/vt/sqlparser/ast.go, go/vt/sqlparser/ast_clone.go, go/vt/sqlparser/ast_equals.go, go/vt/sqlparser/ast_rewrite.go, go/vt/sqlparser/ast_visit.go, go/vt/vtgate/engine/cached_size.go
These should also implement the iCallable interface as they are also callable as functions.
This was missed in #10347
=> Mark aggregate functions callable

go/test/endtoend/vreplication/vdiff2_test.go, go/test/endtoend/vreplication/vdiff_helper_test.go, go/vt/vtctl/vdiff2.go, go/vt/vttablet/tabletmanager/vdiff/engine.go
This adds the `--wait` flag for the [`Create`](https://vitess.io/docs/15.0/reference/vreplication/vdiff2/#start-a-new-vdiff) and [`Resume`](https://vitess.io/docs/15.0/reference/vreplication/vdiff2/#resume-a-previous-vdiff) actions so that you can see the progress as it runs — current status checked and displayed every `--wait-update-interval` which is 1 minute by default — and be informed  when it successfully completes or exits with an error.
- Fixes: https://github.com/vitessio/vitess/issues/10798
-   [x] Documentation: https://github.com/vitessio/website/pull/1110
=> VDiff2: Add --wait flag to Create/Resume actions

go/cmd/mysqlctl/mysqlctl.go, go/cmd/query_analyzer/query_analyzer.go, go/cmd/topo2topo/topo2topo.go, go/cmd/vtbench/vtbench.go, go/cmd/vtclient/vtclient.go, go/cmd/vtctlclient/main.go, go/cmd/vtgate/vtgate.go, go/cmd/vtgr/main.go, go/cmd/vttlstest/vttlstest.go, go/cmd/zk/zkcmd.go, go/cmd/zkctl/zkctl.go, go/cmd/zkctld/zkctld.go, go/flags/endtoend/vtgate.txt, go/flags/endtoend/vttablet.txt, go/internal/flag/flag.go, go/test/endtoend/topoconncache/topo_conn_cache_test.go, go/test/endtoend/vtorc/general/vtorc_test.go, go/vt/servenv/servenv.go, go/vt/vtctld/api_test.go, go/vt/vtgate/tabletgateway.go, go/vt/vtgate/tabletgateway_flaky_test.go, go/vt/wrangler/testlib/planned_reparent_shard_test.go, java/grpc-client/src/test/java/io/client/grpc/GrpcClientStaticAuthTest.java, java/grpc-client/src/test/java/io/client/grpc/GrpcClientTest.java, java/grpc-client/src/test/java/io/client/grpc/GrpcClientTlsClientAuthTest.java, java/grpc-client/src/test/java/io/client/grpc/GrpcClientTlsTest.java, java/grpc-client/src/test/java/io/client/grpc/GrpcClientWithRetriesTest.java
This PR begins the next step in the implementation of [VEP-4](https://github.com/vitessio/enhancements/blob/main/veps/vep-4.md), officially moving us to using `pflag` in all of our CLI flag parsing. It does **not** migrate any flag definitions (except one small proof-of-concept/example), or move any flags (at all) out of the global flagset, which can be done incrementally in follow-up PRs.
(if you think of a good place to house this, let me know!)
For each flag in the package you are tackling, you are going to want to determine if it truly should be global and available to every binary (probably flags that control logging and tracing behavior are good candidates), or if they only make sense for a particular binary or particular subset of binaries.
To see which `cmd` entrypoints actually …
=> [cmd/*] Switch to pflag for all CLI flag parsing

go/test/endtoend/vtorc/general/vtorc_test.go, go/vt/orchestrator/inst/analysis_dao.go
This PR fixes the issue described in https://github.com/vitessio/vitess/issues/10785. 
VTOrc should be repairing replication if either of the threads is stopped and not only when both the threads are stopped. 
In Vitess we only stop 1 thread in the following cases - 
1. `StopReplicationAndGetStatus` RPC of Tablet Manager Client. This RPC is called only from `EmergencyReparentShard` which is run after acquiring a shard lock. By the end, we fix replication on all the tablets, so VTOrc will not interfere in this case.
2. `catchupToGTID` function used in restore. This happens after we change the tablet type to the `RESTORE` type. VTOrc does not fix replication on tablets of this type, so we shouldn't conflict here either.
- Fixes #10785 
-   [x] "Backport me!" label has been added if this …
=> BugFix: VTOrc should repair replication if either replication thread is stopped

go/test/endtoend/vtgate/gen4/gen4_test.go, go/test/endtoend/vtgate/gen4/sharded_schema.sql, go/test/endtoend/vtgate/gen4/sharded_vschema.json, go/vt/vtgate/engine/filter_test.go, go/vt/vtgate/evalengine/comparisons.go, go/vt/vtgate/evalengine/evalengine.go, go/vt/vtgate/evalengine/translate.go
Backport of https://github.com/vitessio/vitess/pull/10793
This PR fails the numeric compare if the type are not same after the type conversion.
This is to prevent from accidentally returning wrong result.
The follow up PR should handle the type conversion for all the missing numeric types.
- Fixes https://github.com/vitessio/vitess/issues/10789
=> [14.0] fix: evalengine - check compare numeric of same type (#10793)

go/mysql/collations/integration/coercion_test.go
MySQL 8.0.30 was released today and it broke our CI. In MySQL 8.0.30, an incompatible change was introduced - 
```
Important Change: A previous change renamed character sets having deprecated names prefixed with utf8_ to use utf8mb3_ instead. In this release, we rename the utf8_ collations as well, using the utf8mb3_ prefix; this is to make the collation names consistent with those of the character sets, not to rely any longer on the deprecated collation names, and to clarify the distinction between utf8mb3 and utf8mb4. The names using the utf8mb3_ prefix are now used exclusively for these collations in the output of SHOW statements such as SHOW CREATE TABLE, as well as in the values displayed in the columns of Information Schema tables including the COLLATIONS and COLUMNS tables. (Bug …
```
=> CI Fix: Collation tests

go/test/endtoend/cluster/topo_process.go, go/test/endtoend/cluster/vtctld_process.go, go/test/endtoend/cluster/vtgate_process.go, go/test/endtoend/cluster/vttablet_process.go
Not closing the body leads to leaking goroutines for the reader / writer of the body.
Found when validating that tests don't leak goroutines (to ensure other things get closed properly, but these cases where also found).
See also https://github.com/vitessio/vitess/pull/10756 for another set of leak fixes.
=> Always close body for HTTP requests in tests

go/flags/endtoend/vttablet.txt, go/vt/mysqlctl/azblobbackupstorage/azblob.go, go/vt/mysqlctl/builtinbackupengine_test.go, go/vt/mysqlctl/cephbackupstorage/ceph.go, go/vt/mysqlctl/filebackupstorage/file.go, go/vt/mysqlctl/filebackupstorage/file_test.go, go/vt/mysqlctl/gcsbackupstorage/gcs.go, go/vt/mysqlctl/s3backupstorage/README.txt, go/vt/mysqlctl/s3backupstorage/s3.go, go/vt/mysqlctl/s3backupstorage/s3_test.go, go/vt/wrangler/testlib/backup_test.go
This scopes all the flags of our backupstorage _implementation_ packages to `pflag` and the associated binaries. Each of these is only used by `vtbackup`, `vtctl`, `vtctld`, and `vttablet`. I'm punting on the one flag in `go/vt/mysqlctl/backupstorage` (#10812) because it ends up being being imported by a lot more things, so I need to do more analysis first.
- Closes #10811 
- Closes #10813 
- Closes #10814 
- Closes #10815 
- Closes #10816 
-   [x] "Backport me!" label has been added if this change should be backported - n/a
=> [cli] [mysqlctl] Scope all backupstorage implementation flags to `pflag` and relevant binaries

go/flags/endtoend/vttablet.txt, go/vt/mysqlctl/backupstorage/interface.go, go/vt/mysqlctl/s3backupstorage/README.txt, go/vt/vtctl/grpcvtctldserver/server_test.go, go/vt/wrangler/testlib/backup_test.go
Builds on #10844 and will need a rebase after that merges.
This package is imported by the following commands, which I've annotated as follows (**reviewers please call out any analysis you disagree with**):
- `go/cmd/mysqlctl` => no need for this flag, imports `mysqlctl` for other functionality
- `go/cmd/mysqlctld` => doesn't need it, "only starts and stops mysql"
- `go/cmd/rulesctl` => imports `go/cmd/rulesctl/cmd`, see below
- `go/cmd/rulesctl/cmd` =>  doesn't need it; imports `go/cmd/rulesctl/common` (see next) and `go/vt/vttablet/tabletserver/rules`, which imports `../tabletserver/schema` which imports `mysqlctl` for `mysqlctl.GetColumns`
- `go/cmd/vtadmin` => doesn't need it, is importing `go/vt/vtexplain` (see below)
- `go/cmd/vtbackup` => **needs the flag**
- `go/cmd/vtcombo` => …
=> [cli] [mysqlctl] Scope `backup_storage_implementation` flag to `pflag`

go/mysql/client.go, go/mysql/conn.go, go/mysql/conn_flaky_test.go, go/mysql/query.go, go/mysql/streaming_query.go
The existing logic to track GTIDs doesn't really work when using it, because there's things lacking and it blows up as well.
First of all, only by manually setting up capability overrides can it be enabled during the handshake. I think we should always send the flag though based on whether the server supports the capability during the handshake.
This removes the need for custom startup flag configuration if anything wants to use GTID tracking.
Secondly, once session level tracking is enabled, things blow up quickly. Session tracking is not only about GTIDs, but it also tracks other session level changes.
Specifically the session tracking when the schema changes is something that affects things here.
https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_session_track_s …
=> Fix client session state tracking logic

go/vt/vtgate/executor_select_test.go, go/vt/vtgate/legacy_scatter_conn_test.go, go/vt/vtgate/scatter_conn_test.go, go/vt/vtgate/tx_conn_test.go, go/vt/vtgate/vstream_manager_test.go, go/vt/vtgate/vtgate_test.go
This ensures that the sandbox works always also if there's tests that depend on the underlying topo to exist and for it to not be a nil pointer.
=> Always setup an underlying topo for a sandbox

go/vt/vtgate/plugin_mysql_server.go
When a vtgate is started and very quickly terminated, it can panic. This is because the shutdown process tried to use parts of the system that have not yet been fully initialized. This change protects the `vtgateHandler` from accidental use before init has happened.
=> feat: don't use the vtgatehandler unless it is known to have been initialized

Makefile
The cross-build and cross-compile make targets are meant to let you
compile from host architecture (e.g. Mac M1) to target architectures
(e.g. Linux AMD64). They don't currently work for Mac M1 to other
targets.
There are a couple problems:
- Some syntactical errors in the Makefile targets.
- Golang doesn't like it when you use GOBIN in cross-architecture
installs.
This commit makes cross builds work on Mac, while preserving existing
usage (used in a build step of docker/lite/Docker.ubi8.arm64.mysql80):
- Fixes syntactical errors in conditional statement in make target.
- Replaces GOBIN usage with VTROOTBIN during build steps, preserving
GOBIN usage in install steps.
Fixes #10704 
-   [x] Tests were added or …
=> Tweak make targets MacOS M1 xc to Linux arches

go/vt/sqlparser/normalizer.go
This doesn't depend on state in the normalizer, so it can be an independent function.
Also makes it public since it can be useful for library style usage of Vitess for example.
=> Separate function for creating bind variables

go/vt/vtcombo/tablet_map.go
`git grep` doesn't turn up a definition for this flag anywhere. As I describe in the issue, this is almost certainly returning a non-nil error, which we also are ignoring. 
Fixes #10888.
=> [vtcombo] Delete `flag.Set` call on non-existent flag

go/vt/vtgate/plugin_mysql_server.go
Very small fix. We can check for nil even earlier
#10879
=> check for nil earlier

go/cmd/vtcombo/main.go, go/test/endtoend/reparent/newfeaturetest/reparent_test.go, go/test/endtoend/reparent/utils/utils.go, go/vt/vtctl/grpcvtctldserver/endtoend/init_shard_primary_test.go, go/vt/vttablet/tabletmanager/restore.go, go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_init_test.go, go/vt/wrangler/testlib/backup_test.go, go/vt/wrangler/testlib/copy_schema_shard_test.go, go/vt/wrangler/testlib/emergency_reparent_shard_test.go, go/vt/wrangler/testlib/external_reparent_test.go, go/vt/wrangler/testlib/fake_tablet.go, go/vt/wrangler/testlib/permissions_test.go, go/vt/wrangler/testlib/planned_reparent_shard_test.go, go/vt/wrangler/testlib/reparent_utils_test.go, go/vt/wrangler/testlib/version_test.go
This PR addresses the issue raised in https://github.com/vitessio/vitess/issues/10880. 
The proposed fix for the problem is to initialize the replication once on startup. Since we have moved to the architecture of storing the durability policy in the topo server instead of being passed in vtctld flags, even vttablets can access that information.
This allows the vttablets to find the current primary when they start and consult the durability policies to know whether they should be setting semi-sync or not.
A new method called `initializeReplication` has been added to the tablet manager which (as the name suggests) is responsible for initializing replication. This method is called in 3 places - 
1. In restoreDataLocked in the case where no backup exists.
2. In restoreDataLocked when a …
=> BugFix: Vttablet semi-sync settings on startup

.github/workflows/semgrep.yml
This adds CI integration with [Semgrep](https://semgrep.dev). This is a trial run of the integration — to back out we would revert this PR and remove the `SEMGREP_APP_TOKEN` GitHub secret that it uses. The hope is that this helps us find and fix more issues before merging, such as goroutine leaks. It will utilize a set of rules in the workflow run which are configured in the semgrep.dev dashboard (I will invite more people if/as needed on that side — log in using GitHub OAuth). 
=> Add semgrep CI workflow

Makefile, go.mod, go.sum
Newer versions don't have the compile issue anymore (see the upstream issue), so we can update and clean this up.
=> Cleanup the go-sqlite3 workaround

go/vt/vtgate/engine/filter_test.go, go/vt/vtgate/evalengine/arithmetic.go, go/vt/vtgate/evalengine/comparisons.go, go/vt/vtgate/evalengine/eval_result.go, go/vt/vtgate/evalengine/evalengine.go, go/vt/vtgate/evalengine/expressions.go, go/vt/vtgate/evalengine/translate.go
This PR includes a few small fixes to the `evalengine` and some new exports that will make working with the engine as a library less painful.
=> evalengine: expose Filter operations

.github/workflows/upgrade_downgrade_test_backups_manual.yml
This should not be merged until after the backport is merged: https://github.com/vitessio/vitess/pull/10895
Once that PR is merged then `release-14.0` will also have the backup fixes and the upgrade/downgrade backup tests will be working again with the latest MySQL releases (8.0.30+).
- Follow-up to: https://github.com/vitessio/vitess/pull/10847
- Dependent-on: https://github.com/vitessio/vitess/pull/10895
=> Revert temporary workflow changes made in #10847

go/test/endtoend/onlineddl/ghost/onlineddl_ghost_test.go, go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go, go/test/endtoend/onlineddl/singleton/onlineddl_singleton_test.go, go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go, go/test/endtoend/onlineddl/vrepl_suite/onlineddl_vrepl_suite_test.go, go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/onlineddl/schema.go
Up till now, when a user would run `ALTER VITESS_MIGRATION '...' CANCEL` or `ALTER VITESS_MIGRATION CANCEL ALL`, an affected pending migration (whether `queued`, `ready` or `running`) would transition into `failed` state.
This is largely because all `ALTER` tools: `pt-osc`, `gh-ost` and even VReplication are "3rd party" executors, and not under direct control of the Online DDL scheduler. The scheduler sends these tools the "abort" signal, and they follow up by failing with error -- which then gets recorded as `failed`.
However, this is not what the user expects. Now, in this PR, if the migration was terminated by a `CANCEL` command, then the migration status transitions to `cancelled` instead of `failed`.
we add a `cancelled_timestamp` in `_vt.schema_migrations` table, which indicates …
=> Online DDL: migration state transitions to 'cancelled' after CANCEL command

go/vt/schemadiff/table.go, go/vt/schemadiff/table_test.go
This PR fixes handling of a `RENAME COLUMN` clause:
1. By correctly ordering the `RenameColumn` statement among other table statements
2. By applying changes to known columns map
Unit test case added.
=> schemadiff: ordering and applying a RenameColumn

go/test/endtoend/topoconncache/topo_conn_cache_test.go, go/vt/proto/vtctlservice/vtctlservice_grpc.pb.go, go/vt/vtcombo/tablet_map.go, go/vt/vtctl/grpcvtctldserver/server.go, go/vt/vtctl/grpcvtctldserver/testutil/test_tmclient.go, go/vt/vttablet/faketmclient/fake_client.go, go/vt/vttablet/grpctmclient/client.go, go/vt/vttablet/grpctmserver/server.go, go/vt/vttablet/tabletmanager/rpc_agent.go, go/vt/vttablet/tabletmanager/rpc_backup.go, go/vt/vttablet/tmclient/rpc_client_api.go, go/vt/vttablet/tmrpctest/test_tm_rpc.go
Similarly to https://github.com/vitessio/vitess/pull/10578 and https://github.com/vitessio/vitess/pull/10671, this PR unexplodes `Backup()` functions to include a `BackupRequest` instead of specific request fields like `concurrency` and `allowPrimary`.
I have used both `vtctldatapb.BackupRequest` as well as `tabletmanagerdata.BackupRequest`. I hope I've used both in their appropriate context - kindly consider this while reviewing.
#10578 , #10671 
=> Refactor: Unexplode Backup() function, pass BackupRequest as argument

go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go, go/test/endtoend/onlineddl/vtgate_util.go
This PR is based on @mattlord 's #10874. Some flaky failures we only ever see on "weak" machines, such as in GitHub CI, and they do not reproduce in a strong test environment.
This PR is gonna be kept open for a while, with many re-runs of `onlineddl_vrepl` tests (mainly over `mysql80`). I'll be incrementally adding changes from over #10874 .
=> onlineddl_vrepl flakiness: further work

.github/workflows/upgrade_downgrade_test_backups_manual.yml, go/mysql/conn_flaky_test.go, go/mysql/flavor.go, go/mysql/flavor_mysql.go, go/mysql/flavor_mysqlgr.go, go/mysql/flavor_test.go, go/mysql/innodb_constants.go, go/vt/mysqlctl/backup_test.go, go/vt/mysqlctl/backupengine.go, go/vt/mysqlctl/builtinbackupengine_test.go, go/vt/mysqlctl/capabilityset.go, go/vt/wrangler/testlib/backup_test.go
This is a backport of https://github.com/vitessio/vitess/pull/10847.
- Backports: https://github.com/vitessio/vitess/pull/10847
- Fixes (in v14): https://github.com/vitessio/vitess/issues/10841
- Blocks: https://github.com/vitessio/vitess/pull/10896
=> Backport: Backups: Support InnoDB Redo Log Location With 8.0.30+

.github/workflows/upgrade_downgrade_test_backups_manual.yml
In https://github.com/vitessio/vitess/pull/10896 we reverted the temporary [upgrade/downgrade backup manual workflow](https://github.com/vitessio/vitess/blob/main/.github/workflows/upgrade_downgrade_test_backups_manual.yml) changes made in https://github.com/vitessio/vitess/pull/10847. 
This was done because the MySQL 8.0.30 backup fixes were merged into the `release-14.0` branch via https://github.com/vitessio/vitess/pull/10895 and given that "v14 had the fix" (though not in an official release) we should no longer need to pin the MySQL version.
Well... I was mistaken about what we downgraded *to* in [this workflow](https://github.com/vitessio/vitess/blob/main/.github/workflows/upgrade_downgrade_test_backups_manual.yml). I thought we built binaries on the previous release branch, in this …
=> Revert: Revert temporary workflow changes made in #10847

go/vt/vttablet/tabletmanager/rpc_replication.go
This PR fixes the upgrade part of the problem as described in https://github.com/vitessio/vitess/issues/10916.
After this change using backups created from v13 work fine with binaries of v14.
The proposed fix is to run the ALTER statement after taking the primary position. This allows for the statement to be replicated to the replicas if it succeeds.
- #10916 
=> BugFix: Using backups from v13 should work with v14

.github/workflows/upgrade_downgrade_test_backups_manual.yml
This backports the workflow changes from https://github.com/vitessio/vitess/pull/10847 so that [the workflow](https://github.com/vitessio/vitess/blob/release-13.0/.github/workflows/upgrade_downgrade_test_backups_manual.yml) passes. We do not currently plan to backport the backup fixes past 14.0 and will need to update the website docs that Vitess backups of 8.0.30 are not supported in 12.0 and 13.0.
- Follow-up to and partial cherry-pick of: https://github.com/vitessio/vitess/pull/10847
-   [x] Documentation: https://github.com/vitessio/website/pull/1129
=> Backport: Pin MySQL at 8.0.29 for upgrade/downgrade manual backup test

go/vt/topo/faketopo/faketopo.go
The refactor of the Watch implementation led me to accidentally adding this to the watcher, but we should keep the same implementation and not add those close here.
Accidentally added in https://github.com/vitessio/vitess/pull/10906
=> Remove potential double close of channel

go/test/endtoend/reparent/utils/utils.go
When IoState is `ReplicationStateConnecting`, then too we should be considering the IOThread to be running. The same goes for the SQL thread. This PR fixes the test expectations to reduce the flakiness.
=> Fix flakiness in TestReplicationStatus

go/flags/endtoend/flags_test.go, go/flags/endtoend/vtctld.txt, go/vt/discovery/healthcheck.go
This PR fixes the panic as described in https://github.com/vitessio/vitess/issues/10901.
The problem was traced back to https://github.com/vitessio/vitess/pull/10863. In this refactor of flags, we accidentally removed discovery flags for being registered for vtctld, which caused the default value of the flag not being used while starting the timer, causing it to panic.
Fixes #10901 
=> BugFix: vtctld panic with `enable_realtime_stats`

go/vt/vtgate/buffer/flags.go, go/vt/vtgate/buffer/flags_test.go, go/vt/vtgate/buffer/test_util.go, go/vt/vtgate/buffer/variables_test.go, go/vt/vtgate/grpcvtgateconn/conn_rpc_test.go
This migrates the flags in `go/vt/vtgate/buffer` to `pflag` and scopes them to just the `vtgate` binary.
**Note to reviewers**: the following binaries also import this package. I know `vtexplain` does not actually use them, but I need a consult on the others because I'm not sure:
- `vitess.io/vitess/go/cmd/vtcombo`
- `vitess.io/vitess/go/cmd/vtexplain`
- `vitess.io/vitess/go/cmd/vtgateclienttest`
Closes #10932 
=> [cli] [vtgate] Migrate `vtgate/buffer` flags to `pflag`

go/flags/endtoend/flags_test.go, go/flags/endtoend/vtexplain.txt, go/vt/vtexplain/vtexplain.go
What it says in the title :) 
```
➜  vitess git:(andrew/pflag-vtexplain) ✗ vtexplain --help 2>&1 | grep batch
--batch-interval duration                                          Interval between logical time slots. (default 10ms)
➜  vitess git:(andrew/pflag-vtexplain) ✗ 
```
Closes #10930
=> [vtexplain] Switch vtexplain flags to use pflag hooks

go/flags/endtoend/vttablet.txt, go/vt/vttablet/tabletserver/query_engine.go, go/vt/vttablet/tabletserver/tabletenv/config.go, go/vt/vttablet/tabletserver/tabletenv/config_test.go
When stream consolidation was added to VTTablet, fields were included in
the YAML configuration interface to set stream consolidator query/total
size. The fields are were set to non-zero by default.
However, equivalent flags were not added to the CLI configuration
interface, which resulted in the default values for stream consolidator
query/total size set to zero, effectively disabling the stream
consolidator, with no way for users to enable it via CLI flags.
This change adds `--consolidator-stream-query-size` and
`--consolidator-stream-query-total` flags to the VTTablet CLI
configuration interface. The default values for these flags are set to
the same values as the default values for the YAML configuration fields.
Addresses #10660
-   [ ] "Backport me!" label has been added if this …
=> add vttablet cli flags for stream consolidator

go/flags/endtoend/vtctld.txt, go/flags/endtoend/vtexplain.txt
Right now tests are broken because of the interaction of https://github.com/vitessio/vitess/pull/10938 and https://github.com/vitessio/vitess/pull/10907
=> Fix main in CI

go/vt/topo/memorytopo/memorytopo.go, go/vt/topo/memorytopo/watch.go
When we call close we want to lock around clearing out the factory object. In the watch goroutine shutdown we want to grab a reference to the factory to ensure that it can keep going with the shutdown procedure.
It's still possible to panic here on wrong usage but that's deliberate to avoid reuse of the memory topo.
Found with the race detector on a build:
```
Write at 0x00c00047c780 by goroutine 19:
vitess.io/vitess/go/vt/topo/memorytopo.(*Conn).Close()
/home/runner/work/vitess-private/vitess-private/go/vt/topo/memorytopo/memorytopo.go:145 +0x30
vitess.io/vitess/go/vt/topo.(*StatsConn).Close()
/home/runner/work/vitess-private/vitess-private/go/vt/topo/stats_conn.go:201 +0x17e
vitess.io/vitess/go/vt/topo.(*Server).Close() …
```
=> Avoid race condition in memory topo watch shutdown

go/vt/mysqlctl/fakemysqldaemon/fakemysqldaemon.go, go/vt/mysqlctl/replication.go, go/vt/vtctl/grpcvtctldserver/endtoend/init_shard_primary_test.go, go/vt/vttablet/tabletmanager/rpc_replication.go, go/vt/vttablet/tabletmanager/tm_init_test.go, go/vt/wrangler/testlib/backup_test.go, go/vt/wrangler/testlib/copy_schema_shard_test.go, go/vt/wrangler/testlib/emergency_reparent_shard_test.go, go/vt/wrangler/testlib/external_reparent_test.go, go/vt/wrangler/testlib/permissions_test.go, go/vt/wrangler/testlib/planned_reparent_shard_test.go, go/vt/wrangler/testlib/reparent_utils_test.go, go/vt/wrangler/testlib/version_test.go
This PR addresses the issue raised in https://github.com/vitessio/vitess/issues/10955. The way to repair replication once it is stuck as described in https://github.com/vitessio/vitess/issues/10955, is to call `RESET REPLICA` and then trying `START REPLICA` again.
The proposed solution is to always `RESET REPLICA` in `setReplicationSourceLocked` when we change the primary source/port or when `forceStartReplication` is specified. 
This allows both VTOrc and the replication manager to be able to address this issue since they both call `setReplicationSourceLocked` with forceStartReplication. 
- Fixes https://github.com/vitessio/vitess/issues/10955 …
=> Replicas should be able to heal if replication is not initialised properly

go/vt/servenv/servenv.go, go/vt/vterrors/errors_test.go, go/vt/vterrors/vterrors.go
Since every binary will involve errors in some way, shape, or form, I
decided to just register the vterrors flags to all binaries, rather than
naming each binary explicitly.
This notably does the _inverse_ of the code samples in the [Mover's Guide][1],
because `servenv` has `vterrors` in its dependency chain, so trying to
import `servenv` from `vterrors` would cause an import cycle.
This is the approach we should continue to use for any vitess package
imported by `servenv`.
[1]: see https://github.com/vitessio/vitess/issues/10697#user-content-movers-guide)
I also went ahead and made `logErrStacks` private; no one outside `vterrors` referenced it at all, so I didn't see a reason to keep it exported as a potential source of races.
Closes #10894.
-   [ ] "Backport me!" label has been added …
=> [cli] Migrate `vterrors` to `pflag`

go/test/endtoend/reparent/utils/utils.go, go/test/endtoend/vtgate/tablet_healthcheck_cache/correctness_test.go
This PR attempts to fix the flakiness observed in `TestCrossCellDurability` and `TestHealthCheckCacheWithTabletChurn`.
The flakiness was tracked to the part where we bring up a new vttablet. When this tablet comes up, a shard primary already exists and the tablet goes to serving status very quickly. 
However, the test code waits for the tablet to reach the non-serving status. This led to a race between the code that checks the non-serving status and the tablet process which goes to serving status eventually.
This has been resolved by waiting for the tablet to reach the Serving status since that is the end state instead of waiting for the non-serving status which is the default.
-   [x] Tests were added or are …
=> Fixing flakiness in TestCrossCellDurability and TestHealthCheckCacheWithTabletChurn

go/vt/vtctld/vtctld_test.go
Accidentally added in https://github.com/vitessio/vitess/pull/10956
Added because of debugging in https://github.com/vitessio/vitess/pull/10956
=> Remove accidentally added fmt.Printf from debugging
